### ISSUE TITLE
Dataset! body + hand

### ISSUE THREAD

**Issue by wangzhangup** [CMU-Perceptual-Computing-Lab/openpose#1]
COCO dataset only contain body-keypoints. What dataset has both body and hand keypoints?

**Comment by jhugestar** [comment]
We made our own dataset to train the hand key point detector. Please check our recent paper:
http://www.cs.cmu.edu/~tsimon/projects/mvbs.html

**Comment by wangzhangup** [comment]
@jhugestar very cool and great work！

**Comment by gineshidalgo99** [comment]
Hand dataset released a few months ago by @jhugestar  and @tsimk :
http://domedb.perception.cs.cmu.edu/handdb.html
