### ISSUE TITLE
can not open BOOST_SYSTEM_LIB_RELEASE.lib when installing Python API

### ISSUE THREAD

**Issue by wardenjohn** [CMU-Perceptual-Computing-Lab/openpose#1001]
System Config:
GPU : Nvidia GTX 1060 3GB
CPU : Intel i7
RAM: 8 GB

### Issue Summary
When I am trying to compile the python API , I met such problem:
I am trying to click the BUILD_PYTHON in CMake , but it raised some problem that "BOOST_SYSTEM_LIB_RELEASE NOFOUND",etc
so, I turn the they into "BOOST_SYSTEM_LIB_RELEASE","BOOST_FILESYSTEM_LIB_DEBUG","BOOST_FILESYSTEM_LIB_RELEASE",""BOOST_FSYSTEM_LIB_DEBUG"

And now ,I can config it can generate it .
Then , I open the project using VS2017 of openpose.sln , when I try to build it , it raised 
"Can not open 'BOOST_SYSTEM_LIB_RELEASE.lib' "

When I run the openpose.py , it raised the issues as follow:
"""
Traceback (most recent call last):
  File "E:/GitHub_Project/oldopen/openpose/buildpyt/python/openpose/openpose.py", line 27, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/Release/_openpose.dll')
  File "D:\Anaconda\envs\imgclassify\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/GitHub_Project/oldopen/openpose/buildpyt/python/openpose/openpose.py", line 17, in <module>
    class OpenPose(object):
  File "E:/GitHub_Project/oldopen/openpose/buildpyt/python/openpose/openpose.py", line 29, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/Debug/_openpose.dll')
  File "D:\Anaconda\envs\imgclassify\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
"""

Someone can tell me why when all the flag like "BOOST_SYSTEM_LIB_DEBUG" is all not found can let me run the openpose which can not allow CMake config with BUILD_PYTHON on???

### Errors (if any)
LNK118 unable open file "..\..\src\openpose\Release\openpose.lib"

### Type of Issue
- Compilation/installation error
-Execution error

### Your System Configuration
1. **Whole console output** 
https://pastebin.com/nGhEznM1

2. **OpenPose version**: 
Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake，compile with VS 2017
    - **Operating system**Windows
    - **Release or Debug mode**? Release
    - Compiler  : VS 2017

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):NO
    - Any other custom CMake configuration with respect to the default version? (by default: no):NO

5. **3rd-party software**:
    - **Caffe version**:?
    - **CMake version** :3.13.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

       !!!!!!!All the 3rdparty was downloaded from the .bat file in the Github project

6. If **GPU mode** issue:
    - **CUDA version** CUDA 9
    - **cuDNN version**:
    - **GPU model**  NVIDIA GTX 1060 3GB

**Comment by soulslicer** [comment]
There is a new API. This should no longer be an issue
