### ISSUE TITLE
Low Speed-the Speed is too slow, Is there anything wrong or do I need to make some additional settings?

### ISSUE THREAD

**Issue by TianhangTang** [CMU-Perceptual-Computing-Lab/openpose#1004]
System:Win10
GPU: GTX1080
CPU: I7-8750H
CUDA: 9.2
When I run the OpenPoseDemo.exe to test on the video, I fond the running speed is too slow, the FPS is about 8 to 10, and when I set --hand --face in the cmd line, the FPS became less than 1. So I wonder whether I set something wrong or else. Please help me, thank you.

**Comment by gineshidalgo99** [comment]
It makes sense if there is several people on the image. A face detector is run per each person.
