### ISSUE TITLE
[Feature Request] Quadruped

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [CMU-Perceptual-Computing-Lab/openpose#1005]
Include detection of four-legged animals.

**Comment by gineshidalgo99** [comment]
The main problem for this is the lack of a big annotated dataset for those.

**Comment by ErfolgreichCharismatisch** [comment]
Which kind of data do you need?

**Comment by gineshidalgo99** [comment]
It would require at least 15k images of each kind of 4-legged animal (e.g., 15k dogs, 15k cats, etc), with their respective annotations saying where each desired anatomical part is (where the dog wrist is, where the dog knee is, etc.).
