### ISSUE TITLE
Is there any documentation to explain the method used in matchLKAndOPGreedy?

### ISSUE THREAD

**Issue by imistyrain** [CMU-Perceptual-Computing-Lab/openpose#1009]
in [personIdExtractor.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/tracking/personIdExtractor.cpp), the core function is matchLKAndOPGreedy, but there's few commits.
Would you like to add some graphs to explain what has down in it?

**Comment by gineshidalgo99** [comment]
An improved multi-person tracking code will be available in 1-2 months, so we will not spend time on this code anymore. Check the readme to know when it's out. Thanks!

**Comment by lianuo** [comment]
@gineshidalgo99 you mean the STAF method? that's great.
