### ISSUE TITLE
Error while trying to collect keypoint data from other video than the example one

### ISSUE THREAD

**Issue by Neykah** [CMU-Perceptual-Computing-Lab/openpose#101]
### Issue summary
When running the write_keypoint option on other videos than the example one, the program crashes on the first frame where a human is detected.
On the same video, OpenPose succeeds in generating both the output video with Pose Estimation (write_video) and the output frames (write_images). On the other hand, the write_keypoint option is working correctly on the /build/example/media/video.avi example video.
Am I doing something wrong ?

### Executed command (if any)

./build/examples/openpose/openpose.bin --video ~/Documents/TUM_kitchen_dataset/0-0/cam1.avi --write_keypoint ~/Documents/TUM_kitchen_dataset/Test\ 0-0-camera0/test_keypoints --logging_level 0

### OpenPose output (if any)

> Starting pose estimation demo.
> examples/openpose/openpose.cpp:gflagsToOpParameters():211
> examples/openpose/openpose.cpp:gflagsToProducer():179
> examples/openpose/openpose.cpp:gflagsToProducerType():159
> examples/openpose/openpose.cpp:gflagToPoseModel():121
> examples/openpose/openpose.cpp:gflagToScaleMode():137
> Configuring OpenPose wrapper. In examples/openpose/openpose.cpp:opRealTimePoseDemo():262
> ./include/openpose/wrapper/wrapper.hpp:configure():423
> Auto-detecting GPUs... Detected 1 GPU(s), using them all.
> ./include/openpose/wrapper/wrapper.hpp:configure():581
> ./include/openpose/wrapper/wrapper.hpp:configure():757
> Starting thread(s)
> ./include/openpose/wrapper/wrapper.hpp:configureThreadManager():1065
> ./include/openpose/thread/threadManager.hpp:exec():166
> ./include/openpose/thread/queueBase.hpp:addPusher():364
> ./include/openpose/thread/queueBase.hpp:addPusher():364
> ./include/openpose/thread/queueBase.hpp:addPusher():364
> ./include/openpose/thread/threadManager.hpp:exec():171
> ./include/openpose/thread/thread.hpp:startInThread():141
> ./include/openpose/thread/thread.hpp:startInThread():141
> ./include/openpose/thread/thread.hpp:startInThread():141
> ./include/openpose/thread/thread.hpp:threadFunction():185
> ./include/openpose/thread/thread.hpp:threadFunction():188
> ./include/openpose/thread/thread.hpp:threadFunction():185
> ./include/openpose/thread/thread.hpp:threadFunction():185
> Starting initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():43
> ./include/openpose/thread/thread.hpp:threadFunction():185
> ./include/openpose/thread/thread.hpp:threadFunction():188
> ./include/openpose/thread/thread.hpp:threadFunction():188
> Finished initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():66
> Starting initialization on thread. In src/openpose/pose/poseRenderer.cpp:initializationOnThread():75
> Finished initialization on thread. In src/openpose/pose/poseRenderer.cpp:initializationOnThread():79
> ./include/openpose/thread/thread.hpp:threadFunction():188
> OpenCV Error: Bad argument (Unknown object) in cvWrite, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp, line 5015
> 
> Error:
> /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:5015: error: (-5) Unknown object in function cvWrite
> 
> 
> Coming from:
> - src/openpose/filestream/fileStream.cpp:saveData():87
> - src/openpose/filestream/keypointSaver.cpp:saveKeypoints():38
> - ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
> - ./include/openpose/thread/subThread.hpp:workTWorkers():138
> - ./include/openpose/thread/subThreadQueueInOut.hpp:work():87
> - ./include/openpose/thread/thread.hpp:threadFunction():206
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  
> Error:
> /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:5015: error: (-5) Unknown object in function cvWrite
> 
> 
> Coming from:
> - src/openpose/filestream/fileStream.cpp:saveData():87
> - src/openpose/filestream/keypointSaver.cpp:saveKeypoints():38
> - ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
> - ./include/openpose/thread/subThread.hpp:workTWorkers():138
> - ./include/openpose/thread/subThreadQueueInOut.hpp:work():87
> - ./include/openpose/thread/thread.hpp:threadFunction():206
> 
> Aborted (core dumped)
> 

### Type of issue
- Execution error
- Help wanted

### Your system configuration
**Operating system** : Ubuntu 16.04.2 LTS
**CUDA version** : 8.0.61
**cuDNN version**:
**GPU model** : GTX 1060
**Caffe version**: Default from OpenPose
**OpenCV version**: installed with `apt-get install libopencv-dev`
Compiler (`gcc --version` on Ubuntu): gcc 5.4.0

**Comment by gineshidalgo99** [comment]
It sounds like an OpenCV error. Could you try completely removing and re-installing OpenCV?

If that does not work, could you post or privately send me (gines[et]cmu.edu) the video where it is crashing? (e.g. Dropbox or Google drive link)

**Comment by Neykah** [comment]
Thank you for your help, I just figured out what the problem was.
Openpose was actually using my OpenCV 3.2 installation, even if I thought it would use the one I got with apt-get install libopencv-dev.
I therefore reinstalled Openpose with the manual installation as detailled in the doc, by changing the Makefile.conf so that it uses opencv 3 and everything works well now.
Sorry for the inconvenience.
