### ISSUE TITLE
How to make the skeleton to be solid lines but not dotted lines

### ISSUE THREAD

**Issue by Freedomxt** [CMU-Perceptual-Computing-Lab/openpose#1010]
When I use the demo to handle my images，the skeletons are dotted lines.
I want to know how to make them to be solid lines.
Thanks everyones!!

**Comment by visonpon** [comment]
I have the same question as above  , hope someone can help. thanks~ @gineshidalgo99

**Comment by Freedomxt** [comment]
@visonpon  I have found the problem !  The reason is that your image size is too small ,you can try to resize your images more bigger!

**Comment by gineshidalgo99** [comment]
Thanks for the feedback, ill add it to doc/faq.md. Complete answer:

You can either 1) manually rescale your images up or 2) use a bigger `--output_resolution` so OpenPose will resize them up.
