### ISSUE TITLE
Fixing Python API  "name 'OpenPose' is not defined" [Ubuntu]

### ISSUE THREAD

**Issue by YoongiKim** [CMU-Perceptual-Computing-Lab/openpose#1011]
### Issue Summary
Python API tutorial_api_python/1_extract_pose.py problem.
Python version 3.5 on ubuntu installation.

If I run openpose/build/examples/tutorial_api_python/1_extract_pose.py

![image](https://user-images.githubusercontent.com/38288705/50870391-2d586e80-13fb-11e9-87b4-d060bc7a9824.png)

Python couldn't find OpenPose class.

So I fixed like this.

![image](https://user-images.githubusercontent.com/38288705/50870423-5d077680-13fb-11e9-8a94-95e3e9ce941b.png)
![image](https://user-images.githubusercontent.com/38288705/50870514-af489780-13fb-11e9-9185-d59c3e36d12d.png)

I don't know this problem only shows to me. But I hope someone would be helped.

**Comment by gineshidalgo99** [comment]
Follow the doc, it specifies from where you must run the Python script. THanks!
