### ISSUE TITLE
Entry point to Caffe network

### ISSUE THREAD

**Issue by Charlesl0129** [CMU-Perceptual-Computing-Lab/openpose#1013]
Hi, could you please kindly tell me where exactly is the entry point to the caffe network? I'm asking this because I'm trying to use Movidius Neural Compute Stick for faster inference.

Now I've traced it to line 256 in poseExtractorCaffe.cpp (upImpl->spNets.at(i)->forwardPass(inputNetData[i]);), but I'm new to C++ and the code isn't making sense.

Thanks in advance!!

**Comment by imistyrain** [comment]
in examples.cpp (line 130:opWrapper.exec();) 
then wrapper.hpp (line 415: configureThreadManager)
wrapperAuxiliary.hpp(line 87:configureThreadManager->line 266:poseExtractorNets.emplace_back(std::make_shared<PoseExtractorCaffe>)
above is the construction of PoseExtractorCaffe.

**Comment by gineshidalgo99** [comment]
Answered then. Closed

**Comment by gaomomo** [comment]
@Charlesl0129 ,Did you finally run openpose successfully on Movidius Neural Compute Stick?
