### ISSUE TITLE
Visual studio build openpose in new project get errors

### ISSUE THREAD

**Issue by LeiTong02** [CMU-Perceptual-Computing-Lab/openpose#1018]
### Issue Summary
I create a new visual studio console project to call openpose. I follow the original openpose project to configure my project properties but when I build my project I get the following error (my laptop only have cpu). So can you give me any suggestions? 
Many thanks
### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
### OpenPose Output (if any)
Output:
![screenshot_20190113_233504](https://user-images.githubusercontent.com/26090828/51092220-c20cf480-178c-11e9-80c7-5778930db9e2.png)
Project Properties setting:
![screenshot_20190113_233931](https://user-images.githubusercontent.com/26090828/51092236-e799fe00-178c-11e9-804a-e95ebd759de9.png)
![screenshot_20190113_233945](https://user-images.githubusercontent.com/26090828/51092225-d05b1080-178c-11e9-9139-a104fa7a0c90.png)

### Errors (if any)
OpenPose must be compiled with the 'USE_CUDA' macro definitions in order to run this functionality. You can alternatively use CPU rendering(flag 'render_pose 1')
### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

System: Window 10
IDE: Visual Studio 2015
CPU: Intel core i5-8250U

**Comment by gineshidalgo99** [comment]
As the error says, add render_pose 1

**Comment by LeiTong02** [comment]
>           As the error says, add render_pose 1

Thanks for your answering. But where can I add the "render_pose 1" in visual studio? (I am new to use the visual studio)

**Comment by LeiTong02** [comment]
Thanks for your answering. But where can I add the "render_pose 1" in visual studio? (I am new to use the visual studio)

Sent from my iPhone

On Jan 13, 2019, at 23:52, Gines <notifications@github.com<mailto:notifications@github.com>> wrote:


As the error says, add render_pose 1
