### ISSUE TITLE
Accuracy dropped when using larger net size

### ISSUE THREAD

**Issue by gyc990326** [CMU-Perceptual-Computing-Lab/openpose#102]
It's said that the result will be more accurate when I increase the net size using "--net_resolution" option. But during my tests, the accuracy(scores of body parts) dropped drastically. Many noise appeared such as objects being mistaken for a person. And it seem that the larger the net is, the worse the result is.
Maybe there is a magic point that the accruacy is at its peak?

**Comment by gineshidalgo99** [comment]
Yeah, you are completely right. I should have said: `it might be potentially more accurate`.
The net was trained with certain resolution, which on average videos and images should be close to the default resolution. So using a much higher resolution will definitively make results worse after some point.
 
The highest accuracy we got was using **2x the current net resolution**, **4 scales** and **0.25 gap** between them.

It might definitively be some better configuration, this is so far the one giving our best results.

**Comment by gyc990326** [comment]
Thanks for your explaination. I'll have a try.
