### ISSUE TITLE
The maximum accuracy configuration for MPII model

### ISSUE THREAD

**Issue by Yuyangaichifan** [CMU-Perceptual-Computing-Lab/openpose#1022]
I am using the MPII pose model on Full HD image, and the performance is not good.

According to your notes in quick start " Note 2: Do not use this configuration for MPII model", there is no suggested configuration for the MPII pose model.

I will be appreciated if you can provide some suggestion of the configuration.

**Comment by soulslicer** [comment]
A new model will be released soon that merges both MPII and COCO together in one network
