### ISSUE TITLE
1_body_from_image.py stops at opWrapper.configure(params) on Windows

### ISSUE THREAD

**Issue by Po-Jen** [CMU-Perceptual-Computing-Lab/openpose#1026]
### Issue Summary

I am running python API, but 1_body_from_image.py stopped and did not show any detection result. 

After a little debugging, I found 1_body_from_image.py stops at `opWrapper.configure(params)`. I know this because I modified the starting openpose part in 1_body_from_image.py to 
```python
# Starting OpenPose
opWrapper = op.WrapperPython()
print('h')
print(params)
opWrapper.configure(params)
print('he')
opWrapper.start()
print('hello')
```

And the output is
![img](https://i.imgur.com/mWtYs2L.jpg)

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

`python 1_body_from_image.py --logging_level 0 --disable_multi_thread`

### OpenPose Output (if any)

```
C:\Users\rosindigo\Documents\GitHub\openpose-master\openpose\build\examples\tutorial_api_python>python 1_body_from_image.py --logging_level 0 --disable_multi_thread
Starting OpenPose Python Wrapper...
```

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: 

![img](https://i.imgur.com/OXREFwx.jpg)

2. **OpenPose version**:  [2fe8292](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/2fe8292c02d7070dede49316883c35ff67064483)

3. **General configuration**:
    - **Installation mode**: CMake Windows, VS2015 Enterprise for build compilation
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows 10
    - **Release or Debug mode**? (by default: release): Debug
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): VS2015 Enterprise Update 3

4. **Non-default settings**: None

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.13.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows)

6. If **Python** API:
    - **Python version**: 3.6
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 

7. If **Windows** system:
    - compiled library

**Comment by gineshidalgo99** [comment]
Could you try with the Release mode and report the results with that one? (that's the only test I can think of to know what it could be)

**Comment by Po-Jen** [comment]
Thanks!! After compiling in Release mode and change the path in 1_body_from_image.py. I can now see the detection result.

![img](https://i.imgur.com/Jas1B8z.jpg)
