### ISSUE TITLE
Python API error: Cannot import name pyopenpose

### ISSUE THREAD

**Issue by ccjack** [CMU-Perceptual-Computing-Lab/openpose#1027]
When I execute the python API sample code in build folder ( 1_body_from_image.py ), the terminal return back the following errors. I also noticed that the python API have been changed during the past month. I am using ubuntu 16.04. cuda 8.0 with cudnn 5.1. The openpose is current version. Any suggestions? 

Thanks!

from openpose import pyopenpose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/Documents/computervision/openpose/build/python/openpose/__init__.py", line 1, in <module>
    from . import pyopenpose as pyopenpose
ImportError: cannot import name pyopenpose

**Comment by StrongRay** [comment]
My environment - UBUNTU 18.04, CUDA 9.2, CUDNN 7.2.1 
Openpose current version 1.4 (Jan 2019)

I did the following to get it to work

a.  After a successful build,  go look for the file - **build/python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so** and copy to **/usr/local/lib/python3.6/dist-packages**

b.   in /usr/local/lib/python3.6/dist-packages I create a symbolic link - **sudo ln -s pyopenpose.cpython-36m-x86_64-linux-gnu.so pyopenpose**

c.  Verify that your LD_LIBRARY_PATH from **env** has the entry  **/usr/local/lib/python3.6/dist-packages**

d.  Now, go to build/examples/tutorial_api_python and do some modification to **1_body_from_image.py**

i)  look for the line **from openpose import pyopenpose as op** and change to **import pyopenpose as op**

ii) Under custom parameters, I modify the following to reduce net_resolution (otherwise I hit a CUDA out of memory error ) and modify the model_folder to where I store the models
```
params = dict()
params["model_folder"] = "/home/XXXXX/openpose/models/"
params["net_resolution"] = "160x80"
```
go to your examples/tutorial_api_python and execute **./1_body_from_image.py**

![h1](https://user-images.githubusercontent.com/42715739/51312801-14009380-1a87-11e9-84a6-20d2c32eb5bb.png)

This version of Python Wrapper is indeed faster !

**Comment by wardenjohn** [comment]
I met the same issuse as you in Windows10!!! After configure in CMake with PYTHON_BUILD flag , I found diffculty in Python . When try to run the demo , i got as follows:
ImportError: No module named 'pyopenpose'

**Comment by gnastacast** [comment]
Make sure you are building with the correct python version or using the python version you built for. For me the problem was that python %example_file.py% was calling python 2.7 when I had built for python 3.5 (Which is only executed if I run  python3 %example_file.py%)

**Comment by ccjack** [comment]
@StrongRay Could you tell me which openpose version you are using? I trace back and found out that the python API was ok before 01/10/2019( commit fc6d35998da5d2153fc0705f9ee74dd6fd4931cd). I can run  1_body_from_image.py. But for the current repository ( 01/16/2019 ), it seems that they changed several things. Not sure this is the reason to get broken. Could you check your tutorial_api_python folder under build foder and see whether you have the below two python code?  
(**2_whole_body_from_image, 3_heatmaps_from_image** ). If you only have 1_body_from_image.py, then this is older python API version which can run well. If not, let me know which commit you use and I am gonna try it.

**Comment by gineshidalgo99** [comment]
@ccjack Please, use the latest version as we have fixed several Python bugs in these last few commits.

**Comment by ccjack** [comment]
@gineshidalgo99 Thanks for prompt response!! I still met the issue regarding the import error ( raise e ImportError: cannot import name pyopenpose.) in the newest version ( commit ce6338f8a6694396990f77c19bbc3d003b12f9b9 ). Then, I will wait a month for v1.4 to be launched and use it for further python application purposes. Thanks!


-

**Comment by soulslicer** [comment]
Can you do a clean removal of openpose and clone again? This seems typical of that kind of error.

**Comment by StrongRay** [comment]
@ccjack I have cloned the latest version yesterday so it has the latest codes and so the tutorial_api_python directory has 2_ and 3_ python examples.

**Comment by ccjack** [comment]
@StrongRay Thanks for your info. I will try you approach later. Really appreciate your help!

**Comment by gineshidalgo99** [comment]
Please, follow the updated doc for the PyOpenPose wrapper (that has been updated today) and post a new GitHub with any new issue that could appear (but adding all the hardware configuration as the GitHub issue template states...).

**Comment by riba972** [comment]
System configuration: Windows 10, CPU only

I also have the error 'no module named 'pyopenpose'', when I attempt to run the file 1_body_from_image.py from the build/examples/tutorial_api_python/ folder. (I have upated to the latest version of the OpenPose library.)

I have enabled BUILD_PYTHON in CMake and compiled the library in Visual Studio. However, I do not have the the folder build/python/openpose/release nor the files pyopenpose.cp36-win_amd64.pyd or pyopenpose.pyd. Is there a specific project file/solution that I need to compile in release mode in Visual Studio that will build Python for Openpose? 

Additionally, does Windows require python-dev to be installed, to use the Python API? 

Thank you

**Comment by soulslicer** [comment]
Please follow all the steps under the Common Issues section for Windows:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md#exporting-python-openpose

**Comment by riba972** [comment]
Hi, thanks for the quick reply.

I have compiled the the Visual Studio solution file OpenPose.sln in release mode. But, this does not produce the file location build/python/openpose/release nor pyopenpose.cp36-win_amd64.pyd nor pyopenpose.pyd. 

The instructions say 'Python for Openpose needs to be compiled in Release mode'. What file do I need to open and compile in VS to follow this step?

**Comment by soulslicer** [comment]
Can you tell me the contents you have in

`build/python/openpose`

**Comment by riba972** [comment]
The contents of build\python\openpose is:

\build\python\openpose\CMakeFiles
\build\python\openpose\cmake_install.cmake
\build\python\openpose\pyopenpose.vcxproj
\build\python\openpose\pyopenpose.vcxproj.filters
\build\python\openpose\__init__.py
\build\python\openpose\CMakeFiles\generate.stamp
\build\python\openpose\CMakeFiles\generate.stamp.depend

**Comment by soulslicer** [comment]
it seems it was not compiled. you might have had compile errors, can you check that pyopenpose was actually compiled successfully?

**Comment by soulslicer** [comment]
These are only the Cmake logs, I need the build logs from within Visual studio as well

**Comment by riba972** [comment]
Thank you so much for the help, I really appreciate it!

I have now managed to successfully run the Python API tutorials. Even though I had built the solution, I also needed to separately build pyopenpose in Visual Studio. This option is located under the Build tab in the VS menu bar.

**Comment by wardenjohn** [comment]
can you tell me how you fix this problem?? I build in VS2017 and I can run when open OpenPose.sln which can let me see the result at first.Then, I open Pycharm and open file 1_body_from_image.py . When I want to run this file , it raise a error called "ImportError: No module named 'pyopenpose'"

**Comment by wardenjohn** [comment]
It is very strange that I can run the 1_body_from_image.py , but when I run 6_face_from_image.py or other python file , it raised such error:
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
import pyopenpose as op
ImportError: No module named 'pyopenpose'

But I do can run 1_body_from_image and got the output picture!

**Comment by Tame7790** [comment]
> It is very strange that I can run the 1_body_from_image.py , but when I run 6_face_from_image.py or other python file , it raised such error:
> Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
> import pyopenpose as op
> ImportError: No module named 'pyopenpose'
> 
> But I do can run 1_body_from_image and got the output picture!

I also have this question, and I can not solve it. Do you solve it now?

**Comment by philadias** [comment]
I was able to fix this problem by pointing in Ubuntu 16.04 by 

> My environment - UBUNTU 18.04, CUDA 9.2, CUDNN 7.2.1
> Openpose current version 1.4 (Jan 2019)
> 
> I did the following to get it to work
> 
> a. After a successful build, go look for the file - **build/python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so** and copy to **/usr/local/lib/python3.6/dist-packages**
> 
> b. in /usr/local/lib/python3.6/dist-packages I create a symbolic link - **sudo ln -s pyopenpose.cpython-36m-x86_64-linux-gnu.so pyopenpose**
> 
> c. Verify that your LD_LIBRARY_PATH from **env** has the entry **/usr/local/lib/python3.6/dist-packages**
> 
> d. Now, go to build/examples/tutorial_api_python and do some modification to **1_body_from_image.py**
> 
> i) look for the line **from openpose import pyopenpose as op** and change to **import pyopenpose as op**
> 
> ii) Under custom parameters, I modify the following to reduce net_resolution (otherwise I hit a CUDA out of memory error ) and modify the model_folder to where I store the models
> 
> ```
> params = dict()
> params["model_folder"] = "/home/XXXXX/openpose/models/"
> params["net_resolution"] = "160x80"
> ```
> go to your examples/tutorial_api_python and execute **./1_body_from_image.py**
> 
> ![h1](https://user-images.githubusercontent.com/42715739/51312801-14009380-1a87-11e9-84a6-20d2c32eb5bb.png)
> 
> This version of Python Wrapper is indeed faster !

In case someone else faces the same problem, I had to link to pyopenpose.so instead of just pyopenpose. Like this:

ln -s ./openpose/build/python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so ./openpose/build/python/openpose/pyopenpose.so

**Comment by soulslicer** [comment]
It seems everyone is having problems because Ubuntu by default uses Python 2, but Python 3 is what we recommend

**Comment by mehdydousty** [comment]
Hi all,
I am facing the same problem of cannot import name pyopenpose. I am using Ubuntu machine, and followed all the instruction, sudo make install without facing any error. Moreover,  I checked to use python3.6 in my cmake configuration and my openpose>build>python?openpose has pyopenpose.cpython-36m-x86_64-linux-gnu. However, when I try to run the py code in spyder environment, I am getting an error that cannot name pyopenpose.
I would be so happy if anyone can help me.
Thanks

**Comment by Redoblue** [comment]
JUST run `make install` in `/openpose/build/python/openpose`.

**Comment by reubencmoyo** [comment]
> JUST run `make install` in `/openpose/build/python/openpose`.

This worked for me. Thank you.

**Comment by tushancse04** [comment]
> > JUST run `make install` in `/openpose/build/python/openpose`.
> 
> I don't have /openpose/build/python/openpose directory. What does that mean? This was not build for python?

**Comment by tushancse04** [comment]
I built openpose successfully but the build folder doesn't contain python. I am not sure what should I do now.

**Comment by franklu323** [comment]
> Thank you so much for the help, I really appreciate it!
> 
> I have now managed to successfully run the Python API tutorials. Even though I had built the solution, I also needed to separately build pyopenpose in Visual Studio. This option is located under the Build tab in the VS menu bar.
Hi there,
I met the same problem, how did you fix the problem?? I also build it with release mode but I didn't get the pyopenpose.cp36-win_amd64.pyd nor pyopenpose.pyd. Could you please help me to sort it out? thank you so much

**Comment by TejasTidke** [comment]
> 
> 
> Thank you so much for the help, I really appreciate it!
> 
> I have now managed to successfully run the Python API tutorials. Even though I had built the solution, I also needed to separately build pyopenpose in Visual Studio. This option is located under the Build tab in the VS menu bar.

Thank You, this was helpful to me as well

**Comment by KimYonghyun94** [comment]
When I 'sudo make install'  I got this errors...

/usr/bin/ld: ../../src/openpose/libopenpose.a(cvMatToOpInput.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN2op14CvMatToOpInputE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
python/openpose/CMakeFiles/pyopenpose.dir/build.make:149: recipe for target 'python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so' failed
make[2]: *** [python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:1930: recipe for target 'python/openpose/CMakeFiles/pyopenpose.dir/all' failed
make[1]: *** [python/openpose/CMakeFiles/pyopenpose.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

how can I get a success??

**Comment by dh10050160** [comment]
我也是類似情況，也已經解決了
我得到的訊息是:
    OpenPose library could not be found. Did you enable BUILD_PYTHON in CMake and have this Python script in the right folder?
我的解決方法是:
        1.將 OpenPose.sln 用VS開啟
        2.點"建置(B) -> 重建pyopenpose(E)"
    就能在"build / python / openpose"產生出"release"資料夾及底下的文件 如:pyopenpose.cp36-win_amd64.pyd
    接著回到python的檔案並執行，即可成功

**Comment by Mr-Shen1994** [comment]
envs : win10 +annaconda + cuda 10.2
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
No module named 'pyopenpose'

The contents of build\python\openpose is:
2020/08/05  16:12    <DIR>          CMakeFiles
2020/08/05  16:12             2,273 cmake_install.cmake
2020/08/05  16:16    <DIR>          Debug
2020/08/05  17:19             7,425 INSTALL.vcxproj
2020/08/05  16:12               531 INSTALL.vcxproj.filters
2020/08/05  17:23    <DIR>          pyopenpose.dir
2020/08/06  08:33            14,927 pyopenpose.vcxproj
2020/08/05  16:12               496 pyopenpose.vcxproj.filters
2020/08/05  17:33               168 pyopenpose.vcxproj.user
2020/08/10  09:44    <DIR>          Release
2020/08/05  16:09                40 __init__.py
2020/08/07  09:56    <DIR>          __pycache__

and I'm sure  I have the following files in my directory:
\python\openpose\Release
2020/08/10  09:45           334,848 pyopenpose.cp37-win_amd64.pyd
2020/08/10  09:44            21,021 pyopenpose.exp
2020/08/10  09:44            27,520 pyopenpose.lib
how can I get a success??

**Comment by SaadAnees** [comment]
For people who are still looking for answer. Open OpenPose.sln which would be in your build folder and Build for pyopenpose. See the image below:

![vs pyopenpose](https://user-images.githubusercontent.com/5564617/103880126-2485fa80-50f2-11eb-8e6e-6c57f57f798b.png)

**Comment by gineshidalgo99** [comment]
Well, the installation instructions explicitly ask to click on "Build Solution", which would build all the projects, including pyopenpose, so that step should not be required if the "Build Solution" option is used.

**Comment by jasmineekka3010** [comment]
> > My environment - UBUNTU 18.04, CUDA 9.2, CUDNN 7.2.1
> > Openpose current version 1.4 (Jan 2019)
> > I did the following to get it to work
> > a. After a successful build, go look for the file - **build/python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so** and copy to **/usr/local/lib/python3.6/dist-packages**
> > b. in /usr/local/lib/python3.6/dist-packages I create a symbolic link - **sudo ln -s pyopenpose.cpython-36m-x86_64-linux-gnu.so pyopenpose**
> > c. Verify that your LD_LIBRARY_PATH from **env** has the entry **/usr/local/lib/python3.6/dist-packages**
> > d. Now, go to build/examples/tutorial_api_python and do some modification to **1_body_from_image.py**
> > i) look for the line **from openpose import pyopenpose as op** and change to **import pyopenpose as op**
> > ii) Under custom parameters, I modify the following to reduce net_resolution (otherwise I hit a CUDA out of memory error ) and modify the model_folder to where I store the models
> > ```
> > params = dict()
> > params["model_folder"] = "/home/XXXXX/openpose/models/"
> > params["net_resolution"] = "160x80"
> > ```
> > 
> > 
> > go to your examples/tutorial_api_python and execute **./1_body_from_image.py**
> > ![h1](https://user-images.githubusercontent.com/42715739/51312801-14009380-1a87-11e9-84a6-20d2c32eb5bb.png)
> > This version of Python Wrapper is indeed faster !
> 
> In case someone else faces the same problem, I had to link to pyopenpose.so instead of just pyopenpose. Like this:
> 
> ln -s ./openpose/build/python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so ./openpose/build/python/openpose/pyopenpose.so

Can this be run in google colaboratory

**Comment by StrongRay** [comment]
I have not tried with Google collab, but you have to know the subtle difference. Collab is hosted server while if you have a local server with GPU, you can show images without Jupyter. I prefer local machines as with collab, whatever you do in that session is gone the next time you login.

**Comment by jasmineekka3010** [comment]
> I have not tried with Google collab, but you have to know the subtle difference. Collab is hosted server while if you have a local server with GPU, you can show images without Jupyter. I prefer local machines as with collab, whatever you do in that session is gone the next time you login.

I have tried this on both local machine as well as colaboratory, but in both cases, there was an error of importing pyopenpose.
The Openpose is successfully installed and the demo video is also running. But I want to extract the body keypoints coordinates and for that I run the following code but an error occurred both in collab as well as local machine.

 "**ImportError: cannot import name 'pyopenpose' from 'openpose' (unknown location)**"

The corresponding code is:

import openpose
import logging
import sys
import time
import math
import cv2
import numpy as np
from openpose import pyopenpose as op

if __name__ == '__main__':
    fps_time = 0

    params = dict()
    params["model_folder"] = "/content/openpose/models"

    # Starting OpenPose
    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()


    print("OpenPose start")
    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

    ret_val, img = cap.read()
    fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
    out_video = cv2.VideoWriter('/tmp/output.mp4', fourcc, cap.get(cv2.CAP_PROP_FPS), (640, 480))

    count = 0

    if cap is None:
        print("Camera Open Error")
        sys.exit(0)
    while cap.isOpened() and count < 30:
        ret_val, dst = cap.read()
        if ret_val == False:
            print("Camera read Error")
            break
        #dst = cv2.resize(image, dsize=(320, 240), interpolation=cv2.INTER_AREA)
        #cv2.imshow("OpenPose 1.5.1 - Tutorial Python API", dst)
        #continue

        datum = op.Datum()
        datum.cvInputData = dst
        opWrapper.emplaceAndPop([datum])
        fps = 1.0 / (time.time() - fps_time)
        fps_time = time.time()
        newImage = datum.cvOutputData[:, :, :]
        cv2.putText(newImage , "FPS: %f" % (fps), (20, 40),  cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        out_video.write(newImage)

        print("captured fps %f"%(fps))
        cv2.imshow("OpenPose 1.5.1 - Tutorial Python API", newImage)
        count += 1


    cv2.destroyAllWindows()
    out_video.release()
    cap.release()




The error is on the line " **from openpose import pyopenpose as op**"

**Comment by StrongRay** [comment]
Execute **dir(openpose)** in the jupyter notebook. It should show pyopenpose as one of the function. 

On a local machine, u can try this in a python shell.

If dir(openpose) did not list pyopenpose, it means the openpose so file is not the right one. 😃

**Comment by senemaktas** [comment]
> My environment - UBUNTU 18.04, CUDA 9.2, CUDNN 7.2.1
> Openpose current version 1.4 (Jan 2019)
> 
> I did the following to get it to work
> 
> a. After a successful build, go look for the file - **build/python/openpose/pyopenpose.cpython-36m-x86_64-linux-gnu.so** and copy to **/usr/local/lib/python3.6/dist-packages**
> 
> b. in /usr/local/lib/python3.6/dist-packages I create a symbolic link - **sudo ln -s pyopenpose.cpython-36m-x86_64-linux-gnu.so pyopenpose**
> 
> c. Verify that your LD_LIBRARY_PATH from **env** has the entry **/usr/local/lib/python3.6/dist-packages**
> 
> d. Now, go to build/examples/tutorial_api_python and do some modification to **1_body_from_image.py**
> 
> i) look for the line **from openpose import pyopenpose as op** and change to **import pyopenpose as op**
> 
> ii) Under custom parameters, I modify the following to reduce net_resolution (otherwise I hit a CUDA out of memory error ) and modify the model_folder to where I store the models
> 
> ```
> params = dict()
> params["model_folder"] = "/home/XXXXX/openpose/models/"
> params["net_resolution"] = "160x80"
> ```
> 
> go to your examples/tutorial_api_python and execute **./1_body_from_image.py**
> 
> ![h1](https://user-images.githubusercontent.com/42715739/51312801-14009380-1a87-11e9-84a6-20d2c32eb5bb.png)
> 
> This version of Python Wrapper is indeed faster !

Hi , I have same issue. How did you build it? Here is my code:

```
# Define Openpose directory destination
OpenposeDir = '/content/openpose/'

# Import general libraries
import os 
import sys
import cv2
import warnings
from google.colab.patches import cv2_imshow
warnings.simplefilter(action='ignore', category=FutureWarning)

# Set Python Openpose Directory for python api (Important)
pyopenpose_dir= os.path.join('openpose/build/python') # ex: '/content/openpose/build/python'
if pyopenpose_dir not in sys.path:
  sys.path.append(pyopenpose_dir)
from openpose import python as op
```

**Comment by hansolo12334** [comment]
2025， found same problem in Windows11:
"ImportError: DLL load failed while importing pyopenpose: 找不到指定的模块。"
just import dlls like this:
`os.add_dll_directory("your_path\openpose\build\x64\Release")
os.add_dll_directory("your_path\openpose\build\bin")
`
the example " os.environ['PATH']  = os.environ['PATH']+';...." is out of date,

then success
