### ISSUE TITLE
Question: Pose estimation for top-view images

### ISSUE THREAD

**Issue by saileshprem** [CMU-Perceptual-Computing-Lab/openpose#1033]
### Issue Summary
I see that the model is trained for front/side-view human pose estimation. Are there plans for extending this to top-view human pose estimation or am I missing something where this is already implemented?

### Type of Issue
- Enhancement / offering possible extensions / pull request / etc

Thanks!

**Comment by gineshidalgo99** [comment]
So far there is no datasets for that kind of data, so I am afraid we cannot do much there until a big annotated dataset for that kind of data appears. Best
