### ISSUE TITLE
Jetsen TX2 Usage  command dir error

### ISSUE THREAD

**Issue by lovicwhite** [CMU-Perceptual-Computing-Lab/openpose#1034]
Jetsen TX2
### Issue Summary
<img width="942" alt="openpose_issue2" src="https://user-images.githubusercontent.com/33448800/51363914-1f020500-1b15-11e9-8693-f95825d697b7.png">

### Type of Issue

- Other 

A dir error, missed "examples"

Command should be:

./build/**examples**/openpose/openpose.bin -camera_resolution 640*480 ...

**Comment by gineshidalgo99** [comment]
Thanks! Fixed on my internal version, it will be pushed with the next commit.
