### ISSUE TITLE
Python standalone Only Hand detection 

### ISSUE THREAD

**Issue by Bhanudutta** [CMU-Perceptual-Computing-Lab/openpose#1035]
How to create a standalone python hand detector for gesture recognition program. Why is it not allowed to set body_disable=True

**Comment by gineshidalgo99** [comment]
Actually, I just introduced a new push that includes standalone hand and face for the C++ API (tutorial_api_cpp/10_hand_from_image.cpp). It will be incorporated into the Python examples eventually, but if you wanna use it right away, you can always take a look to the C++ code.

**Comment by StrongRay** [comment]
@gineshidalgo99 Confirmed the hands finally showing up on my laptop =) However, I had to pass in --model_folder="/home/xxx/openpose/models" and I twig the path to the image in the cpp code
DEFINE_string(image_path, "/home/xxxx/openpose/examples/media/COCO_val2014_000000000241.jpg"

I am running directly from  the build/examples/tutorial_api_cpp directory.  Alternatively, I think a relative path DEFINE_string(image_path, "../../../examples/media/COCO_val2014_000000000241.jpg"
will also refer to the right file

Looking forward to the Python version ! 

![g1](https://user-images.githubusercontent.com/42715739/51425092-7afe8380-1c12-11e9-9260-4d749b0e0ccd.png)
