### ISSUE TITLE
Make Error, fatal error: Python.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by seni04** [CMU-Perceptual-Computing-Lab/openpose#1038]
In file included from /home/sclab/Downloads/openpose/3rdparty/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/sclab/Downloads/openpose/3rdparty/pybind11/include/pybind11/cast.h:13,
                 from /home/sclab/Downloads/openpose/3rdparty/pybind11/include/pybind11/attr.h:13,
                 from /home/sclab/Downloads/openpose/3rdparty/pybind11/include/pybind11/pybind11.h:44,
                 from /home/sclab/Downloads/openpose/python/openpose/openpose_python.cpp:9:
/home/sclab/Downloads/openpose/3rdparty/pybind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
compilation terminated.
python/openpose/CMakeFiles/pyopenpose.dir/build.make:62: recipe for target 'python/openpose/CMakeFiles/pyopenpose.dir/openpose_python.cpp.o' failed
make[2]: *** [python/openpose/CMakeFiles/pyopenpose.dir/openpose_python.cpp.o] Error 1
CMakeFiles/Makefile2:2200: recipe for target 'python/openpose/CMakeFiles/pyopenpose.dir/all' failed
make[1]: *** [python/openpose/CMakeFiles/pyopenpose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

How to solve it, please i am new

**Comment by soulslicer** [comment]
Odd..i assumed Ubuntu as python-dev by default

Can you try these solutions:

https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by gineshidalgo99** [comment]
That actually happened to me because I was using the wrong Python version.

You need to install `sudo apt-get install python3.5-dev` for your Python version (this example is for 3.5, just check which version you are trying to build against).

Please, let me know if this works

**Comment by seni04** [comment]
> Odd..i assumed Ubuntu as python-dev by default
> 
> Can you try these solutions:
> 
> https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

i already try this
sudo apt-get install python-dev
sudo apt-get install python3-dev
sudo apt-get install python3.5-dev

all no update

and delete build folder and build new one, still same error

**Comment by seni04** [comment]
> That actually happened to me because I was using the wrong Python version (I had both 3.5 and 3.6).
> 
> You need to install `sudo apt-get install python3.5-dev` for your Python version (this example is for 3.5, just check which version you are trying to build against).
> 
> Please, let me know if this works

not working, still same error

**Comment by gineshidalgo99** [comment]
Then i can't answer unless you provide your whole config as the issue template indicated.

**Comment by seni04** [comment]
sorry, i give up debugging and try reinstall my ubuntu OS, then install all from beginning

**Comment by eroniki** [comment]
I can confirm the same problem with Ubuntu 16.04. When I locate the Python.h with:
`locate Python.h`

I receive: 
```
/usr/include/python2.7/Python.h
/usr/include/python3.5m/Python.h
```

So, the system contains the necessary header files. I am working on this. If I can figure out what the problem is, I will add it to this thread.

**Comment by bpangrati** [comment]
you can manually add python flags in cmake-gui, if you enable "Advance" mode:

search for CMAKE_CXX_FLAGS and add " -I/usr/include/python2.7 -lpython2.7 "

**Comment by eroniki** [comment]
> you can manually add python flags in cmake-gui, if you enable "Advance" mode:
> 
> search for CMAKE_CXX_FLAGS and add " -I/usr/include/python2.7 -lpython2.7 "

I can confirm this solution works.

**Comment by zxyscz** [comment]
> you can manually add python flags in cmake-gui, if you enable "Advance" mode:
> 
> search for CMAKE_CXX_FLAGS and add " -I/usr/include/python2.7 -lpython2.7 "
i am newer，i do not where CMAKE_CXX_FLAGS is，can you help me？

**Comment by xiang-zhe** [comment]
i got the same problem when using python3.6, it's not work with "sudo apt-get install python-dev python3-dev"; but it works after remove python3.6,

**Comment by JanisSharma** [comment]
On Ubuntu, I was running Python 3 and I had to install

sudo apt-get install python3-dev
If you want to use a version of Python that is not linked to python3, install the associated python3.x-dev package. For example:

sudo apt-get install python3.5-dev

Find All solutions [Here](https://icetutor.com/question/fatal-error-python-h-no-such-file-or-directory)

**Comment by Tanuj-hub** [comment]
> you can manually add python flags in cmake-gui, if you enable "Advance" mode:
> 
> search for CMAKE_CXX_FLAGS and add " -I/usr/include/python2.7 -lpython2.7 "

Can you please give an example what exactly to modify in the file and how?

**Comment by astanwar99** [comment]
None of the solutions worked for me except [this](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1038#issuecomment-477528117) one:

> you can manually add python flags in cmake-gui, if you enable "Advance" mode:
> 
> search for CMAKE_CXX_FLAGS and add " -I/usr/include/python2.7 -lpython2.7 "

I have worked with openpose previously on the same OS but his error popped up for the first time now. Not able to understand what changed.

**Comment by cute-walk** [comment]
By changing ”cmake“, I solved this problem。

`  cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX" \
  -DPYTHON_EXECUTABLE=/usr/bin/python3.6m \
  -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m/
`

**Comment by or-toledano** [comment]
> -I/usr/include/python2.7 -lpython2.7

Thanks. Just checking (because python 2.7 is deprecated) - is it used for internal code only? I.e. won't affect external API

**Comment by ilanasto** [comment]
> > you can manually add python flags in cmake-gui, if you enable "Advance" mode:
> > search for CMAKE_CXX_FLAGS and add " -I/usr/include/python2.7 -lpython2.7 "
> 
> I can confirm this solution works.

Hi could you tell me which file should i modify and how?
