### ISSUE TITLE
Question: does flip still work for video read-write?

### ISSUE THREAD

**Issue by zoombapup** [CMU-Perceptual-Computing-Lab/openpose#1040]
### Issue Summary
I'm trying to process a video file and maintain the orientation. For some reason by default openposedemo flips the video horizontally (so a person on the left now appears on the right etc).

I've tried the --frame_flip parameter with various combinations of 0,1,true,false,True,False just in case there was a parsing issue. But it definitely doesn't seem to correct the issue.

Before I go explore the code in VS, I wondered if this was normal behavior or if I'm being stupid with the command line flags. 

### Executed Command (if any)
OpenPoseDemo.exe --video 1.mp4 --write_video 2.mp4 --display 2 --frame_flip 0
OpenPoseDemo.exe --video 1.mp4 --write_video 2.mp4 --display 2 --frame_flip 1
etc.. for other attempts at trying to get flip to work.

### OpenPose Output (if any)
Flipped (mirrored) video

### Errors (if any)
Video is mirrored horizontally.

### Type of Issue
- Execution error
- Question

### Your System Configuration
Windows, compiled OpenPoseDemo.exe Visual Studio 2017. Not sure any of that matters.

**Comment by gineshidalgo99** [comment]
You are looking for
```
OpenPoseDemo.exe --video 1.mp4 --write_video 2.mp4 --display 2
```

For some reason in G Flags, `--frame_flip 0` actually behaves the same way than `--frame_flip 1` (it considers it as true). In order to make it false, you must not to write it down.

I think there was a way to actually do `--frame_flip false` or something like that, but I do not remember exactly which one (let me know if you figure it out). But easiest solution, do not type frame_flip.

**Comment by zoombapup** [comment]
Thanks, but I've tried OpenPoseDemo.exe --video 1.mp4 --write_video 2.mp4 --display 2 and it actually flips the video, I was trying the flip flags to unflip the video (if that makes sense). 

I can provide an example video if you're interested. I just started noticing that all my videos from openpose are flipped because I'm compositing them with other processed videos.

**Comment by zoombapup** [comment]
It looks like an issue with my compile of the OpenPoseDemo.exe file. I'd set the flags for flip to true by default, but for some reason gFlags doesn't allow me to explicitly set the value to false on the command line. So recompiling with that flag set to false in flags.hpp at least gave me the correct default behavior.
