### ISSUE TITLE
How to get KeyPoints image only? 

### ISSUE THREAD

**Issue by YongWookHa** [CMU-Perceptual-Computing-Lab/openpose#1041]
I'm trying to use `pyopenpose`.

I was able to build and extract keypoints with `WrapperPython` and `datum`.

To get the keypoints image, I subtracted `datum.cvInputData` from `datum.cvOutputData`. But I doubt that this is not the best way. I tried to find it in doc, but I couldn't. So I'm leaving this question here.

Is there a better way to get the image of keypoints?

**Comment by gineshidalgo99** [comment]
--disable_blending --> doc/demo_overview.md
