### ISSUE TITLE
openpose Build fail over RTX2080Ti Cuda 10

### ISSUE THREAD

**Issue by asri0012** [CMU-Perceptual-Computing-Lab/openpose#1042]
### Issue Summary

Having trouble configuring openpose over RTX2080Ti. Cuda 10. Using the caffe provided by Openpose. Would be great to have some advice on resolving this issue

Error facing:
 https://pastebin.com/PgyhpU1b

/3rdparty/caffe/distribute/lib/libcaffe.so: undefined reference to `__cudaPushCallConfiguration'
../../../3rdparty/caffe/distribute/lib/libcaffe.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/PgyhpU1b

/3rdparty/caffe/distribute/lib/libcaffe.so: undefined reference to `__cudaPushCallConfiguration'
../../../3rdparty/caffe/distribute/lib/libcaffe.so: undefined reference to `__cudaPopCallConfiguration'
collect2: error: ld returned 1 exit status

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 18.04

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.10.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` 

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10
    - **cuDNN version**: 7.4
    - **GPU model** (`nvidia-smi` in Ubuntu): RTX 2080Ti
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 18%   37C    P5    29W / 250W |    761MiB / 10987MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       941      G   /usr/lib/xorg/Xorg                           490MiB |
|    0      1477      G   /usr/bin/gnome-shell                         268MiB |
+-----------------------------------------------------------------------------+

8. If **Python** API:
    - **Python version**: 2.7
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.11.0

**Comment by ravijo** [comment]
@asri0012, it seems that the compilation is failing while linking OpenPose with Caffe. The problem could be with your Caffe installation. Why don't you install Caffe separately and link it later with OpenPose?

_PS: It is helpful to copy and paste the whole output reported at the console for better understanding the error. However, you have just shown us the linking error in your [PasteBin file](https://pastebin.com/PgyhpU1b)._

**Comment by gineshidalgo99** [comment]
I believe CUDA 10 requires Nvidia >= 418. That seems the issue. I must close it as it is unrelated to OpenPose .
