### ISSUE TITLE
Error when trying to load foot dataset using COCO API

### ISSUE THREAD

**Issue by soon-yau** [CMU-Perceptual-Computing-Lab/openpose#1044]
In Python3, do the following

> from pycocotools.coco import COCO
> coco = COCO('person_keypoints_val2017_foot_v1.json')

and it crashes

> loading annotations into memory...
> Done (t=0.03s)
> creating index...
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 88, in __init__
>     self.createIndex()
>   File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 106, in createIndex
>     cats[cat['id']] = cat
> TypeError: string indices must be integers
> 

I think the root cause is because in the foot dataset json, categories is a dictionary which should have been a list of dictionary. It would be nice to release a reformatted json to keep compatibility with COCO API.

**Comment by gineshidalgo99** [comment]
I can run it smoothly in the Matlab COCO API, not sure about the differences with respect to the Python COCO API.

**Comment by zzzhacker** [comment]
same issue @soon-yau with python API.
did you manage to solve this issues?

**Comment by gineshidalgo99** [comment]
Thanks for the fix! I will keep it in mind for the final version!

**Comment by cwlinghk** [comment]
additional bracket is needed for segments too

`annFile_foot = 'annotations/person_keypoints_train2017_foot_v1.json' 
annFile_foot_modified = 'annotations/person_keypoints_train2017_foot_v1_modified.json'

with open(annFile_foot) as f:
    data = json.loads(f.read())
    
    #add additional brackets to categories
    data['categories']=[data['categories']] 
    
    #add additional brakets to annotations
    for i in range(len(data['annotations'])):
        if type(data['annotations'][i]['segmentation'][0])!=list:
            data['annotations'][i]['segmentation'] = [data['annotations'][i]['segmentation']] #add additional brackets
    
    #export
    with open(annFile_foot_modified, 'w+') as ff:
        ff.write(json.dumps(data))`
