### ISSUE TITLE
Sudo make install encountered problems in the build folder in openpose

### ISSUE THREAD

**Issue by zhengyuezhi** [CMU-Perceptual-Computing-Lab/openpose#1046]
Hello, I ran sudo make install in the build folder of openpose and I get an error:

/usr/bin/ld: could not find -lcudart_static
Collect2: error: ld returned 1 exit status
Src/openpose/CMakeFiles/openpose.dir/build.make:6922: recipe for target 'src/openpose/libopenpose.so.1.4.0' failed
Make[2]: *** [src/openpose/libopenpose.so.1.4.0] Error 1
CMakeFiles/Makefile2:219: recipe for target 'src/openpose/CMakeFiles/openpose.dir/all' failed
Make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

But I have libcudart_static.a in /usr/local/cuda/lib64 or in /usr/local/cuda-8.0/lib64. What is the problem? Thank you

**Comment by gineshidalgo99** [comment]
This is a CUDA linking error, rather than an OpenPose issue. You should rather look for this kind of questions online.

**Comment by ambersun1234** [comment]
Did you fix it? I'm facing the same problem too.

@gineshidalgo99 
My openpose version is 99855c6a , and I'm pretty sure that my cuda works fine because i had successfully build openpose from source( 5c2714d ) , and run `sudo make install` on my local machine without failure.
