### ISSUE TITLE
openpose.bin --video problem

### ISSUE THREAD

**Issue by lianuo** [CMU-Perceptual-Computing-Lab/openpose#1048]
@gineshidalgo99 thank you for you support, I have a question about the result of video.
after I run the command as follow：
./build/examples/openpose/openpose.bin --video /video_camera_v01.avi --write_json /output/ --display 0 --render_pose 0 --face --hand

I got only one json file.with name video_camera_v01_000000000000_keypoints.json it seems it only run one frame of my video.

**Comment by lianuo** [comment]
The log infomation:

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 3.003374 seconds.

**Comment by eroniki** [comment]
Can it be a codec problem?

**Comment by gineshidalgo99** [comment]
doc/faq.md. If it works for webcam and/or images, then it's an OPenCV codec issue most probably.
