### ISSUE TITLE
Windows : Training an "MPI_4_layers" model.

### ISSUE THREAD

**Issue by AntonN11** [CMU-Perceptual-Computing-Lab/openpose#105]
### Issue summary

I really like the results I got so far with OpenPose. Thank you guys for developing this excellent tool.

I figured out that a gray scale camera gets faster results (higher FPS) than an identical color camera. But, OpenPose (with any trained model) will always give better poses using a color camera.
I guess this is simply due to the fact that the trained models included with OpenPose are trained using color images. For that reason, I'm currently reading and trying to train a new model using the coco images, but converted to gray scale. I'm following the steps explained here : https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation#training

### Type of issue
- Help wanted
- Question

My question is about the [quicker] MPI-4-layer trained model. The mentioned link before helps on how to train a coco model, but how do you train an MPI-4-Layer model?

Thank you for you help,

Anthony

### Your system configuration
**Operating system** : Windows 10 x64
**CUDA version** : 8.0
**cuDNN version**: 6.0
**GPU model** : GTX980
**Caffe version**: Default from OpenPose.
**OpenCV version**: 3.2.0

**Comment by gineshidalgo99** [comment]
Training questions should be referred so far to the https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation repo. OpenPose is only for testing for now (long to-do list for the testing before we incorporate and improve the testing too). I simply used the default models trained from the Realtime_Multi-Person_Pose_Estimation repo. Thanks!
