### ISSUE TITLE
(Ubuntu) Python wrapper datum.cvInputData bug when inputting cropped image

### ISSUE THREAD

**Issue by leon-nn** [CMU-Perceptual-Computing-Lab/openpose#1055]
### Issue Summary
After reading an image with `cv2.imread()`, when I crop an image through numpy indexing, e.g., getting the right half of the image via
```python
width = imageToProcess.shape[1]
imageToProcess = imageToProcess[:, width // 2:]
```
the input stored in `datum.cvInputData` is not stored correctly. See the output below.

### Executed Command (if any)
Consider the patch of `examples/tutorial_api_python/3_keypoints_from_images.py` below, which essentially implements the right-half cropping example above.
[](url)
```patch
diff --git a/examples/tutorial_api_python/3_keypoints_from_images.py b/examples/tutorial_api_python/3_keypoints_from_images.py
index b2c4573..c401afc 100644
--- a/examples/tutorial_api_python/3_keypoints_from_images.py
+++ b/examples/tutorial_api_python/3_keypoints_from_images.py
@@ -65,15 +65,21 @@ start = time.time()
 for imagePath in imagePaths:
     datum = op.Datum()
     imageToProcess = cv2.imread(imagePath)
-    datum.cvInputData = imageToProcess
+    width = imageToProcess.shape[1]
+    modifiedImage = imageToProcess[:, width // 2:]
+    cv2.imshow("Full image", imageToProcess)
+    cv2.imshow("Right half of image", modifiedImage)
+    datum.cvInputData = modifiedImage
+    cv2.imshow("cvInputData", datum.cvInputData)
     opWrapper.emplaceAndPop([datum])
 
     print("Body keypoints: \n" + str(datum.poseKeypoints))
 
     if not args[0].no_display:
         cv2.imshow("OpenPose 1.4.0 - Tutorial Python API", datum.cvOutputData)
-        key = cv2.waitKey(15)
+        key = cv2.waitKey(-1)
         if key == 27: break
+        elif key == 32: continue    # Spacebar to continue
 
 end = time.time()
 print("OpenPose demo successfully finished. Total time: " + str(end - start) + " seconds")
```

I run this modified version of the example in my build folder with the following.
`python 3_keypoints_from_images.py`

### OpenPose Output (if any)
Here are the outputs of the `cv2.imshow()` calls for the first image in the example.

**Original**
![original](https://user-images.githubusercontent.com/15018054/52004210-742a0900-247b-11e9-9941-f662c286ee80.png)

**Right half**
![righthalf](https://user-images.githubusercontent.com/15018054/52004221-78562680-247b-11e9-854f-7747e3d7ca55.png)

**cvInputData**
![cvinputdata](https://user-images.githubusercontent.com/15018054/52004224-7ab88080-247b-11e9-9deb-f0da235e17d3.png)

### Type of Issue
- Help wanted
- Bug

### Your System Configuration
2. **OpenPose version**: ee10cec

3. **General configuration**:
    - **Installation mode**: cmake
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04.5 LTS
    - **Release or Debug mode**?: Release
    - **Compiler**: `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609`

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): `cmake -DCaffe_INCLUDE_DIRS=/some_folder/caffe/include -DCaffe_LIBS=/some_folder/caffe/build/lib/libcaffe.so -DBUILD_CAFFE=OFF -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF -DBUILD_PYTHON=ON ..`

5. **3rd-party software**:
    - **Caffe version**: [https://github.com/BVLC/caffe/commit/3066720](url)
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: 3.4.3.18, via `pip install opencv-python`

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0.61
    - **cuDNN version**: 5.1
    - **GPU model** (`nvidia-smi` in Ubuntu): GeForce GTX 1080

8. If **Python** API:
    - **Python version**: 3.7
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.15.4

**Comment by soulslicer** [comment]
Okay, it seems the stride is being passed incorrectly to Pybind.

If I do a copy, it correctly says the stride is: 960 3 1

But, if I don't do a copy, it says incorrectly that it is: 1920 3 1

**Comment by leon-nn** [comment]
Thanks a lot @soulslicer -- this works for me, so I'll close this.
