### ISSUE TITLE
openpose+vs2017+cudn9.2，LINK : fatal error LNK1181: cannot open input file '....\src\openpose\Release\openpose.lib'

### ISSUE THREAD

**Issue by Tame7790** [CMU-Perceptual-Computing-Lab/openpose#1059]

**Comment by Tame7790** [comment]
When I use the openposedemo by vs2017，there are something wrong。
LINK : fatal error LNK1181: cannot open input file '....\src\openpose\Release\openpose.lib'
error：MSB6006“cmd.exe”已退出，代码为 1。
So what should I do to solve the problems?
![image](https://user-images.githubusercontent.com/43593936/52178275-5821c100-2807-11e9-90c0-1d53735c9fa7.png)

**Comment by gineshidalgo99** [comment]
There are many other similar issues. VS17 and CUDA > 8 requires extra configuration (in addition, Nvidia graphica cards > 2000 are not supported yet, Caffe requires to be compiled for that CUDA version).
