### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by A7ocin** [CMU-Perceptual-Computing-Lab/openpose#106]
Hello, I just wanted to suggest just a little fix for the documentation.
In the Windows installation section, point #2, it is said to execute:

`git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose/ && git checkout windows`

but before executing `git checkout windows` it is necessary to execute `cd openpose`.
Keep up the good work,
Nicola

**Comment by gineshidalgo99** [comment]
Thanks! Fixed.
