### ISSUE TITLE
Error during project building: 'cublas_v2.h' file not found

### ISSUE THREAD

**Issue by lizasaigina** [CMU-Perceptual-Computing-Lab/openpose#1061]
### Issue Summary
Couldn't build openpose for GPU_MODE=OPENCL as it can't find file 'cublas_v2.h'  in device_alternate.hpp (dir /usr/local/include/caffe/util/device_alternate.hpp). For CPU_ONLY everything works fine, however in this case I can't switch to inbuilt AMD graphics card and CPU gives extremely low fps. I have seen solutions for other OS (Windows, Ubuntu) which appeared with CPU_ONLY mode and opposite to mine. And there is no solution particularly for MacOS Mojave and AMD card. 

### Errors (if any)
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/net/bodyPartConnectorCaffe.cpp.o] Error 1
In file included from /Users/LS/openpose/src/openpose/gpu/opencl.cpp:7:
In file included from /usr/local/include/caffe/caffe.hpp:7:
In file included from /usr/local/include/caffe/blob.hpp:8:
In file included from /usr/local/include/caffe/common.hpp:19:
/usr/local/include/caffe/util/device_alternate.hpp:34:10: fatal error: 'cublas_v2.h' file not found
#include <cublas_v2.h>
         ^~~~~~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/net/netCaffe.cpp.o] Error 1
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/net/resizeAndMergeCaffe.cpp.o] Error 1
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/net/nmsCaffe.cpp.o] Error 1
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/pose/poseExtractorCaffe.cpp.o] Error 1
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/net/netOpenCv.cpp.o] Error 1
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/face/faceExtractorCaffe.cpp.o] Error 1
1 error generated.
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/hand/handExtractorCaffe.cpp.o] Error 1
<img width="1417" alt="2019-02-04 17 27 08" src="https://user-images.githubusercontent.com/14216573/52214211-2e69a800-28a2-11e9-9aad-d8d213ac4f1d.png">
<img width="976" alt="2019-02-04 17 26 35" src="https://user-images.githubusercontent.com/14216573/52214300-5c4eec80-28a2-11e9-9609-396f04553155.png">

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)? Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu): macOS Mojave
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...): OS X 10.14
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu): Intel Iris Pro / AMD Radeon R9 M370X

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by lizasaigina** [comment]
> It looks like you are linking to an external version of Caffe. You need to let Openpose build Caffe, which should be the default option. I would uninstall any caffe that has been installed in your mac first

I didn't upload caffe separately and built it with Openpose as it said in your manual.

**Comment by soulslicer** [comment]
Hi, I have made some fixes that eliminates the issues with OpenCL on the latest OSX. It should be merged by tonight

**Comment by lizasaigina** [comment]
> Hi, I have made some fixes that eliminates the issues with OpenCL on the latest OSX.

Thanks, everything works fine now.

**Comment by rajhlinux** [comment]
I'm getting the same issue on FreeBSD, I get GPU to Open_CL. I do not have a NVIDIA GPU.
