### ISSUE TITLE
Not able to build the OpenPose dll with "USE_UNITY_SUPPORT"

### ISSUE THREAD

**Issue by pavchavan** [CMU-Perceptual-Computing-Lab/openpose#1064]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'op::WrapperStructHand::WrapperStructHand(op::WrapperStructHand &&)': cannot convert argument 2 from 'op::Point<int>' to 'const op::Detector' (compiling source file D:\Work\VisualStudioMainWorks\OpenPose_Main_git\Builds\..\src\openpose\unity\unityBinding.cpp)	openpose	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory	901	

getting this error.

commit id : 2a80c660ec5002a3f0b7a6eaf96e308b761daf5d

**Comment by gineshidalgo99** [comment]
Fixed in the latest version. Best

**Comment by pavchavan** [comment]
In openpose unity plugin , the pose model body_25 is selected ?
and where is the "pose_deploy.prototxt" and "pose_iter_584000.caffemodel" files are present.

and from where OpenPose is accessing the files for the Body_25 ?

can you let me know how its running?
and how is the  flow?
