### ISSUE TITLE
[help] Processing frames from Kinect in real-time: slow performance, low accuracy

### ISSUE THREAD

**Issue by Xonxt** [CMU-Perceptual-Computing-Lab/openpose#1065]
### Issue Summary
I'm writing an application, that captures frames from Kinect v2 (RGB in 1080p), uses skeleton information to get hand-ROIs, get some other info, and **preferably**, also extract hand-skeletons using OpenPose.

For the implementation, I basically used the [07_hand_from_image.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/07_hand_from_image.cpp) and the [11_asynchronous_custom_input_output_and_datum.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/11_asynchronous_custom_input_output_and_datum.cpp). 

So the `configureWrapper()` is copied completely from the 07_hand example.

The gist of my code looks like this (sorry, don't want to copy all of it here):

[See code on my Gist](https://gist.github.com/Xonxt/e6ae8ffa9432ddcb9f7ccecf1d8e3ac9)

As you can see, it uses Qt and grabs frames from Kinect every 1ms.
You can also probably see on lines 59 and 70, that I'm trying different options for processing the frames (naturally, one of them is commented out in the real app).

I also for some reason have to clear the vector on line 79, otherwise the application crashes after processing the first frame and trying to "emplace" the second one.

I'm sure I'm doing something wrong, but the provided examples don't make it very obvious to me.

**It works** as it is, but I'm getting extremely low (around 2-4) FPS, and the accuracy of the hand-skeleton detection is very low (only half of the joints are detected at best, and many frames are skipped entirely). 

[See example image](https://dl.dropboxusercontent.com/s/rcngr42kspzop3e/op_hand.png)

The app itself, without using OpenPose, works very fast, and the hand segmentation is very accurate, the RoIs are always very good.

The provided `OpenPoseDemo.exe --hand` works fine, though the FPS is around 15.

### Type of Issue
- Help wanted
- Question

### Your System Configuration

2. **OpenPose version**: Latest GitHub code, 1.4.0

3. **General configuration**:
    - **Installation mode**: CMake, Windows
    - **Operating system**: Windows 10,
    - **Release or Debug mode**?: both
    - **Compiler**: VS2017 Pro

4. **Non-default settings**:
    `body_disable = true`,
    `hand = true`
    `hand_detector = 2`

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose,
    - **CMake version**: 3.12.0
    - **OpenCV version**: compiled from source, 3.4.1

6. If **GPU mode** issue:
    - **CUDA version**: 10.0
    - **cuDNN version**: 6
    - **GPU model**: Nvidia Titan X

9. If **Windows** system:
    - compiled library

**Comment by Xonxt** [comment]
ok, will answer it myself.

1. I need to switch the right and left hand in the `opHandRectangles`
2. `datumsPtr` needs to be a local variable, not a class member
3. The abysmal performance for some reason comes from the QTimer... if I just wrap it into a simple `std::thread` with an infinite loop, the performance is much better.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back!
