### ISSUE TITLE
 `make -j `nproc``  in the build folder gives : `make: *** No targets specified and no makefile found. Stop.`   in ubuntu18.04

### ISSUE THREAD

**Issue by vasanthhr** [CMU-Perceptual-Computing-Lab/openpose#1067]
Hello,

I followed the installation guide and got the result as "Configuring done" in cmake GUI.

when running    make -j `nproc`     inside the build folder, then getting below error:

`make: *** No targets specified and no makefile found. Stop.`

Please let me know how to solve this issue.

**Comment by eroniki** [comment]
I think you are skipping the step 4 in the [installation guide](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-configuration). 

After configuring, you should generate the makefiles.

**Comment by gabriead** [comment]
Hi @eroniki , unfortunately the link you are referring to is broken. Could you state what has to be done in order to configure it?

**Comment by gabriead** [comment]
Hi @eroniki, I assume you mean this command: `git submodule update --init --recursive --remote`. Is that correct?

**Comment by eroniki** [comment]
@gabriead correct!
