### ISSUE TITLE
CMake Error at CMakeLists.txt:929 (add_subdirectory):

### ISSUE THREAD

**Issue by vasanthhr** [CMU-Perceptual-Computing-Lab/openpose#1068]
When I ran make -j `nproc`  in build folder. Getting the below error.
I did this setup in my Ubuntu 18.04  local machine/laptop(Installed with CUDA and CUDNN).

Please help me to resolve this issue.

```

[ 98%] Built target upgrade_net_proto_text
[100%] Built target convert_mnist_siamese_data
[100%] Built target convert_cifar_data
Install the project...
-- Install configuration: "Release"
.
.
.
.

-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:929 (add_subdirectory):
  The source directory

    /home/vasanthahr/code/python/modaka/handLandMark_openPose/handML_openpose/openpose-master/3rdparty/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at python/openpose/CMakeLists.txt:6 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/vasanthahr/code/python/modaka/handLandMark_openPose/handML_openpose/openpose-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/vasanthahr/code/python/modaka/handLandMark_openPose/handML_openpose/openpose-master/build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:124: recipe for target 'openpose_lib' failed
make[2]: *** [openpose_lib] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by soulslicer** [comment]
Openpose is suppose to automatically pull the pybind submodule. Can you check the 3rdparty/pybind11 folder and see if there is anything there? If it's empty just do 

`git submodule update --recursive --remote`

But ideally Openpose should already call this

**Comment by vpview** [comment]
I am getting a similar error.

When I cd into `3rdparty/pybind11` and then run `git submodule update --recursive --remote`, I get that I am not in a git repository:
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by jungdaan** [comment]
I am having the same problem.

`CMake Error at CMakeLists.txt:1000 (add_subdirectory):
  The source directory

    /Users/dani/projectsw/openpose/3rdparty/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at python/openpose/CMakeLists.txt:6 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
`

**Comment by sigma--** [comment]
Temporary workaround. Clone pybind11 separately into the folder. The configure, generate and build all go through with the referenced checkout branch of pybind11.

1. While in folder 3rdparty, run `git clone https://github.com/pybind/pybind11.git`
2. checkout branch 085a29436a8c472caaaf7157aa644b571079bcaa
(I cloned the latest pybind11 and it still works fine. Latest as of 7th august 2019)

3. Click configure again in cmake-gui

**Comment by chethansai** [comment]
Run this in -> `git submodule init && git submodule update`  in openpose/3rdparty/pybind11

**Comment by Zydiii** [comment]
Thanks @chethansai , it works~

**Comment by dh10050160** [comment]
當遇到
CMake Error at python/openpose/CMakeLists.txt:6 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

1. 將 https://github.com/pybind/pybind11.git 下載並解壓縮
2. 將其放到 3rdparty/pybind11 (不是放到build裡面的 "3rdparty" 資料夾喔!!)
3. 重新進入 cmake-gui 按下configure
4. 成功後按下 generate
5. 最後按下 open project
6. 切換到 release 執行

**Comment by d3-worgan** [comment]
Just for reference this is still happening although the above fix works
