### ISSUE TITLE
File not found: models/pose/coco/pose_deploy_linevec.prototxt - Windows

### ISSUE THREAD

**Issue by phongtq2305** [CMU-Perceptual-Computing-Lab/openpose#107]
After build , I run project with video : 

OpenPoseDemo.exe --video video.avi   examples/media/video.avi , program crash and has message erro :

F0628 13:38:02.780624  4956 io.cpp:41] Check failed: fd != -1 (-1 vs. -1) File not found: models/pose/coco/pose_deploy_linevec.prototxt
*** Check failure stack trace: ***

Please help me !!!!

**Comment by gineshidalgo99** [comment]
How did you build it? It looks that you did not use the models/getModels.sh (or something like that) as the installation steps specify.

**Comment by gineshidalgo99** [comment]
@phongtq2305  we released a new simplified Windows version in which Caffe is already installed by default, no need for you to install it. Please, try this new version and let me know the results. Thanks!
(and feel free to open a new issue threads if you find any further problem there)

**Comment by nanthakumar94** [comment]
i have same issue sir please clear me the issue 
Error:
Prototxt file not found: models\face/pose_deploy.prototxt.

**Comment by zky001** [comment]
> 
> 
> i have same issue sir please clear me the issue
> Error:
> Prototxt file not found: models\face/pose_deploy.prototxt.

me too

**Comment by gineshidalgo99** [comment]
Please see https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
