### ISSUE TITLE
OpenPose Unity

### ISSUE THREAD

**Issue by pavchavan** [CMU-Perceptual-Computing-Lab/openpose#1070]
In openpose unity plugin , the pose model body_25 is selected ?
and where is the "pose_deploy.prototxt" and "pose_iter_584000.caffemodel" files are present.

and from where OpenPose is accessing the files for the Body_25 in unity project ?

can you let me know how its running?
and how is the flow?

**Comment by pavchavan** [comment]
(*mThreads.rbegin())->exec(spIsRunning);

runtime error at memory location in openpose when i use the new built dll in unity.
please help..

**Comment by gineshidalgo99** [comment]
This question is not for this GitHub repo.
