### ISSUE TITLE
[Mac OSX] Target DependInfo.cmake file & Directory Information file not found 

### ISSUE THREAD

**Issue by azuic** [CMU-Perceptual-Computing-Lab/openpose#1074]
### Issue Summary
When trying to build with OpenCL on Mac Pro, I got the following CMake errors: 
`Target DependInfo.cmake file not found` and ` Directory Information file not found` for target `openpose_lib`, `openpose_unity` and `openpose`. It looks like it is trying to find the makefile or dir info for the unity and 3D camera flags which I didn't turn on at all.

### Errors (if any)
`-bash: nproc: command not found
-- Building with OpenCL.
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'opencl'
Your branch is up to date with 'origin/opencl'.
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- Model already exists.
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/zuic/GIT/openpose/build
Scanning dependencies of target openpose_lib
CMake Error: Target DependInfo.cmake file not found
Scanning dependencies of target openpose_unity
CMake Error: Directory Information file not found
make[2]: *** No rule to make target `../src/openpose/unity/unityBinding.cpp', needed by `src/openpose/unity/CMakeFiles/openpose_unity.dir/unityBinding.cpp.o'.  Stop.
make[1]: *** [src/openpose/unity/CMakeFiles/openpose_unity.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Performing build step for 'openpose_lib'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
CMake Error: Target DependInfo.cmake file not found
Scanning dependencies of target openpose
CMake Error: Directory Information file not found
make[2]: *** No rule to make target `../src/openpose/3d/cameraParameterReader.cpp', needed by `src/openpose/CMakeFiles/openpose.dir/3d/cameraParameterReader.cpp.o'.  Stop.
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [all] Error 2`

### Type of Issue
- Compilation/installation error
- Execution error

### Your System Configuration
1. **Whole console output** : https://pastebin.com/im9V6qLE

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Mac OSX 10.14.2
    - **Release or Debug mode**: release
    - Compiler:
       `Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

4. **Non-default settings**: No

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : 3.13.4
    - **OpenCV version**: 4.0.1 (installed with openpose setup)

6. If **GPU mode** issue:
    - **GPU model** : AMD FirePro D700 6144 MB

**Comment by soulslicer** [comment]
Yes Unity has broken Openpose. I will need some time to fix this

**Comment by gineshidalgo99** [comment]
In theory this was solved a few weeks back. Let us know otherwise. Thanks
