### ISSUE TITLE
[Mac OSX]  'cublas_v2.h' file not found when building with OpenCL 

### ISSUE THREAD

**Issue by azuic** [CMU-Perceptual-Computing-Lab/openpose#1076]
### Issue Summary
When trying to build with OpenCL on Mac Pro, I got the ` 'cublas_v2.h' file not found` error. It looks like it is trying to looking for the CUDA modules which I did not use because my GPU is an AMD FirePro D700, not a Nvidia device. I had to use `brew` to install caffe. However, when I tried the solution of @soulslicer suggested for [issue #1061 ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1061#issuecomment-460783442), I got this issue [issue#1074](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1074#issue-408291999).

### Errors (if any)
`/usr/local/include/caffe/util/device_alternate.hpp:34:10: fatal error: 
      'cublas_v2.h' file not found
#include <cublas_v2.h>`

### Type of Issue
- Compilation/installation error
- Execution error

### Your System Configuration
1. **Whole console output** : https://pastebin.com/baNWdnhu

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Mac OSX 10.14.2
    - **Release or Debug mode**: release
    - Compiler:
       `Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

4. **Non-default settings**: set `BUILD_CAFFE` to be false

5. **3rd-party software**:
    - **Caffe version**: from `brew` 1.0.0
    - **CMake version** : 3.13.4
    - **OpenCV version**: 4.0.1 (installed with openpose setup)

6. If **GPU mode** issue:
    - **GPU model** : AMD FirePro D700 6144 MB

### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by soulslicer** [comment]
Did you let Openpose build Caffe? Which version of Caffe are you using

**Comment by azuic** [comment]
@soulslicer I had to not turn off the `BUILD_CAFFE` flag first in CMake GUI and use `brew` to install it, otherwise it won't configure successfully. And then I reconfigured it again with the flag on

**Comment by soulslicer** [comment]
You can't do that. This is because you need the OpenCL version of Caffe.

**Comment by azuic** [comment]
I uninstalled caffe and configured with the flag on, which gives me this error:
`-bash: nproc: command not found
Scanning dependencies of target openpose_lib
[ 12%] Creating directories for 'openpose_lib'
[ 25%] No download step for 'openpose_lib'
[ 50%] No patch step for 'openpose_lib'
[ 50%] No update step for 'openpose_lib'
[ 62%] Performing configure step for 'openpose_lib'
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/local/include  
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found Glog: /usr/local/include  
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
-- Found PROTOBUF: /usr/local/lib/libprotobuf.dylib  
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_cpp.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib (found version "1.10.4") found components:  HL 
-- Found SQLITE3: /usr/lib/libsqlite3.dylib  
-- Found ViennaCL include: /usr/local/include
-- Found OpenCL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework  
-- Found OpenCL include: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework
-- -- CUDA is disabled. Building without it...
-- Found vecLib: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers  
-- Found vecLib as part of Accelerate.framework
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
Using native target
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Found Git: /usr/bin/git (found version "2.17.2 (Apple Git-113)") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   1.0-6267-g3f2b97e9
--   System            :   Darwin
--   C++ compiler      :   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -std=c++11 -DCMAKE_BUILD -march=native -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -std=c++11 -DCMAKE_BUILD -march=native -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   OFF
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   OFF
--   USE_FFT           :   OFF
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   OFF
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--   USE_HDF5          :   ON
-- 
-- Dependencies:
--   BLAS              :   Yes (vecLib)
--   Boost             :   Yes (ver. 1.68)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.6.1)
--   CUDA              :   No
-- 
-- Install:
--   Install path      :   /Users/zuic/GIT/openpose/build/caffe
-- 
-- Configuring done
CMake Warning (dev) in src/caffe/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "caffe" has an INTERFACE_LINK_LIBRARIES property which differs from
  its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

    caffeproto;/usr/local/lib/libboost_system-mt.dylib;/usr/local/lib/libboost_thread-mt.dylib;/usr/local/lib/libboost_filesystem-mt.dylib;/usr/local/lib/libboost_chrono-mt.dylib;/usr/local/lib/libboost_date_time-mt.dylib;/usr/local/lib/libboost_atomic-mt.dylib;/usr/local/lib/libglog.dylib;/usr/local/lib/libgflags.dylib;$<$<NOT:$<CONFIG:DEBUG>>:/usr/local/lib/libprotobuf.dylib>;$<$<CONFIG:DEBUG>:/usr/local/lib/libprotobuf.dylib>;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_cpp.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_hl_cpp.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_hl.dylib;/usr/lib/libsqlite3.dylib;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework;-lcblas;-framework Accelerate

  LINK_INTERFACE_LIBRARIES:

    caffeproto;/usr/local/lib/libboost_system-mt.dylib;/usr/local/lib/libboost_thread-mt.dylib;/usr/local/lib/libboost_filesystem-mt.dylib;/usr/local/lib/libboost_chrono-mt.dylib;/usr/local/lib/libboost_date_time-mt.dylib;/usr/local/lib/libboost_atomic-mt.dylib;/usr/local/lib/libglog.dylib;/usr/local/lib/libgflags.dylib;/usr/local/lib/libprotobuf.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_cpp.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_hl_cpp.dylib;/usr/local/Cellar/hdf5/1.10.4/lib/libhdf5_hl.dylib;/usr/lib/libsqlite3.dylib;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework;-lcblas;-framework Accelerate

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CUDA_ARCH_BIN
    CUDA_ARCH_NAME
    CUDA_ARCH_PTX


-- Build files have been written to: /Users/zuic/GIT/openpose/build/caffe/src/openpose_lib-build
[ 75%] Performing build step for 'openpose_lib'
[  1%] Generating layer creator source (python -> C++).
[  1%] Generating blob creator source (python -> C++).
[  1%] Generating quantizer creator source (python -> C++).
[  1%] Generating macros source (python -> C++).
[  1%] Running C++/Python protocol buffer compiler on /Users/zuic/GIT/openpose/3rdparty/caffe/src/caffe/proto/caffe.proto
[  2%] Generating test macros source (python -> C++).
/bin/sh: /Users/zuic/GIT/openpose/3rdparty/caffe/scripts/prebuild/macros.py: Permission denied
/bin/sh: /Users/zuic/GIT/openpose/3rdparty/caffe/scripts/prebuild/test_macros.py: Permission denied
/bin/sh: /Users/zuic/GIT/openpose/3rdparty/caffe/scripts/prebuild/blob_creator.py: Permission denied
/bin/sh: /Users/zuic/GIT/openpose/3rdparty/caffe/scripts/prebuild/quantizer_creator.py: Permission denied
make[5]: *** [include/caffe/macros.hpp] Error 126
make[5]: *** Waiting for unfinished jobs....
/bin/sh: /Users/zuic/GIT/openpose/3rdparty/caffe/scripts/prebuild/layer_creator.py: Permission denied
make[5]: *** [include/caffe/test_macros.hpp] Error 126
make[5]: *** [include/caffe/blob_creator.hpp] Error 126
make[5]: *** [include/caffe/quantizer_creator.hpp] Error 126
make[5]: *** [include/caffe/layer_creator.hpp] Error 126
make[4]: *** [src/caffe/CMakeFiles/pre_build.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
Scanning dependencies of target caffeproto
[  2%] Building CXX object src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  3%] Linking CXX static library ../../lib/libcaffeproto.a
[  3%] Built target caffeproto
make[3]: *** [all] Error 2
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2`

**Comment by soulslicer** [comment]
Very odd..it's suppose to have built it. Can you check if you can build the OpenCL branch of Caffe:

https://github.com/BVLC/caffe/tree/opencl

**Comment by azuic** [comment]
![screen shot 2019-02-08 at 4 13 25 pm](https://user-images.githubusercontent.com/13326060/52506401-7b0ff480-2bbc-11e9-8d92-11ebbdfb3fc2.png)

**Comment by soulslicer** [comment]
Can you try to build the opencl branch of caffe?

**Comment by azuic** [comment]
Trying to build it now. I had problems build it with CMake but it returned me `The dependency target "pycaffe" of target "pytest" does not exist.` I am trying if it works with Make.

**Comment by soulslicer** [comment]
Hi, I have made some fixes that eliminates the issues with OpenCL on the latest OSX. It should be merged by tonight

**Comment by azuic** [comment]
Thank you so much! Should I update to the most recent commit?

**Comment by soulslicer** [comment]
Yes

**Comment by azuic** [comment]
It almost work but I got a whole list of `[CMakeFiles/openpose_lib.dir/all] Error 2` and `[all] Error 2`. I checked the 3rdparty/pybind11 and it is empty. 

```
make[2657]: /bin/sh: Resource temporarily unavailable
make[2657]: *** wait: No child processes.  Stop.
make[2657]: *** Waiting for unfinished jobs....
make[2657]: *** wait: No child processes.  Stop.
make[2656]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2655]: *** [all] Error 2
make[2654]: *** [openpose_lib] Error 2
make[2653]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2652]: *** [all] Error 2
```

**Comment by azuic** [comment]
Just cloned from https://github.com/pybind/pybind11.git

**Comment by azuic** [comment]
It still doesn't work but I got an additional message on top:
```
/bin/sh: fork: Resource temporarily unavailable
make[2648]: *** [CMakeFiles/openpose_lib.dir/depend] Error 128
make[2647]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2646]: *** [all] Error 2
make[2645]: *** [openpose_lib] Error 2
make[2644]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2643]: *** [all] Error 2
make[2642]: *** [openpose_lib] Error 2
make[2641]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2640]: *** [all] Error 2
make[2639]: *** [openpose_lib] Error 2
make[2638]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2637]: *** [all] Error 2
make[2636]: *** [openpose_lib] Error 2
make[2635]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2634]: *** [all] Error 2
make[2633]: *** [openpose_lib] Error 2
make[2632]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2631]: *** [all] Error 2
make[2630]: *** [openpose_lib] Error 2
make[2629]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2628]: *** [all] Error 2
make[2627]: *** [openpose_lib] Error 2
make[2626]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2625]: *** [all] Error 2
make[2624]: *** [openpose_lib] Error 2
make[2623]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[2622]: *** [all] Error 2
...
make[2]: *** [openpose_lib] Error 2
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by azuic** [comment]
It looks like there are something to do with the system limit of file/process per user. I will see if it can be fixed by increase the soft limits.

**Comment by azuic** [comment]
@soulslicer Have you run into this issue when you test building it? I got recursive error messages as the following. I have already increase the maxproc limit in the LaunchDaemon plist file and I feel like it made some improvements since currently it stopped at `make[3971]` and before it was `make[2648]`. I have increase my soft limit to 4096 and my hard limit is 4256. Should I keep increasing it or is it some kind of iteration error in the source?

```
...
Rerunning cmake after building Caffe submodule
-- Building with OpenCL.
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
HEAD is now at fe2a1102 Fix AMD amdgpu-pro miserporting wrong work-group sizes.
M	cmake/Modules/FindvecLib.cmake
M	src/caffe/layers/malis_loss_layer.cpp
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- Model already exists.
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/zuic/GIT/openpose/build
/bin/sh: fork: Resource temporarily unavailable
make[3971]: *** [CMakeFiles/openpose_lib.dir/depend] Error 128
make[3970]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[3969]: *** [all] Error 2
make[3968]: *** [openpose_lib] Error 2
make[3967]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[3966]: *** [all] Error 2
make[3965]: *** [openpose_lib] Error 2
make[3964]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[3963]: *** [all] Error 2
make[3962]: *** [openpose_lib] Error 2
make[3961]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[3960]: *** [all] Error 2
make[3959]: *** [openpose_lib] Error 2
make[3958]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make[3957]: *** [all] Error 2
...
```

**Comment by azuic** [comment]
Also my maxfiles limit has been set to 200000

**Comment by soulslicer** [comment]
Sorry, are we talking about OpenCL or Pybind?

**Comment by azuic** [comment]
I guess still openCL? I got this error when I ran the command. 
``` 
make -j `nproc`
```

**Comment by azuic** [comment]
Actually I am not sure now, I just checked the pybind11 folder inside 3rdparty and it's empty again. Should I reclone it??

**Comment by soulslicer** [comment]
Sorry I am really not sure what this error is about. We are able to build both OpenCL and Python with no problems on the latest Macbooks and OSX. We also have a travis script to test it.

I would suggest first doing a clean build. delete everything, and reclone and build. If that still doesnt work, you may have to consider a fresh install of the latest OSX, following our preinstall instructions

**Comment by azuic** [comment]
Okay! I will do that and thank you!

**Comment by soulslicer** [comment]
I just want to add also, your GPU is almost 5 years old. I am not sure if you will have any performance improvement over CPU tbh

**Comment by azuic** [comment]
Thanks for that reminder! I will have to try it anyway, but if it doesn't work I'll just switch to the CPU version!

**Comment by gineshidalgo99** [comment]
Assumed solved given no further answer. Thanks

**Comment by rajhlinux** [comment]
I get this same error only when caffe is not built with their version of opencl.

Need to delete everything and do the following:
```
cd ~ ; git clone https://github.com/BVLC/caffe
cd caffe ; git checkout opencl
export OCLCAFFE=$PWD
```
Copy ViennaCL library
Download ViennaCL for Linux:
https://sourceforge.net/projects/viennacl/files/1.7.x/ViennaCL-1.7.1.tar.gz/download

Extract downloaded folder:
tar -xvf ViennalCL-<version>.tar.gz

Copy extracted folder to Caffe's root folder.

Then:
pkg install sqlite3

Note: Some python scripts requires to "chmod +x": 

chmod +x /home/user/caffe/scripts/prebuild/blob_creator.py 
chmod +x /home/user/caffe/scripts/prebuild/layer_creator.py 
chmod +x /home/user/caffe/scripts/prebuild/quantizer_creator.py 
chmod +x /home/user/caffe/scripts/prebuild/test_macros.py
chmod +x /home/user/caffe/scripts/prebuild/macros.py

Also each of the above python script files requires to be edited and save 
with the top header containing: 
#!/usr/bin/env python

Then:

mkdir build && cd build

$ export CPLUS_INCLUDE_PATH=/usr/local/include/python3.9
(Note: Make sure to do the export command before the camke.)

cmake \
-D OPENCL_LIBRARIES=/usr/local/lib/libMesaOpenCL.so.1 \
-D CMAKE_BUILD_TYPE=Release \
-D CPU_ONLY=OFF \
-D USE_CUDA=OFF \
-D PYTHON_INCLUDE_DIR="/usr/local/include/python3.9/" \
-D PYTHON_LIBRARY="/usr/local/lib/libpython3.9.so" \
-D BUILD_python=OFF \
-D USE_OPENCL=ON \
-D BLAS=open ..

After doing the above steps, "cublas_v2.h" compiler error is gone. 

However I'm getting errors of something related to OpenCL, maybe because I am not using ROCm drivers...

I'm using FreeBSD 13.1 (Unix) similar to MacOS (Unix).
