### ISSUE TITLE
Missing flag --frame_undistort in documentaion

### ISSUE THREAD

**Issue by ravijo** [CMU-Perceptual-Computing-Lab/openpose#1078]
### Issue Summary
Point 2.2 in [Step 2 - Extrinsic Parameter Calibration](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/calibration_module.md#step-2---extrinsic-parameter-calibration) is missing the flag `--frame_undistort`. It says the following:

> After intrinsics calibration, save undirtoted images for all the camera views:
> ```
> ./build/examples/openpose/openpose.bin --num_gpu 0 --flir_camera --write_images ~/Desktop/extrinsics
> ```

The above says to save _undistorted images_. I guess we need to supply the flag  `--frame_undistort` along with it. I mean to say the command in above quoted text should be changed to following:
```
./build/examples/openpose/openpose.bin --num_gpu 0 --flir_camera --write_images ~/Desktop/extrinsics --frame_undistort
```

### Type of Issue
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc

### System Configuration
**OpenPose version**: Latest GitHub code

Please reply whether `--frame_undistort` is needed or not.

**Comment by gineshidalgo99** [comment]
You are completely right! I will fix it soon in the next commit! Please, use that flag as you mention.

**Comment by ravijo** [comment]
Thank you very much!
