### ISSUE TITLE
What is the naming convention implemented for the flag --write_images

### ISSUE THREAD

**Issue by ravijo** [CMU-Perceptual-Computing-Lab/openpose#1079]
### Issue Summary
Consider, I am using multiple cameras (let say 4) let say `flir_camera`. Let say we execute the following command:
```
./build/examples/openpose/openpose.bin --num_gpu 0 --flir_camera --write_images ~/Desktop/extrinsics
```
OpenPose grabs the images from all 4 cameras and store in `~/Desktop/extrinsics` directory.

### Question
What is the naming convention of the images? Is it the following `SerialNumber_Counter.png`. 
For example: 

1. 17012332_1.png 17012333_1.png 17012334_1.png 17012335_1.png
1. 17012332_2.png 17012333_2.png 17012334_2.png 17012335_2.png
1. 17012332_3.png 17012333_3.png 17012334_3.png 17012335_3.png
1. and so on ...

**What is the naming convention of the images?**

### Type of Issue
- Help wanted
- Question

### System Configuration
**OpenPose version**: Latest GitHub code

**Comment by gineshidalgo99** [comment]
Good question (I will add it to the documentation in the next commit). It is the following:
000000000000_rendered.png
000000000000_rendered_1.png
000000000000_rendered_2.png
[...]
000000000000_rendered_N1.png
000000000001_rendered.png
000000000001_rendered_1.png
000000000001_rendered_2.png
[...]
000000000001_rendered_N1.png
[...]

Where N1 is the number of cameras (N) minus 1, i.e., N1 = N-1.

OpenPose generates them with the base name 000000000000_rendered. Ideally, any other base number should work, as long as the name is kept for all the camera views. E.g., you could call them (assuming 4 cameras):
a.png, a_1.png, a_2.png, a_3.png, b.png, b_1.png, b_2.png, b_3.png, etc
