### ISSUE TITLE
Proper input spec for body_25 model

### ISSUE THREAD

**Issue by elmuz** [CMU-Perceptual-Computing-Lab/openpose#1081]
Hi all,
I just wanted to ask which input format the body_25 network expects.
In particular, if it needs BGR colorspace or RGB, if values need to be scaled between 0.0 and 1.0 or -1/+1 (or something else).

Thank you

**Comment by gineshidalgo99** [comment]
Follow core/cvToOpInput.cpp to know the details, I do not fully remember them at the moment.
