### ISSUE TITLE
Foot keypoints missing from annotations

### ISSUE THREAD

**Issue by aabreu** [CMU-Perceptual-Computing-Lab/openpose#1084]
### Issue Summary
Foot keypoints seems to be missing from the annotations files [posted here](https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/)

Also noticed that all the annotations have 17 keypoints max.

### Executed Command (if any)
wget http://posefs1.perception.cs.cmu.edu/OpenPose/datasets/foot/person_keypoints_train2017_foot_v2.zip
unzip person_keypoints_train2017_foot_v1.zip
python -c "import json;import os;annotations = json.load(open('./person_keypoints_train2017_foot_v1.json'));print(annotations['categories'])"

### OpenPose Output (if any)
{'supercategory': 'person', 'id': 1, 'name': 'person', 'keypoints': ['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle'], 'skeleton': [[16, 14], [14, 12], [17, 15], [15, 13], [12, 13], [6, 12], [7, 13], [6, 7], [6, 8], [7, 9], [8, 10], [9, 11], [2, 3], [1, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7]]}

### Type of Issue
- Help wanted
- Question

**Comment by SoCohesive** [comment]
Hi i've also noticed this issue. Do you know where the valid dataset for foot keypoints are?

**Comment by abdul-mateen-chughtai** [comment]
I have also downloaded the annotations file only to find out that foot keypoints are missing from it.

**Comment by gineshidalgo99** [comment]
If you print the field `keypoints` of any person instance, you will see that the training JSON has 23 keypoints (COCO 17 + Foot 6) and that the validation JSON has 6 keypoints (only the feet keypoints).

**Comment by cwlinghk** [comment]
May I know is that only feet keypoints are used for validation? Thank you very much.

**Comment by gineshidalgo99** [comment]
You can use the COCO JSON for that. In the validation, we only test foot accuracy, that is why body keypoints are omitted.

**Comment by dklospace** [comment]
I found the train / val annotations on https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/ doesn't have foot annotations. Could you please double check? @gineshidalgo99

**Comment by dklospace** [comment]
For example the list of keypoints included in the training dataset annotation json looks like:

```
   "categories": {
     "supercategory": "person",
     "id": 1,
     "name": "person"
     "keypoints": [
       "nose",
       "left_eye",
       "right_eye",
       "left_ear",
       "right_ear",
       "left_shoulder",
       "right_shoulder",
       "left_elbow",
       "right_elbow",
       "left_wrist",
       "right_wrist",
       "left_hip",
       "right_hip",
       "left_knee",
       "right_knee",
       "left_ankle",
       "right_ankle"
     ],
     "skeleton": [
       [
         16,
         14
       ],
```

**Comment by dklospace** [comment]
@gineshidalgo99  Oh alright, I didn't look at `keypoints` field, just double checked and there are 23 keypoints.

**Comment by gineshidalgo99** [comment]
Yep! The keypoints are there! Best

**Comment by Jaykob** [comment]
Hi!
Anybody here willing to help me train as foot-only?
I'd be interested to see how `d_setLayers.py` should be configured.
