### ISSUE TITLE
unable to start program 

### ISSUE THREAD

**Issue by ZHOUXIAOYI95** [CMU-Perceptual-Computing-Lab/openpose#1088]
Hi Everyone,

I'm a beginner, I followed the openpose installation instruction, although the  "openpose.cpp" has been successfully built, the program can't start due to the invalid win32 application. I unchecked the  "BUILD_BIN_FOLDER" already. 
![capture](https://user-images.githubusercontent.com/46758172/52805070-ac396a80-307d-11e9-8647-a8b018e056a1.PNG)

**Comment by aup3gj** [comment]
I meet the same situation

**Comment by gineshidalgo99** [comment]
When using Cmake, select VS 2015 x64 (very important the x64). Thanks.
