### ISSUE TITLE
Do you have pyopenpose documentation？

### ISSUE THREAD

**Issue by zj6362295** [CMU-Perceptual-Computing-Lab/openpose#1089]
I want to know more about pyopenpose, such as what methods and parameters it has and what the return value means, but I haven't found any other documentation except tutorial_api_python.Do you have a complete documentation of pyopenpose?

**Comment by soulslicer** [comment]
Currently it only has an API that is analagous to the C++ Function calls. You may find them here:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/python/openpose/openpose_python.cpp#L194

The API is rather simple. `op::Array<float>` and `cv::Mat` objects get casted to `numpy` arrays automatically. Every other data structure based on standard library is automatically converted into python objects. For example an `std::vector<std::vector<float>>` would become `[[item, item], [item, item]]` etc. We also provide a casting of `op::Rectangle` and `op::Point` which simply expose setter getter for `x,y,width,height` etc.

Some work can definitely be done to expose more of the C++ APIs based on user demand etc. But we agree the documentation of the python API should be exposed via Doxygen. I have not figured out how to do that, but we are definitely open to pull requests.

**Comment by zj6362295** [comment]
> Currently it only has an API that is analagous to the C++ Function calls. You may find them here:
> 
> https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/python/openpose/openpose_python.cpp#L194
> 
> The API is rather simple. `op::Array<float>` and `cv::Mat` objects get casted to `numpy` arrays automatically. Every other data structure based on standard library is automatically converted into python objects. For example an `std::vector<std::vector<float>>` would become `[[item, item], [item, item]]` etc. We also provide a casting of `op::Rectangle` and `op::Point` which simply expose setter getter for `x,y,width,height` etc.
> 
> Some work can definitely be done to expose more of the C++ APIs based on user demand etc. But we agree the documentation of the python API should be exposed via Doxygen. I have not figured out how to do that, but we are definitely open to pull requests.
Thank you for your reply and look forward to your documentation.
