### ISSUE TITLE
HDF5: infinite loop closing library

### ISSUE THREAD

**Issue by GeorgianaPetria** [CMU-Perceptual-Computing-Lab/openpose#109]
I am running the OpenPose demo on a ec2 instance and getting the following error:

> HDF5: infinite loop closing library
>       D,T,F,FD,P,FD,P,FD,P,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E

Command:

> ./build/examples/openpose/openpose.bin --video examples/media/video.mp4 --write_video output/result.avi --no_display

Regardless of the error, the output video is correct.

Do you know what might be wrong with OpenPose & HDF5?

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu 14.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8
**cuDNN version**: 6
**GPU model** (`nvidia-smi`): Tesla K80
**Caffe version**: custom
**OpenCV version**: 2.4.8
Compiler (`gcc --version` on Ubuntu): 4.8.4

**Comment by gineshidalgo99** [comment]
I found that in a server. Removing HDF5 and re-installing the last version (and after that re-installing Caffe + OpenPose) solved the issue.
But still, in case you do not want to mess up other working programs, OpenPose runs fine, even if HDF5 shows that warning when closing OpenPose.
Let me know how you solve it.

**Comment by a2940519** [comment]
I had this problem before, and the latter two discovered that I had forgotten the model file..

**Comment by gineshidalgo99** [comment]
Given there is no answer after 1 week, I'll close this issue assuming it was solved. Please, post again if this issue persists or re-appears.

**Comment by arpit15** [comment]
I am facing the same problem. I have the latest version of libhdf-5 available through apt-get. I am able to run the demo. However I am not able to see anything on my video. My video at the start contains some part when there is no humans. Can it lead to crash in the software?

Operating system (lsb_release -a on Ubuntu): Ubuntu 14.04
CUDA version (cat /usr/local/cuda/version.txt in most cases): 8
cuDNN version: 6
GPU model (nvidia-smi): Tesla K40
Caffe version: custom
OpenCV version: 3.1.0
Compiler (gcc --version on Ubuntu): 4.8.4
