### ISSUE TITLE
ERROR: something wrong with flag 'logtostderr' in file 'src/logging.cc'

### ISSUE THREAD

**Issue by johnxian1** [CMU-Perceptual-Computing-Lab/openpose#1090]
i build openpose succesfully and when i try to run it. It show this message:

./build/examples/openpose/openpose.bin --help
ERROR: something wrong with flag 'logtostderr' in file 'src/logging.cc'. One possibility: file 'src/logging.cc' is being linked both statically and dynamically into this executable.

someone help me

**Comment by johnxian1** [comment]
my build openpose:
cd build
cmake -DCaffe_INCLUDE_DIRS=/usr/local/caffe/include  \
    -DCaffe_LIBS=/usr/local/caffe/build/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

**Comment by Joneny** [comment]
I have the same problem,Do you solve the problem right now?
thank you!

**Comment by gineshidalgo99** [comment]
Try installing Caffe by yourself following their doc, and after it works, just link it to the current OpenPose with Cmake. Thanks.
