### ISSUE TITLE
Python API about Videos

### ISSUE THREAD

**Issue by lilyswang** [CMU-Perceptual-Computing-Lab/openpose#1091]
Hello,everyone.How can we use tutorial_api_python  with some videos about hand gesture?

**Comment by soulslicer** [comment]
I am not clear about your question. You want to run openpose on a video and get hand keypoints?

**Comment by lilyswang** [comment]
yes@soulslicer, the tutorial_api_python only give us an API(eg.07_hand_from_image.py) that deal with one picture.
I want to get all hand keypoints from a vedio as you mention above.  Can you give me some suggestions?  Thanks.

**Comment by soulslicer** [comment]
You may try this tutorial:

https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html

**Comment by lilyswang** [comment]
Thanks a lot,@soulslicer

**Comment by ZDL-Git** [comment]
> You may try this tutorial:
> 
> https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html

C++ command version has the ability of process video, why python wrapper not? Thanks
