### ISSUE TITLE
Failed to run the exmple:"2_thread_user_input_processing_output_and_datum.bin"

### ISSUE THREAD

**Issue by Glorialiujie** [CMU-Perceptual-Computing-Lab/openpose#1094]
### Issue Summary
failed to run the example:"2_thread_user_input_processing_output_and_datum.bin"(core dumped)  while other examples works fine.

### Executed Command (if any)
./build/examples/tutorial_api_thread/2*.bin --logging_level 0

### OpenPose Output (if any)
Starting OpenPose demo...
Starting thread(s)...
/home/leo/openpose/openpose-master20190219/include/openpose/thread/threadManager.hpp:exec():185
/home/leo/openpose/openpose-master20190219/include/openpose/thread/queueBase.hpp:addPusher():362
/home/leo/openpose/openpose-master20190219/include/openpose/thread/queueBase.hpp:addPusher():362
/home/leo/openpose/openpose-master20190219/include/openpose/thread/threadManager.hpp:exec():190
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:startInThread():137
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:startInThread():137
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:threadFunction():182
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:initializationOnThread():167
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:threadFunction():185
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:threadFunction():182
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:initializationOnThread():167
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:threadFunction():185
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:threadFunction():182
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:initializationOnThread():167
/home/leo/openpose/openpose-master20190219/include/openpose/thread/thread.hpp:threadFunction():185

### Type of Issue

- Execution error
- Help wanted

###  System Configuration

ubuntu18.04 x86_64
gpu geforce gtx 1060 6g   Driver Version:415.25
opencv 3.4
cuda  9.2

**Comment by gineshidalgo99** [comment]
Fixed in the latest commit! Please, check it again!
