### ISSUE TITLE
How to train on new hands gesture detection dataset?

### ISSUE THREAD

**Issue by jinfagang** [CMU-Perceptual-Computing-Lab/openpose#1095]
Thanks for this wonderful opensource project. Does there any hands keypoint detection dataset preparation documents or any open dataset which can be used to train openpose?

Does there any training model provided to training a new datasets of hands keypoint detection?

**Comment by gineshidalgo99** [comment]
OpenPose does not provide training. Check the respective papers for more info about that. Thanks
