### ISSUE TITLE
using cmake-gui to build openpose  in ubuntu

### ISSUE THREAD

**Issue by vivek09pathak** [CMU-Perceptual-Computing-Lab/openpose#1097]
Building with CUDA.
CUDA detected: 7.5
Added CUDA NVCC flags for: sm_61
cuDNN not found
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
cuDNN not found.
#!/bin/bash

echo "NOTE: This script assumes Ubuntu 16 or 14 and Nvidia Graphics card up to 10XX. Otherwise, install it by yourself or it will fail."

# Install cuDNN 5.1
CUDNN_URL="http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz"
wget -c ${CUDNN_URL}
sudo tar -xzf cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local
rm cudnn-8.0-linux-x64-v5.1.tgz && sudo ldconfig

CMake Error at CMakeLists.txt:453 (message):
  Install cuDNN using the above commands.  or turn off cuDNN by setting
  USE_CUDNN to OFF.

Configuring incomplete, errors occurred!
See also "/home/ubuntu/Github/tf-pose-estimation/ARUPE/st-gcn/openpose/build/CMakeFiles/CMakeOutput.log".

I have installed cuda-8.0 and when i do nvcc --version it shows cuda 8.0 only

**Comment by salihkaragoz** [comment]
+1

**Comment by gineshidalgo99** [comment]
If OP is finding 7.5 and you installed 8.0, you are having an issue with multiple CUDA versions.

Cmake-gui allows you to select the location of your CUDA path. Other than that, the easiest solution is to remove all older CUDA versions. This is a 3rdparty issue, so I must close it. Best
