### ISSUE TITLE
Prototxt file not found: models\pose/body_25/pose_deploy.prototxt.

### ISSUE THREAD

**Issue by billypig** [CMU-Perceptual-Computing-Lab/openpose#1098]
Run on video is available but when I want to run on image or run on video on cmd commands will show the problem us below
How can I slove this problem
Thanks!!

C:\Users\E501>D:\Openpose\openpose\build\x64\Release\OpenPoseDemo.exe -- video examples\media\video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Webcam was unplugged, trying to reconnect it.
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
Prototxt file not found: models\pose/body_25/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- D:\Openpose\openpose\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():51
- D:\Openpose\openpose\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():162
- D:\Openpose\openpose\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():237
- D:\Openpose\openpose\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():98
- D:\Openpose\openpose\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
- D:\Openpose\openpose\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::initializationOnThread():57
- D:\Openpose\openpose\include\openpose/thread/subThread.hpp:op::SubThread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::initializationOnThread():150
- D:\Openpose\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::initializationOnThread():173
- D:\Openpose\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::threadFunction():203

**Comment by hellboywyh** [comment]
Maybe you didn't work in correct directory……the correct directory is the father directory of xx/models/.

**Comment by blmhds** [comment]
I thk u should change the road in your code

**Comment by gineshidalgo99** [comment]
Please, read the doc/quick_start.md
