### ISSUE TITLE
Ubuntu Python API lag on emplaceAndPop on CPU

### ISSUE THREAD

**Issue by wutter** [CMU-Perceptual-Computing-Lab/openpose#1099]
### Issue Summary
When running openpose from binary with given arguments, it runs about 20 FPS (minor lag every 6 frames,  which coresponds to tracking number + 1 (tested).
But when running from python it runs 5x 0.0X ms and one +2.5s delay on emplaceAndPop and at quite low speed.

### Executed python code (with parameter --image_path and random image with person from same camera as for the other code)
```
# Modified example code to process one image in a loop
# From Python
# It requires OpenCV installed for Python
import sys
import cv2
import os
from sys import platform
import argparse
import datetime as dt
import pyopenpose as op

# Flags
parser = argparse.ArgumentParser()
parser.add_argument("--image_path", default="../../../examples/media/COCO_val2014_000000000192.jpg", help="Process an image. Read all standard formats (jpg, png, bmp, etc.).")
args = parser.parse_known_args()

# Custom Params (refer to include/openpose/flags.hpp for more parameters)
params = dict()
params["model_folder"] = "/absolute/path/to/models"
params["model_pose"] = "COCO"
params["net_resolution"] = "-1x80"
params["tracking"] = 5
params["number_people_max"] = 1
params["profile_speed"] = 15

# Starting OpenPose
opWrapper = op.WrapperPython()
opWrapper.configure(params)
opWrapper.start()

while True:
      # Process Image
      datum = op.Datum()
      imageToProcess = cv2.imread(args[0].image_path)
      datum.cvInputData = imageToProcess

      time = dt.datetime.now() # when the timing is measured here -> it is clear that this function does the delays
      opWrapper.emplaceAndPop([datum])

      print(dt.datetime.now()-time)

```

### Executed binary startup
`./openpose.bin --model_pose COCO --tracking 5 --number_people_max 1 --net_resolution -1x80 --profile_speed 15`

### Type of Issue
- Execution error
- Question
- Speed preformance

### Your System Configuration
2. **OpenPose version**: OpenPose 1.4.0 from 'Release'

3. **General configuration**:
    - **Installation mode**: CMake (Ubuntu)
    - **Operating system**: Ubuntu 18.04.1 LTS
    - **Operating system version**: Ubuntu 18.04
    - **Release mode**
    - Compiler: gcc 7.3.0 (Ubuntu)

4. **Non-default settings**:
    - **BUILD_PYTHON=1**
    - **GPU_MODE=CPU_ONLY**
    - **DOWNLOAD_BODY_COCO_MODEL=1**
    - **PYBIND11_INSTALL=1**
    - **PYTHON_EXECUTABLE=0**
    - **PYTHON_LIBRARY=/.../python2.7**
    - **USE_MKL=1**
    - **PROFILER_ENABLED=1**
    - **USE_PYTHON_INCLUDE_DIR=1**

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.10.2
    - **OpenCV version**: 3.2.0

7. If **CPU-only mode** issue:
    - **CPU brand & model**: Quad core Intel Core i7-8550U (-MT-MCP-)
    - Total **RAM memory** available: Used/Total: 1279.6/15803.7MB (when OpenPose is not running)

8. If **Python** API:
    - **Python version**: 2.7
    - **Numpy version**: 1.16.0

10. If **speed performance** issue:
**Python output**
```
0:00:05.470587
0:00:00.014510
0:00:00.010338
0:00:00.010861
0:00:00.010430
0:00:00.011687
0:00:02.446543
0:00:00.010277
0:00:00.011665
0:00:00.010424
0:00:00.010417
0:00:00.010262
0:00:02.489098
0:00:00.010016
0.000497 msec in /home/naolaptop/Software/openpose/include/openpose/thread/wIdGenerator.hpp:work():76
0.001330 msec in /home/naolaptop/Software/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():74
7.732790 msec in /home/naolaptop/Software/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():70
0.191526 msec in /home/naolaptop/Software/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():73
601.641667 msec in /home/naolaptop/Software/openpose/include/openpose/pose/wPoseExtractor.hpp:work():98
0.068003 msec in /home/naolaptop/Software/openpose/include/openpose/pose/wPoseRenderer.hpp:work():79
0.193666 msec in /home/naolaptop/Software/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():69
```

**openpose.bin output**
```
14.520146 msec in /home/naolaptop/Software/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():79
0.000254 msec in /home/naolaptop/Software/openpose/include/openpose/thread/wIdGenerator.hpp:work():76
0.001494 msec in /home/naolaptop/Software/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():74
0.132837 msec in /home/naolaptop/Software/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():70
1.419228 msec in /home/naolaptop/Software/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():73
35.861055 msec in /home/naolaptop/Software/openpose/include/openpose/pose/wPoseExtractor.hpp:work():98
0.418573 msec in /home/naolaptop/Software/openpose/include/openpose/pose/wPoseRenderer.hpp:work():79
1.740577 msec in /home/naolaptop/Software/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():69
0.280620 msec in /home/naolaptop/Software/openpose/include/openpose/gui/wGuiInfoAdder.hpp:work():73
2.712185 msec in /home/naolaptop/Software/openpose/include/openpose/gui/wGui.hpp:workConsumer():87
```

**Comment by soulslicer** [comment]
Hm...this should not happen. 

I ran `build/examples/tutorial_api_cpp/04_keypoints_from_images.bin` and I also ran `python3 04_keypoints_from_images.py` and they both take roughly the same amount of time. C++ version was 0.3s faster because of multithreading

**Comment by wutter** [comment]
I see you are using python3, I was using python2.7, Ill see if that changes anything.

**Comment by wutter** [comment]
Ok, tried with python3 and it is still same (about 600msec in wPoseExtractor again).

**Comment by wutter** [comment]
Solved by getting external GPU, so I wont be looking for solution anymore, but Ill leave it open if anybody comes across the same problem and finds a solution.

**Comment by gineshidalgo99** [comment]
Thanks for the fix.
