### ISSUE TITLE
Add support for Docker

### ISSUE THREAD

**Issue by ruffsl** [CMU-Perceptual-Computing-Lab/openpose#11]
This is an awesome project, so I think it could use some Dockerfiles to simplify the build steps, thus lowering the barrier of entry for new users. Perhaps we could start making some Dockerfiles building from a parent images like [BVLC's Caffe Docker Image](https://github.com/BVLC/caffe/blob/master/docker/gpu/Dockerfile), then create an automated DockerHub repo to host the latest set of releases of OpenPose? I'll send a PR of a set of Dockerfiles and run scripts that are working for me.

**Comment by gineshidalgo99** [comment]
Thank you so much! I will close this issue and directly reply to the pull request.
