### ISSUE TITLE
compile error. ‘caffe::Blob’ is not a template type || Related to issue #942

### ISSUE THREAD

**Issue by pavithraezhil** [CMU-Perceptual-Computing-Lab/openpose#1101]
### Issue Summary
Issue related to #942
Custom NVCaffe gives this error

### Executed Command (if any)
cmake -DOpenCV_INCLUDE_DIRS=/home/pavithra/opencv/build/include   -DOpenCV_LIBS_DIR=/home/pavithra/opencv/build/lib   -DCaffe_INCLUDE_DIRS=/home/pavithra/caffe/distribute/include   -DCaffe_LIBS=/home/pavithra/caffe/distribute/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

### Errors (if any)
error: ‘caffe::Blob’ is not a template
             std::unique_ptr<caffe::Blob<T>> upCaffeBlobT;
                                    ^
### Type of Issue
- Compilation/installation error

### Your System Configuration
1. https://pastebin.com/MxMSirMD
2. **OpenPose version**: Latest GitHub code
3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**  lsb_release -a in Ubuntu
    - **Operating system version** Ubuntu 16.04
    - **Release or Debug mode**? release
  
5. **3rd-party software**:
    - **Caffe version**: Custom 0.17
    - **CMake version** : 3.10.2
    - **OpenCV version**: 3.4.4
6. If **GPU mode** issue:
    - **CUDA version**: 10
    - **cuDNN version**: 7.3
    - **GPU model**: 2080 Ti

8. If **Python** API:
    - **Python version**: 2.6, 3.5

**Comment by gineshidalgo99** [comment]
I am sorry, I have never tried NVCaffe, we only support official Caffe (unfortunately I do not have time to check all Caffe variants out there), so I do not know how NVCaffe works. Please, let me know if you make it work so I can add it to the doc for other users!

**Comment by pavithraezhil** [comment]
Okay, thank you. I am trying to utilize tensor cores on my GPU which requires an FP16 model. Since the official Caffe doesn't support FP16, I tried NVCaffe. Could you please suggest a way to get Openpose to utilize tensor cores? Thank you.

**Comment by gineshidalgo99** [comment]
Unfortunately, I have never tried that (we don't have those GPUs), so I can't help much. Any community help will be highly appreciated so I can add it to the do for everyone else to use it :)

**Comment by gineshidalgo99** [comment]
This is solved with #1169 PR. You can use that one provisionally. We will try to merge it into OP. Thanks.
