### ISSUE TITLE
ERROR: something wrong with flag 'logtostderr' in file '/home/yiqiaozhou/applications/glog/src/logging.cc'. 

### ISSUE THREAD

**Issue by Joneny** [CMU-Perceptual-Computing-Lab/openpose#1104]
### Issue Summary
I installed the Caffe correctly according to the http://caffe.berkeleyvision.org ,I also build openpose in accordance with the official tutorial.but when i try to run the command :
`./build/examples/openpose/openpose.bin --image_dir examples/media/` or
`./build/examples/openpose/openpose.bin --vedio examples/media/video.avi`

I get error message : 
`ERROR: something wrong with flag 'logtostderr' in file '/home/yiqiaozhou/applications/glog/src/logging.cc'.  One possibility: file '/home/yiqiaozhou/applications/glog/src/logging.cc' is being linked both statically and dynamically into this executable.`

I installed glog through source code

I google this problem and found someone face the same problem in the process of build Caffe.I don't know if I have problems in the process of compiling caffe, which leads to the current error.

I would be very grateful if someone can answer me.

### Errors (if any)

`ERROR: something wrong with flag 'logtostderr' in file '/home/yiqiaozhou/applications/glog/src/logging.cc'.  One possibility: file '/home/yiqiaozhou/applications/glog/src/logging.cc' is being linked both statically and dynamically into this executable.`

### Type of Issue

- Compilation/installation error

### Your System Configuration
1. Ubuntu16.04

2. **OpenPose version**: The latest version

3. **General configuration**:
    - **Installation mode**: cmake-gui
    - **Operating system** : Ubuntu16.04
    - **Release or Debug mode**? (by default: release):release
    - Compiler : g++ 5.4.0

4. **Non-default settings**:
 
5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version all used。
    - **CMake version**:3.5
    - **OpenCV version**: 3.3.0

6. If **GPU mode** issue:
    - **CUDA version** 8.0
    - **cuDNN version**: 5.1
    - **GPU model** :nvidia-smi`

7. If **CPU-only mode** issue:

8. If **Python** API:
    - **Python version**: 2.7
    - **Numpy version** : 1.15.2

**Comment by gineshidalgo99** [comment]
Try running some Caffe example. OpenPose does not uses logging, Caffe is the one using it internally. I would recommend to just install the default that Caffe recommends. But again, try running Caffe examples. If you see this error here, you should see it with Caffe.

**Comment by Joneny** [comment]
> Try running some Caffe example. OpenPose does not uses logging, Caffe is the one using it internally. I would recommend to just install the default that Caffe recommends. But again, try running Caffe examples. If you see this error here, you should see it with Caffe.
> 
> We do not support 3rdparty issues, so you are free to post your solution to help others, but we cannot spend our time in non-default 3rdparty issues (as grad students we do not have much time!)

thanks a lot for your help!Hope you have a good time!
