### ISSUE TITLE
Steps to install openpose python api on jetson Tx2

### ISSUE THREAD

**Issue by SmitSheth** [CMU-Perceptual-Computing-Lab/openpose#1105]
Can someone list proper steps for installing python api on jetson tx2.

While trying to import openpose Im facing following ewrror,

File "<stdin>", line 1, in <module>
File "/home/nvidia/openpose/python/openpose/__init__.py", line 1, in <module>
from . import pyopenpose as pyopenpose
ImportError: cannot import name 'pyopenpose'

**Comment by gineshidalgo99** [comment]
I am sorry, we do not have Jetsons, that doc was introduced by the community. So we cannot help here. Anybody that has made it work on Jetson, please feel free to add some doc steps so everyone else can benefit from it!

**Comment by SmitSheth** [comment]
@gineshidalgo99 Any standalone instruction steps you have for installing python api i.e after we successfully install openpose without python api, how can we add python api after openpose installation.

**Comment by gineshidalgo99** [comment]
For that, follow the current PyOpenPose doc in doc/modules/python.md.

**Comment by gineshidalgo99** [comment]
(closed given no further answer)
