### ISSUE TITLE
cvOutputData modifications not saved to file using --write_video flag -Windows

### ISSUE THREAD

**Issue by ArifSohaib** [CMU-Perceptual-Computing-Lab/openpose#1107]
### Issue Summary
modified cvOutputData not being saved to file after modification. Modifications show up properly in in output but are reset to default pose output when saving file.

### build
default Openpose library with default OpenCV version, compiled using Visual Studio 2017 community and CUDA 10.

### Details
I based the code on example 11_asynchronous_custom_output in the cpp_api.
I am drawing lines and ellipses based on some criteria and I can see the result properly when it is processing. 
I tried setting the ```datumPtr->at(0)->cvOutputData``` directly using the ```cv::ellipse``` and ```cv::line``` functions and also tried copying it to another ```cv::Mat```, modifying it and then copying back to ```cvOutputData``` using setTo and copyTo.
It shows the modifications properly in both cases but switches back to the default output.

My current workaround is to use another ```cv::VideoWriter``` in the ```UserOutputClass``` and that is saving my output videos properly but since there is a```--write_video``` flag, I would prefer to use that.

**Comment by gineshidalgo99** [comment]
For that, you wanna check the example custom_postprocessing, rather than custom_output.

Unrelated question: I see you are using CUDA 10 with OpenPose on Windows. However, Caffe is supposed not to work with CUDA 10. Did you do anything special when installing it? Thanks!

Best

**Comment by ArifSohaib** [comment]
Thanks. 
For CUDA, I just compiled directly. I am using 10 because it works directly with Visual Studio 2017 while older versions can't. I was using the CPU version until I saw a commit message in this repo saying CUDA 10 is working.

**Comment by gineshidalgo99** [comment]
OK, I assume your GPU is not a 20XX model then, probably a 9XX or 10XX, correct? (sorry for the questions but that helps me debug other issues!)

**Comment by ArifSohaib** [comment]
No problem. It is a laptop version of GTX 1070

**Comment by gineshidalgo99** [comment]
OK thanks! Closing this. Feel free to post again here if you have any other question about your modified output

And just FYI, OpenPose with CUDA 10 seems to work on Windows, but 20XX graphic cards do not work (yet) on Windows. The reason is that the binary Caffe version that we include is using CUDA 8 (which is independent of which version you use for OpenPose, in your case CUDA 10)
