### ISSUE TITLE
Convert model to FP16 to leverage NVIDIA Tensor Cores

### ISSUE THREAD

**Issue by tech-gh** [CMU-Perceptual-Computing-Lab/openpose#1108]
### Issue Summary
If we can convert the model being used to FP16, it should result in a large performance boost on NVIDIA cards which have Tensor Cores since they require FP16 to use the Tensor Cores.  I believe it may also cut the memory consumption by a lot.  I'm not sure if TensorRT is ultimately required to utilize the cores as well, but the first step is to get to FP16.  Has anyone tried doing this successfully yet?

### Type of Issue
- Help wanted
- Question

### Your System Configuration
OpenPose 1.4.0 (newer would be fine too)
Ubuntu 16 (18 would be fine too or Windows)

**Comment by gineshidalgo99** [comment]
If anybody has tried it, feel free to do a pull request and/or let us know how!

**Comment by soulslicer** [comment]
If someone is able to port it to Pytorch even, the existing model, we would be able to integrate it

**Comment by tech-gh** [comment]
I think I've read that Intel's OpenVINO Model Optimizer or NVIDIA's tf-trt utility can be used for model conversion - not sure if can go from Caffe to Pytorch or not though.  I think one or both of those also supports precision conversion.

**Comment by gineshidalgo99** [comment]
I will close this, as we will not work on this given our limited resources. But feel free to add any PR about it if you implement it! Thanks.
