### ISSUE TITLE
i succeed run configure and generate. but got make -j'nproc' error

### ISSUE THREAD

**Issue by DragonAndSky** [CMU-Perceptual-Computing-Lab/openpose#1109]
I succeed installed caffe  cuda8.0 opencv

![image](https://user-images.githubusercontent.com/21075743/53551074-4cf65280-3b73-11e9-8d5d-e37b9d43d870.png)

error like this:
CMakeFiles/openpose_lib.dir/build.make:105: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

error log like this:

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/liuyukai/Desktop/pose_estimator/openpose/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2a7e1/fast"
/usr/bin/make -f CMakeFiles/cmTC_2a7e1.dir/build.make CMakeFiles/cmTC_2a7e1.dir/build
make[1]: Entering directory '/home/liuyukai/Desktop/pose_estimator/openpose/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2a7e1.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_2a7e1.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_2a7e1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2a7e1.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_2a7e1.dir/CheckFunctionExists.c.o  -o cmTC_2a7e1 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2a7e1.dir/build.make:97: recipe for target 'cmTC_2a7e1' failed
make[1]: *** [cmTC_2a7e1] Error 1
make[1]: Leaving directory '/home/liuyukai/Desktop/pose_estimator/openpose/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2a7e1/fast' failed
make: *** [cmTC_2a7e1/fast] Error 2

could someone help me ?

**Comment by dmatthes1982** [comment]
I had a similar problem. sudo apt-get install libboost-all-dev helped.

**Comment by DragonAndSky** [comment]
@dmatthes1982  thanks, i've solved it

**Comment by RatsLoveCats** [comment]
@dmatthes1982 Hello, I have encountered the same problem. How did you solve it?

**Comment by kourenmu** [comment]
@DragonAndSky same problem happens. how did you solve it?

**Comment by kourenmu** [comment]
@RatsLoveCats Hi, did you solve the problem?

**Comment by ZhengSaber** [comment]
Hi, I got the same problem, and I do` sudo apt-get install libboost-all-dev`, it told me that `libboost-all-dev is already the newest version (1.58.0.1ubuntu1).` And I still have this problem. did you solve the problem in this way? @dmatthes1982
