### ISSUE TITLE
Keypoints Data/Coordinate

### ISSUE THREAD

**Issue by RickGodLike** [CMU-Perceptual-Computing-Lab/openpose#111]
Hi, right now I am developing games via Kinect. At the moment, I am trying to figure out what is going on in OpenPoseDemo. As an almost-beginner, I am wondering how I can get keywords data directly in the codes instead of accessing numerous output data files one by one. 
Are there real-time variables/vectors storing  keypoint data(x,y,c) which can be accessed within each frame?

**Comment by gineshidalgo99** [comment]
Hi,

For that, you can check the tutorial_wrapper.

Best

**Comment by RickGodLike** [comment]
Hi, I have check examples/tutorial_wrapper/1_user_asynchronous.cpp. However, I cant find the correct one.. Also, I cannot use basic "cout << " method to display certain variables... Could you please help me out?

**Comment by gineshidalgo99** [comment]
1. `1_user_asynchronous.cpp`: in the custom output, you can read the op::Datum elements. E.g. you can read the Array elements (`pose_keypoints` is the one you are looking for I think)
2. `std::cout`: What do you mean you cannot use the basic cout with certain variables? which variables cannot be printed? op::Array, op::Datum cannot be directly printed with cout, but for Array you can use cout with its `toString()` method.

**Comment by RickGodLike** [comment]
like I add 
`std::cout<<op::datum.poeseKeypoints.toString(); `
into the UserOutput class in 1_user_asynchronous.cpp.
Then I compile and run it, nothing is printed on the screen. Everything is the same.
Also, I have a question about how to create my own files in the windows_projects folder. Every time I run the codes, it always show me the OpenPoseDemo.exe
Could you please help me out?

**Comment by gineshidalgo99** [comment]
You are missing `std::endl` at the end: `std::cout<<op::datum.poeseKeypoints.toString() << std::endl;`

You are right, so far we had only included OpenPoseDemo in the Windows version. I have just pushed to the VS solution with all the examples, you can pick and run whatever you like now.

**Comment by RickGodLike** [comment]
Hi! I have update your latest files on `windows_project/OpenPose.sln` and I try to complie/run `1_user_asynchronous.cpp` However, it says that `cant run `...\windows_project\x64\Release\OpenPose.lib` ` 
what happened..

**Comment by gineshidalgo99** [comment]
Hi, did you do right click on the user asynchronous project (or whatever you wanna run) and `Set up as startup project`?

**Comment by RickGodLike** [comment]
Oh... My bad.. Now I have set it as my startup project, and it says that `cant run/find ...\windows_project\x64\release\1_user_asynchronou.exe//`
Also, there's an error: cannot open input files \3rdparty\lib\release\caffe.lib... what happened..

**Comment by gineshidalgo99** [comment]
That is a problem installing Caffe. We will try to release a version in which Caffe does not need to be installed, since Caffe has lots of installation issues. We expect to release it during this week. Please check it every few days.

**Comment by gineshidalgo99** [comment]
@RickGodLike we released a new simplified Windows version in which Caffe is already installed by default, no need for you to install. Please, try this new version and let me know the results. Thanks!

**Comment by RickGodLike** [comment]
@gineshidalgo99 Yeah, I have tried the latest version, and everything goes smoothly! THANK U~

**Comment by gineshidalgo99** [comment]
OK great!
You had 2 issues:

- Compiling -> fixed
- Getting the keypoints from the program (instead of saving them): I updated yesterday the output documentation, I think that + tutorial_wrapper should be sufficient, let me know otherwise!
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

You can close the issue if (and after) all your issues are solved or ask me again otherwise. Thanks!
