### ISSUE TITLE
mAP on COCO2017 dataset

### ISSUE THREAD

**Issue by HONGJUNRL** [CMU-Perceptual-Computing-Lab/openpose#1110]
Could you please tell me how to evaluate with multi scale?

**Comment by soulslicer** [comment]
I happen to have a branch which lets you evaluate on COCO 2017:

https://github.com/soulslicer/openpose/tree/add_coco_script/eval

Simply go to this folder, run `get_cocoval_data.sh` then run `eval_coco.sh`

**Comment by HONGJUNRL** [comment]
> I happen to have a branch which lets you evaluate on COCO 2017:
> 
> https://github.com/soulslicer/openpose/tree/add_coco_script/eval
> 
> Simply go to this folder, run `get_cocoval_data.sh` then run `eval_coco.sh`

Thanks for your reply，could you please tell me how to write the code about multi scale. I am using tensorflow so i need to write it myself

**Comment by HONGJUNRL** [comment]
@soulslicer 
Thanks for your reply，could you please tell me how to write the code about multi scale. I am using tensorflow so i need to write it mysel
f

**Comment by gineshidalgo99** [comment]
We do not support Tensorflow, sorry
