### ISSUE TITLE
windows10 64bit CMake GUIOpenPose Configuration Module computer type "x64" conflicts with target computer type "X86" 2>LINK : fatal error LNK1181: can't open the file“....\src\openpose\Release\openpose.lib”

### ISSUE THREAD

**Issue by zyxcambridge** [CMU-Perceptual-Computing-Lab/openpose#1111]
![error_openpose_win32](https://user-images.githubusercontent.com/1818981/53638528-71c8f380-3c61-11e9-9e24-3d60beee0fc3.png)
![openpose_error](https://user-images.githubusercontent.com/1818981/53638535-78576b00-3c61-11e9-8210-67dc00e57951.png)

work for follow 
![ok](https://user-images.githubusercontent.com/1818981/53638609-ba80ac80-3c61-11e9-925b-d5d3f0b27fea.png)

**Comment by AndroidUnityGit** [comment]
i have the same question
