### ISSUE TITLE
Entry Point Not Found -- The procedure entry point cblas_dasum could not be located in the dynamic link library ... caffe.dll

### ISSUE THREAD

**Issue by IThoughtUGNU** [CMU-Perceptual-Computing-Lab/openpose#1113]
### Issue Summary
Compiling is ok. But when I run in either Debug/Release x64, I get this error message_
"Entry Point Not Found -- The procedure entry point cblas_dasum could not be located in the dynamic link library D:\dev\.tesi\git\openpose\3rdparty\windows\caffe_cpu\bin\caffe.dll"

I know that this is a caffe error and not OpenPose one, but I didn't have a caffe version already installed. I followed just the OpenPose procedure which downloades automatically the dependencies. I did the same procedure succesfully on a MacBook Pro with Windows 10 on BootCamp partition (same VS, Cmake 3.13.2 instead of version here used (see below),, Windows 10 Home, and **default** 3rd party lib configuration), I don't get why on my PC i get different results, above all with a not working program.

### Errors (if any)
Only at runtime (see summary)

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: [LINK](https://pastebin.com/EHpPvenQ)

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

Up to date with master

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...

CMake 3.14.0-rc2
Windows 10 (kinda-Home edition, aka updated from previous Windows 8.1 Home Edition)
Debug and/or Release
VS 2017 community

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

Caffe: default from OpenPose
CMake 3.14.0-rc2
OpenCV from OpenPose, though other versions are installed on the system

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

I got the error in CUDA mode with CUDA 10 (but CUDA 8 doesn't even let me compile, I should open up another issue)
Not sure about the cuDNN version, I have 2 nvcc's, one from CUDA 8 and one from CUDA 10 installations, anyway I get the error in CPU-only mode too (see below)
GPU: Nvidia GTX 1060

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

I got the error ALSO in CPU only mode
- Intel i7 4790 @ 3.60 Ghz
- 32 GB total ram

9. If **Windows** system:
    - Portable demo or compiled library?

Compiled library

-----------

EDIT:
I **still** get the error, having tried with official Release 1.4.0, and CMake 3.13.2 instead of the 3.14.0-rc2.

**Comment by IThoughtUGNU** [comment]
For the information, I tried a successful **workaround**, which is not a solution, but lets me use the library on my hardware (Intel i7 4790 @ 3.60 Ghz, GTX 1060 6 GB, 32 GB ram DDR3, etc.).

Installed a fresh Windows 10 installation on a HDD partition (170 GB)
and:
- VS2015 Enterprise Update 3 (I had problems installing it on SSD partition because Microsoft doesn't let you change the drive of installation, and mine was little of free space)
- CUDA 8 + patch *(as earlier)*
- cuDNN 5.1
- CMake 3.13.4 *(as earlier)*
- No custom OpenCV/Caffe/etc.. *(as earlier except for OpenCV)*
also for the python part:
- Anaconda with Python 3.7 (3.5 was recommended by Caffe but I found more easy to stick with 3.7).

It runs **both** on CPU_ONLY and CUDA mode. cuDNN now installed may explain why CUDA works. 
I am not sure what explains that CPU_ONLY **neither worked earlier** (on VS2017 community. But it actually works on the other PC (MacBook Pro) though).

Not a proper solution because on my first operating system and drive still it doesn't work even in CPU, so I don't know if the issue deserves to be closed, anyway that's it.

**Comment by gineshidalgo99** [comment]
Thanks for the explanation.

The best way is removing the whole OpenPose folder, re-downloading the latest version and re-trying (on Release mode).  Sometimes, when trying CUDA version and CPU Caffe versions in the same folder, VS messes up between the compiled files of both of them.
