### ISSUE TITLE
CMake error "make: *** [all] Error 2" when building OpenPose

### ISSUE THREAD

**Issue by JakeMalis** [CMU-Perceptual-Computing-Lab/openpose#1114]
### Issue Summary
I am trying to build OpenPose using CMake and I am getting errors after configuring and generating OpenPose.

### Executed Command (if any)
``` make -j`nproc` ```

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: [https://pastebin.com/4qUuGnzH](https://pastebin.com/4qUuGnzH)

2. **OpenPose version**: Latest GitHub commit

3. **General configuration**:
    - **Installation mode**: CMake script command in bash
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...): 18.04.2
    - **Release or Debug mode**? (by default: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 7.3.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.10.2
    - **OpenCV version**: pre-compiled `sudo apt install libopencv-dev`

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10.0
    - **cuDNN version**: 7.5.0
    - **GPU model** (`nvidia-smi` in Ubuntu): GeForce RTX 2070

7. If **CPU-only mode** issue:
    - **CPU brand & model**: i7-9700K (5.3 GHz Overclock)
    - Total **RAM memory** available: 16 GB

8. If **Python** API:
    - **Python version**: 3.6.8
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
Please, follow the doc/installation.md.

As it is indicated in there, CMake version 3.10.2 (the default one for Ubuntu 18) is not compatible with CUDA. Install a newer CMake (>=3.12) as the documentation indicates.

**Comment by dtandrade** [comment]
I've got the same problem and I have Cmake version: 3.15.3. I've already tried the same command (`make -j nproc`) with Cmake 3.13.X and 3.14.4. How can I solve that?

**System Configuration**

1. **OpenPose version:** Latest GitHub 
2. **General configuration**:
    
    - Operating system: Ubuntu

    - Operating system version: 18.04

3. **3rd-party software:**
    - **Caffe version:** downloaded from https://github.com/CMU-Perceptual-Computing-Lab/caffe.git

    - **CMake version:** 3.15.3

    - **OpenCV version:** sudo apt install libopencv-dev

4. **If GPU mode issue:**
        **CUDA version** (cat /usr/local/cuda/version.txt): 10.1
        **cuDNN version:** 7.6.3
        **GPU model:** GeForce GTX 1060

5. **If Python API:**
        Python version: 3.7

**Comment by ujjawalcse** [comment]
I'm also facing same problem. Have you got any solution @JakeMalis @gineshidalgo99 @dtandrade ?
**Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   CUDA              :   Yes (ver. 10.1)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_75
--   cuDNN             :   Yes (ver. 7.6.5)
--** 
-- Install:
--   Install path      :   /home/wowexp/ujjawal/smplify-x-master/openpose/build/caffe
-- 
**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /home/wowexp/ujjawal/smplify-x-master/openpose/3rdparty/caffe/src/caffe**

-- Configuring incomplete, errors occurred!
See also "/home/wowexp/ujjawal/smplify-x-master/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/wowexp/ujjawal/smplify-x-master/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:105: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JakeMalis** [comment]
I'm still having the same issue

**Comment by bhavesh2799** [comment]
> Please, follow the doc/installation.md and in particular the prerequisites section.
> 
> As it is indicated in there, CMake version 3.10.2 (the default one for Ubuntu 18) is not compatible with the CUDA script of Caffe. Install a newer CMake (>=3.12) as the documentation indicates.
> 
> Versions 3.08 to 3.11 gives the following error:
> 
> ```
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> CUDA_cublas_device_LIBRARY (ADVANCED)
>    linked by target "caffe" in directory /home/jakebmalis/Documents/openpose/3rdparty/caffe/src/caffe
> ```

I tried with cmake 3.19, it is giving the same error

**Comment by MSKTHU** [comment]
I had the same issue. After changing to cmake 3.20, the error is gone.

**Comment by philipjhc** [comment]
I've already solved this issue ,thank you

**Comment by gaitanignacio** [comment]
Also facing this issue @philipjhc how did you solve it?

**Comment by xin-Dream** [comment]
I have the same problem, but I have solved it.
First, I changed the version of cmake（cmake==3.17）

**Comment by mziyuu** [comment]
I have the same error and update my cmake to 3.27.4 solves the problem!
