### ISSUE TITLE
Command "--hand_alpha_pose 1" does nothing at all

### ISSUE THREAD

**Issue by AndroXD** [CMU-Perceptual-Computing-Lab/openpose#1115]
I'm using OpenPose v1.4.0 Win64 GPU binaries to output the skeleton in solid colors (no transparency) and black background using this command:

bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand --alpha_pose 1 --face_alpha_pose 1 --hand_alpha_pose 1 --hand_tracking --disable_blending --write_images C:\openpose\frames

Everything shows correctly except the hands, they're the only elements that have transparency applied to them, whatever value I apply to --hand_alpha_pose 1 doesn't change anything at all, am I doing anything wrong?
Any help is much appreciated, thanks!

**Comment by AndroXD** [comment]
I have compiled from source the latest commit but the problem it's still there, is there any way to fix this problem?

**Comment by gineshidalgo99** [comment]
It seems like it has been broken since day 0 but noone reported it earlier. My apologies. Fixed in the latest commit!
