### ISSUE TITLE
Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file

### ISSUE THREAD

**Issue by wardenjohn** [CMU-Perceptual-Computing-Lab/openpose#1116]
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0304 22:21:56.302070  8548 upgrade_proto.cpp:95] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: E:\graduate_design\pose_lib\models\hand/pose_iter_102000.caffemodel
*** Check failure stack trace: ***

Process finished with exit code -1073740791 (0xC0000409)

I feel strange that it can do well if I run Openpose without other function . But now I need hand estimation function only to find this problem .

Can anyone tell me how to fix it?

**Comment by gineshidalgo99** [comment]
Either you did not download it (check if E:\graduate_design\pose_lib\models\hand/pose_iter_102000.caffemodel exists), either the file is corrupted. If the file is there, manually remove it and re-download it (links in the doc/installation.md steps). Let me know if that solves it! Best
