### ISSUE TITLE
Ubuntu Cmake-GUI

### ISSUE THREAD

**Issue by bowrian** [CMU-Perceptual-Computing-Lab/openpose#1118]
Hello,when I use the cmake-gui to configure the openpose, but after executed the codes, the following problems has occured: 

The C compiler identification is GNU 5.4.0
The CXX compiler identification is GNU 5.4.0
Check for working C compiler: /usr/bin/cc
Check for working C compiler: /usr/bin/cc -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /usr/bin/c++
Check for working CXX compiler: /usr/bin/c++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
GCC detected, adding compile flags
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - not found
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - found
Found Threads: TRUE  
Found CUDA: /usr/local/cuda (found version "8.0") 
Building with CUDA.
CUDA detected: 8.0
Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
Added CUDA NVCC flags for: sm_35
Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
Found GFlags: /usr/include  
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found Glog: /usr/include  
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
OpenCV ARCH: 
OpenCV RUNTIME: 
OpenCV STATIC: OFF
CMake Warning at /home/peng/opencv-3.1.0/cmake/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:352 (find_package)

CMake Warning at CMakeLists.txt:352 (find_package):
  Found package configuration file:

    /home/peng/opencv-3.1.0/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

CMake Error at CMakeLists.txt:434 (message):
  OpenCV not found.  Install OpenCV from the command line using the
  command(s) -- sudo apt-get install libopencv-dev

Configuring incomplete, errors occurred!
See also "/home/peng/st-gcn/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/peng/st-gcn/openpose/build/CMakeFiles/CMakeError.log".

Could you please tell me how I can solve this problem, thanks!
@loretoparisi @ps2 @jimfcarroll @vrichter

**Comment by vrichter** [comment]
> Found OpenCV Windows Pack but it has no binaries compatible with your
configuration.

Looks like a problem with your OpenCV.

How did you build/install OpenCV?

**Comment by bowrian** [comment]
> > Found OpenCV Windows Pack but it has no binaries compatible with your
> > configuration.
> 
> Looks like a problem with your OpenCV.
> 
> How did you build/install OpenCV?

I use this command : `cmake -DOpenCV_DIR="/home/peng/opencv-3.1.0/build" `to  solve this problem,but ,when I executed the `make -j`nproc` `, the following problem has occured in terminal:
 `make[2]: *** No rule to make target '/home/peng/opencv-3.1.0/lib/libopencv_videostab.so.3.1.0', needed by 'src/openpose/libopenpose.so.1.3.0'。 停止。
make[2]: *** 正在等待未完成的任务....
[ 78%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/renderFace.cpp.o
CMakeFiles/Makefile2:216: recipe for target 'src/openpose/CMakeFiles/openpose.dir/all' failed
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
Do you know why?

**Comment by hvoigt** [comment]
@bowrian why are you mentioning me? I am not involved with you trying to compile stuff...
