### ISSUE TITLE
how to get time points

### ISSUE THREAD

**Issue by harshitAgr** [CMU-Perceptual-Computing-Lab/openpose#112]
### Issue summary

I get JSON output files  for a face video. The number of JSON files is less than number of frames. How to get the information of timestamps when each JSON file is made?

### Type of issue

- Question

**Comment by gineshidalgo99** [comment]
Thank you for pointing it out. I'll see how to add information about the frame number on the output files and let you know.

Meanwhile, this usually happen when the video have some codec not fully supported by OpenCV. Changing the video to basic *.avi should work to fix your problem.

Thanks

**Comment by gineshidalgo99** [comment]
Actually, I have just realized OpenPose includes the frame number in the name of the generated JSON. To get the timestamp, you just need to multiply the video framerate by the current frame. Let me know if this solves your issues.

**Comment by harshitAgr** [comment]
Hi,
Yes it gives output as per number of frames. With .avi format it works fine. Thanks
