### ISSUE TITLE
Projects not supported in Visual studio 15 community

### ISSUE THREAD

**Issue by arbibz001** [CMU-Perceptual-Computing-Lab/openpose#1120]
Hi,

When i succeed to build in cmake and i try to open the project in Visual studio 15 community to build. I get an error that the project is not compatible?

See message below:

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.

I would like to know if others experience this issue and if there is already a solution for this?

Regards,

**Comment by gineshidalgo99** [comment]
I have never seen that error. Actually, when you click on configure in CMake, the first question it asks you is for which version of VS you want to compile it.

**Comment by arbibz001** [comment]
> I have never seen that error. Actually, when you click on configure in CMake, the first question it asks you is for which version of VS you want to compile it.

I selected visual studio 14 2015 and x64 which is visual studio 2015 right?

**Comment by gineshidalgo99** [comment]
I believe so yes, but I have never tried community version so I cannot tell the differences. In the doc, we only officially support VS 2015 Enterprise (the one we internally have), I cannot even download 15 Community anymore, so I am afraid I cannot help much more here, this is not an OpenPose issue but rather CMake and/or VS issue. Please, any other feel free to help him, but I must close this to prioritize purely OpenPose-related issues.

**Comment by IThoughtUGNU** [comment]
I'd like to point out that [this stackoverflow answer](https://stackoverflow.com/a/44290942) actually has **official** Visual Studio 2015 download links. (Microsoft is kind of slow to kill off its links sometimes)

The product can then be used in trial or properly activated if you have a legitimate serial key.
