### ISSUE TITLE
CMU-Perceptual-Computing-Lab / openpose - How can I get pose coordinates?

### ISSUE THREAD

**Issue by JuanPablovas89** [CMU-Perceptual-Computing-Lab/openpose#1121]
Hi. I'm using CMU-Perceptual-Computing-Lab openpose, I can detect the pose of people using the webcam. However, I need to obtain the pose coordinates from a set of images. Any advice?

**Comment by gineshidalgo99** [comment]
Please read the doc before posting such a questions.
