### ISSUE TITLE
the python API   7_hand_from_image.py  not work well sometimes. Give me some suggestions.Thx

### ISSUE THREAD

**Issue by lilyswang** [CMU-Perceptual-Computing-Lab/openpose#1122]
When I try the python API the python API   7_hand_from_image.py .I find that sometimes, it works well like follows.  However ,sometimes,it cannot detect the joints of hand.(I have gave an appropriate rectangle of hand in a image )  Could you give me some suggestions about this, thanks a lot.(How can I get a good 
 result by using this API )

some image works well:
![选区_164](https://user-images.githubusercontent.com/30424943/54069110-1adda280-428f-11e9-9cae-db3b13fdd2c1.png)
![选区_162](https://user-images.githubusercontent.com/30424943/54069116-26c96480-428f-11e9-9bc8-cd9d2996f4d1.png)
some image can not detect well( ** in spite of providing the right hand margin**):.

![选区_161](https://user-images.githubusercontent.com/30424943/54069141-7314a480-428f-11e9-9026-1432d828eac3.png)
![选区_160](https://user-images.githubusercontent.com/30424943/54069142-7740c200-428f-11e9-84c8-e1af7723dc3d.png)
![选区_159](https://user-images.githubusercontent.com/30424943/54069143-790a8580-428f-11e9-8217-a5d31a05a2ed.png)
![选区_156](https://user-images.githubusercontent.com/30424943/54069145-80319380-428f-11e9-9904-cad25f2d1080.png)
![选区_165](https://user-images.githubusercontent.com/30424943/54069147-86c00b00-428f-11e9-8195-f5da430adfa1.png)

Hope your suggestions for this, all the best.

**Comment by gineshidalgo99** [comment]
For maximum accuracy, the picture should have only the hand and a 10-20% margin. Some of your pictures are cutting part of the hand or are taking much more area than only the hand.

Secondly, do not expect the same amazing quality from the hand detector than the one from the body and face detectors (given the greater amount of data  available for those). For hand there are so few datasets that it is much harder to get a detecter with similar quality to body and face.
