### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by Tame7790** [CMU-Perceptual-Computing-Lab/openpose#1125]
![image](https://user-images.githubusercontent.com/43593936/54185937-275b3880-44e5-11e9-88f1-8bbf1ac6ab91.png)
I have some problems about it. I have enabled build python and successfully run the Python API tutorials,  but I can't run the pyopenpose.py. When I make pyopenpose in VS15, it tells me, pyopenpose.cp36-win_amd64 isn't a effective win32 program

**Comment by arbibz001** [comment]
Same issue here. Enabled build python as well in Cmake

**Comment by soulslicer** [comment]
Can you do the following checks:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md#common-issues
