### ISSUE TITLE
Could NOT find HDF5 (missing: HL

### ISSUE THREAD

**Issue by fzy308658** [CMU-Perceptual-Computing-Lab/openpose#1128]
Issue Summary

When I build openpose, I always have the problem
"-- Could NOT find Glog (missing:  GLOG_LIBRARY) 
-- Found PROTOBUF Compiler: /home/fengziyuan/anaconda3/bin/protoc
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES) (found version "1.10.2")
", 
even though I have install HDF5 lib in /usr/local/hdf5, and in /usr/local/lib also have HDF5.
Type of Issue

1.You might select multiple topics, delete the rest:

    Compilation/installation error
    Help wanted

2.Your System Configuration

    OpenPose version: Latest GitHub code

    General configuration:
        Installation mode: CMake, sh script, manual Makefile installation, ... (Ubuntu)
        Operating system: Ubuntu 16.04
        Release or Debug mode:
        Compiler: 4.8.5

   3. Non-default settings:
    None

    4.3rd-party software:
        Caffe version: 1.0.0
        CMake version: 3.6.
        OpenCV version: 3.0.0

    5.If GPU mode issue:
        CUDA version : 8.0
        cuDNN version: 6.0.21
        GPU model : Yes

**Comment by gineshidalgo99** [comment]
Try to install Caffe by yourself first, following its official doc. After you have installed Caffe, OpenPose should install just fine.

**Comment by johndpope** [comment]
so I followed all the cmake-gui steps 

N.B. - in my opinion the DO NOT USE anaconda stuff seems unwarranted.
(Im yet to build successfully though - so this may bite me later on. )
For ubuntu the protobuf-compiler is at v 3.0.0 / and had to rip out  protobuf-compiler using apt-get remove to get configure to work


With the  above hdf5 problem I solved using miniconda 
 **conda install -c anaconda hdf5**
but running into more errors - will persevere with conda and see if I can fix - if so will post update here.


```shell
make -j`nproc`
[ 12%] Performing configure step for 'openpose_lib'
CMake Warning (dev) at cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.8.0") 
-- Found PROTOBUF Compiler: /home/jp/miniconda3/bin/protoc
CMake Error at /home/jp/Downloads/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS
  HDF5_HL_LIBRARIES HL) (found version "")
Call Stack (most recent call first):
  /home/jp/Downloads/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/jp/Downloads/cmake-3.14.5/Modules/FindHDF5.cmake:928 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:46 (find_package)
  CMakeLists.txt:49 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jp/Documents/gitWorkspcae/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/jp/Documents/gitWorkspcae/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:106: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
(base) ➜  build git:(master) ✗ 
(base) ➜  build git:(master) ✗ 
(base) ➜  build git:(master) ✗ 
(base) ➜  build git:(master) ✗ conda install -c anaconda hdf5
```
 for 'openpose_lib'
CMake Warning (dev) at cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /home/jp/miniconda3/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
**-- Found HDF5:** /home/jp/miniconda3/lib/libhdf5_cpp.so;/home/jp/miniconda3/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/home/jp/miniconda3/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.4") found components:  HL 
-- CUDA detected: 9.1
-- Added CUDA NVCC flags for: sm_50
CMake Error at /home/jp/Downloads/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Atlas (missing: Atlas_CBLAS_INCLUDE_DIR
  Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY
  Atlas_LAPACK_LIBRARY)
Call Stack (most recent call first):
  /home/jp/Downloads/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindAtlas.cmake:43 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:121 (find_package)
  CMakeLists.txt:49 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jp/Documents/gitWorkspcae/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/jp/Documents/gitWorkspcae/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:106: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aryamanpandya** [comment]
Were you able to resolve the issue? I'm stuck at the same step
