### ISSUE TITLE
F0313 19:28:14.686606 26764 upgrade_proto.cpp:97], Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel

### ISSUE THREAD

**Issue by salihkaragoz** [CMU-Perceptual-Computing-Lab/openpose#1129]
### Executed Command (if any)
./build/examples/openpose/openpose.bin -video examples/media/video.avi 

### OpenPose Output (if any)

./build/examples/openpose/openpose.bin -video examples/media/video.avi 
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
**F0313 19:12:09.793649 19300 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel**
*** Check failure stack trace: ***
**F0313 19:12:09.793649 19299 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel**
*** Check failure stack trace: ***
    @     0x7fe0806eb5cd  google::LogMessage::Fail()
    @     0x7fe0806eb5cd  google::LogMessage::Fail()
    @     0x7fe0806ed433  google::LogMessage::SendToLog()
    @     0x7fe0806ed433  google::LogMessage::SendToLog()
    @     0x7fe0806eb15b  google::LogMessage::Flush()
    @     0x7fe0806eb15b  google::LogMessage::Flush()
    @     0x7fe0806ede1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe0806ede1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe0800c1e41  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fe0800c1e41  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fe08024413a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fe08024413a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fe081cbc117  op::NetCaffe::initializationOnThread()
    @     0x7fe081cbc117  op::NetCaffe::initializationOnThread()
    @     0x7fe081cd516e  op::addCaffeNetOnThread()
    @     0x7fe081cd516e  op::addCaffeNetOnThread()
    @     0x7fe081cd63b2  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fe081cd63b2  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fe081cdade0  op::PoseExtractorNet::initializationOnThread()
    @     0x7fe081cdade0  op::PoseExtractorNet::initializationOnThread()
    @     0x7fe081cd1e61  op::PoseExtractor::initializationOnThread()
    @     0x7fe081cd1e61  op::PoseExtractor::initializationOnThread()
    @     0x7fe081ccd1b1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fe081ccd1b1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fe081cee091  op::Worker<>::initializationOnThreadNoException()
    @     0x7fe081cee091  op::Worker<>::initializationOnThreadNoException()
    @     0x7fe081cee1d0  op::SubThread<>::initializationOnThread()
    @     0x7fe081cee1d0  op::SubThread<>::initializationOnThread()
    @     0x7fe081cf0fd8  op::Thread<>::initializationOnThread()
    @     0x7fe081cf0fd8  op::Thread<>::initializationOnThread()
    @     0x7fe081cf11dd  op::Thread<>::threadFunction()
    @     0x7fe081cf11dd  op::Thread<>::threadFunction()
    @     0x7fe0815d0c80  (unknown)
    @     0x7fe0815d0c80  (unknown)
    @     0x7fe080d226ba  start_thread
    @     0x7fe080d226ba  start_thread
    @     0x7fe08103f41d  clone
    @     0x7fe08103f41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**-----------------------------------------------------------------------------------------**

I installed caffe correctly, tested works.
GPU: 1080ti x 2
Driver: 384.130
Cuda: 8.0
Cudnn: 5.1
protoc --version: 3.2.0

then mkdir build, cd build
cmake ..
make -j`nproc`

It finished, no error. But when i try to test openpose I got the above errors.

./build/examples/openpose/openpose.bin -video examples/media/video.avi 

Thanks for your interest.

**Comment by shutingh** [comment]
I've met this before.
check the size of model, it may not be fully downloaded.

**Comment by gineshidalgo99** [comment]
Many duplicates of this issue.

**Comment by ZZQQLucky** [comment]
May I ask how you solved it? I don't think the solutions on the forum work
