### ISSUE TITLE
Smaller models

### ISSUE THREAD

**Issue by mxmxlwlw** [CMU-Perceptual-Computing-Lab/openpose#113]
Hi,
     I hope to get smaller models. Can you provide training codes? Or can you give me some new models? Especially those with small numbers of layers. I mean those basic conv layers which extract the foundational features. eg: conv1_1, conv1_2....
     It seems they are greatly affect the speed of the network.

**Comment by gineshidalgo99** [comment]
https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
