### ISSUE TITLE
CAR_12 | Experimental. Do not use. 汽车的模型可否开放出来

### ISSUE THREAD

**Issue by zyxcambridge** [CMU-Perceptual-Computing-Lab/openpose#1130]
CAR_12 | Experimental. Do not use.

BODY_19 | Experimental. Do not use.
-- | --
BODY_19_X2 | Experimental. Do not use.
BODY_19N | Experimental. Do not use.
BODY_25E | Experimental. Do not use.
BODY_65 | Experimental. Do not use.
CAR_12 | Experimental. Do not use.
BODY_25D | Experimental. Do not use.
BODY_23 | Experimental. Do not use.
CAR_22 | Experimental. Do not use.
BODY_19E | Experimental. Do not use.
BODY_25B | Experimental. Do not use.
BODY_95 | Experimental. Do not use.

**Comment by gineshidalgo99** [comment]
Those are ongoing research models, that is why they are not available. The accuracy is not good enough to be used yet.

**Comment by yuzzfeng** [comment]
I am wondering, will the car keypoint be released in future monthes?

**Comment by gineshidalgo99** [comment]
No, it never really worked, OpenPose-style approach would require more data than the dataset we tried.

**Comment by yuzzfeng** [comment]
> No, it never really worked, OpenPose-style approach would require more data than the dataset we tried.

Thank you for this quick response.
