### ISSUE TITLE
Python API not working on Windows 10

### ISSUE THREAD

**Issue by arbibz001** [CMU-Perceptual-Computing-Lab/openpose#1131]
Hi,

I am not able to run the python tutorial files on my windows.

I get the following error: "Did you enable BUILD PYTHON in cmake", even though i did enable the python build.

Furthermore, i am not sure if the python build went well as I only have the following in build\python\openpose
- Folder cmakefiles
- __init__.py
- cmake_install.cmake
- pyopenpose.vcxproj
- pyopenpose.vcxproj.filters

Please help me as i want to start a project in Python using the OpenPose library.

Kind regards,

**Comment by arbibz001** [comment]
Resolved the issue myself by rebuilding only the pyopenpose project with visual studio 2017 community and cuda 10.1 and cudnn 7.5

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back!
