### ISSUE TITLE
Origin point of pose_keypoints_2d in output json file ?

### ISSUE THREAD

**Issue by canaltinigne** [CMU-Perceptual-Computing-Lab/openpose#1132]
In the output.json file, we can see the location of keypoints in an array in the format of x1,y1,c1,x2,y2,c2,....

I was wondering, where is the origin point of x and y-axis ? Because I need to pad my images in accordance with the origin point not to lose the exact positions of keypoints.

**Comment by gineshidalgo99** [comment]
The origin is the image x-y origin (i.e., the top-left part of the image). Let me know if I am not clear enough or if you need more info. Best

**Comment by heet2201** [comment]
If the origin is at top-left then, shouldn't all the Y-coordinates be negative in an image, rather it all are positive as I have observed ?
