### ISSUE TITLE
[CPU version] Examples do not work as-is

### ISSUE THREAD

**Issue by thomasfaingnaert** [CMU-Perceptual-Computing-Lab/openpose#1134]
### Issue Summary
As discussed in https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/1133#issuecomment-473470581, the examples (e.g. 01_body_from_image_default.cpp) do not work in CPU mode without adding this snippet:
```cpp
op::WrapperStructPose wrapperStructPose{};
wrapperStructPose.renderMode = op::RenderMode::Cpu;
opWrapper.configure(wrapperStructPose);

op::WrapperStructFace wrapperStructFace{};
wrapperStructFace.renderMode = op::RenderMode::Cpu;
opWrapper.configure(wrapperStructFace);

op::WrapperStructHand wrapperStructHand{};
wrapperStructHand.renderMode = op::RenderMode::Cpu;
opWrapper.configure(wrapperStructHand);
```

### Errors (if snippet is omitted)
```
Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread:
OpenPose must be compiled with the `USE_CUDA` macro definitions in order to run this functionality. You can alternatively use CPU rendering (flag `--render_pose 1`).
```

A rundown of how this issue occurs is as follows:
- By default, the wrapper's structs have `RenderMode = Gpu`:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/c1cbe3a100662e42bab0593987de84ce8869873a/include/openpose/wrapper/wrapperStructPose.hpp#L216
- Thus, `renderOutputGpu` is `true`: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/c1cbe3a100662e42bab0593987de84ce8869873a/include/openpose/wrapper/wrapperAuxiliary.hpp#L130
- As a result, https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/c1cbe3a100662e42bab0593987de84ce8869873a/include/openpose/wrapper/wrapperAuxiliary.hpp#L285-L295 adds `PoseGpuRenderer`s
- Eventually, `renderPose` is called on these `PoseGpuRenderer`s: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/c1cbe3a100662e42bab0593987de84ce8869873a/include/openpose/pose/wPoseRenderer.hpp#L74-L76
- `PoseGpuRenderer::renderPose` finally prints the aforementioned error at https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/c1cbe3a100662e42bab0593987de84ce8869873a/src/openpose/pose/poseGpuRenderer.cpp#L184-L186

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output**: https://pastebin.com/sz4BxzVX

2. **OpenPose version**: `master` (at the time of writing c1cbe3a100662e42bab0593987de84ce8869873a)

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Windows
    - **Operating system version**: Windows 10 x64
    - **Release or Debug mode**: Release
    - **Compiler**: Visual Studio Community 2017

4. **Non-default settings**:
    - **3-D Reconstruction module added**: No
    - Any other custom CMake configuration with respect to the default version: `-DGPU_MODE=CPU_ONLY`

5. **3rd-party software**:
    - **Caffe version**: default
    - **CMake version**: 3.13.4
    - **OpenCV version**: default

6. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel i7-6500U
    - Total **RAM memory** available: 8 GiB

9. If **Windows** system: self compiled version

**Comment by gineshidalgo99** [comment]
Fixed in latest OpenPose. See #1135 last comment for details. Thanks!
