### ISSUE TITLE
Prerequisites | Cuda 10.0 & cuDNN 7.2 Combination Isn't Available

### ISSUE THREAD

**Issue by zanfranceschi** [CMU-Perceptual-Computing-Lab/openpose#1137]
The prerequisites to build openpose say cuda 10.0 should go with cudnn 7.2 but there isn't such combination. At least, not as of today. Not sure if it's been removed from nvidia archives.

On Ubuntu 16.04 I got to compile openpose ok with 10.0 / 7.5 (and 7.4) but got erros on runtime. I'm gonna try different combinations as there are many people saying it's a cudnn version issue. On Ubunt 18.04 I got openpose working properly with cuda 10.1 and cuDNN 7.5.

Please, note that I'm not asking for help here. Just saying that maybe the prerequisites doc could be updated.

**Comment by gineshidalgo99** [comment]
Where does it say 7.2? I believe it says CUDA 10 / cuDNN 7.5 (which is what I have on my PC).

**Comment by zanfranceschi** [comment]
doc/prerequisites.md: line 38:

1. **Note: OpenPose has been tested extensively with CUDA 8.0 (cuDNN 5.1) and CUDA 10.0 (cuDNN 7.2)

**Comment by gineshidalgo99** [comment]
Typo fixed for my next commit, thanks! Please, use 7.5 as you realized. About errors on runtime, that's usually when messing up cuDNN with CUDA and/or the Nvidia drivers.

**Comment by zanfranceschi** [comment]
Thanks! :)

**Comment by rafuck** [comment]
Dockerfile for last openpose:
https://gist.github.com/rafuck/adf55ba1e61571c85df5b4299da035ca
To authors. Is it possible to provide minimal Dockerfile in your "scrips" directory or somewhere else?

**Comment by gineshidalgo99** [comment]
Closing this as it is solved.

@rafuck Sorry, I am not very familiar with Dockerfiles, that is why we have not added any. If you do a PR with them, I can definitely take a look and try to merge it!
