### ISSUE TITLE
Outputs a photo rather than a video frame

### ISSUE THREAD

**Issue by jamesponwith** [CMU-Perceptual-Computing-Lab/openpose#1138]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary

I am attempting to use the quickstart options to use the webcam or a recorded video to display a video output. However, the only output I receive is a photo frame. 

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

./build/examples/openpose/openpose.bin --video ~/video_James.webm
&&
./build/examples/openpose/openpose.bin --face --hand

### OpenPose Output (if any)

Outputs a window frame with a pose skeleton on my person but instead of a video it is simply the first frame of the video. 

### Errors (if any)

No errors

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted

I am seeking the video example at the bottom of the quickstart page. I am trying to get real time pose estimation using a video but can only receive a photo frame.

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

james@james-iMac:~/workspace/SeniorProject/openpose$ uname -a
Linux james-iMac 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

          description: CPU
          product: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
          vendor: Intel Corp.
          physical id: 22
          bus info: cpu@0
          version: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 3163MHz
          capacity: 4200MHz
          width: 64 bits
          clock: 25MHz

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

Cloned on March 8th. 

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**: 

iMac 2017 running Ubuntu 18.04 

    - Total **RAM memory** available: 

16 GB

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
Please, finish the video path in *.avi format, as the documentation suggests. OpenCV seems to only admit *.avi format when saving output video. Thanks! (Let me know if that does not work)

```
./build/examples/openpose/openpose.bin --video ~/video_James.avi
```
