### ISSUE TITLE
Starting OpenPose Python Wrapper... ERROR: unknown command line flag 'body_disable'

### ISSUE THREAD

**Issue by QuentinBoul** [CMU-Perceptual-Computing-Lab/openpose#1139]
Hi!

I have the following errors when running the example: 07_hand_from_image.py:

Starting OpenPose Python Wrapper...
ERROR: unknown command line flag 'body_disable'

What should I do?

Best regards,

**Comment by QuentinBoul** [comment]
Hi!

 I fixed this problem by replacing  

> params["body_disable"] = True

by 

> params["body"]= 0

I guess it's an error in the example...

I hope it will help someone...

**Comment by gineshidalgo99** [comment]
Thanks! I will fix that typo in the next commit!
