### ISSUE TITLE
How to save proccessed video 

### ISSUE THREAD

**Issue by blmhds** [CMU-Perceptual-Computing-Lab/openpose#1140]
I have tried to  save proccessed images in a pointed director,but I cant save proccessed videos,if anyone can help me,thanks!

**Comment by FrancescoRossi1987** [comment]
you have to add:
--write_video /path/to/file/file.avi

**Comment by gineshidalgo99** [comment]
If write_video does not work is because the path is wrong, you are not finishing the file in avi format, or it is being saved in a read-only location. Thanks.
