### ISSUE TITLE
Link broken in calibration_module.md

### ISSUE THREAD

**Issue by tompollok** [CMU-Perceptual-Computing-Lab/openpose#1142]
Link broken in
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/calibration_module.md

In section "Installing the Calibration Module" the following link doesnt work

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/installation.md#calibration-module

**Comment by mikelassi** [comment]
Hey,
this should be the correct link:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#calibration-module

**Comment by tompollok** [comment]
Thanks

**Comment by gineshidalgo99** [comment]
Thanks @mikelassi ! Fixed in the latest commit. Best
