### ISSUE TITLE
"sudo make install" does not install python api ubuntu 1604

### ISSUE THREAD

**Issue by benjaminabruzzo** [CMU-Perceptual-Computing-Lab/openpose#1143]
### Issue Summary
I am trying to use the openpose library/api in conjunction with another python project.  The tutorials fail @:
"from openpose import pyopenpose as op" :  "ImportError: cannot import name pyopenpose"

### Executed Command (if any)

> cd path/to/openpose/examples/tutorial_api_python
> python 01_body_from_image.py 

### Errors (if any)

> Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
> Traceback (most recent call last):
>   File "01_body_from_image.py", line 26, in <module>
>     raise e
> ImportError: cannot import name pyopenpose

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error

### Your System Configuration
1. **Whole console output** 

> benjamin@helios0:~/CMU/openpose/examples/tutorial_api_python$ python 01_body_from_image.py 
> Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
> Traceback (most recent call last):
>   File "01_body_from_image.py", line 26, in <module>
>     raise e

2. **OpenPose version**: Latest GitHub code

> benjamin@helios0:~/CMU/openpose$ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.

3. **General configuration**:
    - **Installation mode**: cmake .. / cmake-gui / make
    - **Operating system** / **Operating system version**

> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.6 LTS
> Release:	16.04
> Codename:	xenial

    - **Release or Debug mode**? (by default: release):
    - Compiler : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: cmake version 3.5.1
    - **OpenCV version**: from git (git@github.com:opencv/opencv.git) version 3.4.5

6. If **GPU mode** issue:
    - **CUDA version** : CUDA Version 10.0.130
    - **cuDNN version**: ver. 7.4.2
    - **GPU model** 

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Quadro M2000        Off  | 00000000:01:00.0  On |                  N/A |
> | 56%   43C    P0    23W /  75W |    424MiB /  4040MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1416      G   /usr/lib/xorg/Xorg                           157MiB |
> |    0      2340      G   /usr/bin/gnome-shell                         183MiB |
> |    0      2829      G   ...quest-channel-token=2568188631222331943    78MiB |
> +-----------------------------------------------------------------------------+

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: Python 2.7.12 (
    - **Numpy version**: 1.15.4

**Comment by soulslicer** [comment]
Youre right. For some reason this line is commented out

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/python/openpose/CMakeLists.txt#L12

I will try to see if i can get it fixed

**Comment by benjaminabruzzo** [comment]
Okay, great.  I was about to add my build logs:

cmake: https://pastebin.com/MFpcncYh

make: https://pastebin.com/VVLxy8Zk

**Comment by soulslicer** [comment]
ive made a PR. it should be merged by later today.

**Comment by gineshidalgo99** [comment]
PR merged

**Comment by benjaminabruzzo** [comment]
Unfortunately, while tinkering I broke my cuda installation.  However, I had already tried un-commenting those lines yesterday, to no avail.

I'm going to try on a clean installation of 18.04

**Comment by soulslicer** [comment]
i just tested it, it works.

**Comment by benjaminabruzzo** [comment]
Hmm.  Then I have some other issue that is not throwing an error.

Hopefully the clean install will flush something out.

**Comment by benjaminabruzzo** [comment]
Just finished clean install of 16.04, still no python functionality.

make log: https://pastebin.com/0R0pbh2F
cmake log: https://pastebin.com/W9Z5pYuu

I also see that this file is created: /home/benjamin/CMU/openpose/build/python/openpose/pyopenpose.cpython-35m-x86_64-linux-gnu.so

but the best I can get it the following error:
benjamin@titan:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
>>> import openpose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benjamin/CMU/openpose/python/openpose/__init__.py", line 1, in <module>
    from . import pyopenpose as pyopenpose
ImportError: cannot import name pyopenpose

```

**Comment by soulslicer** [comment]
Please take a look at the examples. You need to add it to your syspath. 

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/01_body_from_image.py#L22

**Comment by benjaminabruzzo** [comment]
I just wiped and started on a clean system. I just successfully had openpose import to python 3.5 by following the commands outlined here:

https://github.com/benjaminabruzzo/pipelineOpenPose

**Comment by soulslicer** [comment]
There is no need for additional scripts. It already works out of the box with the instructions clearly outlined in the `python_module` part of the documentation

**Comment by antonialq** [comment]
I got this issue too, who can help? I dont know how to generate this file named pyopenpose.cpython-35m-x86_64-linux-gnu.so.
