### ISSUE TITLE
Segfault in op::resizeFixedAspectRatio from op::CvMatToOpInput::format

### ISSUE THREAD

**Issue by lisayan** [CMU-Perceptual-Computing-Lab/openpose#115]
### Issue summary
I was able to run the demo code on my own images successfully and save the pose output. Now, I am trying to do the same thing in my project code going based off of tutorial_pose/1_extract_from_image.cpp.

Using valgrind, I found an issue of invalid read of size 4 at function stated above.

### OpenPose output (if any)
`==13079== Warning: set address range perms: large range [0x1900000000, 0x2200000000) (noaccess)
==13079== Warning: set address range perms: large range [0x400000000, 0x600000000) (noaccess)
==13079== Invalid read of size 4
==13079==    at 0x66DC741: op::resizeFixedAspectRatio(cv::Mat const&, double, op::Point<int> const&, int, cv::Scalar_<double> const&) (in /home/lisayan/catkin_ws/src/acme_ros/depth_people_tracking/openpose/distribute/lib/libopenpose.so.1.0.0-rc3)
==13079==    by 0x666D945: op::CvMatToOpInput::format(cv::Mat const&) const (in /home/lisayan/catkin_ws/src/acme_ros/depth_people_tracking/openpose/distribute/lib/libopenpose.so.1.0.0-rc3)
==13079==    by 0x4E4B975: acme::PeopleDetector::DetectPose() (in /home/lisayan/catkin_ws/devel/lib/libpeople_detector.so)
==13079==    by 0x407F8F: main::{lambda(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)#1}::operator()(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&) const (in /home/lisayan/catkin_ws/devel/lib/depth_people_tracking/depth_people_tracking)
==13079==    by 0x3BE7CA98: image_transport::RawSubscriber::internalCallback(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&) (in /opt/ros/kinetic/lib/libimage_transport_plugins.so)
==13079==    by 0x5F90BAB: boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const>) (in /opt/ros/kinetic/lib/libimage_transport.so)
==13079==    by 0x3BE84622: ros::SubscriptionCallbackHelperT<boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) (in /opt/ros/kinetic/lib/libimage_transport_plugins.so)
==13079==    by 0x63035DC: ros::SubscriptionQueue::call() (in /opt/ros/kinetic/lib/libroscpp.so)
==13079==    by 0x62ADCEF: ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) (in /opt/ros/kinetic/lib/libroscpp.so)
==13079==    by 0x62AF0F2: ros::CallbackQueue::callAvailable(ros::WallDuration) (in /opt/ros/kinetic/lib/libroscpp.so)
==13079==    by 0x63076A0: ros::SingleThreadedSpinner::spin(ros::CallbackQueue*) (in /opt/ros/kinetic/lib/libroscpp.so)
==13079==    by 0x62EC73A: ros::spin() (in /opt/ros/kinetic/lib/libroscpp.so)
`

### Type of issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your system configuration
**Operating system**: Ubuntu 16.04.2
**CUDA version**: 8.0.61
**cuDNN version**: 5.1
**GPU model**: GeForce 940MX
**Caffe version**: Default from OpenPose
**OpenCV version**: OpenCV 3.1.
Compiler:gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by lisayan** [comment]
Solved this issue by reinstalling openpose and caffe according to manual description, not automatic script

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back!
