### ISSUE TITLE
make file fails

### ISSUE THREAD

**Issue by lehovsepyan** [CMU-Perceptual-Computing-Lab/openpose#1150]
After successfully generating and running make file I get the following errors:

```
MacBook-Pro:build lev$ make
[ 12%] Performing build step for 'openpose_lib'
[  3%] Built target caffeproto
[  3%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/accuracy_layer.cpp.o
/Users/levon.hovsepyan/Desktop/openpose/3rdparty/caffe/src/caffe/layers/accuracy_layer.cpp:101:1: error: out-of-line definition of 'Forward_gpu' does not match any declaration in 'AccuracyLayer<Dtype>'
STUB_GPU(AccuracyLayer);
^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/caffe/util/device_alternate.hpp:14:24: note: expanded from macro 'STUB_GPU'
void classname<Dtype>::Forward_gpu(const vector<Blob<Dtype>*>& bottom, \
                       ^~~~~~~~~~~
/Users/levon.hovsepyan/Desktop/openpose/3rdparty/caffe/src/caffe/layers/accuracy_layer.cpp:101:1: error: out-of-line definition of 'Backward_gpu' does not match any declaration in 'AccuracyLayer<Dtype>'
STUB_GPU(AccuracyLayer);
^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/caffe/util/device_alternate.hpp:17:24: note: expanded from macro 'STUB_GPU'
void classname<Dtype>::Backward_gpu(const vector<Blob<Dtype>*>& top, \
                       ^~~~~~~~~~~~
2 errors generated.
make[5]: *** [src/caffe/CMakeFiles/caffe.dir/layers/accuracy_layer.cpp.o] Error 1
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2
MacBook-Pro:build lev$
```

*all prerequisites are installed

I try on MacOS Mojave, and my macbook does not have a GPU

**Comment by sy1vain** [comment]
How (if) did you solve this? I am possibly running into the same issue.

**Comment by lehovsepyan** [comment]
@sy1vain the issue was related to caffe. I was cloning it to `3rdparty` from 
```git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git```. 

Try to use to install caffe this way, it helped me to solve the issue:

```git submodule update --init --recursive --remote```

**Comment by Herusyahputra** [comment]
hello everybody
I fin this problem, I have been trying but can't be solved
 
make[2]: *** [src/brisk/thirdparty/agast/CMakeFiles/agast.dir/build.make:102: src/brisk/thirdparty/agast/CMakeFiles/agast.dir/src/agast7_12d.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:701: src/brisk/thirdparty/agast/CMakeFiles/agast.dir/all] Error 2
make[2]: *** [src/npoint/CMakeFiles/camodocal_fivepoint.dir/build.make:63: src/npoint/CMakeFiles/camodocal_fivepoint.dir/five-point/five-point.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1150: src/npoint/CMakeFiles/camodocal_fivepoint.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
