### ISSUE TITLE
how to customize the path of building python api

### ISSUE THREAD

**Issue by LU-K-Brant** [CMU-Perceptual-Computing-Lab/openpose#1151]
hi,i have some problem when i was building python api.
![`8 K BHHB77IJTK{(29MR@Q](https://user-images.githubusercontent.com/42348398/54734419-41c69d80-4bda-11e9-8f7e-0192a2d868a2.png)
 I don't have root access，so how to customize the path of installing openpose and pthon api

**Comment by shutingh** [comment]
maybe change a directory.
/usr/local/ needs permission which might cause trouble.

**Comment by soulslicer** [comment]
https://stackoverflow.com/questions/6003374/what-is-cmake-equivalent-of-configure-prefix-dir-make-all-install

**Comment by StrongRay** [comment]
Alternatively, Look for pyopenpose.so which is generated, note the pathname and then check your environment (env) for LD_LIBRARY_PATH variable and append the directory name to the LD_LIBRARY_PATH variable.  I think this method will work as well.

**Comment by LU-K-Brant** [comment]
> https://stackoverflow.com/questions/6003374/what-is-cmake-equivalent-of-configure-prefix-dir-make-all-install

thanks，it works.
