### ISSUE TITLE
Race condition in 'get/set' logModes

### ISSUE THREAD

**Issue by aaron-michaux** [CMU-Perceptual-Computing-Lab/openpose#1152]
### Issue Summary

Look at `openpose/utilities/errorAndLog.cpp`, and in particular, these functions at the bottom of the file:

```
        const std::vector<LogMode>& getLogModes()
        {
            const std::lock_guard<std::mutex> lock{sConfigureLogMutex};
            return sLoggingModes;
        }

        void setLogModes(const std::vector<LogMode>& loggingModes)
        {
            const std::lock_guard<std::mutex> lock{sConfigureLogMutex};
            sLoggingModes = loggingModes;
        }
```

Returning by reference in `getLogModes` invalidates the use of the mutex! Just return by value. It's going to be fast enough. If you're really worried about the speed, then get rid of the mutex, and store the std::vector<LogMode> in a std::shared_ptr. getLogModes should return the shared_ptr<const std::vector<LogMode>> by value, so that the callee can take ownership of the memory in case some other thread calls setLogModes.

C/C++ programmers usually use a bitfield approach to storing the log modes. This will be much faster than using vector, or a shared-ptr, and importantly, it is idiomatic.

### Type of Issue
Coding error: Unsafe/invalid use of mutex.

### Your System Configuration
I'm just reading the code directly. This bug affects *all* configurations.

**Comment by gineshidalgo99** [comment]
You are completely right! Fixed in the latest commit!
