### ISSUE TITLE
Can't use "--body_disable"

### ISSUE THREAD

**Issue by hangforever** [CMU-Perceptual-Computing-Lab/openpose#1155]
Hi!

I have the following errors when running the example: 07_hand_from_image.bin:

When I input "./build/examples/tutorial_api_cpp/07_hand_from_image.bin --body_disable --hand --hand_detector 2", it showed me "ERROR: unknown command line flag 'body_disable'". While when I input "./build/examples/tutorial_api_cpp/07_hand_from_image.bin --hand --hand_detector 2", it worked.

What should I do?

Best regards,

**Comment by gineshidalgo99** [comment]
Please, download (or check online) the latest version. It was fixed in there. Sorry for the troubles!
