### ISSUE TITLE
Custom output window size

### ISSUE THREAD

**Issue by lutsetis** [CMU-Perceptual-Computing-Lab/openpose#1156]
Hello there, i want to resize the output im getting from my webcam. I'm using ZED stereo camera and i want to edit code so i can get the output for the 1 camera only. 
As you can see from the image below, i want to edit the width of the output so i can get only the output of the left camera. So i could just simply edit the output width of the window down to half? Which file should i edit?

![Screenshot from 2019-03-22 15-35-15](https://user-images.githubusercontent.com/48829700/54826351-57aa9000-4cb8-11e9-8f9e-5186f8a69358.png)

**Comment by gineshidalgo99** [comment]
Resizing the output image would resize both images, not one. If you want only 1 image, feed OpenPose with 1 image at the time.

**Comment by lutsetis** [comment]
@gineshidalgo99, i found where to change the frame size in order to get only the 1 image. Thing is that i need to know where the imshow() or whichever else function you using in order to show the output window is. Thanks

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back!

**Comment by lutsetis** [comment]
@gineshidalgo99 so, any idea where the output window is generated? :)
