### ISSUE TITLE
Python API: ImportError pyopenpose 

### ISSUE THREAD

**Issue by adildsw** [CMU-Perceptual-Computing-Lab/openpose#1157]
### Issue Summary
I am not able to import openpose even after successful compiling. 
_pyopenpose.cpython-36m-x86_64-linux-gnu.so_ is getting generated in `/usr/local/python/openpose/`, but python does not recognise pyopenpose

### Executed Command
`import openpose`

### Errors
ImportError: cannot import name 'pyopenpose' from 'openpose' 

### Type of Issue
- Execution error

### Your System Configuration
1. **Console Output** 
https://pastebin.com/tfdhHZKK

2. **OpenPose version**: 
Latest commit `fe767a1`

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Ubuntu
    - **Operating system version**: Ubuntu 18.04.2 LTS
    - **Release or Debug mode**: Release
    - **Compiler**: gcc 5.5.0

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.14.0
    - **OpenCV version**: 3.2.0

8. If **Python** API:
    - **Python version**: 3.7.1
    - **Numpy version**: 1.15.4

**Comment by StrongRay** [comment]
I am also on Ubuntu 18.04.  I can suggest you try the following

1.  Issue the command **env | grep LD_LIBRARY_PATH** and check that you have **/usr/local/python/openpose/** as one of the pathname as you have said you generated the .so file to.  This LD_LIBRARY_PATH variable can be added/changed from your **nano ~/.bashrc**

2.  For me, i created a symbolic link **pyopenpose**  so from your usr/local/python/openpose directory, you can issue **ln -s pyopenpose pyopenpose.cpython-36m-x86_64-linux-gnu.so**  Know the difference between logical name "pyopenpose" vs Physical name "pyopenpose.cpython-36m-x86_64-linux-gnu.so", ie. you can call your logical name anything but physical name must be a file that exist.

3.  Next, in your python file that you are trying to execute, you can add the line at the top **import pyopenpose as op**  , then reference any openpose calls using op.xxxxx.  Similarly, you can always do **import pyopenpose as mickeymouse** and it will work in your code. However, long names are prone to errors and cryptic, as it forces the reader to search for the meaning when reading the codes.  So, **op** is a good choice.

Metaphorically, there are "many ways to skin the cat". This is just one of them =)

**Comment by adildsw** [comment]
@StrongRay thanks for replying!

I've been stuck at it for the last 2 days.
I had already followed your comment from https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1027#issuecomment-455127043 where you suggested adding the path to the LD_LIBRARY_PATH variable and creating a symbolic link, both of which I did.

However, when I tried importing **pyopenpose**, it returned:
`ModuleNotFoundError: No module named 'pyopenpose'`

**Comment by StrongRay** [comment]
I just tried this on my ubuntu environment

$ **env | grep LD_L***
LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/python3.6/dist-packages:/usr/local/cuda-9.2/extras/CUPTI/lib64/:usr/local/cuda-9.2/lib64:

$ **ls -al /usr/local/lib/python3.6/dist-packages/pyopen***
lrwxrwxrwx 1 kenghee staff     81 Jan 25 20:48 /usr/local/lib/python3.6/dist-packages/pyopenpose -> /usr/local/lib/python3.6/dist-packages/pyopenpose.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 kenghee staff 291376 Jan 25 20:47 /usr/local/lib/python3.6/dist-packages/pyopenpose.cpython-36m-x86_64-linux-gnu.so

$ **python**
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
**import pyopenpose as op**
**dir(op)**
['Datum', 'Point', 'Rectangle', 'WrapperPython', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'get_gpu_number', 'get_images_on_directory', 'init_argv', 'init_int']

Commands are in **bold**

I can only ask you check your names **very carefully** including the right ":" as UNIX is extremely case sensitive.  You notice that after loading on a python command prompt, I issue a **dir** to see the various commands that I can call upon.  This means that pyopenpose is properly loaded.

**Comment by benjaminabruzzo** [comment]
I am having a similar issue in 16.04: #1143

**Comment by soulslicer** [comment]
It doesnt need to be this complicated

Please take a look at the examples. You need to add it to your syspath. 

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/01_body_from_image.py#L22

If you do `sudo make install`, it will add it to your `/usr/local/python` folder, at which point you can simply add

`sys.path.append('/usr/local/python')`

to your code.

Please look at the debugging section 

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md#common-issues

**Comment by benjaminabruzzo** [comment]
I agree, it shouldn't be this complicated, and yet:

```
benjamin@titan:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import cv2
>>> import os
>>> from sys import platform
>>> import argparse
>>> sys.path.append('/usr/local/python')
>>> sys.path
['', '/home/benjamin', '/usr/local/lib/python2.7/site-packages', '/home/benjamin/CMU/openpose/python', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/benjamin/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/local/python']
>>> from openpose import pyopenpose as op
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benjamin/CMU/openpose/python/openpose/__init__.py", line 1, in <module>
    from . import pyopenpose as pyopenpose
ImportError: cannot import name pyopenpose
>>> 

```

make install log: https://pastebin.com/M549mnup

**Comment by benjaminabruzzo** [comment]
I just wiped and started on a clean system.  I just successfully had openpose import to python 3.5 by following the commands outlined here: 

https://github.com/benjaminabruzzo/pipelineOpenPose

**Comment by soulslicer** [comment]
If you do

`ls /usr/local/python | grep openpose`

do you actually see openpose?

**Comment by benjaminabruzzo** [comment]
I can't tell you now, because I wiped that system.  For me it might have been an installation issue where cmake was assuming something about python3 while I was using python2.7. But that is just speculation, all I can say is that it works now using python3.5

**Comment by soulslicer** [comment]
Right, it looks like you were using Python 2. That was the problem. The instructions clearly state that Openpose selects the latest version of Python, and that if you want to use Python2, you have to specify that as per the instructions

**Comment by all3naby** [comment]
> If you do
> 
> `ls /usr/local/python | grep openpose`
> 
> do you actually see openpose?

yes.but still cannot import

**Comment by orsveri** [comment]
I encountered such problem.

I had folder: 
`<openpose_dir>/build/python/openpose `
with required files:

```
__init__.py
pyopenpose.cpython-36m-x86_64-linux-gnu.so
```

The error I got was following:
```
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
cannot import name 'pyopenpose' from 'openpose' (../../python/openpose/__init__.py)
```
**But then I changed from python 3.7 in conda to python3.6 and it worked.**
Hope it will be useful if someone else with this problem find this

**Comment by therobomaker** [comment]
Is it possible if I can do without make install and do just make as I do not have sudo access and I am getting the same error: 
    from . import pyopenpose as pyopenpose
ImportError: cannot import name pyopenpose
