### ISSUE TITLE
How to import/use trained model in OpenPose from Realtime_Multi-Person_Pose_Estimation repo

### ISSUE THREAD

**Issue by zhengthomastang** [CMU-Perceptual-Computing-Lab/openpose#116]
I used the training code from the full project repo (https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation) to generate new models (COCO) with less stages. To apply them in OpenPose, I changed the ".caffemodel" file in "./models/pose/coco" into my trained model, but I don't know what to do with the "pose_deploy_linevec.prototxt" file. Is it the same as the "pose_deploy.prototxt" file generated in the directory of "train_pose.sh"? I tried to use that for experiments, but I received the following error: 
The output blob is a nullptr. Did you use the same name than the prototxt? (Used: net_output).

**Comment by gineshidalgo99** [comment]
Some small manual editions are required. I think you can take a look to the provisional forked version:
https://github.com/gineshidalgo99/openpose_training

You should be able to edit https://github.com/gineshidalgo99/openpose_training/blob/master/training/c_setLayers.py as you edited it with ZheC repository, and just take the generated pose_deploy_linevec file (no need to re-train the model). That should work. Let me know otherwise and sorry for any inconveniences.

I think that I basically removed the last 2 layers from ZheC repo and name the last one `net_output`.

**Comment by zhengthomastang** [comment]
Hi Gines! Thank you for your answer! The newly trained model using the provided training code can work now. Here is a reminder to all that after training, you need to manually change the last layer ("net_output") into "concat_stage7". You can just copy the last layer from the original file of "pose_deploy_linevec.prototxt".

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back.

**Comment by makeitraina** [comment]
I noticed that the input and the first two layers in the pose_deploy are different then the pose_deploy_linevec file in openpose.
The original repo with training generates:
```
input: "data"
input_dim: 1
input_dim: 4
input_dim: 368
input_dim: 368
layer {
  name: "image"
  type: "Slice"
  bottom: "data"
  top: "image"
  top: "center_map"
  slice_param {
    slice_point: 3
    axis: 1
  }
}
layer {
  name: "silence2"
  type: "Silence"
  bottom: "center_map"
}
```

Is it fine to replace this with the inputs of the openpose proto file like below?
my main concern in the input_dim 4 vs 3, but I might just be misunderstanding how that is used:
```
input: "image"
input_dim: 1
input_dim: 3
input_dim: 1 # This value will be defined at runtime
input_dim: 1 # This value will be defined at runtime
```

**Comment by yinyuecheng1** [comment]
I cut the last stages , but the result has no keypoint , just as the original image, what's wrong with this?

**Comment by xxxyyyzzzz** [comment]
I have same problem as @zhengthomastang. But ,detailed explanation on this layer configuration 
would be really helpful.
