### ISSUE TITLE
libgomp: Out of memory

### ISSUE THREAD

**Issue by FrancescoRossi1987** [CMU-Perceptual-Computing-Lab/openpose#1160]
_Issue_:
execution error

_With_:
Ubuntu 18, CUDA 10.0, cuDNN 7.5.0, OpenCV 3.4.4

_Steps_:
all prerequisites verified & cmake & make & sudo make install

_Command_:
./build/examples/openpose/openpose.bin --video examples/media/video.avi

**Output**:
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

libgomp: Out of memory allocating 927712937064 bytes

-------------------------
Any suggestion?

**Comment by gineshidalgo99** [comment]
Please, check the doc/faq.md. Best

**Comment by FrancescoRossi1987** [comment]
Thanks for your comment. 
Anyway in the doc/faq.md there is not any "libgomp" issue.

In stackoverflow it seems to be related with OpenCV and OpenMP, I tried to reinstall both but with the same results:
"libgomp: Out of memory allocating 927712937064 bytes"

Do you have any suggestion?
Many thanks

**Comment by FrancescoRossi1987** [comment]
Solved!
I reinstalled and upgraded from scratch:
cuda + cudnn + python + OpenCv.
