### ISSUE TITLE
Can't do type conversion

### ISSUE THREAD

**Issue by esemeniuc** [CMU-Perceptual-Computing-Lab/openpose#1162]
Pybind doesn't have a definition for Array<long long>
Error message:
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: openpose.pyopenpose.Datum) -> op::Array<long long>

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/fe767a1ac4b4874e53b0837a72a84c8b642ef656/include/openpose/core/datum.hpp#L93

**Comment by soulslicer** [comment]
You're right. I didn't implement Array<long long>. We should not even be using that. 

Out of curiosity, why are you using this field? We have not implemented tracking into OP yet

**Comment by esemeniuc** [comment]
I was exploring trying to figure out how to separate the heatmaps for each person detected in a pose. Any suggestions on how to get that? poseHeatmaps does not isolate the people, and poseKeypoints doesn't heatmaps

**Comment by soulslicer** [comment]
technically that is not possible. The neural network jointly predicts keypoints and body part connections for multiple people at once. You can always mask out the output of the heatmap with a bounding box mask

**Comment by gineshidalgo99** [comment]
@soulslicer try with false, no with true. Thanks

**Comment by esemeniuc** [comment]
@gineshidalgo99 I didn't quite follow what you meant

**Comment by esemeniuc** [comment]
```cpp
// Numpy - op::Array<long long> interop
namespace pybind11 { namespace detail {

template <> struct type_caster<op::Array<long long>> {
    public:

        PYBIND11_TYPE_CASTER(op::Array<long long>, _("numpy.ndarray"));

        // Cast numpy to op::Array<long long>
        bool load(handle src, bool imp)
        {
            // array b(src, true);
            array b = reinterpret_borrow<array>(src);
            buffer_info info = b.request();

            if (info.format != format_descriptor<long long>::format())
                throw std::runtime_error("op::Array only supports long long now");

            //std::vector<int> a(info.shape);
            std::vector<int> shape(std::begin(info.shape), std::end(info.shape));

            // No copy
            value = op::Array<long long>(shape, (long long*)info.ptr);
            // Copy
            //value = op::Array<long long>(shape);
            //memcpy(value.getPtr(), info.ptr, value.getVolume()*sizeof(long long));

            return true;
        }

        // Cast op::Array<long long> to numpy
        static handle cast(const op::Array<long long> &m, return_value_policy, handle defval)
        {
            std::string format = format_descriptor<long long>::format();
            return array(buffer_info(
                m.getPseudoConstPtr(),/* Pointer to buffer */
                sizeof(long long),    /* Size of one scalar */
                format,               /* Python struct-style format descriptor */
                m.getSize().size(),   /* Number of dimensions */
                m.getSize(),          /* Buffer dimensions */
                m.getStride()         /* Strides (in bytes) for each index */
                )).release();
        }

    };
}} // namespace pybind11::detail

**Comment by soulslicer** [comment]
I will have to figure out how to templateize Pybind type casters. If you manage to figure out, do let me know

**Comment by gineshidalgo99** [comment]
@esemeniuc Sorry, my previous message was for another thread... My bad. About `poseIds`, it only works for 1 person, it does not work for multiple people yet (we are working on this, but it is not out yet, that is why it is not implemented on Python).
