### ISSUE TITLE
Has anyone tried running openpose on a mac with an eGPU?

### ISSUE THREAD

**Issue by MyJumperBroke23** [CMU-Perceptual-Computing-Lab/openpose#1164]
If so, how were the results? Right now I'm getting a fps close to the benchmark (0.3 fps), and was wondering whether it would be worth it to invest into an eGPU.

**Comment by jacksonkr** [comment]
@MyJumperBroke23 With the right card in an egpu you're looking at a massive upgrade. A good 10fps frames at least. I don't have any benchmarks for an egpu but there are plenty of gaming benchmarks for egpu online.

imo don't waste your time using openpose on a laptop, instead record the video remotely and the run that through openpose on a discrete graphics desktop - that's what I'm doing

**Comment by soulslicer** [comment]
It already runs at ~1 fps on my macbook with an internal radeon gpu

**Comment by MyJumperBroke23** [comment]
@jacksonkr Thanks for the advice! What does your setup look like?

**Comment by MyJumperBroke23** [comment]
@soulslicer Ok thanks for the clarification

**Comment by jacksonkr** [comment]
> @jacksonkr Thanks for the advice! What does your setup look like?

@MyJumperBroke23 https://www.amazon.com/gp/product/B075VSBNQZ/ref=oh_aui_search_asin_title?ie=UTF8&psc=1

**Comment by gineshidalgo99** [comment]
I guess the question is solved (Mac does not support it so we will not either)
