### ISSUE TITLE
Question about pose_keypoints_2d

### ISSUE THREAD

**Issue by Solfeggietto2019** [CMU-Perceptual-Computing-Lab/openpose#1165]
I'm running OpenPose from the cmd, and I'm writing a json file for a video, is there a way that I can get the coordinates just for the right and left shoulder and the neck?

**Comment by gineshidalgo99** [comment]
No, you will have to parse the output from the JSON file itself. Check the doc/output to know the specific indexes you want (i think neck was the coordinate 1 and shoulders 2 and 5)
