### ISSUE TITLE
unknown command line flag 'body_disable'

### ISSUE THREAD

**Issue by zjzhengyin** [CMU-Perceptual-Computing-Lab/openpose#1166]
Hello！When I follow The instructions in the document “OpenPose Library - Standalone Face Or Hand Keypoint Detector“ to use the command   ./build/examples/openpose/openpose.bin --body_disable --face --face_detector 1 .There is a error:unknown command line flag 'body_disable' .
How to solve this problem?

**Comment by gineshidalgo99** [comment]
Typo in the doc! Please, use `body 0` rather than `body_disable`. I will fix it in the official doc soon! Best
