### ISSUE TITLE
Question about webcam input

### ISSUE THREAD

**Issue by yorgosk** [CMU-Perceptual-Computing-Lab/openpose#1168]
### Issue Summary
I am running OpenPose taking real-time video input from a ZED stereo camera. The ZED cam is doing optical stereometry, using the input of two sensors (two cameras). The OpenPose is opening a window split in half, each half showing the input of the respective ZED camera's sensor. It seems to aggregate the results of the two sensors input, e.g. when the camera can only see me, the OpenPose reports that it has detected 2 people, as each sensors input contains a slightly different view of myself. It also reports that it is operating at 3.5 FPS, which, as far as I understand, means that the OpenPose is processing (performing human pose estimation) 3.5 camera frames per second.

As I am trying to develop a real-time application on top of the OpenPose, I would like to know if there is a way to instruct it to take input from only one of the two ZED camera sensors while running. Also, I would like, if possible, to get some more insight regarding how the OpenPose uses one or more web-cameras input. E.g. in which factors the 3.5 FPS that I see depend on, other than my hardware? What are the OpenPose algorithmic and technical details that may affect the camera frames processing rate? Is there any published work discussing such details?

If you need more details about my set-up (computer h/w, OpenPose exact commit, mode of installation, etc.) I would be happy to provide them, but at the moment I think my question is general enough to not be necessary to get into such details.

Thanks in advance!

### Executed Command
./build/examples/openpose/openpose.bin

### Type of Issue
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
Not sure how ZED works, but I assume it would have an SDK. Check the C++ tutorial API to check how to change the input by your custom input (in this case ZED camera). Best
