### ISSUE TITLE
GTK+ 2.x and GTK+ 3 in the same process is no longer supported

### ISSUE THREAD

**Issue by lisayan** [CMU-Perceptual-Computing-Lab/openpose#117]
### Issue summary
I was able to run the demo code on my own images successfully and save the pose output. Now, I am trying to do the same thing in my project code going based off of tutorial_pose/1_extract_from_image.cpp.

This seems like a problem that's not openpose specific, but I'm wondering if anyone has come across this? I've tried many ways but it all doesn't work.

### OpenPose output (if any)
`Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported`

### Type of issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your system configuration
**Operating system**: Ubuntu 16.04.2
**CUDA version**: 8.0.61
**cuDNN version**: 5.1
**GPU model**: GeForce 940MX
**Caffe version**: Default from OpenPose
**OpenCV version**: OpenCV 3.1.
Compiler:gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by HWiese1980** [comment]
Have you already been able to solve this issue? I'm encountering the same error.

**Comment by lisayan** [comment]
Sorry, I was unable to solve it. One potential thing I looked into was eliminating either GTK+ 2.x or 3

**Comment by achbogga** [comment]
I am facing the same issue. Please help.

**Comment by gineshidalgo99** [comment]
This issue is an OpenCV issue, due to libraries incompatibilities, so we can't help you fix it as we haven't face that issue. Removing GTK and re-installing it + re-installing OpenCV seems to be the solution.
