### ISSUE TITLE
Some video streaming at the same time?

### ISSUE THREAD

**Issue by alexmryusta** [CMU-Perceptual-Computing-Lab/openpose#1171]
Hello, I would like to know if it is possible to process several streaming videos at the same time. And that's how I could do it? Thank you

**Comment by gineshidalgo99** [comment]
No there is not. Your best option would be to create your own code to do that, and simply keep OP always opened and keep feeding frames into it from the multiple videos. See the C++ tutorial API for examples on how to use OpenPose.
