### ISSUE TITLE
How to use openpose-python api to detect the body keypoints twice in demo.py ?

### ISSUE THREAD

**Issue by cyummy** [CMU-Perceptual-Computing-Lab/openpose#1173]
### **Issue:**
I try to use openpose-python api twice in a *.py. However, something went wrong during the running.
One for detecting the  position of the target (then crop the target from the whole picture and resize it to a uniform size), one for detecting the keypoints of the target in the new resized-image .

My issue is similar to [https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/93] to some degree.

Is that ok to use openpose to detect keypoints twice in a program?
Is there any more documents to refer to? I don't know how to use the pyopenpose rightly.
Could you give me some advice?
Thank you very much!!!

When the cycle index is bigger than one, the program will stuck and throw a error exception.
This error may has something with the gpu. I don't know how to handle with it.
Need your help.
 
### **Program:**
sys.path.append('/usr/local/lib/python3.6')
import pyopenpose as op 

params = dict()
params["model_folder"] = "./models/"

opWrapper = op.WrapperPython()
opWrapper.configure(params)
opWrapper.start()

for video in videos:
    ...
    cap = cv2.VideoCapture(videoPaths)
    ret,imageToProcess = cap.read()

    datum = op.Datum()
    datum_new=op.Datum()
    .......
    datum.cvInputData = imageToProcess
    opWrapper.emplaceAndPop([datum])

    .......
    datum_new.cvInputData = resize_img
    opWrapper.emplaceAndPop([datum_new])
`
**### Error:**
if (max(datum_new.poseKeypoints[0,j,:])==0):
IndexError: too many indices for array

**Comment by cyummy** [comment]
It's ok to use openpose twice in a *.py. I have solved my issue.

**Comment by rajasrijan** [comment]
@cyummy how did you solve it?

**Comment by zahera-fatima** [comment]
how to install openpose in window and how to use it as library in python
