### ISSUE TITLE
How to decrease GPU utilization to make single GPU run multiple videos?

### ISSUE THREAD

**Issue by ro6842** [CMU-Perceptual-Computing-Lab/openpose#1174]
Now I am trying to use "single" GPU to run the video(about 100 seconds) to esimate poses.
It is about 12 fps. And GPU memory uses 8GB, GPU util uses 80%.

I aim to decrease GPU utilization so that I can use single GPU to run "multiple" videos at the same time.
Do the Openpose have any command like: "gpu_memory_fraction" to lower GPU's memory and utilization?

I know this may lower the fps. But I need some ways to run "multiple" videos at single GPU.
Not just one video occupies one GPU.
Anyone can help me? Thank you very much!

**Comment by gineshidalgo99** [comment]
No, OpenPose does not have that functionality, it is quite specific.

However, you can create your own demo based on the C++ tutorial API and keep OP always open and feed it with multiple videos by yourself. That would be your best bet. Hope this helps.
