### ISSUE TITLE
CentOS Compatibility

### ISSUE THREAD

**Issue by JeBo89** [CMU-Perceptual-Computing-Lab/openpose#1176]
Currently I've tested OpenPose on Windows, but unfortunately my PC is to slow to process the videos in a reasonable amount of time. My (masterthesis) research supervisor pointed me towards a clustercomputer that runs on CentOS --> I'm aware that OpenPose is not officially supported at the moment for CentOS and therefor there is no installation instructions on it. But as mentioned on the installation page, it shows that it has been used on this OS. I'm therfore hoping that there is a user that has figured this out, or is willing to provide the steps how to do it?
Thanks in advance!

**Comment by gineshidalgo99** [comment]
I must close this to focus in real issues, but please feel free to answer to him and/or make a PR to OP with the steps about how to run it in there!

My guess: It should be similar to Ubuntu CMake, start by following those steps (I'd recommend you to install Caffe first, OpenPose is just C++11 + Caffe + OpenCV). Thanks!
