### ISSUE TITLE
OpenPoseDemo Win10 Build :   CUDA 10 , Cudnn 7.5 , VS 2017 , Cmake 3.14.1 , RTX 2070

### ISSUE THREAD

**Issue by zirid** [CMU-Perceptual-Computing-Lab/openpose#1178]
Issue Summary 

I tried OpenPosDemo cpu version , it runs without any issues but its so slow. So i built from source  with CUDA 10  however,  i am getting this error :

`Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
F0411 16:43:22.768380 17860 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***`

Documentation says that the latest version is compatible with CUDA 10 & Vs2017 . Thanks for help.

Compilation/installation error
Help wanted
2.Your System Configuration
OpenPose version: Latest Release (OpenPose v1.4.0 )

General configuration:
    Installation mode: CMake GUI 
    Operating system: Win 10
    Release or Debug mode:  Release
    Compiler:  MSVC v141
   GPU : RTX 2070
Non-default settings:
None
4.3rd-party software:
    CMake version: 3.14.1
    OpenCV version: 3.1.0

5.If GPU mode issue:
    CUDA version : 10
    cuDNN version: 7.5
    GPU model : Yes

6. Cmake output :

`Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
CMake Warning (dev) at CMakeLists.txt:47 (set):
  implicitly converting 'TYPE' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

Building with CUDA.
Downloading windows dependencies...
opencv_310.zip already exists.
caffe3rdparty_2018_06_26.zip already exists.
caffe_2018_01_18.zip already exists.
Windows dependencies downloaded.
Adding Example Calibration
Adding Example OpenPoseDemo
Adding Example 1_custom_post_processing
Adding Example 1_extract_from_image
Adding Example 2_extract_pose_or_heatmat_from_image
Adding Example 1_openpose_read_and_display
Adding Example 2_user_processing_function
Adding Example 3_user_input_processing_and_output
Adding Example 4_user_input_processing_output_and_datum
Adding Example 1_user_synchronous_postprocessing
Adding Example 2_user_synchronous_input
Adding Example 3_user_synchronous_output
Adding Example 4_user_synchronous_all
Adding Example 5_user_asynchronous
Adding Example 6_user_asynchronous_output
Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
Configuring done
Generating done`

**Comment by gineshidalgo99** [comment]
The release is several months old, it does not support CUDA 10. You would have to build it from source from the latest code. The documentation of the current GitHub refers to the current code. My apologies for the confusion.

**Comment by zirid** [comment]
Thank you, It's working fine with the latest code.
