### ISSUE TITLE
what are needed when i want to use openpose-gpu Windows Portable Demo

### ISSUE THREAD

**Issue by sxudai** [CMU-Perceptual-Computing-Lab/openpose#1180]
i am new to CV, and i just want to use openpose. i didn't download anything else before. and there is something wrong like:

Check failed: error == cudaSuccess (2 vs. 0) run out of memory

do i need download something like cuda, caffe, first?

**Comment by gineshidalgo99** [comment]
Please, refer to doc/faq.md
