### ISSUE TITLE
Quick start demo error: symbol lookup error: libopenpose.so.1.4.0: undefined symbol

### ISSUE THREAD

**Issue by Sun1Plus** [CMU-Perceptual-Computing-Lab/openpose#1181]
### Issue Summary
I have finished installation, but when I want to run the quickstart, there's some wrong. I can't solve it, could anyone help me?

### Executed Command (if any)
sun@sun-ThinkPad-Edge-E431:~/openpose$ ./build/examples/openpose/openpose.bin --video examples/media/video.avi

### OpenPose Output (if any)
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
./build/examples/openpose/openpose.bin: symbol lookup error: /home/sun/openpose/build/src/openpose/libopenpose.so.1.4.0: undefined symbol: _ZN5caffe3NetIfE21CopyTrainedLayersFromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### Errors (if any)
symbol lookup error: ./build/src/examples/openpose/libopenpose.so.1.4.0: undefined symbol;

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output**:
sun@sun-ThinkPad-Edge-E431:~/openpose$ ./build/examples/openpose/openpose.bin --video examples/media/video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
./build/examples/openpose/openpose.bin: symbol lookup error: /home/sun/openpose/build/src/openpose/libopenpose.so.1.4.0: undefined symbol: _ZN5caffe3NetIfE21CopyTrainedLayersFromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

2. **OpenPose version**:
 Latest GitHub code

3. **General configuration**:
    - **Installation mode**: Ubuntu18.04 Cmake
    - **Operating system** (`lsb_release -a` in Ubuntu):
       No LSB modules are available.
       Distributor ID:	Ubuntu
       Description:	Ubuntu 18.04.2 LTS
       Release:	18.04
       Codename:	bionic
    - Ubuntu18.04 LTS
    - No compiler, just quick start demo.

4. **Non-default settings**:

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu):cmake version 3.12.4
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu)

6. If **GPU mode** issue:
    - Cuda10.1
    - CuDnn7.5.0
    - GeForce GT 740M

**Comment by gineshidalgo99** [comment]
This seems like an error coming from Caffe. `XXXCopyTrainedLayersFromXXX` seems to be a function from there. Are you sure no other Caffe versions are installed on your machine? Otherwise, try installing Caffe by your own, test it works, and then simply link OpenPose to your custom Caffe with the proper CMake flag. Hope this helps. (I must close this as it is a 3rd-party library issue rather than OP issue). Best

**Comment by Sun1Plus** [comment]
Thank you very much. I have deleted my own caffe, but there's still the problem. Then I will try to change centos system. Best project!

**Comment by neonb88** [comment]
Did you resolve the issue?  Curious about the steps.  I'm facing the same error message coming from the [docker installation](https://hub.docker.com/r/cwaffles/openpose).

**Comment by Sun1Plus** [comment]
> @Sun1Plus Did you resolve the issue?  I'm curious about the steps you took.  I'm facing the same error message coming from the docker installation.

In the system of Ubuntu18.04, I can't solve the problem. I guess that some libraries are incompatible. Then I tried to rebuild in Windows10 + VS2017, followed the steps of installation, it was ok. Maybe you could try another system.

**Comment by nikkolasedi** [comment]
@Sun1Plus @neonb88 I have the same issue. Do you have the solution?

**Comment by krishnachaitanya7** [comment]
I had the same issue. I was installing OpenPose 1.6.0 with Python2.7 bindings. Found out that I actually built the pyopenpose for Python3 rather than Python2. I rebuilt the openpose with following command: 
```bash
cmake -DCMAKE_CXX_FLAGS="-I/usr/include/python2.7 -lpython2.7" -DPYTHON_EXECUTABLE=/usr/bin/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DBUILD_PYTHON=ON ..
```
I hope it helps. Thank you.

**Comment by neonb88** [comment]
@nikkolasedi sorry, just saw this.  Hope you found a solution.  Wow, this is over a year and half old now.  Hopefully these comments help _someone_, at least

**Comment by MSKTHU** [comment]
I had the same issue. Using command ldd libopenpose.so.1.x.x, I found out that the libopenpose.so.1.x.x links to an existing caffe.so rather than the one built in this repo. I also found out that the LD_LIBRARY_PATH directs to the exsiting caffe.so. So I export LD_LIBRARY_PATH='' and rebuilt everything and finally it works.
