### ISSUE TITLE
Relationship between Wrapper and WrapperStructPose

### ISSUE THREAD

**Issue by mooktj** [CMU-Perceptual-Computing-Lab/openpose#1183]
Hi, 

This issue has nothing to do with the set up of the library. It is to do with understanding the structure of the library.

I'm struggling to understand where is WrapperStructPose called to be instantiated on line 92 of  "openpose/examples/tutorial_api_cpp/01_body_from_image_default.cpp" 

where it says...

op::Wrapper opWrapper{op::ThreadManagerMode::Asynchronous};

I have tried printing out checkpoints using std::cout in both Wrapper.hpp's and WrapperStructPose.cpp's constructors, and the result is that the line (line 43) I added in WrapperStructPose.cpp's constructor appears before the line I added (line 268) in Wrapper.hpp's constructor.

What I'm suspecting is that Wrapper.hpp calls WrapperStructPose.cpp to be instantiated but I cannot find how WrapperT knows when to call WrapperStructPose. Could anyone explain how there two files are related?

I don't know where else to put my questions, so I put in issues. Please direct me to somewhere else if it's more appropriate.

Thank you very much.

**Comment by gineshidalgo99** [comment]
WrapperStructPose is set on the files containing the main(), based on the values introduced by the user, with the default values specified en include/openpose/flags.hpp.

WrapperT reads it, to set up all its configuration, but it does not modify it.

For this particular case, 01_body_from_image_default, there are no value specified by the user, therefore, everything is set to the defaults of flags.hpp. Hope this helps. Best

**Comment by mooktj** [comment]
Thank you @gineshidalgo99
