### ISSUE TITLE
how to run this command "bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand" with Demo on windows 

### ISSUE THREAD

**Issue by ayanasser** [CMU-Perceptual-Computing-Lab/openpose#1185]
Hi ,
I have installed the portable  demo and run it on webcam by just clicking on the OpenposeDemo.exe 
and it ran correctly ,
but how and where you type this commands ?
`bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand`
as i used it with git shell it type me this 
`bash: binOpenPoseDemo.exe: command not found`

sorry for this silly one but I am beginner with it

**Comment by gineshidalgo99** [comment]
You need to use a command-line tool. In Windows, that means PowerShell or CMD. I have just updated the doc to mention them (you are right, they were not mentioned previously).  Feel free to watch any Youtube video tutorial if you are not familiar with these non-GUI tools.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md

**Comment by s9443112** [comment]
根本沒東西啊 亂回一通 搞什麼鬼?
