### ISSUE TITLE
how can i extract my Skeleton point and get (.json)file

### ISSUE THREAD

**Issue by facejun** [CMU-Perceptual-Computing-Lab/openpose#1186]
### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue

- Help wanted
- Question
- 

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

3. **General configuration**:
    - **Installation mode**: CMake, (Windows); ...?
    - **Operating system** (`win10):
    - **Operating system version** ( Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows):

8. If **Python** API:
    - **Python version**: 3.7, ...?
    -

9. If **Windows** system:
    - compiled library?

**Comment by gineshidalgo99** [comment]
Please, check the doc/demo_overview.md and quick_start for that
