### ISSUE TITLE
OpenPose without CuDNN? (GFX card does not support it)

### ISSUE THREAD

**Issue by gineshidalgo99** [CMU-Perceptual-Computing-Lab/openpose#119]
Moving @skrish13 question to new issue thread:

> Just in case anyone comes here looking for installing OpenPose without CuDNN (since your GFX card doesn't support it), please mind this point from FAQ. It's useless if you have an older card which CuDNN doesn't support as its RAM is anyways not going to be anywhere near 12GB.

> @gineshidalgo99 am i safe in assuming the above?

**Comment by gineshidalgo99** [comment]
@gineshidalgo99 answer: Maybe using the default configuration and a very very small net_resolution (start trying with 160x160 to see if its fits), it might work, but this would only work with people taking most of the image. Let me know if you try the results. Thanks!
@skrish13 Oh, right. okay. Will do! Will be interesting to see how it works on that resolution :)
@gineshidalgo99 Yeah, it will definitively be. Please, it'd be great if you post your required GPU (or if out-of-memory still appears) or any results you can get for other people. Thanks

**Comment by ThienAnh** [comment]
Can i build Openpose's lib without cuda?. (My computer not support CUDA)

**Comment by gineshidalgo99** [comment]
OpenPose can run without cuDNN, but it requires much more GPU memory, so the `net_resolution` must be highly reduced (e.g. 160x80). Indicated in the doc too.
