### ISSUE TITLE
How to use openpose.bin to generate a file of video test results instead of one file per frame?

### ISSUE THREAD

**Issue by 1209805200** [CMU-Perceptual-Computing-Lab/openpose#1190]
not xxx.avi ----->0001.json&0002.json&....&000n.json

i want :xxx.avi------>p.json("frame_index": 1,pose..."frame_index": 2,pose ....)
 how can i do it?

**Comment by gineshidalgo99** [comment]
#1092

**Comment by whg0023** [comment]
i also wang to know about it
