### ISSUE TITLE
Windows Error: can't find pyopenpose module

### ISSUE THREAD

**Issue by jmcmichael125** [CMU-Perceptual-Computing-Lab/openpose#1193]
### Issue Summary
Have successfully run OpenPose through the command line, however cannot get the python API to run at all, even on the tutorials. I have tried multiple tutorials and versions of the code and each time the same error is produced:   

Solution was build through CMake and Visual studio 2017 and BUILD_PYTHON was enabled. I have already attempted rebuilding the code and re downloading the GitHub code with no effect. The build was successfully completed and the correct folders and files appear to have been created including the pyopenpose.cp36-win_amd64.pyd file in the Release folder.

### Executed Command (if any)
Current code having moved one of the tutorials to the build folder. Note: the same failure occurred in the tutorial code and other modified versions

dir_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(dir_path + '/python/openpose/Release');      
os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + '/x64/Release;' + dir_path + '/bin;'+ dir_path+ 'python/openpose/Release;'
import pyopenpose as op

### Errors (if any)
Traceback (most recent call last):
  File "C:/Users/Administrator/Documents/GitHub/openpose/build/01_body_from_image_build.py", line 16, in <module>
    import pyopenpose as op
ModuleNotFoundError: No module named 'pyopenpose'

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted

### Your System Configuration
**OpenPose version**: Latest GitHub code, retrieved 4/5/19

**General configuration**:
    - **Installation mode**: CMake
    - **Operating system** Windows 10, 64 bit
    - **Release mode**
    - **Compiler**: VS2017 community
    - **IDE**: PyCharm

5. **3rd-party software**:
    - **Caffe version**: Default
    - **CMake version**: 3.14.1
    - **OpenCV version**: default

6. If **GPU mode** issue:
    - **CUDA version**: 10.1
    - **cuDNN version**: 7.5
    - **GPU model**: Nvidia V100

8. If **Python** API:
    - **Python version**: 3.7

**Comment by soulslicer** [comment]
You said youre running from 

""C:/Users/Administrator/Documents/GitHub/openpose/build/01_body_from_image_build.py""

This doesnt make sense. The example files should be generated in the examples folder, inside a Release folder etc.

**Comment by jmcmichael125** [comment]
Apologies, I haven't made it clear what i did. 
That particular error is from when i moved one of the tutorials to the build folder as a test. The same error (with a difference file location) occurred when running from where it was originally generated in the examples folder.

**Comment by jmcmichael125** [comment]
Update: fully reinstalled cmake, python 3.7 and Vidual studio 17 and reclones the openpose repository and the tutorials have begun to work. Nothing changed at all in the file structure or code and the tutorials and code have begun to work. I guess it was an issue with the original installation.

**Comment by Jichen66** [comment]
hi, I also met similar problem recently. I  use the Windows system, and I can only run openpose successfully through visual studio. When I run one of the python files randomly, it is also said "No modules named 'pyopenpose' ". I already choose the build_python in CMake. Do you have any idea on how to solve it?

**Comment by yukun7273** [comment]
hi，i also met the same problem with you, have you solve the problem? can you tell me how do you solve the problem?

**Comment by Tatwik19** [comment]
@yukun7273 @Jichen66 Did you solve the problem?
I am facing the same problem now...
