### ISSUE TITLE
write_bvh is not working

### ISSUE THREAD

**Issue by aitorgutierrez** [CMU-Perceptual-Computing-Lab/openpose#1196]
Hi!

I am using openpose with the following script 

./build/examples/openpose/openpose.bin --net_resolution 160x80 --write_bvh /media/test.bvh --write_video_fps 

Anything is stored in test.bvh. Is it --write_bvh working?

**Comment by gineshidalgo99** [comment]
write_bvh does not work (it indicates "experimental" in the flag description itself to avoid confusion). I will throw an error instead, so it is more clear.

**Comment by delebash** [comment]
Any update on if/when this will be available.  If not do you know of any program to convert the .json files to bvh.  Thanks
