### ISSUE TITLE
Hand detection not working on compiled Windows version

### ISSUE THREAD

**Issue by Klimm-Max** [CMU-Perceptual-Computing-Lab/openpose#1197]
### Issue Summary
Running on several windows machines, the `--hand` command seems to be ignored/not working.
Tried the following commands to execute hand detection as well:
`bin\OpenPoseDemo.exe --face --hand`
`bin\OpenPoseDemo.exe --face --hand --hand_scale_number 6 --hand_scale_range 0.4`

### General configuration:
Installation mode: OpenPose 1.4 gpu from the [Release Section](https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases)
Operating system: Windows 10
Release or Debug mode? Release

GPU model: GTX 1070 & GTX 1060

If Windows system:
Portable demo or compiled library? Compiled Library attempt

**Comment by soulslicer** [comment]
Curious..why are you using OpenCL mode with NVIDIA?

Also, what happens when you compile with CUDA

**Comment by Klimm-Max** [comment]
Ah, sorry just copied the "boilerplate" for submitting an issue.
(removed the openCL version)

We did 0 configuration on the windows machines and just started with the gpu binaries.

**Comment by gineshidalgo99** [comment]
Then please check the doc/faq.md. Most probably you have not properly download it

**Comment by Klimm-Max** [comment]
What Do you mean?
I have been running the `getModels.bat`

Everything works as expected. Eben the --face Parameter works correctly

**Comment by gineshidalgo99** [comment]
They are independent models, most probably the hand model was not downloaded properly. For some reason Caffe simply returns 0s but does not warn against it. Try manually re-downloading it.
