### ISSUE TITLE
Build information update request for windows.

### ISSUE THREAD

**Issue by trustfarm-dev** [CMU-Perceptual-Computing-Lab/openpose#1198]
In case of **Windows build**

[DocumentsLink](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#windows)

How about command line build?

-- Add followings:: --

1. Run "MSVS 2017 Developer Command Console"
```
openpose\mkdir  buildwin
cd buildwin
cmake .. -G "Visual Studio 15 2017 Win64" -T v140
cmake --build . --config Release
copy x64\Release\*  bin\
```

2. If you want to clean build

```
cmake --clean-first .
cmake --build . --config Release
copy x64\Release\*  bin\
```

-------

It may be more instructive for developers.

Thanks , Great Framework **"OpenPose"**

**Comment by riebling** [comment]
This is a wonderful suggestion, and might potentially save people worlds of pain. I will try it and report back any problems, if my boss lets me :)

**Comment by gineshidalgo99** [comment]
Thanks! I will check it in a couple weeks and add it to the doc! :)
