### ISSUE TITLE
error (core dump)

### ISSUE THREAD

**Issue by 1aad1** [CMU-Perceptual-Computing-Lab/openpose#1199]
Made my config , generation well.
also Build done succesfully.

Run through
 ./build/examples/openpose/openpose.bin --video examples/media/video.avi

System config
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
[libprotobuf ERROR google/protobuf/message_lite.cc:118] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F0418 15:18:00.227388  3241 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7f9969d5b0cd  google::LogMessage::Fail()
    @     0x7f9969d5cf33  google::LogMessage::SendToLog()
    @     0x7f9969d5ac28  google::LogMessage::Flush()
    @     0x7f9969d5d999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f996c6cb341  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f996c661f7a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f996cdb7ebb  op::NetCaffe::initializationOnThread()
    @     0x7f996cdda7b2  op::addCaffeNetOnThread()
    @     0x7f996cddbbfc  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f996cde19a3  op::PoseExtractorNet::initializationOnThread()
    @     0x7f996cdd6581  op::PoseExtractor::initializationOnThread()
    @     0x7f996cdd1541  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f996ce14d41  op::Worker<>::initializationOnThreadNoException()
    @     0x7f996ce14e70  op::SubThread<>::initializationOnThread()
    @     0x7f996ce17258  op::Thread<>::initializationOnThread()
    @     0x7f996ce1743b  op::Thread<>::threadFunction()
    @     0x7f996b1e2733  (unknown)
    @     0x7f996a9036db  start_thread
    @     0x7f996ac3c88f  clone
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
doc/faq.md
