### ISSUE TITLE
Connected with Microsoft Kinect 1.0

### ISSUE THREAD

**Issue by RickGodLike** [CMU-Perceptual-Computing-Lab/openpose#120]
Hi! Can you tell me how could I adjust the value of 
![qq 20170701204921](https://user-images.githubusercontent.com/27850396/27762162-de7e167e-5e9e-11e7-80ed-bacdbe203e8a.png)
so I can obtain the real-time video from Kinect?
Also, if I want to run the c++ source file in the examples/tutorial_wrapper file, what kind of project of visual studio should I plug it into? Should the project I created stay in the folder of windows-project?

**Comment by gineshidalgo99** [comment]
Hi, We have no implement any code for Kinect, if you have your own code to read RGB images from Kinnect, then you can use `examples/tutorial_wrapper/` files that read custom images, and change that code by your Kinect images extractor

**Comment by RickGodLike** [comment]
Hi! I have a close look at `windows_project\TutorialWrapper\1_user_asynchronous` and I can print out the posekeypoints by adding `std::cout << datumsPtr->at(0).poseKeypoints.toString() << std::endl;` in the UserOutputClass.
However, when I do the same thing with `windows_project\OpenposeDemo`, which uses a webcam. The window doesn't show me anything! I don't know what is wrong....Could it be that we can only print out keypoints of pictures because when it comes to realtime webcam, it doesn't work... HELP...

**Comment by DarcyWL** [comment]
Just found that we had the same problem..... Can anyone figure it out?

**Comment by gineshidalgo99** [comment]
I've been trying but I am not able to replicate that problem.

Could you try the latest version to see whether it is working in the current version?

**Comment by WilliamRuRu15** [comment]
Maybe you can change the constructor of `WUserInput` in 2_user_synchronous.cpp to construct with color frame (`Mat`) of Kinect. I'm testing with a image (`Mat`) to construct a `WUserInput` instance. And I can actually get the result, but I don't know why my result repeatedly printed on my console window. I think it should stop when the only one image is finished processing. The print part code is shown below.
`if (datumsPtr != nullptr && !datumsPtr->empty())
			{
				std::cout << datumsPtr->at(0).poseKeypoints.toString() << std::endl;
				std::cout << "################# OVER ###################" <<std::endl;
			}`.
 How can I make it stop right after I processed the frame I've just got? Or must I have all the frames ready and process them afterwards?

**Comment by WilliamRuRu15** [comment]
I have the same problem when `cv::imshow()` a image window in that demo (I'm not sure if you mean this), but I can print the keypoints on console window.

**Comment by andudu** [comment]
Never try to change the openpose file structure, if you want to read the keypoints(including body hand face) ,only use 'windows-- cmd' demand '--write_keypoint_json'. 
json file will record the all the keypoints info!!!

**Comment by gineshidalgo99** [comment]
@aniketzz Thanks! Added your instructions to `doc/demo_overview.md`.
