### ISSUE TITLE
OpenPose Windows 10 Build: Cuda 8, Cudnn 5.1, VS 2015, Cmake 3.14.2, GTX 1060

### ISSUE THREAD

**Issue by tsmjohnpascual** [CMU-Perceptual-Computing-Lab/openpose#1200]
Issue Summary:
I am trying to build openpose from source but I am receiving an error in cmake gui.

Errors (if any):
CMake Warning (dev) at CMakeLists.txt:81 (set):
  implicitly converting 'TYPE' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

Type of Issue:
- Compilation/installation error
- Help wanted

Your System Configuration:
2. OpenPose version: Latest release as I cloned it today.

3. General configuration:
    - Installation mode: CMake GUI
    - Operating system: Windows 10
    - Release or Debug mode: Release
    - Compiler: VS2015 Enterprise Update 3

4. Non-default settings:
    None

5. 3rd-party software:
    - Caffe version: Default from OpenPose
    - CMake version: 3.14.2
    - OpenCV version: OpenPose default (only Windows)

6. If GPU mode issue:
    - CUDA version: 8.0
    - cuDNN version: 5.1
    - GPU model: GTX 1060

7. CMake output:
Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.17134.
The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:81 (set):
  implicitly converting 'TYPE' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found version "8.0") 
Building with CUDA.
Downloading windows dependencies...
Downloading http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows...
Extracting C:/Users/ashle/Documents/GitHub/openpose/3rdparty/windows/opencv_401_v14_15_2019_03_14.zip...
Downloading http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows...
Extracting C:/Users/ashle/Documents/GitHub/openpose/3rdparty/windows/caffe3rdparty_15_2019_03_14.zip...
Downloading http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows...
Extracting C:/Users/ashle/Documents/GitHub/openpose/3rdparty/windows/caffe_15_2019_03_14.zip...
Windows dependencies downloaded.
Adding Example Calibration
Adding Example OpenPoseDemo
Adding Example 1_custom_post_processing
Adding Example 01_body_from_image_default
Adding Example 02_whole_body_from_image_default
Adding Example 03_keypoints_from_image
Adding Example 04_keypoints_from_images
Adding Example 05_keypoints_from_images_multi_gpu
Adding Example 06_face_from_image
Adding Example 07_hand_from_image
Adding Example 08_heatmaps_from_image
Adding Example 09_keypoints_from_heatmaps
Adding Example 10_asynchronous_custom_input
Adding Example 11_asynchronous_custom_output
Adding Example 12_asynchronous_custom_input_output_and_datum
Adding Example 13_synchronous_custom_input
Adding Example 14_synchronous_custom_preprocessing
Adding Example 15_synchronous_custom_postprocessing
Adding Example 16_synchronous_custom_output
Adding Example 17_synchronous_custom_all_and_datum
Adding Example 1_thread_user_processing_function
Adding Example 2_thread_user_input_processing_output_and_datum
Download the models.
Downloading BODY_25 model...
NOTE: This process might take several minutes depending on your internet connection.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
NOTE: This process might take several minutes depending on your internet connection.
Downloading hand model...
NOTE: This process might take several minutes depending on your internet connection.
Models Downloaded.
Configuring done
Generating done

**Comment by gineshidalgo99** [comment]
Actually, it is not an error, it is a warning (coming from Cmake), you can click "Configure" and "Generate" and it will still work.

However, I'll check it out and try to remove it. So far I can confirm it only happens with Cmake >= 14. For what I see, they have done a lot of changes in CMake 14 for Windows. I'll update you here

**Comment by gineshidalgo99** [comment]
Warning removed in the latest commit that I have just pushed. It should not occur again, let me know otherwise.

@tsmjohnpascual But again, it is just a warning, so re-downloading the latest OpenPose just to avoid this warning is optional, you can choose to simply ignore it.
