### ISSUE TITLE
one question about detail of training  BODY_25 

### ISSUE THREAD

**Issue by oujieww** [CMU-Perceptual-Computing-Lab/openpose#1201]
I want to know ,when u trained BODY_25, with only the 11065 images which annotated by your group and initialized from imagenet, or mixed the footdataseet with orginal cocoset which without foot annotations? maybe other methods?^_^

**Comment by gineshidalgo99** [comment]
Together.

Please, check the paper for all the details you are asking for:
OpenPose: Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields
https://arxiv.org/abs/1812.08008

Thanks!

**Comment by luaGeeko** [comment]
@oujieww were you able to get results for combined dataset body + foot ?

**Comment by gineshidalgo99** [comment]
Recently released training repo: https://github.com/CMU-Perceptual-Computing-Lab/openpose_train
