### ISSUE TITLE
Does tracking use some filtering(EKF) with openpose detections?

### ISSUE THREAD

**Issue by Harsharma2308** [CMU-Perceptual-Computing-Lab/openpose#1202]
### Issue Summary
Does openpose tracking use something like kalman filter or other filtering algorithms to have the temporal connection between last frames and current frame?

### Type of Issue
- Question

**Comment by gineshidalgo99** [comment]
The current want simply uses LK. But we are working in a new version based on 
https://www.raaj.tech/staf
