### ISSUE TITLE
Solution for Foot-only Keypoint Detection

### ISSUE THREAD

**Issue by ChenFengYe** [CMU-Perceptual-Computing-Lab/openpose#1203]
Hi, thank for your wonderful work. Foot estimation is really helpful.

However, I find the foot part will lose, even if the foot is obvious in the center of the image(not a complete person). I guess Oposepose focuses on the person first, so is there any solution for foot-only keypoint detection?

**Comment by gineshidalgo99** [comment]
Let me know if this "hack" works for you, and if so, I would think about how to add this as an option.

Comment out these 3 lines:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/net/bodyPartConnectorBase.cpp#L641
```
                    // No consider foot keypoints for that
                    for (auto i = 19 ; i < 25 ; i++)
                        personCounter -= (peopleVector[index].first.at(i) > 0);
```

That way, foot-only images should be printed as well. Let me know if it works for your case. It increases the number of false positives, that is why we do this, but if you want foot-only pics, this is the way to make it work.

**Comment by ChenFengYe** [comment]
@gineshidalgo99 Thanks for your reply. Nice work!

**Comment by emirhanylmzz** [comment]
> Updated:
> **The solution to detect standalone feet is to use `--maximize_positives`, read the doc/demo_overview.md for more details.**
> 
> **Explanation**
> The reason is that it automatically skip the following 3 lines of code in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/net/bodyPartConnectorBase.cpp#L641
> 
> ```
>                     // No consider foot keypoints for that
>                     for (auto i = 19 ; i < 25 ; i++)
>                         personCounter -= (peopleVector[index].first.at(i) > 0);
> ```
> 
> That way, keypoints from foot-only images should be printed as well. Let me know if it works for your case. It increases the number of false positives, that is why we do this, but if you want foot-only pics, this is the way to make it work.


I understand you and tried your solution but the result accuracy is not too bad. Is there any way to train only foot database and detect only foot keypoints on foot-only pics.

**Comment by emirhanylmzz** [comment]
> Updated:
> **The solution to detect standalone feet is to use `--maximize_positives`, read the doc/demo_overview.md for more details.**
> 
> **Explanation**
> The reason is that it automatically skip the following 3 lines of code in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/net/bodyPartConnectorBase.cpp#L641
> 
> ```
>                     // No consider foot keypoints for that
>                     for (auto i = 19 ; i < 25 ; i++)
>                         personCounter -= (peopleVector[index].first.at(i) > 0);
> ```
> 
> That way, keypoints from foot-only images should be printed as well. Let me know if it works for your case. It increases the number of false positives, that is why we do this, but if you want foot-only pics, this is the way to make it work.

I understand you and tried your solution but the result accuracy is too bad. Is there any way to train only foot database and detect only foot keypoints on foot-only pics.

**Comment by PeerW** [comment]
@emirhanylmzz  Did you find a solution? I'm experiencing the same low accuracy and would also be interested in a way to detect only foot key points and train on only foot images.

**Comment by devendraswamy** [comment]
Guys have you trained the foot keypoint detection , if you done then kindly help me. if possible please share the your work or open source links here , I am very thankful to you in advance.
