### ISSUE TITLE
Caffe trained model file not found: models\pose/body_25/pose_iter_584000.caffemodel.

### ISSUE THREAD

**Issue by donamel** [CMU-Perceptual-Computing-Lab/openpose#1204]
### Executed Command

C:\Windows\system32>cd C:\Users\Donamel360\Desktop\openpose-1.4.0-win64-gpu-binaries

C:\Users\Donamel360\Desktop\openpose-1.4.0-win64-gpu-binaries>bin\OpenPoseDemo.exe --video examples\media\VID.avi

### Errors (if any)
C:\Windows\system32>cd C:\Users\Donamel360\Desktop\openpose-1.4.0-win64-gpu-binaries

C:\Users\Donamel360\Desktop\openpose-1.4.0-win64-gpu-binaries>bin\OpenPoseDemo.exe --video examples\media\VID.avi
Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...

Error:

Caffe trained model file not found: models\pose/body_25/pose_iter_584000.caffemodel.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():54
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():131
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():94
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > >::initializationOnThread():50
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/subThread.hpp:op::SubThread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::initializationOnThread():150
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::initializationOnThread():174
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::threadFunction():204

### Type of Issue

- Help wanted
- Question

**Comment by superSupa** [comment]
The link you put is not work now. @gineshidalgo99 
I am facing the same problem as donamel.
Please help me~
I am a newbie

**Comment by Bayaniblues** [comment]
> 
> 
> The link you put is not work now. @gineshidalgo99
> I am facing the same problem as donamel.
> Please help me~
> I am a newbie

Hello have you tried following the [prerequisites?](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/018d471bff5f298d113ebd1dc0fa0468b54f3602/doc/prerequisites.md)

**Comment by ChongMingWei** [comment]
If you don't have the caffe model, download it in any way.
Then just create a folder with the same structure mentioned in error message:
 models------>pose------>body_25
Finally put the caffe model in the body_25 folder and it may work.

**Comment by dr-natetorious** [comment]
I resolved the issue by downloading this missing file:

https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe-models/blob/master/caffe_models/openpose/caffe_model/pose_iter_584000.caffemodel

**Comment by wayne931121** [comment]
The full model link: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
