### ISSUE TITLE
Ubuntu16.04 cv screen appears very slowly

### ISSUE THREAD

**Issue by Joneny** [CMU-Perceptual-Computing-Lab/openpose#1206]
### Issue Summary
I can successfully run the video display demo, showing the number of frames around 13 frames. However, after the starting thread(s)... is displayed from the terminal, the video frame appears and is in a crash state. The image can be displayed after about 40s-1min.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
./build/examples/openpose/openpose.bin

### OpenPose Output (if any)

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
VIDEOIO ERROR: V4L: index 0 is not correct!
Auto-detecting camera index... Detected and opened camera 1.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 46.516701 seconds.

### Errors (if any)
no error

### Type of Issue
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake,Make
    - **Operating system**: Ubuntu16.04
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):Ubuntu16.04
    - **Release or Debug mode**? (by default: release): Release
    - Compiler : 5.4.0, ... (Ubuntu); 

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, 
    - **CMake version** (`cmake --version` in Ubuntu):cmake version 3.5.1
    - **OpenCV version**: 3.3

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):CUDA Version 8.0.44
    - **cuDNN version**:cudnn Version 5.1
    - **GPU model** (`nvidia-smi` in Ubuntu):RTX2070//Driver Version: 415.27 

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):1.15.0

### Problem supplement
  Similar to the original caffe compilation, because it is RTX2070, the unsupport compute_75 problem will occur during the initial compilation
  So during the compilation process, I modified the Cuda.cmake file and modified (Caffe_known_gpu_archs "${FERMI} $ {KEPLER} ${MAXWELL} ${PASCAL} ${VOLTA} ${TURING}") to set(Caffe_known_gpu_archs "${PASCAL}")
  and in cmake-gui, set CUDA_ARCH to ALL. 
I don't know if it is because of this modification. The caffe was successfully compiled and tested in the same way.
The computer hardware is very good, and there is no such problem in the test on the gtx1060 notebook.
I would be very grateful if I can take the time to answer！！

**Comment by Joneny** [comment]
The computer hardware is very good, and there is no such problem in the test on the gtx1060 notebook.

**Comment by gineshidalgo99** [comment]
You can't use CUDA 8 with a 20XX. Please, read the install doc before posting this repeated issues.
