### ISSUE TITLE
how to reduce joint trembling?

### ISSUE THREAD

**Issue by jmlee1413** [CMU-Perceptual-Computing-Lab/openpose#121]
I tested with various videos, but there was too much trembling on the joints even though the person was standing still. Is there any way I can improve the quality of the calculation through modifying the code or adding flags like '--iteration,' for example ?

**Comment by gineshidalgo99** [comment]
I am sorry, so far the trembling is unavoidable. Some tracking techniques might help as many other issue threads asked for, but in the short time we are not able to do so. If you are able to reduce it, feel free to email me or make a pull request so we can check it. Thanks

**Comment by Tetsujinfr** [comment]
If you use the previous N poses from the previous N frames, you could implement some smoothing scheme to reduce noise/trempling. Eventually that could introduce some lag or inaccuracies, bt that is the rice to pay for less trembling. Now I have no clue on how to implement best, but an naive approach would be to compute the average position of a given node across the last N frames, or do some EWMA type of weighting.
