### ISSUE TITLE
How could I use tracking by python API 

### ISSUE THREAD

**Issue by lxy5513** [CMU-Perceptual-Computing-Lab/openpose#1217]
Thank you for great project, by C++, I can use tracking by `
--tracking 5 --number_people_max 1`   

In python API,  I use
```
 23 params = dict()
 24 params["model_folder"] = "../../models/"
 25 params["tracking"] = 5
 26 params["number_people_max"] = 1 

 30 try:
 31     # Starting OpenPose
 32     opWrapper = op.WrapperPython()
 33     opWrapper.configure(params)
 34     opWrapper.start()

```

But how could I get tracking result, could you please tell the method, THX.

**Comment by gineshidalgo99** [comment]
You can get it in the same way than the normal result,  tracking just replaces the original estimation method for those frames.

**Comment by lxy5513** [comment]
THX

**Comment by fzqneo** [comment]
What does `tracking=5` mean? The documentation only says -1 and 0, and I suppose 1 means enabled?

More generally, is this feature available and under which settings? As in another issue #1259 the author said this is not available yet. I'm a bit confused here.

Any feedback is highly appreciated!
