### ISSUE TITLE
the  joint angle detecting function based on Openpose

### ISSUE THREAD

**Issue by RangerHuyijun** [CMU-Perceptual-Computing-Lab/openpose#1218]
### Issue Summary
  Hi,l want to know is there a function about measuring the angles of some joints of body in  Openpose and thus we can apply this function to sports detection and analysis, such as running economy .Is there any resources or instruction about openpose toward this?

![image](https://user-images.githubusercontent.com/47939398/57517351-375a9180-7349-11e9-8102-b724cdeab57a.png)

**Comment by gineshidalgo99** [comment]
No, there is not. OpenPose provide only 2D information.

**Comment by basicvisual** [comment]
@RangerHuyijun . what resources did you follow to show the overlayed text  , for different angles in the picture above ?

**Comment by Cassie901** [comment]
> @RangerHuyijun . what resources did you follow to show the overlayed text , for different angles in the picture above ?

Hi, I believe one way to do so is to get the coordinates (x,y) of each body keypoint, and then use trigonometry cosine rule to find the angle manually.
