### ISSUE TITLE
VGG19 Features from Python API

### ISSUE THREAD

**Issue by arbues6** [CMU-Perceptual-Computing-Lab/openpose#1219]
Hi, 

I am working with the Python API version and I wonder if it is possible to get the VGG19 features that are fed into the network before pose estimation. 

My first guess was to access the inputNetData matrix in the "datum" object, but dimensions do not match with the output of the 10 layer of a VGG19 network. For instance, my images have a resolution of 1920x1080x3, and this matrix has size 3x368x656 (being 656x368 more or less 1/3 the resolution of the original image). Which information is stored in this matrix then?

Any kind of help will be appreciated, thanks!

**Comment by gineshidalgo99** [comment]
No, we do not provide pointers to the VGG network, as they happen in a different thread and it would require a slow copy from GPU memory to CPU and some time to actually implement it, sorry! But if somebody has done it, feel free to do a PR. Thanks.
