### ISSUE TITLE
Some noise occurs in the output image

### ISSUE THREAD

**Issue by duckyngo** [CMU-Perceptual-Computing-Lab/openpose#1223]
### Issue Summary
I using Openpose to inference my images data to get the skeleton images but there are some image had a problem . There is some noise like the images below:

![neg_12_rendered](https://user-images.githubusercontent.com/22850962/57878036-28497700-7854-11e9-8b0e-4c5095b14d8a.png)
![neg_354_rendered](https://user-images.githubusercontent.com/22850962/57878047-2aabd100-7854-11e9-9f65-11bca2a19fcc.png)
![neu_1319_rendered](https://user-images.githubusercontent.com/22850962/57878055-2e3f5800-7854-11e9-9ca8-d33eed2c719f.png)

Maybe 10 images over 4000 images of output have this problem and It happened randomly with the images. When I try to run another time the error occurs with other images

### Executed Command (if any)
./build/examples/openpose/openpose.bin --net_resolution "1024x576" --scale_number 4 --scale_gap 0.25 --image_dir /workspace/val --display 0 --write_images /workspace/val_preview --face --hand --hand_scale_number 6 --hand_scale_range 0.4 --write_json /workspace/val_ouput -keypoint_scale 3 --disable_blending 

### OpenPose Output (if any)
I output the JSON files and skeleton images

### Errors (if any)
The error images as above

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Version 1.4.0

3. **General configuration**:
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04 , I install OpenPose via Docker which running on GPU, Cuda 8 and Cudnn 6
I build the Docker image via this Dockerfile:
https://gist.github.com/moiseevigor/11c02c694fc0c22fccd59521793aeaa6

4. **Non-default settings**: No

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
    - **cuDNN version**: 6
    - **GPU model** (`nvidia-smi` in Ubuntu): NVIDIA 1080TI

**Comment by gineshidalgo99** [comment]
Hi @duckyngo 

Unfortunately, I am not able to replicate this error in the current OpenPose version. Not sure if there was a bug in that old version that was fixed later. I would recommend trying the latest version of OpenPose from our GitHub, we cannot support random Dockers from other people. Let me know if the error still exists in the latest version!

Best

**Comment by duckyngo** [comment]
Hi @gineshidalgo99 
Thank for your support. I try the latest version of OpenPose and it works without any problems now.
