### ISSUE TITLE
Build fails - file DOWNLOAD HASH mismatch Ubuntu

### ISSUE THREAD

**Issue by peteruhrig** [CMU-Perceptual-Computing-Lab/openpose#1224]
### Issue Summary
CMAKE appears to fail because the downloaded file does not match the one expected.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
cmake ..

### Errors (if any)
```-- Downloading BODY_25 model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch
 
    for file: [/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [56;"Failure when receiving data from the peer"]
 
Call Stack (most recent call first):
  CMakeLists.txt:969 (download_model)
 
 
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch
 
    for file: [/openpose/models/face/pose_iter_116000.caffemodel]
      expected hash: [e747180d728fa4e4418c465828384333]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [56;"Failure when receiving data from the peer"]
 
Call Stack (most recent call first):
  CMakeLists.txt:975 (download_model)
 
 
-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch
 
    for file: [/openpose/models/hand/pose_iter_102000.caffemodel]
      expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [56;"Failure when receiving data from the peer"]
 
Call Stack (most recent call first):
  CMakeLists.txt:977 (download_model)
 
 
-- Models Downloaded.
```

Interestingly, if I run cmake again, it does not check, it just says file "-- Model already exists."

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/WLkKhsKh

2. **OpenPose version**: Latest GitHub code.

3. **General configuration**:
    - **Installation mode**:  (Ubuntu); CMake, ... 
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04 LTS
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...): Ubuntu 16.04 LTS
    - **Release or Debug mode**? (by default: release): [have not changed anything]
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): gcc 5.4.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); 

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10.0.130
    - **cuDNN version**: 7.5.1
    - **GPU model** (`nvidia-smi` in Ubuntu): various, in this case 4x GTX 1080 Ti

I have attached the [CMakeError.log](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3188767/CMakeError.log), but it only mentions something about pthread.

All the best,
Peter

**Comment by gineshidalgo99** [comment]
That was my bad! I updated the link but forgot to update the HASH. Just to confirm, if you ignore the error and continue, it should all work. Is this correct?

Will push a fix very soon regardless. Thanks for pointing it out!!!

**Comment by gineshidalgo99** [comment]
Actually, I just realized, you are facing an Internet issue. The error you says: "Failure when receiving data from the peer". That means it could not download it. Please, try again in a few minutes or manually download them following the doc. Thanks.

**Comment by peteruhrig** [comment]
Ah, thanks. You are right, the file is 0 bytes. But it went to on to build after that and even executes and says it finished successfully, but the output json's do not contain coordinates.

**Comment by gineshidalgo99** [comment]
Yes, that's a Caffe issue, if the model is not the right size (even if it's half the supposed size, e.g., if the download interrupts), then it just outputs 0, without crashing not complaining.

**Comment by Ojperdomoc** [comment]
> 
> 
> Yes, that's a Caffe issue, if the model is not the right size (even if it's half the supposed size, e.g., if the download interrupts), then it just outputs 0, without crashing not complaining, that's why OpenPose then predicts 0 people all the time with any image.
> 
> With the right models, it will work

I had the same problem in Google Colab, when I run the line:

`!cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. && make -j`nproc``

CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:993 (download_model)


-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/face/pose_iter_116000.caffemodel]
      expected hash: [e747180d728fa4e4418c465828384333]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:999 (download_model)


-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/hand/pose_iter_102000.caffemodel]
      expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:1001 (download_model)


-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/content/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/content/openpose/build/CMakeFiles/CMakeError.log".

But this line was working 1 month ago... Do you have some advice for this issue?

Thanks!

**Comment by mdmorar** [comment]
Hi Guys,

Want to reopen this because I'm getting the exact same error and was not getting this about a month ago when I was installing the latest master then. Currently the v1.6 release just got done so im basically updating my project on a Nvidia TX2 which was working fine with the previous master, but now i get the exact error during the models download.

I am on the internet, so this must be a mistmatch error of sorts with hashcodes? Not exactly sure but have never seen this error before. Please assist.

I'm not sure this is an internet issue since I'm on the hard wired network and my internet is fine? Its still doing the same exact thing?

```txt
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Submodule '3rdparty/caffe' (https://github.com/CMU-Perceptual-Computing-Lab/caffe.git) registered for path '../3rdparty/caffe'
Cloning into '/home/nvidia/datacapture/openpose/3rdparty/caffe'...
Submodule path '../3rdparty/caffe': checked out 'b5ede488952e40861e84e51a9f9fd8fe2395cc8a'
Previous HEAD position was b5ede488 Added TX2 JetPack3.3 support
HEAD is now at c95002fb Added support for newer GPUs
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/nvidia/datacapture/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:993 (download_model)


-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/nvidia/datacapture/openpose/models/face/pose_iter_116000.caffemodel]
      expected hash: [e747180d728fa4e4418c465828384333]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:999 (download_model)


-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/nvidia/datacapture/openpose/models/hand/pose_iter_102000.caffemodel]
      expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:1001 (download_model)


-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/home/nvidia/datacapture/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/datacapture/openpose/build/CMakeFiles/CMakeError.log".

```

**Comment by VCucuiat** [comment]
Hi,
I'm facing the same issue with downloading the models for Open Pose. I wondered if you got any further with your error?

**Comment by Jasonnor** [comment]
Same issue here, error log:
```
Cloning into '3rdparty/caffe'...
Submodule path '../3rdparty/caffe': checked out 'b5ede488952e40861e84e51a9f9fd8fe2395cc8a'
Previous HEAD position was b5ede48... Added TX2 JetPack3.3 support
HEAD is now at c95002f... Added support for newer GPUs
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch
```

**Comment by kruthikakr** [comment]
Previous HEAD position was b5ede488 Added TX2 JetPack3.3 support
HEAD is now at c95002fb Added support for newer GPUs
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [7;"Couldn't connect to server"]


Again the hitting the same issue..
Using this colab https://colab.research.google.com/github/miu200521358/motion_trace_colab/blob/master/Openpose1_6_0.ipynb?authuser=1#scrollTo=bhCJ4zsf2AMa
Any leads ?
