### ISSUE TITLE
openpose.bin silently exits when processing folder with more than 16 images

### ISSUE THREAD

**Issue by elmuz** [CMU-Perceptual-Computing-Lab/openpose#1226]
### Issue Summary
openpose.bin silently exits when processing folder with more than 16 images. Up to 16 images the folder is processed as expected. The error has appeared these days, I had an older version and it was working fine. Today I have tried v1.5.0 and I saw this behavior. Then, I tried  to build some previous commits and the error was still present (I tried one commit from April and one from March). With commit '0d57f78' (February) worked again.

### Executed Command (if any)
`./openpose.bin -logging_level 0 -disable_multi_thread -image_dir /mnt/images`

### OpenPose Output (if any)
`/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():196
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():159
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseMode():11
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():32
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():81
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToHeatMapScaleMode():110
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():136
/root/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():136
Starting thread(s)...
/root/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():98
/root/openpose/src/openpose/producer/producer.cpp:createProducer():413
`

### Type of Issue
- Help wanted

2. **OpenPose version**:
Error is present in v1.5.0, 13dd4a9 and 214808f. Commit 0d57f78 works fine. I didn't try any other version.

3. **General configuration**:
    - All tests done in docker with seeding image "nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04", OpenCV 4.x manually built and OpenPose built through CMake.

**Comment by gineshidalgo99** [comment]
Hi, I continuously test on the latest version a set of 5000 images, and it works perfectly fine in there. Feel free to share the images that causes your error so I can test them on my machine, you can email them to gines@alumni.cmu.edu
Other than that, I would recommend trying with OpenCV 2.4 (the default that comes with sudo apt-get), because that is the setting I use the most. Let me know if this solves your issue.

**Comment by elmuz** [comment]
It is not a matter of which images have been processed. Same image copied/pasted 16 times are processed correctly, copied/pasted once more and the folder is kind of ignored.
Unfortunately OpenCV version in not an option for us. Is `-logging_level 0` the most verbose one?

**Comment by gineshidalgo99** [comment]
`logging` 0 is the most verbose, but you are running in Release mode.

Please, also compile OpenPose in Debug mode and run the same configuration. That will provide way more verbose, and might be able to know in which function OpenPose is crashing. Thanks!

**Comment by elmuz** [comment]
After cleaning old docker images I am not able to reproduce the problem anymore. Now also latest builds are fine. I suspect there were something wrong with some docker cache, but the behavior (in creating the producer I think) was really strange. Anyway, I will close the issue. Thank you anyway for the time you dedicated to me.

**Comment by elmuz** [comment]
Ok, it came up again. I email with details/testing images.

**Comment by gineshidalgo99** [comment]
[Sorry, still on my to-do list]
