### ISSUE TITLE
doc/installation.md#3d-reconstruction-module 404 Not found

### ISSUE THREAD

**Issue by kirk3207** [CMU-Perceptual-Computing-Lab/openpose#1227]
### Issue Summary
 doc/installation.md#3d-reconstruction-module 404 Not found

### Executed Command (if any)
No

### OpenPose Output (if any)
No

### Errors (if any)
No

### Type of Issue
- Other (type your own type)
Maybe missing file?
The page is under openpose/doc/modules/3d_reconstruction_module.md
The Installation one doc/installation.md#3d-reconstruction-module is missing

**Comment by gineshidalgo99** [comment]
Thanks for the catch! This is the right link:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#3d-reconstruction-module

And I will add it into the next OpenPose commit! :)
