### ISSUE TITLE
Fatal error: 'opencv2/highgui/highgui.hpp' file not found

### ISSUE THREAD

**Issue by sabinayakc** [CMU-Perceptual-Computing-Lab/openpose#1228]
### Issue Summary
I am trying to build Open Pose on Mac Mojave . I followed the installation and installed prerequisites by running the scripts inside the repo. I configured and generated files using CMAKE but when I run `make -j  nproc` I get an error. Look at image below.

### OpenPose Output (if any)
![image](https://user-images.githubusercontent.com/13154166/57991246-36c1a980-7a73-11e9-989f-8cdcd4748355.png)

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. https://pastebin.com/ZUNJfeat
https://pastebin.com/5Ud357CQ

2. Latest Version

3. **General configuration**:
    - CMAKE
    - MAC OSX Mojave
    - Macbook Pro 2018

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled 

6. If **GPU mode** issue:
    - **OPEN-CL**

8. If **Python** API:
    - **Python version**: 3.7,

![image](https://user-images.githubusercontent.com/13154166/57991384-1c3c0000-7a74-11e9-9efd-6bc38ce711df.png)

**Comment by soulslicer** [comment]
Hmm, you are right, some recent update has broken caffe once again. I will take a look at it

**Comment by soulslicer** [comment]
This is a quick fix:

```
cd 3rdparty/caffe
git reset --hard HEAD
git checkout fe2a1102
wget https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3203244/mac_patch.txt
git apply mac_patch.txt
```

Then go back to your build folder and rebuild

**Comment by soulslicer** [comment]
It's hidden in the instructions

`
You may also have to apply the following patch if you have the latest OSX 10.14. It can be done as follows:

cd 3rdparty/caffe; git apply ../../scripts/osx/mac_opencl_patch.txt
`

**Comment by sabinayakc** [comment]
@soulslicer Thank you for the reply. Applying the patch fixed my issue.
