### ISSUE TITLE
Problems with c#

### ISSUE THREAD

**Issue by ale22596** [CMU-Perceptual-Computing-Lab/openpose#1229]
I'm at the very beginning of programming, and I want to know how to run openpose in c# code... I'm sure that it's just me and i'm dumb, but putting the path of the .exe files in the c# code doesn't work

**Comment by gineshidalgo99** [comment]
OpenPose is for Python and C++, we do not officially support C# (I am not very familiar with it so I cannot help).

Anyone feel free to answer, but I will close this as it is not an OpenPose bug/issue.

**Comment by ale22596** [comment]
Thank you! So does the DEMO only open from the command windows?

**Comment by gineshidalgo99** [comment]
That is correct, Windows/Ubuntu/Mac command line. From C#, I assume you should be able to call command line instructions, but again, C# is out of our scope here.

**Comment by ale22596** [comment]
Thank you a lot! I'll try another way to process the files, maybe with C++
keep up the good work! I hope I'll become as good as you! :)

**Comment by soulslicer** [comment]
You can consider the Python API as well
