### ISSUE TITLE
Make error when building openpose

### ISSUE THREAD

**Issue by ThanasisTs** [CMU-Perceptual-Computing-Lab/openpose#1231]
Hello,

I am trying to install openpose but when I am building it (running the command make -j`nproc` as told in the instructions) I get the following error.

nvcc fatal   : Unsupported gpu architecture 'compute_61'

Furthermore, I have installed CUDA 10.1, cudnn 7.5 but when i run the command nvcc --version it says that my CUDA compilation release is 7.5. Does this have anything to do with the above-mentioned error? How can I solve this? Thanks in advance.

**Comment by ThanasisTs** [comment]
I added CUDA 10.1 to my PATH and this fixed the problem.

**Comment by gineshidalgo99** [comment]
Otherwise, if that happens, it means you are using a CUDA version that does not support the GPU architecture of your GPU (e.g., Nvidia 20XX cards require CUDA >= 10).
