### ISSUE TITLE
Understanding the op::Wrapper and its workers

### ISSUE THREAD

**Issue by ChrizzyM87** [CMU-Perceptual-Computing-Lab/openpose#1233]
Dear people,
I need some clearance about how the `op::Wrapper` and its workers are scheduled.
My setup is the following: 
I got already a dedicated thread for openpose in my application. Therefore I decided to use the `op::Wrapper` and call it's `exec()` function. I implemented a custom `WUserInput` class derived from `op::WorkerProducer` and a custom `WUserOutput` class derived from `op::WorkerConsumer`.
In `WUserInput::workProducer` everytime a frame is set from the outside a `op::Datum` ptr is returned, like in examples/tutorial_wrapper/2_user_synchronous.cpp. In `WUserOutput::workProducer()` keypoints are only send to the standard output for now.

I'm adding these two workers via `setWorkerInput()` / `setWorkerOutput()` to the `op::wrapper`. Second argument `workerOnNewThread` is set to false.
So I expected that the InputWorker, the actual OpenPose worker, and the output worker are executed in the same thread one after another.
But actually they are executed in different threads and I dont understand why. Even the `WUserOutput::workConsumer` function is executed in an infinite loop concurrently with the `WUserInput::workProducer`.

Can someone shed some light on this? I'm working with openpose v1.3. Thanks!!

**Comment by gineshidalgo99** [comment]
To be sure, your question is how to enforce that they are all in the same thread? For that, you need to use `--disable_multi_thread`, or analogously, check the tutorial cpp example to see how that flag is used to call a Wrapper function with similar name. `workerOnNewThread` affects whether those functions are in the same thread than analogous (and very fast) functions. However, the OpenPose network (the bottleneck) is always on a separate thread, unless `--disable_multi_thread` is set.

Let me know if you need some more insights (and I would keep answering even thought I am closing it). Best

**Comment by ChrizzyM87** [comment]
Hey! Thanks a lot! And yes - I want that they all run in the same thread and I need some more insights ;)
If I call the op::Wrapper::disableMultiThreading() function I directly get a SIGABRT when calling the exec() function. The following is outputted:
>Error:
> Missing thread id 18446744073709551615 of 18446744073709551615.
> 
> Coming from:
> - /builds/Bibliotheken/DockerBase/openpose_package/include/openpose/thread/threadManager.hpp:checkAndCreateEmptyThreads():478
> - /builds/Bibliotheken/DockerBase/openpose_package/include/openpose/thread/threadManager.hpp:checkAndCreateEmptyThreads():491
> - /builds/Bibliotheken/DockerBase/openpose_package/include/openpose/thread/threadManager.hpp:multisetToThreads():461
> - /builds/Bibliotheken/DockerBase/openpose_package/include/openpose/thread/threadManager.hpp:exec():202
> - /builds/Bibliotheken/DockerBase/openpose_package/include/openpose/wrapper/wrapper.hpp:exec():424
terminate called after throwing an instance of 'std::runtime_error'
  what():  
> Error:
> Missing thread id 18446744073709551615 of 18446744073709551615.
> 
> Coming from:
> [...]

The op::wrapper in this case is just instanciated and configured with a default `op::WrapperStructPose`. The thread its running in is a QThread (Qt Environment).

To find a solution I built the openpose examples and executed `17_synchronous_custom_all_and_datum.bin` (by the way I switched to openpose 1.5.0 in the meantime) with the --disable_multi_thread flag set, but this one runs without errors.

You got another hint for me? 
I thought about compiling openpose in DEBUG mode tomorrow to get deeper understanding what's happening inside. Is there anything I need to consider, like setting some flags, or is it sufficient to run cmake with DEBUG flag and recompile?

**Comment by gineshidalgo99** [comment]
Sorry I could not help more, but glad it is working!

I would recommend version 1.5, if you say that one is working better. (It is also about 20% faster than version 1.3 for the BODY_25 model).
