### ISSUE TITLE
Will multiple GPUs increase the frame rate?

### ISSUE THREAD

**Issue by ed-spatialsauce** [CMU-Perceptual-Computing-Lab/openpose#1234]
If I build a machine with multiple GPUS (example x4 GTX 1080) will I see a significant increase in performance?

I am currently using 1x GTX 1070. In the Unity example scene I get average 11 FPS. I am hoping I can increase the FPS by simply throwing more GPUs at it.

**Comment by gineshidalgo99** [comment]
Yes, mostly linearly. If 1 1070 is ~11 GPS, 2 should be ~20-22FPS. Check the speed benchmarks in doc/faq.md
