### ISSUE TITLE
Question : Should the new tracking feature work in CPU ONLY mode?

### ISSUE THREAD

**Issue by YehonatanCaspi** [CMU-Perceptual-Computing-Lab/openpose#1235]
It appears that with an i7  it works,
but with i5  it does not work (it runs the same way as without the flag)

Both tried with the new 1.5 release (CPU ONLY)

Thanks

**Comment by gineshidalgo99** [comment]
The problem might be than the CPU version is super slow for the default OpenPose. Even if the tracking helps 2 or 3 frames, the one that uses the detection will be super slow.

I'd say that if you reduce the `--net_resolution` (less accuracy but faster), you will see tracking helps more (because the detection will be faster). Try with/without tracking with that lower resolution.

(closing this but feel free to answer if I am wrong)

**Comment by YehonatanCaspi** [comment]
Oh sorry forgot to mention the flags im using-
bin\OpenPoseDemo.exe -net_resolution 320x176 -model_pose COCO -number_people_max 1 
It runs on 0.7 fps in the i7 and 0.5 fps on the i5.
Thing is that if adding the tracking flag (bin\OpenPoseDemo.exe -net_resolution 320x176 -model_pose COCO -number_people_max 1 -tracking 100) , the success rate of it in the i7 are much higher (since opening this issue i succeeded to run the tracking on the i5, but not consistently, might be because of the cpu limits but i realy cant tell).

The issue for me i think is that the tracking field does not always "kicks in", when its not , the running looks like you are just running without the flag .
Hope im clear now

**Comment by gineshidalgo99** [comment]
If you are using 100% the same flags and the only difference is the CPU, then it must be the CPU limiting. OpenPose does not change depending on the CPU, it behaves the same, so "kicking in" would happen in both of them or in none.

Also, I am realizing that by using smaller net resolution, the keypoints are less accurate so the tracking will behave more poorly. So I'd not recommend tracking on lower `net_resolution` given the lower quality of the OpenPose detection. I would highly recommend at least a cheap 4GB Nvidia to boost the speed to 5-10 FPS so then you can use tracking to boost it even more.

**Comment by YehonatanCaspi** [comment]
Thanks!
