### ISSUE TITLE
07_hand_from_image.py  has Error: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

### ISSUE THREAD

**Issue by maskedrider555** [CMU-Perceptual-Computing-Lab/openpose#1239]
### Issue Summary
Try to run python example -tutorial_api_python/ 07_hand_from_image.py-  has error
which is Error: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

### Errors (if any)

Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Coming from:
- /home/jin/temp/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1187
- /home/jin/temp/openpose/include/openpose/wrapper/wrapper.hpp:start():442
- /home/jin/temp/openpose/python/openpose/openpose_python.cpp:start():184

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted

### Your System Configuration
1. **Whole console output** :  https://pastebin.com/3310qWr6

2. **OpenPose version**:  Latest Version
3. **General configuration**:
    - **Installation mode**:  Ubuntu CMake
    - **Operating system**  in Ubuntu 
    - **Operating system version** Ubuntu 16
    - **Release or Debug mode**?  Release
    - **Compiler** : CMake 5.4.0 (Ubuntu)

4. **Non-default settings**:
    - **3-D Reconstruction module added**?: No
    - **Any other custom CMake configuration with respect to the default version**? :

     In cmake-gui

     BUILD_PYTHON = Yes
     CUDA_ARCH = Manual 
     CUDA_ARCH_BIN = 30 35 50 52 60 61
     CUDA_ARCH_PTX = 50  

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose,
    - **CMake version** : 3.5.1
    - **OpenCV version**: opencv-3.3.0

6. If **GPU mode** issue:
    - **CUDA version** : 8.0.61
    - **cuDNN version**: 5.1
    - **GPU model** : GeForce RTX 2060 

8. If **Python** API:
    - **Python version**: 3.5
    - **Numpy version** : 1.16.3

**Comment by gineshidalgo99** [comment]
Will push a fix soon today (and update you here).

In the meantime if you need it, in file `include/openpose/wrapper/wrapperAuxiliary.hpp`, replace `addCvMatToOpOutputInCpu = addCvMatToOpOutput && (resizeOnCpu || !renderOutputGpu);`
by
`addCvMatToOpOutputInCpu = addCvMatToOpOutput && (resizeOnCpu || !renderOutputGpu || wrapperStructPose.poseMode != PoseMode::Enabled);`

**Comment by gineshidalgo99** [comment]
Fixed! Sorry for the bug! Please download the latest version, and let me know here if you face any other issue with it! Best

**Comment by maskedrider555** [comment]
Thanks! 
I download the latest version and I run "07_hand_from_image.py" 
It works good!

But I have the other problem
"09_keypoints_from_heatmaps.py"  not works with error 
(Every python exmaples works except "09_keypoints_from_heatmaps.py")

**This is my error when I run "09_keypoints_from_heatmaps.py"**

Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
Kernel only implemented for 8x resize. Notify us if this error appears.

Coming from:
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeBase.cu:resizeAndMergeGpu():334
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeBase.cu:resizeAndMergeGpu():501
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeCaffe.cpp:Forward_gpu():192
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeCaffe.cpp:Forward():144
- /home/jin/temp/openpose/src/openpose/pose/poseExtractorCaffe.cpp:forwardPass():626
- /home/jin/temp/openpose/src/openpose/pose/poseExtractor.cpp:forwardPass():53
- /home/jin/temp/openpose/include/openpose/pose/wPoseExtractor.hpp:work():107
- /home/jin/temp/openpose/include/openpose/thread/worker.hpp:checkAndWork():93

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Kernel only implemented for 8x resize. Notify us if this error appears.

Coming from:
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeBase.cu:resizeAndMergeGpu():334
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeBase.cu:resizeAndMergeGpu():501
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeCaffe.cpp:Forward_gpu():192
- /home/jin/temp/openpose/src/openpose/net/resizeAndMergeCaffe.cpp:Forward():144
- /home/jin/temp/openpose/src/openpose/pose/poseExtractorCaffe.cpp:forwardPass():626
- /home/jin/temp/openpose/src/openpose/pose/poseExtractor.cpp:forwardPass():53
- /home/jin/temp/openpose/include/openpose/pose/wPoseExtractor.hpp:work():107
- /home/jin/temp/openpose/include/openpose/thread/worker.hpp:checkAndWork():93
- [All threads closed and control returned to main thread]
- /home/jin/temp/openpose/src/openpose/utilities/errorAndLog.cpp:checkWorkerErrors():280
- /home/jin/temp/openpose/include/openpose/thread/threadManager.hpp:stop():243
- /home/jin/temp/openpose/include/openpose/wrapper/wrapper.hpp:stop():455
- /home/jin/temp/openpose/python/openpose/openpose_python.cpp:stop():196

**Comment by gineshidalgo99** [comment]
Sorry, that one was a trickier error. Solved now, please, try again the latest version and let me know again if you face any other issue. Best
