### ISSUE TITLE
Hand-related flags

### ISSUE THREAD

**Issue by mocialov** [CMU-Perceptual-Computing-Lab/openpose#124]
Hello,
I am not able to get --hand flag. --help flag does not mention availability of the hand flag either. Am I using the wrong version?

**Comment by gineshidalgo99** [comment]
As the repository mentions in the README (and the error message that pops if you use `--hand` also says the same), hands is not released yet.

**Comment by mocialov** [comment]
Oops, I used older version, it did not tell me that the hand was not implemented. Do you have an estimate for when the hand functionality may be released?

**Comment by gineshidalgo99** [comment]
We expect it by the end of this week. It is not a fix date, but it'd be most probably be released by then.

**Comment by gineshidalgo99** [comment]
The hands detection code has just been released. And it works on Windows. Post new issue thread if errors with the new Windows installation appear.

**Comment by mocialov** [comment]
Already testing. Thanks!
