### ISSUE TITLE
One person's body parts are split between multiple people in keypoints file

### ISSUE THREAD

**Issue by stuartcrobinson** [CMU-Perceptual-Computing-Lab/openpose#1240]
### Issue Summary
input image:
[000099.png.zip](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3225078/000099.png.zip):
![000099](https://user-images.githubusercontent.com/12928716/58441216-29797000-80ae-11e9-9b4e-61d7a3a3fbe5.png)

rendered image:
![000099_rendered](https://user-images.githubusercontent.com/12928716/58440407-cd135200-80a7-11e9-84fa-b4b7835b7818.png)

the coordinates of the right wrist in this image are `(607.85, 419.746)`

the larger tennis player is the first of 5 people in the keypoints file:

[000099_keypoints.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3225038/000099_keypoints.txt)

but the right wrist and elbow for this person are all 0s.

i measured each `person`'s "size" = the distance from their neck to their midhip points.  this file lists each person's size, and each body part's coordinates and score per line:

[people_coords_sizes.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3225058/people_coords_sizes.txt)

here are the coordinates for the largest person detected, with a "size" (distance from neck to hips) of 93.148...

```
size 93.14818350349081
{
    "Nose": "(0, 0)  0",
    "Neck": "(660.662, 366.798)  0.858972",
    "RShoulder": "(0, 0)  0",
    "RElbow": "(0, 0)  0",
    "RWrist": "(0, 0)  0",
    "LShoulder": "(0, 0)  0",
    "LElbow": "(0, 0)  0",
    "LWrist": "(0, 0)  0",
    "MidHip": "(684.193, 456.925)  0.792426",
    "RHip": "(682.23, 453.053)  0.734401",
    "RKnee": "(631.37, 472.688)  0.922731",
    "RAnkle": "(664.685, 527.481)  0.760581",
    "LHip": "(684.289, 458.984)  0.841197",
    "LKnee": "(627.387, 513.86)  0.885806",
    "LAnkle": "(674.486, 580.396)  0.849664",
    "REye": "(0, 0)  0",
    "LEye": "(0, 0)  0",
    "REar": "(0, 0)  0",
    "LEar": "(0, 0)  0",
    "LBigToe": "(646.964, 592.197)  0.908578",
    "LSmallToe": "(654.86, 598.006)  0.899656",
    "LHeel": "(686.254, 584.358)  0.91614",
    "RBigToe": "(654.817, 545.147)  0.305786",
    "RSmallToe": "(654.839, 543.166)  0.278957",
    "RHeel": "(674.477, 531.41)  0.551508"
}
```

and here is the 4th "person" detected (actually just some missing body parts from person 1):
```
size -1
{
    "Nose": "(0, 0)  0",
    "Neck": "(0, 0)  0",
    "RShoulder": "(662.635, 364.907)  0.790921",
    "RElbow": "(635.32, 411.871)  0.843194",
    "RWrist": "(607.85, 419.746)  0.817764",
    "LShoulder": "(0, 0)  0",
    "LElbow": "(0, 0)  0",
    "LWrist": "(0, 0)  0",
    "MidHip": "(0, 0)  0",
    "RHip": "(0, 0)  0",
    "RKnee": "(0, 0)  0",
    "RAnkle": "(0, 0)  0",
    "LHip": "(0, 0)  0",
    "LKnee": "(0, 0)  0",
    "LAnkle": "(0, 0)  0",
    "REye": "(0, 0)  0",
    "LEye": "(0, 0)  0",
    "REar": "(660.68, 337.521)  0.577083",
    "LEar": "(0, 0)  0",
    "LBigToe": "(0, 0)  0",
    "LSmallToe": "(0, 0)  0",
    "LHeel": "(0, 0)  0",
    "RBigToe": "(0, 0)  0",
    "RSmallToe": "(0, 0)  0",
    "RHeel": "(0, 0)  0"
}
```

I don't expect there to be any quick fix for this, just thought I would pass it along.

Thank you for an amazing tool!

### Executed Command (if any)
`./build/examples/openpose/openpose.bin --image_dir ~/repos/computervision/andre_aigassi/images/img/in --write_images ~/repos/computervision/andre_aigassi/images/img/out --write_json ~/repos/computervision/andre_aigassi/images/img/out`

### OpenPose Output (if any)
[000099_keypoints.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3225038/000099_keypoints.txt)
`Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
---------------------------------- WARNING ----------------------------------
We have introduced an additional boost in accuracy of about 0.5% with respect to the official OpenPose 1.4.0 (using default settings). Currently, this increase is only applicable to CUDA version, but might eventually be ported to CPU and OpenCL versions. Therefore, CPU and OpenCL results might vary. Nevertheless, this accuracy boost is almost insignificant so CPU and OpenCL versions can be safely used, they will simply provide the exact same accuracy than OpenPose 1.4.0.
-------------------------------- END WARNING --------------------------------
OpenPose demo successfully finished. Total time: 14.120181 seconds.`

### Type of Issue
- Execution error

### Your System Configuration
2. **OpenPose version**:
```
> git log
commit a0a80b3061d0346c75384f26304200ba648ba36e (HEAD -> master, origin/master, origin/HEAD)
Author: Gines Hidalgo <gineshidalgo99@gmail.com>
Date:   Fri May 17 12:12:47 2019 -0400

    Calibration with more verbose & better NVCaffe doc

```

3. **General configuration**:
    - **Installation mode**:
 CMake GUI
    - **Operating system**
macOS High Sierra 10.13.4

7. If **CPU-only mode** issue:
    - Total **RAM memory** available:
16 GB

8. If **Python** API:
python 3.6

**Comment by stuartcrobinson** [comment]
same thing for this image:
[000338.png.zip](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3225091/000338.png.zip)
closeup of rendered image:
<img width="131" alt="image" src="https://user-images.githubusercontent.com/12928716/58441470-75c5af80-80b0-11e9-8dd5-bc12d91aa09f.png">
right arm is listed as belonging to a different person
[000338_keypoints.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3225093/000338_keypoints.txt)

**Comment by gineshidalgo99** [comment]
Hi, sorry for the delay! This was an issue only for CPU version, CUDA/OpenCL versions were different and had already fixed this issue.
I have just now pushed a fix for the CPU version (e.g., Mac version) so now that issue is solved.
I tested your image and successfully gives only 2 people now.
Please, try the latest version and let me know if you have any other issues, thanks!
