### ISSUE TITLE
Ho get the first biggest Person in the frame? getBiggestPerson() not working

### ISSUE THREAD

**Issue by alexadp1087** [CMU-Perceptual-Computing-Lab/openpose#1243]
Hello, referred to #180,
in the new version of OpenPose, it seems that  getBiggestPerson() function is not working for get the data about only the first big one person inside the frame.
Any solution?

Thank you

**Comment by gineshidalgo99** [comment]
Why does getBiggestPerson() not work in the latest version? Share/explain all your code/edits in order to get help (+ add your hw config). All in a new msg so I am notified. Thanks. (Will close it temporarily until that is added).
