### ISSUE TITLE
VS2017: Error generating openpose_generated_renderFace.cu.obj?

### ISSUE THREAD

**Issue by kebiao** [CMU-Perceptual-Computing-Lab/openpose#1245]
Hello All,

I followed installation instructions and Generated successfully.
VS2017 build error!

**VS2017 logs:**
1>------ Build started: Project: openpose, Configuration: Release x64 ------
1>Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/face/Release/openpose_generated_renderFace.cu.obj
1>CMake Error at openpose_generated_renderFace.cu.obj.Release.cmake:219 (message):
1>  Error generating
1>  D:/openpose-1.5.0/build/src/openpose/CMakeFiles/openpose.dir/face/Release/openpose_generated_renderFace.cu.obj
1>
1>
1>f:\Program Files (x86)\2017\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "openpose.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Environment:**
Windows7、CUDA v10.0.130、cuDNN 7.3.0.29、VS2017、CMake3.10.1、GTX1050

C:\Users\DEV001>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by kebiao** [comment]
`C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi
Tue Jun 04 11:17:30 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 417.35       Driver Version: 417.35       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050   WDDM  | 00000000:01:00.0  On |                  N/A |
| 29%   34C    P8    N/A / 100W |    310MiB /  2048MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+`

**Comment by gineshidalgo99** [comment]
This is an issue with CUDA, please make sure to install CUDA as the doc recommends. Thanks
