### ISSUE TITLE
failure case

### ISSUE THREAD

**Issue by alishsuper** [CMU-Perceptual-Computing-Lab/openpose#1246]
Hello everyone!
I just got this error information.

![image](https://user-images.githubusercontent.com/14852495/58864824-02432400-86e8-11e9-9229-a36727806cb8.png)

Can you explain to me why this could happen?

**Comment by gineshidalgo99** [comment]
Unfortunately, that is an expected error for this low-quality images. :(

Tech reason: the algorithm has not been trained with those kind of images so it will fail more often there.
