### ISSUE TITLE
Could NOT find vecLib (missing: vecLib_INCLUDE_DIR)

### ISSUE THREAD

**Issue by vpview** [CMU-Perceptual-Computing-Lab/openpose#1248]
### Type of Issue
Compilation/installation error

I am following the installation guide that is on github docs. Everything works until the build step. When i run the **make -j `nproc`** command, I get the error below, and I do not know how to solve it.

### My System Configuration
1. **Whole console output**: https://pastebin.com/Uh8FG0Hh
It is written in the link above, but briefly here is the error:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find vecLib (missing: vecLib_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindvecLib.cmake:24 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:135 (find_package)
  CMakeLists.txt:49 (include)
```

2. **OpenPose version**: Latest GitHub code (cloned today 5 Jun 2019)

3. **General configuration**:
    - **Installation mode**: CMake 
    - **Operating system** macOS Mojave 10.14.14

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** cmake version 3.14.5
    - **OpenCV version**: openCV4

7. **CPU-only mode**

**Comment by soulslicer** [comment]
Did you git apply the patch

**Comment by vpview** [comment]
No, how would I do that? Could you please give some details. Thank you so much.

**Comment by soulslicer** [comment]
Please check the mac installation instructions.

**Comment by vpview** [comment]
That worked. Now I just need it to work faster. Thank you for your help!

**Comment by hackerfemo** [comment]
I think the patch link is here: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#mac-osx-version

**Comment by tmedeirosClostra** [comment]
I have run into this same issue on macOS Catalina 10.15.3 but if I attempt to apply the patch from the link provided by @hackerfemo I get the following output.

_error: patch failed: cmake/Modules/FindvecLib.cmake:12
error: cmake/Modules/FindvecLib.cmake: patch does not apply
error: src/caffe/layers/malis_loss_layer.cpp: No such file or directory_

Any ideas?

**Comment by seojpark91** [comment]
> I have run into this same issue on macOS Catalina 10.15.3 but if I attempt to apply the patch from the link provided by @hackerfemo I get the following output.
> 
> _error: patch failed: cmake/Modules/FindvecLib.cmake:12 error: cmake/Modules/FindvecLib.cmake: patch does not apply error: src/caffe/layers/malis_loss_layer.cpp: No such file or directory_
> 
> Any ideas?

I had the same problem! Did you solve the issue? I did the file search to find veclib.h on my mac and manually inserted my path. Go to build/caffe/src/openpose_lib-build/CMakeCache.txt and manually change this:
vecLib_INCLUDE_DIR:PATH=vecLib_INCLUDE_DIR-NOTFOUND  to 

vecLib_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/

**Comment by rafayk7** [comment]
@tmedeirosClostra I'm having the same issue as you - on macOS Catalina 10.15.4. This is after following @appleweed's instructions here : https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/423.  Let me know if you find a fix!

**Comment by soulslicer** [comment]
Oh man..dont tell me OSX broke Caffe again :(

**Comment by rafayk7** [comment]
@seojpark91 That didn't seem to work for me - did you do anything else to solve it?

**Comment by seojpark91** [comment]
@rafayk7 Apply patch also did not work for me with the same error that @tmedeirosClostra had. Were you able to locate your vecLib.h file and put that path CMakeCache.txt?? After it found vecLib path, I was able to build it successfully.

**Comment by soulslicer** [comment]
@seojpark91 can i know how you fixed it?

**Comment by seojpark91** [comment]
@soulslicer Hi, as I mentioned it above, I just changed this part : vecLib_INCLUDE_DIR:PATH=vecLib_INCLUDE_DIR-NOTFOUND in this text file: openpose/build/caffe/src/openpose_lib-build/CMakeCache.txt

I just manually changed above part to vecLib_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/

Then, it found vecLib and worked. Just try to find whether your vecLib.h is also in the above path. I have Mojave 10.14.5, so yours might be different.

**Comment by ideo65** [comment]
I had the same problem and I fixed it with @seojpark91 solution, thanks a lot !
I'm on Mojave 10.14.6

**Comment by stephanwu89** [comment]
Great same worked for me as well with Catalina!

**Comment by sam8401** [comment]
Thanks worked for me too. But I believe an ideal "solution" will be to install your own Caffe as stated here

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#mac-osx-version

**Comment by AngeloRega** [comment]
Work on Big Sur

> @soulslicer Hi, as I mentioned it above, I just changed this part : vecLib_INCLUDE_DIR:PATH=vecLib_INCLUDE_DIR-NOTFOUND in this text file: openpose/build/caffe/src/openpose_lib-build/CMakeCache.txt
> 
> I just manually changed above part to vecLib_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/
> 
> Then, it found vecLib and worked. Just try to find whether your vecLib.h is also in the above path. I have Mojave 10.14.5, so yours might be different.

**Comment by gbengailesanmi** [comment]
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/

This worked for me, but only put me in more hot water.
In file included from /opt/homebrew/include/google/protobuf/io/coded_stream.h:112:
In file included from /opt/homebrew/include/absl/strings/cord.h:79:
In file included from /opt/homebrew/include/absl/container/inlined_vector.h:53:
In file included from /opt/homebrew/include/absl/container/internal/inlined_vector.h:31:
In file included from /opt/homebrew/include/absl/container/internal/compressed_tuple.h:40:
/opt/homebrew/include/absl/utility/utility.h:82:12: error: no member named 'in_place_t' in namespace 'std'
using std::in_place_t;
      ~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[5]: *** [src/caffe/CM
