### ISSUE TITLE
Considering a deploy to PyPi (aka pip)?

### ISSUE THREAD

**Issue by fabian57fabian** [CMU-Perceptual-Computing-Lab/openpose#1250]
Since the python version is available but installing it means having to deal with a huge amount of trouble, would it be nice to have a module and just call 'pip install openpose' with needed requirements (like having CUDA and cudnn working for GPU version).
That would solve a lot of troubles and avoid installing Visual Studio on windows and getting all sorts of errors  (windows, ubuntu and mac).

**Comment by gineshidalgo99** [comment]
Very true, but we do not have the time to deal with this unfortunately sorry! :(

**Comment by davidpagnon** [comment]
Any news on that? :)
