### ISSUE TITLE
How is MPI implemented compared to COCO(Body_25)?

### ISSUE THREAD

**Issue by benjaminabruzzo** [CMU-Perceptual-Computing-Lab/openpose#1251]
### Type of Issue
- Question
Is the MPI skeleton model implemented using the same coco/body_25 procedure with different keypoint locations, or is ti implemented using a different mechanism?

**Comment by gineshidalgo99** [comment]
Same, but MPII dataset is worse so the accuracy is way lower for in-the-wild scenarios.

**Comment by benjaminabruzzo** [comment]
Okay, thank you!
