### ISSUE TITLE
Tons of error: /usr/bin/ld: cannot find -l<Libaray Name>

### ISSUE THREAD

**Issue by lxwgcool** [CMU-Perceptual-Computing-Lab/openpose#1252]
### Issue Summary
I get tons of error while compile openpose. The error as below:

/usr/bin/ld: cannot find -l_stats.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -lmvn.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -lstatlib.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_fftpack.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -lconvolve.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -lvode.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_test_multivariate.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_quadpack.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -llsoda.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_odepack.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_test_odeint_banded.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_dop.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_cobyla.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_zeros.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_slsqp.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_bglu_dense.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -lmoduleTNC.cpython-35m-x86_64-linux-gnu
/usr/bin/ld: cannot find -l_minpack.cpython-35m-x86_64-linux-gnu
.....
.....
(More than 200 similar errors as above)

### Executed Command (if any)
1: Setting ENVs
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export CPATH=/usr/local/cuda/include:$CPATH
export CPATH=/usr/local/include/opencv:/usr/local/include/opencv2:$CPATH

2: cmake
cmake -DOpenCV_INCLUDE_DIRS=/usr/local/include/opencv -DOpenCV_LIBS_DIR=/usr/local/lib/ ../openpose

3: make
make -j 8

### OpenPose Output (if any)
Not apply

### Errors (if any)
Errors as mentioned above.

### Type of Issue
Compilation/installation error

### Your System Configuration
1. System Info
Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:    16.04
Codename:    xenial 

2. **OpenPose version**: 
Latest GitHub code
(git clone --recursive https://github.com/CMU-Perceptual-Computing-Lab/openpose.git)

3. **General configuration**:
    - **Installation mode**: 
　　CMake
    - **Operating system**
　　Linux
    - **Operating system version** 
       Ubuntu 16.04
    - **Release or Debug mode**
      by default: release
    - Compiler 
      gcc 5.4.0

4. **Non-default settings**:
    No

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
      cmake 3.5.1
      cuda: 10.0
      cudnn: 7.5.0.56-1
      opencv: 3.4.6 
      python: 3.5.2

6. If **GPU mode** issue:
    - **CUDA version**  10.0
    - **cuDNN version**:  7.5.0.56-1
    - **GPU model**: NVIDIA Tesla K40m

**Comment by gineshidalgo99** [comment]
Sorry, this are 3rd party issues, rather than OP-itself, we can't help here sorry!

**Comment by lxwgcool** [comment]
Thanks for your reply. I have found the reason. I  forget add the line below:
-DOpenCV_CONFIG_FILE=/usr/local/lib/cmake/opencv4/OpenCVConfig.cmake

After this line be added, everything works fine.
