### ISSUE TITLE
Differences between flags maximize_positives and render_threshold

### ISSUE THREAD

**Issue by AlexanderBendeck** [CMU-Perceptual-Computing-Lab/openpose#1255]
The [flags documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/flags.hpp) says that _maximize_positives_ "reduces the thresholds to accept a person candidate" while _render_threshold_ is the cutoff where "Only estimated keypoints whose score confidences are higher than this threshold will be rendered".

I'm a bit confused as to the differences here. Is maximizing positives just a reduction of the rendering threshold? Or are these actually different thresholds, e.g. a "person" threshold and another "keypoint" threshold just for body parts? (And if the latter, how do these two thresholds work in conjunction?)

**Comment by gineshidalgo99** [comment]
Render is only for display, it does not affect the algorithm at all (only the keypoints you visually see through the basic OpenPose GUI).
