### ISSUE TITLE
tracking theory 

### ISSUE THREAD

**Issue by lxy5513** [CMU-Perceptual-Computing-Lab/openpose#1257]
Hi, I have deployed the openpose in server and using tracking mode. 

However, When I call API to handle videos, if the resolution of two videos are different. something wrong happens.  

I guess this is Tracking problem. when openpose start, The program only receive same resolution videos to do tracking. So, I want to know the theory of openpose tracking,   

where are the buffer/recording of former frame information store? Could I replace them by something I save and how to do that?

I am so appreciate for you if you can give me some advice.

**Comment by CompliceU** [comment]
Hello, I recently tried to use attitude estimation and multi-person behavior recognition with openpose. I don't know how to track it. I can track people and connect them. Can you guide me? Thank you. @lxy5513

**Comment by lxy5513** [comment]
as far as I know， openpose only support single person tracking and refine keypoint location,  

If you want to  multi-person tracking, maybe you need do some post process, like do OKS  metric to do track.,

**Comment by gineshidalgo99** [comment]
Yes, the resolution must be kept for the current tracking module.
