### ISSUE TITLE
Saving Keypoints to a CSV file

### ISSUE THREAD

**Issue by hbtousa** [CMU-Perceptual-Computing-Lab/openpose#1258]
### Issue Summary
I was trying to change color for the keypoints and/or the lines, but according to  `#568  is not possible. Is there anyway of saving the keypoints to a file?

Thanks

### Type of Issue
- Help wanted
###  System Configuration

Windows 10
Intel i5-2400 CPU @ 3.10GHZ
Installed RM 8GB
VS Enterprise 2015 Update 3
CUDA 10
CUDNN 7.5
Python 3.7
NVIDIA GTX 950 Driver 430.86
Openpose: Last fetch May 29 2019

**Comment by gineshidalgo99** [comment]
Check doc
