### ISSUE TITLE
Multi-Person 2D Pose Tracking

### ISSUE THREAD

**Issue by CompliceU** [CMU-Perceptual-Computing-Lab/openpose#1259]
Hello, I have read the recent article, there is a tracking of multi-person gestures, I don’t know if this feature has been added in openpose, thank you

**Comment by gineshidalgo99** [comment]
No [duplicated]

**Comment by fzqneo** [comment]
What would the result be like if we specify `--tracking 0 --number_people_max 1` when video contains more than one person it it?
