### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by lu646510477** [CMU-Perceptual-Computing-Lab/openpose#126]
Hi，I want to ask you some questions:
（1）What format is the data in your openpose? Including node data, face feature data, and user ID
（2）When the human body is blocked or too far away to capture the key points incomplete data, how the bones prior knowledge, calculate the loss of data or do not get?
（3）Does the joint data have only x, y values, no Z values, and no joint rotation information? How to calculate z value? Can be considered based on the same length of bone projections. In addition, whether the camera parameters, if you can get the camera parameters, according to the perspective transformation matrix, calculate the Z value.
（4）which is the major code in the openpose? and whicn is the IO code?
I hope you can answer my questions.

### Your system configuration
**Operating system(`lsb_release -a` on Ubuntu):Ubuntu 14.04 LTS
**CUDA version(`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 8.0.61
**cuDNN version:cuDNN 5.1
**GPU model** (`nvidia-smi`):NVIDIA-SMI 375.66 | Tesla C2075
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev
Compiler (`gcc --version` on Ubuntu):g++ 4.9

**Comment by gineshidalgo99** [comment]
1. What do you mean by `what format`? Or by `node data`?
2. That depends on the score threshold. High score will mean visible parts, very low scores will mean guessed parts or false positives.
3. We do no estimate Z value.
4. I am sorry, I do not fully understand your question
