### ISSUE TITLE
Python API. Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by chamecall** [CMU-Perceptual-Computing-Lab/openpose#1261]
When I try to process image `COCO_val2014_000000000357.jpg` from your example by scripts from `examples/tutorial_api_python/`(for example `01_body_from_image.py`) I get next runtime error:

> F0618 16:48:21.774313  2876 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
> *** Check failure stack trace: ***
>     @     0x7f05af8e10cd  google::LogMessage::Fail()
>     @     0x7f05af8e2f33  google::LogMessage::SendToLog()
>     @     0x7f05af8e0c28  google::LogMessage::Flush()
>     @     0x7f05af8e3999  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f05af3f19ea  caffe::SyncedMemory::mutable_gpu_data()
>     @     0x7f05af24c512  caffe::Blob<>::mutable_gpu_data()
>     @     0x7f05b02b5324  op::ArrayCpuGpu<>::mutable_gpu_data()
>     @     0x7f05b038233c  op::NmsCaffe<>::Forward_gpu()
>     @     0x7f05b038202e  op::NmsCaffe<>::Forward()
>     @     0x7f05b03a3360  op::PoseExtractorCaffe::forwardPass()
>     @     0x7f05b039ae05  op::PoseExtractor::forwardPass()
>     @     0x7f05b0397dff  op::WPoseExtractor<>::work()
>     @     0x7f05b03db439  op::Worker<>::checkAndWork()
>     @     0x7f05b03db5c3  op::SubThread<>::workTWorkers()
>     @     0x7f05b03e5228  op::SubThreadQueueInOut<>::work()
>     @     0x7f05b03dd8a1  op::Thread<>::threadFunction()
>     @     0x7f05bf93566f  (unknown)
>     @     0x7f05c6bbd6db  start_thread
>     @     0x7f05c6ef688f  clone

As I found out OpenPose doesn't find the people here. 
How I can't get rid of the error?

**Comment by lgenzelis** [comment]
That means that your graphic card does not have enough RAM to run the example. Sorry. For comparison, with my 4 GB NVIDIA card I can only run examples without the hand or face flags. Otherwise, I get that same error. 

You should try installing and using the CPU version of OpenPose (you, as me, probably have much more RAM for the CPU than in your graphic card).

**Comment by chamecall** [comment]
@lgenzelis , ok, but what special about this particular picture, I'm able to process another ones but not this one. Is this related with its small size?

**Comment by lgenzelis** [comment]
I don't know. That also happened to my (i.e., enough memory for some pictures but not for all of them). I guess it's related to the size of the image, or maybe to number of people involved.

**Comment by AlyanQ** [comment]
I am having this issue with an RTX3090. Running the demo command works just fine (although doesn't display the actual keypoints in video) but when I try to run openpose using the Python API, I get OOM error. What is the solution?
