### ISSUE TITLE
CUDA_CHECK exception (77 vs. 0) 

### ISSUE THREAD

**Issue by fizmatbfu** [CMU-Perceptual-Computing-Lab/openpose#1262]
### Issue Summary
I run example 01_body_from_image_default.cpp. Sometimes all works fine, but sometimes (about half the time) i get exception in function `caffe_gpu_memcpy(const size_t N, const void* X, void* Y)` (file math_functions.cu in caffe).

This happens after function `Forward_gpu` in BodyPartConnectorCaffe class, line 340 (only in this place):
`const auto* const peaksPtr = bottom.at(1)->cpu_data();`
I tried run only caffe (without your lib) for this image, and all works fine (no crashes).

I use static libs, static version of OpenPose (with /MT), have flags USE_CAFFE, USE_CUDA, USE_CUDNN. When crach doesn't occur, example works fine (all points are valid). Model is COCO_18.

### OpenPose Output (if any)
Console output: https://pastebin.com/xtV7sQRi

### Errors (if any)
Check Failed: error == cudaSuccess (77 vs. 0) an illegal memory access was encountered

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output**: https://pastebin.com/xtV7sQRi

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: Cmake
    - **Operating system**: Windows
    - **Operating system version**: Windows7 64bit
    - **Release or Debug mode**? Release
    - Compiler VS2015

4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? no

5. **3rd-party software**:
    - **Caffe version**: https://github.com/BVLC/caffe/tree/windows
    - **CMake version** : 3.13.3
    - **OpenCV version**: static 4.0.1

6. If **GPU mode** issue:
    - **CUDA version** : 10
    - **cuDNN version**: 5.1
    - **GPU model** : NVidia GeForce GTX 1060 6GB

**Comment by gineshidalgo99** [comment]
Does it occur with the downloaded binaries? Or only with your custom compilation?

**Comment by HolyManoly** [comment]
![image](https://user-images.githubusercontent.com/7072105/61757925-79577900-ad77-11e9-99f5-04bd803dfb5e.png)
I'm getting this when running the portable .exe

**Comment by Neskelogth** [comment]
@fizmatbfu I have the same error, did you manage to solve it?
