### ISSUE TITLE
Question: Sequences and Tracking

### ISSUE THREAD

**Issue by JosephRedfern** [CMU-Perceptual-Computing-Lab/openpose#1264]
Hi,

First off, thank you for your work on OpenPose. It's great to have such an accessible and easy to use pose estimation library.

I had a couple of questions about tracking, and operating on individual frames vs. sequences of frames. Please forgive me if these are duplicates -- I have tried searching through existing issues but may have missed some. I also read your paper, but I believe the current implementation has advanced from what's described (i.e. addition single-person tracker).

1. Should I see any difference in pose estimation accuracy by running OpenPose across a video file vs. running in "single-shot" mode on individual frames? If so, how does this work? Does OpenPose use the previous estimate as a prior for new estimates?
2. I understand that at the moment, OpenPose has tracking support for single-person using a LK-based tracker. Documentation states that this improves smoothness, or can improve run-time performance. Can you elaborate on this? Is performance improved by "cropping" the image based on LK, or is pixel flow from one frame to the next used as a hint for new joint positions?
3. In what order are person IDs allocated? Is this based on their position in the frame? Presumably given the lack of a multi-person tracker, they are not consistent between frames (for moving people, at least)?

Thank you,
Joe

**Comment by gineshidalgo99** [comment]
1. Same results (some people complain they are not, but only because they save the images into video with lossy compression so the image is no longer the same one).
2.  It avoid running OpenPose deep net every frame, that is why it improves speed.
3. No consistency at all unfortunately 

Thanks!

**Comment by JosephRedfern** [comment]
OK, thank you for the information @gineshidalgo99!

**Comment by fzqneo** [comment]
> 1. Same results (some people complain they are not, but only because they save the images into video with lossy compression so the image is no longer the same one).
> 2. It avoid running OpenPose deep net every frame, that is why it improves speed.
> 3. No consistency at all unfortunately
> 
> Thanks!

@gineshidalgo99 can you clarify if the (1) point is with or without tracking? If tracking is turned ON, why would you expect the same result? Thank you!
