### ISSUE TITLE
 Real-time effect in 3D camera

### ISSUE THREAD

**Issue by jiyongma** [CMU-Perceptual-Computing-Lab/openpose#1268]
Can openpose use a 3D camera to detect three-dimensional coordinates to achieve real-time results (without detecting hands and faces)

**Comment by Montage-LSM** [comment]
哥们有没有试过用 单一的视频文件，生成出3D的数据来呢，这个是否可行？

**Comment by gineshidalgo99** [comment]
I guess yes, you can implement your own demo (examples/tutorial*) to use Kinect and look up the 3D value as others reported.
