### ISSUE TITLE
CMake fails to download Caffe [Ubuntu]

### ISSUE THREAD

**Issue by lgenzelis** [CMU-Perceptual-Computing-Lab/openpose#1269]
### Issue Summary

After pressing "Configure" in CMake (leaving all options by default, except for BUILD_PYTHON), the process fails with error
`
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
fatal: not a git repository (or any of the parent directories): .git
`

The error is easy to solve. You need to go to the folder 3rdparty inside the cloned openpose folder, and type the command:
$ git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git

Afterwards, pressing Configure again in CMake gives no error.

Still, I guess the default method should work, so I wanted to give the heads-up (as well as the workaround) here. 

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** https://pastebin.com/CquumL5q

2. **OpenPose version**: Latest GitHub code? Latest

3. **General configuration**:
    - **Installation mode**: CMake, Ubuntu
    - **Operating system** Ubuntu 18.04.2 LTS
    - **Release or Debug mode** release
    - Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

4. **Non-default settings**:
    - Any other custom CMake configuration with respect to the default version? BUILD_PYTHON

**Comment by yuanzhedong** [comment]
Another solution is run `git submodule update --init —recursive`. It will also download `pybind11`.

**Comment by gineshidalgo99** [comment]
Follow @yuanzhedong , I added it to the doc. Thanks!
