### ISSUE TITLE
Cannot open include file "cudnn.h" when compiling on VS

### ISSUE THREAD

**Issue by WilliamRuRu15** [CMU-Perceptual-Computing-Lab/openpose#127]
### Issue summary
I did exactly as the instruction _installation.md_ says step by step. When compiling OpenPoseDemo on VS2015, it reports 

> cannot open include file "cuda.h": No such file or directory

So I added the coresponding paths to Include Directories, Library Directories and Additional Dependencies of Input in Linker. It remains the same. I also googled this issue, and there are solutions to installing caffe on win, but I cannot find  _CommonSettings.props.example_ as many people mentioned to change direction of cudnn path.
And I also have this error

> cannot open include file “..\x64\Release\OpenPose.lib”

I'm so frustrated now. Configuring environment is way too hard!!!

### Type of issue
- Compilation/installation error
- Question

### My system configuration
**Win8.1**
**CUDA8**
**cuDNN5.1**:
**Geforce 605 1GB**

**Comment by WilliamRuRu15** [comment]
I copied the cuda folder directly to .../CUDA/v8.0, which causes the problems above. I merged its lib, include folder into v8.0's and everything goes right. How to close this issue?

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back!
