### ISSUE TITLE
Jetson Nano - Changing the video source to use the RaspberryPi Camera 

### ISSUE THREAD

**Issue by Zeit42** [CMU-Perceptual-Computing-Lab/openpose#1271]
### Issue Summary

I installed OpenPose on my Jetson Nano using [this guide](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2_jetpack3.3.md#installation)

It works fine, but when I run: 
`./build/examples/openpose/openpose.bin -camera_resolution 640x480 -net_resolution 128x96`

I get this following error:

> Starting OpenPose demo...
> Configuring OpenPose...
> Starting thread(s)...
> VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 1 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 2 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 3 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 4 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 5 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 6 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 7 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 8 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> VIDEOIO ERROR: V4L: index 9 is not correct!
> OpenCV Error: Unspecified error (GStreamer: unable to start pipeline
> ) in cvCaptureFromCAM_GStreamer, file /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 887
> VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:
> 
> /home/nvidia/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp:887: error: (-2) GStreamer: unable to start pipeline
>  in function cvCaptureFromCAM_GStreamer
> 
> 
> Error:
> No camera found.
> 
> Coming from:
> - src/openpose/producer/producer.cpp:createProducer():460
> - src/openpose/producer/producer.cpp:createProducer():471
> - ./include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1188
> - ./include/openpose/wrapper/wrapper.hpp:exec():424

### Executed Command (if any)
(kindly see the openpose.bin command I ran)

### OpenPose Output (if any)
(kindly see the quoted output)

### Errors (if any)
No camera detected, among others.

### Type of Issue
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** Kindly see the console output in the quote above

2. **OpenPose version**: OpenPose for Jetson TX2

3. **General configuration**:
    - **Installation mode**: sh script
    - **Operating system** Ubuntu 18
    - **Operating system version** Ubuntu 18
    - **Release or Debug mode**? Release I think
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? No
    - Any other custom CMake configuration with respect to the default version? No

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** 3.10.2
    - **OpenCV version**: OpenCV 3.3.1

6. If **GPU mode** issue:
    - **CUDA version** 10.0
    - **cuDNN version**: 7.3
    - **GPU model** 

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 3.7.6
    - **Numpy version** 1.16.4

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by philipNoonan** [comment]
Ive run openpose on the nano with the Realsense camera and it works fine. I had to specify which camera with the `--camera 2` flag, where 2 was the ID of the color camera, 1 was the IR, 0 is the depth IIRC. But this changes depending on what other cameras are attached, or which version of the realsense I was using. Try going through ID values from -1 upwards.

**Comment by Zeit42** [comment]
> Ive run openpose on the nano with the Realsense camera and it works fine. I had to specify which camera with the `--camera 2` flag, where 2 was the ID of the color camera, 1 was the IR, 0 is the depth IIRC. But this changes depending on what other cameras are attached, or which version of the realsense I was using. Try going through ID values from -1 upwards.

I managed to get a Logitech C270 for my Jetson Nano, but when I ran it again, it gave me a "Cuda Check failed (48 vs 0): no kernel image is available for execution on the device." error. I think it was able to detect the camera at index 0, but it can't find the cuda on the nano

**Comment by philipNoonan** [comment]
#1290 has the same error message. Ive built openpose from source from the latest commit and it works ok. The other post is using python, are you also?

**Comment by gineshidalgo99** [comment]
That error is from the webcam and OpenCV, please try to make OpenCV able to read the images of the webcam and then OpenPose should simply work.
