### ISSUE TITLE
Understanding code: getting heatmaps from Caffe layers

### ISSUE THREAD

**Issue by ortegatron** [CMU-Perceptual-Computing-Lab/openpose#1272]
I'm diving on the hand extractor, but guess it's the same for the pose and the face.

So on handExtractorCaffe.cpp at the detectHandKeypoints method, it makes:
1 - forward pass to upImpl->spNetCaffe. That goes directly into Caffe framework.

But then I can't understand how the heatmaps for each keypoint are generated. As the paper says, the heatmaps are the outputs of the inner layers: 'Mconv7_stage1', 'Mconv7_stage2', and so on. But inside netCaffe.cpp, I can only find one method exposing the neural network outputs: getOutputBlobArray, which returns the content of the last layer:
`  upImpl->spOutputBlob = upImpl->upCaffeNet->blob_by_name(upImpl->mLastBlobName);`

So I can't find where and how the inner blobs of caffe are accessed to compute the heatmaps..

**Comment by gineshidalgo99** [comment]
Check `heatmaps_add_parts`, `heatmaps_add_bkg`, `heatmaps_add_PAFs`, and `heatmaps_scale`
