### ISSUE TITLE
CMake error when generating when trying to build OpenPose

### ISSUE THREAD

**Issue by FireHeartMaster** [CMU-Perceptual-Computing-Lab/openpose#1275]
### Issue Summary
I want to use openpose for 3d hand detection but, when trying to configure and generate with CMake I'm getting errors

### Executed Command (if any)
`make -j`nproc``

### Type of Issue
- Compilation/installation error
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: `https://pastebin.com/nQggBk87`

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake (version 3.14.2 in Windows 10)
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows 10
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...): Microsoft Windows 10 Entreprise, Version 10.0.17763 Numéro 17763

    - **Release or Debug mode**? (by default: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): Visual Studio 15 2017

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): Yes
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Caffe from Pytorch installation (Pytorch from here: [https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-win_amd64.whl](url)
    - **CMake version** (`cmake --version` in Ubuntu): 3.14.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); opencv2 version 4.1.0 installed with pip (pip install opencv-python)

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): Cuda compilation tools, release 10.0, V10.0.130
    - **cuDNN version**: cudnn-10.0-windows10-x64-v7.6.1.34
    - **GPU model** (`nvidia-smi` in Ubuntu): GeForce RTX 2070

7. If **CPU-only mode** issue: 
    - **CPU brand & model**: Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz, 3696 MHz, 6 cores, 12 logic processors
    - Total **RAM memory** available: 64 GB

8. If **Python** API: 
    - **Python version**: 3.7.3
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.16.4

9. If **Windows** system:
    - Portable demo or compiled library: Windows Portable Demo

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
Checking your pastebin, I'd suggest you to follow the 3D documentation in detail. Long story short, either disable the 3D camera support or install the Spinnaker drivers. Thanks!
