### ISSUE TITLE
TX2 ubuntu python api how to enable???

### ISSUE THREAD

**Issue by Systemyescool** [CMU-Perceptual-Computing-Lab/openpose#1276]
### Posting rules
1. **
I have check the FAQ, 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1105
and https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/662 .etc
However, there is no key suit my problem.

2. 
Jetson TX2 
Jetpack 3.3
python version 2.7.12 (`python`)
numpy version 1.16.4 (`python` `import numpy` `print numpy.version.version`)

3.
`cd ~/openpose`
`vim CMakeLists.txt`
Then I find BUILD_PYTHON
and change it as follow:
option(BUILD_PYTHON "Build OpenPose python." OFF)
option(BUILD_PYTHON "Build OpenPose python." ON)
Then
`cd ~/openpose`
`./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh`
Then
`cd ~/openpose/build/examples/tutorial_api_python`
There is no directroy called tutorial_api_python...
Then I check it CMakeLists.txt
make sure BUILD_PYTHON ON
`cd ~/openpose`
`rm build -r`
`mkdir build && cd build`
`make all -j4`
I found that:

-- **************** Caffe Configuration Summary ******************
-- General:
--   ...
--   ...
--   BUILD_python      :        OFF
--   BUILD_matlab      :        OFF
--   ...

It's a big trouble and I check it for many times...
`cd ~/openpose/build`
`vim CMakeCache.txt`
find out PYTHON_BUILD:
//Build OpenPose python.
BUILD_PYTHON:BOOL=ON

I have to run "make" because I am not sure the reason 

Then I successfully run
`cd ~/openpose/build/examples/tutorial_api_python`
Then
`python 01_body_from_image.py`
Error as follow:
Error: OpenPose library could not be found. Did you enable 'BUILD_PYTHON' in CMake and have this Python script in the right folder?
Traceback (most recent call last):
    File "01_bodyfrom_image.py", line 26, in <module>
        raise e
ImportError: cannot import name pyopenpose

4. 
Ubuntu

**Comment by gineshidalgo99** [comment]
Compile following the CMake installer for Ubuntu, you might need some extra edits, but we do not support it officially as we do not have one to test. Good luck and feel free to post / make a PR with your instructions for Jetson with CMake! Best
