### ISSUE TITLE
How to process multiple videos consecutively without restarting openpose in command line interface?

### ISSUE THREAD

**Issue by yyhhoi** [CMU-Perceptual-Computing-Lab/openpose#1277]
I have a large amount of videos (>70k). Currently I use Openpose to process them one by one, in Linux Command Line as a script.sh file:

script.sh:
```
./build/examples/openpose/openpose.bin --video input_video_01.mp4 --write_video output_video_01.mp4 --write_json keypoints_01.json --display 0 --logging_level 4
./build/examples/openpose/openpose.bin --video input_video_02.mp4 --write_video output_video_02.mp4 --write_json keypoints_02.json --display 0 --logging_level 4
./build/examples/openpose/openpose.bin --video input_video_03.mp4 --write_video output_video_03.mp4 --write_json keypoints_03.json --display 0 --logging_level 4
# ... (until input_video_700000)
```
When I execute the code by:
`$ sh script.sh`
In such way, the Openpose software will process one video, then exit and restart and process the next video, shown in the console:

```
Starting OpenPose demo...
Configuring OpenPose...
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Getting help:
    -h      -- print basic options
    -h long -- print more options
# ... (information of help)

Starting OpenPose demo...
Configuring OpenPose...
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Getting help:
    -h      -- print basic options
    -h long -- print more options
# ... (information of help)

Starting OpenPose demo...
Configuring OpenPose...
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Getting help:
    -h      -- print basic options
    -h long -- print more options
# ... (information of help)
# ... (continue until all videos are processed)
```

I find that every time a new video is processed, Openpose needs to reinitialize itself again and such initialization takes most of the time. Clearly, processing a large amount of videos by calling Openpose in every line in a script.sh file is not efficient at all. Is there any way that I can process multiple videos without re-initializing openpose every time?

Any help will be appreciated!

**Comment by Fasko** [comment]
There is no overall flag for processing multiple videos in the way you would like; I don't think it is possible to do so just using the demo, unless you were to concatenate all of your videos into one large, single file, noting the timestamps of each of your ~70k videos, running OpenPose to obtain the video output and keypoint data, then later going back to clip them from the main video. I personally would not do this.

I would build OpenPose from source, then create a script which iterates through your video directory to do what you are doing; modifying one of the demo scripts would be a great start.

**Comment by mundane140** [comment]
@yyhhoi have you tried containerizing your script? 
That might solve the initialization problem.
And you could possibly process multiple videos simultaneously depending on computational power required.

**Comment by yyhhoi** [comment]
> 
> 
> @yyhhoi have you tried containerizing your script?
> That might solve the initialization problem.
> And you could possibly process multiple videos simultaneously depending on computational power required.

Sorry I do not know much about script containerization. Could you elaborate more on it?

**Comment by yyhhoi** [comment]
> 
> 
> There is no overall flag for processing multiple videos in the way you would like; I don't think it is possible to do so just using the demo, unless you were to concatenate all of your videos into one large, single file, noting the timestamps of each of your ~70k videos, running OpenPose to obtain the video output and keypoint data, then later going back to clip them from the main video. I personally would not do this.
> 
> I would build OpenPose from source, then create a script which iterates through your video directory to do what you are doing; modifying one of the demo scripts would be a great start.

Thanks for the answers. I think using python API can solve the re-initialization problem. However, I was not aware of it and did not check the python module while building Openpose. Currently I am going for the less elegant approach of concatenating videos and infer them in one go. Thanks again for such suggestion!

**Comment by Fasko** [comment]
> 
> 
> > There is no overall flag for processing multiple videos in the way you would like; I don't think it is possible to do so just using the demo, unless you were to concatenate all of your videos into one large, single file, noting the timestamps of each of your ~70k videos, running OpenPose to obtain the video output and keypoint data, then later going back to clip them from the main video. I personally would not do this.
> > I would build OpenPose from source, then create a script which iterates through your video directory to do what you are doing; modifying one of the demo scripts would be a great start.
> 
> Thanks for the answers. I think using python API can solve the re-initialization problem. However, I was not aware of it and did not check the python module while building Openpose. Currently I am going for the less elegant approach of concatenating videos and infer them in one go. Thanks again for such suggestion!

Happy to help, best of luck!

**Comment by mundane140** [comment]
> > @yyhhoi have you tried containerizing your script?
> > That might solve the initialization problem.
> > And you could possibly process multiple videos simultaneously depending on computational power required.
> 
> Sorry I do not know much about script containerization. Could you elaborate more on it?

For that I might need some time... Will get back to you when I have a solution.

**Comment by gineshidalgo99** [comment]
Creating your own Python/C++ example demo (following the examples/tutorial* folders) is your best way to go. If you ever create a code for that, please create a PR so I can add it and everyone can benefit from it! Thanks! :)

**Comment by RayLeijingsi** [comment]
hello! I'm also doing this about how to process multiple videos. I started learn it a few days ago and i have no idea about it. Have you solved the problem? Can you give some advice?  Thanks.

**Comment by RayLeijingsi** [comment]
how did you solve the restarting problem? Now i also have this trouble.

**Comment by GregorKachel** [comment]
If somebody can solve this problem, please get in contact with me. We need it in our lab, have funds to compensate for the effort and are willing to share the result publicly. In general, we are looking for programmers who can help us work with OpenPose and we always want to share out pipeline.
