### ISSUE TITLE
Change the pose rendering graphics / style

### ISSUE THREAD

**Issue by Tetsujinfr** [CMU-Perceptual-Computing-Lab/openpose#128]
Hi

where can I find the piece of code which generates the pose colorful lines / dots?
I like those but I would need to connect the ears to the rest of the body (when possible). Not sure in which source files this piece of code is?

Also, are you planning to use your pose algo to ease a body segmentation type of work? Or somehow to generate a shape that is even closer to the real surface used by the body on the frame, rather than the dots+lines only?

**Comment by gineshidalgo99** [comment]
If you change POSE_COCO_PAIRS_RENDER_GPU and makes it equal to POSE_COCO_PAIRS, it should join ears to shoulders.

Render: pose/renderPose.hpp has all the options, CPU and GPU.

About segmentation, so far we are not going for it, too many things to improve first in accuracy & speed. Sorry!

**Comment by Tetsujinfr** [comment]
Thanks for your quick feedback.
Sorry but where can I make POSE_COCO_PAIRS_RENDER_GPU=POSE_COCO_PAIRS ?
It seems it is not a valid param of the demo, so I guess I need to modify some source and re-build?

You are planning to improve the speed further? Your code is pretty fast already I thought. But I understand you want to make the foundations even more robust before extending to segmentation.

**Comment by Tetsujinfr** [comment]
Ok, so I modified the array POSE_COCO_PAIRS_RENDER_GPU and started to play a bit with this. So I wanted to connect the neck with the left ear and right ear. Worked fine. Then I did add an additional connection between both ears, so 3 additional connection in total. Compiled fine, however I got an error message at execution time:
<<
Error:
vector::_M_range_check: __n (which is 38) >= this->size() (which is 38)

Coming from:
- src/openpose/pose/poseRenderer.cpp:createPartToName():37
- ./include/openpose/wrapper/wrapper.hpp:configure():843
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
vector::_M_range_check: __n (which is 38) >= this->size() (which is 38)

Coming from:
- src/openpose/pose/poseRenderer.cpp:createPartToName():37
- ./include/openpose/wrapper/wrapper.hpp:configure():843

Aborted (core dumped)
>>
I did change the list for:
 #define POSE_COCO_PAIRS_RENDER_GPU                      {1,2,   1,5,   2,3,   3,4,   5,6,   6,7,   1,8,   8,9,   9,10,  1,11,  11,12, 12,13,  1,0,   0,14, 14,16,  0,15,  15,17, 1,16,  16,17,  17,18}

Did I do something wrong? Can I not connect the points as I want by adding pairs in POSE_COCO_PAIRS_RENDER_GPU within "poseParameters.hpp"? 

thanks for your help.

**Comment by Tetsujinfr** [comment]
Also, when I connect the left ear to the right ear, it does work but only when the body is facing the camera, when the body back is facing the camera, i.e. the ears are seen both but from the rear, then it does not connect.

I would like to make sure that both ears are connected, irrespective of the body facing the camera or not.

Can I do that?

**Comment by Tetsujinfr** [comment]
All works fine now, I probably did something wrong.
I am using the below array with no issue.

#define POSE_COCO_PAIRS_RENDER_GPU {1,2,   1,5,   2,3,   3,4,   5,6,   6,7,   1,8,   8,9,   9,10,  1,11,  11,12, 12,13,  1,0,   0,14, 14,16,  0,15,  15,17,  14,15,  16,17,  8,11}

**Comment by gineshidalgo99** [comment]
OK thanks for the feed-back! I'll close it then if it's working.
