### ISSUE TITLE
How to use Openpose to detect the skeleton of taking a nap on the desk ?

### ISSUE THREAD

**Issue by ro6842** [CMU-Perceptual-Computing-Lab/openpose#1286]
I can use Openpose to detect the person who is sitting, running, walking or standing.
But when I want to detect the person who takes a nap on the desk, the Openpose can't detect the skeleton, (The person took a nap on the desk. His legs can't show, only showing the upper body.)

Have anyone encounterd this problem?
Whether I can adjust the parameters of Openpose to enhace the keypoints detection?
(Now I am using the COCO model, 18 keypoints)

Thank you!

**Comment by gineshidalgo99** [comment]
Try the BODY_25 model, it should be more accurate and detect more keypoints. But horizontal people are usually not detected, the traiining set does not contain those kind of examples.
