### ISSUE TITLE
not able to use --write_coco_json on google colab

### ISSUE THREAD

**Issue by manansaxena** [CMU-Perceptual-Computing-Lab/openpose#1287]
Hi, 
I am running openpose on google colab and want to use --write_coco_json flag but get the following error.
Please help !

Command : ! ./build/examples/openpose/openpose.bin --image_dir examples/media/ --write_images output/ --write_coco_json output/keypoint.json   --display 0 

Output : 
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
stoull

Coming from:
- /content/openpose/src/openpose/utilities/string.cpp:getLastNumber():15
- /content/openpose/src/openpose/filestream/cocoJsonSaver.cpp:record():258
- /content/openpose/include/openpose/filestream/wCocoJsonSaver.hpp:workConsumer():82
- /content/openpose/include/openpose/thread/workerConsumer.hpp:work():44
- /content/openpose/include/openpose/thread/worker.hpp:checkAndWork():93
- /content/openpose/include/openpose/thread/subThread.hpp:workTWorkers():135
- /content/openpose/include/openpose/thread/subThreadQueueIn.hpp:work():71
- /content/openpose/include/openpose/thread/thread.hpp:threadFunction():203
- /content/openpose/include/openpose/thread/thread.hpp:exec():128
- /content/openpose/include/openpose/thread/threadManager.hpp:exec():202
- /content/openpose/include/openpose/wrapper/wrapper.hpp:exec():424

**Comment by Hunkzer** [comment]
Hi @manansaxena, have you been able to solve this issue? I encountered the same (see reference above)

**Comment by gineshidalgo99** [comment]
#1342
