### ISSUE TITLE
The Openpose's restrict?

### ISSUE THREAD

**Issue by ro6842** [CMU-Perceptual-Computing-Lab/openpose#1289]
I have used Openpose to test different behaviors.
But when I try to test the "sitting". Openpose will automatically predict the skeleton of legs.
Although the person only shows his upper body, not showing his legs.
So the person becomes "standing", not "sitting".

I have tried to increase the parameter of "render_threshold" , but no use.
Can any other way to avoid Openpose predicting unknown skeletion automatically?
Somebody help, thank you very much!

**Comment by gineshidalgo99** [comment]
There is no way than filter depending on the score (what you can visually check with render_threshold), there is no datasets with occlusion params so it has not been trained for that, sorry! (Anyone feel free to post your solutions)
