### ISSUE TITLE
feat(docker): build docker images

### ISSUE THREAD

**Issue by AmitMY** [CMU-Perceptual-Computing-Lab/openpose#1293]
# Enhancement / offering possible extensions / pull request / etc

Nothing in the issue form is relevant. I tried to compile on 2 Ubuntus, 1 MacOS 10.14, 1 MacOS 10.15 (https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1270) and nothing works.

I would love if you could release a docker image containing the model for easy command line run with binding of a directory (volume) or something, so it will be very easy to run this code for people that don't require changing it (I just need to run a few of your models on a few 1000s of videos).

Building a docker will require us to not compile anything, you can allow CUDA or not, OPENCL or not, by different images or configuration of the same image.

I am aware of https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/347, but would love something official. I'll try their solution for the meanwhile

**Comment by gineshidalgo99** [comment]
We do not have the time to do an official one, so we only show in the documentation all the ones that the people provide. Sorry!
