### ISSUE TITLE
Openpose installation problems

### ISSUE THREAD

**Issue by fpotempski** [CMU-Perceptual-Computing-Lab/openpose#1294]
### Issue Summary
When attempting to configure/generate my openpose build in cmake, as explained on the Windows Installation doc, my opencv, caffe, gflag, and glog libraries return as not found. This is my first time using cmake so I'm unfamiliar with it. I attempted to install these libraries outside cmake and then input their addresses as the value but that didn't seem to work either so I scrapped everything to start from scratch. If anyone could explain to me what I'm doing wrong I'd appreciate it.

### Executed Command (if any)
N/A

### OpenPose Output (if any)
N/A

### Errors (if any)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Caffe_LIB
    linked by target "openpose" in directory 
Caffe_Proto_LIB
    linked by target "openpose" in directory 
GFLAGS_LIBRARY_DEBUG
    linked by target "openpose" in directory 
GFLAGS_LIBRARY_RELEASE
    linked by target "openpose" in directory 
GLOG_LIBRARY_DEBUG
    linked by target "openpose" in directory 
GLOG_LIBRARY_RELEASE
    linked by target "openpose" in directory 
OpenCV_LIBS
    linked by target "openpose" in directory 

### Type of Issue
- Compilation/installation error
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** : Cmake output: https://pastebin.com/MEWbgTMr

2. **OpenPose version**: Latest Github Code

3. **General configuration**:
    - **Installation mode**: Cmake (windows)
    - **Operating system**: Windows
    - **Operating system version**: Windows 10
    - **Release or Debug mode**? : Release
    - Compiler: Visual Studio Community 2015

4. **Non-default settings**:
    - **3-D Reconstruction module added**?: No
    - Any other custom CMake configuration with respect to the default version?: No

5. **3rd-party software**:
    - **Caffe version**: OpenPose default
    - **CMake version** : 3.15.0-rc2
    - **OpenCV version**: OpenPose default

6. If **GPU mode** issue:
    - **CUDA version**: 10.1.168
    - **cuDNN version**: 7.6.1
    - **GPU model**: Quadro P4000

8. If **Python** API:
    - **Python version**: 3.6
    - **Numpy version**: 1.16.2

9. If **Windows** system:
    - Compiled Library

**Comment by gineshidalgo99** [comment]
If you are compiling the code is because you plan to edit it, if so, please detailed follow the instructions and get more familiar with CMake. Otherwise, simply download the binaries already compiled so you do not have to deal with that. Thanks.

**Comment by M-Younus** [comment]
> If you are compiling the code is because you plan to edit it, if so, please detailed follow the instructions and get more familiar with CMake. Otherwise, simply download the binaries already compiled so you do not have to deal with that. Thanks.

Can you please guide how I can use python_api with already compiled binaries.I am on windows and successfully ran openpose on my video using already compiled binaries.Thanks

**Comment by nektor211** [comment]
Hello,

I've ran into the same issue - I'd like to use python bindings on windows, cuda wouldn't work and on CPU_ONLY I've ran into:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Caffe_LIB_RELEASE
    linked by target "openpose" in directory C:/gits/openpose/src/openpose
    linked by target "pyopenpose" in directory C:/gits/openpose/python/openpose
Caffe_Proto_LIB_RELEASE
    linked by target "openpose" in directory C:/gits/openpose/src/openpose
    linked by target "pyopenpose" in directory C:/gits/openpose/python/openpose
```
which seems similiar.  And trying to build in visual studio leads to:

1>C:\gits\openpose\src\openpose\core\arrayCpuGpu.cpp(3,14): fatal error C1083: Cannot open include file: 'caffe/blob.hpp': No such file or directory

Is there is a simple(r) way to get openpose working with pyhon on windows please?

**Comment by kaminwong** [comment]
Hi,

There are many new learners here including myself, just telling people to "get familiar" sounds totally like "go fxxx yourself", which is not very helpful.

I faced the same problem and upon digging harder found that you do need to unzip the file inside "/openpose/3rdparty/windows" to get "caffe", "caffe3rdparty" and "opencv" out. After unzipping the said files click "Generate" on CMake gui.

**Comment by gineshidalgo99** [comment]
As I said, if you are a new learner, just use the portable binary and then you won't need to use CMake. This is a free software maintained by 1 person (me), I can't do all the work for every single person. If you are using CMake, it's because you know about C++, otherwise you wouldn't need it. Best

**Comment by SeongjinPark-prelist** [comment]
> Hi,
> 
> There are many new learners here including myself, just telling people to "get familiar" sounds totally like "go fxxx yourself", which is not very helpful.
> 
> I faced the same problem and upon digging harder found that you do need to unzip the file inside "/openpose/3rdparty/windows" to get "caffe", "caffe3rdparty" and "opencv" out. After unzipping the said files click "Generate" on CMake gui.

I tried to do this, then I found that those zip files are empty (0KB) so cannot be unzipped. Luckily, I had old files downloaded 1.5 years ago, so I could copy the old ones to the new folder. It seems the server does not have these files any more. (Issue reported in https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/2227  )
![Dec2022 vs May2024](https://github.com/CMU-Perceptual-Computing-Lab/openpose/assets/40839231/81b15505-48c7-44d9-81c3-4fb66c2565ff)
