### ISSUE TITLE
Zero padding for large net-resolution?

### ISSUE THREAD

**Issue by Yuyangaichifan** [CMU-Perceptual-Computing-Lab/openpose#1296]
If net-resolution is higher than image resolution, which do you apply ? Resize or zero padding?

**Comment by gineshidalgo99** [comment]
Both, image is always resized to maintain aspect ratio (adding zero-padding if required).

**Comment by Yuyangaichifan** [comment]
Thank you very much!
I wish you know the detail of the resize process, could you show me the code?
