### ISSUE TITLE
When will the spatio-temporal affinity field be released?

### ISSUE THREAD

**Issue by Yuyangaichifan** [CMU-Perceptual-Computing-Lab/openpose#1297]
When will your new work be released?
Will it be merged into this repo or an indepenent one?

**Comment by soulslicer** [comment]
Good day, I will be spending a bit more time in this fall semester to integrate that work properly into Openpose, without harming the openpose accuracy itself too much. For now, for a quick demo that we evaluated on Posetrack, you may find it in this repo.

https://github.com/soulslicer/openpose/tree/staf

**Comment by gineshidalgo99** [comment]
See #1297 for updates. Whenever that work is added, then there will be temporal consistency, but unfortunately not yet :(

**Comment by ChrisTiberius** [comment]
Hello
Is stable people tracking already available?

I could´nt find to much information here:
https://cmu-perceptual-computing-lab.github.io/openpose/web/html/doc/structop_1_1_wrapper_struct_extra.html#a86ae9d1faa008aaeed4d6fa6ff03f0fb

thanks!

**Comment by jpdiogoNOVA** [comment]
Any updates yet? The project I'm currently on is very interested in the current state of developments regarding this subject.
