### ISSUE TITLE
Generate the extrinsic parameters: build error with DWITH_EIGEN=ON flag

### ISSUE THREAD

**Issue by jlsneto** [CMU-Perceptual-Computing-Lab/openpose#1298]
### Type of Issue
- Compilation/installation error

### All installation process and include Error
https://pastebin.com/Rtrj40vp

I'm trying to generate the extrinsic parameters. First I get an error indicating that it is necessary to send the flag "USE_EIGEN" in the build. So when I try to build with this command "cmake -DWITH_EIGEN=ON ..". I get the error reported in the link above.

Please help me. Do I need to install the eigen package first?

**Comment by gineshidalgo99** [comment]
Yes you do, please, check the doc. Thanks!
