### ISSUE TITLE
3D reconstruction no results

### ISSUE THREAD

**Issue by RaSick** [CMU-Perceptual-Computing-Lab/openpose#1300]
### Issue Summary
I am trying to use the OpenPose 3D Reconstruction to get the 3D coordinates of the Bodyparts. I use two RGB cameras and OpenPose is running on both. Person will be detected on both images and the results are set in the body key points. The problem is that alle the 3D bodykeypoints are 0.0 without an error.
I calibrated the setup, set the 3D Flag and use the input worker as descibed [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/906).

### Type of Issue
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: `Release` 1.5.0?

3. **General configuration**:
    - **Operating system version** Ubuntu 16:
    - **Release or Debug mode**? Release:

4. **Non-default settings**:
    - **3-D Reconstruction module added**? yes:

**Comment by jlsneto** [comment]
Hi, I had the same problem. Do you already have the camera calibration parameters?

**Comment by RaSick** [comment]
Hi @jlsneto, thanks for answering 
I have calibrated the cameras multiple times and set them to the datum. The intrinsic matrix is an upper triangular matrix and the extrinsic is an 3x4 transformation matrix from the calibration an the calibration data are in [m]

**Comment by jlsneto** [comment]
I had this error because the extrinsic parameters were bad.

**Comment by gineshidalgo99** [comment]
Calibration is not correct if OpenPose is not giving the right results.

**Comment by AndroidUnityGit** [comment]
@RaSick Hello, what problem was found in the end, calibration or other problems？Now my interface is a black screen.......
