### ISSUE TITLE
Python API error on Google Colab: no module named 'pyopenpose'

### ISSUE THREAD

**Issue by Rawan19** [CMU-Perceptual-Computing-Lab/openpose#1304]
When I execute the python API sample code in the build folder ( 1_body_from_image.py ), the terminal returns back the following errors.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-27-61b9ab021cc2> in <module>()
      4 from sys import platform
      5 import argparse
----> 6 import pyopenpose as op
      7 
      8 # Import Openpose (Windows/Ubuntu/OSX)

ModuleNotFoundError: No module named 'pyopenpose'.

 I am working on Google Colab Jupyter Notebook, Cuda 10.0  The openpose is the current version (1.5). Any ideas?

I tried the solutions in issue #1027 but none of them worked

**Comment by soulslicer** [comment]
Please try everything here:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md#common-issues
