### ISSUE TITLE
person ordering across the frames (person id)

### ISSUE THREAD

**Issue by ycelik** [CMU-Perceptual-Computing-Lab/openpose#1308]
There was a similar question back in april 18 ( #525) and I'm wondering if we have some progress regarding person id support. If not, do you have any ideas how I could track a person keypoints reliably / identify persons across the frames? 

Thank you very much for your effort 💯

**Comment by maoyali** [comment]
I'm also curious about it , have you solved the problem?

**Comment by ycelik** [comment]
> I'm also curious about it , have you solved the problem?

Are you using python? Check out openpose + deepsort. I'm using c++ so this isn't an option for me unfortunately.

**Comment by maoyali** [comment]
Yes, I'm using python. But I didn't know how to solve it, do you mean deepsort is a good selection for Muti-person tracking?

**Comment by maoyali** [comment]
Deepsort is a good tracking method, but how to get the correspondence of keypoints and the labled person in the image.

**Comment by ortegatron** [comment]
Hi, 
Ineed Deepsort is a good tracker, although not the optimal one. You can check my following repository where I joined OpenPose with Deepsort:
https://github.com/ortegatron/liveposetracker

**Comment by gineshidalgo99** [comment]
See #1297 for updates. Whenever that work is added, then there will be temporal consistency, but unfortunately not yet :(
