### ISSUE TITLE
Not able to Integrate OpenPose in other projects in Windows

### ISSUE THREAD

**Issue by PratNag** [CMU-Perceptual-Computing-Lab/openpose#1309]
### Issue Summary
I am unable to use OpenPose in other external project in Windows. https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-from-other-projects-ubuntu-and-mac. The instructions to for making changes in Cmake File are only applicable for Ubuntu/Mac. 
I get this error when i make the same changes in the link above

This can be done only Ubuntu and not on windows.
To install the OpenPose headers and libraries into the system environment path (e.g., /usr/local/ or /usr/), run the following command.

cd build/
sudo make install

What changes do I make to Cmake to be able to use OpenPose in other projects in Windows?

### Errors (if any)

By not providing "FindOpenPose.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenPose",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenPose" with any
  of the following names:

    OpenPoseConfig.cmake
    openpose-config.cmake

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: Installed from Source on Windows
    - **Operating system** Windows
    - **Operating system version** Windows 10   
    - **Release or Debug mode**? Release
    - Compiler Windows VS 16 2019

9. If **Windows** system:
    - Compiled library

**Comment by gineshidalgo99** [comment]
We focus in creating OpenPose. How to integrate any library (e.g., OpenPose) into another one in Windows is a completely different topic. We are not experts in Windows, but OpenPose can be integrated just as any other DLL-based library, so please check any tutorial about how to do so. Thanks!
