### ISSUE TITLE
OpenPose - build a exe in Unity and now camera doesn't work

### ISSUE THREAD

**Issue by 22Lars22** [CMU-Perceptual-Computing-Lab/openpose#1311]
Hello,
I have tried the OpenPose application and it runs quite good, also the usage of the camera works. Now, I wanted to use it outside Unity and I have built an exe, but now I am facing issues with the camera. I am starting the exe and nothing happens and not detection. 
My camera is having a light symbol, which tells me, that the camera is in use. Since I am using the exe, the camera light symbol is only shining for the first seconds. Maybe it is a problem of CPU/GPU. With a more powerful computer it works better, but I want to let it run on a standard computer. Can anyone help? I appreciate any comment!
All the best,
Lars

**Comment by gineshidalgo99** [comment]
We can't debug webcam or other hardware issues. OpenPose works out of the box for any webcam that is supported by OpenCV. Make sure it works for OpenCV, and then it'll work for sure fore OP. Thanks!
