### ISSUE TITLE
Use OpenPose with less power

### ISSUE THREAD

**Issue by 22Lars22** [CMU-Perceptual-Computing-Lab/openpose#1312]
Hello,
OpenPose works good with a powerful computer, but not on a standard PC. Has anyone an idea to mitigate the power? I have tried both versions: CPU and GPU
All the best,
Lars

**Comment by ibei** [comment]
i am trying to lighten the model to see the difference against the original one. Any idea is welcome.

**Comment by 22Lars22** [comment]
Would be great, if you could share the outcome!

**Comment by gineshidalgo99** [comment]
Check the doc for the faster OpenPose section (while way less accuracy).

**Comment by 22Lars22** [comment]
Thank you gineshidalgo99 for your comment. What exactly do you mean by checking the doc? I am happy to get a more detailed answer. Thanks!
