### ISSUE TITLE
Error Compiling OpenPose on the Jetson TX2

### ISSUE THREAD

**Issue by mdmorar** [CMU-Perceptual-Computing-Lab/openpose#1313]
Hi Guys,

I am following your direction on the OpenPose Installation readme's and have gotten all the way to the section to run the following shell script:

bash ./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh

This works up till the point where it runs the /scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh where it tries to compile the code using cmake. I get the following error.

src/openpose/gpu/cuda.cpp:2:22: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/gpu/cuda.o' failed
make: *** [.build_release/src/openpose/gpu/cuda.o] Error 1
make: *** Waiting for unfinished jobs....

This is the final step in my development to validate that I can get this thing working on the Jetson TX2 ARM64 platform. Please assist as I am sure that I did not see that header in there. Is this as simple as commenting something out I wonder?

I have the following installed on my system:

cmake version 3.15.1
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Sun_Nov_19_03:16:56_CST_2017
Cuda compilation tools, release 9.0, V9.0.252
#define CUDNN_MAJOR 7
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

Please provide any feedback as this is something that is happening after a direct download of your codebase and using a shell script that says that its compatible with the TX2 JetPack 3.3 installation of Linux for Tegra.

Thanks,

Monil

**Comment by gineshidalgo99** [comment]
Try installing it with the normal Ubuntu (CMake) instructions. Those should auto-find Cuda. Thanks
