### ISSUE TITLE
Openpose human body indexization

### ISSUE THREAD

**Issue by ThanasisTs** [CMU-Perceptual-Computing-Lab/openpose#1315]
Hello,

since Openpose does not work using tracking techniques but instead it operates on each frame independently, I would like to ask how it indexes people. Specifically, let us assume that we use a video containing 3 people as an input. The information for each detected human will be stored in the human_list structure. What i would like to know is how the wrapper maps each detected human in the human_list structure. Thanks in advance!!

**Comment by gineshidalgo99** [comment]
There is unfortunately no way implemented to track people across frames. The tracking from #1297 would make it work, check it for updates.
