### ISSUE TITLE
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2 mac os

### ISSUE THREAD

**Issue by jungdaan** [CMU-Perceptual-Computing-Lab/openpose#1316]
zsh: command not found: nproc
-- GCC detected, adding compile flags
-- Building CPU Only.
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- ${Caffe_INCLUDE_DIRS} set by the user to /usr/local/include/caffe
-- ${Caffe_LIBS} set by the user to /usr/local/lib/libcaffe.dylib
-- Adding Example calibration.bin
-- Adding Example openpose.bin
-- Adding Example 1_custom_post_processing.bin
-- Adding Example 01_body_from_image_default.bin
-- Adding Example 02_whole_body_from_image_default.bin
-- Adding Example 03_keypoints_from_image.bin
-- Adding Example 04_keypoints_from_images.bin
-- Adding Example 05_keypoints_from_images_multi_gpu.bin
-- Adding Example 06_face_from_image.bin
-- Adding Example 07_hand_from_image.bin
-- Adding Example 08_heatmaps_from_image.bin
-- Adding Example 09_keypoints_from_heatmaps.bin
-- Adding Example 10_asynchronous_custom_input.bin
-- Adding Example 11_asynchronous_custom_output.bin
-- Adding Example 12_asynchronous_custom_input_output_and_datum.bin
-- Adding Example 13_synchronous_custom_input.bin
-- Adding Example 14_synchronous_custom_preprocessing.bin
-- Adding Example 15_synchronous_custom_postprocessing.bin
-- Adding Example 16_synchronous_custom_output.bin
-- Adding Example 17_synchronous_custom_all_and_datum.bin
-- Adding Example 1_thread_user_processing_function.bin
-- Adding Example 2_thread_user_input_processing_output_and_datum.bin
-- Adding Example handFromJsonTest.bin
-- Adding Example resizeTest.bin
-- Download the models.
-- Downloading BODY_25 model...
-- Model already exists.
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dani/projectsw/openpose/build
[  0%] Building CXX object src/openpose/CMakeFiles/openpose.dir/3d/poseTriangulation.cpp.o
[  1%] Building CXX object src/openpose/CMakeFiles/openpose.dir/3d/cameraParameterReader.cpp.o
[  1%] Building CXX object src/openpose/CMakeFiles/openpose.dir/3d/jointAngleEstimation.cpp.o
[  1%] Building CXX object src/openpose/CMakeFiles/openpose.dir/calibration/cameraParameterEstimation.cpp.o
[  2%] Building CXX object src/openpose/CMakeFiles/openpose.dir/calibration/gridPatternFunctions.cpp.o
[  2%] Building CXX object src/openpose/CMakeFiles/openpose.dir/3d/defineTemplates.cpp.o
[  2%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/array.cpp.o
[  3%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/cvMatToOpInput.cpp.o
[  3%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/arrayCpuGpu.cpp.o
[  3%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/cvMatToOpOutput.cpp.o
[  4%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/defineTemplates.cpp.o
[  4%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/datum.cpp.o
[  4%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/keepTopNPeople.cpp.o
[  4%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/opOutputToCvMat.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/gpuRenderer.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/keypointScaler.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/point.cpp.o
[  6%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/rectangle.cpp.o
[  6%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/renderer.cpp.o
[  6%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/scaleAndSizeExtractor.cpp.o
[  7%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/defineTemplates.cpp.o
[  7%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceDetector.cpp.o
[  8%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceDetectorOpenCV.cpp.o
[  8%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceExtractorCaffe.cpp.o
[  8%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceExtractorNet.cpp.o
[  9%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceCpuRenderer.cpp.o
[  9%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceRenderer.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/renderFace.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/cocoJsonSaver.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/face/faceGpuRenderer.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/bvhSaver.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/verbosePrinter.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/fileStream.cpp.o
[ 10%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/fileSaver.cpp.o
[ 11%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/heatMapSaver.cpp.o
[ 11%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/imageSaver.cpp.o
[ 11%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/jsonOfstream.cpp.o
[ 11%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/videoSaver.cpp.o
[ 11%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/peopleJsonSaver.cpp.o
[ 12%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/defineTemplates.cpp.o
[ 13%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/keypointSaver.cpp.o
[ 13%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gpu/cuda.cpp.o
[ 14%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gpu/gpu.cpp.o
[ 15%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/udpSender.cpp.o
[ 15%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gpu/opencl.cpp.o
[ 15%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/defineTemplates.cpp.o
[ 16%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/gui.cpp.o
[ 16%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/frameDisplayer.cpp.o
[ 16%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/guiAdam.cpp.o
[ 17%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/gui3D.cpp.o
[ 17%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/guiInfoAdder.cpp.o
[ 17%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/defineTemplates.cpp.o
[ 18%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handDetector.cpp.o
[ 18%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handDetectorFromTxt.cpp.o
[ 18%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handExtractorCaffe.cpp.o
[ 19%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handExtractorNet.cpp.o
[ 19%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handCpuRenderer.cpp.o
[ 19%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handGpuRenderer.cpp.o
[ 19%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/renderHand.cpp.o
[ 20%] Building CXX object src/openpose/CMakeFiles/openpose.dir/hand/handRenderer.cpp.o
[ 20%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/bodyPartConnectorBase.cpp.o
[ 21%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/bodyPartConnectorBaseCL.cpp.o
[ 21%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/bodyPartConnectorCaffe.cpp.o
[ 21%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/maximumBase.cpp.o
[ 22%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/maximumCaffe.cpp.o
[ 22%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/netCaffe.cpp.o
[ 22%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/netOpenCv.cpp.o
[ 23%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/nmsBase.cpp.o
[ 23%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/nmsBaseCL.cpp.o
[ 23%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/nmsCaffe.cpp.o
[ 24%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/resizeAndMergeBase.cpp.o
[ 24%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/resizeAndMergeBaseCL.cpp.o
[ 24%] Building CXX object src/openpose/CMakeFiles/openpose.dir/net/resizeAndMergeCaffe.cpp.o
[ 24%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseExtractor.cpp.o
[ 25%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/defineTemplates.cpp.o
[ 25%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseCpuRenderer.cpp.o
[ 26%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseExtractorCaffe.cpp.o
[ 26%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseGpuRenderer.cpp.o
[ 27%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseParameters.cpp.o
[ 27%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseParametersRender.cpp.o
[ 28%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseRenderer.cpp.o
[ 28%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/imageDirectoryReader.cpp.o
[ 29%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/producer.cpp.o
[ 29%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/spinnakerWrapper.cpp.o
[ 29%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/videoCaptureReader.cpp.o
[ 31%] Building CXX object src/openpose/CMakeFiles/openpose.dir/tracking/defineTemplates.cpp.o
[ 31%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseExtractorNet.cpp.o
[ 31%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/webcamReader.cpp.o
[ 31%] Building CXX object src/openpose/CMakeFiles/openpose.dir/tracking/personTracker.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/videoReader.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/ipCameraReader.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/thread/defineTemplates.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/defineTemplates.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/renderPose.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/flirReader.cpp.o
[ 32%] Building CXX object src/openpose/CMakeFiles/openpose.dir/tracking/personIdExtractor.cpp.o
[ 33%] Building CXX object src/openpose/CMakeFiles/openpose.dir/tracking/pyramidalLK.cpp.o
[ 33%] Building CXX object src/openpose/CMakeFiles/openpose.dir/unity/unityBinding.cpp.o
[ 34%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/fileSystem.cpp.o
[ 34%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/flagsToOpenPose.cpp.o
[ 35%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/openCv.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/defineTemplates.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperAuxiliary.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/keypoint.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/profiler.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/errorAndLog.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/string.cpp.o
[ 36%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructExtra.cpp.o
[ 37%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructFace.cpp.o
[ 37%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructGui.cpp.o
make[2]: *** No rule to make target `/Users/dani/projectsw/opencv/build/lib/libopencv_dnn.4.1.1.dylib', needed by `src/openpose/libopenpose.1.5.0.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructInput.cpp.o
[ 38%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructHand.cpp.o
[ 38%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructOutput.cpp.o
[ 38%] Building CXX object src/openpose/CMakeFiles/openpose.dir/wrapper/wrapperStructPose.cpp.o
/Users/dani/projectsw/openpose/src/openpose/3d/poseTriangulation.cpp:336:5: warning: control
      may reach end of non-void function [-Wreturn-type]
    }
    ^
c/Users/dani/projectsw/openpose/src/openpose/pose/poseExtractorNet.cpp:340:31: warning: braces
      around scalar initializer [-Wbraced-scalar-init]
            propertyElement = {value};
                              ^~~~~~~
1 warning generated.
1 warning generated.
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [all] Error 2

I can't solve it..... plz help me ... this is my cmake 

![image](https://user-images.githubusercontent.com/20366604/62821475-726e9a00-bbb0-11e9-9e50-a5e4b8b6d07e.png)

**Comment by soulslicer** [comment]
This looks like an issue with your opencv installation. Not sure why its linking against the DNN module. Are you able to try with opencv provided by Brew?

**Comment by juanmartin** [comment]
Hi I'm facing the same issue.
my OpenCV_DIR is /usr/local/lib/cmake/opencv4
and still get the error when trying to compile.
Running High Sierra.

```
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_softmax_layer.cu.o] Error 1
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by JakeMalis** [comment]
Bump

**Comment by soulslicer** [comment]
Can you guys post your exact error please? I am not able to recreate this error on my side

**Comment by soulslicer** [comment]
> Hi I'm facing the same issue.
> my OpenCV_DIR is /usr/local/lib/cmake/opencv4
> and still get the error when trying to compile.
> Running High Sierra. Latest CUDA 10.1 and cudNN7
> 
> ```
> make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_softmax_layer.cu.o] Error 1
> make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
> make[3]: *** [all] Error 2
> make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
> make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
> make: *** [all] Error 2
> ```

Sorry but we don't support CUDA + OSX for now as we didn't have the machine to develop for such a scenario

**Comment by yanyanyufei1** [comment]
> Can you guys post your exact error please? I am not able to recreate this error on my side


HelindeMacBook-Air:build helin$ make -j`sysctl -n hw.logicalcpu`
[ 12%] Performing configure step for 'openpose_lib'
CMake Warning (dev) at cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at /usr/local/lib/cmake/boost_system-1.72.0/libboost_system-variant-shared.cmake:64 (message):
  Target Boost::system already has an imported location
  '/usr/local/lib/libboost_system-mt.dylib', which will be overwritten with
  '/usr/local/lib/libboost_system.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_system-1.72.0/boost_system-config.cmake:57 (include)
  /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package)
  /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
  /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:49 (include)


CMake Warning at /usr/local/lib/cmake/boost_filesystem-1.72.0/libboost_filesystem-variant-shared.cmake:64 (message):
  Target Boost::filesystem already has an imported location
  '/usr/local/lib/libboost_filesystem-mt.dylib', which will be overwritten
  with '/usr/local/lib/libboost_filesystem.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_filesystem-1.72.0/boost_filesystem-config.cmake:57 (include)
  /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package)
  /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
  /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:49 (include)


-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- -- CUDA is disabled. Building without it...
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find vecLib (missing: vecLib_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindvecLib.cmake:24 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:135 (find_package)
  CMakeLists.txt:49 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/helin/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2
This is my error. I am a beginner.  I don't konw how to  Use -Wno-dev to suppress it. Could you help me ? thank you very much.
______________________________________________________________________________________________________
more detail in CMake
![屏幕快照 2020-03-06 下午9 34 46](https://user-images.githubusercontent.com/37108000/76088129-781b4980-5ff2-11ea-9927-4e3c6622604d.png)
![屏幕快照 2020-03-06 下午9 35 05](https://user-images.githubusercontent.com/37108000/76088148-80738480-5ff2-11ea-924e-ed67f9b5ac49.png)

**Comment by soulslicer** [comment]
> > Can you guys post your exact error please? I am not able to recreate this error on my side
> 
> HelindeMacBook-Air:build helin$ make -j`sysctl -n hw.logicalcpu`
> [ 12%] Performing configure step for 'openpose_lib'
> CMake Warning (dev) at cmake/Misc.cmake:32 (set):
> implicitly converting 'BOOLEAN' to 'STRING' type.
> Call Stack (most recent call first):
> CMakeLists.txt:25 (include)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning at /usr/local/lib/cmake/boost_system-1.72.0/libboost_system-variant-shared.cmake:64 (message):
> Target Boost::system already has an imported location
> '/usr/local/lib/libboost_system-mt.dylib', which will be overwritten with
> '/usr/local/lib/libboost_system.dylib'
> Call Stack (most recent call first):
> /usr/local/lib/cmake/boost_system-1.72.0/boost_system-config.cmake:57 (include)
> /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package)
> /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
> /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
> cmake/Dependencies.cmake:8 (find_package)
> CMakeLists.txt:49 (include)
> 
> CMake Warning at /usr/local/lib/cmake/boost_filesystem-1.72.0/libboost_filesystem-variant-shared.cmake:64 (message):
> Target Boost::filesystem already has an imported location
> '/usr/local/lib/libboost_filesystem-mt.dylib', which will be overwritten
> with '/usr/local/lib/libboost_filesystem.dylib'
> Call Stack (most recent call first):
> /usr/local/lib/cmake/boost_filesystem-1.72.0/boost_filesystem-config.cmake:57 (include)
> /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package)
> /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
> /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
> cmake/Dependencies.cmake:8 (find_package)
> CMakeLists.txt:49 (include)
> 
> -- Found gflags (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
> -- Found glog (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
> -- Found PROTOBUF Compiler: /usr/local/bin/protoc
> -- HDF5: Using hdf5 compiler wrapper to determine C configuration
> -- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
> -- -- CUDA is disabled. Building without it...
> CMake Error at /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
> Could NOT find vecLib (missing: vecLib_INCLUDE_DIR)
> Call Stack (most recent call first):
> /Applications/CMake.app/Contents/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
> cmake/Modules/FindvecLib.cmake:24 (find_package_handle_standard_args)
> cmake/Dependencies.cmake:135 (find_package)
> CMakeLists.txt:49 (include)
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/helin/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
> make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
> make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
> make: *** [all] Error 2
> This is my error. I am a beginner. I don't konw how to Use -Wno-dev to suppress it. Could you help me ? thank you very much.
> 
> more detail in CMake
> ![屏幕快照 2020-03-06 下午9 34 46](https://user-images.githubusercontent.com/37108000/76088129-781b4980-5ff2-11ea-9927-4e3c6622604d.png)
> ![屏幕快照 2020-03-06 下午9 35 05](https://user-images.githubusercontent.com/37108000/76088148-80738480-5ff2-11ea-924e-ed67f9b5ac49.png)

You have to apply the patch as caffe is broken on the new osx. Please find it in the mac osx section of the readme

**Comment by JakeMalis** [comment]
> > Hi I'm facing the same issue.
> > my OpenCV_DIR is /usr/local/lib/cmake/opencv4
> > and still get the error when trying to compile.
> > Running High Sierra. Latest CUDA 10.1 and cudNN7
> > ```
> > make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_softmax_layer.cu.o] Error 1
> > make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
> > make[3]: *** [all] Error 2
> > make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
> > make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
> > make: *** [all] Error 2
> > ```
> 
> Sorry but we don't support CUDA + OSX for now as we didn't have the machine to develop for such a scenario

I had the **EXACT** same error running on Ubuntu 18.04.

**Comment by soulslicer** [comment]
@gineshidalgo99 Perhaps this is an issue with the latest CUDA?

**Comment by gineshidalgo99** [comment]
That error is not too clear. A whole output will help better. My recomendation for Ubuntu 18, install Caffe from their official website. Once Caffe is working, OpenPose will install right away.
