### ISSUE TITLE
the theory about the Accurate Peak Position？

### ISSUE THREAD

**Issue by mollonpj** [CMU-Perceptual-Computing-Lab/openpose#1318]
### Type of Issue
- Help wanted
- Question

I have a question about the function of nmsCpu
 ```
 template <typename T>
    void nmsCpu(T* targetPtr, int* kernelPtr, const T* const sourcePtr, const T threshold,
                const std::array<int, 4>& targetSize, const std::array<int, 4>& sourceSize,
                const Point<T>& offset) 
```

after get the peak score in the heatmap，why it need  Accurate Peak Position？the peak soce in the featuremap which from vgg16 is not right？
Thanks

**Comment by gineshidalgo99** [comment]
It's just refinement. It's up to you how much speed vs. accuracy you want. We think this is a good trade-off.

**Comment by mollonpj** [comment]
@gineshidalgo99 Thank you for your reply.  Does it Like Gauss filtering? Do you have the paper about the algorithm（Accurate Peak Position）?

**Comment by gineshidalgo99** [comment]
We just got it online at the time, I could not find it now, it just use some kind of interpolation, nothing fancy anyway.

**Comment by mollonpj** [comment]
@gineshidalgo99 Thank you for your reply.  does it looks like Inverse Distance Weighted interpolation？
