### ISSUE TITLE
windows 3rdparty dependencies

### ISSUE THREAD

**Issue by heurainbow** [CMU-Perceptual-Computing-Lab/openpose#132]
### Issue summary
The caffe_and_dependencies_100.zip seems broken. I have already tried to download this file for several times. The file size is all right.

Better offer MD5/SHA1/CRC32 to check if the download file is complete. Same to the caffemodels.

- Other (prebuilt libs)

### Your system configuration
win7

**Comment by gineshidalgo99** [comment]
What do you mean by broken? I was able to download it just fine. Could you detail it a little bit more? Thanks!

**Comment by heurainbow** [comment]
Sorry, it is something wrong with my network. I changed another computer to download the files and it worked fine.

**Comment by gineshidalgo99** [comment]
OK. In case somebody else suffers the same issue, if some file looks broken, it usually means it has not being properly downloaded due to bad internet connection. So removing it and re-executing the download *.bat script usually fixes it. Thanks!

**Comment by ThienAnh** [comment]
I have the same problem when download windows/caffe_and_depandencies_100.zip. Error code 404. I had try some computer but get the same error

**Comment by gineshidalgo99** [comment]
Please update OpenPose to the latest GitHub version.

**Comment by 1icas** [comment]
I meet the same problem when download windows/caffe_and_depandencies_100.zip (http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows/caffe_and_dependencies_100.zip),Error code 404.

**Comment by gineshidalgo99** [comment]
Please update OpenPose to the latest GitHub version, that zip is no longer used.
