### ISSUE TITLE
Error：‘CAP_PROP_FRAME_COUNT’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by RatsLoveCats** [CMU-Perceptual-Computing-Lab/openpose#1321]
/home/linux/desktop/openpose/examples/tutorial_api_cpp/01_body_from_image_default.cpp: In function ‘int tutorialApiCpp()’:
/home/linux/desktop/openpose/examples/tutorial_api_cpp/01_body_from_image_default.cpp:206:27: error: ‘CAP_PROP_FRAME_COUNT’ is not a member of ‘cv’
   int ZhenCount = cap.get(cv::CAP_PROP_FRAME_COUNT);
                           ^
/home/linux/desktop/openpose/examples/tutorial_api_cpp/01_body_from_image_default.cpp:207:21: error: ‘CAP_PROP_FPS’ is not a member of ‘cv’
   int FPS = cap.get(cv::CAP_PROP_FPS);
                     ^
/home/linux/desktop/openpose/examples/tutorial_api_cpp/01_body_from_image_default.cpp:208:21: error: ‘CAP_PROP_FRAME_HEIGHT’ is not a member of ‘cv’
    height = cap.get(cv::CAP_PROP_FRAME_HEIGHT) / 2;
                     ^
/home/linux/desktop/openpose/examples/tutorial_api_cpp/01_body_from_image_default.cpp:209:20: error: ‘CAP_PROP_FRAME_WIDTH’ is not a member of ‘cv’
    width = cap.get(cv::CAP_PROP_FRAME_WIDTH) / 2;
                    ^
examples/tutorial_api_cpp/CMakeFiles/01_body_from_image_default.bin.dir/build.make:62: recipe for target 'examples/tutorial_api_cpp/CMakeFiles/01_body_from_image_default.bin.dir/01_body_from_image_default.cpp.o' failed

**Comment by gineshidalgo99** [comment]
Which version of OpenCV are you using? I might have to add support for that OpenCV version in that example. Thanks!

**Comment by gineshidalgo99** [comment]
I've just realized you are submitting a file you already modified. Please, do not post your own programming files and non-OpenPose related issues in here.
