### ISSUE TITLE
CMake Error: failed to create symbolic link '../../lib/libcaffe.so': function not implemented

### ISSUE THREAD

**Issue by HassanAlsamahi** [CMU-Perceptual-Computing-Lab/openpose#1322]
I am trying to build open pose in google colab, and Cmake configuration passed and done, but make popped this error, why is this happening and how to solve this?? 

```

[ 84%] Linking CXX shared library ../../lib/libcaffe.so
CMake Error: failed to create symbolic link '../../lib/libcaffe.so': function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
src/caffe/CMakeFiles/caffe.dir/build.make:2215: recipe for target 'lib/libcaffe.so.1.0.0' failed
make[5]: *** [lib/libcaffe.so.1.0.0] Error 1
make[5]: *** Deleting file 'lib/libcaffe.so.1.0.0'
CMakeFiles/Makefile2:240: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:110: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-build' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by gineshidalgo99** [comment]
Sorry, we do not support it (we don't have it). But anyone is welcome to help!

**Comment by Light--** [comment]
i met this problem too..

**Comment by talatccan** [comment]
I have same problem. Any update?

**Comment by agibson** [comment]
**I have a similiar problem. Anybody?**

**This is my snippet of the error:**
[ 95%] Linking C shared library libaom.so
CMake Error: cmake_symlink_library: System Error: Function not implemented
CMakeFiles/aom.dir/build.make:482: recipe for target 'libaom.so.0' failed

**I looked at the recipe on line 482, but cryptic.**
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/media/ag/SG2TB/AG-TEST/vdhcoapp-master/converter/src-build/linux/64/aom/aom_build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Linking C shared library libaom.so"

**I will keep looking for an answer. But where to look????**

**Comment by agibson** [comment]
So I found this obscure but similiar reference out on the internet in several places. It appears that trying to build on a windows based partition is a NO NO for linking on a Linux system. So I moved my application build to a ext4 partition, changed nothing, and re did the make. It worked. Well at least I am past the above error listed by me. The build is still running.
> This may solve the “CMake Error: cmake_symlink_library: System Error: Function not implemented” error.
Do not compile opencv on FAT systems, as its fails as a result of not being able of setting the executable bit on those filesystems. Using ext4 should be enough to avoid this kind of problems.
There's a good set of tutorials for installing opencv over here:
https://www.pyimagesearch.com/2018/05/28/ubuntu-18-04-how-to-install-opencv/#comment-475432

**Comment by SpenceraM** [comment]
same issue here.

**Comment by xinzi2018** [comment]
i have the same question

**Comment by whf9527** [comment]
how to resolve this problem

**Comment by 1393987347** [comment]
I have same problem. Any update?

**Comment by szreik** [comment]
> So I found this obscure but similiar reference out on the internet in several places. It appears that trying to build on a windows based partition is a NO NO for linking on a Linux system. So I moved my application build to a ext4 partition, changed nothing, and re did the make. It worked. Well at least I am past the above error listed by me. The build is still running.
> 
> > This may solve the “CMake Error: cmake_symlink_library: System Error: Function not implemented” error.
> > Do not compile opencv on FAT systems, as its fails as a result of not being able of setting the executable bit on those filesystems. Using ext4 should be enough to avoid this kind of problems.
> > There's a good set of tutorials for installing opencv over here:
> > https://www.pyimagesearch.com/2018/05/28/ubuntu-18-04-how-to-install-opencv/#comment-475432

Could you explain how you moved your application to build an ext4 partition? I would appreciate it tremendously
