### ISSUE TITLE
what are units of "pose_keypoints_3d" coordinates？

### ISSUE THREAD

**Issue by deepslee** [CMU-Perceptual-Computing-Lab/openpose#1324]
Hello，goodday.

I want to know what are the units of coordinates of the key points; 
I think 2-d coordinates should be pixel coordinates, and What are the units of 3-d coordinates?
I use two Flir cameras for 3-d reconstruction.

`{"version":1.3,
"people":[{"person_id":[-1],
"pose_keypoints_2d":[662.454,117.842,0.859371,564.523,302.142,0.759253,391.418,293.672,0.627958,260.279,477.928,0.759972,296.532,606.487,0.694276,734.923,318.776,0.620698,838.416,503.151,0.791247,841.084,709.83,0.751022,531.116,813.083,0.43431,422.172,801.966,0.419394,0,0,0,0,0,0,640.055,824.3,0.360893,0,0,0,0,0,0,631.571,75.7758,0.854506,682.045,84.3173,0.862916,522.744,95.499,0.891507,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
"face_keypoints_2d":[],
"hand_left_keypoints_2d":
[838.594,726.641,0.679963,804.051,746.019,0.710286,771.193,772.979,0.766309,765.296,808.365,0.788832,783.831,832.798,0.387987,796.469,800.782,0.835584,792.256,849.648,0.946195,792.256,837.853,0.478125,793.098,822.687,0.355137,825.114,807.522,0.935897,817.531,856.388,0.878726,818.374,846.278,0.50442,819.216,833.64,0.394699,852.074,807.522,0.943514,838.594,854.703,1.03925,837.752,846.278,0.605876,839.437,832.798,0.458359,872.295,805.837,0.779203,860.499,847.963,0.84925,857.129,842.065,0.562605,857.129,831.955,0.489984],
"hand_right_keypoints_2d":[291.073,611.576,0.566484,327.578,619.043,0.514055,365.743,643.103,0.751836,379.847,677.119,0.831311,364.913,705.328,0.832633,319.282,642.274,0.788815,344.171,697.031,0.934687,346.66,680.438,0.366533,342.512,664.674,0.350829,293.562,658.037,0.864959,320.111,709.476,0.757492,325.919,697.861,0.435753,321.771,678.779,0.37406,271.991,670.482,0.865071,298.54,713.624,0.797554,304.348,703.668,0.53655,298.54,685.416,0.36861,254.568,678.779,0.76801,276.969,711.965,0.733836,286.095,708.646,0.529318,285.266,696.202,0.475509],
"pose_keypoints_3d":[0.0752737,-0.352363,1.18727,1,-0.0192231,-0.196172,1.3276,1,-0.203287,-0.211279,1.34014,1,-0.31036,-0.015862,1.21484,1,-0.237564,0.0908977,1.0516,1,0.16171,-0.184139,1.33486,1,0.256485,0.0146835,1.26545,1,0.231435,0.192218,1.12527,1,-0.0545498,0.329848,1.28482,1,-0.165969,0.318801,1.28904,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0473999,-0.405172,1.22415,1,0.0949572,-0.385904,1.20092,1,-0.0608742,-0.402307,1.27787,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
"face_keypoints_3d":[],
"hand_left_keypoints_3d":[0.232598,0.208372,1.13977,1,0.200119,0.225036,1.13351,1,0.168457,0.245804,1.11902,1,0.162569,0.274106,1.11163,1,0.181858,0.301377,1.13106,1,0.190508,0.265242,1.11062,1,0.184351,0.306555,1.09882,1,0.185494,0.301455,1.1102,1,0,0,0,0,0.214075,0.268844,1.1017,1,0.208727,0.313312,1.10804,1,0.209031,0.308952,1.1121,1,0.210374,0.298526,1.11508,1,0.240111,0.272907,1.11449,1,0.226203,0.309923,1.10245,1,0.224603,0.307159,1.10491,1,0,0,0,0,0.259387,0.273833,1.12147,1,0.247847,0.305287,1.11181,1,0.241705,0.302468,1.10411,1,0.238193,0.296308,1.0962,1],
"hand_right_keypoints_3d":[-0.23687,0.0936548,1.02804,1,-0.208861,0.100749,1.03659,1,-0.172164,0.115714,1.00844,1,-0.158877,0.139523,1.00044,1,-0.168369,0.160579,0.985291,1,-0.200064,0.109404,0.964753,1,-0.182387,0.15174,0.974666,1,-0.183407,0.142085,0.988234,1,-0.189614,0.133426,1.00005,1,-0.219069,0.12053,0.962941,1,-0.199777,0.160101,0.969772,1,-0.203578,0.158027,1.00956,1,-0.205903,0.143891,1.00066,1,-0.236787,0.131056,0.96779,1,-0.21689,0.163764,0.972158,1,-0.219529,0.161561,1.004,1,-0.223949,0.148228,1.00031,1,-0.254325,0.140034,0.983572,1,-0.23516,0.164121,0.97815,1,-0.23126,0.163475,0.99228,1,-0.234187,0.155883,1.00053,1]}]}`

**Comment by Tetsujinfr** [comment]
All is explained here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

I even copy/paste the relevant section to save you a click or a google serach. UR welcome.

"Each JSON file has a people array of objects, where each object has:An array pose_keypoints_2dcontaining the body part locations and detection confidence formatted as x1,y1,c1,x2,y2,c2,.... The coordinates x and ycan be normalized to the range [0,1], [-1,1], [0, source size], [0, output size], etc., depending on the flag keypoint_scale (see flag for more information), while c is the confidence score in the range [0,1]."

Fyi a demo result of the opepose inference with body-face-hands keypoints overlaid.
https://youtu.be/mlP8DjAS9Yc

I think you can close this 'issue' now.

**Comment by deepslee** [comment]
Thank you.
But Where is the origin of coordinates in 3-d reconstruction. I want to project the coordinates to Unity3D. I don't know the units of coordinates and the position of the origin, how can I determine them？

**Comment by Tetsujinfr** [comment]
My understanding is that 3d coordinates are in pixel terms, so you need your view parameters (focal length) to convert in real world units. Just my take since I am not using the 3d points.

**Comment by gineshidalgo99** [comment]
You are setting the 3D calibration parameters, so you are setting the origin from those.

**Comment by redyuan43** [comment]
> My understanding is that 3d coordinates are in pixel terms, so you need your view parameters (focal length) to convert in real world units. Just my take since I am not using the 3d points.


> Thank you.
> But Where is the origin of coordinates in 3-d reconstruction. I want to project the coordinates to Unity3D. I don't know the units of coordinates and the position of the origin, how can I determine them？
> 
> I'm using the default Settings.
> Based on the observation data, I guess the coordinate origin is at the reference camera and the unit is meters.


I have the same question about it. 3d points coordinates from openpose are for world units , camera units or the others. I don't understand the answer by auther, because I am a fresh bird. If you get the specification answer, please let me know.  Thanks a  lot.
