### ISSUE TITLE
key points missing

### ISSUE THREAD

**Issue by ChessQian** [CMU-Perceptual-Computing-Lab/openpose#1325]
Hi, I have a question about the missing key points: sometimes, there will be some missing key points in the test results but they do exist in the pictures,  why would the key points miss?

**Comment by Tetsujinfr** [comment]
well this is just detection instabilities. the model is pretty damn good but not yet as good as a human. this is just deep learning, not general intelligence. just my take

**Comment by gineshidalgo99** [comment]
Right answer from Tetsujinfr
