### ISSUE TITLE
possible explicit licence-file extension

### ISSUE THREAD

**Issue by Sickeroni** [CMU-Perceptual-Computing-Lab/openpose#1327]
### Issue Summary
Out legal department is sceptical about usability of generated data (mostly pictures)
for advertising noncommercial **academic research projects**. We want to advertise some research only Projects. 

### Longer explaination
Our legal department assumes that using generated imagefiles or in photos that show part of this images in public media (websites, newspaper and [local]tv) is not covered with this license. 

Commercial usage is explicit disallowed (without other licence). Therefore public media can't use it even if its for advertising researches.   

### Possible solutions
I see two possible solutions for this. both would extend the licence file with one option. 
- explicit allow advertising academic research 
- explicit forbid it.
the later one would not change something, but makes it much easier to understand what is allowed and what not. 

### Preferred Solution
I would prefer the first Option. Because advertising projects that are based on openpose are free advertising for openpose too. The later one would stop our research in this parts.

**Comment by gineshidalgo99** [comment]
Please, allow me a few days to check this and come back to you! Our idea would be the first option, but we have to ask the CMU legal folks first. Please wait for an update, thanks!

**Comment by Sickeroni** [comment]
Hey!
i have to annoy you after one week without news ;) 
is there something new with this topic?

**Comment by gineshidalgo99** [comment]
Sorry, I was making sure I could share his email.

Please, email Scott McEvoy (mcevoy@cmu.edu), our license expert, so you can discuss this issue by call or video-call. You can also cc'd me in that email so I can keep track of the email thread: gines@alumni.cmu.edu

Thanks!
