### ISSUE TITLE
Expected vs. received sizes: Frame size changed

### ISSUE THREAD

**Issue by jlsneto** [CMU-Perceptual-Computing-Lab/openpose#1328]
#### **I did receive that message for ALL FRAMES.**

Expected vs. received sizes: 1365x1080 vs. 1365x1080 in /content/openpose/src/openpose/producer/producer.cpp:checkFrameIntegrity():300
Frame size changed. Returning empty frame.

### Type of Issue
- Help wanted

Is this problem caused by high resolution?
Can you help me, please?

**Comment by lichengxian** [comment]
could you tell me how to fix this issue? I also had this problem

**Comment by EndlessLoops** [comment]
Had someone fixed this problem？

**Comment by jwyhhh123** [comment]
./build/examples/openpose/openpose.bin --camera 2 --camera_resolution 2048x1536
