### ISSUE TITLE
How to read json and show the result in image

### ISSUE THREAD

**Issue by maoyali** [CMU-Perceptual-Computing-Lab/openpose#1329]
In the openpose_python, do you provide the api to read json(the keypoints that created by openpose_python) and show the result in image ? Thanks!

**Comment by ivancccka** [comment]
have u solved the problem?

**Comment by maoyali** [comment]
sorry ,I haven't，do you have any good idea or method? I'm not familiar with pose estimation, but i need to use it now~

**Comment by ivancccka** [comment]
me too,i just don't know how to show the results in images

**Comment by warpdriv** [comment]
From what I understand, the array is organized into x, y, confidence. For the body it makes sense, but I'm having trouble with the face. You can write some code to reshape the array into a list of tuples where [(x,y,c),(x,y,c),...]

**Comment by monkeyhippies** [comment]
I'd very much like this feature for a current project
