### ISSUE TITLE
How to access keypoint name mapping via Python API?

### ISSUE THREAD

**Issue by cschell** [CMU-Perceptual-Computing-Lab/openpose#1335]
I'm using openpose via its python interface and I'm in the process of extracting poses (body+hand) from videos, which is working great so far.

However, I'm wondering how I can make sure I label my csv-columns correctly, especially if I try out different models (COCO, MPI). I understand that there is [documentation for the output](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md), but I'm looking for a programmatic way to ensure correct feature associations. I found [C++ constants](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/7c1e8e40046e581d6ac33c5ca6c5e9806076fafe/src/openpose/pose/poseParameters.cpp) containing the mapping I'm looking for - are these somehow accessible via the Python API?

### Type of Issue
- Help wanted

### Your System Configuration
2. **OpenPose version**: Latest GitHub code
3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**
LSB Version:    core-10.2019031300ubuntu1-noarch:security-10.2019031300ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
    - Compiler: gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0

8. If **Python** API:
    - **Python version**:  3.7
    - **Numpy version**: 1.17.0

**Comment by gineshidalgo99** [comment]
doc/output.md now provides some info about how to read it from Python as well!
