### ISSUE TITLE
Cannot Write Video - Producer not available

### ISSUE THREAD

**Issue by jmcmichael125** [CMU-Perceptual-Computing-Lab/openpose#1338]
### Issue Summary
When writting video is attempted, OpenPose stops as the producer is not available. All other display functions and processing are working well.

Any suggestions for how to activate the producer or where I should be looking?

### Executed Command (if any)
Custom code for 3d processing from saved videos

Flags file and C++ code attached

[3d_synchronous_input_2.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3544169/3d_synchronous_input_2.txt)

[flags.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3544170/flags.txt)

### OpenPose Output (if any)

No Output

### Errors (if any)

Error:
Writting video is only available if the OpenPose producer is used (i.e. producerSharedPtr cannot be a nullptr).

### Type of Issue
- Help wanted

### Your System Configuration
2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** Windows
    - **Operating system version** Windows 10
    - **Release or Debug mode**? release
    - Compiler: VS2017 community

4. **Non-default settings**:
    - **3-D Reconstruction module added**? Yes

5. **3rd-party software**:
    - **Caffe version**: 
    - **CMake version** 
    - **OpenCV version**: 

6. If **GPU mode** issue:
    - **CUDA version** 10.1
    - **cuDNN version**:  7.5
    - **GPU model**

**Comment by gineshidalgo99** [comment]
I believe the error is self-explanatory: you can't generate video if you are not using the OpenPose video reader. Otherwise, OpenPose does not know the frame rate of that video nor whether all the images have the same resolution.
Please, use `--write_images` instead (you can always manually turn that into a video with whatever frame rate you want). Thanks

**Comment by pajama** [comment]
@gineshidalgo99 is there a way to use the videoreader.cpp producer with the python wrapper? Or is this something we'll need to rebuild in python?

I would love to see a python example for processing video

Thank you so much!

**Comment by pajama** [comment]
I was able to build something simple with opencv to read the framerate and ffmpeg to output the compiled video from the image directory

`fps = None

        vcap = cv2.VideoCapture(inputMp4Path)
        if vcap.isOpened():
            width = vcap.get(3)
            height = vcap.get(4)
            fps = vcap.get(5)
            print('width: {}, height: {}, fps: {}'.format(width,height,fps))

        opParams = dict()
        opParams['model_folder'] = '/opt/openpose/models';
        opParams['video'] = inputMp4Path;
        opParams['write_json'] = outputJsonPath;
        opParams['display'] = '0'
        #opParams['write_video'] = outputMp4Path
        opParams['write_images'] = outputImagesPath
        opWrapper = op.WrapperPython(3)
        opWrapper.configure(opParams)
        opWrapper.execute()

        subprocess.call([
            'ffmpeg',
            '-y', '-framerate', '{}'.format(fps),
            '-i', '{}{}%12d_rendered.png'.format(outputImagesPath,imageKey),
            '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
            outputMp4Path
        ])`
