### ISSUE TITLE
Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by sakalu** [CMU-Perceptual-Computing-Lab/openpose#1339]
Hi all,

I have tried to install openpose via the instruction here (No GPU, CPU only on my PC) and everything is ok (pyopenpose.cp37-win_amd64.pyd is generated finally); However, I got an error messege " Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version" when I run " C:\Users\GitHub\openpose\examples\tutorial_api_python>python 01_body_from_image.py". 

Does it mean that I should not install CUDA on my PC  as I run it using CPU but not GPU. Thanks!!

**Comment by gineshidalgo99** [comment]
Plese, follow the instrucions and make sure the CMake flag is set to CPU.

**Comment by sakalu** [comment]
Yes, it does work if the GPU_MODE flag is set to CPU_ONLY. Thank you so much!!

How about the issue "Error:Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version" when I Quick Start-Running on Images, Video, Webcam via the instruction from the website below,

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#quick-start

 

Thanks!!

**Comment by flurpo** [comment]
What if we are just running the OpenPoseDemo.exe in windows 10? Can we find a flag to set in a config file? I get the same error above

**Comment by lucyc166** [comment]
@gineshidalgo99 Hi-- I'm having the same issue as @flurpo. I'm running the OpenPose demo in Windows 10 and can't figure out how to set the CMake flag to CPU.

**Comment by ashwani-rathee** [comment]
Any solution to this issue??Same doubt

**Comment by ARUBiomech** [comment]
Same issue here as well .... @gineshidalgo99 

Why has this been closed when so many have the same issue?

**Comment by AzlanCoding** [comment]
I'm having the same issue 🤣 . Really need help...
