### ISSUE TITLE
Cuda check failed (11 vs. 0):invalid     when  camera_resolution=-1x-1

### ISSUE THREAD

**Issue by senshin998** [CMU-Perceptual-Computing-Lab/openpose#1345]
There is a error  in the version 1.50:  Cuda check failed (11 vs. 0):invalid     when  camera_resolution=-1x-1

 It's fine when  camera_resolution=640x480 , It's Weird.

*configaration:
win 10  64bit
cuda : 10.0.150
Graphics card:Geforce gtx1080t x2  by sli
nvidia driver version: 411.63

**Comment by gineshidalgo99** [comment]
Which camera are you using? Because this seems to be an OpenCV-camera codecs/firmware issue.

**Comment by senshin998** [comment]
Thanks for your prompt reply  ,rgb camera on realsense D415.

**Comment by gineshidalgo99** [comment]
Ok, and did it work with 1.4?

**Comment by senshin998** [comment]
yes .It's fine on  all vertions before 1.50

**Comment by senshin998** [comment]
an firmware issue,are you sure ? because 640x480 is  ok

**Comment by senshin998** [comment]
This question has been bothering me for many days ，please  help ,thanks

**Comment by gineshidalgo99** [comment]
For 1.5 I updated OpenCV to 4.

It's gonna take me a few weeks to check it, but if you are in a rush, I'd say that if you replace the OpenCV in OpenPose 1.5 with the one in e.g. OpenPose 1.4, it should work. Let me know if it does! (You would have to replace it in 3rdparty/windows/opencv/ and also the DLLs and also re-compile everything).

**Comment by senshin998** [comment]
thanks   I will do it and feedback Later

**Comment by senshin998** [comment]
Hi ,not work  when change  OpenCV to 3(replace all and re-compile everything), the same   problem!

**Comment by senshin998** [comment]
It's unnecessary to use D415 camera  for test ,  a  image  which  big than  1080x720  may causing display issue  but no cuda check  error ,Maybe the same problem.
