### ISSUE TITLE
Errors happen when make -j`nproc`

### ISSUE THREAD

**Issue by kourenmu** [CMU-Perceptual-Computing-Lab/openpose#1346]
My configure and generate are done. 
But encountering two errors when I make -j`nproc`.

-- Configuring incomplete, errors occurred!
See also "/home/yejunjie/Documents/Github/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/yejunjie/Documents/Github/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:106: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I've tried the approach (sudo apt-get install libboost-all-dev) proposed in https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1109. 
However it doesn't work. 
Does anyone have the same issue?

**Comment by gineshidalgo99** [comment]
[30-day ban for not following the issue template]
