### ISSUE TITLE
Ubuntu: CvMatToOpInput with gpuResize=true leads to crash

### ISSUE THREAD

**Issue by thomasgolda** [CMU-Perceptual-Computing-Lab/openpose#1347]
### Issue Summary
At an earlier point I create two member variables. When calling `mPoseExtractorCaffe.forwardPass()` the application crashes if and only if `mGpuResize` equals `true`.
```cpp
mCvMatToOpOutput = new op::CvMatToOpOutput(mGpuResize);
mOpOutputToCvMat = new op::OpOutputToCvMat(mGpuResize);
```

The following code works when `mGpuResize` is set to `false`. And crashes otherwise.
```cpp
const op::Point<int> imageSize{inputImage.cols, inputImage.rows};
std::vector<double> scaleInputToNetInputs;
std::vector<op::Point<int>> netInputSizes;
double scaleInputToOutput;
op::Point<int> outputResolution;
std::tie(scaleInputToNetInputs, netInputSizes, scaleInputToOutput, outputResolution) = mScaleAndSizeExtractor->extract(imageSize);

// Format input image to OpenPose input and output formats
const auto netInputArray = mCvMatToOpInput->createArray(inputImage, scaleInputToNetInputs, netInputSizes);
auto outputArray = mCvMatToOpOutput->createArray(inputImage, scaleInputToOutput, outputResolution);

// Estimate poseKeypoints
mPoseExtractorCaffe->forwardPass(netInputArray, imageSize, scaleInputToNetInputs);
```

I was wondering where the crash could come from. I've googled for some weeks and tried various things (different commits of OpenPose, different parameters in my code) but nothing seemed to help. With OpenPose 1.4.0 everything worked like a charm, but since 1.5.0 I encountered this problem.

I should also mention, that the code works when it is called the first time. The second time it is called it crashes.

### Errors (if any)
https://pastebin.com/L18Fx3y2

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted

### Your System Configuration
2. **OpenPose version**: current master commit bbef038 but same with v1.5.0 tag

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** Ubuntu 18.04.3 LTS
    - **Release or Debug mode**? release
    - **Compiler** gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** 3.14.1
    - **OpenCV version**: custom compiled (OpenCV 4.1.0)

6. If **GPU mode** issue:
    - **CUDA version** 10.0.130
    - **cuDNN version** 7.4.2
    - **GPU model** GTX 1080 Ti

**Comment by gineshidalgo99** [comment]
Because before 1.5 that GPU version was not available. The GPU resize is optimized for speed, but makes the code more coupled (so most probably you should not try to isolate it). So please, use the default one. It only reduces latency, but it does not really affect the speed of the system.
