### ISSUE TITLE
How does the network split every people's body instead of mix two people's limbs.

### ISSUE THREAD

**Issue by JimReno** [CMU-Perceptual-Computing-Lab/openpose#1349]
I've successfully installed the Openpose project. Thanks for the excellent work! 
- I have a question about how Openpose recognize every person correctly instead of mix two people's limb even they are really close. I know the Openpose detect every limbs in the image instead of detecting people in the image. My shallow understanding is that when an image is sent to the network, firstly, the CNN model proposes every point of interest. Then all the points will use PAF to split every people's limb.

I know I should have read the paper carefully. Please give me some hints about this mechanism. Feel free to ask me to edit this issue if I didn't express well. :)

**Comment by gineshidalgo99** [comment]
Please check the paper for more details. Basically, given the heatmaps you get candidates, and given the PAF you have the lines connecting those candidates, so you know the person.
