### ISSUE TITLE
How to get the poseIds?

### ISSUE THREAD

**Issue by wangwenfeng0** [CMU-Perceptual-Computing-Lab/openpose#1350]
Hello, I need to get all persons' poseIds, but the return value is -1, how can I get it, thank you very much.

datumsPtr = opWrapper.emplaceAndPop(img);
if (datumsPtr != nullptr && !datumsPtr->empty())
{
auto& poseIDs = datumsPtr->at(0)->poseIds;
op::log("Body id: " + poseIDs.toString(), op::Priority::High);
}
![image](https://user-images.githubusercontent.com/16935291/64242380-f90c6200-cf37-11e9-85f0-dd08de9f92fb.png)

**Comment by gineshidalgo99** [comment]
Not available until #1297  is out.
