### ISSUE TITLE
how to show the results in image using json files?

### ISSUE THREAD

**Issue by ivancccka** [CMU-Perceptual-Computing-Lab/openpose#1353]
now i have some json files but i don't know how to read it and show it in images?

**Comment by gineshidalgo99** [comment]
Check doc/output.md to see the format it has, so then you can understand how you could read it later.

**Comment by ivancccka** [comment]
but there is only the c++ api,i wonder if there is the python api

**Comment by jenny353** [comment]
@ivancccka Were you able to figure out how to show the json output on the images? 

@gineshidalgo99 Can you refer us to some of the open-source libraries we can use to read our saved results that were mentioned in the output.md?  And also how to use the functions in "include/openpose/filestream/fileStream.hpp"?

**Comment by gineshidalgo99** [comment]
Python/Matlab contain multiple options to read json files.

C++ also has the "json" library (free on github).

Either of them should be sufficient to read JSON files
