### ISSUE TITLE
Build issues using command "make -j`nproc`"

### ISSUE THREAD

**Issue by mvmnt** [CMU-Perceptual-Computing-Lab/openpose#1354]
### Issue Summary

I'm attempting to build the project running the command above, and it results in the following error.

### Executed Command (if any)

make -j`nproc`

### Errors (if any)

`CMakeFiles/Makefile2:506: recipe for target 'tools/CMakeFiles/upgrade_net_proto_binary.dir/all' failed
collect2: error: ld returned 1 exit status
make[4]: *** [tools/CMakeFiles/upgrade_net_proto_binary.dir/all] Error 2
examples/CMakeFiles/convert_cifar_data.dir/build.make:119: recipe for target 'examples/cifar10/convert_cifar_data' failed
make[5]: *** [examples/cifar10/convert_cifar_data] Error 1
CMakeFiles/Makefile2:834: recipe for target 'examples/CMakeFiles/convert_cifar_data.dir/all' failed
make[4]: *** [examples/CMakeFiles/convert_cifar_data.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:110: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-build' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted
- Build error

### Your System Configuration

Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1092-aws x86_64v)

MXNet-1.4, TensorFlow-1.14, PyTorch-1.1, Keras-2.2, Chainer-6.1, Caffe/2-0.8, Theano-1.0 & CNTK-2.7, configured with NVIDIA CUDA, cuDNN, NCCL, Intel MKL-DNN, Docker & NVIDIA-Docker.

8 vCPUs, memory 32Gb.

(Command line run, hosted on AWS instance t3a.2xlarge)

1. **Whole console output** (if errors appeared), paste the error to [PasteBin]
https://pastebin.com/ByKkR4uN

2. **OpenPose version**: 

Latest GitHub code (I ran "git pull origin master" to get the latest as soon as I cloned. Cloned on Friday the 6th of September 2019)

3. **General configuration**:
    - **Installation mode**: cmake .. (ran from /build directory)
    - **Operating system**: Ubuntu 16.04.6 LTS (xenial)
    - **Operating system version** (Ubuntu 16, Windows 10, ...): Ubuntu 16
    - **Release or Debug mode**? (by default: release): 16.04
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu): cmake version 3.13.3
    - **OpenCV version**: 2.4.9.1+dfsg-1.5ubuntu1.1

6. If **GPU mode** issue: -Not gpu related
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): nil
    - **cuDNN version**: nil
    - **GPU model** (`nvidia-smi` in Ubuntu): nil

7. If **CPU-only mode** issue: nil
    - **CPU brand & model**: nil
    - Total **RAM memory** available: 32 gb

8. If **Python** API: nil
    - **Python version**: 3.6.6
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.15.4

9. If **Windows** system: nil

10. If **speed performance** issue: nil

Thanks for your work! 
I was able to get it to run on my macBook pro osX (my skeleton dances very ggrovvyy), but in setting up on an aws instance I'm running into a little bit of a pickle.
Any help would be appreciated, thanks muchly for your time and effort 👍

**Comment by gineshidalgo99** [comment]
I am sorry, we do not support 3rd-party libraries (the pastebin shows it is a googleprotobuf issue). But from my general experience with it, it's likely that you have more than 1 version of protobuf. The easiest thing it's to completely uninstall any version of protobuf in the system and only install the one that the doc indicates. These errors are really annoying to deal with unfortunately :(

**Comment by mvmnt** [comment]
Hi @gineshidalgo99 ,
So an update, I've managed to get the openpose working on a google cloud platform, where I had control over what exactly goes on it, and it worked successfully! It was indeed because there was a conflicting version of protobuf on the previous aws instance.

Using: an Intel Broadwell CPU platform, machine type n1-standard-2 (2 vCPUs, 7.5 GB memory), NVIDIA Tesla K80, ubuntu-1604-xenial-v20190913 as the os image.

Also closely following the prerequisites file as well helped loads 👍  

I really hope this helps anyone that might be facing this problem now or in the future. 
Thanks for you and your team's work on this project!

**Comment by gineshidalgo99** [comment]
Thanks for the info! So it can help other folks!
