### ISSUE TITLE
example: PoseExtractorCaffe is not a member of 'op'

### ISSUE THREAD

**Issue by bilipa** [CMU-Perceptual-Computing-Lab/openpose#136]
Hi
I run the '1_extract_from_image.cpp' file in codeblock, and it said 
error: 'PoseExtractorCaffe' is not a member of 'op'
I check the hpp and cpp file, ther are exist in ../include/openpose/pose/ and ../src/openpose/pose/
Can you give me some hint?
Thanks

### Executed command (if any)
the build log as follow:
-------------- Build: Debug in sa (compiler: GNU GCC Compiler)---------------

g++ -Wall -std=c++11 -fexceptions -g -std=c++11 -I/usr/include -I../../include -I/usr/local/cuda-8.0/include -I../../3rdparty/caffe/include -I/disk1/openpose-master/include/openpose/pose -I/disk1/openpose-master/src/openpose/pose -I/disk1/openpose-master/3rdparty/caffe/include/caffe -c /disk1/openpose-master/test_folder/sa/main.cpp -o obj/Debug/main.o
/disk1/openpose-master/test_folder/sa/main.cpp: In function ‘int openPoseTutorialPose1()’:
/disk1/openpose-master/test_folder/sa/main.cpp:81:5: error: ‘PoseExtractorCaffe’ is not a member of ‘op’
     op::PoseExtractorCaffe poseExtractorCaffe{netInputSize, netOutputSize, outputSize, FLAGS_scale_number, poseModel,
     ^
/disk1/openpose-master/test_folder/sa/main.cpp:89:5: error: ‘poseExtractorCaffe’ was not declared in this scope
     poseExtractorCaffe.initializationOnThread();
     ^
Process terminated with status 1 (0 minute(s), 1 second(s))
2 error(s), 0 warning(s) (0 minute(s), 1 second(s))
 

### Type of issue
- Compilation error
- Help wanted
- Enhancement / offering possible extensions / pull request / etc

###  system configuration
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

CUDA Version 8.0.61
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
It looks like you are not using properly the Makefile.config, there must be some flag different to the default behaviour.

**Comment by bilipa** [comment]
Thanks for you reply.
I reinstall the openpose but the error is the same.
My install step as follow:
1. make 3rdparty/caffe/Makefile.config
uncomment the OPENCV_VERSION := 3
2. make the openpose Makefile.config
uncomment the OPENCV_VERSION :=3

I dont know where is wrong, every make is successful,but when i run 
g++ examples/openpose/openpose.cpp, it said could not find headers.hpp and cuda.h
when i add -I path where those file are, it said
error: ‘poseExtractorCaffe’ was not declared in this scope

**Comment by gineshidalgo99** [comment]
That can happen if `USE_CAFFE` is not defined, which is by default defined by `-DUSE_CAFFE` on the `Makefile` file given that the `Makefile.config` has `DEEP_NET := caffe` enabled too

**Comment by bilipa** [comment]
Shall I add USE_CAFFE ：= 1 inopenpose Makefile.config?  I did not find USE_CAFFE appear in that file.The file just include DEEP_NET := caffe.
The Makefilefile i did not change anything.
Would you mind give me more detail operate step？ I am new to c++.
Thanks very much

**Comment by bilipa** [comment]
I found this https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/22 issuse, and i add that command in cmake.
The problem was solved.
Thanks for you help

**Comment by gineshidalgo99** [comment]
You should have clearly stated you were using CMake... If I remember correctly, Makefile.config is not used  at all if you are using CMake...

**Comment by bilipa** [comment]
sorry, I said wrong, i was  use make not cmake...
