### ISSUE TITLE
Incorrect documentation for flag "-part_to_show"

### ISSUE THREAD

**Issue by AndroXD** [CMU-Perceptual-Computing-Lab/openpose#1362]
Just wanted to report that when I do the command "OpenPoseDemo --help" on release version 1.5.1, 1.5.0 and 1.4.0 for Windows 10. The instructions for "-part_to_show" flag are incorrect, ie. it says "20 for all the body part heat maps together" but it shows only the left eye, the correct information seems to be "2", looks like all numbers are incorrectly assigned to the wrong body part/option for heatmap/PAF generation.

**Comment by gineshidalgo99** [comment]
You are right! Will fix it in the next commit later tonight.
