### ISSUE TITLE
Source Directory does not Contain CMakeLists.txt (Windows)

### ISSUE THREAD

**Issue by Lininggggggg** [CMU-Perceptual-Computing-Lab/openpose#1363]
i have read this file which is the OpenPose - Frequently Asked Question (FAQ), but the answer couldn't end my question.
the question is still alive.
i met it when i want to run the file "OpenPose Python Module and Demo" ,and i failed at the step of "Compatibility" .
my systems is win10.
thanks!!

**Comment by gineshidalgo99** [comment]
Follow the issue template... Closed until a new message with the template followed is added
