### ISSUE TITLE
Which version of the paper (2016 OR 2018) is the current OpenPose repository configured with ?

### ISSUE THREAD

**Issue by velociraptor111** [CMU-Perceptual-Computing-Lab/openpose#1364]
There are a couple of differences between the older and newer version of the network described in the most recent OpenPose paper https://arxiv.org/abs/1812.08008. 

After looking at the neural network defined in openpose/models/pose/coco/pose_deploy_linevec.prototxt , it seems like the current repository is still configured to network architecture defined in the old paper. Just want to confirm my understanding.

**Comment by gineshidalgo99** [comment]
Yes, models/pose/coco/ corresponds to the old paper. But the default model used by OpenPose includes foot (new paper) and it is placed in models/pose/body25
