### ISSUE TITLE
error no download info for 'openpose_lib'  during CMake-GUI configuration

### ISSUE THREAD

**Issue by andiconda** [CMU-Perceptual-Computing-Lab/openpose#1367]
CPU version ubuntu 14 
during  CMake-GUI configuration, meet the problem"error: pathspec 'b6712ce' did not match any file(s) known to git." and "  error: no download info for 'openpose_lib' -- please specify". how to solve it? 
the output in cmake-gui as follows:

GCC detected, adding compile flags
GCC detected, adding compile flags
Building CPU Only.
Building with MKL support.
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
Try OpenMP C flag = [-fopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Try OpenMP CXX flag = [-fopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Found OpenMP: -fopenmp  
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
fatal: Not a git repository (or any of the parent directories): .git

error: pathspec 'b6712ce' did not match any file(s) known to git.

NOTFOUND
Caffe will be built from source now.
CMake Error at /usr/share/cmake-3.2/Modules/ExternalProject.cmake:1850 (message):
  error: no download info for 'openpose_lib' -- please specify
  existing/non-empty SOURCE_DIR or one of URL, CVS_REPOSITORY and CVS_MODULE,
  SVN_REPOSITORY, GIT_REPOSITORY, HG_REPOSITORY or DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/ExternalProject.cmake:2321 (_ep_add_download_command)
  CMakeLists.txt:775 (ExternalProject_Add)

**Comment by gineshidalgo99** [comment]
[Closed: GitHub issue template not followed]
