### ISSUE TITLE
A simple question about "Calibration toolbox-extrinsic calibration Matrix"(CameraMatrix) 

### ISSUE THREAD

**Issue by GyeoreLee** [CMU-Perceptual-Computing-Lab/openpose#1368]
### Issue Summary
I'm trying to use calibration tool box to calibrate our multi camera system calibration.
I succeeded running calibration tool using my own syncronized multiple camera images. 
And I earned following matrix.(croped from xml)

0\) 
I wonder the meaning of 3x4  CameraMatrix. 
It means translation matrix to reproject image pixels from local camera image to global camera(baseline) image?
Or It means local camera's position and ration to global camera?

1\) 
I want to know other cameras position & rotation(Pitch, Roll, Yaw) via Camera0(global).
I guess 3x4 matrix composed by simple concatenation(Rotation(3x3) + Transition(3x1)).
Is it right?

2\)
If I want to know the rotation angle(roll,pitch,yaw) of local camera to global, do I need a change using additional Formula?

Thank you.

## OpenPose Output (if any)
```
<CameraMatrix type_id="opencv-matrix">
<rows>3</rows>
<cols>4</cols>
<dt>d</dt>
<data>
    8.4965260991319647e-01 1.1164693980389649e-01
    -5.1538859446064478e-01 2.1494190603291283e+00
    -1.5848315388246692e-01 9.8621217567379460e-01
    -4.7630184633558698e-02 -4.5237471366168569e-01
    5.0296474270386005e-01 1.2214952060972525e-01 8.5563190813085876e-01
    1.1418502919988400e+00</data></CameraMatrix>
```

### Type of Issue
- Question

**Comment by gineshidalgo99** [comment]
Thanks, will add this to the doc (let me know if you still have more questions):
Your CameraMatrix will look something like:
```
<CameraMatrix type_id="opencv-matrix">
<rows>3</rows>
<cols>4</cols>
<dt>d</dt>
<data>
    8.4965260991319647e-01 1.1164693980389649e-01
    -5.1538859446064478e-01 2.1494190603291283e+00
    -1.5848315388246692e-01 9.8621217567379460e-01
    -4.7630184633558698e-02 -4.5237471366168569e-01
    5.0296474270386005e-01 1.2214952060972525e-01 8.5563190813085876e-01
    1.1418502919988400e+00</data></CameraMatrix>
```
This is a 3x4 matrix, which represents rotation (R as a 3x3 matrix) and translation (t as a 3x1 matrix) in the following format: [R | t]. They represent the rotation and translation with respect to the world origin. When calibrating with OpenPose, we set one of the cameras as the origin, but this can be easily modified with some manual post-processing.

**Comment by GyeoreLee** [comment]
> Thanks, will add this to the doc (let me know if you still have more questions):
> Your CameraMatrix will look something like:
> 
> ```
> <CameraMatrix type_id="opencv-matrix">
> <rows>3</rows>
> <cols>4</cols>
> <dt>d</dt>
> <data>
>     8.4965260991319647e-01 1.1164693980389649e-01
>     -5.1538859446064478e-01 2.1494190603291283e+00
>     -1.5848315388246692e-01 9.8621217567379460e-01
>     -4.7630184633558698e-02 -4.5237471366168569e-01
>     5.0296474270386005e-01 1.2214952060972525e-01 8.5563190813085876e-01
>     1.1418502919988400e+00</data></CameraMatrix>
> ```
> 
> This is a 3x4 matrix, which represents rotation (R as a 3x3 matrix) and translation (t as a 3x1 matrix) in the following format: [R | t]. They represent the rotation and translation with respect to the world origin. When calibrating with OpenPose, we set one of the cameras as the origin, but this can be easily modified with some manual post-processing.

Thanks to your answers.
I have successfully finished my work.

One more question, Is there a performance evaluation or publication of the calibration module?
I want to know how to measure the performance of your module.

Thanks.

**Comment by gineshidalgo99** [comment]
No, there is not. We simply did it as a demo to show it works, but didn't do any performance test.
