### ISSUE TITLE
faq out of memory clarification regarding Windows demo

### ISSUE THREAD

**Issue by kjacks21** [CMU-Perceptual-Computing-Lab/openpose#1370]
#1180 raised the issue, but the faqs are still unclear about whether you need to install/enable cuDNN when using the Windows demo. Does enabling cuDNN need to be done with both the demo and when building from source?

**Comment by gineshidalgo99** [comment]
You are right, I'll update the faq. This will be the updated one. Thanks for the question!

#### Out of Memory Error
**Q: Out of memory error** - I get an error similar to: `Check failed: error == cudaSuccess (2 vs. 0)  out of memory`.

**A**: Make sure you have a GPU with at least 4 GB of memory. If your GPU is between 2 and 4 GB, it should be fine for body-only settings, but you can also reduce the `--net_resolution` if it does not fit (check [Speed Up, Memory Reduction, and Benchmark](#speed-up-memory-reduction-and-benchmark) for the consequences of this).

(Only if you are compiling OpenPose by yourself, this does not apply to the portable OpenPose binaries for Windows): If you have a GPU with >= 4 GB of memory, and you still face this error, most probably cuDNN is not installed/enabled. The default Caffe model uses >12 GB of GPU memory, cuDNN reduces it to ~2.2 GB for BODY_25 (default) and ~1.5 GB for COCO (`--model_pose COCO`). Note that you still need at least about 2.2 GB free for the default OpenPose to run. I.e., GPUs with only 2 GB will not fit the default OpenPose, and you will have to either switch to the `COCO` model (slower and less accurate), or reduce the `--net_resolution` (faster speed but also lower accuracy).

Also, hands and face increases the GPU memory requeriments, and 4 GB GPUs might run a bit short in some cases.

**Comment by sypei** [comment]
This resolution works for me " --net_resolution 320x320" with a decent performance.
