### ISSUE TITLE
Low detection rate (single person only in each image)(CPU-only mode)

### ISSUE THREAD

**Issue by sakalu** [CMU-Perceptual-Computing-Lab/openpose#1372]
Hi, 
Having a questions regarding low detection rate (single person only in each image). So it still could detect the person on some images (higher contrast, with bigger people); however it will fail for most of images data (smaller people). 

just wondering the case about the solution to "Q:Zero People Detected" provided from the website below is different from mine??
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md#zero-people-detected

Btw, My image database are infrared camera-taken images.  Thanks!!
==================================================
System Configuration
OpenPose version (Latest)
Operating system version (Windows 10)
Compiler (VS2015 Enterprise Update 3)
CPU brand & model: ProcessorIntel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 3600 Mhz, 4 Core(s), 8 Logical Processor(s)
Python version: 3.7

**Comment by gineshidalgo99** [comment]
That answer is when no people is detected ever. Your case is different.

I'll add another section in faq with the following info answering to you:

#### Very Few People Detected
**Q: Low detection rate. It can detect the person on some images (usually higher contrast, with bigger people), but it will fail for most of images with low resolution or small people.**

**A**: Images with low resolution, or with people too tiny will simply not work too well. However, it can be highly improved by using the maximum accuracy configuration detailed in [doc/quick_start.md#maximum-accuracy-configuration](./quick_start.md#maximum-accuracy-configuration).

**Comment by sakalu** [comment]
> That answer is when no people is detected ever. Your case is different.
> 
> I'll add another section in faq with the following info answering to you:
> 
> #### Very Few People Detected
> **Q: Low detection rate. It can detect the person on some images (usually higher contrast, with bigger people), but it will fail for most of images with low resolution or small people.**
> 
> **A**: Images with low resolution, or with people too tiny will simply not work too well. However, it can be highly improved by using the maximum accuracy configuration detailed in [doc/quick_start.md#maximum-accuracy-configuration](./quick_start.md#maximum-accuracy-configuration).

Thank you very much for your reply. Saka
