### ISSUE TITLE
Dll not found

### ISSUE THREAD

**Issue by aniketzz** [CMU-Perceptual-Computing-Lab/openpose#1373]
i trued to execute the Python API on windows. I rebuild the solution on visual studio 2017 and got dll missing error
1. openpose.dll not found
2. opencv_world401.dll not found
3. gflags.dll not found

**Comment by gineshidalgo99** [comment]
[Duplicated]

**Comment by syukranDev** [comment]
At least tell him where is the original link.

**Comment by aha-h** [comment]
[https://blog.csdn.net/qq_44705642/article/details/138624637?spm=1001.2014.3001.5501](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/url) may help you.
