### ISSUE TITLE
[Windows] How to Improve FPS without increasing the latency?

### ISSUE THREAD

**Issue by templarares** [CMU-Perceptual-Computing-Lab/openpose#1374]
### Issue Summary
I've been trying to use OpenPose for my "parallel-control" robot project. I am using three PS3 EYE cameras (each running at 60HZ) as the source for realtime OpenPose 3D-reconstruction. Howvery, currently the FPS rate is capped at 10 (with RTX2080 GPU x 1). Thus, I am trying to find away to increase the speed of Openpose's FPS  without introducing considerate latency. Per issue #336 and /doc/installation.md#maximum-speed, increasing number # GPU should increase FPS linearly but would introduce extra latency. So I was wondering if there is a way to increase OpenPoses's speed for 3D-reconstruction without introducing too much latency in the system? Say, will wearing a more-reconizable cloth help speed up OpenPose's body recognization? Thank you very much for your help! Any idea would be deeply appreciated. 

### Type of Issue

- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
Anything in this section (but will reduce the accuracy)

#### Speed Up, Memory Reduction, and Benchmark
**Q: Low speed** - OpenPose is quite slow, is it normal? How can I speed it up?

**A**: Check [doc/speed_up_openpose.md](./speed_up_openpose.md) to discover the approximate speed of your graphics card and some speed tips.
