### ISSUE TITLE
Openpose issue with Jetson TX2 along with Opencv 4.0.0

### ISSUE THREAD

**Issue by jaiatncson7** [CMU-Perceptual-Computing-Lab/openpose#1377]
Hi, 
I am working on Jetson TX2 and had to install opencv 4.0.0 due to dependency with Yolo obj detection. Now with this latest opencv, i am having the problem with running openpose demo as below. 
Can someone help to fix this issue?

jetson@jetson-desktop: ~/openpose
$ ./build/examples/openpose/openpose.bin -camera_resolution 640x480 -net_resolution 128x96
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...

(openpose.bin:26241): GStreamer-CRITICAL **: 13:57:07.450: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
VIDEOIO ERROR: V4L: can't open camera by index 0

(openpose.bin:26241): GStreamer-CRITICAL **: 13:57:07.472: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
VIDEOIO ERROR: V4L: can't open camera by index 1
Desired webcam resolution 640x480 could not being set. Final resolution: 1280x720 in /home/jetson/openpose/src/openpose/producer/webcamReader.cpp:WebcamReader():36
Auto-detecting camera index... Detected and opened camera 2.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
OpenCV(4.0.0) /home/jetson/opencv-4.0.0/modules/highgui/src/window_gtk.cpp:146: error: (-215:Assertion failed) dst.data == widget->original_image->data.ptr in function 'cvImageWidgetSetImage'

Coming from:
- /home/jetson/openpose/src/openpose/gui/frameDisplayer.cpp:displayFrame():116
- /home/jetson/openpose/src/openpose/gui/frameDisplayer.cpp:initializationOnThread():44
- /home/jetson/openpose/include/openpose/gui/wGui.hpp:initializationOnThread():57
- /home/jetson/openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
- /home/jetson/openpose/include/openpose/thread/subThread.hpp:initializationOnThread():150
- /home/jetson/openpose/include/openpose/thread/thread.hpp:initializationOnThread():173
- /home/jetson/openpose/include/openpose/thread/thread.hpp:threadFunction():203
- /home/jetson/openpose/include/openpose/thread/thread.hpp:exec():128
- /home/jetson/openpose/include/openpose/thread/threadManager.hpp:exec():202
- /home/jetson/openpose/include/openpose/wrapper/wrapper.hpp:exec():424
jetson@jetson-desktop: ~/openpose

**Comment by gineshidalgo99** [comment]
That's an OpenCV-webcam issue, not an OpenPose one. Make sure you can run webcam in OpenCV first.
