### ISSUE TITLE
Windows Compiling error

### ISSUE THREAD

**Issue by duncanmix** [CMU-Perceptual-Computing-Lab/openpose#1378]
I did all the steps I enable BUILD_PYTHON.
There are two errors when I try to compile in Visual Studio 2019.
C1189 2019 unsupported version
LNK 1181 openpose.lib not found

I have reviewed all the issues but I did not find the solution, I do not know what to do and I tried several times with the cmake.
Please help

**Comment by gineshidalgo99** [comment]
[ban for not adding the hw/sw config as requested in the github template]
