### ISSUE TITLE
Is there any way to use thinner lines in hands rendering?

### ISSUE THREAD

**Issue by ArchNew** [CMU-Perceptual-Computing-Lab/openpose#1379]
The demo on the front page of the site seems to have thinner lines in rendering than what I rendered using my own images, especially on hands. I went through the openpose.bin help file and was unable to find any settings regarding the thickness of the rendered lines.
Is there any way for me to customize the lines of the skeleton in the rendering?

**Comment by gineshidalgo99** [comment]
Given that that's CUDA code, it's hard-coded unfortunately. This rendering is only for quick visualization, I'd recommend you to create your own fancy one if you need something fancier.

Still, you can modify the hard-coded values from https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/hand/handParameters.hpp for a quick hack.
