### ISSUE TITLE
Ubuntu: Execution error for --write_keypoint for yml when no person(no keypoint) is detected

### ISSUE THREAD

**Issue by rainforest1** [CMU-Perceptual-Computing-Lab/openpose#138]
### Issue summary
This issue is similar to Issue #21 . When there is no person (or no keypoints) detected in an image, then error "Aborted: Core Dumped" is thrown. This error is raised only when --write_keypoint (default:yml) is included.

### Executed command (if any)
Note: add `--logging_level 0` to get higher debug information.
./build/examples/openpose/openpose.bin --image_dir examples/media/Tops/ --write_images results/ --no_display --write_keypoint results/data/

### OpenPose output (if any)-
OpenCV Error: Bad argument (Unknown object) in cvWrite, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp, line 5015

Error:
/build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:5015: error: (-5) Unknown object in function cvWrite

Coming from:
- src/openpose/filestream/fileStream.cpp:saveData():91
- src/openpose/filestream/keypointSaver.cpp:saveKeypoints():38
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueIn.hpp:work():64
- ./include/openpose/thread/thread.hpp:threadFunction():206
- ./include/openpose/thread/thread.hpp:exec():132
- ./include/openpose/thread/threadManager.hpp:exec():183
- ./include/openpose/wrapper/wrapper.hpp:exec():856
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
/build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:5015: error: (-5) Unknown object in function cvWrite

Coming from:
- src/openpose/filestream/fileStream.cpp:saveData():91
- src/openpose/filestream/keypointSaver.cpp:saveKeypoints():38
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueIn.hpp:work():64
- ./include/openpose/thread/thread.hpp:threadFunction():206
- ./include/openpose/thread/thread.hpp:exec():132
- ./include/openpose/thread/threadManager.hpp:exec():183
- ./include/openpose/wrapper/wrapper.hpp:exec():856

Aborted (core dumped)

### Type of issue
You might select multiple topics, delete the rest:
- Execution error

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu 16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**:
**GPU model** (`nvidia-smi`): GTX 1080
**Caffe version**: Default from OpenPose or custom version. Default
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X. 2.X
Compiler (`gcc --version` on Ubuntu): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
@rainforest1 Good catch. I'll solve it today (I deleted your other post to avoid duplicates) and post here once fixed

**Comment by gineshidalgo99** [comment]
@rainforest1  Again thanks! Fixed. Let me know if you find more problems.
