### ISSUE TITLE
How to get x,y of Face Output Format

### ISSUE THREAD

**Issue by warpdriv** [CMU-Perceptual-Computing-Lab/openpose#1380]
Thank you for creating this and sharing with everyone.

### Issue Summary
I have no problems running any code. I have searched everywhere and are unable to find an answer. Hence my post for assistance.

In the Face Ouput Format of, https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#face-output-format, I would like to get the x, y coordinates (in 2d) of each keypoint for a face.

Thank you for your assistance.

### Executed Command (if any)
I have tried to get this output from the python 04, 06, 08, 09 samples.

### OpenPose Output (if any)
I do get ouput but none of it makes sense in relation of my end goal of getting all the x, y coordinates of the face keypoints in 2d

### Errors (if any)
none

### Type of Issue
- Help wanted

### Your System Configuration
1. 
Windows 10
Python 3.7.3 in a vituralenv
Open Pose 1.5.0
NVidia 1080
PyCharm IDE

2. **OpenPose version**: 
1.5.0 Release

3. **General configuration**:
    - **Installation mode**:  CMAKE GUI, VS 2017 from source
    - **Operating system** Windows
    - **Operating system version** 10
    - **Release or Debug mode**? Release:
    - Compiler VS2017 community

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? BUILD_PYTHON enabled

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): CMake GUI 3.15.2
    - **OpenCV version**:  OpenPose default (only Windows); compiled from source? No, pip install 4.1.1.26

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 3.7.3 in vituralenv
    - **Numpy version**: 1.17.1

9. If **Windows** system:
    - compiled library

**Comment by warpdriv** [comment]
Here is a location of my json out and the example I am working with.

https://drive.google.com/drive/folders/1kgr4Ggq7laa4fJT1HPQ6ULfDTh5afdyG?usp=sharing

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#output-format
