### ISSUE TITLE
How to close the openpose viewer while using custom input and output in synchronous mode?

### ISSUE THREAD

**Issue by ravijo** [CMU-Perceptual-Computing-Lab/openpose#1383]
### Issue Summary
I am using custom input and output in synchronous mode. I can view the openpose detection since I have configured the wrapper to do so in the following way-

```
const op::WrapperStructGui wrapperStructGui{
    op::flagsToDisplayMode(FLAGS_display, FLAGS_3d), 
    !FLAGS_no_gui_verbose, 
    FLAGS_fullscreen};
opWrapper.configure(wrapperStructGui);
```

This works without any issue. However, it is not possible to close the viewer (therefore process) by using <kbd>CTRL</kbd> + <kbd>C</kbd> or <kbd>ESC</kbd> or <kbd>Q</kbd> key.

_I want to know how to close the openpose viewer while using custom input and output in synchronous mode?_ 

### Possible Workaround
At present, in order to close the viewer, I have done the following-

1. Disabled the default openpose viewer in the following way-
    ```
    opWrapper.configure(op::WrapperStructGui{});
    ```
1.  Added opencv `imshow` inside the outpur worker in the following way-
    ```
    cv::imshow(OPEN_POSE_NAME_AND_VERSION, datumsPtr->at(0)->cvOutputData);
    const char key = (char)cv::waitKey(1);
    if (key == 27)
        this->stop();
    ```

_However, my main motive for adding the custom output worker is not to display the detection. In fact, I believe that adding `imshow` and `this->stop()` on output worker may reduce the performance of this worker._

Furthermore, it would be great to see the detection on the inbuilt openpose viewer since it provides much more information (for example FPS, etc.).

**Therefore, I am looking for a way to close the openpose viewer while using custom input and output in synchronous mode.**

### Type of Issue
- Help wanted
- Question

### Your System Configuration
1. **OpenPose version**: Latest GitHub code
2. **General configuration**:
    - **Installation mode**: CMake (Ubuntu)
    - **Operating system**:
        ```
        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 14.04.6 LTS
        Release:	14.04
        Codename:	trusty
        ```
    - **Operating system version**: Ubuntu 14
    - **Release or Debug mode**: release
    - **Compiler**:
        ```
        gcc (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010
        Copyright (C) 2015 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        ```

4. **Non-default settings**:
    - **3-D Reconstruction module added**: No

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**:
        ```
        cmake version 3.10.1

        CMake suite maintained and supported by Kitware (kitware.com/cmake).
        ```
    - **OpenCV version**: 2.4.8

**Comment by gineshidalgo99** [comment]
```
cv::imshow(OPEN_POSE_NAME_AND_VERSION, datumsPtr->at(0)->cvOutputData);
const char key = (char)cv::waitKey(1);
if (key == 27)
    this->stop();
```
That's not a workaround, that's the way! That's why it's added in the tutorial examples. stop() is closing the threads in a ordered way, making sure to process all frames until it was pressed. That's what you want.

**Comment by ravijo** [comment]
I understand. Please allow me to ask an extended question. How to quit OpenPose if no GUI is active via <kbd>CTRL</kbd> + <kbd>C</kbd>?

I guess I have to add a keystroke listener to call `this->stop()`, though I am not sure. More specifically, since `opWrapper.execute()` is a blocking method, the keystroke listener can’t be added to the main method, instead it should be added to custom worker class. Can you please have a look on this?

**Comment by gineshidalgo99** [comment]
If you want to manually stop it, I guess you could either:
1. Use asynchronous for easy control of the variable.
2. (recommended) Don't use execute but the other alternative that does not block the thread. So you can use that thread to stop it.

**Comment by ravijo** [comment]
Hi @gineshidalgo99 

> 2. (recommended) Don't use execute but the other alternative that does not block the thread. So you can use that thread to stop it.

Thank you very much. Oh yes, I somehow forgot `opWrapper.start()` and  `opWrapper.stop()` methods. 

Thanks
