### ISSUE TITLE
Support to include OpenPose as sub project

### ISSUE THREAD

**Issue by Joe136** [CMU-Perceptual-Computing-Lab/openpose#1384]
Hi,
I want to add this project with `add_subdirectory(3rdParty/OpenPose)`. This is impossible because `CMAKE_SOURCE_DIR` is used in several places, e.g. to include _cmake/Utils.cmake_, which points into the top-level project (I'm possibly also not the top-level project).

I recommend to define a variable in the top CMakeLists.txt and set it to CMAKE_CURRENT_SOURCE_DIR

```
project(OpenPose)
set(OpenPose_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
set(OpenPose_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}")
```
and later
```
include(${OpenPose_SOURCE_DIR}/cmake/Utils.cmake)
```
CMake version: 3.15.3
OpenPose & Caffe version: master

**Comment by Joe136** [comment]
in my project, I also include Caffe with `add_library()`, set BUILD_CAFFE=OFF  and define Caffe_INCLUDE_DIRS/Caffe_LIBS

I get this error because of the command `add_library(caffe SHARED IMPORTED)`
`add_library cannot create imported target "caffe" because another target with the same name already exists.`

I recommend to move this into the e.g. src/CMakeLists.txt and check for existence before defining it.

**Comment by Joe136** [comment]
Further I get this error:
```
CMake Error at 3rdParty/OpenPose/CMakeLists.txt:1059 (add_custom_target):
  add_custom_target cannot create target "uninstall" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "<root>/3rdParty/caffe"
```
``` CMake
add_custom_target(uninstall
    COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake)
```
This conflicts with the existing Caffe project. The keyword 'uninstall' is generic and can occur in other projects as well. I recommend to check for existence before defining it (or remove the target first).

**Comment by gineshidalgo99** [comment]
Unfortunately, I do not have the time for this.

But if you manage to make it work with the edits you mention, feel free to make a pull request! That seems like a useful thing to have!
