### ISSUE TITLE
Can't download getModels.bat. CMU site not responding 

### ISSUE THREAD

**Issue by tstreufert** [CMU-Perceptual-Computing-Lab/openpose#1387]
------------------------- BODY, FOOT, FACE, AND HAND MODELS -------------------------
----- Downloading body pose (COCO and MPI), face and hand models -----

------------------------- POSE (BODY+FOOT) MODELS -------------------------
Body (BODY_25)
--2019-10-02 10:21:41--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 104715850 (100M), 104674681 (100M) remaining [text/plain]
Saving to: 'pose/body_25/pose_iter_584000.caffemodel'

pose_iter_584000.caffemodel     0%[                                                  ]  84.15K  --.-KB/s    eta 11d 6h

**Comment by gineshidalgo99** [comment]
[Duplicated...]
Just try again after a few minutes / hours.
