### ISSUE TITLE
A possible bug in Tutorial_api_cpp

### ISSUE THREAD

**Issue by VisImage** [CMU-Perceptual-Computing-Lab/openpose#1388]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
A possible typo in line 60 of file 01_body_from_image_default.cpp

### Errors (if any)
when compile, the following error appears:
\openpose\examples\tutorial_api_cpp\01_body_from_image_default.cpp(60): error C2039: 'poseKeypoints': is not a member of 'std::shared_ptr<op::Datum>'

### Fix
The following change resolves the error:
from :         const auto& poseKeypoints = datumsPtr->at(0).poseKeypoints;
to :             const auto& poseKeypoints = datumsPtr->at(0)->poseKeypoints;

### Your System Configuration
VS2019 on Windows 10

**Comment by VisImage** [comment]
There was a copy-paste in my original report. The compiling  error is :
openpose\examples\tutorial_api_cpp\01_body_from_image_default.cpp(60): error C2039: 'poseKeypoints': is not a member of 'std::shared_ptr<<op::Datum>>'
It is also checked on VS2017 windows 10. the same error appears
It seems in GitHub, the contents in comment: write  differs from those in comment: preview.

**Comment by gineshidalgo99** [comment]
Corrected in the latest commit. Thanks for the catch.
