### ISSUE TITLE
Cuda check failed (11 vs. 0): invalid argument

### ISSUE THREAD

**Issue by testbot018** [CMU-Perceptual-Computing-Lab/openpose#1389]
Sorry for bothering, but I really don't understand what happen in this error?
Can anyone give me a hand?

###
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Cuda check failed (11 vs. 0): invalid argument

Coming from:
- C:\Users\IIS2622\Documents\openpose\src\openpose\net\netCaffe.cpp:op::NetCaffe::forwardPass():248
- C:\Users\IIS2622\Documents\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():42
- C:\Users\IIS2622\Documents\openpose\src\openpose\net\netCaffe.cpp:op::NetCaffe::forwardPass():256
- C:\Users\IIS2622\Documents\openpose\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::forwardPass():626
- C:\Users\IIS2622\Documents\openpose\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::forwardPass():53
- C:\Users\IIS2622\Documents\openpose\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::work():107
- C:\Users\IIS2622\Documents\openpose\include\openpose/thread/worker.hpp:op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::checkAndWork():93
- [All threads closed and control returned to main thread]
- C:\Users\IIS2622\Documents\openpose\src\openpose\utilities\errorAndLog.cpp:op::checkWorkerErrors():280
- C:\Users\IIS2622\Documents\openpose\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::stop():243
- C:\Users\IIS2622\Documents\openpose\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::exec():202
- C:\Users\IIS2622\Documents\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
[ WARN:2] global C:\build\master_winpack-build-win64-vc14\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
###

Device:
Windows 10
CUDA 8
cuDNN 5.1
GTX 1060 max q

Sorry for bad English

**Comment by skyoung** [comment]
same problem. Have you sovled it?

**Comment by gineshidalgo99** [comment]
[Ban for not adding the hardware configuration, we can't help if you don't give us your system info...]
