### ISSUE TITLE
[doc] Documentation report wrong number of hand keypoints

### ISSUE THREAD

**Issue by severin-lemaignan** [CMU-Perceptual-Computing-Lab/openpose#139]
Documentation on the [handKeypoints structure](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/39a0d767b05c23d55c9427ce623f7eb087505f3a/include/openpose/core/datum.hpp#L99) incorrectly reports 20 hand parts instead of 21, as correctly reported [here](
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md)

**Comment by gineshidalgo99** [comment]
You are right, it is 21, sorry for the confusion. Fixed!
