### ISSUE TITLE
Problem with the installing python api

### ISSUE THREAD

**Issue by franklu323** [CMU-Perceptual-Computing-Lab/openpose#1391]
Hi there,
I am already followed the readme file and I'm trying to use openpose python api.
I have successfully generated the code by using CMake and the vs2017(release/x64). However, I could not find neither pyopenpose.cp36-win_amd64.pyd nor pyopenpose.pyd (and there was no such folder in dir ../../python/openpose/Release).
I tried to delete the original openpose and CMake it again and still no Release file in /python/openpose/
![微信截图_20191008150033](https://user-images.githubusercontent.com/28680833/66361746-6babaa00-e9dc-11e9-9a92-61a2fa4446d9.png)
Did I do something wrong??

**Comment by MAli-Haider** [comment]
Did you find a solution to your problem?

**Comment by racchit** [comment]
I'm facing the same problem, could you explain what you did?

**Comment by MAli-Haider** [comment]
Whilst building Openpose via Cmake make sure you have selected Build Python Flag.
After building openpose.sln from MS Visual Studio, in the same column will be pyopenpose, right clock on pyopenpose and then click build.
Pyopenpose doesnt automatically build itself, You will have to build it manually.
