### ISSUE TITLE
Windows, Python API tutorial execution error

### ISSUE THREAD

**Issue by bluesy7585** [CMU-Perceptual-Computing-Lab/openpose#1392]
Hi
I successfully build and run C++ tutorial **01_body_from_image_default.exe**
but python tutorial does not show anything.

after uncomment line70 in **01_body_from_image.py**
it shows some error message
### System Configuration
Windows 7, Visual Studio 2017, CMake 3.14.1
CUDA 10
Python 3.6.7 (Anaconda env)

### Executed Command (if any)
`..\openpose\build\examples\tutorial_api_python>python 01_body_from_image.py`

### OpenPose Output (if any)
```
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting
 at GPU 0.
```
### Errors (if any)
uncomment line70 in 01_body_from_image.py
it shows
```
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting
 at GPU 0.
(): incompatible function arguments. The following argument types are supported:

    1. (self: pyopenpose.Datum, arg0: op::Matrix) -> None

Invoked with: <pyopenpose.Datum object at 0x0000000009F51FB8>, array([[[ 60, 129
, 102],
...
```
how do I fix this?
thanks

**Comment by Chenxi93** [comment]
Hi I also got this problem. But a few days ago it still worked. Is there some upates leading to this problem or ?

**Comment by PawelFaron** [comment]
@Chenxi93 @bluesy7585 
I had the same problem. It turned out that this line was problematic as the given path didn't existed.

> imageToProcess = cv2.imread(args[0].image_path)

**Comment by PawelFaron** [comment]
Same here.

**Comment by vineet54** [comment]
I had the same problem on Ubuntu 18.04, CUDA 10.1, Python 3.6.

I solved it by reverting to this commit [06d4ea6](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/06d4ea657a0df1a14bcfc3c6b20c01d9db3db844)

`git reset --hard 06d4ea6`
`cd build`
`make`

**Comment by Aakash95-co** [comment]
Thanks It works for me. 
I had the same problem on Ubuntu 16.04 with python3 and cpu-only mode.

**Comment by Trolloldem** [comment]
Works for me as well

**Comment by gineshidalgo99** [comment]
Fixed in the latest commit. Sorry for the troubles.
