### ISSUE TITLE
Cmake boost lib issue

### ISSUE THREAD

**Issue by kk-1** [CMU-Perceptual-Computing-Lab/openpose#1393]
Hello Folks,
I got 64 bit OpenSUSE Tumbleweed with cmake version 3.15.3 and using the default caffe that comes with OpenPose. For compiling, I got the following error. Any idea?

Thanks for your time...
--------------------------------------------------------------------------------------------
[ 12%] Performing configure step for 'openpose_lib'
CMake Warning (dev) at cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/lib64/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_system"
  (requested version 1.71.0) with any of the following names:

    boost_systemConfig.cmake
    boost_system-config.cmake

  Add the installation prefix of "boost_system" to CMAKE_PREFIX_PATH or set
  "boost_system_DIR" to a directory containing one of the above files.  If
  "boost_system" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake/Modules/FindBoost.cmake:443 (find_package)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:49 (include)

-- Configuring incomplete, errors occurred!

--------------------------------------------------------------------------------------------

**Comment by gineshidalgo99** [comment]
OpenSUSE is not officially supported and this question is about 3rd-party libraries (boost), so closed to focus in other important issues.  Other people that has used OP in OpenSUSA, feel free to answer!
