### ISSUE TITLE
How to access keypoints from Openpose on windows? using data from videos/images. not real-time

### ISSUE THREAD

**Issue by dddqqq** [CMU-Perceptual-Computing-Lab/openpose#1395]
Hi everyone,

I am quite knew in openPose. I searched for this question but I could not get clarified answers.
I don't know how to access the keypoints from images/videos on Windows 10/Python 3.7.

I found in here https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md that it is as a .json file we should open the keypoints.

However, when I opened using pycharm, data does not appear and it says format is not the right one.

Thank you in advance and appreciate your help.
I also know that using Ubuntu will make things easier (but i am stilll in the process of installing all the needed dependencies)

**Comment by gineshidalgo99** [comment]
[Ban for not reading the doc, it is quite clearly in there...]
