### ISSUE TITLE
How to debug "vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)"?

### ISSUE THREAD

**Issue by anthnyprschka** [CMU-Perceptual-Computing-Lab/openpose#1396]
I've been running into the following error when trying to do extrinsic calibration:
```
root@8b62f518b143:/openpose# ./build/examples/calibration/calibration.bin --mode 2 --grid_square_size_mm 51.0 --grid_number_inner_corners 9x6 --omit_distortion --calibration_image_dir /data/images_extrinsic_undistorted/ --cam0 1 --cam1 2
Starting OpenPose calibration toolbox...
Running calibration (extrinsic parameters)...

Error:
vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)

Coming from:
- /openpose/src/openpose/calibration/cameraParameterEstimation.cpp:estimateAndSaveExtrinsics():1212
```
Can someone give me some hints on how to debug this? I have basic knowledge of C++. I found this issue that reported the same error but with a different stacktrace: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1239

**Comment by anthnyprschka** [comment]
Nvm, had something to do with camera indices

**Comment by clayding** [comment]
I met the same problem,  how did you solve it? @anthnyprschka

**Comment by anthnyprschka** [comment]
@clayding i think i needed to change the camera indices to `--cam0 0 --cam1 1`
