### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by luoluo-gif** [CMU-Perceptual-Computing-Lab/openpose#1399]
I want use this(such as 'from openpose import pyopenpose as op').My environment is win 8 ,python3.7 (and I'm using pycharm+anaconda),but I'm a little confused about **"To compile, enable BUILD_PYTHON in CMake-gui, or run cmake -DBUILD_PYTHON=ON .. from your build directory. In Windows, make sure you compile the whole solution (clicking the green play button does not compile the whole solution!). You can do that by right-click on the OpenPose project solution, and clicking in Build Solution (or individually building the PyOpenPose module)."**

When I just do as mentioned above，I got an error such as this:
![image](https://user-images.githubusercontent.com/54338956/66811363-872a2e00-ef63-11e9-9e34-0bd9617fc7ea.png)
![image](https://user-images.githubusercontent.com/54338956/66811750-37983200-ef64-11e9-9012-4fcfed3adf06.png)

How can sovle this question?Can you give me some suggestion?

**Comment by luoluo-gif** [comment]
**And I found that my computer does not have vs2015(or vs2019?). Do I must install it?**

**Comment by gineshidalgo99** [comment]
Ban: GitHub issue template not followed.
