### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by igormcsouza** [CMU-Perceptual-Computing-Lab/openpose#1401]
# Issue Summary
I getting this msg always when trying to install openpose! I'm sure I got all the prerequisites and installed them on the right version! I also try FAQ, but not successful! 

I've done so far.. 
1. Installed prerequisites and CMAKE
2. Through CMAKE-GUI I configurate and generate MakeFile
3. Breaks on the last part of tutorial - when typed make -j`nproc`

### Executed Command (if any)
make -j`nproc`

### OpenPose Output (if any)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /data/openpose/3rdparty/caffe/src/caffe
CUDA_curand_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /data/openpose/3rdparty/caffe/src/caffe

-- Configuring incomplete, errors occurred!
See also "/data/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/data/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:105: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Type of Issue
- Installation Process

### Your System Configuration
Openpose -> Latast
Cuda -> 8
Cmake -> 3.12.2
Ubuntu 16.04

**Comment by Pandasea** [comment]
I solved this problem by reinstalling cmake. Ubuntu 18
Ubuntu 18: Download and compile CMake-gui from source. The default CMake-gui version (3.10) installed via sudo apt-get install cmake-qt-gui provokes some compiling errors. Required CMake version >= 3.12.
Uninstall your current Cmake-gui version by running sudo apt purge cmake-qt-gui.
Run sudo apt-get install qtbase5-dev.
Download the Latest Release of CMake Unix/Linux Source from the CMake download website, called cmake-X.X.X.tar.gz.
Unzip it and go inside that folder from the terminal.
Run ./configure --qt-gui. Make sure no error occurred.
Run ./bootstrap && make -j8 && make install -j8. Make sure no error occurred.
Assuming your CMake downloaded folder is in {CMAKE_FOLDER_PATH}, everytime these instructions mentions cmake-gui, you will have to replace that line by {CMAKE_FOLDER_PATH}/bin/cmake-gui.

**Comment by gineshidalgo99** [comment]
THanks for the fix pandasea.

**Comment by mmiakashs** [comment]
I am using cmake version 3.16.0-rc3, I am also facing the same error. What can I do?

**Comment by mmiakashs** [comment]
I think there is a compatibility issue of CUDA_cublas_LIBRARY in CUDA 10.1. I solved this problem by downgrading CUDA from 10.0 to 10.1

**Comment by quan-nguyen-7121996** [comment]
I have the same problem with cuda 9.0 and cmake 3.13.0. Please help me.

**Comment by Alex-Beh** [comment]
> I think there is a compatibility issue of CUDA_cublas_LIBRARY in CUDA 10.1. I solved this problem by downgrading CUDA from 10.0 to 10.1

Do you mean from 10.1 to 10.0?

**Comment by Kismetzc** [comment]
The same question. Did you slove it?

**Comment by KangYoungSeo** [comment]
I got the same question. did you solve that?
CUDA version 11.0 in my container server
Do i have to downgrade CUDA version?

**Comment by sycomix** [comment]
i did, i ended up making a symbolic link with the correct name and path
from the newer resource. its hacky but it works
