### ISSUE TITLE
Hyperparameters for hand pose

### ISSUE THREAD

**Issue by marcobarnobi** [CMU-Perceptual-Computing-Lab/openpose#1404]
### Issue Summary
I am trying to apply openpose for hand pose detection in the following settings:
- The head of the recorded subject is not visible
- The hand is close to the camera, which means that its proportion to the body is not standard. In other words, the subject is close to the camera and brings its hand forward towards the camera, so the hand looks bigger. 

I am attaching an image that exemplifies the settings. 

Given these settings, I am using the command:
**./build/examples/openpose/openpose.bin --hand --hand_scale_number 6 --hand_scale_range 0.4**

I would like to optimise the hand pose performance for this specific application, so I am wondering how I could improve the hyperparameters selection (  --hand_scale_number, --hand_scale_range).

Is there a guideline explaining the function and range of these hyperparameters? I am also wondering...  Do the values of these hyperparameters affect the runtime? If yes, how? 

Finally, I noticed that openpose struggles estimating the pose of hands close to the camera. Is this due to the lack of this type of images in the training dataset used to train openpose or is it consequence of a bad hyperparams choice? 

I would be grateful for any support. 

![Screenshot from 2019-10-18 21-11-34](https://user-images.githubusercontent.com/17983807/67121554-13e71d00-f1ec-11e9-9405-cdf9a4d1684a.png)

### Type of Issue
- Help wanted
- Question
- Hyperparameters

**Comment by gineshidalgo99** [comment]
If the wrist is lost, OpenPose will never be able to detect the hand.

For your case, you might want to try BODY_135 from:
https://github.com/CMU-Perceptual-Computing-Lab/openpose_train

Or you can provide your own bounding boxes of the hand.

**Comment by marcobarnobi** [comment]
Thank you for the answer @gineshidalgo99 !
Good to know that this is not about hyperparameters settings.
:)
