### ISSUE TITLE
Zero Persons Found  HDF5: infinite loop closing library 

### ISSUE THREAD

**Issue by rfmahmood** [CMU-Perceptual-Computing-Lab/openpose#141]
Hi, I am not getting any error while compilation. When I run the video provided with the  code, I see the video display but with a message 0 People found. No pose is displayed. 

The same happen in case I run  webcam. Display is there but no person detected. 

### Executed command 

./build/examples/openpose/openpose.bin --video examples/media/video.avi

####Openpose response:
HDF5: infinite loop closing library D,T,F,FD,P,FD,P,FD,P,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E

Ubuntu 14.04 LTS
CUDA 8.0
cuDNN 5.1

Please suggest some solution

**Comment by gineshidalgo99** [comment]
It might happen if the models have not being properly downloaded. Could you go to models folder and execute the `getModels.sh` from the bash terminal file until a message like `Model already downloaded, not downloaded again` appears?

**Comment by rfmahmood** [comment]
## Following is the response of running  sudo ./getModels.sh
 
--2017-07-14 13:07:02--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2017-07-14 13:07:03--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/mpi/pose_iter_160000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2017-07-14 13:07:04--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/face/pose_iter_116000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2017-07-14 13:07:04--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/hand/pose_iter_102000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

**Comment by gineshidalgo99** [comment]
OK. Could you try 109#issuecomment-311671367 ?

**Comment by rfmahmood** [comment]
Problem partially solved. Now I am getting the person and pose detection. However the HDF5 error message is still there. 

My problem was with cuDNN. When I run 'make runtest' on caffe in 3rdparty folder, some cudnn related tests  failed. More specifically, I run '

$ make runtest GTEST_FILTER='CuDNNConvolutionLayerTest*' 

and got following response: 

[----------] Global test environment tear-down
[==========] 12 tests from 2 test cases ran. (11899 ms total)
[  PASSED  ] 7 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionGroupCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSobelConvolutionCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionCuDNN, where TypeParam = float

 5 FAILED TESTS
make: *** [runtest] Error 1
_____________________________________________________________
I changed the version of cuDNN  from 5.1 to 6 and  copied files from cuDNN folder as:
$ sudo cp -P include/cudnn.h /usr/include
$ sudo cp -P lib64/libcudnn* /usr/lib/x86_64-linux-gnu/
$ sudo chmod a+r /usr/lib/x86_64-linux-gnu/libcudnn*

Also copied same files to  /usr/local/cuda/include and /usr/local/cuda/lib64

$sudo cp -P include/cudnn.h /usr/local/cuda/include
$ sudo cp -P lib64/libcudnn* /usr/local/cuda/lib64
$ sudo chmod a+r /usr/local/cuda/lib64/libcudnn*

Now I  can see the pose  wireframe overlay on video and images.

**Comment by gineshidalgo99** [comment]
This is a very old issue. Closed for now. Post again if it happens in the latest OpenPose versions.
