### ISSUE TITLE
Convert to pytorch

### ISSUE THREAD

**Issue by frankcarey** [CMU-Perceptual-Computing-Lab/openpose#1411]
Now that Caffe is dead and Caffe2 is being merged with PyTorch, should things be updated to use Pytorch 1.x? Is anyone planning to work on this already?

### Context
I'm trying to get the CMU "Monocular Total Capture" project running, and it uses openpose as a dependency. I'm dockerizing things, but the dependencies are still a pain. I noticed that one of the maintainers has been [asking for help with a port of the BM25 model to pytorch at least]( https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1108#issuecomment-467701131). I could be interested in helping with that, as I'm doing a lot of pose research, but it would be helpful to know what exactly needs to be changed. I assume it's mainly reading the caffe protobuf and converting that instead to pytorch?

**Comment by soulslicer** [comment]
I briefly worked on a Pytorch version if that helps:

https://github.com/soulslicer/pytorch_openpose

**Comment by delebash** [comment]
Is the move to pytorch officially planned?

**Comment by MohamedAliRashad** [comment]
What does it take to convert to PyTorch ?
