### ISSUE TITLE
Python API tutorial on Windows 10

### ISSUE THREAD

**Issue by A-zih** [CMU-Perceptual-Computing-Lab/openpose#1414]
### Issue Summary
I have a common issue of running python API tutorial on Windows, and I have tried a lot of solutions, but it still doesn't work.
After I run `01_body_from_image.py` (I am  sure that I run it under `build\examples\tutorial_api_python`)
`Error: OpenPose library could not be found. Did you enable BUILD_PYTHON in CMake and have this Python script in the right folder?
No module named 'pyopenpose'`
![1572358432909](https://user-images.githubusercontent.com/44132730/67775935-95fffd00-fa9a-11e9-9dd6-3dbfc2da4a80.jpg)

I have set `BUILD_PYTHON` to ON and I do have those directories. 
Under `build\python\openpose`:
-CMakeFiles
-cmake_install.cmake
-INSTALL.vcxproj
-INSTALL.vcxproj.filters
-pyopenpose.dir
-pyopenpose.vcxproj
-pyopenpose.vcxproj.filters
-Release
-__init__.py

Under `build\python\openpose\Release`:
**-pyopenpose.cp37-win_amd64.pyd
-pyopenpose.exp
-pyopenpose.lib**
 

### System Configuration
-CUDA 10.1
-Cudnn 7.6.1
-VS 2019
-Python 3.6.8 (anaconda)
-Numpy 1.16.4
-CMake 3.14.5

I wonder if it's a problem of environment variables or I didn't install Openpose correctly. It bothers me for a couple of days. This is my first time posting an issue, so please tell me if any further information needed.

**Comment by 2387762766** [comment]
How did you solve the problem. I have this problem, too.

**Comment by gineshidalgo99** [comment]
Provide exact instructions to reproduce it, close until those instructions are added.

**Comment by MAli-Haider** [comment]
I have the exact same issue, Any help would be appreciated

**Comment by A-zih** [comment]
@MAli-Haider hi! you can try creating a new environment with `Python 3.7` and install the following packages with specific version.

- `numpy 1.17`
- `opencv-python 4.1.2`
![upq4dil](https://user-images.githubusercontent.com/44132730/76824928-8ae41880-6853-11ea-8b8e-43d459a5a32e.jpg)
