### ISSUE TITLE
Export to BVH

### ISSUE THREAD

**Issue by jlsneto** [CMU-Perceptual-Computing-Lab/openpose#1416]
### Type of Issue
- Question

Are you still working on the writing module for .bvh files?

**Comment by edmondboulet** [comment]
I would be interested in the answer as well.

**Comment by gineshidalgo99** [comment]
Bvh requires joint angles, not (only) 3-D keypoints, so it's not trivially possible. But open to any PR or approximation.

**Comment by csaund** [comment]
Working on same issue -- this was a helpful starting point for me: https://github.com/KevinLTT/video2bvh

**Comment by ideo65** [comment]
Hi @csaund 
have you been able to use video2bvh ?
Or maybe you find other project that do similar conversion ? I'm interested
thanks !

**Comment by Sba-Stuff** [comment]
I wonder why don't authors release, .pyd and .so of openpose.?
