### ISSUE TITLE
Problem with USE_EIGEN flag when using release version to estimate extrinsics - Windows - Release 1.5.1

### ISSUE THREAD

**Issue by usefulslug** [CMU-Perceptual-Computing-Lab/openpose#1417]
### Issue Summary
When I try to run the command:
bin\Calibration.exe --mode 2 --grid_square_size_mm 40.0 --grid_number_inner_corners 8x6 --omit_distortion --calibration_image_dir D:/Extrinsics/ --cam0 1 --cam1 0

I get an output error saying:
CMake flag `USE_EIGEN` required when compiling OpenPose`.

I am in the process of trying to calibrate my multi camera setup to be able to do 3d pose estimation.
I am using the pre-compiled release "openpose-1.5.1-binaries-win64-gpu-python-flir-3d_recommended.zip" from the releases page, and trying to follow the documentation found here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/calibration_module.md

### Executed Command (if any)
bin\Calibration.exe --mode 2 --grid_square_size_mm 40.0 --grid_number_inner_corners 8x6 --omit_distortion --calibration_image_dir D:/Extrinsics/ --cam0 1 --cam1 0

### OpenPose Output (if any)
Starting OpenPose calibration toolbox...
Running calibration (extrinsic parameters)...
Error:
CMake flag `USE_EIGEN` required when compiling OpenPose`.
Coming from:
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\calibration\cameraParameterEstimation.cpp:op::estimateAndSaveExtrinsics():1181
- D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\calibration\cameraParameterEstimation.cpp:op::estimateAndSaveExtrinsics():1186

### Errors (if any)
CMake flag `USE_EIGEN` required when compiling OpenPose`.

### Type of Issue
- Execution error
- Help wanted
- Question

### Your System Configuration
2. **OpenPose version**: 
Release: openpose-1.5.1-binaries-win64-gpu-python-flir-3d_recommended.zip

3. **General configuration**:
Windows 10 
Pre-compiled release version

9. If **Windows** system:
    - Portable demo

**Comment by AmesingFlank** [comment]
I'm running into the same problem. Does this mean I must build Openpose from source if I wish to use the extrinsics calibration tool?

**Comment by hadi1376tm** [comment]
hi, did you find the solution.

**Comment by usefulslug** [comment]
> 
> 
> hi, did you find the solution.

For me at the time, the solution was to compile from source.

**Comment by nayha-auradkar** [comment]
In addition to compiling from source, try setting the WITH_EIGEN field in cmake to AUTOBUILD.
