### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by hkpc0715** [CMU-Perceptual-Computing-Lab/openpose#1419]
CMake Error at /usr/share/cmake-3.10/Modules/ExternalProject.cmake:2474 (message):
  No download info given for 'openpose_lib' and its source directory:

   /home/hkpc/Documents/1. openpose-1.5.0/3rdparty/caffe

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/ExternalProject.cmake:3029 (_ep_add_download_command)
  CMakeLists.txt:788 (ExternalProject_Add)

**Comment by helenrensiyu** [comment]
I have the same problem. Could someone help please?

**Comment by gineshidalgo99** [comment]
[Ban for not include all the info that the template asks for...]
