### ISSUE TITLE
Person/Pose detection with Intel RealSense Camera

### ISSUE THREAD

**Issue by Ceepert** [CMU-Perceptual-Computing-Lab/openpose#1420]
I am currently trying to detect the pose of a single person captured by an Intel RealSense Camera using OpenPose in Python.

I am complete beginner in this field and would like to know where to find some guides or even just the commands for those functions.
I saw that the feature "3D real-time single-person keypoint detection" was given, but cant find anything related to it, only how to do person detection with a normal 2D image.

**Comment by gineshidalgo99** [comment]
The doc answers all of these questions... But we do not support RealSense camera, only calibrated multi-view 3-D flir cameras as the doc says.
