### ISSUE TITLE
Recorded depth.avi video as input

### ISSUE THREAD

**Issue by Julian243** [CMU-Perceptual-Computing-Lab/openpose#1422]
I recorded a video sequence using OpenNI for RealSense. I converted the video from .oni to .avi using this tool: https://github.com/KirillLykov/oni2avi. How can I use the avi depth video as an input for Openpose? The 3D Reconstruction module seems to expect multiple camera views as an input.
I am thankful for any help!
Thank you in advance!

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/281
