### ISSUE TITLE
MacOS / clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by IcyW** [CMU-Perceptual-Computing-Lab/openpose#1424]
### Issue Summary
Build failing with error: Undefined symbols for architecture x86_64

### Executed Command (if any)

> make -j`sysctl -n hw.physicalcpu`

### Errors (if any)

> Undefined symbols for architecture x86_64:
  "boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)", referenced from:
      boost::thread_specific_ptr<caffe::Caffe>::reset(caffe::Caffe*) in common.cpp.o
      boost::thread_specific_ptr<caffe::Caffe>::~thread_specific_ptr() in common.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [lib/libcaffe.1.0.0.dylib] Error 1
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/a9AqPWp2

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: manual Makefile installation (MacOS);
    - **Operating system** : macOS
    - **Operating system version**: macOS Mojave  10.14.3
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

**Comment by soulslicer** [comment]
Where is that executed command coming from?

**Comment by IcyW** [comment]
> Where is that executed command coming from?
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#python-api

![image](https://user-images.githubusercontent.com/16513834/68589015-d497ad80-04c5-11ea-9da8-5806960fec05.png)

**Comment by zazazingo** [comment]
I have a similar error. What is the resolution?
```
Undefined symbols for architecture x86_64:
  "boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)", referenced from:
      boost::thread_specific_ptr<caffe::Caffe>::reset(caffe::Caffe*) in common.o
      boost::thread_specific_ptr<caffe::Caffe>::~thread_specific_ptr() in common.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by noelmcloughlin** [comment]
Found this while searching.  I got your error using `pyenv install 3.7.3` and fixed as follows.
```
brew uninstall --force binutils
brew uninstall --force pyenv
brew install --HEAD pyenv 
pyenv install 3.7.3
```
