### ISSUE TITLE
A link in OpenPose-Prerequisites in nonvalid!

### ISSUE THREAD

**Issue by haohao900618** [CMU-Perceptual-Computing-Lab/openpose#1425]
Hello, my sever doesn't support camke-gui, so I can only use camke command line for configuration. However the link "CMake Command Line Configuration (Ubuntu Only)" in OpenPose-Prerequisites is nonvalid. It links to the  "OpenPose-Prerequisites" page. Thanks for your checking it. 

I really want to konw how to cmake configuration by command line not cmake-gui. Thanks very much!

**Comment by gineshidalgo99** [comment]
The link should point to `doc/installation.md`, section `CMake Command Line Configuration (Ubuntu Only)`.

Will be fixed in the next commit, thanks!
