### ISSUE TITLE
Installation Video for Windows 10

### ISSUE THREAD

**Issue by jaskarannagi19** [CMU-Perceptual-Computing-Lab/openpose#1426]
Not an issue but a contribution to this project. It took me tons of time before I could install it perfectly on Windows 10. So I made a video of process if anyone is looking for same head straight to here:

https://youtu.be/QC9GTb6Wsb4

**Comment by jaskarannagi19** [comment]
@gineshidalgo99 Can you please include it in installation guides?

**Comment by gineshidalgo99** [comment]
Thanks!!!
Added in:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#windows-portable-demo
