### ISSUE TITLE
Problems on testing python files on Windows system 

### ISSUE THREAD

**Issue by Jichen66** [CMU-Perceptual-Computing-Lab/openpose#1427]
Hi, 

First of all, thanks for the great job of openpose. 

By following the installation guide on Windows, I have built it successfully on Win10 system, and can run it successfully through Visual Studio 2017. But I also want to test it in python. And when I run 01 body_from_image.py (or any other python file in that file) from the path of '\openpose\build\examples\tutorial_api_python', the errors 'No module named pyopenpose' occured. I have also chose the 'build_python' in cmake and have checked the similar issues online, but could not fix it.  Does anyone met similar issues and have any idea on how to solve it? I am looking forward to the reply. Many thanks in advance!

**Comment by andriy-tsvikla** [comment]
Make sure that openpose path before pyopenpose import points to correct build/python folder in openpose.

**Comment by Jichen66** [comment]
thx a lot, I have checked the path you said, there is no any .py file in this path. Is there anything wrong?

**Comment by andriy-tsvikla** [comment]
My bad, that folder is for Linux, for windows check python/openpose/Release
In my case i have this files there, maybe this will help with your investigation.
```
pyopenpose.cp37-win_amd64.pyd
pyopenpose.exp
pyopenpose.lib
```

**Comment by Jichen66** [comment]
thx a lot again! I have checked and I found these files exist in  'path to
openpose\build\python\openpose\Release'. Is this correct?

Andriy Tsvikla <notifications@github.com> 于2019年11月12日周二 下午7:38写道：

**Comment by andriy-tsvikla** [comment]
should be

**Comment by Jichen66** [comment]
Thank you so much! I have checked that path and made a little modification(previously the path is not in build folder), and I print them out:
`C:\Users\AxIoMDev\dev_root\body_pose_estimation\openpose\examples\tutorial_api_python/../../build/python/openpose/Release
C:\Users\AxIoMDev\.conda\envs\realsense-dev-caffe;C:\Users\AxIoMDev\.conda\envs\realsense-dev-caffe\Library\mingw-w64\bin;C:\Users\AxIoMDev\.conda\envs\realsense-dev-caffe\Library\usr\bin;C:\Users\AxIoMDev\.conda\envs\realsense-dev-caffe\Library\bin;C:\Users\AxIoMDev\.conda\envs\realsense-dev-caffe\Scripts;C:\Users\AxIoMDev\.conda\envs\realsense-dev-caffe\bin;C:\ProgramData\Anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Users\AxIoMDev\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Users\AxIoMDev\AppData\Local\Programs\Git\cmd;C:\Users\AxIoMDev\AppData\Local\GitHubDesktop\bin;C:\Users\AxIoMDev\dev_root\body_pose_estimation\openpose\examples\tutorial_api_python/../../build/x64/Release;C:\Users\AxIoMDev\dev_root\body_pose_estimation\openpose\examples\tutorial_api_python/../../build/bin;;C:\Users\AxIoMDev\dev_root\body_pose_estimation\openpose\examples\tutorial_api_python/../../build/x64/Release;C:\Users\AxIoMDev\dev_root\body_pose_estimation\openpose\examples\tutorial_api_python/../../build/bin;
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
No module named 'pyopenpose'`

Could you help me find the problems through it?

**Comment by Jichen66** [comment]
And this is the part I changed:
`        if platform == "win32":
            # Change these variables to point to the correct folder (Release/x64 etc.)
            sys.path.append(dir_path + '/../../build/python/openpose/Release');
            print(dir_path + '/../../build/python/openpose/Release')
            os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + '/../../build/x64/Release;' +  dir_path + '/../../build/bin;'
            print(os.environ['PATH'] + ';' + dir_path + '/../../build/x64/Release;' +  dir_path + '/../../build/bin;')
            import pyopenpose as op`

**Comment by Jichen66** [comment]
And this is the part I changed:

>         if platform == "win32":
            # Change these variables to point to the correct folder (Release/x64 etc.)
            sys.path.append(dir_path + '/../../build/python/openpose/Release');
            print(dir_path + '/../../build/python/openpose/Release')
            os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + '/../../build/x64/Release;' +  dir_path + '/../../build/bin;'
            print(os.environ['PATH'] + ';' + dir_path + '/../../build/x64/Release;' +  dir_path + '/../../build/bin;')
            import pyopenpose as op

**Comment by tiemaliu** [comment]
Hi, I followed the tutorial and ran into the same problem (No module named 'pyopenpose') when I tried the python APIs in Win10.  I checked the path, they are all good. And also I get pyopenpose.cp36-win_amd64.pyd in /python/openpose/Release.  The demo runs perfectly in VS 2017. 
Python 3.5.6
OpenCV 3.3.1

**Comment by nyudeb** [comment]
Hello, I followed the tutorial and same problem ... but got a: 

```
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the righ
DLL load failed while importing pyopenpose: The specified module could not be found.
```

This is my 01_body_from_image.py file:

```
if platform == "win32":
  # Change these variables to point to the correct folder (Release/x64 etc.)
  sys.path.append(dir_path + '/../../python/openpose/Release');
  os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + '/../../x64/Release;' +  dir_path + '/../../bin;'
  import pyopenpose as op
```

Files from command : 

`dir ../../python/openpose/Release/`
=
`pyopenpose.cp38-win_amd64.pyd  pyopenpose.exp  pyopenpose.lib`

**Comment by Jichen66** [comment]
Still have no idea...Hope someone could me help me solve this problem. Many thanks in advance!

**Comment by 24Beast** [comment]
Hey, was anyone able to solve this problem ?
If yes please share the solution cause I am facing the exact same problem as nyudeb

**Comment by analogously** [comment]
I have the same issue. Win10, Python 3 - CUDA 10 - Visual Studio 2019, demo works and the content of my path seems to be correct according to the others, but no module named openpose.

> Hey, was anyone able to solve this problem ?
> If yes please share the solution cause I am facing the exact same problem as nyudeb
> 
> Edit:
> The problem is not with the library but, your opencv or numpy library updated them in a new environment after reading this issue.
> 
> If the libraries are not compatible with pyopenpose, it will give the same error!
> 
> #1027
Can you explain the edit further? I don't understand.

**Comment by aimanraza** [comment]
I followed this Colab notebook for installing openpose on Google Colab:
https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/OpenPose.ipynb

what to do next in order to run hand_from_image.py file?
If i run there code directly after the above notebook i am getting this error:
Error: OpenPose library could not be found. Did you enable BUILD_PYTHON in CMake and have this Python script in the right folder? No module named 'pyopenpose'.

Also I found there is no "Release" folder in 'path to
openpose\build\python\openpose

Can anyone please help. Thanks in advance

**Comment by jaywong966** [comment]
> I have the same issue. Win10, Python 3 - CUDA 10 - Visual Studio 2019, demo works and the content of my path seems to be correct according to the others, but no module named openpose.
> 
> > Hey, was anyone able to solve this problem ?
> > If yes please share the solution cause I am facing the exact same problem as nyudeb
> > Edit:
> > The problem is not with the library but, your opencv or numpy library updated them in a new environment after reading this issue.
> > If the libraries are not compatible with pyopenpose, it will give the same error!
> > #1027
> > Can you explain the edit further? I don't understand.

You need to build the project first(Ctrl + Shift + B)

**Comment by PrototypeNx** [comment]
Hi, I am also facing the exact same problem as nyudeb. I have checked all the path and got everything as nyudeb mentioned and got the same error.. So have anyone solve this problem? Thx in advance!!

**Comment by ABODFTW** [comment]
I've faced this same problem, and I couldn't find a solution, hope this helps someone.
I fixed it by downgrading the python version to 3.7 (I was using python 3.8), and make sure to update the PYTHON_EXECUTABLE in CMake, to point to python 3.7 directory, and make sure to enable "BUILD_PYTHON", and on visual studio, make sure to click "build" at the top then "build solution" because sometimes pressing the green tringle is not enough.

**Comment by Jichen66** [comment]
@ABODFTW 
So did you run Openpose on Win10 using Python successfully?

**Comment by PrototypeNx** [comment]
Thx a lot!  I changed my python version to 3.7 ,and it works!

**Comment by Jichen66** [comment]
> 
> 
> Thx a lot! I changed my python version to 3.7 ,and it works!

Good to hear! Btw, you mean you can run Openpose successfully in Python now?

**Comment by ABODFTW** [comment]
> > Thx a lot! I changed my python version to 3.7 ,and it works!
> 
> Good to hear! Btw, you mean you can run Openpose successfully in Python now?

Sorry just read your question, Yes, I have got OpenPose/Pyopenpose working on my Win10 machine

**Comment by soulslicer** [comment]
> > > Thx a lot! I changed my python version to 3.7 ,and it works!
> > 
> > 
> > Good to hear! Btw, you mean you can run Openpose successfully in Python now?
> 
> Sorry just read your question, Yes, I have got OpenPose/Pyopenpose working on my Win10 machine

To make it work on Python 3.8 on Windows please look at

https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1468

**Comment by D0683406** [comment]
I had same problem, and my solution is after I cmake my openpose project,  Set "example" as StartUp project in Visual Studio , then i can run the examples.

**Comment by WestbrookZero** [comment]
@nyudeb  My environment is win10, python3.6,VS2017, when i build openpose,c++ api can be used, but python have the error ,i change the code:
sys.path.append('D:/Project/MyThesis/openpose/build/python/openpose/Release');
os.environ['PATH'] = os.environ['PATH'] + ';' + 'D:/Project/MyThesis/openpose/build/x64/Release;' + 'D:/Project/MyThesis/openpose/build/bin;'
import pyopenpose as op
there is the error :
[WinError 126] 找不到指定的模块。

Failed to lad Windows library. Trying to load Linux library...

Failed to load library [WinError 126] 找不到指定的模块。

**Comment by joeban0608** [comment]
> Hi,
> 
> First of all, thanks for the great job of openpose.
> 
> By following the installation guide on Windows, I have built it successfully on Win10 system, and can run it successfully through Visual Studio 2017. But I also want to test it in python. And when I run 01 body_from_image.py (or any other python file in that file) from the path of '\openpose\build\examples\tutorial_api_python', the errors 'No module named pyopenpose' occured. I have also chose the 'build_python' in cmake and have checked the similar issues online, but could not fix it. Does anyone met similar issues and have any idea on how to solve it? I am looking forward to the reply. Many thanks in advance!

I try to change the python version to python3.7.0 then work, there is the link with picture which my testing. 
[https://github.com/joeban0608/tt_group2_Ai_posture-estimation_project/blob/main/0420_pyopenpose_no_model_solve.pdf](url)

**Comment by xXswetXx19** [comment]
> > Hi,
> > First of all, thanks for the great job of openpose.
> > By following the installation guide on Windows, I have built it successfully on Win10 system, and can run it successfully through Visual Studio 2017. But I also want to test it in python. And when I run 01 body_from_image.py (or any other python file in that file) from the path of '\openpose\build\examples\tutorial_api_python', the errors 'No module named pyopenpose' occured. I have also chose the 'build_python' in cmake and have checked the similar issues online, but could not fix it. Does anyone met similar issues and have any idea on how to solve it? I am looking forward to the reply. Many thanks in advance!
> 
> [windows] I try to change the python version to python3.7.0 then work, there is the link with picture which my testing. https://github.com/joeban0608/tt_group2_Ai_posture-estimation_project/blob/main/0420_pyopenpose_no_model_solve.pdf


I were trying to use the python api of the precompiled binaries from "https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases" the 1.7.0 version, and i had the problem "no module named pyopenpose" i tried with some versions of python with venv and didnt work, only when i tried with python 3.7.0 it worked and stopped to throwing this error. For someone to this can help, im using windows 11, nvidia mx350 with cudda and cudnn.
