### ISSUE TITLE
hand action output

### ISSUE THREAD

**Issue by dawgjunior** [CMU-Perceptual-Computing-Lab/openpose#1429]
-question/help
-portable demo on windows 10

The software works well on my setup but now i want to do something with it. I am looking to print "waving" on screen when i wave my hand. I am pretty new to coding and i am looking for a place to start. Any help or guidance would be greatly appreciated. I understand the hand key points tracking information found here(https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md), however, i am unsure how to integrate it to make something happen. Should i be using the information found here:(https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/examples/tutorial_add_module) OR here:(https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/11_asynchronous_custom_output.cpp)? I understand that after i write new code i need to recompile and to get the outcome for "waving' plan to use the euclidean distance formula to track distance between hand key points. 

Thank you

**Comment by gineshidalgo99** [comment]
From the OpenPose side, yes, the C++ examples are the place to start where you can add your hand-action detection algorithm. I'd say 11 might be the easiest demo to start, I agree.

From the research side, you'll need to find information on how to actually detect an action from just 2D keypoints.
