### ISSUE TITLE
Ubuntu: Name is blank in the datum.name

### ISSUE THREAD

**Issue by rainforest1** [CMU-Perceptual-Computing-Lab/openpose#143]
### Issue summary
I have modified the 1_user_asynchronous.cpp to display the image name(filename) with 
std::cout << datumsPtr->at(0).name  <<std::endl;
but the name is always blank. I was expecting file name or image name in it. Am i wrong? I am processing the keypoints in the datum object but not able to find the image (filename) corresponding to those keypoints.

Also the rendered image and rendered key points file have the name of index_rendered.png(when running 1_user_asynchronous.bin and 2_user_synchronous.bin) as opposed to imagefilename_rendered.png(when running openpose.bin).

### Executed command (if any)
Note: add `--logging_level 0` to get higher debug information.
void display(const std::shared_ptr<std::vector<UserDatum>>& datumsPtr)
    {
        // User's displaying/saving/other processing here
            // datum.cvOutputData: rendered frame with pose or heatmaps
            // datum.poseKeypoints: Array<float> with the estimated pose
        if (datumsPtr != nullptr && !datumsPtr->empty())
        {
	    const auto numberPeopleDetected = datumsPtr->at(0).poseKeypoints.getSize(0);
            const auto numberBodyParts = datumsPtr->at(0).poseKeypoints.getSize(1);
            std::cout << datumsPtr->at(0).id  <<std::endl;
            std::cout << datumsPtr->at(0).name  <<std::endl;

### OpenPose output (if any)
 datumsPtr->at(0).name  is blank

### Type of issue
You might select multiple topics, delete the rest:
- Question

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu 14.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):8.0
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose or custom version.Default
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.2.X
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
The `name` field is filled somewhere else, you can check the wrapper Workers to see which one does it (I think the `include/producer/wDatumProducer`).

**Comment by rainforest1** [comment]
ok Thank you!
