### ISSUE TITLE
Why are some points of the body (invisible) equal to zero?

### ISSUE THREAD

**Issue by darkAlert** [CMU-Perceptual-Computing-Lab/openpose#1438]
For example, if the person in the photo is standing with his back, then the points on the face are always zero (I mean the points 0/15/16 in BODY_25 and 0/14/15 in COCO model).

Maybe there is a threshold not to nullify these points?

**Comment by ZhiweiREN97** [comment]
@darkAlert Hi, sorry to bother you. Would you mind telling me if you fixed this issue?

**Comment by darkAlert** [comment]
@ZhiweiREN97 Unfortunately, OpenPose can't predict invisible keypoints. I've tried Detectron2 (with mask R-CNN), but it also can't predict such keypoints. And all estimators that based on bottom-up design can't do it so.
But, fortunately, top-down estimators can do this. For example, ShelfNet or HRNet.

**Comment by ZhiweiREN97** [comment]
> @ZhiweiREN97 Unfortunately, OpenPose can't predict invisible keypoints. I've tried Detectron2 (with mask R-CNN), but it also can't predict such keypoints. And all estimators that based on bottom-up design can't do it so.
> But, fortunately, top-down estimators can do this. For example, ShelfNet or HRNet.

Thanks. I just want to replace the DeeperCut with a better keypoints detector. Also, I am a little confused since HRNet is a bottom-up approch not a top-down one.

**Comment by darkAlert** [comment]
I think you need to try HRNet because it is SOTA at the moment

**Comment by darkAlert** [comment]
> HRNet is a bottom-up approch not a top-down one.
Yes, you are right! I made a mistake, sorry
