### ISSUE TITLE
Framerate seems to be locked to 5 on Windows10

### ISSUE THREAD

**Issue by L1TTl3** [CMU-Perceptual-Computing-Lab/openpose#144]
### Issue summary
Output framerate in Demo application without hands and face matches the benchmark sheet for my GPU (1070 8GB) but goes down to 5fps quickly and seems to lock the FPS there. This is not affected by changing the net_resolution to lower or higher value (only the FPS at start before it goes down to 5). GPU usage also doesn't go above 50%
Is there anything that could lock the output framerate to 5FPS and the hardware usage or is it rather a limitation of my system?

### Executed command (if any)
Demo with webcam input, 1280x720 and lower resolutions tried, no hands and face tracking, mirror output on, tried render mode 1 and 2 (same output). Tried the solutions for performance problems in the docs and issues to be found here.

### Type of issue
You might select multiple topics, delete the rest:
- Help wanted
- Question

### Your system configuration
**Operating system**:
Windows 10
**CUDA version**:
8 with Patch 2 installed
**cuDNN version**:
5.1
**GPU model**:
1070 8GB
**Caffe version**:
default
**OpenCV version**:
3.2.0

**Comment by gineshidalgo99** [comment]
I found that problem before with OpenCV and the webcam. Somehow OpenCV needs good drivers for some cameras. Please check the (just commited) new [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#faq) section for solutions. Let me know whether they work or not. Thanks
