### ISSUE TITLE
ImportError: libopenpose.so.1.5.1: cannot open shared object file: No such file or directory (UBUNTU 16.04)

### ISSUE THREAD

**Issue by seni04** [CMU-Perceptual-Computing-Lab/openpose#1442]
### Issue Summary
Finish all installation, i can run demo using terminal
i try using tutorial_api_python 
I want to use pyopenpose on python, but i cannot import 

ImportError: libopenpose.so.1.5.1: cannot open shared object file: No such file or directory

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Import Error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin]
ImportError: libopenpose.so.1.5.1: cannot open shared object file: No such file or directory

2. **OpenPose version**: 
Latest github version

3. **General configuration**:
UBUNTU 16.04

cmake ..
make -j8
sudo make install

5. **3rd-party software**:
OpenCV 3.2.0 using sudo apt install

6. If **GPU mode** issue:

CUDA Version 10
Cudnn 7.5.1

8. If **Python** API:
Python 3.5

**Comment by MonsterMoriarty** [comment]
I also encountered this problem, did you solve it and how did you solve it?

**Comment by ujjawalcse** [comment]
I was successfully running openpose 3 days earlier. Extracted keypoints for many images as json format those those days.
But Today, I'm getting the following error:-

> ./build/examples/openpose/openpose.bin: error while loading shared libraries: libopenpose.so.1.5.1: cannot open shared object file: No such file or directory


Can anyone guess what may get wrong?

**Comment by kapoorparul** [comment]
I am also getting same error. Did any of you solve it?

**Comment by ujjawalcse** [comment]
Have you moved your openpose folder somewhere? I got the same problem after
moving the folder from Ubuntu server to windows and again moved the folder
from windows back to Ubuntu.
 So, I just freshly installed the openpose and error didn't occur again.

**Comment by kapoorparul** [comment]
Yes I have moved openpose folder to a new location!! Is there any other way other than again installing it?

**Comment by ujjawalcse** [comment]
There should be some ways. But I don't know.
