### ISSUE TITLE
Is openpose really able to track only the hand movement when only the hand is displayed in the video or web camera?

### ISSUE THREAD

**Issue by nikkolasedi** [CMU-Perceptual-Computing-Lab/openpose#1443]
Hello everyone,

I just want to know. Is openpose really able to track only the hand movement when only the hand is displayed in the video or web camera? Or Openpose actually needs the whole body as video input in order to track down the hand from there. I have the feeling that their tracking mechanism always starts from the face or upper body and then continues to the upper arm and hand. I have this problem after trying hands only videos several times and openpose is not able to recognize the hands.  But if I include my body in the video, then openpose can also recognize my hands (even fingers). I will be very happy about your answer, based on your experiences with openpose, because at the moment I can only run openpose with Google Colab and can only feed it with an input video and get the extracted video as a result.

If not, then:
Is there another openpose-like project that only recognizes the hand and fingers?

Many thanks in advance.

**Comment by Priyanka-M96** [comment]
did u get a solution for this?

**Comment by nikkolasedi** [comment]
Not yet. Did you?

> did u get a solution for this?

**Comment by aimanraza** [comment]
> Hello everyone,
> 
> I just want to know. Is openpose really able to track only the hand movement when only the hand is displayed in the video or web camera? Or Openpose actually needs the whole body as video input in order to track down the hand from there. I have the feeling that their tracking mechanism always starts from the face or upper body and then continues to the upper arm and hand. I have this problem after trying hands only videos several times and openpose is not able to recognize the hands. But if I include my body in the video, then openpose can also recognize my hands (even fingers). I will be very happy about your answer, based on your experiences with openpose, because at the moment I can only run openpose with Google Colab and can only feed it with an input video and get the extracted video as a result.
> 
> If not, then:
> Is there another openpose-like project that only recognizes the hand and fingers?
> 
> Many thanks in advance.

How did you run it in Google Colab. I am struck there. I followed this Colab notebook for installing openpose: 
https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/OpenPose.ipynb

what to do next in order to run hand_from_image.py file?
If i run there code directly after the above notebook i am getting this error:
Error: OpenPose library could not be found. Did you enable BUILD_PYTHON in CMake and have this Python script in the right folder? No module named 'pyopenpose'. issue #1427 

Also I found there is no "Release" folder in  'path to
openpose\build\python\openpose

Can anyone please help. Thanks in advance

**Comment by Jichen66** [comment]
By my experience, openpose cannot recognize the hand solely. If you want to only detect the hand, you could try AlphaPose.

**Comment by gineshidalgo99** [comment]
Duplicated of many other GitHub issues:
Openpose needs the whole body as video input in order to track down the hand from there.

If you know where the hand is (a bounding box of it), then check doc/standalone hand or example_tutorial_cpp/standalone_hand (or python analog)
