### ISSUE TITLE
Using pre-trained models for commercial purpose

### ISSUE THREAD

**Issue by BadMachine** [CMU-Perceptual-Computing-Lab/openpose#1444]
### Type of Issue
- Question

### Issue Summary
My question is:
Can i use pre-trained models for my own commercial project, considering that i dont gonna use any of OpenPose project code and openpose libs, just my own code with caffemodels?
Also:
I wrote to the email mcevoy@cmu.edu and gines@cmu.edu, but did not receive any response.
I think this is very important issue not only for me but for the whole community.
Thanks!

**Comment by gineshidalgo99** [comment]
Hi Roman,

All the info and contact info about the commercial license is in here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose#license  

The pre-trained models are part of OpenPose, so they follow the exact same licensing.

Thanks,

**Comment by kartikeyporwal** [comment]
Hi, Many of the implementations of Openpose have transferred Caffe Models to their respective libraries like Tensorflow or PyTorch's model. Can converted models be used commercially or these too are covered under Openpose licensing?

Thanks

**Comment by gineshidalgo99** [comment]
The pre-trained models are part (and the core) of OpenPose, even if they have just been re-converted to another backend, so they follow the exact same licensing.
