### ISSUE TITLE
python 1. (self: openpose.pyopenpose.Datum, arg0: op::Matrix) -> None

### ISSUE THREAD

**Issue by chuhai-spring** [CMU-Perceptual-Computing-Lab/openpose#1445]
datum = op.Datum()
    imageToProcess = cv2.imread(args[0].image_path)
    datum.cvInputData = imageToProcess
    opWrapper.emplaceAndPop([datum])

  datum.cvInputData = imageToProcess
The following argument types are supported:
    1. (self: openpose.pyopenpose.Datum, arg0: op::Matrix) -> None

**Comment by alexeybozhchenko** [comment]
I meet the same issue
