### ISSUE TITLE
person_id is always -1

### ISSUE THREAD

**Issue by TalBarami** [CMU-Perceptual-Computing-Lab/openpose#1448]
Hey,
I'm using the demo version from build 1.5.1 on windows.
I noticed that the 'person_id' field is always -1 for each of the people detected by openpose and was wondering if this feature is not supported yet, or is it some configuration I miss.
I'm executing the following command:
bin\OpenPoseDemo.exe --hand --write_json <path to json> --video <path to video> --display 0 --render_pose 0
A folder is created, with approximately 1 json file per frame. I can then draw the skeleton and everything works really great, but could really use the 'person_id' field if supported.

Thanks.

**Comment by bridger007** [comment]
Is this a known issue? Any plan or progress to fix it?

**Comment by klory** [comment]
same question here, is there a doc explaining person_id and how to use it?

**Comment by TalBarami** [comment]
I wrote a naive solution in the meantime.
Works horribly when skeletons collides but unless it happens often this is pretty stable:
`import numpy as np
import json
from json.decoder import JSONDecodeError
from os import listdir
from os.path import join, isfile

def read_json(file):
    try:
        with open(file, 'r') as j:
            return json.loads(j.read())
    except (OSError, UnicodeDecodeError, JSONDecodeError) as e:
        print(f'Error while reading json file: {file}')
        print(e)
        return


def write_json(j, dst):
    with open(dst, 'w') as f:
        json.dump(j, f)


def distance(p1, p2):
    x1, y1 = center_of_mass(p1)
    x2, y2 = center_of_mass(p2)

    if not any([x for x in [x1, x2, y1, y2] if x is np.NaN]):
        return np.sqrt(np.power(x1 - x2, 2) + np.power(y1 - y2, 2))
    else:
        return np.inf


def center_of_mass(p):
    k = np.array([float(c) for c in p['pose_keypoints_2d']])
    coords = [c for c in zip(k[::3], k[1::3], k[2::3])]
    threshold = 0.1

    x = np.array([c[0] for c in coords if c[2] > threshold]).mean()
    y = np.array([c[1] for c in coords if c[2] > threshold]).mean()

    return x, y


def find_closest(p, prevs):
    ids = set([pi['person_id'] for pi in prevs])
    id_weights = dict([(i, []) for i in ids])
    for pi in prevs:
        d = distance(p, pi)
        id_weights[pi['person_id']].append(d)

    for i in ids:
        id_weights[i] = np.mean(id_weights[i])

    if len(id_weights) > 0:
        selected_id = min(id_weights, key=id_weights.get)
        selected_weight = id_weights[selected_id]
    else:
        selected_id = 0
        selected_weight = 0
    return selected_id, selected_weight


def match_frames(ps, prevs):
    def gen_id(ps):
        ids = [p['person_id'] for p in ps]
        i = 0
        while i in ids:
            i += 1
        return i

    found = {}
    for p in ps:
        new_id, d_new = find_closest(p, prevs)
        if new_id in found:
            p_old, d_old = found[new_id]
            generated_id = gen_id(prevs + [v[0] for v in found.values()])
            if d_old < d_new:
                new_id = generated_id
            else:
                p_old['person_id'] = generated_id
                found[generated_id] = (p_old, d_old)
                p['person_id'] = new_id
        p['person_id'] = new_id
        found[new_id] = (p, d_new)


def set_person_id(json_src, n=5, print_interval=10000):
    file_names = [f for f in listdir(json_src) if isfile(join(json_src, f)) and f.endswith('json')]

    def src_path(i):
        return join(json_src, file_names[i])

    def dst_path(i):
        return join(json_src, file_names[i])

    jsons = [read_json(src_path(0))]
    for idx, p in enumerate(jsons[0]['people']):
        p['person_id'] = idx
    write_json(jsons[0], dst_path(0))

    for i in range(1, len(file_names)):
        jsons.append(read_json(src_path(i)))
        people = jsons[i]['people']

        prevs = []
        for j in range(min(n, i)):
            for p in jsons[j]['people']:
                prevs.append(p)

        match_frames(people, prevs)

        write_json(jsons[i], dst_path(i))

        if i % print_interval == 0:
            print(f'frame: {i}')
`

**Comment by gineshidalgo99** [comment]
See #1297 and https://github.com/soulslicer/openpose/tree/staf

**Comment by priyas1729** [comment]
Hey Gines,
Kudos to you guys for this amazing work. I have been trying pose estimation of a single person in a multi people video frames. I tried tracking module of openpose. The person tracking id is always -1. Does STAF module solve the issue? Is tracking ID consistent? 

Thanks,

**Comment by gineshidalgo99** [comment]
Yes, STAF would solve that. Thanks!

**Comment by matkiller333** [comment]
Hi Gines.
This is a really awesome project you allow us to use so thanks! I was just wondering if the only available option with the STAF module is --tracking, where there is only one person on screen. If not, where can I find the documentation to get person_id for everyone on screen, I can't seem to find it in https://github.com/soulslicer/openpose/tree/staf

Cheers!

**Comment by gineshidalgo99** [comment]
@soulslicer  should know the answer to that one, he is the main author of it and the one that wrote all the code!

**Comment by MarloSM** [comment]
Hi @gineshidalgo99, thanks for the great project. Do you know if the STAF implementation is compatible with your Unity plugin?

Cheers.
