### ISSUE TITLE
openpose compile error

### ISSUE THREAD

**Issue by himlen1990** [CMU-Perceptual-Computing-Lab/openpose#145]
I remove the old version by rm -rf openpose then reinstalled following the instruction:
git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
cd openpose
bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh
------------------------- Caffe Compiled -------------------------

------------------------- Caffe Installed -------------------------

------------------------- Installing OpenPose -------------------------
NOTE: This script assumes that CUDA and cuDNN are already installed on your machine. Otherwise, it might fail.
------------------------- Checking Ubuntu Version -------------------------
Ubuntu Release:	16.04
------------------------- Ubuntu Version Checked -------------------------

------------------------- Checking Number of Processors -------------------------
8 cores
------------------------- Number of Processors Checked -------------------------

------------------------- Compiling OpenPose -------------------------
CXX src/openpose/filestream/keypointSaver.cpp
CXX src/openpose/filestream/jsonOfstream.cpp
CXX src/openpose/filestream/defineTemplates.cpp
CXX src/openpose/filestream/imageSaver.cpp
CXX src/openpose/filestream/keypointJsonSaver.cpp
CXX src/openpose/filestream/heatMapSaver.cpp
CXX src/openpose/filestream/fileStream.cpp
CXX src/openpose/filestream/fileSaver.cpp
In file included from src/openpose/filestream/defineTemplates.cpp:1:0:
./include/openpose/filestream/headers.hpp:5:49: fatal error: openpose/fileStream/cocoJsonSaver.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/filestream/defineTemplates.o' failed
make: *** [.build_release/src/openpose/filestream/defineTemplates.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/openpose/filestream/imageSaver.cpp:1:0:
./include/openpose/filestream/fileStream.hpp:7:47: fatal error: openpose/fileStream/enumClasses.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/filestream/imageSaver.o' failed
make: *** [.build_release/src/openpose/filestream/imageSaver.o] Error 1
In file included from src/openpose/filestream/fileStream.cpp:7:0:
./include/openpose/filestream/fileStream.hpp:7:47: fatal error: openpose/fileStream/enumClasses.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/filestream/fileStream.o' failed
make: *** [.build_release/src/openpose/filestream/fileStream.o] Error 1
In file included from src/openpose/filestream/heatMapSaver.cpp:2:0:
./include/openpose/filestream/fileStream.hpp:7:47: fatal error: openpose/fileStream/enumClasses.hpp: No such file or directory
compilation terminated.
In file included from src/openpose/filestream/keypointJsonSaver.cpp:1:0:
./include/openpose/filestream/fileStream.hpp:7:47: fatal error: openpose/fileStream/enumClasses.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/filestream/heatMapSaver.o' failed
make: *** [.build_release/src/openpose/filestream/heatMapSaver.o] Error 1
Makefile:478: recipe for target '.build_release/src/openpose/filestream/keypointJsonSaver.o' failed
make: *** [.build_release/src/openpose/filestream/keypointJsonSaver.o] Error 1
In file included from src/openpose/filestream/keypointSaver.cpp:1:0:
./include/openpose/filestream/fileStream.hpp:7:47: fatal error: openpose/fileStream/enumClasses.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/filestream/keypointSaver.o' failed
make: *** [.build_release/src/openpose/filestream/keypointSaver.o] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

**Comment by gineshidalgo99** [comment]
Sorry! I commited from Windows, no realizing of a mistake that only affected Ubuntu. Fixed now. Let me know if it still fails. Thanks
