### ISSUE TITLE
Inference time increases the more GPUs I add (above 3)

### ISSUE THREAD

**Issue by AmitMY** [CMU-Perceptual-Computing-Lab/openpose#1454]
### Issue Summary
When executing inference, on many GPUs it is slower than a single GPU...

Here is a benchmark, for a video with 109 frames:

- Time on 8 GPUs: 65.8
- Time on 4 GPUs: 36.44
- Time on 3 GPUs: 33.46
- Time on 2 GPUs: 36.02
- Time on 1 GPU: 54.53

### Executed Command (if any)

```sh
./build/examples/openpose/openpose.bin --video /video.mp4  --display 0 --write_video /out/out.avi --write_json /out/json/ --hand --face --num_gpu X
```

### OpenPose Output (if any)

> Starting OpenPose demo...                                                                                        
> Configuring OpenPose...                                                                                          
> Starting thread(s)...                                                                                            
> OpenPose demo successfully finished. Total time: 33.461531 seconds.

--

### Type of Issue
- Help wanted
- Question
- Other (type your own type) - inference time

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)? Release **1.5.1**

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

```Dockerfile
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install sudo git wget build-essential -y

# download and install the latest version of cmake
RUN wget -c "https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4.tar.gz"
RUN tar xf cmake-3.14.4.tar.gz
RUN cd cmake-3.14.4 && ./configure
RUN cd cmake-3.14.4 && make
RUN cd cmake-3.14.4 && make install

# download OpenPose from Git Repository
RUN git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git

# Install OpenCV
ENV TZ=Europe/Minsk
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install libopencv-dev -y

# install dependencies
RUN chmod -R +x ./openpose/scripts/ubuntu/
RUN ./openpose/scripts/ubuntu/install_deps.sh
#RUN ./openpose/scripts/ubuntu/install_cuda.sh
#RUN ./openpose/scripts/ubuntu/install_cudnn.sh


# this is just a fix to address few compilation issues
RUN sed -i 's/execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/execute_process(COMMAND git checkout f019d0dfe86f49d1140961f8c7dec22130c83154 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/g' openpose/CMakeLists.txt
RUN cd openpose && git pull origin master

# compiling OpenPose with cmake
RUN cd openpose && mkdir build && cd build && cmake -DBUILD_PYTHON=ON ..
RUN cd openpose/build && make -j `nproc`
RUN cd openpose/models && ./getModels.sh

RUN pip3 install opencv-python

RUN mkdir workspace
WORKDIR workspace
```

**Comment by AmitMY** [comment]
Dear bot, consider this as a further activity.

**Comment by gineshidalgo99** [comment]
It takes some time to load the memory into the GPUs. With "only" 109 frames, it takes longer to load the OpenPose models into the GPUs than to actually run the code. Try benchmarking on 1000 (or 10k) images and then 8GPUs should be faster.

IF 8 GPUs is still slower on 1000 frames, please, let me know, I don't have 8 GPUs to test, but that should not happen :)

**Comment by AmitMY** [comment]
I'll try to find the time to test 1000 frames.
Anyway, shouldn't the GPU memory loading be parallel as they are independent compute units? or is that not possible?

**Comment by gineshidalgo99** [comment]
That depends on the hardware. Cheap/old hardware might support 4 GPUs, but using them all at the same time does slow down all of them. More fancy motherboards might minimize this a lot.
