### ISSUE TITLE
How to use body_25b?

### ISSUE THREAD

**Issue by huangshaoguang** [CMU-Perceptual-Computing-Lab/openpose#1457]
Hello! Thank you for sharing! I downloaded your body_25b model， and I change the code where the model is loaded. But result is nothing but the original image. Your anather project says that the body_25b is better than body_25. So how to use body_25b?
Thank you for advance very much!

**Comment by Raven888888** [comment]
@huangshaoguang 

Please refer to [https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/tree/master/experimental_models](url). The instructions are straightforward.

Thanks.

**Comment by Christoph9402** [comment]
Hello, I also want to use the model Body_25b. I downloaded both files and have the correct folder structure. However, I want to use the python API. Do you know how to activate the model there?
The documentation says: "Run the official OpenPose with your usual flags, while adding the --model_pose BODY_25B. Note that this model has been trained for the original and default --net_resolution -1x368, so this flag is not required."
 I am not sure what to do when using Python. How do I have to modify my script?

**Comment by patodichayan** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/2007
