### ISSUE TITLE
image size and net-resolution

### ISSUE THREAD

**Issue by BobDL** [CMU-Perceptual-Computing-Lab/openpose#1458]
Hi,
  If I fix the net-resolution, and cal the pose by resize to different size of one image. I would think, the result should be the same. 
  For example, image =1920X1080, net-resolution= 640x368. 
                       Resize the image to 1280X720 and 640X360.
 And cal pose of this 3 different size.

The output is different. And the original(biggest ) output is worst. Is that make sense? 
Should I get the same result as it's inference and decode at the net-resolution?

Could you help check it?

Thanks

**Comment by quan-nguyen-7121996** [comment]
I have a same problem like you

**Comment by zgzxy001** [comment]
Same problem here.
