### ISSUE TITLE
I succeed in running configure and generate but returned error in making -j'nproc'

### ISSUE THREAD

**Issue by Edhonack** [CMU-Perceptual-Computing-Lab/openpose#1460]
### Issue Summary

I have finished Openpose Configuration and start to do Openpose Building. After I run the command below

cd build
make all

Unexpected error was returned like this

edhonack@user:~/openpose$ cd build/
edhonack@user:~/openpose/build$ makeall
makeall: command not found
edhonack@user:~/openpose/build$ make all
[ 12%] Performing configure step for 'openpose_lib'
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_thread

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:49 (include)

-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find HDF5 (missing: HDF5_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindHDF5.cmake:398 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:46 (find_package)
  CMakeLists.txt:49 (include)

-- Configuring incomplete, errors occurred!
See also "/home/edhonack/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/edhonack/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:105: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Detail

Also this is my ccmake .. interface. The screenshot may indicate some issues.
![question2](https://user-images.githubusercontent.com/55429219/70894750-96dbf680-2028-11ea-8931-e6cf80ce47de.png)

My System Configuration
Ubuntu 16.04/cmake version 3.5.1/opencv version 4.1.2
My Nvidia version is GTX 1080Ti 

There are two similar problems like #1320 and #1109. But these solutions don't fit mine.   
When I do sudo apt-get install libboost-all-dev, it told me that libboost-all-dev is already the newest version (1.58.0.1ubuntu1).
While I do sudo apt-get install hdf5, it tole me that Unable to locate package hdf5.

Could someone help me? Thank you in advance !

**Comment by jameslele** [comment]
I also met same problems and solved it by changing my current cmake-gui.
These instructions maybe can help you:
Ubuntu 18: Download and compile CMake-gui from source. The default CMake-gui version (3.10) installed via sudo apt-get install cmake-qt-gui provokes some compiling errors. Required CMake version >= 3.12. 

Uninstall your current Cmake-gui version by $ sudo apt purge cmake-qt-gui. 

$ sudo apt-get install qtbase5-dev. 

Download the Latest Release of CMake Unix/Linux Source from the CMake download website 
 https://cmake.org/download/, called cmake-X.X.X.tar.gz. 

Unzip it and go inside that folder from the terminal. 

$ sudo snap install cmake --classic 

$ sudo apt-get install libssl-dev 

$ cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib 

$ ./configure --qt-gui. Make sure no error occurred. 

$ ./bootstrap && make -j`nproc` && sudo make install -j`nproc` . Make sure no error occurred. 

Assuming your CMake downloaded folder is in {CMAKE_FOLDER_PATH}, everytime these instructions mentions cmake-gui, you will have to replace that line by
 $ {CMAKE_FOLDER_PATH}/bin/cmake-gui. 

Then try to use this cmake-gui to configure, generate again.
Hope can help you!

**Comment by Edhonack** [comment]
Hi jameslele!@jameslele  Thank you for answering very much!
While when I run the command
$ sudo snap install cmake --classic
An error occurred... Do you know how to solve it?
error: cannot install "cmake": Post https://api.snapcraft.io/v2/snaps/refresh:
       proxyconnect tcp: tls: oversized record received with length 20527

**Comment by jameslele** [comment]
It works for me. I never met this error. The link "https://api.snapcraft.io/v2/snaps/refresh" can not be opened for me. But "proxyconnect tcp:"  is worthy of attention. I guess the problem is with the network.

**Comment by ggare-cmu** [comment]
Was facing the same issue... Logs indicated that vecLib was missing, searching the web found this solution (at https://github.com/BVLC/caffe/issues/4637 ):

Try adding this to your installed CMake's FindvecLib.cmake file in the `find_path` node at `PATHS`

`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.`

Final FindvecLib.cmake file snippet:

`find_path(vecLib_INCLUDE_DIR vecLib.h
          DOC "vecLib include directory"
          PATHS /System/Library/Frameworks/Accelerate.framework/Versions/Current/${__veclib_include_suffix}
                /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/
                /System/Library/${__veclib_include_suffix}
                ${CMAKE_XCODE_DEVELOPER_DIR}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/
          NO_DEFAULT_PATH)`
