### ISSUE TITLE
some questions about detecting hand alone

### ISSUE THREAD

**Issue by wulongyuan** [CMU-Perceptual-Computing-Lab/openpose#1467]
when i run 07_hand_from_image.py ，some errors appear as follow

GUI is not enabled and you are not saving the output frames. You should then disable rendering for a faster code. I.e., add `--render_pose 0`. You could also set mThreadManagerMode = mThreadManagerMode::Asynchronous(Out) and/or add your own output worker class before calling this function.

thanks for your help

**Comment by wulongyuan** [comment]
i set --hand_detector = 3, --body_detector=0,but error appears:
Error:
Body keypoint detection is disabled but hand Detector is set to Body. Either re-enable OpenPose body or select a different hand Detector (`--hand_detector`).

and i change --hand_detector = 2, --body_detector=0
Error:
invalid vector<T> subscript

it seems hands cant be detected alone

**Comment by wulongyuan** [comment]
i set --hand_detector = 3, --body_detector=0,but error appears:
Error:
Body keypoint detection is disabled but hand Detector is set to Body. Either re-enable OpenPose body or select a different hand Detector (`--hand_detector`).

and i change --hand_detector = 2, --body_detector=0
Error:
invalid vector<T> subscript

it seems hands cant be detected alone

**Comment by yojayc** [comment]
I met the same problem when I trying to execute 
./build/examples/openpose/openpose.bin \
    --image_dir /usr/data/hico/hico_det/hico_20160224_det/images/train2015/ \
    --face \
    --hand \
    --write_json /usr/data/hico/hico_det_processed/human_pose/train2015/ \
    --display 0
in exsidius's docker version, and I have no idea how to fix it
Please give me some advice, thanks in advance

**Comment by yojayc** [comment]
solved by changing command to
./build/examples/openpose/openpose.bin --face --hand --num_gpu 1 --num_gpu_start 7 --display 0 --render_pose 0\
    --image_dir /usr/data/hico/hico_det/hico_20160224_det/images/train2015/ \
    --write_json /usr/data/hico/hico_det_processed/human_pose/train2015/ \
it seems that gpu should be specified and the sequence of different command has some impact
