### ISSUE TITLE
config pythonAPI in win10 error

### ISSUE THREAD

**Issue by chde222** [CMU-Perceptual-Computing-Lab/openpose#1468]
### Errors (if any)
![图片](https://user-images.githubusercontent.com/45227620/71260385-b7cc8080-2375-11ea-9d72-e80241911282.png)

### Type of Issue
- Question

### Your System Configuration
1. 
win10  desktop computer and had run in C++ api successfully.
but when run in Pythonapi.emerge this error：
![图片](https://user-images.githubusercontent.com/45227620/71260589-29a4ca00-2376-11ea-828a-00d011d89a02.png)
please help me

**Comment by Xploit3r** [comment]
After the configure step in CMake GUI was completed, did you confirm that the BUILD_PYTHON flag was enabled before generating?

Maybe you could share the screenshot of the CMake GUI before you generated the build?

**Comment by patrickgre** [comment]
I have the same issue with python 3.8. On a other computer with python 3.6 it's running ...

**Comment by patrickgre** [comment]
Resolve on python 3.8 : Use os.add_dll_directory at place of os.environ['PATH']

**Comment by soulslicer** [comment]
Thanks @patrickgre

**Comment by wjtscn** [comment]
@patrickgre Thanks very...

**Comment by rigottimarcello** [comment]
> Resolve on python 3.8 : Use os.add_dll_directory at place of os.environ['PATH']

where I have to change this? I tried to change in 01_body_from_image.py but still have the same error as before

**Comment by connor-john** [comment]
@patrickgre 

Is below the correct change for python 3.8?
```
if platform == "win32":
            # Change these variables to point to the correct folder (Release/x64 etc.)
            sys.path.append(dir_path + '/../../python/openpose/Release')
            os.add_dll_directory(dir_path + '/../../x64/Release')
            os.add_dll_directory(dir_path + '/../../bin')
            import pyopenpose as op
```

I still get the "DLL load failed while importing pyopenpose: The specified module could not be found." after the change.
I have checked other potential issues.

**Comment by vincenzomarotta** [comment]
> Resolve on python 3.8 : Use os.add_dll_directory at place of os.environ['PATH']

This is the solution for anyone looking, just did that and it has finally found openpose
