### ISSUE TITLE
Tried to detect hand alone, failed.

### ISSUE THREAD

**Issue by buaazsj** [CMU-Perceptual-Computing-Lab/openpose#1471]
I used the method of generating the hand detection frame in the OpenPose source code to generate some hand rectangles, and then used the same image to detect the key points of the hand alone, but failed. Why is the original good?

<img width="189" alt="屏幕快照 2019-12-24 14 26 34" src="https://user-images.githubusercontent.com/22587518/71398021-2c473e00-265a-11ea-8dc3-dd0d90f6f997.png">
<img width="183" alt="屏幕快照 2019-12-24 14 26 21" src="https://user-images.githubusercontent.com/22587518/71398025-2ea99800-265a-11ea-8eb0-4b2a8ed4f12f.png">

**Comment by LukeSchoen** [comment]
Hey open pose -hand requires enough of the body to first decide that a person is even there, a clear shot of a hand alone will not produce debug display output.
