### ISSUE TITLE
openpose_lib error 1

### ISSUE THREAD

**Issue by apatne** [CMU-Perceptual-Computing-Lab/openpose#1472]
### Issue Summary

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
CMakeFiles/openpose_lib.dir/build.make:125: recipe for target 'openpose_lib' failed
make[2]: *** [openpose_lib] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Executed Command (if any)
Facing this error after make -j`nproc` 
in cmake gui ,configuration done and genration done .
install and reinstalled cuda toolkit twice , also tried install uninstall openpose repositiory. 

### Type of Issue
- Compilation/installation error

2. **OpenPose version**: Latest GitHub code.

3. **General configuration**:
    - **Installation mode**: CMake, 
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 18.04.3 LTS
    - **Operating system version**:18.04.3
    - **Release or Debug mode**:release
    - Compiler:7.4.0
4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, 
    - **CMake version** (`cmake --version` in Ubuntu): 3.16
    - **OpenCV version**:4.1.1

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10.2
    - **cuDNN version**: 7.5
    - **GPU model** (`nvidia-smi` in Ubuntu):GTX Geforce 1050

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 3.7
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

Stuck with this issue from last 3 days, here attached build.log file for complete build details

[build.log](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/3998680/build.log)

**Comment by soulslicer** [comment]
What version of Eigen are you using?

https://stackoverflow.com/questions/53991812/cmake-find-package-not-working-for-eigen

**Comment by apatne** [comment]
Hello,Thanks for reply.. i fixed that error with reinstalling opencv .. but now some of the opencv library are not recognized
[build.log](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/4070304/build.log)

**Comment by gineshidalgo99** [comment]
Try following the installation.md instructions exactly as they appear, maybe some step was skipped. Insert pastebin with output for further help (I can't visualize build.log from my phone).
