### ISSUE TITLE
Does openpose support 3D on normal videos (without depth sensing)?

### ISSUE THREAD

**Issue by alexdriedger** [CMU-Perceptual-Computing-Lab/openpose#1475]
### Issue Summary

Is it possible to get the 3D keypoints without using multiple cameras / depth sensing cameras?

Example: I have an mp4 video from my phone camera. 

### Type of Issue
- Help wanted
- Question

### Your System Configuration
2. **OpenPose version**:  1.5.1

3. **General configuration**:
    - Windows 10

**Comment by klinefe4** [comment]
Any update on this? It doesn't seem possible to me which is unfortunate.

**Comment by gineshidalgo99** [comment]
No, only multi-camera videos.
