### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:

### ISSUE THREAD

**Issue by ro6842** [CMU-Perceptual-Computing-Lab/openpose#1479]
When I run Openpose, everything is ok, but if I run it 2-3 hours, it will interrupt and shows this error:

Auto-detecting all available GPUs... Detected 4 GPU(s), using 4 of them starting at GPU 0.
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5F.c line 855 in H5Fis_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #001: ../../src/H5FD.c line 958 in H5FD_open(): not a file access property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5F.c line 1585 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../src/H5F.c line 1376 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../src/H5Fsuper.c line 336 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
F0101 08:59:12.272711 132171 net.cpp:794] Check failed: file_hid >= 0 (-1 vs. 0) Couldn't open models/pose/coco/pose_iter_440000.caffemodel
*** Check failure stack trace: ***

Can anyone help me how to solve this?

**Comment by gineshidalgo99** [comment]
There are other posts about this issue, but this usually happens when models/pose/coco/pose_iter_440000.caffemodel is corrupted. Could you manually remove it and re-install it? (i.e., re-running CMake or running getModels.sh as the doc/installation.md says).
