### ISSUE TITLE
libcaffe.so.1.0.0: cannot open

### ISSUE THREAD

**Issue by liu6381810** [CMU-Perceptual-Computing-Lab/openpose#148]
Thanks for you nice work.
But now I have some questions.
I have build caffe and openpose successfully on ubuntu16.04 with cuda8
But when I step into Quick Start and run ./openpose.bin --help I get the error:
`error while loading shared libraries: libcaffe.so.1.0.0: cannot open shared object file: No such file or directory`
So do you know what's wrong with this.I would appreciate it if you can help me.

**Comment by thhung** [comment]
export LD_LIBRARY_PATH=/path/to/folder/contains/libcaffe/:$LD_LIBRARY_PATH
./openpose.bin --help

You can try it and see.

**Comment by gineshidalgo99** [comment]
That should not be necessary since he is using the default Caffe from OpenPose.

Did you move the folder? How did you install Caffe & OpenPose?

**Comment by liu6381810** [comment]
@gineshidalgo99 @thhung  Thanks for your reply. I found that I need to run the demo in the openpose directory but not step into openpose/build/examples/openpose/. Now I have successfully run the demo and my own video.But I have some new problem. I found that some video will rotate 90rads or 180 rads and if some flag to block this rotate?

**Comment by gineshidalgo99** [comment]
Yeah there is for that and for mirroring the image, check the producer section of the doc/demo_overview.md. And let me know if more issues. Thanks!

**Comment by liu6381810** [comment]
@gineshidalgo99 Hello,sorry to bother you again.
I have another question about this paper.
What's the size of the confidence map in stage 1, I mean that if input size is 368*368,the stage 1's output size should be 46*46(after VGG 19 which has 3 pool layer).So in training, the ground truth is generated in a 46*46 size? And in test I got a 46*46 confidence map and I should map it to the original size to get the landmark?

**Comment by gineshidalgo99** [comment]
I am sorry, OpenPose is focused in testing, for training questions see https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation

**Comment by liu6381810** [comment]
@gineshidalgo99 OK Thanks!
And If I want to get the part position(face, wrist e.g),How can I do it?

**Comment by gineshidalgo99** [comment]
Check the doc/output file to see the exact format and position of each one. Thanks!
