### ISSUE TITLE
Error while excute make -j `nproc`

### ISSUE THREAD

**Issue by fenilgodhani** [CMU-Perceptual-Computing-Lab/openpose#1481]
### Issue Summary
error while excute make file

### Executed Command (if any)
make -j`nproc`

### Errors (if any)
 user@user-HP-Z8-G4:~/openpose-master/build$ make -j`nproc`
[ 12%] Performing configure step for 'openpose_lib'
CMake Error: The source directory "/home/robotics/openpose-master/3rdparty/caffe" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
CMakeFiles/openpose_lib.dir/build.make:105: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Type of Issue
- Compilation/installation error

![Screenshot from 2020-01-04 12-00-49](https://user-images.githubusercontent.com/41722685/71760837-9dec7b00-2ee9-11ea-8a19-3c74279aed0d.png)

**General configuration**:
  ubantu 18.04

cuda 10.2

cuDNN 7.6.5

8. If **Python** API:
    - **Python version**: 3.7.4

**Comment by gineshidalgo99** [comment]
That's seems to be a Caffe issue. Try installing Caffe by your own, and then linking it to OpenPose following doc/installation.md. Thanks!
