### ISSUE TITLE
Low resolution images?

### ISSUE THREAD

**Issue by mazatov** [CMU-Perceptual-Computing-Lab/openpose#1482]
I'm trying to run this on low-resolution images that contain one human. The images are about ~ 50x100 pix. The program doesn't work very well on such low-resolution images. The majority of them do not have joints detected well. Though heatmaps appear to be somewhat ok.

I was wondering if someone would have any tips on how to modify the program to perform better on low res images. Thanks.

Here's an example of an image that didn't work.
![1](https://user-images.githubusercontent.com/29291003/71830875-77177b80-3086-11ea-8d83-63e403cd633e.jpg)

**Comment by gineshidalgo99** [comment]
Yeah, they are too small, not what OpenPose was trained with (trained with COCO dataset). The images will have to "look" like the images from the COCO dataset to work well. Resizing them up and sharpening them might help a bit.
