### ISSUE TITLE
Different nvidia graphics cards

### ISSUE THREAD

**Issue by xiongmao5320** [CMU-Perceptual-Computing-Lab/openpose#1483]
I am using openpose on 2 computer， one with nvidia gtx 1070 graphics card and the other with nvidia rtx 2060 super.(1070 with nvidia driver 410+cuda 10.0+cudnn 7.6.4; 2060 with nvidia driver 430+cuda 10.2+cudnn 7.6.5)
The codes are Exactly the same， but 1070 only cost 2.2G gpu memory, otherwise 2060 will cost almost 6G gpu memory.
Why is there such a difference? Can you explain it？ thanks!

**Comment by gineshidalgo99** [comment]
That's a CUDA "feature", I think the new GPUs auto-resize the required memory depending on the free memory of that GPU model. It's supposed not to be something bad, in theory it makes it faster, but definitely annoying, I agree.
