### ISSUE TITLE
How to know heatmaps values are correct or not?

### ISSUE THREAD

**Issue by JasOlean** [CMU-Perceptual-Computing-Lab/openpose#1487]
### OpenPose Output (if any)
Is there a heatmap ground truth dataset for hand. How to know your heatmaps are correct or not?

**Comment by gineshidalgo99** [comment]
See citation papers.

**Comment by mgarbade** [comment]
I read the paper and some similar questions still remain open:
For example: The input image has a 8 fold higher resolution than the ouput.
If we compute the loss on the output, we need to create heatmaps and PAFs that are also 8-fold downsampled with respect to the input. Normally PAFs only contain binary values  {0, 1}, however 

However, I saw two different implementations:

- The first one created the target PAFs  in the image resolution and then applied an 8-fold bilinear downsampling. This leads to PAFs having values between [0, 1]
- The other implementation directly creates targets in the output resolution, which then only contain binary values {0,1}, while also having more severe problems with antialiasing.

Can someone point me to the position in the official code where the target heatmaps and PAFs are computed to solve this issue?
