### ISSUE TITLE
Annotation tool

### ISSUE THREAD

**Issue by adel6666** [CMU-Perceptual-Computing-Lab/openpose#1488]
Hello,
First of all I want to thank you for this great work, I want to train the model on my own data but I do not know which annotation tool I will use can you advise me?
Thank you.

**Comment by adel6666** [comment]
Hello,
First of all I want to thank you for this great work, I want to train the model on my own data but I do not know which annotation tool I will use can you advise me?
Thank you.

**Comment by gineshidalgo99** [comment]
We simply used COCO dataset, we are not experts in labelling. Others, feel free to answer.
