### ISSUE TITLE
18 keypoints & 19 limbSeq questions

### ISSUE THREAD

**Issue by liaowang0125** [CMU-Perceptual-Computing-Lab/openpose#149]
I see the issue #86,it help a lot,but I don't understand something.
### Quesion 1
Why the channels of heatmap is 19 when we only have 18 pose keypoints?**(heatmap: height * width * 19)**  What is the role of the last keypoints?

### Question 2
I see the limbseq you give is like  limbSeq = [[2,3], [2,6], [3,4], [4,5], [6,7], [7,8],[2,1], [2,9], [9,10], [10,11],[2,12], [12,13], [13,14],  [1,15], [15,17],  [1,16], [16,18], [3,17], [6,18]].
But I think the last two limbs  [3,17], [6,18] is not necessary.What is the role of the last two limb?
**Why not  PAF'channel is 2 * 17 ?**

### Type of issue
- Question

**Comment by Tetsujinfr** [comment]
The last key point represents the background if I remember well. There is another issue thread about heatmap file format.

**Comment by liaowang0125** [comment]
thank you for your help.

**Comment by liaowang0125** [comment]
Thank you for your help.

**Comment by liaowang0125** [comment]
@Tetsujinfr Is that issue#86?

**Comment by Tetsujinfr** [comment]
Yes exactly.
