### ISSUE TITLE
left hand heat map's output is not flipped back 

### ISSUE THREAD

**Issue by NengQian** [CMU-Perceptual-Computing-Lab/openpose#1490]
### Issue Summary
The left-hand's heat maps (which can be read from **datum.handHeatMaps[0]**) is not properly flipped back to the original image.

### Type of Issue
- Enhancement / offering possible extensions / pull request / etc

2. **OpenPose version**: Latest GitHub code

**Comment by gineshidalgo99** [comment]
Sorry, that was added by the community as a pull request, but we won't modify that code (but PRs are welcome!)
