### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED while running demo (CUDA 9, Ubuntu 18.04)

### ISSUE THREAD

**Issue by yanina-anastasia** [CMU-Perceptual-Computing-Lab/openpose#1493]
## Issue Summary
While trying to run demo I get
F0123 17:32:14.907090 3954 math_functions.cu:26] Check failed: status == CUBLAS_STATUS_SUCCESS (13 vs. 0) CUBLAS_STATUS_EXECUTION_FAILED

No idea how to solve it
CUDA 9, Ubuntu 18.04

### Executed Command (if any)
`./build/examples/openpose/openpose.bin --video examples/media/video.avi `

### OpenPose Output (if any)
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
F0123 17:32:14.907090  3954 math_functions.cu:26] Check failed: status == CUBLAS_STATUS_SUCCESS (13 vs. 0)  CUBLAS_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***
    @     0x7f78c6d5a0cd  google::LogMessage::Fail()
    @     0x7f78c6d5bf33  google::LogMessage::SendToLog()
    @     0x7f78c6d59c28  google::LogMessage::Flush()
    @     0x7f78c6d5c999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f78c5eddd4a  caffe::caffe_gpu_gemm<>()
    @     0x7f78c5d1d9f1  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7f78c5e98726  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7f78c5e13031  caffe::Net<>::ForwardFromTo()
    @     0x7f78c8379108  op::NetCaffe::forwardPass()
    @     0x7f78c83a171a  op::PoseExtractorCaffe::forwardPass()
    @     0x7f78c8399b25  op::PoseExtractor::forwardPass()
    @     0x7f78c8396952  op::WPoseExtractor<>::work()
    @     0x7f78c83d9239  op::Worker<>::checkAndWork()
    @     0x7f78c83d93e0  op::SubThread<>::workTWorkers()
    @     0x7f78c83e302f  op::SubThreadQueueInOut<>::work()
    @     0x7f78c83db501  op::Thread<>::threadFunction()
    @     0x7f78c7c7066f  (unknown)
    @     0x7f78c73926db  start_thread
    @     0x7f78c76cb88f  clone
Aborted (core dumped)

### Errors (if any)
SegFault while running demo. After quick googling I found posts that suggest to install [CUDA 9 patches](https://developer.nvidia.com/cuda-90-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1704&target_type=deblocal), but there are only patches for Ubuntu 16 and 17. I installed them anyway, it didn't help (as expected).

### Type of Issue
- Help wanted
- Segmentation Fault

### Your System Configuration
1. **Whole console output**: in OpenPose output section

2. **OpenPose version**: latest GitHub code

3. **General configuration**:
    - **Installation mode**: followed the instructions in quick-start guide, also used this[ post](https://medium.com/innovation-incubator/python-openpose-installation-3fd3a58d4887)
    - **Operating system** Ubuntu 18.04.2
    - **Release or debug mode**: release
    - **Compiler**: gcc 6.5.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? 
CUDA_ARCH_BIN=30 35 37 50 52 53 60 61 62 70 (changed it in CMake GUI). It wan't working with '30 35 37... 62 70 **75**'

5. **3rd-party software**:
    - **Caffe version**: 1.0.0
    - **CMake version** 3.16.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (3.2)

6. If **GPU mode** issue:
    - **CUDA version**
CUDA Version 9.1.85
CUDA Patch Version 9.0.176.1
CUDA Patch Version 9.0.176.2
CUDA Patch Version 9.0.176.3
CUDA Patch Version 9.0.176.4

    - **cuDNN version**: 7.6.5
    - **GPU model** (`nvidia-smi` in Ubuntu): GeForce RTX 2080 Ti

8. **CPU**: AMD Ryzen threadripper 1920x 12-core processor × 24

9. If **Python** API:
    - **Python version**: 3.6.8
    - **Numpy version**: 1.17.4

**Comment by gineshidalgo99** [comment]
This is a 3rd party issue, so we can't help with it.

However, this seems to be CUDA/cuDNN not properly installed, or a mess-up of multiple versions of them. Uninstalling all CUDA/cuDNN versions and re-installing only one usually helps.
