### ISSUE TITLE
No header.hpp files found

### ISSUE THREAD

**Issue by Ceepert** [CMU-Perceptual-Computing-Lab/openpose#1495]
Im trying to install a openpose_ros node. There are no errors from that side, but in the console this error happens when i do catkin_make in my workspace. 

```
In file included from /home/student/catkin_workspace/src/ros-openpose/openpose_ros_node/src/openpose_ros_node.cpp:31:0:
/home/student/Desktop/OpenPose/openpose/include/openpose/headers.hpp:5:35: fatal error: openpose/3d/headers.hpp: No such file or directory
```
I read something about that I need to set OPENPOSE_ROOT, which I did to the /home/student/Desktop/OpenPose/openpose/ folder, but I cant find anything more about that variable.
Considering the error happens inside the header.hpp of OpenPose I thought I would check if those files are actually there and its just not finding them. 
Went to openpose/include/openpose/3d and yes there are no header files.
Now this is not only the 3d files, there are alot of those includes and none work if I rearange them its always the first one the throws the error and then quits.
Did I do something wrong at the installation of OpenPose? Cause the examples work?

Im on Ubuntu 16.04
Cuda 10

**Comment by sharafff** [comment]
same error

**Comment by gineshidalgo99** [comment]
Sorry, we did not develop openpose_ros, so we aren't familiarized with it. You'd want to ask the developer of that package.

**Comment by ravijo** [comment]
@Ceepert and @sharafff 

It seems too late to post an answer to this topic. If you are looking for a working ROS wrapper for OpenPose, please have a look at [ros_openpose](https://github.com/ravijo/ros_openpose).
