### ISSUE TITLE
c++ error  while building NVCC

### ISSUE THREAD

**Issue by kapoorparul** [CMU-Perceptual-Computing-Lab/openpose#1499]
### Type of Issue
- Compilation/installation error
- Help wanted

1. **Error**: replacing my path by "/---/---/---/"

/nfs/---/---/---/miniconda/envs/py35/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2977): error: "constexpr" is not valid here

/nfs/---/---/---/miniconda/envs/py35/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2980): error: "is_move_constructible_v" is not a function or static data member

/nfs/---/---/---/miniconda/envs/py35/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2980): error: "constexpr" is not valid here

/nfs/---/---/---//miniconda/envs/py35/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2983): error: "is_assignable_v" is not a function or static data member

/nfs/---/---/---/miniconda/envs/py35/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/type_traits(2983): error: "constexpr" is not valid here

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00003264_00000000-6_base_data_layer.cpp1.ii".
Compilation terminated.
CMake Error at cuda_compile_1_generated_base_data_layer.cu.o.Release.cmake:280 (message):
  Error generating file
  /---/---/---//openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_base_data_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:1716: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o] Error 1
CMakeFiles/Makefile2:371: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:111: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-build' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake (Ubuntu)
    - **Operating system**  Ubuntu 18.04.3
    - **Operating system version**  Ubuntu 18
    - **Release or Debug mode**? (by default: release): release
    - Compiler (`gcc --version): 7.3.0  (in conda environment)

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.10.2
    - **OpenCV version**: conda install version 3.4.2

6. If **GPU mode** issue:
    - **CUDA version**  V10.0.130
    - **cuDNN version**: 7.6.5
    - **GPU model** (`nvidia-smi` in Ubuntu):  Nvidia GetForce gtx

8. If **Python** API:
    - **Python version**: 3.5
    - **Numpy version**  1.15.2

**Comment by gineshidalgo99** [comment]
Unfortunately, we do not officially support miniconda. Other community answers are welcome here! But i'll have to close it to keep only bugs open.
