### ISSUE TITLE
segmentation fault error 

### ISSUE THREAD

**Issue by umarasif** [CMU-Perceptual-Computing-Lab/openpose#1500]
Hi,

I am running the video example on Ubuntu and got segmentation fault error as shown below. How should I fix this error?

Thanks

./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 1
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Segmentation fault (core dumped)

**Comment by dsingh80** [comment]
Try using the `--logging_level 0` flag when running to print out debugging information

**Comment by gineshidalgo99** [comment]
[Ban for not following the instructions for posting here]
