### ISSUE TITLE
OpenPose Python package on jetson TX2

### ISSUE THREAD

**Issue by QBoulanger** [CMU-Perceptual-Computing-Lab/openpose#1502]
Hi guys,

I'm trying to use your wonderful repo Openpose on my jetson TX2. I can install it, and build it... no problem. 

But I meet problems when trying it with python. Here is the log:

> Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
> Traceback (most recent call last):
>   File "07_hand_from_image.py", line 27, in <module>
>     raise e
>   File "07_hand_from_image.py", line 24, in <module>
>     from openpose import pyopenpose as op
>   File "../../python/openpose/__init__.py", line 1, in <module>
>     from . import pyopenpose as pyopenpose
> ImportError: cannot import name 'pyopenpose'

I tried to cmake -DBUILD_PYTHON=ON .. in my build file but that didn't fixed the issue. 

I don't understand: "...have this Python script in the right folder?"

None of the other issues helped me.

Thank you,

**Comment by gineshidalgo99** [comment]
You want to install OpenPose with Cmake in order to enable Python or any other custom flag.
