### ISSUE TITLE
Cuda check failed (100 vs. 0): no CUDA-capable device is detected

### ISSUE THREAD

**Issue by Ceepert** [CMU-Perceptual-Computing-Lab/openpose#1505]
### Issue Summary
When trying to start one of the examples in OpenPose I get an error, saying that no Cuda able device was found, even though it worked just a couple of days ago. I did not change anything system related, just did some programming.

### Executed Command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi --logging_level 0 --disable_multi_thread

*I also did it without the --logging_level 0 ...

### Errors (if any)
`Starting OpenPose demo...
Configuring OpenPose...
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():210
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():170
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseMode():11
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():33
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():82
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToHeatMapScaleMode():116
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():147
/home/student/Desktop/OpenPose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():147
Starting thread(s)...
/home/student/Desktop/OpenPose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():98
/home/student/Desktop/OpenPose/openpose/src/openpose/producer/producer.cpp:createProducer():417
/home/student/Desktop/OpenPose/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():17
/home/student/Desktop/OpenPose/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():184

Error:
Cuda check failed (100 vs. 0): no CUDA-capable device is detected

Coming from:
- /home/student/Desktop/OpenPose/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():53
- /home/student/Desktop/OpenPose/openpose/src/openpose/gpu/cuda.cpp:cudaCheck():42
- /home/student/Desktop/OpenPose/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():63
- /home/student/Desktop/OpenPose/openpose/src/openpose/gpu/gpu.cpp:getGpuNumber():27
cv::VideoCapture released. In /home/student/Desktop/OpenPose/openpose/src/openpose/producer/videoCaptureReader.cpp:release():170
- /home/student/Desktop/OpenPose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1188
- /home/student/Desktop/OpenPose/openpose/include/openpose/wrapper/wrapper.hpp:exec():424
/home/student/Desktop/OpenPose/openpose/include/openpose/thread/threadManager.hpp:stop():230
/home/student/Desktop/OpenPose/openpose/include/openpose/thread/threadManager.hpp:stop():233
/home/student/Desktop/OpenPose/openpose/include/openpose/thread/threadManager.hpp:stop():237
/home/student/Desktop/OpenPose/openpose/include/openpose/thread/threadManager.hpp:stop():239
`

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Cuda error

### Your System Configuration

1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: Ubuntu CMake
    - **Operating system** Ubuntu
    - **Operating system version** Ubuntu 16.04
    

3. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev`

**Comment by Ceepert** [comment]
I figured it out, for anyone else having this issue here is the solution (Replace the <> Brackets with the Version Numbers you are using:

in the Directory: /etc/ld.so.conf.d/cuda<versionNumber>.conf 
add this line
/usr/lib/nvidia-<NvidiaVersionNumber>

Then do this command:
sudo dpkg-reconfigure nvidia-<VersionNumber>

Then restart your system and it should work again

**Comment by jernsting** [comment]
I have the same problem.

nvidia-smi shows my graphics card.
The device query example (and others) from cuda are able to find the graphics card.
Tensorflow is able to use the graphics card via cuda.

The openpose caffe version does not find the graphics card. 

My setup:
 - CUDA 10.0 (also tried 9.2 and 10.1)
 - NVIDIA driver version 440

**Comment by shiva-kumarj** [comment]
I am running the example on colab and in order to avoid having to build openpose repeatedly, I built it once and I copied all the files to the drive and then loaded it back to a runtime in another notebook.
Running the example on the new notebook threw this error.

`Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...

Error:
Cuda check failed (100 vs. 0): no CUDA-capable device is detected

Coming from:
- /content/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():48
- /content/openpose/src/openpose/gpu/cuda.cpp:cudaCheck():37
- /content/openpose/src/openpose/gpu/cuda.cpp:getCudaGpuNumber():58
- /content/openpose/src/openpose/gpu/gpu.cpp:getGpuNumber():27
- /content/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1221
- /content/openpose/include/openpose/wrapper/wrapper.hpp:exec():424`

Any workarounds ?

**Comment by senemaktas** [comment]
> I figured it out, for anyone else having this issue here is the solution (Replace the <> Brackets with the Version Numbers you are using:
> 
> in the Directory: /etc/ld.so.conf.d/cuda.conf
> add this line
> /usr/lib/nvidia-
> 
> Then do this command:
> sudo dpkg-reconfigure nvidia-
> 
> Then restart your system and it should work again

Hi thanks for advice ! I could not understand that part : "I figured it out, for anyone else having this issue here is the solution (Replace the <> Brackets with the Version Numbers you are using" . could you explain little bit more? Thanks. @Ceepert

**Comment by sanabouchama** [comment]
> 

hey please did you get the unswer ??

**Comment by cantonioupao** [comment]
The issue persists for me as well!

**Comment by fahnub** [comment]
Facing the same issue on my Laptop.
