### ISSUE TITLE
bash: scripts/osx/install_deps.sh: No such file or directory

### ISSUE THREAD

**Issue by Aaloneman** [CMU-Perceptual-Computing-Lab/openpose#1506]
I am running on a Mac. sudo bash scripts/osx/install_deps.sh (suggested in the docs) causes the following error

bash: scripts/osx/install_deps.sh: No such file or directory

**Comment by losnooze** [comment]
yep, me too...you solved?

**Comment by gineshidalgo99** [comment]
Are you running it from the folder that it is asked? Can you visually see it in your machine? [This is unrelated to OP but rather a different issue.]

**Comment by MutluCukurova** [comment]
I have the same problem, did you find a solution yet please?

**Comment by camrynfriedman** [comment]
I'm having the same issue. Can someone help me?
