### ISSUE TITLE
getting error CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by mandeeptatras** [CMU-Perceptual-Computing-Lab/openpose#1508]
I have installed cuda=10.2 and cudnn=7.6.5. The code is  built suceessfully, but when i run something from example, rather with python_api or openpose.bin it is showing me the same error:-

Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0212 17:59:14.279742 26709 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***
    @     0x7f6921ed30cd  google::LogMessage::Fail()
    @     0x7f6921ed4f33  google::LogMessage::SendToLog()
    @     0x7f6921ed2c28  google::LogMessage::Flush()
    @     0x7f6921ed5999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f69218f6eb3  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f69219ff03d  caffe::Net<>::Init()
    @     0x7f6921a0113e  caffe::Net<>::Net()
    @     0x7f69234f379a  op::NetCaffe::initializationOnThread()
    @     0x7f6923517fb4  op::addCaffeNetOnThread()
    @     0x7f69235194d6  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f692351f163  op::PoseExtractorNet::initializationOnThread()
    @     0x7f6923513d01  op::PoseExtractor::initializationOnThread()
    @     0x7f692350ea01  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f6923553001  op::Worker<>::initializationOnThreadNoException()
    @     0x7f6923553130  op::SubThread<>::initializationOnThread()
    @     0x7f6923555488  op::Thread<>::initializationOnThread()
    @     0x7f6923555657  op::Thread<>::threadFunction()
    @     0x7f6922de966f  (unknown)
    @     0x7f692250b6db  start_thread
    @     0x7f692284488f  clone
Aborted (core dumped)

Can someone please help me in this.
I have reinstalled cudnn three times and it is not working.

**Comment by Sunny478** [comment]
I am facing the exact same problem. Any help guys??
PS: I am feeling it is a caffe problem.

**Comment by Nikhil-Shenoy** [comment]
I am also having the same issue.

**Comment by DanielJMPinto** [comment]
same here

**Comment by DanielJMPinto** [comment]
using cuda 10.1 and cudnn 7.5.0 solved the issue

**Comment by gineshidalgo99** [comment]
That usually happens when the CUDA/cuDNN drivers are messed up in a machine. Removing ALL cuda/cudnn + installing only 1 usually works. This is a 3rdparty issue, so not officially supported.

**Comment by vagi8** [comment]
> That usually happens when the CUDA/cuDNN drivers are messed up in a machine. Removing ALL cuda/cudnn + installing only 1 usually works. This is a 3rdparty issue, so not officially supported.

I have already installed openpose. 
If i reinstall my cuda/cudnn, then do i also have to reinstall my openpose ?
OS : Ubuntu 18.04
GPU Mode

**Comment by CSN-001** [comment]
I am also having the same issue.

**Comment by CSN-001** [comment]
I am also having the same issue.
OS: Ubuntu 20.04
CUDA:11.0
CUDNN:8.0

**Comment by Sunny478** [comment]
decreasing net_resolution solved the issue for me

**Comment by mohamedabdallah1996** [comment]
> That usually happens when the CUDA/cuDNN drivers are messed up in a machine. Removing ALL cuda/cudnn + installing only 1 usually works. This is a 3rdparty issue, so not officially supported.

I made sure that I have only one nvidia driver and also one version of Cuda and Cudnn and still I have the same problem

```
$ dpkg -l | grep nvidia-driver
ii  nvidia-driver-465                                           465.19.01-0ubuntu1                    amd64        NVIDIA driver metapackage
```
```
$ cat /usr/local/cuda/version.json
{
   "cuda" : {
      "name" : "CUDA SDK",
      "version" : "11.3.0"
   },
   "cuda_cudart" : {
      "name" : "CUDA Runtime (cudart)",
      "version" : "11.3.58"
   },
   "cuda_cuobjdump" : {
      "name" : "cuobjdump",
      "version" : "11.3.58"
   },
   "cuda_cupti" : {
      "name" : "CUPTI",
      "version" : "11.3.58"
   },
   "cuda_cuxxfilt" : {
      "name" : "CUDA cu++ filt",
      "version" : "11.3.58"
   },
   "cuda_demo_suite" : {
      "name" : "CUDA Demo Suite",
      "version" : "11.3.58"
   },
   "cuda_gdb" : {
      "name" : "CUDA GDB",
      "version" : "11.3.58"
   },
   "cuda_memcheck" : {
      "name" : "CUDA Memcheck",
      "version" : "11.3.58"
   },
   "cuda_nsight" : {
      "name" : "Nsight Eclipse Plugins",
      "version" : "11.3.58"
   },
   "cuda_nvcc" : {
      "name" : "CUDA NVCC",
      "version" : "11.3.58"
   },
   "cuda_nvdisasm" : {
      "name" : "CUDA nvdisasm",
      "version" : "11.3.58"
   },
   "cuda_nvml_dev" : {
      "name" : "CUDA NVML Headers",
      "version" : "11.3.58"
   },
   "cuda_nvprof" : {
      "name" : "CUDA nvprof",
      "version" : "11.3.58"
   },
   "cuda_nvprune" : {
      "name" : "CUDA nvprune",
      "version" : "11.3.58"
   },
   "cuda_nvrtc" : {
      "name" : "CUDA NVRTC",
      "version" : "11.3.58"
   },
   "cuda_nvtx" : {
      "name" : "CUDA NVTX",
      "version" : "11.3.58"
   },
   "cuda_nvvp" : {
      "name" : "CUDA NVVP",
      "version" : "11.3.58"
   },
   "cuda_samples" : {
      "name" : "CUDA Samples",
      "version" : "11.3.58"
   },
   "cuda_sanitizer_api" : {
      "name" : "CUDA Compute Sanitizer API",
      "version" : "11.3.58"
   },
   "fabricmanager" : {
      "name" : "Fabric Manager",
      "version" : "465.19.01"
   },
   "libcublas" : {
      "name" : "CUDA cuBLAS",
      "version" : "11.4.2.10064"
   },
   "libcufft" : {
      "name" : "CUDA cuFFT",
      "version" : "10.4.2.58"
   },
   "libcurand" : {
      "name" : "CUDA cuRAND",
      "version" : "10.2.4.58"
   },
   "libcusolver" : {
      "name" : "CUDA cuSOLVER",
      "version" : "11.1.1.58"
   },
   "libcusparse" : {
      "name" : "CUDA cuSPARSE",
      "version" : "11.5.0.58"
   },
   "libnpp" : {
      "name" : "CUDA NPP",
      "version" : "11.3.3.44"
   },
   "libnvjpeg" : {
      "name" : "CUDA nvJPEG",
      "version" : "11.4.1.58"
   },
   "nsight_compute" : {
      "name" : "Nsight Compute",
      "version" : "2021.1.0.18"
   },
   "nsight_systems" : {
      "name" : "Nsight Systems",
      "version" : "2021.1.3.14"
   },
   "nvidia_driver" : {
      "name" : "NVIDIA Linux Driver",
      "version" : "465.19.01"
   }
}
```
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```
```
$ nvidia-smi
Tue Dec 28 13:21:37 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:58:00.0 Off |                  N/A |
| N/A   43C    P0    N/A /  N/A |      9MiB /  1878MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1017      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      1680      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

It seems Cuda and Cudnn drivers are compatible and they worked well. Is this correct or something I am missing?
also I tried to decrease `net_resolution` and the same problem happening.

do you have any idea about that?

**Comment by mayank64ce** [comment]
Facing same issue.
