### ISSUE TITLE
Error saying drivers_types.h file is not found

### ISSUE THREAD

**Issue by SRG2596** [CMU-Perceptual-Computing-Lab/openpose#151]
While executing the demo on Windows 10, the following error came up: 
Cannot include drivers_types.h No such directory or file.
Any help would be appreciated. Thanks in advance :)

### Your system configuration
**Operating system** : Windows 10
**CUDA version** : 8.0
**cuDNN version**: 5.1
**GPU model**: Geforce 940M 
**Caffe version**: Default from OpenPose 
**OpenCV version**: installed with `apt-get install

**Comment by gineshidalgo99** [comment]
Please do not post twice the same issue, you can always delete the other one (I deleted the one in #80).

And I am sorry, but I need more feed-back. From which file is trying to include it? Thanks!

**Comment by SRG2596** [comment]
Apologies for posting the same issue twice!

I hope the following screenshot helps:
![whatsapp image 2017-07-20 at 10 23 12 am](https://user-images.githubusercontent.com/29581472/28401168-c5a6adb4-6d35-11e7-8c00-f5a0b5338589.jpeg)

**Comment by awanabe** [comment]
Same problem

#include "driver_types.h"
#include "cuComplex.h"   
#include "cuda_fp16.h"
#include "library_types.h"


These four h files cannot be found

**Comment by gineshidalgo99** [comment]
OK so it comes from CUDA. I'd say to re-install the Nvidia drivers and after that re-install CUDA.

Did you follow the installation instructions? (in particular the one saying `If CUDA was already installed, re-install it after installing VS!`

**Comment by awanabe** [comment]
I followed your guide.
re-Installed CUDA after install VS. It doesnt work.
Then I uninstall the cuda, then install it, but it still doesnt work.

Maybe CUDA doesnt find the vs.

My Env:
VS2015 Community
Win10

**Comment by gineshidalgo99** [comment]
Is CUDA installed in the default location?

**Comment by awanabe** [comment]
Yes
Program Files

So I give up configuring it on Windows

It is much easier to configure it in Ubuntu.

**Comment by gineshidalgo99** [comment]
Sorry to hear that. It should be easier on Windows, I do not know where the error might be coming from
