### ISSUE TITLE
undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by chenjianqu** [CMU-Perceptual-Computing-Lab/openpose#1513]
When I compile openpose, there were some problems：

[ 92%] Linking CXX executable 1_custom_post_processing.bin
[ 92%] Linking CXX executable 1_openpose_read_and_display.bin
/usr/bin/ld: CMakeFiles/1_custom_post_processing.bin.dir/1_custom_post_processing.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/tutorial_add_module/CMakeFiles/1_custom_post_processing.bin.dir/build.make:120: recipe for target 'examples/tutorial_add_module/1_custom_post_processing.bin' failed
make[2]: *** [examples/tutorial_add_module/1_custom_post_processing.bin] Error 1
CMakeFiles/Makefile2:1153: recipe for target 'examples/tutorial_add_module/CMakeFiles/1_custom_post_processing.bin.dir/all' failed
make[1]: *** [examples/tutorial_add_module/CMakeFiles/1_custom_post_processing.bin.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 92%] Built target 2_extract_pose_or_heatmat_from_image.bin
[ 93%] Built target 1_extract_from_image.bin
[ 94%] Built target 1_openpose_read_and_display.bin
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

how to fix it?

**Comment by gineshidalgo99** [comment]
Dupli of other posts, see eg:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/373
