### ISSUE TITLE
How can i save custom json output(without threshold<0.2 keypoints)

### ISSUE THREAD

**Issue by supernova817** [CMU-Perceptual-Computing-Lab/openpose#1514]
Hello 

i want to save keypoints custom json like this
if handkeypoints thresh score < 0.2 then want to save [... 0,0,0 ...] instead of [... 122.22 , 555 , 0.12223 ...]

how can i do ?

**Comment by gineshidalgo99** [comment]
The easiest thing is to do some post-processing of that JSON to get rid of those points. I can not think of any cases in which you would want to do that, so I do not think it should be done really. What are you trying to achieve exactly?
