### ISSUE TITLE
Cmake error Mac user

### ISSUE THREAD

**Issue by Rainy97** [CMU-Perceptual-Computing-Lab/openpose#1518]
# I searched for an answer but I didn't find the right one. so, please help!
#891

-- Configuring incomplete, errors occurred!
See also "/Users/arwa/openpose/bulid/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [all] Error 2
(base) \w $make -j`sysctl -n hw.logicalcpu`
make: /Applications/CMake.app/Contents/bin/cmake: No such file or directory
make: *** [cmake_check_build_system] Error 1
(base) \w $make -j`sysctl -n hw.logicalcpu`
make: /Applications/CMake.app/Contents/bin/cmake: No such file or directory
make: *** [cmake_check_build_system] Error 1

**Comment by gineshidalgo99** [comment]
Ban for not following the template.
