### ISSUE TITLE
Detection accuracy

### ISSUE THREAD

**Issue by priyankakulkarni411** [CMU-Perceptual-Computing-Lab/openpose#1519]
Hey there!
I have been using OpenPose in one of my hobby projects. Sometimes the model doesn't recognize the body part even though that part is clearly visible. Any other ways to increase the recognition accuracy apart from the one mentioned in the CMU-github repo?

**Comment by gineshidalgo99** [comment]
No, I added all my ideas in there, it is not perfect, unfortunately :(
