### ISSUE TITLE
In CUDA 10.2 CuDNN 7.6.5. Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by hgedia12** [CMU-Perceptual-Computing-Lab/openpose#1520]
Hi guys, I tried to run some demos in my pc having CUDA 10.2 and CuDNN 7.6.5. I saw previous answers but am not able to understand. Please help.

Here's what I am getting

*** Check failure stack trace: ***
    @     0x7f8ae8ac30cd  google::LogMessage::Fail()
    @     0x7f8ae8ac4f33  google::LogMessage::SendToLog()
    @     0x7f8ae8ac2c28  google::LogMessage::Flush()
    @     0x7f8ae8ac5999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8ae84a69e9  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f8ae85a85a3  caffe::Net<>::Init()
    @     0x7f8ae85ab25e  caffe::Net<>::Net()
    @     0x7f8aea0e2aca  op::NetCaffe::initializationOnThread()
    @     0x7f8aea106fe2  op::addCaffeNetOnThread()
    @     0x7f8aea1084c6  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f8aea10e093  op::PoseExtractorNet::initializationOnThread()
    @     0x7f8aea102d61  op::PoseExtractor::initializationOnThread()
    @     0x7f8aea0fdb41  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f8aea141d11  op::Worker<>::initializationOnThreadNoException()
    @     0x7f8aea141e40  op::SubThread<>::initializationOnThread()
    @     0x7f8aea144198  op::Thread<>::initializationOnThread()
    @     0x7f8aea144367  op::Thread<>::threadFunction()
    @     0x7f8ae99d966f  (unknown)
    @     0x7f8ae90fb6db  start_thread
    @     0x7f8ae943488f  clone
Aborted (core dumped)

**Comment by timmy61109** [comment]
Me too.

**Comment by gineshidalgo99** [comment]
Ban for not filling the GitHub issue template
