### ISSUE TITLE
How can I use depth camera and openpose to get 3d keypoints(X,Y,Z) ? Thanks.

### ISSUE THREAD

**Issue by karta1310041** [CMU-Perceptual-Computing-Lab/openpose#1521]
How can I use depth camera and openpose to get 3d keypoints(X,Y,Z) ? Thanks.
I found some information that openpose have a mode can use depth camera to get 3d keypoints.
But I didn't find the information about how to open this mode. Thanks.

**Comment by gineshidalgo99** [comment]
OpenPose will give you 2D keypoints, get the Z coordinate from your favorite depth camera.
