### ISSUE TITLE
3D/2D Kinematic Analysis

### ISSUE THREAD

**Issue by mpourasa** [CMU-Perceptual-Computing-Lab/openpose#1522]
Hello,

I am in the procedure of devising my master's thesis and I am trying to avoid using complicated and expensive equipment for motion analysis.

So I would like to ask if it is possible to extract the movement of the skeletons during the video capture.

I would appreciate any response, since it is a very serious matter.

**Comment by mpourasa** [comment]
Hello. Is there anyone who can answer?

**Comment by gineshidalgo99** [comment]
Possible: OpenPose won't give it directly to you, but yes, but you could implement the code to read 3-D keypoints from OpenPose and return 3D joint angles. This is out of the scope of OpenPose, though, so you would have to do it yourself.
