### ISSUE TITLE
libopenpose ld returned 1 exit status

### ISSUE THREAD

**Issue by VincentKaras** [CMU-Perceptual-Computing-Lab/openpose#1524]
### Issue Summary
Generating finished (cmake warned of cycle  in the constraint graph for examples)
make -j step failed. ld throws an error while linking libopenpose.so

[ 42%] Linking CXX shared library libopenpose.so
/usr/bin/ld: cannot find -l/usr/local/lib/python2.7/dist-packages/scipy/.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so
collect2: error: ld returned 1 exit status
src/openpose/CMakeFiles/openpose.dir/build.make:2106: recipe for target 'src/openpose/libopenpose.so.1.5.1' failed
make[5]: *** [src/openpose/libopenpose.so.1.5.1] Error 1
CMakeFiles/Makefile2:725: recipe for target 'src/openpose/CMakeFiles/openpose.dir/all' failed
make[4]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:125: recipe for target 'openpose_lib' failed
make[2]: *** [openpose_lib] Error 2
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Executed Command (if any)

make -j20

### Errors (if any)

collect2: error: ld returned 1 exit status

using opencv previously installed from source. Followed instructions for Scenario 3 from the installation.md

### Type of Issue

- Compilation/installation error

### Your System Configuration
1. **Whole console output** https://pastebin.com/SCe797y0

2. **OpenPose version**: Latest Github version

3. **General configuration**:
    - **Installation mode**: Cmake
    - **Operating system** Ubuntu 18.04.4 LTS

    - **Operating system version** 18.04.4 
    - **Release or Debug mode**? Release
    - Compiler 7.4.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** 3.16.5
    - **OpenCV version**: compiled from source 4.2.0

6. If **GPU mode** issue:
    - **CUDA version** 10.1.243
    - **cuDNN version**: 7.6.5
    - **GPU model** Tesla V100

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by lstappen** [comment]
same problem here...

**Comment by igorgbs** [comment]
same problem here.

**Comment by gineshidalgo99** [comment]
Try setting any Python configuration to false. It's weird it is trying to link against some Python library, when you are not using Python.

Otherwise, it is about OpenBLAS, try installing OpenBLAS as Caffe website says, that might help too.

(Technically 3rd party issues, so i'll close it, but feel free to keep answering)

**Comment by igorgbs** [comment]
So, I clone the repository using git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose. After that, I use CMake as the documentation said. So, when I try to make -j`nproc`
, this error appears. I don't know how to fix this.

**Comment by gineshidalgo99** [comment]
And did you run all the prerequisites mentioned in the doc/installation.md? I.e.,
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md#ubuntu-prerequisites

**Comment by igorgbs** [comment]
Yeap :/

**Comment by igorgbs** [comment]
I installed the caffe library, but when I run CMake, this error shows to me: Caffe_INCLUDE_DIRS-NOTFOUND and Caffe_LIBS-NOTFOUND.

Do you know how to fix it?

**Comment by gineshidalgo99** [comment]
Actually, those are mostly for Windows or if you wanted to add your custom Caffe path (that's why they are not set), but for the default Caffe that comes with OpenPose you do not need them.

**Comment by gineshidalgo99** [comment]
The thing that will make it work for sure. Compile and install Caffe by your own:
https://github.com/BVLC/caffe

After you can successfully compile and install Caffe on your machine, you should be able to install OpenPose (those error you post are for Caffe trying to link to Atlas/OpenBlas)

**Comment by igorgbs** [comment]
Same error. Unfortunately is really hard to install all dependencies and things to run openpose :/

**Comment by igorgbs** [comment]
src/caffe/CMakeFiles/caffe.dir/build.make:497: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o] Error 1
CMakeFiles/Makefile2:244: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:111: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-build' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lstappen** [comment]
> Same error. Unfortunately is really hard to install all dependencies and things to run openpose :/

Unfortunately, I have to agree... From our and a befriended CS research group, 4 people tried to install it on different systems and none of them was successful... having the above and similar issues :( Also spending days changing the configs etc. did not help. 

Only thing we managed was to get the models to run with opencv on cpu which is ofc impractical to use...

**Comment by garyli03** [comment]
Please make sure you have Numpy 1.16.4 installed.
