### ISSUE TITLE
pyopenpose

### ISSUE THREAD

**Issue by pig14726** [CMU-Perceptual-Computing-Lab/openpose#1526]
EDITED: PyOpenPose might not work well on Python 3.8, use 3.7 if you can't make it compile for 3.8.

**Comment by soulslicer** [comment]
What is your error??

**Comment by wjtscn** [comment]
import pyopenpose as op
ImportError: DLL load failed while importing pyopenpose: cant find...

**Comment by bella-u** [comment]
import pyopenpose as op
ImportError: DLL load failed

could someone fix this problem? this confuses me a few days.
Thanks!

**Comment by wjtscn** [comment]
not use python3.8
>
