### ISSUE TITLE
Can body, face and hand models run separately?

### ISSUE THREAD

**Issue by Sunny478** [CMU-Perceptual-Computing-Lab/openpose#1530]
I think the face and hand models depend on body model, but is there a way I can run body model now and hand+face model later?

**Comment by richie-chang** [comment]
excuse me sir @Sunny478 ,
do you got error when do a hand or face model ?

i got an error when running the hand or face model.

prototxt file not found: models\face/pose_deploy.prototxt

**Comment by soulslicer** [comment]
Yes, but you need to provide the bounding box. See examples:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/06_face_from_image.py

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/07_hand_from_image.py

**Comment by rlczddl** [comment]
excuse me sir @Sunny478 ,
how to get the bounding box of human face and hand, is there any open source project recommended?

**Comment by Sunny478** [comment]
@rlczddl  the image acquisition module here might help...
https://github.com/abhinavpatel2912/Gesture-Detection
