### ISSUE TITLE
Recommended way to run 3D pose estimation on 2 images using Python API

### ISSUE THREAD

**Issue by anthnyprschka** [CMU-Perceptual-Computing-Lab/openpose#1534]
Hello there,

sorry if it's the wrong place to post this but I've been trying to wrap my head around this for a while now.

I am trying to run 3D pose estimation from 2 images using the openpose Python API.

The straightforward way to run 2D pose estimation from the Python API is this:

```
...

opWrapper = op.WrapperPython()
opWrapper.configure(params)
opWrapper.start()

# Process Image
datum = op.Datum()
imageToProcess = cv2.imread(args[0].image_path)
datum.cvInputData = imageToProcess
opWrapper.emplaceAndPop([datum])

# Display Image
print("Body keypoints: \n" + str(datum.poseKeypoints))
cv2.imshow("OpenPose 1.5.1 - Tutorial Python API", datum.cvOutputData)
```
But afaik there is no way to pass in 2 images to `opWrapper.emplaceAndPop`, is there? Any hint is highly appreciated.

(I omitted information about my setup as i think there is no specific issue with it)

**Comment by anthnyprschka** [comment]
So i found this piece of code that is invoked from the C++ API if I am not mistaken (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/producer/wDatumProducer.hpp#L85-L103):
```
            if (tDatums != nullptr && tDatums->size() > 1)
            {
                // Add tDatums to mQueuedElements
                for (auto i = 0u ; i < tDatums->size() ; i++)
                {
                    auto& tDatumPtr = (*tDatums)[i];
                    tDatumPtr->subId = i;
                    tDatumPtr->subIdMax = tDatums->size()-1;
                    mQueuedElements.emplace(
                        std::make_shared<std::vector<std::shared_ptr<TDatum>>>(
                            std::vector<std::shared_ptr<TDatum>>{tDatumPtr}));
                }
            }
            // Queued elements - Multiple views --> Return oldest view
            if (!mQueuedElements.empty())
            {
                tDatums = mQueuedElements.front();
                mQueuedElements.pop();
            }
```
But i don't know how to something similar from Python atm

**Comment by gineshidalgo99** [comment]
Not sure if that functionality is enabled for Python as well, that's a question for @soulslicer

**Comment by anthnyprschka** [comment]
@gineshidalgo99 thanks for your message!!

@soulslicer would be very thankful for your input or some hints how to get it work
