### ISSUE TITLE
--write_video is saving huge file size compared to original

### ISSUE THREAD

**Issue by Vfitstory** [CMU-Perceptual-Computing-Lab/openpose#1535]
Hi,
 Am using openpose in Google Colab and I am getting HUGE post processed files compared to original files size, almost 10x

#this code
cd openpose && ./build/examples/openpose/openpose.bin --video examples/media/4.avi --write_json output/ --display 0 --write_video '/content/gdrive/My Drive/openvideos/pros/4.avi'

original file size is ~48mb, saved video is ~400mb.

any reason why this is happening? iv noticed this as well with the example video file where it is going from ~1.4mb to ~39mb.

extra credit question: where is the json files being saved in colab? when i try to keep a path it no worky.

**Comment by gineshidalgo99** [comment]
Avi is huge compared to mp4. 2 options:
You can convert the avi into your own format.
Or use mp4, but read OP doc about it, it also have some downsides (like it saves first images, and later convert them to mp4 with ffmpeg, only available on Ubuntu).
