### ISSUE TITLE
Error: Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by jdewitt66** [CMU-Perceptual-Computing-Lab/openpose#1536]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
 I have downloaded the OpenPose files to my Windows 10 laptop but when I try to run the OpenPose Demo via: 
bin\OpenPoseDemo.exe --video examples\media\video.avi

I get the Cuda error above. I downloaded and installed the latest CUDA driver from NVIDIA today but the problem was not resolved. Any assistance would be appreciated.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
bin\OpenPoseDemo.exe --video examples\media\video.avi

### OpenPose Output (if any)
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...

### Errors (if any)
Error:
Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

Coming from:
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():53
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():42
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():63
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1188
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424

### Type of Issue
- Execution error
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/zYwGXyDn

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
openpose-1.5.1-binaries-win64-gpu-python-flir-3d_recommended

3. **General configuration**:
    - **Installation mode**: CMake, ... (Windows); ...?
    - **Operating system** Windows 10
    - **Operating system version** Windows 10
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo 

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
Dupli, that's a CUDA issue, not OpenPose issue.
