### ISSUE TITLE
How were the neck keypoints generated with COCO?

### ISSUE THREAD

**Issue by protossw512** [CMU-Perceptual-Computing-Lab/openpose#1537]
I noticed that the original COCO dataset only provides 17 keypoints. But we have an output of 18 keypoints with COCO model(also shown in the [paper](https://arxiv.org/pdf/1812.08008.pdf) Fig 10.b) Seems like we have an additional keypoint on the neck. Were they inferred from the groundtruth annotations (e.g. middle of two shoulders) during training or testing or we have the groundtruth for training from somewhere else?

**Comment by gineshidalgo99** [comment]
Inferred as the middle point between the shoulders.
