### ISSUE TITLE
Estimating keypoints out of frame

### ISSUE THREAD

**Issue by rogerthat94** [CMU-Perceptual-Computing-Lab/openpose#1539]
### Issue Summary

When a joint is out of the video frame, the keypoint corresponding to this joint has zeros for its x and y coordinate in the JSON file that Openpose outputs. Is there an easy way I could get Openpose to estimate coordinates for joints that are out of the frame? 

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
OpenPose will try, and might predict it, if you add a black padding around the image and that keypoint is close to the end of the image. Other than that, no, there is no way to detect out of image frames, sorry!

**Comment by rogerthat94** [comment]
That's too bad. The JHMDB dataset has joints out of frame labeled, and I was hoping to automatically generate joint coordinates that are similar to those that were manually labeled in JHMDB.
