### ISSUE TITLE
Windows Demo Execution Crash

### ISSUE THREAD

**Issue by SRG2596** [CMU-Perceptual-Computing-Lab/openpose#154]
While trying to execute the Windows Demo, the following error has occured:
![whatsapp image 2017-07-20 at 11 52 44 am](https://user-images.githubusercontent.com/29581472/28403898-87189abc-6d44-11e7-82f5-a8b7ab8f5cf8.jpeg)

Even though the file exists at the said location. 
Thanks!

### Your system configuration
**Operating system** : Windows 10
**CUDA version** : 8.0
**cuDNN version**: 5.1
**GPU model** : Nvidia GeForce 940M (2GB)
**Caffe version**: Default from OpenPose.

**Comment by luckynote** [comment]
You need see whether the pose_deploy_1.....prototxt file is same as your file!

**Comment by gineshidalgo99** [comment]
Please, follow the quick start section in the installation md file, you must call OpenPose from the main folder not inside bin.
