### ISSUE TITLE
How do i get the coordinates of a keypoint, like an arm, in unity? 

### ISSUE THREAD

**Issue by laermanskoen** [CMU-Perceptual-Computing-Lab/openpose#1540]
### Issue Summary
I have no idea how to achieve this. 

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)
The demo scene is working but now i just need the coordinates of keypoints instead of the drawing.

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted

**Comment by gineshidalgo99** [comment]
See the tutorials.
