### ISSUE TITLE
openpose debug build uses incorrect runtime library

### ISSUE THREAD

**Issue by Procdox** [CMU-Perceptual-Computing-Lab/openpose#1541]
### Issue Summary
When an openpose project is created, the debug configuration is set to use the release runtime library. When this is changed, openpose no longer compiles due to linker errors.

### Executed Command (if any)

- Cmake configure for MSVC 2017 with x64 flag set
- Cmake generate
- for the openpose dll project, debug configuration...
change C/C++ -> Code Generation -> Runtime Library from /MD to /MDd (multi threaded debug dll)
- Build Project

### OpenPose Output (if any)

None

### Errors (if any)
LNK2038
LNK4049
LNK4217

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** 
https://pastebin.com/Mnc9NtYN

2. **OpenPose version**: 
Latest GitHub code as of 3/27/2020

3. **General configuration**:
    - **Installation mode**: Windows CMAKE to MSVC 2017 x64
    - **Operating system**: Windows
    - **Operating system version**: Windows 10 Pro - 64 bit
    - **Release or Debug mode**: Debug
    - **Compiler**: VS2017 community

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.17.0-rc3
    - **OpenCV version**: compiled from source 4.2.0

6. If **GPU mode** issue:
    - **CUDA version**: 10.2.95
    - **cuDNN version**: packaged
    - **GPU model** RTX 2070 (driver 441.22)

9. If **Windows** system:
    - Compiled

**Comment by Procdox** [comment]
It seems to have something to do with nvcc compiled obj files being built with the wrong runtime library as well.
1>openpose_generated_pyramidalLK.cu.obj : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in cameraParameterReader.obj

After some investigation:
Changing CMAKE_BUILD_TYPE to DEBUG, has no effect on its own.
BUT, adding -D_DEBUG -g to CUDA_NVCC_FLAGS_DEBUG is enough to get the library to compile.
https://pastebin.com/nxC2CS1h

Might follow up if more issues arise

**Comment by gineshidalgo99** [comment]
Actually, OpenPose was not using any of the 3rdparty debug libraries at all.

I have just pushed a relatively big change to all the CMake system to enable the debug mode "for real". It all works on my machine, but please, let me know if you face any issues!

(Closing it for now, but Procdox or anyone else feel free to answer in this thread if any issue arises from Debug in coming days!)
