### ISSUE TITLE
Facial Keypoint Detection for Profile View. 

### ISSUE THREAD

**Issue by Lord-Ashura** [CMU-Perceptual-Computing-Lab/openpose#1542]
Hello, 

I have tried testing Openpose on Profile View Face Images, but openpose does not seem to be able to detect the facial keypoints, but for videos it is able to track the facial keypoints from a profile angle. 

Is it possible to get openpose to detect facial keypoints from the profile angle for images?
Any help would be greatly appreciate!

**Comment by gineshidalgo99** [comment]
Not sure of your exact images, but for best results, you need some part of the body to be visible too, then OpenPose is very good at profile faces. If only the face itself is shown, OpenPose might not work that well.
