### ISSUE TITLE
lunch demo error,please explain

### ISSUE THREAD

**Issue by newyun1979** [CMU-Perceptual-Computing-Lab/openpose#1544]
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F0331 12:19:51.826704  2652 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7f70088095cd  google::LogMessage::Fail()
    @     0x7f700880b433  google::LogMessage::SendToLog()
    @     0x7f700880915b  google::LogMessage::Flush()

**Comment by newyun1979** [comment]
sudo ./build/examples/openpose/openpose.bin --image_dir examples/media/ --face --hand

**Comment by gineshidalgo99** [comment]
Ban for not filling the template
