### ISSUE TITLE
How to use OpenPose as a Python library on Google Colab?

### ISSUE THREAD

**Issue by rachanagugale** [CMU-Perceptual-Computing-Lab/openpose#1545]
### Issue Summary
I need to extract the skeletal keypoints from images in a Python application and then feed them to a Keras Deep Neural Network. [Issue 1173](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1173) mentions something about using OpenPose in a .py file but does not mention how to do so.
The [GitHub Page](https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/examples/tutorial_api_python) of Python API tutorial also does not mention anything about the API functions available.

### Type of Issue
- Help wanted

### System Configuration
**OpenPose version**: Latest GitHub code.

**General configuration**: I am using Google Colab with GPU enabled.

**Comment by gineshidalgo99** [comment]
Check the tutorials for Python in https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/examples/tutorial_api_python
