### ISSUE TITLE
FPS difference between openpose demo executable and python API built

### ISSUE THREAD

**Issue by aditya15081990** [CMU-Perceptual-Computing-Lab/openpose#1547]
###Issue Summary
I am trying to run openpose body keypoints detections through python API using it's built version. The code is running fine without any error. But the FPS achieved using python code is low compared to FPS achieved using openpose demo executable. I am running both on the same video , the same OS ( windows 10) and the same GPU H/W ( GTX 1080 ti, 11 GB memory ). FPS using demo executable is ~24 FPS and using python code is ~17FPS. Is this an expected behavior?

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)
FPS using demo executable is ~24 FPS 
FPS using python code is ~17FPS

### Type of Issue
- Question

### Your System Configuration

2. **OpenPose version**: 
Latest

3. **General configuration**:

    - **Operating system version** (Windows 10)
    - **Release or Debug mode**? (by default: release):
    - Compiler ( VS2017 ENTERPRISE)

6. If **GPU mode** issue:
    - **CUDA version** (10.1)
    - **cuDNN version**(7.6.4)
    - **GPU model** (Nvidia GTX 1080 ti , 11 GB)

8. If **Python** API:
    - **Python version**:  (3.6)
    - **Numpy version** (1.17.5)

9. If **Windows** system:
    - Portable demo or compiled library? BOTH

10. If **speed performance** issue:
 FPS using demo executable is ~24 FPS 
FPS using python code is ~17FPS

**Comment by soulslicer** [comment]
Can you provide the exact commands run on both C++ and Python.

**Comment by aditya15081990** [comment]
Thanks for the reply. Sharing the commands below:

1. Command for portable demo executable:
**bin\OpenPoseDemo.exe --video path_to_my_video.mp4**

2. Python script:

import cv2
import argparse
import openpose.pyopenpose as op
import time

def run_detector(args):

    params = dict()
    params["model_folder"] = 'models/'

    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()
    datum = op.Datum()

    cap = cv2.VideoCapture(args['input_path'])

    start = time.time()
    frame_num = 0
    while True:
        ret,frame = cap.read()

        if frame is None:
            break

        datum.cvInputData = frame
        opWrapper.emplaceAndPop([datum])
        frame = datum.cvOutputData
         
        frame_num += 1

    optime = round(time.time()-start, 2)
    print("Open Pose Time: " + str(optime))
    print("FPS: " + str(round(frame_num/optime,2)))
    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_path", help="Input video file", type=str)
 
    args = parser.parse_args()
    run_detector(vars(args))

Command to run python script:
**python detector_cv2.py --input_path path_to_my_video.mp4**

**Comment by aditya15081990** [comment]
Thanks for the reply. Sharing the commands below:

1. Command for portable demo executable:
        **bin\OpenPoseDemo.exe --video path_to_my_video.mp4**

2. Python script:

`import cv2
import argparse
import openpose.pyopenpose as op
import time

def run_detector(args):

    params = dict()
    params["model_folder"] = args['op_model_folder']

    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()
    datum = op.Datum()

    cap = cv2.VideoCapture(args['input_path'])

    start = time.time()
    frame_num = 0
    while True:
        ret,frame = cap.read()

        if frame is None:
            break

        datum.cvInputData = frame
        opWrapper.emplaceAndPop([datum])
        frame = datum.cvOutputData
        
        # Display the resulting frame
        #cv2.imshow('frame', frame)
        #if cv2.waitKey(1) & 0xFF == ord('q'):
        #   break
         
        frame_num += 1

    optime = round(time.time()-start, 2)
    print("Open Pose Time: " + str(optime))
    print("FPS: " + str(round(frame_num/optime,2)))
    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_path", help="Input video file", type=str)
    parser.add_argument("--op_model_folder", help="OpenPose model folder", type=str, default="models/")

    args = parser.parse_args()
    run_detector(vars(args))`

Command to run python script:
        **python detector_cv2.py --input_path path_to_my_video.mp4**

**Comment by aditya15081990** [comment]
> Can you provide the exact commands run on both C++ and Python.

Thanks for the reply. Sharing the commands below:

1. Command for portable demo executable:
        **bin\OpenPoseDemo.exe --video path_to_my_video.mp4**

2. Python script:

`import cv2
import argparse
import openpose.pyopenpose as op
import time

def run_detector(args):

    params = dict()
    params["model_folder"] = 'models/'

    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()
    datum = op.Datum()

    cap = cv2.VideoCapture(args['input_path'])

    start = time.time()
    frame_num = 0
    while True:
        ret,frame = cap.read()

        if frame is None:
            break

        datum.cvInputData = frame
        opWrapper.emplaceAndPop([datum])
        frame = datum.cvOutputData
        
        frame_num += 1

    optime = round(time.time()-start, 2)
    print("Open Pose Time: " + str(optime))
    print("FPS: " + str(round(frame_num/optime,2)))
    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--input_path", help="Input video file", type=str)
    args = parser.parse_args()
    run_detector(vars(args))`

Command to run python script:
    **python detector_cv2.py --input_path path_to_my_video.mp4**

**Comment by soulslicer** [comment]
This is probably because using the C++ code directly, there is parallelism that occurs from one thread reading and processing the video, while another simultaneously consumes it. In Python however, everything happens in a single thread, resulting in it being slower

**Comment by moncio** [comment]
So understanding your reply @soulslicer , my question is, what do you recomend? should we use the C++ version if we want to obtain the higher FPS ratio (~24)? Is there any option to get this speed using python? Maybe using some kind of multiprocessing?

Thanks in advance.

**Comment by LukeSchoen** [comment]
If you intend on writting interlocked producer consumer multiprocessing systems in order to achieve increased performance, then for you its time to put the toys away and fully embrace c++
