### ISSUE TITLE
Check whether hands are optically visible even though keypoints for wrists exist

### ISSUE THREAD

**Issue by ruizcrp** [CMU-Perceptual-Computing-Lab/openpose#1548]
Hi, when hands are for example in the pockets, then the body algorithm detects the wrists anyway, which is the desired behavior I guess. The question for optically visible hands can be answered by running the "hand detector" as well: if the hand is not visible, the fingers are not found). But is there an easy way in openpose without running the computationally expensive "hand detector" algorithm (it slows down my performance by about factor 3)?

**Comment by gineshidalgo99** [comment]
No, I am afraid that is the only way with OpenPose, sorry!
