### ISSUE TITLE
How to release GPU memory after using OpenPose Python wrapper?

### ISSUE THREAD

**Issue by SirNightTW** [CMU-Perceptual-Computing-Lab/openpose#1551]
Hello, I want to use OpenPose to predict human body keypoints.
My OS is Windows 10, and GPU is Nvidia GTX1050Ti.
I've tried both Windows Portable Demo and OpenPose python wrapper(pyopenpose).
I use pyopenpose on jupyter notebook.
OpenPoseDemo.exe will release the GPU Memory after executing. whereas pyopenpose won't if I don't shutdown the notebook.
I wonder if there is any approach to release GPU memory without shutting down the .ipynb.
I've tried `opWrapper.stop()` but in vain.(Maybe I misunderstand what stop() does)
Thank you~

**Comment by soulslicer** [comment]
In this case the GPU memory is held by the model itself, loaded into memory. If you delete the wrapper, it should release the memory

**Comment by kilianbreathnach** [comment]
Is it necessary to delete everything? I am finding that the memory fills up after just a handful of frames have been processed. If I want to do tracking (such as with the `staf` branch on your fork @soulslicer), it will not be too useful if I need to reload the model every second or so. Is there anything I can do to get around this issue?
