### ISSUE TITLE
3D Keypoints Reconstruction from 2D Keypoints

### ISSUE THREAD

**Issue by tamasino52** [CMU-Perceptual-Computing-Lab/openpose#1552]
### Type of Issue
- Help wanted
- Question

### Question
I want to reconstruct 3D keypoints from 2D keypoints (more than 2), specially in python.
As far as I know, Python, which operates on Windows, does not support these features.
So I'm going to make a module myself in an algebraic way.
Can you tell me how they reconstructed it in 3D?
By any chance, is there an understandable explanation of the doc I couldn't find?

**Comment by delebash** [comment]
Would love this that way can easily display/import live motion in 3D apps such as Maya or any other.  Take a look at this project.  It works great but I want be able to convert on the fly with live stream.  And then export motion data to fbx.  https://github.com/nkeeline/OpenPose-to-Blender-Facial-Capture-Transfer
