### ISSUE TITLE
Has anyone tried running OpenPose on a Windows laptop with an eGPU?

### ISSUE THREAD

**Issue by Martinclayton** [CMU-Perceptual-Computing-Lab/openpose#1556]
Has anyone tried running OpenPose on a Windows laptop with an eGPU? It would be great to be able to run OpenPose on my laptop at home, but I do not have a compatible graphics card and cannot upgrade the GPU. If I add a CUDA Nvidia card through Thunderbolt 3 is this likely to work?

**Comment by jakebell36** [comment]
I was able to run openpose with an eGPU on windows through thunderbolt 3. It sped up openpose for me from about 0.1 fps to 14 fps.
