### ISSUE TITLE
Have anyone successfully installed and got the openpose results with NVIDIA QUADRO RTX 4000?  

### ISSUE THREAD

**Issue by Tahir-Rasheed-437** [CMU-Perceptual-Computing-Lab/openpose#1558]
Planning to use NVIDIA QUADRO RTX 4000 for my new project that uses openpose. It would great to know if anyone have successfully installed openpose on NVIDIA QUADRO RTX 4000.

**Comment by gineshidalgo99** [comment]
I can confirm Quadro RTX 8000 works fine on Windows, nothing special when installing it there.
