### ISSUE TITLE
Request about tracker documentation

### ISSUE THREAD

**Issue by arduinepo** [CMU-Perceptual-Computing-Lab/openpose#1559]
Hi,
I thank you very much for your excellent work. However, I endure difficulties understanding your code ; my Java and Python training explain it a bit, but I think it would be great for everyone if it was documented. I mean a short explanation of each - complex - function, its role and its algorithm. I would be especially interested in a documentation of the tracker.
I thank you very much in advance, and hope my request is not too bold.
Best wishes

**Comment by danielmimimi** [comment]
Hallo, I would also be interested in the documentation of the tracker. I Figured out how to activate it. But I have never seen a Id Property in the resulting object. Thanks for your Help.
