### ISSUE TITLE
Win10-VS2015 running OpenPoseDemo(pose-hand or pose-face) have some questions

### ISSUE THREAD

**Issue by luckynote** [CMU-Perceptual-Computing-Lab/openpose#156]
### Type of issue
You might select multiple topics, delete the rest:
- Execution error
- Question

My OpenPoseDemo-pose is able to be good running. However, while OpenPoseDemo-face or OpenPoseDemo-hand is set true, I meet this question.

![qq 20170720183352](https://user-images.githubusercontent.com/18484155/28414605-0c6bebee-6d7f-11e7-8404-1f3504760062.jpg)

After interrupting and debugging, I found this position have a question. But I do not how to solve it. 
![qq 20170720183431](https://user-images.githubusercontent.com/18484155/28414613-19398386-6d7f-11e7-88b2-dd8de24cf464.jpg)

I need your help!
Thanks!

### Your system configuration
**Operating system**: Windows10
**CUDA version** :8.0
**cuDNN version**:5.1
**GPU model** :Nvidia GeForce 950M (2GB)
**Caffe version**: Default from OpenPose.
**OpenCV version**: Default from OpenPose (Windows).
Generation mode: Visual Studio (Windows).

**Comment by gineshidalgo99** [comment]
Check the black console screen right after the error. It should print the real error. I'd say the error is out of memory, with only 2GB GPU you can only run body, or decrease Net resolution in order to add the other 2 (check that flag information of net resolution). Thanks!,

**Comment by luckynote** [comment]
![qq 20170720193652](https://user-images.githubusercontent.com/18484155/28415558-e84a4e14-6d82-11e7-8986-f638e47d2f13.jpg)
But, the  local variable show " the variable has been optimized and therefore unavailable".

**Comment by gineshidalgo99** [comment]
I'm sorry, with black console I meant the cmd command terminal which is open when OpenPose is started.

**Comment by luckynote** [comment]
I‘m sorry, I don't understand your see. Could you give me a detailed solution？Please! Thanks!

**Comment by luckynote** [comment]
Thank you very much! I have konwn this question. It's just my GPU too less based on https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#quick-start
FAQ. 

following FAQ-two:

1. Reduce the `--net_resolution` (e.g. to 320x176) (lower accuracy).
2. For face, reduce the `--face_net_resolution`. The resolution 320x320 usually works pretty decently.
3. Use the `MPI_4_layers` model (lower accuracy and lower number of parts).

I am sucess!

Thanks!

**Comment by gineshidalgo99** [comment]
Sorry for my late answer. Glad it is solved.

**Comment by RangerHuyijun** [comment]
Thanks for the answer,it helps a lot.Does anyone know how to adjust in order to apply only the body analysis funtion of Openpose?
