### ISSUE TITLE
COCO Body Format Does Not Match the COCO Dataset

### ISSUE THREAD

**Issue by nuzrub** [CMU-Perceptual-Computing-Lab/openpose#1560]
### Issue Summary
The COCO Format layout that can be found in the output.md does not seems to match the COCO skeleton layout seen in their website. Yours has an inverted V shape body while theirs has a rectangular one. Is this just a matter of drawing? 
I also count at most 17 keypoints in their images, while OpenPoses shows (and outputs) 18.
Am I doing anything wrong?
Here are the reference images:
![A](https://user-images.githubusercontent.com/4140686/79165322-3fbd1700-7db9-11ea-851a-2baa20d57882.png)
![B](https://user-images.githubusercontent.com/4140686/79165336-48ade880-7db9-11ea-91d7-7d397ac54367.png)

PS: I am aware Body25 skeletons are better. I am just doing a comparative study right now. 

### Type of Issue
- Question

### Your System Configuration
2. **OpenPose version**: Latest GitHub code. OpenPoseDemo.exe.

**Comment by gineshidalgo99** [comment]
Yes, it is a matter of drawing! The actual 17 keypoints are the same (only in a different ordering).

And also yes, there is 1 keypoint more, but it is just the interpolation between both shoulders (called "neck", but it is not really the neck). This is mostly for drawing too, so you can ignore it as well.

Let me know if something is still not clear!

**Comment by nuzrub** [comment]
This sums it up perfectly, thanks :)

**Comment by nuzrub** [comment]
Just one more thing, regarding MPI this time. The oficial website says there are 16 keypoints while OpenPose outputs 15. It seems to me that the "thorax" is missing. Why is that?

From MPII:
id - joint id (0 - r ankle, 1 - r knee, 2 - r hip, 3 - l hip, 4 - l knee, 5 - l ankle, 6 - pelvis, 7 - thorax, 8 - upper neck, 9 - head top, 10 - r wrist, 11 - r elbow, 12 - r shoulder, 13 - l shoulder, 14 - l elbow, 15 - l wrist)

**Comment by gineshidalgo99** [comment]
If I recall properly, I believe it was mentioned in their website but not labeled in their data (at least back in the day when OpenPose was trained with it)
