### ISSUE TITLE
[Ubuntu] "tutorial_api_thread" example prints unexpectedly empty pose keypoints

### ISSUE THREAD

**Issue by ryan-cha** [CMU-Perceptual-Computing-Lab/openpose#1561]
### Issue Summary

Hello, team!
I'm working on [2_thread_user_input_processing_output_and_datum.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_thread/2_thread_user_input_processing_output_and_datum.cpp#L170). 
I added exactly two lines, each logging filename and keypoint, similar to the following code.
```
op::opLog("keypoints = " +  datumsPtr->at(0)->poseKeypoints.toString());
```

However, **_the keypoints are always EMPTY_**. 
(You can browse my complete code, [here](https://gist.github.com/ryan-cha/29fb1486d014dbe8dd9eb6ed97bf2946).)

(Added: Confirmed this happens also for the [1_thread_user_processing_function.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_thread/1_thread_user_processing_function.cpp#L42).)

To make sure, I ran other tutorials including [examples/tutorial_api_cpp/04_keypoints_from_images.cpp](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/04_keypoints_from_images.cpp#L55). And they print keypoints fine, as expected. 

Please help me to figure out what went wrong. Thanks!

### Executed Command
```shell
./build/examples/tutorial_api_thread/2_thread_user_input_processing_output_and_datum.bin
```

### OpenPose Output
```shell
processing file examples/media/COCO_val2014_000000000569.jpg, 
       keypoints = Array<T>::toString():
processing file examples/media/COCO_val2014_000000000589.jpg, 
       keypoints = Array<T>::toString():
.....
```

### Errors
none

### Type of Issue
- Help wanted
- Question

### Your System Configuration
2. **OpenPose version**: 6b3652b

3. **General configuration**:
    - **Installation mode**: `Ubuntu/CMake`
    - **Operating system** : `Ubuntu 16.04.6 LTS (xenial)`
    - **Operating system version**: `Ubuntu 16.04`
    - **Release or Debug mode**: `Release`
    - **Compiler** : `gcc 5.4.0`

4. **Non-default settings**:
    - **3-D Reconstruction module added**? `no`
    - **Any other custom CMake configuration with respect to the default version**? `no`

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : `3.5.1`
    - **OpenCV version**: `compiled from source(3.4.9)`

6. If **GPU mode** issue:
    - **CUDA version** : `10.1.243`
    - **cuDNN version**: `7.6.5.32`
    - **GPU model** : `GeForce RTX 2080`

**Comment by gineshidalgo99** [comment]
If you plan to use the OpenPose keypoints, then tutorial_api_cpp is the place to go. If you are trying to do multi-threading for something else, then this thread tutorial is the way to go. Extracting keypoints was the example I added it back in the day (that might be obsolete and have some bug), but it is not meant to be used for that, but rather a multi thread example. Please, use the other tutorial for keypoints.

**Comment by ryan-cha** [comment]
I see. Thank you for your reply. I wish there were some comments about it in the code or the readme doc, though.

Actually, I really needed it working to process multiple input sources, concurrently.

Before I discovered the multithread examples, I tried creating multiple wrappers to handle multiple inputs concurrently, but it failed due to segmentation fault. 

So, in order to obtain keypoints from multiple input sources without sacrificing much of the speed, hosting multiple Openpose processes on each separate computer is the best bet?

Could you share some tips on running multiple wrappers from one process to achieve my goal?

Or should I run as many processes as required, each working with one wrapper?

**Comment by gineshidalgo99** [comment]
Sorry about that. Its [README](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_thread/README.md) actually specifies that "It is only meant for people interested in the multi-thread architecture without been interested in the OpenPose pose estimation algorithm."

I will try to make it even more specific and add it to each individual example, but yeah, this part is not meant for pose estimation at all.

For what you are saying, you want to implement something similar to the examples in here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/examples/tutorial_api_cpp

Maybe `13_asynchronous_custom_input_output_and_datum` or the synchronous versions (like `17_synchronous_custom_output.cpp`).

You could have multiple producers generating frames and adding them to the queue, modifying datum to have some id for each producer, so you can retrieve at the end. Something like that would be my guess.
