### ISSUE TITLE
Openpose not using/detecting webcam(windows)

### ISSUE THREAD

**Issue by laermanskoen** [CMU-Perceptual-Computing-Lab/openpose#1562]
### Issue
I first tested it on my laptop and it works with my webcam.
But now i can't run it on this laptop anymore so i cloned the project on another computer. There, it just won't use the webcam and i get no errors.
The windows camera app does detect the camera so it's not that it is not working.
I give webcam as parameter to openpose.
Why could this possibly be?
My first idea was add opencv as unity package again but didn't work.

### OpenPose Output (if any)
Doesn't use webcam

### Errors (if any)
None

### Type of Issue
- Help wanted

**Comment by Monsterisdrinkingwater** [comment]
I get this problems too.
