### ISSUE TITLE
[macOS] git apply patch fails - vecLib/caffe files not found?

### ISSUE THREAD

**Issue by rafayk7** [CMU-Perceptual-Computing-Lab/openpose#1563]
### Issue Summary
So I'm trying to compile OpenPose on the latest macOS Catalina 10.15.4, and ran into the following issues: 
1. CMake GUI Caffe error, which I fixed by applying @appleweed's solution in https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/423
2. Could Not find vecLib error (https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1248) when I ran the make command, which I tried to fix by attempting to apply the patch
3. This error, which occured when I attempted to apply the patch. I followed the instructions under https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#mac-osx-version to apply the patch, however I got the error below.

I tried to manually define the path to vecLib.h in `build/caffe/src/openpose_lib-build/CMakeCache.txt`, however this did not seem to help.

### Executed Command (if any)
`cd 3rdparty/caffe`
`git apply ../../scripts/osx/mac_opencl_patch.txt`

### Errors (if any)

`error: patch failed: cmake/Modules/FindvecLib.cmake:12`
`error: cmake/Modules/FindvecLib.cmake: patch does not apply`
`error: src/caffe/layers/malis_loss_layer.cpp: No such file or directory`

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/1gMiW0fh

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)? Latest

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...? CMake GUI
    - **Operating system** (`lsb_release -a` in Ubuntu): macOS Catalina 10.15.4
    - **Release or Debug mode**? (by default: release): Release

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): No
    - Any other custom CMake configuration with respect to the default version? (by default: no): No

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? cloned from `https://github.com/CMU-Perceptual-Computing-Lab/caffe.git` as per the solution from https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/423
    - **CMake version** (`cmake --version` in Ubuntu): 3.17.1

**Comment by JasonConrad** [comment]
Any progress on this?  I'm having the same issue.

**Comment by rafayk7** [comment]
@JasonConrad Follow the solutions mentioned here https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1248#issuecomment-616408963. 

Seemed to work for me
