### ISSUE TITLE
Demo counts people but not display skeleton

### ISSUE THREAD

**Issue by Haeryangkim** [CMU-Perceptual-Computing-Lab/openpose#1564]
I tested some features of openpose and successfully run the demo which is in the document and tried with other videos that I used. It was also successfully tested.

But when I test with 40+ people video, it counts people but not draw the skeleton. 

Here is screencaputure.
I run with this command line input

`./build/examples/openpose/openpose.bin --video examples/media/27.mp4 
`

![bug](https://user-images.githubusercontent.com/17171195/79824745-f3ce2b80-83d1-11ea-9431-82af2fca82b3.png)
![bug2](https://user-images.githubusercontent.com/17171195/79824800-17917180-83d2-11ea-887e-0a6c9bd4d5de.png)

**Comment by gineshidalgo99** [comment]
Could you share the mp4 video so i can test it out myself? Thanks!

**Comment by Haeryangkim** [comment]
Leaving a goggle drive link of the video file.

https://drive.google.com/file/d/1jmEVJBkyAUFsW4m7R_0T0X1ib_6M092V/view?usp=sharing

Thanks.

**Comment by gineshidalgo99** [comment]
Thanks for the video, it helped me a lot debugging the issue, fixed in the latest version! Let me know if you face any issues!

Details: In order to see the bug, it had to be an image with a lot of people but also a big image (e.g., ~32 people on a 4k image). This bug is actually ~2 years old, it seems nobody tried 4k videos with >30 people before :)

**Comment by Haeryangkim** [comment]
Not Actually, the video I gave you was originally not 4k. Which also not worked with previous version.
Leaving a version of
 low resolution video link
https://drive.google.com/file/d/1ha8EVvitdL7swl9kiMxwf-nQuiMGOym9/view?usp=sharing

It is also work with the latest version but the accuracy is not good as 4k version.

![3](https://user-images.githubusercontent.com/17171195/80447114-7e270a00-8953-11ea-81e1-95d592282819.png)

**Comment by gineshidalgo99** [comment]
That is the expected accuracy, there is too many close-by people, so when OpenPose resizes the image to 368 pixel width (default to maintain real time speed), the distance between people is very small. And I also resized the 4k video to 1k to test them both, they work the same way.

If you need higher accuracy, you can try increasing the `--net_resoulution` and other accuracy flags following the max accuracy setting explained in the doc.
