### ISSUE TITLE
Models are not available at URL http://posefs1.perception.cs.cmu.edu

### ISSUE THREAD

**Issue by daniel347x** [CMU-Perceptual-Computing-Lab/openpose#1567]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary

**Attempting to access one of the models at its URL reveals that the URL is down:

http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel

The build process fails when the URL is not accessible.

...the same is true for other models I attempted to download.

Hopefully, the server is just temporarily down - but in case nobody is aware and the problem remains, I am posting this issue.**

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

**Attempt to access the model at the noted URL.  As of the time I write this issue, there is a "Sorry, the page you are looking for is not found" error.**

### Errors (if any)

**The URL with the models is inaccessible.**

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

**Installation error.**

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by brothersoo** [comment]
So is it right that we can't access or download any of the models until they repair the server?
Thank you for the information! I was in such a panic due to the model http response errors.

**Comment by daniel347x** [comment]
I have 3 of the models on my Dropbox account (for the pose runs).  Feel free to download.

# pose_iter_584000.caffemodel
https://www.dropbox.com/s/3x0xambj2rkyrap/pose_iter_584000.caffemodel?dl=0

# pose_iter_116000.caffemodel
https://www.dropbox.com/s/d08srojpvwnk252/pose_iter_116000.caffemodel?dl=0

# pose_iter_102000.caffemodel
https://www.dropbox.com/s/gqgsme6sgoo0zxf/pose_iter_102000.caffemodel?dl=0


In case you need other models, unfortunately I don't have those.


Also, to get OpenPose to build (assuming the models above are sufficient), you need to edit out the automated attempt to download these scripts.  The following script does it - it is taken from a Dockerfile (remove the RUN command if executing directly at the command line, and replace the path to the OpenPose directory with your own):

```
RUN    cd /home/${USERNAME}/openpose/models/pose/body_25 \
    && wget -c https://www.dropbox.com/s/3x0xambj2rkyrap/pose_iter_584000.caffemodel?dl=0
# pose_iter_116000.caffemodel
RUN    cd /home/${USERNAME}/openpose/models/face \
    && wget -c https://www.dropbox.com/s/d08srojpvwnk252/pose_iter_116000.caffemodel?dl=0
# pose_iter_102000.caffemodel
RUN    cd /home/${USERNAME}/openpose/models/hand \
    && wget -c https://www.dropbox.com/s/gqgsme6sgoo0zxf/pose_iter_102000.caffemodel?dl=0

# use 'sed' to comment out the line in the OpenPose repo that downloads the model from the failed link
RUN sed -i 's/executeShInItsFolder "getModels.sh"/# executeShInItsFolder "getModels.sh"/g' /home/${USERNAME}/openpose/scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.1.sh
RUN sed -i 's/executeShInItsFolder "getModels.sh"/# executeShInItsFolder "getModels.sh"/g' /home/${USERNAME}/openpose/scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh
RUN sed -i 's/download_model("BODY_25"/# download_model("BODY_25"/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/78287B57CF85FA89C03F1393D368E5B7/# 78287B57CF85FA89C03F1393D368E5B7/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/download_model("body (COCO)"/# download_model("body (COCO)"/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/5156d31f670511fce9b4e28b403f2939/# 5156d31f670511fce9b4e28b403f2939/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/download_model("body (MPI)"/# download_model("body (MPI)"/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/2ca0990c7562bd7ae03f3f54afa96e00/# 2ca0990c7562bd7ae03f3f54afa96e00/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/download_model("face"/# download_model("face"/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/e747180d728fa4e4418c465828384333/# e747180d728fa4e4418c465828384333/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/download_model("hand"/# download_model("hand"/g' /home/${USERNAME}/openpose/CMakeLists.txt
RUN sed -i 's/a82cfc3fea7c62f159e11bd3674c1531/# a82cfc3fea7c62f159e11bd3674c1531/g' /home/${USERNAME}/openpose/CMakeLists.txt
```

**Comment by gineshidalgo99** [comment]
Working again, sorry for the troubles!!!

**Comment by ianni67** [comment]
I'm getting the same error right now...

**Comment by sfatjo** [comment]
It seems like the host website (http://posefs1.perception.cs.cmu.edu/) is down again... Error 502 Bad Gateway!!!

**Comment by ncblair** [comment]
Seems like the (http://posefs1.perception.cs.cmu.edu/) website is down again

**Comment by cheapskatecoder** [comment]
I found the models uploaded on kaggle, here's the link 

https://www.kaggle.com/changethetuneman/openpose-model

**Comment by cheapskatecoder** [comment]
> I have 3 of the models on my Dropbox account (for the pose runs). Feel free to download.
> # pose_iter_584000.caffemodel
> 
> https://www.dropbox.com/s/3x0xambj2rkyrap/pose_iter_584000.caffemodel?dl=0
> # pose_iter_116000.caffemodel
> 
> https://www.dropbox.com/s/d08srojpvwnk252/pose_iter_116000.caffemodel?dl=0
> # pose_iter_102000.caffemodel
> 
> https://www.dropbox.com/s/gqgsme6sgoo0zxf/pose_iter_102000.caffemodel?dl=0
> 
> In case you need other models, unfortunately I don't have those.
> 
> Also, to get OpenPose to build (assuming the models above are sufficient), you need to edit out the automated attempt to download these scripts. The following script does it - it is taken from a Dockerfile (remove the RUN command if executing directly at the command line, and replace the path to the OpenPose directory with your own):
> 
> ```
> RUN    cd /home/${USERNAME}/openpose/models/pose/body_25 \
>     && wget -c https://www.dropbox.com/s/3x0xambj2rkyrap/pose_iter_584000.caffemodel?dl=0
> # pose_iter_116000.caffemodel
> RUN    cd /home/${USERNAME}/openpose/models/face \
>     && wget -c https://www.dropbox.com/s/d08srojpvwnk252/pose_iter_116000.caffemodel?dl=0
> # pose_iter_102000.caffemodel
> RUN    cd /home/${USERNAME}/openpose/models/hand \
>     && wget -c https://www.dropbox.com/s/gqgsme6sgoo0zxf/pose_iter_102000.caffemodel?dl=0
> 
> # use 'sed' to comment out the line in the OpenPose repo that downloads the model from the failed link
> RUN sed -i 's/executeShInItsFolder "getModels.sh"/# executeShInItsFolder "getModels.sh"/g' /home/${USERNAME}/openpose/scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.1.sh
> RUN sed -i 's/executeShInItsFolder "getModels.sh"/# executeShInItsFolder "getModels.sh"/g' /home/${USERNAME}/openpose/scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh
> RUN sed -i 's/download_model("BODY_25"/# download_model("BODY_25"/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/78287B57CF85FA89C03F1393D368E5B7/# 78287B57CF85FA89C03F1393D368E5B7/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/download_model("body (COCO)"/# download_model("body (COCO)"/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/5156d31f670511fce9b4e28b403f2939/# 5156d31f670511fce9b4e28b403f2939/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/download_model("body (MPI)"/# download_model("body (MPI)"/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/2ca0990c7562bd7ae03f3f54afa96e00/# 2ca0990c7562bd7ae03f3f54afa96e00/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/download_model("face"/# download_model("face"/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/e747180d728fa4e4418c465828384333/# e747180d728fa4e4418c465828384333/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/download_model("hand"/# download_model("hand"/g' /home/${USERNAME}/openpose/CMakeLists.txt
> RUN sed -i 's/a82cfc3fea7c62f159e11bd3674c1531/# a82cfc3fea7c62f159e11bd3674c1531/g' /home/${USERNAME}/openpose/CMakeLists.txt
> ```

For someone who's still looking for the models, here's the link 

https://www.kaggle.com/changethetuneman/openpose-model

Thank you kaggle

**Comment by gineshidalgo99** [comment]
Please use https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411

**Comment by gamingflexer** [comment]
It is down again, Please put it up again !

**Comment by alvaro-budria** [comment]
> It is down again, Please put it up again !

It is still, down. Please, help!

**Comment by andy40018** [comment]
It is still, down. Please, help!

**Comment by alvaro-budria** [comment]
@andy40018  @gamingflexer @gineshidalgo99 I put up a small Colab that downloads the models and successfully installs OpenPose (working as of August 2023): https://colab.research.google.com/drive/1m0DU-vjjTNWrXMEMqJptQHyp3SXUGbmf?usp=sharing

**Comment by liendong123** [comment]
me too from china

**Comment by 14790897** [comment]
> @andy40018 @gamingflexer @gineshidalgo99 I put up a small Colab that downloads the models and successfully installs OpenPose (working as of August 2023): https://colab.research.google.com/drive/1m0DU-vjjTNWrXMEMqJptQHyp3SXUGbmf?usp=sharing

do we need upload the Models？
Error:
Caffe trained model file not found: models/pose/body_25/pose_iter_584000.caffemodel.

**Comment by 14790897** [comment]
> Who can help me download the models?

https://drive.google.com/file/d/1QCSxJZpnWvM00hx49CJ2zky7PWGzpcEh/edit
Try this link.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411

**Comment by zhengzhw2023** [comment]
> 我建立了一个小型 Colab，用于下载模型并成功安装 OpenPose（截至 2023 年 8 月）：https://colab.research.google.com/drive/1m0DU-vjjTNWrXMEMqJptQHyp3SXUGbmf?usp=sharing
![image](https://github.com/CMU-Perceptual-Computing-Lab/openpose/assets/150008829/17e10e42-45cb-4aa1-b0d7-ee7d796a93e3)
I encountered this error when running your program. How should I handle it?

**Comment by jaumesaa** [comment]
![image](https://github.com/user-attachments/assets/13b578ee-e3c8-45b5-a083-fdc30596dcb0)

**Comment by toprakfirat** [comment]
models are dead
