### ISSUE TITLE
[Ubuntu]cannot import name 'pyopenpose'---in Colab

### ISSUE THREAD

**Issue by weichen96** [CMU-Perceptual-Computing-Lab/openpose#1568]
After the installation of Openpose in Colab, I tested the tutorial_api_python with the code of `!python 01_body_from_image.py`. And it worked normally. But when I imported pyopenpose in the cell of Collab and there was an error of "cannot import name 'pyopenpose'". My detailed code is as follow:

```
import sys
dir_path = '/content/openpose/build/examples/tutorial_api_python'
from openpose import pyopenpose as op
```
So I don't know why it happened.

**Comment by orsveri** [comment]
Hi! Did you set the path for openpose?
In examples there are following lines:
```
sys.path.append('../../python')
from openpose import pyopenpose as op
```
So in your case, you should do something like that:
```
pyopenpose_dir = '/content/openpose/build/python'
sys.path.append(pyopenpose_dir)
from openpose import pyopenpose as op
```
Also, I had such problem because of the version of python - with python 3.7 in conda it didn't work, but with python 3.6 everything is ok!
