### ISSUE TITLE
Foot Keypoint Annotations links are broken

### ISSUE THREAD

**Issue by m-nez** [CMU-Perceptual-Computing-Lab/openpose#1569]
Foot Keypoint Annotations links on the https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/ are broken.
http://posefs1.perception.cs.cmu.edu/OpenPose/datasets/foot/person_keypoints_train2017_foot_v1.zip
http://posefs1.perception.cs.cmu.edu/OpenPose/datasets/foot/person_keypoints_val2017_foot_v1.zip

There currently is no way to download foot annotations.

**Comment by gineshidalgo99** [comment]
Working again, sorry for the troubles!!!

**Comment by ConnorLoP** [comment]
Looks like these links are broken again. 
In fact all of the links in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md under **5. Caffe, OpenCV, and Caffe prerequisites:**
seem to be broken.

**Comment by gineshidalgo99** [comment]
Everything is back to normal now. Lots of issues getting the servers to work when we are not allowed to physically enter that room due to COVID. Sorry!

**Comment by MFredX** [comment]
Hi,
The links in [](`https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md`) are down again

**Comment by gineshidalgo99** [comment]
Working again, sorry!

**Comment by ZimM-LostPolygon** [comment]
And broken again.

**Comment by gineshidalgo99** [comment]
And working again! :)
