### ISSUE TITLE
Must I have an Nvidia GPU and install CUDA?I only have intel(R)  UHD Graphics 630

### ISSUE THREAD

**Issue by cqhblg** [CMU-Perceptual-Computing-Lab/openpose#1571]
![image](https://user-images.githubusercontent.com/29913470/80441787-35188b00-893e-11ea-891e-1dcc4ab87af0.png)

**Comment by gineshidalgo99** [comment]
With that machine, you can only use the slow CPU version. Otherwise, if you want real time frame rate, you need an Nvidia GPU.
