### ISSUE TITLE
ubuntu18.04 build caffe problem"project files may be invalid,caffe not found"

### ISSUE THREAD

**Issue by poincarelee** [CMU-Perceptual-Computing-Lab/openpose#1573]
I am installing openpose acccording to the installtion instruction, while as I use cmake-gui configure the CAFFE_INCLUDE_PATH and LIB_PATH, after I input the correct path in the GUI  and configure, a error occurs: " project files may be invalid, caffe not found, please turn on BUILD_CAFFE or fill in the CAFFE_INCLUDE_PATH and LIB_PATH",  and I also retry it in comand cmake as "DCaffe_INCLUDE_PATH",
however, the same error occurs again.
Could you tell me how to solve this problem? Many thanks.

**Comment by yosagaf** [comment]
Have the same issue @poincarelee how did you resolve this.

**Comment by dmg206** [comment]
I have the same issue too

**Comment by poincarelee** [comment]
I re-downloaded the openpose source code and compiled again and the problem disappears. Finally found out something is wrong with the CMakelists.txt. Maybe  you can replace the old .txt with  the latest one and this will help solve the problem.

**Comment by Ojperdomoc** [comment]
I had the same problem in Google Colab, when I run the line:

!cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. && make -jnproc``

CMake Error at cmake/Utils.cmake:8 (file):
file DOWNLOAD HASH mismatch

for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
  expected hash: [78287b57cf85fa89c03f1393d368e5b7]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
         status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
CMakeLists.txt:993 (download_model)

-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
file DOWNLOAD HASH mismatch

for file: [/content/openpose/models/face/pose_iter_116000.caffemodel]
  expected hash: [e747180d728fa4e4418c465828384333]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
         status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
CMakeLists.txt:999 (download_model)

-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
file DOWNLOAD HASH mismatch

for file: [/content/openpose/models/hand/pose_iter_102000.caffemodel]
  expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
         status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
CMakeLists.txt:1001 (download_model)

-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/content/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/content/openpose/build/CMakeFiles/CMakeError.log".

But this line was working 1 month ago... Do you have some advice for this issue?

Thanks!

**Comment by mdmorar** [comment]
Having the same issue as above when I clone the latest master or the newest tag 1.6. I get exactly the same error which was not happening 1 month ago?

If this is a cmake issue, then please let us know what we can do to get it going for now?

**Comment by jessemyers** [comment]
I have the same issue, suspect that the hosting for these models is not reliable. They currently are downloaded as zero byte files.
