### ISSUE TITLE
Where is the build folder located on ubuntu?

### ISSUE THREAD

**Issue by delebash** [CMU-Perceptual-Computing-Lab/openpose#1574]
The quick start for ubuntu states to run ./build/examples/openpose/openpose.bin --video examples/media/video.avi.  I do not see a .build folder even using ls-a.

**Comment by Wedmal** [comment]
You must first assemble and install. Install all necessary components.
Such as openCV, python, Protobuf, and much more.
- mkdir ./build
- cd ./build
- cmake3 ../
итд...

**Comment by delebash** [comment]
Thanks
