### ISSUE TITLE
Incorrect documentation when using pre-built Caffe

### ISSUE THREAD

**Issue by heisters** [CMU-Perceptual-Computing-Lab/openpose#1575]
### Issue Summary

Documentation and error messages are misleading when using a release version of Caffe on Ubuntu.

### Executed Command (if any)

`cmake .. -DBUILD_CAFFE=OFF -DCaffe_INCLUDE_DIRS=/usr/include/caffe -DCaffe_LIBS=/usr/lib/x86_64-linux-gnu/libcaffe.so`

### OpenPose Output (if any)

```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "10.1")
-- Building with CUDA.
-- CUDA detected: 10.1
-- Found cuDNN: ver. 7.6.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_75
-- Found cuDNN: ver. 7.6.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found GFlags: /usr/include
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0")
-- Found OpenCV: /usr (found version "3.2.0")
CMake Error at CMakeLists.txt:839 (message):
  Caffe not found.  Either turn on the BUILD_CAFFE option or specify the path
  of Caffe includes

          and libs using -DCaffe_INCLUDE_DIRS and -DCaffe_LIBS.


-- Configuring incomplete, errors occurred!
See also "/home/ian/sw/src/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/ian/sw/src/openpose/build/CMakeFiles/CMakeError.log".
```

### Errors (if any)

```
Caffe not found.  Either turn on the BUILD_CAFFE option or specify the path
  of Caffe includes

          and libs using -DCaffe_INCLUDE_DIRS and -DCaffe_LIBS.
```

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** see above

2. **OpenPose version**: 3915b92

3. **General configuration**:
    - **Installation mode**: cmake
    - **Operating system** Ubuntu 18.04.4 LTS
    - **Operating system version** Ubuntu 18
    - **Release or Debug mode**? release
    - **Compiler** gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? (by default: no): `-DBUILD_CAFFE=OFF -DCaffe_INCLUDE_DIRS=/usr/include/caffe -DCaffe_LIBS=/usr/lib/x86_64-linux-gnu/libcaffe.so`

5. **3rd-party software**:
    - **Caffe version**: release of libcaffe-cuda-dev installed from apt: 1.0.0-6build1
    - **CMake version** : 3.10.2
    - **OpenCV version**: release of libopencv-dev installed from apt: 3.2.0+dfsg-4ubuntu0.1

6. If **GPU mode** issue:
    - **CUDA version**: 10.1
    - **cuDNN version**: 7.6.5
    - **GPU model** (`nvidia-smi` in Ubuntu): RTX 2080

--

Documentation [here (albeit for Mac version)](/doc/installation.md) and the CMake output generated [here](/CMakeLists.txt#L839) both say to set `Caffe_LIBS` if not building Caffe from source. However, [CMake uses](/CMakeLists.txt#L703) `Caffe_LIBS_RELEASE`

**Comment by Rajrup** [comment]
I am facing the same issue!

**Comment by juanmaceg** [comment]
Me too

**Comment by bnascimento** [comment]
same

**Comment by mattkrae34** [comment]
It's a documentation issue: so just use -DCaffe_LIBS_RELEASE=/wherever/libcaffe.so instead of -D Caffe_LIBS=

The documentation & cmake config should still be sync'ed

**Comment by frankier** [comment]
For what it's worth, I found it only worked if I set Caffe_LIBS_RELEASE **and** Caffe_LIBS
