### ISSUE TITLE
VIdeo and Image inputs are not able to run the demo on Ubuntu

### ISSUE THREAD

**Issue by siqinli** [CMU-Perceptual-Computing-Lab/openpose#158]
when I run the demo command 

`./build/examples/openpose/openpose.bin --video examples/media/video.avi`

it came out the error:

Coming from:
- src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():73
- src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():85
- src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():133
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Selected simultaneously video and webcam. Please, select only one.'

Running on image has the same problem

**Comment by gineshidalgo99** [comment]
I fixed it a few minutes after I introduced the bug, unfortunately you downloaded it in that moment. Please download the last version. Thanks!
