### ISSUE TITLE
Openpose 1.6.0 Windows Demo frame_rotate limitation/bug?

### ISSUE THREAD

**Issue by crnkoj** [CMU-Perceptual-Computing-Lab/openpose#1586]
Hi,
tried the Windows OpenPose demo 1.6.0 on a windows 10 machine with ryzen 3900x and nvidia rtx 2070. Recent Drivers for chipset and gfx.
The demo works on the provided examples and on my own videos. 
I however have certain videos that are 90 degrees rotated to the right so wanted to use the 
--frame_rotate 270 command to rotate it correctly, but it gives the following error:
"Expected vs. received sizes: 1080x1920 vs. 1920x1080 in D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\producer\producer.cpp:op::Producer::checkFrameIntegrity():305"
Is there something i missed in the documentation, is it a limitation or a bug
Using the --frame_rotate 180 works with 180 degrees rotate video
Thanks

**Comment by gineshidalgo99** [comment]
Sorry, that was a bug fixed in the latest commit for 90 and 270 degree rotations. Let me know if you see any error then.

I will also try to push an official version (1.6.1) that fixes this within the next 2-3 weeks.
