### ISSUE TITLE
How to filter bad pose results in openpose?

### ISSUE THREAD

**Issue by OOF-dura** [CMU-Perceptual-Computing-Lab/openpose#1587]
I have a data set in which the main character (the same size in each image) and the background are basically the same. The character is directly pasted to the background. I am using Openpose to detect joint points. 
Actually, I only want one person's joint position——the main character. Unfortunately, there are also people in the background, which will cause bad results for Openpose. 

I don’t know if there is an efficient way to filter them out? (Currently, I am using the size of skeleton to filter)
![image](https://user-images.githubusercontent.com/22954901/82072946-10c4f880-970b-11ea-9357-9a423c473d58.png)
(please pay attention to the arrow.)

For usage of Openpose, I am using openpose in python: (Code is like this)
```
        datum = op.Datum()
        imageToProcess = cv2.imread(imagePath)
        print("processing... ",imagePath)
        datum.cvInputData = imageToProcess
        opWrapper.emplaceAndPop([datum])
        j_data = {}
        j_data['version'] = 1.3
        j_inner_data = {}
        j_inner_data['person_id'] = [-1]
        j_inner_data['pose_keypoints_2d'] = datum.poseKeypoints.flatten().tolist()
        j_inner_data['face_keypoints_2d'] = []
        j_inner_data['hand_left_keypoints_2d'] = []
        j_inner_data['hand_right_keypoints_2d'] = []
        j_inner_data['pose_keypoints_3d'] = []
        j_inner_data['face_keypoints_3d'] = []
        j_inner_data['hand_left_keypoints_3d'] = []
        j_inner_data['hand_right_keypoints_3d'] = []
        j_data['people'] = [j_inner_data]
        write_json(base_path+new_name,j_data)


```

  [1]: https://i.stack.imgur.com/Wk309.png

**Comment by Avashist1998** [comment]
One can just analyze the reliability scoring of the joints and use that as a metric instead of skeleton size. This is not a full-proof method, but I believe that a larger individual should have key points with a higher average reliability score than of the people in the background.
