### ISSUE TITLE
Colab Openpose not working 

### ISSUE THREAD

**Issue by Avashist1998** [CMU-Perceptual-Computing-Lab/openpose#1588]
I am using google colab to run openpose for a  project, and few day back I am having trouble install openpose in the colab notebook. In the past the notebook/Script has worked perfectly. 

**This is the reference notebook to be used**

https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/OpenPose.ipynb#scrollTo=kDDkgCCSrFTv

The notebook has GPU enabled.The issue is regarding cafe installation. I believe there has been some change made to the installation process, and for this reason the script is not longer working.

Any help regrading the installation process would be appreciated. 

**The Output log**

[CMakeOutput.log](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/4639431/CMakeOutput.log)

**The Error log**

[CMakeError.log](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/4639432/CMakeError.log)

**Comment by Ojperdomoc** [comment]
I had the same problem in Google Colab, when I run the line:

!cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. && make -jnproc``

CMake Error at cmake/Utils.cmake:8 (file):
file DOWNLOAD HASH mismatch

for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
  expected hash: [78287b57cf85fa89c03f1393d368e5b7]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
         status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
CMakeLists.txt:993 (download_model)

-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
file DOWNLOAD HASH mismatch

for file: [/content/openpose/models/face/pose_iter_116000.caffemodel]
  expected hash: [e747180d728fa4e4418c465828384333]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
         status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
CMakeLists.txt:999 (download_model)

-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
file DOWNLOAD HASH mismatch

for file: [/content/openpose/models/hand/pose_iter_102000.caffemodel]
  expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
         status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
CMakeLists.txt:1001 (download_model)

-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/content/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/content/openpose/build/CMakeFiles/CMakeError.log".

But this line was working 1 month ago... Do you have some advice for this issue?

Thanks!

**Comment by dpschool-raveekiat** [comment]
I also run into the same problem.

It occurs because the expected hash is mismatched between the CMakeLists.txt and the actual file download from http://posefs1.perception.cs.cmu.edu/OpenPose/models/

The quick fix can be replacing the hash for BODY_25, Face and Hand in CMakeLists.txt (line 990 to 1004)

For instances,

```
download_model("BODY_25" ${DOWNLOAD_BODY_25_MODEL} pose/body_25/pose_iter_584000.caffemodel
  d41d8cd98f00b204e9800998ecf8427e) # Body (BODY_25)

download_model("face" ${DOWNLOAD_FACE_MODEL} face/pose_iter_116000.caffemodel
  d41d8cd98f00b204e9800998ecf8427e) # Face

download_model("hand" ${DOWNLOAD_HAND_MODEL} hand/pose_iter_102000.caffemodel
  d41d8cd98f00b204e9800998ecf8427e) # Hand
```

Rerun the build command. It should at least solve the error that we are facing. 

Cheers

**Comment by Ojperdomoc** [comment]
Hi,

The code is running but it is not detecting any person in video. 
I tried with two differente ways, but the results is empty json files without any person detected!

!cd openpose && ./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json ./output/ --display 0 --write_video ../openpose.avi

!cd openpose && ./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_json ./output/ --display 0 --write_video ../openpose.avi --face --hand

**Comment by Avashist1998** [comment]
This does not solve the problem, because no key points are generated. I created a sample notebook for testing. 

https://colab.research.google.com/drive/1hnNgcUs3AFPafwrCiXeHhRBMW3Rlsk64?usp=sharing

**Comment by dpschool-raveekiat** [comment]
I just realized that at the first quick-fix solution does not really solve the root cause, all of those hashes are the same. It should be different.

The problem is actually about downloading those models and their weight. By running 

`openpose/models/getModels.sh` 

I received **ERROR 502: Bad Gateway.**
This is related to one of the recent close issues #1576 

If you have models and the weight available locally or from a mirror, it can be upload and replace the empty file under openpose/models/... in Colab. Otherwise, you have to wait until the file storage is up and running again.

I cannot verify it since I do not have those files stored locally.

 I hope this helps

**Comment by brickee** [comment]
I meet the same problem today. Any solution yet?

**Comment by brickee** [comment]
This method works! I just tried! Just run the "make" command again and upload the models to openpose/models/... 

> I just realized that at the first quick-fix solution does not really solve the root cause, all of those hashes are the same. It should be different.
> 
> The problem is actually about downloading those models and their weight. By running
> 
> `openpose/models/getModels.sh`
> 
> I received **ERROR 502: Bad Gateway.**
> This is related to one of the recent close issues #1576
> 
> If you have models and the weight available locally or from a mirror, it can be upload and replace the empty file under openpose/models/... in Colab. Otherwise, you have to wait until the file storage is up and running again.
> 
> I cannot verify it since I do not have those files stored locally.
> 
> I hope this helps

**Comment by AchrafSaddiki** [comment]
> This method works! I just tried! Just run the "make" command again and upload the models to openpose/models/...
> 
> > I just realized that at the first quick-fix solution does not really solve the root cause, all of those hashes are the same. It should be different.
> > The problem is actually about downloading those models and their weight. By running
> > `openpose/models/getModels.sh`
> > I received **ERROR 502: Bad Gateway.**
> > This is related to one of the recent close issues #1576
> > If you have models and the weight available locally or from a mirror, it can be upload and replace the empty file under openpose/models/... in Colab. Otherwise, you have to wait until the file storage is up and running again.
> > I cannot verify it since I do not have those files stored locally.
> > I hope this helps

Can you please provide us with the files you uploaded ?

**Comment by brickee** [comment]
> > This method works! I just tried! Just run the "make" command again and upload the models to openpose/models/...
> > > I just realized that at the first quick-fix solution does not really solve the root cause, all of those hashes are the same. It should be different.
> > > The problem is actually about downloading those models and their weight. By running
> > > `openpose/models/getModels.sh`
> > > I received **ERROR 502: Bad Gateway.**
> > > This is related to one of the recent close issues #1576
> > > If you have models and the weight available locally or from a mirror, it can be upload and replace the empty file under openpose/models/... in Colab. Otherwise, you have to wait until the file storage is up and running again.
> > > I cannot verify it since I do not have those files stored locally.
> > > I hope this helps
> 
> Can you please provide us with the files you uploaded ?

There you go! https://www.kaggle.com/changethetuneman/openpose-model?select=pose_iter_584000.caffemodel

**Comment by kruthikakr** [comment]
> This does not solve the problem, because no key points are generated. I created a sample notebook for testing.
> 
> https://colab.research.google.com/drive/1hnNgcUs3AFPafwrCiXeHhRBMW3Rlsk64?usp=sharing

I am getting same error.. Is this issue solved can be solved without uploading the models .. I am on co lab platform

**Comment by ryegunde** [comment]
> > > This method works! I just tried! Just run the "make" command again and upload the models to openpose/models/...
> > > > I just realized that at the first quick-fix solution does not really solve the root cause, all of those hashes are the same. It should be different.
> > > > The problem is actually about downloading those models and their weight. By running
> > > > `openpose/models/getModels.sh`
> > > > I received **ERROR 502: Bad Gateway.**
> > > > This is related to one of the recent close issues #1576
> > > > If you have models and the weight available locally or from a mirror, it can be upload and replace the empty file under openpose/models/... in Colab. Otherwise, you have to wait until the file storage is up and running again.
> > > > I cannot verify it since I do not have those files stored locally.
> > > > I hope this helps
> > 
> > 
> > Can you please provide us with the files you uploaded ?
> 
> There you go! https://www.kaggle.com/changethetuneman/openpose-model?select=pose_iter_584000.caffemodel

Looks like the link is broken, can you upload again please?
