### ISSUE TITLE
Body25 model dataset

### ISSUE THREAD

**Issue by sebo361** [CMU-Perceptual-Computing-Lab/openpose#1589]
Hi there,

i am wondering on which dataset the pretrained body25 model was trained on? MPII dataset does not include 25 keypoints, so which dataset has been used for training the body25 model?

**Comment by Raven888888** [comment]
+1
Require this :)

**Comment by gineshidalgo99** [comment]
COCO and MPI combined. CHeck the paper for details.

**Comment by OlaFaseru** [comment]
How can I get the caffemodel for body25 pls. Thanks

**Comment by Raven888888** [comment]
@OlaFaseru you may get it from https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/blob/master/experimental_models/README.md
