### ISSUE TITLE
Will the 3D reconstruction demo work with other types of RGB cameras?

### ISSUE THREAD

**Issue by andyyy60** [CMU-Perceptual-Computing-Lab/openpose#159]
We are interested to run your 3D demo with our RGB camera setup, would this be possible if we don't have the FLIR cameras listed on your hardware? We already have a setup with calibrated and synchronized RGB cameras.

**Comment by gineshidalgo99** [comment]
Yes it should, you just need to change the input producer Worker class to use your custom cameras.
