### ISSUE TITLE
Host website http://posefs1.perception.cs.cmu.edu/ is down

### ISSUE THREAD

**Issue by Ob1bob** [CMU-Perceptual-Computing-Lab/openpose#1590]
### Issue Summary

Attempting to download any models or dependencies (opencv, caffe, etc.) from the URLs in the install scripts reveals that the website is down:

http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel

The build process fails because the URL is inaccessible.
_Hopefully, the server is just temporarily down - but in case nobody is aware and the problem remains, I am posting this issue.**_

### Executed Command (if any)
`%WGET_EXE% -c http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows/%ZIP_NAME% -P %CAFEE_FOLDER%`

and other download instructions in setup/installation batch scripts.

### Errors (if any)

Attempting to access the the noted URL, as of the time of posting this issue, yields a 
**"Sorry, the page you are looking for is not found"** error.

### Type of Issue
- Compilation/installation error

**Comment by ryanschulz46** [comment]
+1, same issue

**Comment by liushuan** [comment]
+1 same issue

**Comment by ZZYuting** [comment]
+1 same issue

**Comment by cperbost** [comment]
+1 same issue

**Comment by gineshidalgo99** [comment]
Now fixed, sorry!

**Comment by Ob1bob** [comment]
> Now fixed, sorry!

Hi, sorry - still seems to be down. :(

**Comment by ladaly81** [comment]
I'm also still getting a 502 bad gateway error

**Comment by ZZYuting** [comment]
guys, you can search in google to download this caffe model and put it in right loaciton

**Comment by gineshidalgo99** [comment]
Clicking on this link works;
http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel

If something is still failing, could you let me know the exact link failing?

**Comment by ladaly81** [comment]
It started working late yesterday, thanks!

**Comment by ozamanan** [comment]
The website is unavailable again
[http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel](url)
![Screenshot from 2020-06-09 20-10-56](https://user-images.githubusercontent.com/21983436/84212989-79469180-aa8d-11ea-92a9-ea0ae7d934f2.png)

**Comment by gineshidalgo99** [comment]
Temporary workaround:

Download these 2 links:
https://www.dropbox.com/s/gpwg0tbsimo0fr5/models.zip
https://www.dropbox.com/s/1kfh7lqb9ptqj0l/3rdparty.zip

And unzip them and copy in the right place the required files. To know where each file goes, follow:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md (if you are not using the latest OpenPose version, then follow the names used in whatever doc/prerequisites.md file you have!)

**Comment by tcboy88** [comment]
@gineshidalgo99 the dropbox links seem not working

**Comment by gineshidalgo99** [comment]
Please, use instead G Drive links from #1602  (Dropbox took them down for excessive number of downloads.......)
