### ISSUE TITLE
Dataset Unavailable

### ISSUE THREAD

**Issue by stevendae** [CMU-Perceptual-Computing-Lab/openpose#1591]
Does anyone else have trouble downloading the dataset?

wget http://posefs1.perception.cs.cmu.edu/OpenPose/datasets/foot/person_keypoints_train2017_foot_v2.zip

is giving me 502 Bad Gateways. And as well the link on the site is dead.

**Comment by Ob1bob** [comment]
+1, same issue

**Comment by pch18** [comment]
same issue

**Comment by jehontan** [comment]
same issue

**Comment by jaenna77** [comment]
same here!

**Comment by xikouxi** [comment]
same 502 bad gate way！

**Comment by G-BlueSummer** [comment]
502 bad gate way😭

**Comment by Ob1bob** [comment]
Previously logged issue persists: #1590

Host website is inaccessible: http://posefs1.perception.cs.cmu.edu/

**Comment by cperbost** [comment]
same here

**Comment by cbsudux** [comment]
@gineshidalgo99

**Comment by tcboy88** [comment]
seems down again @gineshidalgo99

**Comment by gineshidalgo99** [comment]
It has now been added. Sorry for the troubles!
http://posefs1.perception.cs.cmu.edu/OpenPose/datasets/foot/person_keypoints_train2017_foot_v2.zip
