### ISSUE TITLE
CMake GUI error while downloading models Ubuntu 18.04

### ISSUE THREAD

**Issue by michele17284** [CMU-Perceptual-Computing-Lab/openpose#1592]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary

When I push "configure" button on CMake GUI, it seem not to download properly the models. I also tried to press again and go on with the installation and it seems to work at first glance, but then when I run the demo it can't find any person in the video and, searching here, I find out it could be a model problem, so I suppose the interrupted and resumed download could be the reason. Here is the full CMake GUI output:
GCC detected, adding compile flags
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 10.2
Found cuDNN: ver. 7.5.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
Added CUDA NVCC flags for: sm_50
Found cuDNN: ver. 7.5.0 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
CMake Warning (dev) at /usr/local/share/cmake-3.17/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:444 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Caffe has already been downloaded.
error: pathspec 'c95002f' did not match any file(s) known to git.

Caffe will be built from source now.
Adding Example calibration.bin
Adding Example openpose.bin
Adding Example 1_custom_post_processing.bin
Adding Example 01_body_from_image_default.bin
Adding Example 02_whole_body_from_image_default.bin
Adding Example 03_keypoints_from_image.bin
Adding Example 04_keypoints_from_images.bin
Adding Example 05_keypoints_from_images_multi_gpu.bin
Adding Example 06_face_from_image.bin
Adding Example 07_hand_from_image.bin
Adding Example 08_heatmaps_from_image.bin
Adding Example 09_keypoints_from_heatmaps.bin
Adding Example 10_asynchronous_custom_input.bin
Adding Example 11_asynchronous_custom_input_multi_camera.bin
Adding Example 12_asynchronous_custom_output.bin
Adding Example 13_asynchronous_custom_input_output_and_datum.bin
Adding Example 14_synchronous_custom_input.bin
Adding Example 15_synchronous_custom_preprocessing.bin
Adding Example 16_synchronous_custom_postprocessing.bin
Adding Example 17_synchronous_custom_output.bin
Adding Example 18_synchronous_custom_all_and_datum.bin
Adding Example 1_thread_user_processing_function.bin
Adding Example 2_thread_user_input_processing_output_and_datum.bin
Adding Example handFromJsonTest.bin
Adding Example resizeTest.bin
Download the models.
Downloading BODY_25 model...
NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/michele/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:993 (download_model)

Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/michele/openpose/models/face/pose_iter_116000.caffemodel]
      expected hash: [e747180d728fa4e4418c465828384333]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:999 (download_model)

Downloading hand model...
NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/michele/openpose/models/hand/pose_iter_102000.caffemodel]
      expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:1001 (download_model)

Models Downloaded.
Configuring incomplete, errors occurred!
See also "/home/michele/openpose/build/CMakeFiles/CMakeOutput.log".

### Executed Command (if any)
"Configure" on CMake GUI

### Errors (if any)

Downloading BODY_25 model...
NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/michele/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:993 (download_model)

Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/michele/openpose/models/face/pose_iter_116000.caffemodel]
      expected hash: [e747180d728fa4e4418c465828384333]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:999 (download_model)

Downloading hand model...
NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/michele/openpose/models/hand/pose_iter_102000.caffemodel]
      expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:1001 (download_model)

Models Downloaded.
Configuring incomplete, errors occurred!
See also "/home/michele/openpose/build/CMakeFiles/CMakeOutput.log".

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
Latest Github code

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
CMake GUI
    - **Operating system** (`lsb_release -a` in Ubuntu):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
Ubuntu 18.04
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
1.0.0
    - **CMake version** (`cmake --version` in Ubuntu):
cmake version 3.17.2

    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
ubuntu pre-compiled

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
CUDA Version: 10.2
    - **cuDNN version**:
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 5
#define CUDNN_PATCHLEVEL 0
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

    - **GPU model** (`nvidia-smi` in Ubuntu):
GeForce GTX 950M

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by jessemyers** [comment]
I see the same error while building OpenPose from the CLI. This worked as recently as last week.

**Comment by johannathiemich** [comment]
I have the same error message now and it was working for me last week as well.

**Comment by gineshidalgo99** [comment]
I was able to finally copy the data out of the servers (although they have fallen again), so this is the temporary workaround until I replace all OpenPose links for Dropbox or G. Drive ones:

Download these 2 links:
https://www.dropbox.com/s/gpwg0tbsimo0fr5/models.zip
https://www.dropbox.com/s/1kfh7lqb9ptqj0l/3rdparty.zip

And unzip them and copy in the right place the required files. To know where each file goes, follow:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md (if you are not using the latest OpenPose version, then follow the names used in whatever doc/prerequisites.md file you have!)

Sorry for the troubles!!!

**Comment by thaond98** [comment]
I'm using Openpose api in another directory, and I need to download OpenPose trained models when running CMake GUI of this directory. How can I download it?
