### ISSUE TITLE
Build and Execution process in Windows 10 with Visual Studio 2019

### ISSUE THREAD

**Issue by quickgrid** [CMU-Perceptual-Computing-Lab/openpose#1594]
I followed the installation process at, https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md, but had trouble with running sample codes from Visual Studio. I want to contribute my setup process for those having problems in windows,

https://github.com/quickgrid/Build-Guide/blob/master/README.md#windows-10-cmu-openpose-setup-visual-studio-2019-cmake-nvidia-gpu

**Comment by gineshidalgo99** [comment]
Thanks, added to doc/installation.md in the latest commit! :)
