### ISSUE TITLE
How should I contribute the ONNX model to OpenPose project

### ISSUE THREAD

**Issue by ganler** [CMU-Perceptual-Computing-Lab/openpose#1595]
Hi, recently my friend @Gyx-One and I successfully converted the COCO OpenPose model(from [here](https://github.com/ildoonet/tf-pose-estimation/blob/master/models/graph/cmu/download.sh)) into ONNX format and ran it on TensorRT. And I wonder if we can share the model on your repo or just leave a link to the model to help more developers to reuse it.

BTW, we got 19FPS on 1070Ti using TensorRT(network resolution = `--input_width 656 --input_height 368`)

**Comment by andriy-tsvikla** [comment]
Hi, is there any test example of your work?
