### ISSUE TITLE
Foot keypoints annotation missing. 

### ISSUE THREAD

**Issue by cbsudux** [CMU-Perceptual-Computing-Lab/openpose#1597]
@gineshidalgo99  In [ val2017_foot_v1.zip](http://posefs1.perception.cs.cmu.edu/OpenPose/datasets/foot/person_keypoints_val2017_foot_v1.zip) there are no foot keypoints. The number of keyoints are < 18 and not 25 like you mentioned previously.

Is this the correct json?

**Comment by gineshidalgo99** [comment]
val contains 6 keypoints (the foot keypoints oonly), so the accuracy given is for the foot keypoints without considering the body too. However, train2017 also includes the body keypoints so everything can be trained together. Best
