### ISSUE TITLE
Error: Cuda check failed (30 vs. 0): unknown error

### ISSUE THREAD

**Issue by 09panesara** [CMU-Perceptual-Computing-Lab/openpose#1598]
I am getting ```Error: Cuda check failed (30 vs. 0): unknown error``` when running OpenPose. 
Installation on ec2 instance running ubuntu 16.04. CUDA Version 10.0 and CUDNN 5.1. 

Any help with this would be much appreciaited!

Thanks,
Amrita

**Comment by Donny2333** [comment]
I have the same problem.
Did you solve this problem?
@09panesara
