### ISSUE TITLE
openpose_config.json missing

### ISSUE THREAD

**Issue by juergmaier** [CMU-Perceptual-Computing-Lab/openpose#1600]
unable to import pyopenpose

core.py tries to load openpose_config.json with hard coded path:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/jfm/GitHub/OpenposeWrapper/openpose_wrapper/openpose_config.json'`

Installing openpose did not give me this file (not existing on my machine and google search does not help),

w10/64, miniconda python 3.7
numpy 1.17.4
pyopenpose-0.1 (pip install pyopenpose)
torch-1.4.0-cp37-c37m-win_amd64.whl
torchvision-0.5.0-cp37-cp37m-win_amd64.whl
in addition I had to 
- install fire (pip install fire, fire-0.3.1.tar.gz)
- make the class ClassDict available to core.py

**Comment by frankier** [comment]
pyopenpose on pypi is not this package. You'll need to compile this manually and add the python module to your PYTHONPATH. There are Docker/Singularity images too, which are a relatively easy option.
