### ISSUE TITLE
openpose cannot detect people

### ISSUE THREAD

**Issue by Ray8716397** [CMU-Perceptual-Computing-Lab/openpose#1603]
my os is ubuntu16.04
cuda10 cudnn 7.6
i compile opencv3.4 and caffe,
cmake -DOpenCV_DIR=/usr/local/opencv3/share/OpenCV/  -DCaffe_INCLUDE_DIRS=/home/guiju/Workspace/OpenPose/openpose/3rdparty/caffe_git/caffe/build_cpu/install/include -DCaffe_LIBS_RELEASE=/home/guiju/Workspace/OpenPose/openpose/3rdparty/caffe_git/caffe/build_cpu/install/lib/libcaffe.so -DCaffe_LIBS=/home/guiju/Workspace/OpenPose/openpose/3rdparty/caffe_git/caffe/build_cpu/install/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

but when i use './build/examples/openpose/openpose.bin --video examples/media/video.avi',
it cannot detect people whatever video file

**Comment by nicolasugrinovic** [comment]
Same here, it was working two days ago

**Comment by nicolasugrinovic** [comment]
#1588 maybe this helps

**Comment by ChongMingWei** [comment]
Thanks to @nicolasugrinovic .
After I re-download all models, the result with skeleton is successfully shown. :+1: :+1:
