### ISSUE TITLE
Ubuntu16.04 - wrapper.emplaceAndPop: CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by EliaOnceAgain** [CMU-Perceptual-Computing-Lab/openpose#1604]
### Issue Summary
Running any of the python examples even on small resolution (160x80, 64x32) results in CUDNN_STATUS_NOT_INITIALIZED error message.  

-DBUILD_PYTHON=ON flag was used during build. (also tried from cmake-gui).  
Made sure the used python version is the same one initialized on build (python3.5).  
I can import openpose in python terminal.  

Cuda compilation tools, release 10.0, V10.0.130  
cuDNN version: 7.6.1  
GPU Model: GeForce GTX 1060 6GB

System: Ubuntu16.04
OpenPose: Latest github as of today
cmake/cmake-gui: Tried with 3.5.1 then updated and tried again with 3.17.3

Installation: Tried both in cmake and cmake-gui. Both times python build flag is on.

Console output for command: python3.5 ./07_hand_from_image.py (same output for any of the example files)

Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0610 15:09:31.446769  9710 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***
    @     0x7fbcdfbdb5cd  google::LogMessage::Fail()
    @     0x7fbcdfbdd433  google::LogMessage::SendToLog()
    @     0x7fbcdfbdb15b  google::LogMessage::Flush()
    @     0x7fbcdfbdde1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbcdf674ba3  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7fbcdf5890a3  caffe::Net<>::Init()
    @     0x7fbcdf58bee0  caffe::Net<>::Net()
    @     0x7fbce006de88  op::NetCaffe::initializationOnThread()
    @     0x7fbce0019cb1  op::HandExtractorCaffe::netInitializationOnThread()
    @     0x7fbce001bcc0  op::HandExtractorNet::initializationOnThread()
    @     0x7fbce0095921  op::Worker<>::initializationOnThreadNoException()
    @     0x7fbce0095a60  op::SubThread<>::initializationOnThread()
    @     0x7fbce0098868  op::Thread<>::initializationOnThread()
    @     0x7fbce0098a6d  op::Thread<>::threadFunction()
    @     0x7fbcfacc2c80  (unknown)
    @     0x7fbd01b896ba  start_thread
    @     0x7fbd018bf41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by zhouhaic** [comment]
Similar problem Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

do you solve?

**Comment by edkreepio** [comment]
I am having the same issue here. Environment:

Ubuntu 20.04
CUDA: 10.0
cuDNN: 7.5

Build process:

```
cd ~/dev/openpose/ && rm -rf build 3rdparty && mkdir build && cd build && cmake -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 .. && make CC=gcc-7 CXX=g++-7 -j8 && cd ~/dev/openpose/
```

Running the demo
```
ed@io:~/dev/openpose$ ./build/examples/openpose/openpose.bin --model_pose BODY_25
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0712 12:36:40.721206 208335 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7fb532e581c3  google::LogMessage::Fail()
    @     0x7fb532e5d25b  google::LogMessage::SendToLog()
    @     0x7fb532e57ebf  google::LogMessage::Flush()
    @     0x7fb532e586ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb531f46f73  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7fb53204d665  caffe::Net<>::Init()
    @     0x7fb53204f787  caffe::Net<>::Net()
    @     0x7fb5335064ba  op::NetCaffe::initializationOnThread()
    @     0x7fb53352a6e4  op::addCaffeNetOnThread()
    @     0x7fb53352bbd6  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fb5335317d3  op::PoseExtractorNet::initializationOnThread()
    @     0x7fb533526451  op::PoseExtractor::initializationOnThread()
    @     0x7fb533521201  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fb533565281  op::Worker<>::initializationOnThreadNoException()
    @     0x7fb5335653b0  op::SubThread<>::initializationOnThread()
    @     0x7fb533567708  op::Thread<>::initializationOnThread()
    @     0x7fb5335678d7  op::Thread<>::threadFunction()
    @     0x7fb533197cb4  (unknown)
    @     0x7fb532e9a609  start_thread
    @     0x7fb532fd6103  clone
Aborted (core dumped)
```

**Comment by AKclown** [comment]
I have the same problem. There is no problem in the cpu, but an error is reported when the GPU is turned on.
