### ISSUE TITLE
Python synchronous output

### ISSUE THREAD

**Issue by johnsk95** [CMU-Perceptual-Computing-Lab/openpose#1606]
### Issue Summary
Hello, 
I am curious if it is possible to replicate the same results from one of the c++ examples '17_synchronous_custom_output.cpp' with the python api. 
The example above prints the keypoint coordinates while simultaneously streaming the detected joints in the GUI. 

Thanks in advance!

**Comment by frankier** [comment]
I added the capability of a few more modes here (including async in/sync out): https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/1593

Not sure how possible what you're asking for is, but you might find that a useful starting point at any rate.
