### ISSUE TITLE
The best model

### ISSUE THREAD

**Issue by zghn** [CMU-Perceptual-Computing-Lab/openpose#1613]
Hi 
I'm looking for the best model to reach the results of the paper. Is it available? If not would you please share it with me?
There are some models in caffe and keras but apparently they aren't the last one, are they?

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/tree/master/experimental_models

**Comment by patodichayan** [comment]
@gineshidalgo99  https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/2007
