### ISSUE TITLE
Ubunto to Windows command conversion

### ISSUE THREAD

**Issue by Maxinger15** [CMU-Perceptual-Computing-Lab/openpose#1616]
Hello. I am currently working with this Repo: 
https://github.com/facebookresearch/pifuhd

It uses openpose on unix. Now I want to use it on Windows10 and have to convert the commands for openpose but I don't find the files.
This is the Linux command:
{openpose_root_dir}/build/examples/openpose/openpose.bin --image_dir {1} --write_json {2} --render_pose 2 --face --face_render 2 --hand --hand_render 2

What is the openpose.bin equivalent on Windows?

**Comment by andriy-tsvikla** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#running-on-video maybe this one?
