### ISSUE TITLE
Creating statically linked Binary

### ISSUE THREAD

**Issue by derylucio** [CMU-Perceptual-Computing-Lab/openpose#162]
### Issue summary
Hi, sorry I've very new to building github projects from scratch so forgive me if this is obvious. 
I've successfully followed the instructions and compiled the project.  And the binary at build/examples/openpose/openpose.bin works fine. 

I however need to create a statically linked version of the binary that can run on any machine. 
I'm new to this and really can't make sense of the makefile. Could you guide me as to how to modify compilation setup to have a statically linked version of the binary ? 
Thank you.

### Type of issue
You might select multiple topics, delete the rest:
- Help wanted

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu):
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core)
Release:	7.3.1611
Codename:	Core

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
CUDA Version 8.0.44
**cuDNN version**:
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows) or OpenCV 2.X or OpenCV 3.X.
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu) or CMake (Ubuntu, Windows) or Visual Studio (Windows).
Compiler (`gcc --version` in Ubuntu):
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gineshidalgo99** [comment]
Even if you want to run on any machine, I'd actually say to use a dynamic library and just copy all the required *.so files inside the same folder where the *.bin file is located.
