### ISSUE TITLE
Build difficulty 

### ISSUE THREAD

**Issue by aryamanpandya** [CMU-Perceptual-Computing-Lab/openpose#1621]
/usr/local/include/caffe/proto/caffe.pb.h:49:51: error: no type named 'AuxillaryParseTableField' in namespace 'google::protobuf::internal'; did you mean 'AuxiliaryParseTableField'?
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
                                                  AuxiliaryParseTableField
/usr/local/include/google/protobuf/generated_message_table_driven.h:141:7: note: 'AuxiliaryParseTableField' declared here
union AuxiliaryParseTableField {

**Comment by ankane** [comment]
Hey @aryamanpandya, it appears to be related to this change in Protobuf 3.12.3: https://github.com/protocolbuffers/protobuf/pull/7496

If you're on Mac and building with Caffe provided by Homebrew, I just submitted a PR with a fix: https://github.com/Homebrew/homebrew-core/pull/58210
