### ISSUE TITLE
Error: No module named 'classdict'

### ISSUE THREAD

**Issue by aimove-master** [CMU-Perceptual-Computing-Lab/openpose#1624]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
Hello. I have been trying to run openpose outside visual studio, but I seem to get a weird error.
Openpose works when I run the OpenPoseDemo.exe, but when I try to run at cmd 'python 01_body_from_image.py' I get the following error:

Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
No module named 'classdict'

I have read all of the issues concerning this or similar issues, but none of the suggested solutions solved the problem. 
- I tried to uninstall and reinstall openpose
- I checked the PYTHONPATH within the python example
- I verified that Python_Build was checked on CMAKE
- I copied all the necessary files, as suggested at the git folder for the installation of openpose. 

I hope it won't be marked as dublicate. Any further suggestions?

### Errors (if any)
No module named 'classdict'

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted

### Your System Configuration
Windows 10, Visual studio Enterprise 2017, cudnn 7.5, cuda 10.0, python 3.7.7. Openpose version is the latest found online

**Comment by kheekko** [comment]
Hi @aimove-master I have been having a similar issue as well. Were you able to find a solution?
