### ISSUE TITLE
Obtain 3D coordinates of each bone point through realsense d435i

### ISSUE THREAD

**Issue by Michael-robo13** [CMU-Perceptual-Computing-Lab/openpose#1625]
Hello,

Can I use openpose and realsense d435i to get the 3D coordinates of each bone point? Looking forward for your reply!

Best wishes!
Rogers

**Comment by johnsk95** [comment]
Yes, you can
You can used the align function in the realsense library to retrieve the depth of the pixel in the corresponding image.
