### ISSUE TITLE
Docs on using caffe model standalone

### ISSUE THREAD

**Issue by s1ddok** [CMU-Perceptual-Computing-Lab/openpose#163]
Hey! 

I'm trying to use caffe models provided in repo without the lib itself. However, It feels like it is not encouraged to do so, because there is no documentation. What I did was that changed input dims of `hand deploy.prototxt` file to this:

```
input: "image"
input_dim: 1 # Original: 2
input_dim: 3 # It crashes if not left to 3
input_dim: 368 # Original: 368
input_dim: 368 # Original: 368
```

And then launched inference. I got an output which is a multi-dim array of this dims: `1x1x22x46x46`

However, I don't know how to interpet this data. I would appreciate any help or hints.

**Comment by gineshidalgo99** [comment]
The library is not only a Caffe CNN model, there are plenty of custom OpenPose code on top of that, you cannot only use the Caffe model.
