### ISSUE TITLE
Output video rotated

### ISSUE THREAD

**Issue by Kojon74** [CMU-Perceptual-Computing-Lab/openpose#1632]
### Issue Summary
Even though the input video is the right way up, output video is rotated 90 degrees.

### Executed Command (if any)
I first tried:

`bin\OpenPoseDemo.exe --video input\path --write_video output\path --write_video_fps 10`

Which worked but output was rotated 90 degrees, so I tried:

`bin\OpenPoseDemo.exe --video input\path --write_video output\path --write_video_fps 10 --frame_rotate 90`

But then I got an error saying:

```
Frame size changed. Returning empty frame.
Expected vs. received sizes: 1080x1920 vs. 1920x1080 in D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\producer\producer.cpp:op::Producer::checkFrameIntegrity():305
```

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted

**Comment by gineshidalgo99** [comment]
Yes, the official version 1.6 has that issue. But that should be fixed in the latest GitHub code, please use that one until 1.6.1 is out.

**Comment by vidheyoza** [comment]
I have the same issue with the latest code. When I provide a portrait video it rotates it inconsistently, sometimes clockwise and sometimes counterclockwise. I understand that the model was trained to accept landscape but I'm not sure why different videos are rotated differently. 

Also, does frame_rotate apply the rotation after output or before input? Couldn't seem to find documentation for that cmd parameter.

**Comment by vidheyoza** [comment]
@gineshidalgo99 And if this is a duplicate issue, can you point us to the main issue where this is being discussed?

**Comment by gineshidalgo99** [comment]
It should not be rotating inconsistently. Could you share 2 videos that rotate in different ways? OpenPose simply uses OpenCV to read the videos, and then rotates the video always in the same way, are you sure the original videos are not rotated in different ways?

**Comment by lichengxian** [comment]
The video size I input is 1920 * 1080， could you tell me how to fix this problem? I had the same issue
