### ISSUE TITLE
There is a way , even paying the program, to use it with commercial use? 

### ISSUE THREAD

**Issue by juanprl** [CMU-Perceptual-Computing-Lab/openpose#1634]
I want to use it in blender animations, but "noncommercial use" dont allow me in the way I want.There is a way to contact the original creator? Or other solution?

You might select multiple topics, delete the rest:
    Help wanted
    Other

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/#license
