### ISSUE TITLE
retain order between frames?

### ISSUE THREAD

**Issue by sh0w** [CMU-Perceptual-Computing-Lab/openpose#1638]
hello!

i was wondering if OpenPose supports the retention of order between frames for real-time interactive pose estimation?

this GIF illustrates our issue (the order changes between each frame):

![order](https://user-images.githubusercontent.com/1136734/86927570-c6bd2980-c133-11ea-9047-5d615b4ef2bb.gif)

thank you and all the best
sarah

**Comment by gineshidalgo99** [comment]
It does not.

You can try https://cmu-perceptual-computing-lab.github.io/spatio-temporal-affinity-fields/ (https://cmu-perceptual-computing-lab.github.io/spatio-temporal-affinity-fields/ )

**Comment by sh0w** [comment]
ok thank you!
