### ISSUE TITLE
File not found: models/pose/coco/pose_deploy_linevec.prototxt - Ubuntu

### ISSUE THREAD

**Issue by GeorgianaPetria** [CMU-Perceptual-Computing-Lab/openpose#164]
I'm using a local caffe installation and I'm getting this error when I'm running the openpose command from outside of the openpose directory.

This works:
`./build/examples/openpose/openpose.bin --video video.mp4 --write_keypoint_json output/`

This doesn't work (outside of the openpose directory):
`/home/ubuntu/projects/openpose/build/examples/openpose/openpose.bin --video /home/ubuntu/projects/openpose/video.mp4 --write_keypoint_json /home/ubuntu/projects/openpose/output/`

Any idea why?

**Comment by gineshidalgo99** [comment]
The models folder must be in the directory where OpenPose is called.

But you can alternatively run OpenPose and tell it where the models folder is with '--model_folder' (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md)

**Comment by nanthakumar94** [comment]
i have same issue in window 10. Please tell me any one 
C:\openpose\build\x64\Release>openposedemo.exe --video C:/openpose/examples/media/video.avi --hand --hand_tracking
Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
Prototxt file not found: models\hand/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

**Comment by abdul-mateen-chughtai** [comment]
Hi, nanthakumar94! I was facing the same issue, and as suggested by gineshidalgo99, I placed my build folder in the same directory as model directory and my problem was solved. Now my folder structure looks like this:

**path to my openpose directory**
...\OpenPose\openpose

**path to my build directory**
...\OpenPose\openpose\build_windows

**Comment by ayanasser** [comment]
@abdul-mateen-chughtai  
i did not find the build_windows folder !
could you tell me where this file located exactly ?
in the main repo or in the one of releases versions !

**Comment by barakmen** [comment]
just copy and paste the model's directory to the release directory
