### ISSUE TITLE
How to detect and blur people's faces in videos via Openpose?

### ISSUE THREAD

**Issue by WeilongRen** [CMU-Perceptual-Computing-Lab/openpose#1641]
Hi, I want to use (modify) Openpose to detect and blur people's heads in videos, and save the results, which is my **Goal**.

In the Unity Plugin (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/media/unity_main.png), I noticed that people's faces were covered by dark roundness. I am very interested in this functionality, but only need the face part (i.e., no need for body and hand parts).

For this functionality (dark roundness), is it only for Unity plugin, or also implemented in Openpose Demo? If it is not implemented in Openpose Demo, is it possible that I implement it in the folder "user_code", and which functions should I revoke to implement it? 

Any help would be appreciated. Meanwhile, I would appreciate it if you would like to give any suggestions to implement my **Goal**. thanks a lot!

**Comment by gineshidalgo99** [comment]
You can use OpenCV to blur parts of the image, and OpenPose to know where the face is.

**Comment by WeilongRen** [comment]
Thanks for your answer.

**Comment by Cherryn0629** [comment]
Hello! I want to apply face blurring in OpenPose but I'm not sure how can I try it. Could you please explain in more detail? OpenCV has a library to blur the part of the image but I have no idea which file I have to modify because it's my first time studying OpenPose and C++. Thank you for reading it.

**Comment by nyck33** [comment]
@gineshidalgo99  which flag do I use to output the keypoint locations in x, y for the face?
