### ISSUE TITLE
load opencv_videoio_gstreamer420_64.dll FAILED

### ISSUE THREAD

**Issue by XUXIN-CHN** [CMU-Perceptual-Computing-Lab/openpose#1642]
ERROR INFO :
DynamicLib::libraryLoad load {my dir}\openpose-master\3rdparty\windows\opencv\x64\vc14\bin\opencv_videoio_gstreamer420_64.dll => FAILED

PLATFORM: WIN 10 with visual studio 2017 enterprise

When I run OpenPoseDemo.exe, I can see the original image/video but without the poses blended on it.
Can u help me?

**Comment by XUXIN-CHN** [comment]
![图片](https://user-images.githubusercontent.com/33954013/87237342-c5d41280-c427-11ea-8f2b-6445405080e1.png)

**Comment by XUXIN-CHN** [comment]
![图片](https://user-images.githubusercontent.com/33954013/87237354-f916a180-c427-11ea-9b5c-4334317a7e7a.png)
![图片](https://user-images.githubusercontent.com/33954013/87237380-2cf1c700-c428-11ea-9c4b-d6d3d3f81818.png)

**Comment by AlexYiningLiu** [comment]
How did you solve this issue? Thanks.

**Comment by iAmBrid** [comment]
How did you solve this issue?

**Comment by iAmBrid** [comment]
I cannot find the opencv_videoio_gstreamer420_64.dll under the 3rdparty\windows\opencv\x64\vc14\bin\ downloaded from opencv_videoio_gstreamer420_64.dll => FAILED，Please help me @gineshidalgo99

**Comment by iAmBrid** [comment]
I cannot find the opencv_videoio_gstreamer420_64.dll under the 3rdparty\windows\opencv\x64\vc14\bin\ downloaded from https://drive.google.com/file/d/1mqPEnqCk5bLMZ3XnfvxA4Dao7pj0TErr/view，Please help me @gineshidalgo99

**Comment by gineshidalgo99** [comment]
That's a warning, but it is not needed to run OpenPose. Also, you could get it by downloading OpenCV version 4.2 (the official one, we just re-use it).

The error of not displaying people is most probably because the model was wrongly downloaded (like a fail occurred while downloading it)
