### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_75

### ISSUE THREAD

**Issue by futureflsl** [CMU-Perceptual-Computing-Lab/openpose#1643]
caffe can be built normally,when I build openpose,error occured:nvcc fatal   : Unsupported gpu architecture 'compute_75
System:ubuntu18.04 CUDA9.2 CUDNN7.1.4 
How to solve this problem?

[  2%] Performing configure step for 'openpose_lib'
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.so)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- CUDA detected: 9.2
-- Found cuDNN: ver. 7.1.4 found (include: /usr/local/cuda-9.2/include, library: /usr/local/cuda-9.2/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_75
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Python interface is disabled or not all required dependencies found. Building without it...
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   unknown
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   OFF
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   OFF
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   OFF
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--   USE_HDF5          :   ON
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.0.0)
--   CUDA              :   Yes (ver. 9.2)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_75
--   cuDNN             :   Yes (ver. 7.1.4)
-- 
-- Install:
--   Install path      :   /home/wyd/openpose-master/build/caffe
-- 
-- Configuring incomplete, errors occurred!
See also "/home/wyd/openpose-master/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/wyd/openpose-master/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:126: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
CMakeFiles/Makefile2:720: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
Makefile:149: recipe for target 'all' failed

**Comment by kurshakuz** [comment]
Have you been able to solve it?

**Comment by gineshidalgo99** [comment]
GPU model?

**Comment by WillLiGitHub** [comment]
same probles, have you solved it?
