### ISSUE TITLE
print brief skeleton figure from .json data

### ISSUE THREAD

**Issue by yujianyuanhaha** [CMU-Perceptual-Computing-Lab/openpose#1644]
Greetings,

Is there any way I can get  brief "skeleton figure" (see figure below)  from the .json data, without print out the orginal photo?
<img width="226" alt="Screen Shot 2020-07-12 at 21 26 44" src="https://user-images.githubusercontent.com/9403813/87262012-6d802d80-c486-11ea-9629-107e09d5c255.png">
I have been able to get .json data and the annotated figures. But I am more interested in printing out  "skeleton figure" only, in that I got another sensor data and learning model that can predict out .json data and I need to visualize what the skeleton is like.

I got a little understands of what is in .json, however, 25 (x_i,y_i) points (see figures below) cannot draw a clear skeleton figure, and not good to go.
<img width="344" alt="Screen Shot 2020-07-12 at 21 31 38" src="https://user-images.githubusercontent.com/9403813/87262255-36f6e280-c487-11ea-846b-314bb8bd24dc.png">
 

Best.

**Comment by frankier** [comment]
Here's what I used a while ago:

```
import sys
from json import load
from math import ceil

import click
import gizeh
from more_itertools.recipes import grouper, pairwise


# From https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/20d8eca4b43fe28cefc02d341476b04c6a6d6ff2/doc/output.md#pose-output-format-body_25
BODY_25_LINES = [
    [17, 15, 0, 1, 8, 9, 10, 11, 22, 23],  # Right eye down to right leg
    [11, 24],  # Right heel
    [0, 16, 18],  # Left eye
    [4, 3, 2, 1, 5, 6, 7],  # Arms
    [8, 12, 13, 14, 18, 20],  # Left leg
    [14, 21]  # Left heel
]


def build_graph(lines):
    graph = {}
    for line in lines:
        for n1, n2 in pairwise(line):
            if n1 > n2:
                n1, n2 = n2, n1
            graph.setdefault(n1, set()).add(n2)
    return graph


BODY_25_GRAPH = build_graph(BODY_25_LINES)


def max_dim(doc, dim):
    return max((
        val
        for person in doc["people"]
        for numarr in person.values()
        for val in numarr[dim::3]
    ))


@click.command()
@click.argument("jsonin", type=click.File("r"))
@click.argument("pngout", type=click.File("wb"))
@click.argument("width", type=int, required=False)
@click.argument("height", type=int, required=False)
def main(jsonin, pngout, width, height):
    doc = load(jsonin)
    if not width or not height:
        print("Warning: no width/height specified. Setting to max known + 10.", file=sys.stderr)
        width = ceil(max_dim(doc, 0)) + 10
        height = ceil(max_dim(doc, 1)) + 10
    surface = gizeh.Surface(width=width, height=height, bg_color=(1, 1, 1))
    for person in doc["people"]:
        numarr = list(grouper(person["pose_keypoints_2d"], 3))
        for idx in range(len(numarr)):
            for other_idx in BODY_25_GRAPH.get(idx, set()):
                x1, y1, c1 = numarr[idx]
                x2, y2, c2 = numarr[other_idx]
                c = min(c1, c2)
                if c == 0:
                    continue
                line = gizeh.polyline(
                    points=[(x1, y1), (x2, y2)], stroke_width=5 * c,
                    stroke=(0, 0, 0)
                )
                line.draw(surface)
    surface.write_to_png(pngout)


if __name__ == "__main__":
    main()
```

If you need videos, etc. I've been working on some tools based on a custom HDF5 format for skeletons (not JSONs). See https://github.com/frankier/skelshop

**Comment by yujianyuanhaha** [comment]
@frankier it works for me, thanks a lot

**Comment by thistlillo** [comment]
> Greetings,
> 
> Is there any way I can get brief "skeleton figure" (see figure below) from the .json data, without print out the orginal photo?
> <img alt="Screen Shot 2020-07-12 at 21 26 44" width="226" src="https://user-images.githubusercontent.com/9403813/87262012-6d802d80-c486-11ea-9629-107e09d5c255.png">
> I have been able to get .json data and the annotated figures. But I am more interested in printing out "skeleton figure" only, in that I got another sensor data and learning model that can predict out .json data and I need to visualize what the skeleton is like.
> 
> I got a little understands of what is in .json, however, 25 (x_i,y_i) points (see figures below) cannot draw a clear skeleton figure, and not good to go.
> <img alt="Screen Shot 2020-07-12 at 21 31 38" width="344" src="https://user-images.githubusercontent.com/9403813/87262255-36f6e280-c487-11ea-846b-314bb8bd24dc.png">
> 
> Best.

Where did you find the picture with the ordering of the keypoints? Are you sure it is correct?
I was using the one at:
https://github.com/ArtificialShane/OpenPose/blob/master/doc/output.md
but - may be - it refers to a different format from the one I am using.

**Comment by Atif-Anwer** [comment]
> Here's what I used a while ago:
> 
> ```
> BODY_25_LINES = [
>     [17, 15, 0, 1, 8, 9, 10, 11, 22, 23],  # Right eye down to right leg
>     [11, 24],  # Right heel
>     [0, 16, 18],  # Left eye
>     [4, 3, 2, 1, 5, 6, 7],  # Arms
>     [8, 12, 13, 14, 18, 20],  # Left leg
>     [14, 21]  # Left heel
> ]
> ```
> 
> If you need videos, etc. I've been working on some tools based on a custom HDF5 format for skeletons (not JSONs). See https://github.com/frankier/skelshop

There was a small correction in the keypoints for generating the BODY_25 skeleton. The correct order should be (there is an extra 18 in the Left Leg):
```
BODY_25_LINES = [
    [17, 15, 0, 1, 8, 9, 10, 11, 22, 23],  # Right eye down to right leg
    [11, 24],  # Right heel
    [0, 16, 18],  # Left eye
    [4, 3, 2, 1, 5, 6, 7],  # Arms
    [8, 12, 13, 14, 20],  # Left leg
    [14, 21]  # Left heel
]
```

This fixes the generation atleast for me. Thanks for the script!
