### ISSUE TITLE
Output json file only contains pose_keypoint_2d, no face hand position

### ISSUE THREAD

**Issue by Chandler-Shuyu-Xie** [CMU-Perceptual-Computing-Lab/openpose#1647]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
I use openpose demo on videos. Output json files only contain pose_keypoints_2d array, other arrays, like hand_left_keypoints_2d array is empty.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
!cd openpose && ./build/examples/openpose/openpose.bin --video ../no_mask_no_teacher.mp4 --write_json ../output_no_mask_no_teacher/ --display 0  --write_video ../openpose.avi

### OpenPose Output (if any)
{
  "version": 1.3,
  "people": [
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        486.229,
        506.83,
        0.854842,
        515.585,
        506.609,
        0.879484,
        477.339,
        506.638,
        0.878002,
        439.145,
        544.922,
        0.815744,
        433.241,
        574.438,
        0.913057,
        553.737,
        506.613,
        0.906769,
        577.385,
        577.349,
        0.90952,
        503.867,
        577.495,
        0.850981,
        533.281,
        603.894,
        0.554041,
        506.851,
        603.835,
        0.572541,
        0,
        0,
        0,
        0,
        0,
        0,
        559.752,
        603.913,
        0.556582,
        0,
        0,
        0,
        0,
        0,
        0,
        480.27,
        500.865,
        0.775271,
        497.954,
        500.839,
        0.859039,
        0,
        0,
        0,
        518.555,
        480.176,
        0.839912,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        718.771,
        312.456,
        0.841225,
        733.41,
        309.58,
        0.857272,
        698.005,
        312.455,
        0.870165,
        665.656,
        344.926,
        0.794767,
        689.148,
        365.385,
        0.298114,
        762.817,
        309.538,
        0.884927,
        780.466,
        359.499,
        0.760579,
        736.31,
        362.558,
        0.452661,
        739.26,
        385.972,
        0.484821,
        715.837,
        386.02,
        0.508863,
        0,
        0,
        0,
        0,
        0,
        0,
        762.674,
        385.919,
        0.482151,
        0,
        0,
        0,
        0,
        0,
        0,
        715.697,
        303.627,
        0.803207,
        724.538,
        300.664,
        0.77768,
        701.043,
        294.947,
        0.206568,
        739.188,
        291.995,
        0.786662,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        1024.65,
        203.561,
        0.847103,
        1021.68,
        224.212,
        0.922984,
        998.23,
        224.142,
        0.94635,
        980.657,
        250.777,
        0.711694,
        998.303,
        268.234,
        0.254361,
        1042.43,
        224.298,
        0.877764,
        1048.38,
        253.616,
        0.725391,
        1045.43,
        268.232,
        0.514916,
        1018.8,
        280.076,
        0.511912,
        1001.16,
        277.189,
        0.564268,
        0,
        0,
        0,
        0,
        0,
        0,
        1024.91,
        282.996,
        0.531244,
        0,
        0,
        0,
        0,
        0,
        0,
        1021.83,
        200.572,
        0.859103,
        1024.85,
        200.636,
        0.834163,
        1015.9,
        200.607,
        0.738299,
        1027.68,
        200.819,
        0.424201,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        833.411,
        265.439,
        0.927575,
        845.222,
        265.39,
        0.863603,
        812.819,
        262.488,
        0.879045,
        789.267,
        300.682,
        0.660649,
        812.85,
        315.482,
        0.127357,
        877.605,
        265.381,
        0.881308,
        901.173,
        297.77,
        0.655624,
        862.949,
        318.258,
        0.15328,
        842.276,
        336.064,
        0.383101,
        827.5,
        338.833,
        0.418309,
        0,
        0,
        0,
        0,
        0,
        0,
        859.99,
        338.853,
        0.414504,
        0,
        0,
        0,
        0,
        0,
        0,
        830.433,
        253.697,
        0.828174,
        836.387,
        253.69,
        0.891115,
        821.65,
        247.646,
        0.0646972,
        856.913,
        247.662,
        0.904899,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        1139.67,
        338.93,
        0.808046,
        1142.48,
        347.81,
        0.874534,
        1112.93,
        344.812,
        0.850802,
        1071.78,
        385.978,
        0.799429,
        1048.28,
        403.671,
        0.0941556,
        1183.68,
        347.857,
        0.768012,
        1189.57,
        406.71,
        0.430672,
        1165.99,
        415.48,
        0.290975,
        1130.75,
        439.067,
        0.462734,
        1107.15,
        439.003,
        0.434668,
        0,
        0,
        0,
        0,
        0,
        0,
        1154.27,
        442.014,
        0.489123,
        0,
        0,
        0,
        0,
        0,
        0,
        1136.53,
        327.156,
        0.716857,
        1148.39,
        327.174,
        0.689366,
        1119.09,
        318.473,
        0.380781,
        1165.95,
        321.305,
        0.490396,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        1404.5,
        380.141,
        0.787169,
        1404.39,
        385.974,
        0.865664,
        1375.05,
        383.028,
        0.850545,
        1351.45,
        418.406,
        0.689126,
        1351.44,
        433.1,
        0.142908,
        1439.71,
        386.192,
        0.828028,
        1466.28,
        388.908,
        0.607952,
        1460.34,
        344.847,
        0.414714,
        1398.45,
        462.672,
        0.518293,
        1375.01,
        462.558,
        0.530409,
        0,
        0,
        0,
        0,
        0,
        0,
        1419.11,
        468.441,
        0.509123,
        0,
        0,
        0,
        0,
        0,
        0,
        1401.44,
        365.576,
        0.842406,
        1419.15,
        368.379,
        0.80259,
        1389.76,
        362.593,
        0.6216,
        1425.16,
        365.5,
        0.530438,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        1063.02,
        415.611,
        0.697089,
        1054.25,
        415.619,
        0.860127,
        1015.91,
        418.408,
        0.83049,
        965.926,
        471.406,
        0.830625,
        977.657,
        492.086,
        0.79273,
        1098.4,
        421.373,
        0.857326,
        1121.99,
        494.959,
        0.848559,
        1068.93,
        506.787,
        0.84506,
        1065.91,
        533.227,
        0.660111,
        1033.56,
        533.219,
        0.646686,
        0,
        0,
        0,
        0,
        0,
        0,
        1092.41,
        533.234,
        0.651766,
        0,
        0,
        0,
        0,
        0,
        0,
        1048.22,
        412.607,
        0.598922,
        1068.86,
        409.687,
        0.667512,
        1027.68,
        412.431,
        0.372326,
        1071.86,
        400.834,
        0.363746,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        1330.98,
        238.942,
        0.216185,
        1330.81,
        247.732,
        0.893622,
        1354.47,
        247.809,
        0.780087,
        1372.09,
        283.069,
        0.617178,
        1360.26,
        303.611,
        0.341057,
        1307.17,
        244.92,
        0.773097,
        1283.7,
        286.006,
        0.635862,
        1286.7,
        297.779,
        0.130257,
        1324.86,
        318.462,
        0.63982,
        1333.8,
        321.306,
        0.628702,
        1348.44,
        353.696,
        0.0756661,
        0,
        0,
        0,
        1307.25,
        318.419,
        0.636509,
        0,
        0,
        0,
        0,
        0,
        0,
        1330.98,
        230.045,
        0.175367,
        1333.74,
        232.955,
        0.197347,
        1339.65,
        224.348,
        0.604933,
        1330.87,
        224.251,
        0.693502,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      "person_id": [
        -1
      ],
      "pose_keypoints_2d": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1348.39,
        247.663,
        0.445246,
        1374.89,
        271.384,
        0.368581,
        1366.18,
        294.772,
        0.261261,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    }
  ]
}

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Output

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
latest

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...? Cmake
    - **Operating system** (`lsb_release -a` in Ubuntu): Google Colab
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...): Google Colab
    - **Release or Debug mode**? (by default: release): release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
You need to add --face or --hand in your command (./build/examples/openpose/openpose.bin --video ../no_mask_no_teacher.mp4 --write_json ../output_no_mask_no_teacher/ --display 0 --write_video ../openpose.avi)
