### ISSUE TITLE
Not enough Memory error with Cudnn 7.5 and CUDA 10.1 

### ISSUE THREAD

**Issue by HansiIMW** [CMU-Perceptual-Computing-Lab/openpose#1648]
### Issue Summary
Hallo, I installed CUDA 10.1 and the Cudnn Libraries 7.5.1 correctly as per the guide provided by nvidia, and have verified their installation. I deleted Cuda 11 and Cuda 10.2 from my system, but when i execute nvidia-smi it shows CUDA Version: 11. WHen executing nvcc --version it says: 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

I thought my GPU would be sufficient, please see the details down below, but OpenPose will not run due to my system running out of memory. This leads me to believe that either CUDA or my cudnn library are wrong? 

### Executed Command (if any)
./build/examples/openpose/openpose.bin 

and 

./build/examples/openpose/openpose.bin --face --hand 

### Errors (if any)

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0717 13:47:39.615442  6255 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fc2219570cd  google::LogMessage::Fail()
    @     0x7fc221958f33  google::LogMessage::SendToLog()
    @     0x7fc221956c28  google::LogMessage::Flush()
    @     0x7fc221959999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc22148ec5a  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7fc2212ebce2  caffe::Blob<>::mutable_gpu_data()
    @     0x7fc2214dedc0  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7fc221456562  caffe::Net<>::ForwardFromTo()
    @     0x7fc222d58983  op::NetCaffe::forwardPass()
    @     0x7fc222d8147a  op::PoseExtractorCaffe::forwardPass()
    @     0x7fc222d7a365  op::PoseExtractor::forwardPass()
    @     0x7fc222d771a6  op::WPoseExtractor<>::work()
    @     0x7fc222db9649  op::Worker<>::checkAndWork()
    @     0x7fc222db97d3  op::SubThread<>::workTWorkers()
    @     0x7fc222dc3438  op::SubThreadQueueInOut<>::work()
    @     0x7fc222dbbab1  op::Thread<>::threadFunction()
    @     0x7fc22264e6df  (unknown)
    @     0x7fc220fb16db  start_thread
    @     0x7fc2220a9a3f  clone
Aborted (core dumped)

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

Fri Jul 17 14:01:42 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 950M    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8    N/A /  N/A |    221MiB /  2004MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1866      G   /usr/lib/xorg/Xorg                130MiB |
|    0   N/A  N/A      2638      G   /usr/bin/gnome-shell               88MiB |
+-----------------------------------------------------------------------------+

2. **OpenPose version**:

Sorry, I am a mechanical engineer, not a programmer, i don't know the exact version I am using, I built OpenPose from scratch yesterday just by cloning the repo through git clone etc... 

3. **General configuration**:
    - **Installation mode**: CMake 
    - **Operating system** Ubuntu
    - **Operating system version** 18.04 
    - **Release or Debug mode**?
    - Compiler: gcc 7.5.0 

4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? no 

5. **3rd-party software**:
    - **Caffe version**: cloned the caffe repo provided by OpenPose CMU here on Github https://github.com/CMU-Perceptual-Computing-Lab/caffe/tree/b5ede488952e40861e84e51a9f9fd8fe2395cc8a 
    - **CMake version** 3.18.0
    - **OpenCV version**: 3.2 

6. If **GPU mode** issue:
    - **CUDA version** 10.1.243
    - **cuDNN version**: 7.5.1 
    - **GPU model** GeForce GTX 950M

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 3.7 
    - **Numpy version** 1.16.6

**Comment by ku294714** [comment]
Hello Dear Team,

Even I face the similar issue when running for images, however, when i run on videos, it runs but no detection are shown on the video and resulted JSON are also empty.

I have a 4 GB GTX 1050 Ti GPU.

**Comment by Alex-Beh** [comment]
@ku294714 @HansiIMW I faced the same issue with the same error output. May I know have y'all solve the issue?

**Comment by UEBoy2019** [comment]
> Hello Dear Team,
> 
> Even I face the similar issue when running for images, however, when i run on videos, it runs but no detection are shown on the video and resulted JSON are also empty.
> 
> I have a 4 GB GTX 1050 Ti GPU.
u should use 16GB GTX

**Comment by HansiIMW** [comment]
> @ku294714 @HansiIMW I faced the same issue with the same error output. May I know have y'all solve the issue?

hello, sorry for the late reply, no i have not, i have just switched to tf-pose for now.

**Comment by gineshidalgo99** [comment]
2GB is too few. You can reduce -net_resolution (which will reduce the accuracy as well but incrase the speed), that's all you can do with < 3 GB GPU. Sorry!
