### ISSUE TITLE
Use CMake to create new project

### ISSUE THREAD

**Issue by Nestarneal** [CMU-Perceptual-Computing-Lab/openpose#165]
Hi, 
I want to use OpenPose in my project, and I did a simple experiment to try to build my own project with OpenPose using cmake.

Here's my directory architecture, it's very simple
|
| ------ build/
| ------ myOpenPose.cpp
| ------ CMakeLists.txt

And I build my project by entering the build folder (cd build/) and using the command "cmake ..; make"

The error message shows that:
[ 50%] Building CXX object CMakeFiles/openpose_test.dir/myOpenPose.cpp.o
/home/ubuntu/Downloads/TestForOpenPose/myOpenPose.cpp:1:37: fatal error: openpose/core/headers.hpp: No such file or directory

The cpp file is correct because I can build the binary executable by putting it under openpose/example/user_code/
Thus, I consider the error is due to some error in CMakeLists.txt

I reference issue #22 to construct the cmake file, following is my CMakeLists.txt:

    CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

    PROJECT(OpenPoseProjectTest)

    SET(CMAKE_CXX_COMPILER "g++")
    SET(CMAKE_BUILD_TYPE Debug)
    SET(CMAKE_CXX_FLAGS "-std=c++11")
    SET(OPENPOSE_DIR /home/ubuntu/openpose)
    SET(CAFFE_DIR /home/ubuntu/openpose/3rdparty/caffe)

    find _package(CUDA REQUIRED)
    if (CUDA_FOUND)
        INCLUDE_DIRECTORIES(
            ${CUDA_INCLUDE_DIRS}
            ${OPENPOSE_DIR}/distribute/include
            ${CAFFE_DIR}/distribute/include
        )

        add_difinitions(-DUSE_CAFFE)
        ADD_EXECUTABLE(openpose_test myOpenPose.cpp)
        TARGET_LINK_LIBRARIES(openpose_test
            ${CUDA_LIBS}
            ${OPENPOSE_DIR}/build/lib/libopenpose.so
            ${CAFFE_DIR}/build/lib/libcaffe.so
        )
    endif ()

What's wrong with my CMakeLists.txt?
Many thanks.

**Comment by Nestarneal** [comment]
It's ok after I modified the path to correct ones.

**Comment by osamazhar** [comment]
Hi, 

what did you modify actually, I am getting the error when I make it, as follows:

Scanning dependencies of target openpose_test
[ 50%] Building CXX object CMakeFiles/openpose_test.dir/2_extract_pose_or_heatmat_from_image.cpp.o
/home/osama/openpose/examples/tutorial_pose/2_extract_pose_or_heatmat_from_image.cpp:15:37: fatal error: openpose/core/headers.hpp: No such file or directory
compilation terminated.
CMakeFiles/openpose_test.dir/build.make:62: recipe for target 'CMakeFiles/openpose_test.dir/2_extract_pose_or_heatmat_from_image.cpp.o' failed
make[2]: *** [CMakeFiles/openpose_test.dir/2_extract_pose_or_heatmat_from_image.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_test.dir/all' failed
make[1]: *** [CMakeFiles/openpose_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gineshidalgo99** [comment]
As an extra detail, instead of using #22 to construct the cmake file, I'd rather consider file example in the doc/installation_cmake.md document itself.
