### ISSUE TITLE
Is it possible to launch demo version outside of the root directory (Linux)?

### ISSUE THREAD

**Issue by tenghiz** [CMU-Perceptual-Computing-Lab/openpose#1654]
I would like to create a web app which estimates people's action using OpenPose. I am using a Python script which in its turn calls OpenPose via os.system. This script runs without any problem when launched from the project's root directory. However, an error is generated when the script is placed in any other place. If I create another Python script placed outside of the root folder and call the Python scipt placed inside of the root folder, it doesn't work neither. The content of the error message is always the same:

Error:
Prototxt file not found: models/pose/body_25/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Is there any method which allows to run demo version from arbitrary place?

**Comment by gembancud** [comment]
I've seen this as well, but I have yet the need to actually fix it on my project.
I would guess that it may not be able to find the model folder based on how it may be relatively or absolutely tracked, irdk.
Modifying the code below might work for you if you know how to properly redirect the model folder when calling the instantiating and configuring the library

```
params["model_folder"] = "./models/" #Insert Proper Model Directory
opWrapper = op.WrapperPython()
opWrapper.configure(params)
```

**Comment by tenghiz** [comment]
1. I am reading the table of flags, maybe it would be also reasonable to change the value of DEFINE_string(prototxt_path,... I am still working through it.

2. I'm not sure whether it is possible, but I would really like to see the source code written. I suppose all paths can be easily modified from there.

**Comment by gembancud** [comment]
```
dir_path = os.path.dirname(os.path.realpath(__file__))
params["model_folder"] =dir_path + "./models/"
```
