### ISSUE TITLE
Use color or just black and white for Hand Keypoint detection

### ISSUE THREAD

**Issue by ksyao2002** [CMU-Perceptual-Computing-Lab/openpose#1655]
### Issue Summary

I am deciding whether or not to convert all my images to black and white for better detection accuracy of the hand. I know that there is a difference, and I was wondering if the model was trained on color images or black and white images. Also, if anyone knows which is better for the hand detection?

**Comment by gineshidalgo99** [comment]
It was trained on color images, so please, use color ones!

**Comment by ksyao2002** [comment]
Thanks for your response! Quick follow up: what aspect ratio was used during training? I noticed that the aspect ratio makes a big difference in the detection accuracy. Should I post a new issue about this?

**Comment by gineshidalgo99** [comment]
They are squared. You could look to how openpose crop them to follow a similar approach, kind of having the whole hand + 10-20% border of margin
