### ISSUE TITLE
What's the correct way to run the Open Pose binary (OpenPoseDemo.exe) from within a Python script?

### ISSUE THREAD

**Issue by PrashantSaikia** [CMU-Perceptual-Computing-Lab/openpose#1658]
I am making a body tracking application where I want to run Open Pose if the user chooses to track their body movements. As we all know, the OpenPose binary file can be run like so:

`bin\OpenPoseDemo.exe --write_json 'path\to\dump\output'`

So, in my Python script, I want to have a line of code that would run Open Pose, instead of having to ask the user to manually run OpenPose by opening a separate command line window. For that, I have tried:

```
import os
os.popen(r"C:\path\to\bin\OpenPoseDemo.exe --write_json 'C:\path\to\dump\output'")
```
But this gives the following error:

```
Error:
Could not create directory: 'C:\Users\Admin\Documents\Openpose\. Status error = -1. Does the parent folder exist and/or do you have writing access to that path?
```

Which I guess means that `OpenPoseDemo.exe` can be opened only by going inside the `openpose` directory where the `bin` subdirectory resides. So, if there's anybody here who made it work, it would be awesome if you could show how. Thanks in advance!

**Comment by gembancud** [comment]
If you're planning to write a python script anyway why not just use the python API altogether? Rebuild it from source, from there you can play with the examples and hopefully extend the API to your means

**Comment by PrashantSaikia** [comment]
> If you're planning to write a python script anyway why not just use the python API altogether? Rebuild it from source, from there you can play with the examples and hopefully extend the API to your means

Because I tried multiple times, checking instructions from multiple online sites, but always get error. This is the latest one from today:

![image](https://user-images.githubusercontent.com/39755678/89116345-bf383880-d4c5-11ea-9bdc-ce184c700358.png)

**Comment by gembancud** [comment]
Have you tried this installation tutorial? Following its steps to the bone? 
https://www.youtube.com/watch?v=QC9GTb6Wsb4&feature=youtu.be

**Comment by gembancud** [comment]
Has OP tried the solution by fixing the relative paths of the module? Link is [here](https://stackoverflow.com/questions/40416072/reading-file-using-relative-path-in-python-project/40416154#:~:text=3%20Answers&text=Relative%20paths%20are%20relative%20to,be%2C%20it%20must%20be%20absolute.&text=This%20requires%20python%203.4%2B%20(for%20the%20pathlib%20module).)
