### ISSUE TITLE
How to save output video with texts on frames(like gui_verbose, such as "Frame:""people" and so on)

### ISSUE THREAD

**Issue by vagrant73** [CMU-Perceptual-Computing-Lab/openpose#1659]
Hi!
   I've saved output video succssesfully, but I wanna save the video with the gui_verbose(e.g., number of current frame and people and other texts(which I added some texts at guiInforadder.cpp)).  could you offer me some suggestions?
    win10 
    openpose 1.6.0
    Visual Studio 2017
    OpenPoseDemo

**Comment by gembancud** [comment]
Opencv for frame processing. embed your text right before you write the frame
