### ISSUE TITLE
lr_mult of some layers

### ISSUE THREAD

**Issue by Maycbj** [CMU-Perceptual-Computing-Lab/openpose#166]
Hi,
I've try to train this model by using code of Zhe Cao. But in "pose_deploy_linevec.prototxt", such as 'conv4_3_CPM' and 'conv5_1_CPM_L2', these layers you have not fine_tuning, but the lr_mult is only 1, why the lr_mult of these layers is so low?

I would really appreciate your help.
Thanks!

**Comment by gineshidalgo99** [comment]
We are just using the testing. For training questions check the training repo. Thanks!
