### ISSUE TITLE
Error: Caffe trained model file not found -- downloading .bat-file not working

### ISSUE THREAD

**Issue by sebahelm** [CMU-Perceptual-Computing-Lab/openpose#1661]
I got an error, by running my OpenPose code in PowerShell, that was still working.
Afterward, I downloaded the newest version of OpenPose v1.6.0 (Demo-Version). But downloading the models, using the .bat-file, was not working.
By running OpenPose, now I'm getting the following error:

_Error:
Caffe trained model file not found: models\face/pose_iter_116000.caffemodel.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces._

Some months ago, there were problems with the server for the models. Is this problem still existing. I can not find that post anymore. 
Do you have this problem, too? Is there any workaround?

**Comment by guilhermesurek** [comment]
I had the same problem.
The bat file keep trying to download it, but it fails.
Opening the url (http://posefs1.perception.cs.cmu.edu/OpenPose/models/) in chrome it gets ERR_CONNECTION_TIMED_OUT.

![image](https://user-images.githubusercontent.com/23281984/91565737-0d9bf400-e919-11ea-953e-efc4abf7f51c.png)

**Comment by frankier** [comment]
Here they are:

https://androidhost.org/IXhctBD
https://androidhost.org/XY00nIp
https://androidhost.org/P8AsRCe

**Comment by guilhermesurek** [comment]
Thanks, it worked!

**Comment by gineshidalgo99** [comment]
Please see https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
