### ISSUE TITLE
Trying to run openpose on ubuntu 16.04 with CPU installation and getting the error symbol lookup error: /home/tron/openpose/build/caffe/lib/libcaffe.so.1.1.0: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev

### ISSUE THREAD

**Issue by MichailTheofanidis** [CMU-Perceptual-Computing-Lab/openpose#1664]
Dear all,

My system configuration is the following:

1) I am using the latest OP version

2) I installed OP via the make-gui and then make -j`nproc`

3) I am doing a CPU installation and Caffe (I have clicked on PYTHON_BUILD and remove CUDA and CDNN)

4) I am using python 3.7 on Linux 16.04

The error I get is the following when I try to execute one of the examples:

tron@IMU-VISION-1:~/openpose/build/examples/tutorial_api_cpp$ ./01_body_from_image_default.bin 
./01_body_from_image_default.bin: symbol lookup error: /home/tron/openpose/build/caffe/lib/libcaffe.so.1.1.0: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev

I am not running conda or any virtual environment.

I would appreciate any help.

Thank you

**Comment by RiccardoMaistri** [comment]
Same happened to me, did you solved @MichailTheofanidis ?
