### ISSUE TITLE
Low FPS on 2x RTX 2080 Ti

### ISSUE THREAD

**Issue by gunjan15aug** [CMU-Perceptual-Computing-Lab/openpose#1665]
Hello,
I have 2x RTX 2080 Ti, cuDNN-7.5, CUDA - 10, VS 2017 in my workstation. When I run the OpenPose I get ~13 FPS. I need ~25 FPS. Would you please suggest me what should I do to get ~25 FPS.?

**Comment by mashuaiwudi** [comment]
I only use an RTX 2060, but I can get ~12 FPS. I think if you need 25 FPS or above, maybe you need to modify the source code.

**Comment by gineshidalgo99** [comment]
Multi-threading is on by default, so there should be no need to use num_gpu or num_gpu_start.

2x2080 will get you ~50-70 FPS for sure, if nothing else is limiting the frame rate (eg your webcam or reading video from the hard disk, which is likely your issue).

However, you haven't posted nor followed the issue template (if i had that information i could tell you your issue exactly), so post closed temporarily until that information is added here. Thanks!
