### ISSUE TITLE
Fail to run  "3-D Reconstruction Real-time demo" 

### ISSUE THREAD

**Issue by Eby-123** [CMU-Perceptual-Computing-Lab/openpose#1666]
Hi，It's OK to run "Running on Webcam :: Windows - Portable Demo" with the codes:

> `build\x64\Release\OpenPoseDemo.exe`

and it returns this:
![2DOPENPOSE](https://user-images.githubusercontent.com/55172761/90137743-9f97ee80-dda8-11ea-89a5-825097dafab3.png)

But,if I want to run "3-D Reconstruction Real-time demo" with the codes:

> `build\x64\Release\OpenPoseDemo.exe --flir_camera --3d --number_people_max 1`

it doesn't work and returns the codes as follows:

`Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Application build date: Aug 13 2020 20:42:33
Number of cameras detected: 0

Error:
No cameras detected.`

Any help you can give me will be very useful. Thank you！

**Comment by gineshidalgo99** [comment]
Hi, see the doc/ about 3D, it requires >1 cameras (and from a specific brand). Best
