### ISSUE TITLE
Drone footage

### ISSUE THREAD

**Issue by TuskAW** [CMU-Perceptual-Computing-Lab/openpose#1667]
Hello,

I am working on an application to generate the pose of of people in view of a drone in concerts. I ran OpenPose on this youtube video (https://www.youtube.com/watch?v=bDBMGxXS23c ), and as would have been expected, not many poses were detected. With the proper training, would OpenPose be able to perform pose detection from a drone at a reasonable altitude or zoom?

**Comment by gineshidalgo99** [comment]
For that one, it'd be probable better a head bounding box detector? I remember seeing papers to count faces in crowds, one from CMU and I believe Deva Ramanan. Pose estimation given the current algorithms will likely perform poorly, no matter the algorithm or approach
