### ISSUE TITLE
All third-party .zip files for Windows are offline?

### ISSUE THREAD

**Issue by rathaROG** [CMU-Perceptual-Computing-Lab/openpose#1673]
`posefs1.perception.cs.cmu.edu` is offline, and I can't download these files:

- caffe_15_2020_04_05.zip
- caffe3rdparty_15_2019_03_14.zip
- opencv_420_v14_15_2020_04_04.zip

I also tried VPN but no luck. Any mirror? Or could anyone please share these files?

**Comment by rathaROG** [comment]
Found solution here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411

**Comment by guangbin-Hu** [comment]
thank you
