### ISSUE TITLE
Model Download Error (Couldn't connect to server)

### ISSUE THREAD

**Issue by litcoderr** [CMU-Perceptual-Computing-Lab/openpose#1674]
## Problem

Hi, I had no problem building Openpose Dockerfile just about 3 weeks ago. But when I tried building it again today, encountered a ```couldn't connect to server``` error when downloading pre-trained model.

I think there is a problem with download hash.

Please help. Thanks !!

-----------------------------------------

I have the same issue.

- This is my ```Dockerfile```

```
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

RUN echo "Installing dependencies..." && \
	apt-get -y --no-install-recommends update && \
	apt-get -y --no-install-recommends upgrade && \
	apt-get install -y --no-install-recommends \
	build-essential \
	cmake \
	git \
	libatlas-base-dev \
	libprotobuf-dev \
	libleveldb-dev \
	libsnappy-dev \
	libhdf5-serial-dev \
	protobuf-compiler \
	libboost-all-dev \
	libgflags-dev \
	libgoogle-glog-dev \
	liblmdb-dev \
	pciutils \
	python3-setuptools \
	python3-dev \
	python3-pip \
	opencl-headers \
	ocl-icd-opencl-dev \
	libviennacl-dev \
	libcanberra-gtk-module \
	libopencv-dev && \
	python3 -m pip install --upgrade pip && \	
	python3 -m pip install \
	numpy \
	protobuf \
	opencv-python

RUN echo "Downloading and building OpenPose..." && \
	git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git && \
	cd openpose/3rdparty && \
	git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe	&& \
	cd ../ && \
	mkdir build && \
	cd build && \
	cmake .. && \
	make -j4 && \
	make install && \
	cd ..

WORKDIR /pose_extractor/script
ENTRYPOINT bash ./preprocess.bash
```

- This is the error that i've got

![image](https://user-images.githubusercontent.com/41692376/90879554-0d17d080-e3e2-11ea-8dcc-802695895ebc.png)
![image](https://user-images.githubusercontent.com/41692376/90879606-1ef97380-e3e2-11ea-9a3a-b0bf5423e367.png)

Think we have the same issue 😇 Please help Thx

_Originally posted by @litcoderr in https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1224#issuecomment-678178948_

**Comment by gineshidalgo99** [comment]
See https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
