### ISSUE TITLE
Error downloading the models from the .bat file

### ISSUE THREAD

**Issue by OmarGarciaAlc** [CMU-Perceptual-Computing-Lab/openpose#1677]
I tried to run the 1.4.0 version on Windows 10 and followed the instructions txt but when i double clicked on the getModels.bat i get this message in a loop.

What could be the reason?

------------------------- BODY, FACE AND HAND MODELS -------------------------
----- Downloading body pose (COCO and MPI), face and hand models -----

------------------------- POSE MODELS -------------------------
Body (BODY_25)
--2020-08-23 13:20:07--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Unknown error.
Retrying.

**Comment by gineshidalgo99** [comment]
See See https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
