### ISSUE TITLE
Isn't there a model that only estimation the joint of the foot?

### ISSUE THREAD

**Issue by park-youngsin** [CMU-Perceptual-Computing-Lab/openpose#1678]
Hi, I'm getting a lot of help from the open pose.

However, If only feet are seen in the image, the joints are not recognized. 

is there any solution for foot-only keypoint detection?

and the link on [the site](https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/) is dead. How can I download datasets?

**Comment by frankier** [comment]
I believe if you use the BODY_135 model, it may be able to detect skeletons that only include a few keypoints. At least this paper talks about it: https://arxiv.org/abs/1909.13423

That link has worked previously. Looks like the server is just down at the moment.

**Comment by emirhanylmzz** [comment]
did you come to a conclusion? i am trying to train only foot. i want to detect only foot keypoints from all angles. help please if u find the conclusion
