### ISSUE TITLE
Successfully build but Keypoints are not detected and drawn

### ISSUE THREAD

**Issue by PJCIP** [CMU-Perceptual-Computing-Lab/openpose#1679]
### Issue Summary
I am trying to build open pose in my local. Once I had built it with the **make -j ‘nproc’** command. I was testing the sample the codes under example/tutorial-python-api. While I am running the script under this directory, I don't see any keypoints drawn on the image.  **./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video output/result.avi --write_json output/**

here Json files are generated but **I couldn’t find any values within those files**.

### OpenPose Output (if any)
![1](https://user-images.githubusercontent.com/43749087/91012447-c1dd0800-e603-11ea-80d0-ff4d5235a182.png)
![2](https://user-images.githubusercontent.com/43749087/91012482-cd303380-e603-11ea-9388-62efd722e96c.png)

### Your System Configuration
**Operating System:** Ubuntu 18.04
**Open pose version:** 1.6.0
**Cuda toolkit:**

NVIDIA (R) Cuda compiler driver

Copyright (c) 2005-2018 NVIDIA Corporation

Built on Sat_Aug_25_21:08:01_CDT_2018

Cuda compilation tools, release 10.0, V10.0.130

**Cudnn library:**

libcudnn7-dev_7.5.0.56-1+cuda10.0_amd64.deb,

libcudnn7-doc_7.5.0.56-1+cuda10.0_amd64.deb,

libcudnn7_7.5.0.56-1+cuda10.0_amd64.deb

**CMake version :** 3.18.2

**Python version:** 3.6.9

**Opencv version:** '4.4.0-dev'

**Caffee used:**  [https://github.com/CMU-Perceptual-Computing-Lab/caffe.git](https://github.com/CMU-Perceptual-Computing-Lab/caffe.git)

**GPU version:** RTX 2080 TI

**Comment by R-Raph** [comment]
same problem. its seem that it is because we "Couldn't connect to server" when building the project.
![image](https://user-images.githubusercontent.com/70207357/91171751-4f3f5b80-e6db-11ea-9e26-346463ae4352.png)

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411

**Comment by R-Raph** [comment]
thanks for the quick answer ! Do you know when the server will be running again ?

**Comment by gineshidalgo99** [comment]
Back online!

**Comment by wenxie18** [comment]
I also installed it successfully, but the testing results show nothing, not sure what's wrong.

**Comment by s9443112** [comment]
一堆問題 code也不修
到底在搞什麼東西???

**Comment by s9443112** [comment]
還敢close problem??????
