### ISSUE TITLE
COCO keypoints ground truth has 17 keypoints while displayed as 18 points in this repo

### ISSUE THREAD

**Issue by Wyk951117** [CMU-Perceptual-Computing-Lab/openpose#1680]
Hi,

As the doc in this repo claims, coco format has 18 keypoints, with an extra "neck" point compared to the ground truth of COCO dataset. How did you get the position of this point? Did you average the shoulders or somehow label the dataset manually?

**Comment by gineshidalgo99** [comment]
Yes

**Comment by Wyk951117** [comment]
apparently there are two choices
