### ISSUE TITLE
Different number of frames in OP output (json) and input video (mp4)

### ISSUE THREAD

**Issue by nikhil1702** [CMU-Perceptual-Computing-Lab/openpose#1682]
So I am trying to use OP to get pose estimation for a mp4.
I am on an ubuntu 18.04 using Openpose compiled from source.
I run the command 
`./build/examples/openpose/openpose.bin --net_resolution "-1x256" --video input.mp4 --write_json output_jsons/ --display 0 --render_pose 0 --hand`
without issues. 
Everything so far works great, however the number of json files differs from the number of frames in input.mp4 (usually about +/- 1 frame). 
Is there a way to figure out where that one frame comes from (or rather which frame gets ignored)?
I need to align the number of the frames to the output frames and therefore need to know which frame got dropped. 
Thanks in Advance for any help.

**Comment by gineshidalgo99** [comment]
Usually it's the last frame, so it's not really a big issue for time measurments. That's an OpenCV issue in some videos with some codecs. A possible fix is turning your video into images before running OpenPose, or saving the output OPenPose images when running it (to confirm it's just the last video)
