### ISSUE TITLE
 Models are not downloading niether by cmake or trying manually! [ expected hash / Timeout was reached]

### ISSUE THREAD

**Issue by good-engineer** [CMU-Perceptual-Computing-Lab/openpose#1683]
# Issue Summary
Models are not downloading niether by cmake or trying manually! [ expected hash / Timeout was reached]

### 1. error by cmake :
 expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [28;"Timeout was reached"]

### 2. using terminal and trying manually:
**Command:** 
sudo wget http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel

**Output:**
--2020-08-27 12:33:41--  (try:13)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Connection timed out.
Retrying.

and finally gives up!

### Type of Issue
- Compilation/installation error

### Your System Configuration
**ubuntu 18.04** 
opencv 3

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)? 
latest

3. **General configuration**:   **I have all requirements installed well.** 
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by erinaldi** [comment]
Possibly duplicated issue #1661

**Comment by mkommar** [comment]
Similarly, any 3rd party library downloads for Windows compiling fails. e.g:
http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows/opencv_420_v14_15_2020_04_04.zip

CMake Error at cmake/Utils.cmake:23 (file):
  file DOWNLOAD HASH mismatch

    for file: [C:/Users/Mahesh/Documents/openpose/3rdparty/windows/caffe_15_2020_04_05.zip]
      expected hash: [cd4ec4d709a70c94aa6b151d2d040300]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [28;"Timeout was reached"]

Call Stack (most recent call first):
  CMakeLists.txt:563 (download_zip)

 Your webservice is down.

**Comment by ambigit** [comment]
@frankier do you also have the train and val datasets per chance?

**Comment by frankier** [comment]
Unfortunately not.

**Comment by gineshidalgo99** [comment]
All working now, sorry!

**Comment by GaopoHuang** [comment]
This issues comes up again when I tried to build from CMake. I think the webservice is down again?
