### ISSUE TITLE
OpenPoseDemo.exe Error Prototxt file not found:module\face/pose_deploy.prototxt 

### ISSUE THREAD

**Issue by UEBoy2019** [CMU-Perceptual-Computing-Lab/openpose#1687]
I'm using a local caffe installation and I'm getting this error when I'm running the openpose command from outside of the openpose directory.

This works:
./build/examples/openpose/openpose.bin --video video.mp4 --write_keypoint_json output/

This doesn't work (outside of the openpose directory):
/home/ubuntu/projects/openpose/build/examples/openpose/openpose.bin --video /home/ubuntu/projects/openpose/video.mp4 --write_keypoint_json /home/ubuntu/projects/openpose/output/

**Comment by UEBoy2019** [comment]
solved
first: (precondition:  you must be had models file)
search for file :" pose_deploy.prototxt",and copy it to face ,hand,and other keypoint what you want to write in output.json
If it doesn't work do that 
you should copy release file to models files 
Trust me, it will work

**Comment by tian0124** [comment]
which release file?
