### ISSUE TITLE
Openpose how to change default camera 

### ISSUE THREAD

**Issue by UEBoy2019** [CMU-Perceptual-Computing-Lab/openpose#1688]
Openpose how to change default camera 
such as to use IntelRealSense camera

**Comment by UEBoy2019** [comment]
OK 
u should open the file flags.hpp，and find the DEFINE_int32(camera ,-1) to DEFINE_int32(camera ,1) or 1 to other int number

**Comment by flacle** [comment]
In case you want to try out a particular webcam in the demo, you can pass an integer ID as a parameter. For example:
```
./build/examples/openpose/openpose.bin -camera 3
```
