### ISSUE TITLE
What is the gcc version that needs openpose?

### ISSUE THREAD

**Issue by hdnh2006** [CMU-Perceptual-Computing-Lab/openpose#1689]
### Issue Summary
I am trying to install openpose for the first time and finally when I run `make -j16` I get the error `unsupported GNU version! gcc versions later than 7 are not supported!` I have tried to follow the recommendation given [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/879) by @christian-lanius but It has not been possible to install older versions on my PC (I use Ubuntu 19)

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Errors (if any)
```
In file included from /usr/local/cuda-10.0/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.0/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 7 are not supported!
```

### Type of Issue
Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/TjBJ2KKs

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
Latest

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...? make
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 19
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...): Ubuntu 19
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...? gcc7

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? default
    - **CMake version** (`cmake --version` in Ubuntu): cmake version 3.15.6
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...? 4.2.0

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10
    - **cuDNN version**: 7.5
    - **GPU model** (`nvidia-smi` in Ubuntu): Geforce RTX 2060 SUPER

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...? 3
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.19.1

9. If **Windows** system:
    - Portable demo or compiled library? NA

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed). NA

**Comment by xiangyann** [comment]
Since you indicated you are using Ubuntu 19(.04/.10) which is post 18.04LTS, I'd assumed that CUDA might have accidentally used the default gcc8 when installing. Can you check if the problem persists if you config [nvcc with the -ccbin flag ](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#file-and-path-specifications-compiler-bindir)? [This SO post](https://stackoverflow.com/questions/28009785/cuda-version-x-complains-about-not-supporting-gcc-version-y-what-to-do) might help on how to do that too.

**Comment by gineshidalgo99** [comment]
That's a CUDA issue, for what i see, not an OpenPose issue, so try checking for help for CUDA. Also, we support Ubuntu 18 and 20, not 19, sorry!
