### ISSUE TITLE
how do i choose flir camera

### ISSUE THREAD

**Issue by he1016060110** [CMU-Perceptual-Computing-Lab/openpose#1693]
3d reconstruction is what i want. how do i choose which flir camera to use.
Choose mono or color ones? gige or usb ports?

**Comment by he1016060110** [comment]
Can you list your devices.We don't want to buy the devices which are useless.

**Comment by gineshidalgo99** [comment]
Check the doc, we listed the hardware we used. We are not experts in hardware, but usually any FLIR camera with the same ethernet connection should also work.
