### ISSUE TITLE
pose estimation patent prevents commercial use

### ISSUE THREAD

**Issue by lgwds** [CMU-Perceptual-Computing-Lab/openpose#1699]
Hi,

I am sorry if this is not the right platform to raise this issue, however, it seems there is a patent that includes the use of human pose estimation to evaluate physical exercises (see [patent](https://patents.google.com/patent/US20190362139A1/)). How does this affect acquiring the commercial licence of CMU-Perceptual-Computing-Lab?

**Comment by gineshidalgo99** [comment]
See license details and link from the README, but yeah, the commercial license is not allowed for physical exercise (it is said somewhere on the licencing website)
