### ISSUE TITLE
Image example folder not found (`examples/media/`)

### ISSUE THREAD

**Issue by xray1111** [CMU-Perceptual-Computing-Lab/openpose#17]
### Issue summary
enviroment: Ubuntu 16.04+CUDA8.0+cuDNN5.1+OpenCV3.2.0
Built and installed successfully(mannually compiled), but failed to run any demo example.

### Executed command (if any)
`./build/examples/openpose/rtpose.bin --image_dir examples/media/`

### OpenPose output (if any)
```
Starting pose estimation demo.
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
boost::filesystem::directory_iterator::construct: No such file or directory


Coming from:
- src/openpose/utilities/fileSystem.cpp:getFilesOnDirectory():186
- src/openpose/producer/imageDirectoryReader.cpp:getImagePathsOnDirectory():26

Aborted (core dumped)
```

### Type of issue
- Execution error 
- Help wanted

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
`CUDA Version 8.0.61
`
**cuDNN version**:
`5.1`
**GPU model** (`nvidia-smi`):
```
Mon May  8 20:56:03 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M4            Off  | 0000:82:00.0     Off |                    0 |
| N/A   35C    P0    19W /  75W |      0MiB /  3784MiB |     91%      Default |
+-------------------------------+----------------------+----------------------+
```
Compiler (`gcc --version` on Ubuntu):
```
gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by gineshidalgo99** [comment]
It looks like it did not find the `examples/media/` folder at all.

From the same directory where you executed `./build/examples/openpose/rtpose.bin --image_dir examples/media/`, could you check whether that folder exist? E.g.
`ls examples/media/`

Thanks!

**Comment by xray1111** [comment]
Yes, I'm sure that the directory exists. Now I'm trying to re-compile and re-install boost library, it may because of the library installed by apt-get are mismatch with my compiler

**Comment by DuinoDu** [comment]
It's better to install boost from src. Here is [how to](http://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu).

**Comment by xiaosibai** [comment]
Can you give the data you used to train for the model? I find 189G mdb file from your URL but cannot find raw data.


------------------ 原始邮件 ------------------
发件人: "Duino";<notifications@github.com>;
发送时间: 2017年5月10日(星期三) 下午3:04
收件人: "CMU-Perceptual-Computing-Lab/openpose"<openpose@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [CMU-Perceptual-Computing-Lab/openpose] Examples folder not found(`examples/media/`) (#17)




It's better to install boost from src. Here is how to.

**Comment by gineshidalgo99** [comment]
@xiaosibai , this issue thread is completely unrelated with your question. Even though, OpenPose is a library that uses the already trained model from [https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation). Training steps can be found there and are not related with this library at the moment.

**Comment by gineshidalgo99** [comment]
@DuinoDu Thank you for your help! 
@xray1111 , did DuinoDu steps help you solving the issue?

**Comment by gineshidalgo99** [comment]
Since there is no answer, I will close this thread. Post again if the error persists.
