### ISSUE TITLE
openpose with Qt

### ISSUE THREAD

**Issue by jinnen** [CMU-Perceptual-Computing-Lab/openpose#170]
### Issue summary
Hello, I am making a program for exercise pose aid using openpose. But for my project, I'm trying to create a gui using Qt, but I do not familiar with  linux and qt. 

Can I use qt in openpose? (let me know how to install that TT)  Or you should use qt with sockets in the openpose project,
 but I would appreciate any advice.

 

 

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu):  linux 16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): cuda 8.0
**cuDNN version**: cudnn 6.0
**GPU model** (`nvidia-smi` in Ubuntu): gtx 1060
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows) or OpenCV 2.X or OpenCV 3.X. : open cv 2.x
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu) or CMake (Ubuntu, Windows) or Visual Studio (Windows) : Makefile + Makefile.config
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
I'd first compile OpenPose, and then add it as 3rd party library.

There is most of the Qt configuration file here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/openpose_3d_reconstruction_demo.md#ubuntu

I did this long time ago, there might be some changes. Let me know if it works or if you add something else!

**Comment by gineshidalgo99** [comment]
Other option from Qt + CMake: #271
