### ISSUE TITLE
Version of CudNN in Cuda.make

### ISSUE THREAD

**Issue by ManuelBeschi** [CMU-Perceptual-Computing-Lab/openpose#1701]
Dear Developers,

I found and possibly solved a problem related to CudNN version in Cuda.make and FindCuDNN.cmake.

They look on the CudNN version in the following line:
file(READ ${CUDNN_INCLUDE}/cudnn.h CUDNN_VERSION_FILE_CONTENTS)

however, the version information are in cudnn_version.h.

The line should become
file(READ ${CUDNN_INCLUDE}/cudnn_version.h CUDNN_VERSION_FILE_CONTENTS)

Thanks,
Manuel

**Comment by gembancud** [comment]
Can confirm this works by changing line 237 in cmake/Cuda.cmake
from 
`    file(READ ${CUDNN_INCLUDE}/cudnn.h CUDNN_VERSION_FILE_CONTENTS`
to
`    file(READ ${CUDNN_INCLUDE}/cudnn_version.h CUDNN_VERSION_FILE_CONTENTS`

![image](https://user-images.githubusercontent.com/29444872/93666004-4dd03b80-faad-11ea-8131-06c95ddebef8.png)

**Comment by beniz** [comment]
> EDIT1 :This step however faces a new problem: Caffe isn't fixed to compile on Cuda 11 Cudnn 8.0.3.33

FYI, I did fix Caffe for cudnn8 here: https://github.com/jolibrain/caffe/pull/75 for other purposes.

This apply to our custom version of Caffe, but it'd be straightforward to merge the relevant files into vanilla Caffe.

**Comment by gineshidalgo99** [comment]
Hi, I actually solved all these issues today. Feel free to re-install the latest OpenPose. Let me know if any issues occur, thanks!
