### ISSUE TITLE
Close OpenPose viewer 

### ISSUE THREAD

**Issue by AmazingRachel** [CMU-Perceptual-Computing-Lab/openpose#1703]
#1681 # Issue Summary
I called openpose through my own module, and I tried to close the viewer of openpose but I failed. Please let me know  How could I close the viewer.

### Executed Command (if any)
`op::Wrapper* OpWrapper_;
int Stop()
{
	try
	{
	
			OpWrapper_->stop();
			return -3;

	}
	catch (const std::exception& e)
	{
		op::error(e.what(), __LINE__, __FUNCTION__, __FILE__);
		
		return -2;
	}
	return -1;	
}`

### Errors (if any)

System.AccessViolationException:"Try to read or write to protected memory. This usually indicates that other memory is corrupted."

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc

**Comment by AmazingRachel** [comment]
Update:
Now I use this->stop to close the viewer. But I cannot restart this window unless I stop debugging and restart the solution.

**Comment by gineshidalgo99** [comment]
Not sure if I follow, but if you "just" wanna not show the display ever, simply add the flag for no display (see flags doc)

**Comment by AmazingRachel** [comment]
> Not sure if I follow, but if you "just" wanna not show the display ever, simply add the flag for no display (see flags doc)
Thank you for ur reply!! I want to independently define when it closes and when it opens. Call openpose could open it, but I could not close it when I want it to close. Like I said, I defined the "stop" function myself to close the thread and release camera resource.

**Comment by gineshidalgo99** [comment]
That's a bit more advance than the demos. You'd want to then create your own example following the samples in examples/tutorial_cpp
