### ISSUE TITLE
How to use the env to train my task?

### ISSUE THREAD

**Issue by aqsc** [CMU-Perceptual-Computing-Lab/openpose#1705]
There are many versions about openpose, for example, CMU-Perceptual-Computing-Lab/openpose, openpose_train, openpose_Caffe_train and caffe_rtpose. It's too mush confusing. How to use the env to train my task (car keypoint detection) ? and how to prepare the dataset? especially the data format? Thanks!

**Comment by gineshidalgo99** [comment]
CMU-Perceptual-Computing-Lab/openpose_train has all the training code, openpose is just inference.

The rest are just old.
