### ISSUE TITLE
Question - Combine two 3d estimates of the same movement.

### ISSUE THREAD

**Issue by andreElrico** [CMU-Perceptual-Computing-Lab/openpose#1712]
+ Sorry if thats not the right place to ask (please tell me a better place if possibe)

Im absolutely new to openPose. I have a project idea of having 2 cameras making a video simultaniously from 2 angles (back + side). In order to generate a more accurate 3d estimate.

Has anyone experience with that?

+ syncing the two videos to the exact frame
+ merging the 2 3d-estimates to a "better" one.
+ automating the process as much as possible.

(I want to use 2 samsung smartphones)

**Comment by gineshidalgo99** [comment]
If you have your own 3d camera hardware, then the easiest is to run OpenPose independently on each camera, and then do your own 3D reconstruction later.

**Comment by andreElrico** [comment]
@gineshidalgo99 thank you for jumping in. I hope I can still get some ideas :-)
