### ISSUE TITLE
Help wanted/Question on the Output: How to get the json file output of the keypoints?

### ISSUE THREAD

**Issue by kaktuseis** [CMU-Perceptual-Computing-Lab/openpose#1715]
I used  ./build/examples/openpose/openpose.bin --image_dir examples/media/ --face --hand to get the 2D keypoint detection on imges. This worked fine :). I wonder where (which folder) are the keypoints saved? Or do I have to add a command to create the json file output of the keypoints?

Thanks,
Stefanie

**Comment by tralala878** [comment]
Have you tried adding "--write_json ___/" ? 
Ignore the "" and you can replace ___ with whatever folder name u want. If it is not there, it will create it for you.

For me, the saved folder will be in the same place as the code that you run.
Hope this helps.

**Comment by kaktuseis** [comment]
Yes, it works :)
Thank you!
