### ISSUE TITLE
Running openpose continuously with --image_dir [windows]

### ISSUE THREAD

**Issue by tralala878** [CMU-Perceptual-Computing-Lab/openpose#1716]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Question

My project involves the use of openpose inside Realsense's pipeline. I want to run openpose on an image saved from Realsense in realtime. Hence, I would need openpose --image_dir to run constantly instead of restarting after every saved frame. Is there a way to continuously run openpose on images without re-executing?
Else
Is there a way to let openpose take in a colour stream from Realsense's pipeline? Then, I won't need to run on images and having it restart every time the image changes.

Thank you!

**Comment by gineshidalgo99** [comment]
For any custom functionality like this one, you'd want to create your own code by following the examples/tutorial_cpp samples.

**Comment by tralala878** [comment]
@gineshidalgo99 I am using python to code. Does that affect anything?

**Comment by gineshidalgo99** [comment]
There is an analog one for python samples.

**Comment by tralala878** [comment]
@gineshidalgo99 sorry for the questions even though this is already closed ><
I would like some help with integrating python sample code 04 into my code if that is still possible.

How i initialise openpose:
`# Import Openpose
dir_path = os.path.dirname(os.path.realpath(__file__))

# Change these variables to point to the correct folder (Release/x64 etc.)
sys.path.append(dir_path + '/../../python/openpose/Release');
os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + '/../../x64/Release;' +  dir_path + '/../../bin;'
import pyopenpose as op


# Flags
parser = argparse.ArgumentParser()
# parser.add_argument("--no_display", default=True, help="Enable to disable the visual display.")
args = parser.parse_known_args()

# !!To use openpose in realsense, i need to be able to read image from a folder, then output the json to another folder,
# then realsense use that folder to import the json files
#
# Custom Params (refer to include/openpose/flags.hpp for more parameters)
params = dict()
params["model_folder"] = "../../../models/" # DO NOT CHANGE
params["keypoint_scale"] = 0 # DO NOT CHANGE
params["part_candidates"] = True # to save as 0-24 joints. DO NOT CHANGE
params["camera_resolution"] = "640x360" # DO NOT CHANGE
params["display"] = 0
params["render_pose"] = 0
params["number_people_max"] = 1
# params["image_dir"] = "Test_input_images" # use this if dont want to test the actual image folder
# params["image_dir"] = "Realsense_colour_images" # use this if want test the actual image folder
# params["write_json"] = "Test_input_images_json"
# params["write_json"] = "test"
# params["render_pose"] =

# Add others in path?
for i in range(0, len(args[1])):
    curr_item = args[1][i]
    if i != len(args[1])-1: next_item = args[1][i+1]
    else: next_item = "1"
    if "--" in curr_item and "--" in next_item:
        key = curr_item.replace('-','')
        if key not in params:  params[key] = "1"
    elif "--" in curr_item and "--" not in next_item:
        key = curr_item.replace('-','')
        if key not in params: params[key] = next_item

# Start openpose later. Here is to configure the openpose
opWrapper = op.WrapperPython(3)
opWrapper.configure(params)
opWrapper.start()`

Running openpose in Realsense pipeline after a frame is saved:
`# OpenPose
        imagepath = r'D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\build\examples\tutorial_api_python\Realsense_colour_images\0_colour_frame.png'
        datum = op.Datum()
        imageToProcess = cv2.imread(imagepath)
        datum.cvInputData = imageToProcess
        opWrapper.emplaceAndPop([datum])
        userskele_json_part = datum.poseKeypoints`

However, I am getting errors as shown below:

> 
Starting OpenPose Python Wrapper...

Error:
No output is selected (`--display 0`) and no results are generated (no `--write_X` flags enabled). Thus, no output would be generated. You could also set mThreadManagerMode = mThreadManagerMode::Asynchronous(Out) and/or add your own output worker class before calling this function.

Coming from:
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():79
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():188
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1222
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::start():442
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\python\openpose\openpose_python.cpp:op::WrapperPython::start():190
Traceback (most recent call last):
  File "D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\build\examples\tutorial_api_python\realsense_openpose_T_start+end_V3.py", line 78, in <module>
    opWrapper.start()
RuntimeError:
Error:
No output is selected (`--display 0`) and no results are generated (no `--write_X` flags enabled). Thus, no output would be generated. You could also set mThreadManagerMode = mThreadManagerMode::Asynchronous(Out) and/or add your own output worker class before calling this function.

Coming from:
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():79
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():188
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1222
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::start():442
- D:\STUDIES\YEAR 3 - SEM 1\ESP3902\openpose-master\python\openpose\openpose_python.cpp:op::WrapperPython::start():190

>

**Comment by gineshidalgo99** [comment]
The error says it all.

No output is selected (--display 0) and no results are generated (no --write_X flags enabled). Thus, no output would be generated. You could also set mThreadManagerMode = mThreadManagerMode::Asynchronous(Out) and/or add your own output worker class before calling this function.

Meaning, you need an output. Right now OpenPose would run without generating any output, because you have disabled the UI (params["display"] = 0) and you have not enabled any kind of saving (JSON, PNGs, etc).

**Comment by tralala878** [comment]
@gineshidalgo99 
Thank you for your help.

I tried adding a write_json params like below:
```
params = dict()
params["model_folder"] = "../../../models/" # DO NOT CHANGE
# params["keypoint_scale"] = 0 # DO NOT CHANGE
# params["part_candidates"] = True # to save as 0-24 joints. DO NOT CHANGE
# params["camera_resolution"] = "640x360" # DO NOT CHANGE
params["display"] = 0
params["render_pose"] = 0
params["number_people_max"] = 1
# params["image_dir"] = "Test_input_images" # use this if dont want to test the actual image folder
# params["image_dir"] = "Realsense_colour_images" # use this if want test the actual image folder
params["write_json"] = "Test_input_images_json"

```
But it gave me another error as shown:

> Error:
> You need to have 1 and only 1 producer selected. You can introduce your own producer by using setWorker(WorkerType::Input, ...) or use the OpenPose default producer by configuring it in the configure function) or use the ThreadManagerMode::Asynchronous(In) mode.

So, I tried to google around how to add ThreadManagerMode in python. I only managed to find this:
```
# Start openpose
op_wrapper = op.WrapperPython(op.ThreadManagerMode.AsynchronousOut)
opWrapper = op.WrapperPython(3)
opWrapper.configure(params)
opWrapper.start()
```
But it also gave me an error:

>     op_wrapper = op.WrapperPython(op.ThreadManagerMode.AsynchronousOut)
> AttributeError: module 'pyopenpose' has no attribute 'ThreadManagerMode'

May I know what would be the correct way to debug this?

**Comment by gineshidalgo99** [comment]
You do not need something so complex. You want your own custom input. You can e.g., follow this example:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/04_keypoints_from_images.py

And replace `imagePaths = op.get_images_on_directory(args[0].image_dir);` with your custom real sense code to keep reading images all the time.
