### ISSUE TITLE
Next Windows Portable Release timeline

### ISSUE THREAD

**Issue by nikky4D** [CMU-Perceptual-Computing-Lab/openpose#1717]
Can someone tell me when will the new windows portable executable will be released? The last was in April. Any ideas on a timeline to incorporate the changes to the repo?

Thanks

**Comment by gineshidalgo99** [comment]
Any particular change you need? Because there are not many changes, mostly doc.

**Comment by nikky4D** [comment]
Thanks for the update. I don't have any particular changes. I've used the binary for color images and IR images. As I want to work with the python interface, can you give any advice on how to build the library for windows?

**Comment by gineshidalgo99** [comment]
Yep, just follow the Python doc in the doc/ folder.

**Comment by gineshidalgo99** [comment]
I.e. https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md

**Comment by gineshidalgo99** [comment]
v1.7.0 has been released.

It adds CUDA 11 compatibliity, as well as it includes the Python bindings by first time ever:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.7.0
