### ISSUE TITLE
Keypoint Output Order

### ISSUE THREAD

**Issue by jason2714** [CMU-Perceptual-Computing-Lab/openpose#1719]
Excuse me, when more than one person in the screen, is there any order of key point arrangement? Or the person's key point is in random order?
For example, currently A's key point is in KeyPoint[0], B's key point is in KeyPoint[1], but when next image receive A's key point becomes KeyPoint[1], B's becomes KeyPoint[0] or other index.
Is there any solution to stable the order? Or is there any order rule when setting the array's value?

**Comment by gineshidalgo99** [comment]
No, it is quite random unfortunately, as this is doing frame by frame detection, no tracking.

For tracking, check https://github.com/soulslicer/openpose/tree/staf
