### ISSUE TITLE
Inquiring about researching

### ISSUE THREAD

**Issue by vrjgamer** [CMU-Perceptual-Computing-Lab/openpose#172]
Hello there, my name is vrushabh, I know this not a place to ask this question and I apologize for that, but I couldn't reach u guys on the department website.
I m currently a final year student studying B. tech in NIT Calicut, india. I m planning to go for higher studies for specializing in computer vision. I have read a lot of articles about the Famous CMU robotic institute for computer perception. I really admire the work of this institute. 
So coming to my main question, I wanted to know what is the pre requisite for the course and also what are the things that will help me in getting admitted in this course. 
I m planning to write gre and TOEFL.
Also, I would like to work on porting this openPose repo for Android.

Again sry for asking this question here.

**Comment by gineshidalgo99** [comment]
Our emails appear in both the hiring offer we posted as well as if you click in our names
https://github.com/CMU-Perceptual-Computing-Lab/openpose#latest-news
https://github.com/CMU-Perceptual-Computing-Lab/openpose#introduction
