### ISSUE TITLE
How to get config.cmake files

### ISSUE THREAD

**Issue by kuroneko306** [CMU-Perceptual-Computing-Lab/openpose#1720]
Hello,

I have downloaded the source code and built openpose on windows10, and successfully run the 2D detection using a webcam.
When I try to build the [zed-openpose](https://github.com/adujardin/zed-openpose) project with CMAKE on win10, it shows error messages saying that one of the files with the following names provided by openpose is required.
> OpenPoseConfig.cmake
> openpose-config.cmake

Is there any clue about files with the names?

Thank you very much.

**Comment by gineshidalgo99** [comment]
That repo is not ours, ask in there! :)
