### ISSUE TITLE
Prototxt file not found: models\pose/body_25/pose_deploy.prototxt.

### ISSUE THREAD

**Issue by justinjohn0306** [CMU-Perceptual-Computing-Lab/openpose#1721]
![Capture](https://user-images.githubusercontent.com/34035011/96206344-51f55900-0f86-11eb-8b00-454065ed9087.PNG)

Even tho the models have been downloaded

**Comment by gineshidalgo99** [comment]
Then please, keep reading with 2nd most common issue: "Not running OpenPose from the same directory where the `model` folder is located."

**Comment by Daz0269** [comment]
I've got same problem. Plz,, does anyone solved this problem ?? 
Really need help there..

**Comment by breitnerq** [comment]
Drag the model folder inside the bin folder, it worked for me.

**Comment by Frany-oss** [comment]
@breitnerq What bin folder are you refering to? Because I dont have a bin folder in my openpose.

**Comment by avishchand117** [comment]
> I've got same problem. Plz,, does anyone solved this problem ?? Really need help there..

If you have the models downloaded (found in openpose/models/), you can run openpose outside the directory, so long as you refer to the models folder by '--model_folder'. @gineshidalgo99 was referring to Issue [#164](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/164).

**Comment by yuncengshangdepingyuan** [comment]
![image](https://github.com/CMU-Perceptual-Computing-Lab/openpose/assets/141716071/2541fa4e-9c1c-4eab-9627-6d58296ea5e4)
I Drag the build folder inside the openpose-master folder,that is worked for me.

**Comment by a-alhaouil** [comment]
> Drag the model folder inside the bin folder, it worked for me.

this work, pass all in models folder in 'openpose\build\x64\Release\'
and note that dont let the models in openpose folder,
