### ISSUE TITLE
(winows)Installation - CMake Error in generation process, project files may be invalid

### ISSUE THREAD

**Issue by kaar0** [CMU-Perceptual-Computing-Lab/openpose#1723]
### Issue Summary
Been trying to get OpenPose on my Windows 10 laptop and stuck on this issue for 2 days.

### Executed Command (if any)
pressed "generate" after follosing the installation guide

### Errors (if any)
On CMake:
Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Caffe_LIB_DEBUG
    linked by target "openpose" in directory C:/openpose/src/openpose
Caffe_LIB_RELEASE
    linked by target "openpose" in directory C:/openpose/src/openpose
Caffe_Proto_LIB_DEBUG
    linked by target "openpose" in directory C:/openpose/src/openpose
Caffe_Proto_LIB_RELEASE
    linked by target "openpose" in directory C:/openpose/src/openpose
GFLAGS_LIBRARY_DEBUG
    linked by target "openpose" in directory C:/openpose/src/openpose
GFLAGS_LIBRARY_RELEASE
    linked by target "openpose" in directory C:/openpose/src/openpose
GLOG_LIBRARY_DEBUG
    linked by target "openpose" in directory C:/openpose/src/openpose
GLOG_LIBRARY_RELEASE
    linked by target "openpose" in directory C:/openpose/src/openpose
OpenCV_LIBS_DEBUG
    linked by target "openpose" in directory C:/openpose/src/openpose
OpenCV_LIBS_RELEASE
    linked by target "openpose" in directory C:/openpose/src/openpose

Generating done

In Visual Code, after running the generated file:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'gflags/gflags.h': No such file or directory	OpenPoseDemo	C:\openpose\include\openpose\flags.hpp	9	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'opencv2/core/core.hpp': No such file or directory	openpose	C:\openpose\include\openpose_private\tracking\pyramidalLK.hpp	4	

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK
pu them under "errors"

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
Latest Github Code

3. **General configuration**:
    - **Installation mode**: CMake on windows, tried 3.19 and 3.17.5, same problem appears
    - **Operating system** windows
    - **Operating system version** Windows 10
    - **Release or Debug mode**? (by default: release): ran the vs in release 
    - Compiler Visual Studio 2017
4. **Non-default settings**:
    - **3-D Reconstruction module added**? no
    - Any other custom CMake configuration with respect to the default version? no

5. **3rd-party software**:
    - **Caffe version**: installed is using anaconda in an environment, had to use python 3.7 to do it, otherwise it wouldn't work
    - **CMake version** (`cmake --version` in Ubuntu): 3.19
    - **OpenCV version**: 4.4.0 installed using anaconda

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10
    - **cuDNN version**: 7.5
    - **GPU model** (`nvidia-smi` in Ubuntu):  GeForce MX350

9. If **Windows** system:
    - Portable demo or compiled library?: compiled library

**Comment by kaar0** [comment]
uninstalled opencv 4.4 and installed 3.4.11 and nothing has changed, all errors remain

**Comment by kaar0** [comment]
kept trying, CMake worked without error eventually. However when opening the sln file in VS2019, i still get the error that there are build issues.

**Comment by sfsy1** [comment]
i'm having the same issue as you. I'm on windows 10 using CMAKE 3.19.0 and VS 2019.

**Comment by sfsy1** [comment]
@nikky4D @kaar0 

Ah i got this fixed. You need to make sure you unzip all of the **caffe**, **caffe3rdparty** and **opencv** libraries (that the script downloads for you, or you can download them manually) and put them into the openpose/3rdparty/windows directory.

So for openCV, cmake should be able to find this directory (refer to line 575 of the CMakeLists.txt) :
`openpose/3rdparty/windows/opencv/x64/vc15/lib`

I'm not very familiar with CMake but i believe it's basically a missing directory issue.

**Comment by gineshidalgo99** [comment]
Thanks @sfsy1 for the explanation!

**Comment by kashnisht1** [comment]
> @nikky4D @kaar0
> 
> Ah i got this fixed. You need to make sure you unzip all of the **caffe**, **caffe3rdparty** and **opencv** libraries (that the script downloads for you, or you can download them manually) and put them into the `openpose/3rdparty/windows` directory.
> 
> So for openCV, cmake should be able to find this directory (refer to line 575 of the CMakeLists.txt): `openpose/3rdparty/windows/opencv/x64/vc15/lib`
> 
> I'm not very familiar with CMake but i believe it's basically a missing directory issue.

not able to find the zip files to download. Cloning the openpose github repo gives empty zip files of caffe, caffe3rdparty and opencv. please advise, thank you!
