### ISSUE TITLE
Batch Inference Features in OpenPose

### ISSUE THREAD

**Issue by albertchristianto** [CMU-Perceptual-Computing-Lab/openpose#1727]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
Batch inference is one of useful features while using GPU for computation. Based from the other inference framework libraries(such as OpenCV, PyTorch, etc), the speed performance and the memory consumption, which can be gained by utilizing this features, is a quite a lot. 
I have tried to read the documentation and the code about batch inference, but I can't find it (I probably missed it).
I do find some related issue from 2 years ago. (https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/100).
Has this library implemented the batch inference features? If it has, where can i find the related example documentation?

### Executed Command (if any)
(None)
### OpenPose Output (if any)
(None)
### Errors (if any)
(None)
### Type of Issue
- Question
- Enhancement / offering possible extensions / pull request / etc
### System Configuration
**OpenPose version**: 1.6.0

**Comment by gineshidalgo99** [comment]
It has not been implemented it and we are not planing to do it. That would very slightly increase speed, but hugely and negatively affect latency, that is why we have not spent resources on it.

In this case, the latency of transferring CPU to GPU is not that bad because we are sending a relatively big RGB image. Batch compute usually help with smaller networks with smaller input size, not this case.

**Comment by albertchristianto** [comment]
Thanks for your quick response, @gineshidalgo99 . 

I am aware that batch inference would negatively affect latency for small speed improvement, but there is some problem in multi-view cameras program. So, right now I am in dilemma.
If I spawn 1 OpenPose model and use it for the multi-view cameras (ex. 2 cameras), the FPS will be dropped to the half of original FPS for each camera since the batch size is equal to 1.
but if I spawn 2 OpenPose model, it would cost me a lot in GPU memory. 

Anyway, I think I have no other choice but to read the OpenPose code and implement the batch inference features. Or do you have some suggestion regarding this problem?

**Comment by gineshidalgo99** [comment]
Even if you spam 2 OpenPose's, the speed will still be half.

I already optimized multi-camera to run fast in multi-GPU setup (each image is feed to a different GPU). Even if you implement that GPU functionality, it's gonna cost you a lot of memory as well.

Still, if you really wanna do it, you'd have to check multiple files (the one moving from OpenCV to Caffe memory, the one doing the opposite, making sure to change the batch size from the prototxt, etc). And all of this will only give you a 5-10% speedup. You would get way better speedup by just getting n GPUs for n cameras, which is already implemented in OpenPose to multi-thread 1 camera per GPU!

**Comment by albertchristianto** [comment]
thanks a lot for the information and the suggestion @gineshidalgo99 

I will check the multi-GPU setup after I get more GPU resources from my lab.
