### ISSUE TITLE
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU common.cpp:66 Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by semi-kim** [CMU-Perceptual-Computing-Lab/openpose#1728]
~/openpose$ ./build/examples/openpose/openpose.bin --video examples/media/video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F1023 20:27:05.959867 17384 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
    @     0x7fd86862c0cd  google::LogMessage::Fail()
    @     0x7fd86862df33  google::LogMessage::SendToLog()
    @     0x7fd86862bc28  google::LogMessage::Flush()
    @     0x7fd86862e999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd86819f770  caffe::Caffe::SetDevice()
    @     0x7fd869cba3ff  op::NetCaffe::initializationOnThread()
    @     0x7fd869cde902  op::addCaffeNetOnThread()
    @     0x7fd869cdfdde  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fd869ce5983  op::PoseExtractorNet::initializationOnThread()
    @     0x7fd869cda671  op::PoseExtractor::initializationOnThread()
    @     0x7fd869cd53f1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fd869d19501  op::Worker<>::initializationOnThreadNoException()
    @     0x7fd869d19630  op::SubThread<>::initializationOnThread()
    @     0x7fd869d1b988  op::Thread<>::initializationOnThread()
    @     0x7fd869d1bb57  op::Thread<>::threadFunction()
    @     0x7fd8695b46df  (unknown)
    @     0x7fd868ad26db  start_thread
    @     0x7fd86900fa3f  clone
중지됨 (core dumped)

i just need to process of openpose
what i wrong

**Comment by gineshidalgo99** [comment]
Please fill our GitHub issue template if you need help

**Comment by 10179013** [comment]
./build/examples/openpose/openpose.bin --video examples/media/video.avi 
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0509 14:44:23.677929 25514 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7fd68eee00cd  google::LogMessage::Fail()
    @     0x7fd68eee1f33  google::LogMessage::SendToLog()
    @     0x7fd68eedfc28  google::LogMessage::Flush()
    @     0x7fd68eee2999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd68e8bdd93  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7fd68e9c1d9d  caffe::Net<>::Init()
    @     0x7fd68e9c3e9e  caffe::Net<>::Net()
    @     0x7fd690502eaa  op::NetCaffe::initializationOnThread()
    @     0x7fd6905273e4  op::addCaffeNetOnThread()
    @     0x7fd6905288d6  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fd69052e4d3  op::PoseExtractorNet::initializationOnThread()
    @     0x7fd690523151  op::PoseExtractor::initializationOnThread()
    @     0x7fd69051df01  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fd6905620e1  op::Worker<>::initializationOnThreadNoException()
    @     0x7fd690562210  op::SubThread<>::initializationOnThread()
    @     0x7fd690564568  op::Thread<>::initializationOnThread()
    @     0x7fd690564737  op::Thread<>::threadFunction()
    @     0x7fd68fdf66df  (unknown)
    @     0x7fd68f5186db  start_thread
    @     0x7fd68f85171f  clone
Aborted (core dumped)



how to solve it?
