### ISSUE TITLE
‘class caffe::Blob<int>’ has no member named ‘set_gpu_data’; did you mean ‘set_cpu_data’? on ubuntu 20.04 

### ISSUE THREAD

**Issue by Navan0** [CMU-Perceptual-Computing-Lab/openpose#1729]
`sudo make -j'nproc'` returns  the following error , 

[  0%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/face/openpose_generated_renderFace.cu.o
[  1%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/tracking/openpose_generated_pyramidalLK.cu.o
[  1%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/gpu/openpose_generated_cuda.cu.o
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/hand/openpose_generated_renderHand.cu.o
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_bodyPartConnectorBase.cu.o
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o
[  2%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_maximumBase.cu.o
[  3%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_nmsBase.cu.o
[  3%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_renderPose.cu.o
[  3%] Building CXX object src/openpose/core/CMakeFiles/openpose_core.dir/arrayCpuGpu.cpp.o
CMake Error at openpose_generated_renderFace.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/face/./openpose_generated_renderFace.cu.o

CMake Error at openpose_generated_pyramidalLK.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/tracking/./openpose_generated_pyramidalLK.cu.o

make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:65: src/openpose/CMakeFiles/openpose.dir/face/openpose_generated_renderFace.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at openpose_generated_cuda.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/gpu/./openpose_generated_cuda.cu.o

make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:121: src/openpose/CMakeFiles/openpose.dir/tracking/openpose_generated_pyramidalLK.cu.o] Error 1
CMake Error at openpose_generated_bodyPartConnectorBase.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_bodyPartConnectorBase.cu.o

make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:72: src/openpose/CMakeFiles/openpose.dir/gpu/openpose_generated_cuda.cu.o] Error 1
CMake Error at openpose_generated_maximumBase.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_maximumBase.cu.o

make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:86: src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_bodyPartConnectorBase.cu.o] Error 1
CMake Error at openpose_generated_renderHand.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/hand/./openpose_generated_renderHand.cu.o

CMake Error at openpose_generated_nmsBase.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_nmsBase.cu.o

make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:93: src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_maximumBase.cu.o] Error 1
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:100: src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_nmsBase.cu.o] Error 1
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:79: src/openpose/CMakeFiles/openpose.dir/hand/openpose_generated_renderHand.cu.o] Error 1
CMake Error at openpose_generated_renderPose.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/pose/./openpose_generated_renderPose.cu.o

CMake Error at openpose_generated_resizeAndMergeBase.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ani/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_resizeAndMergeBase.cu.o

make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:107: src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o] Error 1
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/build.make:114: src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_renderPose.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:698: src/openpose/CMakeFiles/openpose.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/ani/openpose/src/openpose/core/arrayCpuGpu.cpp: In instantiation of ‘void op::ArrayCpuGpu<T>::set_gpu_data(T*) [with T = int]’:
/home/ani/openpose/src/openpose/core/arrayCpuGpu.cpp:890:5:   required from here
/home/ani/openpose/src/openpose/core/arrayCpuGpu.cpp:646:38: error: ‘class caffe::Blob<int>’ has no member named ‘set_gpu_data’; did you mean ‘set_cpu_data’?
  646 |                 spImpl->pCaffeBlobT->set_gpu_data(data);
      |                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
      |                 set_cpu_data
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/openpose/core/CMakeFiles/openpose_core.dir/build.make:76: src/openpose/core/CMakeFiles/openpose_core.dir/arrayCpuGpu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:780: src/openpose/core/CMakeFiles/openpose_core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by gineshidalgo99** [comment]
Please fill our GitHub issue template if you need help

**Comment by trkygt** [comment]
I had the same error and solved it with [https://github.com/BVLC/caffe/pull/4527/files](url)

**Comment by rajhlinux** [comment]
I have the same error...
