### ISSUE TITLE
Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device *** Check failure stack trace: 

### ISSUE THREAD

**Issue by semi-kim** [CMU-Perceptual-Computing-Lab/openpose#1730]
![image](https://user-images.githubusercontent.com/30641843/97098243-09dce180-16be-11eb-93bd-ef3dbe283501.png)

demo error

ubuntu18.04
libprotoc 3.6.1
Cudnn7.5
Cuda10.0
caffe do well
i read all of document
![image](https://user-images.githubusercontent.com/30641843/97097699-13168000-16b7-11eb-9acf-0821403c9e7b.png)

**Comment by gineshidalgo99** [comment]
Looks like your GPU is not compatible, which GPU do you have?

**Comment by 47hao** [comment]
Hi, I'm having a similar problem. I'm using a GTX 950m, and I'm not quite sure how to add GPU architecture in Cmake GUI. What should I do from this point?
![image](https://user-images.githubusercontent.com/25371575/97828100-223b9600-1c94-11eb-880c-0e9e96c1c624.png)
![image](https://user-images.githubusercontent.com/25371575/97828384-f66ce000-1c94-11eb-8aa2-8e2f70229bde.png)

**Comment by loiswen** [comment]
> Hi, I'm having a similar problem. I'm using a GTX 950m, and I'm not quite sure how to add GPU architecture in Cmake GUI. What should I do from this point? ![image](https://user-images.githubusercontent.com/25371575/97828100-223b9600-1c94-11eb-880c-0e9e96c1c624.png) ![image](https://user-images.githubusercontent.com/25371575/97828384-f66ce000-1c94-11eb-8aa2-8e2f70229bde.png)

Hello, I also encountered the same problem, can I ask how you solved it?
