### ISSUE TITLE
18_synchronous_custom_all_and_datum.exe 'image_path' error

### ISSUE THREAD

**Issue by softy2k** [CMU-Perceptual-Computing-Lab/openpose#1731]
Hello

I use OpenPose in Windows 10 with GPU card.
Is possible to run **18_synchronous_custom_all_and_datum.exe** with a specific file for input (not a folder) ?

Command line OK  : 
**D:\openpose\bin\18_synchronous_custom_all_and_datum.exe --body 1 --hand -image_dir D:\Input\ -write_images D:\Output -write_json D:\Output**

If I try :
**D:\openpose\bin\18_synchronous_custom_all_and_datum.exe --body 1 --hand -image_path D:\Input\foto.jpg -write_images D:\Output -write_json D:\Output**  

I got  "**Model_18 ERROR: unknown command line flag 'image_path'**"

**Comment by gineshidalgo99** [comment]
Example 18 is meant to have a custom input, so image_path won't work. Use other examples if you want an input
