### ISSUE TITLE
Implementing Openpose images output model on Google Colab: Can anyone share a working colab notebook

### ISSUE THREAD

**Issue by bhavesh2799** [CMU-Perceptual-Computing-Lab/openpose#1736]
I have been taking the help of the google colab helper script, and tried all the installation methods , reinstalling different versions of CUDA, Cmake, etc., but in the notebook there are still configuration errors. I tried the solutions mentioned in the script, but they don't seem to work.
If anyone could share a colab notebook, it would be great!

**Comment by dinatih** [comment]
Hello, here is my colab : https://colab.research.google.com/drive/1VDjRLKAu9KLQky0gv4RLJjeH6NRPiWXy?usp=sharing if it can help.

**Comment by gineshidalgo99** [comment]
Thanks @dinatih  ! Added to the doc/installation/README.md!

**Comment by stanleyshly** [comment]
> Hello, here is my colab : https://colab.research.google.com/drive/1VDjRLKAu9KLQky0gv4RLJjeH6NRPiWXy?usp=sharing if it can help.

I'm trying to run your approach, but I get an error about not being able to create an symbolic link. Do you have any tips for fixing this error?

**Comment by manlio99** [comment]
Hi!
There is any colab with STAF included?

**Comment by kariskerto** [comment]
> Hello, here is my colab : https://colab.research.google.com/drive/1VDjRLKAu9KLQky0gv4RLJjeH6NRPiWXy?usp=sharing if it can help.

hello sir, thanks for your colab. i try your colab and it works well. but it only give output video with motion capture mark, no json or cvs files. so can you tell me the additional code for that colab to add json output too

**Comment by adityab05** [comment]
Is there a google Colab version which can help me get poses for single images instead of video input ?

**Comment by abrar-aw** [comment]
> Hello, here is my colab : https://colab.research.google.com/drive/1VDjRLKAu9KLQky0gv4RLJjeH6NRPiWXy?usp=sharing if it can help.

Hi there, your colab is really helpful! Could you help me find a way to output the results/coordinate values of the OpenPose being applied videos to JSON files please? Thanks

**Comment by rigvedrs** [comment]
A notebook for using open pose on single image still does not seem to be available.

**Comment by davidpagnon** [comment]
@adityab05 @MazieQueen @rigvedrs 
For single images, I believe you can just put your image in an empty directory, and run this line instead (change the parameters between brakets with your own paths)
```
!cd openpose && ./build/examples/openpose/openpose.bin --image_dir {IMAGE_DIRECTORY} --write_json ./output/ --display 0  --write_images {OUTPUT_DIRECTORY}
```

**Comment by davidpagnon** [comment]
I do have an issue though, I keep running into `Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***`. And yet, 
- I executed my colab with GPU, with free 15360MB
- I use CuDNN: `cuDNN             :   Yes (ver. 8.7.0)`
- I tried with minimal computation requirements:  Plain body_25, --display 0 --render_pose 0 --net_resolution -1x16. Still same error.

Would you be able to help me?

**Comment by davidpagnon** [comment]
I finally made it work by running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` to use compatible CUDA and cuDNN versions (see my Sports2D colab: <a href="https://colab.research.google.com/github/davidpagnon/Sports2D/blob/main/Sports2D/Sports2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>)

**Comment by Syed-Hamza-Ali** [comment]
> I finally made it work by running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` to use compatible CUDA and cuDNN versions (see my Sports2D colab: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/davidpagnon/Sports2D/blob/main/Sports2D/Sports2D.ipynb))

Can you please help me out. I'm Having the same error.
/content/openpose/3rdparty/caffe/include/caffe/util/cudnn.hpp: In function ‘const char* cudnnGetErrorString(cudnnStatus_t)’:
/content/openpose/3rdparty/caffe/include/caffe/util/cudnn.hpp:21:8: warning: enumeration value ‘CUDNN_STATUS_VERSION_MISMATCH’ not handled in switch [-Wswitch]

**Comment by davidpagnon** [comment]
Hi, I'm sorry I'm just about to start a new job and I'm in a rush to finish my current one 😅
Did you try copying the steps that are in my colab? Double click on the first cell to access the code.

**Comment by Syed-Hamza-Ali** [comment]
Wow man..!
You really replied...
I have copied and run the pieces of code where you install openpose...
Currently it's running..
But the same warning about cudnn status version mismatch is appearing....
I guess currently it is building the openpose.
I hope this your additional line works...
I'll let you know once the the it run completely

**Comment by Syed-Hamza-Ali** [comment]
> Hello, here is my colab : https://colab.research.google.com/drive/1VDjRLKAu9KLQky0gv4RLJjeH6NRPiWXy?usp=sharing if it can help.

it still gives the error:
CUDNN_VERSION_MIMATCH

**Comment by davidpagnon** [comment]
Hi there, sorry for the delay, I'm quite busy these days... I just saw that Colab recently upgraded to Ubuntu 22.04, which may have broken the install... I'll have to have a deeper look, but to be fairly honest, I'm not sure I can find this time so I'm happy if someone takes over.

**Comment by Syed-Hamza-Ali** [comment]
> Hi there, sorry for the delay, I'm quite busy these days... I just saw that Colab recently upgraded to Ubuntu 22.04, which may have broken the install... I'll have to have a deeper look, but to be fairly honest, I'm not sure I can find this time so I'm happy if someone takes over.

No worries, Thank you for guidance.
And if you are going to update I just want to let you know that it throws an error that your specified Cuda version is not found.
Your sports 2d project gives the same error.

**Comment by davidpagnon** [comment]
Okay so here are my guesses to help you find a solution.
- `!nvidia-smi` gives: Cuda version12.0

**Comment by davidpagnon** [comment]
Okay so here is how I went to figure out the problem, and the solution.

- `!nvidia-smi` gives: Cuda version 12.0
- !nvcc --version`` gives: Cuda version 11.8
--> Hence the CuDNN version mismatch

I previously solved it by force-installing a compatible CUDA / CuDNN combination: `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2`.
The problem is now that Colab has upgraded from Ubuntu 20.04 to Ubuntu 22.04, where this version no longer exists.

[Here are](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/) the supported CUDA versions available for Ubuntu 22.04:  
And [here are](https://pkgs.org/download/libcudnn8) the available CUDA/CuDNN combinations.

If I choose to take the second one (just to be on the safe side, let's not risk upgrading to CUDA 12, I don't know how OpenPose would go with it), this leads me to edit the initial line with `!apt install --allow-change-held-packages libcudnn8=8.9.3.28-1+cuda11.8`.

Could you reset your environment, try changing just that line (watch out, there are two occurrences), and tell me if this works?

**Comment by Syed-Hamza-Ali** [comment]
um now the installation part runs but it gives the following error while using it:
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0727 12:35:53.047664 14590 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***
    @     0x7a5e79ae9b03  google::LogMessage::Fail()
    @     0x7a5e79af19d1  google::LogMessage::SendToLog()
    @     0x7a5e79ae97c2  google::LogMessage::Flush()
    @     0x7a5e79aeb78f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7a5e7971423b  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7a5e797fd699  caffe::Net<>::Init()
    @     0x7a5e797ff610  caffe::Net<>::Net()
    @     0x7a5e7a1e140c  op::NetCaffe::initializationOnThread()
    @     0x7a5e7a18c02b  op::FaceExtractorCaffe::netInitializationOnThread()
    @     0x7a5e7a18d9a6  op::FaceExtractorNet::initializationOnThread()
    @     0x7a5e7a228b95  op::Worker<>::initializationOnThreadNoException()
    @     0x7a5e7a228d08  op::SubThread<>::initializationOnThread()
    @     0x7a5e7a22a708  op::Thread<>::initializationOnThread()
    @     0x7a5e7a22cc3c  op::Thread<>::threadFunction()
    @     0x7a5e79e352b3  (unknown)
    @     0x7a5e79ba5b43  (unknown)
    @     0x7a5e79c37a00  (unknown)
    @              (nil)  (unknown)

**Comment by Syed-Hamza-Ali** [comment]
I have changed the version in  your colabs but itgives this while running the RUN analysis part:
ValueError: max() arg is an empty sequence



---------------------------------------------------------------------
Detect pose for video video.mp4
---------------------------------------------------------------------
Detecting 2D joint positions with OpenPose model BODY_25B, for video.mp4.
Sorting people across frames.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-053f85bef49c>](https://localhost:8080/#) in <cell line: 10>()
      8 get_ipython().run_line_magic('cd', '$result_path')
      9 with open('Config.toml', "w") as config_file: toml.dump(config_dict, config_file)
---> 10 Sports2D.detect_pose('Config.toml')
     11 Sports2D.compute_angles('Config.toml')

2 frames
[/usr/local/lib/python3.10/dist-packages/Sports2D/Sports2D.py](https://localhost:8080/#) in detect_pose(config)
    174     start = time.time()
    175 
--> 176     detect_pose_fun(config_dict)
    177 
    178     end = time.time()

[/usr/local/lib/python3.10/dist-packages/Sports2D/detect_pose.py](https://localhost:8080/#) in detect_pose_fun(config_dict)
    590 
    591     # Sort people and save to csv, optionally display plot
--> 592         json_to_csv(json_path, frame_rate, pose_model, interp_gap_smaller_than, filter_options, show_plots)
    593 
    594     # Save images and files after reindentification

[/usr/local/lib/python3.10/dist-packages/Sports2D/detect_pose.py](https://localhost:8080/#) in json_to_csv(json_path, frame_rate, pose_model, interp_gap_smaller_than, filter_options, show_plots)
    290     logging.info('Sorting people across frames.')
    291     json_fnames = list(json_path.glob('*.json'))
--> 292     nb_persons_to_detect = max([len(json.load(open(json_fname))['people']) for json_fname in json_fnames])
    293     Coords = [np.array([]).reshape(0,keypoints_nb*3)] * nb_persons_to_detect
    294     for json_fname in json_fnames:    # for each frame

ValueError: max() arg is an empty sequence

**Comment by davidpagnon** [comment]
It probably means that there is no output json file.

Did you do the Google drive install (install once) or the other one? You need to delete the folder on your drive and to disconnect and restart Colab for the changes to take action.

Did you also try that simpler command after instead of running the whole Sports2D flow?
```
!cd $openpose_path
!build/examples/openpose/openpose.bin --video examples/media/video.avi --display 0 --render_pose 0 --write_json examples/media/json```

**Comment by Syed-Hamza-Ali** [comment]
> It probably means that there is no output json file.
> 
> Did you do the Google drive install (install once) or the other one? You need to delete the folder on your drive and to disconnect and restart Colab for the changes to take action.
> 
> Did you also try that simpler command after instead of running the whole Sports2D flow?
> 
> ```
> !cd $openpose_path
> !build/examples/openpose/openpose.bin --video examples/media/video.avi --display 0 --render_pose 0 --write_json examples/media/json```
> ```

Yeah I add that line in other code but it it did the  CUDNN error .
while running the Sports2D I ran install everytime. After installation I ran this command
> !cd $openpose_path
> !build/examples/openpose/openpose.bin --video examples/media/video.avi --display 0 --render_pose 0 --write_json examples/media/json```
But there was no openpose.bin file it was openpose.cpp file 

which threw the arror of no such file directory exist

**Comment by AlmaDev40** [comment]
Hello @Syed-Hamza-Ali 

I did the same changes as you and the installation part seems ok. However I obtain the same error about openpose.bin file not existing. Did you find any solution to install Openpose with collab? Thanks in advance!

**Comment by Syed-Hamza-Ali** [comment]
> Hello @Syed-Hamza-Ali
> 
> I did the same changes as you and the installation part seems ok. However I obtain the same error about openpose.bin file not existing. Did you find any solution to install Openpose with collab? Thanks in advance!

Nope I didn't find any solution... I was told by a fellow that due to collab updation all the projects made on collab using Openpose has been crashed.
.
So I decided to use Mediapipe instead. It's a lot similar to openpose

**Comment by davidpagnon** [comment]
Still the same issue of hash mismatch on my [Sports2D](https://bit.ly/Sports2D_Colab) colab. 

```
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [7;"Couldn't connect to server"]

Call Stack (most recent call first):
  CMakeLists.txt:985 (download_model)
```

Running twice the following line seems like it solves the error:


https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1588
Hello there, 

I have no idea why it would work, but it seems like I made it work. See [here for an implementation].

Here is the error I faced, caused by the line 



```
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [7;"Couldn't connect to server"]

Call Stack (most recent call first):
  CMakeLists.txt:985 (download_model)
```

For some reason, if I run the line twice, it works totally fine... Well, I may not get it, but I'll take it anyway. And if someone can explain, I'm interested, as always :)

**Comment by davidpagnon** [comment]
I fixed it on my end by downloading the body_25 model from a google drive source. (see [there](https://bit.ly/Sports2D_Colab) for the whole install in Colab)

```
!pip install gdown
!gdown 1jehFU9xsxEpxRuOEUgA5jaCutR4l9X8a
!mv pose_iter_584000.caffemodel $openpose_path/models/pose/body_25/pose_iter_584000.caffemodel
```
