### ISSUE TITLE
Ubuntu install caffe and openpose script fails on fresh install of ubuntu 16.04

### ISSUE THREAD

**Issue by neilthomson** [CMU-Perceptual-Computing-Lab/openpose#174]
I installed CUDA then copied cudnn into cuda-8.0 folder as instructed and ran the ./ubuntu/install_caffe script.

It fails for 2 reasons:

The script doesn't check if pip is installed and so the line that installs numpy and protobuf crashes the script as pip is not installed by default on a fresh ubuntu 16.04 install

It then fails again because it looks for numpy in /usr/lib/python2.7/dist-... when pip install numpy puts it into /usr/local/lib/python2.7/dist-... Perhaps apt-get install python-numpy puts it in the former?

When those two lines are amended in the Makefile.config and insatall_caffe script it runs fine.

**Comment by gineshidalgo99** [comment]
Hi, the script has now being fixed to install pip and install numpy in the right place (with apt-get install). Thanks!
