### ISSUE TITLE
OpenPose not working with Python3

### ISSUE THREAD

**Issue by bongbonglemon** [CMU-Perceptual-Computing-Lab/openpose#1740]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

`python3 01_body_from_image.py `

### Errors (if any)

`Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
dlopen(../../python/openpose/pyopenpose.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: ../../python/openpose/pyopenpose.so
  Expected in: flat namespace
 in ../../python/openpose/pyopenpose.so`

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: [LINK](https://pastebin.com/gRYZLdmt)

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

OpenPose Latest Release v1.6.0

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...? CMake
    - **Operating system** (`lsb_release -a` in Ubuntu): MacOS
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):  macOS Catalina Version 10.15.4
    - **Release or Debug mode**? (by default: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...? No idea what's this sorry

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? Downloaded my own using `brew install caffe`
    - **CMake version** (`cmake --version` in Ubuntu): cmake version 3.18.4
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...? 4.4.0

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**: 1.6Ghz Dual-Core Intel Core i5
    - Total **RAM memory** available: 8 GB 1600 MHz DDR3

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...? Python 3.9.0
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.19.3

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by giuseppenovielli** [comment]
Yes me too!! Same Error!!

**Comment by bongbonglemon** [comment]
Hi @giuseppenovielli what a coincidence. I have actually since found [a solution on stackoverflow](https://stackoverflow.com/questions/29245558/how-to-link-with-python3-libs-with-cmake) that worked me.

The solution was to go into the CMakeLists.txt file and add an "additional versions" directive ABOVE the find_package:

set(Python_ADDITIONAL_VERSIONS 3.4)
find_package(PythonLibs 3 REQUIRED)

**Comment by giuseppenovielli** [comment]
@bongbonglemon I add this two line:

set(Python_ADDITIONAL_VERSIONS 3.4)
find_package(PythonLibs 3 REQUIRED)

into file openpose/CMakeLists.txt

openpose is the main directory

Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
cannot import name 'pyopenpose' from partially initialized module 'openpose' (most likely due to a circular import) (../../python/openpose/__init__.py)

**Comment by bongbonglemon** [comment]
@giuseppenovielli Have you configured and generated again in Cmake?

**Comment by giuseppenovielli** [comment]
@bongbonglemon yes, i have open Cmake 3.18.4 and i Click -> Configure and next Generate

This are the log from cmake

Found PythonLibs: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "3.9.0", minimum required is "3") 
GCC detected, adding compile flags
Building with OpenCL.
Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
${Caffe_INCLUDE_DIRS} set by the user to /Users/hrcoffee2/Desktop/openpose_build/openpose/build/caffe/include
${Caffe_LIBS} set by the user to /Users/hrcoffee2/Desktop/openpose_build/openpose/build/caffe/lib/libcaffe.dylib
Download the models.
Downloading BODY_25 model...
Model already exists.
Downloading body (COCO) model...
Model already exists.
Downloading body (MPI) model...
Model already exists.
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
fatal: not a git repository (or any of the parent directories): .git

pybind11 v2.3.dev0
Configuring done
Generating done

**Comment by giuseppenovielli** [comment]
@bongbonglemon yes, i have open Cmake 3.18.4 and i Click -> Configure and next Generate

This are the log from cmake

Found PythonLibs: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "3.9.0", minimum required is "3") 
GCC detected, adding compile flags
Building with OpenCL.
Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
${Caffe_INCLUDE_DIRS} set by the user to /Users/<user>/Desktop/openpose_build/openpose/build/caffe/include
${Caffe_LIBS} set by the user to /Users/<user>/Desktop/openpose_build/openpose/build/caffe/lib/libcaffe.dylib
Download the models.
Downloading BODY_25 model...
Model already exists.
Downloading body (COCO) model...
Model already exists.
Downloading body (MPI) model...
Model already exists.
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
fatal: not a git repository (or any of the parent directories): .git

pybind11 v2.3.dev0
Configuring done
Generating done

**Comment by bongbonglemon** [comment]
You are using Python 3.9.0 so can you change it to

`set(Python_ADDITIONAL_VERSIONS 3.9)` in CMakeLists.txt accordingly? This is actually what I used. The one I posted above was just the answer from the stackoverflow which I copy and pasted for easy reference. Sorry for any confusion.

**Comment by giuseppenovielli** [comment]
@bongbonglemon 

set(Python_ADDITIONAL_VERSIONS 3.9) update to CMakeLists.txt
Configure and Generate with Cmake 3.18.4

SAME ERROR

<macname>:tutorial_api_python hrcoffee2$ python3 01_body_from_image.py
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
cannot import name 'pyopenpose' from partially initialized module 'openpose' (most likely due to a circular import) (../../python/openpose/__init__.py)
<macname>:tutorial_api_python hrcoffee2$

**Comment by bongbonglemon** [comment]
Hi. Firstly, if you getting frustrated, you should take a moment to calm and clear your head. If its any consolation I spent 3-4 days to install openpose. What I'll say now is that your error is actually different from the one I put in this Issue. Mine was specifically `dlopen(../../python/openpose/pyopenpose.so, 2): Symbol not found: __PyThreadState_Current Referenced from: ../../python/openpose/pyopenpose.so Expected in: flat namespace in ../../python/openpose/pyopenpose.so` 

while yours is `cannot import name 'pyopenpose' from partially initialized module 'openpose' (most likely due to a circular import) (../../python/openpose/init.py)`. 

I didn't noticed this at the start because you said that we had the same error. But it is different so thats why my solution is not working for you. I think this is the Github issue page you should be on: [https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1623](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1623)

**Comment by giuseppenovielli** [comment]
@bongbonglemon no after add this lines

set(Python_ADDITIONAL_VERSIONS 3.4)
find_package(PythonLibs 3 REQUIRED)

Erros Will become

`cannot import name 'pyopenpose' from partially initialized module 'openpose' (most likely due to a circular import) (../../python/openpose/init.py)`

But before was 
`2): Symbol not found: __PyThreadState_Current Referenced from: ../../python/openpose/pyopenpose.so Expected in: flat namespace in ../../python/openpose/pyopenpose.so`

**Comment by bongbonglemon** [comment]
@giuseppenovielli AHHH so I did help a bit. I say that because I actually remember having the circular import error too. So I think you are on the right track yet I sadly did not take note of how I overcame it. Do you have a discord? We can quickly compare settings.

**Comment by chn-lee-yumi** [comment]
I want to use python3.8, but it output `pyopenpose.cpython-37m-darwin.so` (I have two versions: python3.8 installed by MacOS, python3.7 installed by brew). So it will show:

```
ImportError: cannot import name 'pyopenpose' from 'openpose' (/Users/***/PycharmProjects/home_cam/openpose/__init__.py)
```

I try to add someting to `CMakeLists.txt`:

```
set(PYTHON_VERSION_MAJOR 3)
set(PYTHON_VERSION_MINOR 8)
set(PYTHON_LIBRARY /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/config-3.8-darwin/libpython3.8.dylib)
set(PYTHON_INCLUDE_DIRS /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8)
set(PYTHON_INCLUDE_DIR /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8)
find_package(PythonLibs 3.8 MODULE REQUIRED)
```

It output the same filename `pyopenpose.cpython-37m-darwin.so`, but when I renamed it to `pyopenpose.cpython-38-darwin.so`, it could be imported successful!

Hope it will help someone.
