### ISSUE TITLE
Compatibility with NVIDIA Geforce RTX 3080?

### ISSUE THREAD

**Issue by diepgfai** [CMU-Perceptual-Computing-Lab/openpose#1741]
Did anyone try running Openpose with the new graphic card NVIDIA Geforce RTX 3080? I just want to ask before I make the purchase.

**Comment by gineshidalgo99** [comment]
It should now work!

**Comment by templarares** [comment]
Hi Gienshidalgo,

We've just deployed openpose on our "RTX3080 + CUDA 11.1.1 +CuDNN8.0.5 + VS2019" desktop. CMake and VS Building both went with no warnings/errors. But when we tried "openposedemo.exe -image_dir examples/media" or "-video examples/media/video.avi" or any other examples (e.g., 01body_from_image), openpose always got stuck at a pop-out black screen after "starting threads" and became "non-responding". No error messages or whatsoever. We then built openpose with "CPU_only" mode, which worked out nicely (though very slow). Could you please help shed some light on this? We really want to utilize the hight performance of RTX3080. Thanks a lot in advance!

(We have conducted some very basic debugging... the process always gets stuck at OP.wrapper.exec()

**Comment by gineshidalgo99** [comment]
I do not have a 30XX to try, so that makes it harder to debug, but please, check 1747.
I'm planning to have a solution this weekend and I'll post it in 1747, so please, subscribe for notifications in 1747 so you can know when the fix is pushed.
Sorry for the troubles!

**Comment by templarares** [comment]
thanks for your quick response, Gines. Really grateful for your support! Will be following 1747, and update there if necessary. Thanks again!

**Comment by richardun** [comment]
I created another post about my install woes... I have an RTX 3080.  @gineshidalgo99 , I can grant you TeamViewer access to my computer if you like to run some tests / debug.  Happy to trade that in exchange for getting help making it work.  I'm excited to see what this is capable of.  :)

**Comment by gineshidalgo99** [comment]
See #1747
