### ISSUE TITLE
Can't build open pose for CPU only build

### ISSUE THREAD

**Issue by sshuvro58** [CMU-Perceptual-Computing-Lab/openpose#1746]
I have followed every instruction for CPU only build , everything went as expected , but when I ran the final command , inside build directory  `make -j nproc`

I get the following error 

```
-- Configuring incomplete, errors occurred!

CMake Warning:
  Value of caffe_LIB_DEPENDS contained a newline; truncating
```

I am using Ubuntu 20

**Comment by gineshidalgo99** [comment]
Hi, please, completely remove OpenPose, re-clone the latest version, and try again! Hopefully it should now work. Otherwise, please, fill the complete issue template that you ignored when filling this issue. Thanks!

( just git pulling won't work given my changes )
