### ISSUE TITLE
[Win10] [Release v1.6.0] OpenPose does not show anything when starting pre-built binaries v1.6.0

### ISSUE THREAD

**Issue by fweidner** [CMU-Perceptual-Computing-Lab/openpose#1747]
### Issue Summary
I want to try the pre-built binaries ```openpose-1.6.0-binaries-win64-gpu-python-flir-3d_recommended```. When I execute the command from [QuickStart v1.6.0](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/v1.6.0/doc/quick_start.md#running-on-video) to test it with video, a window opens up but it stays gray/black. OpenPoseDemo continues to consume about 10% CPU load but nothing happens. After a time, the usual Windows "Not responding" appears.

Q: How can I run OpenPoseDemo?

### Executed Command (if any)
From Powershell: 
```
bin\OpenPoseDemo.exe --logging_level 0 --disable_multi_thread --video examples\media\video.avi
```

### OpenPose Output (if any)
```
Starting OpenPose demo...
Configuring OpenPose...
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():210
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducerType():170
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToPoseMode():11
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToPoseModel():33
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToScaleMode():82
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToHeatMapScaleMode():116
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToDetector():147
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToDetector():147
Starting thread(s)...
Running configureThreadManager...
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\producer\producer.cpp:op::createProducer():417
renderModePose = 3
renderModeFace = 3
renderModeHand = 3
renderOutput = 1
renderOutputGpu = 1
renderFace = 0
renderHand = 0
renderHandGpu = 0
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():17
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():184
userInputAndPreprocessingWsEmpty = 1
userOutputWsEmpty = 1
numberGpuThreads = -1
gpuNumberStart = 0
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
writeImagesCleaned =
writeKeypointCleaned =
writeJsonCleaned =
writeHeatMapsCleaned =
modelFolder = models\
finalOutputSize = [1280,720]
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():371
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():436
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():441
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():452
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():506
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():558
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():602
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():646
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():663
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():680
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():699
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():715
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():748
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():773
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():782
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():798
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():799
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():808
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():825
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():845
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():866
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():875
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():879
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():885
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():944
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():960
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():966
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1042
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1076
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1180
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1204
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1211
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():419
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::exec():185
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > >::addPusher():362
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > >::addPusher():362
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > >::addPusher():362
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::exec():190
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::threadFunction():182
D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::initializationOnThread():167
Starting initialization on thread. In D:\Users\gines\Dropbox\Perceptual_Computing_Lab\openpose\openpose\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():172
```

### Errors (if any)
* OpenPose window appears bu no visual output is displayed
* Program stops responding (I can stop it with CTRL+C, though)

### Type of Issue
- Execution error
- Help wanted

### Your System Configuration
1.  **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: 
    - [Powershell error output on PasteBin](https://pastebin.com/sruGRmZ1)
    - [Output of systeminfo on Powershell](https://pastebin.com/eWMtWxHf) 

2. **OpenPose version**: 
* Release version v1.6.0 
* openpose-1.6.0-binaries-win64-gpu-python-flir-3d_recommended

3. **General configuration**:
    - **Installation mode**: Pre-build binaries from release version
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows
    - **Operating system version** Microsoft Windows 10 Education 10.0.19041 N/A Build 19041
    - **Release or Debug mode**? Release

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.18.4
    - **OpenCV version**: OpenPose default (only Windows)

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 11.1
    - **cuDNN version**: 8.0.4
    - **GPU model** (`nvidia-smi` in Ubuntu): NVIDIA RTX 3070

7. If **CPU-only mode** issue:
    - **CPU brand & model**:7-5820K CPU @ 3.30GHz, 3301 Mhz, 6 Core(s), 12 Logical Processor(s)
    - Total **RAM memory** available: 32GB

9. If **Windows** system:
    - Portable demo

**Comment by gineshidalgo99** [comment]
Actually, the binary was created with CUDA 10, so it might not be compatible with 30XX graphic cards yet!

Compiling OpenPose from scratch from Visual Studio should work in your case (assuming you have CUDA 11.1). Let me know if this works! If that's the case, I will try to push a 1.6.1 with CUDA 11 (although it might break compatibility with very old graphic cards, because CUDA 11 dropped support for some, that's why i'd like to first make sure that would solve your issue).

Thanks!

**Comment by fweidner** [comment]
Thanks for the swift response. 

I'll give it a try. Should I compile the most recent commit or the 1.6.0 version?

**Comment by gineshidalgo99** [comment]
Actually, I just remember that the Caffe version used in Windows is pre-compiled with CUDA 10. So I will have to re-compile Caffe with CUDA 11 before you can try it in Windows, sorry about this problem. Give me about this weekend, and I should give you an updated 1.6.1 with CUDA 11 compatibility. Sorry for the troubles!

**Comment by fweidner** [comment]
Hi, just saw that caffe loads CUDA 10 :). 

For the records, the error appearing at my end after i want to start the compiled OpenPoseDemo from within Visual Studio 2019 Enterprise is the following:
```
The procedure entry point cblas_dasum could not be located in the dynamic link library C:\path-to-openpose\3rdparty\windows\caffe\bin\caffe.dll.
```

Thanks for the the effort. I really appreciate it!

**Comment by gineshidalgo99** [comment]
Hi @luojc123 @richardun @diepgfai @templarares @fweidner  ,

I have pushed to GitHub the latest OpenPose working (hopefully!) with CUDA 11 and cuDNN 8 in both Windows and Ubuntu.

Note: OpenPose v1.6.0 binaries will never work with CUDA 11 / RTX 30XX cards, I am talking about the source code itself.

In a few days I will push OpenPose v1.7.0 (and its Windows pre-compiled binaries), so people won't need to compile OpenPose on Windows. However, before doing that, I'd like to ask you all to confirm whether the latest OpenPose is working with your RTX
30XX card.

Please, post here whether it works or not (and your OS: Windows or Ubuntu), or the new bugs if not!

Thanks

**Comment by fweidner** [comment]
HI, 

I can successfully build OpenPose in Release mode but I'm **unable** to run it. (Win10, RTX 3070 w/ 457.30 drivers, Cuda11.1, cuDNN8)

For reproducability, I started with an empty project and took the following steps during setup:
In Powershell:
* git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
* cd openpose/
* git submodule update --init --recursive --remote
* mkdir build
* cd build
* cmake-gui ..

In CMake
* Configure
* Select VS16 2019 and x64
* OpenCV_LIBS_DEBUG and OpenCV_LIBS_RELEASE not detected automatically
  Set them to C:/Projects/OpenPose/openpose/3rdparty/windows/opencv/x64/vc15/lib/opencv_world420d.lib and C:/Projects/OpenPose/openpose/3rdparty/windows/opencv/x64/vc15/lib/opencv_world420.lib (also tried the vc14 versions - same error)
* Generate
* OpenProject

In VS Studio: 2019 Enterprise
* set to release
* Build solution (F7); Log: [build log](https://pastebin.com/XLwXUiCR)
* Run (F5); Log: [run log](https://pastebin.com/vqL4R1dZ)

And here is the error message that appears: 

![Screenshot 2020-11-15 163748](https://user-images.githubusercontent.com/16336130/99189403-4d78b780-2761-11eb-92a8-f8140483c4ac.png)

![Screenshot 2020-11-15 164753](https://user-images.githubusercontent.com/16336130/99189628-6fbf0500-2762-11eb-8441-498a79d6c106.png)

**Comment by gineshidalgo99** [comment]
@fweidner  Thanks for the logs, that was super useful!

I just found: The reason your machine particularly is having that crash is most probably because it is linking to Octave *.DLL files (no clue why!).

If you see your log:
`
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Octave\Octave-5.2.0\mingw64\bin\libopenblas.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Projects\OpenPose\openpose\3rdparty\windows\caffe\bin\caffehdf5.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cublasLt64_11.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Octave\Octave-5.2.0\mingw64\bin\libxerbla.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Octave\Octave-5.2.0\mingw64\bin\libgcc_s_seh-1.dll'. Module was built without symbols.
`

Probably I have forgotten some DLL and that is why your machine is trying to link against Octave DLLs for some reason. In the meantime, could you (just provisionally!) rename `C:\Octave\Octave-5.2.0\mingw64\bin\` as `C:\Octave\Octave-5.2.0\mingw64\bin_\` and re-run OpenPose? That way OpenPose will tell you which DLLs is missing, just to confirm whether it's libopenblas.dll or also some other. Thanks!

(in the meantime, I am also trying to figure out where to get the "real" and right openblas.dll)

**Comment by gineshidalgo99** [comment]
I've just checked, OpenPose ships with that DLL. After you compile OpenPose, it is located in build/bin/libopenblas.dll

This means your Octave mingw64 is conflicting with Visual Studio. You should probably remove Octave from your Windows environment path. It is not really an OpenPose-related error. After trying my workaround explained before (renaming that `bin` as `bin_`), OpenPose should hopefully just works in your machine. Please, let me know whether this is the case! :)

**Comment by fweidner** [comment]
Your're golden! It was indeed the conflicting libopenblas.dll. 
Now it runs like a charm! 😄👍🏻

**Comment by gineshidalgo99** [comment]
Nope, that was exactly the confirmation I needed! 30XX working on Windows then!

I'll then try to release 1.7.0 after fixing a last issue I have (Ubuntu 20 CPU-only compatibility, it's a nightmare to re-compile everything for every new OS or VS or CUDA...), and then you should be good to go with the portable binaries!

**Comment by richardun** [comment]
Hi.  Since the other ticket was closed, I'll post here.  I followed the exact steps as Florian above.  In CMake, on configure, I noticed I too was missing the same variables for OpenCV... I created "entries" for these before configuring... and got a notice that an error had occurred. "Error in configuration process, project files may be invalid"

The output still had these errors (as before).  Full log here: https://pastebin.com/xtEfQgXT
```
CMAKE_VERSION = 3.19.0-rc3
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindCUDA.cmake:786 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)


CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindCUDA.cmake:787 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)
```
The only other "NOTFOUND" variable in configuration is CUDA_SDK_ROOT_DIR.

Should I make sure this is set to something and will that get rid of this error in Cmake?

Thanks.

**Comment by richardun** [comment]
@gineshidalgo99, I believe OpenCV 4.2.0 should be "VS2019 ready," but the "FindCUDA" errors I'm getting seem to indicate it's an issue with OpenCV since FindCUDA is from OpenCV.  Also, It's up to 4.5.0.  I may try to install 450 libs to see if it makes a difference.  Thanks again for your help.

**Comment by richardun** [comment]
I tried a configuration / generate / open with the latest (OpenCV 450) libs.  Same result.  I didn't blow away the original build folder because this is where I added the new CV files (450), but I added new variables for these versions.

**Comment by fweidner** [comment]
CUDA_SDK_ROOT_DIR. is empty for me as well.

Seems to me like the problem is with you cmake or CUDA installation? Btw, I use cmake 3.18.4

**Comment by richardun** [comment]
@fweidner , you may be right... Here is how I'm installing it if you wouldn't mind confirming it's how you did it as well.
I am using these:
![image](https://user-images.githubusercontent.com/87189/99279354-c295cc80-27f5-11eb-9cca-279717600e09.png)

1. run cuda_11.1.1_456.81_win10.exe and follow steps installing everything (not custom)
2. then I extract and copy everything in cudnn-11.1-windows-x64-v8.0.5.39 to the cuda folder, which adds its files to existing folders there

I also have manually created various system environment variables for CUDA, CUDA_PATH, and CUDA_TOOLKIT_ROOT_DIR.

Anything else?  Diff versions?  I'm going to remove cmake and install 3.18.  Then reinstall CUDA and cuDNN and try it all over again.  Let me know if you notice anything please.

Thanks!

**Comment by fweidner** [comment]
I've used cuda_11.1.1_win10_network.exe and cudnn-11.1-windows-x64-v8.0.4.30 for installation. 
Also, I these are variables are on my path (auto-generated)
![image](https://user-images.githubusercontent.com/16336130/99280192-5a64dc00-2831-11eb-9bd4-2d9cf140ac3c.png)
and the following system variable is also in my environment (also auto-generated): 
![image](https://user-images.githubusercontent.com/16336130/99280306-7a949b00-2831-11eb-8b5c-c583b4437a94.png)

**Comment by richardun** [comment]
It appears I have those also.  There was some error along the way in my cmake where it couldn't find CUDA so I created other the other variables I mentioned... but I have these other ones you mentioned auto-generated as well.

I installed cudnn 8.0.5.39 because the windows-prerequisites section says it's tested extensively with 8.0.5.  @gineshidalgo99 this combination I have should work, right?  cuda 11.1.1 and cudnn 8.0.5 as I show above.

I'm installing cmake 3.18.4 as you have, Florian, just to make sure.  Thanks.

**Comment by richardun** [comment]
Same error as before.  I'm going to install cuDNN 8.0.4 over cuda 11.1.1 next.

**Comment by richardun** [comment]
Still got the same configuration error:  https://pastebin.com/j2rkv1a1
After adding the two variables you mention (OpenCV_LIBS_DEBUG and OpenCV_LIBS_RELEASE) to the 420 versions, it generated fine:  https://pastebin.com/wEKwY8tY

Opened project in VS 2019 (Community), Release already set, ran and got this:
![image](https://user-images.githubusercontent.com/87189/99283973-50c08180-27fb-11eb-9372-3bae6d67ca42.png)
Hit "Yes"... get this:
![image](https://user-images.githubusercontent.com/87189/99284074-72216d80-27fb-11eb-8686-61e5ed680b76.png)

I feel like those FindCUDA errors I'm getting in config are part of this problem, but I don't see what I'm doing wrong. I've installed it several times.

**Comment by richardun** [comment]
\openpose\build\x64\Release\ is empty... I'm guessing this is because configuration or generate didn't work properly although it gives no further errors.

**Comment by fweidner** [comment]
The [FindCUDA](https://cmake.org/cmake/help/latest/module/FindCUDA.html) doc mentions the following:

"It might be necessary to set CUDA_TOOLKIT_ROOT_DIR manually on certain platforms, or to use a CUDA runtime not installed in the default location."

So maybe play around with that var.

**Comment by richardun** [comment]
Thanks.  I already had this set.  I updated the Graphics card firmware, it's now on 457.30 just like yours.  Rebuilt the "build" folder just in case... same result with the FindCUDA error I reference above.

@gineshidalgo99, I would love your help... not sure what else to try or where I went wrong.

**Comment by richardun** [comment]
Here is my VS Community 2019 - 16.8.1 component list:
![image](https://user-images.githubusercontent.com/87189/99326459-fd235780-283d-11eb-9df7-2d23bc7dbbd4.png)
![image](https://user-images.githubusercontent.com/87189/99326724-11ffeb00-283e-11eb-8c97-e1a393f4caa9.png)
![image](https://user-images.githubusercontent.com/87189/99326775-25ab5180-283e-11eb-8bbc-3e35b106eb37.png)

**Comment by gineshidalgo99** [comment]
OpenCV being missing is a bug that i solved in the latest GitHub code. Could you remove your current OpenPose and try again with the latest version of OpenPose?

And then, if you have errors with the latest version, please create a new GitHub issue, and follow all the instructions of the GitHub issue template (so that way I can get all the details of your CMake output as pastebin, your hardware, OS, GPU, etc). Thanks!

**Comment by gineshidalgo99** [comment]
Given that 30XX card is working for @fweidner , i'll close this issue.

Please, if you have errors with the latest version, create a new GitHub issue, and follow all the instructions of the GitHub issue template. That way it's easier for me to debug it! :)
