### ISSUE TITLE
Big thanks from RoboCup@Home

### ISSUE THREAD

**Issue by LoyVanBeek** [CMU-Perceptual-Computing-Lab/openpose#175]
Hi @gineshidalgo99 and other contributors,

On behalf of the [RoboCup@Home](http://www.robocupathome.org/) Technical Committee, I just want to give a big thanks to OpenPose. Many teams in RoboCup@Home used OpenPose since this year and it really improved the level of the teams and the competition. 

For example, in our Restaurant task, customers can wave to the robots and the robots take your order. This is just one of several use cases. In previous years, this did not work very well for the 1-2 teams that tried and now this seems like a solved problems. 
[You can now point at your robot and have it do stuff with the object pointed to](https://youtu.be/SoFniA-eF7M?t=1m)

Again, thnx from @RoboCupAtHome

P.S. sorry for not sticking to the template, but this really didn't fit.

**Comment by tsimk** [comment]
Very cool stuff :) Glad your community is finding it useful, this is precisely the kind of thing we were hoping for when we released it.

Out of curiosity, how did you compute 3D locations for the skeleton joints?

**Comment by gineshidalgo99** [comment]
@LoyVanBeek Thank you so much! Glad our technology can help!

**Comment by shivenmian** [comment]
@LoyVanBeek great stuff! Could you explain how you got the openpose keypoints as 3D? Did you use 3D reconstruction or so?

**Comment by LoyVanBeek** [comment]
You can run OpenPose on the images from a Kinect. The correspondence between the RGB and depth sensors is good enough to do essentially a lookup. 

Some little video of this in action again: https://youtu.be/WGYDB-6KSx8?t=2m5s (but with some more fancy stuff added, like the faces on top of the 3D skeletons)
