### ISSUE TITLE
Openpose-python_api, how do you run this for videos? 

### ISSUE THREAD

**Issue by Dav-Webber** [CMU-Perceptual-Computing-Lab/openpose#1751]
How exactly would you go about running the python_api for videos, the tutorials are good for images but there is not much documentation i can find for implementing it for videos, any help would be much appreciated!!

**Comment by chenshuiyan** [comment]
Hello, I would like to know how to apply python_api to video for quick detection. If you have solved your problem, I would appreciate your help very much

**Comment by Dav-Webber** [comment]
yeah ill link a paste bin of the simplified code i have done for it https://pastebin.pl/view/43f56c31 , let me know if this helps

**Comment by chenshuiyan** [comment]
Thank you for your unselfish help. This is very useful to me

> yeah ill link a paste bin of the simplified code i have done for it https://pastebin.pl/view/43f56c31 , let me know if this helps
