### ISSUE TITLE
Windows 10, VS2019, CUDA 11.1.1 / cuDNN 8.0.5 - error building: cmake-3.19/Modules/FindCUDA.cmake:786

### ISSUE THREAD

**Issue by richardun** [CMU-Perceptual-Computing-Lab/openpose#1752]
### Issue Summary
Trying to build openpose from source.  
Env: Windows 10
with: VS2019, CUDA 11.1.1 / cuDNN 8.0.5

I installed VS2019 with all the seemingly appropriate C++ add-ons (none are listed specifically on the site).  I also re-installed multiple times: CUDA Toolkit 11.1 Update 1, and cuDNN v8.0.5 (November 9th, 2020), for CUDA 11.1.  

Using CMake-3.19.0-rc3 to build.
CUDA environment variables were created in the system and it appears cmake has found CUDA_TOOLKIT_ROOT_DIR, etc.  Only CUDA_SDK_ROOT_DIR is not found, but I don't think it matters.

### CMake Output
The C compiler identification is MSVC 19.28.29333.0
The CXX compiler identification is MSVC 19.28.29333.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMAKE_VERSION = 3.19.0-rc3
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindCUDA.cmake:786 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindCUDA.cmake:787 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)

Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1 (found version ".") 
Building with CUDA.
Downloading windows dependencies...
opencv_420_v14_15_2020_04_04.zip already exists.
caffe3rdparty_15_2019_03_14.zip already exists.
caffe_15_2020_04_05.zip already exists.
Windows dependencies downloaded.
Adding Example Calibration
Adding Example OpenPoseDemo
Adding Example 1_custom_post_processing
Adding Example 01_body_from_image_default
Adding Example 02_whole_body_from_image_default
Adding Example 03_keypoints_from_image
Adding Example 04_keypoints_from_images
Adding Example 05_keypoints_from_images_multi_gpu
Adding Example 06_face_from_image
Adding Example 07_hand_from_image
Adding Example 08_heatmaps_from_image
Adding Example 09_keypoints_from_heatmaps
Adding Example 10_asynchronous_custom_input
Adding Example 11_asynchronous_custom_input_multi_camera
Adding Example 12_asynchronous_custom_output
Adding Example 13_asynchronous_custom_input_output_and_datum
Adding Example 14_synchronous_custom_input
Adding Example 15_synchronous_custom_preprocessing
Adding Example 16_synchronous_custom_postprocessing
Adding Example 17_synchronous_custom_output
Adding Example 18_synchronous_custom_all_and_datum
Adding Example 1_thread_user_processing_function
Adding Example 2_thread_user_input_processing_output_and_datum
Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
Configuring incomplete, errors occurred!
See also "C:/Users/Dave/work/openpose/build/CMakeFiles/CMakeOutput.log".

### Errors
From above output:
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindCUDA.cmake:786 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindCUDA.cmake:787 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code master: 3a21129

3. **General configuration**:
    - **Installation mode**: CMake. (Windows)
    - **Operating system** Windows x64
    - **Operating system version** Windows 10 Pro: version 2004, OS build 19041.572
    - **Release or Debug mode** release
    - Compiler VS2019 community Windows

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** CMake-3.19.0-rc3
    - **OpenCV version**: OpenPose default

6. If **GPU mode** issue:
    - **CUDA version** 11.1.1  (cuda_11.1.1_456.81_win10)
    - **cuDNN version**: 8.0.5 (cudnn-11.1-windows-x64-v8.0.5.39)
    - **GPU model** NVIDIA GeForce RTX 3080

9. If **Windows** system:
    Compiling now... (not demo version)  Although I tried the demo version and it has its own error. Trying to run this command in Powershell:
bin\OpenPoseDemo.exe --video examples\media\video.avi

Gave me this:
PS C:\Users\Dave\work\openpose-windows\openpose> bin\OpenPoseDemo.exe --video examples\media\video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
F1113 19:59:50.434479  3220 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***

**Comment by gineshidalgo99** [comment]
See #1747 and post in there, please do not post in here. I won't reply in this thread anymore. Thanks!
