### ISSUE TITLE
OpenPose Build/Compilation Error

### ISSUE THREAD

**Issue by hisham246** [CMU-Perceptual-Computing-Lab/openpose#1753]
I have an issue building OpenPose in build directory with command: make -j`nproc`, even after successful configuration and generation in CMake and cloning of Caffe in 3rd party directory.

The following output appears in the terminal:

[ 12%] Performing build step for 'openpose_lib'
[  1%] Built target caffeproto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_accuracy_layer.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_norm_layer.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bnll_layer.cu.o
[  4%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bias_layer.cu.o
[  4%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_reindex_layer.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at cuda_compile_1_generated_base_data_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_base_data_layer.cu.o

nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at cuda_compile_1_generated_absval_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_absval_layer.cu.o

CMake Error at cuda_compile_1_generated_math_functions.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:96: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
src/caffe/CMakeFiles/caffe.dir/build.make:82: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o] Error 1
src/caffe/CMakeFiles/caffe.dir/build.make:516: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_80'
nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at cuda_compile_1_generated_batch_norm_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_batch_norm_layer.cu.o

CMake Error at cuda_compile_1_generated_bias_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_bias_layer.cu.o

nvcc fatal   : Unsupported gpu architecture 'compute_80'
src/caffe/CMakeFiles/caffe.dir/build.make:103: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_norm_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_norm_layer.cu.o] Error 1
src/caffe/CMakeFiles/caffe.dir/build.make:117: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bias_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bias_layer.cu.o] Error 1
CMake Error at cuda_compile_1_generated_accuracy_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_accuracy_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:89: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_accuracy_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_accuracy_layer.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at cuda_compile_1_generated_bnll_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_bnll_layer.cu.o

nvcc fatal   : Unsupported gpu architecture 'compute_80'
src/caffe/CMakeFiles/caffe.dir/build.make:124: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bnll_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bnll_layer.cu.o] Error 1
CMake Error at cuda_compile_1_generated_batch_reindex_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /home/hisham246/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_batch_reindex_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:110: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_reindex_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_reindex_layer.cu.o] Error 1
CMakeFiles/Makefile2:390: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:129: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-build' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

How to fix it and compile OpenPose?

Details:
**OS:** Ubuntu 18.04
**GPU:** Nvidia Geforce MX150
CUDA 10.1
cuDNN 7.5.1
CMake 3.18.4
OpenCV 3.2

**Comment by gineshidalgo99** [comment]
Could you show me the CMake configuration? (that shows CUDA version, GPU arch, etc).

**Comment by hisham246** [comment]
> Could you show me the CMake configuration? (that shows CUDA version, GPU arch, etc).

Yes, here it is
![cmake](https://user-images.githubusercontent.com/70494888/99193908-e0900c80-27b6-11eb-8e6f-24034ca91db2.png)

**Comment by hisham246** [comment]
> Could you show me the CMake configuration? (that shows CUDA version, GPU arch, etc).

@gineshidalgo99 This is the output of configuration:

GCC detected, adding compile flags
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 10.1
Found cuDNN: ver. 7.5.1 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
Automatic GPU detection failed. Building for all known architectures.
Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75 sm_80 sm_86
Found cuDNN: ver. 7.5.1 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)

Caffe will be built from source now.
Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
Configuring done

**Comment by gineshidalgo99** [comment]
"Automatic GPU detection failed. Building for all known architectures." --> This is the issue, it should automatically find your GPU!

In your command-line terminal, what is the output of `nvidia-smi`?

**Comment by hisham246** [comment]
@gineshidalgo99 I had Ubuntu 18.04 and due to a crash in the Nvidia graphics driver, I reinstalled Ubuntu 20.04 instead of it. Now I am trying to install OpenPose again, but I don't know how to install Cuda 11.1 as it is compatible with Ubuntu 20.04. Which version of Cuda and cuDNN should I install?

Here is the output of nvidia-smi and nvcc --version:
![nvidia](https://user-images.githubusercontent.com/70494888/99228039-0e149e80-2827-11eb-89b3-a8e10574e62a.png)

It shows I have Cuda 10.1 already but there is no cuda file in usr/local
There is usr/lib/cuda/include but it's empty.

**Comment by dosadadev** [comment]
Just FYI:
I encountered this error when building openpose in a docker container, especially when building docker image.
It seems nvidia container toolkit (nvidia-docker) doesn't support gpu when running `docker build `, so I had to specify the cuda architecture manually.

What I did to solve this problem was to add `DCUDA_ARCH="Turing \(CUDA >= 10\)"` to the cmake command line.
If you use cmake GUI, then writing `Turing (CUDA >= 10)` or the architecture you want to use would solve this problem.

**Comment by wuchichung** [comment]
Hi all, I just find a workaround to build openpose within docker. I am using cuda 10 base image. However the latest version (tag: v1.7.0 in my case) requires support for AMPERE which needs cuda >= 11. I have tried -DCUDA_ARCH="Turing \(CUDA >= 10\)" mentioned by @dosadadev. But it does not work in my case. I just comment the "set(AMPERE "80 86")" line in ./cmake/Cuda.cmake.

**Comment by wuchichung** [comment]
I have checked with @dosadadev 's solution ,but it does not work in my case. This is my workaround.

```
RUN git clone -b v1.7.0 https://github.com/CMU-Perceptual-Computing-Lab/openpose /opt/openpose \
 && cd /opt/openpose \
 && mkdir build  \
 && cd build \
 && cmake -DOpenCV_CONFIG_FILE=/opt/opencv/build/OpenCVConfig.cmake \
          -DDOWNLOAD_BODY_25_MODEL=OFF\
          -DDOWNLOAD_FACE_MODEL=OFF\
          -DDOWNLOAD_HAND_MODEL=OFF\
          -DBUILD_EXAMPLES=OFF\
          -DBUILD_PYTHON=ON\
          .. \
 ## FIXME as v1.7.0 support AMPERE architectur, however we are using cuda 10 which is not compatible with AMPERE we comment these lines as a quick fix
 && sed -ie 's/set(AMPERE "80 86")/#&/g'  ../cmake/Cuda.cmake \
 && sed -ie 's/set(AMPERE "80 86")/#&/g'  ../3rdparty/caffe/cmake/Cuda.cmake \
 && make -j $(nproc)\
 && make install \
 && ln -s /opt/openpose/build/python/openpose /usr/local/lib/python3.7/dist-packages/openpose
```

**Comment by nhhviet98** [comment]
> I have checked with @dosadadev 's solution ,but it does not work in my case. This is my workaround within docker. I am using cuda 10 so I have to disable the support of AMPERE
> 
> ```
> RUN git clone -b v1.7.0 https://github.com/CMU-Perceptual-Computing-Lab/openpose /opt/openpose \
>  && cd /opt/openpose \
>  && mkdir build  \
>  && cd build \
>  && cmake -DOpenCV_CONFIG_FILE=/opt/opencv/build/OpenCVConfig.cmake \
>           -DDOWNLOAD_BODY_25_MODEL=OFF\
>           -DDOWNLOAD_FACE_MODEL=OFF\
>           -DDOWNLOAD_HAND_MODEL=OFF\
>           -DBUILD_EXAMPLES=OFF\
>           -DBUILD_PYTHON=ON\
>           .. \
>  ## FIXME as v1.7.0 support AMPERE architectur, however we are using cuda 10 which is not compatible with AMPERE we comment these lines as a quick fix
>  && sed -ie 's/set(AMPERE "80 86")/#&/g'  ../cmake/Cuda.cmake \
>  && sed -ie 's/set(AMPERE "80 86")/#&/g'  ../3rdparty/caffe/cmake/Cuda.cmake \
>  && make -j $(nproc)\
>  && make install \
>  && ln -s /opt/openpose/build/python/openpose /usr/local/lib/python3.7/dist-packages/openpose
> ```
Thank you, this is my solution based on your problem.
```
# https://hub.docker.com/r/cwaffles/openpose
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

#get deps
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
python3-dev python3-pip python3-setuptools git g++ wget make libprotobuf-dev protobuf-compiler libopencv-dev \
libgoogle-glog-dev libboost-all-dev libcaffe-cuda-dev libhdf5-dev libatlas-base-dev

#for python api
#RUN pip3 install scikit-build
RUN pip3 install scikit-build numpy opencv-python==4.1.1.26

#replace cmake as old version has CUDA variable bugs
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz && \
tar xzf cmake-3.16.0-Linux-x86_64.tar.gz -C /opt && \
rm cmake-3.16.0-Linux-x86_64.tar.gz
ENV PATH="/opt/cmake-3.16.0-Linux-x86_64/bin:${PATH}"

#get openpose
WORKDIR /openpose
RUN git clone -q --depth 1 https://github.com/CMU-Perceptual-Computing-Lab/openpose.git .

#build it
WORKDIR /openpose/build
RUN cmake -DBUILD_PYTHON=ON \
	  -DDOWNLOAD_BODY_25_MODEL=ON \
          -DDOWNLOAD_BODY_MPI_MODEL=OFF \
          -DDOWNLOAD_HAND_MODEL=OFF \
          -DDOWNLOAD_FACE_MODEL=OFF \
	  .. 

RUN sed -ie 's/set(AMPERE "80 86")/#&/g'  ../cmake/Cuda.cmake && \
    sed -ie 's/set(AMPERE "80 86")/#&/g'  ../3rdparty/caffe/cmake/Cuda.cmake
RUN make -j`nproc`
RUN make install

WORKDIR /openpose
```

**Comment by whf9527** [comment]
I have the same issue and how to reslove this problem
Should it upgrade the cuda version from 10 to 11 ?

**Comment by Mejorarsim** [comment]
mkdir: cannot create directory ‘build’: File exists
/content/openpose/build
CMake Warning (dev) at CMakeLists.txt:19 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at CMakeLists.txt:34 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
CMake Warning (dev) at CMakeLists.txt:214 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building with CUDA.
CMake Warning (dev) at CMakeLists.txt:353 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Cuda.cmake:282 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:424 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CUDA detected: 12.2
-- Found cuDNN: ver. 8.9.6 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75
-- Found cuDNN: ver. 8.9.6 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)
M	cmake/Cuda.cmake
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- Model already exists.
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done (1.5s)
-- Generating done (0.0s)
-- Build files have been written to: /content/openpose/build
[ 12%] Performing build step for 'openpose_lib'
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
CMake Warning (dev) at cmake/Cuda.cmake:275 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  cmake/Dependencies.cmake:85 (include)
  CMakeLists.txt:49 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CUDA detected: 12.2
-- Found cuDNN: ver. 8.9.6 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Python interface is disabled or not all required dependencies found. Building without it...
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   1.0-149-g1807aada-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   OFF
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   OFF
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   OFF
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--   USE_HDF5          :   ON
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.74)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. ..)
--   CUDA              :   Yes (ver. 12.2)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75
--   cuDNN             :   Yes (ver. 8.9.6)
-- 
-- Install:
--   Install path      :   /content/openpose/build/caffe
-- 
-- Configuring done (3.6s)
-- Generating done (0.2s)
-- Build files have been written to: /content/openpose/build/caffe/src/openpose_lib-build
[  1%] Built target caffeproto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_35'
nvcc fatal   : Unsupported gpu architecture 'compute_35'
CMake Error at cuda_compile_1_generated_absval_layer.cu.o.Release.cmake:220 (message):
  Error generating
  /content/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_absval_layer.cu.o

CMake Error at cuda_compile_1_generated_math_functions.cu.o.Release.cmake:220 (message):
  Error generating
  /content/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions.cu.o



make[5]: *** [src/caffe/CMakeFiles/caffe.dir/build.make:77: src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [src/caffe/CMakeFiles/caffe.dir/build.make:511: src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:376: src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/openpose_lib.dir/build.make:86: caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/openpose_lib.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
/content/openpose

**Comment by azamjon-xusanov** [comment]
> mkdir: cannot create directory ‘build’: File exists /content/openpose/build CMake Warning (dev) at CMakeLists.txt:19 (project): cmake_minimum_required() should be called prior to this top-level project() call. Please see the cmake-commands(7) manual for usage documentation of both commands. This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Deprecation Warning at CMakeLists.txt:34 (cmake_minimum_required): Compatibility with CMake < 3.5 will be removed from a future version of CMake.
> 
> Update the VERSION argument value or use a ... suffix to tell CMake that the project does not need compatibility with older versions.
> 
> -- GCC detected, adding compile flags -- GCC detected, adding compile flags CMake Warning (dev) at CMakeLists.txt:214 (find_package): Policy CMP0146 is not set: The FindCUDA module is removed. Run "cmake --help-policy CMP0146" for policy details. Use the cmake_policy command to set the policy and suppress this warning.
> 
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Building with CUDA. CMake Warning (dev) at CMakeLists.txt:353 (find_package): Policy CMP0146 is not set: The FindCUDA module is removed. Run "cmake --help-policy CMP0146" for policy details. Use the cmake_policy command to set the policy and suppress this warning.
> 
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at cmake/Cuda.cmake:282 (find_package): Policy CMP0146 is not set: The FindCUDA module is removed. Run "cmake --help-policy CMP0146" for policy details. Use the cmake_policy command to set the policy and suppress this warning.
> 
> Call Stack (most recent call first): CMakeLists.txt:424 (include) This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- CUDA detected: 12.2 -- Found cuDNN: ver. 8.9.6 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so) -- Automatic GPU detection failed. Building for all known architectures. -- Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75 -- Found cuDNN: ver. 8.9.6 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so) -- Found gflags (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so) -- Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so) -- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending on your internet connection. -- Caffe has already been downloaded. HEAD is now at 1807aada Added Ampere arch's (CUDA11) M cmake/Cuda.cmake -- Caffe will be built from source now. -- Download the models. -- Downloading BODY_25 model... -- Model already exists. -- Not downloading body (COCO) model -- Not downloading body (MPI) model -- Downloading face model... -- Model already exists. -- Downloading hand model... -- Model already exists. -- Models Downloaded. -- Configuring done (1.5s) -- Generating done (0.0s) -- Build files have been written to: /content/openpose/build [ 12%] Performing build step for 'openpose_lib' CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required): Compatibility with CMake < 3.5 will be removed from a future version of CMake.
> 
> Update the VERSION argument value or use a ... suffix to tell CMake that the project does not need compatibility with older versions.
> 
> CMake Warning (dev) at cmake/Misc.cmake:32 (set): implicitly converting 'BOOLEAN' to 'STRING' type. Call Stack (most recent call first): CMakeLists.txt:25 (include) This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Found gflags (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so) -- Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so) -- Found PROTOBUF Compiler: /usr/bin/protoc CMake Warning (dev) at cmake/Cuda.cmake:275 (find_package): Policy CMP0146 is not set: The FindCUDA module is removed. Run "cmake --help-policy CMP0146" for policy details. Use the cmake_policy command to set the policy and suppress this warning.
> 
> Call Stack (most recent call first): cmake/Dependencies.cmake:85 (include) CMakeLists.txt:49 (include) This warning is for project developers. Use -Wno-dev to suppress it.
> 
> ## -- CUDA detected: 12.2
> -- Found cuDNN: ver. 8.9.6 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
> -- Automatic GPU detection failed. Building for all known architectures.
> -- Added CUDA NVCC flags for: sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75
> -- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
> -- Python interface is disabled or not all required dependencies found. Building without it...
> ## -- ******************* Caffe Configuration Summary *******************
> -- General:
> -- Version : 1.0.0
> -- Git : 1.0-149-g1807aada-dirty
> -- System : Linux
> -- C++ compiler : /usr/bin/c++
> -- Release CXX flags : -O3 -DNDEBUG -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
> -- Debug CXX flags : -g -fPIC -Wall -std=c++11 -Wno-sign-compare -Wno-uninitialized
> -- Build type : Release
> ## -- BUILD_SHARED_LIBS : ON
> -- BUILD_python : OFF
> -- BUILD_matlab : OFF
> -- BUILD_docs : OFF
> -- CPU_ONLY : OFF
> -- USE_OPENCV : OFF
> -- USE_LEVELDB : OFF
> -- USE_LMDB : OFF
> -- USE_NCCL : OFF
> -- ALLOW_LMDB_NOLOCK : OFF
> -- USE_HDF5 : ON
> ## -- Dependencies:
> -- BLAS : Yes (Atlas)
> -- Boost : Yes (ver. 1.74)
> -- glog : Yes
> -- gflags : Yes
> -- protobuf : Yes (ver. ..)
> -- CUDA : Yes (ver. 12.2)
> ## -- NVIDIA CUDA:
> -- Target GPU(s) : Auto
> -- GPU arch(s) : sm_35 sm_37 sm_50 sm_52 sm_53 sm_60 sm_61 sm_62 sm_70 sm_72 sm_75
> -- cuDNN : Yes (ver. 8.9.6)
> ## -- Install:
> -- Install path : /content/openpose/build/caffe
> -- Configuring done (3.6s) -- Generating done (0.2s) -- Build files have been written to: /content/openpose/build/caffe/src/openpose_lib-build [ 1%] Built target caffeproto [ 1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o [ 1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o nvcc fatal : Unsupported gpu architecture 'compute_35' nvcc fatal : Unsupported gpu architecture 'compute_35' CMake Error at cuda_compile_1_generated_absval_layer.cu.o.Release.cmake:220 (message): Error generating /content/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_absval_layer.cu.o
> 
> CMake Error at cuda_compile_1_generated_math_functions.cu.o.Release.cmake:220 (message): Error generating /content/openpose/build/caffe/src/openpose_lib-build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions.cu.o
> 
> make[5]: *** [src/caffe/CMakeFiles/caffe.dir/build.make:77: src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o] Error 1 make[5]: *** Waiting for unfinished jobs.... make[5]: *** [src/caffe/CMakeFiles/caffe.dir/build.make:511: src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o] Error 1 make[4]: *** [CMakeFiles/Makefile2:376: src/caffe/CMakeFiles/caffe.dir/all] Error 2 make[3]: *** [Makefile:136: all] Error 2 make[2]: *** [CMakeFiles/openpose_lib.dir/build.make:86: caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2 make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/openpose_lib.dir/all] Error 2 make: *** [Makefile:91: all] Error 2 /content/openpose

how to fix it, i got same error
