### ISSUE TITLE
How to build OpenPose without root priviledge

### ISSUE THREAD

**Issue by lonelygoatherd** [CMU-Perceptual-Computing-Lab/openpose#1754]
I'm trying to build Openpose on service . I'm not administrator so not able to use sudo command. How can I build OpenPose in this circumstance ? Python and Cmake are installed in the computer. Can I build the codes without caffe and opencv installed ? 
System: Ubuntu 16

**Comment by gineshidalgo99** [comment]
You do not need root privileges to compile OpenPose (nor any other software really), assuming all the prerequisites of the library are already available in your machine.

However, you can't compile any software without having its prerequisites installed, same with OpenPose. Usually you ask your admin to install the prerequisites, which are pretty standard, and then you can compile OpenPose on it.
