### ISSUE TITLE
[Win10] [Release v1.7.0] Errors during CMake Configuration

### ISSUE THREAD

**Issue by richardun** [CMU-Perceptual-Computing-Lab/openpose#1755]
### Issue Summary
Using the latest [openpose source]( https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/ef06d23865a34658e0a1d1c1bf5ebbffc7a8c7a1), I wanted to build it and use OpenPose.  I got errors in CMake described and linked below.

Please advise.

### Executed Command (if any)
From Powershell [here](https://pastebin.com/6WVxCGkg).
Essentially, steps followed:

**In Powershell:**
- git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
- cd openpose/
- git submodule update --init --recursive --remote
- mkdir build
- cd build
- cmake-gui ..

**In CMake:**
- Configure
- Select VS16 2019 and x64

### CMake Output
Output [here](https://pastebin.com/R32aENY2).

![image](https://user-images.githubusercontent.com/87189/99328449-b899bb00-2841-11eb-93b4-5dc90707193e.png)

(Error in configuration process, project files may be invalid)

### Errors (if any)
From pastebin above, here explicitly:
```
CMAKE_VERSION = 3.18.4
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindCUDA.cmake:784 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)


CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindCUDA.cmake:785 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)
```
[C:/Users/Dave/openpose/build/CMakeFiles/CMakeOutput.log](https://pastebin.com/32qdefvT)

### Type of Issue
- Configuration error
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin]

    - https://pastebin.com/R32aENY2
    - https://pastebin.com/32qdefvT

2. **OpenPose version**: Latest GitHub [openpose source]( https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/ef06d23865a34658e0a1d1c1bf5ebbffc7a8c7a1)

3. **General configuration**:

    - **Installation mode**: CMake. (Windows)
    - **Operating system** Windows x64
    - **Operating system version** Windows 10 Pro: version 2004, OS build 19041.572
    - **Release or Debug mode** release
    - **Compiler** VS2019 community Windows

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: **no**):
    - Any other custom CMake configuration with respect to the default version? (by default: **no**):

5. **3rd-party software**:

    - **Caffe version**: Default from OpenPose
    - **CMake version** CMake-3.18.4
    - **OpenCV version**: OpenPose default

OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** 11.1.1 (cuda_11.1.1_456.81_win10)
    - **cuDNN version**: 8.0.5 (cudnn-11.1-windows-x64-v8.0.5.39)
    - **GPU model** NVIDIA GeForce RTX 3080

7. If **CPU-only mode** issue:
    - n/a

8. If **Python** API:
    - n/a

9. If **Windows** system:
    - compiled library

10. If **speed performance** issue:
    - n/a

**Comment by richardun** [comment]
Here is my VS Community 2019 - 16.8.1 component list:
![image](https://user-images.githubusercontent.com/87189/99329695-6017ed00-2844-11eb-92a1-3471770add50.png)
![image](https://user-images.githubusercontent.com/87189/99329708-660dce00-2844-11eb-8e7f-9eeed04fb9da.png)
![image](https://user-images.githubusercontent.com/87189/99329713-69a15500-2844-11eb-8099-76774a88e3e2.png)

**Comment by gineshidalgo99** [comment]
That is indeed a very weird error which I do not have on my machine. It is not VS related, although your VS config looks good!

Could you try renaming (temporarily at least!) C:/Program Files/CMake/share/cmake-3.18/Modules/FindCUDA.cmake by let's say C:/Program Files/CMake/share/cmake-3.18/Modules/FindCUDA_.cmake, and then re-opening Cmake-gui and re-running it? The problem seems to be that CMake is choosing the CMake find_cuda over the OpenPose find_cuda.

**Comment by richardun** [comment]
Ok, I renamed that file and I got this:  https://pastebin.com/cuf294jD

This:
```
CMake Warning at CMakeLists.txt:214 (find_package):
  By not providing "FindCUDA.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CUDA", but
  CMake did not find one.

  Could not find a package configuration file provided by "CUDA" with any of
  the following names:

    CUDAConfig.cmake
    cuda-config.cmake

  Add the installation prefix of "CUDA" to CMAKE_PREFIX_PATH or set
  "CUDA_DIR" to a directory containing one of the above files.  If "CUDA"
  provides a separate development package or SDK, be sure it has been
  installed.
```

I also just noticed a variable CUDA_DIR that is "not found."  I tried setting this to `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1`, but after hitting "Configure" it removed it and said it was still not found.

**Comment by richardun** [comment]
I did a search for these files on my computer and didn't find them.  Also, I couldn't find "find_cuda" in the openpose source.

**Comment by gineshidalgo99** [comment]
Thanks for the test. And please, rename the file back to avoid future bugs in your code!

Do you "only" need the demo executable? Or are you planning to modify the code? If you only need to use the default OPenPose dmeo functionality, I have just pushed the binaries for v1.7.0, which will work without installing anything!

https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.7.0

**Comment by richardun** [comment]
Hazzah!  That worked.  So, I guess I need to figure out what's going on with Cuda at nvidia if I need to compile this, but I don't think I'll need to.

Thanks for your help!

**Comment by richardun** [comment]
Just FYI, the RTX 3080 does nearly 30fps on video.

**Comment by gineshidalgo99** [comment]
No problem, happy it is working! It was quite painful to get everything back with CUDA 11.

The version you downloaded do not contain the Python code really.

I have just removed that one, and pushed GPU and CPU versions, both with the Python bindings (by first time in the portable binaries), so feel free to use whatever version you want! And if you were planning to use Python, just re-download the GPU one and read its "Instructions.txt":
https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.7.0
