### ISSUE TITLE
CUDA check failed error:cudnn is not being used by caffe when it should have been

### ISSUE THREAD

**Issue by templarares** [CMU-Perceptual-Computing-Lab/openpose#1756]
### Issue Summary
Got the "out of memory" error. Found that this is usually related to "cuDNN not being used". Double-checked that VS project was built with "enable cuDNN" in CMake. Reinstalled cuDNN, nothing changed. Used "Dependencies"/"DependencyWalker" on "caffe.dll" in the bin folder. Found that it was depending on cudnn64_7.dll in my older installation of openpose. But in this newest openpose 1.7.0.1 installation, caffe.dll is not depending on any "cudnn*.dll"--although there is indeed a "cudnn64_8.dll" in openpose's bin folder.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Errors (if any)
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### Type of Issue

- Compilation/installation error
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
1.7.0.1

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

Windows10 + VS2019 comminuity+CMake

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

All default

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

CUDA 11.1, cuDNN 8.0.5, GPU RTX3080

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
Please fill Your System Configuration
