### ISSUE TITLE
[v1.7.0] Request :)  Please build OpenPoseDemo with unity special parameter

### ISSUE THREAD

**Issue by richardun** [CMU-Perceptual-Computing-Lab/openpose#1758]
This is pitiful request if you can oblige... I am using OpenPose with Unity.  Since I had trouble with compiling OpenPose (VS2019, Cuda 11.1, cuDNN 8.0.4), I'm trying to use the 1.7.0 Windows binary for my Unity app to use.  But apparently this wasn't built with the unity option.

Not sure your position on this, but would you mind building this with unity support?  Thank you kindly.

**Comment by gineshidalgo99** [comment]
The Unity project has not been modified in more than a year, I'd use the latest OpenPose release that includes Unity support.

If you have to use CUDA 11 (because of your GPU), I am not sure if you will need to make changes to the Unity plugin API. If so, and you get it to work, please do make a pull request on it so it can be updated to work with the latest OpenPose!

I have made quite a lot of changes lately trying to make the doc simpler and OpenPose way easier to install. Could you please re-try building OpenPose from scratch by following the new doc/installation/README.md instructions? If they don't work, please, show me here whatever errors you are facing now. Hopefully some of your old ones should be gone.

Thanks!

**Comment by richardun** [comment]
Thank you!  I will update, try a rebuild, and let you know.  Cheers.

**Comment by richardun** [comment]
Fresh clone.
`git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose openpose-richard
cd openpose-richard/
git submodule update --init --recursive --remote`

Run Cmake.
`cd {OpenPose_folder}
mkdir build/
cd build/
cmake-gui ..`

No errors!  Here's the config although I reran it so you'll see "already exists."
https://pastebin.com/7gj6L1uw

Generate was good too.  GPU_MODE set to CUDA already... going with it since I have an nvidia 3080.
https://pastebin.com/2XV0cQCw

Opened in VS2019 Community.  Set build from Debug to Release... hit Build > Build Solution
VS2019 Output: https://pastebin.com/2ancFUmp
VS2019 Error List:  https://pastebin.com/fHR1ACUG
Alternatively, this image:
![image](https://user-images.githubusercontent.com/87189/99934115-ae385f00-2d22-11eb-82ed-96ea682def21.png)

I searched for `openpose.lib` but couldn't find it anywhere in `openpose-richard\`

Thanks.

**Comment by richardun** [comment]
@gineshidalgo99 It worked!  After your fixes, I just needed to make a small change:
`set(CUDA_NVCC_EXECUTABLE "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1") to set(CUDA_NVCC_EXECUTABLE "nvcc")`

Thank you so much for working on it last weekend!

**Comment by shaojim12** [comment]
Hi, 

I'm also trying to use openpose on rtx 3070. May I ask you some questions?
Could you run openpose-unity on rtx 30XX now?
Do you change Unity plugin version 1.5.0 to 1.7.0?

Thanks!

**Comment by shaojim12** [comment]
I had solved the problem.
Thanks!

**Comment by richardun** [comment]
> I had solved the problem.
> Thanks!

I'm sorry, @shaojim12.  I've been slammed this week.  Glad you solved the problem!

**Comment by sirua1988** [comment]
@shaojim12 
> I had solved the problem.
> Thanks!

Hi~May I ask you how did you solve this problem?
Cause I have a similar  problem with this:
It work well on my computer(RTX 2070 , win10).
But it crashed when I work on my laptop(RTX 3070 , win10).
I'm use openpose uniy plugin 1.5.0.

Thanks alot.

**Comment by shaojim12** [comment]
> @shaojim12
> 
> > I had solved the problem.
> > Thanks!
> 
> Hi~May I ask you how did you solve this problem?
> Cause I have a similar problem with this:
> It work well on my computer(RTX 2070 , win10).
> But it crashed when I work on my laptop(RTX 3070 , win10).
> I have no any idea with this. . .
> 
> Openpose uniy plugin 1.5.0.
> Unity version 2018.4.22f1
> GPU:RTX 3070 laptop
> 
> Thanks alot.

You have to use cmake to make the new plugin from the latest version of openpose responsitory.
Then copy all the new plugins inside the unity "plugin" folder.

I didn't touch this after January, so let me know if it didn't work.

**Comment by shaojim12** [comment]
> @shaojim12
> 
> > I had solved the problem.
> > Thanks!
> 
> Hi~May I ask you how did you solve this problem?
> Cause I have a similar problem with this:
> It work well on my computer(RTX 2070 , win10).
> But it crashed when I work on my laptop(RTX 3070 , win10).
> I have no any idea with this. . .
> 
> Openpose uniy plugin 1.5.0.
> Unity version 2018.4.22f1
> GPU:RTX 3070 laptop
> 
> Thanks alot.

Okay, I found an introduction.
1. follow the [youtube](https://www.youtube.com/watch?v=QC9GTb6Wsb4) with
•	Visual Studio 2019
•	CUDA 11 
•	cudnn 8
2. follow the video and build a new openpose plugin
3. copy all the file from the builded bin folder to unity's folder .\OpenPosePlugin\Assets\OpenPose\Plugins

**Comment by sirua1988** [comment]
@shaojim12 

Wow it is helpful for me. thank you very very much.

I will try it soon.

**Comment by sirua1988** [comment]
@shaojim12 
Hi ~ I follow your suggestion and it is worked for me!
I use cuda_11.2.0 and cudnn-11.2 , But an error needs to be resolved when visual studio complied:

**OpenPOSE compiles generation error CALLING A __HOST__ FUNCTION ("__ floor") IS not allowed.**

I need to change all floor to floorf.  Other than that, everything went very smoothly.

Thank you again !

**Comment by shaojim12** [comment]
@sirua1988 

Yeah, no problem. Glad you solved the problem!

**Comment by natxein** [comment]
> @sirua1988
> 
> Okay, I found an introduction.
> 
> 1. follow the [youtube](https://www.youtube.com/watch?v=QC9GTb6Wsb4) with
>    •	Visual Studio 2019
>    •	CUDA 11
>    •	cudnn 8
> 2. follow the video and build a new openpose plugin
> 3. copy all the file from the builded bin folder to unity's folder .\OpenPosePlugin\Assets\OpenPose\Plugins
> 
> I didn't touch this after January, so let me know if it didn't work.

Hi @shaojim12! how are you doing? I followed your indications but I'm not sure which files to copy after building from Visual Studio. I select Release and Build but I can't find the bin folder inside the folder "x64/Release"  generated from Visual Studio, so I don't know if you refer to the bin folder of cmake.

![image](https://user-images.githubusercontent.com/69536009/191037355-cca82d79-b3a2-420d-9ccc-c92e40e2b472.png)

![image](https://user-images.githubusercontent.com/69536009/191037488-2d78caad-33c4-4fec-bb2b-62379b677c15.png)

thanks

**Comment by shaojim12** [comment]
@natxein Hey, I forgot the detail about this, but I remember there is a bin folder created after you buiid it.

**Comment by sirua1988** [comment]
@natxein Sorry,I lost my original project
Only keep the built files. I remember that I copied from the path "openpose-binary/bin"
The content of the file is as follows:
![ttt2](https://user-images.githubusercontent.com/82927687/191413149-607ac7ab-19e0-47c8-af95-b5cae6a65452.png)

And the bin folder is:
![ttt](https://user-images.githubusercontent.com/82927687/191412871-da5db70f-fef6-42f1-9e62-21281f838ef4.png)

Maybe the OpenPose version has changed. Compilation results are different.
--OpenPose version 1.5.0

**Comment by natxein** [comment]
> @natxein Sorry,I lost my original project Only keep the built files. I remember that I copied from the path "openpose-binary/bin" The content of the file is as follows: ![ttt2](https://user-images.githubusercontent.com/82927687/191413149-607ac7ab-19e0-47c8-af95-b5cae6a65452.png)
> 
> And the bin folder is: ![ttt](https://user-images.githubusercontent.com/82927687/191412871-da5db70f-fef6-42f1-9e62-21281f838ef4.png)
> 
> Maybe the OpenPose version has changed. Compilation results are different. --OpenPose version 1.5.0

Hi @sirua1988, thank you for your response! 

I was trying with Openpose 1.7.0 so today I have been trying with Openpose 1.5.0 as you said but with same results:

 
![image](https://user-images.githubusercontent.com/69536009/191480834-2905a276-f0c9-4e28-b033-5ec41e15fb89.png)

Maybe I'm doing something wrong when I build it in Visual Studio 2019 . I just select Realease and Build Solution

**Comment by natxein** [comment]
@sirua1988 Are you planning to upload the files to the repository https://github.com/sirua1988/OpenPose_Unity_30series?  XD

**Comment by sirua1988** [comment]
@natxein Yes , but dll is too large. I also forgot how to build.
So I put the release here:
[Download](https://drive.google.com/file/d/1OOymmJoaDs-pu7JR24dRjpm19R1ZBC3p/view)
But not sure if you can use this.

**Comment by natxein** [comment]
Thank you very much @sirua1988 !! I will try it and let you know
