### ISSUE TITLE
5 seconds slower than the real time with ip camera with rtsp

### ISSUE THREAD

**Issue by cactus8711** [CMU-Perceptual-Computing-Lab/openpose#1759]
Dears:
      I have an issue for using the openpose 1.6.0, it is same to the version of 1.5.0 and 1.7.0(have used them of all), it works well with video,images, but the ip camera is slightly slower than the real time,  my configure list as the follow, OS:Windows 10, Cuda:10.1,CudNN 7.6,  GPU: Nvidia GeForce RTX 2080 Ti, Programe Language:C++, Testing Mode: realease and debug.
     I have checked the rescource of my computer , it works normal ,less than 50% in  every moudle(CPU,GPU,NetWork,IO),In debug mode,I have seen the method  CopyTrainedLayersFrom takes almost 3-4 seconds, is that the reason for slower in real time?  
    another,could it input more ipcameras (rtsp) ? If i have more ipcameras and want to  show the analysis frames   in one terminal display.
    thanks for contributing the openpose first and expecting for an anwser for this ,thanks angain.
                                                                                                                         from one fan

**Comment by ananay22** [comment]
Is there a difference between the quality of the image from the IP Camera and the WebCam you use normally?

**Comment by cactus8711** [comment]
thanks for your reply,I have tried a webcamera, it shows  an very well display, not slower more. what's the reason about  the ipcamera works differently?  The network i have saw is normal when the ipcamera running,

**Comment by iCodeiCreateDev** [comment]
No as in what's rhe resolution and frame rate of your IP camera and your web camera.

**Comment by cactus8711** [comment]
the configure of my ip camera:  fps: 6,input resolution:1280x720P;the openposedemo.exe runs with windows cmd parameter,  only the --ip_camera parameter was setted, the --fps_max used it's default value, it worked slower 5 seconds.while i used the webcamera, --fps_max used the default value too, --camera_resolution was 1280x1024,  it keeped  the same dispaly without any slower frame.

**Comment by gineshidalgo99** [comment]
We simply use OpenCV to read the camera, so I am afraid there is not much we can do to improve it's speed.

My only wild guess is that maybe OpenCV can be manually compiled with some codecs to optimize that IP camera. If so, you can link your custom and optimized OPenCV to OpenPose and it should also benefit from it.
