### ISSUE TITLE
How can I only extract foot keypoints?

### ISSUE THREAD

**Issue by IsaacPatole** [CMU-Perceptual-Computing-Lab/openpose#1763]
Hello there,
I am working on Openpose on Google Colab using the following link : https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/OpenPose.ipynb#scrollTo=oNASdyyiO65I

I am able to generate an output video and json file using this command: !cd openpose && ./build/examples/openpose/openpose.bin --video ../video.mp4 --write_json ./output/ --display 0  --write_video ../openpose.avi

I only want to work on Foot keypoints, what does 'pose_keypoints_2d' represents and how can I extract the keypoint location in order to project it onto a video frame?

**Comment by gineshidalgo99** [comment]
Feet are the last 6 keypoints. See doc/output.md

**Comment by IsaacPatole** [comment]
Yes, but after downloading the genarated video and json files, I am trying to draw circles onto the keypoint location on a frame, by taking the first frame of the  video and video_000000000000_keypoints.json and the circles doesnt represent a proper keypoint. do I have to convert x and y keypoints before creating the circle?

**Comment by IsaacPatole** [comment]
The generated json file couldnt help me draw circles around keypoints mostly because of the output dimension mismatch but after adding --net_resolution parameter (--net_resolution "320x320" to be specific) I could perfectly draw the keypoints. Thanks.
