### ISSUE TITLE
An error occurred when run openpose.bin,cpu only

### ISSUE THREAD

**Issue by yangmengace** [CMU-Perceptual-Computing-Lab/openpose#1769]
meng@meng-virtual-machine:~/openpose-master$ ./build/examples/openpose/openpose.bin --image_dir examples/media/
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
---------------------------------- WARNING ----------------------------------
We have introduced an additional boost in accuracy in the CUDA version of about 0.2% with respect to the CPU/OpenCL versions. We will not port this to CPU given the considerable slow down in speed it would add to it. Nevertheless, this accuracy boost is almost insignificant so the CPU/OpenCL versions can be safely used.
-------------------------------- END WARNING --------------------------------
[libprotobuf ERROR google/protobuf/text_format.cc:310] Error parsing text-format caffe.NetParameter: 1:1: Interpreting non ascii codepoint 136.
[libprotobuf ERROR google/protobuf/text_format.cc:310] Error parsing text-format caffe.NetParameter: 1:1: Expected identifier, got: �
F1123 17:15:50.454649 82866 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_deploy.prototxt

**Comment by gineshidalgo99** [comment]
It was probably not downloaded probably, see faq
