### ISSUE TITLE
Any plan for a python interface?

### ISSUE THREAD

**Issue by heurainbow** [CMU-Perceptual-Computing-Lab/openpose#177]
### Issue summary
Any plan for a python interface develop?

- Enhancement / offering possible extensions / pull request / etc

**Comment by gineshidalgo99** [comment]
There is, but it will take at least a few more months :(

I'll close the thread for now to minimize open issue threads, but please check OpenPose every month for that!

**Comment by padeler** [comment]
@heurainbow you can use [PyOpenPose](https://github.com/FORTH-ModelBasedTracker/PyOpenPose). It already exposes keypoints for pose/faces/hands as well as PAFs and heatmaps. 
I used np.ndarrays as a data format so its pretty easy to incorporate to projects.  I plan to keep adding features as they appear on openpose (or until it is deprecated by a python api release).

@gineshidalgo99 I don't know if it fits your plans/needs for a python API, but if it does I could adapt it and send you a pull request.

Openpose is awesome by the way, keep it up! :+1:

**Comment by gineshidalgo99** [comment]
@padeler  Thank you for this! I'll check it out when I have more time!
