### ISSUE TITLE
Minor error in Quick Start - Face and Hands section

### ISSUE THREAD

**Issue by HaoyuWang00** [CMU-Perceptual-Computing-Lab/openpose#1773]
### Minor error in Quick Start - Face and Hands section
In the `Quick Start - Face and Hands` section, it says:
```
# Ubuntu and Mac
./build/examples/openpose/openpose.bin --image_dir examples\media\ --face --hand
./build/examples/openpose/openpose.bin --video examples\media\video.avi --face --hand
./build/examples/openpose/openpose.bin --face --hand
```
The `\` should be `/` under Ubuntu and Mac.

PS: Thanks for maintaining the repo so well!

**Comment by gineshidalgo99** [comment]
Thanks, it will be pushed in my next commit!
