### ISSUE TITLE
 Detected 1 GPU(s), using 1 of them starting at GPU 0.

### ISSUE THREAD

**Issue by liuyao120** [CMU-Perceptual-Computing-Lab/openpose#1775]
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
E1128 18:28:22.757053  9960 common.cpp:123] Cannot create Cublas handle. Cublas won't be available.
E1128 18:28:22.768019  9960 common.cpp:130] Cannot create Curand generator. Curand won't be available.
F1128 18:28:22.772009  9960 common.cpp:161] Check failed: error == cudaSuccess (3 vs. 0)  initialization error
*** Check failure stack trace: ***

**Comment by xyqgcs** [comment]
I have the same problem

**Comment by jasonsosen** [comment]
I have the same problem.
