### ISSUE TITLE
run './build/examples/openpose/openpose.bin --video examples/media/video.avi' error

### ISSUE THREAD

**Issue by yanghhx** [CMU-Perceptual-Computing-Lab/openpose#1777]
error is as following:
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F1129 17:09:18.732748 12455 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7fc78d7155cd  google::LogMessage::Fail()
    @     0x7fc78d717433  google::LogMessage::SendToLog()
    @     0x7fc78d71515b  google::LogMessage::Flush()
    @     0x7fc78d717e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc78b3bb701  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fc78b3f241a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @           0x5d9e94  op::NetCaffe::initializationOnThread()
    @           0x5e8f64  op::addCaffeNetOnThread()
    @           0x5ea23d  op::PoseExtractorCaffe::netInitializationOnThread()
    @           0x5ef58d  op::PoseExtractorNet::initializationOnThread()
    @           0x5e5d5e  op::PoseExtractor::initializationOnThread()
    @           0x5e0abe  op::WPoseExtractor<>::initializationOnThread()
    @           0x6112df  op::Worker<>::initializationOnThreadNoException()
    @           0x611410  op::SubThread<>::initializationOnThread()
    @           0x6140f8  op::Thread<>::initializationOnThread()
    @           0x6142df  op::Thread<>::threadFunction()
    @     0x7fc78adedc80  (unknown)
    @     0x7fc78c3016ba  start_thread
    @     0x7fc78a5534dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
faq
