### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by linjia03** [CMU-Perceptual-Computing-Lab/openpose#1778]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Executed Command (if any)
bin/openposedemo.exe -image_dir "examples/media" --logging_level 0 --disable_multi_thread

### OpenPose Output (if any)
![image](https://user-images.githubusercontent.com/26583335/100622535-ef042980-335b-11eb-8710-1e1aec3ab436.png)

### Errors (if any)
F1130 22:18:40.609138 15812 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output** 
Starting OpenPose demo...
Configuring OpenPose...
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():210
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducerType():170
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToPoseMode():11
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToPoseModel():33
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToScaleMode():82
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToHeatMapScaleMode():116
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToDetector():147
C:\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToDetector():147
Starting thread(s)...
Running configureThreadManager...
C:\openpose\src\openpose\producer\producer.cpp:op::createProducer():417
renderModePose = 3
renderModeFace = 3
renderModeHand = 3
renderOutput = 1
renderOutputGpu = 1
renderFace = 0
renderHand = 0
renderHandGpu = 0
C:\openpose\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():17
C:\openpose\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSanityChecks():184
userInputAndPreprocessingWsEmpty = 1
userOutputWsEmpty = 1
numberGpuThreads = -1
gpuNumberStart = 0
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
writeImagesCleaned = 
writeKeypointCleaned = 
writeJsonCleaned = 
writeHeatMapsCleaned = 
modelFolder = models\
finalOutputSize = [0,0]
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():371
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():436
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():441
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():452
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():506
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():558
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():602
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():646
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():663
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():680
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():699
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():715
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():748
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():773
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():782
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():798
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():799
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():808
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():825
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():845
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():866
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():875
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():879
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():885
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():944
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():960
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():966
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1042
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1076
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1180
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1204
C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1211
C:\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():419
C:\openpose\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::exec():185
C:\openpose\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > >::addPusher():362
C:\openpose\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > >::addPusher():362
C:\openpose\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > >::addPusher():362
C:\openpose\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::exec():190
C:\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::threadFunction():182
C:\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::initializationOnThread():167
Starting initialization on thread. In C:\openpose\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():172
Finished initialization on thread. In C:\openpose\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():191
Starting initialization on thread. In C:\openpose\src\openpose\pose\poseGpuRenderer.cpp:op::PoseGpuRenderer::initializationOnThread():74
Finished initialization on thread. In C:\openpose\src\openpose\pose\poseGpuRenderer.cpp:op::PoseGpuRenderer::initializationOnThread():84
C:\openpose\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::threadFunction():185
F1130 22:18:40.609138 15812 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***

2. **OpenPose version**:
openpose-1.7.0-binaries-win64-gpu-python-flir-3d_recommended.zip

3. **General configuration**:
    - **Installation mode**: Windows unzip
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows 10 x64
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):  Windows 10 x64
    - **Release or Debug mode**? (by default: release): default
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): Windows prebuild binaries

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): none
    - **OpenCV version**: OpenPose default for Windows

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):  cuda_11.1.0_456.43_win10
    - **cuDNN version**: cudnn-11.1-windows-x64-v8.0.5.39
    - **GPU model** (`nvidia-smi` in Ubuntu): RTX 3070

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
Sorry for the delay, please see my answer to #1811
