### ISSUE TITLE
Low FPS on RTX3080 

### ISSUE THREAD

**Issue by dradamPK** [CMU-Perceptual-Computing-Lab/openpose#1780]
Hi, I just tested the RTX 3080 with the OpenPose demo and only got 8 FPS. Can you tell me what could be the reason for such low value and what maximum value should I get with this card?

My test configuration:
-Ubuntu 18.04 x64
-Nvidia driver 455.23.04
-Cuda Toolkit 11.1.1
-cudNN 8.0.5.39
-OpenCV 4.5.0

Response from CMake 3.12.2:

> GCC detected, adding compile flags
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 11.1
Found cuDNN: ver. 8.0.5 found (include: /usr/local/cuda-11.1/include, library: /usr/local/cuda-11.1/lib64/libcudnn.so)
Added CUDA NVCC flags for: sm_86
Found cuDNN: ver. 8.0.5 found (include: /usr/local/cuda-11.1/include, library: /usr/local/cuda-11.1/lib64/libcudnn.so)
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending on your internet connection.
Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)
Caffe will be built from source now.
Adding Example calibration.bin
Adding Example tutorial_add_module_custom_post_processing.bin
Adding Example tutorial_api_thread_1_user_processing_function.bin
Adding Example tutorial_api_thread_2_user_input_processing_output_and_datum.bin
Adding Example openpose.bin
Adding Example 01_body_from_image_default.bin
Adding Example 02_whole_body_from_image_default.bin
Adding Example 03_keypoints_from_image.bin
Adding Example 04_keypoints_from_images.bin
Adding Example 05_keypoints_from_images_multi_gpu.bin
Adding Example 06_face_from_image.bin
Adding Example 07_hand_from_image.bin
Adding Example 08_heatmaps_from_image.bin
Adding Example 09_keypoints_from_heatmaps.bin
Adding Example 10_asynchronous_custom_input.bin
Adding Example 11_asynchronous_custom_input_multi_camera.bin
Adding Example 12_asynchronous_custom_output.bin
Adding Example 13_asynchronous_custom_input_output_and_datum.bin
Adding Example 14_synchronous_custom_input.bin
Adding Example 15_synchronous_custom_preprocessing.bin
Adding Example 16_synchronous_custom_postprocessing.bin
Adding Example 17_synchronous_custom_output.bin
Adding Example 18_synchronous_custom_all_and_datum.bin
Adding Example handFromJsonTest.bin
Adding Example resizeTest.bin
Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
fatal: not a git repository (or any of the parent directories): .git
pybind11 v2.6.2 dev1
Configuring done
Generating done

**Comment by gineshidalgo99** [comment]
Check the profiling flag (as the github template issue asks for) and i'll be able to tell you
