### ISSUE TITLE
openpose 3d error

### ISSUE THREAD

**Issue by chaytonmin** [CMU-Perceptual-Computing-Lab/openpose#1783]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

I build the openpose for multi-view multi-camera  3-D reconstruction. However , I met this problem: 
Error:
3-D reconstruction (`--3d`) requires at least 2 camera views, only found 1 camera parameter matrices. If you are simultaneously using FLIR cameras (`--flir_camera`) and the 3-D reconstruction module (`--3d), you should also enable `--frame_undistort` so their camera parameters are read.

I don't have Flir cameras, so I use ordinary cameras：
build/examples/openpose/openpose.bin --display 1 --3d --camera 0 2 4  --write_video outputVideo.avi   --number_people_max 1 --3d_min_views 2 --logging_level 0 --disable_multi_thread -num_gpu_start 1

**Comment by WestbrookZero** [comment]
@chaytonmin  I have the same problem. Have you solved it?

**Comment by adahdooh** [comment]
I'm facing the same issue, any help on how to generate the 3d pose from a video or sequence of images?

**Comment by gineshidalgo99** [comment]
To use OpenPose 3D, you need flir cameras (as the doc mentions), as I used their API for synchronization. You can use OPenPose for 3D, but you will have to implement your API to get frames synchronized. Best

**Comment by huzijiatao** [comment]
> > 要开箱即用的OpenPose 3D，您需要flir相机（如文档所述），因为我使用他们的API进行同步。您可以将 OPenPose for 3D 与任何其他摄像机一起使用，但您必须实现 API 才能同步帧。最好
> 
> real_time多相机 3D 重建应使用哪个 API 示例？在11_asynchronous_custom_input_multi_camera.cpp中，它不捕获相机，而是读取保存的视频，而在 14 和 18 示例中，它只读取图像。@gineshidalgo99

What kind of video do I need to input to output visual 3D joint points in 11_asynchronous_custom_input_multi_camera.cpp

**Comment by huzijiatao** [comment]
> > 要开箱即用的OpenPose 3D，您需要flir相机（如文档所述），因为我使用他们的API进行同步。您可以将 OPenPose for 3D 与任何其他摄像机一起使用，但您必须实现 API 才能同步帧。最好
> 
> real_time多相机 3D 重建应使用哪个 API 示例？在11_asynchronous_custom_input_multi_camera.cpp中，它不捕获相机，而是读取保存的视频，而在 14 和 18 示例中，它只读取图像。@gineshidalgo99

what kind of video need  input for output visual 3d joint point in 11_asynchronous_custom_input_multi_camera.cpp，and do you get 3d joint point in 11_asynchronous_custom_input_multi_camera.cpp?
