### ISSUE TITLE
Cuda check failed (3 vs. 0): initialization error

### ISSUE THREAD

**Issue by Esha1302** [CMU-Perceptual-Computing-Lab/openpose#1784]
![image](https://user-images.githubusercontent.com/65848409/101182317-ec634600-3673-11eb-8192-6e5c9c4e7fd7.png)

**Comment by Esha1302** [comment]
Can't find the cause of this error, tried building openpose from scratch, got the same error

**Comment by biel-jony** [comment]
Did you solve the problem? Bro. 
I got this error too, 

Error:
Cuda check failed (3 vs. 0): initialization error

Coming from:
- C:\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():48
- C:\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- C:\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():58
- C:\openpose\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1222
- C:\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424

Gpu: NVIDIA Quadro P1000

**Comment by biel-jony** [comment]
Did you solve the problem? Bro.I got this error too.
GPU: NVIDIA Quadro P1000，Is it related to GPU?

**Comment by gineshidalgo99** [comment]
Which gpu and nvidia driver so you have?

Could you try installing the latest nvidia driver?

**Comment by IceSandwich** [comment]
I got the same problem too., but it works fine if i change to 1.6.0 version.

**Comment by Esha1302** [comment]
@IceSandwich 1.6.0 version of?

**Comment by Esha1302** [comment]
Switching to 1.6.0 worked for me! Thanks @IceSandwich

**Comment by gineshidalgo99** [comment]
There are usually 2 solutions:
- 1. Update your Nvidia drivers to the latest version.  The issue is that CUDA 11 (used by OpenPose) requires the latest Nvidia drivers.
- 2. Switch back to version 1.6.0.

**Comment by Esha1302** [comment]
![image](https://user-images.githubusercontent.com/65848409/101258414-606f1e00-3748-11eb-910f-28fb0ff857c0.png)

I got this error after switching to 1.6.0, it is working fine without the write_json flag. But when i add this flag , it displays this error.

**Comment by IceSandwich** [comment]
Maybe the permission problem in windows. Try to execute it in other location instead of C:\ ?

**Comment by Esha1302** [comment]
I don't think that's the problem, I further switched to 1.5.1 and it doesn't show this error
