### ISSUE TITLE
Low FPS on RTX3080

### ISSUE THREAD

**Issue by dradamPK** [CMU-Perceptual-Computing-Lab/openpose#1785]
## Issue Summary
Hi, I just tested the RTX 3080 with the OpenPose demo and only got 8 FPS. Can you tell me please what could be the reason for such low value and what maximum value should I get with this card?

### Executed Command

`./build/examples/openpose/openpose.bin --video examples/media/video.avi --profile_speed 100`

### OpenPose Output

> Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
[ WARN:0] global /home/dradam/opencv/modules/core/src/matrix_expressions.cpp (1334) assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739
4.456380 msec in /home/dradam/openpose-master/include/openpose/producer/wDatumProducer.hpp:workProducer():79
0.002704 msec in /home/dradam/openpose-master/include/openpose/thread/wIdGenerator.hpp:work():76
0.006478 msec in /home/dradam/openpose-master/include/openpose/core/wScaleAndSizeExtractor.hpp:work():74
5.387900 msec in /home/dradam/openpose-master/include/openpose/core/wCvMatToOpInput.hpp:work():70
3.553041 msec in /home/dradam/openpose-master/include/openpose/core/wCvMatToOpOutput.hpp:work():73
119.910851 msec in /home/dradam/openpose-master/include/openpose/pose/wPoseExtractor.hpp:work():98
0.030387 msec in /home/dradam/openpose-master/include/openpose/pose/wPoseRenderer.hpp:work():79
6.974877 msec in /home/dradam/openpose-master/include/openpose/core/wOpOutputToCvMat.hpp:work():69
1.449959 msec in /home/dradam/openpose-master/include/openpose/gui/wGuiInfoAdder.hpp:work():73
5.912661 msec in /home/dradam/openpose-master/include/openpose/gui/wGui.hpp:workConsumer():87
OpenPose demo successfully finished. Total time: 39.442333 seconds.

### Type of Issue

- Question

### Your System Configuration
1. **Whole console output:** no errors in console output

2. **OpenPose version**: Latest GitHub code (1.7.0) downloaded 04.12.2020

3. **General configuration**:

-**Installation mode**: CMake 3.12.2 installation (Ubuntu):

> GCC detected, adding compile flags
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 11.1
Found cuDNN: ver. 8.0.5 found (include: /usr/local/cuda-11.1/include, library: /usr/local/cuda-11.1/lib64/libcudnn.so)
Added CUDA NVCC flags for: sm_86
Found cuDNN: ver. 8.0.5 found (include: /usr/local/cuda-11.1/include, library: /usr/local/cuda-11.1/lib64/libcudnn.so)
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Caffe has already been downloaded.
HEAD is now at 1807aada Added Ampere arch's (CUDA11)
Caffe will be built from source now.
Adding Example calibration.bin
Adding Example tutorial_add_module_custom_post_processing.bin
Adding Example tutorial_api_thread_1_user_processing_function.bin
Adding Example tutorial_api_thread_2_user_input_processing_output_and_datum.bin
Adding Example openpose.bin
Adding Example 01_body_from_image_default.bin
Adding Example 02_whole_body_from_image_default.bin
Adding Example 03_keypoints_from_image.bin
Adding Example 04_keypoints_from_images.bin
Adding Example 05_keypoints_from_images_multi_gpu.bin
Adding Example 06_face_from_image.bin
Adding Example 07_hand_from_image.bin
Adding Example 08_heatmaps_from_image.bin
Adding Example 09_keypoints_from_heatmaps.bin
Adding Example 10_asynchronous_custom_input.bin
Adding Example 11_asynchronous_custom_input_multi_camera.bin
Adding Example 12_asynchronous_custom_output.bin
Adding Example 13_asynchronous_custom_input_output_and_datum.bin
Adding Example 14_synchronous_custom_input.bin
Adding Example 15_synchronous_custom_preprocessing.bin
Adding Example 16_synchronous_custom_postprocessing.bin
Adding Example 17_synchronous_custom_output.bin
Adding Example 18_synchronous_custom_all_and_datum.bin
Adding Example handFromJsonTest.bin
Adding Example resizeTest.bin
Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
fatal: not a git repository (or any of the parent directories): .git
pybind11 v2.6.2 dev1
Configuring done
Generating done

-**Operating system** (`lsb_release -a` in Ubuntu):

> No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

- **Operating system version**: Ubuntu 18.04

- **Release or Debug mode**: release

-**Compiler**:

> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

4. **Non-default settings**:
- **3-D Reconstruction module added**: no
- Any other custom CMake configuration with respect to the default version?:

> BUILD_PYTHON=ON
PROFILER_ENABLED=ON

5. **3rd-party software**:
- **Caffe version**: Default from OpenPose
- **CMake version**:

> cmake version 3.12.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

- **OpenCV version**: 

> ~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.4.0'
>>> 

6.  **GPU mode**:

- **CUDA version** :

> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

- **cuDNN version**:

> N_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#endif /* CUDNN_VERSION_H */

- **GPU model**:

>GeForce RTX 3080
NVIDIA-SMI 455.23.04

7. **CPU-only mode**: no CPU issue

8. **Python** API:

- **Python version**: 3.6.9

- **Numpy version**:

> ~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.19.4'
>>> 

9. **Windows** system: not applicable

10. **Speed performance** issue: only approximately 8 FPS on demo code

**Comment by dradamPK** [comment]
While testing ` $ python3 04_keypoints_from_images.py ` from examples, approx. at the fifth image I get this error below. What might be the reason of that?

>F1212 15:34:46.538151  4049 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f69315c40cd  google::LogMessage::Fail()
    @     0x7f69315c5f33  google::LogMessage::SendToLog()
    @     0x7f69315c3c28  google::LogMessage::Flush()
    @     0x7f69315c6999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f69310c1b0a  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f6930f21412  caffe::Blob<>::mutable_gpu_data()
    @     0x7f6931109a49  caffe::ConcatLayer<>::Forward_gpu()
    @     0x7f6931089642  caffe::Net<>::ForwardFromTo()
    @     0x7f693e8981c5  op::NetCaffe::forwardPass()
    @     0x7f693e8c0742  op::PoseExtractorCaffe::forwardPass()
    @     0x7f693e8b9675  op::PoseExtractor::forwardPass()
    @     0x7f693e8b64d6  op::WPoseExtractor<>::work()
    @     0x7f693e8f86e9  op::Worker<>::checkAndWork()
    @     0x7f693e8f8873  op::SubThread<>::workTWorkers()
    @     0x7f693e9024d8  op::SubThreadQueueInOut<>::work()
    @     0x7f693e8fab51  op::Thread<>::threadFunction()
    @     0x7f69541156df  (unknown)
    @     0x7f695c9df6db  start_thread
    @     0x7f695cd1971f  clone
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
Is you GPU busy doing other work? It is very weird that the 3080 does not reach 20-30 FPS:

This line shows that the bottleneck is "just" the GPU, but i am very concerned on why a 3080 is slower than my 1070
119.910851 msec in /home/dradam/openpose-master/include/openpose/pose/wPoseExtractor.hpp:work():98

**Comment by gineshidalgo99** [comment]
Could you show your `nvidia-smi` result while running OpenPose? To see if something else is running on the background?

**Comment by dradamPK** [comment]
Thank you for your reply.
In the meantime, I reinstalled Ubuntu. All parameters remain as mentioned at the beginning. I only installed the latest nVidia 455.45.01 driver. I saw that there is also a new CUDA 11.2, but I am not installing it because at the moment there is no cudNN for 11.2 yet.

In answer to your question, my GPU is not busy doing other work while I'm testing OpenPose. The minimal Ubuntu I installed is only used for OpenPose purposes. There is an `nvidia-smi` result in the image while the demo is running.

![Screenshot from 2020-12-17 10-39-38](https://user-images.githubusercontent.com/75452358/102470956-e2b6e680-4054-11eb-8d11-21f70ae901a6.png)

**Comment by diepgfai** [comment]
I can confirm that Openpose 1.7.0 can be successfully built with NVIDIA Geforce RTX 3090, CUDA 11.1 and CUDNN 8. But the performance of the 3090 is just as good as 2080 Ti. 
I have tested using the video.avi in the example. Both GPUs have 13-14 fps, which does not make any sense, since the 3090 has more CUDA Cores.

**Comment by dradamPK** [comment]
**diepgfai** thank you for sharing your test results. 

I connected the graphics card directly to the PCI-Express x16 on motherboard (so far I had to use the Riser USB 3.0). Now the speed of the demo program has increased to 10 FPS. Python code `$ python3 04_keypoints_from_images.py` still stops at the fifth image.

Can anyone tell what may be the reason for the low performance of the newest RTX'es? And why the `out of memory` error occurs on Python program?

**Comment by zn123** [comment]
--write_json output_json38_2 --render_pose 0  --display 0

**Comment by dradamPK** [comment]
I found a solution for the `04_keypoints_from_images` codes in Python and C ++. It is necessary to downsize each image in the target directory. I created a new catalog with 20 photos at 368x368 pixels and then the program was successful.

**zn123** to compare I put below results from openpose demo with and without your parameters:

![Screenshot from 2020-12-24 12-33-38](https://user-images.githubusercontent.com/75452358/103087041-92a4ca80-45e6-11eb-8ea1-e84edc993b3b.png)
![Screenshot from 2020-12-24 12-32-04](https://user-images.githubusercontent.com/75452358/103087034-8e78ad00-45e6-11eb-9c6e-a382cdeb9a73.png)

**Comment by gineshidalgo99** [comment]
As @zn123 said, --render_pose 0 --display 0 will increase the speed a bit, as it won't spend time rendering the image on the display. So I recommend it if you don't need to look at the results.

@dradamPK About the out of memory error, it should not happen anymore (by default at least) in the latest master code (I added net_resolution_dynamic if you want more details about it). Also because of this, the speed should be a bit more consistent. Accuracy might drop in theory (for panoramic images), but in practice it's really not important unless you have a lot of panoramic images.

**Comment by rajhlinux** [comment]
> Hi, I just tested the RTX 3080 with the OpenPose demo and only got 8 FPS. Can you tell me please what could be the reason for such low value and what maximum value should I get with this card?

:rofl: :rofl:
