### ISSUE TITLE
Importing data and writing video after the fact

### ISSUE THREAD

**Issue by jabrantley** [CMU-Perceptual-Computing-Lab/openpose#1788]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary

I am wondering if it is possible to load the data and export the video at a later time. For example, if I want to filter the data to remove high freq noise on the movements and then write the video using the filtered data. I am currently using command line implementation. 

### Executed Command (if any)
This is what I hope to find out!

### OpenPose Output (if any)
N/A

### Errors (if any)
N/A

### Type of Issue
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK 

n/a

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)? 
Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...? make
    - **Operating system** (`lsb_release -a` in Ubuntu): 
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

Currently using command line in colab

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):  No 
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

**Comment by gineshidalgo99** [comment]
Sorry, I am not sure i follow your question. Could you please elaborate it a bit more? thanks!

**Comment by jabrantley** [comment]
Thanks for your reply! I am sorry for being unclear. I am currently running openpose on a bunch of videos in batch. The results are neat but have quite a bit of high-frequency noise / jitter on the movements. I am planning to filter the data and do some additional processing. I want to know how I can use the filtered data when rendering the videos? Is there a way to load these data and then use them to render videos?  Basically, I want to:

1. run openpose in batch on server w/ `--display 0` and `--write_video 0`
2. process data separately. e.g., filtering, pre-process for ML
3. use filtered data to `--write_video `

I would not change anything about the format of openpose data so I can continue to use the openpose framework. I feel like this is a simple solution but I can't seem to find the answer in previous issues. 

Please let me know if this still does not clarify the issue. Thanks!

**Comment by gineshidalgo99** [comment]
OK, the easiest thing would be to create your own C++/Python code following the examples/tutorial_api_cpp  or python-analog folder, then you can eg create code to load the cleaned JSONs, read the keypoints from there and use the OpenPose output (renderer). It's not too hard, but will for sure require some work to load the keypoints back onto the OpenPose framework.
