### ISSUE TITLE
Compilation/installation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by chencjiajy** [CMU-Perceptual-Computing-Lab/openpose#179]
### Issue summary

when install caffe in folder: 3rdparty/caffe,  I met the error like this ( many prints are the same):

.build_release/src/caffe/proto/caffe.pb.h: In member function ‘void caffe::V0LayerParameter::clear_has_concat_dim()’:
.build_release/src/caffe/proto/caffe.pb.h:25700:3: error: ‘_has_bits_’ was not declared in this scope
   _has_bits_[0] &= ~0x00400000u;

Makefile:586: recipe for target '.build_release/src/caffe/util/upgrade_proto.o' failed
make: *** [.build_release/src/caffe/util/upgrade_proto.o] Error 1
Makefile:586: recipe for target '.build_release/src/caffe/util/db.o' failed
make: *** [.build_release/src/caffe/util/db.o] Error 1
Makefile:586: recipe for target '.build_release/src/caffe/util/im2col.o' failed
make: *** [.build_release/src/caffe/util/im2col.o] Error 1

### Executed command (if any)

make all -j8 

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### system configuration
**Ubuntu 16.04
**CUDA version : 8.0
**cuDNN version**: 6.0
**GPU model** : Tesla K80
**Caffe version**: Default from OpenPose 
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu)
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu)
Compiler (`gcc --version` in Ubuntu): 5.4.0

**Comment by NonvolatileMemory** [comment]
yeah,I got the same problem.And I think maybe it caused by the makefile of caffe.

**Comment by gineshidalgo99** [comment]
Otherwise, try updating Protobuf, the error is coming from there.

You might also try the new CMake installer to see if it's solved there.
