### ISSUE TITLE
Error in Version of CUDA, CUDANN

### ISSUE THREAD

**Issue by Ankita18Mandal** [CMU-Perceptual-Computing-Lab/openpose#1795]
While running this script in colab, I got error 
nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at cuda_compile_1_generated_absval_layer.cu.o.Release.cmake:219 (message)
Any suggestions would be appreciated.

**Comment by colinbouvry** [comment]
I have the same error with GPU_MODE CUDA
UBUNTU 18.4 
CUDA 10.1
cuDNN 7.5.1

**Comment by colinbouvry** [comment]
Work perfect with CUDA 10.2
See scripts/install_cuda.sh
Openpose should update doc installation !

**Comment by gineshidalgo99** [comment]
Doc updated, CUDA 11 should be used for v1.7.0 and latest. CUDA10 should use v1.6.0, sorry about that!
