### ISSUE TITLE
how to use it on centos system?

### ISSUE THREAD

**Issue by liaowang0125** [CMU-Perceptual-Computing-Lab/openpose#18]
### Issue summary
can i use it on centos7?

### Your system configuration
**Operating system** (`centos7`):
**CUDA version** (`cuda8`):

**Comment by gineshidalgo99** [comment]
I am sorry, but we do not have any Centos machine to try it.

The OpenPose code uses c++11 and the same dependencies than Caffe. So if you are able to compile Caffe (with CUDA and cuDNN) of you own on Centos, you should be able to install OpenPose too.

Please, if you are able to install it, a few lines with the basic steps would be highly appreciated for other Centos users.

**Comment by liaowang0125** [comment]
I will reply if I succeed

**Comment by liaowang0125** [comment]
Compiled OpenPose successfully.

Just as you say,**modify the _CAFFE_DIR_ ,and have an compiled caffe is enough**. 

When I first comment,I met the google::protobuf undefined reference problem,I solved it and can install OpenPose.

**Comment by ZheC** [comment]
Great, thanks for letting us know.

**Comment by saxenarohan97** [comment]
@liaowang0125 How did you modify the CAFFE_DIR, can you please elaborate?

**Comment by liaowang0125** [comment]
modify it to the path to your compiled caffe,like: **path/caffe** @saxenarohan97

**Comment by ankit204** [comment]
Just writing down the steps I ended up running to make things work on centOS.
Create and move to build directory.
Use this command to point cmake to correct libs and include dirs for an existing caffe build:
`$ cmake -DCaffe_INCLUDE_DIRS=/caffe-rc3/include/ -DCaffe_LIBS=/caffe-rc3/build/lib/libcaffe.so -DBUILD_CAFFE=OFF ..`
It gave the following error issuing `make`:
```
Linking CXX executable openpose.bin
/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
/bin/ld: note: 'pthread_rwlock_wrlock@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
/lib64/libpthread.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [examples/openpose/openpose.bin] Error 1
make[1]: *** [examples/openpose/CMakeFiles/openpose.bin.dir/all] Error 2
```

To resolve this, I added a flag to CMakeLists.txt after which the unix sub-case looks like this:

```
elseif (UNIX AND NOT APPLE)
  # Turn on C++11
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lpthread")
  add_definitions(-std=c++11)
  set(CMAKE_CXX_FLAGS_RELEASE "-O3")
```
After the change, issuing `cmake` and `make` should build successfully.
When running the demo, make sure to use `--display 0` if you face X11 issues. Full command:
`$ ./build/examples/openpose/openpose.bin --net_resolution "64x48" --image_dir examples/media/ --display 0 --write_json out`

**Comment by gineshidalgo99** [comment]
@ankit204 
Thanks for the feed-back. I've just pushed a fix to include pthread as you did. Could you try the latest OpenPose and let me know if it works by default? Thanks!

**Comment by boris-lb** [comment]
@liaowang0125 ,can you tell me how do you solve the google::protobuf undefined reference problem？this is my error msg：
[ 91%] Linking CXX executable cpp_classification/classification
[ 93%] Linking CXX executable upgrade_net_proto_text
[ 93%] Linking CXX executable upgrade_net_proto_binary
[ 93%] Linking CXX executable caffe
[ 94%] Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)’未定义的引用
collect2: 错误：ld 返回 1
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)’未定义的引用
collect2: 错误：ld 返回 1
make[5]: *** [tools/convert_imageset] 错误 1
make[4]: *** [tools/CMakeFiles/convert_imageset.dir/all] 错误 2
make[4]: *** 正在等待未完成的任务....
make[5]: *** [examples/siamese/convert_mnist_siamese_data] 错误 1
make[4]: *** [examples/CMakeFiles/convert_mnist_siamese_data.dir/all] 错误 2
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::AssignDescriptors(std::string const&, google::collect2: 错误：ld 返回 1
protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)’未定义的引用
collect2: 错误：ld 返回 1
make[5]: *** [examples/cifar10/convert_cifar_data] 错误 1
make[5]: *** [examples/mnist/convert_mnist_data] 错误 1
make[4]: *** [examples/CMakeFiles/convert_cifar_data.dir/all] 错误 2
make[4]: *** [examples/CMakeFiles/convert_mnist_data.dir/all] 错误 2

**Comment by JeBo89** [comment]
> Just writing down the steps I ended up running to make things work on centOS.
> Create and move to build directory.
> Use this command to point cmake to correct libs and include dirs for an existing caffe build:
> `$ cmake -DCaffe_INCLUDE_DIRS=/caffe-rc3/include/ -DCaffe_LIBS=/caffe-rc3/build/lib/libcaffe.so -DBUILD_CAFFE=OFF ..`
> It gave the following error issuing `make`:
> 
> ```
> Linking CXX executable openpose.bin
> /bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
> /bin/ld: note: 'pthread_rwlock_wrlock@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
> /lib64/libpthread.so.0: could not read symbols: Invalid operation
> collect2: error: ld returned 1 exit status
> make[2]: *** [examples/openpose/openpose.bin] Error 1
> make[1]: *** [examples/openpose/CMakeFiles/openpose.bin.dir/all] Error 2
> ```
> To resolve this, I added a flag to CMakeLists.txt after which the unix sub-case looks like this:
> 
> ```
> elseif (UNIX AND NOT APPLE)
>   # Turn on C++11
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lpthread")
>   add_definitions(-std=c++11)
>   set(CMAKE_CXX_FLAGS_RELEASE "-O3")
> ```
> After the change, issuing `cmake` and `make` should build successfully.
> When running the demo, make sure to use `--display 0` if you face X11 issues. Full command:
> `$ ./build/examples/openpose/openpose.bin --net_resolution "64x48" --image_dir examples/media/ --display 0 --write_json out`

Is this solution still applicable today?

**Comment by guker** [comment]
it works.
os system: centos7 , default( protobuf 2.6.1, gcc 4.8.5)
1. git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose
2. cd 3rdparty
3. git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git
4. cd caffe
5. cp Makefile.config.Ubuntu14_cuda8.example Makefile.config
6. modify  blas choice by changing BLAS := open
7. make all # in caffe dir
