### ISSUE TITLE
Extract single (biggest) person

### ISSUE THREAD

**Issue by jthsieh** [CMU-Perceptual-Computing-Lab/openpose#180]
### Issue summary

I've been using the openpose demo binary (openpose.bin), and it works perfectly. However, ideally I would like to extract only the biggest person in the video/image. I found the `getBiggestPerson()` function in utilities/keypoints.cpp, but I don't know where to add it to the demo code. Can you point me to the place where I should add the code, or is there another easier way to extract just the biggest person?

### Type of issue
You might select multiple topics, delete the rest:
- Help wanted
- Question

### Your system configuration
**Operating system**: Ubuntu 16.04
**CUDA version** : 8.0.61
**cuDNN version**: 
**GPU model**: Tesla K80
**Caffe version**: Default from OpenPose.
**OpenCV version**: OpenCV 3

**Comment by Prestal** [comment]
Hi, jthsieh.

Easies way for CPU rendering:

In "keypoint.cpp"
In "void renderKeypointsCpu()"

replace main for cycle to
"for (auto person = getBiggestPerson(keypoints, threshold); person < keypoints.getSize(0) ; person++)"

and insert
"break;"
at the end of this "FOR"

Thats all

**Comment by jthsieh** [comment]
Thank you. The generated videos now only show the biggest person.
However, I would like the keypoint json files (with the `--write_keypoint_json` flag) to contain only the biggest person's keypoints. How can I do that?

**Comment by Prestal** [comment]
Its strange, because I needed the same thing as you are. But solution that I wrote helped me. 

Why do you thing that you get all key points? How many keypoints do you have in json file?

**Comment by Prestal** [comment]
Yes, you right, forgot about that part.
Make it be the start of the "FOR" that you modified by the previous message.

for (auto person = 0 ; person < keypoints.getSize(0) ; person++)
				{
					const auto personRectangle = getKeypointsRectangle(keypoints, person, numberKeypoints, thresholdRectangle);
					if (personRectangle.area() > 0)
					{

						auto oldKeys = keypoints.clone();
						Array<float>& freeKeypoints = const_cast<Array<float>&>(keypoints);
						freeKeypoints.reset({ 1, (int)numberKeypoints, 3 });


						for (int i = 0; i < numberKeypoints * oldKeys.getSize(2); i++)
						{
							auto b = person * numberKeypoints * oldKeys.getSize(2) + i;
							auto a = oldKeys[person * numberKeypoints * oldKeys.getSize(2) + i];
							freeKeypoints[i] = a;
						}


						person = 0;




Next row should be :
const auto ratioAreas = fastMin(1.f, fastMax(personRectangle.width/(float)width, personRectangle.height/(float)height));

from the original file.

This code is kinda tricky and probably have UB coz keypoints, dat we have from NN came like const one, so i modifed the length of keypoints MAT munually. But it works :)

**Comment by jthsieh** [comment]
It works. Thank you very much!!

**Comment by Feifannaner** [comment]
@Prestal  Thank you for your advice .but just as you suggested, i modified the for cycle and add the break signal in the end. However,I still find two or more people rendered  when i RUN the openpose.bin. Is there some different in the new version?

**Comment by alexadp1087** [comment]
Hello, when i am going to change the code inside keypoint.cpp and rebuild the solution whit your biggest person code, i get all this error:



Severity	Code	Description	Project	File	Line	Suppression State
Error	C2672	'getKeypointsRectangle': no matching overloaded function found	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	209	
Error	C2780	'op::Rectangle<T> op::getKeypointsRectangle(const op::Array<T> &,const int,const T)': expects 3 arguments - 4 provided	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	209	
Error	C2789	'personRectangle': an object of const-qualified type must be initialized	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	209	
Error	C3536	'personRectangle': cannot be used before it is initialized	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	210	
Error	C2672	'op::fastMax': no matching overloaded function found	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	226	
Error	C2780	'T op::fastMax(const T,const T)': expects 2 arguments - 1 provided	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	227	
Error	C2672	'op::fastMin': no matching overloaded function found	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	226	
Error	C2780	'T op::fastMin(const T,const T)': expects 2 arguments - 1 provided	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	227	
Error	C2789	'ratioAreas': an object of const-qualified type must be initialized	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	226	
Error	C3536	'ratioAreas': cannot be used before it is initialized	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	230	
Error	C2440	'const_cast': cannot convert from 'const op::Array<double>' to 'op::Array<float> &'	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	214	
Error	C2530	'freeKeypoints': references must be initialized	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	214	
Warning	C4244	'=': conversion from 'T' to 'T', possible loss of data	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	221	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	438	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	492	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	494	
Warning	C4267	'argument': conversion from 'size_t' to 'const int', possible loss of data	openpose	D:\Alex\OPENPOSE\openpose-master\src\openpose\utilities\keypoint.cpp	495	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	01_body_from_image_default	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	OpenPoseDemo	D:\Alex\OPENPOSE\openpose-master\build\examples\openpose\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	03_keypoints_from_image	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	02_whole_body_from_image_default	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	05_keypoints_from_images_multi_gpu	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	04_keypoints_from_images	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	06_face_from_image	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	09_keypoints_from_heatmaps	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	10_asynchronous_custom_input	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	08_heatmaps_from_image	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	11_asynchronous_custom_output	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	12_asynchronous_custom_input_output_and_datum	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	13_synchronous_custom_input	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	14_synchronous_custom_preprocessing	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	15_synchronous_custom_postprocessing	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	17_synchronous_custom_all_and_datum	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_cpp\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	1_custom_post_processing	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_add_module\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	1_thread_user_processing_function	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_thread\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	2_thread_user_input_processing_output_and_datum	D:\Alex\OPENPOSE\openpose-master\build\examples\tutorial_api_thread\LINK	1	
Error	LNK1181	cannot open input file '..\..\src\openpose\Release\openpose.lib'	Calibration	D:\Alex\OPENPOSE\openpose-master\build\examples\calibration\LINK	1	


Can you help me?
Thank you very much
