### ISSUE TITLE
RTX 2080Ti vs RTX 3090

### ISSUE THREAD

**Issue by krcc5978** [CMU-Perceptual-Computing-Lab/openpose#1803]
## Issue Summary

Excuse me.
I measured the average time with RTX2080Ti and RTX3090 that use pythonAPI.
I thought that RTX3090 was faster than RTX2080Ti because RTX3090 has higher performance than RTX2080Ti, but the result was that RTX3090 was about 20 [msec] slower than RTX2080Ti .

Why do you think I got this result?

### System Configuration
・Windows 10 Pro
・CMake 3.16
・Visual Studio 2019
・CUDA 11.0
・cuDNN 8.0.4

### Verification
used code : 01_body_from_image.py
models : body_25
```
# Used this code that measure time 

opWrapper = op.WrapperPython()
opWrapper.configure(params)
opWrapper.start()

# Process Image
datum = op.Datum()
imageToProcess = cv2.imread(args[0].image_path)
datum.cvInputData = imageToProcess
ave_time = 0
for i in range(1000):
    s = time.time()
    opWrapper.emplaceAndPop(op.VectorDatum([datum]))
    ave_time += time.time()-s
    print(time.time()-s)
print(ave_time/1000)

# Display Image
#print("Body keypoints: \n" + str(datum.poseKeypoints))
#cv2.imshow("OpenPose 1.7.0 - Tutorial Python API", datum.cvOutputData)
#cv2.waitKey(0)
```

**Comment by zn123** [comment]
CUDA 11.0 lower ，no support 3090

**Comment by gineshidalgo99** [comment]
How does the C++ version compare with both of them?

**Comment by krcc5978** [comment]
@gineshidalgo99 
 
I compared RTX2080Ti and RTX3090 using python API.
I don't compare C++ version and python API.

**Comment by zn123** [comment]
python only shell;  please rebuild pyopenpose

**Comment by zn123** [comment]
//ubuntu18.04 cuda11.1 rtx3090x4
openpose.bin --video kssp_38.38.mp4 --write_json output_json38_2 --render_pose 0  --display 0 
OpenPose demo successfully finished. Total time: 44.488074 seconds.
//windows cuda10.1 rtx2070s
OpenPoseDemo.exe --video E:\ai_data\examples\media\kssp_38.38.mp4 --render_pose 0 --display 0  --write_json output_json
OpenPose demo successfully finished. Total time: 132.126076 seconds.

**Comment by zn123** [comment]
![image](https://user-images.githubusercontent.com/3916170/103074125-ee318100-4603-11eb-831f-1832a9b0cf2b.png)

**Comment by krcc5978** [comment]
@zn123 

Sorry for the late reply, and in this case I made a mistake in the version of openpose I was comparing.
I'm sorry for making a noise

**Comment by gineshidalgo99** [comment]
@krcc5978 Thanks for updating us! A final question, which OpenPose version was slow for the 3090 and which one was fast? Just to double check that the latest versions are as fast as they should, thanks!

**Comment by krcc5978** [comment]
@gineshidalgo99 

When I tried, I pulled from version 1.7.0 was slow, and I pulled from master was fast.

**Comment by gineshidalgo99** [comment]
Then hopefully the next v1.7.1 should be fast if master is fast. Thanks for the information!

**Comment by rajhlinux** [comment]
> @gineshidalgo99
> 
> I compared RTX2080Ti and RTX3090 using python API. I don't compare C++ version and python API.

Yea keep doing that and your problems will never be gone. Do things in C/C++ you'll see performance gains.

**Comment by rajhlinux** [comment]
> @krcc5978
> 
> I compared RTX2080Ti and RTX3090 using python API. I don't compare C++ version and python API.

yea, keep doing that and your problems will never be resolved in your machine vision latency issues. Program in C/C++ and you'll gain FPS boost.

**Comment by rajhlinux** [comment]
> @krcc5978
> 
> When I tried, I pulled from version 1.7.0 was slow, and I pulled from master was fast.

How fast?
