### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by zn123** [CMU-Perceptual-Computing-Lab/openpose#1805]
ubuntu 18.04
cuda 10.1
rtx3090 <------
@/@

make
src/openpose/CMakeFiles/openpose.dir/build.make:70: recipe for target 'src/openpose/CMakeFiles/openpose.dir/gpu/openpose_generated_cuda.cu.o' failed
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/gpu/openpose_generated_cuda.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_86'
CMake Error at openpose_generated_renderFace.cu.o.Release.cmake:219 (message):

**Comment by gineshidalgo99** [comment]
You will probably need CUDA 11 for compute_86 / 3090, please upgrade CUDA.
https://forums.developer.nvidia.com/t/can-rtx-3080-support-cuda-10-1/155849
