### ISSUE TITLE
How can I get keypionts heatmaps?

### ISSUE THREAD

**Issue by sdustdk1427** [CMU-Perceptual-Computing-Lab/openpose#1806]
How do I get the keypoints heatmaps of each figure and save them separately? I don't want to save them together with PAFs and other three parts. The effect of the heatmaps is shown as the following figure.When I used -- Part to show, the effect shown in the following figure did not appear.I want to get body_heat_map.png for each keypoints.So what should I do?Thank you!
![image](https://user-images.githubusercontent.com/23044599/103091074-ef77a380-462d-11eb-994c-7d565bc830b4.png)

**Comment by gineshidalgo99** [comment]
After OpenPose have saved them all as a single PNG/JPG, you can run some post-procesing python script to split it.

If you want to save a specific body part (with or without overlapping the background image), you can use --write_video / --write_images with --part_to_show (and optionally with --disable_blending)
