### ISSUE TITLE
Error when make -j`nproc`

### ISSUE THREAD

**Issue by Vegetebird** [CMU-Perceptual-Computing-Lab/openpose#1807]
[  3%] Built target openpose_lib
[  3%] Linking CXX shared library libopenpose.so
/usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/openpose/CMakeFiles/openpose.dir/build.make:6827: recipe for target 'src/openpose/libopenpose.so.1.6.0' failed
make[2]: *** [src/openpose/libopenpose.so.1.6.0] Error 1
CMakeFiles/Makefile2:219: recipe for target 'src/openpose/CMakeFiles/openpose.dir/all' failed
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by G-Apple1** [comment]
i have the same problem. please tell me  if you had solved the problem.

**Comment by Vegetebird** [comment]
> i have the same problem. please tell me if you had solved the problem.

Hi~I solve this problem by reinstall the OpenCV and ffmpeg

**Comment by prakharrrr4** [comment]
I have the same problem. Can you please elaborate further?

**Comment by Vegetebird** [comment]
> I have the same problem. Can you please elaborate further?

Hi~I solve this problem by reinstall the OpenCV and ffmpeg from souce.
