### ISSUE TITLE
0 people detected

### ISSUE THREAD

**Issue by CharlotteZsy** [CMU-Perceptual-Computing-Lab/openpose#181]
### Issue summary
Hello! When I run your latest code on the video and images provided by the code, outputs are able to be displayed but with the result of 0 people found. There's no error during compilation and I have checked that all the 4 models have been downloaded already and placed in right folders. I have tried to reinstall openpose and recomplie opencv but don't work.

Here is a screenshot of the output of the video:
<img width="641" alt="1" src="https://user-images.githubusercontent.com/30646843/28859327-42473e80-7789-11e7-8942-ecadfe7abb29.png">

Here is the contents in Terminal:
$ ./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 0
Starting pose estimation demo.
Starting thread(s)
Real-time pose estimation demo successfully finished. Total time: 2.781860 seconds.

Hope to get your help! Thank you!

### Type of issue
You might select multiple topics, delete the rest:
- Help wanted

### Your system configuration
**Operating system** : Ubuntu14.04 LTS
**CUDA version** : 8.0
**cuDNN version** : 6.0
**GPU model** : NVIDIA Tesla K40c
**Caffe version** : Default from OpenPose
**OpenCV version** : OpenCV 3.1.0
Generation mode (only for Ubuntu): Makefile + Makefile.config
Compiler (`gcc --version` in Ubuntu) : 4.8

**Comment by gineshidalgo99** [comment]
You are not using any GPU ('num_gpu 0'), use at least 1 (or not use that flag at all since it automatically recognizes the GPUs).

**Comment by WeihongM** [comment]
@gineshidalgo99  hello, I met the same problem. When I use the comand --num_gpu 0, why there are no detected people from the image?  what's more, it return the sentence, which is "Real-time pose estimation demo successfully finished. Total time: 7.039026 seconds."  successfully finished???

**Comment by gineshidalgo99** [comment]
You are not using any GPU ('num_gpu 0'), use at least 1 (or not use that flag at all since it automatically recognizes the GPUs).

**Comment by WeihongM** [comment]
which condition can I use the command 'num-gpu 0'? 
thanks a lot

**Comment by gineshidalgo99** [comment]
As it is not using GPUs, it is not using pose detection detectors, so I use it to e.g. record the webcam or decompose video to images.

**Comment by WeihongM** [comment]
Actually I am confused at this [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md](url)   I find the doc which title "Rendering Face and Hands without Pose " , what is the difference between face_render 1 (or 2), and the second question,  CPU (faster) means it can run on --num_gpu 0 ? sorry for the above confused problem.

**Comment by gineshidalgo99** [comment]
`CPU (faster)`? I do not understand that, there is no CPU option, only GPU version. `face_render`: check the doc
