### ISSUE TITLE
installation error : $ cmake-gui .. Error: could not load cache

### ISSUE THREAD

**Issue by monacv** [CMU-Perceptual-Computing-Lab/openpose#1812]
When I am running cmake, I get this error. Is it expected and should I just ignore it?

![Screenshot from 2021-01-05 19-10-20](https://user-images.githubusercontent.com/76495162/103713215-c6d69e80-4f89-11eb-9126-42efab16bc36.png)

my results
![Screenshot from 2021-01-05 19-10-04](https://user-images.githubusercontent.com/76495162/103713223-cccc7f80-4f89-11eb-93da-7e17aa6ad868.png)

```

$ cmake-gui ..
Error: could not load cache
```
I have:

```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
7718/31772MB
[21844:4668 0:1866] 07:12:07 Tue Jan 05 [mona@goku:pts/5 +1] ~/research/code/openpose/build
$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).


```

**Comment by gineshidalgo99** [comment]
#1815 is newer so i guess this one is closed?

**Comment by monacv** [comment]
I agree that getting this error apparently doesn't affect the process.
