### ISSUE TITLE
installation screenshots not available anymore

### ISSUE THREAD

**Issue by monacv** [CMU-Perceptual-Computing-Lab/openpose#1813]
Could you please make the installation screenshots in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/README.md available again?

Here's an example that has 404 error if you also click on images:
![Screenshot from 2021-01-05 19-24-32](https://user-images.githubusercontent.com/76495162/103714088-cccd7f00-4f8b-11eb-8e81-880554e540ae.png)

**Comment by gineshidalgo99** [comment]
Sorry fixed!

**Comment by monacv** [comment]
Thanks a lot for taking care of that and maintaining it.
