### ISSUE TITLE
Hand detector

### ISSUE THREAD

**Issue by alecda573** [CMU-Perceptual-Computing-Lab/openpose#1816]
Does the hand model contain the hand detector embedded also, if not where can I find the model weights for the hand detector you guys use?

**Comment by gineshidalgo99** [comment]
You can see the OpenPose paper for more details, but we mostly just do a bounding box based on the body keypoints

**Comment by alecda573** [comment]
@gineshidalgo99 Thanks for the response, can you point me to the file that has the code for how you create the bounding box and extract the sub image on which you perform hand keypoint detection?

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/hand/handDetector.cpp
