### ISSUE TITLE
I cannot download the trained models via getModels.sh

### ISSUE THREAD

**Issue by fengsky401** [CMU-Perceptual-Computing-Lab/openpose#182]
I tried to install and compile Openpose, when I downloaded the models using bash ./getModels.sh, it could not be connected.

```
> $ bash ./getModels.sh
--2017-08-03 10:31:18--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:20--  (try: 2)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:22--  (try: 3)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:25--  (try: 4)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:29--  (try: 5)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:35--  (try: 6)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:41--  (try: 7)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:48--  (try: 8)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:31:56--  (try: 9)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:32:06--  (try:10)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:32:16--  (try:11)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:32:26--  (try:12)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2017-08-03 10:32:36--  (try:13)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.


```

**Comment by Prestal** [comment]
1. Be sure, that you have the last version of Openpose.
2. Anyway you can download this file manually. Like it seems in your log somehow u can't download 

                http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel

That is available manually. Just insert this link to the browser, and save thos file to
{openpose_folder}\models\pose\coco\

**Comment by gineshidalgo99** [comment]
It looked like an Internet connection issue at that specific moment. If someone experiences that error, please try again after a few minutes, it has never happened to me yet.

**Comment by facejun** [comment]
maybe it is the reason of window defender,i met the question now and i  still dont know how to deal with it

**Comment by gineshidalgo99** [comment]
You an always manually download them following doc/installation.md links.

**Comment by d-fal** [comment]
Dear @gineshidalgo99, I checked out the link and I get this:
![Screenshot from 2020-05-17 16-13-39](https://user-images.githubusercontent.com/9105940/82143492-9ce53600-9859-11ea-88a4-98a0abe48d79.png)

**Comment by ekam14** [comment]
Yes, same issue.

**Comment by gormonn** [comment]
@ekam14
@d-fal
COCO:
https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe-models/raw/master/caffe_models/openpose/caffe_model/pose_iter_440000.caffemodel

**Comment by Neafiol** [comment]
Yes, same issue, what about other models?

**Comment by endlight** [comment]
Same issue. 
The web cannot be reached for at least 3 days.

**Comment by gineshidalgo99** [comment]
It is now back up. Sorry!

**Comment by d-fal** [comment]
@gineshidalgo99 issue persists!

**Comment by SebTota** [comment]
It seems that the site is back down again.

**Comment by normandyr** [comment]
The Kaggle link doesn't work.  When I go to download it wants me to sign-in but won't let me actual sign in.  If I try to create a new account if provides a non-scrollable window.

**Comment by sr714** [comment]
@mchiovaro @gineshidalgo99 I understand that the CMU link to caffe models is down. Are there different versions of caffemodels for ubuntu and windows? I've windows caffe models saved but need to run openpose in ubuntu(running on windows is not an option). If they are different,, does anyone have ubuntu version of caffe models hosted elsewhere?

When I manually uploaded the windows caffe models and tried to run openpose, it fails with the message below.
*************** message ****
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0609 06:36:46.621732 18837 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7fc2647c20cd  google::LogMessage::Fail()
    @     0x7fc2647c3f33  google::LogMessage::SendToLog()
    @     0x7fc2647c1c28  google::LogMessage::Flush()
    @     0x7fc2647c4999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc264354c61  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fc2642ec3da  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fc26639bb27  op::NetCaffe::initializationOnThread()
    @     0x7fc2663c0074  op::addCaffeNetOnThread()
    @     0x7fc2663c1556  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fc2663c7113  op::PoseExtractorNet::initializationOnThread()
    @     0x7fc2663bbdf1  op::PoseExtractor::initializationOnThread()
    @     0x7fc2663b6ba1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fc2663fac41  op::Worker<>::initializationOnThreadNoException()
    @     0x7fc2663fad70  op::SubThread<>::initializationOnThread()
    @     0x7fc2663fd0c8  op::Thread<>::initializationOnThread()
    @     0x7fc2663fd297  op::Thread<>::threadFunction()
    @     0x7fc265c916df  (unknown)
    @     0x7fc2651986db  start_thread
    @     0x7fc2656ec88f  clone

**Comment by gineshidalgo99** [comment]
Ubuntu models are just auto-downloaded with CMake from another GitHub repo, that is not down.

**Comment by OmarGarciaAlc** [comment]
> @shadkain All models are on Kaggle, select Download (783 MB) next to New Notebook and it will give you all of them. https://www.kaggle.com/changethetuneman/openpose-model

After downloading what's the correct route to paste the models?

**Comment by gineshidalgo99** [comment]
See https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411
