### ISSUE TITLE
COCO module process killed

### ISSUE THREAD

**Issue by JahangirButt-BU** [CMU-Perceptual-Computing-Lab/openpose#1829]
### Issue Summary

Cmmd: ./build/examples/openpose/openpose.bin --image_dir /home/fyp/Desktop/v/data/test/image --write_json output_jsons/

by running this cammond json file is genenrated but i want to use the coco module for which i'm using,

/build/examples/openpose/openpose.bin --image_dir /home/fyp/Desktop/v/data/test/image --model_pose COCO --write_json output_jsons/

but the process is killed,

i don't understand what i'm doing wrong by default module works just fine but coco module is killed, what should i do to get the coco module's json file

###RESULT

![000266_0](https://user-images.githubusercontent.com/72991763/104091952-b59bd380-52a2-11eb-882a-eb18fa92ec57.jpg)
The result file i'm getting for the above image is: https://pastebin.com/qDRuevim
The result i'm after: https://pastebin.com/g6C8kKW6

### Errors (if any)

./build/examples/openpose/openpose.bin --image_dir /home/fyp/Desktop/v/data/test/image --model_pose COCO --write_json output_jsons/
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
---------------------------------- WARNING ----------------------------------
We have introduced an additional boost in accuracy in the CUDA version of about 0.2% with respect to the CPU/OpenCL versions. We will not port this to CPU given the considerable slow down in speed it would add to it. Nevertheless, this accuracy boost is almost insignificant so the CPU/OpenCL versions can be safely used.
-------------------------------- END WARNING --------------------------------
[ WARN:0] global /home/fyp/opencv_build/opencv/modules/core/src/matrix_expressions.cpp (1334) assign OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739
Killed

### Type of Issue
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here:https://pastebin.com/VCBZBZLn

2. **OpenPose version**: openpose v1.7.0 ( Nov 17, 2020)

3. **General configuration**:
CMake: cmake-3.19.2.tar.gz
RAM: 4GB
Processor: 2
Ubuntu: 18.04 x86_64 (CPU_ONLY)

Thankyou

**Comment by JahangirButt-BU** [comment]
now i'm able to generate json file using coco module, by using command:
`./build/examples/openpose/openpose.bin --image_dir /home/fyp/Desktop/v/data/test/image --write_json output_jsons/ --model_pose COCO`
and  got this result in json file: https://pastebin.com/jrLBEVG9

but still i'm puzzled on how to generate my desired json file format i tried to use different flags but no luck
desired format json file: https://pastebin.com/uPQePT0h


is it possible to get my desired result? if yes then hoe should i go about getting it.

Thank you

**Comment by gineshidalgo99** [comment]
As you can see in the 2 JSONs, they are different versions: 1.0 vs. 1.3. If you really need 1.0, you'd have to go to older OpenPose versions (not sure if it's 1.4, 1.5, etc). The latest is the one with the maximum amount of information and accuracy, so I would not recommend this.

About why it is being killed, see #1811

**Comment by JahangirButt-BU** [comment]
all error were resolved but after refreshing my system i tried installing openpose but when im running 'make -j2' i facing this error
fyp@ubuntu:~/Desktop/openpose/build$ make -j2
[ 12%] Performing configure step for 'openpose_lib'
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at cmake/Misc.cmake:32 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- -- CUDA is disabled. Building without it...
CMake Warning (dev) at cmake/Dependencies.cmake:129 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable MKL_ROOT is set to:

    MKL_ROOT-NOTFOUND

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:49 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_RT_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMKL.cmake:104 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:129 (find_package)
  CMakeLists.txt:49 (include)


-- Configuring incomplete, errors occurred!
See also "/home/fyp/Desktop/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeOutput.log".
See also "/home/fyp/Desktop/openpose/build/caffe/src/openpose_lib-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_lib.dir/build.make:124: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-configure' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-configure] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

the system is the same, i tired old issues but did find the exact problem or maybe i missed.

**Comment by gineshidalgo99** [comment]
If MKL version fails (MKL Caffe was deprecated long time ago and it no longer works in eg Ubuntu 20, probably not in 18 either), disable the USE_MKL flag in CMake.
