### ISSUE TITLE
Can I use the library on linux (ubuntu)?

### ISSUE THREAD

**Issue by Lantares** [CMU-Perceptual-Computing-Lab/openpose#183]
I want to do a simple demo. I want to get the key point of the video stream,  so I need to use the asynchronous tutorial (examples/tutorial_wrapper/1_user_asynchronous.cpp) for my demo.

If yes, what should I do before I follow the tutorial? Add the path? 

Is there any library config introduction on openpose for Ubuntu? Or, How to compile your tutorial c++ code on Ubuntu? 

Thanks.

**Comment by Prestal** [comment]
What do you mean by "video stream"? Where do u get this stream? If you mean webcam, all you need is nothing. By default Openpose uses webcam to work.

**Comment by Lantares** [comment]
Yeah, I know that it can use a webcam. Can 'webcam mode' give me the real time data of the key point? I mean, the coordinate of the key point, not the render result.

**Comment by Prestal** [comment]
As you can see there
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

there is no any problem with saving realtime data. For fact it's not depends on the input type you using (webcam, video, images)
just change appropriate flag at the head of openposeDemo.cpp or other cpp file in proj you using.

**Comment by Lantares** [comment]
My video comes from Kinect, and I read the issue here (https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/120), so I think it may be impossible for me to use the 'webcam mode'.

**Comment by Prestal** [comment]
Sorry, but I haven't a Kinect to try it, but it look like it's not very hard. Good luck:)

**Comment by Lantares** [comment]
Thanks for your help. I will have a try.

**Comment by Lantares** [comment]
Sorry, so do you know how to compile the 'openposeDemo.cpp' on Ubuntu? I feel confused about it... There is no document about to config the path of the library, and it said that 

fatal error: openpose/headers.hpp: No such file or directory
 #include <openpose/headers.hpp>

What should I do for that?

**Comment by Prestal** [comment]
For fact, i'm using Win8, but your error is very general error for every cpp proj. 
In file headers.hpp there are 'links' for every header of the openPose lib.
To know how to work with the lib you proj should see that file.

"No such file or directory" means that it hasn't. It should work just from start. All dependencies should work  fine. You can try to install lib again, download it from git, probably it should work.
 
If it not, you should google it, how to add sources of openpose folder manually to "Additional include directory"

In MS VS its folder is
..\openpose\include\

which refers studio to look for all sources in include file

**Comment by Lantares** [comment]
OK I find a very crazy way to solve my problem. Here it is.

Note: you should not need to modify the OpenPose source code nor examples. In this way, you are able to directly upgrade OpenPose anytime in the future without changing your code. You might create your custom code on examples/user_code/ and compile it by using make all in the OpenPose folder.
