### ISSUE TITLE
openpose [ WARN:0] OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739

### ISSUE THREAD

**Issue by Vegetebird** [CMU-Perceptual-Computing-Lab/openpose#1832]
openpose [ WARN:0] OpenCV/MatExpr: processing of multi-channel arrays might be changed in the future: https://github.com/opencv/opencv/issues/16739

**Comment by gineshidalgo99** [comment]
Funny thing, after a few weeks of having this warning, I removed it last night, so the latest OpenPose (since yesterday) do not have that warning anymore.

It does not affect he results though, so you can ignore the warning.

**Comment by luisfmnunes** [comment]
Is there any way to suppress this warning. It's for a submission that requires no outputs to either stdout or stderr, and OpenCV is the only piece left providing logging outputs.

**Comment by Gamebielo** [comment]
Luis, I'm not able to call the "logging::setLogLevel" method in python, it's like it doesn't exist, do you have any solution for python?

**Comment by luisfmnunes** [comment]
> Luis, I'm not able to call the "logging::setLogLevel" method in python, it's like it doesn't exist, do you have any solution for python?

sorry the aforementioned solution is the C++ solution. So far in python I haven't noticed this warning, thus I don't know how to sort it out. Probably you need to search the pybind access to the C level logger, if this has been implemented in OpenCV
