### ISSUE TITLE
Error when executing 'DBUILD_PYTHON = ON' after the latest commit - Build Error

### ISSUE THREAD

**Issue by kshitijsingh92** [CMU-Perceptual-Computing-Lab/openpose#1833]
### Type of Issue

- Compilation/installation error

### Issue Summary

- Unable to build openpose for Python in Colab using DBUILD_PYTHON=ON after latest commit

### Executed Command (if any)
`!cd openpose && rm -rf build || true && mkdir build && cd build && cmake -DBUILD_PYTHON=ON .. && make -j`nproc`
`

Hi,
Recently there was an issue building Openpose with the latest commit on Colab about 12 hours ago (specifically for Ubuntu as Gines had mentioned in a previous issue). It was fixed and now we can build Openpose. However, building it Colab for python using **'cmake -DBUILD_PYTHON=ON'** command is still an issue and we get an error (log file at the end). As a result, we don't get the folder called as 'python' under 'build' folder under 'openpose'. The DBUILD_PYTHON=ON command was working perfectly in Colab previously. Please let us know if you know a solution to fix it.

Also do let us know if you need any more information. Since this is my first time raising an issue on Github do let us know if you need to change the format of the issue raised here.

Thanks for your help

`[ 62%] Building CXX object python/openpose/CMakeFiles/pyopenpose.dir/openpose_python.cpp.o
/content/openpose/python/openpose/openpose_python.cpp: In member function ‘void op::WrapperPython::configure(pybind11::dict)’:
/content/openpose/python/openpose/openpose_python.cpp:153:71: error: no matching function for call to ‘op::WrapperStructPose::WrapperStructPose(<brace-enclosed initializer list>)’
                     (float)FLAGS_upsampling_ratio, enableGoogleLogging};
                                                                       ^
In file included from /content/openpose/include/openpose/wrapper/wrapper.hpp:13:0,
                 from /content/openpose/include/openpose/wrapper/headers.hpp:6,
                 from /content/openpose/include/openpose/headers.hpp:47,
                 from /content/openpose/python/openpose/openpose_python.cpp:6:
/content/openpose/include/openpose/wrapper/wrapperStructPose.hpp:221:9: note: candidate: op::WrapperStructPose::WrapperStructPose(op::PoseMode, const op::Point<int>&, double, const op::Point<int>&, op::ScaleMode, int, int, int, float, op::RenderMode, op::PoseModel, bool, float, float, int, const op::String&, const std::vector<op::HeatMapType>&, op::ScaleMode, bool, float, int, bool, double, const op::String&, const op::String&, float, bool)
         WrapperStructPose(
         ^~~~~~~~~~~~~~~~~
/content/openpose/include/openpose/wrapper/wrapperStructPose.hpp:221:9: note:   no known conversion for argument 3 from ‘const op::Point<int>’ to ‘double’
/content/openpose/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note: candidate: op::WrapperStructPose::WrapperStructPose(const op::WrapperStructPose&)
     struct OP_API WrapperStructPose
                   ^~~~~~~~~~~~~~~~~
/content/openpose/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note:   candidate expects 1 argument, 26 provided
/content/openpose/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note: candidate: op::WrapperStructPose::WrapperStructPose(op::WrapperStructPose&&)
/content/openpose/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note:   candidate expects 1 argument, 26 provided
[ 63%] Linking CXX executable handFromJsonTest.bin
[ 63%] Built target handFromJsonTest.bin
Scanning dependencies of target openpose_3d
[ 63%] Building CXX object src/openpose/3d/CMakeFiles/openpose_3d.dir/cameraParameterReader.cpp.o
python/openpose/CMakeFiles/pyopenpose.dir/build.make:62: recipe for target 'python/openpose/CMakeFiles/pyopenpose.dir/openpose_python.cpp.o' failed
make[5]: *** [python/openpose/CMakeFiles/pyopenpose.dir/openpose_python.cpp.o] Error 1
CMakeFiles/Makefile2:2343: recipe for target 'python/openpose/CMakeFiles/pyopenpose.dir/all' failed
make[4]: *** [python/openpose/CMakeFiles/pyopenpose.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 64%] Building CXX object src/openpose/3d/CMakeFiles/openpose_3d.dir/defineTemplates.cpp.o
[ 64%] Building CXX object src/openpose/3d/CMakeFiles/openpose_3d.dir/jointAngleEstimation.cpp.o
[ 64%] Building CXX object src/openpose/3d/CMakeFiles/openpose_3d.dir/poseTriangulation.cpp.o
[ 65%] Building CXX object src/openpose/3d/CMakeFiles/openpose_3d.dir/poseTriangulationPrivate.cpp.o
[ 65%] Linking CXX shared library libopenpose_3d.so
[ 65%] Built target openpose_3d
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:124: recipe for target 'openpose_lib' failed
make[2]: *** [openpose_lib] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by NikiforosTs** [comment]
I have the same issue. When using colab I can build openpose for C++, but when I set DBUILD_PYTHON=ON to build it for Python,
 I get a simmilar error.

**Comment by gineshidalgo99** [comment]
Sorry! Fixed in latest! (let me know otherwise)
