### ISSUE TITLE
Differences in accuracy by version

### ISSUE THREAD

**Issue by whatyougonnado** [CMU-Perceptual-Computing-Lab/openpose#1834]
Hi!
Prior to the question, thank you for sharing a great work.
I just want to know, has the accuracy of the model increased as the version was updated(sometimes)? or is it just a refactoring and update dependency?

**Comment by gineshidalgo99** [comment]
Both speed and accuracy have been very increased over versions (more or less depending on the version). So different versions will most probably provide different results.
