### ISSUE TITLE
win10 gpu cuda 10.1  Run failed

### ISSUE THREAD

**Issue by menkeyi** [CMU-Perceptual-Computing-Lab/openpose#1836]
PS C:\openpose> bin\OpenPoseDemo.exe --video examples\media\video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...

Error:
Cuda check failed (3 vs. 0): initialization error

Coming from:
- C:\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():48
- C:\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- C:\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():58
- C:\openpose\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- C:\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1222
- C:\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424

PS C:\openpose> nvidia-smi.exe
Wed Jan 13 16:42:42 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.96       Driver Version: 418.96       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            TCC  | 00000000:00:0B.0 Off |                    0 |
| N/A   52C    P0    27W /  70W |    266MiB / 15205MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by gineshidalgo99** [comment]
What GPU model do you have? Does the pre-compiled v1.7.0 works in your machine? Also, CUDA errors are usually fixed by re-installing CUDA / Nvidia drivers, rebooting the machine, and re-installing OpenPose.

**Comment by menkeyi** [comment]
> What GPU model do you have? Does the pre-compiled v1.7.0 works in your machine? Also, CUDA errors are usually fixed by re-installing CUDA / Nvidia drivers, rebooting the machine, and re-installing OpenPose.

NVIDIA Tesla T4  Do you need to recompile？  Is cuda10.1 operational？

**Comment by gineshidalgo99** [comment]
I see that GPU was released on 2018, so yeah, 10.1 should be fine, but you have quite an old Nvidia driver (418). CUDA errors are usually fixed by re-installing the latest Nvidia drivers, rebooting the machine, and trying again OPenPose. If that does not solve it, install the latest Nvidia, CUDA, do a reboot, and re-install OpenPose.
