### ISSUE TITLE
Unity bindings broken

### ISSUE THREAD

**Issue by MatthijsBurgh** [CMU-Perceptual-Computing-Lab/openpose#1838]
One of your latest commits, https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/5badd2b6c67f0b04e68162bdac9ec73c0a295ea7, broke the unity bindings.

You extended the arguments of the constructor of `WrapperStructPose` with `const double netInputSizeDynamicBehavior_`

See my GH actions in my fork, https://github.com/MatthijsBurgh/openpose/runs/1694938195?check_suite_focus=true#step:8:661

I don't know how you want to fix this, therefore opening an issue and not a PR.

**Comment by gineshidalgo99** [comment]
Good catch, fixed in my latest commit!
