### ISSUE TITLE
[Question] Where is source code of thesis formula 11

### ISSUE THREAD

**Issue by zunda-pixel** [CMU-Perceptual-Computing-Lab/openpose#1842]
I am Student.
I read openpose thesis.
https://arxiv.org/pdf/1812.08008.pdf

I want to change formula 11 on thesis.

Where should I change source code?

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/net/bodyPartConnectorBase.cu (or their cpp/opencl analogs for those 2 versions)

**Comment by zunda-pixel** [comment]
where is value u of Formulas 12?

**Comment by gineshidalgo99** [comment]
Formulas 11 and 12 are part of:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/net/bodyPartConnectorBase.cu (or their cpp/opencl analogs for those 2 versions)

**Comment by zunda-pixel** [comment]
what mean is peakA, peakB in [bodyPartConnectBase.cu line 114](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/fcc44e4b0ed3ffed74634af1b89a65917c05dfd2/src/openpose/net/bodyPartConnectorBase.cu#L114) ?

**Comment by zunda-pixel** [comment]
where is [Hungarian algorithm in thesis 3.5](https://arxiv.org/pdf/1812.08008.pdf)?

**Comment by gineshidalgo99** [comment]
sorry, as I said, i haven't looked at that code in years and don't really have much time at the moment to do so, but the hungarian algorithm is also in that file. OpenPose consist of: 1) The network (Caffe), 2) A upsampling to improve quality, 3) NMS supression to locate the body part candidates, and 4) Everything else that goes in that bodyPartConnectBase.

**Comment by zunda-pixel** [comment]
Ok thanks!
