### ISSUE TITLE
Specific the sub-images by bounding boxes to accelerate the pose estimation?

### ISSUE THREAD

**Issue by Hao-Quan** [CMU-Perceptual-Computing-Lab/openpose#1843]
Hello, I'd like to run OpenPose (Pose estimation) on the sub-images instead of full images to accelerate the running speed. Actually, I have done the bounding boxes containing the human bodies in each frame of the video data. If there some methods to run OpenPose only in the specific zone of the bounding boxes (where presenting the human body) giving the coordinates. I have gone through the manual of command line parameters, I have not found that. I wonder there are any other methods to do it? Thanks for help.

**Comment by gineshidalgo99** [comment]
If you have those, you can use the OpenPose tutorial (examples/tutorial_cpp-python) and add your bounding boxes and cropped images to the pipeline directly. That is the only way right now, sorry! Feel free to do a PR if you do it and you think it's releaseable and useful for other folks :)
