### ISSUE TITLE
Regenerate cMakeList.txt files after adding new code and files ?

### ISSUE THREAD

**Issue by adahdooh** [CMU-Perceptual-Computing-Lab/openpose#1844]
Hi guys,

I'm working on a project to generate 3dpost from a sequence of images and from a video file. After adding my *.cpp files, and try to execute cmake...  an error message appears "no cMakeList.txt" file exists. 

what is the file and how can I generate it.

Thanks

**Comment by gineshidalgo99** [comment]
See [examples/user_code/README.md](../../examples/user_code/README.md).
