### ISSUE TITLE
[Question] Where is source code of thesis formula 12

### ISSUE THREAD

**Issue by zunda-pixel** [CMU-Perceptual-Computing-Lab/openpose#1849]
I am Student.
I read openpose thesis.
https://arxiv.org/pdf/1812.08008.pdf

I want to change formula 12 on thesis.

Where should I change source code?

**Comment by gineshidalgo99** [comment]
#1842 

Do not keep opening new GitHub issues for the same kind of questions, keep it in the same thread.
