### ISSUE TITLE
v1.7.0 prebuilt windows caffe dll did not uising cudnn 8,how can I reduce the memery(body_25 used 6G,COCO 8G)

### ISSUE THREAD

**Issue by liuwei0812** [CMU-Perceptual-Computing-Lab/openpose#1851]
I used v1.7.0 on windows10 (RTX3080)
openpose run well but memery used too much, I found v1.6.0 prebuilt windows caffe dll used cudnn but v1.7.0 not.
It's the reason?
And v1.6.0 not support RTX3080.
How can I do to using cudnn reduce memery?
Is there prebuilt windows caffe dll using cudnn 8 and support RTX3080?
Or how can I build a caffe dll  using cudnn 8 and support RTX3080?

**Comment by drostifrosti** [comment]
For now it seems that one has to build Caffe from source (via: [https://github.com/BVLC/caffe/tree/windows](https://github.com/BVLC/caffe/tree/windows)), at least that's the way we could modify the attached caffe lib of the openpose prebuilt in the past

**Comment by liuwei0812** [comment]
build  caffe dll with cudnn  on windows10 vs2019 is  Hell difficult...

**Comment by drostifrosti** [comment]
sry to ask so blatantly, but are you by any chance the author of the paper "A two-stage Method for hand-raising gesture recognition in classroom", since I send a request to this group a couple of days ago, asking for the trained network
in return I would give you the building instructions for the dll

**Comment by liuwei0812** [comment]
It's not

**Comment by gineshidalgo99** [comment]
This is my Caffe repo to compile Windows: https://github.com/gineshidalgo99/caffeCompilerForWindowsAndCUDA  It is based on the Windows Caffe one.

I have not been able to compile cuDNN for Windows, it keeps giving me this error:
```
[Many other logs]
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_infer64_8.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_cnn_infer64_8.dll'. Module was built without symbols.
F0207 11:36:55.959534  5612 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
Unhandled exception at 0x00007FFFA5DD286E (ucrtbase.dll) in OpenPoseDemo.exe: Fatal program exit requested.

The program '[7240] OpenPoseDemo.exe' has exited with code 0 (0x0).
```

If anybody is able to get it to work without giving the CUDNN_STATUS_NOT_INITIALIZED error, I'd very highly appreciate some hints of the exact CUDA/cuDNN version and/or instructions to get it to work! :)

Please, keep this discursion in #1845, to centralize messages. Thanks!
