### ISSUE TITLE
Modify trained model to detect just arm keypoints

### ISSUE THREAD

**Issue by nicolettasperaddio** [CMU-Perceptual-Computing-Lab/openpose#1852]
Hi to everyone, I'm working on a project that implicates the control of a robotic arm by using the skeleton estracted from openpose. Since the keypoints I need are less than the whole body key points, it can be possible to reduce the whole body model to a single arm model? If it is, can the fps be improved as a consequence?
I'm using CPU version and I need to increase the fps.
(python, Ubuntu v. 18.04)

**Comment by gineshidalgo99** [comment]
No, only training arm will decrease the accuracy very probably and also not affect the frame rate more than 1-2%.
