### ISSUE TITLE
[Question] How do export face, left and right hand, and pose keypoint separately in different files? 

### ISSUE THREAD

**Issue by stanleyshly** [CMU-Perceptual-Computing-Lab/openpose#1853]
Using the /build/examples/openpose/openpose.bin demo file, what arguments should I add to get a keypoint files like the ones found here:([https://github.com/carolineec/EverybodyDanceNow/tree/master/sample_data/train/keypoints])? Here is my current command: `./build/examples/openpose/openpose.bin --hand --face --video '{colab_video_path}' \
       --display 0 --write_video_with_audio\
       --write_video '{colab_openpose_video_path}' --write_json '{folder_path_json}'` , however, I still only get one keypoint file per detection with all body parts, where as I hope to get all of them separately. Any arguments I should add to my command?

**Comment by gineshidalgo99** [comment]
OpenPose returns them in the same file, you'll have to do post-processing (with the OpenPose C++/Python API or by yourself) later.
