### ISSUE TITLE
Removing background from *video/webcam*

### ISSUE THREAD

**Issue by sv176** [CMU-Perceptual-Computing-Lab/openpose#1856]
Is there any way to remove the background and only have the skeleton showing up when detected? I am currently using openpose to implement a privacy preserving human detection. Thanks

https://www.youtube.com/watch?v=Vf02sGB3ymw < - I am looking to output something like this

**Comment by djramakrishna** [comment]
set the disable blending flat to True, that should give the type of output you are looking for.
