### ISSUE TITLE
Need to improve trained caffemodel

### ISSUE THREAD

**Issue by PanicRay** [CMU-Perceptual-Computing-Lab/openpose#1857]
### Issue Summary
There is no issue when using the library. But I believe the trained caffemodel cause some recognition problem. As you can see, there are some type of recognition error on the top page of this project. And there are more errors you can see, if you put the video or camera upsidedown. I believe, it is because the training datasets are only based on coco dataset. Some images are not well define their joint connection. There is a way to improve the result by adding more training datasets.
![image](https://user-images.githubusercontent.com/61138829/106102540-81695380-617a-11eb-957a-a3423441d80e.png)

I tried the iMaterialist Challenge of Kaggle. It gave me 3000 pictures of non-human pictures with a human pose. [https://www.kaggle.com/c/imaterialist-challenge-furniture-2018/data](https://www.kaggle.com/c/imaterialist-challenge-furniture-2018/data)

### Type of Issue
- Enhancement

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/
