### ISSUE TITLE
Video conversion

### ISSUE THREAD

**Issue by Hellodan-77** [CMU-Perceptual-Computing-Lab/openpose#1858]
Hello, I want to input the video format to extract the human joint points through openpose and output it as a json format file. I downloaded the code you public on github, but I am running the command "./build/examples/openpose/openpose.bin- -video examples/media/video.avi" when an error was reported and the openpose.bin file could not be found. I checked the file under the "examples/openpose" path, and there was only one openpose.cpp file. I would like to ask the reason for my problem. I hope to receive your reply! Thank you very much!

**Comment by RuLee28** [comment]
I got a same problem but I don't have any idea to solve it
ANYONE has some idea?
