### ISSUE TITLE
how to change the cvMat format to op::Array format?

### ISSUE THREAD

**Issue by bilipa** [CMU-Perceptual-Computing-Lab/openpose#186]
Hi, I want to use the openpose/pose/renderPose.cpp function renderPoseKeypointsCpu(...), but i dont how to change the cvMat to op::Array format;
When i do :
    op::Array<float> outputImage;
    cv::Mat inputImage = cv::imread(FLAGS_image_folder, CV_LOAD_IMAGE_COLOR);
    outputImage.setFrom();
But it said Array<T>: T type and cvMat type are different.
Could you tell me where is wrong, or other function can do it.
Thanks.

### Type of issue
- Help wanted
- Question

### Your system configuration
OPENCV 3.2
Ubuntu 16.04

**Comment by gineshidalgo99** [comment]
cv::Mat inputImage = cv::imread(FLAGS_image_folder, CV_LOAD_IMAGE_COLOR);

image_folder is a folder, not an image, so I guess you are trying to read an empty image?

**Comment by bilipa** [comment]
Sorry, but the image is not empty, because I check it and display, it is normal.
Because the code is not in this computer, so I write the wrong "FLAGS_image_folder" instead by "FLAGS_image_path". I feel very sorry about that.

Here is the all my code in main() function
google::InitGoogleLogging("Some information");
gflags::ParseCommandLineFlags(&argc, &argv, true);

cv::Mat inputImage = cv::imread(FLAGS_image_path);
if(inputImage.empty)
    op::error("No image input.", __LINE__, __FUNCTION__, __FILE__);
op::Array<float> outputImage;
outputImage.setFrom(inputImage);
return 0;

---------------------------------------
Array<T>: T type and cvMat type are different.

Coming from:
-src/openpose/core/array.cpp:setFrom():231
-src/openpose/core/array.cpp:setFrom():240
terminate called after throwing an istance of 'std::runtime_error'
---------------------------------------
The image can display by cv::imshow()

**Comment by gineshidalgo99** [comment]
Old topic, and the OpenPose code has slightly changed since then. Closed for now. But feel free to update your question for new OpenPose versions if it still doesn't work.
