### ISSUE TITLE
How to get the keypoints name  after detection

### ISSUE THREAD

**Issue by Williams-CHEN0401** [CMU-Perceptual-Computing-Lab/openpose#1860]
Hi everyone,
I am new in using openpose.
I have successfully installed on the ubuntu 20.04 with CUDA10.1,CUDNN7.5.0 and Opencv4.5.0.
I tried the example and also got the keypoints location.
Could anyone teach me how to get the each keypoints' name and show on image?

**Comment by gineshidalgo99** [comment]
See doc/output
