### ISSUE TITLE
Windows portable demo v1.7.0 crashes due to out of memory - v1.6.0 works without issues

### ISSUE THREAD

**Issue by Witek-** [CMU-Perceptual-Computing-Lab/openpose#1861]
### Issue Summary

The precompiled OpenPoseDemo v1.7.0 with hands and/or face enabled will crash on my 6GB GPU  due to lack of memory, while the previous version works without a problem using just 3-4 GB of GPU RAM. Using default pose, face and hand models.

### Executed Command (if any)
bin\OpenPoseDemo.exe --hand --face --logging_level 0 --disable_multi_thread

### OpenPose Output (if any)

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0201 02:28:29.051620 17604 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***

### Errors (if any)
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### Type of Issue
- Execution error

### Your System Configuration
Console output:
https://pastebin.com/DBhSjtQK

Operationg system: Windows 10
Graphics card: Nvidia GTX1060 6GB  Driver Version: 461.40 from 26.01.2021
CUDA 10.1, CuDNN: 8.0.5
Visual Studio Community 2017
Caffe, OpenCV: Default from OpenPose
OpenPose version 1.7.0 (GPU release), from:
- https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.7.0

**Comment by batselem** [comment]
the same problem

**Comment by moncio** [comment]
The same to me running with CUDA 11.0 and CUDNN 8.0.5 and Ubuntu 20.04 in RTX 2080 Ti 11 GB and Driver version 450.102.04

**Comment by batselem** [comment]
It looks like hand and face detection models are consuming too much memory. Solved the problem by removing --face and --hand flags.

**Comment by Witek-** [comment]
Removing hand and face detection is hardly a solution if one wants hands and face detected.

One more thing I noticed: input images of small width are accepted but with wide ones OpenPose crashes.

**Comment by moncio** [comment]
Someone was able to compile the library with CUDA 11.0 and CUDNN 8?

**Comment by batselem** [comment]
@Witek- Then you need a bigger memory gpu for running face/hand detection model.

**Comment by Witek-** [comment]
@batselem But it works fine with 1.6.0, so something is wrong with the latest code

**Comment by moncio** [comment]
Sorry but, I have next issue when I run the demo after compiling latest version with Ubuntu 20.04, Cuda 11, Cudnn 8:

![image](https://user-images.githubusercontent.com/4520583/106607337-7ab85300-6563-11eb-8810-926e6a201d71.png)

Does someone have the same problem?
Thanks

**Comment by netxue** [comment]
I have a similar problem. I use RTX3090. I try to cancel USE_CUDNN, but the memory consumption is reduced. [this link #1859 ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1859)

**Comment by gineshidalgo99** [comment]
This is my Caffe repo to compile Windows: https://github.com/gineshidalgo99/caffeCompilerForWindowsAndCUDA  It is based on the Windows Caffe one.

I have not been able to compile cuDNN for Windows, it keeps giving me this error:
```
[Many other logs]
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_infer64_8.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_cnn_infer64_8.dll'. Module was built without symbols.
F0207 11:36:55.959534  5612 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
Unhandled exception at 0x00007FFFA5DD286E (ucrtbase.dll) in OpenPoseDemo.exe: Fatal program exit requested.

The program '[7240] OpenPoseDemo.exe' has exited with code 0 (0x0).
```

If anybody is able to get it to work without giving the CUDNN_STATUS_NOT_INITIALIZED error, I'd very highly appreciate some hints of the exact CUDA/cuDNN version and/or instructions to get it to work! :)

Please, keep this discursion in #1845, to centralize messages. Thanks!

**Comment by volkov-maxim** [comment]
Have the same problem with 1.6.0 on wide video. Test on 4096x1200, 2048x600, 1024x300, 656x192, 416x122.
On 640x360 1.6.0 works good.

**Comment by CSN-001** [comment]
> 对我来说，在RTX 2080 Ti 11 GB和驱动程序版本450.102.04中使用CUDA 11.0和CUDNN 8.0.5和Ubuntu 20.04运行的情况相同

I have the same problem as you, have you solved it?

**Comment by jpdiogoNOVA** [comment]
Same problem here only when running with the flags --hand and/or --face.

<details>
  <summary>Openpose Faq</summary>

  ![image](https://user-images.githubusercontent.com/63406159/164205112-42d2b205-8a6e-4c65-b96d-064d40816a2a.png)

</details>

"Also, hands and face increases the GPU memory requeriments, and 4 GB GPUs might run a bit short in some cases."

We are running the binaries from the windows portable version on a 3060 RTX with 8GB o graphics memory so it should be enough.
If anyone has insight into what could be could causing this and how to solve it, it would be very much appreciated.

**Comment by spider853** [comment]
> Same problem here only when running with the flags --hand and/or --face.
> 
> Openpose Faq
> "Also, hands and face increases the GPU memory requeriments, and 4 GB GPUs might run a bit short in some cases."
> 
> We are running the binaries from the windows portable version on a 3060 RTX with 8GB o graphics memory so it should be enough. If anyone has insight into what could be could causing this and how to solve it, it would be very much appreciated.

I was able to run it on 2070 Super 8GB with reduced resolution bin\OpenPoseDemo.exe -hand=true -hand_net_resolution="256x256" -net_resolution="512x512"

**Comment by davidpagnon** [comment]
I'm not sure that it's connected, but just in case, I had this issue and solved it by running `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2` to use compatible CUDA and cuDNN versions.
