### ISSUE TITLE
No camera found

### ISSUE THREAD

**Issue by lovezengya** [CMU-Perceptual-Computing-Lab/openpose#1862]
i had set up  cpu caffe successful,and make the build  folder no error ,but i do ./openpose/build/examples/openpose/openpose.bin in the terminal,The program reminds me No camera found, what can i do to solve this problem.

**Comment by gineshidalgo99** [comment]
OpenPose uses OpenCV for reading the camera, so I'd try the following:
1. Try to check if your browser reads your webcam
2. If/after it does, if OpenPose doesn't yet, try to get it working on OpenCV (following their doc/tutorials)
