### ISSUE TITLE
Run the demo from remote server

### ISSUE THREAD

**Issue by gunagg** [CMU-Perceptual-Computing-Lab/openpose#1863]
I have my code setup on a remote server, and I want to run a real-time demo there. Is there any way by which I can open webcam on my local Mac machine, and run openpose on the remote server, which has Ubuntu?

**Comment by gineshidalgo99** [comment]
Yes, you can totally stream webcam over internet, but that's not the OpenPose scope.

You want to create your own code (based on the tutorial_api_cpp/python examples)
