### ISSUE TITLE
Out of Memory Exception - on Windows OS

### ISSUE THREAD

**Issue by galsapp** [CMU-Perceptual-Computing-Lab/openpose#1865]
### Issue Summary

Out of Memory Exception - on Windows OS
I'm trying to run the test OpenPose demo, by the following documentations:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/1_prerequisites.md#windows-prerequisites
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#prerequisites
I'm stuck on the last part - OpenPose demo, where i'm trying to click on F5(after building the project, in VS 2019) -
The error from the output: 
**F0202 23:03:34.563516  8768 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
OpenPoseDemo.exe has triggered a breakpoint.**

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)

The error from the output: 
**F0202 23:03:34.563516  8768 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
OpenPoseDemo.exe has triggered a breakpoint.**

### Type of Issue
Select the topic(s) on your post, delete the rest:
**- Compilation/installation error**

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: [LINK](https://pastebin.com/W8z6ikrR)

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**:  CMake on Windows
    - **Operating system version** Windows 10
    - **Release or Debug mode**? (by default: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows):  VS2019 community

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? caffe_16_2020_11_14
    - **CMake version** (`cmake --version` in Ubuntu): 3.19.4
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA 11.1.1
    - **cuDNN version**: cuDNN 8.0.5
    - **GPU model** (`nvidia-smi` in Ubuntu): GeForce MX230

7. If **Windows** system:
    - Portable demo or compiled library? Portable demo

**Comment by Witek-** [comment]
I think it's the same as reported here: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1861
Try with version 1.6.0. Version 1.7.0 is bugged.

**Comment by galsapp** [comment]
> I think it's the same as reported here: #1861
> Try with version 1.6.0. Version 1.7.0 is bugged.

I get the same problem in the 1.6.0. Version

**Comment by gineshidalgo99** [comment]
This is my Caffe repo to compile Windows: https://github.com/gineshidalgo99/caffeCompilerForWindowsAndCUDA  It is based on the Windows Caffe one.

I have not been able to compile cuDNN for Windows, it keeps giving me this error:
```
[Many other logs]
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_infer64_8.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_cnn_infer64_8.dll'. Module was built without symbols.
F0207 11:36:55.959534  5612 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
Unhandled exception at 0x00007FFFA5DD286E (ucrtbase.dll) in OpenPoseDemo.exe: Fatal program exit requested.

The program '[7240] OpenPoseDemo.exe' has exited with code 0 (0x0).
```

If anybody is able to get it to work without giving the CUDNN_STATUS_NOT_INITIALIZED error, I'd very highly appreciate some hints of the exact CUDA/cuDNN version and/or instructions to get it to work! :)

Please, continue this discursion in #1845, to centralize messages and hopefully focus efforts to fix the issue. Thanks!





PS: For Ubuntu users with memory issues, v1.7.0 was modified to allow cuDNN 8, which was a pain. I am not an expert, so I am sure there must be a better way to run the cuDNN convolutions using less memory, but I am not an expert on it. I am very open to suggestions about the cudnn_conv implementation to minimize memory:
https://github.com/CMU-Perceptual-Computing-Lab/caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cpp

Please, continue this discursion in #1864, to centralize messages and hopefully focus efforts to fix the issue. Thanks!
