### ISSUE TITLE
After selecting USE_CUDNN, the GPU memory usage of rtx3090 is higher than not selecting it. Why? 

### ISSUE THREAD

**Issue by netxue** [CMU-Perceptual-Computing-Lab/openpose#1869]
### Issue Summary
USE_CUDNN is selected in cmake-gui, and GPU memory usage is about 19G with --face --hand .and Maximum Accuracy can't run
Cancel USE_CUDNN in cmake-gui ,the GPU memory usage is about 11G with --face --hand.and Maximum Accuracy can't run too

### Executed Command (if any)
./build/examples/openpose/openpose.bin --face --hand
./build/examples/openpose/openpose.bin --net_resolution "1312x736" --scale_number 4 --scale_gap 0.25

**USE_CUDNN is selected:**
./build/examples/openpose/openpose.bin --face --hand
Nvidia-smi:
+-------------------------------+----------------------+----------------------+
   0  GeForce RTX 3090    Off  | 00000000:01:00.0  On |                  N/A |
| 53%   54C    P2   209W / 350W |  19635MiB / 24245MiB |     42%      Default |

**Cancel USE_CUDNN:**
./build/examples/openpose/openpose.bin --face --hand
Nvidia-smi:
+-------------------------------+----------------------+----------------------+
|   0  GeForce RTX 3090    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   52C    P2   272W / 350W |  11762MiB / 24245MiB |     51%      Default |

 
### Errors (if any)
**With USE_CUDNN:Errors**
./build/examples/openpose/openpose.bin --net_resolution "1312x736" --scale_number 4 --scale_gap 0.25
**Errors:**
F0206 21:12:51.208909 18964 cudnn_conv_layer.cpp:53] Check failed: status == **CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED**
*** Check failure stack trace: ***
    @     0x7f7d503681c3  google::LogMessage::Fail()
    @     0x7f7d5036d25b  google::LogMessage::SendToLog()
    @     0x7f7d50367ebf  google::LogMessage::Flush()
    @     0x7f7d503686ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7d4ff670f5  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f7d5004be4d  caffe::Net<>::Init()
    @     0x7f7d5004e365  caffe::Net<>::Net()
    @     0x7f7d50a1fa2c  op::NetCaffe::initializationOnThread()
    @     0x7f7d50a395ed  op::addCaffeNetOnThread()
    @     0x7f7d50a3bf46  op::PoseExtractorCaffe::forwardPass()
    @     0x7f7d50a3703b  op::PoseExtractor::forwardPass()
    @     0x7f7d50a34b20  op::WPoseExtractor<>::work()
    @     0x7f7d50a658ef  op::Worker<>::checkAndWork()
    @     0x7f7d50a65a7b  op::SubThread<>::workTWorkers()
    @     0x7f7d50a7358d  op::SubThreadQueueInOut<>::work()
    @     0x7f7d50a6a5f1  op::Thread<>::threadFunction()
    @     0x7f7d506a7d84  (unknown)
    @     0x7f7d503aa609  start_thread
    @     0x7f7d504e6293  clone
Aborted (core dumped)

**Cancel USE_CUDNN:Errors**
./build/examples/openpose/openpose.bin --net_resolution "1312x736" --scale_number 4 --scale_gap 0.25
**Errors:**
F0206 20:07:11.206526 11056 syncedmem.cpp:71] Check failed: error == **cudaSuccess (2 vs. 0)  out of memory**
*** Check failure stack trace: ***
    @     0x7f4ecbac11c3  google::LogMessage::Fail()
    @     0x7f4ecbac625b  google::LogMessage::SendToLog()
    @     0x7f4ecbac0ebf  google::LogMessage::Flush()
    @     0x7f4ecbac16ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4ecb7eb55a  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f4ecb684336  caffe::Blob<>::mutable_gpu_data()
    @     0x7f4ecb6c1b40  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7f4ecb824a81  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7f4ecb7ab292  caffe::Net<>::ForwardFromTo()
    @     0x7f4ecc1780a8  op::NetCaffe::forwardPass()
    @     0x7f4ecc194fba  op::PoseExtractorCaffe::forwardPass()
    @     0x7f4ecc19003b  op::PoseExtractor::forwardPass()
    @     0x7f4ecc18db20  op::WPoseExtractor<>::work()
    @     0x7f4ecc1be8ef  op::Worker<>::checkAndWork()
    @     0x7f4ecc1bea7b  op::SubThread<>::workTWorkers()
    @     0x7f4ecc1cc58d  op::SubThreadQueueInOut<>::work()
    @     0x7f4ecc1c35f1  op::Thread<>::threadFunction()
    @     0x7f4ecbe00d84  (unknown)
    @     0x7f4ecbb03609  start_thread
    @     0x7f4ecbc3f293  clone
Aborted (core dumped)

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: 
USE_CUDNN selected:[https://pastebin.com/9fy27hxE](https://pastebin.com/9fy27hxE)
Cancel CUDNN:[https://pastebin.com/2yD7nK6Q](https://pastebin.com/2yD7nK6Q)

2. **OpenPose version**: 1.7

3. **General configuration**:
    - **Installation mode**: cmake-gui ..,make -j`nproc`
    - **Operating system** (`lsb_release -a` in Ubuntu):Ubuntu 20.04.2 LTS focal
    - **Operating system version** :Ubuntu 20.04
    - **Release or Debug mode**? (by default: release):release
    - Compiler :gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):no
    - Any other custom CMake configuration with respect to the default version? (by default: no):no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu):cmake version 3.16.3
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` 
    -                                 >>> import cv2
                                      >>> print(cv2.__version__)
                                             4.5.1

6. **GPU mode** issue: RTX3090 24G
    - **CUDA version** :
 nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

    - **cuDNN version**:
    - cat /usr/local/cuda/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL
#endif /* CUDNN_VERSION_H */

    - **GPU model** (`nvidia-smi` in Ubuntu):
    - +-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   36C    P8    25W / 350W |    266MiB / 24245MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1052      G   /usr/lib/xorg/Xorg                 53MiB |
|    0   N/A  N/A      1574      G   /usr/lib/xorg/Xorg                139MiB |
|    0   N/A  N/A      1710      G   /usr/bin/gnome-shell               43MiB |
|    0   N/A  N/A      2384      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A      2391      G   /usr/lib/firefox/firefox            4MiB |
|    0   N/A  N/A     18912      G   /usr/lib/firefox/firefox            4MiB |
+-----------------------------------------------------------------------------+

8. **Python** API:
    - **Python version**:  Python 3.8.5
    - **Numpy version** :
    - python3 -c "import numpy; print(numpy.version.version)"
1.20.0

**Comment by gineshidalgo99** [comment]
v1.7.0 was modified to allow cuDNN 8, which was a pain. I am not an expert, so I am sure there must be a better way to run the cuDNN convolutions using less memory, but I am not an expert on it. I am very open to suggestions about the cudnn_conv implementation to minimize memory:
https://github.com/CMU-Perceptual-Computing-Lab/caffe/blob/master/src/caffe/layers/cudnn_conv_layer.cpp

Please, continue this discursion in #1845, to centralize messages and hopefully focus efforts to fix the issue. Thanks!
