### ISSUE TITLE
Improve fps without CUDA or OPENCL

### ISSUE THREAD

**Issue by nicolettasperaddio** [CMU-Perceptual-Computing-Lab/openpose#1878]
Hi to everyone,

I have to improve my project performance, but actually I'm using CPU version (I do not have AMD or NVIDIA GPU). 

Project constraints:
OS: Ubuntu 18.04
GPU: Intel(R) UHD 620
ROS melodic
Python 3.6
Intel Realsense d435i (frame acquisitions)

Have you any suggestions about what can be the best solution? I need to use openpose in GPU version (some solutions I'm thinking about: web service, cloud, virtual GPU, buy AMD or NVIDIA GPU)? I'm not experienced with these kind of environment adaptations, so it can be useful to know if anyone had the same situation and fixed that problem in some way, maybe it can be the solution I'm seaching for and can help me too. 
The main goal I want to reach is to improve fps in order to acquire videos and elaborate keypoints through openpose in real time.

Thank you for the help

**Comment by ravijo** [comment]
@nicolettasperaddio 

So far, I have not checked OpenPose without GPU. So I am not sure how much FPS you are getting right now? and how much you are expecting?

If you are looking for a ROS wrapper for OpenPose, please have a look at [ros_openpose](https://github.com/ravijo/ros_openpose).

Please check [faq #2](https://github.com/ravijo/ros_openpose#faq) which is derived from OpenPose.

Thanks
