### ISSUE TITLE
Makefiles Error 

### ISSUE THREAD

**Issue by 54jj4d** [CMU-Perceptual-Computing-Lab/openpose#188]
i run the installation script after all package fully downloaded i got such this errors . im noob in linux . plz guide me .

compilation terminated. Makefile:478: recipe for target '.build_release/src/openpose/wrapper/defineTemplates.o' failed make: *** [.build_release/src/openpose/wrapper/defineTemplates.o] Error 1 In file included from src/openpose/core/netCaffe.cpp:4:0: ./include/openpose/core/netCaffe.hpp:5:25: fatal error: caffe/net.hpp: No such file or directory compilation terminated. Makefile:478: recipe for target '.build_release/src/openpose/core/netCaffe.o' failed make: *** [.build_release/src/openpose/core/netCaffe.o] Error 1 In file included from src/openpose/pose/bodyPartConnectorCaffe.cpp:3:0: ./include/openpose/pose/bodyPartConnectorCaffe.hpp:5:26: fatal error: caffe/blob.hpp: No such file or directory compilation terminated. Makefile:478: recipe for target '.build_release/src/openpose/pose/bodyPartConnectorCaffe.o' failed make: *** [.build_release/src/openpose/pose/bodyPartConnectorCaffe.o] Error 1 In file included from ./include/openpose/pose/headers.hpp:6:0, from src/openpose/pose/defineTemplates.cpp:1: ./include/openpose/pose/bodyPartConnectorCaffe.hpp:5:26: fatal error: caffe/blob.hpp: No such file or directory compilation terminated. Makefile:478: recipe for target '.build_release/src/openpose/pose/defineTemplates.o' failed make: *** [.build_release/src/openpose/pose/defineTemplates.o] Error 1).

Ubuntu version 16.04
CUDA 8
cudnn 5.1
opencv 2.4.1

**Comment by whluo** [comment]
I have exactly the same problem in compiling the openpose step. Did you solve this problem? @54jj4d

**Comment by 54jj4d** [comment]
Unfortunately no. and no body help me . seems no one else have this problem .
@whluo

**Comment by gineshidalgo99** [comment]
It sounds like Caffe was not properly installed. Please, try installing Caffe (in 3rdparty/caffe/) following their instructions and after it is properly compiled then install OpenPose. THanks!

**Comment by gineshidalgo99** [comment]
(Closed due no further answer)

**Comment by fmnoori** [comment]
Hi, I am a beginner. I also have the similar type of problem.
My Caffe and OpenPose are running perfectly.
initially, I was using this repository https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
(everything is working fine there)
Now I am trying to make run your repository.
But I got the similar type of Issue, which I posted in comments here.
#8

**Comment by yxchng** [comment]
Same problem. @54jj4d @whluo Have you guys solved it?

**Comment by erolrecep** [comment]
It seems that your makefile.config can not find the directory of caffe. Make sure CAFFE_DIR="your caffe installation or caffe distribution". blob.hpp is in caffe include directory.

**Comment by MartinFultot** [comment]
Make sure you add the BUILD_CAFFE=OFF flag during cmake or else it will ignore you caffe build even if you provide the right path to include.

**Comment by mehtanaman-awl** [comment]
It's just as @erolrecep and @MartinFultot said. BUILD_CAFFE=OFF and Caffe_INCLUDE_DIRS=Cafe_Path

Please replace your respective paths in '<>'
(In the Build directory)
cmake \
    -DCMAKE_BUILD_TYPE="Release" \
    -DBUILD_CAFFE=OFF \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_DOCS=ON \
    -DDOWNLOAD_BODY_COCO_MODEL=ON \
    -DDOWNLOAD_BODY_MPI_MODEL=ON \
    -DCaffe_INCLUDE_DIRS="<my_caffe_path : /opt/caffe/include>" \
    -DCaffe_LIBS="<my_libcaffe.so_path : /opt/caffe/build/lib/libcaffe.so>"\
    -DBUILD_PYTHON=ON ../

You can pass other parameters as well.
This worked for me. Also check if you have installed caffe properly, without any errors
(I did get a few errors in caffe, resolved them while installing Openpose)
