### ISSUE TITLE
How can i access Kinect v2 camera as webcam for openPose?

### ISSUE THREAD

**Issue by Anikzzz** [CMU-Perceptual-Computing-Lab/openpose#189]
I am trying to use Kinect v2 camera to capture the frames but when i'm changing the value from -1 to 1 at "DEFINE_int32(camera,-1,....  ) " then i am getting exception as "+errorMessageToPropagate"\nError:\nVideoCapture (webcam) could not be opened.\n\nComing from:\n- ..\\..\\src\\openpose\\producer\\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():16\n- ..\\..\\src\\openpose\\producer\\vide...std::basic_string<char,std::char_traits<char>,std::allocator<char> >"
Can anyone suggest me with any other way to change the webcam and use Kinect v2 camera as primary camera.
Any help will be appreciated.

Regards,
Anizzz

**Comment by callemein** [comment]
Hello @Anikzzz, which operating system are you using? And have you checked the permissions to the webcam? Maybe try opening it with VLC to also check the index of the RGB vs. Depth source.

**Comment by Anikzzz** [comment]
I am using windows 10 os and yaa i gave permission for the kinect camera.
But still i am unable to use kinect as webcam. I tried in VLC as well but
it is not showing there as well .. i did the KinectCam.ax registered to my
pc but still I'm not able to view.

Thanks & Regards,
Anikzzz

**Comment by callemein** [comment]
@Anikzzz Unfortunately I'm not a Windows user and can't really offer support on that. Though I think you first need to make sure you are able to open the Kinect apart from using OpenPose. Maybe a basic webcam application in python to check if OpenCV can handle your camera and your drivers are installed correctly. 

For example -> http://docs.opencv.org/3.3.0/dd/d43/tutorial_py_video_display.html

**Comment by andudu** [comment]
1.write independent project to record the color & depth image as 'jpg/png/or ...' by kinect v2.0;
2.read the 'jpg/png/or...' (from kinect v2.0) by openpose 'cmd' demand ..... windows\x64\Release\OpenPoseDemo.exe  --face --hand....
in other words ,only change the image input of the openpose ,ok.

**Comment by andudu** [comment]
e.g...you need make two parallel projs:
       ---1--->looping record kinectcolor.jpg by kinect2.0 ---> each time rename it as 'newimage.jpg' ---1-->......
       ---2-->if openpose cmd demand detect 'newimage.jpg' existed ----->read  'newimage.jpg' then process and display(or record the keypoints from hand face body) -----> remove 'newimage.jpg'!--->looping process> ---2--> ---2--> ---2--> ---2--> ---2--> ---2-->............

**Comment by rongfeng-china** [comment]
@andudu
The initialization of openpose takes time. In step 2, inside the loop, everytime you do process, openpose is initialized every time as well. Thus it will make the time longer...

**Comment by andudu** [comment]
@rongfeng-china  
that's right！
The speed is influenced. 
But anyway It works as your hope ..... haha

**Comment by aniketzz** [comment]
i have finally figured how i can i access kinect2.0 with openpose. With windows 10 Anniversary update the have added a feature for kinect 2.0 and all i had to do was **update the driver** for "**kinect sensor device**" from "**disk management**" and change "**DEFINE_int32(camera,                    -1,**  "  to "**DEFINE_int32(camera,                    2,**  "  in "**openposeDemo.cpp**" file and now its working quiet well.

**Comment by andudu** [comment]
@aniketzz  great！ 
fast & perfect way！

**Comment by gineshidalgo99** [comment]
@aniketzz Thanks! Added your instructions to `doc/demo_overview.md`.

**Comment by ilovebob** [comment]
@callemein Can you tell me how can i access kinect 2.0 in ubuntu16.04?

**Comment by callemein** [comment]
I’ve only used a ROS implementation of the Kinect (360 and One), try looking op OpenNI that library allows you to use the Kinect. Maybe in combination with the OpenPose implementation in ROS?
