### ISSUE TITLE
[Mac] Makefile returns due to undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by rupang818** [CMU-Perceptual-Computing-Lab/openpose#1890]
### Issue Summary
Thanks for all the great work. I have generated the Makefile by using the recommended options (see snapshot below), but when I run the suggested Makefile build command I am getting some linking errors that I'm unable to resolve by relinking, reinstalling brew/pip packages.

I've tried to reinstall caffe (`brew uninstall caffe; brew install caffe`), I reinstalled all the brew collaterals (`brew list | xargs brew reinstall`) and I tried rebuilding CMake multiple times.

(FYI - I was getting a different set of errors before installing `freeglut`, `glew`, `glfw`, `glm`. I don't have the error messages saved, but maybe this information could be helpful)

### Executed Command (if any)
``make -j`sysctl -n hw.logicalcpu` ``

### OpenPose Output (if any)
https://pastebin.com/VTPXWpLH

### Errors (if any)
[ 39%] Linking CXX shared library libopenpose.dylib
Undefined symbols for architecture x86_64:
  "_glutLeaveMainLoop", referenced from:
      op::Gui3D::~Gui3D() in gui3D.cpp.o
  "_glutMainLoopEvent", referenced from:
      op::Gui3D::update() in gui3D.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/openpose/libopenpose.1.7.0.dylib] Error 1
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [all] Error 2

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output**: https://pastebin.com/VTPXWpLH

2. **OpenPose version**: Latest github master branch (latest commit id: 1f1aa9c59fe59c90cca685b724f4f97f76137224)

3. **General configuration**:
    - **Installation mode**: CMake, then makefile 
    - **Operating system** : macOS 
    - **Operating system version** : 11.2 (20D64) - Big Sur
    - **Release or Debug mode**?: release
    - Compiler: 
        - Apple clang version 12.0.0 (clang-1200.0.32.29)
        - Target: x86_64-apple-darwin20.3.0
        - Thread model: posix
        - InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

4. **Non-default settings**:
    - **3-D Reconstruction module added**?: no
    - Any other custom CMake configuration with respect to the default version?: no

5. **3rd-party software**:
    - **Caffe version**: stable 1.0 (1.0_31)
    - **CMake version** (`cmake --version` in Ubuntu): 3.19.6
    - **OpenCV version**: stable 4.5.1 (4.5.1_3)

6. No GPU issue

7. If **CPU-only mode** issue:
    - **CPU brand & model**: 2.4 GHz 8-Core Intel Core i9
    - Total **RAM memory** available: 64GB ram

8. If **Python** API:
    - **Python version**: 3.9.2
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.20.1

**Comment by rupang818** [comment]
I was able to resolve this myself by:
* Trying to reinstall Caffe multiple times
* Purging /usr/local/include
* Reinstall all the dependencies using `brew`

**Comment by DELTA37** [comment]
Hi ! How do you solve this problem? @rupang818

**Comment by lookcat** [comment]
os: macos big sur

1.  I set BUILD_PYTHON, then the program use the gcc (GCC detected, adding compile flags)
2. make -j`sysctl -n hw.logicalcpu`

It's ok.

I think that It's clang problem.
