### ISSUE TITLE
[Mac] Demo does not run - "Attempt to free invalid pointer"

### ISSUE THREAD

**Issue by rupang818** [CMU-Perceptual-Computing-Lab/openpose#1892]
### Issue Summary
With the files generated from running the CMake, I am trying to run the simple demo, but it it showing the message "Attempt to free invalid pointer 0x7feac270d5c0"

Here's the CMake GUI setting, if it helps:
![Screen Shot 2021-03-13 at 5 54 51 PM](https://user-images.githubusercontent.com/6089540/111054910-3901ae80-8425-11eb-86bb-58a89de26206.png)
(Note `WITH_QT` is on, `WITH_GTK` is off, per [this comment](https://github.com/BVLC/caffe/issues/5282#issuecomment-306063718))

### Executed Command (if any)
`./build/examples/openpose/openpose.bin --video examples/media/video.avi`

### OpenPose Output (if any)
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
---------------------------------- WARNING ----------------------------------
We have introduced an additional boost in accuracy in the CUDA version of about 0.2% with respect to the CPU/OpenCL versions. We will not port this to CPU given the considerable slow down in speed it would add to it. Nevertheless, this accuracy boost is almost insignificant so the CPU/OpenCL versions can be safely used.
-------------------------------- END WARNING --------------------------------
src/tcmalloc.cc:333] Attempt to free invalid pointer 0x7feac270d5c0

### Errors (if any)
Attempt to free invalid pointer 0x7feac270d5c0

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Execution error

### Your System Configuration
1. **Whole console output**: 
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
---------------------------------- WARNING ----------------------------------
We have introduced an additional boost in accuracy in the CUDA version of about 0.2% with respect to the CPU/OpenCL versions. We will not port this to CPU given the considerable slow down in speed it would add to it. Nevertheless, this accuracy boost is almost insignificant so the CPU/OpenCL versions can be safely used.
-------------------------------- END WARNING --------------------------------
src/tcmalloc.cc:333] Attempt to free invalid pointer 0x7feac270d5c0

2. **OpenPose version**: Latest github master branch (latest commit id: 1f1aa9c59fe59c90cca685b724f4f97f76137224)

3. **General configuration**:
    - **Installation mode**: CMake, then makefile 
    - **Operating system** : macOS 
    - **Operating system version** : 11.2 (20D64) - Big Sur
    - **Release or Debug mode**?: release
    - Compiler: 
        - Apple clang version 12.0.0 (clang-1200.0.32.29)
        - Target: x86_64-apple-darwin20.3.0
        - Thread model: posix
        - InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

4. **Non-default settings**:
    - **3-D Reconstruction module added**?: no
    - Any other custom CMake configuration with respect to the default version?: no

5. **3rd-party software**:
    - **Caffe version**: 1.0.0
    - **CMake version** (`cmake --version` in Ubuntu): 3.19.6
    - **OpenCV version**: 4.5.1

6. No GPU issue

7. If **CPU-only mode** issue:
    - **CPU brand & model**: 2.4 GHz 8-Core Intel Core i9
    - Total **RAM memory** available: 64GB ram

8. If **Python** API:
    - **Python version**: 3.6.5
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.20.1

**Comment by Cliwo** [comment]
Did you solve the problem? I'm having same one..

OS : Mac 11.3.1

**Comment by tejacques** [comment]
Also having the same issue

**Comment by elcchan99** [comment]
Same error here as well on 12.1 with M1 chip

**Comment by 0tist** [comment]
got the same error, any fix for that?

**Comment by Jaykob** [comment]
+1

**Comment by atabak-cve** [comment]
Didn't face the second issue on 12.2.1 intel mac.

**Comment by elcchan99** [comment]
I resolved the Attempt to free invalid pointer on OSX issue.
See my comment in another issue thread:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1902#issuecomment-1024890817

**Comment by rajhlinux** [comment]
I had the exact same issue as to [tejacques](https://github.com/tejacques) for compiling "Caffe" (Deep Learning Project on github). The solution was to remove the 2nd argument as stated by [tejacques](https://github.com/tejacques).

**Comment by greatdex** [comment]
> I resolved the Attempt to free invalid pointer on OSX issue. See my comment in another issue thread: [#1902 (comment)](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1902#issuecomment-1024890817)

This was the issue, and I solved it by following your steps, thanks @elcchan99 !
