### ISSUE TITLE
Pyopenpose not found within openpose 

### ISSUE THREAD

**Issue by NitikaGupta16** [CMU-Perceptual-Computing-Lab/openpose#1893]
While importing pyopenpose from openpose, it shows that pyopenpose can't be found. Do I need to install some separate files to import pyopenpose since pyopenpose is not present within any folder in the repository?

**Comment by HYC986** [comment]
I have the same issue!
I have try to fix it for almost 10 days. I doesn't work. I try to reinstall the system, still the same. 
somebody can help us? Thanks!

**Comment by jasmineekka3010** [comment]
> While importing pyopenpose from openpose, it shows that pyopenpose can't be found. Do I need to install some separate files to import pyopenpose since pyopenpose is not present within any folder in the repository?

Even I have tried this on both local machine as well as colaboratory, but in both cases, there was an error of importing pyopenpose.
The Openpose is successfully installed and the demo video is also running. But I want to extract the body keypoints coordinates and for that I run the following code but an error occurred both in collab as well as local machine.

"ImportError: cannot import name 'pyopenpose' from 'openpose' (unknown location)"

The corresponding code is:

import openpose
import logging
import sys
import time
import math
import cv2
import numpy as np
from openpose import pyopenpose as op

if name == 'main':
fps_time = 0

params = dict()
params["model_folder"] = "/content/openpose/models"

# Starting OpenPose
opWrapper = op.WrapperPython()
opWrapper.configure(params)
opWrapper.start()


print("OpenPose start")
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

ret_val, img = cap.read()
fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
out_video = cv2.VideoWriter('/tmp/output.mp4', fourcc, cap.get(cv2.CAP_PROP_FPS), (640, 480))

count = 0

if cap is None:
    print("Camera Open Error")
    sys.exit(0)
while cap.isOpened() and count < 30:
    ret_val, dst = cap.read()
    if ret_val == False:
        print("Camera read Error")
        break
    #dst = cv2.resize(image, dsize=(320, 240), interpolation=cv2.INTER_AREA)
    #cv2.imshow("OpenPose 1.5.1 - Tutorial Python API", dst)
    #continue

    datum = op.Datum()
    datum.cvInputData = dst
    opWrapper.emplaceAndPop([datum])
    fps = 1.0 / (time.time() - fps_time)
    fps_time = time.time()
    newImage = datum.cvOutputData[:, :, :]
    cv2.putText(newImage , "FPS: %f" % (fps), (20, 40),  cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    out_video.write(newImage)

    print("captured fps %f"%(fps))
    cv2.imshow("OpenPose 1.5.1 - Tutorial Python API", newImage)
    count += 1


cv2.destroyAllWindows()
out_video.release()
cap.release()


The error is on the line " from openpose import pyopenpose as op"

**Comment by chrisywong** [comment]
I fixed the `from openpose import pyopenpose as op` error by cleaning up different versions of python on my computer that might have been causing conflicts, and making sure everything compiled with the proper version. I even had to go into the `build/CMakeCache.txt` to manually set the Python version to 2.7 because it was picking remnants of 3.7 (even though I thought I had removed it to downgrade to 3.6). 

You might also want to check that `pyopenpose.so` exists in `/usr/local/python/` to see if it installed properly and that your `sys.path` points to that folder. You can perhaps also just try directly 

You can see my debugging process here https://github.com/ravijo/ros_openpose/issues/31#issuecomment-809430393 (note that this is a repository for a ROS wrapper for OpenPose, and not about OpenPose itself). For a quick check, you can follow the steps outlined here https://github.com/ravijo/ros_openpose/issues/31#issuecomment-809867503

Please take my methods with a grain of salt because I was just guessing at trying to fix what might be potential issues to resolve this.

**Comment by jasmineekka3010** [comment]
> I fixed the `from openpose import pyopenpose as op` error by cleaning up different versions of python on my computer that might have been causing conflicts, and making sure everything compiled with the proper version. I even had to go into the `build/CMakeCache.txt` to manually set the Python version to 2.7 because it was picking remnants of 3.7 (even though I thought I had removed it to downgrade to 3.6).
> 
> You might also want to check that `pyopenpose.so` exists in `/usr/local/python/` to see if it installed properly and that your `sys.path` points to that folder. You can perhaps also just try directly
> 
> You can see my debugging process here [ravijo/ros_openpose#31 (comment)](https://github.com/ravijo/ros_openpose/issues/31#issuecomment-809430393) (note that this is a repository for a ROS wrapper for OpenPose, and not about OpenPose itself). For a quick check, you can follow the steps outlined here [ravijo/ros_openpose#31 (comment)](https://github.com/ravijo/ros_openpose/issues/31#issuecomment-809867503)
> 
> Please take my methods with a grain of salt because I was just guessing at trying to fix what might be potential issues to resolve this.

Is there a  way to resolve this issue in colaboratory? 
Thanks for your response :)

**Comment by NitikaGupta16** [comment]
@jasmineekka3010 After cloning the open pose repository in google colab, make sure to add these commands also:
! git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
! cd openpose && mkdir build && cd build 
**! cd openpose/build && cmake -DBUILD_PYTHON=ON ..** 
! cd openpose/build && make -j`nproc`
! cd openpose/build && make install


cmake -DBUILD_PYTHON=ON ..  => This thing might be missing in your code due to which this error ImportError: cannot import name 'pyopenpose' from 'openpose' is occurring. I was also facing the same issue in colab but after using this command, I am able to use open pose.

**Comment by jasmineekka3010** [comment]
> @jasmineekka3010 After cloning the open pose repository in google colab, make sure to add these commands also:
> ! git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
> ! cd openpose && mkdir build && cd build
> **! cd openpose/build && cmake -DBUILD_PYTHON=ON ..**
> ! cd openpose/build && make -j`nproc`
> ! cd openpose/build && make install
> 
> cmake -DBUILD_PYTHON=ON .. => This thing might be missing in your code due to which this error ImportError: cannot import name 'pyopenpose' from 'openpose' is occurring. I was also facing the same issue in colab but after using this command, I am able to use open pose.

Yes I did. Infact Openpose is running smoothly. I am facing errors in post steps. I want to extract body keypoints coordinates and for that I am running a piece of code which I have mentioned earlier. But, there is an error of pyopenpose. I am using google colaboratory.
