### ISSUE TITLE
COCO JSON output image_id capped at 9999?

### ISSUE THREAD

**Issue by garyfeng** [CMU-Perceptual-Computing-Lab/openpose#190]
### Issue summary

Trying to process a video with 20k frames, with output in coco json. The `image_id` field seems to be mod 1k (see below). 

Been looking at `VideoCaptureReader::getFrameName()` but not sure that's the right place. 

### Executed command (if any)

```
bin\OpenPoseDemo --video examples\media\w21.mp4 --write_video output/w21-op.mp4 --write_coco_json output/w21-coco.json
```

### OpenPose output (if any)

```json
	{
		"image_id":9998,
		"category_id":1,
		"keypoints":[
			829.586,320.929,1,854.998,293.524,1,804.074,293.466,1,888.245,309.119,1,757.233,305.196,1,941.098,444.189,1,692.622,446.094,1,986.068,592.849,1,618.329,594.809,1,921.542,714.163,1,710.178,714.148,1,884.325,714.161,1,753.235,714.166,1,0,0,1,0,0,1,0,0,1,0,0,1
		],
		"score":0.0
	},
	{
		"image_id":9999,
		"category_id":1,
		"keypoints":[
			831.491,320.918,1,855.017,293.478,1,804.063,291.593,1,888.228,307.252,1,757.246,305.221,1,941.108,444.195,1,692.569,448.013,1,988.065,594.797,1,618.276,596.761,1,919.563,714.152,1,710.22,714.154,1,884.376,714.158,1,753.276,714.168,1,0,0,1,0,0,1,0,0,1,0,0,1
		],
		"score":0.0
	},
	{
		"image_id":0,
		"category_id":1,
		"keypoints":[
			829.594,320.915,1,855.029,293.489,1,804.051,291.553,1,888.237,311.105,1,757.247,305.175,1,941.087,446.04,1,692.577,446.127,1,986.104,600.602,1,622.2,594.801,1,919.577,714.164,1,710.218,714.153,1,882.379,714.163,1,751.311,714.17,1,0,0,1,0,0,1,0,0,1,0,0,1
		],
		"score":0.0
	},
	{
		"image_id":1,
		"category_id":1,
		"keypoints":[
			829.585,320.894,1,854.989,293.483,1,804.075,291.539,1,886.361,309.144,1,759.055,305.22,1,941.099,444.166,1,694.506,446.153,1,990.006,596.723,1,620.255,594.803,1,917.637,714.153,1,708.241,714.155,1,884.354,714.162,1,753.268,714.168,1,0,0,1,0,0,1,0,0,1,0,0,1
		],
		"score":0.0
	},
```

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type): output

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu): Win10
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 6
**GPU model** (`nvidia-smi` in Ubuntu): 1070
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows) or OpenCV 2.X or OpenCV 3.X.
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu) or CMake (Ubuntu, Windows) or Visual Studio (Windows).
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
This should be fixed now, as I was able to process 20k images. Let me know otherwise.
