### ISSUE TITLE
no Cmake GUI

### ISSUE THREAD

**Issue by lweingart** [CMU-Perceptual-Computing-Lab/openpose#1901]
Hello guys,

I'm trying to install open pose on a Jetson Xavier, and I'm doing everything through the command line, as I have no monitor for this device.

Could you please share a method to configure CMake for your open pose through the command line?
I don't have CMake-GUI nor do I have the possibility to install it on my device.

If you have any means to do it without CMake GUI, that would help me a great deal.
Thank you for your esteemed help.

Cheers

**Comment by lweingart** [comment]
Hi again,

Finally I went with the cmake-gui via VNC.
However, it fails at the very first step!

I run cmake-gui .. from the openpose/build directory.
Then I click on the "Configure" button and I keep the "Use default native compilers" option with "Unix Makefiles", as described on the screenshot.
Then, when I click on "Finish", I get an error message" "Error in configuration process, project files may be invalid".

See screenshot:

![screenshot](https://user-images.githubusercontent.com/4840059/112524886-9c35fe00-8da0-11eb-9a7b-764a0c1fb7c9.png)

Any help would be very appreciated :-)

Moreover, this repo is the last openpose like repo that appears to be working that I could find, so it would really save my day to be able to make it work.

Cheers guys

P.S. If you have a no gui way to do it, I'm still interested :-)

**Comment by ravijo** [comment]
@lweingart 

Of course, you can use `cmake`  from the command line. However, you need to make sure that variables are set properly. For example, 

- If you have a custom OpenCV, then you need to set the `OpenCV_INCLUDE_DIRS` and `OpenCV_LIBS_DIR` variables. 
- If you want to use Python bindings, then you need to set the `BUILD_PYTHON` variable.
- You need to set `BUILD_CAFFE` accordingly. 

Please see the [CMake Command Line Configuration (Ubuntu Only) documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/d7667624ae6eecbba4ac974b7dbc4905eb680306/doc/installation/0_index.md#cmake-command-line-configuration-ubuntu-only) for an example.

You can also check [CMakeLists.txt file](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/1f1aa9c59fe59c90cca685b724f4f97f76137224/CMakeLists.txt) to know more about these variables.

Hope it helps!
