### ISSUE TITLE
can you suggest the best machine for the project

### ISSUE THREAD

**Issue by hundredcaws** [CMU-Perceptual-Computing-Lab/openpose#191]
i am planning to buy a new pc for the project to be running win10. most vital as you state is over 16.gig nvidia card. what would be more realiable and not to be very expensive. a laptop or desktop pc? can 2 core or quad be decent solution?

**Comment by gineshidalgo99** [comment]
Please, check the OpenPose GPUs benchmark (README.md) in order to check your hardware spec needs vs. desired FPS.
