### ISSUE TITLE
[pyopenpose] ImportError: libopenpose.so.1.7.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MatthijsBurgh** [CMU-Perceptual-Computing-Lab/openpose#1911]
### Issue Summary
After completing the install procedure, I get an import error for the cpp library.

### Executed Command
PWD: `/home/username`
```python
import sys
sys.path.append("/usr/local/python")
import pyopenpose

ImportError: libopenpose.so.1.7.0: cannot open shared object file: No such file or directory
```
### Analysis
Openpose files in `/usr/local`
```bash
[/usr/local]
username@hostname $ find -name "*openpose*"
./python/openpose
./python/openpose/pyopenpose.cpython-38-x86_64-linux-gnu.so
./python/openpose/CMakeFiles/pyopenpose.dir
./python/pyopenpose.cpython-38-x86_64-linux-gnu.so
./include/openpose
./lib/libopenpose_face.so
./lib/libopenpose_filestream.so
./lib/libopenpose_gui.so
./lib/libopenpose_producer.so
./lib/libopenpose_utilities.so
./lib/libopenpose_thread.so
./lib/libopenpose_gpu.so
./lib/libopenpose_core.so
./lib/libopenpose.so
./lib/libopenpose_unity.so
./lib/libopenpose_wrapper.so
./lib/libopenpose.so.1.7.0
./lib/libopenpose_pose.so
./lib/libopenpose_hand.so
./lib/libopenpose_tracking.so
./lib/libopenpose_net.so
./lib/libopenpose_calibration.so
./lib/libopenpose_3d.so
```

When running the commands mentioned above with PWD: `openpose/build/python/openpose`. `pyopenpose` is imported without any issues. 

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Compilation/installation error

### Your System Configuration
2. **OpenPose version**: 1f1aa9c59fe59c90cca685b724f4f97f76137224

3. **General configuration**:
    - **Installation mode**: CMake with Python
    - **Operating system** Ubuntu 20.04
    - **Operating system version** Ubuntu 20.04
    - **Release or Debug mode**? (by default: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 9.3.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): No
    - Any other custom CMake configuration with respect to the default version? (by default: no): cmake .. -DBUILD_PYTHON=on -DPYTHON_EXECUTABLE=/usr/bin/python3.8 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.16.3
    - **OpenCV version**: pre-compiled  libopencv-dev: 4.2.0

8. If **Python** API:
    - **Python version**: 3.8
    - **Numpy version**: 1.19.5

**Comment by MatthijsBurgh** [comment]
Solved by changing import to

```python
from openpose import pyopenpose as op
```

**Comment by RobertoRoos** [comment]
Same issue here with the same solution, Thanks for posting. Though I think 'work around' is a better term. 

This should be mentioned somewhere on the documentation.
Or better yet, a Pip package should be wrapped around the `pyopenpose` module so the import isn't as fickle.

**Comment by MatthijsBurgh** [comment]
This is in the documentation. `import pyopenpose` was only working in an older version of OpenPose. And I just didn't check the updated docs after migrating to a newer version.
