### ISSUE TITLE
$ make -j `nproc` make: *** No targets specified and no makefile found.  Stop

### ISSUE THREAD

**Issue by gabriead** [CMU-Perceptual-Computing-Lab/openpose#1916]
Hi there,
I am having an issue with make step of openpose/build directory. It results in this error:
$ make -j `nproc`make: *** No targets specified and no makefile found.  Stop

I assume that caffe isn't installed properly. I have cloned https://github.com/CMU-Perceptual-Computing-Lab/caffe.git to 3rdparty
and executed ./scripts/ubuntu/install_deps.sh. What step am I missing? 
Thanks a lot in advance!

**Comment by ravijo** [comment]
@gabriead 

> I am having an issue with make step of openpose/build directory. It results in this error:
> $ make -j `nproc`make: *** No targets specified and no makefile found. Stop

Unfortunately, no one can tell the problem by seeing above one line!

> I assume that caffe isn't installed properly. I have cloned https://github.com/CMU-Perceptual-Computing-Lab/caffe.git to 3rdparty
> and executed ./scripts/ubuntu/install_deps.sh.

Why do you assume that Caffe isn't installed? Ideally, after cloning the repository, you should execute the following command:
```
git submodule update --init --recursive --remote
```
Caffe library is cloned automatically based on the CMake configurations.

> What step am I missing?

Please read the installation procedure in the [documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md).

Finally, please remember the following points:

- Please share the error completely. Whatever is reported at the terminal, please copy and paste everything.
- Please always follow the issue template. It makes easier to understand the problem. You can find the template [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/new)
