### ISSUE TITLE
openCV error when run commands "./openpose.bin --image_dir ./samples/ --display 0 --render_pose 0 --tracking 0 --number_people_max 1 -write_json ./features/ --num_gpu 2 --num_gpu_start 2"

### ISSUE THREAD

**Issue by yuwProject** [CMU-Perceptual-Computing-Lab/openpose#1917]
when I run the commands of "./openpose.bin --image_dir ./samples/ --display 0 --render_pose 0 --tracking 0 --number_people_max 1 -write_json ./features/ --num_gpu 2 --num_gpu_start 2"
I got errors as below:

Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Person tracking (`tracking` flag) is in experimental phase. Please, let us know if you find any bug on this alpha version.
OpenCV Error: Assertion failed (prevPyr[level * lvlStep1].size() == nextPyr[level * lvlStep2].size()) in calc, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/video/src/lkpyramid.cpp, line 1365

Error:
/build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/video/src/lkpyramid.cpp:1365: error: (-215) prevPyr[level * lvlStep1].size() == nextPyr[level * lvlStep2].size() in function calc

Coming from:
- /openpose/src/openpose/tracking/pyramidalLK.cpp:pyramidalLKOcv():458
- /openpose/src/openpose/tracking/personTracker.cpp:updateLK():125
- /openpose/src/openpose/tracking/personTracker.cpp:track():531
- /openpose/src/openpose/tracking/personTracker.cpp:trackLockThread():550
- /openpose/src/openpose/pose/poseExtractor.cpp:trackLockThread():229
- /openpose/include/openpose/pose/wPoseExtractor.hpp:work():107
- /openpose/include/openpose/thread/worker.hpp:checkAndWork():93

could you please help check how to solve this? many thanks in advance!

**Comment by Anustup900** [comment]
Hey @yuwProject  
You can look into this https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/213
i guess it will help

**Comment by yuwProject** [comment]
./openpose.bin --image_dir ./samples/ --write_json ./features/  --num_gpu 1 --num_gpu_start 5 --display 0 --render_pose 0


Thanks a lot!   this command fix the problem
