### ISSUE TITLE
from net output to .json

### ISSUE THREAD

**Issue by tamarev** [CMU-Perceptual-Computing-Lab/openpose#192]
where is the code that processes the net output map into a vector (like in the .json files)?
thanks!

**Comment by ktr-hubrt** [comment]
have you found it？

**Comment by gineshidalgo99** [comment]
There are several steps involved: image resize and merging, non-maxima suppression and a greedy algorithm. It's not a simple file/code but several files.

**Comment by ktr-hubrt** [comment]
so what shall i do ,when i want to change the output style in $json file?"version":1.0,
	"people":[
		{
			"pose_keypoints":[
				332.105,315.805,0.773826,342.391,391.269,0.719534,299.556,397.373,0.753655,301.739,476.939,0.758132,334.215,413.762,0.874977,379.101,379.08,0.607376,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,352.6,429.952,0.694569
			],
			"face_keypoints":[
				
			],
			"hand_left_keypoints":[
				
			],
			"hand_right_keypoints":[
				
			]
		}
for example ,i dont want the face &handkeypoint?

**Comment by gineshidalgo99** [comment]
@ktr-hubrt  The JSON file format is fixed, and it makes little or no sense to change it to 3 different files. Given that you will be using a JSON reader, just ignore the outputs when reading. The size difference is minimal to be worth dividing in 4 times more files. Still, using XML/YML formats I think the keypoints are saved in different files given that we simply use OpenCV cv::Mat saving format which cannot work for different keypoints at the same time.
