### ISSUE TITLE
Body_25 converting to other frameworks

### ISSUE THREAD

**Issue by CapnBloodBeard12345** [CMU-Perceptual-Computing-Lab/openpose#1922]
Could you possibly explain how the body_25 model is working a little here? 

I have been playing with converting the model from your prototxt definition to a keras model and also converting the weights to .h5 format. However after the conversion I am not getting the output I would expect after using your repo. So a couple of points of clarification:

The output is structured as (bs,H//8,W//8, 52 + 26)  where the first 52 elements in channel dimension are the PAFS = (Scalar_Field_x,Scalar_Field_y) and then the remainig 26 are 25 keypoints + bg? 

After running some test predictions the pafs look good but the heatmaps almost look like PAFs... so I am wondering about your keypoint extraction method. Is it the same as the initial model Apply Gaussian blur and extract index of maximum for each channel (assuming single person in the frame (similar to CPM))? 

My general interpretation of how the body_25 model is structure: 

Encoder block (essentially VGG_16 like initial OpenPose model)
Followed by four stages to refine PAF prediction (concatenating initial VGG encoded features each stages PAF prediction for next stage).
Followed by two stages to predict heatmaps where first input is (VGG Encoded concatenated with stage_four of paf branch output). 

Is it the case that you apply same standarization as other models (divide by 255 and 0 center with minus 0.5)? Also, is it assumed to have the same (BGR input format)? 

Just as a general last thought: I have successfully converted your other models to different DL frameworks without problem so if you have any insight as to why the heatmap predictions here are bad I would be much appreciated!

**Comment by JJLimmm** [comment]
Hi @CapnBloodBeard12345, i am trying to convert the body_25 caffe model to either ONNX or pytorch or tensorflow. Can i ask how did you do it? can you share with me your code that u used to convert it?

**Comment by abhiraii** [comment]
I am also trying to convert body_25 model to onnx . I used caffe2onnx api to do that but somehow it's not.  supported for few operators in the model. Can anybody share details regarding this?
