### ISSUE TITLE
Can OpenCV achieve the same lines as yours?

### ISSUE THREAD

**Issue by wux024** [CMU-Perceptual-Computing-Lab/openpose#1925]
Hello, OpenPose has made me work well, but I want to beautify my output. The lines of the examples in your document are very beautiful. How did you achieve this? I did not find a suitable method to draw lines as beautiful as yours through OpenCV.

**Comment by ravijo** [comment]
@wux024 

> Can OpenCV achieve the same lines as yours?

Why not?

For easier understanding, I suggest you look at CPU-based rendering. You can notice OpenCV calls easily. Please see `renderKeypointsCpu` [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/b1cb2b69cf8c4c288921e48c37f339a64db26f58/src/openpose/utilities/keypoint.cpp#L176-L278).

Next, for advanced and faster rendering, GPU-based rendering is done using CUDA. I will leave a few links below, please have a look:

- [openpose/include/openpose_private/utilities/render.hu](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/b1cb2b69cf8c4c288921e48c37f339a64db26f58/include/openpose_private/utilities/render.hu)
- [openpose/src/openpose/face/renderFace.cu](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/b1cb2b69cf8c4c288921e48c37f339a64db26f58/src/openpose/face/renderFace.cu)
- [openpose/src/openpose/hand/renderHand.cu](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/b1cb2b69cf8c4c288921e48c37f339a64db26f58/src/openpose/hand/renderHand.cu)

Hope it helps!

**Comment by wux024** [comment]
thank you very much!
