### ISSUE TITLE
Error by the building process (with "BUILD_PYTHON")

### ISSUE THREAD

**Issue by LucasFKobernic** [CMU-Perceptual-Computing-Lab/openpose#1935]
Hi everyone, 

I'm trying to install openpose on my computer (Windows 10). I have installed all the pre-requisites and have followed the steps from here: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#cmake-configuration

but by the step 4 (already inside cmake-gui) by choosing "BUILD_PYTHON" and then "configure", i get the following error:

```
Found PythonInterp: C:/Python3.7/python.exe (found version "3.7.4") 
CMake Error at 3rdparty/pybind11/tools/FindPythonLibsNew.cmake:125 (message):
  Python config failure: Python is 64-bit, chosen compiler is 32-bit
Call Stack (most recent call first):
  3rdparty/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  3rdparty/pybind11/CMakeLists.txt:33 (include)
```

How can i change the compiler from 32-bit to 64 bit? or is the error another one?

Thanks!

Lucas

**Comment by SCWhite** [comment]
@LucasFKobernic  HI, wonder if there is any suggestion for this issue ?

**Comment by SirCamyCamCam** [comment]
I am also experiencing this issue

**Comment by SirCamyCamCam** [comment]
@SCWhite I was able to resolve this issue for my machine however, this may not work for you. The error first occurred when I changed python versions from 3.8 to 3.7. 

Here are the steps I took:
1. I first checked the 'Advanced' option in CMake.
2. I then changed the 'PYTHON_EXECUTABLE' from 'C:/Users/Camer/AppData/Local/Programs/Python/Python38/python.exe' to 'C:/Users/Camer/AppData/Local/Programs/Python/Python37/python.exe'

I then configured and generated without a problem

**Comment by SCWhite** [comment]
@SirCamyCamCam  Thank you for your reply, changing python version do solve my problem.
Thank you.

**Comment by mufenzhimi** [comment]
> @SCWhite I was able to resolve this issue for my machine however, this may not work for you. The error first occurred when I changed python versions from 3.8 to 3.7.
> 
> Here are the steps I took:
> 
> 1. I first checked the 'Advanced' option in CMake.
> 2. I then changed the 'PYTHON_EXECUTABLE' from 'C:/Users/Camer/AppData/Local/Programs/Python/Python38/python.exe' to 'C:/Users/Camer/AppData/Local/Programs/Python/Python37/python.exe'
> 
> I then configured and generated without a problem

It works!!!! Thanks a lot~
