### ISSUE TITLE
openpose python API with no keypoints

### ISSUE THREAD

**Issue by CKTetris** [CMU-Perceptual-Computing-Lab/openpose#1939]
### Issue Summary
Hello, everyone. I want to use openpose python API to make gesture classifying. When I use terminal to open openpose, it can mark keypoints I want. However, when I use python API example to call openpose, it just show no keypoints.  Is there any people know how to solve it? Thank you!
I use ubuntu18.04, cuda 10.1, cudnn 7.6.0.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
Here's the code:
```
# From Python
# It requires OpenCV installed for Python
import sys
import cv2
import os
from sys import platform
import argparse

try:
    # Import Openpose (Windows/Ubuntu/OSX)
    dir_path = os.path.dirname(os.path.realpath(__file__))
    try:
        # Windows Import
        if platform == "win32":
            # Change these variables to point to the correct folder (Release/x64 etc.)
            sys.path.append(dir_path + '/../../python/openpose/Release');
            os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + '/../../x64/Release;' +  dir_path + '/../../bin;'
            import pyopenpose as op
        else:
            # Change these variables to point to the correct folder (Release/x64 etc.)
            #sys.path.append('../../python');
            # If you run `make install` (default path is `/usr/local/python` for Ubuntu), you can also access the OpenPose/python module from there. This will install OpenPose and the python library at your desired installation path. Ensure that this is in your python path in order to use it.
            sys.path.append('/usr/local/python')
            from openpose import pyopenpose as op
    except ImportError as e:
        print('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
        raise e

    # Flags
    parser = argparse.ArgumentParser()
    parser.add_argument("--image_path", default="local/src/openpose/examples/media/COCO_val2014_000000000192.jpg", help="Process an image. Read all standard formats (jpg, png, bmp, etc.).")
    args = parser.parse_known_args()

    # Custom Params (refer to include/openpose/flags.hpp for more parameters)
    params = dict()
    params["model_folder"] = "local/src/openpose/models/"
    params["net_resolution"] = "160x160"
    # Add others in path?
    for i in range(0, len(args[1])):
        curr_item = args[1][i]
        if i != len(args[1])-1: next_item = args[1][i+1]
        else: next_item = "1"
        if "--" in curr_item and "--" in next_item:
            key = curr_item.replace('-','')
            if key not in params:  params[key] = "1"
        elif "--" in curr_item and "--" not in next_item:
            key = curr_item.replace('-','')
            if key not in params: params[key] = next_item

    # Construct it from system arguments
    # op.init_argv(args[1])
    # oppython = op.OpenposePython()

    # Starting OpenPose
    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()

    # Process Image
    datum = op.Datum()
    imageToProcess = cv2.imread(args[0].image_path)
    datum.cvInputData = imageToProcess
    opWrapper.emplaceAndPop(op.VectorDatum([datum]))

    # Display Image
    print("Body keypoints: \n" + str(datum.poseKeypoints))
    cv2.imshow("OpenPose 1.7.0 - Tutorial Python API", datum.cvOutputData)
    cv2.waitKey(0)
except Exception as e:
    print(e)
    sys.exit(-1)
```

### OpenPose Output (if any)
```
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Body keypoints: 
None

```

![OpenPose 1 7 0 - Tutorial Python API_screenshot_09 05 2021](https://user-images.githubusercontent.com/83913515/117576316-184d9080-b118-11eb-8f4f-6b7898ab135b.png)

that pop out from program, not example from openpose. 

### Type of Issue
- Help wanted

**Comment by jimbo99-beep** [comment]
Hello, @CKTetris 
It is possible to have the problem with caffemodel as it is mentioned in "Always Zero People Detected" in [05_faq.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/05_faq.md#always-zero-people-detected).
What i did is to download a new caffemodel for 25-keypoint detection at least. One way to solve this problem( at least in my case) was to go to to this [Dropbox link](https://www.dropbox.com/s/03r8pa8sikrqv62/pose_iter_584000.caffemodell), and download the model. Then in your /[openpose_folder] (not in /[openpose_folder]/build), go to  /[openpose_folder]/models/pose/model/body_25 and replace the old caffemodel with the new one. Then in /[openpose_folder]/build, configure and generate again the libraries in CMAKE (make sure you have checked BUILD_CAFFE ) and then compile. Then i think that you will detect keypoints normally.
I hope that I helped you!

**Comment by CKTetris** [comment]
> Hello, @CKTetris
> It is possible to have the problem with caffemodel as it is mentioned in "Always Zero People Detected" in [05_faq.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/05_faq.md#always-zero-people-detected).
> What i did is to download a new caffemodel for 25-keypoint detection at least. One way to solve this problem( at least in my case) was to go to to this [Dropbox link](https://www.dropbox.com/s/03r8pa8sikrqv62/pose_iter_584000.caffemodell), and download the model. Then in your /[openpose_folder] (not in /[openpose_folder]/build), go to /[openpose_folder]/models/pose/model/body_25 and replace the old caffemodel with the new one. Then in /[openpose_folder]/build, configure and generate again the libraries in CMAKE (make sure you have checked BUILD_CAFFE ) and then compile. Then i think that you will detect keypoints normally.
> I hope that I helped you!

Hi, @jimbo99-beep 
Thanks to reply my question, I think it may have some problem in my openpose model, so I just deleted the all model folder and downloaded a new one on github. After I configured and installed again, the problem was  solved.

**Comment by vrahnos3** [comment]
> Hello, @CKTetris It is possible to have the problem with caffemodel as it is mentioned in "Always Zero People Detected" in [05_faq.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/05_faq.md#always-zero-people-detected). What i did is to download a new caffemodel for 25-keypoint detection at least. One way to solve this problem( at least in my case) was to go to to this [Dropbox link](https://www.dropbox.com/s/03r8pa8sikrqv62/pose_iter_584000.caffemodell), and download the model. Then in your /[openpose_folder] (not in /[openpose_folder]/build), go to /[openpose_folder]/models/pose/model/body_25 and replace the old caffemodel with the new one. Then in /[openpose_folder]/build, configure and generate again the libraries in CMAKE (make sure you have checked BUILD_CAFFE ) and then compile. Then i think that you will detect keypoints normally. I hope that I helped you!

Hello, I was in trouble at least for one month with this issue. I downloaded the model you mentioned and it works. 
Really thanks for your contribution!!!
