### ISSUE TITLE
threre might be a problem with write_coco_json

### ISSUE THREAD

**Issue by tamarev** [CMU-Perceptual-Computing-Lab/openpose#194]
threre might be a problem with write_coco_json:
it seems there are commas at the end of arreys that either shouldn't be ther or a number is missing after them. when trying to initializa a coco instance with them I get: 
ValueError: No JSON object could be decoded

**Comment by gineshidalgo99** [comment]
That code is working with the Matlab COCO interface (at least on my device). Still, I think we fixed the extra comma in newer versions. Are you using the last OpenPose version?

**Comment by tamarev** [comment]
I tried again yesterday after  `/bin/sh -c wget https://github.com/CMU-Perceptual-Computing-Lab/openpose/archive/master.zip` so I guess it is updated.

here is the begining of the result of `./build/examples/openpose/openpose.bin -image_dir <coco dataset path>/images/val2014 -write_coco_json  <target dir>/1.json -no_display`:
```
[
	{
		"image_id":74,
		"category_id":1,
		"keypoints":[
			300.994,97.2895,1,0,0,1,300.977,97.2147,1,304.454,96.0944,1,300.972,97.2009,1,309.14,99.5827,1,299.817,104.167,1,312.55,109.991,1,298.681,113.438,1,311.401,116.931,1,299.804,116.943,1,309.106,118.083,1,301.036,120.384,1,309.051,133.079,1,302.111,133.124,1,309.017,143.528,1,302.121,145.85,1,
		],
		"score":0.0
	},
	{
		"image_id":136,
		"category_id":1,
		"keypoints":[
			0,0,1,0,0,1,0,0,1,0,0,1,44.68,102.647,1,0,0,1,9.13145,169.722,1,0,0,1,22.3439,262.214,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,
		],
		"score":0.0
	},
```
as you can see the length of the "keypoints" array is 51 and ends with a comma, and this is the case for all items in the file.

**Comment by gineshidalgo99** [comment]
That bug is solved. Now there is no extra comma. Thank you for the feed-back!

(I'm sorry, I was on vacations at that moment and I quickly fixed it but I forgot to write it here)
