### ISSUE TITLE
How can i get the Depth data of the body that are been tracked?

### ISSUE THREAD

**Issue by aniketzz** [CMU-Perceptual-Computing-Lab/openpose#195]

**Comment by gineshidalgo99** [comment]
Only 2D

**Comment by archenroot** [comment]
Technically speaking, if I use stereo camera, I can use 2D navigates of specific points from openpose and calculate depth in parallel using opencv only, correct?

**Comment by gineshidalgo99** [comment]
Yes, that's what we do in our 3-D OpenPose demo, re-project 2D keypoints into 3D given calibrated stereo cameras (check the doc for info about it).
