### ISSUE TITLE
Hash mis-match when trying to download BODY_25, COCO, MPI, hand model. 

### ISSUE THREAD

**Issue by SamDuignan** [CMU-Perceptual-Computing-Lab/openpose#1951]
### Issue Summary
Hash mis-match when trying to download BODY_25, COCO, MPI, hand model.
Links are down where supplied on prerequisites page: [prerequisites](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/1_prerequisites.md) 

### Executed Command (if any)

**_DockerFile used to replicate this issue:_**

FROM nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y git vim cmake gcc g++
RUN apt-get install -y cmake-qt-gui 
RUN apt-get install -y                    \
    libprotobuf-dev protobuf-compiler \
    libcudnn8-dev                     \
    libgoogle-glog-dev                \
    libopencv-dev                     \
    libboost-all-dev                  \
    libatlas-base-dev                 \
    libhdf5-dev                       \
    libgflags-dev                     \ 
    libopencv-dev                     
RUN apt-get install -y python3-dev
RUN apt-get install -y python3-pip
RUN pip3 install numpy opencv-python
RUN git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose
WORKDIR /openpose
RUN bash ./scripts/ubuntu/install_deps.sh
RUN git submodule update --init --recursive --remote
RUN mkdir build; 
WORKDIR /build
RUN cmake -DBUILD_PYTHON=ON ..
RUN make -j 'nproc'

### Errors (if any)
`-- Download the models.
-- Downloading BODY_25 model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [28;"Timeout was reached"]

Call Stack (most recent call first):
  CMakeLists.txt:985 (download_model)

-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/openpose/models/face/pose_iter_116000.caffemodel]
      expected hash: [e747180d728fa4e4418c465828384333]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [28;"Timeout was reached"]

Call Stack (most recent call first):
  CMakeLists.txt:991 (download_model)

-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
-- Models Downloaded.
CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/openpose/models/hand/pose_iter_102000.caffemodel]
      expected hash: [a82cfc3fea7c62f159e11bd3674c1531]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [28;"Timeout was reached-DBUILD_PYTHON=ON"]

Call Stack (most recent call first):
  CMakeLists.txt:993 (download_model)
`

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

3. **General configuration**:
    - Installation mode: (Ubuntu); CMake, 
    - Operating system: Ubuntu
    - Operating system version: 20.04
    - Release or Debug mode?: release
    - Compiler ; gcc version 9.3.0

4. **Non-default settings**:
    - 3-D Reconstruction module added?: no
    - Any other custom CMake configuration with respect to the default version? : BUILD_PYTHON=ON

5. **3rd-party software**:
    - Caffe version: Default from OpenPose
    - CMake version: 3.16.3
    - OpenCV version: pre-compiled(only Ubuntu).

6. If **GPU mode** issue:
    - CUDA version : 11.3
    - cuDNN version: 8.2.0
    - GPU model: GeForce RTX 2080 Ti

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - Python version: 3.7
    - Numpy version: 1.20.3

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on the [profiling documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/06_maximizing_openpose_speed.md#profiling-speed).

**Comment by zkwjq** [comment]
Having the same issue. I suspect the server for downloading the models is down (timeout)

**Comment by kishorkuttan** [comment]
For temporary workaround use this CMakeLists.txt to compile the openpose. https://drive.google.com/file/d/1Y_H9XSrkiE9RVjZ-liPoRHGMxHEBLyVH/view?usp=sharing

**Comment by zkwjq** [comment]
If I am not mistaken, these are the same files as in CMakeLists, with the
hash changed. The issue at the moment is that the CMU servers are
unavailable, so the mismatch is actually caused by a timeout error.

Thanks,

Théo

**Comment by ayushgupta9198** [comment]
Hi all ,

**This issue was solved by me you can find the solution in my profile**

Thanks for your time

**Comment by gineshidalgo99** [comment]
#1602 Sorry!
