### ISSUE TITLE
OpenPose Model cannot be reached---Server down!

### ISSUE THREAD

**Issue by 85nnamdi** [CMU-Perceptual-Computing-Lab/openpose#1955]
### Issue Summary
I have been trying to get OpenPose running since 18.05.2021, following the instructions in the [documentation ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#compiling-and-running-openpose-from-source). I tried to build from [source](https://github.com/CMU-Perceptual-Computing-Lab/openpose/archive/refs/tags/v1.7.0.zip), but get the error shown in the figure below in OpenPose Output.

I have also downloaded the pre-compiled [version](https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/download/v1.7.0/openpose-1.7.0-binaries-win64-gpu-python3.7-flir-3d_recommended.zip). Then on running getModel.bat, the ran into the following error that runs infinitely as can be seen in Executed command. After the copying the [link ](http://posefs1.perception.cs.cmu.edu/OpenPose/models/) from the getModel.bat into my browser, the [link ](http://posefs1.perception.cs.cmu.edu/OpenPose/models/) wasn't reachable either.

Therefore, there's a strong indication that the server hosting the Models is down and probably needs to be woken up.

### Executed Command (if any)
![OpenPoseModel](https://user-images.githubusercontent.com/7103201/119394255-41eae800-bcd2-11eb-96b5-452ada767e05.PNG)

### OpenPose Output (if any)
![OpenPoseBuild](https://user-images.githubusercontent.com/7103201/119393540-62ff0900-bcd1-11eb-99ed-1ecff52c9183.PNG)

**Comment by IBNU1** [comment]
Server is down you have to manualy get them from the backups.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602

**Comment by gineshidalgo99** [comment]
#1602 Sorry!
