### ISSUE TITLE
can't import pyopenpose on win10 after successfully compiling

### ISSUE THREAD

**Issue by zxwblublu** [CMU-Perceptual-Computing-Lab/openpose#1956]
### Issue Summary
Hi,I successfully compiled the code ,and I got these files.
![image](https://user-images.githubusercontent.com/43490697/120078086-4ce1b600-c0e0-11eb-8607-7e78a516445f.png)
And then I successfully ran the example demos
![image](https://user-images.githubusercontent.com/43490697/120078109-6c78de80-c0e0-11eb-909d-15d1dfe29b91.png)
But then i ran into error when trying to import pyopenpose. I will appreciate if anyone can give me some help!
![image](https://user-images.githubusercontent.com/43490697/120078214-ef019e00-c0e0-11eb-8180-ca0631c83fcf.png)
### Executed Command (if any)
 import pyopenpose
### Errors (if any)
ImportError: DLL load failed

### Type of Issue
- Compilation/installation error

### System Configuration

**OpenPose version**: Latest GitHub code

    - **Installation mode**: CMake on Windows
    - **Operating system** (`lsb_release -a` in Ubuntu):win10

    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):10.2

    - **Python version**:  3.7

**Comment by ravijo** [comment]
@zxwblublu 

As per your screenshots, it is clear that OpenPose has been installed properly and you can execute the example as well.

I think you have not added `pyopenpose` in your $PATH. Please look at the highlighted piece of code [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/b1cb2b69cf8c4c288921e48c37f339a64db26f58/examples/tutorial_api_python/01_body_from_image.py#L15-L17).


Before you execute `import pyopenpose as op`, you must configure your $PATH properly. 

Hope it helps!

**Comment by zxwblublu** [comment]
> @zxwblublu
> 
> As per your screenshots, it is clear that OpenPose has been installed properly and you can execute the example as well.
> 
> I think you have not added `pyopenpose` in your $PATH. Please look at the highlighted piece of code [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/b1cb2b69cf8c4c288921e48c37f339a64db26f58/examples/tutorial_api_python/01_body_from_image.py#L15-L17).
> 
> Before you execute `import pyopenpose as op`, you must configure your $PATH properly.
> 
> Hope it helps!

problem solved , thank u for help!

**Comment by aha-h** [comment]
https://blog.csdn.net/qq_44705642/article/details/138624637?spm=1001.2014.3001.5501 may help you
