### ISSUE TITLE
How to adjust the net_resolution according to the input image?

### ISSUE THREAD

**Issue by WilliamRuRu15** [CMU-Perceptual-Computing-Lab/openpose#196]
### Issue summary
Due to my low GPU, if I set the `net_resolution` 656x368, it will run very slow; and if I set it 160x160, it runs faster but has a lower precision. So I wonder if there is a principle of adjusting the `net_resolution` to fit the input size and also produce an acceptable framerate. What are the numbers beside 'x' stand for and what is net resolution? I read the paper and I'm still confused about this parameter.

### Type of issue
- Question

### My system configuration
**Operating system** : Win8.1
**CUDA version** : 8
**cuDNN version**: 5.1
**GPU model** : 1050 ti
**Caffe version**: Default

**Comment by gineshidalgo99** [comment]
I am very sorry, I was on vacations when you posted and didn't see it at all.

I added last week the option to use "-1" for one of the 2 dimensions (either width or height). So my recommendation is for you to play with "-1x368", ..., "-1x160". In this way the whole resulting image comes from the original so the speed-accuracy is maximized. Feel free to ask any further question.

Again, sorry for the delayed answer.
