### ISSUE TITLE
Fatal Python error: deallocating None  When the cumulative times of reading datum.poseKeypoints (only when datum.poseKeypoints  is none) exceeds a certain number 

### ISSUE THREAD

**Issue by kexante** [CMU-Perceptual-Computing-Lab/openpose#1967]
### Issue Summary
I used Openpose to extract pose information with a surveillance camera in real-time.  However, sometimes it will stop with fatal python error. I tested it many times and found it is related to the cumulative times of reading datum.poseKeypoints when  datum.poseKeypoints is None. Then I did the test below.

    params = dict()
    params["model_folder"] = '/raid/workspace/openpose/models/'
    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()

    img = cv2.imread('/raid/workspace/openpose/examples/tutorial_api_python/frame.png')
    
    count = 0
    while True:
        datum = op.Datum()
        datum.cvInputData = img
        opWrapper.emplaceAndPop(op.VectorDatum([datum]))
        count = count + 1
        print(count, datum.poseKeypoints)

> ...
11098 None
11099 None
11100 None
11101 None
11102 None
Fatal Python error: deallocating None
Current thread 0x00007f5af0849740 (most recent call first):
  File "test.py", line 31 in <module>
Aborted (core dumped)

Line 31 is 'print(count, datum.poseKeypoints)'. And there is no person in the image, so Openpose can not detect any skeleton, datum.poseKeypoints is None.  And then I only run the image once and read datum.poseKeypoints repeatly. 

 
    params = dict()
    params["model_folder"] = '/raid/workspace/openpose/models/'
    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()

    img = cv2.imread('/raid/workspace/openpose/examples/tutorial_api_python/frame.png')
    datum = op.Datum()
    datum.cvInputData = img
    opWrapper.emplaceAndPop(op.VectorDatum([datum]))
    
    count = 0
    while True:
        count = count + 1
        print(count, datum.poseKeypoints)

> ...
11098 None
11099 None
11100 None
11101 None
11102 None
Fatal Python error: deallocating None
Current thread 0x00007f5af0849740 (most recent call first):
  File "test.py", line 31 in <module>
Aborted (core dumped)

I tested it many times. The result is the same. If datum.poseKeypoints is None, after reading datum.poseKeypoints over 11102 times the code will stop with fatal error.  And if datum.poseKeypoints is not None, no matter how many times reading it the code works well. It's really strange for me. Hope to get help here.  

### OpenPose Output (if any)

> ...
11098 None
11099 None
11100 None
11101 None
11102 None
Fatal Python error: deallocating None
Current thread 0x00007f5af0849740 (most recent call first):
  File "test.py", line 31 in <module>
Aborted (core dumped)

### Errors (if any)

See above 

### Type of Issue
- Execution error

### Your System Configuration
1. **Whole console output** See above

2. **OpenPose version**: Latest GitHub code OpenPose v1.7.0

3. **General configuration**:
    - **Installation mode**: : CMake
    - **Operating system** : Ubuntu
    - **Operating system version** :  Ubuntu 18.04.5 LTS
    - **Release or Debug mode**? : release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows): gcc (Ubuntu 8.4.0-4ubuntu1) 8.4.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.19.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu);
    
6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): release 11.1, V11.1.74
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):CUDA Version: 11.2    

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 3.6
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.18.5

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on the [profiling documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/06_maximizing_openpose_speed.md#profiling-speed).

**Comment by treeebooor** [comment]
I'm having the same exact problem. Did you ever figure out what is going on?

**Comment by kexante** [comment]
> I'm having the same exact problem. Did you ever figure out what is going on?

Not yet. I still don't understand why reading a variable need to deallocate something. However, since the error occurs after the cumulative times of reading datum.poseKeypoints with None reaches a constant number, we can restart the process before that to avoid the error. But this is definitely not a good solution with more time on initialization.

**Comment by treeebooor** [comment]
> > I'm having the same exact problem. Did you ever figure out what is going on?
> 
> Not yet. I still don't understand why reading a variable need to deallocate something. However, since the error occurs after the cumulative times of reading datum.poseKeypoints with None reaches a constant number, we can restart the process before that to avoid the error. But this is definitely not a good solution with more time on initialization.

How do you restart the process? I tried to do what you said when it reaches a certain number restart everything but it is still erroring at the exact same iteration. I just called these lines once the count gets close to 10171(different iteration for me), and it prints out the starting message "Starting OpenPose Python Wrapper...". Then I contiune to access poseKeypoints but still errors. Is this how you restart the openpose process?
```
opWrapper = op.WrapperPython() 
opWrapper.configure(params)
opWrapper.start()
datum = op.Datum()
datum.cvInputData = img
opWrapper.emplaceAndPop(op.VectorDatum([datum]))
```

**Comment by kexante** [comment]
> > > I'm having the same exact problem. Did you ever figure out what is going on?
> > 
> > 
> > Not yet. I still don't understand why reading a variable need to deallocate something. However, since the error occurs after the cumulative times of reading datum.poseKeypoints with None reaches a constant number, we can restart the process before that to avoid the error. But this is definitely not a good solution with more time on initialization.
> 
> How do you restart the process? I tried to do what you said when it reaches a certain number restart everything but it is still erroring at the exact same iteration. I just called these lines once the count gets close to 10171(different iteration for me), and it prints out the starting message "Starting OpenPose Python Wrapper...". Then I contiune to access poseKeypoints but still errors. Is this how you restart the openpose process?
> 
> ```
> opWrapper = op.WrapperPython() 
> opWrapper.configure(params)
> opWrapper.start()
> datum = op.Datum()
> datum.cvInputData = img
> opWrapper.emplaceAndPop(op.VectorDatum([datum]))
> ```

Just Process. And I have tried subprocess and thread, but these can't avoid the error. 
`from multiprocessing import Process,Queue
q = Queue()
p = Process(target=SkeletonNumber,args=(datum, q,))
p.start()
p.join()
number = q.get()

def SkeletonNumber(result,q):
    if result.poseKeypoints is None:
        q.put(0) 
    else:
        q.put(result.poseKeypoints.shape[0])
`
However, the code above doesn't count the number but just starts a new process when need to read datum.poseKeypoints. So it can be   optimize by counting the number of reading datum.poseKeypoints when it's None, then save the time to initialize a process .

**Comment by burnzzz** [comment]
I have the same issue, but always around frame 8900 - 9050. What is this and why does it happen at this point? I do not understand the connection at all? Any hints from the authors?

**Comment by treeebooor** [comment]
> I have the same issue, but always around frame 8900 - 9050. What is this and why does it happen at this point? I do not understand the connection at all? Any hints from the authors?

It seems like when datum.poseKeypoints is None(no person in image), the number of references to that variable is set to that number. If you print out the number of references using `sys.getrefcount(datum.poseKeypoints)`, it should give you that iteration that you error at. I don't understand why but that specific number is different for everyone, might be due to different environments. And as you keep accessing keyPoints(which is still set to None), the number of references decreases each time by 1.  And once you reach 0, thats when the deallocating None error happens. I have no idea why this happens but  I believe that is where the number comes from.

**Comment by treeebooor** [comment]
I have found another workaround by modifying openpose source code. This way you do not have to restart the process over and over again. Instead of accessing datum.poseKeypoints directly, we can create a getter method for the datum class in include/openpose/core/datum.hpp. 
```
Array<float> getPoseKeypoints(){
    if(!poseKeypoints.empty()) return poseKeypoints;
    else return Array<float>(1,-1000);
}
```
And bind it to a python function for the datum object in python/openpose/openpose_python.cpp . Like this
`.def("poseKeypoints", &Datum::getPoseKeypoints)`

The issue with the original code is that when you access poseKeypoints when it is None, python decreases the reference count of poseKeypoints by 1 which will eventually lead to deallocating none error when there are no more references. With this getter function, if poseKeypoints is empty we can return an ordinary array, so poseKeypoints will never be None when we access it in python. Now just call `datum.poseKeypoints()` in python to get poseKeypoints. 

This method will require building openpose from source but is much more efficient than restarting.

**Comment by burnzzz** [comment]
Great workaround! Fixed the issue for me too! Thx a lot for sharing !!!

**Comment by cagdasbas** [comment]
Hi @kexante, this issue causes a lot of trouble for me too. I want to create a PR and implement  @treeebooor 's suggestion. I imagine binding an already used variable to another function is not backward compatible. I'm planning to create a new python binding in openpose_python.cpp:
```
.def("getPoseKeypoints", &Datum::getPoseKeypoints)
```
What do you think? Other than the implementation itself, should I do anything else?

**Comment by kexante** [comment]
> Hi @kexante, this issue causes a lot of trouble for me too. I want to create a PR and implement @treeebooor 's suggestion. I imagine binding an already used variable to another function is not backward compatible. I'm planning to create a new python binding in openpose_python.cpp:
> 
> ```
> .def("getPoseKeypoints", &Datum::getPoseKeypoints)
> ```
> 
> What do you think? Other than the implementation itself, should I do anything else?

@treeebooor ‘s suggestion works well for me. And I think it's relatively easy to modify existing python code. Just replace "datum.poseKeypoints" by "datum.getPoseKeypoints()". If we need to determine whether datum.poseKeypoints is None, just use " if datum.getPoseKeypoints().ndim > 1" to replace " if datum.poseKeypoints is None". Because if Openpose detect people in the image, datum.poseKeypoints will be an array(n*25*3), ndim is 3. Otherwise,  datum.getPoseKeypoints() will return Array<float>(1,-1000), whose ndim is 1.
