### ISSUE TITLE
Result video - The audio isn't recording?

### ISSUE THREAD

**Issue by paulranico** [CMU-Perceptual-Computing-Lab/openpose#199]
### Issue summary
Can't seem to hear any audio recorded

### Type of issue
You might select multiple topics, delete the rest:
- Question

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu): Windows 8.1
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): v8.0
**cuDNN version**: 8.0-windows7
**GPU model** (`nvidia-smi` in Ubuntu): NVIDIA GeForce GTX 1080
**Caffe version**: Default from OpenPose.
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows)
Generation mode (only for Ubuntu): Visual Studio (Windows).
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
No, there is no audio, only video.

You can use any free tool to add audio to video as a post-processing step, but OpenCV does not add the audio files so we cannot either.
