### ISSUE TITLE
License for profit organization 

### ISSUE THREAD

**Issue by xishuaipeng** [CMU-Perceptual-Computing-Lab/openpose#1996]
Hi, 
We notices that there is a term in the openpose license, i.e. "ACADEMIC OR NON-PROFIT ORGANIZATION NONCOMMERCIAL RESEARCH USE ONLY" . 
Does it mean that the resaerchs in profit organization are not allowed to download or use openpose pre-trained model even only for research purpose.

**Comment by gineshidalgo99** [comment]
You'd need a commercial license for that:
https://github.com/CMU-Perceptual-Computing-Lab/openpose#license

Best
