### ISSUE TITLE
Which version of Protobuf?

### ISSUE THREAD

**Issue by jmarsico** [CMU-Perceptual-Computing-Lab/openpose#2]
when running install_caffe_and_openpoase.sh i am getting a lot of errors with caffe.pb.h.  At first, the errors  protobuf version related (2.5 was too old, 3.3 was too new).  I am currently using protobuf 3.0.2 and getting errors:

```
.build_release/src/caffe/proto/caffe.pb.h:8535:30: error: ‘PROTOBUF_FINAL’ does not name a type
   bool IsInitialized() const PROTOBUF_FINAL;
```

**Comment by gineshidalgo99** [comment]
What are your OS and CUDA versions?

I just modified the Caffe installation to fix a small bug in old compilers. I do not thing this is your case, but you should try again.

If it does not work, you might install Caffe manually (without the sh script). Manual installation steps here:
[https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md](doc/installation.md)

If it does not work either, you might not have some Caffe prerequisites, try installing Caffe by your own with their installation steps:
http://caffe.berkeleyvision.org/installation.html

Please, let me know what the issue was or which option did work for you. Thanks!

**Comment by jmarsico** [comment]
I am on Ubuntu 14.04 and CUDA 8. The new fix didn't change anything. This seems to be a caffe problem with me, as I am unable to build caffe at all because of protobuf issues. Closing as doesn't seem to be relevant to openpose. Thanks.

**Comment by gineshidalgo99** [comment]
OK, I am sorry to hear that.

Maybe completely uninstalling the Protobuf library and then reinstalling again?
[http://caffe.berkeleyvision.org/install_apt.html](http://caffe.berkeleyvision.org/install_apt.html)

Once you are able to fix it, if you could let some details here for people with the same problem we will highly appreciate it! Thanks!

**Comment by yanxp** [comment]
@gineshidalgo99  hello ,I already upgrade protobuf(3.2),but I still meet the problem when sh ./install_caffe_and_openpose.sh. My system is cuda 8.0,Ubuntu 14.04.
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
In file included from ./include/caffe/util/cudnn.hpp:8:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/internal_thread.hpp:4,
                 from src/caffe/internal_thread.cpp:4:
.build_release/src/caffe/proto/caffe.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
make: *** [.build_release/src/caffe/internal_thread.o] Error 1

**Comment by gineshidalgo99** [comment]
Maybe you did not clean the installation first? I.e.
```make clean && cd 3rdparty/caffe/ && make clean```

**Comment by jmarsico** [comment]
able to compile caffe on its own with protobuf 3.0.0 (not using apt version). I had not been doing make clean. `make clean` got it compiling properly. I then modified my Makefile.config (also had to modify Makefile.config.example) to use my version of caffe.

**Comment by gineshidalgo99** [comment]
Perfect! I'll close this issue then.

**Comment by kevinkit** [comment]
@gineshidalgo99 Can you please answer the original question, which version of protobuf should be used?
It was mentioned that it "works" with 3.0.0 but is this the desired version?

**Comment by gineshidalgo99** [comment]
Protobuf is asked by Caffe, so whatever version the specific Caffe version requires.

**Comment by kateiyas** [comment]
I could also get around the `arena.h` error message with protobuf 3.0. 
I used the anaconda libraries: `conda install protobuf==3.0`. Before I had to uninstall a newer version of protobuf from the anaconda installation.
