### ISSUE TITLE
Python Import Error

### ISSUE THREAD

**Issue by ATATC** [CMU-Perceptual-Computing-Lab/openpose#2004]
Im using Windows10 with Python3.8.
I did compile all the stuff and there is `pyopenpose.cp38-win_amd64.pyd` on openpose\build\python\openpose\Release.
The working dictionary can actually reach `...build/python/openpose/Release`, `.../build/x64/Release` and `.../build/bin`.
But it still raised this error.

```
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
DLL load failed while importing pyopenpose: The specified module could not be found.
```

There's only one Python interpreter.
I have also tried replacing the seperator but obviously failed.
I have no idea what to do next to fix the problem.

**Comment by ATATC** [comment]
I've figured out what's wrong. Just copy all the .dll files from `/build/bin` to `/build/python/openpose/Release`.

**Comment by ajfkdk** [comment]
ohhhhhhh,it's working!!!!!!!!!!
