### ISSUE TITLE
String(s) could not be found.

### ISSUE THREAD

**Issue by patodichayan** [CMU-Perceptual-Computing-Lab/openpose#2007]
When I follow the instructions for the usage of experimental models from [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/blob/master/experimental_models/README.md) and I use the flags ``` --model_pose BODY_25B --net_resolution -1x480 ```, I get the following error! 

```
Error:
String(s) could not be found.

Coming from:
- /openpose/src/openpose/pose/poseParameters.cpp:poseBodyPartMapStringToKey():652
- /openpose/src/openpose/pose/poseParameters.cpp:poseBodyPartMapStringToKey():657
- /openpose/src/openpose/pose/poseParameters.cpp:poseBodyPartMapStringToKey():670
- /openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1221
- /openpose/include/openpose/wrapper/wrapper.hpp:start():442
- /openpose/python/openpose/openpose_python.cpp:start():216
```

Is there any step missing in the docs?

**Comment by patodichayan** [comment]
Trying the other easy method of renaming the files, as body_25 and changing the name of the Caffe model too, this error doesn't occur, but I either get [Zero-People-Detected](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/1f1aa9c59fe59c90cca685b724f4f97f76137224/doc/05_faq.md#always-zero-people-detected) , or I get [2.0 as keypoints](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1291) . 

The same code works for other models, default body25, COCO and MPI, suggesting the Body25_B caffe model is corrupted. I tried downloading it multiple times, no change. 

**Download_link:** http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/1_25BSuperModel11FullVGG/body_25b/pose_iter_XXXXXX.caffemodel 

Let me know if there is something that I am missing in the whole process.

**Comment by patodichayan** [comment]
I tried the other way around and renamed the body25 folder/model as body25d and it seems to work. It seems that the models are corrupted.

**Comment by patodichayan** [comment]
Change `Upperneck` [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/ecb07d7479e4d9c896ef6693b46cad6ff9dc9fe1/src/openpose/pose/poseParameters.cpp#L140) to just `Neck`

**Comment by greysou1** [comment]
@patodichayan were you able to get it to finally work? I tried "Change Upperneck here to just Neck " but it still didn't work for me.

**Comment by patodichayan** [comment]
Yes, you also need to cmake the whole thing again with the updated code.

**Comment by patodichayan** [comment]
> @patodichayan were you able to get it to finally work? I tried "Change Upperneck here to just Neck " but it still didn't work for me.

Yes, you also need to cmake the whole thing again with the updated code.
