### ISSUE TITLE
DLL Not Found Error. openpose.dll is missing

### ISSUE THREAD

**Issue by ameliacode** [CMU-Perceptual-Computing-Lab/openpose#2012]
### Issue Summary
I've followed your installation instruction, but faced some issues here..

At first this error occured when I ran a demo inside `openpose\examples\tutorial_api_python`:
 
```
Error: OpenPose library could not be found. Did you enable BUILD_PYTHON in CMake and have this Python script in the right folder? No module named 'pyopenpose'
```

I solved this issue by modifying path inside the code.
After that this came up:

```
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
DLL load failed:
```

So I've looked up the installation again whether there are things that I've missed, and found that I had neither openpose.dll nor exe file inside my `openpose\build\bin` folder

- VERY IMPORTANT NOTE: In order to use OpenPose outside Visual Studio, and assuming you have not unchecked the BUILD_BIN_FOLDER flag in CMake, copy all DLLs from `{build_directory}/bin into the folder where the generated openpose.dll and *.exe demos are,` e.g., {build_directory}x64/Release for the 64-bit release version.

Somehow openpose.dll and demo.exe haven't showed up after pressing generating button from cmake.

Here is a list of dlls that were in `openpose/build/bin folder`:

- boost_date_time-vc142-mt-gd-x64-1_74.dll
- boost_date_time-vc142-mt-x64-1_74.dll
- boost_filesystem-vc142-mt-gd-x64-1_74.dll
- boost_filesystem-vc142-mt-x64-1_74.dll
- boost_system-vc142-mt-gd-x64-1_74.dll
- boost_system-vc142-mt-x64-1_74.dll
- boost_thread-vc142-mt-gd-x64-1_74.dll
- boost_thread-vc142-mt-x64-1_74.dll
- caffe-d.dll
- caffe.dll
- caffehdf5.dll
- caffehdf5_D.dll
- caffehdf5_hl.dll
- caffehdf5_hl_D.dll
- caffezlib1.dll
- caffezlibd1.dll
- cublas64_11.dll
- cublasLt64_11.dll
- cudart64_110.dll
- cudnn64_8.dll
- curand64_10.dll
- gflags.dll
- gflagsd.dll
- glog.dll
- glogd.dll
- libgcc_s_seh-1.dll
- libgfortran-3.dll
- libopenblas.dll
- libquadmath-0.dll
- opencv_videoio_ffmpeg450_64.dll
- opencv_videoio_msmf450_64.dll
- opencv_videoio_msmf450_64d.dll
- opencv_world450.dll
- opencv_world450d.dll
- VCRUNTIME140.dll
- VCRUNTIME140_1.dll

Thanks in advance.

### Errors (if any)

```
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
DLL load failed
```

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Compilation/installation error
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code 

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Window 10 
    - **Operating system version** : Window 10
    - **Release or Debug mode**? : Release
    - Compiler : Visual Studio 2019
4. **Non-default settings**:
    - **3-D Reconstruction module added**?: no
    - Any other custom CMake configuration with respect to the default version? : no
5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : 3.21.2
    - **OpenCV version**: 4.2.0

6. If **GPU mode** issue:
    - **CUDA version** : 11.1
    - **cuDNN version**: 8.1.0 
    - **GPU model**: GeForce GTX 1060 Ti 

8. If **Python** API:
    - **Python version**: 3.7
    - **Numpy version** : 1.20.1

9. If **Windows** system:
    - Compiled library

**Comment by ameliacode** [comment]
Looks like I've solved this problem myself 😅
I just have to copy the whole .dll files from `a build(generated by cmake)/bin`
,also copy openpose.dll and openposedemo.exe from `buildalso generated by cmake)/x64/Release`
and paste them into `build/python/openpose/Release`

Hope this helps to anyone who encountered the same issue like I did

**Comment by shilpavakkayil** [comment]
> Looks like I've solved this problem myself 😅 I just had to copy the whole .dll files from `a build(generated by cmake)/bin` ,also copy openpose.dll and openposedemo.exe from `build(also generated by cmake)/x64/Release` and paste them into `build/python/openpose/Release`
> 
> Hope this helped to anyone who encountered the same issue like I did

This has helped to resolve the error **Error: OpenPose library could not be found. Did you enable BUILD_PYTHON in CMake and have this Python script in the right folder? No module named 'pyopenpose'** . Thank you 😊

**Comment by MingZi-Ye** [comment]
It does help the error Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
DLL load failed:
