### ISSUE TITLE
protobuf 3.3 not support?

### ISSUE THREAD

**Issue by xfei6868** [CMU-Perceptual-Computing-Lab/openpose#202]
### Executed command (if any)
sudo ./build/examples/openpose/openpose.bin --logging_level 0 --video ~/github/nnStudy/opencv/zhaoliying.mp4 

### OpenPose output (if any)

[libprotobuf FATAL google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-ui6vjS/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-ui6vjS/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)

### Type of issue
- Execution error

### Your system configuration
**Operating system**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**CUDA version**:
CUDA Version 8.0.61
CUDA Patch Version 8.0.61.2

**cuDNN version**:
cuDNN6.0
**GPU model** (`nvidia-smi` in Ubuntu):
 NVIDIA-SMI 375.66                 Driver Version: 375.66  

**Caffe version**: custom version.
caffe newest

**OpenCV version**:
 OpenCV 3.X.
Generation mode (only for Ubuntu):
 Makefile + Makefile.config (default, Ubuntu) 
Compiler (`gcc --version` in Ubuntu):
gcc (GCC) 4.8.5

**Comment by gineshidalgo99** [comment]
Hi, this error is related with Caffe (we do not directly use Protobuf, but Caffe does). So you will better find solutions in their forums if you do not wanna use the default Protobuf version Caffe uses.

In addition, sometimes these errors are fixed when using OpenCV 2.4 (since 3.X have some conflicts with Caffe).
