### ISSUE TITLE
Update repo url

### ISSUE THREAD

**Issue by MatthijsBurgh** [CMU-Perceptual-Computing-Lab/openpose#2038]
Since https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/1871, there is no need for the long url of the repo.

It can be reduced to `https://cmu-perceptual-computing-lab.github.io/openpose`.

**Comment by gineshidalgo99** [comment]
True, updated in the latest commit, thanks!

**Comment by MatthijsBurgh** [comment]
I was also talking about the url on the top right corner on GitHub.

**Comment by gineshidalgo99** [comment]
True, also updated!
