### ISSUE TITLE
Help Wanted - Create/Train new Pose Model with different joint setup

### ISSUE THREAD

**Issue by paulranico** [CMU-Perceptual-Computing-Lab/openpose#204]
### Issue summary
Is it possible to create a new model with different joint set up. We would like to add joints to the body, we're currently going through the training repo and trying to find out how to do this. If there's anyone  there who could point us to the right direction.

### Type of issue
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
If you have the data yes it is possible. We are focused in the testing part, so we will not provide support at the moment for the training part on this repo, I am sorry but we have to focus our efforts given the few people we are. 😞
