### ISSUE TITLE
hand detectors question!

### ISSUE THREAD

**Issue by chenfsjz** [CMU-Perceptual-Computing-Lab/openpose#206]
Hi,when I run the model with camera,I found that the detector failed to detect the hands when the shoulder and elbow are not appear in the images. I want to now if it can detect the hand independent the shoulder and elbow?

Thank you!

**Comment by gineshidalgo99** [comment]
Shoulder and elbow are needed at the moment.

The only way is if you had your own hand detector, then you could apply our hand keypoint detector in the library API.

This problem is expected to be solved in the following 3-6 months.

**Comment by liaowang0125** [comment]
I find "Hand Keypoint Detection in Single Images using Multiview Bootstrapping",don't need shoulder and elbow to detect hands.What is the difference now? @gineshidalgo99

**Comment by gineshidalgo99** [comment]
@liaowang0125  I am not the author of the paper itself, but (I think) they either used ground truth hand location or they ran the detector in the whole image for that. The paper is about hand keypoint detection, not about hand detection.

**Comment by liaowang0125** [comment]
Ok,and will you release a python version about hand keypoints detection? Like body pose estimation.

**Comment by gineshidalgo99** [comment]
We are currently working on the wrapper. It should be out in a few weeks, but at the moment is still unfinished.

Please, check the repo every 1-2 weeks. Once it is released, it will be announced in the Latest News section of the README.md, so it's easy for you to know if it's released.

**Comment by liaowang0125** [comment]
Ok,thanks for your reply.

**Comment by daisyl0** [comment]
I have my own hand detector,would you please give a hint about how to apply the hand keypoint detector ?  @gineshidalgo99

**Comment by gineshidalgo99** [comment]
@daisyl0 

Hi, I am sorry there is no clear documentation about it, but the easiest solution will be to forget about the OpenPose demo and wrapper, and instead use the https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/hand/handExtractor.hpp class with the output of your hand detector. 

The elegant solution if you wanna use the whole OpenPose framework is to copy wrapper.hpp as e.g. wrapperHand.hpp, and change our HandDetector class by your custom HandDetector class. (If you wanna omit the Pose keypoint detection, you might have to delete it from that custom wrapper too).

Best

**Comment by daisyl0** [comment]
thanks a lot. I'll give it a go. :)

**Comment by gineshidalgo99** [comment]
@daisyl0 
Added some doc in the README in https://github.com/CMU-Perceptual-Computing-Lab/openpose#standalone-face-or-hand-keypoint-detector

**Comment by EthanPen** [comment]
@daisyl0 Hi ,  I have noticed that you had solved the problem of hand detection with openpose hand keypoint detector , it's impressive man.  I'm very interested in hand detection , would you mind to guide us how to do it  if you are available?    thanks a lot  
email: ethan.penx@gmail.com

**Comment by vvirag** [comment]
@gineshidalgo99 
> Shoulder and elbow are needed at the moment.
> The only way is if you had your own hand detector, then you could apply our hand keypoint detector in the library API.
> This problem is expected to be solved in the following 3-6 months.

Any update update on this?

**Comment by gineshidalgo99** [comment]
Not yet, it's going slower than we expected. It'll still need several more months.

**Comment by Narcissuscyn** [comment]
Thanks for your contributions and advices @gineshidalgo99
I wonder if the problem has been solved?

**Comment by pjain03** [comment]
Is there any functioning example code available for standalone hand keypoint detection?
Thanks for the help @gineshidalgo99!

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/standalone_face_or_hand_keypoint_detector.md

**Comment by pjain03** [comment]
I saw that. Sorry I didn't clarify - I meant is there any reference implementation for a standalone hand/face detector?

**Comment by gineshidalgo99** [comment]
Unfortunately no, there is not

**Comment by JasOlean** [comment]
@daisyl0  After using your own hand detector, is your hand-keypoints detection is ok? please can you giude me your experience?

**Comment by MLsmaller** [comment]
> thanks a lot. I'll give it a go. :)

Hi , I noticed that you are also studying hand detector of openpose.I've been learning about this lately.
I don't know how to apply the hand keypoint detector of openpose  to written hand detector. Could you please give me some guidance.Thanks a lot.
email:ccvey789@gmail.com

**Comment by asierras** [comment]
Hello, thank you for the great work.

Has this feature been implemented yet?

**Comment by gineshidalgo99** [comment]
If you have your own hand detector (as in a bounding box detector), then you can check the examples to see how to link it to our hand pose detector.
