### ISSUE TITLE
rendering assumes that numberPeople <= POSE_MAX_PEOPLE = 127

### ISSUE THREAD

**Issue by kexante** [CMU-Perceptual-Computing-Lab/openpose#2061]
### Issue Summary
How to avoid this error? Can OpenPose detect an image with more than 127 people?

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)

Error:
Rendering assumes that numberPeople <= POSE_MAX_PEOPLE = 127

### Errors (if any)

Error:
Rendering assumes that numberPeople <= POSE_MAX_PEOPLE = 127

### Type of Issue

- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** Ubuntu
    - **Operating system version** Ubuntu 18.04
    - **Release or Debug mode**? release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 7.5.0, ... (Ubuntu);
    - 
4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on the [profiling documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/06_maximizing_openpose_speed.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
OpenPose results will be very noise if the image has >127 people, so I'd not recommend to change the hard-coded 127 in the code.

Instead, if you do have >127 people on the image, I'd recommend to split the image in chunks (e.g., 4 subimages?) and run OpenPose individually on each iamge or something like that, as OpenPose has not been trained for such images.
