### ISSUE TITLE
Sub-links in documentation give 404

### ISSUE THREAD

**Issue by flacle** [CMU-Perceptual-Computing-Lab/openpose#2069]
### Issue Summary
Sub-links in the section https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#additional-settings-optional lead to a 404 as the link is incorrect.

For example, this:
```
[CMake Command Line Configuration (Ubuntu Only)](2_advanced_settings.md#cmake-command-line-configuration-ubuntu-only)
```
Should instead be:
```
[CMake Command Line Configuration (Ubuntu Only)](2_additional_settings.md#cmake-command-line-configuration-ubuntu-only)
```

### Errors (if any)
GitHub 404

### Type of Issue
- Enhancement / offering possible extensions / pull request / etc

**Comment by gineshidalgo99** [comment]
Thanks for the fix!
