### ISSUE TITLE
[help] Windows Complie error

### ISSUE THREAD

**Issue by dasheyuan** [CMU-Perceptual-Computing-Lab/openpose#207]
I follow the setups in /doc/installation.md#installation---library，
However，in the setup ```Compile it and run it with F5 or the green play icon.```，
some errors come out like these:
anything  I should deploy  in VS?
```
Error	C2447	'{': missing function header (old-style formal list?)	OpenPose	D:\openpose-master\include\openpose\thread\priorityQueue.hpp	36
```
![default](https://user-images.githubusercontent.com/8971893/29346908-3847dd2a-827b-11e7-8eb2-3b00c989d4f3.PNG)

**Comment by dasheyuan** [comment]
Solved：
'｛'->'('

**Comment by gineshidalgo99** [comment]
Thanks for the feed back!
