### ISSUE TITLE
Recreating heat-maps of pose model via Caffe - help wanted

### ISSUE THREAD

**Issue by tamarev** [CMU-Perceptual-Computing-Lab/openpose#208]
hello!
I am trying to recreate heat-maps (network output only) using Caffe, but I am getting a blurry image that is nowhere near the heat-maps created by the demo. What post processing do you do to get them? (for heat maps only, not skeletons). Also, I cannot find the code that uses the caffemodel...

I am using `models/pose/coco/pose_deploy_linevec.prototxt` + `models/pose/coco/pose_iter_440000.caffemodel`
running with pycaffe

```
    coco_model = os.path.join(openpose_home,'models/pose/coco')
    net = caffe.Net(os.path.join(coco_model,'pose_deploy_linevec.prototxt'),os.path.join(coco_model,'pose_iter_440000.caffemodel'), caffe.TEST)
    net.blobs['image'].reshape(1, 3, im.shape[0], im.shape[1])
    transformer = caffe.io.Transformer({'image': net.blobs['image'].data.shape})
    transformer.set_transpose('image', (2,0,1))
    transformer.set_channel_swap('image', (2,1,0))
    transformer.set_raw_scale('image', 255.0)
    net.blobs['image'].data[...] = transformer.preprocess('image', im)
    out = net.forward()
    for i in range(18):
       plt.figure()
       plt.imshow(out['net_output'][0][i])
   plr.show()
```

Thanks!

**Comment by gineshidalgo99** [comment]
Check the paper and training code for details about that.
https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
