### ISSUE TITLE
Execution error when saving JSON and no people is detected

### ISSUE THREAD

**Issue by kidapu** [CMU-Perceptual-Computing-Lab/openpose#21]
### Type of issue
- Execution error

### Executed command (if any)
I run following command.
```
./build/examples/openpose/rtpose.bin --video $movepath  --write_pose json/ --num_gpu 2
```

### OpenPose output (if any)

When the scene of the movie gradually went fade to white, following error has occured. I tried same movie 3 time. Same error has occured 3 time. 
```
Starting pose estimation demo.
Gtk-Message: Failed to load module "canberra-gtk-module"
Starting thread(s)
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Array<T>: cv::Mat functions only valid for T types defined by OpenCV: unsigned char, signed char, int, float & double

Coming from:
- src/openpose/core/array.cpp:getConstCvMat():328
- src/openpose/core/array.cpp:getConstCvMat():334
- src/openpose/filestream/poseSaver.cpp:savePoseKeyPoints():39
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueInOut.hpp:work():87
- ./include/openpose/thread/thread.hpp:threadFunction():206

Aborted (core dumped)
```

And I analyzed core by gdb.
```
# gdb ./build/examples/openpose/rtpose.bin core.rtpose.bin.2257
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/examples/openpose/rtpose.bin...(no debugging symbols found)...done.
[New LWP 2284]
[New LWP 2257]
[New LWP 2275]
[New LWP 2283]
[New LWP 2282]
[New LWP 2259]
[New LWP 2260]
[New LWP 2258]
[New LWP 2279]
[New LWP 2274]
[New LWP 2270]
[New LWP 2272]
[New LWP 2285]
[New LWP 2280]
[New LWP 2277]
[New LWP 2261]
[New LWP 2265]
[New LWP 2278]
[New LWP 2266]
[New LWP 2267]
[New LWP 2276]
[New LWP 2268]
[New LWP 2269]
[New LWP 2263]
[New LWP 2286]
[New LWP 2262]
[New LWP 2264]
[New LWP 2273]
[New LWP 2271]
[New LWP 2281]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./build/examples/openpose/rtpose.bin --video sozai/notall.mp4 --write_pose json'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f2b557d5428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f2adb2fd700 (LWP 2284))]
(gdb) 
```

And the movie is below. The timing of the error is 1:44.
https://www.youtube.com/watch?v=iZuNdzv3TcE#t=104

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):  16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0.61
**cuDNN version**: 5.1.10.
**GPU model** (`nvidia-smi`): nvidia-tesla  driver version :375.51
Compiler (`gcc --version` on Ubuntu):5.4.0

**Comment by gineshidalgo99** [comment]
I remember this bug (it is not the fading to white, but the 1st instant in which no people appear), but it was solved at some point.

Can you `git pull` or re-download and re-compile the library? (Note the change rtpose.bin --> openpose.bin):
`make clean && cd 3rdparty/caffe && make clean && make distribute -j8 && cd ../.. && make all -j8`

Let me know if it still fails!

**Comment by kidapu** [comment]
Mmm.. I did `git pull` and re-compile openpose.
And check commit log.

```
# git log --oneline
f4dd473 Fixed bug: disable_blending not working
f3454e3 Updated Caffe & more demo doc
...
```

And I run following command. But same error has occured.
```
# ./build/examples/openpose/openpose.bin --video sozai/notall2.mp4 --write_pose j
Starting pose estimation demo.
Gtk-Message: Failed to load module "canberra-gtk-module"
Starting thread(s)
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Array<T>: cv::Mat functions only valid for T types defined by OpenCV: unsigned char, signed char, int, float & double

Coming from:
- src/openpose/core/array.cpp:getConstCvMat():328
- src/openpose/core/array.cpp:getConstCvMat():334
- src/openpose/filestream/poseSaver.cpp:savePoseKeyPoints():39
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueInOut.hpp:work():87
- ./include/openpose/thread/thread.hpp:threadFunction():206

Aborted (core dumped)
```

```
# gdb ./build/examples/openpose/openpose.bin core.openpose.bin.13594
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/examples/openpose/openpose.bin...(no debugging symbols found)...done.
[New LWP 13621]
[New LWP 13595]
[New LWP 13608]
[New LWP 13594]
[New LWP 13620]
[New LWP 13598]
[New LWP 13617]
[New LWP 13619]
[New LWP 13618]
[New LWP 13602]
[New LWP 13596]
[New LWP 13614]
[New LWP 13613]
[New LWP 13616]
[New LWP 13610]
[New LWP 13605]
[New LWP 13606]
[New LWP 13597]
[New LWP 13615]
[New LWP 13603]
[New LWP 13609]
[New LWP 13622]
[New LWP 13601]
[New LWP 13604]
[New LWP 13612]
[New LWP 13607]
[New LWP 13623]
[New LWP 13600]
[New LWP 13599]
[New LWP 13611]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./build/examples/openpose/openpose.bin --video sozai/notall2.mp4 --write_pose j'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f43dff35428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f436dbf7700 (LWP 13621))]
```

**Comment by gineshidalgo99** [comment]
OK then it is something else. I tried that video and it worked for me. I few thoughts:
1. Could you convert that video to standard avi format? Or can you send me a link (Dropbox, Google Drive, etc.) to your exact video? Maybe it is some kind of unsupported codecs.
2. Which version of OpenCV are you using? The one from `apt-get` or a custom build?
3. Could you try on a different video where there is no people on the scene? So I can to know if the error is when no people is there or if it is just this video.
Sorry for any inconveniences!

**Comment by kidapu** [comment]
@gineshidalgo99 
These days I can't reproduce this issue. 
Sorry, I might have mistaken something maybe m(_ _)m

**Comment by muumintroll** [comment]
I received the same error when using the wrapper. I wrote a user-input class that reads image paths and crop positions from a csv file and applies the given cropping to the image. It then resizes the image into 656*358. The image is then put into an  input-datum. 
I followed the asynchronous user code example.
In particular the cropped and resized image is a relatively low-resolution of a pedestrian walking away from the camera, so I can imagine that the issue may be related to the network not a person in the image. Is there something that should be added into the user-input class to avoid this runtime error? It occurs in  function opWrapper.waitAndEmplace(datumToProcess). Could I simply assume that this means that no people were detected?

The error is not present in the demo.
OpenCV version: 3.1.0 (installed from source)
OpenPose: commit  cc4082b

**Your system configuration**
Operating system (lsb_release -a on Ubuntu): 14.04.5 LTS
CUDA version (cat /usr/local/cuda/version.txt in most cases): 7.5.18
cuDNN version: 5.1.10.
GPU model (nvidia-smi): (Titan Z) 375.39 
Compiler (gcc --version on Ubuntu): 5.1.3

**Comment by gineshidalgo99** [comment]
Good catch! It actually happened when Array<T> was empty (e.g. if no keypoints are detected). Fixed in my last commit, it will give you an empty cv::Mat if Array.empty() == true. (I did not handled this situation before).

Please, post again if the error still persists.

**Comment by rainforest1** [comment]
This same error happens for --write_keypoint for yml format as well. When there is no person detected in the image, the error "Aborted. (core dumped)" happens.

OpenCV Error: Bad argument (Unknown object) in cvWrite, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp, line 5015

Error:
/build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:5015: error: (-5) Unknown object in function cvWrite


Coming from:
- src/openpose/filestream/fileStream.cpp:saveData():91
- src/openpose/filestream/keypointSaver.cpp:saveKeypoints():38
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueIn.hpp:work():64
- ./include/openpose/thread/thread.hpp:threadFunction():206
- ./include/openpose/thread/thread.hpp:exec():132
- ./include/openpose/thread/threadManager.hpp:exec():183
- ./include/openpose/wrapper/wrapper.hpp:exec():856
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
/build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:5015: error: (-5) Unknown object in function cvWrite


Coming from:
- src/openpose/filestream/fileStream.cpp:saveData():91
- src/openpose/filestream/keypointSaver.cpp:saveKeypoints():38
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueIn.hpp:work():64
- ./include/openpose/thread/thread.hpp:threadFunction():206
- ./include/openpose/thread/thread.hpp:exec():132
- ./include/openpose/thread/threadManager.hpp:exec():183
- ./include/openpose/wrapper/wrapper.hpp:exec():856

Aborted (core dumped)

**Comment by nikoong** [comment]
@gineshidalgo99 
Hello! I met the same error.when I run this command:
 ./build/examples/openpose/openpose.bin -image_dir /path/to/image/  -write_pose /path/to/save/ -write_pose_format xml -scale_mode 0 -no_display ture


Error:
Array<T>: cv::Mat functions only valid for T types defined by OpenCV: unsigned char, signed char, int, float & double

Coming from:
- src/openpose/core/array.cpp:getConstCvMat():328
- src/openpose/core/array.cpp:getConstCvMat():334
- src/openpose/filestream/poseSaver.cpp:savePoseKeyPoints():39
- ./include/openpose/filestream/wPoseSaver.hpp:workConsumer():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueInOut.hpp:work():87
- ./include/openpose/thread/thread.hpp:threadFunction():206

Aborted (core dumped)



It is because  in some images the demo can’t detect people. But I don't want that the demo to be aborted. I hope it can still run ,and output a xml say there is nobady in the image. How should I change the demo?

**Comment by gineshidalgo99** [comment]
@nikoong Please, try `write_pose_json` and let me know if it works instead. Thanks

**Comment by nikoong** [comment]
@gineshidalgo99  Thank you！It works.
