### ISSUE TITLE
Rotated images don't capture poses

### ISSUE THREAD

**Issue by GeorgianaPetria** [CMU-Perceptual-Computing-Lab/openpose#212]
I noticed there's a huge difference between applying open pose on a rotated image vs the original image. I'm either getting a low confidence or not getting any pose at all if a person is laying on the floor or the if the pose is somehow rotated.

Was the library not trained with the poses rotated?

**Comment by gineshidalgo99** [comment]
At the moment, it is trained with rotations in the range +-45 degrees. It will work with rotations up to around 60-80 degrees.

We thought training with greater rotations might deteriorate non rotated results (the most common).
