### ISSUE TITLE
CMake configure error 

### ISSUE THREAD

**Issue by DTSKT** [CMU-Perceptual-Computing-Lab/openpose#2136]
Hi, im trying to instal openpose in mi ubunto installation (18.04). I've followed up all the prerequisites an index steps, and all went so far. Right now I'm at the index Cmake configuration, at the third point, where you have to ress the `Configure` button and keep the generator in `Unix Makefiles`. Well, it throws an error and doesn't finish the config. I've inluded the CMakeError.log, but basically at the src.c main function throws: 

src.c:(.text+0x3e): reference to `pthread_create' undefined
src.c:(.text+0x4a): reference to `pthread_detach' undefined
src.c:(.text+0x56): reference to `pthread_cancel' undefined
src.c:(.text+0x67): reference to `pthread_join' undefined
src.c:(.text+0x7b): reference to `pthread_atfork' undefined 

I'm from spain, so sorry if some of the text at the error log is in spanish. I'd be so pleased if you could help with that, as I'm a robotics student at the university of alicante, and need openpose for a proyect related to computer vision involving realtime body tracking.

Thanks :D

**Comment by pfeducode** [comment]
> 这是输出和错误日志

have you solved this problem?

**Comment by zhengliu147** [comment]
I have the same issue. Did you fix it? Thanks.

**Comment by DTSKT** [comment]
> I have the same issue. Did you fix it? Thanks.

I couldn't fix it at all. Al last I installed it on windows, following all the steps needed. I works very well as far as you have enough VRAM

**Comment by pfeducode** [comment]
> > 我有同样的问题。你修好了吗？谢谢。
> 
> 我根本无法修复它。最后我按照所有需要的步骤将它安装在 Windows 上。只要你有足够的 VRAM，我就能很好地工作

i do install it on windows,  it works well
