### ISSUE TITLE
what is your datasets of your face keypoints model

### ISSUE THREAD

**Issue by mxmxlwlw** [CMU-Perceptual-Computing-Lab/openpose#215]
Hi,
    What is your datasets of your face keypoints model?

**Comment by gineshidalgo99** [comment]
Several datasets were initially downloaded but at the end no all of them were used. I'll try to find which ones we finally used after I have some free time. Thanks.

**Comment by mxmxlwlw** [comment]
Thank you, I'm waiting for your reply. Please be quick. If you don't have much time, please give me as much information as you can. I would be appreciate.

**Comment by gineshidalgo99** [comment]
Some basic and traditional face datasets were used (any free one you can find), and then to make it quite robust to extreme  positions, we used the our own robust data, which will be eventually released (that might still take several months), but we are working on it:
http://domedb.perception.cs.cmu.edu/

It follows the idea of the hands paper from the README.md. Sorry for the late answer!

**Comment by Shreeyak** [comment]
Hey, thanks for everything! I'm simply curious, why would it take months to
release the data set? Do you do some kind of processing/standardization on
it before release, or to fine tune it or something else?

**Comment by gineshidalgo99** [comment]
A clear ground truth data structure is needed, as well as a toolbox to read/visualize the data, some licensing issues to be finished, etc.

**Comment by mxmxlwlw** [comment]
Can you provide a extreme small model for face keypoints detection? The model seems still too slow, especially for the base network.

**Comment by gineshidalgo99** [comment]
I'm sorry, at the moment that is our only model. If you need speed, I guess other non-DL approaches (e.g. IntraFace) might suit you better.

Alternatively, you can create a OpenCV face detector, and just run our face keypoint detector on top of that instead of running our body keypoint detector as face detector. (feel free to pull request that demo if you create it!)
