### ISSUE TITLE
Will the 3D reconstruction demo work with only 2 RGB cameras?

### ISSUE THREAD

**Issue by fengsky401** [CMU-Perceptual-Computing-Lab/openpose#217]
In Ubuntu version, will the 3d reconstruction demo work with only 2 RGB cameras by removing one camera parameters from cameraParameters.hpp? Anything else should I modify?
What about only 1 RGB camera?  Will the 3D reconstruction work?

**Comment by melhk** [comment]
I have exactly the same questions, could anyone help?

**Comment by gineshidalgo99** [comment]
Some other post already explained how to do this (not remember which one).

**Comment by alexluleme** [comment]
Hey @fengsky401, have you made the 3D reconstruction demo work with the 2 RGB cameras based on the answer of #235 ?
