### ISSUE TITLE
Does OpenPose performance (in FPS) scale with number of GPU cores?

### ISSUE THREAD

**Issue by paloskar** [CMU-Perceptual-Computing-Lab/openpose#218]
Hello,

I was wondering how does the performance of your algorithm (in FPS) scale with the number of GPU cores? 

I am running the OpenPoseDemo on an Intel i7-7700, 16Gb RAM, GeForce GTX 1060 6Gb, Windows 10 machine compiled in VS2015 in release mode and get about 5 FPS when detecting body only (no face, no hands). Could you give me any kind of estimate of how the FPS would improve if I invested into a more expensive GPU? 

For example the GTX 1080 has double the cores of the GTX 1060. Could I expect a nearly double performance in terms of FPS? How about a Titan compared to GTX 1080 (or any other card you used)? It would be great to hear any elaboration on this, which could help the community make decisions about purchasing more powerful equipment to run your algorithms.

Thank you for your great work,

Oskar

### Type of issue
- Question

**Comment by gineshidalgo99** [comment]
There is a GPU benchmark in the README.

And yeah, 2 or 3 GPUs should speed up ~2x or ~3x the speed.
