### ISSUE TITLE
How to use the pose model on its own?

### ISSUE THREAD

**Issue by spurra** [CMU-Perceptual-Computing-Lab/openpose#219]
Inspired by this question https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/206 I'd like to implement a hand detector which interfaces with the hand pose model directly. However, per this question https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/163 it is not sufficient to load the model found in the folder models/hand/. Is there a straightforward way on how to interface directly with the hand pose model? The docs giving the library overview only discuss human pose detection.

**Comment by gineshidalgo99** [comment]
Added some doc in the README in https://github.com/CMU-Perceptual-Computing-Lab/openpose#standalone-face-or-hand-keypoint-detector

(Answer duplicated from last post in #206)
