### ISSUE TITLE
Maybe the submodule of pybind11 is too old?

### ISSUE THREAD

**Issue by p2er1n** [CMU-Perceptual-Computing-Lab/openpose#2199]
### Issue Summary

When I built the pyopenpose in Visual Studio Community 2022, there was an error about pybind11 ocurred.
It is not important about what is the detail about the error, because it's the pybind11's fault.

And I found that the version of pybind11 submodule is too old, its latest commit was pushed in 2019 while the python 3.11 was released in 2020.

But the bug had been fixed. See [Python 3.11 _frame issue #4333](https://github.com/pybind/pybind11/discussions/4333sort=top)

So, how about update the version of pybind11 so that it can be compatible with the python3.11?

### Errors (if any)

It's not important. It's not openpose's fault.

### Type of Issue
- Compilation/installation error
- Enhancement / offering possible extensions / pull request / etc

### Your System Configuration
2. **OpenPose version**:    Latest Github code.

4. **General configuration**:
    - **Installation mode**:   CMake-gui (Windows)
    - **Operating system** :   Windows 11
    - **Operating system version** :   Windows 11
    - **Release or Debug mode**?:   release
    - Compiler :   VS Community 2022

5. **Non-default settings**:
    - **3-D Reconstruction module added**? :  no
    - Any other custom CMake configuration with respect to the default version? :  no

9. If **Python** API:
    - **Python version**:  **3.11** (Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32) 
    - **Numpy version** :   1.24.3

10. If **Windows** system:
    - Portable demo or compiled library?   compiled library

**Comment by oahzuw** [comment]
‪cmake .. -DPYTHON_EXECUTABLE="you python.exe path"   can pass.

**Comment by Mwni** [comment]
You can just drop the latest pybind11 repo into `3rdparty/pybind11` and it will work.
