### ISSUE TITLE
VideoCapture (video) could not be opened for path: 'examples/media/video.avi'.

### ISSUE THREAD

**Issue by sainisanjay** [CMU-Perceptual-Computing-Lab/openpose#220]
> Starting pose estimation demo.
> Error:
> VideoCapture (video) could not be opened for path: 'examples/media/video.avi'.
> 
> Coming from:
> - src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():32
> - src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():36
> - src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():133
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  
> Error:
> VideoCapture (video) could not be opened for path: 'examples/media/video.avi'.
> 
> Coming from:
> - src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():32
> - src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():36
> - src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():133
> 
> Aborted (core dumped)

I have tried #41 as well #17  but nothing is works.....I have install boost library freshly and also i rebuild my opencv 3.1.0. 

I can see in media folder all video file is available:
ls examples/media/
```
COCO_val2014_000000000192.jpg  COCO_val2014_000000000338.jpg  COCO_val2014_000000000428.jpg  COCO_val2014_000000000544.jpg  video.avi
COCO_val2014_000000000241.jpg  COCO_val2014_000000000357.jpg  COCO_val2014_000000000459.jpg  COCO_val2014_000000000564.jpg
COCO_val2014_000000000257.jpg  COCO_val2014_000000000360.jpg  COCO_val2014_000000000474.jpg  COCO_val2014_000000000569.jpg
COCO_val2014_000000000294.jpg  COCO_val2014_000000000395.jpg  COCO_val2014_000000000488.jpg  COCO_val2014_000000000589.jpg
COCO_val2014_000000000328.jpg  COCO_val2014_000000000415.jpg  COCO_val2014_000000000536.jpg  COCO_val2014_000000000623.jpg
```

**Comment by gineshidalgo99** [comment]
Sorry, night time here at that moment.

Could I know what was the problem? (To help others in the future)

**Comment by sainisanjay** [comment]
@gineshidalgo99 , Thanks, actually i build with Anaconda which was not linked with OpenCV libraries. I just removed the anaconda and build with actual python package/libraries. It work perfectly.

**Comment by gineshidalgo99** [comment]
OK thanks!

**Comment by liaowang0125** [comment]
I find the generate video is much larger than origin video.My origin video is 3MB,and result video is 37MB.
./build/examples/openpose/openpose.bin --video examples/mypic/2.mp4 --write_video output/result2.avi  --no_display --hand --render_pose 0 --hand_render 1

**Comment by gineshidalgo99** [comment]
@liaowang0125  That is just AVI format (no advanced compression techniques so it's playable in any video player but bigger size). If you want small videos, I recommend you to save the png frames, and then use `ffmpeg` for advance codec compression.
