### ISSUE TITLE
Not works with opencv 3.3.0-rc

### ISSUE THREAD

**Issue by ricther** [CMU-Perceptual-Computing-Lab/openpose#221]
### Posting rules
1. **Add** the **system configuration (all of it!), command and output** if you have some kind of error or performance question.
2. **No duplicated** posts.
3. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
4. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
5. Only English comments.
Issues/comments that do not follow this will be **ignored or removed** with no further clarification.

Issue summary
The openpose will not work with opencv 3.3.0-rc. when run the demo openpose, will raise malloc error.
The problem to casue this is the opencv 3.3.0-rc cv::mat **add a constructor** with **initilizer list** in file  opencv2/core/mat.inl.hpp:581.  and in openpose file src/openpose/utilities/openCv.cpp:34. where use initilizer list to initilize the **cv::mat**.  
so just change the code from 
cvMat = cv::Mat{resolutionSize.y, resolutionSize.x, CV_8UC3};
to
cvMat = cv::Mat(resolutionSize.y, resolutionSize.x, CV_8UC3);
can sovle this problem

### Executed command (if any)
Note: add `--logging_level 0` to get higher debug information.

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** (`Centos 7):Centos 7
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):CUDA Version 8.0.61
**cuDNN version**: 5.1.3
**GPU model** (`nvidia-smi` in Ubuntu):Tesla P40  
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: opencv 3.3.0-rc
Generation mode (only for Ubuntu): Makefile + Makefile.config 
Compiler (`gcc --version` in Ubuntu): 4.8.5

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back!

It has been solved. Let me know if it works now.

**Comment by ricther** [comment]
Thank you. It works for me now:)
