### ISSUE TITLE
how to use setWorkerOutput (user-define extra Worker )

### ISSUE THREAD

**Issue by jinnen** [CMU-Perceptual-Computing-Lab/openpose#222]
### Issue summary
i want to use setWorkerOutput func to initailze mUserOutputWs
(i tried op::wrapper::setWorkerOutput(mUserOutputWs,true , opwrapper::setWorkOutput ... etc) ... but it bring error TT)
how to use setWorkeroutput! please help me

**Comment by gineshidalgo99** [comment]
See the wrapper tutorial examples for details about it. Thanks
