### ISSUE TITLE
Model Download Issue

### ISSUE THREAD

**Issue by bluehyena** [CMU-Perceptual-Computing-Lab/openpose#2229]
When I try to download the model ERR_CONNECTION_TIMED_OUT error occur. Also in getModels.bat. What should I do? Is there any problem in server?

**Comment by neoglez** [comment]
The same here. Double clicking `getBaseModels.bat` results in requesting an apparently dead server.
![error](https://github.com/CMU-Perceptual-Computing-Lab/openpose/assets/3646037/ed02784c-cd4c-42ee-8583-097bf95055f1)

**Comment by bluehyena** [comment]
@neoglez Thank you so much! and I hope the server is back to normal.

**Comment by alvaro-budria** [comment]
> Downloading the files manually from these two links provided in #1602 worked like a charm.
> 
> https://drive.google.com/file/d/1mqPEnqCk5bLMZ3XnfvxA4Dao7pj0TErr/view?usp=sharing https://drive.google.com/file/d/1QCSxJZpnWvM00hx49CJ2zky7PWGzpcEh/view?usp=sharing

Where did you put the files?

**Comment by SashaEm** [comment]
> > Downloading the files manually from these two links provided in #1602 worked like a charm.
> > https://drive.google.com/file/d/1mqPEnqCk5bLMZ3XnfvxA4Dao7pj0TErr/view?usp=sharing https://drive.google.com/file/d/1QCSxJZpnWvM00hx49CJ2zky7PWGzpcEh/view?usp=sharing
> 
> Where did you put the files?

Did you manage to figure this out? I'm confused by the fact that the OpenPoseDemo.exe is looking for .caffemodel files, but there aren't any
