### ISSUE TITLE
Integrating with iOS CoreML: how to read output multi-array

### ISSUE THREAD

**Issue by tangert** [CMU-Perceptual-Computing-Lab/openpose#224]
### Issue summary
When I try to process images in an iOS app using CoreML, the most I get from the result is a multi-array but cannot read the data. This is the result: "MultiArray : Double 1 x 1 x 44 x 28 x 28 array." Anybody have some insight? 

### OpenPose output (if any)
MultiArray : Double 1 x 1 x 44 x 28 x 28 array

### Type of issue
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

**Comment by snowzurfer** [comment]
Hi, have you made any progress on this?

**Comment by yosun** [comment]
Reactivate?
