### ISSUE TITLE
caffe provided contains error?

### ISSUE THREAD

**Issue by 1uan-yuan** [CMU-Perceptual-Computing-Lab/openpose#2268]
### Issue Summary
caffe.dll is either not designed to run on Windows or it contains an error

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

(In openpose dir) 
build\x64\Release\OpenPoseDemo.exe --image_dir {one of the pictures in the example/media directory}

### Errors (if any)
caffe.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status: 0xc000007b

I followed the steps that was provided. And I downloaded the 3rd party libraries. The compilation and built was correct. Following the tutorial, I also copied the dll files into the correct directories. However, when I used the above command, the error message popped out. I wonder if it is possible that the provided caffe version does not fit in the current software. 

I used caffe_16_2020_11_14, caffe3rdparty_16_2020_11_14, opencv450_v15_2020_11_18 in the provided package in the above link.

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Execution error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?
    
I used CMake GUI to configure and used Visual Studio 16 2019 to build the sln file on Win10 system. 

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? 
          I used the caffe contained in the post (https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602).
    - **CMake version** (`cmake --version` in Ubuntu):
          cmake version 3.250-rc2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on the [profiling documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/06_maximizing_openpose_speed.md#profiling-speed).

**Comment by 1uan-yuan** [comment]
I think I made a quite simple mistake...

I forgot to put myself in the root directory of this project. This problem is solved.

**Comment by MAXMAXMAX555** [comment]
@1uan-yuan if you succeded in building openpose from source, can you provide your setup: visual studio version, cmake version, cuda and cuddn versions, caffe and 3rdparty did you use? I have troubles with building vs project.
