### ISSUE TITLE
Run successfully, but could not get face/hand frame

### ISSUE THREAD

**Issue by 1uan-yuan** [CMU-Perceptual-Computing-Lab/openpose#2269]
### Issue Summary
I could run OpenPose successfully, but I could not get the frame of hand and face correctly. 

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand
bin\OpenPoseDemo.exe --image_dir examples\media\ --face --hand

### OpenPose Output (if any)

C:\......\openpose_source>bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 9.092402 seconds.

C:\......\openpose_source>bin\OpenPoseDemo.exe --image_dir examples\media\ --face --hand
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 3.230856 seconds.

### Errors (if any)

I could not get any of the data. Even though the program runs correctly, the frames of people are not detected. The following are the screenshots of what I could get:

<img width="1280" alt="截屏2023-12-19 下午6 33 02" src="https://github.com/CMU-Perceptual-Computing-Lab/openpose/assets/82657344/5e151206-3f96-4c1d-b227-804c6482e33c">

<img width="639" alt="截屏2023-12-19 下午6 33 50" src="https://github.com/CMU-Perceptual-Computing-Lab/openpose/assets/82657344/7a5b8d5b-d69d-4a9d-ada0-0ebdae27f95a">

I thought that there might be some bug exists in displaying. Therefore, I also tried to log out the data into a JSON file using command --write_json. The JSON files could be generated successfully, but all the data are null.

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Help wanted

### Your System Configuration
1. **Whole console output** 
    -C:\......\openpose_source>bin\OpenPoseDemo.exe --video examples\media\video.avi --face --hand
      Starting OpenPose demo...
      Configuring OpenPose...
      Starting thread(s)...
      Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
      OpenPose demo successfully finished. Total time: 9.092402 seconds.

    -C:\......\openpose_source>bin\OpenPoseDemo.exe --image_dir examples\media\ --face --hand
      Starting OpenPose demo...
      Configuring OpenPose...
      Starting thread(s)...
      Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
      OpenPose demo successfully finished. Total time: 3.230856 seconds.

2. **OpenPose version**: The latest version from github.

3. **General configuration**: I used CMake GUI to configure and used Visual Studio 16 2019 to build the sln file on Win10 system.

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: I used the caffe contained in the post (https://github.com/CMU-Perceptual-Computing Lab/openpose/issues/1602).
    - **CMake version** cmake version 3.250-rc2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...? opencv_450_v15_2020_11_18 provided in https://github.com/CMU-Perceptual-Computing Lab/openpose/issues/1602 .

I would really appreciate all kinds of help. Thank you! =)

**Comment by 1uan-yuan** [comment]
Update:

I solved this problem. I think it might be due to the problem of wrong configuration or wrong build. I solved this problem by redo the whole procedure of installation. i.e., I downloaded OpenPose again and started with a new project.

**Comment by utkarshshukla2912** [comment]
@1uan-yuan did you do the whole process without changing anything, what changes you made in the configuration

**Comment by 1uan-yuan** [comment]
> @1uan-yuan did you do the whole process without changing anything, what changes you made in the configuration

No, I did not change anything. I followed the exact same procedures.
