### ISSUE TITLE
I can't download any model. The URL is just loading and nothing appears

### ISSUE THREAD

**Issue by 14790897** [CMU-Perceptual-Computing-Lab/openpose#2274]
[BODY_25 model](http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel): download in models/pose/body_25/.
[COCO model](http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel): download in models/pose/coco/.
[MPI model](http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/mpi/pose_iter_160000.caffemodel): download in models/pose/mpi/.
[Face model](http://posefs1.perception.cs.cmu.edu/OpenPose/models/face/pose_iter_116000.caffemodel): download in models/face/.
[Hands model](http://posefs1.perception.cs.cmu.edu/OpenPose/models/hand/pose_iter_102000.caffemodel): download in models/hand/.

**Comment by TheAnirudhan** [comment]
https://drive.google.com/file/d/1QCSxJZpnWvM00hx49CJ2zky7PWGzpcEh/edit
Try this link.
[mentioned here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1602#issuecomment-641653411)

**Comment by 14790897** [comment]
thank you bro
