### ISSUE TITLE
3d joints rotation

### ISSUE THREAD

**Issue by zdczdcc** [CMU-Perceptual-Computing-Lab/openpose#228]
I want to get each joints' hierarchical rotation.But i've no idea to do that.Is there anyone could give me some advice?Thanks a lot!

## Edit----
And i think it is possible to get joints' hierarchical rotation even though the joints' position are not in high accuracy(Like Kinect SDK,i could get each joint's hierarchical rotation and absolute rotation to the root joint).

**Comment by chenlx92** [comment]
I also need the 3D pose to human motion capture. Do you have any updates?

**Comment by zdczdcc** [comment]
I've been got the joints' rotation in a rigid-body system.But it's still a problem when the joints' position is inaccuracy,like openpose or Kinect.

**Comment by chenlx92** [comment]
Thanks. Is it possible to get the 6D pose (3D for position + 3D orientation)? 
I want to capture the human motion. I think there must be some relevant works.

**Comment by zdczdcc** [comment]
Yes,i think it could get 6d pose,like Kinect does.But i still have no idea to calculate a decent orientation result with those inaccuracy position input.

**Comment by chenlx92** [comment]
OK. Thanks. I don't know what's the matter with you but I think maybe you can to use a filter to get the filtered position.

**Comment by zdczdcc** [comment]
The  inaccuracy positions would lead to inaccuracy angles.And the angle error would be accumulated.But i want to use the angle to drive a human model with fixed bone length.And what kind of filter did you mean?EKF or something else.

**Comment by zdczdcc** [comment]
@chenlx92 ,please give me some suggestion.Thanks a lot!
