### ISSUE TITLE
how did i visulaize the skeleton joints in 3D space.

### ISSUE THREAD

**Issue by sainisanjay** [CMU-Perceptual-Computing-Lab/openpose#229]
@gineshidalgo99, I really thanks for the wonderful work. I want to visualize the skeleton joints in 3D space similar to paper Figure 10b (Hand Keypoint Detection). I would appreciate if you could tell me this.

Thanks

**Comment by gineshidalgo99** [comment]
Hi, all of those figures were made on the initial Matlab prototype of the hand detector. That code is quite messy and buggy (due to be just for prototyping purposes), so we just recommend the user to implement their own OpenGL implementation. Thanks

**Comment by sainisanjay** [comment]
@gineshidalgo99 Thank you so much for your kind response.
