### ISSUE TITLE
Turn off video back lay in demo project?

### ISSUE THREAD

**Issue by samim23** [CMU-Perceptual-Computing-Lab/openpose#23]
I'm curios to find out what the best way is to customise the openpose demo project, so that it only renders the skeleton - excluding the original video back lay. Looking as well how to set the Skeleton color and background color. Thanks in advance!

**Comment by gineshidalgo99** [comment]
You can find all the demo options (including that one) on the demo help, [demo documentation here](../blob/master/doc/demo_overview.md):
`./build/examples/openpose/openpose.bin --help`

In your case, the `disable_blending` option (also related: `part_to_show`, `alpha_pose`, and `alpha_pose`).

Alternatively, while running the demo, you can see the `'h' for help` text on the top-right side of the demo GUI, after pressing `h`, you can see there is a `press b` option that removes or adds the background in running time.

**Comment by samim23** [comment]
Thanks for the tips! I tried "disable_blending" but it seems like it does not have an effect, when using openpose in headless mode (on a Amazon EC2 box) to process video files. Here is my query, using the standard video file:

./build/examples/openpose/openpose.bin --video examples/media/video.avi --no_display --num_gpu 1 --write_video output.avi --disable_blending --alpha_pose 1

**Comment by gineshidalgo99** [comment]
You are right, sorry for the bug. I just added a fix, try the new version! Your command is good.
Let me know if you have any more questions/issues.

**Comment by cduguet** [comment]
Would you mind checking this again? For me Image blending can only be deactivated if I'm rendering with GPU. If I'm rendering on CPU instead, the Source Image is always on.

**Comment by gineshidalgo99** [comment]
I've just tested it in the last GitHub code and it works perfectly fine with both GPU and CPU rendering, and with both using `--disable_blending` and pressing the `b` key in the UI.
