### ISSUE TITLE
how to computer the mean average precision ?

### ISSUE THREAD

**Issue by andyqian2015** [CMU-Perceptual-Computing-Lab/openpose#230]
Hi,I try to drop the net resolution to raise the fps. and then I use the MPII Human Pose Dataset mentioned in your article to check out how much the map drop.On the Website:
http://human-pose.mpi-inf.mpg.de/#evaluation I mess around by the README.
```
pos = zeros(length(rect),2);
for ridx = 1:length(rect)
    pos(ridx,:) = [rect(ridx).objpos.x rect(ridx).objpos.y];
end
x1 = min(pos(:,1)); y1 = min(pos(:,2)); x2 = max(pos(:,1)); y2 = max(pos(:,2));
```
where can I get the rect ?

```
load('groups_v12.mat','groups');
[imgidxs_multi_test,rectidxs_multi_test] = getMultiPersonGroups(groups,RELEASE,false);
```
what is the groups_v12.mat ?
 I search on the web for a day, and get little effective information. can you give me some suggestion ? thx

**Comment by ZheC** [comment]
The groups_v12.mat is in the annotations downloaded from their website. For the evaluation question, you may want to write an email to them instead of posting issues here. We are not able to answer questions about others' code.
