### ISSUE TITLE
Hand/face joint heatmaps 

### ISSUE THREAD

**Issue by padeler** [CMU-Perceptual-Computing-Lab/openpose#231]
### Issue summary

Are there plans to expose the hand/face heatmaps?

handExtractor does not have a getHeatMaps() as the poseExtractor. 
There is a private member spHeatMapsBlob. Are all the heatmaps stored in that member? 

### Type of issue
- Enhancement / offering possible extensions / pull request / etc

**Comment by gineshidalgo99** [comment]
Yes, we'd like to, but not at the moment (busy with many other tasks).

**Comment by padeler** [comment]
so the spHeatMapsBlob private members in both the handExtractor and the faceExtractor point to the same body pose heatmaps?

**Comment by gineshidalgo99** [comment]
Ups forget that comment! Yes you are right, `spHeatMapsBlob` has the heatmaps. You'd have to do some kind of wrapper as I did in the poseExtractor class.

**Comment by padeler** [comment]
Ok thanks!

**Comment by padeler** [comment]
@gineshidalgo99 I opened a PR #260 for this issue. Any feedback?

**Comment by gineshidalgo99** [comment]
Thanks! Please, comment directly there to avoid mixing the 2 threads. Best
