### ISSUE TITLE
Model Download Fails During OpenPose Build on Google Colab

### ISSUE THREAD

**Issue by Mobina-Zibandepour** [CMU-Perceptual-Computing-Lab/openpose#2311]
The OpenPose build process on Google Colab has recently started failing during the model download step. This issue began on August 29, 2024, after the script had been running successfully without any problems until yesterday.

Steps to Reproduce
Run the following script on Google Colab:

```
import os
from os.path import exists, join, basename, splitext

git_repo_url = 'https://github.com/CMU-Perceptual-Computing-Lab/openpose.git'
project_name = splitext(basename(git_repo_url))[0]
if not exists(project_name):
  !wget -q https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz
  !tar xfz cmake-3.13.0-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local
  !git clone -q --depth 1 $git_repo_url
  !sed -i 's/execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/execute_process(COMMAND git checkout f019d0dfe86f49d1140961f8c7dec22130c83154 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/g' openpose/CMakeLists.txt
  !apt-get -qq install -y libatlas-base-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler libgflags-dev libgoogle-glog-dev liblmdb-dev opencl-headers ocl-icd-opencl-dev libviennacl-dev
  !pip install -q youtube-dl
  !cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. && make -j`nproc`

```

Observe the error during the cmake configuration step.

Expected Behavior
The models should download correctly, and the build process should be completed without errors.

Actual Behavior
The script fails with the following error:

CMake Error at cmake/Utils.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/content/openpose/models/pose/body_25/pose_iter_584000.caffemodel]
      expected hash: [78287b57cf85fa89c03f1393d368e5b7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [7;"Couldn't connect to server"]

environment:
Operating System: Google Colab (Linux)
CMake Version: 3.13.0
OpenPose Version: Latest from GitHub
Additional Context
I have confirmed that the issue is unrelated to my network or firewall.
The issue seems to be with the model download URLs or server accessibility.

I thank you if you could help me.

**Comment by Swabhan** [comment]
#2286 

The above pull request could be useful
