### ISSUE TITLE
getCaffe3rdparty.bat & getOpenCV.bat’s problem

### ISSUE THREAD

**Issue by wangyutao** [CMU-Perceptual-Computing-Lab/openpose#232]
1.run file getCaffe3rdparty.bat
----- Downloading Caffe -----
--2017-09-02 14:42:40--  http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/
windows/caffe3rdparty_2017_07_11.zip
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2
.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.
2.176.37|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://101.96.10.65/posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/wi
ndows/caffe3rdparty_2017_07_11.zip [following]
--2017-09-02 14:42:40--  http://101.96.10.65/posefs1.perception.cs.cmu.edu/OpenP
ose/3rdparty/windows/caffe3rdparty_2017_07_11.zip
Connecting to 101.96.10.65:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-02 14:42:40 ERROR 404: Not Found.

----- Unzipping Caffe -----
unzip:  cannot find either caffe3rdparty/caffe3rdparty_2017_07_11.zip or caffe3r
dparty/caffe3rdparty_2017_07_11.zip.zip.

2.run file getOpenCV.bat
----- Downloading OpenCV -----
--2017-09-02 14:44:33--  http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/
windows/opencv_310.zip
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2
.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.
2.176.37|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://101.96.10.60/posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/wi
ndows/opencv_310.zip [following]
--2017-09-02 14:44:34--  http://101.96.10.60/posefs1.perception.cs.cmu.edu/OpenP
ose/3rdparty/windows/opencv_310.zip
Connecting to 101.96.10.60:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-09-02 14:44:34 ERROR 403: Forbidden.

----- Unzipping OpenCV -----
unzip:  cannot find either opencv/opencv_310.zip or opencv/opencv_310.zip.zip.

The file server does not exist. Can you provide a URL that can download? Thank you very much

**Comment by gineshidalgo99** [comment]
The server might have been down for a little time. Is it working now?
