### ISSUE TITLE
Execution error on Windows 10

### ISSUE THREAD

**Issue by C-H-Nacion** [CMU-Perceptual-Computing-Lab/openpose#233]
### System Configuration
Windows 10 Pro
Visual Studio 2015
CUDA 8.0
cuDNN 5.1
Graphic card:Nvidia GeForce GTX 1060

### Issue summary
I installed OpenPose as described in the instructions(doc/installation.md).
I compiled, but I can't execute OpenPoseDemo.exe with error.

### Executed command (if any)
As described in the instructions.
> 4. In order to verify OpenPose is working, try compiling and executing the demo:
    1. Right click on `OpenPoseDemo` --> `Set as StartUp Project`.
    2. Change `Debug` by `Release` mode.
    3. Compile it and run it with F5 or the green play icon.

### OpenPose output (if any)
This is an output on VisualStudio(Translated).

`Exception thrown at 0x00007FFE5DBC0372 (OpenPose.dll) (in OpenPoseDemo.exe): 0xC0000005: An access violation occurred while reading the location 0x0000000000000008`

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error

**Comment by gineshidalgo99** [comment]
This problem should be fixed now. Please, let me know otherwise. Thanks!
