### ISSUE TITLE
how to get keypoints in wrapper.hpp

### ISSUE THREAD

**Issue by jinnen** [CMU-Perceptual-Computing-Lab/openpose#237]
i want to use keypoint value in wrapper.hpp
now i'm try to use TDatums.... but it seems like impossible
any one help me ...
or any recommend not using datum....

**Comment by gineshidalgo99** [comment]
Hi. In order to use the keypoints, check the `tutorial_wrapper` examples, I've just edited them so that they also show how to access the keypoints. I think this is what you are looking for, let me know otherwise. Thanks!

**Comment by RaphaelGross** [comment]
Hi Gineshidalgo99 ,
I have a similar question. I checked already the tutorial_wrapper directories, 3_user_synchronous_output.cpp.

I would like to add a function in the class WuserOutput that would return a value (x,y) once called in openPoseDemo. 
Do you have some insight on how to do this.
Thank you so much.
Raphe.

**Comment by RaphaelGross** [comment]
Hi Gineshidalgo99 ,
I have a similar question. I checked already the tutorial_wrapper directory, 3_user_synchronous_output.cpp.

I would like to add a function in the class WuserOutput that would return a value (x,y) once called in openPoseDemo. 
Do you have some insight on how to do this.
Thank you so much.
Raphe.
