### ISSUE TITLE
Build error in examples/tutorial_wrapper for Ubuntu 16.04

### ISSUE THREAD

**Issue by pamalite** [CMU-Perceptual-Computing-Lab/openpose#239]
### Makefile.config
Copied from `ubuntu/Makefile.config.Ubuntu16_cuda8.example`. 

The difference are `DEBUG : = 1`  and  `USE_PKG_CONFIG := 1` are set. The rest are defaults from the example.

### Issue summary
When trying to build OpenPose with `make all` command, the compile stops with the following error:

```
CXX/LD -o .build_debug/examples/tutorial_wrapper/2_user_synchronous.bin
.build_debug/examples/tutorial_wrapper/2_user_synchronous.o: In function `op::WCocoJsonSaver<std::shared_ptr<std::vector<UserDatum, std::allocator<UserDatum> > > >::workConsumer(std::shared_ptr<std::vector<UserDatum, std::allocator<UserDatum> > > const&)':
/home/kwong13/Documents/openpose/./include/openpose/filestream/wCocoJsonSaver.hpp:63: undefined reference to `op::CocoJsonSaver::record(op::Array<float> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:492: recipe for target '.build_debug/examples/tutorial_wrapper/2_user_synchronous.bin' failed
make: *** [.build_debug/examples/tutorial_wrapper/2_user_synchronous.bin] Error 1
```

I checked the file `include/openpose/filestream/CocoJsonSaver.hppr has a `record()` method. I am not sure why is it not taking that. 

I also tried disabling `DEBUG := 1` and `USE_PKG_CONFIG := 1`. Same problem. 

I tried removing the 2 cpp files from `exampels/tutorial_wrapper` directory and the `make all` works. 
 
### Type of issue
- Compilation/installation error

### Your system configuration
**Operating system** :
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**CUDA version**: 8.0.61
**cuDNN version**: 7.0.1
**GPU model**: GeForce GTX 980 Ti
**Caffe version**: Default from OpenPose.
**OpenCV version**: installed with `apt-get install libopencv-dev`.
**Compiler**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
This is a very old topic. Please, try again with the latest OpenPose version and let me know if it still fails. Thanks
