### ISSUE TITLE
How to detect pose of an image with only hands,without human face or body on it?

### ISSUE THREAD

**Issue by daisyl0** [CMU-Perceptual-Computing-Lab/openpose#240]
I found out that the demo can't detect pose of  an image with only hands on it, without face or body.
Is there some way to detect images with only hands on them?

**Comment by gineshidalgo99** [comment]
#206

**Comment by fmnoori** [comment]
Hi, I am a beginner. I also have the similar type of problem. 
My Caffe and OpenPose are running perfectly. 
initially, I was using this repository https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
(everything is working fine there)
Now I am trying to make run your repository.
But I got the similar type of Issue, which I posted in comments here.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/8
