### ISSUE TITLE
Render only specific joints from pose:

### ISSUE THREAD

**Issue by trshashank** [CMU-Perceptual-Computing-Lab/openpose#242]
### Issue summary
I have Openpose working quite well for live data / recorded videos. Although, there is an option of rendering FACE / POSE / HAND I did not find any inputs on how to display only certain connect joints. For instance, I want my output to contain connected joints of the left shoulder, elbow and hand. Is there a way to do that.

### Type of issue
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8
**cuDNN version**: 5
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose or custom version. Default
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows) or OpenCV 2.X or OpenCV 3.X. Especify **full version** (e.g. 3.1 or 2.4.9)
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu) or CMake (Ubuntu, Windows) or Visual Studio (Windows).
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
Hi, I am sorry but there is no way with the current library. That's a good suggestion I'll try to consider in future releases (but not at the moment given our long to-do list!)

**Comment by yyn19951228** [comment]
I think you can do it by editing the configuration in the '..../include/openpose/pose/poseParameters.hpp'. For example if you want to shadow the face joints(i.e. the No.14,15,16,17 joint), you can delete them from the   'POSE_COCO_BODY_PARTS' (if the model you use is COCO_S2), and edit the 'POSE_COCO_NUMBER_PARTS ', 'POSE_COCO_MAP_IDX', 'POSE_COCO_PAIRS' and 'POSE_COCO_COLORs_RENDER' accordingly.

**Comment by gineshidalgo99** [comment]
We will not adding, this seems like a quite specific functionality. Any person interested should follow the tutorial C++ API, and 1) render the output in a different way or 2) Add a post-processing step to remove the non-desired keypoints (recommended).
