### ISSUE TITLE
How to analyze yml file

### ISSUE THREAD

**Issue by Devy001** [CMU-Perceptual-Computing-Lab/openpose#243]
Hi,
   I analyze the yml file according the code of loadData function in the fileStream.cpp             
cv::FileStorage fileStorage{getFullName(fileNameNoExtension, format), cv::FileStorage::READ};
            std::vector<cv::Mat> cvMats(cvMatNames.size());
            for (auto i = 0 ; i < cvMats.size() ; i++)
                fileStorage[cvMatNames[i]] >> cvMats[i];
            fileStorage.release();

but I get nothing,what's the data format in the yml file? and how to analyze correctly?

**Comment by gineshidalgo99** [comment]
Try with `std::vector<cv::Mat> loadData(const std::vector<std::string>& cvMatNames, const std::string& fileNameNoExtension, const DataFormat format)` in `openpose/filestream/fileStream.hpp`

**Comment by GentlemanWei** [comment]
Ｗhat's the meaning of `const std::vector<std::string>& cvMatNames`
