### ISSUE TITLE
Adding Wrapper function - Openpose for windows

### ISSUE THREAD

**Issue by arthitag** [CMU-Perceptual-Computing-Lab/openpose#244]
### Issue summary
I want to add a new wrapper in tutorial/user_code which would run openpose model on a given image file and return the output Joint locations(x,y coordinates) as a suitable data structure (array/vector etc.)
I understand this will be very similar to 1_user_asynchronous.cpp that displays the results in a GUI. 

I don't need the GUI - but only a variable that contains x,y locations of all body joints.

Can someone give me some pointers on how to implement this quickly? (what FLAGS to set etc.)

### Type of issue
- Help wanted
- Question

### Your system configuration
**Operating system** Windows 10, x64,
**CUDA version** cuda 8.0  
**cuDNN version**: cudnn 5.1
**GPU model**
**Caffe version**: Default from OpenPose 
**OpenCV version**: 
Generation mode 
 Visual Studio 15 (Windows).

**Comment by gineshidalgo99** [comment]
It was added 1-2 weeks ago in both demos in `tutorial_wrapper` how to access the (x,y,score) locations of all the points. Just delete the imshow part.
