### ISSUE TITLE
models/pose/coco/pose_deploy_linevec.prototxt not found. 

### ISSUE THREAD

**Issue by arthitag** [CMU-Perceptual-Computing-Lab/openpose#246]
### Issue summary

runtime error : models/pose/coco/pose_deploy_linevec.prototxt not found. 
Hi,
 I wanted to use the wrapper function in 1_user_asynchronous.cpp to generate Keypoints. I modified the code slightly (to change the input and output formats) and it was initially working. I made a few further changes in the input format and rebuilt /cleaned and built the project a few times after that. Now it is building but when I try to use the exe file it's giving me a runtime error that says models/pose/coco/pose_deploy_linevec.prototxt not found. 
I checked that the file exists on the correct path.

This error wasn't there previously and it has suddenly cropped up now.
Please give some pointers on how to resolve this issue.

### Executed command (if any)
1_user_asynchronous.exe <root_dir> <folder_path> <frame_num>

### OpenPose output (if any)
It loads pose model
It configures openpose
It detects 1 GPU
It starts threads 
It prints out the correct path for the test image
io.cpp 41]Check failed:fd != -1 (-1 vs. -1) File not found: models/pose/coco/pose_deploy_linevec.prototxt

### Type of issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu): windows 10, 64 bit
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):  8.0
**cuDNN version**: 5.1
**GPU model**: NVidia GeForce GTX 745
**Caffe version**: Default from OpenPose 
**OpenCV version**: Default from OpenPose (Windows) 
Generation mode: Visual Studio 15 (Windows). v140 toolset, target platform version 8.1
Compiler:

**Comment by gineshidalgo99** [comment]
It looks like you must be running it from a different relative path than the original

**Comment by arthitag** [comment]
thank you

**Comment by nanthakumar94** [comment]
Error:
Prototxt file not found: models\face/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

**Comment by nanthakumar94** [comment]
can you explain please why this error came

**Comment by junely1** [comment]
In my case, I had the same problem and I enabled DOWNLOAD_BODY_MPI_MODEL in Cmake GUI and generated again. Then it worked on my Macbook pro
