### ISSUE TITLE
Speedup face tracking / Is there a paper about the face landmarks detection algorithm?

### ISSUE THREAD

**Issue by zhaoningning** [CMU-Perceptual-Computing-Lab/openpose#248]
hi guys:
           I see the model used by face landmarks detection, which i think is a really big model, and  i want to simplify it to reduce detection time,  is there a paper about the algorithm?

**Comment by Feifannaner** [comment]
speed up using this method.https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/standalone_face_or_hand_keypoint_detector.md

**Comment by gineshidalgo99** [comment]
No, there is no paper. Please, follow the doc as @Feifannaner  indicated in order to speed it up. Thanks

**Comment by gineshidalgo99** [comment]
From today, it has been added a quite faster Face Keypoint Detector (if body is not required). See https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/standalone_face_or_hand_keypoint_detector.md
 for further details
