### ISSUE TITLE
PoseExtractorCaffe::netInitializationOnThread() does not initialize mTheradId 

### ISSUE THREAD

**Issue by chenpaz** [CMU-Perceptual-Computing-Lab/openpose#249]
### Issue summary

PoseExtractorCaffe::netInitializationOnThread() does not initialize mTheradId  and cause 
PoseExtractor::checkThread() to fail.

**Comment by gineshidalgo99** [comment]
What are you and how are you running it? Just OpenPose demo? C++ API from your custom program?

**Comment by chenpaz** [comment]
Sorry my mistake. I was calling netInitializationOnThread()  instead of initializationOnThread()
