### ISSUE TITLE
How to get the skeleton points?

### ISSUE THREAD

**Issue by duduRodrigues** [CMU-Perceptual-Computing-Lab/openpose#25]
How to get only the skeleton points?

**Comment by gineshidalgo99** [comment]
It depends on what you want: display them, save them as JSON/XML/YML, etc. You can find all the information in the [README.md](../blob/master/README.md) and [documentation](../blob/master/doc/).

**Comment by duduRodrigues** [comment]
I want to display them. I will take a look at the documentation to find how to solve this problem! Thank you!

**Comment by gineshidalgo99** [comment]
Then you should start with the demo and its [documentation](../blob/master/doc/demo_overview.md).

**Comment by a-tbd** [comment]
hi there, i've gone through the demo and run a few times on my own images, but still don't understand how to get the skeleton only :/  Any other pointers?

**Comment by gineshidalgo99** [comment]
I think you wanna use the `--disable_blending` flag

**Comment by a-tbd** [comment]
@gineshidalgo99 ah thank you!
