### ISSUE TITLE
how to detect the hand key points alone  ? 

### ISSUE THREAD

**Issue by Feifannaner** [CMU-Perceptual-Computing-Lab/openpose#250]
### Issue summary : Speed Problems and How to detect the hand alone
      Thanks to the Authors  CONTRIBUTION WORKS here. 

      Here I have a problem. I want to use the accurate algorithm to detect the hand ,after that  using the rectangle to make a label of hands. However, the speed in my computer equipped with GFORCE 960 & Cuda 8 & Cudnn 7 is only 3.7 fps ,far from  my need. So I want to speed up the algorithm . A easy way is to detect the hand alone.

      BUT, I do not know how to detect the hand in camera producer. I used the Wrapper to find the key points of left and right hand in examples/media/*.jpg  . but I do not know how to use the camera to detect the hand alone. Can it accomplished without detecting the pose key points?  I can not find the method in the tutorial C++ files. 

     Thanks a million for solving my problems,If you have the code, Please share with me.
     Here is the code for hand detecting but not successful .
### Code
`// ------------------------- OpenPose Library Tutorial - Pose - Example 1 - Extract from Image -------------------------
// This first example shows the user how to:
    // 1. Load an image (`filestream` module)
    // 2. Extract the pose of that image (`pose` module)
    // 3. Render the pose on a resized copy of the input image (`pose` module)
    // 4. Display the rendered pose (`gui` module)
// In addition to the previous OpenPose modules, we also need to use:
    // 1. `core` module: for the Array<float> class that the `pose` module needs
    // 2. `utilities` module: for the error & logging functions, i.e. op::error & op::log respectively

// 3rdparty dependencies
#include <gflags/gflags.h> // DEFINE_bool, DEFINE_int32, DEFINE_int64, DEFINE_uint64, DEFINE_double, DEFINE_string
#include <glog/logging.h> // google::InitGoogleLogging
// OpenPose dependencies
#include <openpose/core/headers.hpp>
#include <openpose/filestream/headers.hpp>
#include <openpose/gui/headers.hpp>
#include <openpose/pose/headers.hpp>
#include <openpose/hand/headers.hpp>
#include <openpose/utilities/headers.hpp>

#define  PR(x) std::cout<<#x<<"="<<x<<std::endl;
#define here std::cout << "here" << std::endl;
bool debug = true;
// See all the available parameter options withe the `--help` flag. E.g. `./build/examples/openpose/openpose.bin --help`.
// Note: This command will show you flags for other unnecessary 3rdparty files. Check only the flags for the OpenPose
// executable. E.g. for `openpose.bin`, look for `Flags from examples/openpose/openpose.cpp:`.
// Debugging
DEFINE_int32(logging_level,             3,              "The logging level. Integer in the range [0, 255]. 0 will output any log() message, while"
                                                        " 255 will not output any. Current OpenPose library messages are in the range 0-4: 1 for"" low priority messages and 4 for important ones.");
DEFINE_int32(camera,                    -1,             "The camera index for cv::VideoCapture. Integer in the range [0, 9]. Select a negative"
                                                        " number (by default), to auto-detect and open the first available camera.");                                                       
// Producer
DEFINE_string(image_path,               "examples/media/COCO_val2014_000000000192.jpg",     "Process the desired image.");
// OpenPose
DEFINE_string(model_pose,               "COCO",         "Model to be used. E.g. `COCO` (18 keypoints), `MPI` (15 keypoints, ~10% faster), "
                                                        "`MPI_4_layers` (15 keypoints, even faster but less accurate).");
DEFINE_string(model_folder,             "models/",      "Folder path (absolute or relative) where the models (pose, face, ...) are located.");
DEFINE_string(net_resolution,           "368x368",      "Multiples of 16. If it is increased, the accuracy potentially increases. If it is decreased,"
                                                        " the speed increases. For maximum speed-accuracy balance, it should keep the closest aspect"
                                                        " ratio possible to the images or videos to be processed. E.g. the default `656x368` is"
                                                        " optimal for 16:9 videos, e.g. full HD (1980x1080) and HD (1280x720) videos.");
DEFINE_string(resolution,               "1280x720",     "The image resolution (display and output). Use \"-1x-1\" to force the program to use the"
                                                        " default images resolution.");
DEFINE_int32(num_gpu_start,             0,              "GPU device start number.");
DEFINE_double(scale_gap,                1.0,            "0.3Scale gap between scales. No effect unless scale_number > 1. Initial scale is always 1."
                                                        " If you want to change the initial scale, you actually want to multiply the"
                                                        " `net_resolution` by your desired initial scale.");
DEFINE_int32(scale_number,              1,              "Number of scales to average.");
// OpenPose Rendering
DEFINE_bool(disable_blending,           false,          "If blending is enabled, it will merge the results with the original frame. If disabled, it"
                                                        " will only display the results on a black background.");
DEFINE_double(render_threshold,         0.05,           "Only estimated keypoints whose score confidences are higher than this threshold will be"
                                                        " rendered. Generally, a high threshold (> 0.5) will only render very clear body parts;"
                                                        " while small thresholds (~0.1) will also output guessed and occluded keypoints, but also"
                                                        " more false positives (i.e. wrong detections).");
DEFINE_double(alpha_pose,               0.6,            "Blending factor (range 0-1) for the body part rendering. 1 will show it completely, 0 will"
                                                        " hide it. Only valid for GPU rendering.");

int openPoseTutorialPose1()
{
    op::log("OpenPose Library Tutorial - Example 1.", op::Priority::High);
    // ------------------------- INITIALIZATION -------------------------
    // Step 1 - Set logging level
        // - 0 will output all the logging messages
        // - 255 will output nothing
    op::check(0 <= FLAGS_logging_level && FLAGS_logging_level <= 255, "Wrong logging_level value.", __LINE__, __FUNCTION__, __FILE__);
    op::ConfigureLog::setPriorityThreshold((op::Priority)FLAGS_logging_level);
    op::log("", op::Priority::Low, __LINE__, __FUNCTION__, __FILE__);
    // Step 2 - Read Google flags (user defined configuration)
    // outputSize
    const auto outputSize = op::flagsToPoint(FLAGS_resolution, "1280x720");
    // netInputSize
    const auto netInputSize = op::flagsToPoint(FLAGS_net_resolution, "368x368");
    // netOutputSize
    const auto netOutputSize = netInputSize;
    // poseModel
    //const auto poseModel = op::flagsToPoseModel(FLAGS_model_pose);
    //const auto handModel = op::flagsToHandModel(FLAGS_model_hand);
    // Check no contradictory flags enabled
    if (FLAGS_alpha_pose < 0. || FLAGS_alpha_pose > 1.)
        op::error("Alpha value for blending must be in the range [0,1].", __LINE__, __FUNCTION__, __FILE__);
    if (FLAGS_scale_gap <= 0. && FLAGS_scale_number > 1)
        op::error("Incompatible flag configuration: scale_gap must be greater than 0 or scale_number = 1.", __LINE__, __FUNCTION__, __FILE__);
    // Logging
    op::log("", op::Priority::Low, __LINE__, __FUNCTION__, __FILE__);
    // Step 3 - Initialize all required classes
    //const auto scale_gap = op::flagsToPoint(FLAGS_scale_gap, 1.0);
    //op::log(netInputSize, op::Priority::Low, __LINE__, __FUNCTION__, __FILE__);
    //op::CvMatToOpInput cvMatToOpInput{netInputSize, FLAGS_scale_number, (float)FLAGS_scale_gap};
    op::CvMatToOpOutput cvMatToOpOutput{outputSize};
    //op::PoseExtractorCaffe poseExtractorCaffe{netInputSize, netOutputSize, outputSize, FLAGS_scale_number, poseModel,
                                              //FLAGS_model_folder, FLAGS_num_gpu_start};
    //const int gpuId = 0;
    const unsigned short numberScales = 1;
    const float rangeScales = 0.4f;
    here;
    op::HandExtractor handExtractor{netInputSize, netOutputSize, FLAGS_model_folder, FLAGS_num_gpu_start,
                                numberScales , rangeScales};
    //const op::RenderMode renderMode = op::RenderMode::Cpu;
    // we adopt the dafault value
    op::HandRenderer  handRenderer{netInputSize,  (float)FLAGS_render_threshold};//, const float alphaKeypoint,
                              // (float)FLAGS_alpha_pose, renderMode} :
    //op::PoseRenderer poseRenderer{netOutputSize, outputSize, poseModel, nullptr, (float)FLAGS_render_threshold,
     //                             !FLAGS_disable_blending, (float)FLAGS_alpha_pose};
    //op::PoseRenderer poseRenderer{netOutputSize, outputSize, poseModel, nullptr, (float)FLAGS_render_threshold,
                                 // !FLAGS_disable_blending, (float)FLAGS_alpha_pose};
    op::OpOutputToCvMat opOutputToCvMat{outputSize};
    const op::Point<int> windowedSize = outputSize;
    op::FrameDisplayer frameDisplayer{windowedSize, "OpenPose Tutorial - Example 1"};
    here;
    // Step 4 - Initialize resources on desired thread (in this case single thread, i.e. we init resources here)
    handExtractor.initializationOnThread();
    handRenderer.initializationOnThread();

    // ------------------------- POSE ESTIMATION AND RENDERING -------------------------
    // Step 1 - Read and load image, error if empty (possibly wrong path)
    cv::Mat frame;
    cv::VideoCapture cap(0);
    if(!cap.isOpened())
        std::cout << "open camera failed!" << std::endl;    
    cv::namedWindow("edges",-1);  
    here;
    cap.set(CV_CAP_PROP_FRAME_WIDTH,160);
    cap.set(CV_CAP_PROP_FRAME_HEIGHT,160);  
    while (cap.isOpened())
    {   
        //here;    
        //cv::waitKey(4000);
        cap.read(frame);
        //cv::imshow("edges",frame);
        //cv::imwrite("1.jpg",frame);
        cv::Mat inputImage = frame;        
        //cv::imwrite("hand.jpg",frame);
        //cv::waitKey(3000);
        //cv::resize(inputImage,inputImage,cv::Size(80,80),0, 0);
        //cv::imwrite("2.jpg",inputImage);
        //cv::Mat inputImage = op::loadImage(FLAGS_image_path, CV_LOAD_IMAGE_COLOR); // Alternative: cv::imread(FLAGS_image_path, CV_LOAD_IMAGE_COLOR);
        if(inputImage.empty())
            op::error("Could not open or find the image: " + FLAGS_image_path, __LINE__, __FUNCTION__, __FILE__);
        // Step 2 - Format input image to OpenPose input and output formats
        //op::Array<float> netInputArray;
        //std::vector<float> scaleRatios;
        //PR(scaleRatios);
        /*
        if (!debug)
        {
            std::cout <<  "here"  << std::endl;
            for (std::vector<float>::const_iterator i = scaleRatios.begin(); i != scaleRatios.end(); ++i)
                std::cout <<  "here" <<*i << ' ';

        }
        
        std::tie(netInputArray, scaleRatios) = cvMatToOpInput.format(inputImage);
        double scaleInputToOutput;
        op::Array<float> outputArray;
        std::tie(scaleInputToOutput, outputArray) = cvMatToOpOutput.format(inputImage);
        // Step 3 - Estimate poseKeypoints
        
        //scaleInputToOutput Desired scale of the final keypoints. Set to 1 if the desired size is the cvInputData size.
        */
        std::vector<float> scaleRatios;
        const std::vector<std::array<op::Rectangle<float>, 2>> handRectangles;
        const float scaleInputToOutput = 1;
        //handExtractor.forwardPass();
        cv::Mat netInputArray = frame;
        //std::tie(netInputArray, scaleRatios) = cvMatToOpInput.format(inputImage);
        
        handExtractor.forwardPass(handRectangles, netInputArray,scaleInputToOutput);
        
        if (!handRectangles.empty())
            std::cout << "not empty!!!" << std::endl;
        //const std::vector<std::array<Rectangle<float>, 2>> handRectangles, const cv::Mat& cvInputData,
                         //const float scaleInputToOutput)
        const auto HandKeypoints = handExtractor.getHandKeypoints();
        
        if(debug)
                if (!HandKeypoints.empty())
                {

                    for (auto person = 0 ; person < HandKeypoints[0].getSize(0) ; person++)
                    {
                
                        op::log("Person " + std::to_string(person) + " (x, y, score):");
                        for (auto bodyPart = 0 ; bodyPart < HandKeypoints[0].getSize(1) ; bodyPart++)
                        {
                            //PR(bodyPart);
                            std::string valueToPrint;
                            for (auto xyscore = 0 ; xyscore < HandKeypoints[0].getSize(2) ; xyscore++)
                            {
                        //const auto xL = poseKeypoints[{person, bodyPart, 0}];
                        //op::log("***********xl:*******" + xL);
                        //std::cout<<"***********xl**********"<<xL<<std::endl;
                                //PR(xyscore);
                                valueToPrint += std::to_string(   HandKeypoints[0][{person, bodyPart, xyscore}]   ) + " ";
                            }
                            op::log(valueToPrint);  
                        }
                    
                    //op::log("ponints:" + std::to_string(poseKeypoints[{0,0,0}]));
                    //op::log("ponints:" + poseKeypoints.to_String());
                    }
                }
        
        // Step 4 - Render poseKeypoints
        //std::cout << poseKeypoints << std::endl;
        double scaleInputToOutput_1;
        op::Array<float> outputData;
        std::tie(scaleInputToOutput_1, outputData) = cvMatToOpOutput.format(inputImage);
        handRenderer.renderHand(outputData, HandKeypoints);
        // Step 5 - OpenPose output format to cv::Mat
        auto outputImage = opOutputToCvMat.formatToCvMat(outputData);

        // ------------------------- SHOWING RESULT AND CLOSING -------------------------
        // Step 1 - Show results
        cv::imshow("edges",outputImage);
        cv::waitKey(1);
        //frameDisplayer.displayFrame(outputImage, 0); // Alternative: cv::imshow(outputImage) + cv::waitKey(0)
        // Step 2 - Logging information message
        //op::log("Example 1 successfully finished.", op::Priority::High);
        //cv::imwrite("hand.jpg",outputImage);
        cv::waitKey(1);
        int key =cv:: waitKey(2) & 0xff;
        if (key == 27)
            break;
        //PR(key);
       //break;
    }

    // Return successful message
    cap.release();
    cv::destroyAllWindows();
    return 0;
}

int main(int argc, char *argv[])
{
    // Initializing google logging (Caffe uses it for logging)
    google::InitGoogleLogging("openPoseTutorialPose1");

    // Parsing command line flags
    gflags::ParseCommandLineFlags(&argc, &argv, true);

    // Running openPoseTutorialPose1
    return openPoseTutorialPose1();
}
`

### Type of issue
You might select multiple topics, delete the rest:
- Help wanted
- Question
### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**CUDA version** 8
**cuDNN version 7 :
**GPU model GForce 960
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version 2.4.13 
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/standalone_face_or_hand_keypoint_detector.md
