### ISSUE TITLE
success with manual built but failed using Qtcreator

### ISSUE THREAD

**Issue by guiyuliu** [CMU-Perceptual-Computing-Lab/openpose#256]
### Issue summary
I built it successfully using manual installation, I can run the demo using openpose.bin.
when I want to built the code with Qtcreator ,I failed.

### Executed command (if any)
I open Qtcreator,  load the CMakelist.txt in the root folder. The whole project can be opened , but when I start to built openpose, firstly caffe was built ,then the source code but they can't find the file caffe/include/caffe/net.hpp
 

### OpenPose output (if any)
openpose/include/openpose/core/netCaffe.hpp:5: error: caffe/net.hpp: No such file or directory

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**cuDNN version**: 
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose 
**OpenCV version**:
Generation mode (only for Ubuntu): qtcreator
Compiler (`gcc --version` in Ubuntu):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by guiyuliu** [comment]
problem solved

**Comment by gineshidalgo99** [comment]
Glad you solved. Could you please make a pull request or show me your GitHub project with the Qt project? I'd like to take a look and try to add some similar demo. Thanks!

**Comment by WangJinxinNEU** [comment]
Could you please show me your .pro file? I want to use OpenPose in  Qt project. Thanks!

**Comment by gineshidalgo99** [comment]
Other option from Qt + CMake: #271

**Comment by TX-Yeager** [comment]
@WangJinxinNEU  do you solve the problems?

**Comment by WangJinxinNEU** [comment]
@TX-Yeager yes,solved
