### ISSUE TITLE
how to output images or videos without rgb frames?

### ISSUE THREAD

**Issue by liu666666** [CMU-Perceptual-Computing-Lab/openpose#258]
Thanks for your great work!  Could you please tell me how to output images or videos without rgb frames? I only want to get the key-points and linking lines in it. Thanks for your nice help! @gineshidalgo99

**Comment by gineshidalgo99** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md#flags-description

**Comment by liu666666** [comment]
sorry, i did not find an parameter to implement the above function. could you please tell me which parameter?

**Comment by gineshidalgo99** [comment]
`disable_blending`

**Comment by liu666666** [comment]
You are so nice ! Thank you very much!
