### ISSUE TITLE
Compilation/installation error - VS2015 Windows

### ISSUE THREAD

**Issue by lishunda** [CMU-Perceptual-Computing-Lab/openpose#259]
Issue summary

I have been working on it for several weeks and tried to install and reintall cuda&vs2015&openpose......

I tried to build OpenposeDemo on Visual Studio 15. I followed  steps of installation  in the doc/installation.md.

When I try to build OpenposeDemo I get the following error:

Error	LNK1181	cannot open input file '..\x64\Release\OpenPose.lib'	OpenPoseDemo
Error	LNK1181   cannot open input file“boost_atomic-vc140-mt-1_61.lib”   OpenPoseDemo

then I try to build openpose library,and I get the following error:
Error	LNK1181   cannot open input file“boost_atomic-vc140-mt-1_61.lib”   OpenPose

Executed command (if any)

Build OpenposeDemo on VS 2015

OpenPose output (if any)

None

Type of issue

Compilation/installation error
Help wanted

Your system configuration

windows 10
cuda: v8.0
cuDNN version:5.1
Caffe version: Default from OpenPose
OpenCV version: default from OpenPose (Windows)
Visual Studio (Windows): visual studio 15

**Comment by dishang13** [comment]
did you get it to work? i have the same issue

**Comment by gineshidalgo99** [comment]
`Error LNK1181 cannot open input file` sounds like the files that has to be downloaded were not properly downloaded. Please, try manually downloading and unzipping them (see [instructions](https://github.com/CMU-PerceptualComputing-Lab/openpose/blob/master/doc/installation.md#installation---library) to get their links)

**Comment by gineshidalgo99** [comment]
(Assumed solved)
