### ISSUE TITLE
processing a folder with variable image sizes, and "-1x-1" option crashed

### ISSUE THREAD

**Issue by umdjanus** [CMU-Perceptual-Computing-Lab/openpose#262]
### Posting rules
1. **Add** the **system configuration (all of it!), command and output** if you have some kind of error or performance question.
2. **No duplicated** posts.
3. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
4. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
5. Only English comments.
Issues/comments that do not follow this will be **ignored or removed** with no further clarification.

### Issue summary
I testing the simplist program openpose.bin. When running openpose.bin on a folder with different size images, and using the option --resolution  "-1x-1"
(to process the images with rescaling) I get crash indicating the images must be the same size.

Otherwise all works as expected.

### Executed command (if any)
Note: add `--logging_level 0` to get higher debug information.

./openpose/build/examples/openpose/openpose.bin --image_dir  MCMs  --write_images tempooo  --no_display --resolution  "-1x-1"

### OpenPose output (if any)

Error:
Output resolution = input resolution not valid for image reading (size might change between images).

Coming from:
- ./include/openpose/wrapper/wrapper.hpp:configure():548
- ./include/openpose/wrapper/wrapper.hpp:configure():842
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Output resolution = input resolution not valid for image reading (size might change between images).

Coming from:
- ./include/openpose/wrapper/wrapper.hpp:configure():548
- ./include/openpose/wrapper/wrapper.hpp:configure():842

### Type of issue
You might select multiple topics, delete the rest:
 
- Execution error
 

### Your system configuration

Linux (Redhat), Cuda8.0,  default Caffe, Opencv from openpose.

**Comment by gineshidalgo99** [comment]
That functionality has now being implemented and added to the repository. You can use a variable output resolution with the `-1x-1` option for the `output_resolution` flag (which replaces the ambiguous `resolution` and by default is already `-1,1`). Let me know if something fails. Thanks!
