### ISSUE TITLE
Suppress net loading output

### ISSUE THREAD

**Issue by HWiese1980** [CMU-Perceptual-Computing-Lab/openpose#267]
Printing out the whole CaffeNet configuration to the screen, especially on `stderr` is kind of an annoyance. I'm trying to use OpenPose in a ROS node, which is launched through `roslaunch` There's no direct option to redirect or otherwise suppress output on `stderr`. 

Please make it a CMAKE option to disable the output. Thanks!

**Comment by gineshidalgo99** [comment]
That does not happen in the official version (e.g. Ubuntu & Windows), so I cant debug it and I am not sure the reason why it happens in your ROS mode, but you should be able to disable it somehow. I think Caffe has flags to control the verbose, and for the OpenPose verbose you can check the `doc/demo_overview.md` to see how to avoid any OpenPose output (unrelated with Caffe output). Please, feel free to post your solution to the problem so other ROS users can also apply it. Best

**Comment by HWiese1980** [comment]
Figured it out, thanks. Easy as can be... just set the environment variable `GLOG_minloglevel` to some sufficiently high value. I have mine at 50 now and neither OpenPose nor Caffe bugs me with any unwanted outputs anymore. 

    user:~$ export GLOG_minloglevel=50

That's about it. Just play with the value if still want to see some outputs.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back!
