### ISSUE TITLE
Can openpose read from a video stream (RTSP) coming from an IP camera. (Ubuntu 16.04)

### ISSUE THREAD

**Issue by achbogga** [CMU-Perceptual-Computing-Lab/openpose#269]
### Posting rules
1. **Add** the **system configuration (all of it!), command and output** if you have some kind of error or performance question.
2. **No duplicated** posts.
3. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
4. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
5. **No** questions about **training**. OpenPose only implements testing.
6. Only English comments.
Issues/comments that do not follow this will be **ignored or removed** with no further clarification.

### Issue summary
I wish to read and write pose rendered output in real time using openpose. I am using an IP camera which sends an rtsp stream. Please find below my system config:
Ubuntu 16.04 Quadro P5000 Xeon 12 Core 32GB RAM
Openpose, caffe latest custom built with NCCL support, opencv 3.3.0 custom built with gstreamer and FFMPEG support.

Thanks in advance.

### Executed command (if any)
Note: add `--logging_level 0` to get higher debug information.

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows) or OpenCV 2.X or OpenCV 3.X. Especify **full version** (e.g. 3.1 or 2.4.9)
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu) or CMake (Ubuntu, Windows) or Visual Studio (Windows).
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
#167

**Comment by achbogga** [comment]
Hello gineshdalgo99,

I tried forking and merging the above mentioned repo. It did not work out. There are many conflicts and the build fails as the master is 40 commits ahead of when the user implemented rtsp support. I request you to implement the support into the existing master branch. The reason being I would love to have cmake support included. Thanks a million.

**Comment by gineshidalgo99** [comment]
@achbogga IP camera support has been officially added. Let me know whether it works fine. Thanks!

**Comment by achbogga** [comment]
@ Team Openpose, @gineshidalgo99 ,

You guys are amazing. Thanks a million for the outstanding support. Kudos to you guys for maintaining such a huge library so well. Keep up the good work.

**Comment by gineshidalgo99** [comment]
Thank you very much, we'll definitively try our best.

**Comment by achbogga** [comment]
@gineshidalgo99 @Team Openpose,

The IP camera support is working for some frames but is producing decode error for some frames which were not there with the webcam demo option. I would really appreciate if you guys look into it. Below is the sample output:

build/examples/openpose/openpose.bin --ip_camera rtsp://xxxxx:xxxxx@x:x:x:x/streaming/channels-101/
Starting pose estimation demo.
Auto-detecting GPUs... Detected 2 GPU(s), using them all.
Starting thread(s)
[h264 @ 0x1d90760] error while decoding MB 17 19, bytestream -7
[h264 @ 0x1dd7ce0] error while decoding MB 34 22, bytestream -6
[h264 @ 0x1e1f260] error while decoding MB 14 31, bytestream -5
[h264 @ 0x1e667e0] error while decoding MB 22 37, bytestream -5
[h264 @ 0x1ef5660] error while decoding MB 75 39, bytestream -5
[h264 @ 0x1eadf20] error while decoding MB 60 23, bytestream -17
[h264 @ 0x1c3b680] error while decoding MB 52 6, bytestream -17
[h264 @ 0x1c73160] left block unavailable for requested intra4x4 mode -1 at 0 4

**Comment by gineshidalgo99** [comment]
It looks like the h264 codecs are failing somehow. It might be for 2 reasons:
- Easy solution: the h264 camera codecs are somehow non-recognized by OpenCV. In this case,  you should try to use MPEG in the IP camera. This is possible in almost any IP camera, e.g. in AXIS cameras. I could only try with public IP cameras, so I have no idea how to change to MPEG video and I cannot debug your error from here. I am sorry.
- If you really need H264 codecs support, OpenCV should be compiled from scratch with proper code H264 support (try a simple OpenCV demo to verify your IP camera is working there, we simply use OpenCV for reading the IP camera).

Let me know how you solved so others can use it too.

**Comment by Jochlove** [comment]
@gineshidalgo99 
I have an issue using the ip_camera on openpose. I always got this error. Does it need to have a path?
Please help me understand how the ip camera works. Thanks!

In cmd:
OpenPoseDemo.exe --ip_camera rtsp://ipaddress:port

Starting pose estimation demo.
[rtsp @ 0000014ae9a681e0] Nonmatching transport in server reply
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:578)

Error:
VideoCapture (IP camera/video) could not be opened for path: 'rtsp://192.168.xx.xx:xxxx'. If it is a video path, is the path correct?

Coming from:
- ..\..\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():37
- ..\..\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():41
- ..\..\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():183

**Comment by kangkaikang** [comment]
> @gineshidalgo99，使用 openpose 上的ip_camera有问题。我总是收到这个错误。是否需要路径？
> 请帮我了解 ip 相机是如何工作的。谢谢！
> 
> Openpose 在窗口中运行。
> 
> 以 cmd：
> openPosedemo.exe -- ip_camera rtsp/ ipaddress： 端口
> 
> 开始姿势估计演示。
> [rtsp _ 000014ae9a681e0] 服务器回复警告中的非
> 匹配传输： 打开文件错误打开文件 （/生成/打开cv/模块/视频/src/cap_ffmpeg_impl.hpp：578）
> 
> 错误：
> 无法打开视频捕获（IP 摄像机/视频）路径："rtsp：//192.168.xx.xx：xxxx"。如果是视频路径，路径是否正确？
> 
> 来自：
> 
> * .__src_openpose_制作人\视频捕获阅读器.cpp：操作：：视频捕获阅读器：：视频捕获阅读器（）：37
> * .__src_openpose_制作人\视频捕获阅读器.cpp：操作：：视频捕获阅读器：：视频捕获阅读器（）：41
> * .__src_openpose_实用程序\flagstoOpenpose.cpp：操作：：标志生产者（）：183

Have you solved this problem? I have also encountered this problem

**Comment by kangkaikang** [comment]
> @gineshidalgo99
> I have an issue using the ip_camera on openpose. I always got this error. Does it need to have a path?
> Please help me understand how the ip camera works. Thanks!
> 
> Openpose is running on windows.
> 
> In cmd:
> OpenPoseDemo.exe --ip_camera rtsp://ipaddress:port
> 
> Starting pose estimation demo.
> [rtsp @ 0000014ae9a681e0] Nonmatching transport in server reply
> warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:578)
> 
> Error:
> VideoCapture (IP camera/video) could not be opened for path: 'rtsp://192.168.xx.xx:xxxx'. If it is a video path, is the path correct?
> 
> Coming from:
> 
> * ....\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():37
> * ....\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():41
> * ....\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():183

Have you solved this problem? I have also encountered this problem

**Comment by kangkaikang** [comment]
> It looks like the h264 codecs are failing somehow. It might be for 2 reasons:
> 
> * Easy solution: the h264 camera codecs are somehow non-recognized by OpenCV. In this case,  you should try to use MPEG in the IP camera. This is possible in almost any IP camera, e.g. in AXIS cameras. I could only try with public IP cameras, so I have no idea how to change to MPEG video and I cannot debug your error from here. I am sorry.
> * If you really need H264 codecs support, OpenCV should be compiled from scratch with proper code H264 support (try a simple OpenCV demo to verify your IP camera is working there, we simply use OpenCV for reading the IP camera).
> 
> Let me know how you solved so others can use it too.

**Comment by gineshidalgo99** [comment]
@Jochlove  The IP camera reader is implemented with OpenCV. Please, make sure to understand how to use the IP camera on OpenCV, and then you can use it the same way with OpenPose. If for any reason a command works in OpenCV but not in OpenPose, then for sure post it here and I will try to debug it!

**Comment by kangkaikang** [comment]
@gineshidalgo99 
Hello, because my IP camera only supports UDP, and it seems that the default implementation in opencv is TCP. I want to know what I should do and how to configure it. Thank you and look forward to your reply. The following is the content of my error report with OpenCV.

Traceback (most recent call last):
  File "vedio.py", line 18, in <module>
    cv2.imshow("camera",img)
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-kh7iq4w7\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

[rtsp @ 000001edd9798880] Nonmatching transport in server reply

code：
#coding=utf-8
import cv2 
import time
import os
os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"] = "rtsp_transport;udp"
if __name__ == '__main__':
 
    cv2.namedWindow("camera",1)
    video="rtsp://root:kk961114@192.168.1.10:554/stream_chn0.h264"   #此处@后的ipv4 地址需要修改为自己的地址
    #video="rtsp://192.168.1.10:554/stream_chn0.h264"
    #video="rtsp://kk:kk961114@192.168.1.12:8554/live"
    capture =cv2.VideoCapture(video)
 
    num = 0;
    while True:
        success,img = capture.read()
        cv2.imshow("camera",img)
        key = cv2.waitKey(10) 
 
        if key == 27:
            print("esc break...")
            break
        if key == ord(' '):
            num = num+1
            filename = "frames_%s.jpg" % num
            cv2.imwrite(filename,img)
 
 
    capture.release()
    cv2.destroyWindow("camera")
