### ISSUE TITLE
How to use OpenPose in QtCreator

### ISSUE THREAD

**Issue by WangJinxinNEU** [CMU-Perceptual-Computing-Lab/openpose#271]
Could you please show me your .pro file? I want to use OpenPose in Qt project. Thanks!

**Comment by soulslicer** [comment]
That is completely redundant. 

First make a build folder and build it through the terminal.

Then Open the CMakeLists.txt file in Qtcreator, then select it in qtcreator, and then select your build folder as what you created earlier. 

Example:

https://imgur.com/a/jaNHa

**Comment by WangJinxinNEU** [comment]
But I want to develop a system that use QT GUI ,so I have to build a new project use qt

**Comment by gineshidalgo99** [comment]
OK. If you have completely installed OpenPose with CMake (including `sudo make install`), then you should be able to just add the flag: -lopenpose as you do with e.g. -lopencv_core. The only other dependencies are OpenCV and Gflags, same with them. Those are the only 2 deps you need to use with OpenPose after it has being installed. If you did not make `sudo make install`, then just link the include and lib folders of OpenPose.

**Comment by WangJinxinNEU** [comment]
Thank you,can I re-write the "cameraRead" function?I use IP camera,but rtsp is instability，so I want to use camera API to get RGB image,then use the openpose model to analyse this image,please tell me is  there such an interface to complete this work.

**Comment by gineshidalgo99** [comment]
Then use the `tutorial_wrapper/` functions for that. In particular, you want a custom input, while keeping the default output/processing. So I highly recommend example `2_user_synchronous.cpp` for more functionality, but `3_user_asynchronous.cpp` would also work.
