### ISSUE TITLE
openpose crash when requesting input image size preservation

### ISSUE THREAD

**Issue by yaseryacoob** [CMU-Perceptual-Computing-Lab/openpose#272]
Any explanation for the crash when using the basic openpose.bin with a folder that have different size images, and requesting preservation of the image resolution for each image?

Linux, Red Hat, installation, executing the command

bash-4.2$ **./build/examples/openpose/openpose.bin --image_dir  ydata --write_images yyout --no_display -resolution "-1x-1"**
Starting pose estimation demo.
Auto-detecting GPUs... Detected 1 GPU(s), using them all.

Error:
Output resolution = input resolution not valid for image reading (size might change between images).

Coming from:
- ./include/openpose/wrapper/wrapper.hpp:configure():548
- ./include/openpose/wrapper/wrapper.hpp:configure():842
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Output resolution = input resolution not valid for image reading (size might change between images).

Coming from:
- ./include/openpose/wrapper/wrapper.hpp:configure():548
- ./include/openpose/wrapper/wrapper.hpp:configure():842

Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
OpenPose was actually updated on Sat to allow this functionality, so just download the latest OpenPose version. Best
