### ISSUE TITLE
Favour request: Can I get keypoint json output as stdout from commandline?

### ISSUE THREAD

**Issue by achbogga** [CMU-Perceptual-Computing-Lab/openpose#273]
### Posting rules
1. **Add** the **system configuration (all of it!), command and output** if you have some kind of error or performance question.
2. **No duplicated** posts.
3. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
4. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
5. **No** questions about **training**. OpenPose only implements testing.
6. Only English comments.
Issues/comments that do not follow this will be **ignored or removed** with no further clarification.

### Executed command (if any)
Note: add `--logging_level 0` to get higher debug information.

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Installation mode**: CMake or sh script or manual Makefile installation.
**Operating system** (`lsb_release -a` in Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` (Ubuntu) or default from OpenPose (Windows) or OpenCV 2.X or OpenCV 3.X. Especify **full version** (e.g. 3.1 or 2.4.9)
Generation mode (only for Ubuntu): Makefile + Makefile.config (default, Ubuntu) or CMake (Ubuntu, Windows) or Visual Studio (Windows).
Compiler (`gcc --version` in Ubuntu):

I wish to to use the keypoint information and do something with it. But, it would be great to get it in real-time on the commandline so that there is no os io read write lag to do something with it in real-time. 

Thanks and regards
Achyut

**Comment by gineshidalgo99** [comment]
You cannot get points from command line, but can add OpenPose to your C++ program. Check the tutorial_wrapper tutorials. Best

**Comment by hellochar** [comment]
@gineshidalgo99 could I request the demo app support writing JSON to stdout? I need to process realtime keypoints from a webcam. I'm currently using `--write_json` and then periodically `ls`-ing the folder to find the latest frame but this won't work for a long-running process (I'd like to keep the process on for ~3 days at least). Simply streaming the data to stdout would allow me to pipe the data to other applications that can handle the JSON in real time as it comes in.

**Comment by riebling** [comment]
what about piping the stdout of `tail -f <json output>`  (I am wanting to try the same kind of thing)
