### ISSUE TITLE
Demo wont run on the TitanX machine even after setting the --net_resolution to 160*80. Please help

### ISSUE THREAD

**Issue by achbogga** [CMU-Perceptual-Computing-Lab/openpose#275]
### Posting rules
1. **Add** the **system configuration (all of it!), command and output** if you have some kind of error or performance question.
output of lspci:
00:00.0 Host bridge: Intel Corporation 5520/5500/X58 I/O Hub to ESI Port (rev 22)
00:01.0 PCI bridge: Intel Corporation 5520/5500/X58 I/O Hub PCI Express Root Port 1 (rev 22)
00:03.0 PCI bridge: Intel Corporation 5520/5500/X58 I/O Hub PCI Express Root Port 3 (rev 22)
00:07.0 PCI bridge: Intel Corporation 5520/5500/X58 I/O Hub PCI Express Root Port 7 (rev 22)
00:14.0 PIC: Intel Corporation 7500/5520/5500/X58 I/O Hub System Management Registers (rev 22)
00:14.1 PIC: Intel Corporation 7500/5520/5500/X58 I/O Hub GPIO and Scratch Pad Registers (rev 22)
00:14.2 PIC: Intel Corporation 7500/5520/5500/X58 I/O Hub Control Status and RAS Registers (rev 22)
00:1a.0 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #4
00:1a.1 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #5
00:1a.2 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #6
00:1a.7 USB controller: Intel Corporation 82801JI (ICH10 Family) USB2 EHCI Controller #2
00:1b.0 Audio device: Intel Corporation 82801JI (ICH10 Family) HD Audio Controller
00:1c.0 PCI bridge: Intel Corporation 82801JI (ICH10 Family) PCI Express Root Port 1
00:1c.5 PCI bridge: Intel Corporation 82801JI (ICH10 Family) PCI Express Root Port 6
00:1d.0 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #1
00:1d.1 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #2
00:1d.2 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #3
00:1d.7 USB controller: Intel Corporation 82801JI (ICH10 Family) USB2 EHCI Controller #1
00:1e.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev 90)
00:1f.0 ISA bridge: Intel Corporation 82801JIR (ICH10R) LPC Interface Controller
00:1f.2 SATA controller: Intel Corporation 82801JI (ICH10 Family) SATA AHCI Controller
00:1f.3 SMBus: Intel Corporation 82801JI (ICH10 Family) SMBus Controller
02:00.0 VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX TITAN X] (rev a1)
02:00.1 Audio device: NVIDIA Corporation Device 0fb0 (rev a1)
05:00.0 Ethernet controller: Broadcom Corporation NetXtreme BCM5761 Gigabit Ethernet PCIe (rev 10)
06:04.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8169 PCI Gigabit Ethernet Controller (rev 10)
3f:00.0 Host bridge: Intel Corporation Xeon 5500/Core i7 QuickPath Architecture Generic Non-Core Registers (rev 05)
3f:00.1 Host bridge: Intel Corporation Xeon 5500/Core i7 QuickPath Architecture System Address Decoder (rev 05)
3f:02.0 Host bridge: Intel Corporation Xeon 5500/Core i7 QPI Link 0 (rev 05)
3f:02.1 Host bridge: Intel Corporation Xeon 5500/Core i7 QPI Physical 0 (rev 05)
3f:03.0 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller (rev 05)
3f:03.1 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Target Address Decoder (rev 05)
3f:03.4 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Test Registers (rev 05)
3f:04.0 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 0 Control Registers (rev 05)
3f:04.1 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 0 Address Registers (rev 05)
3f:04.2 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 0 Rank Registers (rev 05)
3f:04.3 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 0 Thermal Control Registers (rev 05)
3f:05.0 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 1 Control Registers (rev 05)
3f:05.1 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 1 Address Registers (rev 05)
3f:05.2 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 1 Rank Registers (rev 05)
3f:05.3 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 1 Thermal Control Registers (rev 05)
3f:06.0 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 2 Control Registers (rev 05)
3f:06.1 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 2 Address Registers (rev 05)
3f:06.2 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 2 Rank Registers (rev 05)
3f:06.3 Host bridge: Intel Corporation Xeon 5500/Core i7 Integrated Memory Controller Channel 2 Thermal Control Registers (rev 05)

2. **No duplicated** posts.
3. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
4. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
5. **No** questions about **training**. OpenPose only implements testing.
6. Only English comments.
Issues/comments that do not follow this will be **ignored or removed** with no further clarification.

### Issue summary
Hello @gineshidalgo99 and team, I am using custom built caffe and opencv on the machine which has a titanx GPU and Xeon i7. It has CUDA 9, CUDNN 7.

The demo fails to run and produces the following output.
ovuser@ovl-ubuntu-titanx:~/projects/openpose$ build/examples/openpose/openpose.bin --net_resolution "160x80" --logging_level 0
Starting pose estimation demo.
/home/ovuser/projects/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():112
/home/ovuser/projects/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():74
Auto-detecting camera index... Detected and opened camera 0.
/home/ovuser/projects/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():15
/home/ovuser/projects/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():44
/home/ovuser/projects/openpose/examples/openpose/openpose.cpp:openPoseDemo():195
Configuring OpenPose wrapper. In /home/ovuser/projects/openpose/examples/openpose/openpose.cpp:openPoseDemo():198
/home/ovuser/projects/openpose/include/openpose/wrapper/wrapper.hpp:configure():439
Auto-detecting GPUs... Detected 1 GPU(s), using them all.
/home/ovuser/projects/openpose/include/openpose/wrapper/wrapper.hpp:configure():655
/home/ovuser/projects/openpose/include/openpose/wrapper/wrapper.hpp:configure():931
Starting thread(s)
/home/ovuser/projects/openpose/include/openpose/wrapper/wrapper.hpp:configureThreadManager():1261
/home/ovuser/projects/openpose/include/openpose/thread/threadManager.hpp:exec():163
/home/ovuser/projects/openpose/include/openpose/thread/queueBase.hpp:addPusher():360
/home/ovuser/projects/openpose/include/openpose/thread/queueBase.hpp:addPusher():360
/home/ovuser/projects/openpose/include/openpose/thread/queueBase.hpp:addPusher():360
/home/ovuser/projects/openpose/include/openpose/thread/threadManager.hpp:exec():168
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:startInThread():138
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:startInThread():138
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:startInThread():138
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():182
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():185
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():182/home/ovuser/projects/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():53

/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():182
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():182
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():185
Starting initialization on thread. In /home/ovuser/projects/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():46
/home/ovuser/projects/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():65
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():55
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():65
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():55
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():67
/home/ovuser/projects/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():53
/home/ovuser/projects/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():65
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():55
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():65
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():55
/home/ovuser/projects/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():67
/home/ovuser/projects/openpose/include/openpose/thread/thread.hpp:threadFunction():185
E1004 12:38:42.529747  7697 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
F1004 12:38:42.612352  7697 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7f57993b35cd  google::LogMessage::Fail()
    @     0x7f57993b5433  google::LogMessage::SendToLog()
    @     0x7f57993b315b  google::LogMessage::Flush()
    @     0x7f57993b5e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5790119b3b  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f57901d0fbc  caffe::Net<>::Init()
    @     0x7f57901d4080  caffe::Net<>::Net()
    @     0x7f5797235a60  op::NetCaffe::initializationOnThread()
    @     0x7f5797ad29fc  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f5797accc36  op::PoseExtractor::initializationOnThread()
    @     0x7f5797ac6e7e  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f57975dfa5c  op::SubThread<>::initializationOnThread()
    @     0x7f57975e1c6b  op::Thread<>::initializationOnThread()
    @     0x7f57975e1ebd  op::Thread<>::threadFunction()
    @     0x7f57975fe047  std::_Mem_fn_base<>::operator()<>()
    @     0x7f57975fdfdb  _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7f57975fdd8c  std::_Bind_simple<>::operator()()
    @     0x7f57975fdb5c  std::thread::_Impl<>::_M_run()
    @     0x7f5798c78c80  (unknown)
    @     0x7f57955b56ba  start_thread
    @     0x7f57986e73dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)

### Type of issue
You might select multiple topics, delete the rest:

- Execution error
- Help wanted
- Question

### Your system configuration
**Installation mode**: CMake
**Operating system**Ubuntu 16.04

Thanks as always

**Comment by Tetsujinfr** [comment]
"the machine which has a titanx GPU and Xeon i7. It has CUDA 9, CUDNN 7.", ... 
Heu, I do not think that caffe works with Cuda9 and CuDNN 7. Does it? Did you get caffe to work on your machine with other projects?
Try CuDNN4 and cuda 8.0 or cuda 7.0. Or try without cudnn.

Tets

**Comment by gineshidalgo99** [comment]
### Posting rules
4. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.

I.e.:

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...?
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose, custom version, ...?
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
Still, the error has something to do with cuDNN version mismatch. Try recompiling CUDA and cuDNN.
