### ISSUE TITLE
Jetson TX2 installation instructions

### ISSUE THREAD

**Issue by robotlinker** [CMU-Perceptual-Computing-Lab/openpose#276]
HI,

The instructions for TX2 installation is not accessible:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2

**Comment by gineshidalgo99** [comment]
It's https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2.md

I'll update it very soon. Thanks!

**Comment by robotlinker** [comment]
Thanks, I am running on my JETSON TX2 board, it works!

**Comment by megashigger** [comment]
@robotlinker what kind of performance are you getting (FPS) and at which resolution? Thx!
