### ISSUE TITLE
Supporting depth data natively (RGB-D images)

### ISSUE THREAD

**Issue by marlonmisra** [CMU-Perceptual-Computing-Lab/openpose#281]
### Issue Summary
I was wondering if there are plans to support depth data natively? So, instead of having RGB images as input, using RGB-D images.

### Type of Issue
You might select multiple topics, delete the rest:
- Enhancement / offering possible extensions / pull request / etc

**Comment by walterwang** [comment]
just curious what type of information does depth offer?

**Comment by marlonmisra** [comment]
@walterwang my project requires a 3D skeleton of each person and their relative position. I can use Kinect and look up the depth value of each pixel. That works fine but I'd imagine that you can get even higher accuracy if your training data has a depth dimension too. Do you think that wouldn't be the case?

**Comment by gineshidalgo99** [comment]
#120, #287

**Comment by themoob** [comment]
This is not a duplicate, the issue is still relevant. The linked issues are connected to using the RGB camera in Kinect, not the additional depth data layer during prediction.

**Comment by pcp16** [comment]
@themoob is right, proprietary software like MS SDK and NITE2 provide depth-based skeleton detection, but there isn't an open alternative yet.

**Comment by gineshidalgo99** [comment]
In addition, you can implement your own for your custom private depth-based data following the tutorials (C++/Python)
