### ISSUE TITLE
Skeleton order

### ISSUE THREAD

**Issue by joaogantunes** [CMU-Perceptual-Computing-Lab/openpose#283]
I'm using OpenPose to use the skeletons as features to classify video with multiple persons per video.

The output gives me a list of skeleton joint coordinates, but there is no identification on the skeleton.

Is it safe to assume that the order in which the skeleton data is given in the JSON file doesn't change for the duration of the video? (assuming the skeleton is still detected).

Just to illustrate, if I have two skeletons being detected by OpenPose, will their order in the JSON file be constant throughout the video?

Thank you for your time!

**Comment by gineshidalgo99** [comment]
There is complete no order at all across frames. We are working in incorporating some kind of temporal consistency, but it will take (at least) a couple months more. Sorry for the inconvenience!

**Comment by n8modo** [comment]
@gineshidalgo99 I would love a pointer to the alternatives that you mention, searching 'skeleton order' and 'person keypoint order' (and variations) do not reveal the old threads. Thank you in advance.

**Comment by AlexanderBendeck** [comment]
Following up, has any kind of temporal consistency been implemented, or is the ordering still arbitrary? I can't seem to find anything in the docs.

I did try running OpenPose on a video where two people originally in the frame were joined by a third. The original two people were ordered 0 and 1 in the early frames, but were numbered 1 and 2 in the later frames (with the new figure taking the 0 spot), so it appears to still lack consistency.
