### ISSUE TITLE
Improving performance on TX2

### ISSUE THREAD

**Issue by megashigger** [CMU-Perceptual-Computing-Lab/openpose#284]
I'm working with a Jetson TX2 and am only getting ~1.5FPS, significantly lower than most of the graphics cards on the benchmarks. What's causing the low performance?  Why do desktop graphics cards do so much better, even with comparable specs?

**Comment by gineshidalgo99** [comment]
You already asked in #245 and #276 so I'm closing this (and I have no idea about TX2 so I can't answer myself).
