### ISSUE TITLE
Keypoints Angle and Number List

### ISSUE THREAD

**Issue by oguzhankarabulut** [CMU-Perceptual-Computing-Lab/openpose#286]
Thanks for your project, IT IS AMAZING!!!
But i have a question; How can i find key point number list (like knee=keypoint1, leftshoulder=keypoint2 etc..) and after finding these key points number, i want to find angles between key points? Can you help about this situation? 

Best Regards

**Comment by liutao2017** [comment]
look at
[https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/pose/poseParameters.hpp](url)

**Comment by gineshidalgo99** [comment]
doc/output.md for the list. About angles, OpenPose doesn't provide them.
