### ISSUE TITLE
Openpose with Kinect

### ISSUE THREAD

**Issue by agilesai** [CMU-Perceptual-Computing-Lab/openpose#287]
How can i integrate openpose with kinect v2 sensor?

**Comment by soulslicer** [comment]
uhm. If youre using ROS, you can use iai-kinect and get the image stream from ROS. If not, you can use libfreenect to extract it. Then, for openpose, its quite straightforward, just look at the 3_user_asynchronous.cpp file for an example on how to integrate your image stream

**Comment by gineshidalgo99** [comment]
#120

**Comment by femifapo** [comment]
Hi, has the 3_user_asynchronous.cpp file example been replaced by another tutorial? I can't seem to find it. Also is there a python equivalent?

**Comment by gineshidalgo99** [comment]
Yes, if you look at the folder, there are multiple asynchronous examples, so you can start from a further customized example for your needs.
