### ISSUE TITLE
"Starting thread(s)" -> "Killed" error on Jetson TX1 after running test on images at reduced net_resolution

### ISSUE THREAD

**Issue by marlonmisra** [CMU-Perceptual-Computing-Lab/openpose#288]
### Issue Summary
1. Installed Jetpack 3.1 according to this: https://www.youtube.com/watch?v=RJkOGMC8IrY
2. Ran scripts in Ubuntu folder to install cuda and cudnn.
2. Ran "./ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.1.sh" 
4. After executing the test command below at a significantly reduced net_resolution, I get a "Killed" error message about a minute later.

### Executed Command (if any)
`./build/examples/openpose/openpose.bin --image_dir examples/media/ --net_resolution 80x32 --logging_level 0`

### OpenPose Output (if any)
```
Starting pose estimation demo.
src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():112
src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():74
src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():15
src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():44
examples/openpose/openpose.cpp:openPoseDemo():204
Configuring OpenPose wrapper. In examples/openpose/openpose.cpp:openPoseDemo():207
./include/openpose/wrapper/wrapper.hpp:configure():440
Auto-detecting GPUs... Detected 1 GPU(s), using them all.
./include/openpose/wrapper/wrapper.hpp:configure():677
./include/openpose/wrapper/wrapper.hpp:configure():946
Starting thread(s)
./include/openpose/wrapper/wrapper.hpp:configureThreadManager():1286
./include/openpose/thread/threadManager.hpp:exec():163
./include/openpose/thread/queueBase.hpp:addPusher():360
./include/openpose/thread/queueBase.hpp:addPusher():360
./include/openpose/thread/queueBase.hpp:addPusher():360
./include/openpose/thread/threadManager.hpp:exec():168
./include/openpose/thread/thread.hpp:startInThread():138
./include/openpose/thread/thread.hpp:startInThread():138
./include/openpose/thread/thread.hpp:startInThread():138
./include/openpose/thread/thread.hpp:threadFunction():182
./include/openpose/thread/thread.hpp:threadFunction():182
./include/openpose/thread/thread.hpp:threadFunction():185
Starting initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():99
./include/openpose/thread/thread.hpp:threadFunction():182
./include/openpose/thread/thread.hpp:threadFunction():182
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():185
Killed
```

### Type of Issue
- Execution error
- Help wanted

### Your System Configuration
**Operating system**: 16.04
**CUDA version**: 8.0.84
**cuDNN version**: 6.0
**Caffe version**: Default

**Comment by marlonmisra** [comment]
@bushibushi I followed the instructions in your doc.. Those mention the TX2 only though. Should it be working for the TX1 as well? Thx!

**Comment by yaochx** [comment]
You should use 'top/htop' command to watch the memory usage.
'Killed' message means 'memory is not available, thread is killed by system'
You can try lxde window system instead of Unity and close the Chrome/Firefox etc applications, then rerun the openpose.bin instance.

**Comment by bushibushi** [comment]
Hi @marlonmisra I did not test on TX1 as specified on the doc : only TX2 and Jetpack 3.1.

It seems to me there are memory issues, but there is too little info here to guess what the exact issue is. Maybe 80x32 is still too big.

**Comment by Anonymous991001** [comment]
Can anyone tell me how to solve this. I am also going through same issue using Jetson AGX
