### ISSUE TITLE
emotions

### ISSUE THREAD

**Issue by sebastienjouhans** [CMU-Perceptual-Computing-Lab/openpose#289]
Not really an issue but more of a feature request. 

Do you guys plan to implement the ability emotions? not suggest facial but also adding a combination of body behaviour/movement/posture?

Keep up the awesome work!

**Comment by gineshidalgo99** [comment]
Unfortunately not in the short run, and no idea about in the long-distance future. That'd be really cool, but at the moment we have other research directions on mind.
