### ISSUE TITLE
Can this model tracking people or hand movement

### ISSUE THREAD

**Issue by ufohuang98** [CMU-Perceptual-Computing-Lab/openpose#29]
I want to use this to make a gesture demo to control application or other IoT.
Does it possible?

**Comment by gineshidalgo99** [comment]
Not for now, but we are planing to.

We have them both as pending extensions in our wait-list (hands should be added within 1-2 months, tracking we do not have an idea yet).

There are some methods for tracking, in case you are interested. You can take a look to #15.

Let me know if you have any other question.

**Comment by ufohuang98** [comment]
Thank you for your reply！

**Comment by heurainbow** [comment]
I am going to implement a multi-person pose tracker. I find the hand tracker already implemented is quite helpful. However, I wonder how to acquire (or update) frame ID in class HandDetector. Can I simply make mCurrentId++ when calling updateTracker()? I am not familiar with the multi-threading framework, and I am not sure if this is the right way. @gineshidalgo99

**Comment by gineshidalgo99** [comment]
I think the easiest way is to get the frame ID is by checking the Datum that is shared among the multi-threads. In particular, its `id` field. Since you will have to use the shared Datum anyway, using that ID should be the easiest. @heurainbow

**Comment by heurainbow** [comment]
@gineshidalgo99 I wonder how a webcam producer or a video producer keep the frame order sequentially in a multi-gpu case. Since each frame is processed by one gpu, there is no guarantee that each frame is processed in order. But the gui does show images in order and I couldn't find the reason in the code.

**Comment by gineshidalgo99** [comment]
There is a internal buffer to keep the order

**Comment by heurainbow** [comment]
@gineshidalgo99 If possible, please show me which file or code I should refer to, and please give me a brief explanation.

**Comment by gineshidalgo99** [comment]
This is the file, it simply uses the Datum ID to sort the frames
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/thread/wQueueOrderer.hpp

**Comment by seovchinnikov** [comment]
@gineshidalgo99 what methods for tracking did you look at?

**Comment by gineshidalgo99** [comment]
@seovchinnikov We are currently working in an expensive but accurate body recognition algorithm and in a basic bust fast LK tracking algorithm. We are trying to add them by the end of the year. Thanks

**Comment by seovchinnikov** [comment]
@gineshidalgo99 thank you,
As far as I understand will body recognition algorithm' be based on basic body keypoints detector or will it be inderpendent end-to-end part to complement library smth like https://github.com/bendidi/Tracking-with-darkflow?

**Comment by gineshidalgo99** [comment]
It'd be an extra component, that can be enabled (slower but with temporary information) or disabled (to keep the current OpenPose behavior)

**Comment by superying** [comment]
@heurainbow Are there any progress in your multi-person pose tracker? Do you implement it base on the key points from openpose?
