### ISSUE TITLE
Demo Execution Error & OpenPose Compilation Error 

### ISSUE THREAD

**Issue by iremozkal** [CMU-Perceptual-Computing-Lab/openpose#290]
Hi! 
When I execute the demo, I have an error like below. I've tried to re-download but there's no change. In fact, the file mentioned in the extension below (pose_deploy_linevec.prototxt) is actually there.
![exe hata](https://user-images.githubusercontent.com/22520332/31788177-a697a044-b516-11e7-8142-4801c63eae98.PNG)

I've also tried compiling OpenPose from the VS solution for this. I did all the steps for installation but this time I got another error that says "cannot open file OpenPose.lib" I've tried to do 'batch build' which it normally creates .lib files but it also didn't.  
![error](https://user-images.githubusercontent.com/22520332/31788460-723aec38-b517-11e7-86f8-5357f111a422.PNG)
For this error, I looked at an earlier comment but it didn't fix the problem.  [(https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/53)](url) I installed Cuda after VS2015 but still have the same error. 

I have been working on it for several weeks and tried to install and reinstall cuda&vs2015&openpose...
So i do not know where the problem is. Why demo cannot be executed? Why OpenPose project load failed? How can I get the OpenPose.lib? 

Thank you.

### Type of Issue
- Compilation/installation error
- Execution error
- Help wanted
- Question

### System Configuration
Operating system   Windows10 64Bits
Installation mode   VS2015
CUDA version    9.0
cuDNN version   7.0.3
GPU model   Intel(R) HD Graphics 4000 + NVIDIA GeForce GT 740M
Caffe version   Default from OpenPose.
OpenCV version   Default from OpenPose (3.1)

**Comment by gineshidalgo99** [comment]
This is a quite duplicated post so I must close it, but we only officially support CUDA 8 for Windows 10.

**Comment by iremozkal** [comment]
I cannot reach CUDA 8 when version 9 is available, so what can I do?
