### ISSUE TITLE
Version for other graphics cards like amd radeon graphics (OpenCL)?

### ISSUE THREAD

**Issue by sivasso** [CMU-Perceptual-Computing-Lab/openpose#292]
Please make it possible for amd64 graphics card also

**Comment by Sivagss97** [comment]
so guys please make as soon as possible for amd radeon graphics card too, 
cuz we are also waiting and this method doesnt work for us.

**Comment by gineshidalgo99** [comment]
It's in our to-do list, but we need someone that knows OpenCL for that, so we expect a version in between 2-4 months, but it depends on when we found an OpenCL guy.

**Comment by soulslicer** [comment]
Can I know what card do you have?

**Comment by davclark** [comment]
Not an expert on this, but my guess is that it will be far less work to translate the CUDA code using the ROCm / HIP tools that AMD designed for this purpose. They are working well for me on regular caffe, at least. You can find that port here:

https://github.com/ROCmSoftwarePlatform/hipCaffe

**Comment by soulslicer** [comment]
We have a version that should be released shortly.
