### ISSUE TITLE
cv::Mat problem

### ISSUE THREAD

**Issue by WangJinxinNEU** [CMU-Perceptual-Computing-Lab/openpose#293]
Can I process a Mat image( from memory) directly? The Mat format image was obtained by my own method， not webcam or a image path.

ubuntu 14.04
opencv3

**Comment by gineshidalgo99** [comment]
Yes, check the `examples/tutorial_wrapper/` examples.

**Comment by WangJinxinNEU** [comment]
I have solved this question,thanks.
