### ISSUE TITLE
Raspberry 3

### ISSUE THREAD

**Issue by totovr** [CMU-Perceptual-Computing-Lab/openpose#294]
Hello Gines! I have a question, do you think that I could use openpose in a Raspberry 3 with Linux?

**Comment by Tetsujinfr** [comment]
Actually you can not even use the rpi gpu here, no compute framework for deepnets available.
So you will have to do 100% on CPU. Hardly conceivable, you will run short on RAM here as well anyway I think.
With Rpi6 maybe...

You may want to close the issue here, not sure you will get much more I am afraid.

Tets

**Comment by gineshidalgo99** [comment]
Thanks for your answer, it's the right one I am afraid it's not possible at the moment.

**Comment by crosofg** [comment]
How about using Movidius NCS for CNN Inference in the Raspberry pi?

**Comment by lciruelo** [comment]
@crosofg have you achieved to use Movidius NCS with openpose?

**Comment by Rezar** [comment]
We have used Open pose on NVIDIA Jetson TX2, it is a bit slow but working fine. Do anybody try  to use it on another single board computer ? NVIDIA Jetson TX2 is quit expensive and not very affordable for IoT projects.

**Comment by ss32** [comment]
@crosofg @lciruelo OpenPose is not compatible with the movidius chip without some modification to the architecture.  I have tried and it won't compile.  The convolutional kernels must be <=5 and there are other restrictions, see here - https://aiyprojects.withgoogle.com/vision/#constraints

**Comment by bastianklopfer** [comment]
@ss32 @crosofg have you found a way to use Movidius NCS with openpose?

**Comment by zerometal** [comment]
how about raspberry pi with Coral USB?
