### ISSUE TITLE
Is there any way to get version 1.0

### ISSUE THREAD

**Issue by AlexLuya** [CMU-Perceptual-Computing-Lab/openpose#295]
It seems that no versioning mechanism got maintained in this repo,is there any way to get version 1.0.For some reason,I need it.

**Comment by gineshidalgo99** [comment]
On GitHub you can move to any exact commit you want, so yes you can get any version you want from OpenPose. Any version has it's version number on the commit name itself, so if you desired 1.0.0, you can move the GitHub repo to the commit called "Version 1.0.0: Hands added", you can find it in:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/commits/master?before=7ae8d776204e265ae50f11d0ddfec1e73fb24bea+140

Still, I will add during the week shortcuts for the each version release, so it's easier for all of you to locate any version release. I'll keep you updated here. Sorry for the inconveniences!

**Comment by gineshidalgo99** [comment]
Hi @AlexLuya 

All the versions can now be found in the Releases section:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases

Thank you for your feed-back. Best
