### ISSUE TITLE
GPU usage question

### ISSUE THREAD

**Issue by sihan416** [CMU-Perceptual-Computing-Lab/openpose#297]
### Issue Summary
Quick questions about performance, I was bench marking two videos, while I was looking at system performance, it appears there is minimal GPU usage but a large amount of CPU usage, is that as expected?
Also, I was running tests using GPU and CPU based rendering and got approximately the same times, is that normal, for reference I ran a two minute video, is that too short to see the difference in speeds? (I read that CPU should be faster than GPU)

### Executed Command (if any)
bin\OpenPoseDemo.exe --video examples\media\sample-data.avi --write_video output/long_video/result.avi --no_display --render_pose 2 --face --face_render 2 --hand --hand_render 2
bin\OpenPoseDemo.exe --video examples\media\sample-data.avi --write_video output/long_video/result.avi --no_display --render_pose 1 --face --face_render 1 --hand --hand_render 1

### Type of Issue
- Question

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Windows 10
**Installation mode**: Precompiled Demo
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi` in Ubuntu): GTX 1080
**Caffe version**: Default from OpenPose
**OpenCV version**: OpenPose default (only Windows);

**Comment by gineshidalgo99** [comment]
That is not expected, the GPU should be >90% usage the whole time (checkable with `nvidia-smi`). Can you try with webcam or a directory of images? If the directory of images is quite faster than the video FPS, then most probably OpenCV is not recognizing properly the video drivers (use display to debug it).

PS: CPU rendering is in practice only ~0.5 FPS faster, so you should barely see any difference.

**Comment by Tetsujinfr** [comment]
How much fps do you see on the body joint inference ? (De-activate the face and hand detection )
I would expect 8-10fps on a 1080. Less would be a sign of a pb (likely a driver thing or that you did not compile with Cuda)
Tets

**Comment by sihan416** [comment]
Thanks I figured it out, I wasn't using nvidia-smi, I was using an external GPU usage monitor.
