### ISSUE TITLE
VideoCapture (IP camera/video) could not be opened for path

### ISSUE THREAD

**Issue by hstern2** [CMU-Perceptual-Computing-Lab/openpose#298]
### Issue Summary

VideoCapture (IP camera/video) could not be opened for path: 'examples/media/video.avi'

### Executed Command (if any)

./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_keypoint_json ~/output --no_display --render_pose 0 --logging_level 0

### OpenPose Output (if any)

Starting pose estimation demo.
src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():112
src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():74

Error:
VideoCapture (IP camera/video) could not be opened for path: 'examples/media/video.avi'.

Coming from:
- src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():37
- src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():41
- src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():155
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
VideoCapture (IP camera/video) could not be opened for path: 'examples/media/video.avi'.

Coming from:
- src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():37
- src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():41
- src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():155

Abort

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Red Hat Enterprise Linux Server release 7.2 (Maipo)
**Installation mode**:  manual Makefile installation
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 8.0.61
**cuDNN version**: cudnn-8.0-linux-x64-v6.0
**GPU model** (`nvidia-smi` in Ubuntu): Tesla K80
**Caffe version**: Default from OpenPose
**OpenCV version**:  compiled from source:  3.2.0
Compiler (`gcc --version` in Ubuntu): gcc 5.4.0

**Comment by gineshidalgo99** [comment]
That's weird. Are you sure the video is there and that it can be opened with your default video player? (e.g. VLC). If so, it sounds like OpenCV codecs issue maybe, could you check you can play videos with OpenCV and/or instead using the default OpenCV from apt-get?

**Comment by gineshidalgo99** [comment]
#41

**Comment by shash29-dev** [comment]
Same issue. My specs are also same instead of:
opencv : 3.4.0
GPU: RTX 5000

**Comment by Apfelkuchenbemme** [comment]
I had the same issue, but there was an OpenCV exception raised before it, quote:

_(-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): examples\media\video.avi in function 'cv::icvExtractPattern'_

I solved it by copying the "opencv_videoio_ffmpeg450_64.dll" over to where the OpenPoseDemo.exe was built. As for "Why is that required if we use the opencv_world package?!", see PJ217's answer to a seemingly similar issue on stackoverflow:

`https://stackoverflow.com/a/61749143`
