### ISSUE TITLE
Does the hand-pose will declose the training code? 

### ISSUE THREAD

**Issue by TuringKi** [CMU-Perceptual-Computing-Lab/openpose#3]
I have read your paper "Hand Keypoint Detection in Single Images using Multiview Bootstrapping",  if you can share with us about the training details, it will be very helpful for the RGB based hand detection research!

**Comment by ZheC** [comment]
The training details are in the paper, do you mean the training data?

**Comment by akarali** [comment]
when do you plan to share the implementation of this paper ?

**Comment by TuringKi** [comment]
yes, especially the training data.

**Comment by handale88** [comment]
I also wonder when you are planning to share the implementation of this hand detection.
Please let us know. : )

**Comment by ysh329** [comment]
mark

**Comment by gineshidalgo99** [comment]
Yeah, we plan to share the test implementation, we have just done it: The hands detection code has just been released.

**Comment by TuringKi** [comment]
@gineshidalgo99 ,thanks for sharing it!  May I ask when do you declose the training datasets?

**Comment by gineshidalgo99** [comment]
@TuringKi About the dataset itself, we will release it eventually, but we need to prepare a license for it and a server where to host it and a few other details. So no defined release date for that yet, sorry!

**Comment by tamarev** [comment]
hello!
just wondering if the training data is out yet?

**Comment by Flyfries** [comment]
The hand training datasets have been released yet?

**Comment by Soledad89** [comment]
mark

**Comment by tsimk** [comment]
You can download parts of the 2D dataset here:
http://domedb.perception.cs.cmu.edu/handdb.html
We're still working on getting the 3D data up.
