### ISSUE TITLE
The system runs with low efficiency, and  is only 6.5fps, any what should I modify？

### ISSUE THREAD

**Issue by lusj** [CMU-Perceptual-Computing-Lab/openpose#30]
### Issue summary
the fps is only +=6.5

### Executed command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi

### Type of issue
- Execution error
- Help wanted

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
ubuntu 14.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
cuda 8.0
**cuDNN version**:
cudnn-8.0-linux-x64-v5.1
**GPU model** (`nvidia-smi`):
nvidia-smi
Tue May 16 15:02:50 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 0000:01:00.0      On |                  N/A |
| 36%   65C    P2   185W / 180W |   1514MiB /  4032MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1144    G   /usr/lib/xorg/Xorg                             151MiB |
|    0      1993    G   compiz                                          50MiB |
|    0     29649    C   ./build/examples/openpose/openpose.bin        1310MiB |
+-----------------------------------------------------------------------------+
Compiler (`gcc --version` on  Ubuntu):
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by lusj** [comment]
![run](https://cloud.githubusercontent.com/assets/12148289/26096828/133ac556-3a55-11e7-821f-534dac4a36fe.jpg)

**Comment by gineshidalgo99** [comment]
Hi @lusj , that is a expected speed.

You can check the benchmark section from the [README.md#openpose-benchmark](../blob/master/README.md#openpose-benchmark). The 980 is somewhere in between 1050 and 1080, so it makes sense (I just added the 980 result on that benchmark based on your 6.5 fps).

If you want to speed it up (but accuracy will drop), you can play with the flag: --net_resolution.

About accuracy, it also looks normal.

**Comment by lusj** [comment]
@gineshidalgo99  Thank you so very much for your response!!!

**Comment by gineshidalgo99** [comment]
No problem. I will close this issue then.

We are preparing a model ~30% faster (so your ~6.5 should go to ~8.5), while keeping approximately the same accuracy (it might even be slightly better in accuracy too). Check the repo every week until we release it!
