### ISSUE TITLE
Delay Problem

### ISSUE THREAD

**Issue by iremozkal** [CMU-Perceptual-Computing-Lab/openpose#300]
Movements are detected after about 10 seconds. What can be the reason of this delay or slowness of the movements' detection?

### Type of Issue
- Question

### Your System Configuration
Operating system Windows10 64Bits
Installation mode VS2015
CUDA version 8.0
cuDNN version 5.0.1
GPU model Intel(R) HD Graphics 4000 + NVIDIA GeForce GT 740M
Caffe version Default from OpenPose.
OpenCV version Default from OpenPose (3.1)

**Comment by gineshidalgo99** [comment]
The system has several internal multi-threaded queues to speed up the frame rate. But given your very weak GPU (740M), that generates a big bottleneck of several queued frames as the whole OpenPose is waiting for the GPU to process those frames.

I have just pushed a solution to that problem (it'll highly help low GPU models), so the frame rate would be slightly lower, but the delay should be highly reduced. Please, let me know the results:
```
openpose.bin --disable_multi_thread
```

Thanks

**Comment by iremozkal** [comment]
I just realized that there's no .bin file in the project so far.

**Comment by gineshidalgo99** [comment]
Sorry, that was in Ubuntu, use the equivalent steps in the doc from Windows, simply add the `--disable_multi_thread` flag.
