### ISSUE TITLE
Is it possible for having a lightweight training model for a body part only.

### ISSUE THREAD

**Issue by technicalReport** [CMU-Perceptual-Computing-Lab/openpose#302]
### Issue Summary
Current openpose detects all 18 key points of the whole body with a relative heavy model. In some case, we are only interested in a body part, e.g., left/right hand. Is it possible to have a lightweight model for a local body part?  If so, how to modify the current network? Thanks

**Comment by gineshidalgo99** [comment]
I guess it might be possible, but it does not make sense practically. I mean:
1) The amount of false positives would be too big
2) It would not make it lighter because of that. Adding/removing body parts barely affect speed/net size.
