### ISSUE TITLE
CNN inferences using Movidius NCS

### ISSUE THREAD

**Issue by crosofg** [CMU-Perceptual-Computing-Lab/openpose#303]
Is it possible to use Movidius NCS for CNN inferences to get  PAF and confidence map and rest calculation on RPI 3?

**Comment by ohadcn** [comment]
currently i've found no one that run openpose on Movidius.
have a  look at this posts:
https://ncsforum.movidius.com/discussion/224/nan-result-error-after-huge-network-was-used
I don't have the stick so I can't try their solution yet..
