### ISSUE TITLE
Compilation/installation error - CMake

### ISSUE THREAD

**Issue by jonmatthis** [CMU-Perceptual-Computing-Lab/openpose#305]
### Issue Summary

I was working through the installation instructions here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md

I got to the "OpenPose Building" section successfully and without errors

### Executed Command (if any)

make -j `nproc`

### OpenPose Output (if any)

[  0%] Performing configure step for 'openpose_caffe'
[  0%] Built target openpose_thread
[  0%] Built target openpose_filestream
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_60 sm_61
-- OpenCV found (/usr/share/OpenCV)
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Atlas (missing: Atlas_CBLAS_INCLUDE_DIR
  Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY
  Atlas_LAPACK_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindAtlas.cmake:43 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:113 (find_package)
  CMakeLists.txt:46 (include)

-- Configuring incomplete, errors occurred!
See also "/home/jon/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeOutput.log".
See also "/home/jon/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_caffe.dir/build.make:105: recipe for target 'caffe/src/openpose_caffe-stamp/openpose_caffe-configure' failed
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

### Type of Issue

- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Installation mode**: 
Following instructions from: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md

**CUDA version** 
--CUDA detected 8.0

**cuDNN version**:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md

**GPU model** (`nvidia-smi` in Ubuntu):
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Caffe version**: Default from OpenPose or custom version.

**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source: 2.4.9, 2.4.12, 3.1, 3.2, ...

Compiler (`gcc --version` in Ubuntu):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

Any help appreciated! Thanks in advance!!

**Comment by bikz05** [comment]
Looks like ATLAS is not installed. 
Try the command below and make again.
```bash
sudo apt-get install libatlas-base-dev
```

**Comment by gineshidalgo99** [comment]
That installation command has been added to `ubuntu/install_cmake.sh`, so you can either install it or run the new version of the sh script. Let us know if something else fails. Thanks.
