### ISSUE TITLE
comlilation/installation error

### ISSUE THREAD

**Issue by derekwong66** [CMU-Perceptual-Computing-Lab/openpose#307]
### Issue Summary
[ 93%] Linking CXX executable extract_features
/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.9: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/extract_features.dir/build.make:134: recipe for target 'tools/extract_features' failed
make[5]: *** [tools/extract_features] Error 1
CMakeFiles/Makefile2:809: recipe for target 'tools/CMakeFiles/extract_features.dir/all' failed
make[4]: *** [tools/CMakeFiles/extract_features.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_caffe.dir/build.make:110: recipe for target 'caffe/src/openpose_caffe-stamp/openpose_caffe-build' failed
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

### Your System Configuration
**Operating system** :ubuntu16
**Installation mode**: CMake
**CUDA version:8
**cuDNN version**:5.1
**GPU model:1070
**Caffe version**: Default from OpenPose.
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu)

**Comment by bikz05** [comment]
Check this [issue](https://github.com/BVLC/caffe/issues/1559).

**Comment by derekwong66** [comment]
@bikz05 I fixed this problem by reinstalling opencv3. change opencv dir at the cmake step

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back. For other users, this also seems to work: If you install libopencv using apt, install libtiff4 such as:
```
sudo apt-get install libtiff4-dev
```

**Comment by hosna** [comment]
I have this error :+1: 

make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

Do you have any idea why I am getting it?
the full output is:
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /BS/fashion_dataset/work/linuxbrew/bin/cc
-- Check for working C compiler: /BS/fashion_dataset/work/linuxbrew/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /BS/fashion_dataset/work/linuxbrew/bin/c++
-- Check for working CXX compiler: /BS/fashion_dataset/work/linuxbrew/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GCC detected, adding compile flags
-- Found CUDA: /usr (found version "8.0") 
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 7.1.3 found (include: /BS/alldieck-3dpeople/work/lib/cudnn/include, library: /BS/alldieck-3dpeople/work/lib/cudnn/lib)
-- Added CUDA NVCC flags for: sm_35
-- Found cuDNN: ver. 7.1.3 found (include: /BS/alldieck-3dpeople/work/lib/cudnn/include, library: /BS/alldieck-3dpeople/work/lib/cudnn/lib)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- Model already exists.
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /BS/fashion_dataset/work/openpose/build
(SMP_env)sattar@tenerife:/BS/fashion_dataset/work/openpose/build$ make -j`nproc`
Scanning dependencies of target openpose_caffe
[ 12%] Creating directories for 'openpose_caffe'
[ 25%] No download step for 'openpose_caffe'
[ 37%] No patch step for 'openpose_caffe'
[ 50%] No update step for 'openpose_caffe'
[ 62%] Performing configure step for 'openpose_caffe'
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /BS/fashion_dataset/work/linuxbrew/bin/cc
-- Check for working C compiler: /BS/fashion_dataset/work/linuxbrew/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /BS/fashion_dataset/work/linuxbrew/bin/c++
-- Check for working CXX compiler: /BS/fashion_dataset/work/linuxbrew/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "2.6.1") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.13") found components:  HL 
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_35
-- Cuda + Boost 1.55: Applying noinline work around
-- Found Atlas: /usr/include  
-- Found Atlas (include: /usr/include library: /usr/lib/libatlas.so lapack: /usr/lib/liblapack.so
CMake Error at CMakeLists.txt:85 (list):
  list sub-command REMOVE_ITEM requires list to be present.


CMake Error at src/caffe/CMakeLists.txt:30 (target_compile_definitions):
  target_compile_definitions called with incorrect number of arguments


-- Python interface is disabled or not all required dependencies found. Building without it...
-- Found Git: /usr/bin/git (found version "2.1.4") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   1.0-112-g9453eb0
--   System            :   Linux
--   C++ compiler      :   /BS/fashion_dataset/work/linuxbrew/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   OFF
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   OFF
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   OFF
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35
--   cuDNN             :   Not found
-- 
-- Install:
--   Install path      :   /BS/fashion_dataset/work/openpose/build/caffe
-- 
-- Configuring incomplete, errors occurred!
See also "/BS/fashion_dataset/work/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeOutput.log".
See also "/BS/fashion_dataset/work/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_caffe.dir/build.make:105: recipe for target 'caffe/src/openpose_caffe-stamp/openpose_caffe-configure' failed

make: *** [all] Error 2

**Comment by yurochang** [comment]
I have the same problems as you! @hosna

**Comment by hosna** [comment]
I couldnt solve it.  I notice that while building it does not find my Cudnn. I solve that problem now I am getting the file was building with newer version of proto. I already changed my proto to different version as it was suggested in other posts but yet it is not working.

**Comment by soulslicer** [comment]
@hosna This appears to happen when your CUDA version is too old

**Comment by hosna** [comment]
Also tried on CUDA 9 same problem. I could not install the openpose.

**Comment by sebo313** [comment]
Any news about this issue @hosna ?

**Comment by chengxmeng** [comment]
@hosna Have you solved this problem？I have encountered the same problem.Do you know the specific solution?

**Comment by chengxmeng** [comment]
HI,Have you solved this problem？ @yurochang

**Comment by JakeMalis** [comment]
Bump?

**Comment by marc-moreaux** [comment]
+1

**Comment by madisonpb1** [comment]
I'm experiencing a similar issue. Did anyone solve it??

**Comment by hosnasattar** [comment]
oh this is for so long time ago! I give up on openpose basically! So did not find an easy way to resolve it!
