### ISSUE TITLE
Windows portable demo run problem

### ISSUE THREAD

**Issue by jonmatthis** [CMU-Perceptual-Computing-Lab/openpose#308]
### Issue Summary
Can't get Windows standalone demo to run

### Executed Command (if any)
Clicking on OpenPoseDemo.exe

### OpenPose Output (if any)
 Gui window opens (but is blank), other window shows error: 

"F1108 16:50:31.670817   388 io.cpp:41] CheckFailed: fd != -1  (-1 vs. -1) File not found: models/pose/coco/pose_deploy_linevec.prototxt
*** Check failure stack trace: ***

...then both windows close

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** Windows 7

**Installation mode**: Windows Standalone
**CUDA version**  CUDA 9
**cuDNN version**:
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source: 2.4.9, 2.4.12, 3.1, 3.2, ...
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
It is not a GUI demo, you must open it from Windows terminal, you cannot simply double-click it. Please, follow the Windows instructions and quick_install files on `doc/`.
