### ISSUE TITLE
QT runtime error

### ISSUE THREAD

**Issue by ieyer** [CMU-Perceptual-Computing-Lab/openpose#31]
### Issue summary
libqxcb load failed. 

### Executed command (if any)
./rtpose.bin

### OpenPose output (if any)
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/huangw/workspace/openpose/.build_release/examples/openpose/platforms" ...
loaded library "/home/huangw/anaconda2/plugins/platforms/libqxcb.so"
QLibraryPrivate::loadPlugin failed on "/home/huangw/anaconda2/plugins/platforms/libqxcb.so" : "Cannot load library /home/huangw/anaconda2/plugins/platforms/libqxcb.so: (/home/huangw/anaconda2/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /home/huangw/Qt5.8.0/5.8/gcc_64/lib/libQt5XcbQpa.so.5))"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

### Type of issue
- Execution error

### Your system configuration
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

CUDA Version 8.0.44

± |master ↓7 U:2 ✗| → nvidia-smi
Wed May 17 16:18:23 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M5000        Off  | 0000:03:00.0      On |                  Off |
| 38%   34C    P8    14W / 150W |    253MiB /  8120MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1160    G   /usr/lib/xorg/Xorg                             166MiB |
|    0      1923    G   compiz                                          85MiB |
+-----------------------------------------------------------------------------+

± |master ↓7 U:2 ✗| → gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gineshidalgo99** [comment]
Please, remove this old version and install the last version (it uses openpose.bin instead of rtpose.bin). I fixed some bugs related with OpenCV with Qt support (which might be related with your problem).

Still, this looks like you are using OpenCV 3 with Qt support, so you (or somebody) compiled it from scratch in your machine. I'd say it is a OpenCV issue, so if after trying the last OpenPose version, if it does not work yet, can you try any OpenCV visualization example to check your OpenCV visualization is working fine? If not, try: a) Downloading Qt 5, and then re-compiling OpenCV from scratch with Qt support. Or b) Re-compile OpenCV without Qt support.

You can always use the OpenCV 2 version from `apt-get install libopencv-dev`, but I'd say your problem should be easily solved by my previous hints.

Let me know your results!

**Comment by k3nnywilliam** [comment]
I had similar issue but as @gineshidalgo99 mentioned in the one of the solutions above, recompiling OpenCV without Qt works for me. Openpose works perfectly fine on my end, finally! Thanks @gineshidalgo99 

@ieyer, if you still have problems with openpose I can try to help by recalling the installation steps that I did.

**Comment by gineshidalgo99** [comment]
Since some of you were able to fix this issue. I will close it. Thanks.

**Comment by gineshidalgo99** [comment]
Other option from Qt + CMake: #271
