### ISSUE TITLE
Video is not playing

### ISSUE THREAD

**Issue by nanma56** [CMU-Perceptual-Computing-Lab/openpose#313]
### Issue Summary
When I run the cmd OpenPoseDemo.exe --video people_test.mp4 --face --hand. No error was reported, but the video window is black

### OpenPose Output (if any)

C:\openpose-master\openpose-master\windows\x64\Release>OpenPoseDemo.exe --video examples\media\video.avi --face --hand
Starting pose estimation demo.
Auto-detecting GPUs... Detected 2 GPU(s), using them all.
Starting thread(s)
Real-time pose estimation demo successfully finished. Total time: 5.839329 seconds.

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Windows Server 2016
**Installation mode**: Openpose lib, VS2015  
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi` in Ubuntu): NVDA Tesla M60
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**:  OpenPose default 
Compiler (`gcc --version` in Ubuntu): VS2015

**Comment by gineshidalgo99** [comment]
As you are in a server, try with `no_display` but saving the results as JSON or something, so you can tell whether OpenPose is working and the problem is just the visualization.

Also, try a folder of images to isolate the problem to only video or not.

Let me know the results. Thanks

**Comment by nanma56** [comment]
Thank you very much for the replying. I got the problem fixed by using the openCV libraries from the Openpose demo zip package.

Another quick question, do you know if the Openpose will work with openCV 3.31

Regards

Nan
On Nov 12, 2017, at 2:25 AM, Gines <notifications@github.com<mailto:notifications@github.com>> wrote:

As you are in a server, try with no_display but saving the results as JSON or something, so you can tell whether OpenPose is working and the problem is just the visualization.

Also, try a folder of images to isolate the problem to only video or not.

Let me know the results. Thanks

**Comment by gineshidalgo99** [comment]
Any OpenCV > 2.4.9 should work (and also older versions, but I didn't test them).
