### ISSUE TITLE
What is the best way to get keypoints from cv::Mat ?

### ISSUE THREAD

**Issue by HanSeungBeom** [CMU-Perceptual-Computing-Lab/openpose#314]
Hello. I'm David and I am a senior in University from Korea.
Our team choose this openpose our graduation project.
Actually, we have little experience in dealing with such vast sources.
I'd like to ask you a few questions.

we decided to use AWS for server because of gpu performance.
so client has a web camera and sends the captured frame to AWS server.
we want AWS server to analyze frame(cv::Mat) and send keypoints to client.

my question is "what I have to do if I want to get keypoints from cv::Mat".
I am looking at your source (/examples/turorial_wrapper 1,2,3)
I want to know where is cap>>frame .. and where openpose make frame keypoints.

I am sorry that the question is too personal.
And really thank you for using this great open source.

**Comment by gineshidalgo99** [comment]
Follow the tutorial_wrapper and replace reading from an image directory for your functionality.

**Comment by sirramsalott** [comment]
I would also like this functionality, and tutorial_wrapper doesn't appear to exist any more. Would you know where I can find pointers on this?

**Comment by gineshidalgo99** [comment]
@HanSeungBeom @sirramsalott 

As an update, I simplified the tutorials to actually include examples for this specific functionality in a much simplified way. Please, check:
examples/tutorial_api_cpp/1_*, examples/tutorial_api_cpp/2_*, and examples/tutorial_api_cpp/3_*

Thanks
