### ISSUE TITLE
Interpreting output of openpose in CoreML

### ISSUE THREAD

**Issue by arjunsubway** [CMU-Perceptual-Computing-Lab/openpose#315]
Hello— I am trying to integrate openpose into an iOS app using coreML, and have successfully converted the MPI pose caffemodel to an mlmodel. When I feed in a 100x100 image to this mlmodel, I get an output that I cannot comprehend. I would really appreciate any assistance in understanding this output.

**Output**

MLMultiArray (1 X 1 X 44 X 13 X 13)

My theory is that this output represents 13X13 heatmaps for each of the 44 classes in the dataset. However, I am not sure what these 44 classes are, or whether this is even the correct theory. Again, would really appreciate any insight.

**Comment by gineshidalgo99** [comment]
Check the original paper (in the readme) for a description of the heatmaps, they include both body heatmaps and Part Affinity Fields (PAFs).
