### ISSUE TITLE
Data structure of feature points and the size of a picture

### ISSUE THREAD

**Issue by ldq77pku** [CMU-Perceptual-Computing-Lab/openpose#316]
Hello, I'm a college student coming from china. Now, I'm learning how to recognise facial expression. But I don't know why the structure of  feature points includes three dimensions, could you please tell me the meaning of the three dimensions?
And when I tested pictures, some of them could not be tested. After I changed their size, they could be tested. For example, change  100*100 pixels to 50*100 pixels. So, if there is a rule that requires a size of picture? 
Thank you for your help.

**Comment by gineshidalgo99** [comment]
Check the README for the output format information.

About the pictures, which format were they? Any image readable for OpenCV should be also readable for OpenPose. They all should work.
