### ISSUE TITLE
Compilation/installation error

### ISSUE THREAD

**Issue by Yuren-Zhong** [CMU-Perceptual-Computing-Lab/openpose#317]
### Issue Summary
When I compile openpose following the method Installation - Manual Compilation in [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md](url).
And there are many errors.
I am not sure if this problem is due to that I don't have to root access. If so, is there any possible solution that I can install openpose locally?

### Executed Command (if any)
(cnn) yurzho@srgws-08:~/openpose$ make all -j${number_of_cpus}

### OpenPose Output (if any)
CXX src/openpose/pose/poseExtractorCaffe.cpp
CXX src/openpose/pose/bodyPartConnectorCaffe.cpp
CXX src/openpose/pose/bodyPartConnectorBase.cpp
CXX src/openpose/producer/ipCameraReader.cpp
CXX src/openpose/face/faceDetectorOpenCV.cpp
CXX src/openpose/face/faceExtractorCaffe.cpp
CXX src/openpose/hand/handExtractorCaffe.cpp
CXX src/openpose/core/nmsCaffe.cpp
CXX src/openpose/core/array.cpp
CXX src/openpose/thread/defineTemplates.cpp
CXX src/openpose/core/resizeAndMergeCaffe.cpp
CXX src/openpose/core/datum.cpp
CXX src/openpose/core/point.cpp
CXX src/openpose/core/rectangle.cpp
CXX src/openpose/core/maximumCaffe.cpp
CXX src/openpose/core/netCaffe.cpp
CXX src/openpose/wrapper/defineTemplates.cpp
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/pose/poseExtractorCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/face/faceExtractorCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/pose/poseExtractorCaffe.o' failed
make: *** [.build_release/src/openpose/pose/poseExtractorCaffe.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:434: recipe for target '.build_release/src/openpose/face/faceExtractorCaffe.o' failed
make: *** [.build_release/src/openpose/face/faceExtractorCaffe.o] Error 1
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/pose/bodyPartConnectorCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/pose/bodyPartConnectorCaffe.o' failed
make: *** [.build_release/src/openpose/pose/bodyPartConnectorCaffe.o] Error 1
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/core/nmsCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/core/nmsCaffe.o' failed
make: *** [.build_release/src/openpose/core/nmsCaffe.o] Error 1
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/hand/handExtractorCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/hand/handExtractorCaffe.o' failed
make: *** [.build_release/src/openpose/hand/handExtractorCaffe.o] Error 1
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/core/resizeAndMergeCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/core/resizeAndMergeCaffe.o' failed
make: *** [.build_release/src/openpose/core/resizeAndMergeCaffe.o] Error 1
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from src/openpose/core/maximumCaffe.cpp:2:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/core/maximumCaffe.o' failed
make: *** [.build_release/src/openpose/core/maximumCaffe.o] Error 1
In file included from /home/yurzho/anaconda3/envs/cnn/include/caffe/blob.hpp:9:0,
                 from /home/yurzho/anaconda3/envs/cnn/include/caffe/net.hpp:10,
                 from src/openpose/core/netCaffe.cpp:5:
/home/yurzho/anaconda3/envs/cnn/include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
compilation terminated due to -Wfatal-errors.
Makefile:434: recipe for target '.build_release/src/openpose/core/netCaffe.o' failed
make: *** [.build_release/src/openpose/core/netCaffe.o] Error 1

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Installation mode**: manual Makefile installation (Ubuntu)
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 8.0.44

**cuDNN version**:
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 3

**GPU model** (`nvidia-smi` in Ubuntu):

**Caffe version**: custom installation by annaconda : caffe    1.0.0rc5    np112py36_0

**OpenCV version**: custom installation by annaconda : opencv    3.1.0  np112py36_1

Compiler (`gcc --version` in Ubuntu):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
The error is coming from your custom Caffe, so we cannot really help you with it. Still, that is a Caffe prepared for Python, so not sure how well it is ready for the C++ version.
You can always use the generic Caffe (and same for OpenCV if it failed too) than OpenPose provides by default if you cannot find the error in that custom Caffe. Please, let us know how you solved it so others can see it.
