### ISSUE TITLE
Possibility to only extract datapoints of skeleton with no GUI?

### ISSUE THREAD

**Issue by ddorstijn** [CMU-Perceptual-Computing-Lab/openpose#318]
### Issue Summary
I am trying to get used to the OpenPose. One thing I am wondering is that I don't see a possibilty to only extract data points without feedback though the GUI. I only need the datapoints and it would be a waste of resources if the GUI had to be updated all the time.

### Type of Issue
You might select multiple topics, delete the rest:
- Question

**Comment by gineshidalgo99** [comment]
Please, check the doc: 'no_display'
