### ISSUE TITLE
Which pose represents the same person in different frames of a video?

### ISSUE THREAD

**Issue by lz683** [CMU-Perceptual-Computing-Lab/openpose#319]
I processed a video using Openpose. The number of poses detected in different frames is different. Is it possible to know which pose represents the same person in different frames?

Looking forward to your reply.
Thank you very much.

**Comment by gineshidalgo99** [comment]
Currently OpenPose does not give information for different frames.

We hope to add some LK tracking in 1-2 months.

Duplicated of: #29
