### ISSUE TITLE
PoseExtractorCaffe Problem

### ISSUE THREAD

**Issue by bilipa** [CMU-Perceptual-Computing-Lab/openpose#322]
I create a subThread, and use my class opPredictor
which like:
class OpPredictor
{
public:
    void init(){ ...  spPredictor->initializationOnThread(); ...}
    int predict(...) {... spPredictor->forwardPass(...); spPredictor->getPoseKeypoints();}

private:
    std::shared_ptr<op::PoseExtractorCaffe> spPredictor;
}

class Do
{
    Do() {predictor->init()};

   alwaysDo(...) { predictor->predict(...)}
} 
it will throw a error : The CPU/GPU pointer data cannot  be accessed from a different thread.

but in this way ：
class Do
{
    Do() {};

   alwaysDo(...)
 {
if (! initDone)
{
predictor->init(); initDone=true;
}
 predictor->predict(...)}
}  
it will not throw that error.
* alwaysDo function will alway excute in thread.
I print the thread_id in Do() and alwaysDo(), it is different. But in theory, they belong to the same thread.

Could you give me some tips ? Thanks.

**Comment by gineshidalgo99** [comment]
I am sorry, but without format is hard to read that code. But I'd recommend you to check the wrapper/wrapper.hpp file itself, and how I join the PoseRendererGPU with the PoseExtractorCaffe (names might be slightly different). Let me know whether you are able to figure it out.

**Comment by bilipa** [comment]
I'm sorry about the format.
I'm not use the Wrapper class, it's too heavy and long(at least for me).
In shortly, I create a sub thread, and put the PoseExtractorCaffe class. 
But i find the method initializationOnThread() and forwardpass()  must  within the same function, or it will throw a wrong:The CPU/GPU pointer data cannot be accessed from a different thread.

**Comment by gineshidalgo99** [comment]
Yes, `initializationOnThread` must be used in the same thread were the functions are gonna be used. That's the only difference between `initializationOnThread` and the constructor itself. Caffe/CUDA requires initialization in the thread itself or it'd give some segmentation faults.

Is then your question solved? Feel free to ask again if something else is not clear.

**Comment by bilipa** [comment]
Yes, I see the checkThread() function in the code, but I still have some confusion.
If I create a sub thread, and put a class(for example class Predictor).
The class Predictor only have 4 method: constructor, destructor, init, predict. Does the init and predict thread id will be same?
Because I put the initializationOnThread in init,  forwardPass in predict, it will throw that error. If put initializationOnThread and forwardPass in predict, it not.
Thanks for your reply.

**Comment by gineshidalgo99** [comment]
After remembering the source code a bit, you actually should not need to use `op::SubThread`, it is just a internal function for `op::Thread`.

You should simply take a look to the examples in `examples/tutorial_thread`.

For example, what you want looks as example 2 or 3 (or a mixed of both). Rather than reading the source code of `SubThread`, try to follow those thread examples. Let me know the results.

**Comment by bilipa** [comment]
No! My  class subThread() is not op::SubThread. It is writted with my boss.

**Comment by gineshidalgo99** [comment]
OK, then I have no idea how you implemented it, but `initializationOnThread` must simply be performed in the same thread as `predict`, that's all.

**Comment by bilipa** [comment]
Ok, thanks for your help.

**Comment by yxchng** [comment]
@gineshidalgo99 doesn't that mean that it has to be initialized unnecessarily all the time when forward pass is used? my forward pass is called through a separate thread and not in a while loop

**Comment by gineshidalgo99** [comment]
@yxchng  Answered in the other thread. Don't duplicate messages.

**Comment by yxchng** [comment]
@gineshidalgo99 which other thread? Can you reference it here?

**Comment by gineshidalgo99** [comment]
@yxchng  I answered your message in #390

**Comment by Aishwary1** [comment]
@yxchng We are working on the similar project.  We need a solution to support ~100 simultaneous liveframes but openpose crashes on 4-5. How many users' liveframe can your project support per GPU?
