### ISSUE TITLE
compiling caffe error

### ISSUE THREAD

**Issue by derekwong66** [CMU-Perceptual-Computing-Lab/openpose#323]
------------------------- Compiling Caffe -------------------------
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
/usr/bin/ld: warning: libprotobuf.so.9, needed by .build_release/lib/libcaffe.so, may conflict with libprotobuf.so.14
.build_release/tools/compute_image_mean.o: In function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
compute_image_mean.cpp:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/tools/compute_image_mean.o: In function `std::string* google::MakeCheckOpString<unsigned long, int>(unsigned long const&, int const&, char const*)':
compute_image_mean.cpp:(.text._ZN6google17MakeCheckOpStringImiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringImiEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/tools/compute_image_mean.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x172): undefined reference to `google::SetUsageMessage(std::string const&)'
compute_image_mean.cpp:(.text.startup+0x2ab): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
compute_image_mean.cpp:(.text.startup+0x499): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::string const&)'
.build_release//lib/libcaffe.so: undefined reference to `google::protobuf:usr:Message:/:InitializationErrorString()bin const'/
ld.build_release/lib:/libcaffe.so: undefined  reference towarning `google:: :protobuf:libprotobuf.so.9:internal::,WireFormatLite::WriteStringMaybeAliased (int, neededstd::string const &, bygoogle::protobuf ::io:.:CodedOutputStream*)'
build_release.build_release/lib//libcaffe.so: libundefined reference/ to `googlelibcaffe.so::protobuf,: :mayio:: CodedOutputStream::WriteStringWithSizeToArrayconflict( std::stringwith const& , unsigned char*libprotobuf.so.14
).'
.build_releasebuild_release/lib/libcaffe.so/:lib /undefined reference to libcaffe.so`google::protobuf:::internal :undefined:WireFormatLite:: ReadString(google:reference:protobuf: :io::toCodedInputStream*,  std::string`*)'google
:.build_release/lib/libcaffe.so:: undefined protobufreference to :`google:::protobuf::MessageMessage::GetTypeName() :const'
:.build_release/libInitializationErrorString/libcaffe.so: (undefined reference )to `google:: protobuf::Messageconst::DebugString(') const'

Requirement already satisfied 

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):ubuntu16
**Installation mode**:bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):8.0
**cuDNN version**:5.1
**GPU model** (`nvidia-smi` in Ubuntu):1070
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu);
Compiler (`gcc --version` in Ubuntu):5

**Comment by gineshidalgo99** [comment]
It's the first time I see this error. However, it is a Caffe error not OpenPose itself, so please refer to their documentation and forums and try to install Caffe from their tutorials. After it is working, OpenPose should work fine.
