### ISSUE TITLE
GTX980,  Cuda check failed (9 vs. 0)  invalid configuration argument

### ISSUE THREAD

**Issue by JinmingZhao** [CMU-Perceptual-Computing-Lab/openpose#324]
### Issue Summary
when run the openpose.bin to get the key_points and will get this error, Whether it's cudnn5.0 or cudnn6.0.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)
Error:
Cuda check failed (9 vs. 0): invalid configuration argument

Coming from:
- src/openpose/pose/renderPose.cu:renderPoseKeypointsGpu():408
- src/openpose/utilities/cuda.cpp:cudaCheck():36
- src/openpose/pose/renderPose.cu:renderPoseKeypointsGpu():413
- src/openpose/pose/poseGpuRenderer.cpp:renderPose():168
- ./include/openpose/pose/wPoseRenderer.hpp:work():74
- ./include/openpose/thread/subThread.hpp:workTWorkers():135
- ./include/openpose/thread/subThreadQueueInOut.hpp:work():84
- ./include/openpose/thread/thread.hpp:threadFunction():203

Aborted (core dumped)

### Type of Issue
- Execution error

### Your System Configuration
**Operating system** ubuntu 16.04
**Installation mode**: CMake, sh script, 
**CUDA version**  8.0
**cuDNN version**: 5.1.10 or 6.0
**GPU model** GTX 980
**Caffe version**: dafault
**OpenCV version**: default 2.4.9
Compiler (`gcc --version` in Ubuntu):  5.4.0

**Comment by gineshidalgo99** [comment]
I am not sure why that error happens in your GPU and not in others. As I do not have that GPU to test values, I'll need you to do so and let me know which one did work for you.

You have to modify the values in `src/openpose/utilities/cuda.cpp` in this function:
`void getNumberCudaThreadsAndBlocks(dim3& numberCudaThreads, dim3& numberCudaBlocks, const Point<int>& frameSize)`

In particular, the:

**Comment by JinmingZhao** [comment]
Thanks for your advices. 
When the 
maxValue is 5243 in src/openpose/utilities/cuda.cpp:getNumberCudaThreadsAndBlocks():83
and will broken. and I modify the THREADS_PER_BLOCK_MEDIUM to THREADS_PER_BLOCK_BIG and will will be OK, just like below:
```
else if (maxValue > 1280)
                    numberCudaThreads = THREADS_PER_BLOCK_BIG; 
                    // original: numberCudaThreads = THREADS_PER_BLOCK_MEDIUM;
```
So, I think the gap is so large between THREADS_PER_BLOCK_BIG and THREADS_PER_BLOCK_MEDIUM, 
```
if (maxValue >= **16384**)
                    numberCudaThreads = THREADS_PER_BLOCK_BIG;
else if (maxValue > **1280**)
                    numberCudaThreads = THREADS_PER_BLOCK_BIG;
                    //numberCudaThreads = THREADS_PER_BLOCK_MEDIUM;
```
Thanks again!

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back. You are right, I should have used smaller gap. Please, try the new code I've just pushed and let me know if it now works with no code changes. Thanks!
