### ISSUE TITLE
Using without GPU in Ubuntu

### ISSUE THREAD

**Issue by shulace13** [CMU-Perceptual-Computing-Lab/openpose#325]
### Issue Summary

I'm trying to run openpose without using the GPU, so only the CPU.
I commented out the "USE_CUDA:=1" in the /openpose/Makefile.config file.
And also rewrote the Makefile.config file under the caffe directory so that it won't use cuDNN.

Although there are some warnings while executing make, like unused parameter 'use_cuda', I tried to run openpose and it didn't work out. 
I then tried changing the value of USE_CUDA to 0 but that didn't work either.

I am planning to buy a new GPU board so that I can run openpose...
But in the mean time, I would like to test it out right now to see what's going on!
I will appreciate the help very much, thank you.

### Executed Command (if any)
./build/examples/openpose/openpose.bin --image_dir examples/media/

### OpenPose Output (if any)
Starting pose estimation demo.

Error:
OpenPose must be compiled with the `USE_CUDA` macro definition in order to use this functionality.

Coming from:
- src/openpose/utilities/cuda.cpp:getGpuNumber():52
- src/openpose/utilities/cuda.cpp:getGpuNumber():58
- ./include/openpose/wrapper/wrapper.hpp:configure():937
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
OpenPose must be compiled with the `USE_CUDA` macro definition in order to use this functionality.

Coming from:
- src/openpose/utilities/cuda.cpp:getGpuNumber():52
- src/openpose/utilities/cuda.cpp:getGpuNumber():58
- ./include/openpose/wrapper/wrapper.hpp:configure():937

### Type of Issue

- Execution error
- Help wanted
- Question

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04
**Installation mode**: manual makefile installation
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi` in Ubuntu): GeForce GT 750M
**Caffe version**: Default from OpenPose
**OpenCV version**: 3.1 (only Ubuntu); OpenPose default 
Compiler (`gcc --version` in Ubuntu): 5.4.0

**Comment by gineshidalgo99** [comment]
There is no CPU version yet, that's why the exception error asks for CUDA. There will eventually be, but not sure about when yet.

**Comment by shulace13** [comment]
Thank you so much for the quick response.
I see, hope it'll work out soon!

**Comment by Kimhyunsu** [comment]
Is there only CPU version now?

**Comment by soyjorge** [comment]
Is the GPU version still the only version available?

**Comment by kapoorparul** [comment]
Same question...is the CPU version available yet?
