### ISSUE TITLE
My Project have some error about openpose(I cannot compile the 'OpenPose' Successfully)

### ISSUE THREAD

**Issue by WindowsDriver** [CMU-Perceptual-Computing-Lab/openpose#326]
Error LNK2001 cannot resolve external symbols "public: __cdecl op::PersonIdExtractor::PersonIdExtractor(void)" (??0PersonIdExtractor@op@@QEAA@XZ)	OpenPose	E:\openpose-master\openpose-master\windows\OpenPose\defineTemplates.cpp.obj	1

**Comment by gineshidalgo99** [comment]
It has been solved in the latest version, sorry for the problems.
