### ISSUE TITLE
Distance measurement with keypoints?

### ISSUE THREAD

**Issue by alosaulo** [CMU-Perceptual-Computing-Lab/openpose#327]
First of all, awesome project!
My issue here is more a question than an issue.
I want to ask if it is possible to estimate, using the keypoints, how far a person is from the source camera.

**Comment by aniketzz** [comment]
this project is all about 2D. you can only get x,y coordinates and not the z coordinates. so you cannot know the distance of the person if you cannot know the z coordinate. for your solution you can also refer to Openpose3D documentation.
