### ISSUE TITLE
OpenPose Can not compile successfully.(Windows7+CUDA8.0)

### ISSUE THREAD

**Issue by WindowsDriver** [CMU-Perceptual-Computing-Lab/openpose#329]
The severity code indicates that the item file line is not allowed to display status
External symbol "error LNK2001 public: class op: could not parse: Array<__int64> __cdecl op:: PersonIdExtractor:: extractIds (class op:: Array<float> & const)" (? ExtractIds@PersonIdExtractor@op@@QEAA? AV? $Array@_J@2@AEBV? $Array@M@2@@Z) OpenPose E:\\openpose-master\\openpose-master\\windows\\OpenPose\\defineTemplates.cpp.obj 1

**Comment by gineshidalgo99** [comment]
That should have been fixed in the last commit.
