### ISSUE TITLE
Custom Caffe Section on doc/installation.md

### ISSUE THREAD

**Issue by firephinx** [CMU-Perceptual-Computing-Lab/openpose#33]
### Issue summary

The custom caffe section in doc/installation.md is missing.

Just a simple pointer would be enough. For example:

Modify your CAFFE_DIR:=/path/to/caffe/distribute in the Makefile.config.Ubuntu14.example.

### Type of issue
- Enhancement / offering possible extensions / pull request / etc

**Comment by gineshidalgo99** [comment]
I guess you closed it because you found the documentation.

But other people, the `Custom Caffe` section is on the README, on [README.md#custom-caffe](../blob/master/README.md#custom-caffe)
