### ISSUE TITLE
Gstreamer error outputting to a video file (Ubuntu)

### ISSUE THREAD

**Issue by kaisark** [CMU-Perceptual-Computing-Lab/openpose#330]
### Posting rules
1. **No** questions about **training**. OpenPose only implements testing.
2. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
3. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
4. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**) explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
Update: issue turned out to be a typo on the output file directory name...

Running into a gstreamer issue related to processing video file input and outputting openpose processing data to an AVI video output file. Openpose can process and write webcam data to a video file successfully. Openpose can also process video file input successfully. But, there is an issue when openpose reads from a video file and outputs to a video file. System is using gstreamer1.0.

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

./build/examples/openpose/openpose.bin --video examples/media/video.avi -write_video /home/Videos/test.avi --logging_level 0 --disable_multi_thread

### OpenPose Output (if any)
Starting pose estimation demo.
/home/nvidia/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():112
/home/nvidia/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():74
/home/nvidia/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():15
/home/nvidia/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():44
/home/nvidia/openpose/examples/openpose/openpose.cpp:openPoseDemo():208
Configuring OpenPose wrapper. In /home/nvidia/openpose/examples/openpose/openpose.cpp:openPoseDemo():211
/home/nvidia/openpose/include/openpose/wrapper/wrapper.hpp:configure():440
Auto-detecting GPUs... Detected 1 GPU(s), using them all.
/home/nvidia/openpose/include/openpose/wrapper/wrapper.hpp:configure():657

(openpose.bin:11444): GStreamer-CRITICAL **: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed
JPEG parameter struct mismatch: library thinks size is 584, caller expects 704

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error: X
- Execution error: X

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Installation mode**: CMake (Ubuntu)
cmake -DOpenCV_DIR=/home/"${USER}"/opencv/build \
  -DCaffe_INCLUDE_DIRS=/home/"${USER}"/openpose/3rdparty/caffe/distribute/include \
  -DCaffe_LIBS=/home/"${USER}"/openpose/3rdparty/caffe/distribute/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 8.0.84

**cuDNN version**: 6

**GPU model** (`nvidia-smi` in Ubuntu): Running on Nvidia TX1. Problem also exists on Amazon AWS P2.xlarge GPU instance.

**Caffe version**: Default from OpenPose,

**OpenCV version**: compiled from source - 3.3
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_PNG=OFF \
    -DBUILD_TIFF=OFF \
    -DBUILD_TBB=OFF \
    -DBUILD_JPEG=OFF \
    -DBUILD_JASPER=OFF \
    -DBUILD_ZLIB=OFF \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_opencv_java=OFF \
    -DBUILD_opencv_python2=ON \
    -DBUILD_opencv_python3=OFF \
    -DENABLE_PRECOMPILED_HEADERS=OFF \
    -DWITH_OPENCL=OFF \
    -DWITH_OPENMP=OFF \
    -DWITH_FFMPEG=ON \
    -DWITH_GSTREAMER=ON \
    -DWITH_GSTREAMER_0_10=OFF \
    -DWITH_CUDA=ON \
    -DWITH_GTK=ON \
    -DWITH_VTK=OFF \
    -DWITH_TBB=ON \
    -DWITH_1394=OFF \
    -DWITH_OPENEXR=OFF \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \
    -DCUDA_ARCH_BIN=5.3 \
    -DCUDA_ARCH_PTX="" \
    -DINSTALL_C_EXAMPLES=ON \
    -DINSTALL_TESTS=ON \
    -DOPENCV_TEST_DATA_PATH=../opencv_extra/testdata \
    ../

Compiler (`gcc --version` in Ubuntu):
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

nvidia@tegra-ubuntu:~$ /home/nvidia/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery/deviceQuery 
/home/nvidia/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA Tegra X1"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    5.3
  Total amount of global memory:                 3981 MBytes (4174815232 bytes)
  ( 2) Multiprocessors, (128) CUDA Cores/MP:     256 CUDA Cores
  GPU Max Clock rate:                            998 MHz (1.00 GHz)
  Memory Clock rate:                             13 Mhz
  Memory Bus Width:                              64-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            Yes
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = NVIDIA Tegra X1
Result = PASS

---------------------------------------------------------------------------------
Opencv Python script that reads and writes files succesfully on my system:

import cv2
import numpy as np

\# Create a VideoCapture object
\#cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture('/home/nvidia/openpose/examples/media/video.avi')

\# Check if opened successfully
if (cap.isOpened() == False): 
  print("Unable to read from file")

\# Default resolutions of the frame are obtained.The default resolutions are system dependent.
\# We convert the resolutions from float to integer.
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))

\# Define the codec and create VideoWriter object.The output is stored in 'outpy.avi' file.
out = cv2.VideoWriter('outpy.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 30, (frame_width,frame_height))

while(True):
  ret, frame = cap.read()

  if ret == True:
    \# Write the frame into the file 'output.avi'
    out.write(frame)

    # Display the resulting frame
    cv2.imshow('frame',frame)

    # Press Q on keyboard to stop recording
    if cv2.waitKey(1) & 0xFF == ord('q'):
      break

  \# Break the loop
  else:
    break

\# When everything done, release the video capture and video write objects
cap.release()
out.release()

\# Closes all the frames
cv2.destroyAllWindows()

**Comment by gineshidalgo99** [comment]
So, just to isolate the error, I guess that these 2 are working right?
```
./build/examples/openpose/openpose.bin --video examples/media/video.avi
```
```
./build/examples/openpose/openpose.bin --video examples/media/video.avi -write_images /home/Images
```

**Comment by kaisark** [comment]
The code is working. The issue can be closed.

./build/examples/openpose/openpose.bin --video examples/media/video.avi -write_video /home/nvidia/Videos/test.avi
