### ISSUE TITLE
OpenPose position information

### ISSUE THREAD

**Issue by iremozkal** [CMU-Perceptual-Computing-Lab/openpose#331]
Hi,
I will use OpenPose for the upper body detection in a game on Unity. 
I need only the position information. The positions of the points that you put on detected joints. I do not need the rendered points or the camera frame to fit the skeleton. Just the pose infromation. The pose positions are going to be placed to the avatar. 
Where can I get these funcitons that return detected body positions? 

### Type of Issue
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
Check the doc and `examples/tutorial_wrapper`
