### ISSUE TITLE
Build Error in openpose3D

### ISSUE THREAD

**Issue by aniketzz** [CMU-Perceptual-Computing-Lab/openpose#334]
i am trying to build openpose3D project. i am getting 16 errors related to "Severity	Code	Description	Project	File	Line	Suppression State
"Error LNK2001	unresolved external symbol __imp___glutCreateWindowWithExit OpenPose3DReconstruction	C:\Users\acer.LAPTOP-DAK58UAQ\Downloads\Compressed\openposemaster \windows\OpenPose3DReconstruction\renderer.cpp.obj"
All the 16 errors are similar to this above errors. 
I am unable to understand the error. Please help me with this. I have attached the screen of the error.
![screenshot 15](https://user-images.githubusercontent.com/23217704/33005763-4e84a52e-cded-11e7-9488-4cb04457c9d4.png)

**Comment by gineshidalgo99** [comment]
That's the FreeGLUT library. Maybe trying to re-downloading it (and try to be sure to use the 64-bit version, not the 32-bit one). Let me know if it still fails. Thanks

**Comment by aniketzz** [comment]
i reinstalled the FreeGLUT library 64 bit. but the issue remains the same..

**Comment by aniketzz** [comment]
i am able to solve all the **15/16 errors** so far but still i am getting 1 error as cannot open "**freeglut.lib**" file.
I tried copy pasting the lib file by downloading again and again but no use. the error remains same. please help me if there is any other way or am i missing something.
Any help will be appreciated. Thanks

**Comment by ohadcn** [comment]
On what project did it failed? on all of them? have you verified that freeglut is found in the right directory?

**Comment by aniketzz** [comment]
It failed on openpose3d project..

**Comment by ohadcn** [comment]
have you installed skinnaker sdk?
https://www.ptgrey.com/spinnaker-sdk

**Comment by aniketzz** [comment]
Yes i hav installed that ...

**Comment by aniketzz** [comment]
i have solve all the error .. The freeglut error is also solved now.
I have a quick question. Do i need Blackfly S camera to run this openpose3d project or can i use Kinect as well... and can you specify the exact number of cameras needed for the project to run. and can i use (say 3) different cameras for it to work...
I tried with my webcam and kinect as a normal camera. but now i got an error message in the command prompt as "no camera detected".  Thanks for all the helps so far. and please check this query as well...
 
![screenshot 103](https://user-images.githubusercontent.com/23217704/34146248-3ec76778-e4bf-11e7-8fd0-4a23463fa42b.png)

**Comment by dibusch** [comment]
How did you solve the  freeglut error @aniketzz?

**Comment by dibusch** [comment]
solved. I set the linker to ".. \ .. \ 3rdparty \ windows \ freeglut \ lib \ x64 \ freeglut.lib".

**Comment by aniketzz** [comment]
yes thats one way of solving freeglut error @dibusch ... but i just copied the freeglut.lib file in " \ .. \ 3rdparty \ windows \freeglut\freeglut.lib   and it started working for me now...
