### ISSUE TITLE
Ubuntu. Cmake build Error at OpenPoseConfig.cmake

### ISSUE THREAD

**Issue by HanSeungBeom** [CMU-Perceptual-Computing-Lab/openpose#335]
Hello.I am doing another project with Openpose and I build my source code completely just a hour ago.
but It is not working now. I don't know why it is. can you give me a little hint ?.. I searched all of your issue and google . but there are no hint.

this is my CMakeLists.txt (I wrote this from your "installation_cmake.md, example CMakeLists.txt.)

--------------------------------------------------------------------------------------------------------------------------------------
cmake_minimum_required(VERSION 2.8.7)
add_definitions(-std=c++11)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules")
find_package(GFlags)
find_package(Glog)
find_package(OpenCV)
find_package(OpenPose REQUIRED)

include_directories(${OpenPose_INCLUDE_DIRS} ${GFLAGS_INCLUDE_DIR} ${GLOG_INCLUDE_DIR} ${OpenCV_INCLUDE_DIRS})

add_executable(Server.bin Server.cpp PracticalSocket.cpp)

target_link_libraries(Server.bin ${OpenPose_LIBS} ${GFLAGS_LIBRARY} ${GLOG_LIBRARY} ${OpenCV_LIBS})
target_link_libraries(Server.bin pthread)

--------------------------------------------------------------------------------------------------------------------------------------

that CMakeList.txt worked just a hour ago.. but It is not working now.
"cmake ." error message is like that

----------------------------------------------------------------------------------------------------------------------------------------

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
CMake Error at /home/hansb/openpose/cmake/OpenPoseConfig.cmake:6 (include):
  include could not find load file:
    /home/hansb/lib/OpenPose/OpenPose.cmake
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/hansb/openpose/examples/user_code/CMakeFiles/CMakeOutput.log".

--------------------------------------------------------------------------------------------------------------------------

I think One possible reason is that I did "cmake . && make" at openpose main folder.
so it run and I was surprised and stopped it.. 
I thought maybe It had a problem because I stopped, so I did it again and It was completed.
but "cmake . " is not working. 

can I get a advice..? Thank you.

**Comment by gineshidalgo99** [comment]
Please, follow the instructions and run it as `cmake ..` as they indicate.

**Comment by HanSeungBeom** [comment]
Thanks for your reply and sorry that I didn't see it carefully.
