### ISSUE TITLE
Noticeable lag (200ms) on 60fps webcam + 4x 1080Ti

### ISSUE THREAD

**Issue by carstenschwede** [CMU-Perceptual-Computing-Lab/openpose#336]
### Issue Summary
Running on 60fps camera with 4x 1080Ti. Framerate is limited by camera (~60fps), but there is a noticeable lag of around ~200ms. I assume that either the cameras video buffer or an internal thread queue is buffering frames for processing. Are there any option to discard old frames or clear the buffer? A simple opencv program does not exhibit similar behaviour.

### Type of Issue
- Performance

### Your System Configuration
**Operating system**:
Ubuntu 16.04.3 LTS

**Installation mode**:
cmake

**CUDA version**:
CUDA Version 8.0.61

**cuDNN version**:
cuDNN 6.0.21

**GPU model**:
4x GTX 1080 Ti, 11GB, Driver version 384.98

**Caffe version**: 
Default from OpenPose

**OpenCV version**:
OpenCV 3.3.0 compiled from source

**Compiler:**
gcc 5.4.0

**Comment by gineshidalgo99** [comment]
We used internal queues to process each frame on a different GPU, but they introduced that lag.

So unfortunately, the only way to reduce the lag is to disable multithreading (there is an option for it, something like `disable_multithreading`), but then it'd only work with 1 GPU, so the frame rate will go down 4x in your case.

If you are also visualizing the result, it might help not using for OpenPose the GPU used for display visualization (with `num_gpu` and `num_gpu_start`).

But in general, I could not think of a better way to get both that speed and smaller lag (I am always open to solutions!)

**Comment by carstenschwede** [comment]
Do newer versions improve on this issue? Is lag reduced?

**Comment by gineshidalgo99** [comment]
Our target and current research efforts is towards a faster OpenPose, so ideally yes, the faster the model is, the more FPS and lower lag that it will have.

**Comment by carstenschwede** [comment]
Great! Have there been significant speed improvements since end of november 2017?

**Comment by Doremii46** [comment]
Do you know how to measure or calculate the lag time?

**Comment by gineshidalgo99** [comment]
[Profile](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed). the OpenPose speed. For 1-GPU or CPU-only systems (use `--disable_multi_thread` for simplicity in multi-GPU systems for latency measurement), the latency will be roughly the sum of all the reported measurements.

(I will add this to the doc, thanks for the question)

**Comment by Doremii46** [comment]
For the noticeable lag like **carstenschwede** mentioned, is that ~200ms lag the sum of all the reported measurements?  
I feel there is a delay time in Openpose and it seems not frame cycle time.
