### ISSUE TITLE
Folder structure inconsistency when linking libcaffe.so Ubuntu 14.04 - CMake

### ISSUE THREAD

**Issue by AlbertoCenzato** [CMU-Perceptual-Computing-Lab/openpose#339]
### Issue Summary

**Foreword**
Following the instructions in [installation_cmake.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md). I have executed [cmake_install.sh](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/ubuntu/install_cmake.sh) to install Cuda, CuDNN and all dependencies. 

**Issue**
Then I ran cmake and make as specified in  [installation_cmake.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md) to build OpenPose. Make builds Caffe without problems. When it's building OpenPose and it's time to link libcaffe.so though it fails finding libcaffe.so. 
Make looks for caffe/lib/libcaffe.so while the file is in caffe/lib/x86_64-linux-gnu/libcaffe.so. Not a big deal, I moved it to the correct path. Probably a CMakeLists.txt inconsistency between OpenPose and Caffe.

### Executed Command (if any)
ubuntu/install_cmake.sh
configured with cmake gui (default settings), configuration files in build directory
cd build
make

### Make Output
[ 39%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/cvMatToOpOutput.cpp.o
[ 39%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/scaleAndSizeExtractor.cpp.o
[ 40%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/rectangle.cpp.o
[ 40%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/nmsCaffe.cpp.o
[ 41%] Building CXX object src/openpose/CMakeFiles/openpose.dir/core/resizeAndMergeBase.cpp.o
[ 41%] Building CXX object src/openpose/CMakeFiles/openpose.dir/experimental/tracking/defineTemplates.cpp.o
[ 42%] Building CXX object src/openpose/CMakeFiles/openpose.dir/experimental/tracking/personIdExtractor.cpp.o
[ 42%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/keypointJsonSaver.cpp.o
[ 43%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/defineTemplates.cpp.o
[ 43%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/fileSaver.cpp.o
[ 44%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/imageSaver.cpp.o
[ 44%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/videoSaver.cpp.o
[ 45%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/fileStream.cpp.o
[ 45%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/heatMapSaver.cpp.o
[ 46%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/keypointSaver.cpp.o
[ 46%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/cocoJsonSaver.cpp.o
[ 47%] Building CXX object src/openpose/CMakeFiles/openpose.dir/filestream/jsonOfstream.cpp.o
[ 47%] Building CXX object src/openpose/CMakeFiles/openpose.dir/thread/defineTemplates.cpp.o
[ 48%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/defineTemplates.cpp.o
[ 48%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/gui.cpp.o
[ 49%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/guiInfoAdder.cpp.o
[ 49%] Building CXX object src/openpose/CMakeFiles/openpose.dir/gui/frameDisplayer.cpp.o
make[2]: *** No rule to make target `caffe/lib/libcaffe.so', needed by `src/openpose/libopenpose.so.1.1.0'.  Stop.
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [all] Error 2

### Type of Issue
- Compilation/installation error
- Enhancement

### Your System Configuration
**Operating system**: Ubuntu 14.04.5 LTS
**Installation mode**: CMake
**CUDA version**: 8.0.61
**cuDNN version**: 5.1
**GPU model**: GeForce GT 540M
**Caffe version**: Default from OpenPose
**OpenCV version**: compiled from source version 3.2
Compiler: gcc 5.4.1

**Comment by ipa-nhg-dd** [comment]
I have same issue how to resolve it ?

**Comment by AlbertoCenzato** [comment]
When I run CMake build process for caffe libcaffe.so is built and placed in my_openpose_dir/build/caffe/lib/x86_64-linux-gnu. The name of x86_64-linux-gnu folder depends on which architecture you are building for, so yours could be different from mine. Simply move the content of this folder in your_openpose_dir/build/caffe/lib; it is where make looks for libcaffe.so when building openpose (as specified by the error message: `make[2]: *** No rule to make target caffe/lib/libcaffe.so', needed by src/openpose`). Then build again openpose exactly as done before, this time libcaffe.so should be in the right place. It's a dirty workaround, but it does the job if you don't want to mess up with CMakeLists.txt

**Comment by huangjiancong1** [comment]
I have same issue how to resolve it ?

**Comment by bikz05** [comment]
Can you guys let us know the CMake version you are using? (Use the command `cmake --version`).

I fixed this error on machine by updating CMake. Here are the steps I used --

```
sudo apt-get remove cmake
sudo apt-get update
sudo apt-get upgrade
# Download the latest release of cmake from https://cmake.org/download/
wget https://cmake.org/files/v3.10/cmake-3.10.2.tar.gz
tar xvzf cmake-3.10.2.tar.gz
cd cmake-3.10.2
./configure
make
sudo make install
```
I will update with a neater solution soon.
