### ISSUE TITLE
resolution format (1920*1080) invalid

### ISSUE THREAD

**Issue by zg9uagfv** [CMU-Perceptual-Computing-Lab/openpose#34]
### Issue summary
openpose didn't support 1920*1080 video,why?

Thanks.

### Executed command (if any)
./.build_release/examples/openpose/openpose.bin --video ~/Downloads/deep\ learning/datasets/mp4/chunxilu1.mp4 --num_gpu 2  --resolution 1920*1080

### OpenPose output (if any)
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Error, resolution format (1920*1080) invalid, should be e.g., 960x540 

Coming from:
- examples/openpose/openpose.cpp:gflagsToOpParameters():211

### Type of issue
You might select multiple topics, delete the rest:
- Question

### Your system configuration
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
OpenCV 3.2
**Operating system** (`lsb_release -a` on Ubuntu):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
8.0
**cuDNN version**:
5_5.1
**GPU model** (`nvidia-smi`):
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K2200        Off  | 0000:03:00.0      On |                  N/A |
| 42%   39C    P8     1W /  39W |    461MiB /  4040MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro K2200        Off  | 0000:04:00.0     Off |                  N/A |
| 42%   40C    P8     1W /  39W |      1MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1011    G   /usr/lib/xorg/Xorg                             190MiB |
|    0      1796    G   compiz                                         135MiB |
|    0      2324    G   ...el-token=658504E00CA47FDB0199A5AA20B8E4EB   134MiB |
+-----------------------------------------------------------------------------+
**Caffe version**: Default from OpenPose or custom version.
Compiler (`gcc --version` on Ubuntu):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by gaborpapp** [comment]
try '1920x1080' not '1920*1080'

**Comment by gineshidalgo99** [comment]
@gaborpapp is right.
I will close this issue since it is solved by that typo correction. Post again if you have related issues, or open a new issue thread if you have other kind of issues. Thanks!
