### ISSUE TITLE
fatal error C1083: Cannot open include file: 'Spinnaker.h': No such file or directory

### ISSUE THREAD

**Issue by evehal** [CMU-Perceptual-Computing-Lab/openpose#340]
Hi,cannot compile Tutorial OpenPose3DReconstruction in vs2015
fatal error C1083: Cannot open include file: 'Spinnaker.h': No such file or directory
thanks for any help

**Comment by Zakeiswo** [comment]
I also have the same problem. Did you use the Blackfly S cameras or rewrite the WPointGrey class to use your own cameras?

**Comment by aniketzz** [comment]
did you copy the directories and contents of the Spinnaker to the correct directory in openpose project directory. refer the installation of openpose3d. You can also try reinstalling the spinnaker for Blackfly S camera and try using the sdk. It almost worked for me .. I am getting errors with openGL freeGlut library. if you know anything about the error i get please let me know .. refer #334 for my query

**Comment by gineshidalgo99** [comment]
As aniketzz says, follow the instructions for 3D OpenPose and download the extra libraries. Thanks
