### ISSUE TITLE
Can't use OpenPose in my project

### ISSUE THREAD

**Issue by brunoua** [CMU-Perceptual-Computing-Lab/openpose#342]
### Issue Summary

I tried to use openpose in my project, but I think I'm having errors without cmakelists, which is this:

```
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(openpose)
SET(CMAKE_CXX_COMPILER "g++")
SET(CMAKE_BUILD_TYPE Debug)
SET(CMAKE_CXX_FLAGS "-std=c++0x")
find_package(CUDA REQUIRED)
INCLUDE_DIRECTORIES(
	${CUDA_INCLUDE_DIRS}
	/home/ieeta/openpose/include
	/home/ieeta/openpose/3rdparty/caffe/include
)
ADD_EXECUTABLE(openpose openpose.cpp)
TARGET_LINK_LIBRARIES(openpose
	${CUDA_LIBS}
	/home/ieeta/openpose/build/lib/libopenpose.so
	/home/ieeta/openpose/3rdparty/caffe/build/lib/libcaffe.so ${Caffe_LIBS}
)
```

### Executed Command (if any)

After running cmake .

When I run make I find the error below.

### OpenPose Output (if any)

`/usr/bin/ld: CMakeFiles/openpose.dir/openpose.cpp.o: undefined reference '_ZN6google21ParseCommandLineFlagsEPiPPPcb'
//usr/lib/x86_64-linux-gnu/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/openpose.dir/build.make:96: recipe for target 'openpose' failed
make[2]: *** [openpose] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose.dir/all' failed
make[1]: *** [CMakeFiles/openpose.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

### Type of Issue

- Help wanted

### System Configuration
**Operating system**:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Installation mode**: CMake, sh script (Ubuntu)

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): Cuda 8.0.61

**cuDNN version**: cuDNN 5.1

**GPU model** (`nvidia-smi` in Ubuntu):

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 378.13                 Driver Version: 378.13                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 0000:65:00.0      On |                  N/A |
|  0%   33C    P8    13W / 275W |    405MiB / 11171MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       995    G   /usr/lib/xorg/Xorg                             227MiB |
|    0      1678    G   compiz                                         175MiB |
+-----------------------------------------------------------------------------+

**Caffe version**: Default from OpenPose

**OpenCV version**: compiled from source. Version 3.3.1

GCC Compiler: 5.4.0

**Comment by brunoua** [comment]
@gineshidalgo99 can you help me with this issue? I think that is a problem with caffe but i'm not sure

Thanks!

**Comment by gineshidalgo99** [comment]
### Posting rules
4. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.

**Comment by brunoua** [comment]
@gineshidalgo99 I apologize for not having set the system specifications. I already edited my post.
Can you help me with this problem?

Thank you,
Bruno Barbosa

**Comment by gineshidalgo99** [comment]
Allow some time for @bikz05 to answer. He knows better about CMake than I do. Thanks!

**Comment by bikz05** [comment]
@brunoua looks like you are not linking against gflags. I recommend you check out the [sample CMakeLists.txt](https://github.com/bikz05/openpose/blob/master/doc/installation_cmake.md#openpose-from-other-projects) that we created to use OpenPose in other projects.

**Comment by brunoua** [comment]
@bikz05 Thank you in advance for your availability.
I have tried with your example too:

`cmake_minimum_required(VERSION 2.8.7)

add_definitions(-std=c++11)
link_directories(/home/ieeta/openpose/3party/caffe/build/install/lib)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules")

find_package(GFlags)
find_package(Glog)
find_package(OpenCV)
find_package(OpenPose REQUIRED)

include_directories(${OpenPose_INCLUDE_DIRS} ${GFLAGS_INCLUDE_DIR} ${GLOG_INCLUDE_DIR} ${OpenCV_INCLUDE_DIRS})

add_executable(openpose.bin openpose.cpp)

target_link_libraries(openpose.bin ${OpenPose_LIBS} ${GFLAGS_LIBRARY} ${GLOG_LIBRARY} ${OpenCV_LIBS})`

However I have the error when i run "cmake ." :

```
CMake Warning at CMakeLists.txt:7 (find_package):
  By not providing "FindGFlags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GFlags", but
  CMake did not find one.

  Could not find a package configuration file provided by "GFlags" with any
  of the following names:

    GFlagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "GFlags" to CMAKE_PREFIX_PATH or set
  "GFlags_DIR" to a directory containing one of the above files.  If "GFlags"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Warning at CMakeLists.txt:8 (find_package):
  By not providing "FindGlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "Glog" with any of
  the following names:

    GlogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "Glog" to CMAKE_PREFIX_PATH or set
  "Glog_DIR" to a directory containing one of the above files.  If "Glog"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/ieeta/Desktop/BrunoBarbosa/Projeto
```

And i get the same error that i said early on make.

Any suggestion?

thank you,
Bruno Barbosa

**Comment by bikz05** [comment]
Okay, I see. You need to copy these 2 files [FindGFlags.cmake](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/cmake/Modules/FindGFlags.cmake) and [FindGlog.cmake](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/cmake/Modules/FindGlog.cmake) into `<project_root_directory>/cmake/Modules`. Create the directory, if it doesn't exist.

**Comment by brunoua** [comment]
@bikz05 Thank you so much for the help, now I've got it.

**Comment by AVINASH18794** [comment]
CMake Error at CMakeList.txt:11
No CMAKE_CXX_COMPILER could be found.

**Comment by ashxpltz** [comment]
Same for me also

 No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

**Comment by mehdydousty** [comment]
Hi Everybody,
I am quite new to this field, so I have some novice questions. So far I have succesfully installed the Openpose, that is I can easily run demo mode. I was wondering if anybody could guide me on how to run C++ example code available in the example/openpose section. I am using Mac-xcode.

**Comment by AlexMacdonlad** [comment]
Hi Everybody, I am quite new to this field, so I have some novice questions. So far I have successfully installed Openpose, that is I can easily run demo mode. I was wondering if anybody could guide me on how to run C++ example code available in the example/openpose section.Particularly, after importing the example file into Xcode, I get an error of gflags/gflags.h' file not found
I appreciate the help in advance
