### ISSUE TITLE
Multiple gpus, PoseExtractorCaffe

### ISSUE THREAD

**Issue by osamazhar** [CMU-Perceptual-Computing-Lab/openpose#345]
Hi,

I am using openpose to extract the keypoints of the person in the camera not using the wrapper. In the following:

op::PoseExtractorCaffe poseExtractorCaffe{netInputSize, netOutputSize, outputSize, FLAGS_scale_number, poseModel, FLAGS_model_folder, FLAGS_num_gpu_start};

I am not able to see any argument related to the number of gpus to use. I have two gpus in my computer and with he above initialization, seems like I can't use both of them. While when I run openpose.bin the pre-compiled program it utilizes two gpus. I request you to help me in this.

Thanks for replying in advance.

**Comment by gineshidalgo99** [comment]
`PoseExtractorCaffe` simply takes an image and returns keypoints, it does not use >1 GPU.

The multi-threading (using several GPUs) happens in the `thread` module, and I configure the `Wrapper` to split the images across different GPUS.

So you can either:
1. Copy the wrapper and simplify it for your specific case.
2. Check the `tutorial_thread` to know how to also use the thread module.
3. Create your own thread structure.

Feel free to post what you ended up using, so other might also use that guide.
