### ISSUE TITLE
Any Docker Images updates?

### ISSUE THREAD

**Issue by HoracceFeng** [CMU-Perceptual-Computing-Lab/openpose#347]
Hi,

I know this may be answered before, BUT I still haven't seen any docker images updates for new users. To be honest, the configuration of environment is really difficult, especially for users who are now familiar with cmake compile. I try to use other openpose project written by python tensorflow, but they are too slow and cannot support the real time webcam actually. Any suggestion? 

Thank you so much!

**Comment by sberryman** [comment]
I've been using nvidia-docker2 (also works with the now depreciated nvidia-docker v1) with success on two of my boxes. One machine has two 1080 TI's and the other a standard 1080 running Ubuntu 16. They only have the drivers installed according to nvidia's docker install guide and everything is run inside containers.

Sample:
https://gist.github.com/sberryman/6770363f02336af82cb175a83b79de33

Probably quite a bit of room to shrink the dockerfile size down and make it easier to change out opencv, openpose versions etc but should be enough to get you going. Dockerfile has been hacked together to keep it working with 1.2.1 and is probably safe to upgrade OpenCV version 3.4.0.

I also don't recall why I blow away 3rdparty/caffe and pull from openpose's fork but it works and this isn't designed for production use.

**Comment by moiseevigor** [comment]
Hi @sberryman, you're inspired me to produce this [Dockerfile - OpenPose 1.4.0, OpenCV, CUDA 8, CuDNN 5, Python2.7](https://gist.github.com/moiseevigor/11c02c694fc0c22fccd59521793aeaa6 ) that uses latest Caffe build through the `bvlc/caffe:gpu` image.

**Comment by sberryman** [comment]
@moiseevigor - Glad it was able to help you! Any chance you can share what you are using OpenPose for?

**Comment by moiseevigor** [comment]
Using as a state-of-art benchmark for pose estimation and evaluating for some projects, not able to disclose more for now.

**Comment by ExSidius** [comment]
I've got another Dockerfile working with CUDA 10 if anybody is interested.

[https://github.com/ExSidius/openpose-docker](https://github.com/ExSidius/openpose-docker)

[https://cloud.docker.com/repository/docker/exsidius/openpose/general](https://cloud.docker.com/repository/docker/exsidius/openpose/general)

**Comment by gineshidalgo99** [comment]
I will close this, but I have added a link to your Docker files in our doc/installation.md (it will be pushed in the next commit). Thanks for the help!

And feel free to post new Dockerfiles in here, I will keep adding them to that file :)

**Comment by johndpope** [comment]
UPDATE - so seems nvidia has switched things up under the hood with nvidia-runtime container - you don't need the custom etc/docker/daemon.json

see https://github.com/NVIDIA/nvidia-docker
for latest info

N.B. - you can actually just invoke nvidia runtime like this
**docker run --runtime=nvidia** 

```shell
# If you have nvidia-docker 1.0 installed: we need to remove it and all existing GPU containers
docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
sudo apt-get purge -y nvidia-docker

# Add the package repositories
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

# Install nvidia-docker2 and reload the Docker daemon configuration
sudo apt-get install -y nvidia-docker2
sudo pkill -SIGHUP dockerd

# Test nvidia-smi with the latest official CUDA image
docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
```

**Comment by neonb88** [comment]
@gineshidalgo99  Hi, how can I submit a push request for a README?  Otherwise, please make the reference to ExSidius' image the first one on `https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#operating-systems`.  The first docker link's Caffe is broken, and I wasted at least a day's productivity trying to get it to work.  It might take you 15 minutes to update https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md, and it might save the world's hackers 10+ days.

Hopefully people keep this updated, so if nvidia or caffe pushes something that breaks `ExSidius`'s docker image, a valid docker image will still be present

Finally, thanks for all your hard work, Gines!  This is far and away the standard for 2-D pose detection, at least in the U.S.  Hopefully development continues on this project even if you move on to other projects

-nxb

**Comment by gineshidalgo99** [comment]
You can easily do a Pull request! 
Simply go to https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md (if that's the page you wanna edit) and click in the pen icon. It should allow you to edit it and do a pull request about it.

**Comment by neonb88** [comment]
Cool, submitted!  I guess I'm now officially a very very minor contributor to an Open Source project, haha
