### ISSUE TITLE
Best way to train OpenPose on custom data?

### ISSUE THREAD

**Issue by megashigger** [CMU-Perceptual-Computing-Lab/openpose#349]
We've got some data that's more suited to our use case and would like to train OpenPose on it. 

Is the Multi Person Pose Estimation repo (https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation) still the best starting point to train on custom data? Thanks.

**Comment by gineshidalgo99** [comment]
Yes, we intend to release a more updated version after we release the next OpenPose models (in at least a couple months more), but for the current ones that one is the one used.
