### ISSUE TITLE
How to train the net myself

### ISSUE THREAD

**Issue by andyqian2015** [CMU-Perceptual-Computing-Lab/openpose#350]
Hi @gineshidalgo99 ,thank you for your appreciation work. now I have puzzle when I try to retrain the net by myself, I cannot find the file figure out  how to retrain the net. I would appreciate if  you can give me some suggest.

**Comment by gineshidalgo99** [comment]
https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
