### ISSUE TITLE
Please add freeglut download to get* scripts

### ISSUE THREAD

**Issue by ohadcn** [CMU-Perceptual-Computing-Lab/openpose#352]
freeglut library is used on OpenPose3DReconstruction sample, but the libs downloading scripts do not include it.
If I had write permissions on the repo (e,g: http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/) I would upload it myself and send a Pull request.

freeglut build for windows (not by me) can be found here:
https://www.transmissionzero.co.uk/software/freeglut-devel/

**Comment by aniketzz** [comment]
yes i too have exactly the same issue .. i am getting 1 error as "**cannot open input file freeglut.lib**". please let me know if you get anything on this.

**Comment by ohadcn** [comment]
@aniketzz sory for the late reply.
You can download freeglut from the second link I gave and set the search path accordingly (just extract it to openpose\3rdparty\windows directory)

**Comment by aniketzz** [comment]
@ohadcn  i have downloaded the freeglut library from the same website you have providedand i have download this one "freeglut 3.0.0 MSVC Package". It didn't work for me as well.

**Comment by gineshidalgo99** [comment]
I'll try to add an *.sh file to auto-download it too (similar to the other dependencies) in the couple weeks.

**Comment by gineshidalgo99** [comment]
Added and updated in the instructions. Thanks
