### ISSUE TITLE
How to set custom picture data(video frame) form memory to find body？

### ISSUE THREAD

**Issue by beyond6699** [CMU-Perceptual-Computing-Lab/openpose#354]
### Issue Summary

How to set custom picture data(video frame) form memory to find body？
I see there is a image_dir to set path or camera to use opencv capture ,But I want set picture data(video frame) from my custom memory,How to do this?
I use DirectShow to capture webcamare frame, and I want use this frame to find body,Not use
opencv capture.How can I do this?

### Type of Issue

- Question

### Your System Configuration
**Operating system** : windows 10
**Installation mode**: VS2015
**CUDA version** :8.0
**cuDNN version**:5.1
**GPU model** :nvidia
**Caffe version**: Default from OpenPose
**OpenCV version**: OpenPose default
Compiler :VS2015

**Comment by gineshidalgo99** [comment]
There is an option for video: `video` for OpenCV capture. If you need your custom input , simply check `examples/tutorial_wrapper`.
