### ISSUE TITLE
Kinect SDK instead of Spinnaker SDK in openpose 3D

### ISSUE THREAD

**Issue by aniketzz** [CMU-Perceptual-Computing-Lab/openpose#356]
Can i use Kinect SDK 2.0 instead of Spinnaker SDK . If so then can any one tell me how can i do so.

**Comment by aniketzz** [comment]
can anyone lease specify me in the openpose 3D, do i need the exact same camera that is been used or can i use any 3D camera insted.

**Comment by gineshidalgo99** [comment]
You can use any SDK you want, you will simply have to implement your custom C++ code.

The current code is for point-grey cameras, if you use different brand, you'll need to change more code.
