### ISSUE TITLE
Error using flag --write_video

### ISSUE THREAD

**Issue by ximenesfel** [CMU-Perceptual-Computing-Lab/openpose#358]
### Posting rules
1. **No** questions about **training**. OpenPose only implements testing.
2. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
3. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
4. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
When I tried to use the flag --write_video, openpose output the below error. I've tried to search where to set 'render_output' but unfortunately, I can't find.

### Executed Command (if any)
./build/examples/openpose/openpose.bin --video /home/carnd/test.MP4  --write_video output/ --write_keypoint_json output/ --render_pose 0 --no_display

### OpenPose Output (if any)
Error:
In order to save the rendered frames (`write_images` or `write_video`), you must set `render_output` to true.

Coming from:
- ./include/openpose/wrapper/wrapper.hpp:configure():461
- ./include/openpose/wrapper/wrapper.hpp:configure():955
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
In order to save the rendered frames (`write_images` or `write_video`), you must set `render_output` to true.

Coming from:
- ./include/openpose/wrapper/wrapper.hpp:configure():461
- ./include/openpose/wrapper/wrapper.hpp:configure():955

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
**Installation mode**: sh script 
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA 8
**cuDNN version**: cuDNN 5.1
**GPU model** (`nvidia-smi` in Ubuntu): GRID K520
**Caffe version**: Default from OpenPose
**OpenCV version**: `apt-get install libopencv-dev` 
Compiler (`gcc --version` in Ubuntu): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
As the error says, you need to enable `render_pose` if you wanna save frames (`render_output` actually refers to that flag).

But I understand why you might want to save the original frames and the keypoint JSON at the same time. So it should be possible with the new version I have just pushed. Thanks.

**Comment by ximenesfel** [comment]
Thanks for the quick response. I'm only looking in the main flags in demo documentation but you defined another in the text bellow. I will change the render_pose flag to 1 or 2. Thanks.

**Comment by gineshidalgo99** [comment]
Yeah I'm sorry, `render_output` was the initial one, but it was splitted into `render_pose` `render_hand` and `render_face` after introducing face and hands (I forgot to update that text).

**Comment by ximenesfel** [comment]
No problem. You're doing a great job !!! Thanks a lot to provide this code in public domain.
