### ISSUE TITLE
Loading the xml/yaml/json keypoint generated data into opencv and render as video

### ISSUE THREAD

**Issue by kaisark** [CMU-Perceptual-Computing-Lab/openpose#359]
Is there example code/tools to load the xml/yaml/json keypoint generated data into opencv and render as video? fileStream.hpp??? I just want to see the skeleton keypoint data without the original background image...

I am using opencv 3.3 with caffe on ubuntu 16.

Thanks.

./build/examples/openpose/openpose.bin --video /home/nvidia/openpose/input/video.avi -write_video /home/nvidia/openpose/output/video/video.avi -write_keypoint /home/nvidia/openpose/output/video -write_keypoint_format "json"  -write_coco_json /home/nvidia/openpose/output/video/write_coco_json-video.json

{
    "pose_0": {
        "type_id": "opencv-nd-matrix",
        "sizes": [ 6, 18, 3 ],
        "dt": "f",
        "data": [ 0.0, 0.0, 0.0, 1.63033005e+02, 8.66368866e+01,
            8.89896929e-01, 1.78800919e+02, 8.47416611e+01,
            8.86810303e-01, 1.92508881e+02, 1.12167625e+02,
            7.03759730e-01, 1.94475891e+02, 1.29807632e+02,
            3.70512843e-01, 1.45511032e+02, 8.68119659e+01,
            7.47562170e-01, 1.33800613e+02, 1.18011902e+02,
            5.45420051e-01, 1.35714874e+02, 1.35667908e+02,
            2.72589952e-01, 1.80830139e+02, 1.35713699e+02,
            7.97624469e-01, 1.96360718e+02, 1.76830566e+02,
            6.96083426e-01, 2.08167175e+02, 2.14079422e+02,
            4.93851781e-01, 1.61087814e+02, 1.41543793e+02,
            7.19213784e-01, 1.63140198e+02, 1.90518173e+02,
            5.59031546e-01, 1.65094772e+02, 2.41462723e+02,
            3.23034644e-01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.67029144e+02,
            6.90192108e+01, 2.22305417e-01, 1.49373581e+02,
            6.91253510e+01, 9.47999358e-02, 2.65000824e+02,
            1.00475838e+02, 3.76689732e-01, 2.72746368e+02,
            1.23890213e+02, 8.98387194e-01, 2.51230896e+02,
            1.27839256e+02, 7.72993922e-01, 2.45468811e+02,
            1.63122894e+02, 7.11490273e-01, 2.43453262e+02,
            1.94396957e+02, 4.69640434e-01, 2.90435516e+02,
            1.20043892e+02, 8.81775677e-01, 3.04216187e+02,
            1.61099426e+02, 8.37879896e-01, 3.10009949e+02,
            1.90554306e+02, 7.45619297e-01, 2.68854126e+02,
            1.92517303e+02, 7.59419382e-01, 2.76699677e+02,
            2.37529358e+02, 8.03770125e-01, 3.00226868e+02,
            2.70867554e+02, 6.72538102e-01, 2.92407990e+02,
            1.90529572e+02, 7.66174436e-01, 2.98297455e+02,
            2.35575531e+02, 7.29984999e-01, 3.04200500e+02,
            2.72745331e+02, 7.67690778e-01, 2.61050446e+02,
            9.84370575e+01, 3.09654504e-01, 2.70878601e+02,
            9.65190811e+01, 3.45676750e-01, 2.57128448e+02,
            1.00333267e+02, 1.48649991e-01, 2.74768066e+02,
            9.84791718e+01, 3.32468420e-01, 0.0, 0.0, 0.0,
            1.05853467e+03, 6.71161652e+01, 8.27124715e-01,
            1.07220215e+03, 6.51502762e+01, 7.80262291e-01,
            1.08581091e+03, 8.46509171e+01, 5.57573557e-01,
            1.08386768e+03, 1.02333672e+02, 4.15406287e-01,
            1.05059277e+03, 6.90633926e+01, 7.55993128e-01,
            1.05251831e+03, 8.86534729e+01, 6.03551507e-01,
            1.05848645e+03, 1.08235191e+02, 4.70336288e-01,
            1.07422424e+03, 1.04389297e+02, 7.82204926e-01,
            1.07997400e+03, 1.43467896e+02, 7.02348471e-01,
            1.08779358e+03, 1.65161087e+02, 6.90604150e-01,
            1.06038477e+03, 1.10227615e+02, 7.45504498e-01,
            1.06239136e+03, 1.43483582e+02, 6.72268152e-01,
            1.06236963e+03, 1.67084259e+02, 4.17137355e-01, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 1.06044495e+03, 4.55484314e+01,
            3.08232665e-01, 1.04475916e+03, 4.95041161e+01,
            2.97033191e-01, 3.84599121e+02, 6.32000771e+01,
            5.94274342e-01, 3.70769714e+02, 8.86560364e+01,
            7.37714529e-01, 3.66799561e+02, 8.86558304e+01,
            8.63192141e-01, 3.66942993e+02, 1.29782379e+02,
            8.64251852e-01, 4.04123535e+02, 1.31848618e+02,
            8.53449225e-01, 3.82463959e+02, 8.68033447e+01,
            7.26044893e-01, 3.92291321e+02, 1.25878723e+02,
            2.07746595e-01, 4.11862396e+02, 1.27809799e+02,
            1.91270888e-01, 3.84567200e+02, 1.63159607e+02,
            7.32061565e-01, 4.13830292e+02, 2.21840118e+02,
            7.96688020e-01, 4.07968475e+02, 2.80675293e+02,
            7.65626311e-01, 3.90362244e+02, 1.63066528e+02,
            6.70182288e-01, 3.84553925e+02, 2.25752136e+02,
            8.66476297e-01, 3.90382202e+02, 2.84546722e+02,
            7.59463370e-01, 3.82566071e+02, 5.73596344e+01,
            5.99957168e-01, 0.0, 0.0, 0.0, 3.68885406e+02,
            6.31964989e+01, 6.94858789e-01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            6.52879028e+02, 8.66667023e+01, 6.84058785e-01,
            6.78330383e+02, 8.47205505e+01, 5.57151794e-01, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 6.31279236e+02, 8.86587372e+01,
            6.25975132e-01, 6.05907776e+02, 1.35723358e+02,
            7.65723288e-01, 5.96037659e+02, 1.06298851e+02,
            5.27584672e-01, 6.80335144e+02, 1.86625397e+02,
            6.79192185e-01, 6.66625977e+02, 2.74717407e+02,
            8.26367974e-01, 6.94031128e+02, 3.53227600e+02,
            7.85423040e-01, 6.46963806e+02, 1.94402878e+02,
            6.44809663e-01, 6.35267822e+02, 2.78687866e+02,
            7.78296351e-01, 6.58794617e+02, 3.64832092e+02,
            7.24303484e-01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.64696228e+02,
            5.53561592e+01, 1.33042380e-01, 6.33358093e+02,
            5.92768135e+01, 2.57797509e-01, 1.20728601e+03,
            3.96755219e+01, 7.00356737e-02, 1.20927832e+03,
            4.94694748e+01, 4.06074733e-01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            1.21506665e+03, 8.86307297e+01, 5.15745401e-01,
            1.21512915e+03, 1.19970337e+02, 4.59844261e-01,
            1.21525244e+03, 1.47498566e+02, 3.56626719e-01,
            1.21509094e+03, 8.67921600e+01, 5.03318965e-01,
            1.21511841e+03, 1.18125656e+02, 4.76349950e-01,
            1.21525586e+03, 1.47469467e+02, 3.57263863e-01, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    }
}

-------------------------------------------------------------------------------------------------------------------------------------------
--coco json
[
	{
		"image_id":0,
		"category_id":1,
		"keypoints":[
			0,0,0,0,0,0,0,0,0,149.374,69.1254,1,167.029,69.0192,1,145.511,86.812,1,178.801,84.7417,1,133.801,118.012,1,192.509,112.168,1,135.715,135.668,1,194.476,129.808,1,161.088,141.544,1,180.83,135.714,1,163.14,190.518,1,196.361,176.831,1,165.095,241.463,1,208.167,214.079,1
		],
		"score":0.458438
	},
	{
		"image_id":0,
		"category_id":1,
		"keypoints":[
			265.001,100.476,1,270.879,96.5191,1,261.05,98.4371,1,274.768,98.4792,1,257.128,100.333,1,290.436,120.044,1,251.231,127.839,1,304.216,161.099,1,245.469,163.123,1,310.01,190.554,1,243.453,194.397,1,292.408,190.53,1,268.854,192.517,1,298.297,235.576,1,276.7,237.529,1,304.201,272.745,1,300.227,270.868,1
		],
		"score":0.642497
	},
	{
		"image_id":0,
		"category_id":1,
		"keypoints":[
			0,0,0,0,0,0,0,0,0,1044.76,49.5041,1,1060.44,45.5484,1,1050.59,69.0634,1,1072.2,65.1503,1,1052.52,88.6535,1,1085.81,84.6509,1,1058.49,108.235,1,1083.87,102.334,1,1060.38,110.228,1,1074.22,104.389,1,1062.39,143.484,1,1079.97,143.468,1,1062.37,167.084,1,1087.79,165.161,1
		],
		"score":0.465346
	},

**Comment by gineshidalgo99** [comment]
skeleton keypoint data without the original background image --> there is a flag to disable it, check doc/demo_overview.md --> `--disable_blending` flag
