### ISSUE TITLE
Fail to detect keypoints when only lower limbs are visible

### ISSUE THREAD

**Issue by guxiao0822** [CMU-Perceptual-Computing-Lab/openpose#360]
![video_1490200501_rotate_000000000324_rendered](https://user-images.githubusercontent.com/18308220/34331845-6c2fc444-e965-11e7-8fd4-1a80fffed9f8.png)

I have met with a problem. When the camera is close to the subject and only the lower limbs are visible, it sometimes cannot detect the joints correctly. But I found that when only upper body is visible, it shows strong robustness. Is there any solution to fixing this problem? 

Thanks a lot!

**Comment by yanchao12122** [comment]
You should train your own model for this special task.
The current model is trained on normal images.

**Comment by postgraduater** [comment]
it is a good
 question

**Comment by gineshidalgo99** [comment]
@yanchao12122  answer is the best one. We cannot make it work on this scenario without harming the general cases

**Comment by djramakrishna** [comment]
You should train the model with your own custom dataset containing the images that are specific to your use case. As the current model is trained on BODY25, COCO it may not give the desired results in this specific use case.
