### ISSUE TITLE
【Ubuntu C++】If I want to only use the third GPU in all detected GPUs to run openpose

### ISSUE THREAD

**Issue by postgraduater** [CMU-Perceptual-Computing-Lab/openpose#361]
"Starting pose estimation demo.
Auto-detecting GPUs... Detected 7 GPU(s), using them all.
..."

As showed above, openpose defaults to use all of the detected GPU 
If I want to only use the third GPU in all detected GPUs to run openpose, which command/function should I use in the source code? Thank you!

**Comment by gineshidalgo99** [comment]
Please check the doc/demo_overview.md
