### ISSUE TITLE
How does the matlab version openpose specify certain GPUs to run openpose?

### ISSUE THREAD

**Issue by postgraduater** [CMU-Perceptual-Computing-Lab/openpose#362]
Thank you very much!
If I want to only use the third GPU in all detected GPUs to run openpose,
the doc/demo_overview.md just says how the c++ version openpose specifies certain GPUs (./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 2 --num_gpu_start 1).
How does the matlab version openpose specify certain GPUs to run openpose?

**Comment by gineshidalgo99** [comment]
There is no Matlab version in OpenPose so far, it's in our to-do list, but not in the short term.
