### ISSUE TITLE
Can't compile when passing CUDA_ARCH_NAME=Manual

### ISSUE THREAD

**Issue by peetonn** [CMU-Perceptual-Computing-Lab/openpose#365]
When trying to compile openpose by default, it fails with error:

```
nvcc fatal   : Unsupported gpu architecture 'compute_20'
```

When trying to avoid building for `compute_20` by passing [flags](https://github.com/BVLC/caffe/pull/1667):

`cmake -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="35 52 60 61 70" -DCUDA_ARCH_PTX="70" ..`

it still fails with the same error and in configuration output I can see this:

```
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
```

with additional notice at the end:

```
  Manually-specified variables were not used by the project:

    CUDA_ARCH_BIN
    CUDA_ARCH_NAME

```

Why does it ignore flags I pass for cmake?

**Comment by gineshidalgo99** [comment]
### Posting rules
4. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.

**Comment by dmaugis** [comment]
well, you can close it if you like, but untill this issue is solved it will be difficult to create a docker out of openpose: in a docker environment the build system has no access to cuda, hence cannot find the architecture => it tries to build all architectures, including compute_20 wich is deprecated => build fails.

**Comment by canmor** [comment]
@peetonn CUDA_ARCH_NAME is a typo, should be CUDA_ARCH.

And, the warning message: `Manually-specified variables were not used by the project` is comes from cmake it self, not the cmake script, cmake will check whether each of variables you passed had been **actually** used, and warns for those used variables.
