### ISSUE TITLE
Low, 8.0 FPS with a GTX 1080 (8GB of memory)

### ISSUE THREAD

**Issue by RoboEvangelist** [CMU-Perceptual-Computing-Lab/openpose#367]
CUDA 8.0.61
cDNN 6.0
Latest Caffe
GTX 1080
Ubuntu 16.04.03

I can't get the demo video to run faster than 8 FPS. This is the command I used:
~/openpose/build/examples/openpose/openpose.bin --video examples/media/video.avi --render_pose 2

I also ran a grayscale, VGA video that I have, and it wont go beyond 10 FPS (14 FPS if I run it "real time") 
Is there a way that I can run a VGA size video, or higher, at 20+ FPS?

Thanks,

**Comment by gineshidalgo99** [comment]
That's the normal speed. You can check the README for the benchmark of GPUs and for tips for speed up.

**Comment by RoboEvangelist** [comment]
Thanks.

Also, why is this duplicated? Can you send me the link to the previously asked question?

**Comment by gineshidalgo99** [comment]
There are several questions about how to make it faster and about GPU benchmark in general in the issues
