### ISSUE TITLE
what does connectBodyPartsCpu() function do?

### ISSUE THREAD

**Issue by zg9uagfv** [CMU-Perceptual-Computing-Lab/openpose#37]
### Issue summary
I can't understand the connectBodyPartsCpu() function, could you give me some more details on it?

Thanks.

### Type of issue
You might select multiple topics, delete the rest:
- Help wanted
- Other (type your own type)

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
It performs a greedy algorithm to interconnect body parts in order to estimate the people on each image. Check the paper for more technical details:
[https://arxiv.org/abs/1611.08050](https://arxiv.org/abs/1611.08050)
