### ISSUE TITLE
use openpose in a new qt gui

### ISSUE THREAD

**Issue by shuang0713** [CMU-Perceptual-Computing-Lab/openpose#370]
i want to know if i can use  openpose in a new project. i didn't find any methods  about windows system.there are only methods for ubuntu system.  i want to add qt gui  to the openpose.

**Comment by gineshidalgo99** [comment]
If you want to use any library with Qt, you must include the libs and DLLs into the Qt project.

**Comment by shuang0713** [comment]
thanks for the answer. What i want to do is adding a interface to the 2_user_synchronous project.i have already adding libs and DLLs to the project. and after copy the codes to the main.cpp, the qt files seems wrong.
 i am beginner to learn this.could you tell me if there any easy methods to realize this.just like i can choose the video file through the button. thank you very much.

**Comment by hengchuan** [comment]
ooo

**Comment by gineshidalgo99** [comment]
This is a Qt usage issue, not a OpenPose issue. (still, there is newer post with example Qt.pro files)

**Comment by whycn** [comment]
@gineshidalgo99 I'm sorry but I can't find the example QT.pro file in your repo. Could you please tell me where it is. Thanks.
