### ISSUE TITLE
Can your approach be used to extract motion capture data from a single video or just 2d pixel coordinates?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [CMU-Perceptual-Computing-Lab/openpose#371]
I read https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md and noticed that the output has no z component.

Can your approach be used to extract motion capture data from a single video or just 2d pixel coordinates?

**Comment by gineshidalgo99** [comment]
It's only 2D pixel data.

**Comment by ErfolgreichCharismatisch** [comment]
Then I would like to change this into a feature request.
