### ISSUE TITLE
[v1.2.1] POSE_COCO_BODY_PARTS not available through the API anymore

### ISSUE THREAD

**Issue by HWiese1980** [CMU-Perceptual-Computing-Lab/openpose#372]
Hi everyone,

until recently I've been using `POSE_COCO_BODY_PARTS` that had been defined in `poseParameters.hpp` to get the names of the body parts corresponding to their index. 

As of b3c04ec0d475f15c05a4e2140da28961092adc90 that array isn't available anymore and I wonder how I'm supposed to get the body part name per body part index now. I'd be happy if anyone could elaborate on that change.

Cheers!

**Comment by gineshidalgo99** [comment]
Sorry, the doc was outdated.

Please, check the latest version of doc/output.md and feel free to ask any confusing part of it.

Thanks!

**Comment by HWiese1980** [comment]
Thanks a lot!
