### ISSUE TITLE
using Cmake-GUI to build openpose in Ubuntu

### ISSUE THREAD

**Issue by huangjiancong1** [CMU-Perceptual-Computing-Lab/openpose#373]
### Issue Summary
In terminal, i used 
`make -j4`

 to building the OpenPose after created the /build under the /openpose ,and the terminal output:

> [ 84%] [ 85%] make[2]: *** No rule to make target `caffe/lib/libcaffe.so', needed by `src/openpose/libopenpose.so.1.1.0'.  Stop.
make[2]: *** Waiting for unfinished jobs....
Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/errorAndLog.cpp.o
[ 85%] Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/cuda.cpp.o
Building CXX object src/openpose/CMakeFiles/openpose.dir/utilities/keypoint.cpp.o
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
make: *** [all] 

reference： [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md#custom-caffe](url)

### Executed Command (if any)
` bash ./ubuntu/install_cmake.sh`
`sudo apt-get install cmake-qt-gui`
`cd build/`
`make -j4`

### Type of Issue
You might select multiple topics, delete the rest:
- This method to install OpenPose is very easy but there is something wrong in libcaffe.so, hoping that we can solve it together

- And i will try the next method [Installation - Script Compilation meanwhile](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation---script-compilation)

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):

> No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Installation mode**: CMake OpenCV caffe CUDA CUDNN

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):CUDA Version 8.0.61

**cuDNN version**:

> #define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

**GPU model** (`nvidia-smi` in Ubuntu): nvidia-390.12 and NVIDIA GTX1050
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu);

**Comment by huangjiancong1** [comment]
use the other method ,[ Installation - Script Compilation meanwhile](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation---script-compilation)
to compile caffe,
after running: 
`make all -j4 && make distribute -j4`

output:

> AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status

**Comment by huangjiancong1** [comment]
I can compile caffe which download from [https://github.com/BVLC/caffe.git  ](https://github.com/BVLC/caffe.git  ) and test the caffe success.
Can i use this caffe to run Openpose?
After , i compile the /openpose package, some issue output:

> CXX src/openpose/utilities/openCv.cpp
CXX src/openpose/utilities/errorAndLog.cpp
CXX src/openpose/utilities/keypoint.cpp
CXX src/openpose/utilities/cuda.cpp
NVCC src/openpose/pose/bodyPartConnectorBase.cu
nvcc fatal   : redefinition of argument 'std'
make: *** [.build_release/cuda/src/openpose/pose/bodyPartConnectorBase.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by gineshidalgo99** [comment]
Please, try removing OpenPose. Re-downloading the latest version, and performing the installation steps again. It seems like some step was missing.

**Comment by huangjiancong1** [comment]
After Re-downloading the latest version and compiled the caffe, there are some issue in compile openpose:

>src/openpose/pose/bodyPartConnectorCaffe.cpp:2:30: fatal error: caffe/blob.hpp: No such file or directory
     #include <caffe/blob.hpp>
                              ^
compilation terminated.
make: *** [.build_release/src/openpose/pose/bodyPartConnectorCaffe.o] Error 1
make: *** Waiting for unfinished jobs....
src/openpose/pose/poseExtractorCaffe.cpp:2:30: fatal error: caffe/blob.hpp: No such file or directory
     #include <caffe/blob.hpp>
                              ^

**Comment by gineshidalgo99** [comment]
It's not finding Caffe. Are you sure Caffe is in 3rdparty/caffe?

**Comment by huangjiancong1** [comment]
Sure and i can `make runtest` under /3rdparty/caffe success, i think there have something error about my cuda, i can not test cuda 8.0, my nvidia driver is nvidia-390.

**Comment by huangjiancong1** [comment]
makefile in the /openpose 

> ## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# uncomment to disable IO dependencies and corresponding data layers
# USE_OPENCV := 0
# USE_LEVELDB := 0
# USE_LMDB := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
OPENCV_VERSION := 3

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61
# Deprecated
# CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
# 		-gencode arch=compute_20,code=sm_21 \
# 		-gencode arch=compute_30,code=sm_30 \
# 		-gencode arch=compute_35,code=sm_35 \
# 		-gencode arch=compute_50,code=sm_50 \
# 		-gencode arch=compute_52,code=sm_52 \
# 		-gencode arch=compute_60,code=sm_60 \
# 		-gencode arch=compute_61,code=sm_61 \
# 		-gencode arch=compute_61,code=compute_61

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
# ANACONDA_HOME := $(HOME)/anaconda
# PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		# $(ANACONDA_HOME)/include/python2.7 \
		# $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include

# Uncomment to use Python 3 (default is Python 2)
# PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /usr/lib /usr/local/lib
# PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
# WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# NCCL acceleration switch (uncomment to build with NCCL)
# https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
# USE_NCCL := 1

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := /3rdparty/caffe/distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @

**Comment by gineshidalgo99** [comment]
I'm confused, I thought you were using CMake, as you specify in your first message, not Makefile. Please, follow the exact steps from the installer in CMake, do not mix them with the old installer.

**Comment by huangjiancong1** [comment]
I see, and i use cmake like my first message, caffe compile success, but openpose compile output error at last,

> [100%] Building CXX object examples/tutorial_wrapper/CMakeFiles/2_user_synchronous.bin.dir/2_user_synchronous.cpp.o
Linking CXX executable 4_user_input_processing_output_and_datum.bin
Linking CXX executable 1_custom_post_processing.bin
/usr/bin/ld: CMakeFiles/4_user_input_processing_output_and_datum.bin.dir/4_user_input_processing_output_and_datum.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/tutorial_thread/4_user_input_processing_output_and_datum.bin] Error 1
make[1]: *** [examples/tutorial_thread/CMakeFiles/4_user_input_processing_output_and_datum.bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/1_custom_post_processing.bin.dir/1_custom_post_processing.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/tutorial_add_module/1_custom_post_processing.bin] Error 1
make[1]: *** [examples/tutorial_add_module/CMakeFiles/1_custom_post_processing.bin.dir/all] Error 2
Linking CXX executable 1_user_asynchronous_output.bin
/usr/bin/ld: CMakeFiles/1_user_asynchronous_output.bin.dir/1_user_asynchronous_output.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/tutorial_wrapper/1_user_asynchronous_output.bin] Error 1
make[1]: *** [examples/tutorial_wrapper/CMakeFiles/1_user_asynchronous_output.bin.dir/all] Error 2
Linking CXX executable 2_user_synchronous.bin
/usr/bin/ld: CMakeFiles/2_user_synchronous.bin.dir/2_user_synchronous.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/tutorial_wrapper/2_user_synchronous.bin] Error 1
make[1]: *** [examples/tutorial_wrapper/CMakeFiles/2_user_synchronous.bin.dir/all] Error 2
make: *** [all] Error 2

And i will reinstall the system to reinstall everything again.

**Comment by gineshidalgo99** [comment]
I have seen that error in some old Ubuntu 14. Usually updating the system helps a lot with these kind of compiler errors (and rebooting after this command):
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove`

**Comment by huangjiancong1** [comment]
which version of gcc g++、cmake-gui、nvidia-* driver and opencv are good for ubuntu14 and cuda 8.0

**Comment by atasoglou** [comment]
I am compiling fine under a clean Ubuntu 14, so I don't think it is OpenPose related. Could that be OpenCV related? Or could it be that you are using any updated/downgraded lib in your system?
This also sometimes helps: `sudo ldconfig` when the OS cannot find libraries.

**Comment by huangjiancong1** [comment]
I use the opencv by type `sudo apt-get install libopencv-dev`,issue output.... and i change to use opencv 3.3.0(test success), issue output....

Which opencv version you using? 

Can you share your  ubuntu 14.so

**Comment by atasoglou** [comment]
`libopencv-dev` is version 2.4.8, if I am not wrong. In my case, I am using OpenCV 3. I haven't tested it with version 2 to be honest. [I installed it manually](https://www.learnopencv.com/install-opencv3-on-ubuntu/).

**Comment by gineshidalgo99** [comment]
I've just seen the error says: `src/openpose/libopenpose.so.1.1.0`. Please, download the latest version, old versions might have old bugs. Otherwise, compile Caffe by your own, and then tell OpenPose where your Caffe is located with CMake-GUI

**Comment by huangjiancong1** [comment]
Dose it mean that everything it installed? 

> 2018-01-21 15:37:31 (1021 KB/s) - ‘hand/pose_iter_102000.caffemodel’ saved [147344024/147344024]

Models downloaded
------------------------- OpenPose Models Downloaded -------------------------

------------------------- OpenPose Installed -------------------------

------------------------- Caffe and OpenPose Installed -------------------------

huang@huang-Inspiron-7577:~/openpose$ ls

**Comment by gineshidalgo99** [comment]
Yes it does, but I thought you were using the CMake installer rather than the sh script. If you wanna import it to Qt, I think you prefer to install it with CMake.

**Comment by KevinQian97** [comment]
Hi I am also encountered with such problem.
Seems openpose  can't detect cuda correctly.
It keeps telling me that it can't find cuda which I have already installed.

**Comment by gineshidalgo99** [comment]
@KevinQian97 You can manually introduce it with Qt-gui

**Comment by KevinQian97** [comment]
@gineshidalgo99 
Thanks for your immediate reply！
I am using the sever without desktop. So i use CMake Command Line for configuration.
I am not sure if i could at that into the CMake.txt?

**Comment by KevinQian97** [comment]
In fact I tried to change the commend
form 
cmake ..
to
cmake .. -DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
But it still doesn't work

**Comment by KevinQian97** [comment]
Sorry
I am so silly that I forgot to delete the folder build.......
Sorry for bothering
