### ISSUE TITLE
CPU version - Running Without CUDA

### ISSUE THREAD

**Issue by Adeelyousaf** [CMU-Perceptual-Computing-Lab/openpose#375]
What if one has no NVIDIA card and want to run code without CUDA?

**Comment by gineshidalgo99** [comment]
We're finishing a CPU version. We'll keep you posted here, but it's ~100x slower than Titan X in Windows (from ~10 FPS to ~0.1...), and ~50x slower in Ubuntu (~0.2 FPS)

**Comment by Oknuz** [comment]
When will you present CPU version? I'm really looking forward to it.

**Comment by dfoley84** [comment]
+ 1 for CPU version would be great to try it out on a Embedded system

**Comment by gineshidalgo99** [comment]
Ideally within the next couple of months. Note again the speed will not be real-time.

**Comment by MasterScrat** [comment]
Is this development code already available somewhere?

**Comment by seovchinnikov** [comment]
+1 for cpu version

**Comment by gineshidalgo99** [comment]
It was released a few weeks back. Feel free to try it.
