### ISSUE TITLE
Demo detects nothing.

### ISSUE THREAD

**Issue by lw396285v** [CMU-Perceptual-Computing-Lab/openpose#376]
### Issue Summary
I compiled the whole stuff on ubuntu 16.04 using the script.
I followed the installation tutorial and everything seemed to be OK, however when I run the two women kissing demo cideo, there is nothing else except the original video playing, and the bottom-left corner shows 'people: 0'.
I also tried other videos however the problem is the same, nothing been detected.

I'm not familiar with this project, the question maybe stupid. Hope anyone can help, thanks.

### Executed Command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04
**Installation mode**: sh script
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: v6
**GPU model** (`nvidia-smi` in Ubuntu):  GTX1070
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev`
Compiler (`gcc --version` in Ubuntu): 5.4.0

**Comment by gineshidalgo99** [comment]
So with the default video there is no detected people either?
./build/examples/openpose/openpose.bin --video examples/media/video.avi
???

**Comment by johaq** [comment]
I had the same problem earlier today.
The download of the models failed for some reason (I did not notice at the time). But after downloading again everything works fine. Maybe check the size of your models, they are around 200MB.

**Comment by lw396285v** [comment]
Thanks, man.
I delete and redownload the models, and the demo works fine.
I don't know what happened when I first downloaded them, and what is surprising is no error comes up when the program is running.
May be you can add a MD5 check in the getModel script, and such problem will not happen.

**Comment by gineshidalgo99** [comment]
Thanks for the suggestions, we've actually already added it in our next CMake release, which should be pushed in within 1 week.

**Comment by kechunliu** [comment]
I had the same problem today. 
I have tried re-download the models, but still get no output when running the demo.

**Comment by sylerip** [comment]
I have got the same problem too.
I am using the Window portable version from the official release.

**Comment by AswinkarthikeyenAK** [comment]
Hi @gineshidalgo99 , 
I am still facing the problem after downloading the models again. I am using ubuntu 18.04.

`./build/examples/openpose/openpose.bin —video examples/media/video.avi —write_video examples/out/result.avi —no_display --num_gpu 0 --num_gpu_start 0
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting camera index... Detected and opened camera `

kindly let me know if you need more information. 
Thanks

**Comment by PratikBodawala** [comment]
Same here, even after re-download.
One thing I want to point out that, I have old GPU. One is nvidia 520m and another machine has nvidia 610. Both has 2.1 compute capability. I'm running with opencl.
