### ISSUE TITLE
Window portable demo version detects a ghost in a solo dance

### ISSUE THREAD

**Issue by tung-nguyen-uet** [CMU-Perceptual-Computing-Lab/openpose#377]
### Issue Summary
The portable version on Window detect 2 people in a video of a single performer.

### OpenPose Output (if any)
I attached an image of the frame that the error occur [here](https://drive.google.com/file/d/1LjTKJUBY_XoRSj5sftf2Up57bObbON4R/view?usp=sharing)

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Window 10
**Installation mode**: (Windows);Portable demo version?
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 5.11
**GPU model** (`nvidia-smi` in Ubuntu): Nvidia GeForce 1060 6GB
**Caffe version**: Default from OpenPose, custom version, ...?
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
I can't visualize the image:
```
403. That’s an error.

Your client does not have permission to get URL /7CcagiUmSLMs3rSd4JxHH6bmr-O1hh8I-fBlAIdbHEx7KOxQ4IHB963SA_2UTMjAPQTTWUN1s1GRievNayxw=w1360-h662-rw from this server. (Client IP address: 128.2.194.103)
```

**Comment by tung-nguyen-uet** [comment]
Hi @gineshidalgo99 , I updated the link. Please have a look.

**Comment by gineshidalgo99** [comment]
That false positive is non-avoidable, given how much the net is resized down to detect the people.

You can try to maximum accuracy settings (in the doc), they might remove that false positive from the detection. Otherwise, you'd need some extra post-processing step to clean it up.
