### ISSUE TITLE
[question] Output 3D coordinates available

### ISSUE THREAD

**Issue by archenroot** [CMU-Perceptual-Computing-Lab/openpose#38]
First of all: This is really something here, really good piece of code and math behind and tricks :-) 

I have one question: Can I export 3D coordinates out or it is not in scope of this project?

**Comment by gineshidalgo99** [comment]
Do you mean with 1 or >1 cameras?

With >1 cameras, you can create your own stereo system and apply some basic 3-D keypoint reconstruction method.

With only 1 camera, it would require much more effort and it is not in our plans in short-medium future.

Let me know any further question.

**Comment by archenroot** [comment]
So clearly you focus on framework itself and such as 3D processing must be additionally implemented, fine. Thx for clear answer on my not-clear question :-)

stereo or cross or multi camera systems are clear to me. When it comes to single one, I believe with some preconfigured "natural human movement limitation matrix" it should be possible to generate 3D, of course probably not that accurate, but still to some acceptable degree.

Thanks again!

**Comment by gineshidalgo99** [comment]
Exactly, we still have a long way to improve the framework itself as much as we want before thinking in extensions.

But any extension is welcome to the library after a few control verification steps!

Thanks

**Comment by A7ocin** [comment]
Actually, I wanted to extend it to a 3D domain for my master's thesis. If someone is willing to help me on doing it, he/she's more than welcome! :D
