### ISSUE TITLE
Makefile:630: recipe for target '.build_release/tools/caffe.bin' failed make: *** [.build_release/tools/caffe.bin] Error 1

### ISSUE THREAD

**Issue by prasoonmayank** [CMU-Perceptual-Computing-Lab/openpose#381]
The steps proceeding have been done. Though while executing 
bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh
the following error pops up
-------------------------------------------------------------

------------------------- Installing Caffe and OpenPose -------------------------
NOTE: This script assumes that CUDA and cuDNN are already installed on your machine. Otherwise, it might fail.
------------------------- Installing Caffe -------------------------
NOTE: This script assumes that CUDA and cuDNN are already installed on your machine. Otherwise, it might fail.
------------------------- Checking Ubuntu Version -------------------------
Ubuntu Release:	16.04
------------------------- Ubuntu Version Checked -------------------------

------------------------- Checking Number of Processors -------------------------
4 cores
------------------------- Number of Processors Checked -------------------------

------------------------- Installing some Caffe Dependencies -------------------------
Get:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Ign:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Get:2 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:2 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Ign:4 http://linux.teamviewer.com/deb stable InRelease                         
Hit:5 http://archive.canonical.com/ubuntu xenial InRelease                     
Hit:6 http://in.archive.ubuntu.com/ubuntu xenial InRelease                     
Get:7 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Ign:8 http://linux.dropbox.com/ubuntu xenial InRelease                         
Ign:9 http://linux.teamviewer.com/deb preview InRelease                        
Hit:10 http://linux.teamviewer.com/deb stable Release                          
Hit:11 http://linux.dropbox.com/ubuntu xenial Release                          
Ign:12 http://mirror.cse.iitk.ac.in/debian oldstable InRelease                 
Hit:13 http://linux.teamviewer.com/deb preview Release                         
Hit:14 http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial InRelease        
Hit:15 http://packages.microsoft.com/repos/vscode stable InRelease             
Get:16 http://linux.dropbox.com/ubuntu xenial Release.gpg [473 B]              
Hit:17 http://ppa.launchpad.net/damien-moore/codeblocks-stable/ubuntu xenial InRelease
Get:19 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]   
Get:20 http://mirror.cse.iitk.ac.in/debian oldstable Release [148 kB]          
Get:22 http://mirror.cse.iitk.ac.in/debian oldstable Release.gpg [2,434 B]     
Ign:16 http://linux.dropbox.com/ubuntu xenial Release.gpg                      
Hit:23 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial InRelease   
Ign:22 http://mirror.cse.iitk.ac.in/debian oldstable Release.gpg               
Hit:25 http://ppa.launchpad.net/kivy-team/kivy/ubuntu xenial InRelease         
Hit:26 https://download.sublimetext.com apt/stable/ InRelease                  
Ign:27 https://mega.nz/linux/MEGAsync/xUbuntu_16.04 ./ InRelease               
Hit:28 http://ppa.launchpad.net/luke-jr/db48/ubuntu xenial InRelease           
Hit:29 http://ppa.launchpad.net/umang/indicator-stickynotes/ubuntu xenial InRelease
Get:31 https://mega.nz/linux/MEGAsync/xUbuntu_16.04 ./ Release [988 B]         
Get:33 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB] 
Hit:34 http://ppa.launchpad.net/xqms/opencv-nonfree/ubuntu xenial InRelease    
Hit:24 http://mirror.cse.iitk.ac.in/debian oldstable/main amd64 Packages       
Ign:24 http://mirror.cse.iitk.ac.in/debian oldstable/main amd64 Packages       
Get:35 https://mega.nz/linux/MEGAsync/xUbuntu_16.04 ./ Release.gpg [481 B]     
Hit:30 http://mirror.cse.iitk.ac.in/debian oldstable/main i386 Packages        
Ign:30 http://mirror.cse.iitk.ac.in/debian oldstable/main i386 Packages        
Hit:32 http://mirror.cse.iitk.ac.in/debian oldstable/main Translation-en       
Ign:32 http://mirror.cse.iitk.ac.in/debian oldstable/main Translation-en       
Get:24 http://mirror.cse.iitk.ac.in/debian oldstable/main amd64 Packages [9,064 kB]
Hit:36 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease 
Get:30 http://mirror.cse.iitk.ac.in/debian oldstable/main i386 Packages [9,065 kB]
Err:32 http://mirror.cse.iitk.ac.in/debian oldstable/main Translation-en       
  BZ2_bzread: /var/lib/apt/lists/partial/mirror.cse.iitk.ac.in_debian_dists_oldstable_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
Fetched 311 kB in 31s (9,745 B/s)                                              
Reading package lists... Done
W: GPG error: http://linux.dropbox.com/ubuntu xenial Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FC918B335044912E
W: The repository 'http://linux.dropbox.com/ubuntu xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirror.cse.iitk.ac.in/debian oldstable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553  NO_PUBKEY 7638D0442B90D010  NO_PUBKEY CBF8D6FD518E17E1
W: The repository 'http://mirror.cse.iitk.ac.in/debian oldstable Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://mirror.cse.iitk.ac.in/debian/dists/oldstable/main/i18n/Translation-en  BZ2_bzread: /var/lib/apt/lists/partial/mirror.cse.iitk.ac.in_debian_dists_oldstable_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libleveldb-dev is already the newest version (1.18-5).
libprotobuf-dev is already the newest version (2.6.1-1.3).
libsnappy-dev is already the newest version (1.1.3-2).
protobuf-compiler is already the newest version (2.6.1-1.3).
libhdf5-serial-dev is already the newest version (1.8.16+docs-4ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-all-dev is already the newest version (1.58.0.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgflags-dev is already the newest version (2.1.2-3).
libgoogle-glog-dev is already the newest version (0.3.4-0.1).
liblmdb-dev is already the newest version (0.9.17-3).
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
python-dev is already the newest version (2.7.11-1).
python-setuptools is already the newest version (20.7.0-1).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-numpy is already the newest version (1:1.11.0-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
Searching for pip
Best match: pip 9.0.1
Adding pip 9.0.1 to easy-install.pth file
Installing pip3 script to /usr/local/bin
Installing pip3.5 script to /usr/local/bin
Installing pip script to /usr/local/bin

Using /home/mayank/.local/lib/python3.5/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 8.1.1 (/usr/lib/python3/dist-packages), Requirement.parse('pip==9.0.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==9.0.1' distribution was not found and is required by the application
------------------------- Some Caffe Dependencies Installed -------------------------

------------------------- Compiling Caffe -------------------------
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/convert_imageset.bin
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/convert_imageset.bin' failed
make: *** [.build_release/tools/convert_imageset.bin] Error 1
Makefile:630: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
Makefile:630: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

**Comment by gineshidalgo99** [comment]
Please, use the CMake installer (you'll have to re-download OpenPose to avoid mixing both installers)
