### ISSUE TITLE
Unable to build even after proper installation through cmake

### ISSUE THREAD

**Issue by prasoonmayank** [CMU-Perceptual-Computing-Lab/openpose#382]
Failure coming up on running the demo after installation

Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0118 11:44:16.078200 13991 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7f3eebed25cd  google::LogMessage::Fail()
    @     0x7f3eebed4433  google::LogMessage::SendToLog()
    @     0x7f3eebed215b  google::LogMessage::Flush()
    @     0x7f3eebed4e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3eea23b3cb  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f3eea1d1dfc  caffe::Net<>::Init()
    @     0x7f3eea1d4ed0  caffe::Net<>::Net()
    @     0x7f3eec53f43f  op::NetCaffe::initializationOnThread()
    @     0x7f3eec5a2946  op::addCaffeNetOnThread()
    @     0x7f3eec5a325a  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f3eec5b4ebe  op::PoseExtractor::initializationOnThread()
    @     0x7f3eec5a0428  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f3eec5d3d1e  op::SubThread<>::initializationOnThread()
    @     0x7f3eec5d5f2d  op::Thread<>::initializationOnThread()
    @     0x7f3eec5d617f  op::Thread<>::threadFunction()
    @     0x7f3eec5eed4b  std::_Mem_fn_base<>::operator()<>()
    @     0x7f3eec5eecdf  _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7f3eec5eea90  std::_Bind_simple<>::operator()()
    @     0x7f3eec5ee860  std::thread::_Impl<>::_M_run()
    @     0x7f3eeb9dcc80  (unknown)
    @     0x7f3eeb12e6ba  start_thread
    @     0x7f3eeb44b41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
### Posting rules
4. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
