### ISSUE TITLE
Preprocessing Image for hand detector

### ISSUE THREAD

**Issue by xiao7199** [CMU-Perceptual-Computing-Lab/openpose#384]
Hi:
   I want to do reproduce the result from CVPR 17 handpose paper with the model provided. But I can't find any preprocessing information, like image mean value. And when I try to using original image,  /256 or /256 - 0.5, I got non-sense result. So could you please share the image preprocessing parameter ? 

  Thanks

**Comment by MetalSlugxx** [comment]
Hi, xiao. Where is the handpose model? Could you give me a website?

**Comment by xiao7199** [comment]
Hi:
  The prototxt is
https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models/hand

**Comment by gineshidalgo99** [comment]
It's not only that, but also the cropping and parameters.

This is not related to OpenPose, we only crop the hand and feed it into the net with the trained model (hand/handExtractorCaffe.cpp)

**Comment by DanielMao2015** [comment]
@gineshidalgo99  Hi, Is it a necessary step to crop hands out of the whole images when I train the hand-only pose estimation? What it would be if I feed the whole images for training instead of the cropped images?  Is there a severe degradation? Thank you!

**Comment by gineshidalgo99** [comment]
Your pixel resolution would deteriorate a lot, so it is really not recommended at all.
