### ISSUE TITLE
Initialize openpose as a class filed to handle RPC request(contains an image),but get error:The CPU/GPU pointer data cannot be accessed from a different thread

### ISSUE THREAD

**Issue by AlexLuya** [CMU-Perceptual-Computing-Lab/openpose#387]
I want to  initialize an openose instance,save it as a class field,and this class implemented some grpc related logic,will listen on a port,and I want pass the request(an image) from this port to saved openpose instance for detection,then return back detection result to this port.

After googling.I found PyOpenpose,and implement my design like this:
```
  class PosingServer:
    def __init__(self, setting=PosingSetting):
        self.setting=setting
        self.initNetwork()
        
    def detect(self, req):
            #detect pose
            net.detectPose(req.image)
            #detect pose
           return net.getKeypoints(net.KeypointType.POSE)[0]

    def initNetwork(self):
        setting = self.setting
        self.net = OP.OpenPose(setting.poseSize, setting.faceHandSize, setting.outSize,\
                               setting.modelType, setting.modelFolder, setting.logLevel,\
                               setting.downloadHeatmaps)

   *****grpc related stuffs*******
```
After PosingServer running,it can receive rpc request  and perform detection but this line:

`           return net.getKeypoints(net.KeypointType.POSE)[0]   `   

 gives error:
```
The CPU/GPU pointer data cannot be accessed from a different thread.

Coming from:
- src/openpose/pose/poseExtractor.cpp:checkThread():341
- src/openpose/pose/poseExtractor.cpp:checkThread():345
- src/openpose/pose/poseExtractor.cpp:getPoseKeypoints():265
ERROR    Exception calling application: 
Error:
The CPU/GPU pointer data cannot be accessed from a different thread.

Coming from:
- src/openpose/pose/poseExtractor.cpp:checkThread():341
- src/openpose/pose/poseExtractor.cpp:checkThread():345
- src/openpose/pose/poseExtractor.cpp:getPoseKeypoints():265
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grpc/_server.py", line 377, in _call_behavior
    return behavior(argument, context), True
  File "server/pose/PosingServer.py", line 81, in carryOut
    return self.detector.detect(req)
  File "server/pose/PosingServer.py", line 40, in detect
    return net.getKeypoints(net.KeypointType.POSE)[0])
RuntimeError: 
Error:
The CPU/GPU pointer data cannot be accessed from a different thread.
```
How to solve this problem?

**Comment by gineshidalgo99** [comment]
I'm sorry but that's a PyOpenpose issue, not ours. I'd try the `--disable_multi_thread` flag, but again, it's not our repo.

**Comment by AlexLuya** [comment]
After change poseExtractor:checkThread() method to

void PoseExtractor::checkThread() const
{
    try
    {
        if(mThreadId != std::this_thread::get_id())
			std::cout<<"poseExtractor:Error from a different thread access CPU/GPU pointer*****but Alex disabled this error for RPC mechnism*****god bless no any side effects"<<std::endl;
           // error("The CPU/GPU pointer data cannot be accessed from a different thread.",
           //      __LINE__, __FUNCTION__, __FILE__);
    }
    catch (const std::exception& e)
    {
        error(e.what(), __LINE__, __FUNCTION__, __FILE__);
    }
}
Hope no side effect
