### ISSUE TITLE
CMake GUI configuration errors during openpose installation in Ubuntu

### ISSUE THREAD

**Issue by yoummiegao** [CMU-Perceptual-Computing-Lab/openpose#388]
### Issue Summary
When I press down the finish button following the  3rd step of  OpenPose Configuration, some errors  output:

**Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: /home/yoummiegao/OpenPose/openpose-master/build/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /home/yoummiegao/OpenPose/openpose-master/build/CMakeCache.txt
CMake Error: : System Error: Permission denied**

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...?
CMake(Ubuntu)

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
CUDA Version 8.0.61

**cuDNN version**:
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

**GPU model** (`nvidia-smi` in Ubuntu):
-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P3    N/A /  N/A |    441MiB /  4041MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1114      G   /usr/lib/xorg/Xorg                           208MiB |
|    0      2043      G   compiz                                       140MiB |
|    0      4924      G   ...-token=4ECFB7392D695668A38DA55C649EA767    92MiB |
+-----------------------------------------------------------------------------+
**Caffe version**: Default from OpenPose, custom version, ...?
1.0.0
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
2.7.12
Compiler (`gcc --version` in Ubuntu):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
I'd like to try a couple things to debug the error, could you please rename `openpose-master` as `openpose` and try again? Please, let me know the results.

**Comment by yoummiegao** [comment]
It’s same result.

**Comment by bikz05** [comment]
It's saying "Permission Denied", which usually occurs when you don't have write previleges.

**Comment by yoummiegao** [comment]
Thx@ Bikramjot Hanzra, but how to entitle the CMake-GUI with write previleges? Could you provide any sentences like sudo … or reference link to implement it in detail?

**Comment by bikz05** [comment]
Can you run the following commands from the terminal and let us know the output --

```
cd /home/yoummiegao/OpenPose/openpose/
ls -l
```

Also, you can open the cmake-gui with root privileges using the command below --

```
sudo cmake-gui
```
Although, it's not recommended.

**Comment by yoummiegao** [comment]
Thanks@bikz05, It moves forward with few  errors about "pthread_create" left.

>cd /home/yoummiegao/OpenPose/openpose/
>ls -l

The output is 

total 80
drwxr-xr-x  4 root root 4096 Jan 13 12:07 3rdparty
drwxr-xr-x  2 root root 4096 Jan 13 19:44 build
drwxr-xr-x  3 root root 4096 Jan 13 12:07 cmake
-rw-r--r--  1 root root 9373 Jan 13 12:07 CMakeLists.txt
drwxr-xr-x  5 root root 4096 Jan 13 12:07 doc
drwxr-xr-x 10 root root 4096 Jan 13 12:07 examples
drwxr-xr-x  3 root root 4096 Jan 13 12:07 examples_beta
drwxr-xr-x  3 root root 4096 Jan 13 12:07 include
-rw-r--r--  1 root root 9686 Jan 13 12:07 LICENSE
drwxr-xr-x  5 root root 4096 Jan 13 12:07 models
-rw-r--r--  1 root root 8229 Jan 13 12:07 README.md
drwxr-xr-x  3 root root 4096 Jan 13 12:07 src
drwxrwxrwx  2 root root 4096 Jan 19 20:13 ubuntu
drwxr-xr-x  9 root root 4096 Jan 13 12:07 windows

for the second command
>sudo cmake-gui
It helps the configuration move forward,

Download the models.
Downloading body (COCO) model...
NOTE: This process might take several minutes depending on your internet connection.
Downloading face model...
NOTE: This process might take several minutes depending on your internet connection.
Downloading hand model...
NOTE: This process might take several minutes depending on your internet connection.
Models Downloaded.
Configuring incomplete, errors occurred!
See also "/home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/yoummiegao/OpenPoCse/openpose/build/CMakeFiles/CMakeError.log".

######################CMakeError.log####################################
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_faf3c/fast"
/usr/bin/make -f CMakeFiles/cmTC_faf3c.dir/build.make CMakeFiles/cmTC_faf3c.dir/build
make[1]: Entering directory '/home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_faf3c.dir/CheckSymbolExists.c.o
/usr/bin/cc    -fPIC    -o CMakeFiles/cmTC_faf3c.dir/CheckSymbolExists.c.o   -c /home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_faf3c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_faf3c.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC     CMakeFiles/cmTC_faf3c.dir/CheckSymbolExists.c.o  -o cmTC_faf3c -rdynamic 
CMakeFiles/cmTC_faf3c.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_faf3c.dir/build.make:97: recipe for target 'cmTC_faf3c' failed
make[1]: *** [cmTC_faf3c] Error 1
make[1]: Leaving directory '/home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_faf3c/fast' failed
make: *** [cmTC_faf3c/fast] Error 2

File /home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e7466/fast"
/usr/bin/make -f CMakeFiles/cmTC_e7466.dir/build.make CMakeFiles/cmTC_e7466.dir/build
make[1]: Entering directory '/home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e7466.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_e7466.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_e7466
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e7466.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_e7466.dir/CheckFunctionExists.c.o  -o cmTC_e7466 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e7466.dir/build.make:97: recipe for target 'cmTC_e7466' failed
make[1]: *** [cmTC_e7466] Error 1
make[1]: Leaving directory '/home/yoummiegao/OpenPose/openpose/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_e7466/fast' failed
make: *** [cmTC_e7466/fast] Error 2
###################################################################################

**Comment by bikz05** [comment]
I am not sure why `root` is the owner. Can you clone OpenPose using the command --

```
git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
```

Also, before running this command check the output of the command `whoami`. It should be your username which I guess is `yoummiegao` and not `root`.

**Comment by Maninders-Chetu** [comment]
Hi sir,
i m getting this error in windows 10 can you please help me out
CMake Error: Cannot open file for write: /CMakeCache.txt.tmp
