### ISSUE TITLE
How to use write qt .pro for openpose.cpp

### ISSUE THREAD

**Issue by TX-Yeager** [CMU-Perceptual-Computing-Lab/openpose#389]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 0000:01:00.0      On |                  N/A |
| 38%   32C    P8    15W / 300W |    153MiB /  4034MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1199    G   /usr/bin/X                                     151MiB 

system ubuntu14.04lts
cuda8.0 cudnn 6.0 opencv 3.2.0

MY PROBLEMS
/usr/bin/ld: main.o: undefined reference to symbol '_ZN6google21ParseCommandLineFlagsEPiPPPcb'
//usr/lib/x86_64-linux-gnu/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [openposeconsole] Error 1
19:55:40: The process "/usr/bin/make" exited with code 2.

I need to make a ui with qt and openpose.i can use opencv in 
there may be something wrong with the gflags because of the undefined reference 'google21parsecommandlineflags' .
Or is there any one can teach me how to make a available .pro document
HELP !!!!!!

**Comment by TX-Yeager** [comment]
i can use opencv in qt

**Comment by TX-Yeager** [comment]
I solved my question by adding your path to  ld.so.conf
sudo gedit /etc/ld.so,conf
add cuda ,openpose, to this document
and compile the openpose.cpp at qt
lolololololol

**Comment by cyummy** [comment]
Could you please share your .pro document ?  I have also met with some trouble when using openpose in a QT project. Thanks!

**Comment by TX-Yeager** [comment]
remember to change your path.




#-------------------------------------------------
#
# Project created by QtCreator 2018-03-08T08:16:00
#
#-------------------------------------------------


QT       += core gui


greaterThan(QT_MAJOR_VERSION, 4): QT += widgets


TARGET = sportsangle


CONFIG += c++11
TEMPLATE = app




INCLUDEPATH += /usr/local/include \
/usr/local/include/opencv \
/usr/local/include/opencv2 \
/home/chacky/openpose/distribute/include \
/usr/include \
/usr/include/gflags


LIBS += /usr/local/lib/libopencv_calib3d.so \
/usr/local/lib/libopencv_core.so \
/usr/local/lib/libopencv_features2d.so \
/usr/local/lib/libopencv_flann.so \
/usr/local/lib/libopencv_highgui.so \
/usr/local/lib/libopencv_imgcodecs.so \
/usr/local/lib/libopencv_imgproc.so \
/usr/local/lib/libopencv_ml.so \
/usr/local/lib/libopencv_objdetect.so \
/usr/local/lib/libopencv_photo.so \
/usr/local/lib/libopencv_shape.so \
/usr/local/lib/libopencv_stitching.so \
/usr/local/lib/libopencv_superres.so \
/usr/local/lib/libopencv_videoio.so \
/usr/local/lib/libopencv_video.so \
/usr/local/lib/libopencv_videostab.so \
/home/chacky/openpose/build/lib/libopenpose.so \
/usr/lib/x86_64-linux-gnu/libgflags.so \
/usr/local/cuda-8.0/lib64/libcudart.so \
/usr/local/cuda-8.0/lib64/libcublas.so \
/usr/local/cuda-8.0/lib64/libcurand.so \
/usr/local/cuda-8.0/lib64/libcudnn.so


SOURCES += main.cpp\
        mainwindow.cpp


HEADERS  += mainwindow.h


FORMS    += mainwindow.ui







------------------ 原始邮件 ------------------
发件人: "cyummy"<notifications@github.com>; 
发送时间: 2019年6月3日(星期一) 下午5:32
收件人: "CMU-Perceptual-Computing-Lab/openpose"<openpose@noreply.github.com>; 
抄送: "237855424"<237855424@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [CMU-Perceptual-Computing-Lab/openpose] How to use write qt .profor openpose.cpp (#389)




Could you please share your .pro document ?  I have also met with some trouble when using openpose in a QT project. Thanks!

**Comment by cyummy** [comment]
@TX-Yeager Thanks for your reply. I have finished  the .pro doc with your help.
Howerver , many errors occurred when I quote #include <openpose/flags.hpp> in the mainwindow.h.
I think maybe you have ever come across  similar problems.
Could you give me any advice? Thanks!


Error:
/home/cyummy/GaitSet/tmp/build-myfirstTry-unknown-Debug/videomainwindow.o:-1: error: multiple definition of `fLI::FLAGS_logging_level'
/usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:251: error: multiple definition of `fLI::FLAGS_nologging_level'

error: multiple definition of `fLI::FLAGS_camera'
.....
