### ISSUE TITLE
the process is  killed

### ISSUE THREAD

**Issue by caffelearn** [CMU-Perceptual-Computing-Lab/openpose#39]
the command:
   ./build/examples/openpose/rtpose.bin --image_dir examples/media/ --write_images output/  --model_pose MPI
 OR
  ./build/examples/openpose/rtpose.bin --image_dir examples/media/ --write_images output/  --model_pose COCO
  
the process:
Starting pose estimation demo.
Starting thread(s)
Killed

how to solve the problem?

by the way:
opencv is 2.4.13 
GPU is TX1

**Comment by caffelearn** [comment]
i solved it ! before  i do not use CUDNN

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back!

**Comment by anujpasricha01** [comment]
Facing the same issue. @caffelearn Do you mean I should rebuild openpose using GPU_MODE=CUDA?

**Comment by jkelso662** [comment]
I am also facing this "Killed" issue. I am trying to build on CPU_ONLY and run inside a docker container (such as https://github.com/seancook/docker-openpose-cpu) but all produce the same error with no useful output. Any advice would be much appreciated!

**Comment by jkelso662** [comment]
# Update
Turns out in my case this is a memory-related issue. I assigned docker more memory and now it is running without the "Killed" error.

**Comment by Anonymous991001** [comment]
@caffelearn Can you tell me how you solved this. I am also going through same issue using Jetson AGX

**Comment by xiepip** [comment]
> 

hi @Anonymous991001 I meet the same issue now.
Did you fix it?
