### ISSUE TITLE
Get Pose data from Video camera

### ISSUE THREAD

**Issue by georgecfwebtools** [CMU-Perceptual-Computing-Lab/openpose#391]
Hello,

Just got to know this library, seems pretty cool. When I run the portable version demos, all worked as expected. 

Currently I would build an application with following features:

1) Build a console application
2) Get video information from computer's video camera
3) Display pose json  in console.

I would not display the video camera UI, not save the pose data to file, all I need is the pose JSON result.

Could any one show me some hint how to do this?

Thank you!

George

**Comment by gineshidalgo99** [comment]
`--display 0` (doc/demo_overview.md)

**Comment by georgecfwebtools** [comment]
OK, will try out and let you know if I have further questions.

Thank you very much!

Geoge

**Comment by georgecfwebtools** [comment]
Just read through the code, that is exactly the answer I am looking for. 

Thank you again for the information!

George
