### ISSUE TITLE
OpenPose in Unity

### ISSUE THREAD

**Issue by georgecfwebtools** [CMU-Perceptual-Computing-Lab/openpose#392]
I would run OpenPose in Unity and I tried to use "1_extract_from_image" as start point, however, it crashed the Unity. 

There are multiple factors I could think of: Dlls, models, image.

I wonder if someone already make OpenPose works in Unity, it would be great if we could get a Tutorial on OpenPose in Unity.

The error I got is on (OpenPose) op::renderPosePAFsGpu, my environment is Windows 10, GTX 1050 4GB, 7th generation i5 CPU, 8 GM memory.

========== OUTPUTING STACK TRACE ==================

0x00007FFB63879D98 (KERNELBASE) RaiseException
0x00007FFB617144F2 (VCRUNTIME140) CxxThrowException
0x00007FFB16C7E7AB (OpenPose) op::error
0x00007FFB16CE204A (OpenPose) op::renderPosePAFsGpu
0x00007FFB6171C1E0 (VCRUNTIME140) _C_specific_handler
0x00007FFB61712D03 (VCRUNTIME140) _TypeMatch
0x00007FFB671C9603 (ntdll) RtlCaptureContext
0x00007FFB16C6413A (OpenPose) op::PoseExtractor::initializationOnThread
0x00007FFB60F72696 (SimpleActionDLL) openPoseDemo
0x000000003538DCD4 (Mono JIT Code) (wrapper managed-to-native) PlayerController:openPoseDemo ()
0x000000003538D856 (Mono JIT Code) [C:\Users\georg\Documents\Roll a Ball\Assets\Scripts\PlayerController.cs:18] PlayerController:Start () 
0x0000000000897192 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFB234564AF (mono) [c:\buildslave\mono\build\mono\mini\mini.c:4937] mono_jit_runtime_invoke 
0x00007FFB233A8A19 (mono) [c:\buildslave\mono\build\mono\metadata\object.c:2623] mono_runtime_invoke 
0x0000000140A2EAEC (Unity) scripting_method_invoke
0x0000000140A2243A (Unity) ScriptingInvocation::Invoke
0x00000001409EB7DF (Unity) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00000001409ED356 (Unity) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00000001409EEBA8 (Unity) MonoBehaviour::Start
0x00000001409EF199 (Unity) MonoBehaviour::DelayedStartCall
0x00000001405031B5 (Unity) DelayedCallManager::Update
0x000000014071F87C (Unity) `InitPlayerLoopCallbacks'::`34'::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward
0x000000014071CB4E (Unity) PlayerLoop
0x00000001411DE245 (Unity) PlayerLoopController::UpdateScene
0x00000001411E85FA (Unity) PlayerLoopController::EnterPlayMode
0x00000001411E8E76 (Unity) PlayerLoopController::SetIsPlaying
0x00000001411E9CC6 (Unity) Application::TickTimer
0x000000014140EB0F (Unity) MainMessageLoop
0x00000001414103B5 (Unity) WinMain
0x0000000141E643A8 (Unity) __tmainCRTStartup
0x00007FFB66942774 (KERNEL32) BaseThreadInitThunk
0x00007FFB67190D51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

Thanks!

George

**Comment by minorbug** [comment]
I am also interested in OpenPose to Unity import. Any progress?

**Comment by idchlife** [comment]
Me too, hope for update!
