### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by osamazhar** [CMU-Perceptual-Computing-Lab/openpose#395]
1. Alienware-51-R2; Ubuntu 16.04, RAM 64Gb, GPUs: 2 GeForce GTX 1080

https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/44

### Issue Summary:
I get the following error whenever I run openpose.bin example:

Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
Starting thread(s)
F0123 11:57:00.049329 26206 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fc4337935cd  google::LogMessage::Fail()
    @     0x7fc433795433  google::LogMessage::SendToLog()
    @     0x7fc43379315b  google::LogMessage::Flush()
    @     0x7fc433795e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc433db8208  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7fc433ee9b02  caffe::Blob<>::mutable_gpu_data()
    @     0x7fc433e1b868  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7fc433f52ac6  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7fc433dbf011  caffe::Net<>::ForwardFromTo()
    @     0x7fc4355056f0  op::NetCaffe::forwardPass()
    @     0x7fc435556fc3  op::PoseExtractorCaffe::forwardPass()
    @     0x7fc43555207b  op::WPoseExtractor<>::work()
    @     0x7fc4355b83fa  op::Worker<>::checkAndWork()
    @     0x7fc4355bb33b  op::SubThread<>::workTWorkers()
    @     0x7fc4355c4f07  op::SubThreadQueueInOut<>::work()
    @     0x7fc4355c066b  op::Thread<>::threadFunction()
    @     0x7fc434f15c80  (unknown)
    @     0x7fc4324f56ba  start_thread
    @     0x7fc43498441d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

Earlier i compiled Caffe manually downloading it from github and thought that it might be the reason for this error. But then I followed normal installation instructions on openpose website and this error remains. 

### Type of Issue

- Execution error
- Help wanted

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Installation mode**: manual Makefile installation, ... (Ubuntu);
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 8.0.61
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi` in Ubuntu):
Tue Jan 23 12:03:53 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:03:00.0  On |                  N/A |
| 27%   34C    P8     9W / 180W |    496MiB /  8112MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:04:00.0 Off |                  N/A |
| 27%   29C    P8     6W / 180W |      2MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1206      G   /usr/lib/xorg/Xorg                           283MiB |
|    0      2385      G   compiz                                        78MiB |
|    0      4684      G   ...-token=CA57780E92B7B5177C483794A14DF225   130MiB |
|    0     26300      G   unity-control-center                           2MiB |
+-----------------------------------------------------------------------------+

**Caffe version**: Default from OpenPose,
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu)
Compiler (`gcc --version` in Ubuntu): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
It can't run out of memory with the basic command in the quick_start and cuDNN enabled. Most probably, you are using a different CUDA version or sth (e.g. having more than one version of CUDA in ls /usr/local/ )

**Comment by osamazhar** [comment]
I have removed cuDNN from 5.1 to 7. so here is the output you asked for:

libcublas_device.a    libcurand.so           libnppidei.so.8.0     libnpps.so.8.0.61
libcublas.so          libcurand.so.8.0       libnppidei.so.8.0.61  libnpps_static.a
libcublas.so.8.0      libcurand.so.8.0.61    libnppif.so           libnvblas.so
libcublas.so.8.0.61   libcurand_static.a     libnppif.so.8.0       libnvblas.so.8.0
libcublas_static.a    libcusolver.so         libnppif.so.8.0.61    libnvblas.so.8.0.61
libcudadevrt.a        libcusolver.so.8.0     libnppig.so           libnvgraph.so
libcudart.so          libcusolver.so.8.0.61  libnppig.so.8.0       libnvgraph.so.8.0
libcudart.so.8.0      libcusolver_static.a   libnppig.so.8.0.61    libnvgraph.so.8.0.61
libcudart.so.8.0.61   libcusparse.so         libnppim.so           libnvgraph_static.a
libcudart_static.a    libcusparse.so.8.0     libnppim.so.8.0       libnvrtc-builtins.so
libcudnn.so           libcusparse.so.8.0.61  libnppim.so.8.0.61    libnvrtc-builtins.so.8.0
libcudnn.so.7         libcusparse_static.a   libnppi.so            libnvrtc-builtins.so.8.0.61
libcudnn.so.7.0.4     libnppc.so             libnppi.so.8.0        libnvrtc.so
libcudnn_static.a     libnppc.so.8.0         libnppi.so.8.0.61     libnvrtc.so.8.0
libcufft.so           libnppc.so.8.0.61      libnppi_static.a      libnvrtc.so.8.0.61
libcufft.so.8.0       libnppc_static.a       libnppist.so          libnvToolsExt.so
libcufft.so.8.0.61    libnppial.so           libnppist.so.8.0      libnvToolsExt.so.1
libcufft_static.a     libnppial.so.8.0       libnppist.so.8.0.61   libnvToolsExt.so.1.0.0
libcufftw.so          libnppial.so.8.0.61    libnppisu.so          libOpenCL.so
libcufftw.so.8.0      libnppicc.so           libnppisu.so.8.0      libOpenCL.so.1
libcufftw.so.8.0.61   libnppicc.so.8.0       libnppisu.so.8.0.61   libOpenCL.so.1.0
libcufftw_static.a    libnppicc.so.8.0.61    libnppitc.so          libOpenCL.so.1.0.0
libcuinj64.so         libnppicom.so          libnppitc.so.8.0      stubs
libcuinj64.so.8.0     libnppicom.so.8.0      libnppitc.so.8.0.61
libcuinj64.so.8.0.61  libnppicom.so.8.0.61   libnpps.so
libculibos.a          libnppidei.so          libnpps.so.8.0

**Comment by gineshidalgo99** [comment]
Could you try installing it with CMake?

**Comment by osamazhar** [comment]
I tried with CMake, it gives me this:

CMakeFiles/Makefile2:842: recipe for target 'examples/tutorial_pose/CMakeFiles/openpose_test.dir/all' failed
make[1]: *** [examples/tutorial_pose/CMakeFiles/openpose_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target face
[ 23%] Building CXX object src/openpose/face/CMakeFiles/face.dir/renderFace.cpp.o
[ 25%] Building CXX object src/openpose/face/CMakeFiles/face.dir/defineTemplates.cpp.o
[ 25%] Building CXX object src/openpose/face/CMakeFiles/face.dir/faceCpuRenderer.cpp.o
[ 26%] Building CXX object src/openpose/face/CMakeFiles/face.dir/faceExtractor.cpp.o
[ 27%] Building CXX object src/openpose/face/CMakeFiles/face.dir/faceDetector.cpp.o
[ 27%] Building CXX object src/openpose/face/CMakeFiles/face.dir/faceGpuRenderer.cpp.o
Scanning dependencies of target hand
[ 28%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/defineTemplates.cpp.o
[ 29%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/handDetector.cpp.o
[ 30%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/handDetectorFromTxt.cpp.o
Scanning dependencies of target pose
[ 31%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/bodyPartConnectorBase.cpp.o
[ 32%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/bodyPartConnectorCaffe.cpp.o
[ 32%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/handExtractor.cpp.o
[ 33%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/handCpuRenderer.cpp.o
[ 34%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/handGpuRenderer.cpp.o
[ 35%] Building CXX object src/openpose/hand/CMakeFiles/hand.dir/renderHand.cpp.o
[ 36%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/defineTemplates.cpp.o
[ 36%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/poseCpuRenderer.cpp.o
[ 37%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/poseExtractor.cpp.o
[ 38%] Linking CXX shared library libface.so
[ 39%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/poseExtractorCaffe.cpp.o
[ 40%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/poseGpuRenderer.cpp.o
[ 41%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/poseParameters.cpp.o
[ 42%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/poseRenderer.cpp.o
[ 42%] Built target face
[ 42%] Building CXX object src/openpose/pose/CMakeFiles/pose.dir/renderPose.cpp.o
[ 43%] Linking CXX shared library libhand.so
[ 43%] Built target hand
[ 44%] Linking CXX shared library libpose.so
[ 44%] Built target pose
Scanning dependencies of target core
[ 45%] Building CXX object src/openpose/core/CMakeFiles/core.dir/datum.cpp.o
[ 46%] Building CXX object src/openpose/core/CMakeFiles/core.dir/cvMatToOpInput.cpp.o
[ 47%] Building CXX object src/openpose/core/CMakeFiles/core.dir/keypointScaler.cpp.o
[ 47%] Building CXX object src/openpose/core/CMakeFiles/core.dir/cvMatToOpOutput.cpp.o
[ 48%] Building CXX object src/openpose/core/CMakeFiles/core.dir/nmsCaffe.cpp.o
[ 48%] Building CXX object src/openpose/core/CMakeFiles/core.dir/maximumCaffe.cpp.o
[ 49%] Building CXX object src/openpose/core/CMakeFiles/core.dir/array.cpp.o
[ 50%] Building CXX object src/openpose/core/CMakeFiles/core.dir/defineTemplates.cpp.o
[ 51%] Building CXX object src/openpose/core/CMakeFiles/core.dir/netCaffe.cpp.o
[ 52%] Building CXX object src/openpose/core/CMakeFiles/core.dir/maximumBase.cpp.o
[ 54%] Building CXX object src/openpose/core/CMakeFiles/core.dir/nmsBase.cpp.o
[ 54%] Building CXX object src/openpose/core/CMakeFiles/core.dir/gpuRenderer.cpp.o
[ 55%] Building CXX object src/openpose/core/CMakeFiles/core.dir/point.cpp.o
[ 55%] Building CXX object src/openpose/core/CMakeFiles/core.dir/opOutputToCvMat.cpp.o
[ 56%] Building CXX object src/openpose/core/CMakeFiles/core.dir/rectangle.cpp.o
[ 57%] Building CXX object src/openpose/core/CMakeFiles/core.dir/renderer.cpp.o
[ 58%] Building CXX object src/openpose/core/CMakeFiles/core.dir/resizeAndMergeBase.cpp.o
[ 59%] Building CXX object src/openpose/core/CMakeFiles/core.dir/resizeAndMergeCaffe.cpp.o
[ 60%] Linking CXX shared library libcore.so
[ 60%] Built target core
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by elkalash** [comment]
I was wondering maybe it's because openPose can't access the available GPUs,if so,how to fix it?

**Comment by osamazhar** [comment]
I had openpose 1.1.0 with me, so I compiled it and it is somehow working fine. I couldn't compile openpose 1.2.0 with cmake as suggested by gineshidalgo99. My problem appeared to be related to cuda memory (I suppose) but you have an error related to cuDNN. So may be you should check if it is rightly installed. I have tried running openpose with cuDNN 5.1, 6 and 7. The version does not hinder the operation (it may slow down the frame rates as said in the documentation).

**Comment by elkalash** [comment]
I Have fixed it,the problem was with the GPUs,it'a now working properly,Thank you so much

**Comment by lvpengfeifei** [comment]
I'm having the same problem  with runing the release version.it makes me upset..

**Comment by elkalash** [comment]
@lvpengfeifei make sure that the GPUs are available,if you're having the problem that I;ve posted.

**Comment by lvpengfeifei** [comment]
@elkalash Thank you sir.this is the console debug message.


D:\Downloads>cd openpose-1.2.1-win64-binaries

D:\Downloads\openpose-1.2.1-win64-binaries>bin\OpenPoseDemo.exe --video examples\media\video.avi
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0206 17:09:37.923095  1040 upgrade_proto.cpp:95] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/coco/pose_iter_440000.caffemodel
*** Check failure stack trace: ***

**Comment by lvpengfeifei** [comment]
@elkalash Thank you lad. this is the console output message.
D:\Downloads\openpose-1.2.1-win64-binaries>bin\OpenPoseDemo.exe --video examples\media\video.avi
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0206 17:14:01.623456 10148 syncedmem.cpp:78] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***

**Comment by lvpengfeifei** [comment]
@elkalash 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
"cublas64_80.dll cudnn64_5.dll nvblas64_80"

**Comment by lvpengfeifei** [comment]
@elkalash I also install the cudnn-8.0 and cuda_8.0;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
"cublas64_80.dll cudnn64_5.dll nvblas64_80"

**Comment by 645704621** [comment]
I'm having the same problem. And how to solve the problem if the GPUs are not available.

**Comment by BalajiB3663** [comment]
I'm having same issue, I want to check my cudnn is enabled or not while the training starts , can anybody suggest me how to check cudnn?

**Comment by kz81** [comment]
You might have two versions of cudart*.dll files in your %OUTPUT_DIR%, for example 
cudart64_75.dll AND cudart32_75.dll in C:\Program Files (x86)\caffe-master\Build\x64\Release.
At least that is the problem I have and I hope this will be the solution.

**Comment by hvoigt** [comment]
I'm having the same error as @elkalash. But but only when start a second application using openpose on the same machine. Is it not possible to run multiple instances of openpose?

**Comment by riebling** [comment]
Same error.

**Comment by hanhanshangying** [comment]
I'm having the same problem. How can I fix it?

**Comment by fauzan923** [comment]
me too how to solve this problem?
