### ISSUE TITLE
Tensorflow (with GPU) as deep_net

### ISSUE THREAD

**Issue by osamazhar** [CMU-Perceptual-Computing-Lab/openpose#396]
### Issue Summary
It is not an issue but a question. How is it possible to use tensorflow as DEEP_NET as in the Makefile. Does it mean that we won't need to use Caffe at all?

### Type of Issue

- Question

**Comment by gineshidalgo99** [comment]
Caffe is the only option for now (and so far we have not explorer others yet). This extension is a long-term goal

**Comment by osamazhar** [comment]
Thanks!

**Comment by aligajani** [comment]
You can use Google's posenet or a Korean guys openpose with tf implementation.
