### ISSUE TITLE
No output displayed or it gets stuck

### ISSUE THREAD

**Issue by RainBoltz** [CMU-Perceptual-Computing-Lab/openpose#4]
my terminal isn't responding after executed the command below:

`./build/examples/openpose/rtpose.bin --image_dir examples/media/ --logging_level 1 --net_resolution 496x368 --resolution 640x480`

since i got the following message:

`Starting pose estimation demo.
examples/openpose/rtpose.cpp:gflagsToOpParameters():203
examples/openpose/rtpose.cpp:gflagsToProducer():171
examples/openpose/rtpose.cpp:gflagsToProducerType():151
examples/openpose/rtpose.cpp:gflagToPoseModel():113
examples/openpose/rtpose.cpp:gflagToScaleMode():129
Configuring OpenPose wrapper. In examples/openpose/rtpose.cpp:opRealTimePoseDemo():249
./include/openpose/wrapper/wrapper.hpp:configure():418
./include/openpose/wrapper/wrapper.hpp:configure():555
./include/openpose/wrapper/wrapper.hpp:configure():716
Starting thread(s)
./include/openpose/wrapper/wrapper.hpp:configureThreadManager():1024
./include/openpose/thread/threadManager.hpp:start():192
./include/openpose/thread/queueBase.hpp:addPusher():364
./include/openpose/thread/queueBase.hpp:addPusher():364
./include/openpose/thread/queueBase.hpp:addPusher():364
./include/openpose/thread/thread.hpp:startInThread():141
./include/openpose/thread/thread.hpp:startInThread():141
./include/openpose/thread/thread.hpp:startInThread():141
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:startInThread():141
Starting initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():38./include/openpose/thread/thread.hpp:threadFunction():188
./include/openpose/thread/threadManager.hpp:start():198
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():188
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():188
Finished initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():61
Starting initialization on thread. In src/openpose/pose/poseRenderer.cpp:initializationOnThread():75
Finished initialization on thread. In src/openpose/pose/poseRenderer.cpp:initializationOnThread():79
./include/openpose/thread/thread.hpp:threadFunction():188`

i'm running on ubuntu16 with opencv3
other requires were setup by `./install_caffe_and_openpose.sh` , which was provided by official

**Comment by bigmoumou** [comment]
I have the same problem too

Is there any solution ?

**Comment by Shawnroom** [comment]
I have the same issue, and wonder if there is any solution.

**Comment by gineshidalgo99** [comment]
Sorry to hear that, we are working on fixing that error. We think it is due to OpenCV 3.

Meanwhile, if you use the default OpenCV from the Ubuntu repository: `apt-get install libopencv-dev`, it should work.

We will notify this thread once we solve this issue with OpenCV 3. Thanks!

**Comment by RainBoltz** [comment]
thanks!!! i solved it by switching the opencv version to 2.4.13
(btw, simply execute `sudo apt-get install libopencv-dev` doesnt work for me,
so i recompiled and install the total opencv then it worked)

and for the questions above, the same issue DO occurs when processing video...

i have to say this really works amazingly!! great work:)

**Comment by gineshidalgo99** [comment]
This issue has finally being solved (at least for some people after our last commit).

You can `git pull` or re-download the latest version of the library and re-compile it.

To re-compile it in case you just do `git pull`:
`make clean && cd 3rdparty/caffe && make clean && make distribute -j8 && cd ../.. && make all -j8`

In case you re-download it, just delete the old version and follow the installation steps again.

Please, reopen this post if this issue persists (this message is for everybody).

**Comment by taxuezcy** [comment]
how can i build without display instead of giving arg when running @gineshidalgo99

**Comment by saumyasaxena8** [comment]
Hi
I am facing the same issue on Ubuntu 18.04 with Opencv 4.1.1. The screen opens up but blacks out with no output. I am facing this for images and videos.
Any help would be appreciated

**Comment by MichaelGMoore** [comment]
This is happening to me on Ubuntu 16.04 using sudo apt-get install libopencv-dev. Any help appreciated.

**Comment by shash29-dev** [comment]
same problem. On Linux.
window dont respond and crashes with following output:
F0803 21:38:10.637179 20637 cudnn.hpp:128] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7f9bd7b455cd  google::LogMessage::Fail()
    @     0x7f9bd7b47433  google::LogMessage::SendToLog()
    @     0x7f9bd7b4515b  google::LogMessage::Flush()
    @     0x7f9bd7b47e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9bd7115ec0  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f9bd71eab62  caffe::Net<>::Init()
    @     0x7f9bd71edb60  caffe::Net<>::Net()
    @     0x7f9bd9102468  op::NetCaffe::initializationOnThread()
    @     0x7f9bd91974cc  op::addCaffeNetOnThread()
    @     0x7f9bd919879f  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f9bd919db00  op::PoseExtractorNet::initializationOnThread()
    @     0x7f9bd9194111  op::PoseExtractor::initializationOnThread()
    @     0x7f9bd918e9b1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f9bd9119aa1  op::Worker<>::initializationOnThreadNoException()
    @     0x7f9bd9119be0  op::SubThread<>::initializationOnThread()
    @     0x7f9bd911caf8  op::Thread<>::initializationOnThread()
    @     0x7f9bd911ccfd  op::Thread<>::threadFunction()
    @     0x7f9bd8a44b8e  (unknown)
    @     0x7f9bd817c6ba  start_thread
    @     0x7f9bd849951d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
