### ISSUE TITLE
Python binding？

### ISSUE THREAD

**Issue by shizhenjun** [CMU-Perceptual-Computing-Lab/openpose#400]
Do you have plan to develop the python binding of openpose？
I think many are looking forward to it！

**Comment by gineshidalgo99** [comment]
Yes we'd like to, we'll eventually do it but we haven't started it yet.

**Comment by shizhenjun** [comment]
If so,I believe the work must be awaresome！

**Comment by soulslicer** [comment]
We should be releasing one shortly

**Comment by gineshidalgo99** [comment]
Released a few months back.
