### ISSUE TITLE
Would it be more efficient if I used gray-scaled images?

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [CMU-Perceptual-Computing-Lab/openpose#401]
### Issue Summary
First of all, thanks for distributing this good program. 
I have a question.
Since FPS is a little low, I wonder if it would be helpful to use pre-gray-scaled images 

### Type of Issue
- Question
- Enhancement / offering possible extensions / pull request / etc

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): **Ubuntu 16.04** 
**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...? **CMake**
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): **8**
**cuDNN version**: **5.1**
**GPU model** (`nvidia-smi` in Ubuntu): **8 * NVIDIA K80 GPU 12GiB**
**Caffe version**: Default from OpenPose, custom version, ...? **Default from OpenPose**
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...? **Default from OpenPose**
Compiler (`gcc --version` in Ubuntu):  **5.4.0**

**Comment by gineshidalgo99** [comment]
No, the net has been trained with RGB images, so no difference in speed at all.

**Comment by KimSangYeon-DGU** [comment]
Thank you for your answer!!
