### ISSUE TITLE
Openpose on AWS Lambda

### ISSUE THREAD

**Issue by GeorgianaPetria** [CMU-Perceptual-Computing-Lab/openpose#404]
Has anybody manage to run open pose serverless on aws?

I know I can trigger a job on my EC2 machine, but was wondering if I can get away with not having a server.

**Comment by rumicuna** [comment]
Hi GeorgianaPetria,
I'm about to embark on trying to do this. Did you have any luck doing this? Any pointers would be appreciated.

**Comment by paulfryer** [comment]
Would love to know if anyone has done this successfully?

**Comment by DiarKarim** [comment]
What about now, has this issue been solved yet?
