### ISSUE TITLE
Question regarding 1_extract_from_image.cpp

### ISSUE THREAD

**Issue by georgecfwebtools** [CMU-Perceptual-Computing-Lab/openpose#405]
I am on Windows 10 with GPU 1050, i5 CPU. I could run 1_extract_from_image.cpp without a problem, it shows the result correctly.

I have the question regarding the pose data in this code.

After reading the image, where we get the pose data? I read through the [output page](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#keypoint-ordering), but within the code, I could not find where we get the 18 COCO pose data.

Could someone point me where in the code (1_extract_from_image.cpp) we capture the 18 COCO pose data?

Please if this is duplicate post, could you point me the right direction to find the answer, not just close the question.

Thank you!

George

**Comment by gineshidalgo99** [comment]
tutorial_wrapper/ examples should help you with it.

It's an array called poseKeypoints.

Let us know otherwise.
