### ISSUE TITLE
Detecting or focusing on only a subset of keypoints

### ISSUE THREAD

**Issue by mz496** [CMU-Perceptual-Computing-Lab/openpose#406]
### Issue Summary
Potentially a generalized version of https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/360.

I'm trying to apply OpenPose to use pose estimation on people who are sitting, potentially in an auditorium setting. Ideally, OpenPose would only try to identify some limbs, like the arms.

Is there a way to specify that I want OpenPose to estimate particular limbs only? I noticed that the pose keypoint "skeletons" are defined in one of the files, so could I add my own structures to change what OpenPose will detect?

Or would the best approach to be to feed in a specialized model on the type of images/video I plan to process? (I noticed that OpenPose does fine with missing lower body limbs on my images/video but sometimes tries to incorrectly guess at limbs that aren't actually visible, probably because the default model expects legs to be visible.)

### Type of Issue
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
You'd have to modify pose/poseParametersRender.cpp and pose/poseRender.cu-cpp to only display a few of them or to create your own rendering/skeleton function.
