### ISSUE TITLE
I have some questions in 3d, could anyone help ?

### ISSUE THREAD

**Issue by Andy95800** [CMU-Perceptual-Computing-Lab/openpose#408]
is PS3 Eye cameras work as well as FLIR cameras ? What's the difference?
 Is the Spinnaker Necessary? thanks

**Comment by aniketzz** [comment]
you can use any camera. you need to make some changes within the code. please refer #356. I had the similar doubt earlier.

Thanks

**Comment by Andy95800** [comment]
Thanks
