### ISSUE TITLE
OpenPose build failed VS2017 + Windows 10 + CUDA 9.1

### ISSUE THREAD

**Issue by nanma56** [CMU-Perceptual-Computing-Lab/openpose#410]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
The CMD:
cuda_execute_process(
  "Generating dependency file: ${NVCC_generated_dependency_file}"
  COMMAND "${CUDA_NVCC_EXECUTABLE}"
  -M
  ${CUDACC_DEFINE}
  "${source_file}"
  -o "${NVCC_generated_dependency_file}"
  ${CCBIN}
  ${nvcc_flags}
  ${nvcc_host_compiler_flags}
  ${depends_CUDA_NVCC_FLAGS}
  -DNVCC
  ${CUDA_NVCC_INCLUDE_ARGS}
  )

under the file "openpose_generated_maximumBase.cu.obj.Release.cmake" generated an error

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)

1>Generating dependency file: C:/openpose_git/openpose/build/src/openpose/CMakeFiles/openpose.dir/core/openpose_generated_maximumBase.cu.obj.NVCC-dependCOMMANDC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/bin/nvcc.exe-M-D__CUDACC__C:/openpose_git/openpose/src/openpose/core/maximumBase.cu-oC:/openpose_git/openpose/build/src/openpose/CMakeFiles/openpose.dir/core/openpose_generated_maximumBase.cu.obj.NVCC-depend-ccbinC:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/bin-m64-Dopenpose_EXPORTS-DBOOST_ALL_NO_LIB-DUSE_CAFFE-DUSE_CUDA-DBUILD_MODULE_3D-Xcompiler,"/W4","/EHsc","/MP","/MD","/Ox","/DNDEBUG","/Ot","/Oi","/Gy","/Z7"-DNVCC-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/include-IC:/openpose_git/openpose/include-IC:/openpose_git/openpose/3rdparty/windows/opencv/include-IC:/openpose_git/openpose/3rdparty/windows/caffe/include-IC:/openpose_git/openpose/3rdparty/windows/caffe/include2-IC:/openpose_git/openpose/3rdparty/windows/freeglut/include-IC:/openpose_git/openpose/3rdparty/windows/spinnaker/include-IC:/openpose_git/openpose/3rdparty/windows/caffe3rdparty/include/boost-1_61-IC:/openpose_git/openpose/3rdparty/windows/caffe3rdparty/include
1>CMake Error at openpose_generated_maximumBase.cu.obj.Release.cmake:230 (message):
1>  Error generating
1>  C:/openpose_git/openpose/build/src/openpose/CMakeFiles/openpose.dir/core/Release/openpose_generated_maximumBase.cu.obj
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "openpose.vcxproj" -- FAILED.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Windows 10 64bit
**Installation mode**:  VS2017, CMake-GUI
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 9.1
**cuDNN version**: 
**GPU model** (`nvidia-smi` in Ubuntu): 1080 TI
**Caffe version**: Default from OpenPose
**OpenCV version**: 3.3.1
Compiler (`gcc --version` in Ubuntu):

**Comment by lidabing** [comment]
caffe don't support CUDA 9

**Comment by nanma56** [comment]
Thank you for the comments. I managed to get it work on Ubuntu with cuda 9.1 and cudnn7 by regenerating caffe.pb.h.

I will see if similar trick can be applied to Windows

Sent from BlueMail<http://www.bluemail.me/r?b=11870>
On Feb 3, 2018, at 12:03 AM, "李大兵" <notifications@github.com<mailto:notifications@github.com>> wrote:

caffe don't support CUDA 9

**Comment by nanma56** [comment]
This issue is due to the cuda and VS2017 incompatibilities. So the working combinations for me are:
1) ubuntu 16.04, cuda9+ cudnn7
2) windows 10, VS2015 + cuda8 + cudnn6

**Comment by gineshidalgo99** [comment]
windows 10, VS2015 + cuda8 + cudnn5.1 should also work (it's the one i use and the one that the doc recommends)

**Comment by yw155** [comment]
Hi @nanma56, could you tell me how to manage caffe to get it work on ubuntu 16.04 with cuda 9.1 and cudnn 7? Now the lastest nvidia driver is not compatible with cuda 8. If openpose can use the lastest cuda and cudnn, it should be better. Thanks.

**Comment by repoalpha** [comment]
I raised a similar issue using CUDA 9.1 cuDNN 7 on 16.04 where it all compiles ok using the GPU, loads the default caffe ok when compiling, but when I run the demo:

./build/examples/openpose/openpose.bin --video examples/media/video.avi

It auto detects 1 GPU but says it "cannot use GPU in CPU-only caffe:check mode

But it was compiled using GPU mode. The keyword CUDA is present. I heard I may need to change the Cmake.config file but I am unsure where that is located.
