### ISSUE TITLE
can't find cuda.cpp

### ISSUE THREAD

**Issue by lidabing** [CMU-Perceptual-Computing-Lab/openpose#411]
### OpenPose Output (if any)
1>------ Build started: Project: OpenPose, Configuration: Release x64 ------
1>  cuda.cpp
1>c1xx : fatal error C1083: Cannot open source file: '..\..\src\openpose\utilities\cuda.cpp': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
**Operating system** (`Win10):
**Installation mode**:  VS2015, (Windows);

**Comment by gineshidalgo99** [comment]
My bad, I'll fix it. But that version is anyway deprecated. Please, use the Cmake installer version (recommended), see the instructions in doc/instructions.md.

**Comment by alexdd1987** [comment]
Hi, I tried used the cmake installer as you suggested here, but it still does not compile, there are a lot of unresolved externals.

1>------ Build started: Project: openpose, Configuration: Debug x64 ------
1>     Creating library C:/Users/Alessandro/Desktop/newuser/openpose/build/src/openpose/Debug/openposed.lib and object C:/Users/Alessandro/Desktop/newuser/openpose/build/src/openpose/Debug/openposed.exp
1>openpose_generated_renderHand.cu.obj : warning LNK4049: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_bodyPartConnectorBase.cu.obj : warning LNK4049: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_renderPose.cu.obj : warning LNK4049: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_maximumBase.cu.obj : warning LNK4217: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported in function "void __cdecl op::error<char const *>(char const * const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$error@PEBD@op@@YAXAEBQEBDHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1@Z)
1>openpose_generated_nmsBase.cu.obj : warning LNK4049: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_resizeAndMergeBase.cu.obj : warning LNK4049: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_renderFace.cu.obj : warning LNK4049: locally defined symbol ?error@op@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H00@Z (void __cdecl op::error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_renderHand.cu.obj : warning LNK4049: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_bodyPartConnectorBase.cu.obj : warning LNK4049: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_renderPose.cu.obj : warning LNK4049: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_maximumBase.cu.obj : warning LNK4217: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported in function "void __cdecl op::maximumGpu<float>(float *,float const * const,class std::array<int,4> const &,class std::array<int,4> const &)" (??$maximumGpu@M@op@@YAXPEAMQEBMAEBV?$array@H$03@std@@2@Z)
1>openpose_generated_nmsBase.cu.obj : warning LNK4049: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_resizeAndMergeBase.cu.obj : warning LNK4049: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_renderFace.cu.obj : warning LNK4049: locally defined symbol ?cudaCheck@op@@YAXHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z (void __cdecl op::cudaCheck(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported
1>openpose_generated_renderFace.cu.obj : warning LNK4217: locally defined symbol ?getNumberCudaThreadsAndBlocks@op@@YAXAEAUdim3@@0AEBU?$Point@H@1@@Z (void __cdecl op::getNumberCudaThreadsAndBlocks(struct dim3 &,struct dim3 &,struct op::Point<int> const &)) imported in function "void __cdecl op::renderFaceKeypointsGpu(float *,struct op::Point<int> const &,float const * const,int,float,float)" (?renderFaceKeypointsGpu@op@@YAXPEAMAEBU?$Point@H@1@QEBMHMM@Z)
1>openpose_generated_renderHand.cu.obj : warning LNK4217: locally defined symbol ?getNumberCudaThreadsAndBlocks@op@@YAXAEAUdim3@@0AEBU?$Point@H@1@@Z (void __cdecl op::getNumberCudaThreadsAndBlocks(struct dim3 &,struct dim3 &,struct op::Point<int> const &)) imported in function "void __cdecl op::`dynamic initializer for 'HAND_TRAINED_MODEL''(void)" (??__EHAND_TRAINED_MODEL@op@@YAXXZ)
1>openpose_generated_renderPose.cu.obj : warning LNK4049: locally defined symbol ?getNumberCudaThreadsAndBlocks@op@@YAXAEAUdim3@@0AEBU?$Point@H@1@@Z (void __cdecl op::getNumberCudaThreadsAndBlocks(struct dim3 &,struct dim3 &,struct op::Point<int> const &)) imported
1>openpose_generated_bodyPartConnectorBase.cu.obj : warning LNK4217: locally defined symbol ?getPoseNumberBodyParts@op@@YAIW4PoseModel@1@@Z (unsigned int __cdecl op::getPoseNumberBodyParts(enum op::PoseModel)) imported in function "void __cdecl op::connectBodyPartsGpu<float>(class op::Array<float> &,class op::Array<float> &,float const * const,float const * const,enum op::PoseModel,struct op::Point<int> const &,int,float,float,int,float,float,float const * const,float const * const)" (??$connectBodyPartsGpu@M@op@@YAXAEAV?$Array@M@0@0QEBM1W4PoseModel@0@AEBU?$Point@H@0@HMMHMM11@Z)
1>openpose_generated_renderPose.cu.obj : warning LNK4217: locally defined symbol ?getPoseNumberBodyParts@op@@YAIW4PoseModel@1@@Z (unsigned int __cdecl op::getPoseNumberBodyParts(enum op::PoseModel)) imported in function "void __cdecl op::checkAlpha(float)" (?checkAlpha@op@@YAXM@Z)
1>openpose_generated_bodyPartConnectorBase.cu.obj : warning LNK4217: locally defined symbol ?getPosePartPairs@op@@YAAEBV?$vector@IV?$allocator@I@std@@@std@@W4PoseModel@1@@Z (class std::vector<unsigned int,class std::allocator<unsigned int> > const & __cdecl op::getPosePartPairs(enum op::PoseModel)) imported in function "void __cdecl op::connectBodyPartsGpu<float>(class op::Array<float> &,class op::Array<float> &,float const * const,float const * const,enum op::PoseModel,struct op::Point<int> const &,int,float,float,int,float,float,float const * const,float const * const)" (??$connectBodyPartsGpu@M@op@@YAXAEAV?$Array@M@0@0QEBM1W4PoseModel@0@AEBU?$Point@H@0@HMMHMM11@Z)
1>openpose_generated_renderPose.cu.obj : warning LNK4217: locally defined symbol ?getPosePartPairs@op@@YAAEBV?$vector@IV?$allocator@I@std@@@std@@W4PoseModel@1@@Z (class std::vector<unsigned int,class std::allocator<unsigned int> > const & __cdecl op::getPosePartPairs(enum op::PoseModel)) imported in function "void __cdecl op::renderPoseKeypointsGpu(float *,enum op::PoseModel,int,struct op::Point<int> const &,float const * const,float,bool,bool,float)" (?renderPoseKeypointsGpu@op@@YAXPEAMW4PoseModel@1@HAEBU?$Point@H@1@QEBMM_N4M@Z)
1>openpose_generated_bodyPartConnectorBase.cu.obj : warning LNK4217: locally defined symbol ?getPoseMapIndex@op@@YAAEBV?$vector@IV?$allocator@I@std@@@std@@W4PoseModel@1@@Z (class std::vector<unsigned int,class std::allocator<unsigned int> > const & __cdecl op::getPoseMapIndex(enum op::PoseModel)) imported in function "void __cdecl op::connectBodyPartsGpu<float>(class op::Array<float> &,class op::Array<float> &,float const * const,float const * const,enum op::PoseModel,struct op::Point<int> const &,int,float,float,int,float,float,float const * const,float const * const)" (??$connectBodyPartsGpu@M@op@@YAXAEAV?$Array@M@0@0QEBM1W4PoseModel@0@AEBU?$Point@H@0@HMMHMM11@Z)
1>openpose_generated_renderFace.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_renderHand.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_bodyPartConnectorBase.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_renderPose.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_maximumBase.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_nmsBase.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_resizeAndMergeBase.cu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>wrapperStructPose.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>renderer.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>renderer.cpp.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>wrapperAuxiliary.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>wrapperStructFace.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>wrapperStructHand.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>wrapperStructOutput.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>keypoint.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openCv.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>profiler.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>string.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>webcamReader.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>errorAndLog.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>fileSystem.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>flagsToOpenPose.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>ipCameraReader.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>producer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>videoCaptureReader.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>videoReader.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseParametersRender.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>renderPose.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>imageDirectoryReader.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseExtractor.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseExtractorCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseGpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseParameters.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>renderHand.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>bodyPartConnectorBase.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>bodyPartConnectorCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>poseCpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>handExtractor.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>handExtractorCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>handCpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>handGpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>gui.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>guiInfoAdder.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>handDetector.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>handDetectorFromTxt.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>videoSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>cuda.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>gpu.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>frameDisplayer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>imageSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>jsonOfstream.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>keypointSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>peopleJsonSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>cocoJsonSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>fileSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>fileStream.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>heatMapSaver.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>faceExtractorCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>faceCpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>faceGpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>renderFace.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>personIdExtractor.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>faceDetector.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>faceDetectorOpenCV.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>faceExtractor.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>scaleAndSizeExtractor.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>cameraParameters.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>pointGrey.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>reconstruction3D.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>point.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>rectangle.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>resizeAndMergeBase.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>resizeAndMergeCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>netCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>nmsBase.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>nmsCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>opOutputToCvMat.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>gpuRenderer.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>keypointScaler.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>maximumBase.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>maximumCaffe.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>array.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>cvMatToOpInput.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>cvMatToOpOutput.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>datum.obj : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>openpose_generated_renderFace.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openpose_generated_renderHand.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openpose_generated_bodyPartConnectorBase.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openpose_generated_renderPose.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openpose_generated_maximumBase.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openpose_generated_nmsBase.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openpose_generated_resizeAndMergeBase.cu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>wrapperStructPose.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>defineTemplates.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>renderer.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>renderer.cpp.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>wrapperAuxiliary.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>wrapperStructFace.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>wrapperStructHand.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>wrapperStructOutput.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>keypoint.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>openCv.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>profiler.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>string.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>webcamReader.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>errorAndLog.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>fileSystem.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>flagsToOpenPose.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>ipCameraReader.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>producer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>videoCaptureReader.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>videoReader.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseParametersRender.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>renderPose.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>imageDirectoryReader.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseExtractor.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseExtractorCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseGpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseParameters.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>renderHand.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>bodyPartConnectorBase.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>bodyPartConnectorCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>poseCpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>handExtractor.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>handExtractorCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>handCpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>handGpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>gui.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>guiInfoAdder.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>handDetector.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>handDetectorFromTxt.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>videoSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>cuda.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>gpu.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>frameDisplayer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>imageSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>jsonOfstream.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>keypointSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>peopleJsonSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>cocoJsonSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>fileSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>fileStream.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>heatMapSaver.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>faceExtractorCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>faceCpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>faceGpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>renderFace.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>personIdExtractor.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>faceDetector.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>faceDetectorOpenCV.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>faceExtractor.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>scaleAndSizeExtractor.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>cameraParameters.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>pointGrey.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>reconstruction3D.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>point.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>rectangle.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>resizeAndMergeBase.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>resizeAndMergeCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>netCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>nmsBase.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>nmsCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>opOutputToCvMat.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>gpuRenderer.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>keypointScaler.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>maximumBase.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>maximumCaffe.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>array.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>cvMatToOpInput.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>cvMatToOpOutput.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>datum.obj : error LNK2001: unresolved external symbol __imp__CrtDbgReportW
1>msvcprtd.lib(locale0_implib.obj) : error LNK2019: unresolved external symbol __imp__free_dbg referenced in function "public: static void __cdecl std::_Fac_node::operator delete(void *)" (??3_Fac_node@std@@SAXPEAX@Z)
1>msvcprtd.lib(locale0_implib.obj) : error LNK2019: unresolved external symbol __imp__malloc_dbg referenced in function "public: static void * __cdecl std::_Fac_node::operator new(unsigned __int64)" (??2_Fac_node@std@@SAPEAX_K@Z)
1>C:\Users\Alessandro\Desktop\newuser\openpose\build\x64\Debug\openposed.dll : fatal error LNK1120: 4 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by gineshidalgo99** [comment]
Could you try compiling in Release mode rather than Debug? (Just to know where the error is located)

**Comment by alexdd1987** [comment]
I just tried the Release version and it's compiling, but Debug is still not compiling, with the output that I pasted in my previous message

**Comment by gineshidalgo99** [comment]
@alexdd1987 That error comes from FreeGLUT, so I understand it only happens when using the 3D module. With no 3D module, debug version should work. Is this correct? Does the non-3D module enabled OPenPose version work? (So I can isolate the error and fix it)

**Comment by gineshidalgo99** [comment]
@lidabing Fixed

**Comment by gineshidalgo99** [comment]
@alexdd1987 It doesn't happen if downloading the latest OpenPose version and installing it with CMake. So I assume that maybe you are using an old OpenPose version (before the debug version was added 2-3 weeks ago) or maybe you did not download the freeglut version that includes the debug binaries.
