### ISSUE TITLE
Something wrong when I use --write_images

### ISSUE THREAD

**Issue by shootingliu** [CMU-Perceptual-Computing-Lab/openpose#413]
Hello, 

Thanks for the great job.

All things gose well , but when I use --write_images I got damaged images sometimes.

Like this:

![1](https://user-images.githubusercontent.com/24687585/35769464-49e9cbd6-0946-11e8-8db2-caddec7b6d4b.png)

**Comment by gineshidalgo99** [comment]
Fill the issues template to allow us to debug it. Closed meanwhile
