### ISSUE TITLE
how can i make the '--part_candidates' to be used?

### ISSUE THREAD

**Issue by DongJT1996** [CMU-Perceptual-Computing-Lab/openpose#414]
### OpenPose Output -- how can i make the '--part_candidates' to be used?

the result shows like the follows:

ting@ting:~/mywork/openpose$ ./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_keypoint_json output/ --no_display --render_pose 0 --part_candidates
ERROR: unknown command line flag 'part_candidates'

**Comment by gineshidalgo99** [comment]
You must be using an old version, try updating OpenPose.
