### ISSUE TITLE
January 2018 - Windows 10 and openpose not working

### ISSUE THREAD

**Issue by jrm2107** [CMU-Perceptual-Computing-Lab/openpose#415]
I've been through every post and workaround, and I still cannot get openpose to work on Windows 10.  CUDA 8, CUDA 9, VS 2015, VS 2017, you name it...

Can someone please provide an updated post (Jan 2018) on the state of successfully compiling openpose on Windows 10.  The installation page is worthless.  It would be great if someone had a installable MSI file by now...

**Comment by gineshidalgo99** [comment]
Following the latest installation steps (CMake) perfectly work in the 3 Windows PCs I tried. Otherwise, provide your whole system configuration and error

**Comment by jrm2107** [comment]
Let's start with this one.  There isn't even mention of CUDA on your installation website, but it seems to be one of the biggest problems.

`Starting pose estimation demo.
Auto-detecting camera index... Detected and opened camera 0.

Error:
Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

Coming from:
- C:\Users\user\Documents\GitHub\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():48
- C:\Users\user\Documents\GitHub\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- C:\Users\user\Documents\GitHub\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():58
- C:\Users\user\Documents\GitHub\openpose\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- C:\Users\user\Documents\GitHub\openpose\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::configure():888`

**Comment by gineshidalgo99** [comment]
I've just added in the doc/installation.md file the installation pre-requisites. Best

**Comment by jrm2107** [comment]
JetPack for Windows?
