### ISSUE TITLE
Taking input from the network

### ISSUE THREAD

**Issue by manu-tej** [CMU-Perceptual-Computing-Lab/openpose#416]
Hi,

I can send and receive data using zmqueues (zmqs). I am wondering whether I can use the zmqs to transfer images to openpose and receive processed images/keypoints. Kindly let me know how it can be done. I tried to change the UserInputClass of 3_user_asynchronous.cpp in examples/tutorial_wrappers/ to take my input but of no avail.

**Comment by gineshidalgo99** [comment]
I am not familiar with zmqueues, but my understanding is that you desire to modify the input (to read your custom image) and output (to send back the image/keypoints to your custom system).

Therefore, you must simply follow the examples in tutorial_wrapper. I'd say the best fit is 2_user_synchronous.cpp for your case, where you simply wanna re-implement `WUserInput` and `WUserOutput` to receive/send back to your zmqs system, while you can remove `WUserPostProcessing` as you don't need it here.
