### ISSUE TITLE
OpenPose build issue -- "unresolved external symbol "void __cdecl op::wrapperConfigureSecurityChecks(struct op::WrapperStructPose const &,struct op::WrapperStructFace const &,struct op::WrapperStructHand const &,struct op::WrapperStructInput const &,struct op::WrapperStructOutput const &,bool,bool,enum op::ThreadManagerMode)"

### ISSUE THREAD

**Issue by nanma56** [CMU-Perceptual-Computing-Lab/openpose#417]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
With the latest openpose code, without 3D, there are some linkage issues

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl op::wrapperConfigureSecurityChecks(struct op::WrapperStructPose const &,struct op::WrapperStructFace const &,struct op::WrapperStructHand const &,struct op::WrapperStructInput const &,struct op::WrapperStructOutput const &,bool,bool,enum op::ThreadManagerMode)" (?wrapperConfigureSecurityChecks@op@@YAXAEBUWrapperStructPose@1@AEBUWrapperStructFace@1@AEBUWrapperStructHand@1@AEBUWrapperStructInput@1@AEBUWrapperStructOutput@1@_N5W4ThreadManagerMode@1@@Z) referenced in function "public: void __cdecl op::Wrapper<class std::vector<struct UserDatum,class std::allocator<struct UserDatum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct UserDatum,class std::allocator<struct UserDatum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct UserDatum,class std::allocator<struct UserDatum> > >,class std::queue<class std::shared_ptr<class std::vector<struct UserDatum,class std::allocator<struct UserDatum> > >,class std::deque<class std::shared_ptr<class std::vector<struct UserDatum,class std::allocator<struct UserDatum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct UserDatum,class std::allocator<struct UserDatum> > > > > > > >::configure(struct op::WrapperStructPose const &,struct op::WrapperStructFace const &,struct op::WrapperStructHand const &,struct op::WrapperStructInput const &,struct op::WrapperStructOutput const &)" (?configure@?$Wrapper@V?$vector@UUserDatum@@V?$allocator@UUserDatum@@@std@@@std@@V?$shared_ptr@V?$Worker@V?$shared_ptr@V?$vector@UUserDatum@@V?$allocator@UUserDatum@@@std@@@std@@@std@@@op@@@2@V?$Queue@V?$shared_ptr@V?$vector@UUserDatum@@V?$allocator@UUserDatum@@@std@@@std@@@std@@V?$queue@V?$shared_ptr@V?$vector@UUserDatum@@V?$allocator@UUserDatum@@@std@@@std@@@std@@V?$deque@V?$shared_ptr@V?$vector@UUserDatum@@V?$allocator@UUserDatum@@@std@@@std@@@std@@V?$allocator@V?$shared_ptr@V?$vector@UUserDatum@@V?$allocator@UUserDatum@@@std@@@std@@@std@@@2@@2@@2@@op@@@op@@QEAAXAEBUWrapperStructPose@2@AEBUWrapperStructFace@2@AEBUWrapperStructHand@2@AEBUWrapperStructInput@2@AEBUWrapperStructOutput@2@@Z)	3_user_asynchronous	C:\openpose_git\openpose\build\examples\tutorial_wrapper\3_user_asynchronous.obj	1	

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Windows 10
**Installation mode**: VS2015, CMake,
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA 8.0
**cuDNN version**: 5.1
**Release or Debug mode**? (by defualt: release): Release
**3-D Reconstruction module added**? (by default: no): No
**GPU model** (`nvidia-smi` in Ubuntu): 1080 Ti
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled 3.3.1
Compiler (`gcc --version` in Ubuntu): MS V140

**Comment by gineshidalgo99** [comment]
Try deleting the cache of CMake, the file is there.

**Comment by nanma56** [comment]
I did a little debugging, so far,  on the latest Openpose code the following components builds ok on WIndows 10 + CUDA 8 + CUDNN 5.1 + VS2015
1) Openpose lib
2) OpenPose demo
3) examples->tutorial->pose
4) examples->tutorial->thread
The ones failed on windows:
1) Examples->Tutorial-> add modules
2)  Examples->Tutorial->Wrapper

**Comment by nanma56** [comment]
@gineshidalgo99 Thank you for the comment. I deleted the CMakelist.txt but the problem persisit

**Comment by gineshidalgo99** [comment]
@nanma56 Fixed in the latest commit. Your feed-back telling me where it fails was super useful (as I was compiling only the demo and I couldn't see any error)

**Comment by nanma56** [comment]
Beautiful. Thank you for your help.

Sent from BlueMail<http://www.bluemail.me/r?b=11998>
On Feb 6, 2018, at 12:52 PM, Gines <notifications@github.com<mailto:notifications@github.com>> wrote:

@nanma56<https://github.com/nanma56> Fixed in the latest commit. Your feed-back telling me where it fails was super useful (as I was compiling only the demo and I couldn't see any error)
