### ISSUE TITLE
Compilation halts at NVCC stage

### ISSUE THREAD

**Issue by gbtom** [CMU-Perceptual-Computing-Lab/openpose#418]
### Issue Summary

After configuring and generating with Cmake-GUI,

VS2015 gives the following output when building the openpose library
```
1> Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/core/Release/openpose_generated_maximumBase.cu.obj
1>  maximumBase.cu
1>  CMake Error at openpose_generated_maximumBase.cu.obj.Release.cmake:222 (message):
1>    Error generating
1>    openpose/build/src/openpose/CMakeFiles/openpose.dir/core/Release/openpose_generated_maximumBase.cu.obj
```

Observation is that Cmake/NVCC fails to create "openpose/build/src/openpose/CMakeFiles/openpose.dir/core/openpose_generated_maximumBase.cu.obj.NVCC-depend". Compilation can't continue without this file.

### Type of Issue
Compilation/installation error

### Your System Configuration
**Operating system**: Windows 10 x64
**Installation mode**:  CMake 3.9.4 VS2015
**CUDA version**: 8.0
**cuDNN version**: 5.1
**Release or Debug mode**: Release
**3-D Reconstruction module added**: No
**GPU model** : GTX 1080 Ti
**Caffe version**: Default
**OpenCV version**: Default

**Comment by gineshidalgo99** [comment]
It sounds as VS is not finding CUDA. Did you install CUDA 8.0 after Visual Studio 2015 was installed to assure that the CUDA installation will generate all necessary files for VS? If CUDA was already installed, re-install CUDA after installing VS.

**Comment by gbtom** [comment]
I think that was the problem, but reinstall didn't fix it. NVCC wasn't finding some of the headers, so I had to the change the .cmake files manually to add extra include paths.

**Comment by Arthurfangm** [comment]
> I think that was the problem, but reinstall didn't fix it. NVCC wasn't finding some of the headers, so I had to the change the .cmake files manually to add extra include paths.

Hello, glad to see you solved the problem. I am facing the same problem now. Could you give me some advice to modify the .cmake files.
