### ISSUE TITLE
Build failed -- 3D demo on Ubuntu

### ISSUE THREAD

**Issue by nanma56** [CMU-Perceptual-Computing-Lab/openpose#419]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
When enable the building the 3D demo, compiler complaint about :"undefined reference to `gluLookAt'"

OpenGL was installed on my system:
/usr/include/GL/freeglut.h
/usr/include/GL/freeglut_std.h
/usr/include/GL/glut.h
/usr/include/GL/freeglut_ext.h
/usr/lib/x86_64-linux-gnu/libglut.so.3
/usr/lib/x86_64-linux-gnu/libglut.so
/usr/lib/x86_64-linux-gnu/libglut.a
/usr/lib/x86_64-linux-gnu/libglut.so.3.9.0

I think we may need to explicitly tell the compiler where to find the lib as below, 
g++ <CPP file> -o <OBJ> -I /usr/lib/libglut.so.3 /usr/lib/libGL.so.1 /usr/lib/libGLU.so.1 -lG

but I cant find which file i should add it to.

Please advise

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
You might select multiple topics, :
- Compilation/installation error
### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04
**Installation mode**: CMake, sh script, manual Makefile installation, 
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA-8.0
**cuDNN version**: 5.1
**Release or Debug mode**? (by defualt: release): Release
**3-D Reconstruction module added**? (by default: no): Yes
**GPU model** (`nvidia-smi` in Ubuntu): NVIDIA-SMI 390.12                 Driver Version: 390.12 
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled 3.3.`
Compiler (`gcc --version` in Ubuntu):(Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
Using CMake-gui, check the "Advanced" checkbox and make sure CMake is actually finding all the `GLUT_something_else` flags. Let me know whether it is finding them or not (if not, also try to manually set them).

**Comment by nanma56** [comment]
![image](https://user-images.githubusercontent.com/19244104/35877143-685d039e-0b6c-11e8-9e28-2edb308aa5f3.png)

Sorry, I forgot to mention it. It found them and double checked the lib was there. But the build still fails

**Comment by gineshidalgo99** [comment]
Maybe:
`sudo apt-get update`

This will update your apt database to the most recent available packages.
`sudo apt-get install build-essential`
This installs the necessary development tools for building source code.
`sudo apt-get install freeglut3 freeglut3-dev libxmu-dev libxi-dev`

**Comment by nanma56** [comment]
issue solved. Thank you

**Comment by gineshidalgo99** [comment]
What did it fix it? My previous answer or something else? Thanks!

**Comment by nanma56** [comment]
Hi,

So I did your steps with force install and reboot fixed it.

Thanks

Nan

Sent from BlueMail<http://www.bluemail.me/r?b=11998>
On Feb 12, 2018, at 3:05 PM, Gines <notifications@github.com<mailto:notifications@github.com>> wrote:

What did it fix it? My previous answer or something else? Thanks!
