### ISSUE TITLE
Can I used open pose to train my own data?

### ISSUE THREAD

**Issue by spark123456789** [CMU-Perceptual-Computing-Lab/openpose#42]
Hi all,
I have two question:
First， Can I use open pose to train my own data, something like houre parts detection?
Second, Can I specified The joint number of an object, like 15, 19 or 50 joints ?
Thank you for your reply!

**Comment by gineshidalgo99** [comment]
Both 1 and 2: Yeah, you can, but we do not support that feature so far. Check the original training repository: https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation
Best
