### ISSUE TITLE
Unresolved external symbol "void __cdecl op::wrapperConfigureSecurityChecks .......

### ISSUE THREAD

**Issue by alchemyincarnate** [CMU-Perceptual-Computing-Lab/openpose#421]
### Issue Summary
I am unable to build after generating the solution with CMake. I have run all the batch files found in 3rdparty/windows/. CMake generates the files without error. When I try to build OpenPose.sln, it throws me the following error.

Other setups I have tried (with no success);
1. Visual Studio 2017 Community with CUDA 9.1
2. Building openpose with Caffe/BVLC instead of the libraries from the included downloaders

### OpenPose Output (if any)
![image](https://user-images.githubusercontent.com/36218507/35898693-1483f18c-0c03-11e8-86f1-db3a69ea3d48.png)

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** Windows 10
**Installation mode**: CMake, Visual Studio Enterprise 2015 with Update 3 x64
**CUDA version** 8.0, 9.1
**cuDNN version**: 5.1 (8.0), 7.0 (9.1)
**Release or Debug mode**? Release
**3-D Reconstruction module added**? No
**GPU model** Nvidia GeForce GTX 1080
**Caffe version**: Default from OpenPose
**OpenCV version**: Default from OpenPose
Compiler (`gcc --version` in Ubuntu): cl.exe 2015 x64

Thank you very much!!

**Comment by gineshidalgo99** [comment]
Please update OP, that problem was fixed yesterday.  Best
