### ISSUE TITLE
Why does increasing net_resolution sometimes decrease accuracy? 

### ISSUE THREAD

**Issue by megashigger** [CMU-Perceptual-Computing-Lab/openpose#422]
I've been testing OpenPose with various parameters and have noticed this happen quite frequently. For images of size 1920x1080, a net resolution of 512x288 performs consistently better than a net resolution of 1920x1080. Specifically: 
1. At higher resolutions, there are often detections of people who aren't present at all.
2. At higher resolutions, keypoints are missing or at the wrong location.

Should a higher net_resolution always perform better, everything else being equal?
Also, related question - what's the impact of setting a net_resolution that's lower than the input image?

**Comment by gineshidalgo99** [comment]
Lower = faster but less accuracy
Higher = slower but possibly more accurate

The net was trained on the default net_resolution, so unless you use the maximum configuration accuracy setting in the doc (~+12% acc boost), there is no guarantee that it'll be better or worse, as it was not trained with such a big resolution.

**Comment by megashigger** [comment]
@gineshidalgo99  got it. In that case how did you determine coupling multi scale with specifically a net_resolution of "1312x736" was optimal, and not an even higher net_resolution?

**Comment by gineshidalgo99** [comment]
`-1x736` shouldn't be better, just faster, but it'll consume much more GPU memory.

How to pick it? Trying different multi scales and checking acc. in COCO dataset

**Comment by megashigger** [comment]
@gineshidalgo99 thanks for helping me understand. I'm still a little unclear on where you derive those conclusions from.

1. Is `-1x736` faster than `1312x736` because the latter ads potentially unnecessary borders which means the input image is bigger?
2. Why does `-1x736` require more GPU memory?

**Comment by gineshidalgo99** [comment]
1. Exactly
2. For vertical images, -1 would become very high, so more memory. Ideally -1 should give more accuracy, but in practice there is no difference (I guess because vertical images don't have people or if they do, it's very big people)

**Comment by megashigger** [comment]
thanks @gineshidalgo99. One last questions - did you choose 1312x736 because that yielded the best results on coco, or some other reason?
