### ISSUE TITLE
Ubuntu Cmake-gui error while getting default Caffe

### ISSUE THREAD

**Issue by svarnypetr** [CMU-Perceptual-Computing-Lab/openpose#423]
### Issue Summary
This should not be a Caffe problem per se, but before I install custom Caffe I would like to make sure. I followed all the steps in the [install doc](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md) up until using the CMake-gui. There I ran into an error while downloading Caffe.

It seems to me CMake-gui does not download Caffe at all. I tried to wipe everything and try to install OpenPose again, but received the same mistake. I also tried to see if cmake follows the ifs in the CMakeLists.txt correctly and reaches the branches where he establishes that Caffe needs to be downloaded and it seems to me it does so.

CMake-gui returns the following error:

```
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Already on 'master'

M	CMakeLists.txt
Your branch is up-to-date with 'origin/master'.

Caffe will be built from source now.
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1915 (message):
  No download info given for 'openpose_caffe' and its source directory:

   /home/naoskin/openpose/3rdparty/caffe

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * URL
   * GIT_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
   * SVN_REVISION
   * DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  CMakeLists.txt:392 (ExternalProject_Add)
```

### Executed Command (if any)
CMake-gui according to installation guide.

### OpenPose Output (if any)
 None.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Installation mode**: CMake-gui

**CUDA version**: `CUDA Version 8.0.61`
**cuDNN version**: `ver. 5.1.10`
**Release or Debug mode**?: `release`
**3-D Reconstruction module added**?: `no`
**GPU model** `nvidia-smi 384.111 GeForce GTX 106`
**Caffe version**: `Default from OpenPose - or at least trying`
**OpenCV version**: ```pre-compiled `apt-get install libopencv-dev` (only Ubuntu)```
Compiler (`gcc --version` in Ubuntu): `5.4.0 20160609`

**Comment by gineshidalgo99** [comment]
If you were using an old OP version and you just updated it, you should simply re-download or re-clone OpenPose again and re-compile it.

We changed Caffe from being inside OP to be a submodule in GitHub (so it's easier to keep the latest Caffe version, but we found this kind of error when updating OpenPose from an old version).

Let me know if re-downloading it from scratch doesn't fix the issue.

**Comment by svarnypetr** [comment]
Hello Gines, 
thank you  for the reply. I tried a totally new install - removed OpenPose, followed the installation guide again from the top (i.e. went through the prerequisites also). Surprisingly it worked although my first clone was a clean install made from the master repo I cloned on Feb 8th. The only changes I made now that I am aware of:
1. cloning the current master repo (should be the same for ubuntu)
2. letting CMake-gui create the `/build` subfolder

So thank you for pushing me to restart.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back!

**Comment by MasterScrat** [comment]
Had the same issue. Same thing fixed it. Did both clones today. So thanks for the feedback! But this cost me quite some time. I used a fresh install of `ubuntu-16.04.4-server-amd64`.

**Comment by ashwinvk94** [comment]
### Issue Summary

I am facing the same issue while compiling for the CPU-ONLY  version.

Even when I reclone the openpose repo and start installation from scratch, I get the the same error.

CMake-gui returns the following error:
```
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1915 (message):
  No download info given for 'openpose_caffe' and its source directory:

   /home/ashwin/center_for_robolution/Intelligent retail store Demonstration/Body detection/openpose/3rdparty/caffe

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * URL
   * GIT_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
   * SVN_REVISION
   * DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  CMakeLists.txt:471 (ExternalProject_Add)
```
### Executed Command (if any)
CMake-gui according to installation guide.

### OpenPose Output (if any)

No output since it is a cmake error.

### Type of Issue

- Compilation/installation error

### Your System Configuration
**Operating system**: No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Installation mode**: CMake (Ubuntu)
**CUDA version** : CPU_ONLY mode
**cuDNN version**: CPU_ONLY mode
**CMake version** : 3.5.1
**Release or Debug mode**?: Release
**3-D Reconstruction module added**?: No
**GPU model** : CPU_ONLY mode
**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` 
Compiler :gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
Re-download OpenPose from scratch. If you try to move from Caffe CPU to Caffe GPU, this kind of errors might happen (as we use different Caffe repos for each one).

**Comment by ashwinvk94** [comment]
Even when I clone the repository and redo the installation process, I get the same error that I have mentioned above.

I have also tried the same with a fresh installation of Ubuntu 16.04.3 LTS. cmake still shows the same error.

**Comment by appleweed** [comment]
I fixed this issue by manually clone the caffe repo into the 3rdparty directory:
1. cd 3rdparty
2. git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git
3. Now, run cmake gui to Configure and Generate.

**Comment by vssli** [comment]
@appleweed  
works for me, bro, thanks!

**Comment by verihelp-viktor** [comment]
@appleweed 
Thank you, you saved my day!

**Comment by jbrownkramer** [comment]
I am installing on a Mac and I had this problem.  I tried re-cloning the repo and it didn't work.  I used the trick @appleweed suggested, which allowed me to make progress.

**Comment by soulslicer** [comment]
Hmm..i am unable to recreate this error. On my Mac, Cmake automatically downloads / clones caffe

**Comment by ShuminY** [comment]
I re-clone it. and got the same issue. (on Mac).
the 3rdparty/caffe folder is empty after the cloning. 
and I followed @appleweed by cloning caffe manually, and the configuring got done on CMake GUI.

**Comment by linhtn** [comment]
@appleweed Thank bro ^^

**Comment by rubenvandeven** [comment]
After cloning master, the 3rdparty/caffe folder stayed empty. For me this fix was to manually trigger the [git submodules](https://git-scm.com/book/nl/v1/Git-tools-Submodules) to update. So the clone step becomes:

```bash
git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose
cd openpose

git submodule init
git submodle update
```

Should this be added to the docs?

Thanks @appleweed for pointing me in the right direction.

**Comment by MartinFultot** [comment]
@appleweed You saved my life, fam.

**Comment by jhirsh** [comment]
@rubenvandeven After trying a lot, your message was the only one that pushed me forward :)

**Comment by gineshidalgo99** [comment]
@rubenvandeven Thanks! I will add it to the following commit!

**Comment by MiaYangheeKim** [comment]
@appleweed You are the best!!! Thank you very much! You saved my day!!! :3

**Comment by yuanzhedong** [comment]
@appleweed life saver!!

**Comment by njuallen** [comment]
I think document should mention that, git submodule init/update should be manually triggered.

**Comment by yaoolu** [comment]
@appleweed 
Thanks bro! Saved my day!!

**Comment by alon1samuel** [comment]
Thanks! I was stuck... :)

**Comment by Hunter0098** [comment]
@appleweed Thanks you.

**Comment by Aakash95-co** [comment]
thanks @appleweed your suggestion work for me !

**Comment by mdhmz1** [comment]
@appleweed Thanks, brother !! Appreciate the help

**Comment by poojakittur** [comment]
> I fixed this issue by manually clone the caffe repo into the 3rdparty directory:
> 
> 1. cd 3rdparty
> 2. git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git
> 3. Now, run cmake gui to Configure and Generate.

Works for me. Thanks !!

**Comment by tnzl** [comment]
@appleweed  Thanks brother! I was stuck on it from the last 2 days.

**Comment by jumpy88** [comment]
I think it should be better clarified, but [prerequisites docs](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md#general-tips) provide the solution:
`git submodule update --init --recursive --remote`

**Comment by TGMcLean** [comment]
@appleweed 's approach also worked for me, on MacOS.

**Comment by IternaAdolfo** [comment]
> After cloning master, the 3rdparty/caffe folder stayed empty. For me this fix was to manually trigger the [git submodules](https://git-scm.com/book/nl/v1/Git-tools-Submodules) to update. So the clone step becomes:
> 
> ```shell
> git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose
> cd openpose
> 
> git submodule init
> git submodle update
> ```
> 
> Should this be added to the docs?
> 
> Thanks @appleweed for pointing me in the right direction.

git submodule update
fatal: destination path '/home/amtete/Desktop/tf-pose/openpose/3rdparty/caffe' already exists and is not an empty directory.
fatal: clone of 'https://github.com/CMU-Perceptual-Computing-Lab/caffe.git' into submodule path '/home/amtete/Desktop/tf-pose/openpose/3rdparty/caffe' failed
Failed to clone '3rdparty/caffe'. Retry scheduled
Cloning into '/home/amtete/Desktop/tf-pose/openpose/3rdparty/pybind11'...
fatal: destination path '/home/amtete/Desktop/tf-pose/openpose/3rdparty/caffe' already exists and is not an empty directory.
fatal: clone of 'https://github.com/CMU-Perceptual-Computing-Lab/caffe.git' into submodule path '/home/amtete/Desktop/tf-pose/openpose/3rdparty/caffe' failed
Failed to clone '3rdparty/caffe' a second time, aborting
:P

**Comment by gsethi2409** [comment]
Hi! I'm using CPU-only OpenPose on Mac
When I try to build on GUI CMAKE it gives these errors:
Caffe_LIBRARIES-NOTFOUND
Caffe_LIBS-NOTFOUND

Please help!

**Comment by svarnypetr** [comment]
Probably do not post 

> Hi! I'm using CPU-only OpenPose on Mac
> When I try to build on GUI CMAKE it gives these errors:
> Caffe_LIBRARIES-NOTFOUND
> Caffe_LIBS-NOTFOUND

Probably do not post to a closed topic. But also, did you install Caffe?

**Comment by chamin96** [comment]
@appleweed Thanks!

**Comment by uhobeike** [comment]
>I fixed this issue by manually clone the caffe repo into the 3rdparty directory:
>
>    cd 3rdparty
>   git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git
>    Now, run cmake gui to Configure and Generate.

You may be able to do it this way, but it's not the way it should be. 
I think it is correct to clone using the submodule command.
```
git clone --recursive https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
```
