### ISSUE TITLE
can i use 2 regular cameras at once?

### ISSUE THREAD

**Issue by aniketzz** [CMU-Perceptual-Computing-Lab/openpose#425]
i would like to know, if i can use 2 regular cameras at once in openpose or do i have to use 2 different systems and run on each system with 2 different cameras.

**Comment by gineshidalgo99** [comment]
That's a quite ambiguous question, not sure if you just want to process 2 at the same time but indepently or if you wanna do some 3-D on top of them.
You can prepare your own code to do that from the `tutorial_wrapper` examples, whatever your goal is. e.g. you could run 2 webcams and run them with the 3d module to get 3d keypoints (doc/3d_overview or sth like that).

Let me know if something is not clear

**Comment by Em-Lopez** [comment]
I too, would like to know this:

**Comment by gurbela** [comment]
I can run 2 or 3 webcams from different positions and tracked one face (not 3d module)? If I can, How can I do this?
