### ISSUE TITLE
Cannot find OpenPose.Dll [Windows]

### ISSUE THREAD

**Issue by nellyneil** [CMU-Perceptual-Computing-Lab/openpose#426]
### Issue Summary
After following all of the installation instructions and generating with CMake, I receive a "System cannot find the file specified" (Openpose.dll) error when trying to release, with the system type set to x64. After checking myself, I see that I don't have the required file. How do I go about acquiring the necessary dll? 

My question specifically addresses this file, I've struggled with getting this installation to run properly but can never get past (sometimes) running the demo. I'd very much like to be able to get and store output if possible. 
Thank you! I apologize for my computer ineptitude. 

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** : Windows 8.1 x64
**Installation mode**: CMake VS2015
**CUDA version**: 8.0.61
**cuDNN version**: 5.1
**Release or Debug mode**?: Release
**3-D Reconstruction module added**?: No
**GPU model** :  GeForce GTX 1050 Ti
**Caffe version**: Default from OpenPose
**OpenCV version**: OpenPose default

**Comment by gineshidalgo99** [comment]
Then try compiling only the OpenPose (not the demo), by right click and set as startup project the OpenPose library project. In that way, VS gives you the exact error so you can know and share the issue.

**Comment by nellyneil** [comment]
Thanks for the clear tip and the quick response! I followed your instructions of setting up the OpenPose as a startup project, made sure that it was set to Release & x64 and pressed F5. I've attached a screenshot of my error, I see that I have the openpose.dll file in my folder now but I suppose it's not being recognized properly. I hope this helped to clarify the issue, and thank you for your time! 

![openpose dll error](https://user-images.githubusercontent.com/32889641/36084181-e96d4afa-0f88-11e8-81c3-a8aaa1439579.png)

**Comment by gineshidalgo99** [comment]
That makes sense, `OpenPose library` is a library, not an executable. So instead of clicking F5 or the green button, you must simply do right click and: "Build". Then, bottom left, in the error list, you should see which errors it had while compiling. If it didn't have, then setting OPenPoseDemo as main project and right click and build (and later green play button) should work

**Comment by z384647062** [comment]
I face the same problem.

**Comment by gineshidalgo99** [comment]
As a side note, compiling OpenPose is because you plan to edit OpenPose or integrate it with your program, so then you should already have experience in VS. Otherwise, simply use the latest OpenPose portable demo which you can find in the releases section:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases

**Comment by nellyneil** [comment]
This was super clear! Thank you so much, I'm really impressed with the level of support you're able to give. I'll be sure to check it tomorrow morning and let you know what the errors I receive are.

**Comment by nellyneil** [comment]
Hello! Sorry for the late update. 

So when I build the "openpose" located inside the library I get no errors and it says "Build succeeded" in the bottom right. Afterwards, I set OpenPoseDemo as the startup project, which I think is what you mean by main project, and this builds just fine. Finally, when I press the green button I'm given the following errors (2 pictures titled Debugger OpenPoseDemo in VS). I also took a screenshot of the CMake data as well, if that's helpful. 
![cmake report](https://user-images.githubusercontent.com/32889641/36292064-1c95911e-129d-11e8-9d97-10d1bf8ab334.png)
![first error-debugger openposedemo in vs](https://user-images.githubusercontent.com/32889641/36292065-1ca0429e-129d-11e8-8d30-f607c30a245c.png)
![second error- debugger openposedemo in vs](https://user-images.githubusercontent.com/32889641/36292066-1cab05a8-129d-11e8-97a9-17092f6b2e2d.png)





 I'm not planning to edit OpenPose or integrate it into anything, so I followed your advice and tried to use the portable demo. I extracted it to the default location in my downloads folder and clicked to launch the exe without changing any paths. I've attached the errors that that gave me and the VS debugger report. I hope these are helpful! 

![third error command prompt folder display](https://user-images.githubusercontent.com/32889641/36292068-23bd6cdc-129d-11e8-9620-ebaf63b37977.png)
![third error corresponding vs screen](https://user-images.githubusercontent.com/32889641/36292069-23cf3430-129d-11e8-9344-359fe1eedce3.png)

Finally, I've attached my system information in case there's any incompatibility issue. I think my machine is fine but just in case. 
[DXDIAG.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/1730107/DXDIAG.txt)

**Comment by nellyneil** [comment]
Update: I didn't correctly follow the quickstart directions. The demo will not work if you try to launch it by clicking on the .exe file. You need to open the command prompt, type `cd <the location of the file found from right clicking inside the bin file and clicking properties> ` and then type OpenPoseDemo.exe. 

Hopefully that will be useful for anyone else struggling like me haha. Thank you Gines for your help and patience with me, and if you see any other mistakes from these pictures I'd love to make sure that it's running optimally!

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back
