### ISSUE TITLE
question about the Neural Net ouput format at the last layer

### ISSUE THREAD

**Issue by nanma56** [CMU-Perceptual-Computing-Lab/openpose#427]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
After evaluating the framework, I'm trying to use the Neural Nets to do a transfer learning for my specific problem. I'm a little confused about the output heatmap format at the end of the network. The shape of the output in my case is (1, 57, 46, 82). My question is on the number, 57. 

Since i was using the coco model, so I should have 18 joints + 1 background, so 19. and Because it is RGB, so it is 19x3 = 57. My question is is the heatmap ordered as R: [0]. G:[19], B[38], or R[0], G:[1], B[2]?

I tried the do the scatter plot for both cases, but neither of them overlapping, so I dont know which assumption is correct. Please advise

Thank you

**Comment by gineshidalgo99** [comment]
18 joints + 1 bck + 19x2 PAFs. Check paper for details.
