### ISSUE TITLE
Cmake 3.9.1 error

### ISSUE THREAD

**Issue by caoyongang** [CMU-Perceptual-Computing-Lab/openpose#430]
### Issue Summary

Any hints about the configure error as below? 
---------------------------------------------------------------------
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 8.0
Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
Added CUDA NVCC flags for: sm_61
Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Caffe has already been downloaded.
Already on 'master'

Your branch is up-to-date with 'origin/master'.

Caffe will be built from source now.
CMake Error at /opt/cmake-3.9.1/share/cmake-3.9/Modules/FindCUDA.cmake:1739 (add_library):
  add_library cannot create target "openpose_core" because another target
  with the same name already exists.  The existing target is a shared library
  created in source directory "/root/src/openpose/src/openpose/3d".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  src/openpose/core/CMakeLists.txt:33 (cuda_add_library)

CMake Error at src/openpose/core/CMakeLists.txt:40 (target_link_libraries):
  Attempt to add link library "caffe" to target "openpose_core" which is not
  built in this directory.

CMake Error at src/openpose/core/CMakeLists.txt:46 (install):
  install TARGETS given target "openpose_core" which does not exist in this
  directory.

Adding Example 3d.bin
Adding Example openpose.bin
Adding Example 1_custom_post_processing.bin
Adding Example 1_extract_from_image.bin
Adding Example 2_extract_pose_or_heatmat_from_image.bin
Adding Example 1_openpose_read_and_display.bin
Adding Example 2_user_processing_function.bin
Adding Example 3_user_input_processing_and_output.bin
Adding Example 4_user_input_processing_output_and_datum.bin
Adding Example 1_user_asynchronous_output.bin
Adding Example 2_user_synchronous.bin
Adding Example 3_user_asynchronous.bin
Adding Example handFromJsonTest.bin
Download the models.
Downloading body (COCO) model...
Model already exists.
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
Configuring incomplete, errors occurred!
See also "/root/src/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/root/src/openpose/build/CMakeFiles/CMakeError.log".

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted

### Your System Configuration
**Operating system** (ubuntu 16.04 LTS):
**Installation mode**: CMake-gui (v 3.9.1)
**CUDA version** (8.0):
**cuDNN version**:5.1
**Release or Debug mode**? (by defualt: release):
**3-D Reconstruction module added**? (by default: no):
**GPU model** (GTX1060):
**Caffe version**: Default from OpenPose, custom version, ...?
**OpenCV version**: compiled from source 3.2.0
Compiler (`gcc --version` in Ubuntu):5.4.0

**Comment by gineshidalgo99** [comment]
Please update to the latest version, it was fixed today. Thanks
