### ISSUE TITLE
osc support

### ISSUE THREAD

**Issue by b2renger** [CMU-Perceptual-Computing-Lab/openpose#432]
Hello ,

The demo is quite impressive, thanks for making this available ! I would just like to propose an enhancement : what about giving out some osc support with the binaries ?

Ideally all the data could be streamed to software used by artists such as : pure-data, processing, openframeworks etc.

**Comment by gineshidalgo99** [comment]
Could you farther explain what osc actually means? (as I am not an expert in artistic software)

**Comment by b2renger** [comment]
Yes of course ! Thanks for inquiring

I mean this protocol : https://en.wikipedia.org/wiki/Open_Sound_Control
It's just a basic wrapper to package messages sent via udp or tcp, easy to use and to parse.

Since openframeworks is c++, I can point you to this implementation : https://github.com/openframeworks/openFrameworks/tree/master/addons/ofxOsc

This would enable people to just run the binaries, specify an ip and port number to get ready to do things with their favorite tool.

**Comment by sergiolover** [comment]
hello , first, what a great demo ! great great work !

and about OSC, Yes PLZZZ !!!!!!!!! anyway to stream point coordinates would be amazing !!!

**Comment by javl** [comment]
Just to add some more info to this request:

I believe OSC was meant as sort of a replacement for MIDI (hence the name, Open Sound Control).
It allows you to specify endpoints to send data to. 

For instance, you can take the center position of a face from a video, and send it to ```localhost:8338/pose/position```. Other applications can now listen to this address and if something is send, they will receive it.

An example of a similar application that uses OSC is FaceOSC ([more info here](https://github.com/kylemcdonald/ofxFaceTracker/releases), [general repository here](https://github.com/kylemcdonald/ofxFaceTracker)). This program detects faces and sends all available data (markers, position, etc.) over OSC.

Any other application that has OSC capability (such as Max MSP, OpenFrameworks, Pure Data, Processing, etc.) is able to receive these messages, allowing users to access the data on their programming platform of choice.
It would be great if openpose would support something similar, so the openpose script detects bodies and sends all available data over OSC to users can work with this data in any other program.

**Comment by gineshidalgo99** [comment]
We'll keep it in mind, but it's impossible for us to do it in the short run

**Comment by javl** [comment]
Thanks for considering it

**Comment by sergiolover** [comment]
yes thks for cnsidering it !!!

I've stopped coding a while back but still I know PHP, Py, Js,... 

would it be not too hard for me to dive in your code to find a way to extract as an array the XY coordinates of each color dot that represents a part of the body in whatever protocol ?

**Comment by javl** [comment]
In case anyone with better knowledge of c++ is following this issue:
I've set up Visual Studio 2015 to compile openpose and tried to add OSC using oscpack. If you download their zip file you'll find all of the files needed, together with a simple osc sender example (which should be all we need).
I managed to add the files to the project but get some errors I didn't manage to fix yet. `unresolved external symbol`, like:

    LNK2019	unresolved external symbol "public: void __cdecl UdpSocket::Connect(class IpEndpointName const &)" (?Connect@UdpSocket@@QEAAXAEBVIpEndpointName@@@Z)

I managed to overcome a similar error by removing all of the class's initialization options (with different types of arguments) except for the one I was using, but that doesn't work for this particular error.

Still, looking at the example file adding OSC support should be doable (and even easy for someone who knows C++ I guess). If anyone else thinks they'll be able to add the support, be my guest. Otherwise I'll keep messing around and let you know if I succeed.

OSCpack download: https://code.google.com/archive/p/oscpack/downloads
OSCpack website: http://www.rossbencina.com/code/oscpack

**Comment by L05** [comment]
Hi @javl and @b2renger, I am also trying to get oscpack to work with openpose. While I am able to read and write c++ code, I am not good with dependencies, CMAKE, etc. I've been unsuccessful integrating oscpack into the openpose project thus far, although I am reaching out to some people I hope can help. I agree it should be relatively straightforward for anyone who is knowledgeable in this realm. I will post back here with any findings.

**Comment by b2renger** [comment]
it looks like someone has been working on a bigger picture : https://twitter.com/c_valenzuelab/status/983340181121007617

:)

**Comment by n1ckfg** [comment]
Once there's an ofxOpenPose wrapper, adding OSC should be trivial.

**Comment by hollyhook** [comment]
there is a MaxMSP wrapper, sending OSC from Max would be another possibility.

**Comment by yurikleb** [comment]
Hey all I had similar errors, when implementing oscpack into [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace).
I have a work in progress version [here](https://github.com/yurikleb/OpenFace).

To make oscpack work you have to define some settings in the VisualStudio Linker, see screenshots [here](https://github.com/yurikleb/OpenFace/tree/master/OSC_Examples/VisualStudio%20OSC%20Settings).

**Comment by gineshidalgo99** [comment]
We will not be able to work on this, given our limited resources, so I will close this issue to focus in others. But if anyone is able to do a working system, please, feel free to report the GitHub link (I would add it to the doc) or do a PR! :)

**Comment by asus4** [comment]
Hey all, I've been testing Spout input and OSC output with OpenPose. seems useful for creative coders?

https://github.com/asus4/openpose/tree/osc-spout

ToutchDesigner -> Spout -> OpenPose -> OSC -> Unity
https://mobile.twitter.com/asus4/status/1082877391704338432
