### ISSUE TITLE
FPS dependent on window size when doing real-time visualization

### ISSUE THREAD

**Issue by megashigger** [CMU-Perceptual-Computing-Lab/openpose#434]
I'm running the visualization real-time with my webcam connected to a large 65" TV. I've noticed then when I max the window the size, the FPS is significantly lower and there's a very noticeable lag, both of which get better as I reduce the window size of the visualization. 

Is this expected? Anything I can do to speed up the visualization? 
Thanks.

**Comment by megashigger** [comment]
To clarify, the FPS goes down as well but that' the lesser problem. The bigger problem is the lag/delay.

**Comment by yuanyuanli85** [comment]
The rendering/display usually consumes GPU resources, while the FlexPose's CNN inference runs on GPU. I guess the competition on GPU resources causes the low fps.

**Comment by gineshidalgo99** [comment]
@yuanyuanli85  is right.
