### ISSUE TITLE
The CXX compiler identification is unknown CMake Error at CMakeLists.txt:10 (project):   No CMAKE_CXX_COMPILER could be found.

### ISSUE THREAD

**Issue by ashxpltz** [CMU-Perceptual-Computing-Lab/openpose#437]
I am getting this error while building openpose in ubuntu 16.04 LTS
with gcc and g++ version 5.4.1. How can i resolve this error??

This is the error ,  i am getting

**[ 12%] Performing configure step for **'openpose_caffe'**
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/oranz-dell/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeOutput.log".
See also "/home/oranz-dell/openpose/build/caffe/src/openpose_caffe-build/CMakeFiles/CMakeError.log".
CMakeFiles/openpose_caffe.dir/build.make:105: recipe for target 'caffe/src/openpose_caffe-stamp/openpose_caffe-configure' failed
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by gineshidalgo99** [comment]
Fill ALL your "Your System Configuration" section if you want us to take a look to it:

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...?
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**Release or Debug mode**? (by defualt: release):
**3-D Reconstruction module added**? (by default: no):
**GPU model** (`nvidia-smi` in Ubuntu):
**Caffe version**: Default from OpenPose, custom version, ...?
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
Compiler (`gcc --version` in Ubuntu):

**Comment by bikz05** [comment]
@arkceajin What version of cmake are you using? (Check using `cmake --version`).

**Comment by arkceajin** [comment]
My cmake version is `3.10.1`

**Comment by ashxpltz** [comment]
My cmake version is 3.5.1

**Comment by ashxpltz** [comment]
@gineshidalgo99 


Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
CUDA Version 8.0.61

cmake version 3.5.1
CUDA Version 8.0.61
cuDNN version release
3-D Reconstruction module added: No
GPU version :   product: 2nd Generation Core Processor Family Integrated Graphics Controller [8086:116]
                vendor: Intel Corporation [8086]
                version: 09
                configuration: driver=i915 latency=0

opencv : 2.4.9.1

**Comment by gineshidalgo99** [comment]
@ashxpltz  Could you try updating CMake to the latest version and checking again?

**Comment by bikz05** [comment]
Looks like CMake cannot find the compiler. Please have a look at [this](https://stackoverflow.com/questions/32801638/cmake-error-at-cmakelists-txt30-project-no-cmake-c-compiler-could-be-found) SO thread.
