### ISSUE TITLE
The video camera window keeps openning on video camera demo

### ISSUE THREAD

**Issue by georgecfwebtools** [CMU-Perceptual-Computing-Lab/openpose#438]
### Issue Summary
When running the Portable version (or openposedemo project in visual studio) on Windows 10 to use video camera, it works fine. But when I close the video camera window, it will open another one, and if I close it again, the window will open again. It seems no way to close the video camera window.

Is this a bug or feature? How could I fix it in Visual Studio project?

### Executed Command (if any)
bin\OpenPoseDemo.exe

### OpenPose Output (if any)
It will show a console window and a video camera window. There is no way to close the video camera window.

### Type of Issue
- Execution error

### Your System Configuration
Windows 10, GTX 1050, Visual Studio 2015

Thank you very much!

George

**Comment by gineshidalgo99** [comment]
That's how OpenCV works unfortunately (we  use their display).

You can close it with the Esc key (I should add this in the doc, thanks for pointing it out!)

**Comment by georgecfwebtools** [comment]
Thank you very much! That is exactly the information I am looking for.
