### ISSUE TITLE
How to install OpenPose using Visual studio Community 2017

### ISSUE THREAD

**Issue by MoneyChildren084** [CMU-Perceptual-Computing-Lab/openpose#439]
### Issue Summary
I'd like to use OpenPose,so I tried installing it referring to the following link.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#prerequisites

Then I had same trouble.so I got the following error:`Error LNK1181 cannot open input file '..\x64\Release\OpenPose.lib' OpenPoseDemo`

That's why I saw the following link:https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/211

According to the link above, it seems to edit the `.vcxproj`. However, I fixed the PATH of the `OpenPose .vcxproj` file but it did not go well. Specifically, please tell me which file and how to fix it.

(By the way,I tried using Visual studio Community 2015.
But I got the following error:`MSB8020 The build tools for v141 (Platform Toolset = 'v141') cannot be found.`

As far as I have examined, the cause of this error is because Visual studio Community 2015 components are not appropriate.
So I tried using Visual studio Community 2017.)

### Executed Command (if any)
I changed `CUDA_PATH_V8_0` in `OpenPose .vcxproj` to `CUDA_PATH_V9_1`.
(`CUDA_PATH_V9_1` has a path of CUDA9.1 set up)

### OpenPose Output (if any)
`Error LNK1181 cannot open input file '..\x64\Release\OpenPose.lib' OpenPoseDemo`

### Type of Issue
- Help wanted

### Your System Configuration
**Operating system** :Windows10 home
**Installation mode**: VS2017(Visual studio Community 2017)
**CUDA version**:CUDA9.1 
**cuDNN version**:5.1(maybe..)
**Release or Debug mode**?:Release
**3-D Reconstruction module added**? :no
**GPU model** :Default
**Caffe version**: Default from OpenPose, custom version, ...?:Default

**Comment by noxxomatik** [comment]
I use Visual Studio 2017 Community with CUDA 8. I followed this tutorial (steps 1 to 5): https://stackoverflow.com/questions/43745099/using-cuda-with-visual-studio-2017?answertab=active#tab-top
Also I had to change the platform toolset in the openpose project settings to **Visual Studio 2015 (v140)**.

Maybe the last step also helps with CUDA 9. I think the important part is to install the **VC++ 2015.3 v140 toolset**.

**Comment by MoneyChildren084** [comment]
Thanks for the reply! And Sorry for reply late.

I uninstalled VC2017 once and installed it again, but I can not build OpenPose.sln. . .

That's why, I'm going to give up using VC 2017 and use VC 2015. But "MSB8020 The build tools for v141 (Platform Toolset = 'v141') cannot be found" is not fixed. If you know how to solve this error, please let me know.

**Comment by khaledosama999** [comment]
im using vs 2017 when using cmake and choosing the configure options  vs 2014  wind64  it gives me 
this error
 CMake Error at CMakeLists.txt:11 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified
i followed the steps in the link of how to use cuda 8.0 with vs 2017 can anybody help ??
