### ISSUE TITLE
Get Pose from video camera on demand

### ISSUE THREAD

**Issue by georgecfwebtools** [CMU-Perceptual-Computing-Lab/openpose#441]
### Issue Summary
For my application, I converted the 1_user_asynchronous_output.cpp into a DLL and call the DLL from C# code. The dll has a function openPoseTutorialWrapper1, which is exactly current openPoseTutorialWrapper1 in 1_user_asynchronous_output.cpp. It worked ok however has one issue: when calling openPoseTutorialWrapper1, it keeps running and block all other code. The main code of the application does not start and just wait the openPoseTutorialWrapper1 to finish then main code will start. 

What I would from the DLL is two functions:
1) Turn on the video camera
2) Get pose information from video camera frame when being called from C#, after being called, it stops.

So the main application and the openPoseTutorialWrapper1 could interactive with each other: when application needs pose data, get from openPoseTutorialWrapper1, at other case, openPoseTutorialWrapper1 does not run.

Could some one give me some hint how to do this?

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc

### Your System Configuration
My environment is Windows 10 with VS 2015, GTX 1050.

Thank you very much!

George

**Comment by oakkas** [comment]
Hi George,
Did you achieve what you are working on?
 I am working on a similar application. 

Best,

Oguz
