### ISSUE TITLE
Compiling Openpose with Cuda9.0 and CuDNN 7 (Ubuntu): Known Archs

### ISSUE THREAD

**Issue by christian-lanius** [CMU-Perceptual-Computing-Lab/openpose#445]
With Cuda 9.0 compute_20 and compute_21 have become deprecated. Openpose compiles if the GPU is automatically detected but fails if the **GPU detection failed** and it is compiled for all architecture. The offending line is line 21 in [cmake/Cuda.cmake](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/cmake/Cuda.cmake#L21). 
`set(Caffe_known_gpu_archs "20 21(20) 30 35 50 52 60 61")`
to
`set(Caffe_known_gpu_archs "30 35 50 52 60 61 70")`

If it is changed to not include 20 and 21, Openpose compiles against Cuda 9.0. Because this change would lead to people with old GPUs who want to use Openpose with previous versions of Cuda being excluded, the true fix would be not this simple change but rather a check which compute architectures are supported by caffe/Cuda which is installed/used.

**Comment by gineshidalgo99** [comment]
@christian-lanius Thanks for the feed-back, we'll eventually fix it

**Comment by cameron2018** [comment]
are you compiling on ubuntu ?

**Comment by christian-lanius** [comment]
I am running a modified version of deepo (https://github.com/christian-lanius/deepo this one specifically: https://gist.github.com/christian-lanius/fd6846d44eeee63719858c2291c559ba) to build openpose and it's dependencies to run in a docker. It works with the fix implemented in openpose.py file, specifically line 159 in the linked Dockerfile. The base image is based on ubuntu (I think).
The error intuitively makes "sense" that it fails for this specific case. In most cases, the automatic GPU detection works fine and thus the problematic part of the code won't execute, but for the docker file, the GPU is not known during build time. The best course of action would be to check which CUDA version is used and map that to the respective supported compute architectures. I do not have enough knowledge in using CMAKE though to make such a change.

**Comment by alvaroga91** [comment]
What are the chances of this working in a TK1? (Ubuntu 14.04, 32bit, CUDA 6.5)

**Comment by christian-lanius** [comment]
The dockerfile? If you can run nvidia-docker  (https://github.com/NVIDIA/nvidia-docker), then the provided docker file should work. You can check out my fork of the deepo repo to add other deep learning framework if so desired: https://github.com/christian-lanius/deepo
Let me know if the dockerfile works for you or if there are any problems. I have no experience with the TK1. If CUDA 9 does not run on the board, there is little chance getting it to work without changing the base image of the dockerfile.

**Comment by davclark** [comment]
I wanted to thank @christian-lanius for pointing out and extending deepo. I have based my own work on this and based on the response of the deepo team to your pull request, it seems like the best way to collaborate with them is to simply build on top of one of their standard configurations. Here's [a Dockerfile](https://gist.github.com/davclark/7b5ccb3e494631841d934d827ffb2736) that builds on my own version of deepo, but you could easily just use your approach this way even with the standard deepo images.

**Comment by gineshidalgo99** [comment]
Check #996, but it has been finally fixed!
