### ISSUE TITLE
Some errors to run in Qtcreator

### ISSUE THREAD

**Issue by choyaFan** [CMU-Perceptual-Computing-Lab/openpose#446]
I want to use the latest OpenPose in Qtcreator(win10). 
First I make a build folder and then Open the CMakeLists.txt file in Qtcreator. I select the build folder as I created earlier.
The general message shows that "CMake Project was parsed successfully."  
But when I try to run the OpenPose, there is an error that "openpose_generated_renderPose.cu.obj.Release.cmake:219: error: Error generating openpose/build/src/openpose/CMakeFiles/openpose.dir/pose/./openpose_generated_renderPose.cu.obj"
How should I do to use OpenPose in Qtcreator?   thank you!

**Comment by gineshidalgo99** [comment]
it works right away in Ubuntu. It seems that it's not finding the CUDA files (*.cu files) in your system. Try checking CUDA is properly installed (following the installation steps that ask for a certain order between install CUDA and Visual Studio, as Qt uses Visual Studio in the background)

Please, let us know if you find the reason/make it work.

**Comment by choyaFan** [comment]
I can run the demo in VS2015 successful, then I want to develop a system with QT. So I try to run it in Qtcreator. But now I know that it's not a good idea. Sorry!
So I create a new QT project and want to use “2_user_synchronous.cpp” for my system.
But I cant make it work either. There are 348 errors occurred when I build it, here are some of them:
```
error: undefined reference to `op::Array<float>::Array(std::vector<int, std::allocator<int> > const&)'
error: undefined reference to `_imp___ZN2op12ConfigureLog20setPriorityThresholdENS_8PriorityE'
error: undefined reference to `_imp___ZN2op16flagsToScaleModeEi'
error: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
error: undefined reference to `op::Array<float>::getSize(int) const'
```
I think it is because I don't set CORE, GFLAGS, UTILITIES correctly, then I added the includepath and libs for it. But it seems doesnt work. 
here is my .pro file:
```
INCLUDEPATH += E:\environment\opencv\build\install\include
INCLUDEPATH += E:\environment\opencv\build\install\include\opencv
INCLUDEPATH += E:\environment\opencv\build\install\include\opencv2
INCLUDEPATH += C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
INCLUDEPATH += E:\myRepository\openpose-master\3rdparty\windows\caffe3rdparty\include
INCLUDEPATH += E:\myRepository\openpose-master\include

LIBS += -lboost_filesystem-vc140-mt-1_61 -lboost_filesystem-vc140-mt-gd-1_61 -lboost_system-vc140-mt-1_61 -lboost_system-vc140-mt-gd-1_61 \
        -lcaffehdf5 -lcaffehdf5_hl -lcaffezlib -lgflags -lglog -lleveldb \
        -llibprotobuf -llmdb -lsnappy -llibopencv_core310 -lopenpose
LIBS += -LE:\environment\opencv\build\install\x86\mingw\lib -llibopencv_core310.dll
```
Can you help me for this new problem? Thank you!

**Comment by LynnChan706** [comment]
There are some errors in your pro file. You can import it like this.

`win32:CONFIG(release, debug|release): LIBS += -L$$PWD/openpose/windows/x64/release/ -lOpenPose
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/openpose/windows/x64/debug/ -lOpenPose

INCLUDEPATH += $$PWD/openpose/include
DEPENDPATH += $$PWD/openpose/include

unix|win32: LIBS += -L$$PWD/openpose/3rdparty/windows/caffe3rdparty/lib/ -lgflags

INCLUDEPATH += $$PWD/openpose/3rdparty/windows/caffe3rdparty/include
DEPENDPATH += $$PWD/openpose/3rdparty/windows/caffe3rdparty/include

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/openpose/3rdparty/windows/opencv/x64/vc14/lib/ -lopencv_world310
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/openpose/3rdparty/windows/opencv/x64/vc14/lib/ -lopencv_world310d
else:unix: LIBS += -L$$PWD/openpose/3rdparty/windows/opencv/x64/vc14/lib/ -lopencv_world310

INCLUDEPATH += $$PWD/openpose/3rdparty/windows/opencv/include
DEPENDPATH += $$PWD/openpose/3rdparty/windows/opencv/include

unix|win32: LIBS += -L$$PWD/thrdlib/camera/ -lcamera

INCLUDEPATH += $$PWD/thrdlib/camera/include
DEPENDPATH += $$PWD/thrdlib/camera/include`

That's how I write it.

**Comment by gineshidalgo99** [comment]
THanks

**Comment by diennv** [comment]
I solved my problem by adding depended lib to build folder. 
Thanks.
