### ISSUE TITLE
Jetson Tx2 Jetpack 3.2 Installation

### ISSUE THREAD

**Issue by Rafcin** [CMU-Perceptual-Computing-Lab/openpose#448]
For some reason when trying to install Openpose on the TX2 3.2, openpose always runs into a similar error. Also caffe has trouble installing and has to be manually made each time. Could an update be pushed for 3.2? I have not found a single way in 2 months to make this work.

------------------------- Compiling OpenPose -------------------------
CXX src/openpose/gui/frameDisplayer.cpp
CXX src/openpose/gui/guiInfoAdder.cpp
CXX src/openpose/gui/gui3D.cpp
CXX src/openpose/gui/gui.cpp
CXX src/openpose/gui/defineTemplates.cpp
CXX src/openpose/hand/renderHand.cpp
CXX src/openpose/hand/handExtractorCaffe.cpp
src/openpose/hand/handExtractorCaffe.cpp:2:30: fatal error: caffe/blob.hpp: No such file or directory
compilation terminated.
Makefile:443: recipe for target '.build_release/src/openpose/hand/handExtractorCaffe.o' failed
make: *** [.build_release/src/openpose/hand/handExtractorCaffe.o] Error 1
make: *** Waiting for unfinished jobs....

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

**Comment by mepix** [comment]
In my case, I was able to get Openpose to compile just fine on the TX2 with Jetpack 3.2.  For 3.2, Nvidia deprecated OpenCV4tegra and replaced it with OpenCV 3.3.1.  The Openpose TX2 install scripts assume that you are using Jetpack <= 3.1 with OpenCV4Tegra.  I had to uncomment the line enabling OpenCV3 in both `Makefile.config.Ubuntu16_cuda8_JetsonTX2` in /3rdparty/caffe and /ubuntu.

Openpose built without a problem.

Note that the OpenCV 3.3.1 installed with Jetpack 3.2 is [not a complete install](https://devtalk.nvidia.com/default/topic/1029387/does-opencv-3-3-1-in-jetpack-3-2-support-cuda-gpu-/?offset=4), and your milage may vary!  I ended up removing the Nvidia install and building OpenCV 3.3.1 myself.

**Comment by gineshidalgo99** [comment]
Thanks for the info!

**Comment by Rafcin** [comment]
@mepix did you ever run into a Cuda issue for Cuda 9?


nvidia@panther:~/Desktop/OpenPose/openpose$ ./build/examples/openpose/openpose.bin 
Starting pose estimation demo.
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Desired webcam resolution 1280x720 could not being set. Final resolution: 1344x376 in src/openpose/producer/webcamReader.cpp:WebcamReader():31
Auto-detecting camera index... Detected and opened camera 1.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0307 06:06:38.368062 10163 cudnn_conv_layer.cpp:138] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*** Check failure stack trace: ***
    @       0x7f97790718  google::LogMessage::Fail()
    @       0x7f97792614  google::LogMessage::SendToLog()
    @       0x7f97790290  google::LogMessage::Flush()
    @       0x7f97792eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f97b2f010  caffe::CuDNNConvolutionLayer<>::Reshape()
    @       0x7f97aa8230  caffe::Net<>::Init()
    @       0x7f97aaa0a4  caffe::Net<>::Net()
    @       0x7f988fb3d8  op::NetCaffe::initializationOnThread()
    @       0x7f989a12b8  op::addCaffeNetOnThread()
    @       0x7f989a1c40  op::PoseExtractorCaffe::netInitializationOnThread()
    @       0x7f989a8cc0  op::PoseExtractor::initializationOnThread()
    @       0x7f989bfd04  op::SubThread<>::initializationOnThread()
    @       0x7f989c02d8  op::Thread<>::initializationOnThread()
    @       0x7f989c4738  op::Thread<>::threadFunction()
    @       0x7f986dd280  (unknown)
    @       0x7f96a84fc4  start_thread
Aborted (core dumped)

**Comment by tingxueronghua** [comment]
I think you just need to compile the file by yourself. Although I use Jetpack3.1, similar problems occurred.
