### ISSUE TITLE
Two Jetson Tx2 working in parallel

### ISSUE THREAD

**Issue by ClaudioMor** [CMU-Perceptual-Computing-Lab/openpose#449]
By chance, is it possible working in parallel with two Jetson Tx2?

In particular, my idea is testing Openpose benefiting from two tx2 working together to increase performance. At the moment Openpose works on only one Tx2 with low fps and low resolution.
Thank you!

**Comment by alvaroga91** [comment]
The easiest approach to do this would be to try to have one TX2 to capture the images and leave the other to the processing, but imho capturing images with a TX2 is an extreme overkill, although you can check the performance diference between capturing images in real-time with a webcam aand using a image folder to see if the FPS difference is worth the try or not.
