### ISSUE TITLE
Visualize only certain body parts

### ISSUE THREAD

**Issue by somacoder** [CMU-Perceptual-Computing-Lab/openpose#451]
System:
Windows
i7 4790K
16 GB RAM
GTX 1080

Are there any options to only visualize the skeleton of certain keypoint pairs on the demo/default executable (I am using Windows)? The --part_to_show option appears to only work with heatmaps and PAFs.

Thanks!

**Comment by gineshidalgo99** [comment]
No, there is not. OpenPose will display them all.

Your only option is creating your own demo based on examples/tutorial_wrapper
