### ISSUE TITLE
Compilation Error: libboost_filesystem-vc140-mt-gd-1_61.lib

### ISSUE THREAD

**Issue by mrutyu1987** [CMU-Perceptual-Computing-Lab/openpose#454]
Hi,

Trying to build the my own example app with openpose.lib on windows with VS2015. Included all required config paths. Configuration of the project is similar to openpose example projects. 

Get the compilation error for Boost: 
Error	LNK1104	cannot open file 'libboost_filesystem-vc140-mt-gd-1_61.lib'	of_openpose	D:\Dev\of_openpose\of_openpose\LINK	1

Regards,
Mrutyunjay

**Comment by gineshidalgo99** [comment]
Boost is not used in the latest OpenPose versions, so you should not try to include it.

**Comment by mrutyu1987** [comment]
If no boost included...openpose build fails with Caffe error. And I'm not including boost in the my app, still get the error. 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/shared_ptr.hpp': No such file or directory (compiling source file D:\Dev\openpose\src\openpose\core\maximumCaffe.cpp)	openpose	D:\Dev\openpose\3rdparty\windows\caffe\include\caffe\common.hpp	4	

```

**Comment by rlczddl** [comment]
still this problem, how do you fixed it?

**Comment by rlczddl** [comment]
Remove the caffe header file and only include the header file of the openpose interface.This way can solve the problem, but I don't know why.
