### ISSUE TITLE
A problem about CMakeLists.txt while installing

### ISSUE THREAD

**Issue by SeeleRan** [CMU-Perceptual-Computing-Lab/openpose#457]
openstack@ubuntu:~/openpose$ make
-- GCC detected, adding compile flags
CMake Warning at CMakeLists.txt:105 (find_package):
  By not providing "FindOpenCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCL" with any
  of the following names:

    OpenCLConfig.cmake
    opencl-config.cmake

  Add the installation prefix of "OpenCL" to CMAKE_PREFIX_PATH or set
  "OpenCL_DIR" to a directory containing one of the above files.  If "OpenCL"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
-- Caffe will be built from source now.
CMake Error at src/openpose/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/openstack/openpose/src/openpose/CMakeFiles

  does not contain a CMakeLists.txt file.

CMake Error at src/openpose/CMakeLists.txt:31 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  openpose_CMakeFiles

-- Adding Example openpose.bin
-- Adding Example 1_custom_post_processing.bin
-- Adding Example 1_extract_from_image.bin
-- Adding Example 2_extract_pose_or_heatmat_from_image.bin
-- Adding Example 1_openpose_read_and_display.bin
-- Adding Example 2_user_processing_function.bin
-- Adding Example 3_user_input_processing_and_output.bin
-- Adding Example 4_user_input_processing_output_and_datum.bin
-- Adding Example 1_user_asynchronous_output.bin
-- Adding Example 2_user_synchronous.bin
-- Adding Example 3_user_asynchronous.bin
-- Adding Example handFromJsonTest.bin
-- Adding Example resizeTest.bin
-- Download the models.
-- Downloading body (COCO) model...
-- Model already exists.
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/home/openstack/openpose/CMakeFiles/CMakeOutput.log".
make: *** [cmake_check_build_system] 

is that a CMakeLists.txt missing?

**Comment by gineshidalgo99** [comment]
Please, try the version I have just pushed. Let me know whether it works or not, ideally it should work now. Thanks

**Comment by SeeleRan** [comment]
openstack@ubuntu:~/openpose$ make
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
已经位于 'master'
您的分支与上游分支 'origin/master' 一致。
-- Caffe will be built from source now.
CMake Error at src/openpose/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/openstack/openpose/src/openpose/CMakeFiles

  does not contain a CMakeLists.txt file.


CMake Error at src/openpose/CMakeLists.txt:31 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  openpose_CMakeFiles


-- Adding Example openpose.bin
-- Adding Example 1_custom_post_processing.bin
-- Adding Example 1_extract_from_image.bin
-- Adding Example 2_extract_pose_or_heatmat_from_image.bin
-- Adding Example 1_openpose_read_and_display.bin
-- Adding Example 2_user_processing_function.bin
-- Adding Example 3_user_input_processing_and_output.bin
-- Adding Example 4_user_input_processing_output_and_datum.bin
-- Adding Example 1_user_asynchronous_output.bin
-- Adding Example 2_user_synchronous.bin
-- Adding Example 3_user_asynchronous.bin
-- Adding Example handFromJsonTest.bin
-- Adding Example resizeTest.bin
-- Download the models.
-- Downloading body (COCO) model...
-- Model already exists.
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/home/openstack/openpose/CMakeFiles/CMakeOutput.log".
make: *** [cmake_check_build_system] error 1

the warning about opencl disappeared but the Error about CMakeList.txt still exist.
really thanks for your help.

**Comment by gineshidalgo99** [comment]
It's finding a folder called `/home/openstack/openpose/src/openpose/CMakeFiles`, there should not be any folder with that name there. Could you manually delete it?

**Comment by SeeleRan** [comment]
i delete it and make it again, but it still error.
and i found the folder CMakeFiles which i deleted exists again.....
-- Caffe will be built from source now.
CMake Error at src/openpose/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/openstack/openpose/src/openpose/CMakeFiles

  does not contain a CMakeLists.txt file.


CMake Error at src/openpose/CMakeLists.txt:31 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  openpose_CMakeFiles

**Comment by gineshidalgo99** [comment]
That's a weird error. Please, fill all the info for a better answer:

### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

**Comment by SeeleRan** [comment]
Operating system (lsb_release -a in Ubuntu):  14.04
Installation mode: CMake
CUDA version (cat /usr/local/cuda/version.txt in most cases): CUDA Version 8.0.61
cuDNN version:  5.1.10
Release or Debug mode? (by defualt: release): release
3-D Reconstruction module added? (by default: no): no
GPU model (nvidia-smi in Ubuntu):   no NVIDIA-SMI, is that necessary？
Caffe version: Default from OpenPose
OpenCV version: 2.4.8
Compiler (gcc --version in Ubuntu):  gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

**Comment by gineshidalgo99** [comment]
An Nvidia graphics card is required to run OpenPose, that's why is failing.  #375

**Comment by SeeleRan** [comment]
OK,i got it....really thanks for your time~

**Comment by cnzJohn** [comment]
I also encountered this issue:
ubuntu@ip-10-55-2-44:~/openpose$ make
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_30
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
CMake Error at CMakeLists.txt:567 (add_subdirectory):
  The source directory

    /home/ubuntu/openpose/src

  does not contain a CMakeLists.txt file.


-- Adding Example openpose.bin
-- Adding Example 1_custom_post_processing.bin
-- Adding Example 1_extract_from_image.bin
-- Adding Example 2_extract_pose_or_heatmat_from_image.bin
-- Adding Example 1_openpose_read_and_display.bin
-- Adding Example 2_user_processing_function.bin
-- Adding Example 3_user_input_processing_and_output.bin
-- Adding Example 4_user_input_processing_output_and_datum.bin
-- Adding Example 1_user_asynchronous_output.bin
-- Adding Example 2_user_synchronous.bin
-- Adding Example 3_user_asynchronous.bin
-- Adding Example handFromJsonTest.bin
-- Adding Example resizeTest.bin
-- Download the models.
-- Downloading body (COCO) model...
-- Model already exists.
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/openpose/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/openpose/CMakeFiles/CMakeError.log".
Makefile:146: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

I am sure I pulled the latest version

**Comment by cnzJohn** [comment]
Below is my operating system
operating system (lsb_release -a in Ubuntu): Ubuntu 16.04
Installation mode: CMake
CUDA version (cat /usr/local/cuda-8.0/version.txt): CUDA Version 8.0.61
cuDNN version: 5.1.10
Release or Debug mode? (by defualt: release): release
3-D Reconstruction module added? (by default: no): no
GPU model (nvidia-smi in Ubuntu): NVIDIA-SMI 384.111                Driver Version: 384.111 
Caffe version: Default from OpenPose
OpenCV version: 2.4.8
Compiler (gcc --version in Ubuntu): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by cnzJohn** [comment]
Before I  manually edit cmake/Modules/FindCuDNN.cmake with the include and library paths:

find_path(CUDNN_INCLUDE cudnn.h
    PATHS ${CUDNN_ROOT} $ENV{CUDNN_ROOT} ${CUDA_TOOLKIT_INCLUDE} /usr/local/cuda/include
    DOC "Path to cuDNN include directory." )
find_library(CUDNN_LIBRARY NAMES ${CUDNN_LIB_NAME}
    PATHS ${CUDNN_ROOT} $ENV{CUDNN_ROOT} ${CUDNN_INCLUDE} ${__libpath_hist} ${__libpath_hist}/../lib /usr/local/cuda/lib64
    DOC "Path to cuDNN library.")
Didn't do other changes

**Comment by cnzJohn** [comment]
also when I run "make -j`nproc`" command under "build" directory.There is an exception:

 make: *** No targets specified and no makefile found.  Stop.
