### ISSUE TITLE
Could I process two videos meanwhile?

### ISSUE THREAD

**Issue by shuang0713** [CMU-Perceptual-Computing-Lab/openpose#461]
I want to use two cameras at the same time to display different views. Read two cameras or two videos and display them meanwhile.Could u tell me how can i realize this.
thank sir.

**Comment by shuang0713** [comment]
just like this but using  normal camera
![image](https://user-images.githubusercontent.com/34330515/36887068-5c3f618a-1e2a-11e8-9456-636868d0a2de.png)

**Comment by gineshidalgo99** [comment]
With video yes (assuming you have the intrinsic and extrinsic camera parameters set). Check doc/3d*.md
