### ISSUE TITLE
Using KeepTopNPeople crashes the application

### ISSUE THREAD

**Issue by matthiasferch** [CMU-Perceptual-Computing-Lab/openpose#462]
### Issue Summary

Application crashes after a seemingly random interval if the new KeepTopNPeople worker is added to pose estimation.

### OpenPose Output
```
Error:
Index out of bounds: 0 <= index && index < mVolume

Coming from:
  \Projects\openpose\src\openpose\core\array.cpp:op::Array<float>::commonAt():467
  \Projects\openpose\src\openpose\core\array.cpp:op::Array<float>::commonAt():473
   
  \Projects\openpose\src\openpose\core\keepTopNPeople.cpp:op::KeepTopNPeople::keepTopPeople():82
  \Projects\openpose\include\openpose\core\wKeepTopNPeople.hpp:op::WKeepTopNPeople<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum>>> >::work():76
```

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
**Operating system**: Windows 10
**Installation mode**: CMake, VS2015
**CUDA version**: 8.0
**Release or Debug mode**: both
**GPU model**: NVIDIA GeForce GTX 1050
**Caffe version**: Custom build
**OpenCV version**: OpenPose default

**Comment by gineshidalgo99** [comment]
Could you add the exact command and forward the video/image where it happened? So i can replicate and fix it. Thanks!

**Comment by matthiasferch** [comment]
Hi Gines, thank you for the quick response!
That's difficult, I'm afraid. I'm working on a custom application using a webcam stream as input. Is there another way I can help?

**Comment by gineshidalgo99** [comment]
You mean this is not based on OpenPoseDemo, but a custom code that you wrote, right?
If that's the case, which value are you introducing as `numberPeopleMax` in that function?

**Comment by matthiasferch** [comment]
numberPeopleMax is always 1.

**Comment by matthiasferch** [comment]
I can reliably reproduce the crash with this video:
https://videos.pexels.com/videos/people-walking-by-on-a-sidewalk-854100

**Comment by matthiasferch** [comment]
The crash seems to occur in wKeepTopNPeople.hpp at line 123:
```tDatum.faceKeypoints = spKeepTopNPeople->keepTopPeople(tDatum.faceKeypoints, tDatum.poseScores);```

I'm tracking only poses, not hands or faces.

**Comment by gineshidalgo99** [comment]
I have run that video with no problem in OpenPose. In addition, there is no line 123 in `wKeepTopNPeople`, I guess you are referring to line 59. If you are implementing some custom code, I think you might be changing something else, as I am not being able to replicate this error with the software. If you are not detecting face or hands, then both of those arrays should be completely empty, therefore that line cannot crash. Make sure both tDatum.faceKeypoints.empty() and tDatum.handKeypoints.empty() are true.
