### ISSUE TITLE
Broken link in doc page

### ISSUE THREAD

**Issue by siarez** [CMU-Perceptual-Computing-Lab/openpose#464]
### Issue Summary
The links on bullet point no.1 (“Demo” and  “OpenPose Wrapper”) in [this page](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/library_introduction.md) are broken.

### Type of Issue
- Documentation error

**Comment by gineshidalgo99** [comment]
Thanks! Updated.
