### ISSUE TITLE
Newly implemented openpose.

### ISSUE THREAD

**Issue by youansheng** [CMU-Perceptual-Computing-Lab/openpose#468]
https://github.com/youansheng/pytorch-cv/tree/master/methods/pose

**Comment by scnu-Yhz** [comment]
Hello,I am a new hand of the using the github open source code,I am so confused with using the open source code to build a .exe project.I don't know how what is need to use and how to do if there is a little different with the readme.doc and installation.doc!Could you tell me a study way to the github installation?Thank you so much!

**Comment by scnu-Yhz** [comment]
Hello,I am a new hand of the using the github open source code,I am so confused with using the open source code to build a .exe project.I don't know how what is need to use and how to do when there is a little different  in my conputer with the readme.doc and installation.doc!Could you tell me a study way to the github installation?Thank you so much!

**Comment by gineshidalgo99** [comment]
Thanks for the info!

**Comment by gineshidalgo99** [comment]
(Repo disappeared, closing this)
