### ISSUE TITLE
failed to compile openpose with Vs2017?

### ISSUE THREAD

**Issue by yuhangli1991** [CMU-Perceptual-Computing-Lab/openpose#469]
**# output:**
>CMake Error at openpose_generated_maximumBase.cu.obj.Debug.cmake:219 (message):
1>  Error generating
1>  F:/openpose/tt/src/openpose/CMakeFiles/openpose.dir/core/Debug/openpose_generated_maximumBase.cu.obj
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”。

Your System Configuration
Operating system: Windows 10
Installation mode: CMake, VS2017
CUDA version: 8.0
Release or Debug mode: Debug 
GPU model: NVIDIA GeForce GTX 1050Ti
Caffe version: Windows Realease
OpenCV version: OpenPose default

**Comment by gineshidalgo99** [comment]
That's a problem with CUDA. Check doc/installation.md. CUDA with VS2017 is somehow tricky, we recommend VS 2015 (again, check the doc for details)
