### ISSUE TITLE
The question with dataset 

### ISSUE THREAD

**Issue by ufohuang98** [CMU-Perceptual-Computing-Lab/openpose#47]
Hi, 
I'm new in deep learning (about 3 months). and I want to train a model that can recognize people(or head) like openpose that  can work almost everywhere.
I know that the dataset is very important.
Could please tell me how many images and which dataset has openspoe used to train?
※I read the paper. Does it only used mpii and MS coco +image augmentation?or other datasets?
Could your please give me some advices?

**Comment by gineshidalgo99** [comment]
Check https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation for training questions. We are using their model.
