### ISSUE TITLE
VideoCapture (IP camera/video) could not be opened for path: 'examples\media\video.avi'

### ISSUE THREAD

**Issue by techjjun** [CMU-Perceptual-Computing-Lab/openpose#470]
### Issue Summary

VideoCapture (IP camera/video) could not be opened for path: 'examples\media\video.avi'

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

C:\Users\admin\openpose>build\x64\Release\OpenPoseDemo.exe --video examples\media\video.avi

### OpenPose Output (if any)
C:\Users\admin\openpose>build\x64\Release\OpenPoseDemo.exe --video examples\media\video.avi
Starting pose estimation demo.

Error:
VideoCapture (IP camera/video) could not be opened for path: 'examples\media\video.avi'. If it is a video path, is the path correct?

Coming from:
- C:\Users\admin\openpose\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():37
- C:\Users\admin\openpose\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():41
- C:\Users\admin\openpose\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():201

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error

I checked there is a video.avi in C:\Users\admin\openpose\examples\media   but error computed

how can i fix it..?

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Window 10
**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...? CMake, VS2015
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 6
**CMake version** (`cmake --version` in Ubuntu):
**Release or Debug mode**? (by defualt: release): release
**3-D Reconstruction module added**? (by default: no): no
**GPU model** (`nvidia-smi` in Ubuntu):  gGTX 1060 3G
**Caffe version**: Default from OpenPose, custom version, ...? Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...? OpenPose default
Compiler (`gcc --version` in Ubuntu):

**Comment by gineshidalgo99** [comment]
Try downloading the portable executable from the releases section. Does it occur there?

**Comment by techjjun** [comment]
It works at portable demo releases section.  though

**Comment by yuhangli1991** [comment]
i need an openposed.lib

**Comment by gineshidalgo99** [comment]
I'd say the DLLs are not in the executable folder and you are trying to run the bin from outside Visual Studio without copying all the DLL files inside the executable folder.

**Comment by marApol** [comment]
I have all DLLs in the executable folder. I managed to build it a long time ago on a different computer and I copied all DLLs to exactly the same folder in the same place, but it doesn't work :/

**Comment by gineshidalgo99** [comment]
@yuhangli1991 The release/portable version includes the *.lib file.

**Comment by gineshidalgo99** [comment]
@marApol Does image/webcam/video work? Which one works? which one doesnt?

**Comment by marApol** [comment]
@gineshidalgo99 Image and webcam work. Only video doesn't
