### ISSUE TITLE
How can i use openpose with kinect v2 in ubuntu?

### ISSUE THREAD

**Issue by ilovebob** [CMU-Perceptual-Computing-Lab/openpose#471]
How can i use openpose with kinect v2 in ubuntu?

**Comment by Qayou** [comment]
I personally use the Kinect v2 through [ROS](http://www.ros.org/).

With that I used a bridge publishing the images and then another module that creates a virtual camera in ubuntu streaming those images.

* Kinect 2 driver: [libfreenect2](https://github.com/OpenKinect/libfreenect2)
* ROS Kinect 2 bridge: [iai_kinect2](https://github.com/code-iai/iai_kinect2)
* ROS virtual camera: [ros_virtual_cam](https://github.com/jgoppert/ros-virtual-cam)

There must be an easier and more lightweight way but as I use ROS in my project, this is what I do!

**Comment by ilovebob** [comment]
@Qayou I follow the steps of iai_kinect2 Kinect2 Calibration(https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration#calibrating-the-kinect-one), but I still didn't get right images. Can I get your contact information? I have some questions want to ask you..
Thanks a lot.
My email is zhutun@outlook.com

**Comment by Harsharma2308** [comment]
Hi can anyone comment on this please? If someone has been able to successfully do this.
