### ISSUE TITLE
Seeking advice on Single Person detection 

### ISSUE THREAD

**Issue by heng2j** [CMU-Perceptual-Computing-Lab/openpose#474]
Hi team,

Is there a way to tune the code or the parameters to just detect 1 person? Currently our project just need to ignore any person appear on the background.

Thank you,
Heng

**Comment by gineshidalgo99** [comment]
doc/demo_overview.md --> number_people_max 1 (or something like that)

Best

**Comment by heng2j** [comment]
Hi @gineshidalgo99 , 

Thank you for your reply.

However, when I tired to run this test run:

./build/examples/openpose/openpose.bin --image_dir /data/OpenPose/input/RGB/reserve  --write_images ../data/output/images/OpenPose_Results/CSL/reserve --no_display  --hand --disable_blending --alpha_pose 1 **--number_people_max 1** --resolution 360x640  

I received the following error message
**ERROR: unknown command line flag 'number_people_max'**

**Comment by gineshidalgo99** [comment]
Update OpenPose, it's a new flag (<1 month)

**Comment by MritulaC** [comment]
Hi where can I find this openpose.bin. How to start using it? 
Thanks_
