### ISSUE TITLE
Where can I find openpose.bin file?- Unable to start

### ISSUE THREAD

**Issue by MritulaC** [CMU-Perceptual-Computing-Lab/openpose#479]
I want to" compile the library and use the demo ./build/examples/openpose/openpose.bin."

Can you help me how to start for this. I am using Matlab. I have Caffe installed and working over Windows 10.  I couldn't find openpose.bin file from the latest binaries I downloaded. 

Kindly direct me how to proceed.

Thanks

**Comment by alvaroga91** [comment]
You need to compile the project with a previously configured Makefile done by CMake, making sure you select to generate the examples. If you have already Caffe compiled and installed, make sure to select to not build Caffe, and the path of its include/ and libs/ 

More info: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md (Read carefully, and your specific scenario is 2, at the end of the page)

**Comment by MritulaC** [comment]
Hi,
 Thanks for your reply.
 Where can I find bin\OpenPoseDemo.exe? I dont find bin folder under openpose.

Thanks,

**Comment by Ayehsu** [comment]
I have also this problem." I don't find *.bin files under /examples/openpose folder.
I found only CMakeFiles folder.

**Comment by AkashNagaraj** [comment]
Hey did you find a solution?

**Comment by amrabozeid** [comment]
Ubuntu and Mac file : openpose.bin
Windows file : openpose.exe
you know .. there is no problem
