### ISSUE TITLE
can't find the build_win.cmd

### ISSUE THREAD

**Issue by 408550969** [CMU-Perceptual-Computing-Lab/openpose#48]
### Issue summary
I have downloaded the https://github.com/CMU-Perceptual-Computing-Lab/openpose. but I can't find the build_win.cmd in caffe.should I download caffe-windows from the official website and cover it?And can I compile it with vs2013?

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** Windows10
**CUDA version** 5.1
**cuDNN version**:8.0
**GPU model** (`nvidia-smi`):
**Caffe version**: Default
**OpenCV version**: Default
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
Check the updated https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md

And we only support VS 2015. You can try VS 2013 and let us know the result, but we will not be able to help for any errors there since we only have VS 2015.
