### ISSUE TITLE
Ubuntu MATE 16.04.4 - Cmake Configure error

### ISSUE THREAD

**Issue by tolgasaglik** [CMU-Perceptual-Computing-Lab/openpose#480]
Hello,
When I try to configure Openpose with CMake I get below error. I followed every step of tutorial. Your help is appreciated. 

tolga@tolga-Ubuntu:~/programs/openpose$ cmake -C ~/programs/openpose/
loading initial cache file /home/tolga/programs/openpose/
CMake Error: Error processing file: /home/tolga/programs/openpose/
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
-- Download the models.
-- Downloading body (COCO) model...
-- Model already exists.
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/home/tolga/programs/openpose/CMakeFiles/CMakeOutput.log".
See also "/home/tolga/programs/openpose/CMakeFiles/CMakeError.log".

----------------------------------------------------------------
CMakeError.log:

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/tolga/programs/openpose/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_8edca/fast"
/usr/bin/make -f CMakeFiles/cmTC_8edca.dir/build.make CMakeFiles/cmTC_8edca.dir/build
make[1]: Entering directory '/home/tolga/programs/openpose/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8edca.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_8edca.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_8edca
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8edca.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_8edca.dir/CheckFunctionExists.c.o  -o cmTC_8edca -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_8edca.dir/build.make:97: recipe for target 'cmTC_8edca' failed
make[1]: *** [cmTC_8edca] Error 1
make[1]: Leaving directory '/home/tolga/programs/openpose/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_8edca/fast' failed
make: *** [cmTC_8edca/fast] Error 2

Thanks,

**Comment by alvaroga91** [comment]
Are you compiling Caffe separately or all together? 

I remember having this error and solving it by compiling Caffe first, and then in CMake choose not to build it (and select its lib/ and 

My best recomendation is to delete the openpose/build/ folder and start the CMake process again once Caffe is built. You may find more info in the Scenario 2 at the end of the page:  https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md

Although with the GUI is much more straightforward, no need to mess up with commands flags :)

**Comment by tolgasaglik** [comment]
I tried both GUI and the command line actually. From GUI I get attached return. It looks like it cannot find CAFFE which was supposed to be downloaded already.
![screenshot at 2018-03-11 09 37 02](https://user-images.githubusercontent.com/32940055/37251403-cd8177e8-250f-11e8-8ab3-c24ad75c6536.png)

**Comment by alvaroga91** [comment]
If you are compiling Caffe separately (This is, if you not cloning the repo itself from BLVC but using the 3rdparty folder), just cp the Makefile.config.example to Makefile.config, make any required changes to that, and then launch "make all -jX" (I hope you are familiar with the -jX meaning) in the 3rdparty/caffe folder.

That will build Caffe.

After that, in the CMake, you have to select NOT to build Caffe (untick BUILD_CAFFE) and then select the path of the include dir (openpose/3rdparty/caffe/include) in Caffe_INCLUDE_DIRS and the path of the newly generated libcaffe.so (openpose/3rdparty/caffe/build/lib/libcaffe.so). Configure and generate. Now you can build Openpose.

Please take into account that these are 2 different builds: First Caffe, and then use that to build OpenPose.

**Comment by tolgasaglik** [comment]
> If you are using the Caffe folder in the OpenPose project (This is, if you are not cloning the repo itself from BLVC but using the 3rdparty folder), just cp the Makefile.config.example to Makefile.config, make any required changes to that, and then launch "make all -jX" (I hope you are familiar with the -jX meaning) in the 3rdparty/caffe folder.

Where do I copy the Makefile.config.example? Am I not supposed to run make -j8 inside the /build folder? What changes to Makefile do you mean with "required"?

Thank you,

**Comment by alvaroga91** [comment]
- To the same 3rdparty folder: $ cp Makefile.config.example Makefile.config 
- Yes, but that's why I'm making empashis that you are making 2 builds. The first one is in the /3rdparty in order to build Caffe. Then, once Caffe is built, you can build OpenPose.
- To Makefile.config, not Makefile. For instance, deleting some CUDA_ARCH for compatibility. I don't remember all the flags and env variables, but the file is pretty self explanatory (I just began working with OpenPose this week). Hopefully, you may not have to change anuthing

**Comment by anselanza** [comment]
I believe the confusion is caused by the documentation failing to mention that Caffe needs to be fetched as a submodule **before**  attempting to configure and build.

The installation documentation should definitely mention that, after cloning, the user should `init` and then `update` the gitmodules. For example:

```
cd openpose
git submodule init
git submodule update --remote
```

Following these instructions means that none of the proposed "fixes" above (coping make files and compiling Caffe separately, for example) are necessary. The installation instructions can be followed as is.

**Comment by gineshidalgo99** [comment]
@anselanza CMake automatically runs these commands, so there is no need to manually do it.

**Comment by anselanza** [comment]
@gineshidalgo99 Hmm curious. I got the errors and only running the git submodule commands made everything work properly.

**Comment by gineshidalgo99** [comment]
I am not sure the reason of this error, unless your Caffe folder were not empty when you downloaded OpenPose (in that case CMake gives you an error message), it shouldn't do that.

**Comment by anselanza** [comment]
Indeed it was not empty. But I did not create it. Are the instructions perhaps incomplete?
