### ISSUE TITLE
Retrieve FPS in X-less system.

### ISSUE THREAD

**Issue by alvaroga91** [CMU-Perceptual-Computing-Lab/openpose#481]
Hi again,

just a simple question. I've been making some tests in my 16.04 machine with --display 0, and I could retrieve some images with the --write_images (as expected).

However I'm interested in obtaining the FPS the system is running, since I'll be running OpenPose without any display in my real scenario. Any approach?

Sorry if it seems dumb, I've been looking in the [flags readme](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md) and I couldn't find anything.

**Comment by gineshidalgo99** [comment]
@alvaroga91 Sorry for the delay. I added it to the doc:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md#estimating-fps-without-display
