### ISSUE TITLE
How to process the image more faster?  

### ISSUE THREAD

**Issue by yuhangli1991** [CMU-Perceptual-Computing-Lab/openpose#484]
modify the parameter？

**Comment by Qayou** [comment]
We need way way more information about what you are doing...

What are you specs (GPU, CPU, ...)?
What frame rate do you achieve?
What parameters do you use now?

**Comment by Zhangliuwei** [comment]
@Qayou i am using 1_extract_from_image with default parameters   CPU I7  NVIDIA GTX1050TI win10 vs2015

**Comment by soulslicer** [comment]
You can reduce the net resolution parameter

**Comment by gineshidalgo99** [comment]
Highly duplicated
