### ISSUE TITLE
Ordering of keypoints in output

### ISSUE THREAD

**Issue by sagarkukreja** [CMU-Perceptual-Computing-Lab/openpose#488]
### Issue Summary
I would like to know if the keypoint ordering of co-ordinates in the pose_keypoints_2d array of output JSON file is same as the body part mapping order of any model. If not , how can I know that which co-ordinates correspond to which body part ?

### Type of Issue
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
doc/output.md

**Comment by sagarkukreja** [comment]
I went through the output.md file already but it isn't clear to me if output JSON files follows the same order. It would e great if you could clarify it.

Thanks

**Comment by gineshidalgo99** [comment]
Yes it's exactly the same order

**Comment by sagarkukreja** [comment]
Thank you so much Gines!!
