### ISSUE TITLE
Cuda check failed (9 vs. 0): invalid configuration argument

### ISSUE THREAD

**Issue by yangpc615** [CMU-Perceptual-Computing-Lab/openpose#489]
### Issue Summary
Coming from:
- src/openpose/core/netCaffe.cpp:forwardPass():86
- src/openpose/core/netCaffe.cpp:forwardPass():90
- src/openpose/pose/poseExtractorCaffe.cpp:forwardPass():123
- ./include/openpose/pose/wPoseExtractor.hpp:work():80
- ./include/openpose/thread/subThread.hpp:workTWorkers():138
- ./include/openpose/thread/subThreadQueueInOut.hpp:work():87
- ./include/openpose/thread/thread.hpp:threadFunction():206

### Executed Command (if any)
./build/examples/openpose/openpose.bin --image_dir examples/media/ --write_images output/  --no_display

### Type of Issue
- Execution error

### Your System Configuration
14.04.1-Ubuntu
manual Makefile installation, ... (Ubuntu);
CUDA-8.0
cuDNN 5.1.10
GPU: GeForce GTX TIT... 12G
caffe： the same as your
OpenCV: 3.3.1
gcc: g++ (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1

**Comment by gineshidalgo99** [comment]
Unfortunately, that seems to be an error coming from CUDA, not from OpenPose itself, so I can't help you debugging it much. I'd recommend you to google for that CUDA error, I found several threads talking about that error:
https://www.google.com/search?q=9+vs.+0)%3A+invalid+configuration+argument&rlz=1C1PRFE_enUS669US669&oq=9+vs.+0)%3A+invalid+configuration+argument&aqs=chrome..69i57j69i61l2.263j0j7&sourceid=chrome&ie=UTF-8

Sorry for not be able to provide more help :( Please let us know if you could fix it!

**Comment by yangpc615** [comment]
That's OK， I will try to fix it again.

**Comment by yangpc615** [comment]
Hello, it can be installed successfully  by cmake. In addition, to my case, I have to add the three libraries, blas, gfortran and pthread to make it pass compilation. But it's ok, and by the way, your work is wonderful.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back
