### ISSUE TITLE
Execution error - Segment error( core dump)

### ISSUE THREAD

**Issue by simon199250** [CMU-Perceptual-Computing-Lab/openpose#49]
### Executed command (if any)
./build/examples/openpose/openpose.bin --video examples/media/1.avi --logging_level 0
or ./build/examples/openpose/openpose.bin --camera 0 --logging_level 0

### OpenPose output (if any)
error :dl@dl:~/openpose-master$ ./build/examples/openpose/openpose.bin --camera 0 --logging_level 0
Starting pose estimation demo.
examples/openpose/openpose.cpp:gflagsToOpParameters():203
examples/openpose/openpose.cpp:gflagsToProducer():171
examples/openpose/openpose.cpp:gflagsToProducerType():151
examples/openpose/openpose.cpp:gflagToPoseModel():113
examples/openpose/openpose.cpp:gflagToScaleMode():129
Configuring OpenPose wrapper. In examples/openpose/openpose.cpp:opRealTimePoseDemo():249
./include/openpose/wrapper/wrapper.hpp:configure():422
./include/openpose/wrapper/wrapper.hpp:configure():559
./include/openpose/wrapper/wrapper.hpp:configure():722
Starting thread(s)
./include/openpose/wrapper/wrapper.hpp:configureThreadManager():1030
./include/openpose/thread/threadManager.hpp:exec():166
./include/openpose/thread/queueBase.hpp:addPusher():364
./include/openpose/thread/queueBase.hpp:addPusher():364
./include/openpose/thread/queueBase.hpp:addPusher():364
./include/openpose/thread/threadManager.hpp:exec():171
./include/openpose/thread/thread.hpp:startInThread():141
./include/openpose/thread/thread.hpp:startInThread():141
./include/openpose/thread/thread.hpp:startInThread():141
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():188
./include/openpose/thread/thread.hpp:threadFunction():185
./include/openpose/thread/thread.hpp:threadFunction():188
./include/openpose/thread/thread.hpp:threadFunction():185
Starting initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():42
init done 
./include/openpose/thread/thread.hpp:threadFunction():188
Segment error( core dump)
dl@dl:~/openpose-master$ 
### Your system configuration
**Operating system: Ubuntu14.04
**CUDA version:7.5
**cuDNN version:5.1
**GPU model** (`nvidia-smi`):titan x
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):gcc 4.8.5

**Comment by gineshidalgo99** [comment]
I think this is the same issue as #4 (OpenCV issue), even if the warning it outputs you is different.

Please try https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/4#issuecomment-299192764

Let me know whether it works or not. Thanks

**Comment by ahuirecome** [comment]
I solved this problem with the method from #4:
1. Completely uninstalling your current OpenCV version.
2. Installing the default OpenCV from the Ubuntu repository: apt-get install libopencv-dev
