### ISSUE TITLE
using cmake with vs 2017

### ISSUE THREAD

**Issue by khaledosama999** [CMU-Perceptual-Computing-Lab/openpose#490]
windows : 10 
CUDA : V 8.0
visual studio : 2017
im using cmake to build the .sln files  i followed the steps to use cuda 8.0 with vs 2017(i installed the vs 2015 toolset)  , when trying to use the vs 2015 toolset with cmake it gives me this error : 

CMake Error at CMakeLists.txt:11 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified

**Comment by scnu-Yhz** [comment]
Hello,I am a new hand of the using the github open source code,I am so confused that where the cuda is necessary for the openpose installation by using the cmakelist.txt.

**Comment by scnu-Yhz** [comment]
Hello,I am a new hand of the using the github open source code,I am so confused that whether the cuda is necessary for the openpose installation by using the cmakelist.txt.
