### ISSUE TITLE
UE4 Blueprint support

### ISSUE THREAD

**Issue by Phrogz** [CMU-Perceptual-Computing-Lab/openpose#492]
Please provide support for Unreal engine, preferably via Blueprints, similar to the [Kinect 4 Unreal](https://www.opaque.media/kinect-4-unreal/) plugin.

**Comment by Phrogz** [comment]
Closing a feature request because it hasn’t been commented on, but has emoji upvotes? Bad bot. (Bad human who coded up this policy.)

**Comment by gineshidalgo99** [comment]
I skipped this request (too many emails about issues every day, most of them from people that doesn't read the installation instructions, sorry for the others that I skip!).

I'll keep it open as request, right now we are actually working on a Unity wrapper, but timelines are still far from being finished for release.

**Comment by andreykhorkov** [comment]
Do you have a git branch for openPoseUnity? So we could contribute and make pull requests. Thanks

**Comment by gineshidalgo99** [comment]
@andreykhorkov 
Sorry, yes, it was released a few months back:
https://github.com/CMU-Perceptual-Computing-Lab/openpose_unity_plugin

I will close this, as I do not believe we will focus on UE as well. But feel free to add a PR if anyone does it!

**Comment by vladyslavkhakov** [comment]
Hi @gineshidalgo99 
Is team working on UE5 Openpose plugin?
