### ISSUE TITLE
Cmake openpose but build directory not found

### ISSUE THREAD

**Issue by cnzJohn** [CMU-Perceptual-Computing-Lab/openpose#493]
Hi, 
    I Cmake the openpose, but after the cmake, there is no build directory. My ubuntu version is 14.
Cmake command: 
~/openpose$ cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ./

**Below is the running logs:**
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_30
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
-- Download the models.
-- Downloading body (COCO) model...
-- Model already exists.
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/openpose
but I didn't find the build directory under openpose folder.

**Comment by christian-lanius** [comment]
You have to create the build folder. In your /home/ubuntu/openpose folder run:
`mkdir build
cd build
cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ..
make`

**Comment by SreehariRamMohan** [comment]
@christian-lanius Hey I am trying to install openpose on macos. 

I have done: 

`mkdir build
cd build
cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ..`

But when I try to `make` I get the following errors:

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
45 warnings and 20 errors generated.
make[5]: *** [src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o] Error 1
make[4]: *** [src/caffe/CMakeFiles/caffeproto.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-build] Error 2
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
make: *** [all] Error 2
`
