### ISSUE TITLE
Error Installation with VS 2015 Community

### ISSUE THREAD

**Issue by albertchristianto** [CMU-Perceptual-Computing-Lab/openpose#494]
Hi,
I tried to follow your installation procedure in Windows. 
Windows
In order to build the project, open the Visual Studio solution (Windows), called build/OpenPose.sln. Then, set the configuration from Debug to Release and press the green triangle icon (alternatively press F5).
There is an error in building project. Here is the debug log
'OpenPoseDemo.exe' (Win32): Loaded 'H:\HumanPose\openpose-master\build\x64\Release\OpenPoseDemo.exe'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\build\x64\Release\openpose.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\M10502803\sahasuman-bmvc2016_code-061eae975868\external\caffe\matlab\caffe_faster_rcnn\gflags.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\opencv_world310.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\caffe.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\glog.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\boost_system-vc140-mt-1_61.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\boost_thread-vc140-mt-1_61.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\caffehdf5_hl.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\curand64_80.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cublas64_80.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\libopenblas.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\cudnn64_5.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Users\ee401_2\Miniconda2\python27.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\boost_python-vc140-mt-1_61.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\caffehdf5.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\boost_filesystem-vc140-mt-1_61.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\opencv_imgcodecs310.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\opencv_imgproc310.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcp120.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcr120.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\opencv_core310.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.16299.309_none_8875ce284abe80d8\comctl32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvfw32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\avifil32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\avicap32.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\concrt140.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\boost_chrono-vc140-mt-1_61.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\libgcc_s_seh-1.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\libgfortran-3.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Unloaded 'D:\Dependencies\caffe-windows-ms\Build\x64\Release\libgfortran-3.dll'
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcr90.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'E:9\HumanPose\openpose-master\3rdparty\windows\caffe\bin\caffezlib1.dll'. Module was built without symbols.
Exception thrown at 0x00007FFCB3902B10 (ntdll.dll) in OpenPoseDemo.exe: 0xC0000139: Entry Point Not Found.
Exception thrown at 0x00007FFCB3902B10 (ntdll.dll) in OpenPoseDemo.exe: 0xC0000139: Entry Point Not Found.
Exception thrown at 0x00007FFCB3902B10 (ntdll.dll) in OpenPoseDemo.exe: 0xC0000139: Entry Point Not Found.
The thread 0x13fc has exited with code -1073741511 (0xc0000139).
The thread 0x1454 has exited with code -1073741511 (0xc0000139).
The thread 0x17d0 has exited with code -1073741511 (0xc0000139).
The program '[9824] OpenPoseDemo.exe' has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.
I use VS 2015 Community. I know that VS 2015 Community has not been tested, what should I do to fix the bug ? 
Thank you very much. I really appreciate your answer.

**Comment by Achyuth1234** [comment]
I am also getting the same error. Can anyone please help?

**Comment by MAli-Haider** [comment]
Try go to Tools->Options->Debugging->Symbols and select checkbox "Microsoft Symbol Servers", Visual Studio will download PDBs automatically.

PDB is a debug information file used by Visual Studio. These are system DLLs, which you don't have debug symbols for.[...]

**Comment by salihkaragoz** [comment]
the same problem : (

**Comment by FPT-ThaiTuan** [comment]
I also had the same problem. Who can help me solve it?

**Comment by FPT-ThaiTuan** [comment]
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\build\x64\Debug\OpenPoseDemo.exe'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\build\x64\Debug\openposed.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\gflagsd.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\opencv\x64\vc15\bin\opencv_world450d.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\glogd.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\caffe-d.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\comctl32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\concrt140d.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\boost_thread-vc142-mt-gd-x64-1_74.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\caffehdf5_hl_D.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\cudart64_110.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\curand64_10.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\cublas64_11.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\libopenblas.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'F:\Models\openpose-master\3rdparty\windows\caffe\bin\caffehdf5_D.dll'. Cannot find or open the PDB file.
The thread 0x1c94 has exited with code -1073741515 (0xc0000135).
The thread 0x704 has exited with code -1073741515 (0xc0000135).
The program '[5344] OpenPoseDemo.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.
