### ISSUE TITLE
everything is fine but the result video NOT marked

### ISSUE THREAD

**Issue by shinerio** [CMU-Perceptual-Computing-Lab/openpose#498]
when i use openpoe-v1.2.1 in Ubuntu16.04 , everything is fine and compile successfully with caffe and opencv3.4.1.
i try to run the demo,but output video is not marked ,just the same as input video.

the following sentence is my instruction on Ubuntu:

`./build/examples/openpose/openpose.bin —video examples/media/video.avi —write_video examples/out/result.avi —no_display`

next few sentences are the output results in commond line:

```
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
Real-time pose estimation demo successfully finished. Total time: 34.859467 seconds.
```

**Comment by gineshidalgo99** [comment]
Can you check without `no_display`? Is the visualized video OK?

**Comment by shinerio** [comment]
The openpose project is running on ubuntu environment without user interface,when i installed nvidia driver in the Ubuntu server ,my computer became “infinity log in loop”,so we can just save the result video but not show it .I have tried to run without the flag and i got an error “Gtk-WARNING **: cannot open display”

**Comment by shinerio** [comment]
Hello,i fixed the nvidia driver bug and now i try to run without any other flags,below is my instruction

`./build/examples/openpose/openpose.bin —video examples/media/video.avi`

here is the output

```
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
Real-time pose estimation demo successfully finished. Total time: 34.859467 seconds.
```
but  the visualized video still not marked
![image](https://user-images.githubusercontent.com/22368855/37751984-7b6e1bb8-2dd0-11e8-925f-649e16a36281.png)

**Comment by shinerio** [comment]
Thank you , I hava solved the problem by downloading the models again and then the result marked.

**Comment by gineshidalgo99** [comment]
@shinerio  I was getting crazy trying to figure out the error. Thanks for the feed-back, I didn't expect the reason was the models being corrupted. Most probably, the internet connection dropped when they were being downloaded. Thanks!

**Comment by SCUT2014** [comment]
Starting pose estimation demo.
GStreamer Plugin: Embedded video playback halted; module decodebin20 reported: Your GStreamer installation is missing a plug-in.
Auto-detecting GPUs... Detected 2 GPU(s), using them all.
warning: GStreamer: unable to seek (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:710)
Starting thread(s)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
Empty frame detected, frame number 0 of 0. In src/openpose/producer/producer.cpp:checkFrameIntegrity():148
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
Input images must be 3-channel BGR. Converting your grey image into BGR. In ./include/openpose/producer/datumProducer.hpp:checkIfRunningAndGetDatum():107

(openpose.bin:8896): Gtk-WARNING **: cannot open display:

**Comment by limberc** [comment]
Hi there, I got the same problem here, how can I download the new model that could solve this problem? By just ran the script again?

**Comment by mas2tg** [comment]
Re-downloading the models by running the scripts under models/ worked for me!

**Comment by hellozjj** [comment]
> Starting pose estimation demo.
> GStreamer Plugin: Embedded video playback halted; module decodebin20 reported: Your GStreamer installation is missing a plug-in.
> Auto-detecting GPUs... Detected 2 GPU(s), using them all.
> warning: GStreamer: unable to seek (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:710)
> Starting thread(s)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
> Empty frame detected, frame number 0 of 0. In src/openpose/producer/producer.cpp:checkFrameIntegrity():148
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
> Input images must be 3-channel BGR. Converting your grey image into BGR. In ./include/openpose/producer/datumProducer.hpp:checkIfRunningAndGetDatum():107
> 
> (openpose.bin:8896): Gtk-WARNING **: cannot open display:

how do you solve this ?
