### ISSUE TITLE
It is writing features for more number of peoples than there are in video

### ISSUE THREAD

**Issue by sagarkukreja** [CMU-Perceptual-Computing-Lab/openpose#499]
### Issue Summary
My video contains 3 people sitting around a table in a room and having conversation. When I run openpose on it , for some frames its writing features for 4 or 5 people while there are only three of them in the video. How can I make sure that it detects and write features for the ones present in video.

### Type of Issue
- Help wanted
- Question

**Comment by CockPc** [comment]
If what I know is true, there is factor of possiblity after x, y

**Comment by ehx-v1** [comment]
A thought on issues of this kind (detection producing wrong results): It might be a good idea to re-check the video with overlay, to see what exactly is going wrong. In this case, it might for example be some people being detected more than once, or something that's not a person at all being detected as person (or something entirely different but I can't think of anything else). If the second one is true, it's probably down to refining the neural network behind it (which is declared as off topic by the guidelines).
