### ISSUE TITLE
Makefile.config in 3rdparty/caffe is incnosistent with same in root folder.

### ISSUE THREAD

**Issue by malchun** [CMU-Perceptual-Computing-Lab/openpose#5]
Makefile.config in 3rdparty/caffe isn't affected by main config (during installation with install_caffe_and_openpose.sh script), which leads to trouble with configuration (for example: you are trying to setup openblas with main config, but still has error message about absence of atlas).

**Comment by gineshidalgo99** [comment]
You are right, so far you must (manually) set the same flags in both Makefile.config files (the one from OpenPose and the one from Caffe).

We will notify this thread once we solve this issue. Thanks!

**Comment by gineshidalgo99** [comment]
Problem solved with the new CMake version. Thanks

Note: The old Makefile version will keep this bug.
