### ISSUE TITLE
 fatal error C1083: Cannot open file included: “cudnn.h”: No such file or directory

### ISSUE THREAD

**Issue by 408550969** [CMU-Perceptual-Computing-Lab/openpose#50]
### Your system configuration
**Operating system** Windows10
**CUDA version** 8.0
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi`):
**Caffe version**: Default
**OpenCV version**: Default
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
cuDNN was not properly installed.
