### ISSUE TITLE
Issue with CMakeLists.txt while installing

### ISSUE THREAD

**Issue by cnzJohn** [CMU-Perceptual-Computing-Lab/openpose#503]
### Issue Summary
Issue with CMakeLists.txt while installing

### Executed Command (if any)
make
Before I manually edit cmake/Modules/FindCuDNN.cmake with the include and library paths:

find_path(CUDNN_INCLUDE cudnn.h
PATHS ${CUDNN_ROOT} $ENV{CUDNN_ROOT} ${CUDA_TOOLKIT_INCLUDE} /usr/local/cuda/include
DOC "Path to cuDNN include directory." )
find_library(CUDNN_LIBRARY NAMES ${CUDNN_LIB_NAME}
PATHS ${CUDNN_ROOT} $ENV{CUDNN_ROOT} ${CUDNN_INCLUDE} ${__libpath_hist} ${__libpath_hist}/../lib /usr/local/cuda/lib64
DOC "Path to cuDNN library.")
Didn't do other changes

### OpenPose Output (if any)
ubuntu@ip-10-55-2-44:~/openpose$ make
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_30
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
CMake Error at CMakeLists.txt:567 (add_subdirectory):
The source directory

/home/ubuntu/openpose/src
does not contain a CMakeLists.txt file.

-- Adding Example openpose.bin
-- Adding Example 1_custom_post_processing.bin
-- Adding Example 1_extract_from_image.bin
-- Adding Example 2_extract_pose_or_heatmat_from_image.bin
-- Adding Example 1_openpose_read_and_display.bin
-- Adding Example 2_user_processing_function.bin
-- Adding Example 3_user_input_processing_and_output.bin
-- Adding Example 4_user_input_processing_output_and_datum.bin
-- Adding Example 1_user_asynchronous_output.bin
-- Adding Example 2_user_synchronous.bin
-- Adding Example 3_user_asynchronous.bin
-- Adding Example handFromJsonTest.bin
-- Adding Example resizeTest.bin
-- Download the models.
-- Downloading body (COCO) model...
-- Model already exists.
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/openpose/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/openpose/CMakeFiles/CMakeError.log".
Makefile:146: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

I am sure I pulled the latest version

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):Ubuntu 16.04
**Installation mode**: CMake
**CUDA version**  (cat /usr/local/cuda-8.0/version.txt): CUDA Version 8.0.61
**cuDNN version**:5.1.10
**CMake version** (`cmake --version` in Ubuntu):cmake version 3.5.1
**Release or Debug mode**? (by defualt: release):release
**3-D Reconstruction module added**? (by default: no):no 
**GPU model** (`nvidia-smi` in Ubuntu):NVIDIA-SMI 384.111 Driver Version: 384.111
**Caffe version**: Default from OpenPose
**OpenCV version**: 2.4.8
Compiler (`gcc --version` in Ubuntu):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by christian-lanius** [comment]
Did you run cmake before? Make sure to follow the instructions in the readme. You should never run the make command in the openpose folder. Instead you should create a build folder, change into it, run cmake on the parent to generate a build in in your build folder and then run the make command (check #493). The build documentation can be found at https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation

**Comment by cnzJohn** [comment]
yes, I followed the instructions in the ReadMe. I created a build foled and cd into this folder. After that, I run the below Cmake command, still got same errors. 
~/openpose/build$ cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ..

**Comment by cnzJohn** [comment]
I retried again, I followed all instructions which is from (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation) here.
Then I run the below command:
**cd ~/openpose
mkdir build
cd build
cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ..**
After this I got below errors:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GCC detected, adding compile flags
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- Building with CUDA.
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_30
-- cuDNN not found
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- cuDNN not found.
# Install cuDNN 5.1
ubuntu_version="$(lsb_release -r)"
CUDNN_URL="http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz"
wget -c ${CUDNN_URL}
sudo tar -xzf cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local
rm cudnn-8.0-linux-x64-v5.1.tgz && sudo ldconfig
CMake Error at CMakeLists.txt:282 (message):
  Install cuDNN using the above commands.  or turn off cuDNN by setting
  USE_CUDNN to OFF.


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/openpose/build/CMakeFiles/CMakeError.log".

**So** I edit the cmake/Modules/FindCuDNN.cmake to the below files:
find_path(CUDNN_INCLUDE cudnn.h
    PATHS ${CUDNN_ROOT} $ENV{CUDNN_ROOT} ${CUDA_TOOLKIT_INCLUDE} /usr/local/cuda/include
    DOC "Path to cuDNN include directory." )
find_library(CUDNN_LIBRARY NAMES ${CUDNN_LIB_NAME}
    PATHS ${CUDNN_ROOT} $ENV{CUDNN_ROOT} ${CUDNN_INCLUDE} ${__libpath_hist} ${__libpath_hist}/../lib /usr/local/cuda/lib64
    DOC "Path to cuDNN library.")

**After this** I tried the below command again
cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ..

**fortunately no errors** Below is output
-- GCC detected, adding compile flags
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- Building with CUDA.
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_30
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
Submodule '3rdparty/caffe' (https://github.com/CMU-Perceptual-Computing-Lab/caffe.git) registered for path '../3rdparty/caffe'
Cloning into '3rdparty/caffe'...
Submodule path '../3rdparty/caffe': checked out '569352cc8e6a3ce8e8b03c12c975779235522f19'
Previous HEAD position was 569352c... Merge https://github.com/BVLC/caffe
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
-- Download the models.
-- Downloading body (COCO) model...
-- NOTE: This process might take several minutes depending on your internet connection.
-- Not downloading body (MPI) model
-- Downloading face model...
-- NOTE: This process might take several minutes depending on your internet connection.
-- Downloading hand model...
-- NOTE: This process might take several minutes depending on your internet connection.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/openpose/build

*And I run make command again* , then there are below errors:
-- Build files have been written to: /home/ubuntu/openpose/build
[  3%] Built target openpose_caffe
[  4%] Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o
CMake Error at openpose_generated_resizeAndMergeBase.cu.o.cmake:207 (message):
  Error generating
  /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_resizeAndMergeBase.cu.o


src/openpose/CMakeFiles/openpose.dir/build.make:105: recipe for target 'src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o' failed
make[5]: *** [src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o] Error 1
CMakeFiles/Makefile2:213: recipe for target 'src/openpose/CMakeFiles/openpose.dir/all' failed
make[4]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_caffe.dir/build.make:124: recipe for target 'openpose_caffe' failed
make[2]: *** [openpose_caffe] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gineshidalgo99** [comment]
The error is coming from the CUDA files (*.cu files). It's definitely something to do with the CUDA installation.

**Comment by cnzJohn** [comment]
Thanks for your reply. my cuda version is cuda 8.0. I rerun the below command:
sudo ubuntu/install_cuda.sh
I got the below info, seems the installation is successful. 
Get:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Ign:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Get:2 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:2 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Hit:3 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease                                                                                                           
Hit:4 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                   
Hit:5 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease                                           
Get:7 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                                      
Hit:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease                           
Fetched 102 kB in 1s (59.0 kB/s)                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wget is already the newest version (1.17.1-1ubuntu1.3).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
ubuntu/install_cuda.sh: 3: ubuntu/install_cuda.sh: [[: not found
ubuntu/install_cuda.sh: 6: ubuntu/install_cuda.sh: [[: not found
Get:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Ign:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Get:2 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:2 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Hit:3 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease                                                                            
Hit:4 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                    
Hit:5 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                  
Get:7 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                                       
Hit:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease                            
Fetched 102 kB in 2s (48.5 kB/s)                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cuda is already the newest version (8.0.61-1).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.

I run again the "cmake" command and "make" command, but after "make", still got same errors.

**Comment by cnzJohn** [comment]
Below is the files in the build folder after I run "camke" under build folder.
CMakeCache.txt  CMakeFiles  Makefile  caffe  cmake  cmake_install.cmake  cmake_uninstall.cmake  detect_cuda_archs.cu  examples  src

**Comment by cnzJohn** [comment]
Seems it's a CUDA issue. Closed as it's not issue related to openpose

**Comment by vasanthhr** [comment]
I got the same issue. can someone help me here.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1087

**Comment by SREE27NIDHI** [comment]
ss

**Comment by Mr-yun** [comment]
I had the same problem, and then it was caused by a mismatch between cuda and the libcublas version.
My cuda is 10.0, but apt installs 9.1 (queried by the command: `ldconfig-p` | grep cublas`).
Then I downloaded the appropriate version in (https://ubuntu.pkgs.org/19.04/ubuntu-multiverse-amd64/libcublas10_10.1.105-0ubuntu1_amd64.deb.html) and executed 
`dpkg-I` libcublas10_10.1.105-0ubuntu1_amd64.deb`

**Comment by Mr-yun** [comment]
I had the same problem, and then it was caused by a mismatch between cuda and the libcublas version.
My cuda is 10.0, but apt installs 9.1 (queried by the command: `ldconfig-p | grep cublas`).
Then I downloaded the appropriate version in (https://ubuntu.pkgs.org/19.04/ubuntu-multiverse-amd64/libcublas10_10.1.105-0ubuntu1_amd64.deb.html) and executed
`dpkg -i libcublas10_10.1.105-0ubuntu1_amd64.deb`
