### ISSUE TITLE
error: /usr/local/lib/libcurl.so.4: no version information available

### ISSUE THREAD

**Issue by dalewen** [CMU-Perceptual-Computing-Lab/openpose#507]
wanggw@liutl:~/work/openpose/build$ make -j`nproc`
[100%] Built target handFromJsonTest.bin
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)

wanggw@liutl:~/work/openpose/build$ locate libcurl.so.4
/home/chenm/anaconda2/lib/libcurl.so.4
/home/chenm/anaconda2/lib/libcurl.so.4.5.0
/home/chenm/anaconda2/pkgs/libcurl-7.58.0-h1ad7b7a_0/lib/libcurl.so.4
/home/chenm/anaconda2/pkgs/libcurl-7.58.0-h1ad7b7a_0/lib/libcurl.so.4.5.0
/home/dongxd/anaconda2/lib/libcurl.so.4
/home/dongxd/anaconda2/lib/libcurl.so.4.4.0
/home/dongxd/anaconda2/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4
/home/dongxd/anaconda2/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4.4.0
/home/liutl/anaconda/lib/libcurl.so.4
/home/liutl/anaconda/lib/libcurl.so.4.3.0
/home/liutl/anaconda/pkgs/curl-7.38.0-0/lib/libcurl.so.4
/home/liutl/anaconda/pkgs/curl-7.38.0-0/lib/libcurl.so.4.3.0
/home/pinga/anaconda3/lib/libcurl.so.4
/home/pinga/anaconda3/lib/libcurl.so.4.4.0
/home/pinga/anaconda3/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4
/home/pinga/anaconda3/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4.4.0
/home/wanggw/anaconda2/lib/libcurl.so.4
/home/wanggw/anaconda2/lib/libcurl.so.4.4.0
/home/wanggw/anaconda2/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4
/home/wanggw/anaconda2/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4.4.0
/home/wangj/anaconda2/lib/libcurl.so.4
/home/wangj/anaconda2/lib/libcurl.so.4.4.0
/home/wangj/anaconda2/pkgs/curl-7.49.0-0/lib/libcurl.so.4
/home/wangj/anaconda2/pkgs/curl-7.49.0-0/lib/libcurl.so.4.4.0
/home/wanjw/anaconda2/lib/libcurl.so.4
/home/wanjw/anaconda2/lib/libcurl.so.4.4.0
/home/wanjw/anaconda2/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4
/home/wanjw/anaconda2/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4.4.0
/home/wanjw/anaconda3/lib/libcurl.so.4
/home/wanjw/anaconda3/lib/libcurl.so.4.4.0
/home/wanjw/anaconda3/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4
/home/wanjw/anaconda3/pkgs/curl-7.55.1-hcb0b314_2/lib/libcurl.so.4.4.0
/usr/lib/x86_64-linux-gnu/libcurl.so.4
/usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
/usr/local/MATLAB/R2013b/bin/glnxa64/libcurl.so.4
/usr/local/MATLAB/R2013b/bin/glnxa64/libcurl.so.4.2.0
/usr/local/MATLAB/R2015b/bin/glnxa64/libcurl.so.4
/usr/local/MATLAB/R2015b/bin/glnxa64/libcurl.so.4.3.0
/usr/local/MATLAB/R2015b/toolbox/compiler_sdk/mps_clients/c/glnxa64/lib/libcurl.so.4
/usr/local/MATLAB/R2015b/toolbox/compiler_sdk/mps_clients/c/glnxa64/lib/libcurl.so.4.3.0
/usr/local/lib/libcurl.so.4

wanggw@liutl:~/work/openpose/build$ ls -l /usr/local/lib/libcurl.so.4
lrwxrwxrwx 1 root root 37 5月  21  2015 /usr/local/lib/libcurl.so.4 -> /home/liutl/anaconda/lib/libcurl.so.4

wanggw@liutl:~/work/openpose/build$ cmake -version
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
wanggw@liutl:~/work/openpose/build$

**Comment by Qayou** [comment]
This issue is not related to OpenPose but to CMake.

Looking up the error (first line of `cmake -version` output) on Google gives you some solutions you can try.

**Comment by gineshidalgo99** [comment]
Compiling with Anaconda is actually quite hard. I'd recommend using normal OpenCV (from apt-get install libopencv) + default Caffe
