### ISSUE TITLE
Running performance test

### ISSUE THREAD

**Issue by jamestodo** [CMU-Perceptual-Computing-Lab/openpose#509]
I want to test the performance by using Quadro-P6000 and Quadro-M6000.
My system environment is described as blow:
**Ubuntu 16.04,Cuda 9.0,cuDNN 7.0,Nvidia Driver Version--384.111(suitable for both P6000 and M6000).**

When i run with the command:
`./openpose.bin --video demo.mp4 --resolution 1280x720 --net_resolution 1312x736 --write_video result.avi`

The P6000(3.5 fps) is about ~20% faster than the M6000(2.9).

When i run the command:
`./openpose.bin --video demo.mp4 --resolution 1280x720 --net_resolution 656x368 --write_video result.avi`

The P6000 and M6000 both about  ~10 fps.

I think it might be that the P6000/M6000 both have enough cores to parallel process one image at one time with the `net_resolution=656x368`.But they couldn't do that with the `net_resolution=1312x736`.

But i want to compare the running time between P6000 and M6000 by using the option `net_resolution=656x368`.How could i do that.

Any help is appreciated.Thanks a lot!

**Comment by gineshidalgo99** [comment]
PROFILER_ENABLED in CMake and let it run for 1000 frames (check doc).
