### ISSUE TITLE
Openpose cannot detect people and model_folder option not work

### ISSUE THREAD

**Issue by shensha9** [CMU-Perceptual-Computing-Lab/openpose#510]
### Issue Summary
I am trying the CPU_ONLY option in openpose v1.3 because my PC has no nvidia GPU. openpose can run successfully with a GUI displaying the video. But no people are detected. I have seen that the previous post says deleting the model and trying again fix the problem. But it didn't work for me. I downloaded more than 3 times and check the md5 for each download files.  The model file should be fine. 

One wired thing is that： even if I deliberately input the wrong directory of model in the command line， openpose can also run without error. I remember in previous version an error will occur saying "pose/face/hand model not found".  

### Executed Command (if any)
The following 3 commands are used. Both are the same result
 ./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 0

./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 0 -model_folder "models/"

./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 0 -model_folder "wrong_dir"

### OpenPose Output (if any)
![image](https://user-images.githubusercontent.com/36256944/37964772-39361786-31f5-11e8-9a85-57611bba770c.png)

### Type of Issue

- Execution error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...?
Ubuntu

**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
CUDA Version 8.0.61

**cuDNN version**:
**CMake version** (`cmake --version` in Ubuntu):
cmake version 3.5.1

**Release or Debug mode**? (by defualt: release):
release

**3-D Reconstruction module added**? (by default: no):
no

**GPU model** (`nvidia-smi` in Ubuntu):
No 

**Caffe version**: Default from OpenPose, custom version, ...?
Default from OpenPose

**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
pre-compiled `apt-get install libopencv-dev`

Compiler (`gcc --version` in Ubuntu):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
Don't use `--num_gpu 0`. If you want CPU version, follow the doc/installation.md points. num_gpu 0 makes something different
