### ISSUE TITLE
How to control fps?

### ISSUE THREAD

**Issue by Yun-Jung** [CMU-Perceptual-Computing-Lab/openpose#511]
I have already looked up issues of the website, but I still don't know how to fix fps and keep it stable. I want to fix fps to get the relation between coordinate and time. Is there any information about these? Or it is determined automatically?

**Comment by gineshidalgo99** [comment]
It will simply process as fast as possible. You would have to create some extra logic to control your FPS (e.g. following the tutorial_wrapper examples)
