### ISSUE TITLE
Issue about protoc version with custom caffe

### ISSUE THREAD

**Issue by daooshee** [CMU-Perceptual-Computing-Lab/openpose#512]
### Issue Summary
Custom caffe is compiled with protobuf 3.4.0, and the default protobuf of the system is also set to 3.4.0. However, when compiling openpose, it seems that it is using an older version. 

### Executed Command
Hi, I encountered this problem when I was trying `make all -jX` in `/build`
I have checked my protoc version:
```
$ protoc --version
libprotoc 3.4.0
$ which protoc
/home/XXX/anaconda2/bin/protoc
```
and in /home/XXX/caffe-master/include/caffe/caffe.pb.h it says:
```
#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif
```
Which means protobuf version 3.4.0 is suitable.

I can `cmake` successfully. I use
```
cmake -DOpenCV_INCLUDE_DIRS=/home/XXX/anaconda2/pkgs/opencv-3.1.0-np113py27_intel_8/include \
  -DOpenCV_LIBS_DIR=/home/XXX/anaconda2/pkgs/opencv-3.1.0-np113py27_intel_8/lib \
  -DCaffe_INCLUDE_DIRS=/home/XXX/caffe-master/include \
  -DCaffe_LIBS=/home/XXX/caffe-master/.build_release/lib/libcaffe.so -DBUILD_CAFFE=OFF ..
```
Moreover, I can rebuild caffe in this environment successfully.

### OpenPose Output
```
In file included from /home/XXX/caffe-master/include/caffe/blob.hpp:9:0,
                 from /home/XXX/openpose/src/openpose/face/faceExtractorCaffe.cpp:2:
/home/XXX/caffe-master/include/caffe/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
```
There do exist an old-version protobuf-2.5.0 in `/usr/bin/protoc`, but for some reason I can't edit or delete it. It seems that the `make` in openpose uses `/usr/bin/protoc` instead of `/home/XXX/anaconda2/bin/protoc`. Does openpose use `/usr/bin/protoc` instead of `protoc`? Is there any file in /openpose that resets the protoc version?

The only difference between the default caffe from openpose and my custom version is the `Makefile.config`, I added anaconda libs and paths. 

I also tried to build the default caffe with edited `Makefile.config` (with anaconda libs). Caffe can be build successfully, but when I link it to openpose in the custom version way, still there are errors with caffe/caffe.pb.h and protobuf version)

(When I tried to build openpose with the default caffe and BUILD_CAFFE=on, I encountered more errors about libs and paths, and also errors about protobuf version.)

### Type of Issue
- Compilation/installation error

### Your System Configuration
**Operating system**: Ubuntu 14.04.5 LTS
**Installation mode**: CMake
**CUDA version**: CUDA Version 8.0.44
**cuDNN version**: 5.1.5
**CMake version** : cmake version 2.8.12.2
**Release or Debug mode**? :  by defualt: release
**3-D Reconstruction module added**? no
**GPU model** : NVIDIA-SMI 367.57     Driver Version: 367.57  
**Caffe version**: custom version
**OpenCV version**: 3.1
Compiler: gcc (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3

**Comment by rainforest1** [comment]
Yes, i have the same issue. The code compiles successfully but throws linking errors with Protobuf versions at run time. Were you able to fix this issue?

**Comment by daooshee** [comment]
Well... I gave up the fight against the conda library and solved the problem by installing Openpose on another computer (without conda) and using Caffe provided by Openpose.

**Comment by ruizcrp** [comment]
Hi, I solved it but I am not sure how as I did so many things. I think I did the following that worked:
-first of all clean the build-folder in case that you did already things.
-Downloading and compiling protobuf from source
-Install the openpose caffee dependencies as in the installation-guide.
-cmake

**Comment by Abduoit** [comment]
@ruizcrp 
what version do you have??, I have the following and I am encountering the same above issue !!

```
(py3-gpu) abdu@grasp-uoit:~/openpose/build$ protoc --version
libprotoc 3.5.1
(py3-gpu) abdu@grasp-uoit:~/openpose/build$ which protoc
/usr/local/bin/protoc
```

**Comment by ruizcrp** [comment]
@Abduoit 
I also have version 3.5.1 !
Did you find a solution?

**Comment by Abduoit** [comment]
@ruizcrp 
No not yet

**Comment by zhxun00cn** [comment]
I overcome this issue with installing protobuf whose version(3.5.1) is consistent with other libs

My System Configuration is Ubuntu 16.04 +  opencv3.4.1(compiled from source) +protobuf3.5.1 + linux python2 
additional I have anaconda3.5 in my system, but trying to avoid other annoying problems, I don't use almost any libs in anaconda.

I tried to modified the caffe.pb.h like this:
#if GOOGLE_PROTOBUF_VERSION == 3001000
and it shows the error information which means that the protobuf version is 3.1.0. This version is just the one installed by `sudo apt-get install protobuf-compiler protobuf-c-compiler`, which indict that I haven't purge or remove the protobuf in the `/usr`. Although with protobuf3.5.1 in anaconda, openpose still use the system protobuf, and edit cmake entried didn't do well. 
So I uninstalled the anaconda protobuf, and installed protobuf from source [https://github.com/google/protobuf/releases](url) with protobuf-all-3.5.1.tar.gz. Then:
`./autogen.sh
./configure
make
make check
sudo make install`

delete the openpose/build and cmake+make again maybe help.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back.
