### ISSUE TITLE
[Feature request] 3D from 2D video stream

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [CMU-Perceptual-Computing-Lab/openpose#516]
Extract and save 3D skeleton coordinates based on a regular single video stream on Windows 10.

**Comment by gineshidalgo99** [comment]
Thanks for the request, but it'll definitely take a lot of time before we can actually implement such an algorithm.

**Comment by ErfolgreichCharismatisch** [comment]
I have different cameras with different lenses and chips. Is it possible to sync them all and use recorded(not live) footage? In other words, input several videos plus the 3d switch.

**Comment by gineshidalgo99** [comment]
You'd have to create the code to sync them and to get an image at the same time from each of them (+ providing the extrinsic parameters), then OpenPose would use the 3d switch

**Comment by kmushegi** [comment]
Alternatively, you can use OpenCV, run OpenPose on two aligned images and then reconstruct the 3D information. You'd have to know camera parameters, however - there are some tools out there to calibrate a stereo pair, as well as OpenCV tutorials.

**Comment by seadra** [comment]
As a workaround, you can achieve this by exporting a overlayed video using openpose, and open it in Blender for [motion tracking](https://docs.blender.org/manual/nb/dev/editors/movie_clip_editor/tracking/index.html).

**Comment by gineshidalgo99** [comment]
I will close this, it is a really appealing thing to do, but a complete and independent research parallel/complementary to OpenPose. Thanks
