### ISSUE TITLE
Does the "disable_blending" images can reflect the scores?

### ISSUE THREAD

**Issue by CuiYiZe** [CMU-Perceptual-Computing-Lab/openpose#52]
### Issue summary
I want to use Openpose to do some action recognition. But could you tell me if the "disable_blending" images can reflect the scores? 
Thank you very much!!!!!!!   
 (if they can, i will train the disable_blending images to do a action classification work. And i know i can save the images as .json , but i just want to use the images to train a CNN net)

 

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
We have not tried action recognition ourselves, so we cannot answer that kind of questions. I am closing this since it is not an OpenPose issue. But please, feel free to post your conclusions after trying it. Thanks!
