### ISSUE TITLE
how about the recognition ?

### ISSUE THREAD

**Issue by Running-He** [CMU-Perceptual-Computing-Lab/openpose#521]
understand it can do the facial and body detection , how about facial recognition and body language recognition ?

**Comment by gineshidalgo99** [comment]
Interesting research topic that we have not explored yet, so I can't help here.

**Comment by Running-He** [comment]
ic,, so how to track the individual(s) without the recognition ?

**Comment by gineshidalgo99** [comment]
For now, that's up to the user. We'll include (expected within the next 2-4 months)  person tracking/basic identification, to track the people across frames.

**Comment by Gautam1121** [comment]
If you like the results:
pose recognition

![newcreation1](https://user-images.githubusercontent.com/43058499/45872248-2d315600-bdad-11e8-8cd2-602554b01b4f.jpeg)
![newcreation2](https://user-images.githubusercontent.com/43058499/45872249-2d315600-bdad-11e8-8b29-cc3fc279a643.jpeg)
![newcreation4](https://user-images.githubusercontent.com/43058499/45872251-2d315600-bdad-11e8-84f6-1565b5af2398.jpeg)
![newcreation5](https://user-images.githubusercontent.com/43058499/45872253-2dc9ec80-bdad-11e8-81bf-cce3287069c0.jpeg)
![newcreation6](https://user-images.githubusercontent.com/43058499/45872254-2dc9ec80-bdad-11e8-87f7-66586b61f4cd.jpeg)
![newcreation7](https://user-images.githubusercontent.com/43058499/45872255-2e628300-bdad-11e8-8a5e-931124a9ebe7.jpeg)
![newcreation8](https://user-images.githubusercontent.com/43058499/45872256-2e628300-bdad-11e8-916d-d6b030a6cd37.jpeg)
![newcreation9](https://user-images.githubusercontent.com/43058499/45872257-2e628300-bdad-11e8-938c-d5a27c0e1174.jpeg)

**Comment by NicksonYap** [comment]
You can check this repo: https://github.com/srianant/computer_vision
Seems promising

**Comment by RedDestractor** [comment]
any news about topic?
