### ISSUE TITLE
Best way to run it on a folder of videos [Ubuntu]

### ISSUE THREAD

**Issue by joaogantunes** [CMU-Perceptual-Computing-Lab/openpose#522]
I have OpenPose installed and Running correctly on my Ubuntu system. I just wanted to ask, my goal is to run OpenPose on all the videos I have on a dataset. What is the most efficient way of doing so? Currently I'm using a shell script to call the OpenPose demo on a single video and then looping over all the videos.

Is there a way to do it the same way I can do it for images? (i.e. I just input the folder where all the images are and it goes through all of them)

Thanks!

**Comment by gineshidalgo99** [comment]
I thought about doing something like that, but it'd require the user to place the videos folders in that exact structure (and datasets are always different to each other in structure), so I discarded the idea.
So what I do when running it on datasets is exactly that: bash script. So far I think it's the most generic and flexible approach.
But I'm open to discuss any other ideas.

**Comment by joaogantunes** [comment]
Ok, Thanks.

From what I saw it feels like a significant amount of time is wasted in loading the OpenPose model and connecting to the GPUs for each video so I thought that maybe there was a better option.

Thank you for your answer.

**Comment by gineshidalgo99** [comment]
That's true. But for long videos, taking 2 sec to load a model is not significant if you are taking e.g. 20 sec to process the whole video.

But for very small videos, yes, you are right, the time could be much better optimized if OP is kept opened. However, I think this is usually not the case.

**Comment by gineshidalgo99** [comment]
Creating your own bash script for that is the fastest thing to do.
