### ISSUE TITLE
What is the order of key_points saved?

### ISSUE THREAD

**Issue by taylover-pei** [CMU-Perceptual-Computing-Lab/openpose#525]
I want to ask what's the order of key_point saved?
That means if the openpose has detected more than one person and the key_points have been saved in the json file. So, how can I find out which list of key_points belongs to which person?

**Comment by gineshidalgo99** [comment]
Unfortunately, there is no a way to know the person ordering. So there is not a way to know the person ordering across frames for now. We are working in adding person id but it'll still take some time.
