### ISSUE TITLE
Which parameter controls GPU memory consumption?

### ISSUE THREAD

**Issue by AlexLuya** [CMU-Perceptual-Computing-Lab/openpose#526]
Hello,I am using PyOpenpose with below settings:

```
       self.poseSize = (656, 368)
        self.faceHandSize = (240, 240)
        self.outSize = (640, 480)
        self.modelType = "COCO"
        self.logLevel = 0
        self.downloadHeatmaps = False
        self.detectFace = False
        self.detectHands = False
```
Same python scripts+same settings as above,
under my laptop with a nvidia  **1070** card,python wrapped openpose process consumed 
**1516MB** GPU memory,
but under a server with nvidia  **1080Ti** card,openpose process consumed 
**7883MB** GPU memory,
where does this big memory consumption comef from?Any parameter to specify GPU memory consumption?

**Comment by gineshidalgo99** [comment]
I am sorry, but PyOpenPose is not ours. So i'd recommend you to open an issue there, we can't help you here.
