### ISSUE TITLE
Any convenient way to get the bounding box coordinates of people head  when only pose detection enabled?

### ISSUE THREAD

**Issue by AlexLuya** [CMU-Perceptual-Computing-Lab/openpose#527]
Currently,I used a complex calculation to get this coordinates,but as you can see below,two much(and big) bias due to detection errors,so any convenient way to do this?
![arbeitsflache 1_152](https://user-images.githubusercontent.com/303353/38462955-4e047ec0-3b21-11e8-8d4e-3438b9a7a61b.png)

**Comment by crazyfrog-github** [comment]
Hi,

How did you determine if a person is standing or sitting down and put a label on person?

Is it based on angles of keypoints or the distance between certain keypoints for example feet and neck?

**Comment by aniketzz** [comment]
Hi ,
From the image I think its the angles of the keypoints.  Mostly the knee vs the spine angles i guess. Because in picture .  Ine person's legs are straing but he has bent forward and its been detected as sitting posture.

**Comment by rentonliu** [comment]
here is the answer for getting bunding boxes for people: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/93

**Comment by gineshidalgo99** [comment]
@rentonliu  Thanks for the link, I forgot i typed that answer in the past.
