### ISSUE TITLE
Is it possible to have multiple ip camera streams and openpose process the ip cameras concurrently?

### ISSUE THREAD

**Issue by hotdogs123** [CMU-Perceptual-Computing-Lab/openpose#529]
Is it possible to have multiple ip camera inputs streaming realtime video to a single instance of openpose to process the streams concurrently or multiple instances of openpose to process a single ip camera stream concurrently?

If so how would this be achieved?

If not is this on the development roadmap?

**Comment by gineshidalgo99** [comment]
That's a very specific case, so unfortunately no, it is not done nor expected. You can implement your custom code with tutorial_wrapper/2* example to read your cameras (e.g. with OpenCV as we do).
