### ISSUE TITLE
Where is the OpenPose.lib? (Compiler with VS2015)

### ISSUE THREAD

**Issue by jerry7767** [CMU-Perceptual-Computing-Lab/openpose#53]
I can't find OpenPose.lib under the openpose folder.

![image](http://i.imgur.com/j4foWzK.png)

How can I get the OpenPose.lib?

And...why OpenPose project load failed?

Thank you.

**Comment by solbach** [comment]
Hi!
before you are able to build and run the demo you need to build the ```OpenPose.lib```.
To do so, open ```openpose.sln``` and select ```OpenPose``` as ```set as startup project```.
The project definition of ```OpenPose``` is broken. Right click on the project and ```Reload Files``` will tell you what is going on (probably ```Cuda 8.0.props``` is not in the right spot). In my case, I had to copy 
* CUDA 8.0.props
* CUDA 8.0.targets
* CUDA 8.0.xml

__From__ ```C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations```
__To__ ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations```

Try reloading the OpenPose project ... fingers crossed that's it! Make sure you have ```Release``` and ```x64``` selected and hit ```Build```. Don't worry about the _"OpenPose.lib is not a valid Win32 application"_ message. This takes some time and you should find the library generated in folder ```openpose\windows_project\x64\Release```. 
After this, you are able to switch to the Demo project to build it!

__Another hint:__ Install Cuda 8.0 AFTER Visual Studio 2015 to assure that the Cuda Installation will generate all necessary files for Visual Studio 2015.

Hope this helps!

**Comment by jerry7767** [comment]
Hi solbach,

I can generate the _"OpenPose.lib"_ by your steps, and build the Demo project success!

p.s. Re-install Cuda 8.0 after Visual Studio 2015 is necessary.

Thank you! Have a nice day!

**Comment by gineshidalgo99** [comment]
@solbach thank you for the suggestions/hints.

For new users, please follow the [installation steps](../blob/master/doc/installation.md), which already includes the solbach suggestions/hints. (I just added and commited them)
