### ISSUE TITLE
Issue about OpenPose3D

### ISSUE THREAD

**Issue by ilovebob** [CMU-Perceptual-Computing-Lab/openpose#531]
[OpenPose3D](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/3d_reconstruction_demo.md)
Fujinon 3 MP Varifocal Lens (3.8-13mm, 3.4x Zoom) has a iris cable but Blackfly S Color 1.3 MP USB3 Vision has not a interface to enable it.
So how to solve it？

**Comment by gineshidalgo99** [comment]
Not sure I understand the question, the cameras and lens we mention in the doc are just plug and play, you just manually "screw" it with your hand.

**Comment by ilovebob** [comment]
![qq 20180411105856](https://user-images.githubusercontent.com/11513803/38594104-5f6696dc-3d77-11e8-9cdf-1e0f301dbde7.jpg)

**Comment by gineshidalgo99** [comment]
When I ordered these lens 1 year ago, they did not have this cable. I guess they have improved the model or you have ordered a most updated version. Is the cable required? Try without the cable.

**Comment by gineshidalgo99** [comment]
I have just bought a new Fujinon lens, I can confirm the model specified in the 3d doc does not have this cable. You must have ordered and slightly different model.

**Comment by AdeV-Oly** [comment]
To my understanding, that's the model with a DC iris lens, so you can automatically adjust the amount of light. The previous models, such as the one referred to in the 3d doc had a manual iris and therefore no cable.
