### ISSUE TITLE
Call openpose as a library function instead of using wrapper

### ISSUE THREAD

**Issue by hbhzwj** [CMU-Perceptual-Computing-Lab/openpose#536]
Hi everyone,

Thanks for providing such a great tool! I am working on a project in which I want to extract skeletons and do some additional processing. I checked out the wrapper examples: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_wrapper/2_user_synchronous.cpp. It seems that it requires me to define input as `WUserInput` and put all post-processing logic in  `WUserPostProcessing` class.

However, my project includes many other existing components, so it would be much easier if I can just call a **library function that takes an image as input and returns all key points**.

I wonder if it is possible to call openpose as a library function instead of using wrapper framework? Any help will be highly appreciated. Looking forward to hearing from you. Thanks!

Best Wishes,
Jing Conan Wang

**Comment by gineshidalgo99** [comment]
You can check e.g. tutorial_pose to get pose keypoints, which you can adapt for hand and face as well.

**Comment by hbhzwj** [comment]
Thanks a lot for your help Gines! FYI, I found a simplified version of OpenPose (https://github.com/dlunion/EasyOpenPose/blob/master/easyOpenPose.cpp). I converted the main function to a library function and it seems to work very well.

**Comment by MJUSER** [comment]
Hey , Is there any tutorials available for this libraries implementation?
Its for my projects purpose ! Help me out?
