### ISSUE TITLE
Genuine upside down orientation video processing

### ISSUE THREAD

**Issue by automatemyhome** [CMU-Perceptual-Computing-Lab/openpose#537]
Hi

I am trying to get openpose to recognise pose of people from ip camera that is streaming video upside down.

I want to leave the ip camera source as it is that is upside down and process it in thjs orientation also.

 Based on the demo it appears that openpose only recognises / detects pose when people are feet at the bottom of the image and does not recognise /detect pose when vertically flipped that is upside down.

Can anyone tell me how to make openpose work with ip camera video that is uoside down that is peoples feet near the top and head near the bottom?

Any suggestions would be appreciated.

**Comment by gineshidalgo99** [comment]
There is a flag for it, check doc/demo_overview. There is a flipping (mirroring) flag and a 90, 180, 270 degree rotation flag. Not sure the name right now.

**Comment by automatemyhome** [comment]
Thanks for the reply but that is exactly not what I wanted I know how to rotate a video.

I do not want to rotate the video it MUST process upside down.

I will reopen.

**Comment by gineshidalgo99** [comment]
Then just manually rotate the keypoints back again after OpenPose finds them. But you will have to give the image with the people with the head up and legs down.

**Comment by automatemyhome** [comment]
Thanks for your prompt response. This is the problem, most of the time people are the right way up head at the top etc but there are times when the person can be upside down so therefore open pose does not detect them at all.

Which keypoint does openpose start to identify first before estimate the rest of the keypoints is it the head or the feet?

Is there any way for openpose to detect a person if head is at the bottom and feet near the top of an image to recognise them without flipping the video?

Probably overkill but is it an option to retrain the data model to include vertical flipped data as well as right way up so ot has both or will that confuse openpose completely?

Is what you suggesting above to post process frame by frame check first frame for successful recognition if so draw keypoints if not flip the image then check again if successful draw keypoints and just keep processing frame by frame like this?

If so I suppose that this approach would slow as having to double handle each frame?

Any suggestions.

Cheers

**Comment by crazyfrog-github** [comment]
Hi

Thanks for the response very informative.

Great to know you already tried the +-180 degrees training thought it would impact accuracy.

Like your idea option 2. Using an ip camera real time stream how would I feed the original frame copy it then flip and feed the flipped frame to openpose then grab next frame and repeat?

I know you have trained on +-40deg how would increase this to say +-60deg what do I have to change?

Thanks for your help with this really help speaking to someone who knows.

**Comment by gineshidalgo99** [comment]
If it's offline video/image dir you can always process it twice. For IP/webcam online streaming, I guess the only option is to modify producer/ipreader or producer/producer to duplicate the image but rotated 180 degrees (which is different than flipped horizontally). OpenPose will process both frames and save 2 different json files for each one.

+-60deg: No idea, I didn't play that much. You can always play with the training code yourself: https://github.com/ZheC/Multi-Person-Pose-Estimation/
