### ISSUE TITLE
Not solved yet - Genuine upside down orientation video processing 

### ISSUE THREAD

**Issue by automatemyhome** [CMU-Perceptual-Computing-Lab/openpose#538]
Hi

I am trying to get openpose to recognise pose of people from ip camera that is streaming video upside down.

I want to leave the ip camera source as it is that is upside down and process it in this orientation NOT to rotate the video right way up.

Based on the demo it appears that openpose only recognises / detects pose when peoples feet at the bottom of the image and does not recognise /detect pose when upside down.

Can anyone tell me how to make openpose work with ip camera video that is upside down that is peoples feet near the top and head near the bottom?

Any suggestions would be appreciated.

**Comment by gineshidalgo99** [comment]
Duplicated #537
