### ISSUE TITLE
what command run BODY_19b code 

### ISSUE THREAD

**Issue by puface** [CMU-Perceptual-Computing-Lab/openpose#539]
Hi all 
       i looking at openpose add new  Added BODY_19b code .what command run BODY_19b code in openpose . may i use --model_pose ?  i got an error .

**Comment by gineshidalgo99** [comment]
Those are just internal test versions, which doesn't work very well yet. You don't really wanna use them at the moment yet. We'd release any version we think has a good quality / speedup improvement.
