### ISSUE TITLE
How to get heatmap coordinate??

### ISSUE THREAD

**Issue by orientalh** [CMU-Perceptual-Computing-Lab/openpose#54]
Hi, i have some questions.

In poseParameters.hpp, you define heatmap part like POSE_COCO_BODY_PARTS and POSE_MPI_BODY_PARTS. 
And in Demo, i press '1' i can only see nose heatmap.

1. How can i get one part heatmap x, y coordinate??
(For example nose heatmap x, y coordinate) 

2. If 3 people are in the image. I get 3 heatmeap in the image.
Can i classify the 3 people??
For example if i want to detect the person who is the tallest person among the 3 people.
Can i detect the only the person not other 2 people??

Thanks to read it.

**Comment by CuiYiZe** [comment]
1 you can get the x y coordinate with --write_pose_json  json_output/

**Comment by gineshidalgo99** [comment]
Please, do not post questions answered on the README/documentation (question 1) and do not post question already asked on the issues thread (question 2).
