### ISSUE TITLE
On the use of openpose code 

### ISSUE THREAD

**Issue by zzzzgamer** [CMU-Perceptual-Computing-Lab/openpose#540]
Can openpose's open source code be used as a college student event and for commercial purposes?

**Comment by gineshidalgo99** [comment]
open source code --> yes
Commercial --> check README and LICENSE

**Comment by AlexDaniel** [comment]
@gineshidalgo99 I don't think you understand what open source means. In fact, “open” in “openpose” is misleading and incorrect.

See https://opensource.org/osd.

**Comment by gineshidalgo99** [comment]
The code is open source for research purposes, we don't claim to be open source for all purposes.

**Comment by AlexDaniel** [comment]
@gineshidalgo99 then it is not open-source. From https://opensource.org/osd:

> 6. No Discrimination Against Fields of Endeavor
>
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

**Comment by jarrellmark** [comment]
I agree with @AlexDaniel, the openpose license is not open source. It is a source-available license as defined by Wikipedia: [Source-available software](https://en.wikipedia.org/wiki/Source-available_software). Some example of source-available software are the Unreal Engine and MongoDB.

Openpose's commercial usage fee is 25k per year and is non-negotiable according to their website.
