### ISSUE TITLE
System Error while running OpenPoseDemo.exe on Windows

### ISSUE THREAD

**Issue by vasavig** [CMU-Perceptual-Computing-Lab/openpose#547]
### Issue Summary
After building the solution in VS 2015 Enterprise, I proceeded to check if the library installation succeeded or not. There I received errors about the executable not finding gflags.dll, glog.dll and  opencv_world310.dll. 

### Executed Command 
build\x64\Release\OpenPoseDemo.exe --video examples\media\video.avi --face --hand

### Type of Issue
- Execution error
Three pop-up windows with the following messages appeared:
1) The code execution cannot proceed because gflags.dll was not found. Reinstalling the program may fix the problem.
2) The code execution cannot proceed because opencv_world310.dll was not found. Reinstalling the program may fix the problem.
3) The code execution cannot proceed because glog.dll was not found. Reinstalling the program may fix the problem.

### System Configuration
**Operating system** : Windows 10
**Installation mode**: VS 2015 Enterprise with Update 3 build
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):cuda 8
**cuDNN version**: v 5.1
**CMake version** (`cmake --version` in Ubuntu): 3.11.1
**Release or Debug mode**? (by defualt: release): Release
**3-D Reconstruction module added**? (by default: no): No
**GPU model** (`nvidia-smi` in Ubuntu): Nvidia Titan X
**Caffe version**: Default from OpenPose

If anyone knows how to fix this issue, please comment. Thanks in advance!

**Comment by vasavig** [comment]
It seems like the executable demo is not able to locate the dlls it is dependent on. I fixed this issue by copying all the dlls to the release folder.

**Comment by abdul-mateen-chughtai** [comment]
Hi, vasavig! I am also facing the same issue and can't seem to find a solution. How did you manage to get the missing dll files? I have searched online, but still haven't found any of these.

**Comment by saketGuptaTiger** [comment]
@vasavig  Where did you find all these .dll files ?

**Comment by barakmen** [comment]
@saketGuptaTiger  inside the bin directory - copy all of the dll files to the x64/release folder.
