### ISSUE TITLE
Ubuntu: Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by repoalpha** [CMU-Perceptual-Computing-Lab/openpose#549]
I ran into the above issue causing a core dump after compiling what I believe was successful without errors.

I ran this example:

./build/examples/openpose/openpose.bin --video examples/media/video.avi

and got ...

Starting pose estimation demo.
Starting thread(s)
F0423 16:21:41.361513 17011 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.

I am guessing it somehow compiled Caffe in CPU mode or I missed a flag in the example build but so far I am drawing a blank on what went wrong. I am using CUDA everything looks ok from output messages during configure and generate (I think).

**Comment by HospitableHost** [comment]
I got the same problem too. How to fix it?
