### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [CMU-Perceptual-Computing-Lab/openpose#55]
I would like to point out that an identifier like “[`OPENPOSE__CORE__RENDERER_HPP`](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/de5e778c6a558d5c522cef9f1910acf774ca5d64/include/openpose/core/renderer.hpp#L1 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gyc990326** [comment]
Hi Markus,

In fact, that identifier does not has any special meaning, and is autogenerated by the IDE or other tools. It is only used to prevent that header from being processed for more than once, and it won't be in the final executables. So we needn't change it at all.

**Comment by elfring** [comment]
How do you think about to [avoid](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by gineshidalgo99** [comment]
Hi, I am interested in following the naming convention of the C++ language standard. But I have a question after reading your links. How is `OPENPOSE__CORE__RENDERER_HPP` not fitting the naming convention? The link you sent me just says not to use underscores at the beginning/end and not to repeat names used in the std library. Thanks!

**Comment by elfring** [comment]
I recommend to [reconsider the use of double underscores](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Check usage of the reserved name space") here according to the rules of the C++ programming language.

**Comment by gineshidalgo99** [comment]
@elfring OK! I will remove it within this week. Thanks! Given your better experience, may I also ask you how would you distinguish between separating folders (I was using double underscores) and separating Upper case letters (I was using single underscore)? I did not find a standard way to do it so far. Thanks!

**Comment by elfring** [comment]
I was not concerned about a name selection for folders in this use case. I am curious if some C+ identifiers (like affected include guards) will be adjusted.

**Comment by gineshidalgo99** [comment]
The include guards have been changed for the next release (1.0.0rc3) by changing `__` by `_`. I am still finishing some other small issues, and then I will commit and push everything at the same time. But it should be done by this week.

**Comment by gineshidalgo99** [comment]
@elfring Thank you for your demanding feed-back and requests! `__` were removed in our last commit (BTW we also added face).

Please, feel free to post any other naming rule not followed or recommendations you might have.

**Comment by elfring** [comment]
Did you publish corresponding changes in a separate commit?

**Comment by gineshidalgo99** [comment]
No, it was a common commit with other changes. We were quite in a hurry at that moment and did it this way, but you are completely right and we should avoid doing that. Thanks
