### ISSUE TITLE
multi_thread failed - Computer restarts

### ISSUE THREAD

**Issue by vogali** [CMU-Perceptual-Computing-Lab/openpose#553]
####  Success
./build/examples/openpose/openpose.bin --video examples/media/720p_.mp4 --write_video output/coco.avi --display 0 --face --hand --disable_multi_thread 
####  fail
./build/examples/openpose/openpose.bin --video examples/media/720p_.mp4 --write_video output/coco.avi --display 0 --face --hand

report: 
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
Starting thread(s)

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(cnpvgl903653.apj.global.corp.sap) at 11:02:25.

computer restart!

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Linux version 4.4.0-119-generic (buildd@lcy01-amd64-013) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018

**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); 
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 8.0.61
**cuDNN version**:  5.1
**CMake version** (`cmake --version` in Ubuntu): cmake version 3.5.1
**Release or Debug mode**? (by defualt: release):release
**3-D Reconstruction module added**? (by default: no):no
**GPU model** (`nvidia-smi` in Ubuntu):
Fri Apr 27 03:14:42 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:83:00.0 Off |                  N/A |
| 35%   53C    P0    41W / 180W |      0MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:84:00.0 Off |                  N/A |
| 30%   45C    P0    40W / 180W |      0MiB /  8114MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Caffe version**: Default from OpenPose, custom version, ...?
**OpenCV version**: compiled from source? 3.3.1
Compiler (`gcc --version` in Ubuntu):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
Your computer might not be enough power supply for running in the 2 GPUs at the same time. Do you have a power supply of at least 900W?

**Comment by vogali** [comment]
It’s a GPU server. I don’t know the power of power supply. But I have ran in the 2 GPUs before, use tensorflow for two programs. It did not failed. So the power supply should be enough. But I ran openpose multi-thread model, it really power off after ~10s about.

**Comment by gineshidalgo99** [comment]
It did not failed because you were using non-heavy GPU programs. OpenPose is optimized to use 100% of both GPUs all the time. It's definitively a GPU hardware issue (either not sufficient power supply or overheating), those are the only reasons why a PC will reboot.

Again: Does this one work? If so, it's your power supply that is not big enough.
./build/examples/openpose/openpose.bin --video examples/media/720p_.mp4 --write_video output/coco.avi --display 0 --face --hand --num_gpu 1

**Comment by WonJu-Bae** [comment]
(windows 10,visual studio 2015 pro)
CUDA version (cat /usr/local/cuda/version.txt in most cases): CUDA Version 8.0.61
cuDNN version: 5.1
CMake version (cmake --version in Ubuntu): cmake version 311.0
Release or Debug mode? (by defualt: release):release
3-D Reconstruction module added? (by default: no):no
GPU model : NVIDIA GeForce GTX TITAN Black
Caffe version: Default from OpenPose, custom version, ...?
OpenCV version: compiled from source? 3.3.1
--------------------------------------------------------
C:\Users\media\Desktop\openpose-1.3.0\openpose-1.3.0\build\examples\openpose\openposedemo.vcxproj

DEFINE_bool(disable_multi_thread,       true, 

A webcam is running.

but(DEFINE_bool(disable_multi_thread,       false,)  multi_thread makes computer restart

**Comment by gineshidalgo99** [comment]
@WonJu-Bae  Same issue, your power supply is not sufficient or your GPUs are overheating.

**Comment by WonJu-Bae** [comment]
Installation mode: 
CUDA version (cat /usr/local/cuda/version.txt in most cases): CUDA Version 8.0.61
cuDNN version: 5.1
CMake version (cmake --version in Ubuntu): cmake version 3.11.0
Release or Debug mode? (by defualt: release):release
3-D Reconstruction module added? (by default: no):no
GPU model
Caffe version: Default from OpenPose, custom version, ...?
OpenCV version: compiled from source? default

**Comment by WonJu-Bae** [comment]
thank you!!!! GPUs overheating haha
you so good good nice
very very sorry
-----Original Message-----
