### ISSUE TITLE
Cannot specify the compiler

### ISSUE THREAD

**Issue by martinfaucheux** [CMU-Perceptual-Computing-Lab/openpose#555]
### Issue Summary

Hi ! I have a problem in the compilation. my default gcc compiler is 6.4. However when I build openpose it says

`-- The CXX compiler identification is GNU 7.2.0`

which fails later the total installation with:

`
In file included from /usr/local/cuda-9.1/include/host_config.h:50:0,
                 from /usr/local/cuda-9.1/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda-9.1/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at cuda_compile_1_generated_math_functions.cu.o.Release.cmake:222 (message):
  Error generating
  /home/martin/other_projects/openpose/build/caffe/src/openpose_caffe-build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions.cu.o
`

I am no expert with CMake but I clearly specified the gcc-6 and g++-6 version (CMAKE_C_COMPILER & CMAKE_CXX_COMPILER).

Also, I already installed caffe (with `apt-get install caffe-cuda`) but I fail to indicate it in the cmake : I don't know where to find the caffe include file. 

### Executed Command (if any)
(I generated the makefile with cmake-gui)
`make`

### OpenPose Output (if any)
[log.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/1955580/log.txt)

### Type of Issue
Compilation/installation error

###  System information

**Operating system**: Ubuntu 17.10
**Installation mode**: CMake with cmake-gui
**CUDA version**: 9.1
**cuDNN version**: 5.1.10
**CMake version**: 3.9.1
**Release or Debug mode**? release
**3-D Reconstruction module added**? no
**GPU model**: NVIDIA Quadro M1000M
**Caffe version**: from Openpose
**OpenCV version**: from Anaconda (3.4.1)
**Compiler**: 6.4.0

Any help would be really appreciated ! thanks

**Comment by davclark** [comment]
I'm reviewing various issues as I'm trying to figure this out compiling openpose on 17.10 myself.

First off, you can see the files for caffe with `dpkg-query -L libcaffe-cuda-dev`. There, you can see that they are in the "regular place": /usr/include/caffe and /usr/lib/x86_64-linux-gnu/libcaffeproto.a. This means the build process doesn't actually require any special lib or include directories, but cmake requires you to specify these variables. I bet the build would work (if there weren't other problems) no matter what you specify for these variables.

Anyway, the bigger issue seems to be that gcc-5 is broken on ubuntu 17.10, and 6 is not supported by CUDA 8. Also, the caffe package is built against CUDA 8 (in addition to recommended by OpenPose).

Anyway, I guess the most appropriate place to figure this out is #519, which most clearly states the underlying issue.

**Comment by davclark** [comment]
Also, FWIW, I am able to successfully set the compiler in multiple ways (see #561 for details)

**Comment by hhoomn** [comment]
using the command `CC='gcc-6' CXX='g++-6' make -j`nproc`` worked for me

**Comment by DomFo** [comment]
I had the same issue on ubuntu 20.04. I followed the steps in [https://linuxize.com/post/how-to-install-gcc-on-ubuntu-20-04/](url) to choose gcc-8 via `sudo update-alternatives --config gcc`.

**Comment by monacv** [comment]
@DomFo 
```
$ sudo update-alternatives --config gcc

update-alternatives: error: no alternatives for gcc
```
