### ISSUE TITLE
Save rendered images

### ISSUE THREAD

**Issue by gxstudy** [CMU-Perceptual-Computing-Lab/openpose#56]
### Issue summary
Thanks for making the library academic available, I am wondering if there is a way to save images with the body parts locations, with or without background, simply using the demo. I see the video can be simply save as a .avi file with parts locations, but such function is not available for individual images. 
Thanks a lot.

Best,
Cindy

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by gyc990326** [comment]
Maybe you can use the write_images option?

**Comment by gineshidalgo99** [comment]
Thanks gyc990326 for answering. In addition, `--write_images` works for all the input sources (video, webcam, image_dir, ...)
