### ISSUE TITLE
Stops with error: Attempting to use an MPI routine before initializing MPI [Debian, CPU_ONLY]

### ISSUE THREAD

**Issue by sopho22** [CMU-Perceptual-Computing-Lab/openpose#560]
### Issue Summary
openpose.bin stop with:
Attempting to use an MPI routine before initializing MPI

### Executed Command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi --logging_level 0 --disable_multi_thread

### OpenPose Output (if any)
Starting pose estimation demo.
/home/sophos/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():149
/home/sophos/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():110
/home/sophos/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():16
/home/sophos/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():53
/home/sophos/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToHeatMapScaleMode():82
/home/sophos/openpose/examples/openpose/openpose.cpp:openPoseDemo():267
Configuring OpenPose wrapper. In /home/sophos/openpose/examples/openpose/openpose.cpp:openPoseDemo():270
/home/sophos/openpose/include/openpose/wrapper/wrapper.hpp:configure():435
/home/sophos/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():18
/home/sophos/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():148
/home/sophos/openpose/include/openpose/wrapper/wrapper.hpp:configure():603
/home/sophos/openpose/include/openpose/wrapper/wrapper.hpp:configure():937
Starting thread(s)
/home/sophos/openpose/include/openpose/wrapper/wrapper.hpp:configureThreadManager():1288
/home/sophos/openpose/include/openpose/wrapper/wrapper.hpp:exec():951
/home/sophos/openpose/include/openpose/thread/threadManager.hpp:exec():163
/home/sophos/openpose/include/openpose/thread/queueBase.hpp:addPusher():360
/home/sophos/openpose/include/openpose/thread/queueBase.hpp:addPusher():360
/home/sophos/openpose/include/openpose/thread/queueBase.hpp:addPusher():360
/home/sophos/openpose/include/openpose/thread/threadManager.hpp:exec():168
/home/sophos/openpose/include/openpose/thread/thread.hpp:threadFunction():182
Starting initialization on thread. In /home/sophos/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():177
Attempting to use an MPI routine before initializing MPI

### Type of Issue
- Execution error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
Debian 9.0
**Installation mode**:
CMAKE with CPU_ONLY Mode selected
**OpenCV version**: 
libopencv-dev (2.4.9.1+dfsg-1+deb8u1)
Compiler (`gcc --version` in Ubuntu):
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by gineshidalgo99** [comment]
I am sorry but I am not familiar with Debian. Try using CPU_ONLY without MKL flag (much slower, but just to debug the reason of the error). You would have to remove the build folder first

**Comment by sopho22** [comment]
Compiling without MKL flag worked but it is indeed very slow. Is there anything else I could try to find the source of error? Compilation does not throw any errors with or without MKL flag enabled. Thanks!

**Comment by gineshidalgo99** [comment]
You could try compiling and running by your own the MKL version of Caffe:
https://github.com/BVLC/caffe/tree/intel

Not sure whether it is compatible with Debian. It's much faster for CPU version compared to standard Caffe.

**Comment by sopho22** [comment]
I have now tried to build the CPU_ONLY version on a clean Ubuntu 18.04 machine but the build process failes at two locations and when manually fixing these errors, the same "Attempting to use an MPI routine before initializing MPI" error occurs. 

Seems that the CPU_ONLY version for Ubuntu is broken and should be fixed. Will probably also solve this issue on Debian.

**Comment by gineshidalgo99** [comment]
`CPU_ONLY` version works in both Ubuntu 16 and 14, which are the 2 officially supported systems for both OpenPose and Caffe. We can't try them on Debian or Ubuntu 18, we don't have the machines for that unfortunately.

**Comment by gineshidalgo99** [comment]
Oh ok! I thought it was a different error, not sure then why it was working on Ubuntu 16, my apologies.
