### ISSUE TITLE
BUILD_CAFFE ignored by cmake

### ISSUE THREAD

**Issue by davclark** [CMU-Perceptual-Computing-Lab/openpose#561]
### Issue Summary

cmake ignores the BUILD_CAFFE option. That's too bad, as caffe is now bundled by default in Ubuntu 17.04 and up. 

Moreover, I wouldn't care so much if I could get caffe to build, but I'm getting errors regarding gcc version there... (it complains about gcc > version 5 even when I specify CC=/usr/bin/gcc=5 CXX=/usr/bin/g++-5 both before cmake AND make).

### Executed Command (if any)

cmake -DCaffe_INCLUDE_DIRS=/usr/include -DCaffe_LIBS=/usr/lib/x86_64-linux-gnu/libcaffe.so -DBUILD_CAFE=OFF ..

### OpenPose Output (if any)

```
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
...

CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_CAFE
```

### Type of Issue

- Compilation/installation error
- Help wanted
- Question

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 17.10
**Installation mode**: CMake
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 9.0.176
**cuDNN version**: 7.1.3
**CMake version** (`cmake --version` in Ubuntu): 3.9.1
**Release or Debug mode**? (by defualt: release): release
**3-D Reconstruction module added**? (by default: no): no
**GPU model** (`nvidia-smi` in Ubuntu): GTX 1080 Ti
**Caffe version**: Default from OpenPose, custom version, ...? 1.0.0 (default ubuntu install), also OpenPose version does not build either
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu)
Compiler (`gcc --version` in Ubuntu): 7.2.0 (also have 5.4.1 installed)

**Comment by davclark** [comment]
Minor update, I installed CUDA 8 and CuDNN 5.1 per the automated installer, and still have the same issues. More specifically, the Caffe failing to build is the result of both requiring g++ 5 while expecting C++11, which is not supported by default in g++ 5. The build system is complex enough that I'm not clear on how to specify c++11, even given this SO post:

https://stackoverflow.com/questions/47574698/stdisnan-has-not-been-declared-with-g-5

**Comment by gineshidalgo99** [comment]
DBUILD_CAFE has a typo, that's why it's not working. So I guess it should work once it's properly typed. Let me know otherwise

**Comment by davclark** [comment]
Ack! I can't believe I missed that... the result of trying too many things in the build system, I guess. Thank you, though.

This does of course resolve the cmake variable issue. But the g++ 5 / C++11 issue remains, even when caffe is already built.

Is anyone building on 17.10? If so, what version of CUDA (/CuDNN)?

**Comment by davclark** [comment]
OK - so I think I'm not crazy, but rather Ubuntu has decided it won't support gcc 5 in 17.10 because it's too old (and it's also got broken C++11 support):

https://github.com/pytorch/pytorch/issues/5136

there are a number of solutions suggested there, the first of which is trying gcc-4.8. That also doesn't work, and others report the same. I'll work through the list of solutions tomorrow.

**Comment by davclark** [comment]
My notes here are somewhat off-topic, so I'm going to move to #519, which is the actual problem I'm contending with here.
