### ISSUE TITLE
Cmake+vs2015+can't find the file"openpose.lib"

### ISSUE THREAD

**Issue by scnu-Yhz** [CMU-Perceptual-Computing-Lab/openpose#562]
My computer configuration:
OS:Windiw7
MODE:CPU ONLY
CUDA:no
cuDNN:no
Compilation platfor：vs2015

After I make the .sln project by using the CMakeGui,I open it in vs2015,but there is some error occured :
1>x64\Release\cameraParameterReader.obj : fatal error LNK1112: Module computer type "x64" conflicts with target computer type "X86"
2>LINK : fatal error LNK1181: 无法打开输入文件“..\..\src\openpose\Release\openpose.lib”

I can't find the the file "..\..\src\openpose\Release\openpose.lib" also,I want to know whether there will be the openpose.lib file after using the CMakeList.txt?

Looking forward to your reply！
Best wishes!

**Comment by zyxcambridge** [comment]
cmake gui 
![ok](https://user-images.githubusercontent.com/1818981/53638598-ab99fa00-3c61-11e9-844e-3d746c4b2ec8.png)

**Comment by facejun** [comment]
so have you resorved it？

**Comment by facejun** [comment]
so have you resolved it?

**Comment by scnu-Yhz** [comment]
Unfortunately, I have not resolved it.It was about half year ago,I wanted to use this project.I can't resolved it,but at the same time,I find that my computer don't support the CUDA,so I did this with my friend.
       Sorry, I may not be able to help you.But,good luck to you!
       


------------------ 原始邮件 ------------------
发件人: "facejun"<notifications@github.com>;
发送时间: 2019年3月12日(星期二) 凌晨2:48
收件人: "CMU-Perceptual-Computing-Lab/openpose"<openpose@noreply.github.com>;
抄送: "杨海珍"<2950965373@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [CMU-Perceptual-Computing-Lab/openpose] Cmake+vs2015+can't findthe file"openpose.lib" (#562)




so have you resolved it?
