### ISSUE TITLE
Cmake+vs2015+can't open file "openpose.lib"

### ISSUE THREAD

**Issue by scnu-Yhz** [CMU-Perceptual-Computing-Lab/openpose#563]
My computer configuration:
OS:Windiw7
MODE:CPU ONLY
CUDA:no
cuDNN:no
Compilation platfor：vs2015

After I make the .sln project by using the CMakeGui,I open it in vs2015,but there is some error occured :
1>x64\Release\cameraParameterReader.obj : fatal error LNK1112: Module computer type "x64" conflicts with target computer type "X86"
2>LINK : fatal error LNK1181: can't open the file“....\src\openpose\Release\openpose.lib”

I can't find the the file "....\src\openpose\Release\openpose.lib" also,I want to know whether there will be the openpose.lib file after using the CMakeList.txt?

Looking forward to your reply！
Best wishes!

**Comment by aup3gj** [comment]
I face the same problem.

**Comment by facejun** [comment]
i have the same question

**Comment by AndroidUnityGit** [comment]
i have the same question

**Comment by scnu-Yhz** [comment]
I feel very sorry that I did not solve this problem in the end because I found that one of the software needs to have NVDIA g graphics card. Hope you solve it soon.



---Original---

**Comment by fhxsa** [comment]
I face the same problem! 2025.4.27
