### ISSUE TITLE
Questions about 3D data on a RGB-D camera 

### ISSUE THREAD

**Issue by is0388ik** [CMU-Perceptual-Computing-Lab/openpose#565]
I have successfully connected OpenPose through Kinect 2.0 as a webcam. I want to output a 3D keypoint data through this webcam for my future research and I am asking if there is a library/command for output a 3D data on OpenPose. Thank you.
P.S: I don't want to buy another camera for 2-camera capturing. I want only one Kinect for 3D data capturing.

**Comment by is0388ik** [comment]
I do not want to buy another camera for my future research on 3D data. Is it possible for me to collect the 3D data only by Kinect through Openpose?

**Comment by gineshidalgo99** [comment]
Several posts already mention this.

**Comment by lily0101** [comment]
@is0388ik ， how do you do that? using the Kinect as webcam, can you tell me the solution?
