### ISSUE TITLE
windows CMake error 

### ISSUE THREAD

**Issue by linye9** [CMU-Perceptual-Computing-Lab/openpose#571]
I saw CMake error shown in your openpose/doc/installation.md folder -> [OpenPose Configuration](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-configuration) :
" CUDA_SDK_ROOT_DIR-NOTFOUND" <img src="https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/media/cmake_installation/im_3.png?raw=true" alt="CMake">
Did you ignore the error and straight to next VS OpenPose Building step? 

I add value "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0" to the CUDA_TOOLKIT_ROOT_DIR, but get another error":
**Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE)** , 

and the error in the next step Building step in VS:
##### 1>------ Build started: Project: openpose, Configuration: Release x64 ------
1>  Building NVCC (Device) object src/openpose/CMakeFiles/openpose.dir/experimental/tracking/Release/openpose_generated_pyramidalLK.cu.obj
1>  CMake Error at openpose_generated_pyramidalLK.cu.obj.Release.cmake:219 (message):
1>    Error generating
1>    D:/Cmake_openPose/build/src/openpose/CMakeFiles/openpose.dir/experimental/tracking/Release/openpose_generated_pyramidalLK.cu.obj
1>
1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
2>------ Build started: Project: OpenPoseDemo, Configuration: Release x64 ------
2>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

 can anyone fix this ?
Thanks

**Comment by gineshidalgo99** [comment]
CUDA is not found (maybe not installed?) Check the installation steps for Windows and follow that order.

**Comment by zjzhengyin** [comment]
I also have this problem. Is this problem solved?

**Comment by linye9** [comment]
@zjzhengyin not yet, I gave up using this long time ago, and use tensorflow instead
