### ISSUE TITLE
Why only first 10 layers of VGG19 ?

### ISSUE THREAD

**Issue by GajjarMihir** [CMU-Perceptual-Computing-Lab/openpose#574]
Why are we using only first 10 layers of VGG19? We can use maybe a few less layers or a few more layers? I guess the reason would be that using the first 10 layers or all the 19 layers would be having almost the same accuracy. Any help would be really appreciated.

**Comment by soulslicer** [comment]
![image](https://user-images.githubusercontent.com/3193196/40319612-c9d2fdaa-5cf6-11e8-9ff6-49884d3b2e9b.png)

It is using the first 12 layers of VGG19.
