### ISSUE TITLE
A Configuration problemo occur 

### ISSUE THREAD

**Issue by GAVANXU** [CMU-Perceptual-Computing-Lab/openpose#575]
when i run the code make -j`nproc`, the error occur:
[ 12%] Performing build step for 'openpose_caffe'
[  0%] Running C++/Python protocol buffer compiler on /home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/3rdparty/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target caffeproto
[  1%] Building CXX object src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  1%] Linking CXX static library ../../lib/libcaffeproto.a
[  1%] Built target caffeproto
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_swish_layer.cu.o
/home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(16): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(52): here

/home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(16): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(52): here

/home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(44): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(52): here

/home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(16): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(52): here

/home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(44): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]" 
(52): here

4 errors detected in the compilation of "/tmp/tmpxft_00005935_00000000-7_swish_layer.cpp1.ii".
CMake Error at cuda_compile_generated_swish_layer.cu.o.cmake:266 (message):
  Error generating file
  /home/jhd/face_recognition/xjh_pytorch/3d_pose_sec/openpose/build/caffe/src/openpose_caffe-build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_swish_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:13038: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_swish_layer.cu.o' failed
make[5]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_swish_layer.cu.o] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_caffe.dir/build.make:110: recipe for target 'caffe/src/openpose_caffe-stamp/openpose_caffe-build' failed
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/openpose_caffe.dir/all' failed
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

what should i do, i use deepin 15.5,opencv 3.4.0 cmake version 3.5.1. thanks for your help.

**Comment by gineshidalgo99** [comment]
We updated Caffe, that error seems to be Caffe not properly compiled.

Could you try removing the build folder, `rm -rf 3rdparty/caffe && mkdir 3rdparty/caffe` and running the CMake installation process again?

**Comment by GAVANXU** [comment]
thank for you sucn a quick reply, i try again as your suggestion but the same error occur @gineshidalgo99

**Comment by khanhha** [comment]
I cloned the latest code of OpenPose but the problem still happens.

**Comment by hosna** [comment]
for me too

**Comment by khanhha** [comment]
it took me two days to bring up Openpose. Even I was able to build OpensePose inside an anaconda environment, it still crashed when I first run it due to a different version of Protobuf. However, when I compiled OpenPose on native python on Linux, it runs very well.
