### ISSUE TITLE
error in number_people_max parameter

### ISSUE THREAD

**Issue by chaomaer** [CMU-Perceptual-Computing-Lab/openpose#579]
Hi !
when i execute the command with parameter --number_people_max like the [tutorial](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#running-on-video) does , some errors happen.
my command is:
```
sudo ./build/examples/openpose/openpose.bin --video examples/media/video.avi  --number_people_max 6
```
and the error info is
```
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)

Error:
Index out of bounds: 0 <= index && index < mVolume

Coming from:
- /home/chaomaer/openpose/src/openpose/core/array.cpp:commonAt():467
- /home/chaomaer/openpose/src/openpose/core/array.cpp:commonAt():473
- /home/chaomaer/openpose/src/openpose/core/keepTopNPeople.cpp:keepTopPeople():82
- /home/chaomaer/openpose/include/openpose/core/wKeepTopNPeople.hpp:work():76
- /home/chaomaer/openpose/include/openpose/thread/subThread.hpp:workTWorkers():135
- /home/chaomaer/openpose/include/openpose/thread/subThreadQueueInOut.hpp:work():84
- /home/chaomaer/openpose/include/openpose/thread/thread.hpp:threadFunction():203
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Index out of bounds: 0 <= index && index < mVolume

Coming from:
- /home/chaomaer/openpose/src/openpose/core/array.cpp:commonAt():467
- /home/chaomaer/openpose/src/openpose/core/array.cpp:commonAt():473
- /home/chaomaer/openpose/src/openpose/core/keepTopNPeople.cpp:keepTopPeople():82
- /home/chaomaer/openpose/include/openpose/core/wKeepTopNPeople.hpp:work():76
- /home/chaomaer/openpose/include/openpose/thread/subThread.hpp:workTWorkers():135
- /home/chaomaer/openpose/include/openpose/thread/subThreadQueueInOut.hpp:work():84
- /home/chaomaer/openpose/include/openpose/thread/thread.hpp:threadFunction():203

Aborted (core dumped)

```
Personally, i think the number_people_max = min(real_num_person, number_people_max), but it crashes when running, can someone explain it,(if any info is needed, i will add it) thanks in advance.

### System Configuration
**Operating system** (Ubuntu_16.04):
**Installation mode**: CMake
**CUDA version** (cuda8):
**CMake version** (3.5):
**3-D Reconstruction module added**? (no):
**GPU model** (GTX 1080):
**Caffe version**: custom version
**OpenCV version**: pre-compiled `apt-get install libopencv-dev`
Compiler (5.4):

**Comment by gineshidalgo99** [comment]
I did actually fix a mini-bug about `number_people_max` 2 days ago. Are you using the latest OpenPose or an older version? Thanks

**Comment by chaomaer** [comment]
thank you for the quick reply, I reinstall the openpose using the latest version just now, it still can not work, and the error log is the same as above.
