### ISSUE TITLE
Run demo failed---Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by liugang27** [CMU-Perceptual-Computing-Lab/openpose#580]
run demo I get failed , Could you tell me how I can modify it.
./build/examples/openpose/openpose.bin --video examples/media/video.avi
dmesg
[21534.368592] traps: openpose.bin[11475] general protection ip:7f6463b075a6 sp:7ffe9e335640 error:0 in libopencv_dnn.so.3.3.0[7f64635c0000+6f5000]

My system info:
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
cmake version 3.5.1
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P2    34W /  N/A |    804MiB /  8108MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

thanks !

**Comment by liugang27** [comment]
gdb ./build/examples/openpose/openpose.bin

Thread 1 "openpose.bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff4e545a6 in google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long) () from /usr/local/lib/libopencv_dnn.so.3.3

**Comment by chaomaer** [comment]
try this 
`sudo ./build/examples/openpose/openpose.bin --video examples/media/video.avi`
