### ISSUE TITLE
only 1.6FPS with titan V +  Xeon(R) CPU E5-2678 + 32GB + cuda9.1 + cudnn7 + opencv3.4.0

### ISSUE THREAD

**Issue by WepLeo** [CMU-Perceptual-Computing-Lab/openpose#581]
OS:Ubuntu 16.04

**Comment by gineshidalgo99** [comment]
Could I know the reason and the fix? (Just for other people checking this issue). Thanks!

**Comment by WepLeo** [comment]
Sorry, I don't know how to fix it. I need time to read source code and then fix it if  I can.
I am sure that the graphics card and its driver is work well. And graphics card was in work when the openpose started
I Just found that "**no more low-speed nor out-of-memory questions**" in the tips. so I closed this issue.
I guess one reason may be the version problems of cuda and cudnn, because you told us in the faq.md.
Besides, I found that libcudart.so.8.0 was still needed even though the version of cuda is 9.1.

**Comment by gineshidalgo99** [comment]
Using a server? Servers are usually slow for the internet connection.

**Comment by WepLeo** [comment]
About 2.4FPS if I set '--display 0 ' in the command line.

**Comment by gineshidalgo99** [comment]
That's weird. Please, include the whole github issue template (command, whole hardware conf. etc), then i might be able to help further

**Comment by WepLeo** [comment]
sorry,I'm too late to reply.
System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): 
     No LSB modules are available.
     Distributor ID: Ubuntu
     Description:    Ubuntu 16.04.4 LTS
     Release:        16.04
     Codename:       xenial
**Installation mode**: 
     CMake
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
     CUDA Version 9.1.85
**cuDNN version**:
     cudnn-9.0-linux-x64-v7
**CMake version** (`cmake --version` in Ubuntu):
     cmake version 3.5.1
**Release or Debug mode**? (by defualt: release):
     release
**3-D Reconstruction module added**? (by default: no):
     no
**GPU model** (`nvidia-smi` in Ubuntu):
     TITAN V 
**Caffe version**: 
     Default from OpenPose
**OpenCV version**: 
     compiled from source   3.4.0   compiled with cuda
Compiler (`gcc --version` in Ubuntu):
     gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609


command:
./build/examples/openpose/openpose.bin --image_dir ./examples/media/ --write_images /home/wepleo/dplearning/openpose_test_image/ret  --display 0

**Comment by gineshidalgo99** [comment]
writing images might be slow depending on how big they are and where you are saving them. Could you check this section?
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed

After running it for 1000 frames (or you can alternatively choose 100 or 50 to have faster results), it will display all the speed results for any internal OpenPose function. Please post those speed metrics

**Comment by WepLeo** [comment]
## command
./build/examples/openpose/openpose.bin --image_dir /home/wepleo/dplearning/openpose_test_image_100/ --write_images /home/wepleo/dplearning/openpose_test_image/ret100  --display 0 --profile_speed 10
## speed result
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
3.802307 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():63
0.030327 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
2.989975 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():64
4.785562 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():66
84.844939 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseExtractor.hpp:work():72
1.533400 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseRenderer.hpp:work():65
19.632279 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():62
266.494654 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/filestream/wImageSaver.hpp:workConsumer():67
Real-time pose estimation demo successfully finished. Total time: 79.238396 seconds.

## image size 
(640, 480, 3) --(rows, column, channels)

I got about 16fps by the version of darknet(https://github.com/lincolnhard/openpose-darknet) with the same environment.  Including save the result without display.

**Comment by gineshidalgo99** [comment]
OpenPose is running at >10FPS: 84.844939 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseExtractor.hpp:work():72

4 FPS is because of the file saving, don't use png format or use a SSD

**Comment by WepLeo** [comment]
## 100 pictures 
### command
./build/examples/openpose/openpose.bin --image_dir /home/wepleo/dplearning/openpose_test_image/100image --write_images /home/wepleo/dplearning/openpose_test_image/ret100  --display 0 --profile_speed 100   
### speed result
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
3.444406 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():63
0.017185 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
1.770121 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():64
3.901855 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():66
73.941441 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseExtractor.hpp:work():72
1.480626 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseRenderer.hpp:work():65
19.595614 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():62
314.112943 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/filestream/wImageSaver.hpp:workConsumer():67
Real-time pose estimation demo successfully finished. Total time: 72.091062 seconds.

## 180 pictures
### command
./build/examples/openpose/openpose.bin --image_dir /home/wepleo/dplearning/openpose_test_image/180image --write_images /home/wepleo/dplearning/openpose_test_image/ret180  --display 0 --profile_speed 100
### speed result
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
3.905500 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():63
0.018172 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
1.899812 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():64
3.942061 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():66
74.215624 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseExtractor.hpp:work():72
1.654415 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/pose/wPoseRenderer.hpp:work():65
19.926192 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():62
392.692173 msec at in /home/wepleo/dplearning/openpose/openpose/include/openpose/filestream/wImageSaver.hpp:workConsumer():67
Real-time pose estimation demo successfully finished. Total time: 104.886290 seconds.

**Comment by WepLeo** [comment]
Thanks！About 11fps when I use jpg.

**Comment by shreyasrajesh** [comment]
I am facing a similar issue. My network is running quite fast however wDatumProducer.hpp:workProducer():63 seems much slower than expected and affecting the FPS as a whole. Any help regarding what the issue might be and how to solve it would be very helpful. Thank you.

![img_20180607_220322201](https://user-images.githubusercontent.com/32326244/41113395-24a93f0e-6a9f-11e8-9f15-660a8e9335bb.jpg)

**Comment by gineshidalgo99** [comment]
WorkProducer = your input (image_dir, video, webcam). This is unrelated to OpenPose, it just means that the input is or way way too big or in a really slow hard disk.

Given that wOpOutputToCvMat is also super slow, i'll assume your image is super huge. Could I know the image resolution? Also, you can disable `wOpOutputToCvMat` with `--render_pose 0` (if my memory is correct), it would save those 75ms (in case you are not saving the output image).

**Comment by gineshidalgo99** [comment]
@shreyasrajesh That's not big at all, it shouldn't take more than 10-15msec with that size. Which CPU do you have? Maybe it's just a old-slow model.

**Comment by shreyasrajesh** [comment]
I have 6 processors with 
model name: Intel(R) Xeon(R) CPU-E5-2690 v3 @ 2.60GHz.
model:63
CPU Mhz: 2596.990
Cache size: 30720
Please let me know if you need anymore information.
I am using the repository inside docker.

It is images. That is quite definitely not the issue.

**Comment by gineshidalgo99** [comment]
Pasting the timing metrics again, but with the `--disable_multi_thread` could help me know whether the CPU cores are saturated.

Other than that, I have no idea why your CPU is so slow processing normal-size images. I am not sure how to further debug it. I am not very familiar with docker, maybe the limit the number of used cores or something? (disable_multi_thread would help me to know this)

**Comment by shreyasrajesh** [comment]
@gineshidalgo99 I realised that the problem was due to the network speed. I am accessing data from another PC using a remote desktop protocol and a result I was facing reduced speeds. Sorry for the trouble and thank you very much for all the help and support.
