### ISSUE TITLE
The optimal way to get depth value(z) of the body key points with Realsense Camera

### ISSUE THREAD

**Issue by tolgasaglik** [CMU-Perceptual-Computing-Lab/openpose#582]
### Issue Summary

There are lot of people asking questions about the depth info of the nodes. I am sorry for adding another one on top of the pile. 
I use openpose with realsense SR300 camera. Rviz can display the point cloud or camera itself is capable of delivering depth information.
What would be the way to obtain the depth value or Openpose has already become capable of it?

### Type of Issue
- Help wanted
- Question

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04
**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...? Cmake
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 5.1
**CMake version** (`cmake --version` in Ubuntu):  3.5.1
**Release or Debug mode**? (by defualt: release): Release
**3-D Reconstruction module added**? (by default: no): No.
**GPU model** (`nvidia-smi` in Ubuntu): 384.111
**Caffe version**:  Default
**OpenCV version**: 3.2
Compiler (`gcc --version` in Ubuntu): Ubuntu 5.4.0-6ubuntu1~16.04.9 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
We don't control other softwares, you'll have to deploy your custom input code from `tutorial_wrapper/` to run RealSense camera depth code

**Comment by tolgasaglik** [comment]
Is there a way to extract depth info from Openpose?

**Comment by gineshidalgo99** [comment]
3D OpenPose if you have multiple synchronized cameras (check doc/3d)

**Comment by gregorsamsa183** [comment]
You can use PyOpenPose (https://github.com/FORTH-ModelBasedTracker/PyOpenPose), give the color frame as an OpenPose input and align it with the depth frame in order to get the Depth information of a particular pixel. They can also be converted into real world coordinates.

**Comment by tolgasaglik** [comment]
@gineshidalgo99 Thank you for your feedback. Unfortunately multiple sync-cams are not an option as we use a more compact 3d cam. It is easier to manage and work with. I would appreciate if you let everyone know when you come up with a generalized solution. I believe many suffer the lack of same functionality.

@gregorsamsa183  Thank you very much. I will take a look at it.

**Comment by drzraf** [comment]
I've a slightly related but different question.
openpose use a model trained on RGB-only images and although there have been impressive results, RGB-D still seems to offer performance advantage (for example https://github.com/mks0601/V2V-PoseNet_RELEASE [MIT/Torch] won HAND2017 using depth map).
Is openpose, in its current shape, able to take advantage of depth-enabled models?

**Comment by gineshidalgo99** [comment]
Instead of using multi RGB camera, you could use a single RGBD camera, run OpenPose in the RGB channel for x and y, and directly use the Depth information to obtain z, that's the option that maximizes the FPS (compared to multi-camera)

**Comment by tralala878** [comment]
@gineshidalgo99 Any guide on how to run openpose in the RGB channel?

**Comment by bokku01** [comment]
> Instead of using multi RGB camera, you could use a single RGBD camera, run OpenPose in the RGB channel for x and y, and directly use the Depth information to obtain z, that's the option that maximizes the FPS (compared to multi-camera)

Hi
I'm curious about this part too. How does openpose know which frame to extract the skeleton from? The frame was not an inputimage. thank you.
