### ISSUE TITLE
Deploy custom model

### ISSUE THREAD

**Issue by yw155** [CMU-Perceptual-Computing-Lab/openpose#583]
### Type of Issue
- Help wanted
- offering possible extensions

Hi, I would like to ask a question that if I want to use the custom model with different name, where should I modify the constraint of using fixed model name. For example, now the model name is fixed as 'pose_iter_440000.caffemodel'. Using another name will cause an error. Thanks.

**Comment by gineshidalgo99** [comment]
The easy way is to keep the same name. The right one requires several changes in the code.

You can also use `model_pose BODY_18` and call the model: `pose_iter_XXXXXX.caffemodel` under a new models/pose/body_18 folder.

**Comment by yw155** [comment]
Hi @gineshidalgo99, thanks for your suggestion. Because each time using the same name will be confused and easily make a mistake, so could you tell me where should I change in the code? Thanks.

**Comment by gineshidalgo99** [comment]
pose/poseParameters.cpp

**Comment by yw155** [comment]
@gineshidalgo99, thank you.
