### ISSUE TITLE
mkldnn_inner_product_layer.cpp:357:2: error: this ‘else’ 

### ISSUE THREAD

**Issue by MyraBaba** [CMU-Perceptual-Computing-Lab/openpose#586]
OS:  ubuntu 17
CPU only

I have below error when compiling,  any idea ? 

38%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_concat_layer.cpp.o
[ 38%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_convolution_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_eltwise_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_inner_product_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_lrn_layer.cpp.o
[ 41%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_pooling_layer.cpp.o
/home/osboxes/openpose/3rdparty/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp: In member function ‘void caffe::MKLDNNInnerProductLayer<Dtype>::InitInnerProductBwd(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’:
/home/osboxes/openpose/3rdparty/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp:357:2: error: this ‘else’ clause does not guard... [-Werror=misleading-indentation]
  else
  ^~~~
/home/osboxes/openpose/3rdparty/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp:361:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
     ipBwdData_desc.reset(new inner_product_backward_data::desc(init_bottom_md, init_weights_md, init_top_md));
     ^~~~~~~~~~~~~~

**Comment by peteruhrig** [comment]
See here:
https://github.com/intel/caffe/issues/202

**Comment by peteruhrig** [comment]
The problem is still there although it has been fixed in Intel Caffe.

**Comment by peteruhrig** [comment]
To fix, add 3 spaces at the beginning of lines 354 and 357 and 4 spaces at the beginning of lines 355 and 358.
