### ISSUE TITLE
modified : :  mkldnn_inner_product_layer.cpp:357:2: error: this ‘else’

### ISSUE THREAD

**Issue by MyraBaba** [CMU-Perceptual-Computing-Lab/openpose#587]
OS:  Ubuntu 17.10
installation mode : cmake sh script

I have below error when compiling, any idea ?

38%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_concat_layer.cpp.o
[ 38%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_convolution_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_eltwise_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_inner_product_layer.cpp.o
[ 39%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_lrn_layer.cpp.o
[ 41%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mkldnn_pooling_layer.cpp.o
/home/osboxes/openpose/3rdparty/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp: In member function ‘void caffe::MKLDNNInnerProductLayer::InitInnerProductBwd(const std::vector<caffe::Blob>&, const std::vector&, const std::vector<caffe::Blob>&)’:
/home/osboxes/openpose/3rdparty/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp:357:2: error: this ‘else’ clause does not guard... [-Werror=misleading-indentation]
else
^~~~
/home/osboxes/openpose/3rdparty/caffe/src/caffe/layers/mkldnn_inner_product_layer.cpp:361:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
ipBwdData_desc.reset(new inner_product_backward_data::desc(init_bottom_md, init_weights_md, init_top_md));
^~~~~~~~~~~~~~

**Comment by soulslicer** [comment]
Hello, Caffe MKL does not compile on Ubuntu 17 and above, only 14 and 16.

It appears there is a patch you can apply to make it work:

https://github.com/ctuning/ck-request-asplos18-caffe-intel/issues/2
