### ISSUE TITLE
Slight documentation typo in CPU speed discussion

### ISSUE THREAD

**Issue by ajdroid** [CMU-Perceptual-Computing-Lab/openpose#592]
The CPU version code says:
> The default CPU version takes ~0.2 seconds per image on Ubuntu (~50x slower than GPU) while the MKL version provides a roughly 2x speedup at ~0.4 seconds

I think this number is images/frames per second rather than seconds per image. Is that the case?

**Comment by gineshidalgo99** [comment]
Thanks for the catch! Fixed in my local doc, it'll be pushed with my next commit within the next week.
