### ISSUE TITLE
logging.cc is being linked both statically and dynamically

### ISSUE THREAD

**Issue by robertinonicolazzi** [CMU-Perceptual-Computing-Lab/openpose#593]
Hi friend, after i build openpose succesfully and when i try to run it. It show this message:

./build/examples/openpose/openpose.bin --video examples/media/video.avi 

ERROR: something wrong with flag 'logtostderr' in file 'src/logging.cc'.  One possibility: file 'src/logging.cc' is being linked both statically and dynamically into this executable.

i build glflags and glog from source in a custom location /home/rober/.local because im in a server and not have root permissons. I reinstall both twice and rebuild caffe

**Comment by robertinonicolazzi** [comment]
someone please?

**Comment by JolyZhang** [comment]
ME TOOOOO...

ERROR: something wrong with flag 'logtostderr' in file '/home/Joly/glog/src/logging.cc'.  One possibility: file '/home/Joly/glog/src/logging.cc' is being linked both statically and dynamically into this executable.

**Comment by johnxian1** [comment]
me to...
someone help.....

ERROR:something wrong with flag 'logtostderr' in file '/usr/local/glog-master/src/logging.cc'. One possibility: file '/usr/local/glog-master/src/logging.cc' is being linked both statically and dynamically into this executable.

**Comment by Wuxinxiaoshifu** [comment]
me too ....
had you handled this problem

**Comment by Wuxinxiaoshifu** [comment]
me too 
please help

**Comment by tianxiaguixin002** [comment]
me too
please help :(
