### ISSUE TITLE
runtime error on full CPU mode (Windows) - No console output

### ISSUE THREAD

**Issue by dthy2018** [CMU-Perceptual-Computing-Lab/openpose#594]
### Issue Summary

On full CPU mode, I get the error "OpenPose has stopped working" when I try to run OpenposeDemo.exe with the command : 
"OpenPoseDemo.exe --model_folder C:\Tech\OpenPose\models --render_pose 1 --net_resolution 320x320 --hand "
However, OpenPose works well when I don't add the hand detection :
"OpenPoseDemo.exe --model_folder C:\Tech\OpenPose\models --render_pose 1 --net_resolution 320x320"

The same issue happens when i add --face at the end of the line.

### Executed Command (if any)
OpenPoseDemo.exe --model_folder C:\Tech\OpenPose\models --render_pose 1 --net_resolution 320x320 --hand

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted

### Your System Configuration
**Operating system** : Windows 10 , CPU : core i-7 and 16 Go RAM
**Installation mode**: CMake, VS14 2015 
**CUDA version**: 8.0
**cuDNN version**:6.0
**CMake version**:3.11.1
**Release or Debug mode**? (by defualt: release):Release
**3-D Reconstruction module added**? (by default: no):no
**Caffe version**: Default from OpenPose
**OpenCV version**: ; 3.2.0

**Comment by gineshidalgo99** [comment]
Maybe out of memory? Which error is the command line giving you? (it will tell you the exact error)

**Comment by dthy2018** [comment]
I forgot to say that there was no error shown : when I execute the command, a window with  "OpenPoseDemo.exe has stopped working". The command line is not giving any error as you can see : 
![image](https://user-images.githubusercontent.com/39267000/40043286-5615c612-5824-11e8-98f4-20a2e7f7a296.png)

**Comment by gineshidalgo99** [comment]
I think that the error is displayed after you click to "Fermer le programme", and it would display it in the black screen right after the "Starting thread(s)" message

**Comment by dthy2018** [comment]
When I click on "Fermer le programme" there is no error message. The programme just ends. 
![image](https://user-images.githubusercontent.com/39267000/40103060-81a65abc-58ec-11e8-8c65-d2ddf0597c7b.png)
