### ISSUE TITLE
Real-time Performance 

### ISSUE THREAD

**Issue by technicalReport** [CMU-Perceptual-Computing-Lab/openpose#60]
### Issue summary
I have some question about its real time speed. I have run it with some dataset, but its performance is not  fast enough to be 'real time'. 

- Question
 I test the openpose with Tesla K80 by using the zhenduoyan.avi dataset. But it can only be up to 0.6 fps, which is much smaller than 8fps as the author mentioned in his paper. Any comments or suggestions on this point?

**Comment by gineshidalgo99** [comment]
Check https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#faq In particular, the `Q: Low speed` question. Post again if you have any further question about it (and please also post your hardware if you post again, so we can better answer). Thanks

**Comment by technicalReport** [comment]
Thanks for your kindly reply. Now I try it with the command ' ./build/examples/openpose/openpose.bin --video ../zhenduoyan.mp4 --net_resolution 320x176 --model_pose MPI_4_layers --process_real_time --num_gpu 4' , the average fps turns to be 1.6, which is still much slower than the result mentioned in the paper. 
Below is my hardware configuration: 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+=======|
|   0  Tesla K80           Off  | 0000:06:00.0     Off |                    0 |
| N/A   56C    P0    66W / 149W |   1154MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:07:00.0     Off |                    0 |
| N/A   45C    P0    77W / 149W |    956MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000:84:00.0     Off |                    0 |
| N/A   62C    P0    66W / 149W |    956MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000:85:00.0     Off |                    0 |
| N/A   48C    P0   124W / 149W |    956MiB / 11439MiB |     89%      Default |

**Comment by gineshidalgo99** [comment]
If you are sending back the output video the speed is highly conditioned by that. Try without any visual output (`--no_render_pose`) to see the real speed.
