### ISSUE TITLE
HDF5 - Caffemodel issue when running

### ISSUE THREAD

**Issue by zzzzgamer** [CMU-Perceptual-Computing-Lab/openpose#601]
![default](https://user-images.githubusercontent.com/37992017/40274656-b9c02674-5c0e-11e8-81b5-37f730014269.png)
How to solve this problem？

**Comment by gineshidalgo99** [comment]
The models seems wrong/corrupted, try deleting all *.caffemodel files in the models folder and re-downloading them.
