### ISSUE TITLE
CPU-only mode can't analyse the pose(Windows)

### ISSUE THREAD

**Issue by gjlroka** [CMU-Perceptual-Computing-Lab/openpose#602]
### Issue Summary
I select the CPU Version by set the GPU_MODE flag to CPU_ONLY in CMake GUI,and I set "num_gpu" to 0.
But on full CPU mode, I can't see the pose show on the image and can't get the keypoints in json file.
If I set "num_gpu" to -1,it will throw std::runtime_error,is it out of memory?

### OpenPose Output (if any)
![1](https://user-images.githubusercontent.com/39449446/40275230-d37ce58a-5c1c-11e8-93a6-a7eb7badc7c8.jpg)

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **General configuration**:
    - **Installation mode**: CMake,VS14 2015 (Windows);
    - **Operating system** :Windows 10
    - **Release or Debug mode**? :Release
    - Compiler : VS2015 Community

2. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):no
    
3. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** :3.7.2
    - **OpenCV version**: OpenPose default (only Windows); 

4. If **GPU mode** issue:
    - **CUDA version** :8.0
    - **cuDNN version**:5.1

5. If **CPU-only mode** issue:
    - **CPU model**:core i5 
    - Total **RAM memory** available:8G

**Comment by gineshidalgo99** [comment]
num_gpu 0 is to not use OpenPose (name kept for backcompatibility), you must follow the CPU instructions
