### ISSUE TITLE
Compiling openPose error in CPU-only mode

### ISSUE THREAD

**Issue by gqy2468** [CMU-Perceptual-Computing-Lab/openpose#605]
### Executed Command (if any)
./ubuntu/install_openpose_if_cuda8.sh

### OpenPose Output (if any)
------------------------- Compiling OpenPose -------------------------
CXX examples/tutorial_add_module/1_custom_post_processing.cpp
CXX/LD -o .build_release/examples/tutorial_add_module/1_custom_post_processing.bin
.build_release/lib/libopenpose.so: undefined reference to `cudaGetDevice'
.build_release/lib/libopenpose.so: undefined reference to `cudaSetupArgument'
.build_release/lib/libopenpose.so: undefined reference to `cudaEventCreateWithFlags'
.build_release/lib/libopenpose.so: undefined reference to `cudaMemcpyAsync'
.build_release/lib/libopenpose.so: undefined reference to `cudaConfigureCall'
.build_release/lib/libopenpose.so: undefined reference to `cudaGetErrorString'
.build_release/lib/libopenpose.so: undefined reference to `cudaStreamDestroy'
.build_release/lib/libopenpose.so: undefined reference to `__cudaRegisterFunction'
.build_release/lib/libopenpose.so: undefined reference to `cudaFree'
.build_release/lib/libopenpose.so: undefined reference to `cudaEventDestroy'
.build_release/lib/libopenpose.so: undefined reference to `cudaDeviceGetAttribute'
.build_release/lib/libopenpose.so: undefined reference to `cudaFuncGetAttributes'
.build_release/lib/libopenpose.so: undefined reference to `__cudaUnregisterFatBinary'
.build_release/lib/libopenpose.so: undefined reference to `__cudaRegisterFatBinary'
.build_release/lib/libopenpose.so: undefined reference to `cudaMalloc'
.build_release/lib/libopenpose.so: undefined reference to `__cudaRegisterVar'
.build_release/lib/libopenpose.so: undefined reference to `cudaMemset'
.build_release/lib/libopenpose.so: undefined reference to `cudaStreamSynchronize'
.build_release/lib/libopenpose.so: undefined reference to `cudaLaunch'
.build_release/lib/libopenpose.so: undefined reference to `cudaEventRecord'
collect2: error: ld returned 1 exit status
Makefile:458: recipe for target '.build_release/examples/tutorial_add_module/1_custom_post_processing.bin' failed
make: *** [.build_release/examples/tutorial_add_module/1_custom_post_processing.bin] Error 1

### Type of Issue
Compilation/installation error

### Your System Configuration
1. **General configuration**:
    - **Installation mode**: sh script
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu
    - **Release or Debug mode**? (by defualt: release): Release 
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0

2. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

3. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` 

4. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

5. If **CPU-only mode** issue:
    - **CPU model**: x86_64
    - Total **RAM memory** available: 367M

6. If **speed performance** issue:

**Comment by gineshidalgo99** [comment]
If you want CPU version don't use the script that says "if CUDA 8", follow the installation steps for CPU

**Comment by gqy2468** [comment]
But when I compile with cmake like this: "sudo cmake -G "Unix Makefiles" -DGPU_MODE=CPU_ONLY", an error occured as follow: 

```
CMake Error at src/openpose/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/guoqiya/openpose-1.3.0/src/openpose/CMakeFiles

  does not contain a CMakeLists.txt file.


CMake Error at src/openpose/CMakeLists.txt:31 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  openpose_CMakeFiles
```

**Comment by spitfire88** [comment]
"sudo cmake -G "Unix Makefiles" -DGPU_MODE=CPU_ONLY" worked for me on Ubuntu 1804. Needed libopencv-dev and caffe-cpu to be installed as dependencies.
