### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [CMU-Perceptual-Computing-Lab/openpose#61]
Would you like to [replace any double quotes](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/44398bd62293efc20b36e9b5c03d20d4149d675b/include/openpose/headers.hpp#L4 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by gineshidalgo99** [comment]
Why would it be beneficial? I want to let the compiler know that I am in that folder when using the double quotes, and that I am not looking for system or std libraries. Which advantage or conventional rule prefers double quotes over angle brackets when looking within the same library/module?

I found the answers in the Stackoverflow link you send saying that we should use double quotes for including files within my same directory.

Thanks!

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Working draft: Standard for programming language C++") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for the include syntax") for header files of your software?

**Comment by gineshidalgo99** [comment]
Sorry for my late answer, really busy with hands and Windows.

- Would you like to restrict the searched directories for header files of your software?
Yes, that is the only moment at which I use the double quotes, for any 3rd party library I use `#include <>`. So in that case, is it OK to use them?

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

**Comment by gineshidalgo99** [comment]
1. They should not, they should be only looked in that directory
2. If it is not found, I understand angle brackets will not find that either, so the answer should be no.

**Comment by elfring** [comment]
1. How would you interpret the wording “current inclusion directory” according to documentation for implementation-defined behaviour?
2. Are you aware that “the quoting inclusion method” might look at other storage locations than the default method?
  I suggest to check once more what you seem to expect for places of software libraries at the moment.

**Comment by gineshidalgo99** [comment]
OK, you are right, got your point now. I've just replaced them and commit it. Thank you for the detailed explanations of each point! I've learn a few new things about C++ and its compiler...

**Comment by elfring** [comment]
Thanks for [your adjustment of the inclusion style](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/ca7fd21c0a502b31b64e0fdd7ad6ce3a15fccc73#diff-819d0b55934484a14a5de890067194d4R92 "Usage of angle brackets around file names for include statements").

**Comment by gineshidalgo99** [comment]
Sure, feel free to let me know any other rules issue!
