### ISSUE TITLE
Add Caffe2 support

### ISSUE THREAD

**Issue by 95n** [CMU-Perceptual-Computing-Lab/openpose#610]
Caffe2 support

**Comment by gineshidalgo99** [comment]
Yes, we'd like to, but it'd require some time and effort, so it's in our (long) to-do list.

We are open to anyone that implements it in Caffe2 to email me in order to coordinate and officially adding that functionality to official OpenPose.

**Comment by jiapei100** [comment]
need Caffe2 support ... ^_^
How is the progress?

**Comment by gineshidalgo99** [comment]
So far no people interested on this task :(

**Comment by gineshidalgo99** [comment]
No people was interested, and now Caffe2 has been merged into Pytorch. Indeed, we are trying to work on a Pytorch version instead. Not sure about the expected timeline here.
