### ISSUE TITLE
stepSize in floatPtrToUCharCvMat(..)

### ISSUE THREAD

**Issue by secutron** [CMU-Perceptual-Computing-Lab/openpose#611]
##  Issue Summary

- First of all, I'd like to say thanks to all of you at 'openpose' team.
- I'm not sure but I think 'stepSize' variable below may not be assigned correctly.

```
// codes from floatPtrToUCharCvMat(..) in openCv.cpp (openpose/utility)
... 
   const auto stepSize = uCharCvMat.step; // step = cols * channels
...


// to be...
// const auto stepSize = uCharCvMat.step.buf[0]; // step = cols * channels 

```

## Type of Issue
- code smells

## System Configuration
- Operating system : Windows 10
- Installation mode: VS 2015 
- CUDA version (cat /usr/local/cuda/version.txt in most cases):cuda 8
- cuDNN version: v 5.1
- CMake version (cmake --version in Ubuntu): 3.10.0-rc5
- Release or Debug mode? (by defualt: release): Debug
- 3-D Reconstruction module added? (by default: no): No
- GPU model (nvidia-smi in Ubuntu): Nvidia Titan X
- Caffe version: 1.0 (I'm not using openpose's default)
- OpenCV: 3.4.1 (I'm not using openpose's default)

**Comment by secutron** [comment]
## console outputs
![console](https://user-images.githubusercontent.com/1733748/40460790-6948ac06-5f43-11e8-827a-66ea92be4b3c.jpg)

## quick watch status
![qwatch](https://user-images.githubusercontent.com/1733748/40460791-6976214a-5f43-11e8-8421-b22d4e56d6c8.jpg)

**Comment by gineshidalgo99** [comment]
Hi, apologies for the delay. This function has been removed for an optimized equivalent that actually doesn't require this stepSize variable. Thus, it should be now safe (and faster). Thanks.
