### ISSUE TITLE
Feature Request: Can we add the counter to count steps while movement

### ISSUE THREAD

**Issue by jaskarannagi19** [CMU-Perceptual-Computing-Lab/openpose#612]

**Comment by gineshidalgo99** [comment]
Never thought about it, but we will not add such specific functionality, we are more focused on the algorithm itself or very generic extensions rather than very specific ones.

**Comment by jaskarannagi19** [comment]
ahh snap may be I should take some look here then.

**Comment by gineshidalgo99** [comment]
(Closing this)
