### ISSUE TITLE
Output Normalizing Explanation

### ISSUE THREAD

**Issue by alirezamosh** [CMU-Perceptual-Computing-Lab/openpose#613]
In the ouput.md it is mentioned that:
1. An array `pose_keypoints_2d` containing the body part locations and detection confidence formatted as `x1,y1,c1,x2,y2,c2,...`. The coordinates `x` and `y` can be normalized to the range [0,1], [-1,1], [0, source size], [0, output size], etc., depending on the flag `keypoint_scale`, while `c` is the confidence score in the range [0,1].

Could you please explain how the normalization for [0,1] and [-1,1] is done? In the case of [0,1] is it simply division by the height/width of the frame?

Thanks in advance.

**Comment by gineshidalgo99** [comment]
Yes, with respect to the image size, (0,0) would be top-left, (1,1) bottom-right of the image.
