### ISSUE TITLE
Use too many memory when I run with CPU-only mode

### ISSUE THREAD

**Issue by gqy2468** [CMU-Perceptual-Computing-Lab/openpose#614]
### Issue Summary

Use too many memory when I run with CPU-only mode :

```
xxx@ubuntu:~$ free -mh
              total        used        free      shared  buff/cache   available
Mem:           9.7G        7.4G        1.9G        8.9M        460M        2.1G
Swap:          979M          0B        979M
```
Is there any way to reduce the memory amount we use?

### Executed Command (if any)
./.build_release/examples/openpose/openpose.bin --video examples/media/video.avi --write_json examples/output/ --display 0

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
1. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu
    - **Release or Debug mode**? (by defualt: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0

2. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

3. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default

4. **CPU-only mode** issue:
    - **CPU brand & model**: x86_64
    - Total **RAM memory** available: 10G

**Comment by gineshidalgo99** [comment]
That's expected. Memory is proportional to speed, use the speed tips to reduce memory too (while decreasing accuracy).
