### ISSUE TITLE
Confidence value larger than 1

### ISSUE THREAD

**Issue by xiaoyuliu** [CMU-Perceptual-Computing-Lab/openpose#615]
Hi, 

Thanks for the work. I test the openpose on some videos but find there is one confidence larger than 1. Is that possible? Or how does this happen? Because on your [output page](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md), I see that confidence is clearly limited to be in [0,1].

My output is like:
```
{"version":1.2,"people":[{"pose_keypoints_2d":[0,0,0,706.931,500.816,0.872227,745.116,503.734,0.897626,765.669,571.405,0.910142,771.588,624.442,0.975486,668.486,503.694,1.40701,668.722,600.821,0.931326,671.692,686.247,0.869659,733.352,627.434,0.786468,733.398,718.765,0.901205,721.697,809.779,0.889741,677.469,633.317,0.634031,689.137,718.572,0.55023,668.729,812.895,0.337298,0,0,0,0,0,0,736.279,456.528,0.992519,686.27,444.863,0.792458],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]},{"pose_keypoints_2d":[621.64,412.572,0.949555,600.989,497.959,0.865944,547.878,489.095,0.817564,530.253,601.013,0.906608,577.314,695.155,0.907035,0,0,0,0,0,0,0,0,0,559.762,692.184,0.742412,577.424,836.42,0.871279,580.272,980.569,0.825294,644.973,686.246,0.799202,648.057,809.838,0.853169,636.198,906.996,0.8078,603.915,406.593,0.874822,639.098,406.576,0.887048,583.326,412.644,0.863106,653.903,415.566,0.825439],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]}]}
```

The 5-th joint of the first person got: `668.486,503.694,1.40701`

Thanks.

**Comment by gineshidalgo99** [comment]
Most of the data should be in the range [0,1]. I need to think whether to clarify this better or to manually truncate the scores to [0,1]. I'll take some time to think about the best action out of those 2.

Reason:
The ground-truth data is [0,1], but the algorithm could learn something slightly different and have some outliers (such as this case).

I wound't be worry, it just means the algorithm is quite certain of that position being a peak (could you post the image and point where exactly that pixel is located? So I can actually have a better insight and be sure it's not a different problem. Thanks!)

**Comment by xiaoyuliu** [comment]
No problem, I put the video and the corresponding `.json` output files in this [link](https://www.dropbox.com/sh/k4gfwdzrotuq9t8/AACRRwNVFJHCM0_AIzonvYNMa?dl=0)

And you can find the value I mentioned in `39_keypoints.json`. It should be the 6th point and I guess the reason could probably be that two 6th points from two subjects are overlapped.

Thanks for your quick reply!

**Comment by gineshidalgo99** [comment]
I agree with you, it might be `mistake` of the network given the fact that both instances of the same keypoint overlap, so you can safely truncate values to [0,1]
