### ISSUE TITLE
On the hardware problem of running openpose 

### ISSUE THREAD

**Issue by zzzzgamer** [CMU-Perceptual-Computing-Lab/openpose#617]
My graphics card is GTX1050, but I can't run openpose without cuda8.0. How can I solve this problem?

**Comment by soulslicer** [comment]
Hi @zzzzgamer 

Thank you for trying openpose. I see that you are posting rather cryptic issueswith no additional information for us to help you. I suggest you follow the posting rules, rather than removing them, in order to get responses from anyone
