### ISSUE TITLE
- Execution error Check failed: error == cudaSuccess (2 vs. 0) out of memory

### ISSUE THREAD

**Issue by zhangwei147258** [CMU-Perceptual-Computing-Lab/openpose#619]
I run openpose in the nvidia tx2 board, but it always fails when some demo (path:build/examples/openpose/openpose.bin ) was runned.
In fact ,I can run caffe with cuda8.0 and cudnn6.1
ubuntu： 16.04   memory ： 8G  GPU（only one） ：GP10B

The error is folowed :

nvidia@tegra-ubuntu:/opt/openpose$ ./build/examples/openpose/openpose.bin
Starting OpenPose demo...
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
F0525 11:42:48.736145 22182 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0) out of memory
*** Check failure stack trace: ***
@ 0x7f9a68b718 google::LogMessage::Fail()
@ 0x7f9a68d614 google::LogMessage::SendToLog()
@ 0x7f9a68b290 google::LogMessage::Flush()
@ 0x7f9a68deb4 google::LogMessageFatal::~LogMessageFatal()
@ 0x7f99db71f8 caffe::SyncedMemory::mutable_gpu_data()
@ 0x7f99f0b8cc caffe::Blob<>::mutable_gpu_data()
@ 0x7f99f61ce4 caffe::CuDNNConvolutionLayer<>::Forward_gpu()
@ 0x7f99ef3868 caffe::Net<>::ForwardFromTo()
@ 0x7f9b46ebf0 op::NetCaffe::forwardPass()
@ 0x7f9b320624 op::PoseExtractorCaffe::forwardPass()
@ 0x7f9b31bdb8 op::PoseExtractor::forwardPass()
@ 0x7f9b3187d0 op::WPoseExtractor<>::work()
@ 0x7f9b4b14e8 op::Worker<>::checkAndWork()
@ 0x7f9b4ab158 op::SubThread<>::workTWorkers()
@ 0x7f9b4aba18 op::SubThreadQueueInOut<>::work()
@ 0x7f9b4acf1c op::Thread<>::threadFunction()
@ 0x7f9b4c58ec std::_Mem_fn_base<>::operator()<>()
@ 0x7f9b4c5868 _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
@ 0x7f9b4c5588 std::_Bind_simple<>::operator()()
@ 0x7f9b4c5334 std::thread::_Impl<>::_M_run()
@ 0x7f9a8df280 (unknown)
@ 0x7f9a9e6fc4 start_thread
Aborted (core dumped)
nvidia@tegra-ubuntu:/opt/openpose$

**Comment by yuanyuanli85** [comment]
It is out of memory issue.  Could you try to use small network input by setting `--net_resolution` ?
