### ISSUE TITLE
[Question] testing/using for humanoid arms

### ISSUE THREAD

**Issue by Anitkrun** [CMU-Perceptual-Computing-Lab/openpose#621]
Is it possible to use the library for arms that are human-like? 

I have tested the demo and found it to be generating paf's for a few key-points that are correct, i.e. the demo (used a mobilenet module) is detecting some joints on humanoid-arms out of the box. 

I'm sorry if this question is not according to the rules, I couldn't find any place else to ask.

**Comment by mohit-sinha** [comment]
It will work well corresponding to the extent of optical similarity of humanoid to actual humans.
By optical similarity, I mean color, texture, shape etc.

**Comment by Anitkrun** [comment]
I was able to achieve some success.
