### ISSUE TITLE
How the coefficient "scale_number" and "scale_gap" be used exactly?

### ISSUE THREAD

**Issue by rhaegal7** [CMU-Perceptual-Computing-Lab/openpose#622]
For example,
--net_resolution -1x368 --scale_number 4 --scale_gap 0.25
then what's the other 3 net_resolution for processing except for the initial scale -1x368 ?

How you process 4 outputs ?
Just average the 4 heatmaps of 4 different net_resolution?

Please help me figure this out
Thank you so much!

**Comment by gineshidalgo99** [comment]
Just average the 4 heatmaps of 4 different net_resolution? **Yes**

**Comment by rhaegal7** [comment]
Could you tell me how to calculate the  other 3 net_resolution except for the initial scale -1x368 for  "--scale_number 4 --scale_gap 0.25" ?
Thanks!

**Comment by gineshidalgo99** [comment]
I did it quite long time ago, but it is basically multiplying by the scale, e.g. 368 * 0.75, 368 * 0.5, 368 * 0.25. I remember I had to do some extra things because of the CUDA code (e.g. resize them to a size that can be divided into 16), but it was mostly just multiplying it by the scale.
