### ISSUE TITLE
2 frames per hour (!?) with CPU version in Ubuntu 18.04

### ISSUE THREAD

**Issue by peteruhrig** [CMU-Perceptual-Computing-Lab/openpose#623]
### Issue Summary
Openpose CPU version on Ubuntu 18.04 with Caffe and OpenCV provided by the default repositories and MKL directly from Intel has been working on the example video for 3.5 days now. It uses 13-18 GB of RAM but only one CPU core and produces one JSON file every 20-35 minutes. (Full setup detailed in [this Singularity recipe](https://github.com/RedHenLab/singularity_containers/blob/master/Singularity.openpose).
I'd be grateful for ideas of what to change and am happy to try it out and provide more details where necessary.

### Executed Command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --display=0 --write_json ~/pgutest_json --write_video ~/pgutest.avi

### OpenPose Output (if any)
Starting OpenPose demo...
Starting thread(s)...

### Type of Issue
- Help wanted

### Your System Configuration
1. **General configuration**:
    - **Installation mode**: cmake -DGPU_MODE=CPU_ONLY -DBUILD_CAFFE=OFF -DCaffe_INCLUDE_DIRS=/usr/include/caffe/ -DCaffe_LIBS=/usr/lib/x86_64-linux-gnu/libcaffe.so ..
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 18.04 inside a Singularity container
    - **Release or Debug mode**? (by defualt: release): I guess release?
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): gcc 7.3.0

2. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): (see no. 1)

3. **3rd-party software**:
    - **Caffe version**: caffe-cpu from Ubuntu 18.04, says "1.0.0-6"
    - **CMake version** (`cmake --version` in Ubuntu): 3.10.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu), i.e. 3.2.0

4. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

5. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel Xeon E5-2665
    - Total **RAM memory** available: 128 GB

6. If **Windows** system:
    - Portable demo or compiled library?

7. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed). 
Does this help at these low speeds? If so, I'll recompile.

**Comment by gineshidalgo99** [comment]
Default Caffe is that slow. Intel Caffe branch is the fast one and the only one we recommend for Ubuntu CPU version. Default Caffe was never implemented with CPU enhanced instruction set instructions.

**Comment by soulslicer** [comment]
Hi, I just tested your exact command on my computer with the latest MKL version, with both body and hands on my 7600K Intel with 8 cores.

I can get 0.2FPS with the default resolution, and 0.8FPS with -1x192. And I am using 8 threads. And that too with visualization enabled.

Perhaps it is an issue with the newer GCC version? Are you able to test on a computer with Ubuntu 16.04

**Comment by peteruhrig** [comment]
Thanks for your replies! I have looked at both in turn.

1. I now let openpose compile caffe instead of installing it via apt-get. This gets me to roughly 0.5 frames per minute.

2. I have now switched to the latest MKL (2018.3, released 2 days ago), but I think MKL was enabled by default, since compiling with -DUSE_MKL=ON does not change anything. Still about 0.5 frames per minute.

openpose.bin now uses up to 16 cores.

So I see a huge improvement, but still a performance so far off the reported performance that I think I'm doing something wrong...

**Comment by soulslicer** [comment]
1. Yes it is better to compile from source. Also, you should compile OP in release mode (its not by default)

2. How did you do this? We ship a specific version/branch of MKL that compiles with OP. We cannot get the later versions to compile.

**Comment by peteruhrig** [comment]
So the first thing to note is that the really bad performance was at least partially due to the very old CPU I was using first. So the 0.5 per minute improved to 5 per minute by moving to a machine with a more recent CPU ( Xeon E5-2630 v4 @ 2.20GHz and 2 x 10 instead of 2 x 8 physical cores).
Again, my simple measure is counting how many JSON files I get per minute on the example video with the `--face --hand --display=0 --write_json and --write_video` parameters.
How much does OP depend on single-thread CPU power? According to cpubenchmark.net, both machines I used are more powerful than yours, but considerably worse in single-thread performance:
https://www.cpubenchmark.net/compare/Intel-i5-7600K-vs-Intel-Xeon-E5-2630-v4-vs-Intel-Xeon-E5-2665/2919vs2758vs1439
The difference between the two servers I used can however not be explained with the Benchmarks - maybe it is the difference between AVX and AVX-2 that makes the E5-2630 v4 so much faster with OP. (https://ark.intel.com/compare/64597,92981)

ad 1.: I have now built it with cmake -DGPU_MODE=CPU_ONLY -DUSE_MKL=ON -DCMAKE_BUILD_TYPE=Release ..
But I fail to see substantial differences with the release parameter - what would you expect to be different there?

ad 2.: It turns out I have not. When I originally used the caffe-cpu included in Ubuntu 18.04, OP did not compile, complaining about a missing mkl.h, so I installed MKL and made available the right path to the build process, and it worked. I never got rid of that part, so I assumed OP would use it during the build process. Now, with letting OP build caffe, you are right of course: If I have MKL installed or not does not change a thing - OP will always used the version shipped with it. Thanks for explaining that to me!

I have now also re-built the whole thing on Ubuntu 16.04, just to test whether anything changes, but the performance appears to be comparable.

So at the moment, I'm getting better performance, but I just wanted to make sure, this is what I can get, since we may be deploying OP on a relatively large dataset. So please excuse me for asking more questions about this:

1. How did you measure your FPS? Also by counting JSON files?

2. I am using the OpenCV package available via Ubuntu. Could it improve performance to compile a version optimized for Intel/MKL processors? If so, do you happen to have a pointer to working instructions on how to do that? (My memories of building OpenCV manually are not entirely pleasant...)

3. Does OP somehow restrict processing features when built on older processors? Or will the build process be the same and it will see which processor features are available at run-time? This is relevant for me because I would be deploying OP on a heterogeneous HPC infrastructure and would have to build various containers if features are selected at compile-time.

4. Do you have any idea whether OP takes a performance hit when running on NUMA machines? Would it be better to reduce the number of threads per process, pin the process to one physical CPU and run one process per physical CPU on the same machine? (If you don't, I'll try to figure that part out with the help of our HPC support group.)

Thanks a lot!

**Comment by gineshidalgo99** [comment]
1. Check point 7 If speed performance issue from the GitHub issue template: Report OpenPose timing speed based on this link.
2. OpenCV is fine, the problem is Caffe network.
3. No, it might limit across OSs, but not across different versions of e.g. Ubuntu
4. I am not sure, I am not familiar with NUMA machines, but i'll happily like if you could post your conclusions about it here after you figure it out for other people with similar issues.

**Comment by peteruhrig** [comment]
Thanks a lot for your replies! I have now played around with the speed-profiling and can report the following preliminary results:

### 2 CPUs with 10 cores each
Calling it:
```
singularity shell openpose_6.simg
cd /localdata/src/openpose
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --display=0 --write_json ~/temp/openpose_6_performance_test --write_video ~/temp/openpose_6_performance_test.avi --profile_speed 10 > ~/openpose/output_6_performance_test.txt 2> ~/openpose/error_6_performance_test.txt
```

This just gives the full machine with both CPUs to OP. I don't know whether it uses 20 or 40 threads, but it definitely uses all CPU time on the machine.

```
7.748231 msec at in /localdata/src/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():63
0.003076 msec at in /localdata/src/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
4.369901 msec at in /localdata/src/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():64
4.101963 msec at in /localdata/src/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():66
3000.599386 msec at in /localdata/src/openpose/include/openpose/pose/wPoseExtractor.hpp:work():84
0.004011 msec at in /localdata/src/openpose/include/openpose/face/wFaceDetector.hpp:work():62
1856.039085 msec at in /localdata/src/openpose/include/openpose/face/wFaceExtractorNet.hpp:work():67
0.005013 msec at in /localdata/src/openpose/include/openpose/hand/wHandDetector.hpp:work():62
6875.737138 msec at in /localdata/src/openpose/include/openpose/hand/wHandExtractorNet.hpp:work():70
3.237818 msec at in /localdata/src/openpose/include/openpose/pose/wPoseRenderer.hpp:work():65
0.015323 msec at in /localdata/src/openpose/include/openpose/face/wFaceRenderer.hpp:work():64
0.017719 msec at in /localdata/src/openpose/include/openpose/hand/wHandRenderer.hpp:work():64
6.055612 msec at in /localdata/src/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():62
19.551245 msec at in /localdata/src/openpose/include/openpose/filestream/wPeopleJsonSaver.hpp:workConsumer():85
13.534976 msec at in /localdata/src/openpose/include/openpose/filestream/wVideoSaver.hpp:workConsumer():66
OpenPose demo successfully finished. Total time: 2711.763976 seconds.
```

### Pin to 1 CPU with 10 cores
Calling it:
```
numactl --membind=1 --cpunodebind=1 singularity shell openpose_6.simg
cd /localdata/src/openpose
export MKL_NUM_THREADS="10"
export OMP_NUM_THREADS="10"
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --display=0 --write_json ~/temp/openpose_6_performance_test_bind_1 --write_video ~/temp/openpose_6_performance_test_bind_1.avi --profile_speed 10 > ~/openpose/output_6_performance_test_bind_1.txt 2> ~/openpose/error_6_performance_test_bind_1.txt
```

This means I did not only bind it to one CPU but also limit the number of threads to 10. I'll play around a bit more to test whether this makes sense. At any rate, it only uses 50% of the machine's processing power, so we could run the same task in parallel without any significant drop in performance, I think.

```
4.536031 msec at in /localdata/src/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():63
0.002500 msec at in /localdata/src/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
3.698599 msec at in /localdata/src/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():64
3.408417 msec at in /localdata/src/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():66
2899.388392 msec at in /localdata/src/openpose/include/openpose/pose/wPoseExtractor.hpp:work():84
0.003165 msec at in /localdata/src/openpose/include/openpose/face/wFaceDetector.hpp:work():62
1550.755007 msec at in /localdata/src/openpose/include/openpose/face/wFaceExtractorNet.hpp:work():67
0.003458 msec at in /localdata/src/openpose/include/openpose/hand/wHandDetector.hpp:work():62
7311.372637 msec at in /localdata/src/openpose/include/openpose/hand/wHandExtractorNet.hpp:work():70
2.089059 msec at in /localdata/src/openpose/include/openpose/pose/wPoseRenderer.hpp:work():65
0.006794 msec at in /localdata/src/openpose/include/openpose/face/wFaceRenderer.hpp:work():64
0.008315 msec at in /localdata/src/openpose/include/openpose/hand/wHandRenderer.hpp:work():64
4.587523 msec at in /localdata/src/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():62
19.821343 msec at in /localdata/src/openpose/include/openpose/filestream/wPeopleJsonSaver.hpp:workConsumer():85
12.931855 msec at in /localdata/src/openpose/include/openpose/filestream/wVideoSaver.hpp:workConsumer():66
OpenPose demo successfully finished. Total time: 3032.747624 seconds.
```

If I translate these into FPS by using 1000/(msec value) for the individual extractors and 1000/(sum of msec values) for the overall FPS [Is that how you do it?], I get the following results:

| CPUs | FPS PoseExtractor | FPS FaceExtractor | FPS HandExtractor | FPS combined |
| ----- | ------------------ | ------------------ | ------------------- | --------------- |
| 2 CPUs (20 cores) | 0.333 | 0.539 | 0.145 | 0.08524 |
| 1 CPU (10 cores) | 0.345 | 0.645 | 0.137 | 0.08503 |

However, these speeds do not explain the difference in runtime (2711 seconds for 20 cores, 3032 seconds for 10 cores), I think. Am I reading these results correctly?

**Comment by gineshidalgo99** [comment]
OK I am sorry for the confusion, all our arguments were based on BODY-only setup. We didn't expect people to use hand-face given how slow it is and RAM it uses (as you have just verified).

You are getting about 0.33 FPS in BODY (~3sec), so the speed is comparable to our official benchmark (from the README, which specifies it is for body-only). So yeah, unfortuntately that is the fastest speed you can get right now out of the CPU version for full body-hand-face (hand-face speed dependent on how many people on the scene).

Let me know any other question.
