### ISSUE TITLE
nmsGpu and nmsCpu take time

### ISSUE THREAD

**Issue by younger-diao** [CMU-Perceptual-Computing-Lab/openpose#626]
nmsGpu and nmsCpu take above 30ms,having a little time diffference,and unable to reach the time described in the note about 2ms and 7ms. Thank you for the answer.

**Comment by gineshidalgo99** [comment]
CPU version maybe, but GPU version is 2-5 ms on my PC. You are most probably not measuring the time properly, as GPU code cannot be simply measured with a C++ timer, as those calls get send to GPU and the C++ code continues executing the code. Also, if you are using a really old GPU, maybe GPU NMS is 30ms, but then the Caffe network should take seconds.
