### ISSUE TITLE
undefined reference to :: function QTcreator / Ubuntu

### ISSUE THREAD

**Issue by Myrah76** [CMU-Perceptual-Computing-Lab/openpose#627]
Hello ,

Its been 2 days i am trying to sort out this error , i have searched everywhere and have tried all the ways to figure out but failed to compile the program .My projects name is SmartAgent where as CCOS is the library kit i am using .Error lies inside the SA_UserPreference.cpp file.... your help will be highly appreciated.Note that i am using QTcreator 5 in Ubuntu 14.04 .The error is following...

/home/sy/Projects/SmartAgent/build-SmartAgent-ccOS_V031_kit-Debug/../SmartAgent/src/SA_UserPreference.cpp:58: undefined reference to `ccos::system::HSystemInfo::getInstance()'
/home/sy/Projects/SmartAgent/build-SmartAgent-ccOS_V031_kit-Debug/../SmartAgent/src/SA_UserPreference.cpp:64: undefined reference to `ccos::system::HSystemInfo::getValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
make: *** [SmartAgent] Error 1
13:50:12: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project SmartAgent (kit: ccOS-V031-kit)
When executing step "Make"

**Comment by gineshidalgo99** [comment]
This project is not related to OpenPose at all, nor the errors.

**Comment by Myrah76** [comment]
why closed ?


Myrah Naeem
System Software Developer,Seoul,South Korea
Email : myrah.naeem76@gmail.com
C/P : 010-5042-6996

**Comment by soulslicer** [comment]
Because this has absolutely nothing to do with OpenPose.
