### ISSUE TITLE
error happened when wrapping code

### ISSUE THREAD

**Issue by sanggehouzhihoujue** [CMU-Perceptual-Computing-Lab/openpose#628]
When I wrapped the code as a class， I encountered encounter some problems.
If the PoseExtractorCaffe and initializationOnThread are created in the constructor，everthing is ok.
![image](https://user-images.githubusercontent.com/31615736/40760407-441921d2-64c9-11e8-9670-403fcb100fc6.png)
However, if the PoseExtractorCaffe is created in the constructor while initializationOnThread is created in a class method，it results in errors.
![image](https://user-images.githubusercontent.com/31615736/40760607-15167b7c-64ca-11e8-9d62-7e1b8085d5d7.png)
It seems some memory has been free before the blob share_ptr been deleted.  But I don't know why. 
Waiting for your reply, thank you.

**Comment by gineshidalgo99** [comment]
initializationOnThread must be called in the same thread where forwardPass will run, otherwise CUDA memory (in Caffe) gets messed up completely.

**Comment by sanggehouzhihoujue** [comment]
@gineshidalgo99 But the global code is called in one thread, and the thread id is always the same. What's more, the code with  PoseExtractorCaffe and initializationOnThread together in the constructor is called normally yesterday,  but it corrupts today. May be there is some error in the environment ?(No one changed the environment.)
![image](https://user-images.githubusercontent.com/31615736/40815504-89c9e1de-6579-11e8-8ad2-2ee56480ed05.png)
The code is called with root authority.
Thank you.

**Comment by gineshidalgo99** [comment]
cuDNN error (as in the last screenshot) is usually for a CUDA/cuDNN installation/environment issue, not related to OpenPose code

**Comment by sanggehouzhihoujue** [comment]
Thank you. I have solved the problem of cudnn-error(4 vs. 0). Too many instances lead to GPU memory overflow.
