### ISSUE TITLE
Out of memory.  How to check cuDNN is installed/enabled?

### ISSUE THREAD

**Issue by aerotran** [CMU-Perceptual-Computing-Lab/openpose#63]
### Issue summary
Running out of memory when running OpenPoseDemo.exe.  I saw the FAQ about checking cuDNN is installed/enabled, but I'm not sure how to do this.  I tried reinstalling Caffe and CUDA, but still run out of memory.

### Executed command (if any)
bin\OpenPoseDemo.exe --video examples/media/video.avi

### OpenPose output (if any)
F0609 15:43:06.328490 10640 syncedem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0) out of memory

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted

### Your system configuration
**Operating system**):  Windows 8.1
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):  8.0.61
**cuDNN version**: 8.0 windows7 x64 v5.1
**GPU model**:  NVIDIA GeForce GT 540M, Intel(R) HD Graphics 3000
**Caffe version**: Default from OpenPose
**OpenCV version**: Default
Compiler:  Visual Studio 2015

**Comment by gineshidalgo99** [comment]
Hardware requirements: NVIDIA graphics card with at least 1.5 GB available.

The Intel would not work, and the GT 540M only hast 1.5 GB, and the OS usually uses around 300 MB, so you cannot fit default OpenPose there.

You can try reducing the `net_resolution` as the FAQ suggest. that is your only shoot

**Comment by aerotran** [comment]
Shoot.  Okay, thanks for the response.

**Comment by skrish13** [comment]
Just in case anyone comes here looking for installing openpose without CuDNN (since your GFX card doesn't support it), please mind this point from [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#faq). It's useless if you have an older card which CuDNN doesn't support as its RAM is anyways not going to be anywhere near 12GB. 

@gineshidalgo99 am i safe in assuming the above?

**Comment by gineshidalgo99** [comment]
@skrish13 Maybe using the default configuration and a very very small `net_resolution` (start trying with 160x160 to see if its fits), it might work, but this would only work with people taking most of the image. Let me know if you try the results. Thanks!

**Comment by skrish13** [comment]
Oh, right. okay. Will do! Will be interesting to see how it works on that resolution :)

**Comment by gineshidalgo99** [comment]
Yeah, it will definitively be. Please, it'd be great if you post your required GPU (or if out-of-memory still appears) or any results you can get for other people. Thanks
