### ISSUE TITLE
Dynamic --net_resolution is not supported in MKL (CPU) and OpenCL Caffe versions

### ISSUE THREAD

**Issue by Honghe** [CMU-Perceptual-Computing-Lab/openpose#630]
### Issue Summary
Dynamic `--net_resolution` is not supported in MKL (CPU) and OpenCL Caffe versions. Please remove `-1` from `net_resolution` or use the Caffe master branch when processing images and when using your custom image reader.

### Executed Command (if any)
```
./build/examples/openpose/openpose.bin --image_dir examples/media/ --face --hand
```
### OpenPose Output (if any)
```
openpose git:(master) ✗ ./build/examples/openpose/openpose.bin --image_dir examples/media/ --face --hand
Starting OpenPose demo...

Error:
Dynamic `--net_resolution` is not supported in MKL (CPU) and OpenCL Caffe versions. Please remove `-1` from `net_resolution` or use the Caffe master branch when processing images and when using your custom image reader.

Coming from:
- /home/honhe/Downloads/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():146
- /home/honhe/Downloads/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():153
- /home/honhe/Downloads/openpose/include/openpose/wrapper/wrapper.hpp:configure():982
- /home/honhe/Downloads/openpose/examples/openpose/openpose.cpp:openPoseDemo():369
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Dynamic `--net_resolution` is not supported in MKL (CPU) and OpenCL Caffe versions. Please remove `-1` from `net_resolution` or use the Caffe master branch when processing images and when using your custom image reader.

Coming from:
- /home/honhe/Downloads/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():146
- /home/honhe/Downloads/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():153
- /home/honhe/Downloads/openpose/include/openpose/wrapper/wrapper.hpp:configure():982
- /home/honhe/Downloads/openpose/examples/openpose/openpose.cpp:openPoseDemo():369

[1]    10541 abort (core dumped)  ./build/examples/openpose/openpose.bin --image_dir examples/media/ --face 
```

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
1. **General configuration**:
    - **Installation mode**: CMake(Ubuntu)
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04.4 LTS
    - **Release or Debug mode**? (by defualt: release): release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

2. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

3. **3rd-party software**:
    - **Caffe version**:  custom Caffe master branch #8645207
    - **CMake version** (`cmake --version` in Ubuntu): cmake version 3.5.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); 

5. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    - Total **RAM memory** available: 8G

**Comment by gineshidalgo99** [comment]
You are right, it's not clear enough, I will change the error message. It means you should add this flag:
```
--net_resolution 656x368
```

**Comment by Honghe** [comment]
@gineshidalgo99 By adding `--net_resolution 656x368`, it works fine now. But what is the `-1` stand for and used for in `net_resolution`?

**Comment by gineshidalgo99** [comment]
Check doc/demo_overview.md
