### ISSUE TITLE
ubuntu14 cmake error

### ISSUE THREAD

**Issue by lmclmc** [CMU-Perceptual-Computing-Lab/openpose#631]
when i compile openpose in ubuntu14 system, there is the wrong information
The wrong information is as follows：

-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
CMake Error at src/openpose/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/lmc/Desktop/openpose/openpose/src/openpose/CMakeFiles

  does not contain a CMakeLists.txt file.

CMake Error at src/openpose/CMakeLists.txt:31 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  openpose_CMakeFiles

what should i do,
i am grateful your apply

**Comment by drzraf** [comment]
same issue (Ubuntu 18.04, cmake version 3.10.2)

**Comment by gineshidalgo99** [comment]
Fixed by adding pull request from @drzraf  . Sorry for the delayed fix.

**Comment by Harsharma2308** [comment]
I still got this error after December 14 2018 pull.

**Comment by drzraf** [comment]
Maybe this is one more directory to ignore from Cmake processing.
See the diff at #823
