### ISSUE TITLE
Does this library also work for fisheye lens camera?

### ISSUE THREAD

**Issue by KeunwooPark** [CMU-Perceptual-Computing-Lab/openpose#632]
### Issue Summary
Hi.
I'm really new to this field, and I want to know if this library works for a fisheye camera(180 degrees).
I saw publications related to this project, but it is hard for me to answer the question on my own.

Can this library find keypoints of a human hand from an image of fisheye camera?
It would be appricated if anyone can answer this question.

### Type of Issue
You might select multiple topics, delete the rest:
- Question

**Comment by yuanyuanli85** [comment]
We tried to use a fisheye camera 120 degree. Openpose is able to detect the keypoints with distortion. 

But, the best practice is to un-distort the image before sending it to openpose.

**Comment by Anitkrun** [comment]
IMO you can "un-fisheye" your images using some correction methods, which might be tedious but better than getting skewed detections.

**Comment by gineshidalgo99** [comment]
Both answers are the right answer, so closing this.
