### ISSUE TITLE
openpose from other project

### ISSUE THREAD

**Issue by mohit-sinha** [CMU-Perceptual-Computing-Lab/openpose#633]
I am using OpenPose (1.3.0) and it is running well(demo)
(I am currently working with CPU_ONLY version.)

I wish to compile other projects using OpenPose.
According to README, I tried `make install` in build folder. I still get linking errors on compilation.
(I compile using `g++ file_name.cpp`)

There are many errors like this-
`/usr/local/include/openpose/face/wFaceDetectorOpenCV.hpp:75:5: error: ‘shared_ptr’ is not a member of ‘std’
     COMPILE_TEMPLATE_DATUM(WFaceDetectorOpenCV);`

#### Apart, I also need help on building from user_code directory. There is no directory user_code in `build/examples` after `make all` in `build/`

**Comment by mohit-sinha** [comment]
It was a silly mistake. I didn't run `make all` in `/build` directory of the external project. It is working fine now.
However, I am still puzzled by the user_code issue. Kindly help if anyone has any idea.

**Comment by ehx-v1** [comment]
Didn't have it much with this particular project yet, but my guess would be that `build/example/user_code` is where the created setup puts the build results of your surrounding code. That's at least what would make most sense to me.

**Comment by gineshidalgo99** [comment]
Hi all,

Actually, `user_code` comes from the deprecated Makefile installer (which is deprecated). So unfortunately no, it won't compile anything there by default.

I'll try to make it work for that folder so quick prototypes can be easily tested without having to create a whole new project just for it. Thanks.

**Comment by ehx-v1** [comment]
> There are many errors like this- `/usr/local/include/openpose/face/wFaceDetectorOpenCV.hpp:75:5: error: 'shared_ptr’ is not a member of ‘std’ COMPILE_TEMPLATE_DATUM(WFaceDetectorOpenCV);`

By the way, to anyone else getting an error like this: Most likely, either you didn't run `make all` in `build/`, or you're using a too low C++ version. `std::shared_ptr` was added with C++11, and it's very likely this project also uses STL features added in newer versions. However, some `g++` implementations still compile with a way deprecated C++ version by default, so if you're getting "not part of `std`" errors you might want to check that.

**Comment by gineshidalgo99** [comment]
@mohit-sinha  OK, now it should work with the CMake installer. Please, let me know the results.

Instructions in the README.md, in the `Quick Start` section.
