### ISSUE TITLE
openpose-1.3.0-win64-cpu-binaries\bin\OpenPoseDemo.exe doesn't run

### ISSUE THREAD

**Issue by jbrownkramer** [CMU-Perceptual-Computing-Lab/openpose#635]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
I downloaded the CPU binaries for windows and tried the example command (bin\OpenPoseDemo.exe --video examples\media\video.avi) I got this:
![image](https://user-images.githubusercontent.com/4051645/40944090-14b0895a-6819-11e8-8c5d-dbc57d8296c8.png)

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
bin\OpenPoseDemo.exe --video examples\media\video.avi

### OpenPose Output (if any)
None

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: openpose-1.3.0-win64-cpu

2. **General configuration**:
    - **Installation mode**: Downloaded binaries
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows 10.0.17134.48 
    - **Release or Debug mode**? (by defualt: release): not sure.  Release?
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): None.  Downloaded binaries.

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

5. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

6. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

7. If **Windows** system:
    - Portable demo or compiled library?

8. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
I have just removed it. OpenPose CPU version doesn't work on version 1.3.0 until CUDA is also installed on the PC.

If you download the latest GitHub master branch and compile it following the instructions, that one would work. You can just replace the Caffe and OpenPose includes in the downloaded version so you would still have the same structure and the others DLLs already copied there.

Version 1.4.0, when released, will incorporate a CPU version that actually work in computers without CUDA.

Thanks
