### ISSUE TITLE
Error when building OpenPose. Missing 'swish_param'.

### ISSUE THREAD

**Issue by daniel-flores** [CMU-Perceptual-Computing-Lab/openpose#636]
### Issue Summary
We are trying to configure OpenPose to run on Amazon Web Services as we have seen it is possible. We are using a Ubuntu instance with a GPU GRID K520. It has Caffe, CUDA and cuDNN already installed. We have encountered the following error.

### Executed Command (if any)

`make -j`nproc` `

### OpenPose Output (if any)
[ 12%] Performing build step for 'openpose_caffe'
[  1%] Built target caffeproto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_swish_layer.cu.o
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/solvers/cuda_compile_1_generated_rmsprop_solver.cu.o
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/solvers/cuda_compile_1_generated_sgd_solver.cu.o
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_im2col.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/ubuntu/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(16): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]"
(52): here

/home/ubuntu/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(44): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]"
(52): here

/home/ubuntu/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(16): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]"
(52): here

/home/ubuntu/openpose/3rdparty/caffe/src/caffe/layers/swish_layer.cu(44): error: class "caffe::LayerParameter" has no member "swish_param"
          detected during instantiation of "void caffe::SwishLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<__nv_bool, std::allocator<__nv_bool>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=double]"
(52): here

4 errors detected in the compilation of "/tmp/tmpxft_00002727_00000000-17_swish_layer.compute_61.cpp1.ii".
CMake Error at cuda_compile_1_generated_swish_layer.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/ubuntu/openpose/build/caffe/src/openpose_caffe-build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_swish_layer.cu.o

make[5]: *** [src/caffe/CMakeFiles/caffe.dir/build.make:26280: src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_swish_layer.cu.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/Makefile2:272: src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/openpose_caffe.dir/build.make:111: caffe/src/openpose_caffe-stamp/openpose_caffe-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/openpose_caffe.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted
- Question

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** Ubuntu 
    - **Release or Debug mode**? 16.04.4 LTS
    - Compiler: 5.4.0 20160609

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): No
    - Any other custom CMake configuration with respect to the default version? (by default: no): No

4. **3rd-party software**:
    - **Caffe version**: Caffe 1
    - **CMake version** : 3.5.1
    - **OpenCV version**: 2.4.9.1+dfsg-1.5ubuntu1

**Comment by gineshidalgo99** [comment]
If you have Caffe already installed, use your custom Caffe version (check doc/installation.md). Right now you are using the one in OpenPose (3rdparty/caffe) as I see in those logs.
