### ISSUE TITLE
openpose-1.3.0-win64-gpu-binaries.zip missing model?

### ISSUE THREAD

**Issue by jbrownkramer** [CMU-Perceptual-Computing-Lab/openpose#637]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **Caffe installation errors/issues**. Check [Caffe](http://caffe.berkeleyvision.org) documentation and help for those errors.
4. **No** questions about **CUDA check failed errors**. These errors are usually fixed by re-installing CUDA, re-installing the proper cuDNN version, and re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
5. **No duplicated** posts.
6. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
7. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
8. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
I have downloaded the latest gpu windows binaries, and have run bin\OpenPoseDemo.exe --video examples\media\video.avi.  I get the following error

````
Caffe trained model file not found: models\pose/coco/pose_iter_440000.caffemodel.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():54
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():131
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():93
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\include\openpose/thread/subThread.hpp:op::SubThread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::initializationOnThread():150
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::initializationOnThread():173
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::threadFunction():203

C:\Users\jbrownkramer\Downloads\openpose-1.3.0-win64-gpu-binaries\openpose-1.3.0-win64-gpu-binaries>bin\OpenPoseDemo.exe --video examples\media\video.avi
````

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.
bin\OpenPoseDemo.exe --video examples\media\video.avi

### OpenPose Output (if any)
(see above)

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?  1.31

2. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?  Windows binaries
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows Version 10.0.17134.48
    - **Release or Debug mode**? (by defualt: release): Don't know
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...? N/A

4. **3rd-party software**:  I have some of these packages, but I don't think it should matter given that this is meant to be a stand alone demo.
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

7. If **Windows** system:
    - Portable demo or compiled library?  Portable demo

**Comment by gineshidalgo99** [comment]
Read the Instructions.txt file attached with the zip file to learn to download the models
