### ISSUE TITLE
 Website does not respond

### ISSUE THREAD

**Issue by zjzhengyin** [CMU-Perceptual-Computing-Lab/openpose#638]
When I run the getModels.bat and getCaffe3rdparty.bat ，Website does not respond.Is the site changed?
------------------------- POSE MODELS -------------------------
Body (COCO)
--2018-06-06 09:34:27--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Unknown error.
Retrying.
------------------------- Download 3rdparty Libraries -------------------------
Downloading Caffe...
----- Downloading Caffe -----
--2018-06-06 09:30:18--  http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows/caffe_2017_07_11.zip
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Unknown error.
Retrying.

**Comment by gineshidalgo99** [comment]
it is working for me right now when i click that button, so it must be at your internet end.

Try again in a few minutes / tomorrow. 

Best
