### ISSUE TITLE
Compile Error by ‘atomic’

### ISSUE THREAD

**Issue by nnn112358** [CMU-Perceptual-Computing-Lab/openpose#64]
### Issue summary
Compile Error in ./include/openpose/core/renderer.hpp
I added the following code, there is no problem.

Add Code:
```
#include <atomic> 
```
Place:
./include/openpose/core/renderer.hpp

### Executed command (if any)
$ ./install_caffe_and_openpose.sh

### OpenPose output (if any)

>------------------------- Compiling OpenPose -------------------------
CXX src/openpose/pose/poseExtractorCaffe.cpp
CXX src/openpose/pose/bodyPartConnectorCaffe.cpp
CXX src/openpose/pose/defineTemplates.cpp
CXX src/openpose/experimental/hand/handExtractor.cpp
CXX src/openpose/experimental/hand/defineTemplates.cpp
CXX src/openpose/core/netCaffe.cpp
CXX src/openpose/core/resizeAndMergeCaffe.cpp
CXX src/openpose/core/defineTemplates.cpp
CXX src/openpose/core/nmsCaffe.cpp
In file included from ./include/openpose/core/headers.hpp:18:0,
                 from src/openpose/core/defineTemplates.cpp:1:
./include/openpose/core/renderer.hpp:24:84: error: ‘atomic’ is not a member of ‘std’
         std::tuple<std::shared_ptr<float*>, std::shared_ptr<bool>, std::shared_ptr<std::atomic<unsigned int>>, std::shared_ptr<const unsigned int>> getSharedParameters();
                                                                                    ^
compilation terminated due to -Wfatal-errors.
make: *** [.build_release/src/openpose/core/defineTemplates.o]

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):Ubuntu 14.04.5 LTS
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):CUDA Version 8.0.61
**cuDNN version**:6.0
**GPU model** (`nvidia-smi`):   Driver Version: 375.66  GeForce GTX 1050 
**Caffe version**: Default from OpenPose 
**OpenCV version**: installed with `apt-get install libopencv-dev` 
Compiler (`gcc --version` on Ubuntu):gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by GeorgianaPetria** [comment]
I have the exact same issue, with the only difference that I am using my own caffe version.

**Comment by potato-cat** [comment]
I have the same issue,I don't know what is atomic.HELP!!!

**Comment by gineshidalgo99** [comment]
Hi @nnn112358, then let me clarify your message, if you add `#include <atomic>` it works fine, so there is no further problem and you can run OpenPose, right? (So i will add it as soon as possible). Thansk!

**Comment by nnn112358** [comment]
Yes, I add #include <atomic>, I can run I lastest OpenPose.

Regards.

**Comment by gineshidalgo99** [comment]
OK thanks! So it was fixed in the latest versions and issue closed.
