### ISSUE TITLE
sudo bash 3rdparty/osx/install_deps.sh fails

### ISSUE THREAD

**Issue by jbrownkramer** [CMU-Perceptual-Computing-Lab/openpose#643]
### Issue Summary
I am running on a Mac.  `sudo bash 3rdparty/osx/install_deps.sh` (suggested in the docs) causes the following error 

> Error: Running Homebrew as root is extremely dangerous and no longer supported. As Homebrew does not drop privileges on installation you would be giving all build scripts full access to your system.

I am running Homebrew 1.6.7

The installation seems to have gone just fine with `bash 3rdparty/osx/install_deps.sh`

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

**Comment by soulslicer** [comment]
You are absolutely right, we will amend the docs
