### ISSUE TITLE
Compile under Windows vs2015 x64

### ISSUE THREAD

**Issue by ehtick** [CMU-Perceptual-Computing-Lab/openpose#647]
I use Windows 10.

After using Cmake (WIndows) to create the VS 2015 x64 project i get the following error when compiling the Openpose library:

error LNK2005: "public: virtual __cdecl op::PersonIdExtractor::~PersonIdExtractor(void)" (??1PersonIdExtractor@op@@UEAA@XZ) already defined in personIdExtractor.cpp.obj

Because we already have a user interface in WPF c# tried building it with /clr option but the mutex class
can not be compiled with this option.

  #error <mutex> is not supported when compiling with /clr or /clr:pure.

Is this the only class that has this problem and is it even possible to use the /clr code with the other code?

regards

Eddy

**Comment by soulslicer** [comment]
You are trying to wrap this object inside of a class which has a mutex, which should not be possible. Try to wrap it in a shared or unique pointer

**Comment by ehtick** [comment]
and why does it not compile (link)

error LNK2005: "public: virtual __cdecl op::PersonIdExtractor::~PersonIdExtractor(void)" (??1PersonIdExtractor@op@@UEAA@XZ) already defined in personIdExtractor.cpp.obj
