### ISSUE TITLE
[Question] Real-time 3-D Performance/Latency for Experimental Usage **Windows**

### ISSUE THREAD

**Issue by n8powe** [CMU-Perceptual-Computing-Lab/openpose#649]
I am curious about the performance for real-time tracking in 3D. The hope is to use this software to track body position in real-time for an experimental setup, where body position influences the output from a projector, which then influences the body position (etc etc etc). Is latency needed for this kind of setup achievable with the current release? If so, what kind of hardware would be necessary?

I can answer further questions in case this is unclear.

**Comment by gineshidalgo99** [comment]
Only-body latency is about 200ms with a good graphic cards, latency including hands-face is was worse.

**Comment by n8powe** [comment]
That isn't too bad. Since multiple cameras are going to be used, would it be beneficial (or necessary) to have a separate graphics card for each camera? 

I also read from a previous issue thread that you are planning on adding support for foot keypoint recognition. I was curious what influence [like what order of magnitude worse] that would have on the latency? If that information is available at the present time. 

Thanks!

**Comment by vinjn** [comment]
I achieved 60ms for body-only on GTX 1060, with the darknet framework in stead:
https://github.com/jing-vision/yolo-studio/tree/master/openpose-darknet

**Comment by n8powe** [comment]
Thanks, I will definitely look into that. Looks very promising.

**Comment by gineshidalgo99** [comment]
@n8powe Note that you can get similar speed/accuracy to that Yolo version by reducing `net_resolution` to values as -1x160 or -1x80. But note that the accuracy will be much lower than the default OpenPose (which I see also happens in the Darknet version).
