### ISSUE TITLE
DEMO Execution 0xc000007b error - Windows 7 & 10

### ISSUE THREAD

**Issue by m1kanch0r** [CMU-Perceptual-Computing-Lab/openpose#65]
### Executed command (if any)
.\bin\OpenPoseDemo.exe --video examples\media\video.avi

### OpenPose output (if any)
It can not be executed

### Type of issue
- Execution error

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):WIdnwos10 64bit and Windows 7 64bit
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):v8.0
**cuDNN version**:v5.1
**GPU model** (`nvidia-smi`):GTX960 and GTX550Ti (different PC, same error)

sorry, I'm Japanese student, so please forgive me my lousy English.

**Comment by gyc990326** [comment]
Hi,

Have you tried to re-download the demo file, since the c000007b stands for bad image format.

**Comment by gineshidalgo99** [comment]
What do you mean by `It can not be executed` or `0xc000007b error`? Can you send screenshots?

Anyway, try downloading the VS solution, it works most of the cases, the portable demo fails more often.

**Comment by m1kanch0r** [comment]
@gyc990326 
I tried to re-download the demo file, but the results were unchanged.
Thank you for your reply.

**Comment by gineshidalgo99** [comment]
What do you mean by It can not be executed or 0xc000007b error? Can you send screenshots?

Anyway, try downloading the VS solution, it works most of the cases, the portable demo fails more often.

**Comment by m1kanch0r** [comment]
@gineshidalgo99 
This is screenshot of error.
It written in Japanese, "The application failed to start correctly (0xc000007b)"
Thank you for your reply.

![default](https://user-images.githubusercontent.com/13114007/27039173-22d88c36-4fc8-11e7-8a0a-f3de1241d26f.PNG)

**Comment by gineshidalgo99** [comment]
OK. I think it is a portable demo issue.
Please, try compiling OpenPose from the VS solution and let us know if it works that way. Thanks!

**Comment by m1kanch0r** [comment]
@gineshidalgo99 

OK, I'll try compiling OpenPose from the VS solution.
Thank you for carefully corresponding.

**Comment by gyc990326** [comment]
@gineshidalgo99
I googled for a while and it shows that the win7 cannot execute the program compiled with target platform "8.1", because win 8 added a bunch of new features, we can compile the demo with macro _WIN32_WINNT set to 0x0601.

Reference:
https://stackoverflow.com/questions/34706246/visual-studio-2015-change-target-platform-to-windows-7

**Comment by m1kanch0r** [comment]
@gyc990326 
You have a point, my computer is Windows7 and Windows10.
But some japanese people were able to execute it with Windows 10.

**Comment by gineshidalgo99** [comment]
@gyc990326 I did not know that, thank you.

Anyway, we only support Windows 10. For that one, the problem should be solved by using the VS solution (otherwise let me know). We will make the portable demo more compatible in the future, but meanwhile the VS solution would work.

**Comment by gyc990326** [comment]
Well I finally got the openpose demo to run on Windows 7.
Adding macro "_WIN32_WINNT=0x0601" will solve the problem.
If you want me to send you the compiled version, please tell me.

**Comment by gineshidalgo99** [comment]
@gyc990326 
Thank you for the feed-back! I first need to finish a dynamic library version, so we can do a portable demo across computers. The current VS solution would only work in the computer where it has been compiled or computers with very similar HW/SW. I might ask you for the details to make it work on W7 after we have a portable demo! Thanks!

**Comment by gineshidalgo99** [comment]
@gyc990326 When you say adding `_WIN32_WINNT=0x0601`, where and how do you add it? So I incorporate it to OpenPose now that we've just released a non-required-Caffe-installation so so much easier-to-use version? Thanks!

**Comment by gyc990326** [comment]
Oh sorry for the late reply
I added it in VS Project Settings of both projects.
It's in fact #define _WIN32_WINNT 0x0601
I don't know the exact name of this option, since we are using different language, but it should be easy to find with the help of Google.;)

**Comment by iremozkal** [comment]
Hi,
I have the same problem, too. When I execute the demo, I have an error like below. I've tried to re-download but there's no change. In fact, the file mentioned in the extension below (pose_deploy_linevec.prototxt) is actually there.
![exe hata](https://user-images.githubusercontent.com/22520332/31788177-a697a044-b516-11e7-8142-4801c63eae98.PNG)

I've also tried compiling OpenPose from the VS solution for this. I did all the steps for installation but this time I got another error that says "cannot open file OpenPose.lib"
![error](https://user-images.githubusercontent.com/22520332/31788460-723aec38-b517-11e7-86f8-5357f111a422.PNG)
For this error, I looked at an earlier comment. [(https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/53)](url) I installed Cuda after Visual Studio 2015. But I still have the same error.

Operating system Windows 10 (64bit) 
CUDA version v9.0
cuDNN version v7.0.3
Visual Studio 2015

**Comment by L05** [comment]
I am experiencing the same problem with the demo as @iremozkal. 
I get this error message when trying to run the demo:
![image](https://user-images.githubusercontent.com/3998826/32870375-83f385ba-ca30-11e7-8fc0-75904e088045.png)

I've also tried compiling OpenPose from the VS solution. I followed the [Windows installation instructions](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#windows) and I get the following errors:
![image](https://user-images.githubusercontent.com/3998826/32870359-6caa569a-ca30-11e7-9221-77e6057e81f2.png)

I've experienced the exact same problems on two different machines.
I would love to get this working.

**Operating system** Windows 10.0.15063 Build 15063
**Installation mode**: Windows
**CUDA version** 8.1
**cuDNN version**: 5.1
**GPU model**: Nvidia Geforce GTX 1060 / Nvidia Geforce GTX 1080
**Caffe version**: Default from OpenPose
**OpenCV version**: OpenPose default (only Windows)

**Comment by gineshidalgo99** [comment]
@L05  My apologies, should be fixed now.

**Comment by L05** [comment]
@gineshidalgo99 Thank you! I am now able to compile it.
