### ISSUE TITLE
USB-camera

### ISSUE THREAD

**Issue by Ai-is-light** [CMU-Perceptual-Computing-Lab/openpose#650]
@gineshidalgo99 I have a webcam of my notebook computer and have another USB-camera, but I would like the USB-camera instead of the nobtebook computer's webcam. How can I do that.
Looking forward to any answers.
Thanks

**Comment by gineshidalgo99** [comment]
Check the flag camera from the doc (or disabling the laptop camera with the shortcut all laptops has for it)
