### ISSUE TITLE
This method does not seem to exist, fails in Cmake build.

### ISSUE THREAD

**Issue by eddbrown** [CMU-Perceptual-Computing-Lab/openpose#651]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/66b02dbda39622317d600dd4fa2cbba0f02e51cf/cmake/Cuda.cmake#L305

**Comment by soulslicer** [comment]
Are you testing on a MAC with a NVIDIA GPU?

**Comment by soulslicer** [comment]
The next release should support OpenCL too so you should be able to test that

**Comment by CarlosRDomin** [comment]
Sorry to reopen this issue, just wanted to say I've been successful in installing GPU-based OpenPose in OSX 10.13.6 with CUDA 9.2, cuDNN 7.2, a compiled-from-source GPU build of Caffe (from master) and finally OpenPose through cmake and GPU support activated. I'd be happy to provide additional details if anyone's interested or testing on OSX (I'm a PhD at CMU as well 👍).

As for this particular problem, I simply commented out that line (wasn't relevant for CUDA 9.2 anyways) and everything worked :)

PS: It runs at 7.5fps on a Titan Xp (eGPU setup).
