### ISSUE TITLE
The error occured when compiling the latest openpose code on macOS

### ISSUE THREAD

**Issue by gqy2468** [CMU-Perceptual-Computing-Lab/openpose#654]
### Issue Summary

```
/.../openpose-master/src/openpose/3d/poseTriangulation.cpp:360:62: error: no member named 'accumulate' in namespace 'std'
                    const auto reprojectionErrorTotal = std::accumulate(
                                                        ~~~~~^
1 warning and 1 error generated.
make[5]: *** [src/openpose/CMakeFiles/openpose.dir/3d/poseTriangulation.cpp.o] Error 1
```

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`lsb_release -a` in Ubuntu): macOS (MacBook Pro 2017)
    - **Release or Debug mode**? (by defualt: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): clang

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

5. If **GPU mode** issue: 

6. If **CPU-only mode** issue:
    - **CPU brand & model**: i5
    - Total **RAM memory** available: 8G

7. If **Windows** system:

8. If **speed performance** issue:

**Comment by soulslicer** [comment]
Sorry its a weird bug. Can you try to add `#include <algorithm>` to the top of that file and try to compile it.

https://stackoverflow.com/questions/32614922/os-x-clang-wont-use-c11-headers

**Comment by gqy2468** [comment]
Thanks! It's fixed.

**Comment by gineshidalgo99** [comment]
Thanks! Fixed in the latest commit from today.
