### ISSUE TITLE
Problems with compilation by the VS2015

### ISSUE THREAD

**Issue by zjzhengyin** [CMU-Perceptual-Computing-Lab/openpose#656]
When I opened the OpenPose.sln and compiled openpose after the Cmake，I found these problems：
1、C2039	"accumulate": Not a member of "std" 
2、Error LNK1181  Unable to open input file "..\..\src\openpose\Release\openpose.lib"
（I was so confused with that and surf the Internet ，but there is no answer）

**Comment by zjzhengyin** [comment]
I found the accumulate whose header file is in numeric，but when I add header file numeric ，there are other problems：
1、 C2612	Illegal suffixes in the list of base/member initializers“'template<'”
2、C1004	Unexpected end of file found 
3、"extern template" canont  class "op::SubThreadQueueIn<std::shared_ptr<std::vector<op::Datum, std::allocator<op::Datum>>>, std::shared_ptr<op::Worker<std::shared_ptr<std::vector<op::Datum, std::allocator<op::Datum>>>>>, op::Queue<std::shared_ptr<std::vector<op::Datum, std::allocator<op::Datum>>>, std::queue<std::shared_ptr<std::vector<op::Datum, std::allocator<op::Datum>>>, std::deque<std::shared_ptr<std::vector<op::Datum, std::allocator<op::Datum>>>, std::allocator<std::shared_ptr<std::vector<op::Datum, std::allocator<op::Datum>>>>>>>>" 	openpose	e:\project\github\openpose-master\include\openpose\thread\subThreadQueueIn.hpp

**Comment by soulslicer** [comment]
Is anyone else having this issue?

**Comment by shaikster101** [comment]
Yes, same issue here. Is VS also giving a project out of date warning before compiling?

**Comment by crrobert427427** [comment]
I also encounter same issue in VS2015 and win10.
Opened the OpenPose.sln and compiled openpose after the Cmake.

Error LNK1181 Unable to open input file "....\src\openpose\Release\openpose.lib"

**Comment by shaikster101** [comment]
So the older version compiles no problem, so the problem is with the new code

**Comment by gineshidalgo99** [comment]
Hi all (@shaikster101 @crrobert427427  @zjzhengyin ). This issue has been solved in the latest version (at least on my Win10-VS2015 PC), after I fixed the std::accumulate issue.

If it still fail to your, please, post the whole output/error log, including which lines are crashing. Thanks.
