### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by MJUSER** [CMU-Perceptual-Computing-Lab/openpose#658]
_Made my config , generation well.
also Build done succesfully.
Later i ,_

### **Run through**
./build/examples/openpose/openpose.bin --image_dir examples/media/
### **System config**
mj@mj-Inspiron-3543:~/Desktop/test/openpose$ nvidia-smi
Thu Jun 21 11:22:24 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 820M        Off  | 00000000:08:00.0 N/A |                  N/A |
| N/A   48C    P0    N/A /  N/A |    223MiB /  1985MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
mj@mj-Inspiron-3543:~/Desktop/test/openpose$ 
**### error got like**
mj@mj-Inspiron-3543:~/Desktop/test/openpose$ ./build/examples/openpose/openpose.bin --image_dir examples/media/
Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
F0621 11:19:25.470058  3839 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7fb8d372f5cd  google::LogMessage::Fail()
    @     0x7fb8d3731433  google::LogMessage::SendToLog()
    @     0x7fb8d372f15b  google::LogMessage::Flush()
    @     0x7fb8d3731e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb8d3231aab  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7fb8d3126f4c  caffe::Net<>::Init()
    @     0x7fb8d312a020  caffe::Net<>::Net()
    @     0x7fb8d4fb95a7  op::NetCaffe::initializationOnThread()
    @     0x7fb8d4f3f74e  op::addCaffeNetOnThread()
    @     0x7fb8d4f4006e  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fb8d4f4cb2e  op::PoseExtractorNet::initializationOnThread()
    @     0x7fb8d4f3b6df  op::PoseExtractor::initializationOnThread()
    @     0x7fb8d4f36fa1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fb8d5073b4c  op::SubThread<>::initializationOnThread()
    @     0x7fb8d5075d5b  op::Thread<>::initializationOnThread()
    @     0x7fb8d5075fad  op::Thread<>::threadFunction()
    @     0x7fb8d508ecc7  std::_Mem_fn_base<>::operator()<>()
    @     0x7fb8d508ec5b  _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7fb8d508ea0c  std::_Bind_simple<>::operator()()
    @     0x7fb8d508e7dc  std::thread::_Impl<>::_M_run()
    @     0x7fb8d4614c80  (unknown)
    @     0x7fb8d3d666ba  start_thread
    @     0x7fb8d408341d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
This is a CUDA/cuDNN error, unrelated with OpenPose. Check online for help for those.

**Comment by MJUSER** [comment]
Is there any other way to fix this?
Its for my project purpose?

**Comment by gineshidalgo99** [comment]
Yes there should be, but again, it's unrelated to openpose

**Comment by MJUSER** [comment]
Alast i hve done my work. Implemented cpu version.
succesfully. Tanks for the work.
