### ISSUE TITLE
Model (body_25/pose_iter_585000.caffemodel) can not download

### ISSUE THREAD

**Issue by rockzhan** [CMU-Perceptual-Computing-Lab/openpose#659]
New Body Model:
> http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_585000.caffemodel

Download link failed.

**Comment by gineshidalgo99** [comment]
Fixed, thanks! It was an issue in the *.sh file. Still, official documentation asks to use CMake. The *.sh file is not updated.

**Comment by tmanh** [comment]
I cannot download the models. I can't even access the webpage. It's likely the the server is down.

**Comment by 1blackghost** [comment]
Server down same issue
