### ISSUE TITLE
python Error

### ISSUE THREAD

**Issue by diaodiaozhuye** [CMU-Perceptual-Computing-Lab/openpose#660]
### Posting rules
1. run sudo python ./build/examples/tutorial_python/1_extract_pose.py 

### Issue Summary

Error:
Prototxt file not found: /usr/local/python/openpose/../../../models/pose/coco/pose_deploy_linevec.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /usr/rep/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():51
- /usr/rep/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():131
- /usr/rep/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /usr/rep/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():93
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Prototxt file not found: /usr/local/python/openpose/../../../models/pose/coco/pose_deploy_linevec.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /usr/rep/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():51
- /usr/rep/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():131
- /usr/rep/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /usr/rep/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():93

**Comment by soulslicer** [comment]
Hello,

As per the instructions here:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/python_module.md

You need to navigate to the path and then run it. So

```
cd build/examples/tutorial_python;
python 1_extract_pose.py
```

**Comment by gineshidalgo99** [comment]
The new instructions are more clear about this. Thanks for the feed-back.

**Comment by Zzoey** [comment]
@diaodiaozhuye did you fix this issue ? If yes, can you please help? I am trying to use this https://github.com/yysijie/st-gcn and I face the same error.

**Comment by soulslicer** [comment]
Are you using Windows as well? What error do you face?
