### ISSUE TITLE
How to build python API

### ISSUE THREAD

**Issue by iwonnor** [CMU-Perceptual-Computing-Lab/openpose#662]
I modified this:
  ./CMakeLists.txt:option(BUILD_PYTHON "Build OpenPose python." ON)
 
but  no python API is build.

**Comment by soulslicer** [comment]
Can you post your cmake and build process in to a pastebin?

**Comment by iwonnor** [comment]
I'm using  ./ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.1.sh   and  no change to this file.

**Comment by gineshidalgo99** [comment]
The *.sh file is not related to CMake. you must install OpenPose with the CMake instructions to enable Python module.
