### ISSUE TITLE
How to train my data?

### ISSUE THREAD

**Issue by ZhongXiaoFang** [CMU-Perceptual-Computing-Lab/openpose#664]
Hello, first of all,thank you for good job. Now I have a problem. I want to train openPose use my data.
But I don't know how to annotate my data. I  look COCO‘s keyPoints data is annotated like this:
###  {"segmentation": [[63.18,107.68,69.41,74.75,71.19,42.71,86.32,20.47,94.33,9.79,119.24,6.23,137.04,9.79,157.51,27.59,161.07,43.6,155.73,56.06,163.74,64.07,163.74,66.74,158.4,77.42,154.84,88.99,145.94,100.56,159.29,97,177.09,107.68,192.22,130.81,200.22,149.5,207.34,132.59,198.44,124.58,188.66,107.68,184.21,92.55,185.99,77.42,192.22,74.75,202.89,78.31,215.35,94.33,221.58,109.46,221.58,131.7,226.92,152.17,215.35,181.54,206.45,194,179.76,185.1,192.22,223.36,197.56,272.31,199.33,290.99,192.22,291.88,168.19,289.21,140.6,299.89,108.57,312.35,100.56,301.67,75.64,290.1,70.3,290.1,64.07,273.2,71.19,255.4,71.19,242.94,68.52,226.03,80.09,213.57,72.97,203.78,57.84,203.78,41.82,203.78,39.16,187.77,38.27,161.96,42.71,143.27,54.28,123.69]],"num_keypoints": 12,"area": 36807.29445,"iscrowd": 0,  ### "keypoints": [157,62,2,153,50,2,144,50,2,0,0,0,109,58,2,166,112,2,64,131,2,198,174,2,52,203,2,208,122,2,107,211,2,176,273,2,108,281,2,0,0,0,0,0,0,0,0,0,0,0,0],"image_id": 84241,"bbox": [38.27,6.23,188.65,306.12],"category_id": 1,"id": 471845}

Now, I want to know  whether  the "segmentation" of annotation is  necessary when I train openPose using  my own data ? If I remove the “segmentation” of annotation and just keep "keypoints", it will get what results?   
    thanks !

**Comment by adel6666** [comment]
same problem for me. Thanks
