### ISSUE TITLE
configuration step in mac os

### ISSUE THREAD

**Issue by ggrrll** [CMU-Perceptual-Computing-Lab/openpose#665]
Hi, 

thanks for the great tool  – it seems very promising.

Could you please help me understand the [configuration step](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-configuration), for _mac os_? 
where is/how should I use the GUI?

Thanks for your help

**Comment by ggrrll** [comment]
Problem solved with:

`brew cask install cmake`

ps: maybe other ppl mind find it useful to read it directly in the doc

**Comment by SreehariRamMohan** [comment]
@ggrrll after we installed cmake how do we launch the GUI to pop up so we can configure?
