### ISSUE TITLE
About 3D real-time multi-person keypoint detection

### ISSUE THREAD

**Issue by DongJT1996** [CMU-Perceptual-Computing-Lab/openpose#669]
Hi,

I find that there is some thing about the 3D real-time multi-person keypoint detection, as shown below:
![image](https://user-images.githubusercontent.com/25705996/41849822-f3c3f158-78b4-11e8-8417-b6995a452c8b.png)

But, i just find 3D reconstruction for only 1 person from ![here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/3d_reconstruction_module.md)

I just want to know whether there is something about 3D multi-person keypoint detection that i didn't find? 
thank you

**Comment by gineshidalgo99** [comment]
Hi.

You are right, right now 3-D is only for single person. I have fixed it in the doc for the next commit.

Multi-person 3D will take some time (months), as it requires some kind of person re-association between frames.
