### ISSUE TITLE
Inconsistent keypoint detection with caffe_rtpose

### ISSUE THREAD

**Issue by xiaoyong** [CMU-Perceptual-Computing-Lab/openpose#67]
Hi @gineshidalgo99 , thanks for this great repository!

I'm trying to figure out the consistency (difference) between caffe_rtpose and openpose. The first difference I noticed is the image preprocessing (imresize) step. Then I modified the imresize code so that they are identical. Given the same input image, I got the same heatmap and PAF output (so far so good:-). However, the final output joints are slightly different. See the example below:

```text
# caffe_rtpose
"joints":[0,0,0,430.011,235.606,0.871526,460.024,237.635,0.767007,483.023,268.706,0.825832,465.984,281.766,0.445015,398.014,231.633,0.797925,365.989,252.723,0.748569,388.029,270.727,0.250657,437.01,300.789,0.663318,428.016,348.924,0.739353,426.986,366.035,0.0734525,404.038,294.806,0.675424,392.002,338.936,0.7262,380.024,366.029,0.0513162,0,0,0,0,0,0,449.003,218.607,0.786961,420.028,215.598,0.902283]
# openpose
"body_parts":[0,0,0,430.011,234.967,0.871526,460.024,236.991,0.767007,483.023,267.978,0.825832,465.984,281.003,0.445015,398.014,231.005,0.797925,365.989,252.038,0.748569,388.029,269.993,0.250657,437.01,299.974,0.663318,428.016,347.979,0.739353,426.986,365.043,0.0734525,404.038,294.007,0.675424,392.002,338.017,0.7262,380.024,365.037,0.0513162,0,0,0,0,0,0,449.003,218.015,0.786961,420.028,215.014,0.902283]
```

Score and x-axis of each joint are identical, while y-axis are slightly different (~0.5 offset). I'd like to know where the difference resides and why.

**Comment by xiaoyong** [comment]
I have confirmed that the subtle difference is due to different calculation way of scale factors. And the openpose way is more reasonable. Now I'm happy to adopt openpose instead of caffe_rtpose in my project :-)

**Comment by gineshidalgo99** [comment]
Thanks for confirming!
I wanted to be sure there was no mistake in the current method before answering, but we basically changed the scaling because it was not keeping the aspect ratio on rt_pose.

**Comment by xiaoyong** [comment]
If I understand correctly, the scaling scheme of caffe_rtpose and OpenPose are:

* caffe_rtpose: InputScale -> DisplayScale -> NetworkScale for image scaling and its reversed order for joint scaling. Aspect ratio is kept from InputScale to DisplayScale, while may be broken from DisplayScale to NetworkScale. 
* OpenPose: InputScale -> NetworkScale for image scaling and reversed order for joint scaling. Aspect ratio is kept.

Indeed the inconsistency comes from broken aspect ratio of caffe_rtpose.

**Comment by gineshidalgo99** [comment]
Exactly, you are right.
However, thanks to your answer I actually found a small error in the multiscale scenario (if `num_scales` > 1). It has been fixed now.
(If you use `num_scales 1` the result should be the same)
