### ISSUE TITLE
Compile Error in poseTriangulation.cpp file

### ISSUE THREAD

**Issue by shydow** [CMU-Perceptual-Computing-Lab/openpose#678]
detail info:

/home/hongrong/workspace/openpose/src/openpose/3d/poseTriangulation.cpp: In function ‘void op::reconstructArrayThread(op::Array<float>*, const std::vector<op::Array<float> >&, const std::vector<cv::Mat>&, const std::vector<op::Point<int> >&, int)’:
/home/hongrong/workspace/openpose/src/openpose/3d/poseTriangulation.cpp:360:62: error: ‘accumulate’ is not a member of ‘std’
                     const auto reprojectionErrorTotal = std::accumulate(
                                                              ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.

**Comment by gineshidalgo99** [comment]
Hi, that error should be fixed in the latest version. Please, try the latest version and let us know if it still doesn't work. THanks
