### ISSUE TITLE
How to only detect keypoints of hands on the win10 by the VS15 

### ISSUE THREAD

**Issue by zjzhengyin** [CMU-Perceptual-Computing-Lab/openpose#682]

**Comment by zjzhengyin** [comment]
In the installation instructions, I only found detecting keypoints of hands in ubuntu。

**Comment by gineshidalgo99** [comment]
check doc/quick_start.md

**Comment by zjzhengyin** [comment]
Sorry, I read the OpenPose - Quick Start. What I want to say is that it can be changed in the program so that only the hand can be detected, not the body and face.




------------------ 原始邮件 ------------------
发件人: "Gines"<notifications@github.com>;
发送时间: 2018年6月27日(星期三) 晚上10:33
收件人: "CMU-Perceptual-Computing-Lab/openpose"<openpose@noreply.github.com>;
抄送: "很有意思"<635973976@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CMU-Perceptual-Computing-Lab/openpose] How to only detectkeypoints of hands on the win10 by the VS15 (#682)




check doc/quick_start.md

**Comment by gineshidalgo99** [comment]
Hand requires body, that's why it's always enabled
