### ISSUE TITLE
OpenposeDemo on Webcam crashing 

### ISSUE THREAD

**Issue by shaikster101** [CMU-Perceptual-Computing-Lab/openpose#683]
### Issue Summary
I first installed and compiled the library after which I run the webcam demo, howeve it crashes after "Starting thread(s)". 
The video and Image demos work perfectly

### Executed Command 
build\x64\Release\OpenPoseDemo.exe --logging_level 0 --disable_multi_thread

### OpenPose Output 
C:\Users\hshaik\Desktop\Re-Search\openpose-master>build\x64\Release\OpenPoseDemo.exe --logging_level 0 --disable_multi_thread
Starting OpenPose demo...
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():154
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducerType():114
Desired webcam resolution 1280x720 could not being set. Final resolution: 612x460 in C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\producer\webcamReader.cpp:op::WebcamReader::WebcamReader():31
Auto-detecting camera index... Detected and opened camera 0.
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToPoseModel():16
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToScaleMode():57
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToHeatMapScaleMode():86
C:\Users\hshaik\Desktop\Re-Search\openpose-master\examples\openpose\openpose.cpp:openPoseDemo():290
Configuring OpenPose wrapper... In C:\Users\hshaik\Desktop\Re-Search\openpose-master\examples\openpose\openpose.cpp:openPoseDemo():293
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::configure():443
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSecurityChecks():19
C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\wrapper\wrapperAuxiliary.cpp:op::wrapperConfigureSecurityChecks():160
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::configure():615
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::configure():1065
Starting thread(s)...
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::configureThreadManager():1459
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::exec():1079
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::exec():163
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > >::addPusher():360
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > >::addPusher():360
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > >::addPusher():360
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/queueBase.hpp:op::QueueBase<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > >::addPusher():360
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::exec():168
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::threadFunction():182
Starting initialization on thread. In C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():177
Finished initialization on thread. In C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():191
Starting initialization on thread. In C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\pose\poseGpuRenderer.cpp:op::PoseGpuRenderer::initializationOnThread():48
Finished initialization on thread. In C:\Users\hshaik\Desktop\Re-Search\openpose-master\src\openpose\pose\poseGpuRenderer.cpp:op::PoseGpuRenderer::initializationOnThread():55
C:\Users\hshaik\Desktop\Re-Search\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<cl

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
Webcam Demo Crashes before starting.

### Your System Configuration

1. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`lsb_release -a` in Ubuntu): Windows 10
    - **Release or Debug mode**? (by defualt: release): Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows):  VS 2015 Enterprise with Update 3 build

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): No
    - Any other custom CMake configuration with respect to the default version? (by default: no): No

4. **3rd-party software**:
    - **Caffe version**: Default from openPose
    - **CMake version** (`cmake --version` in Ubuntu):3.12.0
    - **OpenCV version**: OpenPose Default

5. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):8.0
    - **cuDNN version**:5.1
    - **GPU model** (`nvidia-smi` in Ubuntu): Nvidia Titan X

7. If **Windows** system: Compiled Library

**Comment by gineshidalgo99** [comment]
From your output, I don't see any error. What do you mean by it crashes? could you also attach screenshot?

**Comment by shaikster101** [comment]
So i narrowed it down to missing and inaccessible PDB files. I ran a clean build as a admin to get past this issue but the webcam demo is still stopping after the "starting thread(s) message. I got the following output from VS after clean build and running as admin. Any feedback is much appreciated.

'OpenPoseDemo.exe' (Win32): Unloaded 'C:\Windows\System32\frapsv64.dll'
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\msyuv.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\nvcuda.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\nvfatbinaryLoader.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\OpenCL.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\IntelOpenCLProfiler.dll'. Module was built without symbols.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\Intelopencl64_2_1.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files (x86)\Common Files\Intel\OpenCL2.1\bin\x64\Intelocl64.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files (x86)\Common Files\Intel\OpenCL2.1\bin\x64\task_executor64_2_1.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files (x86)\Common Files\Intel\OpenCL2.1\bin\x64\cpu_device64_2_1.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\intelopencl64.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files (x86)\Common Files\Intel\OpenCL\bin\x64\Intelocl64.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files (x86)\Common Files\Intel\OpenCL\bin\x64\task_executor64.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Program Files (x86)\Common Files\Intel\OpenCL\bin\x64\cpu_device64.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\igdrcl64.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. Symbols loaded.
'OpenPoseDemo.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'OpenPoseDemo.exe' (Win32): Unloaded 'C:\Windows\System32\igdrcl64.dll'
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\nvopencl.dll'. Cannot find or open the PDB file.
'OpenPoseDemo.exe' (Win32): Loaded 'C:\Windows\System32\nvptxJitCompiler.dll'. Cannot find or open the PDB file.

**Comment by gineshidalgo99** [comment]
I see Win32 in your output, so you are running 32-bit version. OpenPose is not compatible at 32bit

**Comment by jackrex** [comment]
use mac have same error, os version Mojave

**Comment by Naveennavik** [comment]
This is the output when i run using cmnd: OpenPoseDemo.exe --video (I couldnt understand what the error.this is present inside present directory opencv_videoio_ffmpeg420_64.dll
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\videoio_registry.cpp (187) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (353) cv::impl::getPluginCandidates Found 2 plugin(s) for FFMPEG
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (172) cv::impl::DynamicLib::libraryLoad load D:\Drive Analytics\openpose-master\build\x64\Debug\opencv_videoio_ffmpeg420_64.dll => OK
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (233) cv::impl::PluginBackend::PluginBackend Video I/O: loaded plugin 'FFmpeg OpenCV Video I/O plugin'
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
Prototxt file not found: models\pose/body_25/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():58
- D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():94
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():106
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():102
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
- D:\Drive Analytics\openpose-master\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::initializationOnThread():57
- D:\Drive Analytics\openpose-master\include\openpose/thread/worker.hpp:op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::initializationOnThreadNoException():77

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Prototxt file not found: models\pose/body_25/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():58
- D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():94
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():106
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():102
- D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
- D:\Drive Analytics\openpose-master\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::initializationOnThread():57
- D:\Drive Analytics\openpose-master\include\openpose/thread/worker.hpp:op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > >::initializationOnThreadNoException():77
- [All threads closed and control returned to main thread]
- D:\Drive Analytics\openpose-master\src\openpose\utilities\errorAndLog.cpp:op::checkWorkerErrors():280
- D:\Drive Analytics\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::stop():243
- D:\Drive Analytics\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > > > >::exec():202
- D:\Drive Analytics\openpose-master\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
[ INFO:2] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (178) cv::impl::DynamicLib::libraryRelease unload D:\Drive Analytics\openpose-master\build\x64\Debug\opencv_videoio_ffmpeg420_64.dll

**Comment by vincenzomarotta** [comment]
> This is the output when i run using cmnd: OpenPoseDemo.exe --video (I couldnt understand what the error.this is present inside present directory opencv_videoio_ffmpeg420_64.dll Starting OpenPose demo... Configuring OpenPose... Starting thread(s)... [ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\videoio_registry.cpp (187) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940) [ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (353) cv::impl::getPluginCandidates Found 2 plugin(s) for FFMPEG [ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (172) cv::impl::DynamicLib::libraryLoad load D:\Drive Analytics\openpose-master\build\x64\Debug\opencv_videoio_ffmpeg420_64.dll => OK [ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (233) cv::impl::PluginBackend::PluginBackend Video I/O: loaded plugin 'FFmpeg OpenCV Video I/O plugin' Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
> 
> Error: Prototxt file not found: models\pose/body_25/pose_deploy.prototxt. Possible causes: 1. Not downloading the OpenPose trained models. 2. Not running OpenPose from the same directory where the `model` folder is located. 3. Using paths with spaces.
> 
> Coming from:
> 
> * D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():58
> * D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():94
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():106
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():102
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
> * D:\Drive Analytics\openpose-master\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > >::initializationOnThread():57
> * D:\Drive Analytics\openpose-master\include\openpose/thread/worker.hpp:op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > >::initializationOnThreadNoException():77
> 
> Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:
> 
> Prototxt file not found: models\pose/body_25/pose_deploy.prototxt. Possible causes: 1. Not downloading the OpenPose trained models. 2. Not running OpenPose from the same directory where the `model` folder is located. 3. Using paths with spaces.
> 
> Coming from:
> 
> * D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():58
> * D:\Drive Analytics\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():94
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():106
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():102
> * D:\Drive Analytics\openpose-master\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
> * D:\Drive Analytics\openpose-master\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > >::initializationOnThread():57
> * D:\Drive Analytics\openpose-master\include\openpose/thread/worker.hpp:op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > >::initializationOnThreadNoException():77
> * [All threads closed and control returned to main thread]
> * D:\Drive Analytics\openpose-master\src\openpose\utilities\errorAndLog.cpp:op::checkWorkerErrors():280
> * D:\Drive Analytics\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > > > > > >::stop():243
> * D:\Drive Analytics\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > > >,class op::Queue<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::queue<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::deque<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::allocator<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > > > > > >::exec():202
> * D:\Drive Analytics\openpose-master\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > >,class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr,class std::allocator<class std::shared_ptr > > > > > >::exec():424
>   [ INFO:2] global C:\build\master_winpack-build-win64-vc15\opencv\modules\videoio\src\backend_plugin.cpp (178) cv::impl::DynamicLib::libraryRelease unload D:\Drive Analytics\openpose-master\build\x64\Debug\opencv_videoio_ffmpeg420_64.dll

Hi, did you find a solution?
