### ISSUE TITLE
Quick Start Issues : MAC 

### ISSUE THREAD

**Issue by Eyshika** [CMU-Perceptual-Computing-Lab/openpose#684]
Installed Openpose successfully using thread . [https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/677](url) and Installation guidance: [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation](url) for mac.

Openpose building is successfully done too.
Checked desired folder (i.e. examples/media ) exist too.

### Issue Summary

> dyld: Library not loaded: @rpath/libopencv_shape.3.1.dylib
>   Referenced from: /Users/eyshika.agarwal/openpose/./build/examples/openpose/openpose.bin
>   Reason: image not found
> Abort trap: 6

### Executed Command (if any)
command : `./build/examples/openpose/openpose.bin`  for webcam (as given in doc for Quick start)
command: `./build/examples/openpose/openpose.bin --video examples/media/video.avi` for video 

### Type of Issue
- Execution error
- Help wanted

### Your System Configuration
1. **OpenPose version**: Latest GitHub code 

2. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (MAC); 

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

4. **3rd-party software**:
    - **Caffe version**:  custom version, as introduced in the issue [https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/677](url)
    - **OpenCV version**: 3.4.1

**Comment by Eyshika** [comment]
@gineshidalgo99 : It would be great if you can hep in solving this.

**Comment by gineshidalgo99** [comment]
You are having and OpenCV issue, not OpenPose one:
```
dyld: Library not loaded: @rpath/libopencv_shape.3.1.dylib
```
You might look for help in OpenCV forums. We can't also debug 3rd-party libraries issues. Thanks.

**Comment by Eyshika** [comment]
@gineshidalgo99 

I got the Opencv issue resolved, but I still have Openpose errors while I am using it on Images on videos. I works fine on webcam but now it's for images/videos

Here is the error:

> ./build/examples/openpose/openpose.bin --image_dir examples/media/ --face --hand
Starting OpenPose demo...

Error:
The default dynamic `--net_resolution` is not supported in MKL (CPU Caffe) and OpenCL Caffe versions. Please, use a static `net_resolution` (recommended `--net_resolution 656x368`) or use the Caffe CUDA master branch when processing images and/or when using your custom image reader.

Coming from:
- /Users/eyshika.agarwal/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():157
- /Users/eyshika.agarwal/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():164
- /Users/eyshika.agarwal/openpose/include/openpose/wrapper/wrapper.hpp:configure():1056
- /Users/eyshika.agarwal/openpose/examples/openpose/openpose.cpp:openPoseDemo():372
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: 
Error:
The default dynamic `--net_resolution` is not supported in MKL (CPU Caffe) and OpenCL Caffe versions. Please, use a static `net_resolution` (recommended `--net_resolution 656x368`) or use the Caffe CUDA master branch when processing images and/or when using your custom image reader.

Coming from:
- /Users/eyshika.agarwal/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():157
- /Users/eyshika.agarwal/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSecurityChecks():164
- /Users/eyshika.agarwal/openpose/include/openpose/wrapper/wrapper.hpp:configure():1056
- /Users/eyshika.agarwal/openpose/examples/openpose/openpose.cpp:openPoseDemo():372

**Comment by gineshidalgo99** [comment]
As the error clearly indicates, use --net_resolution 656x368

**Comment by Eyshika** [comment]
@gineshidalgo99 but I am using default images and videos provided by this code, so I am supposing it would be provided according to code requirement.

Also why does it need only specific resolution of image , it means I cant run on my images of different sizes

**Comment by gineshidalgo99** [comment]
The default code is for CUDA version (Mac doesn't have Nvidia graphic cards so it can't run there).

About different sizes, yes it will run, just slightly slower. That's a problem of Caffe CPU version, that has a memory leak when using different sizes, we can't do much until they fix it.

**Comment by gineshidalgo99** [comment]
@Eyshika Hi again, @soulslicer commented me that in Mac Caffe version this memory leak issue does not happen, it's mainly for Ubuntu MKL version. So I have removed this error throwing for Mac. Please, download the latest version and try that one, it should work fine. Thanks!
