### ISSUE TITLE
A single input file is required for a non-link phase when an outputfile is specified

### ISSUE THREAD

**Issue by Gjain234** [CMU-Perceptual-Computing-Lab/openpose#697]
### Issue Summary
When I try to make the openpose files, I get a bunch of the same error on terminal that looks like this for multiple files:

[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMake Error at cuda_compile_1_generated_math_functions.cu.o.Release.cmake:219 (message):
  Error generating
  /home/il/software/openpose/build/caffe/src/openpose_caffe-build/src/caffe/CMakeFiles/cuda_compile_1.dir/util/./cuda_compile_1_generated_math_functions.cu.o

I don't know what this means and have not found anything online about the input file for non-link phase. The make process was working earlier before I properly set the cudnn path. However in that situation openpose wouldn't run because it ran out of memory. 

### Executed Command (if any)
make -j`nproc`

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**: Ubuntu
    - **Installation mode**: Manual CMake (Ubuntu)
    - **Operating system** Ubuntu 16.04
    - Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): added lines suggested in https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/486 by sam fowler.

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose 
    - **CMake version**: 3.11.0
    - **OpenCV version**: 3.3.1

5. If **GPU mode** issue: 
    - **CUDA version** : 8.0.61
    - **cuDNN version**: 5.1.10
    - **GPU model** : Quadro K2200

**Comment by Gjain234** [comment]
So based on what I’ve checked, the quadro k2200 has a computing capability of 3.0 which should be good for cudnn.

**Comment by gineshidalgo99** [comment]
OK, I don't have that GPU so I can't test it myself, but I'd look into running some basic Caffe example to make sure cuDNN is running with Caffe (Caffe has a bigger community so it should be easier to debug). After that is working, OpenPose doesn't directly use cuDNN, but its internal Caffe does.

**Comment by Gjain234** [comment]
Thank you! I had edited some code earlier trying to fix an error with a REMOVE_ITEM function in the caffe CMakeLists.txt needing to take in a list. When I got rid of that edit everything seemed to work out. I will add my GPU and its processing speed to the excel spreadsheet.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back.
