### ISSUE TITLE
compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by andiefromhk** [CMU-Perceptual-Computing-Lab/openpose#698]
I have attempted to build the Openpose source code on AWS p3.2xlarge instance with AWS Deep Learning AMI https://aws.amazon.com/marketplace/pp/B077GCH38C?qid=1530671113739&sr=0-2&ref_=srh_res_product_title
Hardware:
vCPU 8
memory 61GB
Nvidia Tesla V100 

The OS was Ubuntu 16.04 with almost all the prerequisites preinstalled:
CUDA 9
cuDNN - not sure which ver.
OpenCV - latest on github
Caffe - not sure coz both are preinstalled
cmake 3.5.1

Before the make command to build openpose, I configured the build and lib dir of OpenCV and Caffe in cmake as follows OpenCV build dir : /usr/local/include/opencv/
OpenCV lib dir:
/usr/local/include/

Caffe build dir:
/usr/local/include/

Caffe lib dir :
/usr/local/include/caffe2lib_GPU.so

The main error message I got is this:

**nvcc fatal   : Unsupported gpu architecture 'compute_70'**

Do I need to pick another GPU instead to get it compiled and run?

Is there any possibility of something wrong in the step before the build? 

Which AWS EC2 instance can really run Openpose? Is p2.xlarge with only 4 CPU cores enough for this? Any report is appreciated.

The whole error message is here btw. 

> src/openpose/CMakeFiles/openpose.dir/build.make:63: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/hand/openpose_generated_renderHand.cu.o'
> failed make[2]: *
> [src/openpose/CMakeFiles/openpose.dir/hand/openpose_generated_renderHand.cu.o]
> Error 1 make[2]: * Waiting for unfinished jobs.... nvcc fatal :
> Unsupported gpu architecture 'compute_70' CMake Error at
> openpose_generated_bodyPartConnectorBase.cu.o.cmake:207 (message):
> Error generating
> /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/pose/./openpose_generated_bodyPartConnectorBase.cu.o
> 
> nvcc fatal : Unsupported gpu architecture 'compute_70'
> src/openpose/CMakeFiles/openpose.dir/build.make:77: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_bodyPartConnectorBase.cu.o'
> failed make[2]: ***
> [src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_bodyPartConnectorBase.cu.o]
> Error 1 CMake Error at openpose_generated_maximumBase.cu.o.cmake:207
> (message): Error generating
> /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_maximumBase.cu.o
> 
> src/openpose/CMakeFiles/openpose.dir/build.make:98: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_maximumBase.cu.o'
> failed make[2]: ***
> [src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_maximumBase.cu.o]
> Error 1 nvcc fatal : Unsupported gpu architecture 'compute_70' CMake
> Error at openpose_generated_renderPose.cu.o.cmake:207 (message): Error
> generating
> /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/pose/./openpose_generated_renderPose.cu.o
> 
> nvcc fatal : Unsupported gpu architecture 'compute_70' CMake Error at
> openpose_generated_renderFace.cu.o.cmake:207 (message): Error
> generating
> /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/face/./openpose_generated_renderFace.cu.o
> 
> src/openpose/CMakeFiles/openpose.dir/build.make:84: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_renderPose.cu.o'
> failed make[2]: ***
> [src/openpose/CMakeFiles/openpose.dir/pose/openpose_generated_renderPose.cu.o]
> Error 1 nvcc fatal : Unsupported gpu architecture 'compute_70' CMake
> Error at openpose_generated_resizeAndMergeBase.cu.o.cmake:207
> (message): Error generating
> /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/net/./openpose_generated_resizeAndMergeBase.cu.o
> 
> src/openpose/CMakeFiles/openpose.dir/build.make:70: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/face/openpose_generated_renderFace.cu.o'
> failed make[2]: *
> [src/openpose/CMakeFiles/openpose.dir/face/openpose_generated_renderFace.cu.o]
> Error 1 src/openpose/CMakeFiles/openpose.dir/build.make:112: recipe
> for target
> 'src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o'
> failed make[2]: *
> [src/openpose/CMakeFiles/openpose.dir/net/openpose_generated_resizeAndMergeBase.cu.o]
> Error 1 nvcc fatal : Unsupported gpu architecture 'compute_70' CMake
> Error at openpose_generated_pyramidalLK.cu.o.cmake:207 (message):
> Error generating
> /home/ubuntu/openpose/build/src/openpose/CMakeFiles/openpose.dir/tracking/./openpose_generated_pyramidalLK.cu.o
> 
> src/openpose/CMakeFiles/openpose.dir/build.make:91: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/tracking/openpose_generated_pyramidalLK.cu.o'
> failed make[2]: *
> [src/openpose/CMakeFiles/openpose.dir/tracking/openpose_generated_pyramidalLK.cu.o]
> Error 1 CMakeFiles/Makefile2:179: recipe for target
> 'src/openpose/CMakeFiles/openpose.dir/all' failed make[1]: *
> [src/openpose/CMakeFiles/openpose.dir/all] Error 2 make[1]: ***
> Waiting for unfinished jobs.... [ 8%] Building CXX object
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/bvhSaver.cpp.o
> Scanning dependencies of target openpose_gpu Scanning dependencies of
> target openpose_thread [ 8%] Building NVCC (Device) object
> src/openpose/hand/CMakeFiles/openpose_hand.dir/openpose_hand_generated_renderHand.cu.o
> [ 9%] Building NVCC (Device) object
> src/openpose/face/CMakeFiles/openpose_face.dir/openpose_face_generated_renderFace.cu.o
> Scanning dependencies of target openpose_calibration [ 9%] Building
> CXX object
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/cocoJsonSaver.cpp.o
> [ 9%] Building CXX object
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/defineTemplates.cpp.o
> [ 10%] Building CXX object
> src/openpose/thread/CMakeFiles/openpose_thread.dir/defineTemplates.cpp.o
> [ 11%] Building CXX object
> src/openpose/calibration/CMakeFiles/openpose_calibration.dir/cameraParameterEstimation.cpp.o
> [ 11%] Building CXX object
> src/openpose/calibration/CMakeFiles/openpose_calibration.dir/gridPatternFunctions.cpp.o
> nvcc fatal : Unsupported gpu architecture 'compute_70' CMake Error at
> openpose_hand_generated_renderHand.cu.o.cmake:207 (message): Error
> generating
> /home/ubuntu/openpose/build/src/openpose/hand/CMakeFiles/openpose_hand.dir//./openpose_hand_generated_renderHand.cu.o
> 
> nvcc fatal : Unsupported gpu architecture 'compute_70' CMake Error at
> openpose_face_generated_renderFace.cu.o.cmake:207 (message): Error
> generating
> /home/ubuntu/openpose/build/src/openpose/face/CMakeFiles/openpose_face.dir//./openpose_face_generated_renderFace.cu.o
> 
> src/openpose/hand/CMakeFiles/openpose_hand.dir/build.make:63: recipe
> for target
> 'src/openpose/hand/CMakeFiles/openpose_hand.dir/openpose_hand_generated_renderHand.cu.o'
> failed make[2]: *
> [src/openpose/hand/CMakeFiles/openpose_hand.dir/openpose_hand_generated_renderHand.cu.o]
> Error 1 CMakeFiles/Makefile2:344: recipe for target
> 'src/openpose/hand/CMakeFiles/openpose_hand.dir/all' failed make[1]: *
> [src/openpose/hand/CMakeFiles/openpose_hand.dir/all] Error 2
> 
> src/openpose/face/CMakeFiles/openpose_face.dir/build.make:63: recipe
> for target
> 'src/openpose/face/CMakeFiles/openpose_face.dir/openpose_face_generated_renderFace.cu.o'
> failed make[2]: *
> [src/openpose/face/CMakeFiles/openpose_face.dir/openpose_face_generated_renderFace.cu.o]
> Error 1 CMakeFiles/Makefile2:456: recipe for target
> 'src/openpose/face/CMakeFiles/openpose_face.dir/all' failed make[1]:
> [src/openpose/face/CMakeFiles/openpose_face.dir/all] Error 2 [ 12%]
> Building CXX object
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/fileSaver.cpp.o
> [ 12%] Building CXX object
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/fileStream.cpp.o
> [ 12%] Building CXX object
> src/openpose/gpu/CMakeFiles/openpose_gpu.dir/cuda.cpp.o In file
> included from
> /home/ubuntu/openpose/include/openpose/filestream/headers.hpp:9:0,
> from
> /home/ubuntu/openpose/src/openpose/filestream/defineTemplates.cpp:1:
> /home/ubuntu/openpose/include/openpose/filestream/fileStream.hpp:54:32:
> error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope =
> {CV_IMWRITE_JPEG_QUALITY, 100, CV_IMWRITE_PNG_COMPRESSION, 9}); ^
> compilation terminated due to -Wfatal-errors.
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/build.make:110:
> recipe for target
> 'src/openpose/filestream/CMakeFiles/openpose_filestream.dir/defineTemplates.cpp.o'
> failed make[2]:
> [src/openpose/filestream/CMakeFiles/openpose_filestream.dir/defineTemplates.cpp.o]
> Error 1 make[2]: Waiting for unfinished jobs.... [ 13%] Building CXX
> object src/openpose/gpu/CMakeFiles/openpose_gpu.dir/gpu.cpp.o In file
> included from
> /home/ubuntu/openpose/src/openpose/filestream/fileStream.cpp:7:0:
> /home/ubuntu/openpose/include/openpose/filestream/fileStream.hpp:54:32:
> error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope =
> {CV_IMWRITE_JPEG_QUALITY, 100, CV_IMWRITE_PNG_COMPRESSION, 9}); ^
> compilation terminated due to -Wfatal-errors.
> src/openpose/filestream/CMakeFiles/openpose_filestream.dir/build.make:158:
> recipe for target
> 'src/openpose/filestream/CMakeFiles/openpose_filestream.dir/fileStream.cpp.o'
> failed make[2]:
> [src/openpose/filestream/CMakeFiles/openpose_filestream.dir/fileStream.cpp.o]
> Error 1 [ 13%] Building CXX object
> src/openpose/gpu/CMakeFiles/openpose_gpu.dir/opencl.cpp.o
> CMakeFiles/Makefile2:234: recipe for target
> 'src/openpose/filestream/CMakeFiles/openpose_filestream.dir/all'
> failed make[1]:
> [src/openpose/filestream/CMakeFiles/openpose_filestream.dir/all] Error
> 2 In file included from
> /home/ubuntu/openpose/src/openpose/calibration/cameraParameterEstimation.cpp:11:0:
> /home/ubuntu/openpose/include/openpose/filestream/fileStream.hpp:54:32:
> error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope =
> {CV_IMWRITE_JPEG_QUALITY, 100, CV_IMWRITE_PNG_COMPRESSION, 9}); ^
> compilation terminated due to -Wfatal-errors.
> src/openpose/calibration/CMakeFiles/openpose_calibration.dir/build.make:62:
> recipe for target
> 'src/openpose/calibration/CMakeFiles/openpose_calibration.dir/cameraParameterEstimation.cpp.o'
> failed make[2]:
> [src/openpose/calibration/CMakeFiles/openpose_calibration.dir/cameraParameterEstimation.cpp.o]
> Error 1 make[2]: Waiting for unfinished jobs....
> /home/ubuntu/openpose/src/openpose/calibration/gridPatternFunctions.cpp:
> In function ‘void
> op::improveCornersPositionsAtSubPixelLevel(std::vector >&, const
> cv::Mat&)’:
> /home/ubuntu/openpose/src/openpose/calibration/gridPatternFunctions.cpp:22:52:
> error: ‘CV_TERMCRIT_EPS’ was not declared in this scope
> cv::TermCriteria{ CV_TERMCRIT_EPS+CV_TERMCRIT_ITER, 1000, 1e-9 }); ^
> compilation terminated due to -Wfatal-errors.
> src/openpose/calibration/CMakeFiles/openpose_calibration.dir/build.make:86:
> recipe for target
> 'src/openpose/calibration/CMakeFiles/openpose_calibration.dir/gridPatternFunctions.cpp.o'
> failed make[2]:
> [src/openpose/calibration/CMakeFiles/openpose_calibration.dir/gridPatternFunctions.cpp.o]
> Error 1 CMakeFiles/Makefile2:511: recipe for target
> 'src/openpose/calibration/CMakeFiles/openpose_calibration.dir/all'
> failed make[1]: *
> [src/openpose/calibration/CMakeFiles/openpose_calibration.dir/all]
> Error 2 [ 13%] Linking CXX shared library libopenpose_gpu.so [ 13%]
> Built target openpose_gpu [ 13%] Linking CXX shared library
> libopenpose_thread.so [ 13%] Built target openpose_thread
> Makefile:127: recipe for target 'all' failed make: *** [all] Error 2

**Comment by soulslicer** [comment]
Can you try to install it with OpenPose building the required dependencies for you first? That way the OpenCV and Caffe errors can be eliminated. Also, you are trying to build against Caffe2, but OpenPose uses Caffe.

**Comment by andiefromhk** [comment]
Sorry, I can't get it. What is the required dependencies in my case? 
Is it more preferable to start from AMI without any prerequisite preinstalled to get openpose run?

Also, the error seems to mean that is a hardware problem. Nvidia Tesla V100 in p3 instance used CUDA 9. It can't run in CUDA 8 as specified in the official instruction. Would it be a possible reason for failure of compilation?
I haven't seen any report of successful case of this GPU so I am considering to switch to other GPU that use CUDA 8.

**Comment by soulslicer** [comment]
You are linking against Caffe2. OpenPose does not support Caffe 2. Also I tested Openpose on the V100 with latest CUDA, there is no problems

**Comment by JasOlean** [comment]
same error

**Comment by vasanthhr** [comment]
I got the same issue. can someone help me here.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1087

**Comment by hhoomn** [comment]
If your cuda does not support your gpu, change your cuda version.
Otherwise, if your device is not  compute_71 (e.g. a GTX 10XX series). 
You can remove the nvcc compute_71 flags in the cmake files with the following command.
First configure the cmake but before generating the makefile run:
To remove the flag from .cmake files:<br/>
`find . -name "**.cmake" -exec sed -i "s/-gencode;arch=compute_75,code=sm_75;//g" {} \;`<br/>
To remove the flag from .pre-gen files (I don't know if this is necessary):<br/>
`find . -name "**.pre-gen" -exec sed -i "s/-gencode;arch=compute_75,code=sm_75;//g" {} \;` <br/>
Finally run the following command to see if any flag is remaining,<br/>
` grep -r "compute_75"`<br/>
Manually remove those flags (for me there were one example file which was not .cmake and .pre-gen)
After this generate the makefile using cmake-gui and build openpose.

**Comment by ZhangYouyi** [comment]
Comment the following line in openpose-1.4.0/cmake/Cuda.cmake
list(APPEND CUDA_NVCC_FLAGS ${NVCC_FLAGS_EXTRA})

**Comment by ruizcrp** [comment]
I have the same issue with compute_70 and tried the solution by @hhoomn (modified to compute_70 and sm_70) as well as by @ZhangYouyi . It however still says the same error with compute_70
