### ISSUE TITLE
Makefile:586: recipe for target '.build_release/src/caffe/layers/xxxxxx_layer.o' failed

### ISSUE THREAD

**Issue by wkcw** [CMU-Perceptual-Computing-Lab/openpose#7]
Requirements are met.
Here's the error message,  I hope you can help me, please 

------------------------- Compiling Caffe -------------------------
CXX src/caffe/layers/bias_layer.cpp
CXX src/caffe/layers/parameter_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/dropout_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/sigmoid_layer.cpp
CXX src/caffe/layers/filter_layer.cpp
CXX src/caffe/layers/lstm_layer.cpp
CXX src/caffe/layers/hdf5_output_layer.cpp
CXX src/caffe/layers/softmax_layer.cpp
CXX src/caffe/layers/scale_layer.cpp
CXX src/caffe/layers/argmax_layer.cpp
CXX src/caffe/layers/crop_layer.cpp
CXX src/caffe/layers/euclidean_loss_layer.cpp
CXX src/caffe/layers/inner_product_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/parameter_layer.hpp:6,
                 from src/caffe/layers/parameter_layer.cpp:1:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/parameter_layer.o' failed
make: *** [.build_release/src/caffe/layers/parameter_layer.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/hdf5_output_layer.hpp:10,
                 from src/caffe/layers/hdf5_output_layer.cpp:6:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/filter_layer.hpp:7,
                 from src/caffe/layers/filter_layer.cpp:3:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/hdf5_output_layer.o' failed
make: *** [.build_release/src/caffe/layers/hdf5_output_layer.o] Error 1
Makefile:586: recipe for target '.build_release/src/caffe/layers/filter_layer.o' failed
make: *** [.build_release/src/caffe/layers/filter_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/sigmoid_cross_entropy_loss_layer.hpp:7,
                 from src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/filler.hpp:13,
                 from src/caffe/layers/bias_layer.cpp:3:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/bias_layer.o' failed
make: *** [.build_release/src/caffe/layers/bias_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/euclidean_loss_layer.hpp:7,
                 from src/caffe/layers/euclidean_loss_layer.cpp:3:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/euclidean_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/euclidean_loss_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/cudnn_sigmoid_layer.hpp:7,
                 from src/caffe/layers/cudnn_sigmoid_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/cudnn_sigmoid_layer.o' failed
make: *** [.build_release/src/caffe/layers/cudnn_sigmoid_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from src/caffe/layers/crop_layer.cpp:8:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/crop_layer.o' failed
make: *** [.build_release/src/caffe/layers/crop_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/dropout_layer.hpp:7,
                 from src/caffe/layers/dropout_layer.cpp:5:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/filler.hpp:13,
                 from src/caffe/layers/scale_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/dropout_layer.o' failed
make: *** [.build_release/src/caffe/layers/dropout_layer.o] Error 1
Makefile:586: recipe for target '.build_release/src/caffe/layers/scale_layer.o' failed
make: *** [.build_release/src/caffe/layers/scale_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/sigmoid_layer.hpp:7,
                 from src/caffe/layers/sigmoid_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/sigmoid_layer.o' failed
make: *** [.build_release/src/caffe/layers/sigmoid_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/softmax_layer.hpp:7,
                 from src/caffe/layers/softmax_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/softmax_layer.o' failed
make: *** [.build_release/src/caffe/layers/softmax_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/cudnn_tanh_layer.hpp:7,
                 from src/caffe/layers/cudnn_tanh_layer.cpp:4:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/cudnn_tanh_layer.o' failed
make: *** [.build_release/src/caffe/layers/cudnn_tanh_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/layer.hpp:12,
                 from ./include/caffe/layers/argmax_layer.hpp:7,
                 from src/caffe/layers/argmax_layer.cpp:6:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/argmax_layer.o' failed
make: *** [.build_release/src/caffe/layers/argmax_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/filler.hpp:13,
                 from src/caffe/layers/lstm_layer.cpp:6:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/lstm_layer.o' failed
make: *** [.build_release/src/caffe/layers/lstm_layer.o] Error 1
In file included from ./include/caffe/util/math_functions.hpp:11:0,
                 from ./include/caffe/filler.hpp:13,
                 from src/caffe/layers/inner_product_layer.cpp:3:
./include/caffe/util/mkl_alternate.hpp:14:19: fatal error: cblas.h: No such file or directory
compilation terminated.
Makefile:586: recipe for target '.build_release/src/caffe/layers/inner_product_layer.o' failed
make: *** [.build_release/src/caffe/layers/inner_product_layer.o] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.

**Comment by gineshidalgo99** [comment]
It looks like you do not have Atlas installed. You might try installing it with `sudo apt-get install libatlas-base-dev` and recompiling again. Let us know whether it works. Thanks!

**Comment by wkcw** [comment]
@gineshidalgo99  It works!  And the demo is excellent. Great work!

**Comment by gineshidalgo99** [comment]
Thank you!

**Comment by andongchen** [comment]
@gineshidalgo99 
I also have compiling error ?do you know how to solved it?thanks
cy@cy:~/anProjects/openpose-master$ make all -j4
LD -o .build_release/lib/libopenpose.so.1.0.0-rc2
CXX examples/openpose/openpose.cpp
CXX examples/tutorial_thread/2_user_processing_function.cpp
CXX examples/tutorial_thread/3_user_input_processing_and_output.cpp
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:462: recipe for target '.build_release/lib/libopenpose.so.1.0.0-rc2' failed
make: *** [.build_release/lib/libopenpose.so.1.0.0-rc2] Error 1
make: *** Waiting for unfinished jobs....

**Comment by gineshidalgo99** [comment]
It is a Caffe dependencies problem. Try installing the pre-requisites Caffe asks for (and rebooting after that):
http://caffe.berkeleyvision.org/install_apt.html

Let me know the results.

If it still fails, also let me know:
**Operating system** (`lsb_release -a` on Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by andongchen** [comment]
@gineshidalgo99 
I install all the Caffe dependencies,but get the same error
Operating system :ubuntu16.04
CUDA version (cat /usr/local/cuda/version.txt in most cases):CUDA Version 8.0.44
cuDNN version:5.1
GPU model (nvidia-smi):NVIDIA-SMI 375.26                 Driver Version: 375.26 gtx1080
Caffe version: Default from OpenPose 
OpenCV version:  OpenCV 3.1
Compiler (gcc --version on Ubuntu):gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by BLCKPSTV** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
CUDA Version 9.0.176
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 780M    Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   42C    P8    N/A /  N/A |    722MiB /  4035MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
```
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

Error when doing make all.

nvcc fatal   : Unsupported gpu architecture 'compute_20'
Makefile:594: recipe for target '.build_release/cuda/src/caffe/layers/cudnn_lcn_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/cudnn_lcn_layer.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by gineshidalgo99** [comment]
As it says, CUDA 9 is not compatible with compute_20. Our Makefile.config does not include compute_20, so you are not properly following the instructions or using your custom Caffe version. If it's the later, make sure Caffe works by its own.

**Comment by BLCKPSTV** [comment]
reverted to cuda 8 and got other errors, no custom version! 

```
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
Makefile:594: recipe for target '.build_release/cuda/src/caffe/layers/cudnn_lcn_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/cudnn_lcn_layer.o] Error 1
make: *** Waiting for unfinished jobs....

```

Cuddn error? Don't know what to do exactly to fix it. Downgrade cuddn?  or downgrade gcc?

**Comment by gineshidalgo99** [comment]
Are you install with Makefile.config or CMake steps?

**Comment by cv-shiyanshi** [comment]
> It looks like you do not have Atlas installed. You might install it with `sudo apt-get install libatlas-base-dev` and recompile again. Let us know whether it works. Thanks!
> 
> PS: I added that information in the [doc/installation.md](../blob/master/doc/installation.md)

I have meet the same question, and I have installed Atlas with "sudo apt-get install libatlas-base-dev"，Please help!
