### ISSUE TITLE
body_25 vs COCO

### ISSUE THREAD

**Issue by jpbillzhou** [CMU-Perceptual-Computing-Lab/openpose#701]
I found BODY_25 model is much faster than COCO. How come?

**Comment by gineshidalgo99** [comment]
That's mentioned on the Latest feature section from the README, it is ~40% faster AND 5% more accurate AND it includes foot keypoints. A paper with the architecture might be available in a few months. Downside: it uses more memory. Thanks

**Comment by jpbillzhou** [comment]
thanks, how could I train it with what data set?

**Comment by gineshidalgo99** [comment]
We are still labeling more foot annotations before releasing the foot dataset, we see that even though it works, it's still less robust than body keypoints

**Comment by shreyasrajesh** [comment]
Hi, I was wondering if a version of the body_25 network architecture but with just the 18 COCO keypoints is avaiable and, if not are there any plans for something like this ?

Thank you.

**Comment by gineshidalgo99** [comment]
@shreyasrajesh  No, there is no point on doing that (same speed, same accuracy for the body keypoints, but less keypoints).

**Comment by mikeolasz** [comment]
@gineshidalgo99 If you claim a huge increase in speed using the new model why is it not worth to use it with the body keypoints only?

Thanks

**Comment by gineshidalgo99** [comment]
No, I meant that speed and accuracy are the same between training the new model with body and foot vs. training the new model with body only. So no, there would be not benefit in doing it.

**Comment by mikeolasz** [comment]
Oh, I see. So training the new model with either 18 or 25 keypoints takes the same amount of time, but the inference (and I guess training also?) is still faster compared to the previous 2 branch model regardless how many keypoints you want to detect. Am I correct?

**Comment by gineshidalgo99** [comment]
Exactly, sorry if my explanation was not clear enough.
