### ISSUE TITLE
How to pass other parameters like 'number_people_max' while calling python module.

### ISSUE THREAD

**Issue by vijay1131** [CMU-Perceptual-Computing-Lab/openpose#705]
I am trying to use the parameter 'num_people _max' which can be used with c++ build and c++ api.
But i am not sure how to use the same with Python Module. Any directions will be helpful.

**Comment by soulslicer** [comment]
Hi, this feature is not there yet, but I am planning on adding it within the next 2 weeks

**Comment by vijay1131** [comment]
Thanks! that would be great.

**Comment by varunjammula** [comment]
The Python module does not support adding other parameters, can you please update it.

**Comment by vijay1131** [comment]
Hi Any update on this Issue?

**Comment by larrypm** [comment]
Same question. Is it updated yet? Thanks
