### ISSUE TITLE
Getting join information 

### ISSUE THREAD

**Issue by ehtick** [CMU-Perceptual-Computing-Lab/openpose#706]
Is it possible to get information about the joins in the pose i.e. which lines connect from a certain body parts to an other. Such as from shoulder to elbow etc..

**Comment by gineshidalgo99** [comment]
It appears in the doc/output.md for COCO model. You are right, I should add an image for the new model. I will try to add it within 1-2 weeks.

**Comment by ehtick** [comment]
Thanks i am trying to see that a person raises his arm and count the raised arms (left and right separate)
If i can figure out the joins and then see that the lower arm is higher then the upper arm it could be a raised arm. Wouldn't it be helpfull that the information now given by keypoints include this information?
Or is there an other way to get this?

**Comment by gineshidalgo99** [comment]
You can check doc/output.md for that information about which keypoint index is which (left shoulder, right elbow, etc). I'll eventually add a pic as I did for COCO with the connections, but they can be easily guessed from the keypoints. Thanks!
