### ISSUE TITLE
specific protobuf version  needed?

### ISSUE THREAD

**Issue by jeremy-rutman** [CMU-Perceptual-Computing-Lab/openpose#707]
### Executed Command (if any)
make -j4 

### OpenPose Output (if any)

/home/jeremy/PycharmProjects/openpose/build/caffe/src/openpose_caffe-build/include/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
/home/jeremy/PycharmProjects/openpose/build/caffe/src/openpose_caffe-build/include/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

v1.3.0-82-g7c21e0b

2. **General configuration**:
    - **Installation mode**: 
cmake-gui   , no gpu , no cudnn
    - **Operating system**
 ubuntu 18.04
    - **Release or Debug mode**?
 release
    - Compiler 
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

6. If **CPU-only mode** issue:
    - **CPU brand & model**:
 product: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
MemTotal:       16356504 kB
    - Total **RAM memory** available:

**Comment by gineshidalgo99** [comment]
Hi, that error is coming from caffe side. Please, try installing caffe (Intel mkl branch, as you are using could version) by following it's official instructions, then you can link OpenPose against that one.

**Comment by markelwin** [comment]
This dependency on Caffe seems to be a continued issue, especially for Mac and operating environments in where Caffe has been deprecated. The installation instructions for OpenPose do not seem to support this use case, and solutions in its issues repository seem to be rare. These have become massive burdens for each time that my group has installed OpenPose, which is the de facto standard in the industry, and is particularly detrimental to remote and automated installation of OpenPose, as semi-manual editing of files is often required. Does OpenPose support automated remote deployment of its software, and is this part of its mandate as the industry leader? Is there a standard recipe guide which is intended to cover this use case?
Thank you very much.
