### ISSUE TITLE
How to set python version?

### ISSUE THREAD

**Issue by universewill** [CMU-Perceptual-Computing-Lab/openpose#709]
My system is ubuntu16.04, and got python2.7 and python3.6

I set /usr/bin/python to python3.6. But after building openpose, it can only run by python2.
The 1_extract_pose.py demo will encounters error like below if run by python3:

```
Traceback (most recent call last):
  File "1_extract_pose.py", line 37, in <module>
    openpose = OpenPose(params)
NameError: name 'OpenPose' is not defined
```

**Comment by Gjain234** [comment]
Yes having the same problem!

**Comment by soulslicer** [comment]
As per the instructions, you need to set your PYTHONPATH to where OpenPose python is built. If you ran `sudo make install`, it'll install by default to /usr/local/python, so you would add this to your environmental variables:

`export PYTHONPATH=/usr/local/python/:$PYTHONPATH`

If you are on Ubuntu or OSX, you can add this to your `.bashrc`

**Comment by Danivilanova** [comment]
I have found a solution for that problem. It works for me so here it go.
You need to import:
`from openpose import openpose as op`
And then use it as:
`op.OpenPose(params)`

I hope this help you!

**Comment by universewill** [comment]
I run 'sudo make install' and openpose is installed in /usr/local/python/ directory.
I also add the path as PYTHONPATH in ~/.bashrc file, and source it.
However, my python code can not find openpose module. Besides, the demo code in build/example/python_tutorial can execute well.
@soulslicer

**Comment by universewill** [comment]
I replace export PYTHONPATH=/usr/local/python/:$PYTHONPATH by export PYTHONPATH=/usr/local/python/openpose:$PYTHONPATH.
And problem solved!

**Comment by Necrote** [comment]
I get the same error with Python3.7 on Windows10. I can't import openpose either.
Although, I can import pyopenpose and all 'tutorial_api_python' examples work.

I tried `cmake install .` instead, by following the [doc/deployment.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/deployment.md) instructions. But still no luck.

Am I supposed to work through pyopenpose Wrapper `opWrapper = op.WrapperPython()` to get this working?
