### ISSUE TITLE
How to draw the returned points on cpu

### ISSUE THREAD

**Issue by mxmxlwlw** [CMU-Perceptual-Computing-Lab/openpose#71]
I used the getPoseKeyPoints() class method to get the pts. And I draw these pts in cv::Mat. But it doesn't seem right. How should I do to convert these pts to the right position.

**Comment by gineshidalgo99** [comment]
Hi @mxmxlwlw , if you did draw the keypoints with CPU, could you post your implementation here? So I can try to add it to OpenPose with some new flag (e.g. `render_output_cpu`). Thanks!

**Comment by mxmxlwlw** [comment]
Hi @gineshidalgo99 , here's the code. Hope I can help.
#include <opencv2/opencv.hpp>
#include <string>
#include <sstream>

#define USE_CAFFE
#include <openpose/headers.hpp>

struct openpose_out
{
    cv::Rect rect;
    std::vector<cv::Vec3f> pts;
    std::vector<std::pair<cv::Vec2i, float>> pts_pairs;
    std::vector<cv::Mat> part_img;
    std::pair<cv::Rect, cv::Mat> head;
    std::pair<cv::Rect, cv::Mat> topBody;
    std::pair<cv::Rect, cv::Mat> bottomBody;
    std::pair<cv::Rect, cv::Mat> fullBody;
};


class openpose_lib
{
private:
    cv::Size outputSize;
    cv::Size netInputSize;
    cv::Size netOutputSize;
    op::PoseModel poseModel;
    op::CvMatToOpInput cvMatToOpInput;
    op::CvMatToOpOutput cvMatToOpOutput;
    op::OpOutputToCvMat opOutputToCvMat;
    op::PoseExtractorCaffe poseExtractorCaffe;
public:
    openpose_lib()
        : outputSize(1280, 720),
        netInputSize(656,368),
        netOutputSize(656, 368),
        poseModel(op::PoseModel::COCO_18),
        cvMatToOpInput{netInputSize, 1, 0.3},
        cvMatToOpOutput{outputSize},
        opOutputToCvMat(outputSize),
        poseExtractorCaffe{netInputSize, netOutputSize, outputSize,
            1, 0.3, poseModel, "./models/", 0}
    {
        poseExtractorCaffe.initializationOnThread();
    }

    void detect(cv::Mat &img, std::vector<openpose_out> &out)
    {
        const auto netInputArray=cvMatToOpInput.format(img);
        op::Array<float> outputArray;
        double scaleInputToOutput;
        std::tie(scaleInputToOutput, outputArray) = cvMatToOpOutput.format(img);
        poseExtractorCaffe.forwardPass(netInputArray, img.size());
        const auto poseKeyPoints=poseExtractorCaffe.getPoseKeyPoints();
        const float *pts = poseKeyPoints.getConstPtr();
        auto outputImage=opOutputToCvMat.formatToCvMat(outputArray);

        float radio1=(float)img.cols/outputSize.width;
        float radio2=(float)img.rows/outputSize.height;
        float radio = std::max(radio1, radio2);





        const float *dst=pts;
        for (int i=0; i<poseKeyPoints.getSize()[0]; i++)
        {
            openpose_out o;
            const float *dst2=dst;
            for (int j=0; j<poseKeyPoints.getSize()[1]; j++)
            {
                cv::Vec3f pt1={dst2[0]*radio, dst2[1]*radio, dst2[2]};
                //cv::circle(img, cv::Point(dst2[0]*radio, dst2[1]*radio), 3, cv::Scalar(255, 0, 0));
                o.pts.push_back(pt1);
                dst2+=3;
            }

            auto f=[&](int i, int j){
                o.pts_pairs.push_back({{i,j},std::min(o.pts[i][2], o.pts[i][2])});
                cv::Mat transM;
                cv::Size sz;
                cv::Point2f pt1(o.pts[i][0], o.pts[i][1]);
                cv::Point2f pt2(o.pts[j][0], o.pts[j][1]);
                float dist = cv::norm(pt1 - pt2);

                getTransferM(pt1, pt2, dist*0.2, dist*0.2, transM, sz);
                cv::Mat subimg;
                cv::warpPerspective(img, subimg, transM, sz);
                o.part_img.push_back(subimg);
            
            };
            f(1,2);
            f(1,5);
            f(2,3);
            f(5,6);
            f(3,4);
            f(6,7);
            f(8,9);
            f(9,10);
            f(11,12);
            f(12,13);

            auto f2=[&](std::vector<cv::Vec3f> pts, std::pair<cv::Rect, cv::Mat> &ox){
                cv::Point lt(10000,10000), rb(-10000,-10000);
                for (auto &k : pts)
                {
                    if (k[2]!=0)
                    {
                        lt=cv::Point(std::min(lt.x, (int)k[0]), std::min(lt.y, (int)k[1]));
                        rb=cv::Point(std::max(rb.x, (int)k[0]), std::max(rb.y, (int)k[1]));
                    }
                }
                ox.first=cv::Rect(lt, rb);
                ox.first.x-=10;
                ox.first.width+=20;
                ox.first.y-=10;
                ox.first.height+=20;
                clipBox(ox.first, img.size());
                ox.second = img(ox.first).clone();
            };
        
            f2({o.pts[1], o.pts[2], o.pts[3], o.pts[4], o.pts[7], o.pts[6], o.pts[5]}, o.topBody);
            f2({o.pts[8], o.pts[9], o.pts[10], o.pts[11], o.pts[12], o.pts[13]}, o.bottomBody);
            f2(o.pts, o.fullBody);

            float minX=10000, maxX=-10000;
            float meanY=0;
            int c=0;
            for (auto &k : {o.pts[0], o.pts[14], o.pts[15], o.pts[16], o.pts[17]})
            {
                if (k[2]!=0)
                {
                    minX=std::min(k[0], minX);
                    maxX=std::max(k[0], maxX);
                    meanY+=k[1];
                    c++;
                }
            }
            meanY/=c;

            float headLen=maxX-minX;

            o.head.first.x=minX-10;
            o.head.first.y=meanY-headLen/2-10;
            o.head.first.width=headLen+21;
            o.head.first.height=headLen+21;
            clipBox(o.head.first, img.size());

            //cv::rectangle(img, o.topBody.first, cv::Scalar(255, 0, 0), 1);
            //cv::rectangle(img, o.bottomBody.first, cv::Scalar(255, 0, 0), 1);
            //cv::rectangle(img, o.fullBody.first, cv::Scalar(0, 0, 255), 1);
            //cv::rectangle(img, o.head.first, cv::Scalar(0, 255, 0), 1);



            out.push_back(o);
            dst+=18*3;
        }

        //for (auto &i : out[0].part_img)
        //{
        //    cv::imshow("mx", i);
        //    cv::waitKey(0);
        //}
        //cv::imshow("mx", out[0].topBody.second);
        //cv::waitKey(0);
        //cv::imshow("mx", out[0].bottomBody.second);
        //cv::waitKey(0);

        //cv::imshow("mx", img);
        //cv::waitKey(0);
    }

private:
    void getPtsBy2Pts(cv::Point2f &pt1, cv::Point2f &pt2, float dist1, float dist2, std::vector<cv::Point2f> &vPts)
    {
        cv::Point2f k = pt1 - pt2;
        float dist = cv::norm(k);
        cv::Point2f k2(-k.y / dist, k.x / dist);
        cv::Point p;
        p = dist1*k2 + pt1;
        vPts.push_back(p);
        p = dist1*k2 + pt2;
        vPts.push_back(p);
        p = -dist2*k2 + pt2;
        vPts.push_back(p);
        p = -dist2*k2 + pt1;
        vPts.push_back(p);
    }

    void getTransferM(cv::Point2f &pt1, cv::Point2f &pt2, float dist1, float dist2, cv::Mat &transferM, cv::Size &sz)
    {
        std::vector<cv::Point2f> rect1, rect2;
        getPtsBy2Pts(pt1, pt2, dist1, dist2, rect1);
        float width, height;
        width = cv::norm(rect1[1] - rect1[0]);
        height = cv::norm(rect1[1] - rect1[2]);
        rect2.push_back(cv::Point2f(0, 0));
        rect2.push_back(cv::Point2f(width, 0));
        rect2.push_back(cv::Point2f(width, height));
        rect2.push_back(cv::Point2f(0, height));
        transferM=cv::getPerspectiveTransform(rect1, rect2);
        sz = cv::Size(width, height);
    }

    void clipBox(cv::Rect &rect, cv::Size imgsz)
    {
        cv::Rect k;
        k.x = std::min(std::max(0, rect.x), imgsz.width-1);
        k.y = std::min(std::max(0, rect.y), imgsz.height-1);
        k.width = std::min(std::max(0, rect.x+rect.width-1), imgsz.width-1)-k.x+1;
        k.height = std::min(std::max(0, rect.y+rect.height), imgsz.height-1)-k.y+1;

        rect=k;
    }
};

int main()
{
    openpose_lib lib;
    cv::Mat img = cv::imread("./1.jpg");
    std::vector<openpose_out> out;
    lib.detect(img, out);
    return 0;
}

**Comment by mxmxlwlw** [comment]
@gineshidalgo99 And it may have some bugs... I just took me several hours to write it.

**Comment by gineshidalgo99** [comment]
Thank you I'll check it soon!

**Comment by gineshidalgo99** [comment]
I just added and pushed a CPU rendering version. See the OpenPose demo or wrappers tutorial to take a look.

**Comment by mxmxlwlw** [comment]
ok!
