### ISSUE TITLE
Extracting 3D keypoints in Json file.

### ISSUE THREAD

**Issue by MritulaC** [CMU-Perceptual-Computing-Lab/openpose#712]
Hi,
  Is it possible to extract 3D keypoints from images of videos(both with single person only) using openpose? If yes then how?

I tried many combinations similar to 2D extraction but ended up with error.

Thanks,
 Mritula

**Comment by nyudeb** [comment]
Need an answer here ! plz :)
Is it possible to assign camera from another program like Blender ? Or maybe 2 video like : 
![openpose3d](https://user-images.githubusercontent.com/24704802/44254446-29853f00-a203-11e8-9c7a-d560e2867918.gif)
