### ISSUE TITLE
cmake loop 

### ISSUE THREAD

**Issue by jeremy-rutman** [CMU-Perceptual-Computing-Lab/openpose#717]
### Issue Summary
cmake goes into a loop and fails to generate openpose.bin (for example)_ 

### Executed Command (if any)
cmake -DOpenCV_INCLUDE_DIRS=/usr/include/opencv   -DOpenCV_LIBS_DIR=/usr/lib   -DCaffe_INCLUDE_DIRS=/root/caffe/include -DCaffe_LIBS=/root/caffe/build/install/lib/libcaffe.so  ..

same results for cmake ..

### OpenPose Output (if any)
A bunch of warnings like the following get output , with the same list of dirs after each warning 

```
CMake Warning at examples/tests/CMakeLists.txt:16 (add_executable):
  Cannot generate a safe runtime search path for target resizeTest.bin
  because there is a cycle in the constraint graph:
....
    dir 51 is [/usr/lib/openblas-base]
      dir 41 must precede it due to runtime library [liblapack.so.3]
      dir 52 must precede it due to runtime library [libblas.so.3]
      dir 53 must precede it due to runtime library [liblapack.so.3]
    dir 52 is [/usr/lib/libblas]
      dir 41 must precede it due to runtime library [libblas.so.3]
      dir 51 must precede it due to runtime library [libblas.so.3]
    dir 53 is [/usr/lib/lapack]
      dir 41 must precede it due to runtime library [liblapack.so.3]
      dir 51 must precede it due to runtime library [liblapack.so.3]
    dir 54 is [/usr/libx86_64-linux-gnu]
    dir 55 is [/root/caffe/build/install/lib]

  Some of these libraries may not be found correctly.
-- Generating done
```
And the binaries dont seem to have been generated 

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: ubuntu 16.04 cmake
    - **Operating system** (`lsb_release -a` in Ubuntu): ubuntu 16.04.3 
    - **Release or Debug mode**? (by defualt: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0 20160609

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

4. **3rd-party software**:
    - **Caffe version**: 1.0
    - **CMake version** (`cmake --version` in Ubuntu):3.5.1
    - **OpenCV version**: 3.3.0 self compiled

5. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):8.0.61
    - **cuDNN version**: 6 
    - **GPU model** (`nvidia-smi` in Ubuntu): P6000 quadro

**Comment by gineshidalgo99** [comment]
It says `Generating done`, so it's being generated, so the warnings seems to be just warnings. Follow the full installation.md, your commands don't seem complete, you have just run Cmake.

**Comment by zhihuiFan** [comment]
@jeremy-rutman  hope you doing well.   do you still remember how did you fix?   I am stuck in this situation as well.    I'm using cmake 3.11, all the other environment looks pretty same.

**Comment by jeremy-rutman** [comment]
I don't recall, maybe try the advice of @gineshidalgo99
