### ISSUE TITLE
./build/examples/openpose/openpose.bin: No such file or directory

### ISSUE THREAD

**Issue by query-box** [CMU-Perceptual-Computing-Lab/openpose#719]
I run following commands:
git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose --recursive
cd openpose
mkdir build
cd build
cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-8.0 -DCUDA_INCLUDE_DIRS=/usr/local/cuda-8.0 CUDA_CUDART_LIBRARY=/usr/local/cuda-8.0 ..

Following output is generated:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GCC detected, adding compile flags
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
-- Caffe has already been downloaded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
-- Caffe will be built from source now.
-- Download the models.
-- Downloading BODY_25 model...
-- Model already exists.
-- Not downloading body (COCO) model
-- Not downloading body (MPI) model
-- Downloading face model...
-- Model already exists.
-- Downloading hand model...
-- Model already exists.
-- Models Downloaded.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mysystem/Downloads/openpose/build

Then I tried running:
cd ..                          # came to openpose directory
./build/examples/openpose/openpose.bin --image_dir examples/media/
 this second line shows following error:
bash: ./examples/openpose/openpose.bin: No such file or directory

It was found that no examples folder was present in build dir. But one examples folder was persent in openpose [outside build dir]. I tired with :
./examples/openpose/openpose.bin --image_dir examples/media/
But got the same error.

**Comment by edrdos101** [comment]
I have a similar issue, were you able to find the solution?

**Comment by MonaCS** [comment]
I also have the same issue, build is done successfully but I cannot find openpose.bin file in the build folder. Any advice?

**Comment by ShaminiKoravuna** [comment]
I have the same issue did anyone solve the problem?

**Comment by DongHwanJang** [comment]
@query-box  same issue here. did you solve this?

**Comment by MonaCS** [comment]
Sorry Shaminin, I cannot recall the problem, seems it was long time back.
Would you please remind me what was the problem? thanks

**Comment by ParmpalSinghGill** [comment]
You have issue in building the openpose. follow the steps to install it 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md

**Comment by NotErikUden** [comment]
I have the exact same issue. Build installed correctly (I assume) but the openpose.bin file in ./build/examples/openpose/openpose.bin doesn't exist. Does anyone know how to fix this issue? I'm trying to use [PIFuHD](https://github.com/facebookresearch/pifuhd).

**Comment by camrynfriedman** [comment]
> I have the exact same issue. Build installed correctly (I assume) but the openpose.bin file in ./build/examples/openpose/openpose.bin doesn't exist. Does anyone know how to fix this issue? I'm trying to use [PIFuHD](https://github.com/facebookresearch/pifuhd).

I'm having the same problem. @NotErikUden did you solve it?

**Comment by seshadri-c** [comment]
@camrynfriedman did you solve the issue ? please let me know once done.

**Comment by camrynfriedman** [comment]
> @camrynfriedman did you solve the issue ? please let me know once done.

@seshadri-c I haven't fixed it yet but I'm going to work on it in the next few days.

**Comment by senemaktas** [comment]
Hi, now I have the same problem. did you find any solution? help.

**Comment by senemaktas** [comment]
> Hi, now I have the same problem. did you find any solution? help.

```
import os
from os.path import exists, join, basename, splitext

# give the url of openpose repo to get codes
git_repo_url = 'https://github.com/CMU-Perceptual-Computing-Lab/openpose.git'

# name the project name the repo
project_name = splitext(basename(git_repo_url))[0]

# if you do not have that repo name project then create one
if not exists(project_name):

  # see: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/949
  # install new CMake becaue of CUDA10
  wget -q https://cmake.org/files/v3.21/cmake-3.21.0-rc3-linux-x86_64.tar.gz
  !tar xfz cmake-3.21.0-rc3-linux-x86_64.tar.gz --strip-components=1 -C /usr/local
  # clone openpose
  !git clone -q --depth 1 $git_repo_url
  !sed -i 's/execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/execute_process(COMMAND git checkout f019d0dfe86f49d1140961f8c7dec22130c83154 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/g' openpose/CMakeLists.txt
  # install system dependencies
  !apt-get -qq install -y libatlas-base-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler libgflags-dev libgoogle-glog-dev liblmdb-dev opencl-headers ocl-icd-opencl-dev libviennacl-dev
  # install python dependencies
  !pip install -q youtube-dl
  # build openpose
  !cd openpose && rm -rf build || true && mkdir build && cd build && cmake -DBUILD_PYTHON=ON .. && make -j`nproc`
!mkdir openpose/videos 
```

In this part try to find latest version of cmake. 
```

  !wget -q https://cmake.org/files/v3.21/cmake-3.21.0-rc3-linux-x86_64.tar.gz
  !tar xfz cmake-3.21.0-rc3-linux-x86_64.tar.gz --strip-components=1 -C /usr/local
```

Follow the link: [https://cmake.org/files/](https://cmake.org/files/)
