### ISSUE TITLE
how to use openpose in other dir

### ISSUE THREAD

**Issue by wxy656** [CMU-Perceptual-Computing-Lab/openpose#72]
### Issue summary
i want to  call openpose as one part in my  project ,so i try in other dir(not in openpose dir ),it would not work.
I know this is caused by the path problem，but how to change  "models" dir to a absolute path or link it with "/home/ubuntu/openpose/build/examples/openpose/openpose.bin" 

### Executed command (if any)
"./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 1 --no_display --write_pose_json output/vedio" 
this command works in openpose dir but failed in other dir

### OpenPose output (if any)

Starting pose estimation demo.
Starting thread(s)
F0612 11:48:41.891775  3775 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: models/pose/coco/pose_deploy_linevec.prototxt
*** Check failure stack trace: ***
    @     0x7f1bf3925daa  (unknown)
    @     0x7f1bf3925ce4  (unknown)
    @     0x7f1bf39256e6  (unknown)
    @     0x7f1bf3928687  (unknown)
    @     0x7f1bf249114d  caffe::ReadProtoFromTextFile()
    @     0x7f1bf24a35d4  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f1bf24e50dc  caffe::Net<>::Net()
    @     0x7f1bf3c69522  op::NetCaffe::initializationOnThread()
    @     0x7f1bf3befde3  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f1bf3c120b9  op::SubThread<>::initializationOnThread()
    @     0x7f1bf3c12648  op::Thread<>::initializationOnThread()
    @     0x7f1bf3c14ece  op::Thread<>::threadFunction()
    @     0x7f1bf34a2a60  (unknown)
    @     0x7f1bf0b2f184  start_thread
    @     0x7f1bf2f10bed  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

### Type of issue
You might select multiple topics, delete the rest:

- Execution error

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):  16.0
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):cuda 8.0
**cuDNN version**:
**GPU model** (`nvidia-smi`):nvidia-smi
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):OpenCV 2.X

**Comment by gineshidalgo99** [comment]
Please check the documentation:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md --> `model_folder`
