### ISSUE TITLE
Feet

### ISSUE THREAD

**Issue by MikePelton** [CMU-Perceptual-Computing-Lab/openpose#720]
### Help wanted
Hi - the inclusion of foot detection is massively important for us, but it's very unclear from the doc how I would go about getting the extra keypoints to correspond with feet. Do I need to load a different model, and if so which? Does OpenPoseDemo in the v1.3 build include appropriate options or could openpose.cpp be modified to do so?
All help welcome
Thanks
Mike Pelton

**Comment by gineshidalgo99** [comment]
It's included in the latest version from GitHub (if you manually compile it) and it runs by default. I didn't add it to the new releases because I want to make sure all the changes are working fine before releasing it as an official version.

**Comment by MikePelton** [comment]
Fantastic, and many thanks for coming back so quickly.
