### ISSUE TITLE
Json file - sometimes double results

### ISSUE THREAD

**Issue by nyudeb** [CMU-Perceptual-Computing-Lab/openpose#721]
Hello, I work with the Windows portable demo (v1.3.0) on multiple images. I got weird json results sometimes, like 2x pose_keypoints_2d in the same file... It's like the process pass 2 times and give 2 differents points lists...

I don't know if it's "normal" but the result I don't have in the first pass are added in the second one, and this happen randomly... (I work with a lot of different 3D Model)

Is it normal ? :)

**keypoints.json:**

{
  **"version"**: 1.2,
  **"people"**: [
    {
      **"pose_keypoints_2d"**: [
        0.55488,
        0.317166,
        0.93771,
        0.500208,
        0.374595,
        0.628497,
        0.497535,
        0.371862,
        0.795112,
        0.511129,
        0.448347,
        0.892602,
        0.541299,
        0.511108,
        0.882342,
        0.497507,
        0.37182,
        0.560543,
        0.524819,
        0.464605,
        0.0566016,
        0,
        0,
        0,
        0.494869,
        0.55216,
        0.738225,
        0.489343,
        0.66973,
        0.753382,
        0.472886,
        0.80355,
        0.677582,
        0.511169,
        0.549445,
        0.593518,
        0.492182,
        0.672347,
        0.654019,
        0.489364,
        0.798004,
        0.594962,
        0.541297,
        0.308982,
        0.83414,
        0,
        0,
        0,
        0.513865,
        0.314507,
        0.935348,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    },
    {
      **"pose_keypoints_2d"**: [
        0,
        0,
        0,
        0,
        0,
        0,
        0.497535,
        0.371862,
        0.795112,
        0.511129,
        0.448347,
        0.892602,
        0.541299,
        0.511108,
        0.882342,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0.513865,
        0.314507,
        0.935348,
        0,
        0,
        0
      ],
      "face_keypoints_2d": [],
      "hand_left_keypoints_2d": [],
      "hand_right_keypoints_2d": [],
      "pose_keypoints_3d": [],
      "face_keypoints_3d": [],
      "hand_left_keypoints_3d": [],
      "hand_right_keypoints_3d": []
    }
  ]
}

**Comment by gineshidalgo99** [comment]
That means OpenPose detects 2 people on that image, that's why it outputs 2 pair of elements.

**Comment by nyudeb** [comment]
![4271_right_rendered](https://user-images.githubusercontent.com/24704802/42582212-db7dbd00-852e-11e8-84e6-841f6ba63a07.png)

**Comment by nyudeb** [comment]
I don't know how it can detect 2 people here...

**Comment by gineshidalgo99** [comment]
THanks for the image, seeing the results, the first 2d keypoints seems valid, the second one is a wrong left arm labeled where the right arm is.

You can also use `number_people_max 1`  (check doc/demo_overview.md) to force 1 person if you know there is only 1 person.

**Comment by nyudeb** [comment]
oh cool ! - but now I don't have the other result part... ^^  I will merge the other part in the first one when needed 'cause the results seems valid for the right arm. Thanks for the reply and thanks for this awesome project ! :)

**Comment by gineshidalgo99** [comment]
I didn't check it much, but as I said, i think the second one IS actually a mistake of OpenPose, as (I think) it's putting the left arm AS the right one. However, the first one is still estimating part of the left arm (so both arm are estimated in the 1st one). So I don't think you should merge them, but rather use the one with higher score (the one that number_people_max 1 will use).
