### ISSUE TITLE
[ubuntu] [speed] Network take time 

### ISSUE THREAD

**Issue by Qidian213** [CMU-Perceptual-Computing-Lab/openpose#723]
# Configure :
For PC 
1.OpenPose version : openpose 1.3.0 
2.3rd-party software:
     Caffe version: Default
     OpenCV version: compiled from source opencv3.2.0
     CUDA version: cuda8
     cuDNN version : cudnn5.1.10
3.GPU model : GTX1060 6G (total 1 GPU), NVIDIA-SMI 384.130
     CPU I7-7700

# Questions 
I test the network use caffe tools with cmd ,

`./build/caffe/bin/caffe time --model=models/pose/body_25/pose_deploy.prototxt --weights=models/pose/body_25/pose_iter_584000.caffemodel --iterations=1000 --gpu=0`

Got result ,

`
I0712 14:43:15.637372 19952 caffe.cpp:408] Average Forward pass: 13.5472 ms.
I0712 14:43:15.637377 19952 caffe.cpp:410] Average Backward pass: 10.7096 ms.
I0712 14:43:15.637418 19952 caffe.cpp:412] Average Forward-Backward: 24.378 ms.
I0712 14:43:15.637424 19952 caffe.cpp:414] Total Time: 24378 ms.

`

and test thread time with `PROFILER_ENABLED` enable , got result ,

`
Starting thread(s)...
0.320534 msec at in /openpose-master/include/openpose/producer/wDatumProducer.hpp:workProducer():70
0.000348 msec at in /openpose-master/include/openpose/thread/wIdGenerator.hpp:work():69
0.001970 msec at in /openpose-master/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
3.279423 msec at in /openpose-master/include/openpose/core/wCvMatToOpInput.hpp:work():64
3.478171 msec at in /openpose-master/include/openpose/core/wCvMatToOpOutput.hpp:work():66
125.562591 msec at in /openpose-master/include/openpose/pose/wPoseExtractor.hpp:work():91
6.192852 msec at in /openpose-master/include/openpose/pose/wPoseRenderer.hpp:work():72
5.452538 msec at in /openpose-master/include/openpose/core/wOpOutputToCvMat.hpp:work():62
0.548657 msec at in /openpose-master/include/openpose/gui/wGuiInfoAdder.hpp:work():65
3.813766 msec at in /openpose-master/include/openpose/gui/wGui.hpp:workConsumer():80

`

It seems that the Network not really took many time , but i could only got 7.5--8.2 fps with a 640x480 camera , others all use default . I test different part of the `wPoseExtractor.hpp:work()` not found which Function take many time while running .  It same with your test ? thanks .

**Comment by gineshidalgo99** [comment]
1000 / 125.562591 ms  is about 6-8 FPS as you said, so that's the expected speed with that GPU.
