### ISSUE TITLE
writing images and json failed

### ISSUE THREAD

**Issue by andieheung-s4d** [CMU-Perceptual-Computing-Lab/openpose#725]
My environment:
OS: Ubuntu 16.04
GPU: Nvidia Tesla M60
CUDA 8
Cudnn 5.1
OpenCV latest
CAFFE

I built Openpose in Ubuntu 16.04 on AWS g3.4xlarge instance without GUI and tried to test it by this command:
./build/examples/openpose/openpose.bin --image_dir /data/openpose/build/examples/files/ --write_images /data/openpose/build/examples/output --write_json /data/openpose/build/examples/output

Sure the image directory has a jpeg image file for testing.
 
The only output is this message:
(OpenPose 1.3.0:2004): Gtk-WARNING **: cannot open display: 

It didn't actually output anything to the destination path.
Do I really need GUI to get the output function work? 
Is it possible to get it output something without GUI in Ubuntu?

**Comment by gineshidalgo99** [comment]
Disable the gui (check display in doc/demo overview.md)
