### ISSUE TITLE
it doesn't display any keypoint in the video? my computer system version is mac 10.12.6 with cpu

### ISSUE THREAD

**Issue by hwt41042** [CMU-Perceptual-Computing-Lab/openpose#728]

**Comment by ShuminY** [comment]
Hi, did you get your issue resolved? I am also trying openpose on macOS and didn't manage to install it yet (issue 764 and 765). It seems that you have installed it successfully. Really appreciate it if you could help me out or give me any advices. Thanks a lot.

**Comment by hwt41042** [comment]
Yes,follow the tips, it's Ok.
Maybe you should install the caffe first before you cmake the project.Then find the absolute path of caffe headers and libs, modify the cmake path.Good luck!

**Comment by ShuminY** [comment]
thank you. I got the answer at issue [#423](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/423).
