### ISSUE TITLE
Masks

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [CMU-Perceptual-Computing-Lab/openpose#733]
How to get masks out of using OpenPoseDemo.exe? The best I got was -heatmaps_add_bkg, yet this is just circles. What I want are masks I can use with videoavatars.

**Comment by soulslicer** [comment]
openpose currently does not produce masks. it does however produce part affinity fields (lines across keypoints) which you can use.

**Comment by soulslicer** [comment]
no it does not provide masks internally. it provides heatmaps and part affinity fields. please read the paper on the main github page if you want more details on the internal workings of openpose
