### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by smakaviani** [CMU-Perceptual-Computing-Lab/openpose#735]
Hello, 
I want to use the open pose model as a pre-trained model, can you help me with that? I mean where I can find the pretrained model?
Thanks,

**Comment by smakaviani** [comment]
I mean as a pose estimator to use the estimated pose from the image

**Comment by JafirDon** [comment]
Hi,

Openpose pre-trained models links in getModels.sh file. 
[(https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/models/getModels.sh](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/models/getModels.sh)
