### ISSUE TITLE
The result of openpose.bin is better than python api for coco 18 key points?

### ISSUE THREAD

**Issue by universewill** [CMU-Perceptual-Computing-Lab/openpose#738]
I use openpose.bin to predict pose and save as json file.I also use 'forward' function in python api to predict pose. However, i find the result is not the same as openpose.bin file.

It seems the openpose.bin result is better, and the scores are higher. I checked my paras for python api, it is the same like the settings here: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/openpose/openpose.cpp

FYI, I use coco 18 key points model.

This is the python api result for one frame:
```
[[[102.48478     60.27833      0.77804685]
  [110.24185     76.48418      0.80473477]
  [ 99.221176    75.83982      0.7555801 ]
  [ 78.422386    69.98817      0.61053574]
  [ 69.34277     47.251816     0.25439146]
  [121.28634     77.12805      0.80524635]
  [124.54307     95.95928      0.7903464 ]
  [112.21387     91.44811      0.5297946 ]
  [ 98.558975   118.051704     0.69093734]
  [ 88.16793    146.62285      0.7047412 ]
  [ 90.774605   173.25587      0.38851827]
  [114.15679    121.278786     0.68092257]
  [106.347885   150.52107      0.7822241 ]
  [ 97.91361    180.40459      0.7457255 ]
  [101.18824     58.960052     0.7395617 ]
  [106.37294     58.936558     0.8457739 ]
  [  0.           0.           0.        ]
  [112.23128     60.23603      0.77435005]]]
```

This is  openpose.bin json result for the same frame:
```
[101.847,59.6171,0.952928,
110.883,75.2111,0.881218,
99.2172,73.2411,0.78186,
77.79,69.9729,0.821772,
69.3424,47.2515,0.588551,
121.302,76.4978,0.82828,
125.204,95.9776,0.861314,
115.462,92.0688,0.667706,
99.212,116.77,0.730823,
86.8949,147.948,0.797325,
90.7766,178.456,0.434711,
114.148,119.994,0.689505,
104.406,149.246,0.756883,
96.6061,181.061,0.799491,
101.193,58.3029,0.64854,
106.34,57.0154,0.908564,
0,0,0,
112.213,59.6292,0.923988]
```

**Comment by universewill** [comment]
Can you guys give any help here ? @soulslicer  @gineshidalgo99 
Thanks a lot.I really can not figure this out. 
Is it because the code language difference between python and c++?

The accuracy was harmed by python?

**Comment by gineshidalgo99** [comment]
Please add your FULL hw configuration if you expect an answer from us (post it as a new message so we are notified). Ideally, there is NO difference.

**Comment by universewill** [comment]
### Executed Command (if any)
build/examples/openpose/openpose.bin --video UCF50/Punch/v_Punch_g08_c01.avi --write_json ./data/openpose_estimation/snippets/v_Punch_g08_c01 --display 0 --render_pose 0 --model_pose COCO


### Type of Issue
- Help wanted
- Question

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: CMake  (Ubuntu)
    - **Operating system** ubuntu16.04
    - **Release or Debug mode**? (by defualt: release):
    - Compiler  5.4.0, ... (Ubuntu)

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** , cmake version 3.11.1
    - **OpenCV version**: opencv 3.2

5. If **GPU mode** issue:
    - **CUDA version** : 9.0
    - **cuDNN version**: cudnn7.0.5
    - **GPU model**: 1080 TI

@gineshidalgo99

**Comment by gineshidalgo99** [comment]
kvideo.io.vread python --> Could you actually follow the demo instead of using a custom one? To make sure the error is not coming from there? Because for us the result is exactly the same.

**Comment by universewill** [comment]
The build/examples/tutorial_python folder only gives demo to read image and predict pose in image.
Not video.
@gineshidalgo99

**Comment by soulslicer** [comment]
Hi all,

I just compared the sample images on Python vs C++. The output is exactly the same. There is a very minor floating point mismatch towards the last 2 decimal places, but that shouldnt affect overall accuracy.

I think the kvideo API you are using is affecting your image quality. You might want to use OpenCV to load videos instead

**Comment by universewill** [comment]
ok, i will use opencv api to load video for predicting.
Thanks for all!

**Comment by bhavesh2799** [comment]
@soulslicer @universewill @gineshidalgo99 @ps2 @loretoparisi Can anyone share a script to get 18 keypoints coco output.  It would be great if it could convert the output of body25 model to coco 18 keypoints output. I tried using the openpose write_coco_json, but it gave the result in an entirely different format than usual. I don't have much experience with json, so any help would be appreciated.

**Comment by Popinpon** [comment]
for pythonAPI
`        points25=datum.poseKeypoints[0]
index=[0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18] #body25->coco18 format
        points18=points25[index]`
