### ISSUE TITLE
i can't find info about accelerate model in the new update link:Jun 2018: Combined body-foot model released! Faster and more accurate!

### ISSUE THREAD

**Issue by cswwp** [CMU-Perceptual-Computing-Lab/openpose#739]
it seems like has nothing in this link:Jun 2018: Combined body-foot model released! Faster and more accurate!

**Comment by gineshidalgo99** [comment]
The link sends you to the installation website. You just follow the installation steps, and you'll have the body-foot model. Best

**Comment by SoCohesive** [comment]
@cswwp were you able to get the body-foot estimation model to work ?
