### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by sscdemodern** [CMU-Perceptual-Computing-Lab/openpose#740]
Hello!

I have found a project that implements OpenPose in Unity (https://github.com/ZiuTinyat/OpenPoseUnityDemo). To my suprise he uses UDP for communication and explains that one should use the `udp_host` and `udp_port` flags to enable this. It seems to be working for him atleast. From what I can tell by reading your code it seems that UDP is not yet enabled. Is this correct? Will it be enabled soon? And if it isn't enabled yet how is it possible for ZiuTinyat to use this feature. Is there an experimental flag or something one can set?

Thanks alot!

**Comment by gineshidalgo99** [comment]
This is an experimental project that should be added to OpenPose within the next few months. We are working on it.
