### ISSUE TITLE
changing the keypoint_scale  to have the keypoints coordinate in [-1, 1]

### ISSUE THREAD

**Issue by smakaviani** [CMU-Perceptual-Computing-Lab/openpose#741]
Hi, 
I could run the example code `openpose/examples/tutorial_python/1_extract_pose.py`, but if I want to have the keypoints coordinate in scale `[-1, 1] or [0,1]` what parameter should I add to this code?

Thanks,
Samira,

**Comment by soulslicer** [comment]
Isn't this something you can do yourself easily? I dont think OP can do this for you

**Comment by gineshidalgo99** [comment]
Only the whole demo provides this functionality, not the examples. As Raaj says, you can always do it yourself easily.

**Comment by smakaviani** [comment]
Thank you so much for writing to me,
