### ISSUE TITLE
openpose怎么融合TensorRT

### ISSUE THREAD

**Issue by songxinlu** [CMU-Perceptual-Computing-Lab/openpose#743]

**Comment by vinjn** [comment]
plz use English

**Comment by z13974509906** [comment]
@songxinlu you are 666

**Comment by yyyreal** [comment]
@songxinlu you are 999(6 upside down)

**Comment by yucolabjames** [comment]
Am also interested in this question.

OP meant how to integrate OpenPose with TensorFlow.
