### ISSUE TITLE
I have error in CMake configure

### ISSUE THREAD

**Issue by gonyang** [CMU-Perceptual-Computing-Lab/openpose#746]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDART_LIBRARY (ADVANCED)
    linked by target "openpose" in directory C:/Users/Team Elysium/Desktop/openpose/openpose/src/openpose
CUDA_TOOLKIT_INCLUDE (ADVANCED)
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/src/openpose
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/calibration
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/openpose
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_add_module
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_pose
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_pose
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_thread
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_thread
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_thread
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_thread
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_wrapper
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_wrapper
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_wrapper
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_wrapper
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_wrapper
   used as include directory in directory C:/Users/Team Elysium/Desktop/openpose/openpose/examples/tutorial_wrapper

Configuring incomplete, errors occurred!
See also "C:/Users/Team Elysium/Desktop/openpose/openpose/build/CMakeFiles/CMakeOutput.log".
----------------------------------------------------------------------------------------------------------------

My system spec ~
os : windows 10
graphic card : geforce 1050
visual studio : 2015 enterprise update 3
cuda : cuda_8.0.61.2_windows
cudnn : cudnn-8.0-windows10-x64-v5.1
Cmake : cmake-3.12.0-win64-x64

I think i installed everything. but i blocked in CMake configureing... i need your help.

i got these errors.  
is there any solution ? 
i could not find anything on docs and issue..
if you know other issues of this error , mention at below. 

Thanks

**Comment by guochaodlnu** [comment]
#I meeting the same errors ! I will try to find the reason of this problem. 
My system spec ~
os : ubuntu 16.04LTS
graphic card : geforce 1060
cuda : cuda_9.2
cudnn : cudnn7.1.4
Cmake : cmake-3.5.1
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLUT_Xmu_LIBRARY (ADVANCED)
    linked by target "openpose" in directory /home/chuck/track_detection/OpencvPose/openpose/src/openpose
    linked by target "calibration.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/calibration
    linked by target "openpose.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/openpose
    linked by target "1_custom_post_processing.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_add_module
    linked by target "1_extract_from_image.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_pose
    linked by target "2_extract_pose_or_heatmat_from_image.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_pose
    linked by target "1_openpose_read_and_display.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_thread
    linked by target "2_user_processing_function.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_thread
    linked by target "3_user_input_processing_and_output.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_thread
    linked by target "4_user_input_processing_output_and_datum.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_thread
    linked by target "2_user_synchronous_input.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_wrapper
    linked by target "1_user_synchronous_postprocessing.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_wrapper
    linked by target "5_user_asynchronous.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_wrapper
    linked by target "6_user_asynchronous_output.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_wrapper
    linked by target "4_user_synchronous_all.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_wrapper
    linked by target "3_user_synchronous_output.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tutorial_wrapper
    linked by target "handFromJsonTest.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tests
    linked by target "resizeTest.bin" in directory /home/chuck/track_detection/OpencvPose/openpose/examples/tests
    linked by target "_openpose" in directory /home/chuck/track_detection/OpencvPose/openpose/python/openpose
Configuring incomplete, errors occurred!
See also "/home/chuck/track_detection/OpencvPose/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/chuck/track_detection/OpencvPose/openpose/build/CMakeFiles/CMakeError.log".
```

**Comment by guochaodlnu** [comment]
I try re-clone the  repositories ,then re-configure find the problem solved.I don't know why....

**Comment by gonyang** [comment]
i delete all related program , and download vs 2017 , cuda 9.2 , cudnn that supports cuda 9.2 .
It works....
I didn't re-clone the repositories.. 
so i don't know why this error is occur.

if you got these error,i recommend you to change all related program's version.
