### ISSUE TITLE
python layer not made despite setting flag in  CMakeCache.txt  (...and caffe/src/openpose_caffe-build/CMakeCache.txt, and CMakeFiles/openpose_caffe.dir/build.make)

### ISSUE THREAD

**Issue by jeremy-rutman** [CMU-Perceptual-Computing-Lab/openpose#748]
### Issue Summary
python api not built despite changing entry at 
CMakeCache.txt  , when that didnt work tried 
CMakeFiles/openpose_caffe.dir/build.make , when that didnt work tried 
caffe/src/openpose_caffe-build/CMakeCache.txt, when that didnt work tried 
caffe/tmp/openpose_caffe-cfgcmd.txt

line in CMakelists.txt: 
option(BUILD_PYTHON "Build OpenPose python." ON)

### Executed Command (if any)

python 1_extract_pose.py

### OpenPose Output (if any)

```
root@8ba95f9fc941:/data/openpose/examples/tutorial_python# python 1_extract_pose.py 
Traceback (most recent call last):
  File "1_extract_pose.py", line 21, in <module>
    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
Exception: Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
```

also, from make:
```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   1.0-112-g9453eb0
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF

```

if i further  edit caffe/tmp/openpose_caffe-cfgcmd.txt  then I can force the report of BUILD_python in the make to be on. However the python examples still dont work (' OpenPose library could not be found ' ) 

output when searching for where build_python occurs:

```
root@8ba95f9fc941:/data/openpose# grep -ir build_python *
3rdparty/caffe/cmake/Dependencies.cmake:if(BUILD_python)
3rdparty/caffe/cmake/Dependencies.cmake:    if(BUILD_python_layer)
3rdparty/caffe/cmake/Summary.cmake:  caffe_status("  BUILD_python      :   ${BUILD_python}")
3rdparty/caffe/CMakeLists.txt:caffe_option(BUILD_python "Build Python wrapper" ON)
3rdparty/caffe/CMakeLists.txt:caffe_option(BUILD_python_layer "Build the Caffe Python layer" ON)
3rdparty/caffe/CMakeLists.txt:if(BUILD_python)
CMakeLists.txt:option(BUILD_PYTHON "Build OpenPose python." ON)
CMakeLists.txt:  if (${GPU_MODE} MATCHES "OPENCL" OR BUILD_PYTHON)
CMakeLists.txt:  if (${GPU_MODE} MATCHES "CPU_ONLY" OR ${GPU_MODE} MATCHES "OPENCL" OR BUILD_PYTHON)
CMakeLists.txt:  if (BUILD_PYTHON)
CMakeLists.txt:#          -DBUILD_python=OFF
CMakeLists.txt:          -DBUILD_python=ON
CMakeLists.txt:#          -DBUILD_python=OFF
CMakeLists.txt:          -DBUILD_python=ON
CMakeLists.txt:#          -DBUILD_python_layer=OFF
CMakeLists.txt:          -DBUILD_python_layer=OFF
CMakeLists.txt:#          -DBUILD_python=OFF
CMakeLists.txt:          -DBUILD_python=ON
CMakeLists.txt:          -DBUILD_python_layer=OFF
CMakeLists.txt:    if (${GPU_MODE} MATCHES "CPU_ONLY" OR ${GPU_MODE} MATCHES "OPENCL" OR BUILD_PYTHON)
CMakeLists.txt:  if(BUILD_PYTHON)
build/caffe/src/openpose_caffe-build/CMakeCache.txt:BUILD_python:BOOL=ON
build/caffe/src/openpose_caffe-build/CMakeCache.txt:BUILD_python_layer:BOOL=OFF
build/caffe/tmp/openpose_caffe-cfgcmd.txt:cmd='/usr/bin/cmake;-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>;-DUSE_CUDNN=ON;-DCPU_ONLY=OFF;-DCMAKE_BUILD_TYPE=Release;-DBUILD_docs=OFF;-DBUILD_python=ON;-DBUILD_python_layer=OFF;-DUSE_LEVELDB=OFF;-DUSE_LMDB=OFF;-DUSE_OPENCV=OFF;-GUnix Makefiles;/data/openpose/3rdparty/caffe'
build/examples/tutorial_python/2_pose_from_heatmaps.py:    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
build/examples/tutorial_python/1_extract_pose.py:    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
build/CMakeCache.txt:BUILD_PYTHON:BOOL=ON
build/CMakeFiles/openpose_caffe.dir/build.make:	cd /data/openpose/build/caffe/src/openpose_caffe-build && /usr/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=/data/openpose/build/caffe -DUSE_CUDNN=ON -DCPU_ONLY=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_docs=OFF -DBUILD_python=ON -DBUILD_python_layer=OFF -DUSE_LEVELDB=OFF -DUSE_LMDB=OFF -DUSE_OPENCV=OFF "-GUnix Makefiles" /data/openpose/3rdparty/caffe
doc/installation.md:To install the Python API, ensure that the `BUILD_PYTHON` flag is turned on while running CMake GUI. Check [doc/modules/python_module.md](./modules/python_module.md) for further details.
examples/tutorial_python/2_pose_from_heatmaps.py:    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
examples/tutorial_python/1_extract_pose.py:    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')

```

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: CMake fro command line (cmake ..) 

    - **Operating system** (`lsb_release -a` in Ubuntu):  Ubuntu 16.04.3 LTS
    - **Release or Debug mode**? (by default: release): release
    - Compiler  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

3. **Non-default settings**:
MAKE_PYTHON:ON

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

5. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

6. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

7. If **Python** API:
    - **Python version**: 2.7
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

**Comment by soulslicer** [comment]
Can you try deleting your build folder and try again. Generally such cmake issues can be resolved as such

**Comment by jeremy-rutman** [comment]
deleted build folder, edited CMakelists.txt to switch build_python flag on after fresh git pull (Updating 7c21e0b..6f90b30)  
make still reports 
 --   BUILD_python      :   OFF
 and I still dont get the pyhton lib made.  Maybe I also need to nuke the caffe dirs

**Comment by jeremy-rutman** [comment]
nuking 3rdparty/caffe which forces re-download also doesnt help,t he caffe configuration summary still reports build_python:OFF.   any hints?

**Comment by jeremy-rutman** [comment]
in the hopes that someone might shed light:

**Comment by soulslicer** [comment]
you cannot modify the cmakelists directly. set it in the gui or pass it in as an option as I described in my previous post

**Comment by jeremy-rutman** [comment]
I'm sorry , I can't find a reference to passing in build_python as an option - where is this previous post?

**Comment by jeremy-rutman** [comment]
unfortunately this cmake parameter seems  not to work either::

```
git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
cd openpose/
mkdir build
cd build/
cmake -DBUILD_PYTHON=ON ..
make -j20
cd examples/tutorial_python/
python 1_extract_pose.py 
-> OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake 
```

**Comment by jeremy-rutman** [comment]
perhaps I should be using one of the shell scripts under the openpose/ubuntu dir?

**Comment by jeremy-rutman** [comment]
also - when i specify -DBUILD_PYTHON, should the cafe configuration summary reflect this, or is the caffe  BUILD_python flag a different one than the openpose build_python flag?

**Comment by soulslicer** [comment]
Okay, i see whats going on now..

You need to go to build/examples/tutorial_python and run it from there

**Comment by jeremy-rutman** [comment]
also the python install instructions link 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/installation.md#python-module  ,  referred to on the link you recommended 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md#testing
is brokenj 
is broken

**Comment by vasanthhr** [comment]
I got the same issue. can someone help me here.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1087

**Comment by soulslicer** [comment]
@vasanthhr Stop commenting all over the issues please. Please post on the specific issue

**Comment by vasanthhr** [comment]
@soulslicer , I have posted since few days back, so far no updates.

Do you able to take a look into this issue ?

issue number: 1087

**Comment by diogohmsilva** [comment]
I know it has been a while but I was facing the same issues as @jeremy-rutman and solved it with -DBUILD_PYTHON='ON' instead of -DBUILD_PYTHON=ON
