### ISSUE TITLE
Unexpected termination without processing all images in directory

### ISSUE THREAD

**Issue by 404noahfound** [CMU-Perceptual-Computing-Lab/openpose#75]
### Issue summary
I have more than 40 000 coco validation images in the directory. But the demo only process 3599 of them and terminated with a success message. How to fix this? 

### Executed command (if any)
./build/examples/openpose/openpose.bin --image_dir ./../coco/val2014/ --write_coco_json coco_result.json

### Type of issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): CentOS 7.2.1511
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0.44
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose 
**OpenCV version**: installed with `apt-get install libopencv-dev`

**Comment by gineshidalgo99** [comment]
The COCO extractor was still an experimental module only meant for internal purposes. I have just finished it and pushed it to the repository.

In case you want to process a subset of images, you can specify the first-last frames to process by `--frame_first` & `--frame_last` (both 0-based).

Let me know if you find more issues.
