### ISSUE TITLE
Click noise when running openpose, harddisk read/write ?

### ISSUE THREAD

**Issue by Fungungun** [CMU-Perceptual-Computing-Lab/openpose#751]
### Issue Summary
I'm running openpose on a alienware-like laptop with SSD and nvidia 1080 gpu. My laptop makes
clicking noise when and only when I run openpose. It might come from hard disk. I'm just wondering
whether there's a heavy harddisk read/write in openpose?

Thanks

### Executed Command (if any)
demo

### OpenPose Output (if any)
Normal

### Type of Issue
- Other (type your own type)

### Your System Configuration
1. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
latest

2. **General configuration**:
Ubuntu16.04

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

5. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

cuda8.0 gpu1080

6. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

7. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

yes

8. If **Windows** system:
    - Portable demo or compiled library?
no
9. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).
no

**Comment by soulslicer** [comment]
Well, there will definitely be disk read if you are reading a video file

**Comment by Fungungun** [comment]
well thanks. I guess there's no json writter or video writer etc in openpose demo, right? still can't figure out where the clicking noise comes from.

**Comment by gineshidalgo99** [comment]
@Fungungun  Not by default, yes if you enable them with the flags. Since you are running default demo, no, there is not disk reading/writing (other than reading the image source)

**Comment by cleverlight** [comment]
I can confirm this is a live issue.  I hear a mechanical tick coincident with each new frame, at the same volume as a loud harddisk write.  It's quite alarming for an almost silent PC to make such a noise!

**Steps**
Create RAM disk
Copy video file to RAM disk
No output, display only
Execute from Powershell: bin/OpenPoseDemo.exe --video R:\tmp\piano.mp4 --face --hand
Video parses at about 3-6fps, loud ticks coincident with frames

**System Configuration**
OpenPose version: 1.4.0

**General configuration**
Desktop: Asus Z390 motherboard, ASUS GTX1080ti, Samsung NVMe SSD, Intel core i9 CPU
OS: Windows 10
Caffe version: Default from OpenPose
Using pre-compiled OpenPoseDemo.exe (1.4.0 release)
CUDA version: 10.0 (nvidia-smi.exe reported)

**Analysis**
I think this is emanating from the graphics card (1080ti).  It's not an old card and it's not had a hard life!
I ran the demo from an SSD drive, then re-ran just using a RAM disk to eliminate the possibility of confusing the noise with a harddisk read/write.

**Question**
Is it possible that OpenPose is setting the fan speed (high-low-high) every frame?

**Comment by gineshidalgo99** [comment]
OpenPose does not change any setting, it is simply quite computationally heavy (specially for the GPU). Your computer has some mechanical issue that is only visible when CPU and GPU are being fully used (most probably GPU).
