### ISSUE TITLE
Runtime error when calling poseExtractorCaffe.initializationOnThread()

### ISSUE THREAD

**Issue by biggoood** [CMU-Perceptual-Computing-Lab/openpose#752]
Hi, there
I'm trying to use openpose as a third party library on UE4 engine, but when I trying to call the poseExtractorCaffe.initializationOnThread() an runtime error comes out:
 **Unhandled exception at 0x00007FFEBFB2DBDD (openpose.dll) in UE4Editor.exe: 0xC0000005: Access violation writing location 0x0000000000000198.**

My system environment is Windows10, what I'm trying to do is input a frame(data type is Mat) each time and run the openpose on this frame. Is there any way to solve this problem or to avoid this function?

Thanks for any help!

**Comment by biggoood** [comment]
btw, this function runs perfectly in the openpose tutorial program, so I'm assuming if the error comes from openpose dll file... but I can still call the OpenCV functions through openpose/headers.hpp.

**Comment by soulslicer** [comment]
well..its a strange error. you can try to compile openpose in debug mode so you get a more detailed error. generally this happens if you attempt to access an object whose thread was initialized already or you're not accessing it from the same thread

**Comment by davemurphy** [comment]
Are you running open pose on a dedicated thread in UE4?
What version of UE4 are you using?

**Comment by biggoood** [comment]
@davemurphy  Hi, The version I'm using is 4.17.
I didn't create a dedicated thread for openpose functions.

**Comment by biggoood** [comment]
@soulslicer hi, Raaj and thanks, yes it is a strange error and I can't run the code in debug mode cause its runs in UE4 environment, all the links are done by the UE4 code which the dll files are not import directly by the VS2015. You are right I think, I'm thinking about the threads problems, the UE4 and openpose may have different threads management method? Is there a way to shut down the multi thread in the PoseExtractorCaffe class?
