### ISSUE TITLE
RUN ./build/examples/openpose/openpose.bin --video examples/media/video.avi

### ISSUE THREAD

**Issue by SCUT2014** [CMU-Perceptual-Computing-Lab/openpose#755]
Starting pose estimation demo.
GStreamer Plugin: Embedded video playback halted; module decodebin20 reported: Your GStreamer installation is missing a plug-in.
Auto-detecting GPUs... Detected 2 GPU(s), using them all.
warning: GStreamer: unable to seek (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:710)
Starting thread(s)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
Empty frame detected, frame number 0 of 0. In src/openpose/producer/producer.cpp:checkFrameIntegrity():148
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
Input images must be 3-channel BGR. Converting your grey image into BGR. In ./include/openpose/producer/datumProducer.hpp:checkIfRunningAndGetDatum():107

(openpose.bin:31807): Gtk-WARNING **: cannot open display:

**Comment by soulslicer** [comment]
This is an issue with opencv and not openpose. Try to see if you can get a simple opencv python example to work first

**Comment by SCUT2014** [comment]
The opencv2.4.5 is installed in my ubuntu 14.04, I don't know whether openpose is compatiable with opencv 2.4.5 or not ?

**Comment by hellozjj** [comment]
Did you solved it?

**Comment by hellozjj** [comment]
> Starting pose estimation demo.
> GStreamer Plugin: Embedded video playback halted; module decodebin20 reported: Your GStreamer installation is missing a plug-in.
> Auto-detecting GPUs... Detected 2 GPU(s), using them all.
> warning: GStreamer: unable to seek (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:710)
> Starting thread(s)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
> Empty frame detected, frame number 0 of 0. In src/openpose/producer/producer.cpp:checkFrameIntegrity():148
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:641)
> warning: GStreamer: unable to query position of stream (/builddir/build/BUILD/opencv-2.4.5/modules/highgui/src/cap_gstreamer.cpp:660)
> Input images must be 3-channel BGR. Converting your grey image into BGR. In ./include/openpose/producer/datumProducer.hpp:checkIfRunningAndGetDatum():107
> 
> (openpose.bin:31807): Gtk-WARNING **: cannot open display:

Did you solve it?
