### ISSUE TITLE
wrong cuda version detected

### ISSUE THREAD

**Issue by jeremy-rutman** [CMU-Perceptual-Computing-Lab/openpose#756]
### Issue Summary

make is detecting cuda9 which hasnt been installed on the system

### Executed Command (if any)

```

root@033d8e742bb8:/usr/local/cuda-8.0# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

root@59cb31ceeea0:/usr/local/cuda-8.0# ls -l /usr/local/cu*
lrwxrwxrwx 1 root root    8 Nov  4  2017 /usr/local/cuda -> cuda-8.0
/usr/local/cuda-8.0:
total 48
-rw-r--r-- 1 root root  365 Jan 26  2017 LICENSE
...

```

### OpenPose Output (if any)
```
root@033d8e742bb8:/data/openpose/build# cmake -DBUILD_PYTHON=ON ..
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 9.0
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 6.0.21 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
CMake Error at /usr/share/OpenCV/OpenCVConfig.cmake:108 (message):
  OpenCV static library was compiled with CUDA 8.0 support.  Please, use the

```

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: Latest GitHub code

2. **General configuration**:
    - **Installation mode**: cli CMake ubuntu , cuda8 cudnn6
    - **Operating system** ubuntu16.04
    - **Release or Debug mode**? (by default: release):
    - Compiler : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? 
-Dbuild_python=on

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: compiled 3.3

5. If **GPU mode** issue:
    - **CUDA version** ```
root@033d8e742bb8:/usr/local/cuda-8.0# cat /usr/local/cuda/version.txt
CUDA Version 8.0.61

```
    - **cuDNN version**:   6
    - **GPU model** (`nvidia-smi` in Ubuntu): quadro p6000 Driver Version: 396.37


7. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?  2.7

**Comment by jeremy-rutman** [comment]
i blv this is due to a different cuda on bare machine than that in the docker container running the openpose code.

**Comment by Harsharma2308** [comment]
The same thing is happening with me. I have CUDA-8 installed and 
`cmake .. 
`gives
```
Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)

```
But when I do 

`make -j8`
I get
```
CUDA detected: 7.5
-- Found cuDNN: ver. 7.3.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- Found Atlas: /usr/include  
```

Which is weird as I don't have CUDA 7.5 on my machine at all.
Two versions I have are cuda-9.0 and cuda-8.0.
```
 ls -la | grep cuda

lrwxrwxrwx  1 root root    8 Dec 13 22:12 cuda -> cuda-8.0
drwxr-xr-x 14 root root 4096 Dec 13 22:12 cuda-8.0
drwxr-xr-x 15 root root 4096 Dec 12 17:12 cuda-9.0

```

**Comment by apatsekin** [comment]
You can run cmake gui and set CUDA_VERSION = [whatever_you_need].

**Comment by whf9527** [comment]
how to solve the problem.

It show:
CMake Error at /usr/local/share/OpenCV/OpenCVConfig.cmake:108 (message):
  OpenCV static library was compiled with CUDA 9.0 support.  Please, use the
  same version or rebuild OpenCV with CUDA 10.0

**Comment by Open-Debin** [comment]
![捕获](https://user-images.githubusercontent.com/52323137/147635081-c7081445-187e-441c-8c7a-ea8b81ead052.PNG)

Hello everyone! I solved this problems by change the CUDA_TOOLKIT_ROOT_DIR in cmake_gui
