### ISSUE TITLE
Model can not download

### ISSUE THREAD

**Issue by syamlu** [CMU-Perceptual-Computing-Lab/openpose#759]
The model (body_25/pose_iter_584000.caffemodel, face/pose_iter_116000.caffemodel, hand/pose_iter_102000.caffemodel) can not be downloaded when using cmake, it returns "Couldn't connect to server".
The download link "http://posefs1.perception.cs.cmu.edu/OpenPose/models/" failed.

**Comment by gineshidalgo99** [comment]
Try after a few minutes

**Comment by syamlu** [comment]
Sorry, I have tried many times, could you give me a download link which I can download directly? Thanks

**Comment by gineshidalgo99** [comment]
There are links in the doc
