### ISSUE TITLE
F0616 errors

### ISSUE THREAD

**Issue by shiangyoung** [CMU-Perceptual-Computing-Lab/openpose#76]
### Issue summary
Not sure with the error

### Executed command (if any)
./build/examples/openpose/openpose.bin --image_dir examples/media/

### OpenPose output (if any)
F0616 05:01:45.039072 27538 upgrade_proto.cpp:95] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/coco/pose_iter_440000.caffemodel

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): 16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0.61
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi`): GTX850M 
**Caffe version**: Default from OpenPose
**OpenCV version**: installed with `apt-get install libopencv-dev`
Compiler (`gcc --version` on Ubuntu): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
That might happen if models/pose/coco/pose_iter_440000.caffemodel was not properly downloaded.

Please, manually remove models/pose/coco/pose_iter_440000.caffemodel and re-download it again:
`cd models/`
`bash getModels.sh`

Let us know your result.

**Comment by shiangyoung** [comment]
I remove all the files and reinstall again...now it works very well...thanks

**Comment by nanthakumar94** [comment]
can you tell me how to download windows using getModels.sh file?

**Comment by plocircle** [comment]
@nanthakumar94 
I saw getModels.bat alongside with getModels.sh under models/, try in cmd with
```
cd models
.\getModels.bat 
```

**Comment by zhangscth** [comment]
i have met the same problem! and I redownloaded the caffemodel file, but it doesn't work. plz help, thank you!

**Comment by shash29-dev** [comment]
redownloading doesn't help
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F0731 22:57:13.291972 26533 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel

**Comment by zhan-xu** [comment]
@zhangscth @shash29-dev I wonder if you have any updates on this problem? Thank you!

**Comment by ShashankInteli** [comment]
> @zhangscth @shash29-dev I wonder if you have any updates on this problem? Thank you!

still a issue
