### ISSUE TITLE
enabling 3d data output

### ISSUE THREAD

**Issue by mabosl** [CMU-Perceptual-Computing-Lab/openpose#761]
Hi there,

I'm running openpose via a docker image on a ubuntu 18.04 machine.
https://hub.docker.com/r/garyfeng/docker-openpose/

The tool itself works perfectly fine with all of the functions an implementations.

I want to extract 3d tracking data from videos, but the documentation does not exactly define how.
The command i am using is:
`./build/examples/openpose/openpose.bin --video /data/example.mp4 --no_display --write_video /data/op_output/op_example.avi --write_keypoint_json /data/example_data/ --3d`

where or how do i have to enable the --3d flag?...
I tried lots of different variations but it does not generate the data. 
what's the right command?
when i leave out the 3d-flag the 2d data gets generated perfectly fine.

The --part_candidates flag does not work as well.
Is the DockerImage to old maybe?

All of the issues did not and the --help flag etc. didn't help me out.
Thanks in advance.

**Comment by gineshidalgo99** [comment]
That Docker file is not ours, so unfortunately we can't help much there. Try contacting whoever did that Docker file. Thanks
