### ISSUE TITLE
Issue While running :libopenpose.so.1.3.0: cannot open shared object file:

### ISSUE THREAD

**Issue by MJUSER** [CMU-Perceptual-Computing-Lab/openpose#762]
### Issue Summary
I have successfully installed openpose cpu version. And i was using it properly. But after some weeks i came back today , and i run openpose,  then it resulted in  an error. 

### Executed Command (if any)
This is the command in was using like,
cd openpose
./build/examples/openpose/openpose.bin --image_dir examples/media/ --write_json --display 1 --render_pose 1  --net_resolution 656x368

### OpenPose Output (if any)
No output, got error like

ERROR-
./build/examples/openpose/openpose.bin: error while loading shared libraries: libopenpose.so.1.3.0: cannot open shared object file: No such file or directory

### Type of Issue
Run isuue
### Your System Configuration
1. **OpenPose version**:1.3.0?

2. **General configuration**:
    - **Installation mode**: Ubuntu 16.04 LTS , CPU version with default installations procedures.

**Comment by gineshidalgo99** [comment]
If you changed the OP path location, you need to completely re-compile the whole OP code (i.e., starting by completely deleting the old build folder).

**Comment by MJUSER** [comment]
Thank u sir, i got my app fixed again. Keep supporting sir. doing a greate
Job


[image: MailTag]  Sent with MailTag <https://www.mailtag.io>
