### ISSUE TITLE
question about installation on MacOS

### ISSUE THREAD

**Issue by ShuminY** [CMU-Perceptual-Computing-Lab/openpose#764]
### Issue Summary
cmake configuration failed (Mac) and got below output by CMake GUI:
**Building CPU Only.
Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
        on your internet connection.
fatal: Not a git repository (or any of the parent directories): .git

Already on 'master'

Your branch is up to date with 'origin/master'.

Caffe will be built from source now.
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.12/Modules/ExternalProject.cmake:2525 (message):
  No download info given for 'openpose_caffe' and its source directory:

   /Users/yangshumin/AGV/OpenPose/openpose/3rdparty/caffe

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.12/Modules/ExternalProject.cmake:3100 (_ep_add_download_command)
  CMakeLists.txt:687 (ExternalProject_Add)

Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
Configuring incomplete, errors occurred!
See also "/Users/yangshumin/AGV/OpenPose/openpose/build/CMakeFiles/CMakeOutput.log".**

### Executed Command (if any)
cmake configure 

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. Latest clone from GitHub master branch

2. **General configuration**:
    - **Installation mode**: CMake(Mac)
    - **Operating system** (macOS 10.13.6):
    - **Release or Debug mode**? ( release):
    - Compiler (`gcc --version`): 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

   

4. **3rd-party software**:
    - **Caffe version**: not installed
    - **CMake version** 3.11.4:
    - **OpenCV version**: ?

6. If **CPU-only mode** issue:
    - **CPU brand & model**:intel i5
    - Total **RAM memory** available:8G

7. If **Python** API:
    - **Python version**: 2.7.15
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):1.14.3

**Comment by ShuminY** [comment]
I found the solution at [#423](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/423)

git cloning caffe to 3rdparty/ get this fixed.

**Comment by sdewailly** [comment]
Hi,
But caffe directory already exits, so how can you clone caffe?

Thx

**Comment by airman00** [comment]
Related issue I experienced on MacOSX 



If you get this error

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
  is not able to compile a simple test program.

```

You may need to run this in Terminal before you run your make command
`export PATH=$PATH:/opt/local/bin:/opt/local/sbin:/usr/bin/c++:/usr/bin/make
`
