### ISSUE TITLE
Run openpose on Movidius Neural Compute Stick

### ISSUE THREAD

**Issue by negarl** [CMU-Perceptual-Computing-Lab/openpose#767]
I want to run openpose on Movidius Neural Compute Stick (to get better performance). I want to know how exactly openpose use Caffe? And Can I use Movidius to run openpose?

**Comment by soulslicer** [comment]
it should be possible. There seems to be some tutorials online on using Caffe with the NCS. However, we are not experienced in the use of the Movidius NCS and we cannot help you there

**Comment by negarl** [comment]
I want you to explain to me how Openpose works with Caffe. One of the Movidius Neural Compute Stick frameworks is Caffe. MNCS gets a precomputed graph which is computed by train data. Has Openpose this graph?

**Comment by soulslicer** [comment]
OpenPose uses Caffe as its AI backend, and has the caffemodel and prototxt in the models folder. You can take a look at those

**Comment by negarl** [comment]
Thank you for helping me. In which file or files you read the network from caffemodel and prototxt files to estimate poses in new images?

**Comment by negarl** [comment]
Also, What is the output of the neural network?

**Comment by bigdimboom** [comment]
This is a very interesting topic. @negarl How do configure the stick?

**Comment by gzuroy** [comment]
I am doing the same things, any tutorial suggestion?

**Comment by negarl** [comment]
@bigdimboom It's very easy you can go to the Movidius website and see the steps of configuration, but I have a problem running Openpose with it.

**Comment by gaomomo** [comment]
> @bigdimboom It's very easy you can go to the Movidius website and see the steps of configuration, but I have a problem running Openpose with it.

@negarl hello,I also have a problem running Openpose on Movidius Neural Compute Stick 2,Did you finally run successfully？

**Comment by negarl** [comment]
> > @bigdimboom It's very easy you can go to the Movidius website and see the steps of configuration, but I have a problem running Openpose with it.
> 
> @negarl hello,I also have a problem running Openpose on Movidius Neural Compute Stick 2,Did you finally run successfully？

Hi! 
Unfortunately, no. I can't remember what was the problem very well but as far as I remember it was that Openpose uses a deep network which the stick couldn't run it. Maybe Stick 2 has the same problem. 
Good luck!

**Comment by royiluo** [comment]
> > @bigdimboom It's very easy you can go to the Movidius website and see the steps of configuration, but I have a problem running Openpose with it.
> 
> @negarl hello,I also have a problem running Openpose on Movidius Neural Compute Stick 2,Did you finally run successfully？

The Intel OpenVINO team has converted the OpenPose to the OpenVINO model format, and you can run OpenPose on NCS2 via OpenVINO.

Please check these links: 
https://github.com/openvinotoolkit/open_model_zoo/blob/develop/models/public/human-pose-estimation-3d-0001/description/human-pose-estimation-3d-0001.md
https://arxiv.org/pdf/1811.12004.pdf

Thanks
