### ISSUE TITLE
Openpose with blender

### ISSUE THREAD

**Issue by jdstech** [CMU-Perceptual-Computing-Lab/openpose#774]
Hey guys, I'm not sure if this is the right place for this, but under "Send us failure cases and feedback" it says to leave a comment if you have a feature request and this is the only way I knew how.

I'm trying to get openpose working in blender to determine the chin, neck, shoulders, wrists, ankles, and groin of a model for rigging, but the only way I've been able to do that is by rendering an image from blender and feeding that to openpose. The problem is that translating the coordinates obtained from openpose back into blender and having them line up properly is almost impossible. If there some way I could have openpose run off of the screen on my computer and try to line up the markers from there?

**Comment by soulslicer** [comment]
?

I assume you are trying to "rig" your model, so it doesn't have a skeleton structure to begin with. I am not sure what you mean by lining them up? Openpose takes in an image and produces the keypoints at the original location

**Comment by nyudeb** [comment]
1. Take screenshot of your model from blender [Ortho camera] - Face + Back + Right + Left
2. Process these images to OpenPose and save json files with "keypoint_scale 3" to have values between 0 and 1.
3. Get json files data and triangulate values to have the x, y, z results [ex : Face + Right | Face + Left | ...]

You will have to do some calculs to have the rights scaled results.
