### ISSUE TITLE
what's the workflow for input data in the GPU memory already

### ISSUE THREAD

**Issue by bigdimboom** [CMU-Perceptual-Computing-Lab/openpose#775]
I have data(video) that is in GPU memory already because I have done some processing with that video data. For now I have to download data back to CPU. I assume the library would upload data to GPU anyway. What's the workflow of applying openpose to GPU data without using "Producer" interface since cv::Mat is CPU code? Thanks.

**Comment by soulslicer** [comment]
Sorry, your question is not very clear. Could you give more details

**Comment by gineshidalgo99** [comment]
It must be normalized to Caffe format anyway, it is not an easy thing to do. You would have to normalize it following core/cvToOPInput.cpp
