### ISSUE TITLE
Cannot Use Multiple GPU's using pyopenpose

### ISSUE THREAD

**Issue by HidayatRahman** [CMU-Perceptual-Computing-Lab/openpose#776]
hi,
I am using pyopenpose, currently there is option available for just single gpu through the flag 
"num_gpu_start", through this flag i can set the gpu id, but the problem is using single gpu the processing speed is slow is there a way that i can use multiple gpus ? If there is how can i use multiple gpu's. Any suggestion would be appreciated.

Thanks is Advance,

**Comment by gineshidalgo99** [comment]
You're looking for `num_gpu`, anyway, OP uses by default all available GPUs.

**Comment by HidayatRahman** [comment]
@gineshidalgo99 i know about C++ but is there a way that i can run it on multiple gpus in parallel like one image will be processed by gpu 0, other by gpu 1 and so on.

thanks.

**Comment by soulslicer** [comment]
@HidayatRahman 

There is no concept of threads in Python due to GIL. That is how Python was designed. You can however construct multiple OpenPose objects in Python (and specify the GPU ID), and you can use the multiprocessing library to launch multiple processes to speed up inference.

**Comment by HidayatRahman** [comment]
hi @soulslicer 
When i use multi threading i get error 
The CPU/Gpu pointer data cannot be acessed from a different thread
here is my code structure
op1=openpose(param1)
op2=openpose(param2)

thread1 uses op1 to extract the key-points and thread 2 uses op2 to extract the key-points
Thanks in Advance,

**Comment by soulslicer** [comment]
you need to construct your objects in different threads. perhaps i can do a simple example some time in the future

**Comment by HidayatRahman** [comment]
hi @soulslicer 
i tried the same to construct the object in different threads but still i am getting the error, can you please elaborate it using a simple example
Thanks in advance,

**Comment by DevelopJoy** [comment]
@HidayatRahman   Did you solved this problem,Please tell me how to do

**Comment by LRuid** [comment]
> 你需要在不同的线程中构造你的对象。也许我可以在将来的某个时候做一个简单的例子
hi，i am using python's multiprocessing library.i run 4 process ,it not work ,as follows ,my code and error. 
```
from multiprocessing import Process
for i in range(4):
    p = Process(target=runing_openpose,args=(image_root,))
    p.start()
```
```
def runing_openpose(image_root):
    sys.path.append('/usr/local/python')
    from openpose import pyopenpose as op
    params = dict()
    params["model_folder"] = "MODELS"
    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()
    imagePaths = op.get_images_on_directory(image_root)
    for imagePath in imagePaths:
        datum = op.Datum()
        imageToProcess = cv2.imread(imagePath)
        datum.cvInputData = imageToProcess
        opWrapper.emplaceAndPop(op.VectorDatum([datum]))
        print("Body keypoints: \n" + str(datum.poseKeypoints))
```

> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> E1114 21:21:01.461006 21528 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.462309 21514 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.465152 21509 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.471258 21520 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.481060 21508 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.489166 21521 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.497902 21527 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.502249 21509 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.505977 21508 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.514278 21516 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.516794 21520 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.523866 21528 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.531649 21514 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> F1114 21:21:01.532974 21508 syncedmem.hpp:22] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

*** Check failure stack trace: ***
    @     0x7f64eab4c0cd  google::LogMessage::Fail()
    @     0x7f64eab4df33  google::LogMessage::SendToLog()
    @     0x7f64eab4bc28  google::LogMessage::Flush()

Then i run 2 process, it work . but i not specify GPU.` Auto-detecting all available GPUs...,`
What can I do to specify that process 1 uses GPU 0 and process 2 uses GPU 1?or other better way to use openpose. Please give me some reference . Thanks
> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
Body keypoints: 
[[[4.5617700e+02 2.5491418e+02 9.7750974e-01]
  [5.0641528e+02 2.9397977e+02 8.1965744e-01]
........
