### ISSUE TITLE
Could NOT find HDF5 (missing: HL) (found version "1.8.9")

### ISSUE THREAD

**Issue by ly-atdawn** [CMU-Perceptual-Computing-Lab/openpose#781]
### Issue Summary
When I build openpose, I always have the problem" Could NOT find HDF5 (missing: HL) (found version "1.8.9")", even though I have install HDF5 lib in /usr/local/hdf5, and in /usr/local/lib also have HDF5.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted

### Your System Configuration
1. **OpenPose version**: Latest GitHub code
2. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu)
    - **Operating system**: Ubuntu 14.04
    - **Release or Debug mode**: 
    - Compiler: 4.8.5
3. **Non-default settings**:
   None

4. **3rd-party software**:
    - **Caffe version**: 1.0.0
    - **CMake version**: 3.6.
    - **OpenCV version**: 3.0.0

5. If **GPU mode** issue:
    - **CUDA version** : 8.0
    - **cuDNN version**: 6.0.21
    - **GPU model** : Yes

**Comment by fzy308658** [comment]
Hi, do you solve this problem?  I met the same one and didn't know how to solve this.  Need your help!
