### ISSUE TITLE
Extrinsic Calibration for 2 cameras

### ISSUE THREAD

**Issue by ag2020** [CMU-Perceptual-Computing-Lab/openpose#784]
I am trying to do extrinsic calibration for 2 cameras in Openpose. When I run the calibration, it appears to work, outputting "Extrinsic Calibration Successful!". However, upon further look in the camera xml files, I find that the 3x4 camera matrix is something like this:

some_number some_number some_number NaN
some_number some_number some_number NaN
some_number some_number some_number NaN

However, the last column is supposed to be the x,y,z between the two cameras. Does anyone know why this might be happening? Thanks in advance.

**Comment by AdeV-Oly** [comment]
Somehow, somewhere, the matrix gets reshaped to a vector.

Say the 3x4 matrix is [A, B, C, D; E F G H; I J K L], then it's saved in the xml files as [A, B, C, D, E, F, G, H, I, J, K, L].
