### ISSUE TITLE
Demo very slow

### ISSUE THREAD

**Issue by sdewailly** [CMU-Perceptual-Computing-Lab/openpose#785]
### Issue Summary

Demo very slow after following the installing tutorial
### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

./build/examples/openpose/openpose.bin --video examples/media/video.avi

### OpenPose Output (if any)
a window with images but at really slow rate, it's never been greater than 0 fps...

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
As it was noticed, I unchecked the box to avoid installing Caffe in cmake-gui. Before I used brew to install it, then this step passed!
- Execution error
- Help wanted
I saw that a problem could be resolved with #423 by cloning caffe manually to pass the build stage.
First, by cloning openpose the directory caffe exists... and in fact, the problem at build stays.
- Question
I suppose the problem comes from caffe and its installing using brew (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#mac-osx-version) as openpose doesn't work properly.
So can you help me to build Caffe within cmake-gui?
- Enhancement / offering possible extensions / pull request / etc
Harmonization between #423 and (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#mac-osx-version)
- Other (type your own type)

### Your System Configuration
1. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
1.3.0

2. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
cmake-gui
    - **Operating system** (`lsb_release -a` in Ubuntu): macOS High Sierra 10.13.6
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 
Enterprise Update 3, VS2017 community, ... (Windows); ...?
I launched make -j'nproc'
3. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
Default from brew
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

3.4.2

5. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

6. If **CPU-only mode** issue: none
    - **CPU brand & model**:i5
    - Total **RAM memory** available:8GB

7. If **Python** API:
    - **Python version**: 2.7, 3.7, ...? 3
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

8. If **Windows** system:
    - Portable demo or compiled library?

9. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

0 fps

**Comment by gineshidalgo99** [comment]
Could you try COCO instead of BODY_25? BODY_25 seems to be super slow in CPU version.

**Comment by sdewailly** [comment]
Hello,

I generate the build once again with the download option COCO set, then compile.
To try it I launched ./build/examples/openpose/openpose.bin -model_pose='COCO' --video examples/media/video.avi
But there were no better results (very slow).

Thanks for your help!

**Comment by gineshidalgo99** [comment]
The expected speed (shown in the OpenPose doc) of that one is about 0.3 FPS (COCO), rather than 0.1 FPS (BODY_25). Which speed are you getting?

**Comment by gineshidalgo99** [comment]
That's expected. If you desire faster speed, reduce the `net_resolution` (check the doc for details)

**Comment by sdewailly** [comment]
Hi @gineshidalgo99 ,

I made a launch of the video demo with profiling speed flag, in order to have more accurate measures:
macbook-pro-de-sebastien-2:openpose sebast$ ./build/examples/openpose/openpose.bin --profile_speed=12 --video examples/media/video.avi
Starting OpenPose demo...
Starting thread(s)...
31.062490 msec at in /Users/sebastien 1/development/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():70
0.001030 msec at in /Users/sebastien 1/development/openpose/include/openpose/thread/wIdGenerator.hpp:work():69
0.004955 msec at in /Users/sebastien 1/development/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():67
6.691391 msec at in /Users/sebastien 1/development/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():64
24.076623 msec at in /Users/sebastien 1/development/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():66
36332.615372 msec at in /Users/sebastien 1/development/openpose/include/openpose/pose/wPoseExtractor.hpp:work():91
20.803803 msec at in /Users/sebastien 1/development/openpose/include/openpose/pose/wPoseRenderer.hpp:work():72
23.449569 msec at in /Users/sebastien 1/development/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():62
0.899657 msec at in /Users/sebastien 1/development/openpose/include/openpose/gui/wGuiInfoAdder.hpp:work():65
79.902224 msec at in /Users/sebastien 1/development/openpose/include/openpose/gui/wGui.hpp:workConsumer():80


Please notice the duration of wPoseExtractor.hpp:work() thread of 36 seconds...
Thx in advance

**Comment by gineshidalgo99** [comment]
That's normal for BODY_25, but the COCO  model should be less than 1 second. Could you confirm this? Thanks. (BODY_25 is faster in GPU than COCO, but COCO is much much faster than BODY_25 in CPU version)

**Comment by sdewailly** [comment]
With COCO not faster than a frame every 20 seconds.
 ./build/examples/openpose/openpose.bin --profile_speed 10 --model_pose COCO --video examples/media/video.avi
Starting OpenPose demo...
Starting thread(s)...
^C

bye

**Comment by gineshidalgo99** [comment]
Sorry, I did not realize you are in Mac.

MKL-Caffe (CPU version) provides about 0.3 FPS in Ubuntu, but non-MKL Caffe (in both CPU Ubuntu and Mac) are as slow as you are pointing out. So it's the normal speed.

I think MKL Caffe is not supported in Mac. If you were able to install MKL-Caffe, and link OpenPose against it, then you should solve this speed issue and go up to about 0.1-0.3 FPS.

**Comment by yavana** [comment]
> With COCO not faster than a frame every 20 seconds.
> ./build/examples/openpose/openpose.bin --profile_speed 10 --model_pose COCO --video examples/media/video.avi
> Starting OpenPose demo...
> Starting thread(s)...
> ^C
> 
> bye

A picture takes 50 seconds on my computer.

**Comment by gineshidalgo99** [comment]
@yavana If you look for help, please include your hw configuration as the GitHub issue template indicates.

**Comment by tarchounaa** [comment]
> Guys I'm using a GTX 1080 and manage to get 45/50fps on other pose estimation systems based on Cuda but only up to 12fps on OpenPose. Is this expected or am I doing something wrong?

Please can you tell me which one did you use i am faceing the same problem with openPose very slow and i have no idea how to make it faster or find other library

**Comment by rajhlinux** [comment]
On FreeBSD 13.1 using:

`$ /usr/home/user/openpose/build/examples/openpose/openpose.bin --camera 4
`

It's super slow, like video freezes then updates after every 10mins... (at least it works on FreeBSD :))

**Comment by ShiraGavriel** [comment]
Can OpenPose be sped up?
 Currently, when using a CPU, it takes around 6 seconds to extract keypoints from a single image. 
Has there been any recent progress in improving its performance?
