### ISSUE TITLE
fatal error LNK1181:

### ISSUE THREAD

**Issue by BalajiB3663** [CMU-Perceptual-Computing-Lab/openpose#79]
cannot open input file '..\..\3rdparty\caffe\dependencies\libraries_v140_x64_py27_1.1.0\libraries\x64\vc14\lib\opencv_calib3d310.lib'

"opencv_calib3d310.lib"-- exactly help me, what this library role in the project. As the name contains 3d little confused in resolving the error.
I run the same project in my colleague m/c which as a graphic card of Nvidia no error.

After release complete not able to find .exe files.

**Comment by gineshidalgo99** [comment]
Use the issue template to type an issue, so I can know your hardware and software before answering. It is not there to be deleted...

**Comment by gyc990326** [comment]
It seem that your dependencies package(libraries_v140_x64_py27_1.1.0.tar.gz) is not downloaded correctly. Maybe it's the problem of your network? You can try to rerun the build-win.cmd in caffe folder

**Comment by gineshidalgo99** [comment]
Given there is no answer, I'll assume it was solved.
