### ISSUE TITLE
Cuda check failed (11 vs. 0): invalid argument

### ISSUE THREAD

**Issue by rebider** [CMU-Perceptual-Computing-Lab/openpose#795]
what happen in this error??

win10 vs2015 cuda8.0 

Starting OpenPose demo...
Desired webcam resolution 1280x720 could not being set. Final resolution: 1024x768 in G:\\openpose-master\src\openpose\producer\webcamReader.cpp:op::WebcamReader::WebcamReader():31
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...

Error:
Cuda check failed (11 vs. 0): invalid argument

Coming from:
- G:\openpose-master\src\openpose\pose\poseGpuRenderer.cpp:op::PoseGpuRenderer::renderPose():81
- G:\openpose-master\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- G:\openpose-master\src\openpose\pose\poseGpuRenderer.cpp:op::PoseGpuRenderer::renderPose():193
- G:\openpose-master\include\openpose/pose/wPoseRenderer.hpp:op::WPoseRenderer<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > >::work():81
- G:\openpose-master\include\openpose/thread/subThread.hpp:op::SubThread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::workTWorkers():135
- G:\openpose-master\include\openpose/thread/subThreadQueueInOut.hpp:op::SubThreadQueueInOut<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::work():96
- G:\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::threadFunction():204

**Comment by rebider** [comment]
sweet god ,i got it! hey hey

**Comment by ekim1423** [comment]
Do you know what the problem was?

**Comment by senshin998** [comment]
the same problem  ,please help

**Comment by skyoung** [comment]
same problem. Anyone gives a hint?

**Comment by nanHeK** [comment]
the same problem ,please help @rebider
