### ISSUE TITLE
3D Reconstruction With Saved RGB Video

### ISSUE THREAD

**Issue by kratliff7** [CMU-Perceptual-Computing-Lab/openpose#797]
Hi all, I am looking to do 3D reconstruction with openpose using 3 previously saved videos from different angles. When looking through the documentation, I could only find commands for using live feed from cameras. I was just wondering if it is possible to link the system to videos that already exist, and whether the code needs to be rewritten to compensate for the different camera type as detailed in the documentation. Thanks for any help you can give!

System and software information - Windows Server 2008 R2 with VS 2015 and the latest commit of openpose. Installed with the full Cmake installation using CPU_only. The 3D construction model was added when the program was built. 32 available gigs of ram and  an Intel i7 @ 3.40 GHz, 4 core.

**Comment by dimkadimon** [comment]
I am also very much interested in this. Also do the cameras need to be calibrated first?

I have noticed that there is a way to read in stereo video (or images), but it is not clear how to make such stereo video from multiple non-stereo videos. See 3D reconstruction step 4 from here:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#quick-start

**Comment by awm-nchaumont** [comment]
@kratliff7 and @dimkadimon , I am also interested in doing something very similar to what you guys are trying to achieve.

FYI, there are a few pointers in the doc:
in PoseTriangulation.cpp/reconstructArrayThread ~l.338 there is a check that says:
 error("Only 1 camera detected. The 3-D reconstruction module can only be used with > 1 cameras"

I'm going to try if I can use 2 non-FLIR cameras put side-by-side...
Anyone please ping me if you have any news about this!

**Comment by karfly** [comment]
I'm also trying to run 3d-reconstruction from multiple muliview videos. I found the parameter `--3d_views` in `openpose.cpp` which says:
`Complementary option to `--image_dir` or `--video`. OpenPose will read as many images per iteration, allowing tasks such as stereo camera processing (`--3d`). Note that `--camera_parameters_folder` must be set. OpenPose must find as many `xml` files in the parameter folder as this number indicates`.

@gineshidalgo99, is it exactly what we want? If yes, what structure of the folder (given as `--3d_views` parameter) must it be?

**Comment by yirenpingsheng** [comment]
Hi, I'm also on this issue. Maybe we should modify the original cpp files([https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/984]) But I am afraid I cannot work it out.
Does anyone has achieved this function?

**Comment by Siba-07** [comment]
@kratliff7 @dimkadimon @awm-nchaumont @karfly @FrancescoRossi1987 Did you find anything regarding this? I am interested to know how you proceeded.
