### ISSUE TITLE
Error Compiling OpenPose

### ISSUE THREAD

**Issue by felipheggaliza** [CMU-Perceptual-Computing-Lab/openpose#8]
CXX src/openpose/core/array.cpp
CXX src/openpose/core/nmsCaffe.cpp
CXX src/openpose/core/resizeAndMergeCaffe.cpp
src/openpose/core/array.cpp: In member function ‘void op::Array<T>::reset(const std::vector<int>&)’:
src/openpose/core/array.cpp:166:28: error: ‘accumulate’ is not a member of ‘std’
                 mVolume = {std::accumulate(sizes.begin(), sizes.end(), 1ul, std::multiplies<size_t>())};
                            ^
compilation terminated due to -Wfatal-errors.
Makefile:471: recipe for target '.build_release/src/openpose/core/array.o' failed
make: *** [.build_release/src/openpose/core/array.o] Error 1
make: *** Waiting for unfinished jobs....

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

**Comment by gineshidalgo99** [comment]
If you add `#include <numeric>` at the top of `src/openpose/core/array.cpp`, does it compile? (If so, I will add it to the file for new users). Thanks!

**Comment by felipheggaliza** [comment]
It seems the bug on array.cpp was fixed by adding #include <numeric> to the beginning of the file, but I also had to do the same solutions for src/openpose/core/netCaffe.cpp

Now I am getting new error:

------------------------- Compiling OpenPose -------------------------
CXX src/openpose/pose/poseExtractorCaffe.cpp
CXX src/openpose/pose/bodyPartConnectorCaffe.cpp
CXX src/openpose/pose/defineTemplates.cpp
CXX src/openpose/experimental/hand/handExtractor.cpp
CXX src/openpose/experimental/hand/defineTemplates.cpp
CXX src/openpose/experimental/face/faceExtractor.cpp
CXX src/openpose/experimental/face/defineTemplates.cpp
CXX src/openpose/wrapper/defineTemplates.cpp
CXX src/openpose/core/nmsCaffe.cpp
CXX src/openpose/core/resizeAndMergeCaffe.cpp
CXX src/openpose/core/netCaffe.cpp
CXX src/openpose/core/defineTemplates.cpp
CXX src/openpose/core/keyPointScaler.cpp
CXX src/openpose/core/cvMatToOpOutput.cpp
CXX src/openpose/core/renderer.cpp
CXX src/openpose/core/scaleKeyPoints.cpp
CXX src/openpose/core/cvMatToOpInput.cpp
NVCC src/openpose/pose/poseRenderGpu.cu
NVCC src/openpose/pose/bodyPartConnectorBase.cu
NVCC src/openpose/experimental/hand/handRenderGpu.cu
NVCC src/openpose/experimental/face/faceRenderGpu.cu
NVCC src/openpose/core/resizeAndMergeBase.cu
NVCC src/openpose/core/nmsBase.cu
CXX examples/openpose/rtpose.cpp
^Cnvcc error   : 'g++' died due to signal 2 
Makefile:471: recipe for target '.build_release/examples/openpose/rtpose.o' failed
make: *** [.build_release/examples/openpose/rtpose.o] Interrupt
Makefile:477: recipe for target '.build_release/cuda/src/openpose/core/nmsBase.o' failed
make: *** [.build_release/cuda/src/openpose/core/nmsBase.o] Error 2
Makefile:477: recipe for target '.build_release/cuda/src/openpose/pose/poseRenderGpu.o' failed
make: *** [.build_release/cuda/src/openpose/pose/poseRenderGpu.o] Interrupt
Makefile:477: recipe for target '.build_release/cuda/src/openpose/core/resizeAndMergeBase.o' failed
make: *** [.build_release/cuda/src/openpose/core/resizeAndMergeBase.o] Interrupt

**Comment by gineshidalgo99** [comment]
That `^Cnvcc error : 'g++' died due to signal 2` line, `^C` happens when the user manually stops the compilation (I am not aware of `^C` being used on non-user activities). Can you perform `make clean` in both the OpenPose and 3rdparty/caffe/ folders and try again? Thanks!

**Comment by felipheggaliza** [comment]
Now everything compiled successfully!

Thank you very much!

------------------------- OpenPose Installed -------------------------

------------------------- Caffe and OpenPose Installed -------------------------

**Comment by yeechongyeung** [comment]
Compile Caffe and OpenPose by running these lines:

### Install Caffe ###
cd 3rdparty/caffe/
# Select your desired Makefile file (run only one of the next 4 commands)
cp Makefile.config.Ubuntu14_cuda_7.example Makefile.config # Ubuntu 14, cuda 7
cp Makefile.config.Ubuntu14.example Makefile.config # Ubuntu 14, cuda 8
cp Makefile.config.Ubuntu16_cuda_7.example Makefile.config # Ubuntu 16, cuda 7
cp Makefile.config.Ubuntu16.example Makefile.config # Ubuntu 16, cuda 8
# Change any custom flag from the resulting Makefile.config (e.g. OpenCV 3, Atlas/OpenBLAS/MKL, etc.)
# Compile Caffe
make all -j${number_of_cpus} && make distribute -j${number_of_cpus}

### Install OpenPose ###
cd ../../models/
./getModels.sh # It just downloads the Caffe trained models
cd ..
# Same file cp command as the one used for Caffe
cp Makefile.config.Ubuntu14_cuda_7.example Makefile.config
# Change any custom flag from the resulting Makefile.config (e.g. OpenCV 3, Atlas/OpenBLAS/MKL, etc.)
make all -j${number_of_cpus}

------------------------- Compiling OpenPose Error -------------------------

.build_release/lib/libopenpose.so：对‘caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)’  Undefined reference
.build_release/lib/libopenpose.so：对‘caffe::Net<float>::blob_by_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’ Undefined reference
.build_release/lib/libopenpose.so：对‘google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()’ Undefined reference
.build_release/lib/libopenpose.so：对‘caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*)’ Undefined reference
collect2: Error：ld return 1
make: *** [.build_release/examples/tutorial_thread/4_user_input_processing_output_and_datum.bin] Error 1

**Comment by gineshidalgo99** [comment]
@yeechongyeung message completely unrelated with the error this issue discuss. I deleted it. Please, post it in a new issue thread.

**Comment by fmnoori** [comment]
Hi folks,
I am getting some sort of similar error, but not exactly the same.

CXX src/openpose/producer/videoReader.cpp
CXX src/openpose/producer/producer.cpp
CXX src/openpose/producer/imageDirectoryReader.cpp
CXX src/openpose/producer/videoCaptureReader.cpp
CXX src/openpose/producer/ipCameraReader.cpp
CXX src/openpose/producer/defineTemplates.cpp
CXX src/openpose/producer/webcamReader.cpp
CXX src/openpose/gui/frameDisplayer.cpp
CXX src/openpose/gui/guiInfoAdder.cpp
CXX src/openpose/gui/gui.cpp
CXX src/openpose/gui/defineTemplates.cpp
CXX src/openpose/pose/poseRenderer.cpp
CXX src/openpose/pose/bodyPartConnectorCaffe.cpp
CXX src/openpose/pose/renderPose.cpp
CXX src/openpose/pose/poseExtractor.cpp
CXX src/openpose/pose/poseParameters.cpp
CXX src/openpose/pose/poseExtractorCaffe.cpp
CXX src/openpose/pose/poseCpuRenderer.cpp
CXX src/openpose/pose/poseGpuRenderer.cpp
CXX src/openpose/pose/poseParametersRender.cpp
CXX src/openpose/pose/bodyPartConnectorBase.cpp
In file included from ./include/openpose/utilities/errorAndLog.hpp:9:0,
                 from ./include/openpose/core/common.hpp:13,
                 from ./include/openpose/pose/bodyPartConnectorBase.hpp:4,
                 from src/openpose/pose/bodyPartConnectorCaffe.cpp:4:
src/openpose/pose/bodyPartConnectorCaffe.cpp: In member function ‘virtual void op::BodyPartConnectorCaffe<T>::Forward_gpu(const std::vector<caffe::Blob<T>*>&, op::Array<T>&, op::Array<T>&)’:
src/openpose/pose/bodyPartConnectorCaffe.cpp:178:24: error: ‘top’ was not declared in this scope
                 UNUSED(top);
                        ^
./include/openpose/core/macros.hpp:23:39: note: in definition of macro ‘UNUSED’
 #define UNUSED(unusedVariable) (void)(unusedVariable)
                                       ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/pose/bodyPartConnectorCaffe.o' failed
make: *** [.build_release/src/openpose/pose/bodyPartConnectorCaffe.o] Error 1
make: *** Waiting for unfinished jobs....
src/openpose/pose/poseGpuRenderer.cpp:65:73: warning: unused parameter ‘scaleInputToOutput’ [-Wunused-parameter]
                                                             const float scaleInputToOutput,

**Comment by gineshidalgo99** [comment]
Please use the default installation steps, that could only happen if you are omitting something or trying to change a non-editable parameter

**Comment by fmnoori** [comment]
Thank you, I missed 1 step,
Now everything is fine. I am trying to get models from Yesterday.
but it is showing this 

ap4isr@casir-impep:~/new/openpose/models$ bash ./getModels.sh
--2018-01-17 10:18:57--  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Resolving posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)... 128.2.176.37
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Connection timed out.
Retrying.

--2018-01-17 10:21:07--  (try: 2)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Connection timed out.
Retrying.

--2018-01-17 10:23:19--  (try: 3)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Connection timed out.
Retrying.

--2018-01-17 10:25:34--  (try: 4)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Connection timed out.
Retrying.

--2018-01-17 10:27:48--  (try: 5)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... failed: Connection timed out.
Retrying.

--2018-01-17 10:30:04--  (try: 6)  http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/coco/pose_iter_440000.caffemodel
Connecting to posefs1.perception.cs.cmu.edu (posefs1.perception.cs.cmu.edu)|128.2.176.37|:80... ^C
------------------------------------------


My internet is working perfectly,
Is there any other way to download models? Thankyou
Regards,

**Comment by fmnoori** [comment]
Thank you! 
I missed 1 step. Everything is working fine :+1:
