### ISSUE TITLE
How to run 3d module using different brand cameras?

### ISSUE THREAD

**Issue by whycn** [CMU-Perceptual-Computing-Lab/openpose#800]
Hi there,

I'm really new to this. Now I have 3 logitech cameras. Is it possible to use them for 3d reconstruction? I notice the tutorial:

Copy any of the examples/tutorial_wrapper/*.cpp examples (we recommend 2_user_synchronous.cpp).
Modify WUserInput and add your custom code there. Your code should fill Datum::name, Datum::cameraMatrix, Datum::cvInputData, and Datum::cvOutputData (fill cvOutputData = cvInputData).

But I still have these qustions:

1. When using flir cameras, it seems to read and process the synchronous images from several flir cameras in spinnakerWrapper.cpp. Is it from spinnaker sdk? If I want to use logitech cameras, should I also write a script like this?

2. I can't find the place to implement the functions in spinnakerWrapper.cpp like acquireImages(). So if I use my own cameras, where should I read and save the images (in WUserInput class?)?

3. What is the flags should I set to run 3d modules without flir camera? maybe --3d 1   ----number_people_max 1?

4. Do you have a plan to add 3d reconstruction to python module?

Thank you in advance.

**Comment by nayha-auradkar** [comment]
@whycn did you ever figure out this issue?
