### ISSUE TITLE
Artifacts on the floor 

### ISSUE THREAD

**Issue by dvdobrovolskiy** [CMU-Perceptual-Computing-Lab/openpose#801]
Got too many wrong positives on the boxing ring floor

https://youtu.be/mv1KVYTS15I

![sp_000000000000_rendered](https://user-images.githubusercontent.com/7299951/44781696-9e963400-ab74-11e8-80ca-ebe4f219ba90.png)
![sp_000000000001_rendered](https://user-images.githubusercontent.com/7299951/44781703-a35ae800-ab74-11e8-9a29-42c14033de21.png)
![sp_000000000003_rendered](https://user-images.githubusercontent.com/7299951/44781708-a8b83280-ab74-11e8-91df-fb766ff47314.png)
![sp_000000000016_rendered](https://user-images.githubusercontent.com/7299951/44781720-af46aa00-ab74-11e8-8d1c-bea3aebd7c88.png)
![sp_000000000026_rendered](https://user-images.githubusercontent.com/7299951/44781741-b79ee500-ab74-11e8-82f3-c4b844b65cd2.png)
![sp_000000000030_rendered](https://user-images.githubusercontent.com/7299951/44781754-bec5f300-ab74-11e8-95bc-ad3ccaa193a9.png)

command
.\bin\OpenPoseDemo.exe -video "test.mp4" -no_gui_verbose -write_video out.avi  -display 0 -write_images img\ --net_resolution "1312x736"

**Comment by gineshidalgo99** [comment]
There is no trivial solution here. You can increase the minimum threshold to be rendered, but it might also block real people. COCO challenge is biased towards many (true and false) positives

**Comment by phamdat09** [comment]
Hello, I have the same issue.
How can I increase the minimum threshold in the code ?
Thanks
