### ISSUE TITLE
OpenCV error while running openpose.bin

### ISSUE THREAD

**Issue by gamenn** [CMU-Perceptual-Computing-Lab/openpose#803]
I followed the instructions for building OpenPose on my Ubuntu 16.04 machine within a conda environment. It built without errors. But, when I try to run "./build/examples/openpose/openpose.bin --video examples/media/video.avi", I get the following error:

```
Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file /tmp/build/80754af9/opencv_1512491966934/work/modules/highgui/src/window.cpp, line 593
```
When I try to install "libgtk2.0-dev" and "pkg-config" as it suggests, I get the message saying the machine already has their newest versions.

Any idea how to make the error go away so that I can run OpenPose?
Thanks.

**Comment by gineshidalgo99** [comment]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
3. **No** questions about **3rd party libraries**.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
