### ISSUE TITLE
openposedemo cannot run on GPU

### ISSUE THREAD

**Issue by MadCreeper** [CMU-Perceptual-Computing-Lab/openpose#804]
### Issue Summary

although I have installed  CUDA and cudnn, the demo won't work on my GTX 1050, but runs on my CPU.
and thus the FPS is very low, about 2-3 fps.
### Executed Command (if any)

.\OpenPosedemo.exe --image_dir examples\sit\ --render_pose 1 --net_resolution "320x176" --write_images examples\sit_out\ --write_json examples/sit_data/

CUDA version 8.0, cudnn v5.1, gpu model GTX 1050
sorry for poor English

**Comment by gineshidalgo99** [comment]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
3. **No** questions about **3rd party libraries**.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
