### ISSUE TITLE
Compiling Caffe Error

### ISSUE THREAD

**Issue by JasOlean** [CMU-Perceptual-Computing-Lab/openpose#806]
CXX src/caffe/util/hdf5.cpp
CXX src/caffe/util/upgrade_proto.cpp
CXX src/caffe/util/im2col.cpp
examples/cpp_classification/classification.cpp: In function ‘int main(int, char**)’:
examples/cpp_classification/classification.cpp:250:17: error: ‘imread’ is not a member of ‘cv’
   cv::Mat img = cv::imread(file, -1);
                 ^
Makefile:586: recipe for target '.build_release/examples/cpp_classification/classification.o' failed
make: *** [.build_release/examples/cpp_classification/classification.o] Error 1
make: *** Waiting for unfinished jobs....

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.

when I install openpose "bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh", 
I got this error. how can i solve this? I have already install opencv  using command "sudo apt-get install libopencv-dev".

**Comment by gineshidalgo99** [comment]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
3. **No** questions about **3rd party libraries**.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
