### ISSUE TITLE
Example in demo_overview.md needs to be updated

### ISSUE THREAD

**Issue by Quasimondo** [CMU-Perceptual-Computing-Lab/openpose#81]
The video example on demo_overview.md throws  
> ERROR: unknown command line flag 'write_json'

The correct argument is --write_keypoint_json
so the example should be changed to:
`./build/examples/openpose/openpose.bin --video examples/media/video.avi --num_gpu 2 --write_video output/result.avi --write_keypoint_json output/
`

**Comment by shiangyoung** [comment]
Is there any example of execution code to generate xml files?

**Comment by gineshidalgo99** [comment]
@Quasimondo Thank you! Just updated.
@shiangyoung Please check the doc https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/demo_overview.md --> `write_keypoint`
