### ISSUE TITLE
Python API error

### ISSUE THREAD

**Issue by JasOlean** [CMU-Perceptual-Computing-Lab/openpose#810]
~/openpose/build/examples/tutorial_python$ python3 1_extract_pose.py
OpenPose Library Python Wrapper

Error:
Prototxt file not found: /usr/local/python/openpose/../../../models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /home/khin/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():51
- /home/khin/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():131
- /home/khin/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /home/khin/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():94
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Prototxt file not found: /usr/local/python/openpose/../../../models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the same directory where the `model` folder is located.
	3. Using paths with spaces.

Coming from:
- /home/khin/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():51
- /home/khin/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():131
- /home/khin/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /home/khin/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():94

Aborted (core dumped)

there is a prototxt file, and already downloaded all trained models. How can I fix this?

**Comment by StrongRay** [comment]
i made 2 modifications to the python example:
 
params["net_resolution"] = "**160x80**"
params["default_model_folder"] = "**/home/xxxx/openpose/models/**" 

and it worked fine.  My system ( UBUNTU 18.04.01 LTS, CuDNN 7.2.1, Cuda 9.0.176, Tensorflow 1.9.0, gcc 6.4.0, OpenCV 3.4.0, Nvidia 390.87 )

![screenshot from 2018-09-03 18-32-25](https://user-images.githubusercontent.com/42715739/44984904-9e4ccd00-afa8-11e8-92a9-76114b09e816.png)

**Comment by JasOlean** [comment]
how can I detect hand keypoints like this? because in default model folder, i cannot choose hand model to detect hand keypoints.

**Comment by yavana** [comment]
> how can I detect hand keypoints like this? because in default model folder, i cannot choose hand model to detect hand keypoints.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/21eac3784c608a8b25162cae058cfb526f4cd673
