### ISSUE TITLE
Are there plans for the python API supporting also the Hands and Face models?

### ISSUE THREAD

**Issue by jhaux** [CMU-Perceptual-Computing-Lab/openpose#812]
### Type of Issue

- Question (see title)

It would be a very helpful feature of the python wrapper to also output the hand and/or face keypoints for us, as we currently label lots of data in a python pipeline. We thought about adding this functionality ourselves, but had to realize, that this might be more complicated that what we are used to do.

If this feature is currently not planned, could you point me to some code, showing, how the Hand and Face models can be used in c++? Ideally I would like to be able to enhance the `openpose/python/openpose/_openpose.cpp` such that I can later pass a `--hands` or `--face` flag to my python script.

Best, Johannes

**Comment by yavana** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/786/commits/21eac3784c608a8b25162cae058cfb526f4cd673



Is this a solution?

**Comment by jhaux** [comment]
That looks great, thanks!

**Comment by yavana** [comment]
> That looks great, thanks!

I tried but failed,how about you.

**Comment by jhaux** [comment]
I haven't had the time yet. I will as soon as possible, but that will probably be in a few weeks.

**Comment by yoon28** [comment]
> [21eac37](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/21eac3784c608a8b25162cae058cfb526f4cd673)
> 
> Is this a solution?

Yes, it works fine when at least one person exists in a image. 
It fails when the image (video) contains no person.
I think it needs some codes for that case.

**Comment by yavana** [comment]
> > [21eac37](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/21eac3784c608a8b25162cae058cfb526f4cd673)
> > Is this a solution?
> 
> Yes, it works fine when at least one person exists in a image.
> It fails when the image (video) contains no person.
> I think it needs some codes for that case.
> 
> To solve the exceptional case, I insert code "if hands_array.size > 0:" before the line 128 in openpose.py. This prevents 'getHandOutputs' from execution when a image has no person.

I tried several times on different machines, and finally failed.

**Comment by lukaspistelak** [comment]
i need face thanks!

**Comment by JasOlean** [comment]
21eac37 is ok for hand keypoints detection?
Is there anyone update for answer for this?

**Comment by yoon28** [comment]
> [21eac37](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/21eac3784c608a8b25162cae058cfb526f4cd673) is ok for hand keypoints detection?
> Is there anyone update for answer for this?

yes, it works. change the source codes and build them.

**Comment by yavana** [comment]
> them

When there are many people, how do we know who the hand is?

**Comment by yavana** [comment]
> > [21eac37](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/21eac3784c608a8b25162cae058cfb526f4cd673) is ok for hand keypoints detection?
> > Is there anyone update for answer for this?
> 
> yes, it works. change the source codes and build them.

When there are many people, how do we know whose hands are?
