### ISSUE TITLE
OpenPoseConfig.cmake includes openpose and caffe folders

### ISSUE THREAD

**Issue by ocanevet** [CMU-Perceptual-Computing-Lab/openpose#814]
When using openpose as an external library via cmake, like
```bash
cmake -DCMAKE_INSTALL_PREFIX=/my/path/to/openpose/install ..
```
and using
```cmake
FIND_PACKAGE(OpenPose)
INCLUDE_DIRECTORIES(${OpenPose_INCLUDE_DIRS})
```
we get error like
```
fatal error: openpose/core/headers.hpp: No such file or directory
```
because at lines
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/5401f668e5bccee7c67fad914e05c124cbe65a5f/cmake/OpenPoseConfig.cmake.in#L8
and
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/5401f668e5bccee7c67fad914e05c124cbe65a5f/cmake/OpenPoseConfig.cmake.in#L13
`openpose` and `caffe` folders are included. We cannot do
```c++
#include <openpose/core/headers.hpp>
```
Workaround can be
```cmake
INCLUDE_DIRECTORIES(${OpenPose_INCLUDE_DIRS}/..)
```
but in the OpenPoseConfig.cmake, it should be
```cmake
set(Caffe_INCLUDE_DIRS "${_prefix}/include/")
set(OpenPose_INCLUDE_DIRS "${_prefix}/include/")
```

**Comment by encoder1995** [comment]
Hey @gineshidalgo99 , I would like to work on this issue.

**Comment by gineshidalgo99** [comment]
It should be fixed now thanks to @encoder1995 pull request that was already merged. #815.

Let me know otherwise. THanks
