### ISSUE TITLE
"Not Responding" when running the demo

### ISSUE THREAD

**Issue by ekim1423** [CMU-Perceptual-Computing-Lab/openpose#816]
### Issue Summary
The popped-up window just get stuck on black screen saying "not responding".

I'm able to get the images from webcam without any openpose computation; but when running the openpose demo, the screen gets freeze and not responding

Please help me!

### Executed Command (if any)
bin\OpenPoseDemo.exe --num_gpu=1 --video=examples\media\video.avi
bin\OpenPoseDemo.exe --video=examples\media\video.avi

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **OpenPose version**: f49e184

2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Window 10
    - **Release or Debug mode**: Release
    - **Compiler**: Visual Studio 2015 - Visual C++ 14.0

3. **Non-default settings**:
    - **3-D Reconstruction module added**? NO
    - Any other custom CMake configuration with respect to the default version?  NO

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : 3.12.1
    - **OpenCV version**:  OpenPose default

5. If **GPU mode** issue:
    - **CUDA version**:  8.0.61
    - **cuDNN version**: 6.0.21
    - **GPU model** : NVIDIA TITAN V and NVIDIA QUADRO P600

8. If **Windows** system:
    - Portable demo or compiled library? Demo

**Comment by gineshidalgo99** [comment]
Note: Titan V requires CUDA 9 (and cuDNN valid for CUDA 9), otherwise, it might not work.

**Comment by adfi** [comment]
@ekim1423 did you manage to fix this, I'm running into the same issue.

**Comment by adfi** [comment]
Ok never mind, it's just really really slow.

**Comment by tech-gh** [comment]
We get this issue too when trying to run on a 2080 Ti with CUDA 10 on Windows 10 64 bit.  Works fine on 1060 and 1080.  Tried binary release as well as building with VS2015 and VS2017.  @gineshidalgo99  or @EunSolKim-Nano do you know what the fix is? Thanks!
