### ISSUE TITLE
Compiling error - Ubuntu  - cannot convert ‘std::array<unsigned int, 6ul>’ to ‘unsigned int’

### ISSUE THREAD

**Issue by handale88** [CMU-Perceptual-Computing-Lab/openpose#82]
### Issue summary
When I compile openpose with hand added source, I get compiling errors.

### Executed command (if any)
in both way,
./make all -j8
./install_caffe_and_openpose.sh

### OpenPose output (if any)

CXX src/openpose/face/faceExtractor.cpp
CXX src/openpose/face/defineTemplates.cpp
CXX src/openpose/core/netCaffe.cpp
CXX src/openpose/core/resizeAndMergeCaffe.cpp
CXX src/openpose/core/nmsCaffe.cpp
CXX src/openpose/core/defineTemplates.cpp
CXX src/openpose/hand/handDetector.cpp
CXX src/openpose/hand/handExtractor.cpp
src/openpose/hand/handDetector.cpp: In function ‘std::array<op::Rectangle<float>, 2ul> op::getHandFromPoseIndexes(const op::Array<float>&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, float)’:
src/openpose/hand/handDetector.cpp:63:52: warning: missing initializer for member ‘std::array<op::Rectangle<float>, 2ul>::_M_elems’ [-Wmissing-field-initializers]
             return std::array<Rectangle<float>, 2>{};
                                                    ^
src/openpose/hand/handDetector.cpp: In constructor ‘op::HandDetector::HandDetector(op::PoseModel)’:
src/openpose/hand/handDetector.cpp:68:117: error: cannot convert ‘std::array<unsigned int, 6ul>’ to ‘unsigned int’ in initialization
         mPoseIndexes{getPoseKeypoints(poseModel, {"LWrist", "LElbow", "LShoulder", "RWrist", "RElbow", "RShoulder"})}
                                                                                                                     ^
compilation terminated due to -Wfatal-errors.
make: *** [.build_release/src/openpose/hand/handDetector.o] Error 1
make: *** Waiting for unfinished jobs....

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu 14.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): cuda v8.0.61
**cuDNN version**:cudnn 5.1
**GPU model** (`nvidia-smi`):375.39 / GeForce GTX 1080
**Caffe version**: Default from OpenPose
**OpenCV version**:OpenCV 2.4.13 
Compiler (`gcc --version` on Ubuntu): gcc 4.8.4

**Comment by gineshidalgo99** [comment]
Hi, I cannot debug it by myself because it works on our computers. Could you try the following and let me know the result?
Could you change this line?
`mPoseIndexes{getPoseKeypoints(poseModel, {"LWrist", "LElbow", "LShoulder", "RWrist", "RElbow", "RShoulder"})}`
To this one (i.e. changing braces by parenthesis)?
`mPoseIndexes(getPoseKeypoints(poseModel, {"LWrist", "LElbow", "LShoulder", "RWrist", "RElbow", "RShoulder"}))`

**Comment by handale88** [comment]
@gineshidalgo99 Thank you! After changing some braces by parenthesis, it worked. Thank you for your help.

**Comment by gineshidalgo99** [comment]
Fixed in the latest version. Thanks!
