### ISSUE TITLE
openpose-1.4.0 generate fail while openpose-1.3.0 is generate done with the same system setting by using cmake in windows10

### ISSUE THREAD

**Issue by ChaneWu** [CMU-Perceptual-Computing-Lab/openpose#821]
### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**: 
123cb64

2. **General configuration**:
    - **Installation mode**: CMake (Windows)
    - **Operating system**: Windows10
    - **Release or Debug mode**? (by default: release):
    - Compiler: VS2015 Enterprise Update 3
3. **Non-default settings**:
    - **3-D Reconstruction module added**: no
    - Any other custom CMake configuration with respect to the default version? : no

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : cmake3.12
    - **OpenCV version**: pre-compiled

**Comment by gineshidalgo99** [comment]
It directly works for me with that configuration, so I'd need more info. Please include your whole console output: paste the error to [PasteBin](https://pastebin.com/) and then paste the link here

**Comment by ChaneWu** [comment]
Thanks for your reply. The link below is the output of the generate for the openpose-1.4.0 got from CMAKE: https://pastebin.com/95adfNp3. And if I generate with openpose-1.3.0, the output is shown below: https://pastebin.com/UyH5eT3J. I don't change any thing for generating these two project, and that makes me confused.

**Comment by ChaneWu** [comment]
The problem solved, thanks!

**Comment by gineshidalgo99** [comment]
Hi @ChaneWu , I did look in your log, but I couldn't find the reason. Could you let me know how you were able to solve it for future people with similar errors? Thanks!
