### ISSUE TITLE
Sometimes hands cannot be detected

### ISSUE THREAD

**Issue by quinnliu4real** [CMU-Perceptual-Computing-Lab/openpose#828]
Openpose hand keypoint detector runs pretty well when I use a webcam, however it fails when I try some video clips. For example:
![041_000000000063_rendered](https://user-images.githubusercontent.com/33365197/45350263-e9d52b80-b5e5-11e8-99d6-05c2fcbee081.png)
In this frame, hand is pretty obvious, but is not fully detected. So do other frames in this video.
I am wondering is there any trick when using openpose, e.g. input video frame size? 
Looking forward to HELLLPPP!!!

**Comment by ihewro** [comment]
do you have a solution?
