### ISSUE TITLE
Memory Overflow with flag --hand --face in 1.40 Version !

### ISSUE THREAD

**Issue by drmarya** [CMU-Perceptual-Computing-Lab/openpose#829]
When run openpos via 1.30 version this is correct and there is no problem, everything is fine.  but in 1.40 Version CUDA get memory problem (overflow) ? why this challenge is occurred?

**Comment by fulsz** [comment]
I get the same error in windows 10. How to resolve it?

**Comment by fulsz** [comment]
It required more GPU memory via 1.40. 

I solve it by change net_resolution, like this

-  DEFINE_string(model_pose,               "BODY_25",
+ DEFINE_string(model_pose,               "COCO",	

- DEFINE_string(net_resolution,           "-1x368",
+DEFINE_string(net_resolution,           "-1x128",

You also need download "pose_iter_440000.caffemodel".

Good Lucy.

**Comment by gineshidalgo99** [comment]
Check the doc about how to speed up openpose (speed up also reduces memory). But it's basically what the above answer mentions.
