### ISSUE TITLE
About Example - "2_extract_pose_or_heatmat_from_image.cpp"

### ISSUE THREAD

**Issue by pdon4603** [CMU-Perceptual-Computing-Lab/openpose#83]
Amazing work and contributions in OpenPose. Thank all the authors.

When I was using "examples/tutorial_pose/2_extract_pose_or_heatmat_from_image.cpp", it was found that merely mofidying the values of FLAGS_alpha_pose and FLAGS_alpha_heatmap did not work. Then I looked into the code and found that the 5th parameter (const bool blendOriginalFrame) was missing.

This issue could be solved by modifying the code from:
    pPoseRenderer = new op::PoseRenderer{netOutputSize, outputSize, poseModel,
            pPoseExtractor, (float)FLAGS_alpha_pose, (float)FLAGS_alpha_heatmap};
to
    pPoseRenderer = new op::PoseRenderer{netOutputSize, outputSize, poseModel,
            pPoseExtractor, true, (float)FLAGS_alpha_pose, (float)FLAGS_alpha_heatmap};

Enjoy OpenPose!

**Comment by gineshidalgo99** [comment]
I just updated them and incorporated the proper flag (`disable_blending`).

Let me know if you find any other issue.

Thanks!

**Comment by pdon4603** [comment]
Well done. Thanks!
