### ISSUE TITLE
LNk1181: cannot open input file

### ISSUE THREAD

**Issue by ekim1423** [CMU-Perceptual-Computing-Lab/openpose#831]
### Issue Summary
When trying to build the solution from VS2015 enterprise in release mode, I keep getting this error.

### OpenPose Output (if any)
.....
17>  C:\Users\EKIM\Documents\AIPC-Video\CMU\openpose\python\openpose\_openpose.cpp(216): note: see reference to function template instantiation 'std::vector<float,std::allocator<_Ty>>::vector<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double>>>,void>(_Iter,_Iter)' being compiled
17>          with
17>          [
17>              _Ty=float,
17>              _Iter=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double>>>
17>          ]
13>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
11>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
17>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
3>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
6>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
14>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
15>LINK : fatal error LNK1181: cannot open input file '..\..\src\openpose\Release\openpose.lib'
18>------ Rebuild All started: Project: ALL_BUILD, Configuration: Release x64 ------
19>------ Skipped Rebuild All: Project: INSTALL, Configuration: Release x64 ------
19>Project not selected to build for this solution configuration 
========== Rebuild All: 1 succeeded, 17 failed, 1 skipped ==========

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **OpenPose version**:  a03253a

2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Window 10
    - **Release or Debug mode**: Release
    - **Compiler**: Visual Studio 2015 - Visual C++ 14.0

3. **Non-default settings**:
    - **3-D Reconstruction module added**? NO
    - Any other custom CMake configuration with respect to the default version?  With_Eigen

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : 3.12.1
    - **OpenCV version**:  OpenPose default

5. If **GPU mode** issue:
    - **CUDA version**:  8.0.61
    - **cuDNN version**: 5.1.10
    - **GPU model** : NVIDIA GV100

8. If **Windows** system:
    - Portable demo or compiled library? Compiling library

**Comment by UchihaIzumi** [comment]
@EunSolKim-Nano I'm sorry to bother you, but I happened to have exactly the same problem, which occurred after I chose the build flag for with_eigen. I wonder if you can give me some help. Thank you.

**Comment by EunSolKim-Nano** [comment]
@UchihaIzumi  No problem! I just uncheck "With_eigen" to build. and it worked perfectly fine.  Unless you really need "Eigen" library, you might just wanna take that out.

**Comment by UchihaIzumi** [comment]
@EunSolKim-Nano 
That's true. Cmake compiles smoothly without with_eigen, but it seems necessary to use the eigen library for parameter calibration using the openpose camera calibration toolbox. I use multiple usb Logitech webcams. Is there any good way to get the  extrinsic parameters of multiple webcams?

**Comment by EunSolKim-Nano** [comment]
@UchihaIzumi Oh I didn't test it with multiple cameras. In that case, yeah I think you need to compile it with "With_Eigen". As far as I know, there are multiple open source from opencv for multiple camera calibration.

**Comment by UchihaIzumi** [comment]
@EunSolKim-Nano
Thank you for your reply anyway. Finally, I would like to ask if the parameters obtained by respectively calibrating multiple cameras with MATLAB camera calibration toolbox can meet the requirements of openpose.
