### ISSUE TITLE
Bounding box around each person to search

### ISSUE THREAD

**Issue by Ivamcoder** [CMU-Perceptual-Computing-Lab/openpose#832]
Hi,

In paper `Convolutional Pose Machine` , bounding box is taken from the ground truth for training , and during test it wants from the user to draw a bounding box around person, to have  a multi-scaled region for finding joints,
I was wondering if Open Pose use  a people detector inside to have regions to search in?

Thanks,

**Comment by soulslicer** [comment]
Openpose is based on https://arxiv.org/pdf/1611.08050.pdf which is an extension of CPM
