### ISSUE TITLE
Confidence for each joint

### ISSUE THREAD

**Issue by Ivamcoder** [CMU-Perceptual-Computing-Lab/openpose#835]
Hi 
the output of open pose is the joint location and the confidence of that estimates, 
I could not figure out based on what analysis you give the confidence for each joint
is it extracted just from heat map or ...
as it is , how you knows that estimated heatmap itself is true and does not have uncertainty?

**Comment by oga-git** [comment]
Hello!
I also want to know the meaning of the confidence score.
if you figured out what it is, I would appreciate if you could tell me.
