### ISSUE TITLE
Leveraging tensor cores (which seem "unused").

### ISSUE THREAD

**Issue by sergionegri** [CMU-Perceptual-Computing-Lab/openpose#837]
Just checked benchmarks here: https://docs.google.com/spreadsheets/d/1-DynFGvoScvfWDA1P4jDInCkbD4lg0IKOYbXgEq0sK0/edit#gid=0

The **performance with a P100 or a V100 are basically identical**. Considering that the V100 is provided with tensor cores while the P100 is not, and that (on paper) tensor cores should provide a substantial boost in performance:
- would the code (in theory) benefit from them, or is intrisically algorithmically limited in that respect?
- is there any plan to rewrite the code to take advantage of them?

Thank you!

**Comment by soulslicer** [comment]
We plan to port to TensorRT soon. Stay tuned

**Comment by sergionegri** [comment]
Thank you!

I'm trying to understand one thing, I spoke about tensor **cores** and you answered about tensor **RT**. They are not the same stuff as far as I understand.

Tensor RT stuff can run on a P100 too (as you can read here: https://devblogs.nvidia.com/deploying-deep-learning-nvidia-tensorrt/).

But tensor cores are only present in new gen Nvidia cards (V100, Jetson Xavier, RTX).

**Comment by awm-pezhilarasan** [comment]
Hi, are there any developments on this front?

Thank you.

**Comment by soulslicer** [comment]
Not right now, but the plan is to port this to Pytorch and use the Pytorch C++ API. Would definitely be welcome if someone can help us port our existing BODY25 model into Pytorch in Python
