### ISSUE TITLE
Empty frame detected, frame number 751 of 752

### ISSUE THREAD

**Issue by MLsmaller** [CMU-Perceptual-Computing-Lab/openpose#838]
In the official example I was able to run the program properly.
eg:  ./build/examples/openpose/openpose.bin --video examples/media/gangqing.avi

However, this error occurred while running with video, which I downloaded myself.The error is :Empty frame detected, frame number 751 of 752.

And the output video is the same as the original video,which confuse me a lot.

I sincerely hope to get your guidance, thank you.

**Comment by gineshidalgo99** [comment]
This is an OpenCV codecs issue with some video formats. It just can't read the last frame, or there is not a last frame and OpenCV thinks there is. It is not a big issue, you can ignored. If you really wanna solve it, just convert the video to basic AVI or low compressed MP4 format. Best
