### ISSUE TITLE
Calibration xml not found

### ISSUE THREAD

**Issue by EunSolKim-Nano** [CMU-Perceptual-Computing-Lab/openpose#839]
### Issue Summary

- I completed the calibration for one of my webcam. I used 156 images and it took 861.47.0335 seconds, which was unexpectedly long.
- I completed the calibration. The output of calibration (instrinsic) should be saved in xml file in the  calibration_image_dir but I couldn't find any.

### Executed Command (if any)
./build/examples/calibration/calibration.bin --mode 1 --grid_square_size_mm 24 --grid_number_inner_corners "9x6" --camera_serial_number {I wrote something but I tend to not publish here} --calibration_image_dir {some directory}

### OpenPose Output (if any)
Intrinsic calibration completed!
OpenPose demo successfully finished. Total time: 861.470335 seconds.

### Type of Issue
- Performance

### Your System Configuration
1. **OpenPose version**:  a03253a

2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Ubuntu 16.04
    - **Release or Debug mode**: Release

3. **Non-default settings**:
    - **3-D Reconstruction module added**? NO

4. **3rd-party software**:
    - **Caffe version**: 1.0 - Compiled 
    - **CMake version** : 3.12.1
    - **OpenCV version**:  OpenPose default

5. If **GPU mode** issue:
    - **CUDA version**:  9.2
    - **cuDNN version**: 7.1
    - **GPU model** : NVIDIA GV100

**Comment by gineshidalgo99** [comment]
Could you check you have writing access to that folder? That seems like a file read/write permissions issue.
