### ISSUE TITLE
Output video of poses only

### ISSUE THREAD

**Issue by whensbrunch** [CMU-Perceptual-Computing-Lab/openpose#843]
Using the `--write_video <path>` option of `./build/examples/openpose/openpose.bin` I can produce a video with the detected pose as an overlay on the original. Is it possible to produce just the pose (i.e. a moving a stick figure with a white background)?

Awesome tool - cheers!

**Comment by gineshidalgo99** [comment]
With black background yes, check doc/demo_overview.md the flag is called blender-something

**Comment by whensbrunch** [comment]
`--disable-blending`

Thank you!
