### ISSUE TITLE
Commercial license cost too prohibitive

### ISSUE THREAD

**Issue by thejae** [CMU-Perceptual-Computing-Lab/openpose#845]
Am looking at your library, it's very interesting and full of potential. We have been using MS Kinect for many of our interactive projects, since Kinect has a fixed cost in terms of hardware and software frameworks (unity addons and plugins), we can easily quote a per project price to our client. 

I understand you guys have used a lot of R&D to create this solution but the current pricing and licensing method is very unfriendly to most marketing agencies and exhibition show centers. The cost of the license alone is already too prohibitive, on top of that, there are other dev costs and installation/ fabrication costs to consider.

**Comment by kyleboddy** [comment]
This is still an obvious problem not solved by just marking it closed.

**Comment by ohkjames** [comment]
Anybody curious what we've done during the past 2 years while waiting for a reply from the Open Pose guys. 

TensorFlow (free) has a pose estimation which works quite well, there's even a Javascript version which works great in browsers - it doesn't do skeleton detection though:
https://www.tensorflow.org/lite/models/pose_estimation/overview

For more accurate skeleton and people tracking, we're using Nuitrack in combination with Intel RealSense which has a commercial-friendly license:
https://nuitrack.com/#pricing

**Comment by thejae** [comment]
Anybody curious what we've done during the past 2 years while waiting for a reply from the Open Pose guys.

TensorFlow (free) has a pose estimation which works quite well, there's even a Javascript version which works great in browsers - it doesn't do skeleton detection though:
https://www.tensorflow.org/lite/models/pose_estimation/overview

For more accurate skeleton and people tracking, we're using Nuitrack in combination with Intel RealSense which has a commercial-friendly license:
https://nuitrack.com/#pricing
