### ISSUE TITLE
how to convert heatmap to pose in python

### ISSUE THREAD

**Issue by wangfei-cs** [CMU-Perceptual-Computing-Lab/openpose#846]
In a project, I made our outputs be like openpose-style heatmaps. What we need is the script for linking joints from the heatmaps.

I noticed  the folder of _openpose/python/openpose/_, has a script named _openpose.py_, and a function **poseFromHM**, that should be what I need.

My question are:
1. 'make install' not worked for wrapping it with python, Could you please tell more detailed steps?
2. What the shape of heatmaps I should prepare if using **poseFromHM** function

**Comment by soulslicer** [comment]
Nobody can help you if you don't post your error logs
