### ISSUE TITLE
Question |  OpenPose and tf-pose estimation

### ISSUE THREAD

**Issue by Rutulpatel7077** [CMU-Perceptual-Computing-Lab/openpose#847]
I love OpenPose. Thanks for the great library.

I am absolute beginner.

My question is why generated keypoints (JSON file) are different in both OpenPose and tensorflow-pose-estimation ?

What is the main difference?

is there any way to compare both keypoints results ?.

**Tensorflow JS Pose Estimation example**
```
{
  "score": 0.32371445304906,
  "keypoints": [
    { // nose
      "position": {
        "x": 301.42237830162,
        "y": 177.69162777066
      },
      "score": 0.99799561500549
    },
    { // left eye
      "position": {
        "x": 326.05302262306,
        "y": 122.9596464932
      },
      "score": 0.99766051769257
    },
    { // right eye
      "position": {
        "x": 258.72196650505,
        "y": 127.51624706388
      },
      "score": 0.99926537275314
    },
    ...
  ]
}
```

**OpenPose example**
```
{
	"version":1.1,
	"people":[
		{
			"pose_keypoints":[
				376.034,327.151,0.948575,443.19,430.934,0.785305,372.936,433.979,0.736717,363.816,620.328,0.793385,253.757,571.352,0.766581,516.383,427.911,0.766405,482.803,608.042,0.749979,376.084,501.212,0.844809,443.176,736.191,0.510191,376.046,919.351,0.851897,400.538,1075.03,0.653059,553.102,739.226,0.522832,498.057,986.485,0.842563,0,0,0,357.694,305.745,0.968881,400.494,305.648,0.976137,0,0,0,449.234,311.902,0.751298
			],
			"face_keypoints":[
				
			],
			"hand_left_keypoints":[
				
			],
			"hand_right_keypoints":[
				
			]
		}
	]
}

```

**Comment by lvcoc** [comment]
please,can you tell me how to get JSON with tf-pose estimation

**Comment by aligajani** [comment]
Just a different output because posenet uses TF.js and OpenPose doesn't.

**Comment by 2429581027** [comment]
Hello, your question has been solved, how do you calculate the score?

**Comment by Rutulpatel7077** [comment]
Score is just an accuracy of the prediction

**Comment by andreibirladeanu** [comment]
> please,can you tell me how to get JSON with tf-pose estimation

I wrote this function which parses the Human tf-pose object as there wasn't any way to get that data in the tensorflow 2.0 implementation
https://github.com/andreibirladeanu/phd_code/blob/master/openpose_tf/extract_skeleton.py
