### ISSUE TITLE
Configuratioon error

### ISSUE THREAD

**Issue by Deepak3994** [CMU-Perceptual-Computing-Lab/openpose#848]
I am trying to install openpose on my system. During the configuration stage, i got the following error.

![screenshot from 2018-09-24 12-01-02](https://user-images.githubusercontent.com/20994657/45939707-3cedac00-bff2-11e8-8481-61260b162996.png)

Kindly let me know how to proceed further?

**Comment by anooptoffy** [comment]
Please copy and paste the log that is apprearin it has the clue.
