### ISSUE TITLE
How can I train custom hand dataset with openpose network?

### ISSUE THREAD

**Issue by JasOlean** [CMU-Perceptual-Computing-Lab/openpose#849]
Hello,

I would like to use custom hand dataset. When I insert the images in your demo, I cannot get hand keypoints correctly. So, for custom dataset, do I need to train again the openpose network? how can I train them? 
Please help me.

**Comment by ldfinfontainebleau** [comment]
models/hand/pose_deploy.prototxt  I think you can use this to train and get your custom hand caffemodel. Hope it could help you!

**Comment by gineshidalgo99** [comment]
There is not a public training code for hands, so you might want to follow @ldfinfontainebleau  answer.

We are rather working on a combined model that offers body-foot-fade-hands with the same network (so much faster speed), so we will not try to clean the hand code.

**Comment by ortegatron** [comment]
Just for the record, I wrote an article about training a hand detector like the openpose one, it's here:
https://medium.com/@apofeniaco/training-a-hand-detector-like-the-openpose-one-in-tensorflow-45c5177d6679
