### ISSUE TITLE
(Openpose for Windows) Compiling error - fatal error C1083: Cannot open include file: 'opencv2/core/core.hpp' 

### ISSUE THREAD

**Issue by k3nnywilliam** [CMU-Perceptual-Computing-Lab/openpose#85]
### Issue summary
I followed the Openpose's Windows installation instruction all the way to step number 5 but then I received this compile error:

`D:\openpose\include\openpose/utilities/cuda.hpp(8): fatal error C1083: Cannot open include file: 'opencv2/core/core.hpp': No such file or directory

D:\openpose\include\openpose/core/datum.hpp(5): fatal error C1083: Cannot open include file: 'opencv2/core/core.hpp': No such file or directory

..\..\examples\openpose\openpose.cpp(25): fatal error C1083: Cannot open include file: 'opencv2/core/core.hpp': No such file or directory

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets(689,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_61,code=\"compute_61,compute_61\" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"  -I..\..\include -I"..\..\3rdparty\caffe\caffe-windows\include" -I..\..\3rdparty\caffe\include -I..\..\3rdparty\caffe\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include -I"..\..\3rdparty\caffe\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include\boost-1_61" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\"    -DCAFFE_VERSION=1.0.0 -DBOOST_ALL_NO_LIB -DUSE_LMDB -DUSE_LEVELDB -DUSE_CUDNN -DUSE_OPENCV -DUSE_CAFFE -DCMAKE_WINDOWS_BUILD -DGLOG_NO_ABBREVIATED_SEVERITIES -D"GOOGLE_GLOG_DLL_DECL=__declspec(dllimport)" -D"GOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport)" -DH5_BUILT_AS_DYNAMIC_LIB=1 -D"CMAKE_INTDIR=\"Release\"" -D_CRT_SECURE_NO_WARNINGS -D_MBCS -Xcompiler "/EHsc /W4 /nologo /Ox /FS /Zi  /MD " -o x64\Release\\obj\obj\obj\..\..\src\openpose\pose\\bodyPartConnectorBase.cu.obj "D:\openpose\src\openpose\pose\bodyPartConnectorBase.cu"" exited with code 2.`

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Windows 10
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**: 5.1
**GPU model** (`nvidia-smi`): GTX 960M
**Caffe version**: Default from OpenPose.
**OpenCV version**: OpenCV3.2

**Comment by gyc990326** [comment]
Did you succeeded in step iii?
It seem that the caffe was not correctly installed

**Comment by k3nnywilliam** [comment]
I also suspected it was caffe but no, I did not get any errors in step 3.

**Comment by gyc990326** [comment]
It seem that the project file you downloaded is corrupted.
Look at compiler output: "-I....\include"
it should be ..\..\include, and "...." actually is equal to ".", so please check the additional include directory in the C/C++, and change all "...." to "..\..", or try to redownload the OpenPose

**Comment by k3nnywilliam** [comment]
Redownloaded the Openpose, no luck again. My additional include directory in the C/C++ currently looks like this. Do you mean I need to remove the extra ..\ at the front?:
 
![add-include-cpp](https://user-images.githubusercontent.com/14914320/27386074-3713695e-56c7-11e7-878b-a7f1b1e0449b.jpg)



Also, my caffe configuration is described below, if you need more info:
![caffe-configuration](https://user-images.githubusercontent.com/14914320/27386170-92e2b88e-56c7-11e7-95c8-5562d78fd018.jpg)

**Comment by gyc990326** [comment]
Sorry I made the wrong guess. Could you please check whether the file D:\openpose\3rdparty\caffe\dependencies\libraries_v140_x64_py27_1.1.0\libraries\include\opencv2\core\core.hpp exists?

**Comment by k3nnywilliam** [comment]
Yes the file exists.

**Comment by k3nnywilliam** [comment]
@gyc990326 Any ideas on what the problem might be?

**Comment by gyc990326** [comment]
Sorry but I have no idea.

**Comment by gyc990326** [comment]
I suspect that the ..\.. is not interpretd correctly, but it worked perfectly on other environments.

**Comment by k3nnywilliam** [comment]
@gyc990326 I still have yet to find the solution but thanks for helping anyway.

Is there anyone out there successfully installed the Windows version of Openpose? If you have please let me know what you did to make it work. Would be a great help.

**Comment by gineshidalgo99** [comment]
Hands is next in our release to-do list, but right after that I will try to give a pre-default already-built Caffe files, so it does not need to be installed by default. I think all of this should be done by this week. Sorry for all the Caffe problems.

**Comment by k3nnywilliam** [comment]
@gineshidalgo99 No worries, hope it will work fine in the next update. Looking forward to it!

**Comment by gineshidalgo99** [comment]
I've just added a commit that merges Ubuntu and Windows versions. In addition, the Windows version should be easier to install (no need to install Caffe). Could you try it and see if the new one works for you?

**Comment by gineshidalgo99** [comment]
PS: The hands detection code has just been released. And it works on Windows. Post new issue thread if errors with the new Windows installation appear.
