### ISSUE TITLE
Cannot Run Python Scripts From Outside of build/examples/tutorials_python/

### ISSUE THREAD

**Issue by bkarpowicz3** [CMU-Perceptual-Computing-Lab/openpose#851]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
2. **No** questions about **training**. OpenPose only implements testing.
3. **No** questions about **3rd party libraries**.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. **No duplicated** posts.
5. **No** posts about **questions already answered / clearly explained in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
6. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
7. Only English comments.
Issues/comments which do not follow these rules will be **ignored or removed** with no further clarification.

### Issue Summary
Python scripts only run from within build/examples/tutorials_python/. I need to be able to access the library from outside of this directory. I have run sudo make install multiple times.

### Executed Command (if any)
cd build/
sudo make install

### OpenPose Output (if any)
raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
Exception: Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?

### Errors (if any)
Cannot run OpenPose library outside of build directory.

### Type of Issue
- Execution error
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code (pulled 9/25/18)

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** Mac Mojave
    - **Release or Debug mode**? Release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...? gcc Mac 

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...? 2.7 
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.13.1

9. If **Windows** system:
    - Portable demo or compiled library? 

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by soulslicer** [comment]
You need to add it to your PYTHONPATH:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md

> Option b, not Installing OpenPose: To move the OpenPose Python API demos to a different folder, ensure that the line sys.path.append('{OpenPose_path}/python') is properly set in your *.py files, where {OpenPose_path} points to your build folder of OpenPose. Take a look at build/examples/tutorial_pose/1_extract_pose.py for an example.

**Comment by bkarpowicz3** [comment]
Even if I run the exact code in 1_extract_pose.py from another directory, it cannot find the OpenPose module.

**Comment by adiser** [comment]
if you are using ubuntu or macos try editing your ~/.bashrc file and add your PYTHONPATH

in shell, type

`vim ~/.bashrc`

add this line

`export PYTHONPATH=path/to/openpose/build/python:$PYTHONPATH`

you might also want to do this for caffe

`export PYTHONPATH=path/to/caffe/python`

**Comment by AditSoni** [comment]
any solutions??
