### ISSUE TITLE
Adam Pose Model Enquiry

### ISSUE THREAD

**Issue by deven-dhaka** [CMU-Perceptual-Computing-Lab/openpose#854]
I've been trying openpose for inferring 3d human model structure, just body structure, with 3 camera system, with calibration performed and all the parameters extracted. However, openpose fails to identify some joint locations in more than one camera, for a given frame. That's why I thought it might be a better idea to look upon the openpose joint angle estimation module together with 3d position estimation.

Can you provide some assistance in order to find out what *Adam_FastFit()* and *Adam_FastFit_Initialize()* functions are supposed to perform. I couldn't find any location where these functions are listed explicitly. The header mentions #include <adam/fileName.h>, have no clue where these are located.

PS: I think it might be better, if you can look over *triangulation* code. I have found two different approaches. First is openpose [code](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/3d/poseTriangulation.cpp), lines: 137-40 ;and another one [here](https://github.com/cdemel/OpenCV/blob/master/modules/legacy/src/trifocal.cpp), lines: 2148-50. You have taken matrix of size 2Cx4 whereas latter considers 3Cx4.

**Comment by gineshidalgo99** [comment]
Please, do not try to use Adam (as it's not possible). That's why it appears nowhere in the README nor doc.

Adam is an experimental code that is not in the doc because it is not ready nor fully in the library (it requires on-going research includes that are not publishable).

**Comment by ChingMuVisionTech** [comment]
Hi @gineshidalgo99 ,how is the Adam research is going now?  I am working on 3D pose estimation recently and need to reconstruct 3D joint positions along with bone rotations, and I am wondering if there is a suitable solution now?

**Comment by Jerryzhangzhao** [comment]
Hi @gineshidalgo99 ,how is the Adam research is going now? I am working on 3D pose estimation recently and need to reconstruct 3D joint positions along with bone rotations, and I am wondering if there is a suitable solution now?

**Comment by gineshidalgo99** [comment]
Sorry, but it was sadly abandoned! (the people involved graduated and left)

**Comment by Jerryzhangzhao** [comment]
OK... so do you know if there are some related algorithm or papers for solving this problem?
