### ISSUE TITLE
Missing _openpose.dylib on Mac OSX

### ISSUE THREAD

**Issue by r-wettstaedt** [CMU-Perceptual-Computing-Lab/openpose#856]
### Issue Summary
When building with `BUILD_PYTHON`, no `_openpose.dylib` seems to be compiled and added. There are no errors in CMake. I tried compiling openpose as described in the instructions for the [Mac OSX version](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#mac-osx-version) and for the [Python API](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#python-api). This leaves me with the following output from CMake:

```
The C compiler identification is AppleClang 10.0.0.10001145
The CXX compiler identification is AppleClang 10.0.0.10001145
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Building CPU Only.
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - found
Found Threads: TRUE  
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106700
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:273 (find_package)


Boost version: 1.67.0
Found the following Boost libraries:
  system
Found GFlags: /usr/local/include  
Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
Found Glog: /usr/local/include  
Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
Found OpenCV: /usr/local (found version "3.4.1") 
Try OpenMP C flag = [-fopenmp=libomp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [ ]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [-fopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [-Qopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [-openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [-xopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [+Oopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [-qsmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP C flag = [-mp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-fopenmp=libomp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [ ]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-fopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-Qopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-xopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [+Oopenmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-qsmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Try OpenMP CXX flag = [-mp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Failed
Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
${Caffe_INCLUDE_DIRS} set by the user to /usr/local/include/caffe
${Caffe_LIBS} set by the user to /usr/local/lib/libcaffe.dylib
Adding Example calibration.bin
Adding Example openpose.bin
Adding Example 1_custom_post_processing.bin
Adding Example 1_extract_from_image.bin
Adding Example 2_extract_pose_or_heatmat_from_image.bin
Adding Example 1_openpose_read_and_display.bin
Adding Example 2_user_processing_function.bin
Adding Example 3_user_input_processing_and_output.bin
Adding Example 4_user_input_processing_output_and_datum.bin
Adding Example 1_user_synchronous_postprocessing.bin
Adding Example 2_user_synchronous_input.bin
Adding Example 3_user_synchronous_output.bin
Adding Example 4_user_synchronous_all.bin
Adding Example 5_user_asynchronous.bin
Adding Example 6_user_asynchronous_output.bin
Adding Example handFromJsonTest.bin
Adding Example resizeTest.bin
Download the models.
Downloading BODY_25 model...
Model already exists.
Not downloading body (COCO) model
Not downloading body (MPI) model
Downloading face model...
Model already exists.
Downloading hand model...
Model already exists.
Models Downloaded.
Configuring done
Generating done
```

### Executed Command (if any)
```bash
▶ pwd
[...]/openpose/build/examples/tutorial_python
▶ python 1_extract_pose.py
```

### Errors (if any)
```
Traceback (most recent call last):
  File "1_extract_pose.py", line 19, in <module>
    from openpose import *
  File "[...]/openpose/build/python/openpose/openpose.py", line 17, in <module>
    class OpenPose(object):
  File "[...]/openpose/build/python/openpose/openpose.py", line 24, in OpenPose
    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/_openpose.dylib')
  File "/Library/Anaconda/lib/python3.6/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1_extract_pose.py", line 21, in <module>
    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
Exception: Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
```

Checking the `build/python/openpose` folder shows that there is no _openpose.dylib
```
▶ ls -la build/python/openpose
total 40
drwxr-xr-x  8 wettstaedt  staff   256 Sep 29 12:25 .
drwxr-xr-x  5 wettstaedt  staff   160 Sep 29 12:13 ..
drwxr-xr-x  2 wettstaedt  staff    64 Sep 29 12:13 CMakeFiles
drwxr-xr-x  6 wettstaedt  staff   192 Sep 29 12:13 CMakeScripts
-rw-r--r--  1 wettstaedt  staff    23 Sep 29 12:13 __init__.py
drwxr-xr-x  3 wettstaedt  staff    96 Sep 29 12:25 __pycache__
-rw-r--r--  1 wettstaedt  staff  1490 Sep 29 12:13 cmake_install.cmake
-rw-r--r--  1 wettstaedt  staff  9924 Sep 29 12:13 openpose.py
```

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: I tried it with both, latest commit from `master` and the tag `v1.4.0`

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Mac OSX 10.14
    - **Release or Debug mode**?: release
    - **Compiler**: XCode 10.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: default from Homebrew, Version 1.0
    - **CMake version**: 3.6.1
    - **OpenCV version**: default from Homebrew, Version 3.4.2

6. If **GPU mode** issue:
    - **CUDA version**:
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**: 2,4 GHz Intel Core i5
    - Total **RAM memory** available: 8GB

8. If **Python** API:
    - **Python version**: 3.6.5
    - **Numpy version**: 1.13.3

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by r-wettstaedt** [comment]
Quoting from my first comment:

> Executed Command (if any)
> ```
> ▶ pwd
> [...]/openpose/build/examples/tutorial_python
> ▶ python 1_extract_pose.py
> ```
> Errors (if any)
> ```
>Traceback (most recent call last):
>  File "1_extract_pose.py", line 19, in <module>
>    from openpose import *
>  File "[...]/openpose/build/python/openpose/openpose.py", line 17, in <module>
>    class OpenPose(object):
>  File "[...]/openpose/build/python/openpose/openpose.py", line 24, in OpenPose
>    _libop= np.ctypeslib.load_library('_openpose', dir_path+'/_openpose.dylib')
>  File "/Library/Anaconda/lib/python3.6/site-packages/numpy/ctypeslib.py", line 155, in load_library
>    raise OSError("no file with expected extension")
>OSError: no file with expected extension
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "1_extract_pose.py", line 21, in <module>
>    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in >CMake and have this Python script in the right folder?')
>Exception: Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and >have this Python script in the right folder?
>```

**Comment by soulslicer** [comment]
Hmm..no one else is having such an issue. Can you clean everything, make a new build folder and send paste the build log here

**Comment by r-wettstaedt** [comment]
It's the same error every time I try it out. As stated in my initial comment I also tried latest commit from `master` and the tag `v1.4.0`

**Comment by soulslicer** [comment]
Unless you post your build log I cant help

**Comment by r-wettstaedt** [comment]
The build log from CMake is also in my initial comment.

**Comment by r-wettstaedt** [comment]
Alright I'm sorry, I never realized you have to `make` to actually build openpose. I thought this is what CMake was for. However, there is no makefile in my build folder, so both ``make -j`nproc` `` and `make install` fail.

```bash
▶ make -j`nproc`
zsh: command not found: nproc
make: *** No targets specified and no makefile found.  Stop.
```

```bash
▶ make install
make: *** No rule to make target `install'.  Stop.
```

```bash
▶ ls -la
total 88
drwxr-xr-x  12 wettstaedt  staff    384 Oct 10 16:31 .
drwxr-xr-x  21 wettstaedt  staff    672 Oct 10 16:28 ..
-rw-r--r--   1 wettstaedt  staff  29718 Oct 10 16:31 CMakeCache.txt
drwxr-xr-x  12 wettstaedt  staff    384 Oct 10 16:31 CMakeFiles
drwxr-xr-x  19 wettstaedt  staff    608 Oct 10 16:31 CMakeScripts
drwxr-xr-x   3 wettstaedt  staff     96 Oct 10 16:31 OpenPose.xcodeproj
drwxr-xr-x   3 wettstaedt  staff     96 Oct 10 16:30 cmake
-rw-r--r--   1 wettstaedt  staff   4394 Oct 10 16:31 cmake_install.cmake
-rw-r--r--   1 wettstaedt  staff   1279 Oct 10 16:30 cmake_uninstall.cmake
drwxr-xr-x  13 wettstaedt  staff    416 Oct 10 16:31 examples
drwxr-xr-x   5 wettstaedt  staff    160 Oct 10 16:31 python
drwxr-xr-x   5 wettstaedt  staff    160 Oct 10 16:31 src
```

**Comment by soulslicer** [comment]
Please follow the instructions step by step in the Ubuntu/Mac Section

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md

**Comment by r-wettstaedt** [comment]
Finally I got to the make step. Now I am stuck on an error. 
Here ist my output from make https://pastebin.com/xE1uuwRt

**Comment by soulslicer** [comment]
this is a different error..please repost it as another issue and close this

**Comment by r-wettstaedt** [comment]
Opened the new issue #878

**Comment by vasanthhr** [comment]
@r-wettstaedt 

When I ran below command:

make -j`nproc`

Then getting this error:

make: *** No rule to make target `install'.  Stop.

Please help me to resolve the same.

**Comment by vasanthhr** [comment]
I am running on Ubuntu laptop/Machine.

with this command: make -j`nproc`

so getting this error:  make: *** No rule to make target `install'. Stop.

**Comment by vasanthhr** [comment]
@StrongRay 

(FYI: I am running on Ubuntu laptop/Machine.)

I tried "make -j 4" as well, but still the same error. 

I tried "make -j4" as well, but still the same error. 

Even I tried "make" and then again same error.

 FYI: I checked in build folder has "caffe" folder, "CMakeFiles" folder, "CMakeCache.txt" file and "detect_cuda_archs.cu" file.

 Please let me know If I am missing anything here

**Comment by StrongRay** [comment]
I am on Ubuntu 18.04.  From a fresh download, make a directory build ie.  there should be a .../openpose/build

Then, in the build directory, issue cmake..
Download ccmake which is a GUI version and you can select options for the generated make file.   Issue “ccmake ..”

Look for caffe line item and select BUILD, it will download caffe when rebuilding. 

Press configure and generate

Then do a make

**Comment by StrongRay** [comment]
Note it’s **cmake ..**
And **ccmake ..**
The **..** is asking cmake to go look for the makelist one directory before /build ie. in openpose directory.  

To select options in ccmake, use arrow keys to move up and down then press Enter on the item to change and I believe left and right arrows will give you options with explanation on the bottom.
