### ISSUE TITLE
Model directory 

### ISSUE THREAD

**Issue by negarl** [CMU-Perceptual-Computing-Lab/openpose#858]
Hi. I want to use the newly released OpenPose with ROS. I made a C++ file in catkin_workspace and I got this error: 

Error : 
Prototxt file not found: models/face/pose_deploy.prototxt. 
Possible causes:
    1. Not downloading the OpenPose trained models.
    2. Not running OpenPose from the same directory where the model folder is located.
    3. Using paths with spaces.

Coming from:
- /home/robb/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():51
- /home/robb/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():970
- /home/robb/openpose/include/openpose/wrapper/wrapper.hpp:start():392
terminate called after throwing an instance of 'std::runtime_error'
  what():

I tried to use DEFINE_STRING (model_folder, "/home/robb/openpose/models" , "Folder path") but it didn't work. What should I do?

**Comment by xaiocaibi** [comment]
Hi,i have the same error,Have you solved this problem?

**Comment by soulslicer** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/3_keypoints_from_image_configurable.cpp#L93
