### ISSUE TITLE
How to identify the keypoints corresponding to a particular person in the image frame from the json output file.

### ISSUE THREAD

**Issue by Ann-Geo** [CMU-Perceptual-Computing-Lab/openpose#859]
Hi,

Really appreciate the great pose detection application openpose. I have a question regarding person identification from keypoints. I have 4 people in an image frame and I generated the json output file for this image frame using openpose. The json file contents are given below. As we can see openpose has generated the pose_keypoints_2d corresponding to 4 persons in the file. But how do I identify which pose_keypoints_2d belongs to person 1, 2, 3 and 4. Does openpose detect people in any specific order?
Thanks in advance.

{"version":1.2,"people":[{"pose_keypoints_2d":[0,0,0,0.0891983,0.591956,0.672821,0.0984191,0.594722,0.637289,0.104598,0.621955,0.475032,0,0,0,0.0784882,0.586562,0.664515,0.0678355,0.619161,0.0896371,0,0,0,0.0922308,0.671046,0.734622,0.103049,0.728299,0.848782,0.104513,0.793654,0.856487,0.0754369,0.668319,0.703233,0.0662161,0.728206,0.640709,0.0554738,0.752764,0.346164,0,0,0,0,0,0,0.0923676,0.556667,0.233932,0.086147,0.567467,0.0986126],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]},{"pose_keypoints_2d":[0.377214,0.360308,0.337782,0.36188,0.442042,0.406314,0.317462,0.431238,0.351065,0.282244,0.534743,0.059707,0,0,0,0.406287,0.447483,0.343648,0.409392,0.570154,0.0832243,0,0,0,0.322069,0.627406,0.0505409,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.364981,0.338508,0.412315,0.386386,0.338581,0.422549,0.343489,0.33314,0.524313,0.397105,0.344024,0.0921592],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]},{"pose_keypoints_2d":[0.620777,0.556685,0.340042,0.622289,0.597448,0.377325,0.608542,0.600074,0.308489,0.58708,0.632868,0.114417,0.594656,0.60566,0.176847,0.639116,0.59742,0.371015,0.642174,0.638338,0.154826,0,0,0,0.616119,0.681921,0.125368,0,0,0,0,0,0,0.62992,0.679169,0.126896,0,0,0,0,0,0,0.61917,0.553891,0.24084,0.626898,0.553845,0.397245,0,0,0,0.631469,0.559306,0.328417],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]},{"pose_keypoints_2d":[0.769325,0.499298,0.265306,0.767785,0.578368,0.248502,0.73718,0.578311,0.23156,0,0,0,0,0,0,0.799995,0.581042,0.219404,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.763196,0.483003,0.301966,0.780036,0.488302,0.321071,0.75247,0.488422,0.176461,0.795371,0.493954,0.216596],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]}]}

**Comment by gineshidalgo99** [comment]
No, unfortunately, there is no order at all. Even across frames the order will change. Best

**Comment by hejia-zhang** [comment]
I guess you can order the results based on some keypoint's pixel coordinate (e.g. neck keypoint).
