### ISSUE TITLE
Get abort Running on Webcam with Mac

### ISSUE THREAD

**Issue by jackrex** [CMU-Perceptual-Computing-Lab/openpose#860]
### Issue

I compile step by step and everything works fine when Running on Video and Running on Images, BUT if i run on webcamera use `./build/examples/openpose/openpose.bin` or `./build/examples/openpose/openpose.bin --face --hand` that will be abort and no more error message.

I even use `./build/examples/openpose/openpose.bin --image_dir examples/media/ -logtostderr true` no helped.

Here is the only error message:

Starting OpenPose demo...
[2]    31260 abort      ./build/examples/openpose/openpose.bin --face --hand

### System Info

Mac OS Mojave 10.14
Python 2.7.15
Opencv 3.4.3

**Comment by jackrex** [comment]
Update:
when i use  `./build/examples/openpose/openpose.bin --logging_level 0` i get this message, but this just logging 
![image](https://user-images.githubusercontent.com/3631994/46483166-9e4f1f80-c829-11e8-9408-f1ff47d876d8.png)

**Comment by soulslicer** [comment]
This is a very strange error. It's likely to do with some issue with opencv. We don't have a OS 10.14 machine to test, so we would have to ask you to help us. 

Do you have experience with gdb? If so, can you compile in debug mode and run it with gdb. If not, we can tell you the steps

**Comment by jackrex** [comment]
ok i will try it

**Comment by gineshidalgo99** [comment]
Please try the new Mac version and make a new PR if it still fails. Hopefully this new version fixes all issues + adds OpenCL (GPU) support. Thanks!
