### ISSUE TITLE
Is it possible use the program with rtx 2080?

### ISSUE THREAD

**Issue by louisme87** [CMU-Perceptual-Computing-Lab/openpose#862]
I'd just download the portable demo for windows,
and i had installed cuda(10.0) and cudnn(7.3.1),
and there is no error message had shown,
but the window comes out with nothing.
Is it because cuda is so new that the program can't execute correctly?
If yes, what shoud i do, the cuda 9 can't install for turing architecture.
By the way i'm not double click the exe i use the cmd to get it.

**Comment by soulslicer** [comment]
Interesting. We have tested with no issues on Pascal (all platforms) and volta (ubuntu). Can you turn on the the logging feature in cmake and share your output

**Comment by louisme87** [comment]
I'm runing with the windows portable version,
so i don't have any output from cmake or something else.

**Comment by yaoyutian** [comment]
RTX2070 blank black terminal; installed cuda 8,9,10.environment path may not set right
F:\Code_Ai\openpose-1.4.0-win64-gpu-binaries>bin\OpenPoseDemo.exe
Starting OpenPose demo...
Auto-detecting camera index... Detected and opened camera 0.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
F1025 01:09:38.918107  6992 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***

**Comment by soulslicer** [comment]
Can you all please turn on the logging feature and run it.

cmake -DPROFILER_ENABLED=ON ..

**Comment by gineshidalgo99** [comment]
Follow the GitHub issue template, and include all the details it indicates in there, otherwise we can't help much. (closed in the meanwhile)

For the GPU binaries (@yaoyutian ), they are compiled with CUDA 8, so you can't use Turing / Volta on it, you will have to compile OpenPose from scratch in Windows.

**Comment by tech-gh** [comment]
@gineshidalgo99 @soulslicer Got the same issue @yaoyutian mentioned on Oct 24.  Opened as https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/996 with details requested in GitHub issue template
