### ISSUE TITLE
Flickering orientation (left vs right hand/arm)

### ISSUE THREAD

**Issue by seadra** [CMU-Perceptual-Computing-Lab/openpose#865]
(Using the latest master branch, CPU-only, running the command `openpose--video video.avi --write_video out.avi  --number_people_max 1` on Linux.)

Sometimes, openpose gets confused about which arm/leg is the left one and which one is the right, and this happens in consecutive frames. I've seen left and right flipping 7 times in ~10 frames.

This happened to me when a character turns his back, but sometimes faces back to the camera.

Such sudden jumps should have a large error cost associated with them (since they correspond to a 180 rotation in a single frame!), no?

**Comment by soulslicer** [comment]
Can you send to our email a sample video

**Comment by seadra** [comment]
Thanks, I will do that next week!

**Comment by seadra** [comment]
Sorry, been busy recently. Will try to cut that part of the video soon.

**Comment by samarth-robo** [comment]
Hi @seadra did you get this figured out? I'm observing the same problem.

**Comment by seadra** [comment]
Nope, the problem persists.
