### ISSUE TITLE
Inference Time difference for multi-person vs single-person

### ISSUE THREAD

**Issue by vikasguptaiisc** [CMU-Perceptual-Computing-Lab/openpose#867]
In the readme, it is written that for Body Pose estimation, the inference time is independent of the number of persons.

When I run the code for 1 or 2 persons, the difference is negligible. But when I compare with 1 person vs 9 person, then the inference time becomes 1.5 times that of single person.

Given below are the images I have used.
NOTE : The images are of same size.

![000000000785](https://user-images.githubusercontent.com/7848248/46629682-644e8800-cb5f-11e8-95cb-555baeea2de1.jpg)

![000000044279](https://user-images.githubusercontent.com/7848248/46629700-6adcff80-cb5f-11e8-8c0f-3e11035d6640.jpg)

![000000016309](https://user-images.githubusercontent.com/7848248/46629707-6dd7f000-cb5f-11e8-92e5-15d28a525205.jpg)

**Comment by gineshidalgo99** [comment]
I can run 20 people at about 22FPS in a Titan Xp while 1 person is about 23-24 FPS, so the difference is less than 10%. Something else is going on in your particular case. If you want me to give you a possible higher insight to your particular case, please post the hardward config as our GitHub issue template indicates. Thanks.
