### ISSUE TITLE
unable to download models

### ISSUE THREAD

**Issue by avrana** [CMU-Perceptual-Computing-Lab/openpose#868]
Hi,
for several days I am unable to download trained models. Could you please check the server?
Unsucccesfully trying both
`openpose-1.4.0-win64-cpu-binaries\models\getModels.bat`
and
`http://posefs1.perception.cs.cmu.edu/OpenPose/models/pose/body_25/pose_iter_584000.caffemodel` from browser.

**Comment by gineshidalgo99** [comment]
I can download it right now. Best

**Comment by avrana** [comment]
Thank you for reaction ... using tor browser I am able to download it ... maybe some network/region limitation ...

Thank you  again.
