### ISSUE TITLE
Obtain Heatmaps from Python Interface

### ISSUE THREAD

**Issue by christian-lanius** [CMU-Perceptual-Computing-Lab/openpose#870]
Hi everybody,
Using the latest version, is it currently possible to obtain the heatmaps using the python interface? I dug a bit through the code, but it does not seem to be possible. I assume that one would need a function in the python/_openpose.cpp file which copies the contents from the heatMapsBlob pointer to an array which can be returned to the calling python code?

**Comment by soulslicer** [comment]
We are working on a completely new Python API using Pybind11 which should automatically allow access to all the C++ API's without needing to write too much code. This will take a few months

**Comment by gineshidalgo99** [comment]
Hopefully it should be release about January, check the latest feature section.
