### ISSUE TITLE
Build error on Mac OSX

### ISSUE THREAD

**Issue by r-wettstaedt** [CMU-Perceptual-Computing-Lab/openpose#878]
### Issue Summary
When building with `make` the following error appears.

### Executed Command (if any)
```bash
make -j`nproc`
```

### Errors (if any)
https://pastebin.com/xE1uuwRt

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/xE1uuwRt

2. **OpenPose version**: I tried it with both, latest commit from `master` and the tag `v1.4.0`

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Mac OSX 10.14
    - **Release or Debug mode**?: release
    - **Compiler**: XCode 10.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: default from Homebrew, Version 1.0
    - **CMake version**: 3.6.1
    - **OpenCV version**: default from Homebrew, Version 3.4.2

6. If **GPU mode** issue:
    - **CUDA version**:
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**: 2,4 GHz Intel Core i5
    - Total **RAM memory** available: 8GB

8. If **Python** API:
    - **Python version**: 3.6.5
    - **Numpy version**: 1.13.3

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by airinterface** [comment]
cd <your_buiid_dir>

cmake --build . --config Release

cmake --build . --config Debug

will let cmake generate  .dylib for mac.
