### ISSUE TITLE
Can't choose compiler

### ISSUE THREAD

**Issue by joaqo** [CMU-Perceptual-Computing-Lab/openpose#879]
### Issue Summary
I get `unsupported GNU version! gcc versions later than 6 are not supported!` when trying to run make -j\`nproc\`. I see that I am getting 
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
```
when running make, which clearly shows I am using the wrong compiler version, but I can't for the life of me make openpose use `/usr/bin/gcc-6`. I tried setting it up when configuring the build in cmake-gui but it ignores my settings for some reason.

**Comment by christian-lanius** [comment]
What I did was use update-alternatives:
https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version

**Comment by joaqo** [comment]
@christian-lanius this works perfectly, thanks!

**Comment by hhoomn** [comment]
If you don't like change the default gcc, g++:
using the command `CC='gcc-6' CXX='g++-6' make -j`nproc` ` worked for me

**Comment by Joeboy** [comment]
For anybody else with the same issue, the simple, non-invasive method suggested by hhoomn works, but you need to set the env vars *before* running cmake for the first time. At least, that is what I found trying to build it on Ubuntu 20.10. eg.

```
rm -rf build && mkdir build && cd build
CC='gcc-9' CXX='g++-9' cmake -DUSE_CUDNN=OFF -DBUILD_PYTHON=ON ..
CC='gcc-9' CXX='g++-9' make -j7
```

Just leaving this here in case it saves somebody some time and confusion.

**Comment by John-HarringtonNZ** [comment]
@Joeboy Thanks for that! That worked for me with a slight modification. 

Be sure to specify the `gcc` version that matches the `gcc` requirements mentioned by the errors. As of July 2020 (Ubuntu 20.04), this should work:

`rm -rf build && mkdir build && cd build`
`CC='gcc-8' CXX='g++-8' cmake -DUSE_CUDNN=OFF -DBUILD_PYTHON=ON .. `
`CC='gcc-8' CXX='g++-8' make -j7`
