### ISSUE TITLE
Ubuntu:OpenPose demo run failure parsing pose.caffemodel

### ISSUE THREAD

**Issue by salians** [CMU-Perceptual-Computing-Lab/openpose#880]
OpenPose failed to load bodypose using both these documented commands: 

```
# Ubuntu and Mac
./build/examples/openpose/openpose.bin --video examples/media/video.avi
# With face and hands
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand
```

The model loading error/s are in failing to parse params in the caffe model. I am using caffe from the BVLC main branch sync'd 2 days back using "git clone https://github.com/BVLC/caffe and then caffe paths were setup as documented in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#custom-caffe-ubuntu-only

The model parsing error is as follows which appear after the popup UI window dims out:
```
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 4 GPU(s), using 4 of them starting at GPU 0.
[libprotobuf ERROR google/protobuf/message_lite.cc:121] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F1012 16:52:34.120153 20513 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7fb43f145daa  (unknown)
    @     0x7fb43f145ce4  (unknown)
    @     0x7fb43f1456e6  (unknown)
    @     0x7fb43f148687  (unknown)
    @     0x7fb43ebfbf1e  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fb43ec39867  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fb4415383fd  op::NetCaffe::initializationOnThread()
    @     0x7fb44140be56  op::addCaffeNetOnThread()
    @     0x7fb44140cf0a  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fb441411be0  op::PoseExtractorNet::initializationOnThread()
    @     0x7fb441408431  op::PoseExtractor::initializationOnThread()
    @     0x7fb441403641  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fb44141fff1  op::SubThread<>::initializationOnThread()
    @     0x7fb441423e88  op::Thread<>::initializationOnThread()
    @     0x7fb44142407c  op::Thread<>::threadFunction()
    @     0x7fb440ed9a60  (unknown)
    @     0x7fb43e829184  start_thread
    @     0x7fb440946ffd  (unknown)
    @              (nil)  (unknown)
```

Another issue with --face and --hand flags passed I was expecting other models under hand and face folders to be used instead it still uses the model under the pose folder : models/pose/body_25/...

Any ideas on how  I can get past this model parsing error?

**Comment by zoujq98** [comment]
hello~I have the same problem. Have you solve the problem?

**Comment by salians** [comment]
No I couldn't resolve it and I haven't had a chance to get back to it. If I make progress I'll update.

**Comment by lagidigu** [comment]
Same problem here...

**Comment by wakingking77** [comment]
I have the same problem..  Do you solve it???  Thank you !

**Comment by salians** [comment]
No luck. 
@gineshidalgo99 any ideas?

**Comment by matze-newtown** [comment]
I also have this problem. Would be thankful for any help...

**Comment by gineshidalgo99** [comment]
It seems like you are using a custom Caffe version? This post is invalid given that no hw config is added.

**Comment by salians** [comment]
@gineshidalgo99 I did mention I am using a custom caffe version from BVLC main branch and followed the docs on using the custom doc. On HW I have 4 NVIDIA TitanX as seen in the output spew. There are so many of us with the same issue that the HW config should matter but the version of the caffe does seem to matter so instead of closing why not update with a source URL to the caffe version that can be used to build open pose?

**Comment by gineshidalgo99** [comment]
I am sorry, but I can't replicate this error. I am using latest OpenPose and this error does not occur on any of my machines (I have Ubuntu 14 and 16 machines), so I can't debug it.

**Comment by algorithm-josh** [comment]
I am getting this issue on my machine as well Ubuntu 18.04.

Previously this process worked for me on commit `5295f2f38609a6ff24739b37cf348b9c9324faef` but I can not reproduce the working build with this commit or get a working build with the latest commit on master `7aaea878231f78c798df1e67d3f31ee9527b`

GPU info:
```
$ nvidia-smi                                                                     
Thu Dec 20 11:32:22 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.73       Driver Version: 410.73       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   46C    P8     9W / 180W |     86MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1082      G   /usr/lib/xorg/Xorg                            67MiB |
|    0      1123      G   /usr/bin/gnome-shell                          16MiB |
+-----------------------------------------------------------------------------+
```

To reproduce run the following commands:
```
$ git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git ; cd openpose ; git submodule update --init --recursive; mkdir build; cd build; cmake -DBUILD_PYTHON=ON .. ; make -j12; cd ..
... Normal cmake and build output ...

$ ./build/examples/openpose/openpose.bin --video examples/media/video.avi 
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F1220 11:29:27.930549 21758 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.ca
ffemodel
*** Check failure stack trace: ***
    @     0x7f0c791b50cd  google::LogMessage::Fail()
    @     0x7f0c791b6f33  google::LogMessage::SendToLog()
    @     0x7f0c791b4c28  google::LogMessage::Flush()
    @     0x7f0c791b7999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0c78cff191  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f0c78c968ba  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f0c7aecd5fb  op::NetCaffe::initializationOnThread()
    @     0x7f0c7aef5c2c  op::addCaffeNetOnThread()
    @     0x7f0c7aef70fe  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f0c7aefc963  op::PoseExtractorNet::initializationOnThread()
    @     0x7f0c7aef1d51  op::PoseExtractor::initializationOnThread()
    @     0x7f0c7aeecc81  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f0c7af2dbc1  op::SubThread<>::initializationOnThread()
    @     0x7f0c7af313e8  op::Thread<>::initializationOnThread()
    @     0x7f0c7af315cb  op::Thread<>::threadFunction()
    @     0x7f0c7a32657f  (unknown)
    @     0x7f0c79a486db  start_thread
    @     0x7f0c79d8188f  clone
fish: “./build/examples/openpose/openp…” terminated by signal SIGABRT (Abort)

**Comment by gineshidalgo99** [comment]
@algorithm-josh That's usually the model being corrupted. Tried re-downloading caffemodel and protototxt

**Comment by algorithm-josh** [comment]
@gineshidalgo99 thanks for the quick response.

I have tried removing the cafemodels and redownloading them using `bash models/getModels.sh` which did not work even with a full recompilation.

Is there somewhere I can download the `pose_deploy.prototxt` files from?

**Comment by algorithm-josh** [comment]
@gineshidalgo99 Sorry just read your update that I do not need to worry about the prototxt files.

Is there a way I can get the sha256sum of the caffemodel files? They seem to be consistently corrupted during the download as I have tried redownloading them multiple times with no luck.

**Comment by gineshidalgo99** [comment]
Thinking more about it, can you run COCO or MPII model? If so, then it's BODY_25 corrupted. Otherwise, maybe Caffe issue?

**Comment by algorithm-josh** [comment]
COCO works perfectly. I'll keep trying the download for BODY_25 until it works

**Comment by gineshidalgo99** [comment]
OK, would this one work (Dropbox download from a browser should be quite reliable)
https://www.dropbox.com/s/03r8pa8sikrqv62/pose_iter_584000.caffemodel?dl=0

**Comment by algorithm-josh** [comment]
That works thank you very much for that!

**Comment by gineshidalgo99** [comment]
Thanks for helping debug the issue, I will add all these steps to the doc/faq.md.

**Comment by akhalili** [comment]
downloading pose_iter_584000.caffemodel from dropbox dosn't work for me

**Comment by marvin2yan** [comment]
I met the same issue,how to fix it ?

**Comment by codingbelief** [comment]
Revert the [clip layer pull request](https://github.com/CMU-Perceptual-Computing-Lab/caffe/commit/dc6d3303a45e8c5a0fe7249881ca6bd8387c9203) of caffe works for me.
It's just a temporary workaround.

```
git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
git submodule update --init --recursive

mkdir build
cd build
cmake \
  -DBUILD_CAFFE=ON \
  -DDOWNLOAD_BODY_25_MODEL=ON \
  -DDOWNLOAD_BODY_COCO_MODEL=OFF \
  -DDOWNLOAD_FACE_MODEL=OFF \
  -DDOWNLOAD_HAND_MODEL=OFF \
  -DDOWNLOAD_BODY_MPI_MODEL=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  ..

cd ../3rdparty/caffe/
git reset --hard 974172cd6b3b61163354b7c072f039fadc4c1339
git revert -m 1 dc6d3303a45e8c5a0fe7249881ca6bd8387c9203

cd ../../build/
make -j`nproc`
```

**Comment by gineshidalgo99** [comment]
I was finally able to replicate the error and fix it. Our latest https://github.com/CMU-Perceptual-Computing-Lab/caffe
 should handle it now. Simply remove the whole OpenPose folder and re-install it completely (so the new Caffe is updated, otherwise the OpenPose Caffe would not be updated).
