### ISSUE TITLE
Virus detected!

### ISSUE THREAD

**Issue by Usernames10** [CMU-Perceptual-Computing-Lab/openpose#881]
Your file "openpose.dll" inside "openpose-1.4.0-win64-gpu-binaries-recommended.zip" for windows contains a virus and was detected by Bitdefender Antivirus.

**Comment by gineshidalgo99** [comment]
Don't worry, OpenPose does not contain any virus. Not sure why that antivirus considers so.

**Comment by Usernames10** [comment]
The threat's name is: Gen:Variant.Razy.384522,  It shows on GPU versions
but not into CPU ones. It's some sort of troyan for Bitcoin mining.
Obviously works on gpu resources.

Well it might not be a virus itself.

**Comment by gineshidalgo99** [comment]
Hi, I have run my antivirus (both Windows 10 one + Kaspersky Anti-Virus) but they don't seem to find it. I'll check with other antiviruses. Thanks
