### ISSUE TITLE
（win7）report errors after running OpenPoseDemo

### ISSUE THREAD

**Issue by vegetabee** [CMU-Perceptual-Computing-Lab/openpose#882]
The demo of 1.3.0 could be successfully finished, but when I ran the 1.4.0, it errored:

*** Check failure stack trace: ***
F1017 07:50:15.537199  5808 syncedmem.cpp:71] 
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

Sincerely hoping for some guidance.

**Comment by gineshidalgo99** [comment]
1.4.0 uses BODY_25 (faster & more accurate & include foot keypoitns), but it uses more memory. I guess you only have a 2GB memory, either reduce the net_resolution or switch back to COCO model.
