### ISSUE TITLE
_openpose.dll in Release folder, not proper win32 application

### ISSUE THREAD

**Issue by MartinFultot** [CMU-Perceptual-Computing-Lab/openpose#884]
I have followed strictly all the instructions for Python.
Installed with CMake, checked BUILD_PYTHON

Then run the visual studio project (Using Visual studio 2017 x64 with -T v140

Then set RELEASE x64 and choose the openpose library as start project.
21 projects built successfully, 1 failed.

build/python/openpose/Release 
has 
_openpose.dll
_openpose.exp
_openpose.lib.

I go to build/examples/tutorial_api_python, open the command prompt there (already on the right folder) execute 1_extract_pose.py and get 

openpose library not found, have you checked BUILD_PYTHON ? YES I HAVE
Are you sure you are in the right folder ? YES I AM

I have tried 100 more things, including building the project several times with CMake and same error systematically.

Going to the build/python/openpose/ and running openpose.py gives me

File "C:\Python27\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library raise OSError ("no file with expected extension")
So I changed the line just to test, under the exception it tries a Debug folder which doesn't exist. Instead I pasted the same command to load from Release again, and that's when the error is "not a proper win32 file."

So it looks like the .dll is being created but with bugs. WHY? 

Please help!

**Comment by soulslicer** [comment]
Please follow the issue template, which also involves pasting your build log. Something has failed to build clearly and may be causing issues

**Comment by MartinFultot** [comment]
Thanks for the reply, I have submitted a new issue
