### ISSUE TITLE
Could not install openpose on mac

### ISSUE THREAD

**Issue by ericklarac** [CMU-Perceptual-Computing-Lab/openpose#885]
I was following the installation steps and I'm facing the following error, wish someone can help me:

![image](https://user-images.githubusercontent.com/8422946/47053839-7c806180-d174-11e8-81c1-1861c5dd89e6.png)

![image](https://user-images.githubusercontent.com/8422946/47053865-95891280-d174-11e8-8a72-2e6ab8cf4581.png)

![image](https://user-images.githubusercontent.com/8422946/47053867-9d48b700-d174-11e8-85ec-efe89acc5b08.png)

**Comment by rdv0011** [comment]
try to install protobuf 3.5.1 manually from sources

**Comment by bahdah** [comment]
The steps to manually installing protobuf 3.5.1 on mac will be much appreciated.
