### ISSUE TITLE
openpose.dll is infected with Gen:Variant.Razy

### ISSUE THREAD

**Issue by cleverlight** [CMU-Perceptual-Computing-Lab/openpose#887]
### Issue Summary
* I've downloaded [v1.4.0](https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/download/v1.4.0/openpose-1.4.0-win64-gpu-binaries_recommended.zip) and expanded it using 7zip.
* My virus software scanned and restricted openpose.dll.  After the scan it moved the file to the Virus chest and reported it was infected with Gen:Variant.Razy.
* I repeated the operation on [1.3.0](https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/download/v1.3.0/openpose-1.3.0-win64-gpu-binaries.zip) and got the same result.
* I can confirm that [1.2.1](https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/download/v1.2.1/openpose-1.2.1-win64-binaries.zip) does not trigger the same warning, so I presume the infection occurred between January and March.

### Executed Command (if any)
None

### OpenPose Output (if any)
None

### Errors (if any)
None

### Type of Issue
- Execution error

### Your System Configuration
1. Windows 10 Professional, up-to-date on 20/10/2018
BitDefender Antivirus Plus 2019
Build 23.0.11.48 (last update 16/10/2018 11:36)
Threat Database updates: 11700521, engine 7.77893

2. **OpenPose version**: 
1.4.0
1.3.0

3. **General configuration**:
Unable to install due to virus scanner warning

4. **Non-default settings**:
None

5. **3rd-party software**:
https://www.bitdefender.co.uk/

9. If **Windows** system:
- Portable demo, although the issue seems to be with openpose.dll which is a compiled library.

**Comment by elliotwoods** [comment]
On my machine I'm also getting this virus detected in the 1.4.0 download.
Chrome will delete the download after complaining that it contains a virus, and Windows Defender will delete the openpose.dll if you have it installed anywhere and try and run OpenPoseDemo.exe

**Comment by elliotwoods** [comment]
I've made a build of openpose here from the recent github version
https://github.com/elliotwoods/calibrating-with-python-opencv.git 

note that the calibration.exe doesn't work with this version (but you can use the one from the CPU build of OpenPose online)

Another note : this was built on a computer which had the other openpose (possibly infected) files on it. So best to virus check this one also.

**Comment by philippwerner** [comment]
Same Problem for me. The Virus is found by several Scanners:
https://www.virustotal.com/de/file/6fa6eb50d229c1bfd95aa79d5a9f70712d05a9ad026a5e0dc6f5fad4afca7a9d/analysis/
