### ISSUE TITLE
Compilation error with opencv 3

### ISSUE THREAD

**Issue by mohamedsuhail** [CMU-Perceptual-Computing-Lab/openpose#89]
### Issue summary
Compilation error with the new face and hand tracking version, with OpenCV 3.

### Executed command (if any)
./install_openpose.sh 

### OpenPose output (if any)
src/openpose/utilities/keypoint.cpp: In function ‘void op::renderKeypointsCpu(op::Array<float>&, const op::Array<float>&, const std::vector<unsigned int>&, std::vector<float>, float, float)’:
src/openpose/utilities/keypoint.cpp:152:29: error: ‘line’ is not a member of ‘cv’
                             cv::line(frameR, keypoint1, keypoint2, color[0], thicknessLine, lineType, shift);

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Help wanted

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu 16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8
**cuDNN version**: latest
**GPU model** (`nvidia-smi`): nvidia quadro 4000
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
Hi, does it work if you add this line at the top of `src/openpose/utilities/keypoint.cpp`?
`#include <opencv2/imgproc/imgproc.hpp> // cv::line, cv::circle`

**Comment by mohamedsuhail** [comment]
that fix cleared the previous issue, now when i run the install script, i see

In file included from src/openpose/experimental/hand/handRenderer.cpp:3:0:
./include/openpose/experimental/hand/handParameters.hpp:28:43: error: ‘POSE_DEFAULT_ALPHA_POSE’ was not declared in this scope
     const auto HAND_DEFAULT_ALPHA_HANDS = POSE_DEFAULT_ALPHA_POSE;
                                           ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/experimental/hand/handRenderer.o' failed
make: *** [.build_release/src/openpose/experimental/hand/handRenderer.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/openpose/experimental/face/faceRenderer.cpp:3:0:
./include/openpose/experimental/face/faceParameters.hpp:31:42: error: ‘POSE_DEFAULT_ALPHA_POSE’ was not declared in this scope
     const auto FACE_DEFAULT_ALPHA_FACE = POSE_DEFAULT_ALPHA_POSE;
                                          ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/experimental/face/faceRenderer.o' failed
make: *** [.build_release/src/openpose/experimental/face/faceRenderer.o] Error 1
In file included from ./include/openpose/experimental/filestream/headers.hpp:5:0,
                 from src/openpose/experimental/filestream/defineTemplates.cpp:1:
./include/openpose/experimental/filestream/wPoseJsonCocoSaver.hpp: In instantiation of ‘void op::experimental::WPoseJsonCocoSaver<TDatums>::workConsumer(const TDatums&) [with TDatums = std::shared_ptr<std::vector<op::Datum> >]’:
src/openpose/experimental/filestream/defineTemplates.cpp:5:5:   required from here
./include/openpose/experimental/filestream/wPoseJsonCocoSaver.hpp:81:25: error: ‘const struct op::Datum’ has no member named ‘poseKeyPoints’
                         spPoseJsonCocoSaver->record(tDatum.poseKeyPoints, imageId);
                         ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/experimental/filestream/defineTemplates.o' failed
make: *** [.build_release/src/openpose/experimental/filestream/defineTemplates.o] Error 1
In file included from ./include/openpose/experimental/hand/headers.hpp:7:0,
                 from src/openpose/experimental/hand/defineTemplates.cpp:1:
./include/openpose/experimental/hand/handParameters.hpp:28:43: error: ‘POSE_DEFAULT_ALPHA_POSE’ was not declared in this scope
     const auto HAND_DEFAULT_ALPHA_HANDS = POSE_DEFAULT_ALPHA_POSE;
                                           ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/experimental/hand/defineTemplates.o' failed
make: *** [.build_release/src/openpose/experimental/hand/defineTemplates.o] Error 1
In file included from ./include/openpose/experimental/face/headers.hpp:7:0,
                 from src/openpose/experimental/face/defineTemplates.cpp:1:
./include/openpose/experimental/face/faceParameters.hpp:31:42: error: ‘POSE_DEFAULT_ALPHA_POSE’ was not declared in this scope
     const auto FACE_DEFAULT_ALPHA_FACE = POSE_DEFAULT_ALPHA_POSE;
                                          ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/experimental/face/defineTemplates.o' failed
make: *** [.build_release/src/openpose/experimental/face/defineTemplates.o] Error 1
In file included from src/openpose/experimental/hand/handExtractor.cpp:3:0:
./include/openpose/experimental/hand/handParameters.hpp:28:43: error: ‘POSE_DEFAULT_ALPHA_POSE’ was not declared in this scope
     const auto HAND_DEFAULT_ALPHA_HANDS = POSE_DEFAULT_ALPHA_POSE;
                                           ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/src/openpose/experimental/hand/handExtractor.o' failed
make: *** [.build_release/src/openpose/experimental/hand/handExtractor.o] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.

**Comment by gineshidalgo99** [comment]
You are using an old version (experimental/hand/ is not longer there). Could you try downloading the last version and try it?
(in addition I just pushed the fix to your first question, so it should be ready-to-compile without any changes). Let me know your result. Thanks!

**Comment by mohamedsuhail** [comment]
Perfect! Thanks for your help. Works like a charm with opencv 3.
