### ISSUE TITLE
ROS Wrapper example

### ISSUE THREAD

**Issue by graberj** [CMU-Perceptual-Computing-Lab/openpose#891]
### Issue Summary

Would it be possible for an example of a ROS wrapper to be uploaded? I have been attempting to implement one myself but I don't think I'll be able to, as my programming knowledge is a bit behind what it would need to be for me to successfully write one.

Ideally, it could take any rgb image as a stream of type image, and publish both the detected keypoints, and the new image openpose would render.

### Type of Issue
- Help wanted
- Enhancement / offering possible extensions / pull request / etc

**Comment by ravijo** [comment]
@graberj Although this is an old topic. However if you are still looking for an answer, I recommend you to checkout my ROS package [here](https://github.com/ravijo/ros_openpose). Hope it helps.

Cheers!

**Comment by gineshidalgo99** [comment]
Thanks @ravijo ! I'll added it to our doc/installation.md#Community-Based Work :)

**Comment by ravijo** [comment]
Thank you very much, @gineshidalgo99 

I really appreciate your kind gesture.
