### ISSUE TITLE
Make Errors: undefined reference to `gluPerspective'  &  `gluLookAt'

### ISSUE THREAD

**Issue by wakingking77** [CMU-Perceptual-Computing-Lab/openpose#894]
This is where I stuck：
```

[ 88%] Linking CXX executable 1_extract_from_image.bin
../../src/openpose/libopenpose.so.1.4.0: undefined reference to `gluPerspective'
../../src/openpose/libopenpose.so.1.4.0: undefined reference to `gluLookAt'
collect2: error: ld returned 1 exit status
examples/tutorial_pose/CMakeFiles/1_extract_from_image.bin.dir/build.make:155: recipe for target 'examples/tutorial_pose/1_extract_from_image.bin' failed
make[2]: *** [examples/tutorial_pose/1_extract_from_image.bin] Error 1
CMakeFiles/Makefile2:1282: recipe for target 'examples/tutorial_pose/CMakeFiles/1_extract_from_image.bin.dir/all' failed
make[1]: *** [examples/tutorial_pose/CMakeFiles/1_extract_from_image.bin.dir/all] Error 2
mak
```e[1]: *** Waiting for unfinished jobs....



Who know why? Thank you very much!!

**Comment by sergionegri** [comment]
We struggled 2 days with that problem. You have to modify the CmakeList like follows:

if (WITH_3D_RENDERER)
    set(OpenPose_3rdparty_libraries ${OpenPose_3rdparty_libraries} ${GLUT_LIBRARY} **-lGLU**)
endif (WITH_3D_RENDERER)

Please notice the -lGLU parameter added.

Then you also have to make sure the libGL.so links are not broken.

**Comment by wakingking77** [comment]
> We struggled 2 days with that problem. You have to modify the CmakeList.txt as follows:
> 
> if (WITH_3D_RENDERER)
> set(OpenPose_3rdparty_libraries ${OpenPose_3rdparty_libraries} ${GLUT_LIBRARY} **-lGLU**)
> endif (WITH_3D_RENDERER)
> 
> Please notice the -lGLU parameter added.
> 
> Then you also have to make sure the libGL.so links are not broken.

Thank you very much! I will try it tonight,and I hope it could work!!

**Comment by wakingking77** [comment]
> We struggled 2 days with that problem. You have to modify the CmakeList.txt as follows:
> 
> if (WITH_3D_RENDERER)
> set(OpenPose_3rdparty_libraries ${OpenPose_3rdparty_libraries} ${GLUT_LIBRARY} **-lGLU**)
> endif (WITH_3D_RENDERER)
> 
> Please notice the -lGLU parameter added.
> 
> Then you also have to make sure the libGL.so links are not broken.

It can work! I make passed! Thank you very much!!!

**Comment by gineshidalgo99** [comment]
Issue fixed after PR #771

**Comment by rajhlinux** [comment]
I'm getting the same issue...

I added starting on line 362:

```
if (WITH_3D_RENDERER)
set(OpenPose_3rdparty_libraries {GLUT_LIBRARY} -lGLU)
add_definitions(-DUSE_3D_RENDERER)
endif (WITH_3D_RENDERER)
```

But get the error:

```
ld: error: unable to find library -l{GLUT_LIBRARY}
ld: error: unable to find library -lGLU
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
--- src/openpose/unity/libopenpose_unity.so ---
```

**Comment by Hirva98** [comment]
I am getting this error

 Linking CXX executable tutorial_api_thread_2_user_input_processing_output_and_datum.bin
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidSphere'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutDisplayFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutGetModifiers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutLeaveMainLoop'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowPosition'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSwapBuffers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowSize'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidCone'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMouseFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMainLoopEvent'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutPostRedisplay'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutCreateWindow'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInit'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutKeyboardFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMotionFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitDisplayMode'
collect2: error: ld returned 1 exit status
examples/calibration/CMakeFiles/calibration.bin.dir/build.make:147: recipe for target 'examples/calibration/calibration.bin' failed
make[2]: *** [examples/calibration/calibration.bin] Error 1
CMakeFiles/Makefile2:1098: recipe for target 'examples/calibration/CMakeFiles/calibration.bin.dir/all' failed
make[1]: *** [examples/calibration/CMakeFiles/calibration.bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidSphere'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutDisplayFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutGetModifiers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutLeaveMainLoop'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowPosition'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSwapBuffers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowSize'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidCone'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMouseFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMainLoopEvent'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutPostRedisplay'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutCreateWindow'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInit'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutKeyboardFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMotionFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitDisplayMode'
collect2: error: ld returned 1 exit status
examples/deprecated/CMakeFiles/tutorial_api_thread_1_user_processing_function.bin.dir/build.make:147: recipe for target 'examples/deprecated/tutorial_api_thread_1_user_processing_function.bin' failed
make[2]: *** [examples/deprecated/tutorial_api_thread_1_user_processing_function.bin] Error 1
CMakeFiles/Makefile2:1150: recipe for target 'examples/deprecated/CMakeFiles/tutorial_api_thread_1_user_processing_function.bin.dir/all' failed
make[1]: *** [examples/deprecated/CMakeFiles/tutorial_api_thread_1_user_processing_function.bin.dir/all] Error 2
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidSphere'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutDisplayFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutGetModifiers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutLeaveMainLoop'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowPosition'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSwapBuffers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowSize'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidCone'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMouseFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMainLoopEvent'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutPostRedisplay'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutCreateWindow'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInit'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutKeyboardFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMotionFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitDisplayMode'
collect2: error: ld returned 1 exit status
examples/deprecated/CMakeFiles/tutorial_api_thread_2_user_input_processing_output_and_datum.bin.dir/build.make:147: recipe for target 'examples/deprecated/tutorial_api_thread_2_user_input_processing_output_and_datum.bin' failed
make[2]: *** [examples/deprecated/tutorial_api_thread_2_user_input_processing_output_and_datum.bin] Error 1
CMakeFiles/Makefile2:1176: recipe for target 'examples/deprecated/CMakeFiles/tutorial_api_thread_2_user_input_processing_output_and_datum.bin.dir/all' failed
make[1]: *** [examples/deprecated/CMakeFiles/tutorial_api_thread_2_user_input_processing_output_and_datum.bin.dir/all] Error 2
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidSphere'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutDisplayFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutGetModifiers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutLeaveMainLoop'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowPosition'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSwapBuffers'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitWindowSize'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutSolidCone'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMouseFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMainLoopEvent'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutPostRedisplay'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutCreateWindow'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInit'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutKeyboardFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutMotionFunc'
../../src/openpose/libopenpose.so.1.7.0: undefined reference to `glutInitDisplayMode'
collect2: error: ld returned 1 exit status
examples/deprecated/CMakeFiles/tutorial_add_module_custom_post_processing.bin.dir/build.make:147: recipe for target 'examples/deprecated/tutorial_add_module_custom_post_processing.bin' failed
make[2]: *** [examples/deprecated/tutorial_add_module_custom_post_processing.bin] Error 1
CMakeFiles/Makefile2:1124: recipe for target 'examples/deprecated/CMakeFiles/tutorial_add_module_custom_post_processing.bin.dir/all' failed
make[1]: *** [examples/deprecated/CMakeFiles/tutorial_add_module_custom_post_processing.bin.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2


I tried : 
1. if (WITH_3D_RENDERER)
set(OpenPose_3rdparty_libraries 
{GLUT_LIBRARY} -lGLU)
endif (WITH_3D_RENDERER)

I also have all the libraries correctly installed and they are being detected by cmake-gui but when I compile with openpose. I get this error.
