### ISSUE TITLE
Calculating Latency/Lag

### ISSUE THREAD

**Issue by Doremii46** [CMU-Perceptual-Computing-Lab/openpose#895]
Are there any suggested methods for calculating the latency？
I tried to add a t1=cv::getTickCount() in cv::Mat VideoCaptureReader::getRawFrame() and t2=cv::getTickCount() when Openpose output the result.
But I feel this method is calculating the frame cycle time.
Do you have any methods for calculating the lag time?

**Comment by gineshidalgo99** [comment]
doc/faq.md#how-to-measure-the-latency-time
