### ISSUE TITLE
Extend towards web?

### ISSUE THREAD

**Issue by miktoki** [CMU-Perceptual-Computing-Lab/openpose#896]
Have you considered making a web implementation of OpenPose similar to [PoseNet](https://github.com/tensorflow/tfjs-models/tree/master/posenet)?
I believe a lot of code, if written in c/c++ could be reused using WebAssembly, and there seems to be ways of utilizing the gpu on the web via WebGL (see eg [gpu.js](http://gpu.rocks/), [turbo.js](https://turbo.js.org/).

**Comment by ctralie** [comment]
@miktoki how does the accuracy of PoseNet compare to that of OpenPose?

**Comment by miktoki** [comment]
@ctralie It is hard to quantify the accuracy as Google has not released any benchmarks AFAIK. Based on my experience it has lower accuracy but is less computationally intensive than the full OpenPose model. I find it inferior to OpenPose in separating people, and has lower precision but higer recall.

The architecture is essentially MobilenetV1 with a keypoint heatmap and offset vectors for each keypoint (using COCO keypoints). The model is also a bottom-up pose estimation model, but for multiple pose estimation it imposes a configurable upper limit on the number of people to detect. The offset vectors which serve a similar purpose to the Part Affinity Field, but without connecting parts, instead giving an estimate of the offset from a given coordinate to where one would expect a given keypoint to be.

**Comment by gineshidalgo99** [comment]
Only checking the visual results and gifs in their README, the accuracy is much lower, as a trade-off for speed. Running OpenPose with super low net_resolution should match their faster speed and lower accuracy.

**Comment by ctralie** [comment]
Thank you both for the detailed info!
