### ISSUE TITLE
Mac Install, error running make command in build folder - 

### ISSUE THREAD

**Issue by heaversm** [CMU-Perceptual-Computing-Lab/openpose#898]
Mac OSX 10.13.6 Intel Core i7 (4 core)
NVidia GForce GT 650M (Cuda Compatible)

### Issue Summary

Used CMake to successfully configure and generate the code, but then when running cd build/
make -j`nproc`, error occurs after this step:

```
[ 82%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
```

First warning seen in log:

```
In file included from /Users/mikeheavers/Sites/prototypes/ml/openpose/openpose/3rdparty/caffe/src/caffe/layers/lstm_unit_layer.cpp:6:
In file included from /Users/mikeheavers/Sites/prototypes/ml/openpose/openpose/3rdparty/caffe/include/caffe/layers/lstm_layer.hpp:11:
In file included from /Users/mikeheavers/Sites/prototypes/ml/openpose/openpose/3rdparty/caffe/include/caffe/layers/recurrent_layer.hpp:11:
/Users/mikeheavers/Sites/prototypes/ml/openpose/openpose/3rdparty/caffe/include/caffe/net.hpp:41:5: warning:
      unused typedef 'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
    LOG_EVERY_N(WARNING, 1000) << "DEPRECATED: ForwardPrefilled() "
    ^
/usr/local/include/glog/logging.h:943:30: note: expanded from macro
      'LOG_EVERY_N'
                             INVALID_REQUESTED_LOG_SEVERITY);
```

I get a number of output warnings like that, and then the last output I see (the only actual error) is:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [lib/libcaffe.1.0.0.dylib] Error 1
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-build] Error 2
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
make: *** [all] Error 2
```

Attached is my CMAKE output log, didn't look like there were any errors in there.

[CMakeOutput.log.zip](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/2520926/CMakeOutput.log.zip)

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

make -j`nproc`

### Type of Issue

- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

Latest Github (as of 10/24/2018)

3. **General configuration**:

CMake after compiling Caffe with [these instructions](http://caffe.berkeleyvision.org/install_osx.html)

**Comment by AddeNordh** [comment]
Hello @heaversm 
Did you manage to solve this issue? i have the same problem when trying to build with the 3-D Reconstruction module enabled, if i disable the module it builds without problems.
See #910 for my issue

**Comment by gineshidalgo99** [comment]
Please try the new Mac version and make a new PR if it still fails. Hopefully this new version fixes all issues + adds OpenCL (GPU) support. Thanks!

**Comment by gineshidalgo99** [comment]
Please try the new Mac version and make a new PR if it still fails. Hopefully this new version fixes all issues + adds OpenCL (GPU) support. Thanks!
