### ISSUE TITLE
zero people detect

### ISSUE THREAD

**Issue by HaoWangXiDian** [CMU-Perceptual-Computing-Lab/openpose#899]
### Configuration
1.  Ubuntu16.04, cuda8.0, cudnn5.1
2. pre-compiled caffe and opencv3.1

### OpenPose Output (if any)
zero people output for test video and images

**Comment by gineshidalgo99** [comment]
That has happened when the caffemodel has not been properly downloaded (e.g., connection drop when downloading it). Please, try downloading it manually (links in doc/installation.md), or just remove the current ones in model/ and run Cmake again.

**Comment by HaoWangXiDian** [comment]
I have tried those solutions above and it did not work for me.

**Comment by gineshidalgo99** [comment]
Try filling here all your hw configuration as the template states so I might have a better insight.
