### ISSUE TITLE
Face tracking as standalone feature

### ISSUE THREAD

**Issue by mohamedsuhail** [CMU-Perceptual-Computing-Lab/openpose#90]
### Issue summary

Can the new face tracking module work as a standalone feature without enabling body tracking?

### Type of issue
- Question

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8
**cuDNN version**: latest
**GPU model** (`nvidia-smi`): 
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
Hi Mohamed,

The face keypoint detection could work by its own, but you need an alternative face detector (e.g. the OpenCV one, because right now we are using the pose keypoints as initial face detector).

Is this what you would want?

Best

**Comment by gineshidalgo99** [comment]
Given there is no further answer, I'll assume it was solved.

**Comment by tommyshelby4** [comment]
The link you have posted above no longer exists, so would it be possible to post the currently valid link as I would be interesting in capturing exclusively 3D facial expression? Thanks in advance for your assistance.
