### ISSUE TITLE
Build error with OpenCL

### ISSUE THREAD

**Issue by rinriki** [CMU-Perceptual-Computing-Lab/openpose#901]
### Issue Summary
Failed to build OpenPose for my Intel Core i7-8809G with AMD Radeon GPU, using OpenCL.

### Errors (if any)
The program OpenPoseDemo.exe has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.

Here is the whole debug log:  https://pastebin.com/vNUmT3sa

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error

### Your System Configuration
1. **Whole console output**: https://pastebin.com/vNUmT3sa

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Windows 10 version 1803; Build 17134.345
    - **Release or Debug mode**?: Release
    - **Compiler**: Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.12.2
    - **OpenCV version**: OpenPose default

6. If **GPU mode** issue:
    - **CUDA version**:
    - **cuDNN version**:
    - **GPU model**: OPENCL

7. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel Core i7-8809G @3.10GHz with Radeon™ RX Vega M GH graphics
    - Total **RAM memory** available: 32.0GB

8. If **Python** API:
    - **Python version**:
    - **Numpy version**:

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:

**Comment by rinriki** [comment]
The error dialog says: 

The procedure entry point
?GetOpenCLContect@Caffe@caffe@ @SAAEBQEAU_cl_context@
@H_N@Z could not be located in the dynamic link library
C:\OpenPose\openpose-build\x64\Release\openpose.dll.

**Comment by gineshidalgo99** [comment]
Try removing the build folder and re-installing OP from scratch (issues when compiling both CL and other versions in the same OpeNPose folder)

**Comment by soulslicer** [comment]
@rinriki 

What GPU is it exactly? Also can you clear your build completely, and try to build in both release and debug and try for me?

**Comment by rinriki** [comment]
Thank you @gineshidalgo99 and @soulslicer for your response!  My AMD GPU is integrated with Intel CPU. (https://ark.intel.com/products/130409/Intel-Core-i7-8809G-Processor-with-Radeon-RX-Vega-M-GH-graphics-8M-Cache-up-to-4-20-GHz-)

Removed everything and tried again from scratch, then a different error dialog appeared: "The code execution cannot proceed because gflagsd.dll was not found.  Reinstalling the program may fix the probelm." and the same message for "opencv_world310.dll" and "glogd.dll."

**Comment by soulslicer** [comment]
Can you delete everything and build in release mode

**Comment by rinriki** [comment]
Deleted everything and built in release mode, but got similar error messages for "gflags.dll", "glog.dll" and "opencv_world310.dll."

**Comment by rinriki** [comment]
I fixed this issue by copying all the dlls to the Release folder.  Thank you all for your kind advice!

**Comment by soulslicer** [comment]
Weird it should have copied automatically. Thx for posting your fix
