### ISSUE TITLE
Compilation fails on Ubuntu 18.04 with undefined reference to symbol '_ZN2cv6String10deallocateEv'

### ISSUE THREAD

**Issue by meglstuart** [CMU-Perceptual-Computing-Lab/openpose#909]
### Issue Summary
I'm attempting to install openpose on Ubuntu 18.04 with Caffe and OpenCV built from source.
Build failing when compiling calibration example, with " undefined reference to symbol '_ZN2cv6String10deallocateEv'"

### Executed Command (if any)
```
cmake -DOpenCV_INCLUDE_DIRS=/home/mstuart/buildground/opencv/opencv/build/include \
-DOpenCV_LIBS_DIR=/home/mstuart/buildground/opencv/opencv/build/lib \
-DCaffe_INCLUDE_DIRS=/home/mstuart/buildground/caffe/caffe/build/install/include \
-DCaffe_LIBS=/home/mstuart/buildground/caffe/caffe/build/install/lib/libcaffe.so \ 
-DBUILD_CAFFE=OFF ..
```
and then
`make`
produces no errors until:
```
[ 87%] Linking CXX executable calibration.bin
/usr/bin/ld: CMakeFiles/calibration.bin.dir/calibration.cpp.o: undefined reference to symbol '_ZN2cv6String10deallocateEv'
//usr/lib/x86_64-linux-gnu/libopencv_core.so.3.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/calibration/CMakeFiles/calibration.bin.dir/build.make:193: recipe for target 'examples/calibration/calibration.bin' failed
make[2]: *** [examples/calibration/calibration.bin] Error 1
CMakeFiles/Makefile2:1117: recipe for target 'examples/calibration/CMakeFiles/calibration.bin.dir/all' failed
make[1]: *** [examples/calibration/CMakeFiles/calibration.bin.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

### Type of Issue
- Compilation/installation error
- Help wanted

### Your System Configuration
1. **Whole console output** Entire output from cmake, then make. Clean build:
[https://pastebin.com/vWU8jk6g](https://pastebin.com/vWU8jk6g)

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system**:  Ubuntu 18.04.1 LTS
    - **Release or Debug mode**?: release
    - **Compiler**: gcc 7.3.0

5. **3rd-party software**:
    - **Caffe version**: Compiled from source. Latest github version
    - **CMake version**: 3.12.2
    - **OpenCV version**: Compiled from source. Latest github version

**Comment by Mind-Trap** [comment]
@meglstuart did you work this out?

**Comment by DeH40** [comment]
did you work this out? i have the same problem on ubuntu16

**Comment by DeH40** [comment]
> @meglstuart did you work this out?

did you work this out?

**Comment by meglstuart** [comment]
I honestly don't remember how I worked around this. I will try to take a look at it soon, but I am busy for the next few weeks.

**Comment by stephennspencer** [comment]
I'm encountering this same issue and would love to know how it was resolved. I'm setting -DOpenCV_LIBS_DIR to the "opencv-3.4.7/lib64" path, and so it SHOULD be finding all of the OpenCV libraries (they're all there).

**Comment by meteorlin** [comment]
我的解决方法是在使用cmake-gui的时候不勾选 BUILD_EXAMPLES，这样就能直接编译到100%
