### ISSUE TITLE
thread access problem

### ISSUE THREAD

**Issue by mxmxlwlw** [CMU-Perceptual-Computing-Lab/openpose#91]
I construct openpose objects from one thread, and access them from other threads. And it crashes. Is there any method to avoid this kind of problem? Besides, can I use openpose objects in many threads?

**Comment by gineshidalgo99** [comment]
I am sorry, your description is too brief. Can you give more details? Which objects? what part of them are you accessing?

**Comment by mxmxlwlw** [comment]
@gineshidalgo99  My exception was throw in the function of PoseExtractor::checkThread. Why the lib forbid to call it in another thread other than the one constructing it.

**Comment by gineshidalgo99** [comment]
For performance purposes we did not make those specific variables thread-safe, so you can only get the results on that thread (as the wrapper does).

You can wrap that functions and mutex it and copy the values you are interested continuously to a thread-safe variable if you want to.

**Comment by mxmxlwlw** [comment]
@gineshidalgo99 I don't use it from many threads. I just construct the class from one thread, while invoking the instanse from other thread. At one time, only one thread can access it.  My exception was throw in the function of PoseExtractor::checkThread. What is the function of the checkThread in your library? Is there any solution to do with my problem?

**Comment by gineshidalgo99** [comment]
OK, I think the easiest solution is to wrap PoseExtractor on e.g. PoseExtractorThreadSafe. This `PoseExtractorThreadSafe` should call getKeypoints and then clone the keypoints (`keypoints.clone()`) in the shared auxiliary variable that your other thread will ready/copy.

The point is that for efficiency, the keypoints are not copied unless you use `keypoints.clone()`.

**Comment by mxmxlwlw** [comment]
thank you for you replay!
