### ISSUE TITLE
Mac build error: Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by AddeNordh** [CMU-Perceptual-Computing-Lab/openpose#910]
### Issue Summary

When building with `make` and the 3-D Reconstruction module enabled the following error appears.
If i disable the 3-D Reconstruction module in CMake GUI everything works fine.

### Executed Command (if any)

```
make -j`nproc`
```

### Errors (if any)

https://pastebin.com/VKQYM94g

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/VKQYM94g

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** MacOS Mojave 10.14
    - **Release or Debug mode**? (by default: release): release
    - Compiler: XCode 10.1

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): yes
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: From homebrew, version 1.0.0
    - **CMake version**: From homebrew, 3.12.3
    - **OpenCV version**: From Homebrew, version 3.4.2

6. If **GPU mode** issue:
    - **CUDA version**:
    - **cuDNN version**:
    - **GPU model** (nvidia-smi in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**: Intel Core i5 2,3 GHz
    - Total **RAM memory** available: 8 GB

**Comment by gineshidalgo99** [comment]
Please try the new Mac version and make a new PR if it still fails. Hopefully this new version fixes all issues + adds OpenCL (GPU) support. Thanks!
