### ISSUE TITLE
How to accelerate the inference speed by using inference engine (ex:Intel Openvino, NVIDIA TensorRT) instead of using caffe?

### ISSUE THREAD

**Issue by jackgao0323** [CMU-Perceptual-Computing-Lab/openpose#914]
### Type of Issue
- Help wanted

### Your System Configuration
2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Windows 10
    - **Release or Debug mode** : Release
    - Compiler : VS2015 community

4. **Non-default settings**:
    - **3-D Reconstruction module added**? : no
    - Any other custom CMake configuration with respect to the default version? : no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : CMake 3.8.0
    - **OpenCV version**: OpenPose default 

9. If **Windows** system:
    - Portable demo or compiled library?

I want to accelerate the inference speed by using inference engine (ex:Intel Openvino, NVIDIA TensorRT) instead of using caffe.

I want to know how to get the input of the caffe model in your program and what should I do after I get the output?

Thank you very much.

**Comment by bushibushi** [comment]
Hello, I started a TensorRT PR last year but left it after the big PIMPL refactoring messed things up just when I got less time to work on this repo. [You can still see it](https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/285) in unmerged PRs, it can give you ideas on how to make it work for actual repo configuration. I only got to replace the main NN inference part, did a few computation changes for other ops but didn't replace some of the caffe components.

**Comment by jackgao0323** [comment]
@bushibushi Thank you very much. I'll take a look right now.

**Comment by bushibushi** [comment]
I'd suggest checking out early in the branch where i am certain things worked like  8023fb1
