### ISSUE TITLE
cannot find -lopencv_cudawarping [Openpose installation on NVIDIA Jetson TX2] 

### ISSUE THREAD

**Issue by abhinavtripathi95** [CMU-Perceptual-Computing-Lab/openpose#918]
Hi,

I am trying to install openpose on NVIDIA Jetson TX2 with the following configuration:

- Jetpack 3.3
- OpenCV 3.3.1
- CUDA 9
- CuDNN 7.1.5

I get this error while Compiling OpenPose

```
CXX examples/openpose/openpose.cpp
AR -o .build_release/lib/libopenpose.a
LD -o .build_release/lib/libopenpose.so.1.4.0
/usr/bin/ld: cannot find -lopencv_cudawarping
collect2: error: ld returned 1 exit status
Makefile:457: recipe for target '.build_release/lib/libopenpose.so.1.4.0'
failed
make: *** [.build_release/lib/libopenpose.so.1.4.0] Error 1
make: *** Waiting for unfinished jobs....

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been
successfully installed.
------------------------- -------------------------

```

**Comment by goldenpartner** [comment]
Hi abhinavtripathi95,

I'm running the same configuration as yours and have successfully installed openpose and get it running. There are some changes to be made to some files. I have initiated a pull request to those files. In the mean time, I put those files [here](https://github.com/goldenpartner/openpose_jetpack3.3_patch) to make them available. Instructions are included. Hope this can help with your issue.

Regards,
Leo

**Comment by aashishsoni05** [comment]
> Hi abhinavtripathi95,
> 
> I'm running the same configuration as yours and have successfully installed openpose and get it running. There are some changes to be made to some files. I have initiated a pull request to those files. In the mean time, I put those files [here](https://github.com/goldenpartner/openpose_jetpack3.3_patch) to make them available. Instructions are included. Hope this can help with your issue.
> 
> Regards,
> Leo

Hello,
I tried again with the new updated files and facing an error which I am unable to understand


------------------------- Compiling Caffe -------------------------
PROTOC src/caffe/proto/caffe.proto
NVCC src/caffe/layers/cudnn_deconv_layer.cu
NVCC src/caffe/layers/cudnn_lrn_layer.cu
NVCC src/caffe/layers/recurrent_layer.cu
make: /usr/local/cuda/bin/nvcc: Command not found
make: /usr/local/cuda/bin/nvcc: Command not found
Makefile:599: recipe for target '.build_release/cuda/src/caffe/layers/cudnn_lrn_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/cudnn_lrn_layer.o] Error 127
make: /usr/local/cuda/bin/nvcc: Command not found
make: *** Waiting for unfinished jobs....
Makefile:599: recipe for target '.build_release/cuda/src/caffe/layers/cudnn_deconv_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/cudnn_deconv_layer.o] Error 127
Makefile:599: recipe for target '.build_release/cuda/src/caffe/layers/recurrent_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/recurrent_layer.o] Error 127

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

**Comment by aashishsoni05** [comment]
and when I am running directly 'install_caffe_JetsonTX2_JetPack3.3.sh' I am facing a different error 


------------------------- Compiling Caffe -------------------------
make: *** No rule to make target 'all'.  Stop.

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

**Comment by aashishsoni05** [comment]
@goldenpartner Since u had mentioned that u are also working with same configuration (Jetson TX2 with JetPack 3.3), can u explain what is wrong from the above error message.

**Comment by aashishsoni05** [comment]
solved the above error. It was a GCC error. NVCC required the latest GCC and g++ version for the respective CUDA version. for CUDA 9.0, gcc6 and g++6 were required. after installing the required GCC versions, had to provide a symlink to the CUDA bin directory.
