### ISSUE TITLE
Install Openpose on Ubuntu 16.04 LTS Server

### ISSUE THREAD

**Issue by francesco-iorio** [CMU-Perceptual-Computing-Lab/openpose#924]
Hi, I'm trying to install Openpose on ubuntu Server 16.04 LTS, but with poor results. The virtual machine has these features: 8 CPU (4 sockets, 2 cores, Intel Xeon D-1520), 20 GB RAM, 500 Giga free space, no GPU. I followed all that is written in the installation guide via CLI, I tried new installations and configurations even recreating the virtual machine, but nothing. I report in principle the sequence of instructions I use for the installation. I state that at the moment I would use only the demo to process images

git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
openpose cd
git submodule init
git submodule update
sudo ubuntu/install_cudnn.sh -> with this command I get an error (webcam not found) when I run the demo
sudo bash ./ubuntu/install_cmake.sh
sudo apt-get install libopencv-dev
sudo mkdir build
cd build

option 1) sudo cmake -DGPU_MODE = CPU_ONLY ..
option 2) sudo cmake ..
- For both options, after executing the command to launch the demo, or freezes with "webcam not found" (if I install cudnn) or after a while it interrupts the process.

sudo make -j`nproc`
cd ..
./build/examples/openpose/openpose.bin -image_dir examples / media / --write_json output / --display 0 --render_pose 0

During the execution of the demo, the cpu oscillates between 50 and 99%, while the RAM is fixed at 95%. I tried to also lower the resolution through net_resolution and other things described in "Speed ​​Up, Memory Reduction, and Benchmark", but nothing…

Solutions to avoid interrupting the process?

**Comment by drkalvin** [comment]
Hello all,

Any news on the above? I am facing the same issue.
Thanks

**Comment by gineshidalgo99** [comment]
Highly reducing the `--net_resolution` and following the tips in the [Speed Up, Memory Reduction, and Benchmark](#speed-up-memory-reduction-and-benchmark) from doc/faq.md are the only way to reduce the RAM usage. Alternatively, you can disable `USE_MKL` in CMake, which will highly reduce the RAM usage of the Caffe version, but it might also reduce the program speed.
