### ISSUE TITLE
[OpenPos+Unity] OpenPosePlugin project error

### ISSUE THREAD

**Issue by JVinceW** [CMU-Perceptual-Computing-Lab/openpose#926]
### Posting rules
1. **Duplicated posts will not be answered**. Check the [FAQ](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md) section, other GitHub issues, and general documentation before posting. E.g., **low-speed, out-of-memory, output format, 0-people detected, installation issues, ...**).
2. **Fill** the **Your System Configuration section (all of it or it will not be answered!)** if you are facing an error or unexpected behavior. Feature requests or some other type of posts might not require it.
3. **No questions about training or 3rd party libraries**:
    - OpenPose only implements testing.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.
4. Set a **proper issue title**: add the Ubuntu/Windows keyword and be specific (e.g., do not call it: `Error`).
5. Only English comments.
Posts which do not follow these rules will be **ignored, closed, or reported** with no further clarification.

### Issue Summary
This is the very basic test to reach how OpenPose works with Unity. Follow the guideline, I built out the openpose.dll file and put it into Plugins folder of OpenPosePlugin project. (I also put the other DLLs inside the Release folder into the plugin folder of the unity project). Then I Start the Output2D scene to see what amazing thing Openpose can do inside Unity. And all I got is below error:

```
EntryPointNotFoundException: OP_ConfigurePose
OpenPose.OPWrapper.OPConfigurePose (Boolean body_disable, Nullable`1 net_resolution, Nullable`1 output_resolution, ScaleMode keypoint_scale_mode, Int32 num_gpu, Int32 num_gpu_start, Int32 scale_number, Single scale_gap, RenderMode pose_render_mode, PoseModel model_pose, Boolean disable_blending, Single alpha_pose, Single alpha_heatmap, Int32 part_to_show, System.String model_folder, HeatMapType heatmap_type, ScaleMode heatmap_scale_mode, Boolean part_candidates, Single render_threshold, Int32 number_people_max) (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:65)
OpenPose.OPWrapper.OPConfigureAllInDefault () (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:42)
OpenPose.Example.Output2DHandler.Start () (at Assets/OpenPose/Examples/Scripts/Output2DHandler.cs:27)
```

Please tell me what should I do to play this demo project

### Type of Issue
- wanted/Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: 
Github commit :  b2725c0

3. **General configuration**:
    - **Installation mode**: CMake(Windows)
    - **Operating system** Window 10
    - **Release or Debug mode**? Release
    - **Compiler**:  VS2017 community (Windows)

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: 3.13.0-rc3 (Windows)
    - **OpenCV version**:  OpenPose default (only Windows)

6. If **GPU mode** issue:
    - **CUDA version** : 
    - **cuDNN version**: 
    - **GPU model**: 

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Compiled library

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

**Comment by gineshidalgo99** [comment]
I am sorry, but those are Unity-specific and your-project-specific errors (I see functions that OP does not have). I can't help you debug your custom project (especially if it's Unity, for which I am not an expert at all).

But we are trying to release a Unity wrapper by the end of the year. Check the README to see if it has been released from time to time. Best
