### ISSUE TITLE
Improve Processing Time by Removing keypoints in pose skeleton

### ISSUE THREAD

**Issue by lausi119** [CMU-Perceptual-Computing-Lab/openpose#927]
### Issue Summary
Hello,
I am trying to use openpose to identify the chest area of an individual to then do further processing on a selected area. In the process many keypoints from the pose skeleton would be disregarded, so I'm wondering if it is possible to disable some of them? The idea behind it is to decrease processing time. It was mentioned before in #406 that the keypoints help openpose to detect other keypoints. What if I only removed keypoints that are at distance d >1 to the keypoints I plan on using (in my specific example feet and wrist keypoints)? Would that decrease the accuracy significantly and would the performance increase worthwhile? 

Thank you for any help!

### Type of Issue
- Help wanted
- Question

**Comment by gineshidalgo99** [comment]
There is no speed increase in disabling keypoints, 99% of the network is generic, only the last layer out of about 100 take into account the # of keypoints, so the speed up would be less than 1%.  Not worthy.
