### ISSUE TITLE
Openpose 1.4 Install Compile Error on Ubuntu 16.04 (/usr/bin/ld: cannot find -lopencv_contrib)

### ISSUE THREAD

**Issue by kaisark** [CMU-Perceptual-Computing-Lab/openpose#928]
### Issue Summary
Openpose 1.4 Install Compile Error on Ubuntu 16.04 using manual Make method (Note: Cmake install works properly and everything builds correctly). 
Error: 
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lopencv_contrib

### Errors (if any)
/usr/bin/ld: cannot find -lopencv_contrib

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: https://pastebin.com/qFg5KfsK

2. **OpenPose version**:  Github v1.4.0

3. **General configuration**:
    - **Installation mode**: manual Makefile installation (Ubuntu)
    - **Operating system**: Ubuntu 16.04.3 LTS
    - **Release or Debug mode**: Release
    - Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** cmake version 3.5.1
    - **OpenCV version**: compiled from source - v3.4.2
cmake -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -DINSTALL_PYTHON_EXAMPLES=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON -DENABLE_PRECOMPILED_HEADERS=OFF ..

OpenCV Install Output: https://pastebin.com/3Cyuuv0p

**GPU mode**:
    - **CUDA version** 8
    - **cuDNN version**: 7
    - **GPU model**:
ubuntu@ip-172-31-0-76:~$ nvidia-smi
Thu Nov 15 02:28:41 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:1E.0     Off |                    0 |
| N/A   41C    P0    55W / 149W |      0MiB / 11439MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------

**Comment by gineshidalgo99** [comment]
Makefile install is outdated and deprecated. Please, use the cmake installer, it will solve the opencv issue automatically. Otherwise, enable opencv 3 in the makefile config.
