### ISSUE TITLE
Fails due to symbol collision with OpenCV 4.0.0-rc

### ISSUE THREAD

**Issue by jimfcarroll** [CMU-Perceptual-Computing-Lab/openpose#929]
There is a series of #defines that clash with opencv variable names.

One example:
Openpose's macros.hpp line here: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/core/macros.hpp#L118

which clashes with the OpenCV include enum: https://github.com/opencv/opencv/blob/4.0.0-rc/modules/imgcodecs/include/opencv2/imgcodecs.hpp#L62

and results in code, after the preprocessor runs, that looks like this:
```
enum
{

    CV_LOAD_IMAGE_UNCHANGED =-1,

    
   cv::IMREAD_GRAYSCALE 
                            =0,

    
   cv::IMREAD_COLOR 
                            =1,

    
   cv::IMREAD_ANYDEPTH 
                            =2,

    CV_LOAD_IMAGE_ANYCOLOR =4,

    CV_LOAD_IMAGE_IGNORE_ORIENTATION =128
};
```

**Comment by gineshidalgo99** [comment]
Hi @jimfcarroll . Which OpenCV exact version are you using? This code does work with OpenCV 2.4.X, 3.X, and 4.0.0-beta on my machine. I haven't tried the new 4.0.0 pre-release. Thanks!

**Comment by jimfcarroll** [comment]
4.0.0-rc is the tag. It's the release candidate and the most recent tag.

**Comment by gineshidalgo99** [comment]
OK, I added the fix in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/core/macros.hpp#L118 to actually make it work with 4.0.0 alpha and beta versions. They seem to have added back those enums in 4.0.0-rc. I will try to make it work also with 4.0.0-rc and keep you posted...

**Comment by jimfcarroll** [comment]
It probably doesn't make too much sense spinning on it until the actual release but I just thought I'd try it since it's at a release candidate and I noticed you had 4.0.0 specific code so I figured I'd let you know.

**Comment by gineshidalgo99** [comment]
OK, fixed in the latest commit. Now all 4.0.0 versions works (alpha, beta, and rc). Let me know otherwise!

**Comment by jimfcarroll** [comment]
Great. I'll give it a shot.

**Comment by jimfcarroll** [comment]
Sorry for the series of messages. It looks like the `define` for `OPEN_CV_DNN_AVAILABLE` isn't being set correctly for my build.

**Comment by jimfcarroll** [comment]
I see what's happening. I think I can fix it for you. I'll submit a PR later.

**Comment by gineshidalgo99** [comment]
In my case, OpenCV DNN and Caffe are running both fine and together with no issues. Not sure why it crashes on your PC. However, I should have added OpenCV DNN module as optional (and disabled by default), so it doesn't crash in machines configured like yours.

Please, try the latest commit, OpenCV DNN is disabled by default (as it should have been done initially).

I also look forward to see your PR (if you still thing is useful). Thanks!

**Comment by jimfcarroll** [comment]
Well, I'm not a cmake guru and it looks like it's going to be difficult to determine automatically if OpenCV's DNN is part of the `find_package` for OpenCV. It looks like I'd have to scan the resulting library link line for `opencv_dnn` or the includes for the appropriate directory. This seem circuitous and brittle. So I was going to do what (I'm guessing) you did which was just make it explicit on the OpenPose build.

**Comment by jimfcarroll** [comment]
> For now, their module only works with CPU-only or Intel GPU (OpenCL) versions, so it is not worth at this point.

Heh. That's why I suggested I didn't think it was the right direction if you were going to replace Caffe. I doubt it will ever be otherwise since Intel now controls the OpenCV.
