### ISSUE TITLE
does openpose have output the bounding box of person  ( like x,y,w,h

### ISSUE THREAD

**Issue by Phoebe-star** [CMU-Perceptual-Computing-Lab/openpose#93]

**Comment by gineshidalgo99** [comment]
No the demo, but the library has a function for that: the `getKeypointsRectangle` in [include/openpose/utilities/keypoint.hpp](../blob/master/include/openpose/utilities/keypoint.hpp)

Use example:
```
                const auto thresholdRectangle = 0.1f;
                const auto numberKeypoints = keypoints.getSize(1);
                const auto areaKeypoints = numberKeypoints * keypoints.getSize(2);
                const auto personRectangle = getKeypointsRectangle(&keypoints[personIndex*areaKeypoints], numberKeypoints, thresholdRectangle);
```
(from [include/openpose/utilities/keypoint.hpp](../blob/master/src/openpose/utilities/keypoint.cpp) )

**Comment by gineshidalgo99** [comment]
Given there is no further answer, I'll assume it was solved.

**Comment by taraprasad73** [comment]
Is there a way to access getKeypointsRectangle() in python?

**Comment by soulslicer** [comment]
Currently this API is not exposed via Python. Is this a feature you would like to have?

@taraprasad73

**Comment by tsing90** [comment]
@soulslicer Hi, thanks for your answer. I'm not familiar with pybind11. when adding that line of code in `openpose_python.cpp`, I got an error. Do I have to compile openpose again to make it work? 
One more question, which parameters should I put into the `op.get_keypoints_rectangle` function? I saw in the .cpp example above, there should be three:` &keypoints[personIndex*areaKeypoints, numberKeypoints, thresholdRectangle` ; how can I find related information in python API? 
many thanks.

**Comment by gineshidalgo99** [comment]
Yes you would have to recompile it

**Comment by soulslicer** [comment]
Can you paste the error? When does it happen?

**Comment by tsing90** [comment]
@soulslicer I think it's an OS support issue. I am using Ubuntu 16.04, the error explained the reason:

Error:
Unity plugin only available on Windows.

Coming from:
- /home/kevin/git/openpose/src/openpose/utilities/errorAndLog.cpp:DebugInUnity():47

**Comment by gineshidalgo99** [comment]
You can enabled WITH_UNITY, which you do not wanna enable. Disable it from CMake

**Comment by tsing90** [comment]
@gineshidalgo99 Many thanks, perfectly solved !  Then I realized the rectangle is drawn by using the maximum and minimum of estimated keypoints (as shown in the image below) , which is not able to cover the whole body. Please bear with me if I have asked too much, is there a way to find accurate bounding box of whole body ?  thanks

![openpose 1 4 0 - tutorial python api_screenshot_14 02 2019](https://user-images.githubusercontent.com/20683656/52820091-f84ad600-30a2-11e9-81cd-98d56cffc2f7.png)

**Comment by gineshidalgo99** [comment]
No there is not, it is based on the body pose keypoints.

**Comment by Walid-Ahmed** [comment]
Was it working fine when you have more than one persons in the frame?

**Comment by aniquazereen** [comment]
> @gineshidalgo99 Many thanks, perfectly solved ! Then I realized the rectangle is drawn by using the maximum and minimum of estimated keypoints (as shown in the image below) , which is not able to cover the whole body. Please bear with me if I have asked too much, is there a way to find an accurate bounding box where the whole body can be fully covered? thanks
> 
> ![openpose 1 4 0 - tutorial python api_screenshot_14 02 2019](https://user-images.githubusercontent.com/20683656/52820091-f84ad600-30a2-11e9-81cd-98d56cffc2f7.png)

Hi

Could you please mention how did you run the program to get the rectangle?
