### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by lan2720** [CMU-Perceptual-Computing-Lab/openpose#931]
Operation System: ubuntu18.04
Openpose: master

I just git clone the master and use cmake gui to build.
When I run make -j`nproc`, everything is ok but the [line](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/python/openpose/_openpose.cpp#L191) raise a error:
```
openpose/python/openpose/_openpose.cpp:191:101: error: too many arguments to function ‘unsigned int op::getPoseMaxPeaks()’
```
So I just delete `poseModel` and leave `getPoseMaxPeaks()` no argument and re-make, then it's ok and running demo looks like correct.
Just report the bug.

**Comment by gineshidalgo99** [comment]
Fixed thanks to PR in #930. Please, try again. Thanks!
