### ISSUE TITLE
Compile error in another project using openpose, `openpose/face/faceExtractor.hpp: No such file or directory` in Ubuntu16.04

### ISSUE THREAD

**Issue by Jingorho** [CMU-Perceptual-Computing-Lab/openpose#932]
### Issue Summary
**What changed about `openpose/face/faceExtractor.hpp` and `openpose/hand/handExtractor.hpp`?**

I'm trying "[computer_vision library](https://github.com/srianant/computer_vision/tree/master/openpose)" to use emotions recognition. I followed [installation.md](https://github.com/srianant/computer_vision/blob/master/openpose/installation.md) and faced an error at the end of compiling it.

I think the wrong reference in "computer_vision library" causes this compiling error. As an error below says, openpose does not have `openpose/face/faceExtractor.hpp` and `openpose/hand/handExtractor.hpp` now, while "computer_vision library" uses these old file name. 
So what changed about these files? Can I edit "computer_vision library" reference corresponding to the change?
Openpose is successfully installed and I can run some examples in quickstart.

### Executed Command (if any)
At the end of compiling section of [installation.md](https://github.com/srianant/computer_vision/blob/master/openpose/installation.md) 
```
// From ~/openpose/ directory
make clean
make -j8
```

### Errors (if any)
```
In file included from src/openpose/user_code/pose_model.cpp:10:0:
./include/openpose/user_code/pose_model.hpp:37:43: fatal error: openpose/face/faceExtractor.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/user_code/pose_model.o' failed
make: *** [.build_release/src/openpose/user_code/pose_model.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./include/openpose/user_code/dlib_model.hpp:29:0,
             	from src/openpose/user_code/dlib_model.cpp:11:
./include/openpose/user_code/pose_model.hpp:37:43: fatal error: openpose/face/faceExtractor.hpp: No such file or directory
compilation terminated.
Makefile:478: recipe for target '.build_release/src/openpose/user_code/dlib_model.o' failed
make: *** [.build_release/src/openpose/user_code/dlib_model.o] Error 1
src/openpose/user_code/kerasify_model.cpp: In member function ‘virtual bool KerasLayerActivation::Apply(Tensor*, Tensor*)’:
src/openpose/user_code/kerasify_model.cpp:112:41: warning: ISO C++ forbids variable length array ‘data_exp’ [-Wvla]
     	float data_exp[out->data_.size()];
                                     	^
```

### Type of Issue
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: 

2. **OpenPose version**: Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake, sh script
    - **Operating system** : 
Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:    16.04
Codename:    xenial
    - **Release or Debug mode**? : by default, release
    - Compiler: 
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

4. **Non-default settings**:
    - **3-D Reconstruction module added**? :  by default, no
    - Any other custom CMake configuration with respect to the default version?: by default, no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: cmake version 3.5.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev`

**Comment by chokkarapu** [comment]
Hi
Have U resolved this issue?
if yes please send me that file, since we are facing same issue. 

Even I need "handExtractor.hpp"

Look forward for your prompt response.

Thanks,
Anil.

**Comment by MohammadKassemZein** [comment]
Anybody found a solution ?
