### ISSUE TITLE
Is the dataset with BigToe, SmallToe and Heel labels available for download?

### ISSUE THREAD

**Issue by rbruga** [CMU-Perceptual-Computing-Lab/openpose#935]
Is the dataset with BigToe, SmallToe and Heel labels available for download?
I am interested on learning more about the training dataset used to train BODY_25 
Thanks!

**Comment by gineshidalgo99** [comment]
Now it is:
https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/
