### ISSUE TITLE
Bad Allocation while using op::log()

### ISSUE THREAD

**Issue by AliAsgharManjotho** [CMU-Perceptual-Computing-Lab/openpose#936]
### Issue Summary
After completely building and importing the openpose and dependencies. I get BAD ALLOCATION error while I execute my code. Given Below:

### Executed Command (if any)

#include "stdafx.h"
#include <openpose\headers.hpp>
#include <openpose\flags.hpp>

int openPoseDemo()
{
	try
	{
		op::log("Starting OpenPose demo...", op::Priority::High);
		return 0;
	}
	catch (const std::exception e)
	{
		std::cout << e.what();
		return -1;
	}
}

int main(int argc, char *argv[])
{
	gflags::ParseCommandLineFlags(&argc, &argv, true);

	// Running openPoseDemo
	int ret = openPoseDemo();

	std::cout << "\nDONE";
	std::cin.get();
	return ret;
}

### Errors (if any)

bad allocation
DONE

![image](https://user-images.githubusercontent.com/20890689/48926143-1d95d100-ef06-11e8-873e-d4d99fcfc1db.png)

### Type of Issue
- Execution error

### Your System Configuration
1. [PasteBin]https://pastebin.com/8vU3aNPi

2. **OpenPose version**: OpenPose V1.4.0

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** : Windows 10 Pro 64-bit
    - **Release or Debug mode**? Debug
    - Compiler: VS2015 Enterprise Update 3

4. **Non-default settings**:
    - **3-D Reconstruction module added**? No
    - Any other custom CMake configuration with respect to the default version? (by default: no): No

5. **3rd-party software**:
    - **Caffe version**: from openpose
    - **CMake version** (`cmake --version` in Ubuntu): Cmake 3.13 windows 64-bit
    - **OpenCV version**: OpenPose default

6. If **GPU mode** issue:
    - **CUDA version**: CUDA 8.0.61.2
    - **cuDNN version**: cuDNN 5.1
    - **GPU model**: NVIDIA GeForce GTX 1080 Ti

9. If **Windows** system:
    - compiled library

**Comment by gineshidalgo99** [comment]
Please, try Release instead of Debug, and are you using the demo? Or are you porting OP to a different project?

**Comment by gineshidalgo99** [comment]
Close given no answer.

For future references, my best guesses are: 1) Debug does not work on some Windows machines, change to Release. 2) Your machine is going out of RAM/GPU memory (reduce net_resolution and disable face/hands to verify this).
