### ISSUE TITLE
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max

### ISSUE THREAD

**Issue by ziyueSeo** [CMU-Perceptual-Computing-Lab/openpose#939]
I have compile my own caffe and Protobuf, my cuda is 8.0, cudnn is 6.0.21, protobuf is 2.5.0. And after I run `make -j`nproc``, I run the `./build/examples/openpose/openpose.bin --video examples/media/video.avi`, i get this error:

### Errors
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F1125 21:36:33.818452 14233 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7fbfce9fedaa  (unknown)
    @     0x7fbfce9fece4  (unknown)
    @     0x7fbfce9fe6e6  (unknown)
    @     0x7fbfcea01687  (unknown)
    @     0x7fbfcdebce51  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fbfcdeff0d7  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fbfd4abdddc  op::NetCaffe::initializationOnThread()
    @     0x7fbfd4c3fe14  op::addCaffeNetOnThread()
    @     0x7fbfd4c4076b  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fbfd4c44710  op::PoseExtractorNet::initializationOnThread()
    @     0x7fbfd4c3c781  op::PoseExtractor::initializationOnThread()
    @     0x7fbfd4c37861  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fbfd4b519b1  op::SubThread<>::initializationOnThread()
    @     0x7fbfd4b55130  op::Thread<>::initializationOnThread()
    @     0x7fbfd4b55351  op::Thread<>::threadFunction()
    @     0x7fbfd3248c10  (unknown)
    @     0x7fbfcd9ae184  start_thread
    @     0x7fbfd2cd403d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

I don't know why it happen. Anyone help me? Thanks.

**Comment by AIHGF** [comment]
delete the 'clip layer' may be ok.

**Comment by ziyueSeo** [comment]
> delete the 'clip layer' may be ok.

Can you tell me how to delete the 'clip layer', please? thanks

**Comment by AIHGF** [comment]
> > delete the 'clip layer' may be ok.
> 
> Can you tell me how to delete the 'clip layer', please? thanks

remove 'caffe_root/include/layers/clip_layer.hpp' and 'caffe_root/src/caffe/layers/clip_layer.cpp'; 
then modify 'caffe_root/src/caffe/proto/caffe.proto`, delete the define of 'clip_layer' params.

**Comment by philipNoonan** [comment]
This is similar to #799

**Comment by givemeareasonLi** [comment]
I have see the smiliar issues, but it doesn't help. I have tried to use the caffe given by openpose and it failed. I also tried to use older caffe and the problem still happened.

**Comment by givemeareasonLi** [comment]
Solved the problem. I find that when I use cmake-gui to configure, it will change the caffe to the master instead of 9453eb0, so I git clone the 9453eb0 caffe and delete the remote git of it. Then it works. Just keep the caffe as 9453eb0.

**Comment by gineshidalgo99** [comment]
Hi, I did update the Caffe version last week. I believe this update should fix this issue (but you have to completely remove the current Caffe version inside your OpenPose folder and the build folder). Let me know if with the new version it still doesn't work.Thanks!

**Comment by ed-dev** [comment]
Hi,
I just installed openpose on ubuntu 16.04. Seemed to install ok using cmake and make but when I tried the example ` ./build/examples/openpose/openpose.bin --video examples/media/video.avi` I got the same error.
I then tried using the install script in the subdirectory (install_caffe_if_cuda8.sh) and re-ran the example - same error . 
I'm using cuda 8, cuDNN 7.1, openCV 4.0

```
./build/examples/openpose/openpose.bin --video examples/media/video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F1218 09:32:20.801959  2964 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7f32bbf2d5cd  google::LogMessage::Fail()
    @     0x7f32bbf2f433  google::LogMessage::SendToLog()
    @     0x7f32bbf2d15b  google::LogMessage::Flush()
    @     0x7f32bbf2fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f32bbaaa9a1  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f32bbad4eaa  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f32bd9925a7  op::NetCaffe::initializationOnThread()
    @     0x7f32bd9eff4e  op::addCaffeNetOnThread()
    @     0x7f32bd9f0a08  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f32bd9f5080  op::PoseExtractorNet::initializationOnThread()
    @     0x7f32bd9ec6c1  op::PoseExtractor::initializationOnThread()
    @     0x7f32bd9e7851  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f32bd9cf951  op::SubThread<>::initializationOnThread()
    @     0x7f32bd9d4bd8  op::Thread<>::initializationOnThread()
    @     0x7f32bd9d4ddd  op::Thread<>::threadFunction()
    @     0x7f32bd2efc80  (unknown)
    @     0x7f32bca416ba  start_thread
    @     0x7f32bcd5e41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)



```

**Comment by gineshidalgo99** [comment]
I am sorry, but I can't replicate this error. I am using latest OpenPose and this error does not occur on any of my machines (I have Ubuntu 14 and 16 machines), so I can't debug it.

**Comment by ed-dev** [comment]
Hi,
Removed the directory then cloned the respository. Compiled and ran the example. Got the error
```
./build/examples/openpose/openpose.bin --video examples/media/video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].clip_param.min, layer[0].clip_param.max
F1218 11:40:38.155475 12638 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/pose/body_25/pose_iter_584000.caffemodel
*** Check failure stack trace: ***
    @     0x7f7395e885cd  google::LogMessage::Fail()
    @     0x7f7395e8a433  google::LogMessage::SendToLog()
    @     0x7f7395e8815b  google::LogMessage::Flush()
    @     0x7f7395e8ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7395a059a1  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f7395a2feaa  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f73978ed5a7  op::NetCaffe::initializationOnThread()
    @     0x7f739794af4e  op::addCaffeNetOnThread()
    @     0x7f739794ba08  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f7397950080  op::PoseExtractorNet::initializationOnThread()
    @     0x7f73979476c1  op::PoseExtractor::initializationOnThread()
    @     0x7f7397942851  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f739792a951  op::SubThread<>::initializationOnThread()
    @     0x7f739792fbd8  op::Thread<>::initializationOnThread()
    @     0x7f739792fddd  op::Thread<>::threadFunction()
    @     0x7f739724ac80  (unknown)
    @     0x7f739699c6ba  start_thread
    @     0x7f7396cb941d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
```
Tried AIHGF's suggestion removing the clip layer by removing the .hpp , .cpp files, the clip_layer.cu file and the layerfactory.cpp file. The clip layer definitions in caffee.proto were also commented

```
 // optional ClipParameter clip_param = 148;
//message ClipParameter {
//  required float min = 1;
//  required float max = 2;
//}
```
ran `make` from the build directory then retried the example
```

./build/examples/openpose/openpose.bin --video examples/media/video.avi
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F1218 13:06:29.470595 23334 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Convolution (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Crop, Data, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, InfogainLoss, InnerProduct, Input, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Power, RNN, Reduction, Reshape, SPP, Scale, SigmoidCrossEntropyLoss, Silence, Slice, SoftmaxWithLoss, Split, Swish, Threshold, Tile)
*** Check failure stack trace: ***
    @     0x7fccefe115cd  google::LogMessage::Fail()
    @     0x7fccefe13433  google::LogMessage::SendToLog()
    @     0x7fccefe1115b  google::LogMessage::Flush()
    @     0x7fccefe13e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fccef9c4725  caffe::Net<>::Init()
    @     0x7fccef9c62c0  caffe::Net<>::Net()
    @     0x7fccf1876558  op::NetCaffe::initializationOnThread()
    @     0x7fccf18d3f4e  op::addCaffeNetOnThread()
    @     0x7fccf18d4a08  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fccf18d9080  op::PoseExtractorNet::initializationOnThread()
    @     0x7fccf18d06c1  op::PoseExtractor::initializationOnThread()
    @     0x7fccf18cb851  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fccf18b3951  op::SubThread<>::initializationOnThread()
    @     0x7fccf18b8bd8  op::Thread<>::initializationOnThread()
    @     0x7fccf18b8ddd  op::Thread<>::threadFunction()
    @     0x7fccf11d3c80  (unknown)
    @     0x7fccf09256ba  start_thread
    @     0x7fccf0c4241d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

```


`Also have version 2.6.1-1.3 of protobuf installed (if that helps?).

**Comment by gineshidalgo99** [comment]
I would say it's a protobuf-Caffe issue, we don't use that clip layer it mentions, so I'd say it is a Caffe-related issue. But again, I can't replicate the error so I can't know for sure how to solve it.

If somebody has a fix for the issue, feel free to do a PR.

**Comment by ed-dev** [comment]
@gineshidalgo99 .Thanks. Should I try an older version of protobuf? What are you using?

**Comment by ed-dev** [comment]
@AIHGF. No I removed it. I tried just commenting it but then other include errors emerged in relu_layer.hpp and slice_layer.hpp. I commented those out but then slice_layer produced an error (as it relies on a type in layer.hpp) ..and then I bailed.

**Comment by AIHGF** [comment]
> @AIHGF. No I removed it. I tried just commenting the include in layer_factory.cpp but then other include errors emerged in relu_layer.hpp and slice_layer.hpp. I commented those out but then slice_layer produced an error (as it relies on a type in layer.hpp) ..and then I bailed.

With the "https://github.com/BVLC/caffe" newest version, by removing "clip_layer" related info, I success.

**Comment by ed-dev** [comment]
@AIHGF. What exactly did you remove to succeed?Did you see the things I commented/removed. How close was that to what you did?

**Comment by AIHGF** [comment]
> @AIHGF. What exactly did you remove to succeed?Did you see the things I commented/removed. How close was that to what you did?Did you clone the repository into the 3rd party folder? I didn't have caffe installed so the version I have is the version the master pulled down.

The “layer[0].clip_param.min, layer[0].clip_param.max” error should be the caffe  layers problem, not the openpose repository. Just put the correct caffe into the 3rd party folder, without the clip_layer. Then the "clip_layer" error will disappear.

**Comment by dccho** [comment]
@gineshidalgo99 In CMakeLists.txt file on openpose root folder, there is git checkout command to change caffe from 9453eb0 to master. Why don't you remove that git command? After remove that, the problem is solved.

      if (${GPU_MODE} MATCHES "CUDA")
        **execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe)**
      elseif (${GPU_MODE} MATCHES "CPU_ONLY")
        if (USE_MKL)
          #execute_process(COMMAND git checkout intel WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe)
          execute_process(COMMAND git checkout b6712ce WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe)
          execute_process(COMMAND sh prepare_mkl.sh WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe/external/mkl
              OUTPUT_VARIABLE rv)
          set( MLIST ${rv} )
          separate_arguments(MLIST)
          list(GET MLIST 0 MKL_PATH)
          message(STATUS ${MKL_PATH})
          file(GLOB MKL_SO
            "${MKL_PATH}lib/*"
            )
          file(COPY ${MKL_SO} DESTINATION ${CMAKE_BINARY_DIR}/caffe)


          # New MLSL Lib
          #execute_process(COMMAND sh prepare_mlsl.sh WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe/external/mlsl
          #    OUTPUT_VARIABLE rv)
          #set( MLIST ${rv} )
          #separate_arguments(MLIST)
          #list(GET MLIST 0 MLSL_PATH)
          #message(STATUS ${MLSL_PATH})
          #file(GLOB MLSL_SO
          #  "${MLSL_PATH}/intel64/lib/*"
          #  )
          #file(COPY ${MLSL_SO} DESTINATION ${CMAKE_BINARY_DIR}/caffe)


          set(MKL_LIBS
            #"${CMAKE_BINARY_DIR}/caffe/libmlsl.so"
            "${CMAKE_BINARY_DIR}/caffe/libiomp5.so"
            "${CMAKE_BINARY_DIR}/caffe/libmklml_intel.so"
            "${CMAKE_BINARY_DIR}/caffe/lib/libmkldnn.so"
            )
        else (USE_MKL)
          execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe)
        endif (USE_MKL)
        set(CAFFE_CPU_ONLY ON)
        set(USE_CUDNN OFF)
      elseif (${GPU_MODE} MATCHES "OPENCL")
        execute_process(COMMAND git checkout opencl WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/3rdparty/caffe)
        set(USE_CUDNN OFF)
      endif (${GPU_MODE} MATCHES "CUDA")

**Comment by gineshidalgo99** [comment]
This error only happens in some Ubuntu machines. Following #787, compile your own Caffe with an older version of it. The hacky (quick but not recommended way) is to follow [#787#issuecomment-415476837](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/787#issuecomment-415476837), the elegant way (compatible with future OpenPose versions) is to build your own Caffe independently, following [doc/installation.md#custom-caffe-ubuntu-only](./installation.md#custom-caffe-ubuntu-only).

(This message will be added to the doc/faq.md doc)

**Comment by ed-dev** [comment]
Managed to get rid of the error. I cloned caffe (git clone https://github.com/BVLC/caffe.git) and built it. Built openpose with the appropriate caffe flags and I got the same error. 
Went back, removed the clip layer, rebuilt caffe and openpose, ran the example and the error was gone (ran out of memory but the original error had gone).
Thanks for the help.

**Comment by SilentLancer** [comment]
@ed-dev  I am trying to follow your step but just cant replicate it. Can you please provide step by step of your process? Thank you.

**Comment by ed-dev** [comment]
From memory remove clip_layer.hpp and clip_layer.cpp from  caffe_root/src/caffe/layers.  
In caffe_root/src/caffe/layers/clip_layer.cu comment out the include and  the two templates and the instantiate. Comment out the include in caffe_root/src/caffe/layer_factory.cpp.
Then in src/caffe/proto/caffe.proto comment out the ClipParameter message and the optional clipparameter. 
If there are any other errors just comment out the source line. 
Once you've compiled caffe follow the installation doc's recommendations. I used the command line  for cmake . openCV was installed globally, caffe was only local so for cmake I used
 -DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include \
  -DCaffe_LIBS=/home/"${USER}"/softwares/caffe/build/install/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

**Comment by ed-dev** [comment]
> @ed-dev I am trying to follow your steps but just cant replicate it. Can you please provide step by step of your process? Thank you.
> 
> (I am new to using Ubuntu)

From memory remove clip_layer.hpp and clip_layer.cpp from  caffe_root/src/caffe/layers.  
In caffe_root/src/caffe/layers/clip_layer.cu comment out the include and  the two templates and the instantiate. Comment out the include in caffe_root/src/caffe/layer_factory.cpp.
Then in src/caffe/proto/caffe.proto comment out the ClipParameter message and the optional clipparameter. 
If there are any other errors just comment out the source line. 
Once you've compiled caffe follow the installation doc's recommendations. I used the command line  for cmake . openCV was installed globally, caffe was only local so for cmake I used
 -DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include \
  -DCaffe_LIBS=/home/"${USER}"/softwares/caffe/build/install/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

**Comment by SilentLancer** [comment]
@ed-dev just to be sure can you specify which include in caffe_root/src/caffe/layer_factory.cpp to comment out? Thank you so much for helping me out and will probably be the last question if all goes well.

**Comment by SilentLancer** [comment]
> > @ed-dev I am trying to follow your steps but just cant replicate it. Can you please provide step by step of your process? Thank you.
> > (I am new to using Ubuntu)
> 
> From memory remove clip_layer.hpp and clip_layer.cpp from caffe_root/src/caffe/layers.
> In caffe_root/src/caffe/layers/clip_layer.cu comment out the include and the two templates and the instantiate. Comment out the include in caffe_root/src/caffe/layer_factory.cpp.
> Then in src/caffe/proto/caffe.proto comment out the ClipParameter message and the optional clipparameter.
> If there are any other errors just comment out the source line.
> Once you've compiled caffe follow the installation doc's recommendations. I used the command line for cmake . openCV was installed globally, caffe was only local so for cmake I used
> -DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include 
> -DCaffe_LIBS=/home/"${USER}"/softwares/caffe/build/install/lib/libcaffe.so -DBUILD_CAFFE=OFF ..

@ed-dev just to be sure can you specify which include in caffe_root/src/caffe/layer_factory.cpp to comment out? Thank you so much for helping me out and will probably be the last question if all goes well.

**Comment by ed-dev** [comment]
> > > @ed-dev I am trying to follow your steps but just cant replicate it. Can you please provide step by step of your process? Thank you.
> > > (I am new to using Ubuntu)
> > 
> > 
> > From memory remove clip_layer.hpp and clip_layer.cpp from caffe_root/src/caffe/layers.
> > In caffe_root/src/caffe/layers/clip_layer.cu comment out the include and the two templates and the instantiate. Comment out the include in caffe_root/src/caffe/layer_factory.cpp.
> > Then in src/caffe/proto/caffe.proto comment out the ClipParameter message and the optional clipparameter.
> > If there are any other errors just comment out the source line.
> > Once you've compiled caffe follow the installation doc's recommendations. I used the command line for cmake . openCV was installed globally, caffe was only local so for cmake I used
> > -DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include
> > -DCaffe_LIBS=/home/"${USER}"/softwares/caffe/build/install/lib/libcaffe.so -DBUILD_CAFFE=OFF ..
> 
> @ed-dev just to be sure can you specify which include in caffe_root/src/caffe/layer_factory.cpp to comment out? Thank you so much for helping me out and will probably be the last question if all goes well.

#include "caffe/layers/clip_layer.hpp"

**Comment by makino-ryota** [comment]
@ed-dev 
I would appreciate if you could help me as there are so many things that I don't know.
①I couldnt rebuilt caffe, and I need help. 
I built caffe like this.
$cd /home/"${USER}"/softwares/caffe/build/
$cmake ..
$make -j8
Then, I removed clip layer.
I tried to rebuild but an error occurred.
$cmake -DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include
CMake Error: The source directory "/home/"${USER}"" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Could you tell me how to make CMakeLists.txt?
or please tell me if I am doing something wrong.

②How can I connect caffe to OpenPose when I installed individual packages?
I cloned OpenPose(git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose)
 and caffe(git clone https://github.com/BVLC/caffe.git).
If I succeeded in rebuilt caffe, what should I do after that?

Forgive me if I make you feel bad by using incorrect words in English, i don't mean it at all.

**Comment by ed-dev** [comment]
> @ed-dev
> I would appreciate if you could help me as there are so many things that I don't know.
> ①I couldnt rebuilt caffe, and I need help.
> I built caffe like this.
> $cd /home/"${USER}"/softwares/caffe/build/
> $cmake ..
> $make -j8
> Then, I removed clip layer.
> I tried to rebuild but an error occurred.
> $cmake -DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include
> CMake Error: The source directory "/home/"${USER}"" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.
> 
> Could you tell me how to make CMakeLists.txt?
> or please tell me if I am doing something wrong.
> 
> ②How can I connect caffe to OpenPose when I installed individual packages?
> I cloned OpenPose(git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose)
> and caffe(git clone https://github.com/BVLC/caffe.git).
> If I succeeded in rebuilt caffe, what should I do after that?
> 
> Forgive me if I make you feel bad by using incorrect words in English, i don't mean it at all.

You need to change the include directory so it matches your directory structure. That directory doesn't exist, you don't have a 'softwares' directory so it's looked in your home directory.
(-DCaffe_INCLUDE_DIRS=/home/"${USER}"/softwares/caffe/build/install/include is just the example supplied in the documentation). 
Within your build directory there is the folder install/include. Point '-DCaffe_INCLUDE_DIRS=' at that directory. (You'll also need to change -DCaffe_LIBS)

**Comment by makino-ryota** [comment]
@ed-dev Thank you for replying.
Sorry, I made a mistake about directory.

And, I found different way to solve this problem.
I cloned OpenPose only.
And build it like this.(at OpenPose directory)

$ cd build
$ cmake ..
$ make -j`nproc`

Then, I removed clip layer as you said.(in the 3rd party)
Deleted build directory, and rebuild.

Then it worked fine!!
Thank you so much for helping me politely.

**Comment by gineshidalgo99** [comment]
I was finally able to replicate the error and fix it. Our latest https://github.com/CMU-Perceptual-Computing-Lab/caffe
 should handle it now. Simply remove the whole OpenPose folder and re-install it completely (so the new Caffe is updated, otherwise the OpenPose Caffe would not be updated).

**Comment by makino-ryota** [comment]
I installed it again and I checked it on my PC.
It worked without removing the clip layer.
Thank you very much.

**Comment by gineshidalgo99** [comment]
@makino-ryota great thanks for the feed-back!

**Comment by gineshidalgo99** [comment]
Update: The latest version of OpenPose does fix this issue (if using the OpenPose default Caffe, which was modified to solve this issue).

**Comment by bowrian** [comment]
I meet the same problems, then I delete the /openpose/3rdparty/caffe files and /openpose/build files , download the old caffe from the [https://github.com/CMU-Perceptual-Computing-Lab/caffe](url) , use the Cmake-GUI configure and generate, And build it like this. (at OpenPose directory)

$ cd build
$ make -j`nproc`
finally,it's works

**Comment by onyxiakylin** [comment]
yeah, I also meet the problem. And my solution is to replace the old caffe (1.0.0) with the caffe one: https://github.com/CMU-Perceptual-Computing-Lab/caffe , and don't need to modify other words or params, just change the lib.so files and remake it. It wiil succeed some time later.

**Comment by onyxiakylin** [comment]
BTW, the problem tend to arise when you're using the demo with the aim of testing whether you have install successfully. And just abandon the former caffe and install the CMU-caffe.

**Comment by AlexandrParkhomenko** [comment]
Use **"optional"** not **"required"** in caffe.proto

**Comment by rajhlinux** [comment]
Alright I was getting issues, I built caffe on my own. Got the same error as to OP.
I avoided building OpenPose's fork of Caffe because it makes us to install Atlas Math Library when OpenBlas is better.

Here is what I did which seems to eradicate the error:
-Comment/Remove the definition and params of "ClipParameter": located at /usr/home/user/caffe/src/caffe/proto/caffe.proto
(Note: do not edit "clip_gradients" parameters)

-Remove the files of "clip_layer.cpp" and "clip_layer.cu": located at: /usr/home/user/caffe/src/caffe/layers/

-Remove the file "clip_layer.hpp": located at: /usr/home/user/caffe/include/caffe/layers/

-Comment the line "#include "caffe/layers/clip_layer.hpp": located at: "src/caffe/layer_factory.cpp" file.

Build caffe, then build openpose, make sure to manually set the caffe include and lib files on OpenPose before building. 

This seems to work for me on FreeBSD 13.1 when I run the demo:
`$ cd /usr/home/user/openpose/
``$ /usr/home/user/openpose/build/examples/openpose/openpose.bin --camera 4`

**Comment by OrangeTsien** [comment]
> Alright I was getting issues, I built caffe on my own. Got the same error as to OP. I avoided building OpenPose's fork of Caffe because it makes us to install Atlas Math Library when OpenBlas is better.
> 
> Here is what I did which seems to eradicate the error:
> 
> -Comment/Remove the definition and params of "ClipParameter": located at /usr/home/user/caffe/src/caffe/proto/caffe.proto
> 
> Such as the following, comment everything:
> 
> ```
> // Message that stores parameters used by ClipLayer:
> message ClipParameter 
> {
>   required float min = 1;
>   required float max = 2;
> }
> ```
> 
> and also Comment the line: `optional ClipParameter clip_param = 148;` (Note: do not edit other "clip_gradients" and "LayerParameter" parameters in the caffe.proto file.)
> 
> -Remove the files of "clip_layer.cpp" and "clip_layer.cu": located at: /usr/home/user/caffe/src/caffe/layers/
> 
> -Remove the file "clip_layer.hpp": located at: /usr/home/user/caffe/include/caffe/layers/
> 
> -Comment the line "#include "caffe/layers/clip_layer.hpp": located at: "src/caffe/layer_factory.cpp" file.
> 
> Build caffe, then build openpose, make sure to manually set the caffe include and lib files on OpenPose before building.
> 
> This seems to work for me on FreeBSD 13.1 when I run the demo: `$ cd /usr/home/user/openpose/` `$ /usr/home/user/openpose/build/examples/openpose/openpose.bin --camera 4`
> 
> Finally able to view OpenPose implementation on a FreeBSD OS. After running the demo command, it takes literally like 5 mins to show a window dialog... not sure why it takes so long to load and 8 thread CPU maxes out. Will need to read the demo documentations...
> 
> ![screenshot](https://user-images.githubusercontent.com/61344181/193435773-d2c7ad82-08c2-41ae-a51f-89047c6b64ee.jpg)

Solved my problem thx!
