### ISSUE TITLE
The poseKeyPoints is 3D or 2D data?

### ISSUE THREAD

**Issue by segatecm** [CMU-Perceptual-Computing-Lab/openpose#94]
I read the example code, tutorial_pose, and seen the code like this
const auto poseKeyPoints = poseExtractorCaffe.getPoseKeyPoints();

so, please tell me the the poseKeyPoints is 3D or 2D data?
if i want to get the 3D of human pose, how can i do it?

Thanks for your replay!

**Comment by gineshidalgo99** [comment]
The output is 2D: (x,y,score).

Deeper explanation here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

There is no automatic 3D human pose so far: #38
