### ISSUE TITLE
compile error. ‘caffe::Blob’ is not a template type

### ISSUE THREAD

**Issue by GerrieWell** [CMU-Perceptual-Computing-Lab/openpose#942]
### Issue Summary
I use custom caffe to compile and get this error:.

### Executed Command (if any)
```shell
cmake .. -DPROTOBUF_INCLUDE_DIR=/cm/shared/apps/protobuf/3.2.1/include -DPROTOBUF_LIBRARY=/cm/shared/apps/protobuf/3.2.1/lib
VERBOSE=1 make
```

### Errors (if any)
```
/home/user012/jwei/openpose/include/openpose/core/macros.hpp:81:33: error: ‘caffe::Blob’ is not a template type
     template <typename T> class Blob;
                                 ^
In file included from /home/user012/jwei/openpose/src/openpose/face/faceExtractorCaffe.cpp:7:0:
/home/user012/jwei/openpose/include/openpose/net/maximumCaffe.hpp:19:58: error: ‘caffe::Blob’ is not a template
         virtual void LayerSetUp(const std::vector<caffe::Blob<T>*>& bottom, const std::vector<caffe::Blob<T>*>& top);
                                                          ^
/home/user012/jwei/openpose/include/openpose/net/maximumCaffe.hpp:19:102: error: ‘caffe::Blob’ is not a template
         virtual void LayerSetUp(const std::vector<caffe::Blob<T>*>& bottom, const std::vector<caffe::Blob<T>*>& top);
```
the VERBOSE make output : 
```
cd /home/user012/jwei/openpose/build_cli/src/openpose && /usr/bin/c++   -DUSE_CAFFE -DUSE_CUDA -Dopenpose_EXPORTS -O3 -fPIC -I/usr/include/opencv -I/home/user012/jwei/openpose/include -I/cm/shared/apps/caffe/0.17/include -I/home/user012/jwei/openpose/PUBLIC -I/cm/shared/apps/cuda80/toolkit/8.0.61/include -I/cm/shared/apps/cudnn/7.0/include    -std=c++11   -fopenmp -Wpedantic -Wall -Wextra  -o CMakeFiles/openpose.dir/face/faceExtractorCaffe.cpp.o -c /home/user012/jwei/openpose/src/openpose/face/faceExtractorCaffe.cpp
```

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code.

3. **General configuration**:
    - **Installation mode**: CMake(centos);
    - **Operating system** (`lsb_release -a` in Ubuntu):CentOS Linux release 7.4.1708
    - **Release or Debug mode**? (by default: release):
    - Compiler: gcc 5.5 

5. **3rd-party software**:
    - **Caffe version**: custom version 0.17
    - **CMake version** (`cmake --version` in Ubuntu):2.8
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
    - **cuDNN version**: 7.0
    - **GPU model** (`nvidia-smi` in Ubuntu):

**Comment by gineshidalgo99** [comment]
Sorry for the delay. I have updated OpenPose in a way that this error is no longer there. Thanks!
