### ISSUE TITLE
When will openpose be fully released for Ubuntu 18.04?

### ISSUE THREAD

**Issue by ylevental** [CMU-Perceptual-Computing-Lab/openpose#944]
### Issue Summary
Hello, I am just wondering when openpose will be fully released for Ubuntu 18.04.  I saw that there are still some big errors while installing.

### Type of Issue
- Question

**Comment by barcode** [comment]
This script (https://gist.github.com/barcode/9b325162002f0f7fec0812a7e68417be) can create a working setup for ubuntu 18 using this branch (https://github.com/barcode/openpose/tree/FindCuDNN_check_other_env_var).

**Comment by gineshidalgo99** [comment]
It has been released for Ubuntu 18 (a few weeks back). Please, carefully follow the doc for those.
