### ISSUE TITLE
cmake error file

### ISSUE THREAD

**Issue by mbmamin1996** [CMU-Perceptual-Computing-Lab/openpose#947]
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/hand16/openpose-master/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_bb4cd/fast"
/usr/bin/make -f CMakeFiles/cmTC_bb4cd.dir/build.make CMakeFiles/cmTC_bb4cd.dir/build
make[1]: Entering directory '/home/hand16/openpose-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_bb4cd.dir/CheckSymbolExists.c.o
/usr/bin/cc    -fPIC    -o CMakeFiles/cmTC_bb4cd.dir/CheckSymbolExists.c.o   -c /home/hand16/openpose-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_bb4cd
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bb4cd.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC     CMakeFiles/cmTC_bb4cd.dir/CheckSymbolExists.c.o  -o cmTC_bb4cd -rdynamic 
CMakeFiles/cmTC_bb4cd.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_bb4cd.dir/build.make:97: recipe for target 'cmTC_bb4cd' failed
make[1]: *** [cmTC_bb4cd] Error 1
make[1]: Leaving directory '/home/hand16/openpose-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_bb4cd/fast' failed
make: *** [cmTC_bb4cd/fast] Error 2

File /home/hand16/openpose-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/hand16/openpose-master/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_0f676/fast"
/usr/bin/make -f CMakeFiles/cmTC_0f676.dir/build.make CMakeFiles/cmTC_0f676.dir/build
make[1]: Entering directory '/home/hand16/openpose-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0f676.dir/CheckFunctionExists.c.o
/usr/bin/cc    -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_0f676.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_0f676
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0f676.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_0f676.dir/CheckFunctionExists.c.o  -o cmTC_0f676 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_0f676.dir/build.make:97: recipe for target 'cmTC_0f676' failed
make[1]: *** [cmTC_0f676] Error 1
make[1]: Leaving directory '/home/hand16/openpose-master/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_0f676/fast' failed
make: *** [cmTC_0f676/fast] Error 2

thanks for helping

**Comment by rmaria** [comment]
I have the same problem. Ubuntu 16.04, no GPU, I used Visual CMake.
