### ISSUE TITLE
Add a tracker of the pose data for multi-person tracking?

### ISSUE THREAD

**Issue by hitsx** [CMU-Perceptual-Computing-Lab/openpose#95]
### Issue summary
Is there any plan to add a tracker of pose data for multi-person tracking?
My understanding of this feature can be done using a kd-tree to track the latest model of each person using the pose 18 point data, and then we can get classify each person when we get a new pose detection.
If there is no plan of such feature, I will do it and when I finished, I can contribute the code into the example directory.

### Executed command (if any)
N/A

### OpenPose output (if any)
N/A

### Type of issue
- Enhancement / offering possible extensions

### Your system configuration
N/A

**Comment by gineshidalgo99** [comment]
#29

**Comment by Gautam1121** [comment]
Hi,

I have implemented tracking in openpose (python script)
You can contact me at gautam.patel@einfochips.com for details.
:)

**Comment by Gautam1121** [comment]
Hello,

I have implemented PersonIdExtractor and PersonTracker in python, which is tested fine.
there is a small issue of PersonID getting swiped when they cross or overlap each other.

connect me at gautam.patel@einfochips.com for details.

**Comment by jeffzout** [comment]
> Hello,
> 
> I have implemented PersonIdExtractor and PersonTracker in python, which is tested fine.
> there is a small issue of PersonID getting swiped when they cross or overlap each other.
> 
> connect me at [gautam.patel@einfochips.com](mailto:gautam.patel@einfochips.com) for details.

I am trying to understand how it is designed, but lack of documentation. Would you please give more detail or some useful instruction to help find the documentation.  Thanks!

**Comment by jeffzout** [comment]
I found that problem too. I am trying to understand how it works and to resolve it, but lack of documentation. Is there anyone who can give more information about it?  Thanks~

**Comment by gineshidalgo99** [comment]
You can now use the new Python OpenPose version, it allows it.

**Comment by gineshidalgo99** [comment]
You can now use the new Python OpenPose version, it allows it.

**Comment by MagnusAnders** [comment]
@gineshidalgo99 how can we use it ? A want to apply openpose with a tracker... What should I do to make use of this utility in the code ? Thanks

**Comment by gineshidalgo99** [comment]
--tracking or something like that was the flag, please see the --help or doc about it!
