### ISSUE TITLE
op:Array changes between alpha and 1.4 lost data ubuntu 18

### ISSUE THREAD

**Issue by functionalprototype** [CMU-Perceptual-Computing-Lab/openpose#951]
### Issue Summary
We have some code that worked just fine under the March/1.0 release that is not working in the OP 1.4 tag.  I haven't touched cv::Mat in a decade and this is my first time working with OP source so maybe I'm just being clueless or missing the obvious.

We wrote a wrapper CLI using the examples docs, it worked well enough, and not I'm trying to upgrade to the 1.4 tag.   We take data from an op:Array using op::Array::getConstCvMat() and push that mat to a different data structure.  Before, we got the right data in a 3d mat but in 1.4 we get only the first column of the mat.

(There's also an opArray type error() later in this code, I'll file a new ticket on that if fixing this doesn't make the error go away.)

```
// we're in a method class 
void class::getPoseKeypoints() {}
// in class Person.hpp there is the method variable: 
op::Array<float> mPoseKeypoints;
// the variable "person" is a from a map element:
 map<long long int, std::shared_ptr<Person>> mSortedPeople;
// and we're in a  loop 
for (const auto & person : mSortedPeople) {

// here's where the error happens:
auto pose = person.second->mPoseKeypoints;
Logger::log("found getPoseKeypoints: " + pose.toString(), Logger::Priority::High);
cv::Mat m = pose.getConstCvMat();
cv::MatIterator_<float> it;
Logger::log("cv::Mat getPoseKeypoints: ", Logger::Priority::High);
for (it = m.begin<float>(); it != m.end<float>();  ++it) {
    Logger::log(" " + std::to_string(*it), Logger::Priority::High);
}
```

### OpenPose Output (if any)

This is the correct output, testing with me in front of a webcam:

found getPoseKeypoints: Array<T>::toString():
760.703979 480.538696 0.407970
735.207153 580.429993 0.307429
572.586914 572.600464 0.249950
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
903.669922 588.283630 0.206988
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
723.384521 445.115326 0.419303
792.030396 443.185089 0.433553
660.716736 429.584076 0.340023
835.113831 431.492218 0.327707

cv::Mat getPoseKeypoints:
 760.703979
 480.538696
 0.407970
 735.207153
 580.429993
 0.307429
 572.586914
 572.600464
 0.249950
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 903.669922
 588.283630
 0.206988
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 723.384521
 445.115326
 0.419303
 792.030396
 443.185089
 0.433553
 660.716736
 429.584076
 0.340023
 835.113831
 431.492218
 0.327707

### Errors (if any)

When I run that same code with OP 1.4, I only get the first column of data from the opArray:

found getPoseKeypoints: Array<T>::toString():
713.628113 451.091614 0.850471 
731.232971 562.770752 0.604149 
572.526123 558.870178 0.496133 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
886.041687 566.675232 0.484168 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
680.332947 413.837219 0.922774 
750.875244 409.929779 0.815524 
637.199402 413.807007 0.595202 
797.891479 400.178833 0.709776 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 
0.000000 0.000000 0.000000 

cv::Mat getPoseKeypoints: 
 713.628113
 731.232971
 572.526123
 0.000000
 0.000000
 886.041687
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 680.332947
 750.875244
 637.199402
 797.891479
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000

### Type of Issue
- Execution error
- Help wanted

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

commit 123cb64750c81e9c396fdd2d502a92a319d848a0 (tag: v1.4.0)
Author: gineshidalgo99 <gineshidalgo99@gmail.com>
Date:   Sat Sep 1 22:41:56 2018 -0400

    OpenPose v1.4.0

3. **General configuration**:
    - **Installation mode**: CMake (Ubuntu);
    - **Operating system** (`lsb_release -a` in Ubuntu):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

    - **Release or Debug mode**? (by default: release):
release

    - Compiler 
 gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010

4. **Non-default settings**:
no

5. **3rd-party software**:
    - **Caffe version**: default
    - **CMake version** (`cmake --version` in Ubuntu): cmake version 3.11.0-rc4
    - **OpenCV version**: built from source
commit 6ffc48769ac60d53c4bd1913eac15117c9b1c9f7 (HEAD, tag: 3.4.1)
Author: Alexander Alekhin <alexander.alekhin@intel.com>
Date:   Mon Feb 19 17:30:06 2018 +0300

    OpenCV version++
    
    OpenCV 3.4.1

6. If **GPU mode** issue:
    N/A

7. If **CPU-only mode** issue:
N/A

8. If **Python** API:
N/A

9. If **Windows** system:
N/A

10. If **speed performance** issue:
   N/A

**Comment by gineshidalgo99** [comment]
Not an expert in OpenCV iterators.

From your pose.getConstCvMat(), could you let me know the following results:
std::cout << pose.getConstCvMat() << std::endl;
std::cout << pose.getConstCvMat().cols << std::endl;
std::cout << pose.getConstCvMat().rows << std::endl;
std::cout << pose.getConstCvMat().size() << std::endl;

Thanks

**Comment by functionalprototype** [comment]
using this code:

 ```
cv::Mat m = pose.getConstCvMat();
 std::cout << "debug request 1.4.0" << std::endl;
 std::cout << "getConstCvMat(): " << pose.getConstCvMat() << std::endl;
 std::cout << "getConstCvMat().cols: " << pose.getConstCvMat().cols << std::endl;
 std::cout << "getConstCvMat().rows: " << pose.getConstCvMat().rows << std::endl;
 std::cout << "getConstCvMat.().size(): " << pose.getConstCvMat().size() << std::endl;
 cv::MatIterator_<float> it;
 Logger::log("cv::Mat iterator: ", Logger::Priority::High);
 for (it = m.begin<float>(); it != m.end<float>();  ++it) {
	Logger::log(" " + std::to_string(*it), Logger::Priority::High);
}
```

debug request 1.4.0
getConstCvMat(): [721.45618, 431.47168, 0.84730405, 717.52075, 539.22742, 0.67454034, 572.53522, 541.2077, 0.54453725, 476.62131, 684.29254, 0.27927303, 0, 0, 0, 868.43323, 535.35022, 0.53460795, 983.99976, 688.1629, 0.30101487, 1011.4202, 715.61115, 0.059106912, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 688.18939, 396.22812, 0.85349727, 756.70325, 396.20911, 0.86291099, 641.15375, 402.14227, 0.82667738, 793.96851, 398.10294, 0.83369571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
getConstCvMat().cols: 25
getConstCvMat().rows: 1
getConstCvMat.().size(): [25 x 1]
cv::Mat iterator: 
 721.456177
 717.520752
 572.535217
 476.621307
 0.000000
 868.433228
 983.999756
 1011.420166
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 688.189392
 756.703247
 641.153748
 793.968506
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000
 0.000000

**Comment by gineshidalgo99** [comment]
OK I get it. getConstCvMat().channels should give you 3 then (If the getConstCvMat is a HxWx3 matrix, it turns it into a RGB image, but given that we have 3 channels (x,y,score), it is doing the same with the 2D keypoints.

I am not an expert in OpenCV, but you have to consider the number of channels too. Feel free to post the final iterator so other people can also use it.

**Comment by functionalprototype** [comment]
Thanks, but I don't think I understand what is happening.  If the cv:Mat has 75 values, it should be 25 x 3 and not 25 x 1, correct?  When you say "turns it into a RGB image", is that being done by op::Array().  It would be 25 x (3 floats), but I'm only seeing 25 x 1 float. 

We're getting the x/y/score straight from Datum::Array<float> poseKeypoints.  The examples code looks at a specific point using: a traditional array reference:
poseKeypoints[{person, bodyPart, xyscore}]
should we use this instead of the Array() interface?

Here's a simple example that worked in 1.0.0 but now crashes when we array.setFrom().  (I obfuscated our project name with "fubar".)
 
```
source:

cv::Mat people(std::vector<int>{0, mNumberBodyParts, 3}, CV_32FC1);

for (const auto & person : mSortedPeople) {
  auto pose = person.second->mPoseKeypoints;
  people.push_back(pose.getConstCvMat());
}				}

op::Array<float> array;
array.setFrom(people);
return(array)

and when I execute:

Error:
Array<T>: T type and cvMat type are different.

Coming from:
- /home/jet/ci-1.4/3rdparty/openpose/src/openpose/core/array.cpp:setFrom():246
- /home/jet/ci-1.4/3rdparty/openpose/src/openpose/core/array.cpp:setFrom():256
- /home/jet/ci-1.4/src/fubar/tracker/tracker.cpp:getPoseKeypoints():92
- /home/jet/ci-1.4/include/fubar/tracker/wTracker.hpp:work():97
- /home/jet/ci-1.4/build/openpose/include/openpose/thread/subThread.hpp:workTWorkers():135
- /home/jet/ci-1.4/build/openpose/include/openpose/thread/subThreadQueueInOut.hpp:work():96
- /home/jet/ci-1.4/build/openpose/include/openpose/thread/thread.hpp:threadFunction():204
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
Array<T>: T type and cvMat type are different.



```

**Comment by functionalprototype** [comment]
It looks like setFrom() is stale code, it's not used anywhere in OP 1.4.  Is it better if I just make my own Array subclass to work around these issues?

**Comment by gineshidalgo99** [comment]
It is not stale, it is rather fixed code that I expect not to need to change in the future after that change from version 1.0.0.

What I meant is that you will have to read the cv::Mat as an RGB image (where R would be x, G y, and B scale), rather than as a grey image, so it will be 25 x 1 x 3channels

**Comment by functionalprototype** [comment]
Ok, I think I tried that in an earlier attempt to sort this out, I declared people as a 32 float x 3 cv::Mat

cv::Mat people(std::vector<int>{0, mNumberBodyParts, 3}, CV_32FC3);

but setfrom() still crashes with a type error -- I added the found types to the error message:

Array<T>: T type 5 and cvMat type 21 are different.

**Comment by functionalprototype** [comment]
More research -- it looks like poseKeypoints are set to CV_32FC3 before wPoseExtractor::work

```
  tDatum.poseKeypoints = spPoseExtractor->getPoseKeypoints().clone();
  log("WPoseExtractor poseKeypoints type " +  std::to_string(tDatum.poseKeypoints.getConstCvMat().type()), Priority::High);
```
results in

WPoseExtractor poseKeypoints type 21

What's the reason for a list of keypoints being stored as an RGB image type instead of CV_32FC1, as they were in alpha?  When I try to use Array::setFrom() on a list of points stored in CV_32FC3 forma, setFrom() errors out.

**Comment by gineshidalgo99** [comment]
It is saved in CV_32FC3 format because that is convenient when Array stores images (so those images can be standard cv::Mat that can use normal functions such as cv::imshow). Otherwise, RGB images saved as Array would be stored as multi-dimensional cv::Mat instead of RGB cv::Mat, difficulting it's post-processing.

**Comment by gineshidalgo99** [comment]
Closing it given missing answer.

For any person facing this issue, the solution is to read the image as an RGB image (with 3 channels, which instead of being Red Green and Blue are x,y, and score).
