### ISSUE TITLE
C++ Tutorial 7_synchronous_custom_input.bin Seg Faults due to producer nullptr dereference

### ISSUE THREAD

**Issue by djns99** [CMU-Perceptual-Computing-Lab/openpose#954]
### Issue Summary

I just pulled the latest version of openpose and I started getting a seg fault on the C++ API tutorial 7. I have also implemented my own version which also seg faults. I did a bit of debugging myself and it appears there is no check for null around  `const auto numberViews = (intRound(producerSharedPtr->get(ProducerProperty::NumberViews)));` at line 711 of wrapperAuxilary.cpp. I am running the default example so I presume this is a legal use case.

This only started happening since I pulled 5295f2f38609a6ff24739b37cf348b9c9324faef. Previously I had not pulled since 26 Nov 2018, and this worked for me.

### Executed Command (if any)
`./build/examples/tutorial_api_cpp/7* --logging_level 0 --disable_multi_thread`

### OpenPose Output (if any)
```
Starting OpenPose demo...
/home/dast/uni/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():11
/home/dast/uni/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():60
/home/dast/uni/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToHeatMapScaleMode():89
Configuring OpenPose...
Starting thread(s)...
/home/dast/uni/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():96
/home/dast/uni/openpose/src/openpose/producer/producer.cpp:createProducer():454
/home/dast/uni/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():21
/home/dast/uni/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():174
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
/home/dast/uni/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():299
Segmentation fault (core dumped)
```

### Type of Issue
- Execution error

### Your System Configuration
2. **OpenPose version**:  Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation (Ubuntu); 
    - **Operating system**: Ubuntu 16.04.5 LTS
    - **Release or Debug mode**: Tested both
    - **Compiler**: `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609`

4. **Non-default settings**:
    - **3-D Reconstruction module added**?: Tested both

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** (`cmake --version` in Ubuntu): 3.11.4
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu);

6. If **GPU mode** issue:
    - **CUDA version**: cuda-8.0
    - **cuDNN version**: cuDNN 7.4
    - **GPU model**: GTX 1050Ti

**Comment by djns99** [comment]
Checking out commit 72d1992a64b859dc83c35274d139edeecc115370 works. Seems bug was introduced in `Undistort works for all producer types`

**Comment by Glorialiujie** [comment]
hi,I think I met the same problem .I tried to debug in Clion,it shows that "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)" and pointed to #46 " spPoseExtractor->initializationOnThread();" in the WPoseExtractor.hpp.
Have you solve it?

**Comment by gineshidalgo99** [comment]
Fixed. Please, post in #998 if there is any further issue. Thanks.
