### ISSUE TITLE
Build Issue: Unable to pass BOOST_LIBRARYDIR or BOOST_ROOT to Cmake. Boost is not found by the make script

### ISSUE THREAD

**Issue by 00SteinsGate00** [CMU-Perceptual-Computing-Lab/openpose#957]
### Issue Summary

Hey there,

I'm trying to compile open pose on a Linux Server running OpenSuse 15 and I don't have root privileges to install anything. So I downloaded Boost and compiled it myself. Now I'm having trouble telling  Cmake/Make where to find it.

CMake runs without errors but as soon as I run `make` I get an error that Boost is not found (see the pastebin in the next section) and I should set the path by using BOOST_LIBRARYDIR or BOOST_ROOT. However when I pass those options to Cmake it says, that the project doesn't use these flags and nothing changes, the error remains the same.

When I list all the possible Cmake Flags they don't show up either so I find it very confusing that they are actually suggested. On my local machine running MacOS where I could install Boost to default directories this was not an issue, all the boost headers and libs were found.

### Executed Command (if any)

`cmake -D BOOST_LIBRARYDIR=/b_test/holub/CLibs/boost_1_68_0/lib -D BOOST_INCLUDEDIR=/b_test/holub/CLibs/boost_1_68_0/boost .`

### Type of Issue

- Compilation/installation error

### Your System Configuration
1. **Whole console output** 

`cat /etc/os-release`: [pastebin](https://pastebin.com/S9B6Frbw)

CMake Output: [cmake Pastebin](https://pastebin.com/i1Ae88Rk)
Make Output: [Make Pastebin](https://pastebin.com/t7eb75W9)

2. **OpenPose version**: 1.4.0

3. **General configuration**:
    - **Installation mode**: CMake, Linux Server I don't have root access on

4. **Non-default settings**:

5. **3rd-party software**:
    - **CMake version**:  3.10.2

**Comment by 00SteinsGate00** [comment]
Nevermind. Setting it as en environment variable using export did the job. Next step is figuring out how to get ATLAS to compile. Sorry for the unnecessary issue.

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back for other users.
