### ISSUE TITLE
3D Reconstruction error

### ISSUE THREAD

**Issue by gurbela** [CMU-Perceptual-Computing-Lab/openpose#959]
I Running 3-D  reconstruction demo, I have two Flir camera, Calibration done. 
When I do run returns error: 

> Unusual high re-projection error (averaged over #keypoints) of value **-nan(ind)** pixels, while the average for a good OpenPose detection from 4 cameras is about 2-3 pixels. It might be simply a wrong OpenPose detection. If this message appears very frequently, your calibration parameters might be wrong.

Can not calculate the value of pixels, What is the reason for this? Has a problem of calibration?

**Comment by Edison-xiao927** [comment]
Have you solved the problem？
