### ISSUE TITLE
Does it work on Mac OS?

### ISSUE THREAD

**Issue by totovr** [CMU-Perceptual-Computing-Lab/openpose#96]
### Posting rules
1. **No duplicated** posts.
2. **No** posts about **questions already answered in** the **documentation** (e.g. **no more low-speed nor out-of-memory questions**).
3. **Add** the **system configuration (all of it!), command and output** if you have some kind of error or performance question.
4. Set a **proper issue title**: add the Ubuntu/Windows word and be specific (e.g. do not simple call it: `Compile error`).
5. Only English comments.
Issues/comments that do not follow this will be **ignored or removed** with no further clarification.

### Type of issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
**cuDNN version**:
**GPU model** (`nvidia-smi`):
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment]
I know some people made it work there. But I have no idea how, we do not have any MAC with an NVIDIA graphics to try it. Sorry.

**Comment by nicky918** [comment]
how can i do with my Mac OS if my gpu is **AMD Radeon R9 M370X**, though caffe support cpu only.

> In file included from src/openpose/core/netCaffe.cpp:3:
> ./include/openpose/utilities/cuda.hpp:5:10: fatal error: 'cuda.h' file not found
> #include <cuda.h>
>          ^
> 1 error generated.
> make: *** [.build_release/src/openpose/core/netCaffe.o] Error 1

**Comment by totovr** [comment]
In my case I could not use it, it present some errors at the end of the installation, but I didnt have problems with the cudas

**Comment by gineshidalgo99** [comment]
Some was able to use MAC OS: #168

(Assuming you have a Nvidia graphic card)
