### ISSUE TITLE
Ubuntu python API keypoints question

### ISSUE THREAD

**Issue by ambersun1234** [CMU-Perceptual-Computing-Lab/openpose#960]
### Issue Summary
I'm trying to use the keypoints( return value from `openpose.forward()` ) to draw keypoints on a new image with the same size as the input image. I notice that some of the keypoints will result out of bounds compare to the original image size.

For example , i took one of the image you provided , called `COCO_val2014_000000000395.jpg` with `height = 580 , width = 640` , there is one keypoint`[5.6103979e+02 5.8506830e+02 2.3352341e-01]` , after using python `math.floor` function , the result will be `x = 561 , y = 585`. Obviously , with the `height = 580` , the result `y = 585` can't draw on the image because of out of bound.
I tried to swap the x , y and try to draw again , due to the same reason , it failed.

Not sure if I used the API correctly , please help me
The source code is as follow

```python
from openpose import *
import numpy as np
import cv2

params = dict()
params[ "logging_level" ] = 3
params[ "output_resolution" ] = "-1x-1"
params[ "net_resolution" ] = "-1x368"
params[ "model_pose" ] = "BODY_25"
params[ "alpha_pose" ] = 0.6
params[ "scale_gap" ] = 0.3
params[ "scale_number" ] = 1
params[ "render_threshold" ] = 0.05
params[ "num_gpu_start" ] = 0
params[ "disable_blending" ] = False
params[ "default_model_folder" ] = mypath + "/models/"
openpose = OpenPose( params )

# suppose mypath points directly to openpose directory
img = cv2.imread( mypath + "/examples/media/COCO_val2014_000000000395.jpg" )
height , width , channel = img.shape
keypoints , output_image = openpose.forward( img , True )

# new image with same image height and width 
testImg = np.ones( (height , width , 3) , np.uint8 )

# with the keypoints of all the people on that image
for people in keypoints :
    colorCount = 0
    for points in people :
        count = 0
        print( points )
        for item in points :
            if count == 0 :
                x = math.floor( item )
            elif count == 1 :
                y = math.floor( item )
            else :
                xyConfidence = item
            count += 1
        # end keypoints item
        print( "x = {} , y = {} , xyc = {}".format( x , y , xyConfidence ) )
        # if x , y confidence equals zero , then don't draw color
        if xyConfidence == 0 :
            colorCount += 1
            continue
        # set color ordered by BGR
        testImg[ y , x ] = (color[ colorCount ][ 0 ] , color[ colorCount ][ 1 ] , color[ colorCount ][ 2 ])
        colorCount += 1
```

### Executed Command (if any)
none

### OpenPose Output (if any)
none

### Errors (if any)
IndexError: index 585 is out of bounds for axis 0 with size 580

### Type of Issue
Help wanted
Question

### Your System Configuration
2. **OpenPose version**: 5c2714d6

3. **General configuration**:
    - **Installation mode**: CMake cli
    - **Operating system**: 
      ```
      No LSB modules are available.
      Distributor ID:	Ubuntu
      Description:	Ubuntu 16.04.5 LTS
      Release:	16.04
      Codename:	xenial
      ```
    - **Release or Debug mode**? (by default: release): release
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): no
    - Any other custom CMake configuration with respect to the default version? (by default: no): no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...? 9453eb00( https://github.com/CMU-Perceptual-Computing-Lab/caffe )
    - **CMake version** (`cmake --version` in Ubuntu): cmake version 3.5.1
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...? build from source , version 3.4.3

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): CUDA Version 9.0.176
    - **cuDNN version**: cudnn version 7
    - **GPU model** (`nvidia-smi` in Ubuntu): GeForce GTX 1070

8. If **Python** API:
    - **Python version**: 3.5.2
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu): 1.15.3

**Comment by gineshidalgo99** [comment]
This question is no longer valid given that the Python API has been completely changed to a faster, cleaner, and more complete version.
