### ISSUE TITLE
How to get handKeyPoints and faceKeyPoints with Python API

### ISSUE THREAD

**Issue by taku-mania** [CMU-Perceptual-Computing-Lab/openpose#962]
### Issue Summary
I'd like to get bodyKeyPoints, handKeyPoints and FaceKeyPoints from Python using openpose.
I ran the  "examples/tutorial_api_python/1_extract_pose.py". But `openpose.forward()` returns only bodyKeypoints.
How can I get handKeyPoints and faceKeyPoints?

### Type of Issue
- Help wanted
- Question

### Your System Configuration
**OpenPose version**: 
1.4.0

**General configuration**:
    - **Installation mode**: CMake
    - **Operating system**: Ubuntu 16.04.5 LTS
    - **Release or Debug mode**?: release
    - Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Non-default settings**:
    - **3-D Reconstruction module added**?: no
    - Any other custom CMake configuration with respect to the default version?: BUILD_PYTHON flag is turned on

**3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version**: cmake version 3.5.1
    - **OpenCV version**: pre-compiled 2.4.9

**GPU mode** issue:
    - **CUDA version**: 8.0.61
    - **cuDNN version**: 5.1.10
    - **GPU model**: TITAN X (Pascal)

**Python** API:
    - **Python version**: 2.7.12
    - **Numpy version**: 1.15.1

**Comment by wakingking77** [comment]
hello! Did you solved it? I have the same problem..

**Comment by gineshidalgo99** [comment]
Check the latest section periodically, we will release a full Python API in 1-2 months (that extend all C++ functionality)

**Comment by taku-mania** [comment]
I solved it with reference to #866. 
I'm looking forward to full API.
thanks.

**Comment by wakingking77** [comment]
> I solved it with reference to #866.
> I'm looking forward to full API.
> thanks.

thank you very much!!

**Comment by wakingking77** [comment]
> Check the latest features section of the README periodically, we will release a full Python API in 1-2 months (that extend all C++ functionality)

I'm looking forward to your official version,too! Thank you for your hard work　very much!
