### ISSUE TITLE
poseTriangulation.cpp 3D reconstruction Calculation error

### ISSUE THREAD

**Issue by gurbela** [CMU-Perceptual-Computing-Lab/openpose#963]
in poseTriangulation.cpp  Line: 394 
// Do 3D reconstruction
``` std::vector<cv::Point3f> xyzPoints(xyPoints.size());
     for (auto i = 0u; i < xyPoints.size(); i++)
       {
         cv::Mat reconstructedPoint;
         reprojectionErrors[i] = triangulateWithOptimization(reconstructedPoint,
                                                 cameraMatricesPerPoint[i],
                                                 xyPoints[i],
                                                 reprojectionMaxAcceptable);
           // log(reprojectionErrors[i]);                
         xyzPoints[i] = cv::Point3d{
                            reconstructedPoint.at<double>(0),
                            reconstructedPoint.at<double>(1),
                            reconstructedPoint.at<double>(2)};
        }
      
       const auto reprojectionErrorTotal = std::accumulate(reprojectionErrors.begin(), reprojectionErrors.end(), 0.0) / xyPoints.size();
```
**reprojectionErrors[i]**  value is  **-nan(ind)**
**triangulateWithOptimization** function Can not calculation.

function **calcReprojectionError()** return wrong information.
 specifically:  `cv::Mat imageX = cameraMatrices[i] * reconstructedPoint;`
where  
```
cameraMatrices[i] = [3922.916318988908, 0, 628.1608746198333, 0;
 0, 2737.275176579742, 515.0350370360935, 0;
 0, 0, 1, 0];
 reconstructedPoint = [0;  0;  0;  1];
```
Accordingly: 
`imageX = [0; 0; 0];` 
and when it will be executed
`imageX /= imageX.at<double>(2,0);`
**imageX** Makes the wrong value
`imageX = [-nan(ind); -nan(ind); -nan(ind)]`

Then the calculation ends by mistake, How to fix this? Or what might be the reason?
Please help me.

**Comment by gineshidalgo99** [comment]
This is 99.99% of the cases due to wrong or poor calibration. Repeat the calibration making sure the reprojection error is about 0.1 pixels.
