### ISSUE TITLE
VS2015+openpose-master→LINK : fatal error LNK1561: Entry points must be defined

### ISSUE THREAD

**Issue by rookieopenpose** [CMU-Perceptual-Computing-Lab/openpose#964]
Hello，@gineshidalgo99 
Im a rookie from China，it seems a dump question，cuz nobody answer me in the study group，I dont know how to fix it.
Can you help me?

Operations performed (if any)
when I build the “OpenPoseDemo” programme

OpenPose output (if any)
1>  All 10112 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1> The code generation is complete
1>  OpenPose.vcxproj -> D:\openpose-master\windows\x64\Release\OpenPose.dll
1>  OpenPose.vcxproj -> D:\openpose-master\windows\x64\Release\OpenPose.pdb (Full PDB)
2>------ All rebuilds have been started: project: OpenPoseDemo, configuration: Release x64 ------
**2>  openpose.cpp
2>LINK : fatal error LNK1561: Entry points must be defined**
========== All regenerated: 1 successful, 1 failed, 0 skipped ==========

Type of issue

LINK : fatal error LNK1561: Entry points must be defined

Your system configuration
openpose version：openpose-master
Operating system : Windows10 64bit
CUDA version (cat /usr/local/cuda/version.txt in most cases): cuda_8.0.61_win10
cuDNN version: cudnn-8.0-windows10-x64-v5.1
GPU model (nvidia-smi):NVS 300 and GTX1080 (different PC, same error)

This is the main function：
int main(int argc, char *argv[])
 {     
  google::InitGoogleLogging("openPoseDemo");   
  gflags::ParseCommandLineFlags(&argc, &argv, true);      
  return openPoseDemo();
  }

Have a nice day！：）

**Comment by rookieopenpose** [comment]
@gineshidalgo99
Hi there，I change the version from openpose-master to **openpose 1.0.0**,it running sucessfully.
thanks to your team share this gorgeous project with us！！！
Have a nice day！

**Comment by gineshidalgo99** [comment]
Thanks for the feedback
