### ISSUE TITLE
Logic of displaying pose results between pose detection and tracking

### ISSUE THREAD

**Issue by yw155** [CMU-Perceptual-Computing-Lab/openpose#965]
Hi @gineshidalgo99, I would like to ask a question that what is the logic of displaying the results between pose detection and tracking. If both results of detection and tracking are available, how to determine the final pose result? Thanks in advance.

**Comment by gineshidalgo99** [comment]
We do some average between both, depending on how close they are. We will release an improved version for multi-people in 1-2 months, check the latest features section to know when it's out. Thanks
