### ISSUE TITLE
For a clean install of Ubuntu 16.04, doc/installation.md is missing several prerequisites

### ISSUE THREAD

**Issue by ylevental** [CMU-Perceptual-Computing-Lab/openpose#966]
Instructions should be given on how to clone the caffe repo into the 3rdparty directory.

```
cd 3rdparty
git clone https://github.com/CMU-Perceptual-Computing-Lab/caffe.git
```
Now, run cmake to Configure and Generate.

Other dependencies missing from the installation document:

```
sudo apt-get install libhdf5-dev
sudo apt-get install libgoogle-glog-dev
sudo apt-get install libprotobuf-dev
sudo apt-get install protobuf-compiler
sudo apt-get install libboost-all-dev
```

**Comment by gineshidalgo99** [comment]
Thanks, but it's already there.

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md --> Step 6
