### ISSUE TITLE
Is Jetson TX2 installation possible without flashing it with Jetpack

### ISSUE THREAD

**Issue by aashishsoni05** [CMU-Perceptual-Computing-Lab/openpose#968]
Hello,
I am having just one machine (Which is Jetson TX2) and as per installation instructions, it is mentioned that I am supposed to flash my Jetson with JetPack. Unfortunately, Jetson cannot flash itself. is there any workaround possible here?

**Comment by waseemkhan1989** [comment]
Hi,
you need a host machine(PC/Laptop) with ubuntu 16.04 installed. You need to install Jetpack3.1 on your host  machine and need a micro usb cable for the flashing purpose from your host machine to Jetson board. All softwares would be installed by Jetpack itself. Please google it, you will find many forums and articles.

**Comment by aashishsoni05** [comment]
Hi, I managed to install Jetpack 3.3 on the Jetson TX2. the "install_caffe_and_openpose_JetsonTX2_JetPack3.1.sh" script is showing an error that software has not been installed properly. 
Also, jetpack 3.3 has installed Cuda 9.0, how can I fix this issue further?

**Comment by gineshidalgo99** [comment]
A push for JetPack 3.3 has been added 5min ago, you might try the updated install instructions.
