### ISSUE TITLE
jetson tx2 script - Makefile.example missed

### ISSUE THREAD

**Issue by AndreV84** [CMU-Perceptual-Computing-Lab/openpose#969]
The script fails finding not the file Makefile.example in ubuntu folder.

**Comment by AndreV84** [comment]
`cp ubuntu/Makefile.example Makefile`

**Comment by AndreV84** [comment]
found the file in depreciated ubuntu folder, thx

**Comment by celbertin** [comment]
@AndreV84 Could you give more details on your workaround? I'm having the exact same problem. I followed the instructions from the [Jetson install guide](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2_jetpack3.3.md), and I have a fresh install of JetPack 3.3 with everything compiled and installed.

**Comment by gineshidalgo99** [comment]
@celbertin can you show your error? Because the latest commits should have fixed the above issue.

**Comment by celbertin** [comment]
What I've done:
In a clean install of Jetpack 3.3 with everything installed and compiled

git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
cd openpose
./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh

After compiling caffe successfully, I get the following error:

> 
> ------------------------- Caffe Compiled -------------------------
> 
> ------------------------- Caffe Installed -------------------------
> 
> [sudo] password for nvidia: 
> ------------------------- Installing OpenPose -------------------------
> NOTE: This script assumes that just flashed JetPack 3.1 : Ubuntu 16, CUDA 8, cuDNN 6 and OpenCV are already installed on your machine. Otherwise, it might fail.
> ------------------------- Checking Ubuntu Version -------------------------
> ------------------------- Ubuntu Version Checked -------------------------
> 
> ------------------------- Compiling OpenPose -------------------------
> cp: cannot stat 'scripts/ubuntu/Makefile.example_openpose': No such file or directory
> make: *** No rule to make target 'all'.  Stop.
> 
> ------------------------- -------------------------
> Errors detected. Exiting script. The software might have not been successfully installed.
> ------------------------- -------------------------
> 
> ------------------------- -------------------------
> Errors detected. Exiting script. The software might have not been successfully installed.
> ------------------------- -------------------------
>

Even though I used the script for JetPack 3.3, this part mentions Jetpack 3.1, but when compiling coffe mentions JetPack 3.3.

**Comment by gineshidalgo99** [comment]
@celbertin 
Thanks for the feed-back. Forget that it mentions 3.1, that's just a typo in the output message, but internally it is only using commands for JetPack 3.3.

To fix the error (I do not have 1 of those boards so please help me debug it), could you modify the script:
./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh

Then Remove line 45, the one that says: `../..`.

Then run the file again as you did:
```
cd openpose
bash ./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh
```

Let me know if this works so I can fix it :)

Thanks!

**Comment by AndreV84** [comment]
Hi   @celbertin ,
When I first encountered the issue , I did look through the github repo and found missed file at ubuntu_depreciated folder and manually supplied it to the required folder.
What you need is to have the file 'Makefile.config' that is pressumed to be created from 'Makefile.config.Ubuntu16_cuda9_JetsonTX2_openpose ' and a file 'Makefile' that is created from 'Makefile.example_openpose'. Once yolu got these two files in place you can forget amout the script and execute the make sequence and other commands in a manual way.

**Comment by celbertin** [comment]
@gineshidalgo99 the line `../..` appears in file `./scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh` , not in `./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh` (line 45 is empty there) so I made the change in the first file and ran the file as I did earler:
```
cd openpose
bash ./scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh
```
Now the error looks like this:

```
------------------------- Caffe Compiled -------------------------

------------------------- Caffe Installed -------------------------

[sudo] password for nvidia: 
------------------------- Installing OpenPose -------------------------
NOTE: This script assumes that just flashed JetPack 3.1 : Ubuntu 16, CUDA 8, cuDNN 6 and OpenCV are already installed on your machine. Otherwise, it might fail.
------------------------- Checking Ubuntu Version -------------------------
------------------------- Ubuntu Version Checked -------------------------

------------------------- Compiling OpenPose -------------------------
cp: cannot stat 'scripts/ubuntu/Makefile.example_openpose': No such file or directory
cp: cannot stat 'scripts/ubuntu/Makefile.config.Ubuntu16_cuda9_JetsonTX2_openpose': No such file or directory

make: *** No rule to make target 'all'.  Stop.

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------
```

@AndreV84 I see what you did there, I'll give it a try .

**Comment by gineshidalgo99** [comment]
Thanks for the feed-back. After a deeper inspection of the script, I realized of a couple more bugs. Please, download the latest OpenPose version and try again, I did several fixes to that file. Let me know whether it works or the new error. Thanks!

**Comment by celbertin** [comment]
@gineshidalgo99 I tried the latest version, error is now the following:

```
------------------------- Caffe Compiled -------------------------

------------------------- Caffe Installed -------------------------

[sudo] password for nvidia:
------------------------- Installing OpenPose -------------------------
NOTE: This script assumes that just flashed JetPack 3.3 : Ubuntu 16, CUDA 9, cuDNN 7 and OpenCV are already installed on your machine. Otherwise, it might fail.
------------------------- Checking Ubuntu Version -------------------------
------------------------- Ubuntu Version Checked -------------------------

------------------------- Compiling OpenPose -------------------------
cp: cannot stat 'scripts/ubuntu/Makefile.example_openpose': No such file or directory
cp: cannot stat 'scripts/ubuntu/Makefile.config.Ubuntu16_cuda9_JetsonTX2_JetPack33': No such file or directory
make: *** No rule to make target 'all'.  Stop.

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

```

**Comment by gineshidalgo99** [comment]
OK. I believe that this final change should work (again thanks for helping me fix it for future people using it!). In scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh, change line 45 from
```
executeShInItsFolder "install_openpose_JetsonTX2_JetPack3.3.sh" "./scripts/ubuntu/" "./"
```

Into
```
executeShInItsFolder "install_openpose_JetsonTX2_JetPack3.3.sh" "./" "./"
```

Please, let me know the result. Thanks!

**Comment by gineshidalgo99** [comment]
OK. I believe that this final change should work (again thanks for helping me fix it for future people using it!). In scripts/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.3.sh, change line 45 from
```
executeShInItsFolder "install_openpose_JetsonTX2_JetPack3.3.sh" "./scripts/ubuntu/" "./"
Into
```
executeShInItsFolder "./scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh" "./" "./"
```
Please, let me know the result. Thanks!

**Comment by celbertin** [comment]
@gineshidalgo99 I tried this change, still get an error :(

```
------------------------- Caffe Compiled -------------------------
 
------------------------- Caffe Installed -------------------------
 
[sudo] password for nvidia:
------------------------- Installing OpenPose -------------------------
NOTE: This script assumes that just flashed JetPack 3.3 : Ubuntu 16, CUDA 9, cuDNN 7 and OpenCV are already installed on your machine. Otherwise, it might fail.
------------------------- Checking Ubuntu Version -------------------------
------------------------- Ubuntu Version Checked -------------------------
 
------------------------- Compiling OpenPose -------------------------
cp: cannot stat 'scripts/ubuntu/Makefile.example_openpose': No such file or directory
make: *** No rule to make target 'all'.  Stop.
 
------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------
 
------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------
```

[Here's the entire output](https://pastebin.com/mthNeSkU) in case it helps.

**Comment by gineshidalgo99** [comment]
OK, could you type a `ls` right before the `executeShInItsFolder` line (45) and show me the output. In addition, please, do the same and add another `ls` in the first line of `./scripts/ubuntu/install_openpose_JetsonTX2_JetPack3.3.sh`. Please, let me know those outputs, thanks!

**Comment by celbertin** [comment]
Both `ls` give the same output:
`3rdparty cmake CMakeLists.txt doc examples include LICENCE Makefile.config models python README.md scripts src`

I'm thinking the problem is that the file `scripts/ubuntu/Makefile.example_openpose` isn't there. I notice that the pull request for JetPack 3.3 mentions deleting `Makefile.example_openpose` but in the repo for [the fix](https://github.com/goldenpartner/openpose_jetpack3.3_patch) the file is there.

**Comment by gineshidalgo99** [comment]
OK, then a 2nd and hopefully last change, could you edit in line 38 of install_openpose_jet[...]:
```
cp scripts/ubuntu/Makefile.example_openpose Makefile
```
by:
```
cp scripts/ubuntu/Makefile.example Makefile
```
Thanks!

**Comment by gineshidalgo99** [comment]
I will push all the changes in the next commit so it should work automatically for any new user. Thanks again for your help!

**Comment by AndreV84** [comment]
FYI: I also managed to build openpose at jetson xavier and tf-openpose as well, using the default, non scripted method and installed caffe & opencv4.0[pre-release]

**Comment by AndreV84** [comment]
@gineshidalgo99 : Could you extend how to use the standalone hand detector please?
reference : https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/standalone_face_or_hand_keypoint_detector.md#custom-standalone-hand-keypoint-detector
