### ISSUE TITLE
Stability issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by eitanrich** [CMU-Perceptual-Computing-Lab/openpose#97]
### Issue summary
Occasional segmentation fault when running openpose.bin demo - about every other time.
When it works, all functionality seem to work well and processing continues till the end of the video.
When it crashes - it happens immediately when the demo starts (nothing else is shown).

### Executed command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi -num_gpu 1

### OpenPose output (if any)
Segmentation fault (core dumped)

### Type of issue
- Execution error
- Help wanted

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu):  Ubuntu 16.04.2 LTS
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0.61
**cuDNN version**: 6.0.21
**GPU model** (`nvidia-smi`):
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
|  0%   45C    P8     9W / 200W |     72MiB /  8110MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |
|  0%   45C    P8     9W / 200W |      1MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1282    G   /usr/lib/xorg/Xorg                              70MiB |
+-----------------------------------------------------------------------------+

**Caffe version**: Default from OpenPose.
**OpenCV version**: 3.2.0
Compiler (`gcc --version` on Ubuntu): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by gineshidalgo99** [comment]
I'd guess OpenCV might be the issue.

Could you try OpenCV 3.1 or 2.4.X?

**Comment by eitanrich** [comment]
Re-installing on a different machine with a similar setup solved the stability issues (still with OpenCV 3.2.0).
Not sure what went wrong the first time...
Thanks,
Eitan

**Comment by gineshidalgo99** [comment]
Thank you for the feed-back, maybe the version you downloaded had a bug we might have fixed later. No idea. Glad it is working now.

Best
