### ISSUE TITLE
Which method used for the 'hand pose' model?  

### ISSUE THREAD

**Issue by timctho** [CMU-Perceptual-Computing-Lab/openpose#98]
### Issue summary
I know the hand pose model will be released soon.
But I've collected my own data and want to train the model now.

Could you please refer which paper or method (CPM?) should I use to train the model?
The hand training data is monocular or stereo camera images?
And did you find something else that need to be noticed between training human pose and hands?
(like the setting to gaussian variance of ground truth joint heat maps)

These will be very helpful for my researches. Thanks for the reply.

 - Question

**Comment by gineshidalgo99** [comment]
All the information can be found in the hands paper specified in the README:
Hand Keypoint Detection in Single Images using Multiview Bootstrapping
