### ISSUE TITLE
identifier "nullptr" is undefined

### ISSUE THREAD

**Issue by kedama05** [CMU-Perceptual-Computing-Lab/openpose#981]
When I try OpenPose Building,  I have an error message: ** identifier "nullptr" is undefined**.

make -l `nproc`

_[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_deconv_layer.cu.o
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stddef.h(432): error: identifier "nullptr" is undefined
..._

Please tell me how to solve this problem.

Ubuntu / 14.04
Cuda / 8.0
cudnn / 5.1

**Comment by gineshidalgo99** [comment]
This error is not coming from OpenPose, but rather Ubuntu C++ libraries. Try updating Ubuntu:
```
sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove
```
