### ISSUE TITLE
How to enable the 3D reconstruction from the calibrated stereo video or images sources

### ISSUE THREAD

**Issue by asjmasjm** [CMU-Perceptual-Computing-Lab/openpose#984]
With the pre-calibrated stereo cameras .xml files and corresponding videos captured by these cameras, is there any flag command for the openpose.bin to support 3d reconstruction from video source other than the flir-camera? I tried adding the --3d options but the openpose.bin seemed not to be able to find either the video sources or the .xml files.

**Comment by asjmasjm** [comment]
I have tried to set --3d_views 2 to enable the render window but how to set the video path with more than one videos should be input

**Comment by djns99** [comment]
As mentioned https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/3d_reconstruction_module.md#expected-visual-results you need to write your own extension to 7_synchronous_custom_input example. In your case the class would need to read from the image/video sources. You would also need to set the cameraIntrinsics/cameraExtrinsics fields of the datum using your .xml files. (the CameraParameterReader class might help here). The discussion on #906 may also help if you have any issues implementing your class.

**Comment by asjmasjm** [comment]
I finally extracted the codes and realized it in my own frame. Thanks for your reply anyway.

**Comment by yirenpingsheng** [comment]
@asjmasjm Sorry to bother you. Could you please tell me how to achieve the 3D Reconstruction with saved RGB videos? Actually, I have 3 three RGB videos coming from different angles. But I cannot find the command to process those videos.

**Comment by UchihaIzumi** [comment]
@asjmasjm @yirenpingsheng I happen to have the same question, is there a command to use video coming from three cameras for three-dimensional reconstruction?

**Comment by yirenpingsheng** [comment]
@UchihaIzumi I cannot find the command to process saved videos coming from three cameras. They only provide the instruction for image streaming from cameras connected to the machine[https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/3d_reconstruction_module.md].  I think we should modify some cpp files to process saved videos coming from three cameras. But I am not familiar to C++. It's a very difficult work for me.

**Comment by Siba-07** [comment]
@yirenpingsheng @Medjed46 @asjmasjm  Could you all find a way to use synchronized recorded videos, for 3d reconstruction?
