### ISSUE TITLE
The speed I download the model through the getModels.bat is very very slow. How I can speed it up?

### ISSUE THREAD

**Issue by ericsqxd** [CMU-Perceptual-Computing-Lab/openpose#985]
I just want to try the window demo, but when I download the models through the getModels.bat, the speed is very slow? How I can speed it up? Or is there any other way to download it?such as google drive.

**Comment by lianuo** [comment]
I have some problem

**Comment by lianuo** [comment]
you can download the files from your own browser , the uRL is  in the makelist.txt

**Comment by gineshidalgo99** [comment]
And it's also in doc/installation.md
