### ISSUE TITLE
I have also this problem." I don't find *.bin files under /examples/openpose folder.

### ISSUE THREAD

**Issue by Ayehsu** [CMU-Perceptual-Computing-Lab/openpose#987]
I have also this problem." I don't find *.bin files under /examples/openpose folder.
I found only CMakeFiles folder."

Thanks.
Please if anyone has solutions or advices.

_Originally posted by @Ayehsu in https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/479#issuecomment-449687570_

**Comment by andrewjong** [comment]
did you find it? I'm having this issue too.

**Comment by mvmnt** [comment]
My assumption is that you need to run ccmake in the openpose root directory to get the build folder. I've had this problem as well, and I'm currently trying to run ccmake.

If you usee a mac, use homebrew to install cmake (brew install cmake) 
then run "ccmake your/openpose/directory/path"

unsure about windows systems, but I do hope this helps you somewhat.

**Comment by ihewro** [comment]
in cmake app, you should Check the "BUILD_EXAMPLE" in center pane then press generate button

at last, to process cmake
