### ISSUE TITLE
Compilation Error - Windows 10

### ISSUE THREAD

**Issue by totovr** [CMU-Perceptual-Computing-Lab/openpose#99]
Im trying to generate the OpenPose example but appears the next error

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'caffe/export.hpp': No such file or directory	OpenPose	C:\openpose\3rdparty\caffe\caffe-windows\include\caffe\common.hpp	20	

- Compilation/installation error
- Execution error
- Help wanted

### Your system configuration
**Operating system** (W10):
**CUDA version** (8.0.61):
**cuDNN version*5.1*:
**GPU model** (`750M`):
**Caffe version**: Default from OpenPose.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X.

**Comment by gineshidalgo99** [comment]
Hi, after all the new changes we applied to the Windows version, could you try the latest version and let us know if this problem still appears? Thanks

**Comment by totovr** [comment]
Hello! I try to do it again but I received many errors, I will try to do it one again
![errors](https://user-images.githubusercontent.com/15333235/27780564-a14eea46-6004-11e7-88be-862778467ef5.PNG)

**Comment by gineshidalgo99** [comment]
In your screenshot I only see lots of warnings but 0 errors. The warnings mainly come from the 3rdparty libraries, so unfortunately we cannot remove them.
But it should work given your screenshot, let me know if there is any other error printed out somewhere else.

**Comment by totovr** [comment]
Hello I am continue trying to install it, one point that you miss in the manual of Windows is that you should open one new project of visual studio of C ++ in order to install some libraries that Visual Studio need

**Comment by gineshidalgo99** [comment]
Hi, I did not need to do that in the 3 devices I tried on. Could you specify what libs was VS asking for? Thanks!

**Comment by totovr** [comment]
Sorry maybe it was becuase I didnt have the C++ usual libraries installed (I used the default settings of visual 2015), I tryed again from 0 and now it showed me this errors.

Thanks for your time
![errors](https://user-images.githubusercontent.com/15333235/27939877-7d9ce502-6302-11e7-85a8-8a475a00936c.PNG)
![errors2](https://user-images.githubusercontent.com/15333235/27939881-840bd3b2-6302-11e7-85e6-b18bad631413.PNG)

**Comment by totovr** [comment]
I change the version of Cmake for the newest one and also I follow this steps:

https://stackoverflow.com/questions/31619296/cmake-does-not-find-visual-c-compiler
https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe/18565268

**Comment by totovr** [comment]
where should I install Install all the demo pre-requisites.?

**Comment by gineshidalgo99** [comment]
I've just added a commit that merges Ubuntu and Windows versions. In addition, the Windows version should be easier to install (no need to install Caffe). Could you try it and see if the new one works for you?
