### ISSUE TITLE
Problems when installing openpose in Windows10

### ISSUE THREAD

**Issue by wardenjohn** [CMU-Perceptual-Computing-Lab/openpose#994]
System Config:
GPU : Nvidia GTX 1060 3GB
CPU : Intel i7
RAM: 8 GB

### Issue Summary
When compiling this project in Visual Studio 2017 . Before I run this project ,I had already use CMake and generate it , which created a OpenPose.sln doc.
After that ,I open this doc with VS 2017 ,when I was compiling it,it gave me some error as follows:
unable to open file "..\..\src\openpose\Release\openpose.lib"

### Errors (if any)
LNK118 unable open file "..\..\src\openpose\Release\openpose.lib"

### Type of Issue
- Compilation/installation error

### Your System Configuration
1. **Whole console output** 
https://pastebin.com/y9EJnSX7

2. **OpenPose version**: 
Latest GitHub code

3. **General configuration**:
    - **Installation mode**: CMake，compile with VS 2017
    - **Operating system**Windows
    - **Release or Debug mode**? Release
    - Compiler  : VS 2017

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):NO
    - Any other custom CMake configuration with respect to the default version? (by default: no):NO

5. **3rd-party software**:
    - **Caffe version**:?
    - **CMake version** :3.13.2
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

       !!!!!!!All the 3rdparty was downloaded from the .bat file in the Github project

6. If **GPU mode** issue:
    - **CUDA version** CUDA 8
    - **cuDNN version**:cuDNN 5.1
    - **GPU model**  NVIDIA GTX 1060 3GB

**Comment by EnricoBeltramo** [comment]
I had similar issue and fixed building for visual studio 2015 win64 and CUDA 9.0

**Comment by wardenjohn** [comment]
> 
> 
> I had similar issue and fixed building for visual studio 2015 win64 and CUDA 9.0

My environment is Visual Studio 2017 and CUDA8,I am confused by this building problem...

**Comment by takuya-takeuchi** [comment]
I have no issues on Visual Studio 2015 and 2017 on CUDA 9.2.
I guess CUDA 8.0 does not support VS 2017.

You must check minor version of VS 2017 and install proper CUDA version.
At least, latest CUDA 9 version could not occur any issues about VS version trouble.

**Comment by wardenjohn** [comment]
> 
> 
> I have no issues on Visual Studio 2015 and 2017 on CUDA 9.2.
> I guess CUDA 8.0 does not support VS 2017.
> 
> You must check minor version of VS 2017 and install proper CUDA version.
> At least, latest CUDA 9 version could not occur any issues about VS version trouble.

Thanks !!!!!!!  I reinstalled CUDA 9 version and this problem was sloved!

**Comment by wardenjohn** [comment]
I searched on the Internet , some people said CUDA 8 does not support VS 2017 , and now I think it is a fact....
